using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

namespace Lean
{
	[ExecuteInEditMode]
	public class LeanTouch : MonoBehaviour
	{
		private sealed class JIIIIJIIJIJJJIJIJJJJIJIJIJIIIJJIJJIJIIJIJIIIIIJ
		{
			public int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ;

			internal bool JIIJJIIJJIIJIIIIJIJJJIJJIIJJIJJIIIIIIJIIJJIIJII(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool JJJIJJIIJJJIJJJJIJIJIIJJIJIIIIIIIIJIJJIIIJJJIJI(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool JJJIIJJIJJJIJJJJIIJJJJIIIJIJJIIJIIJJIJIIJIJJIII(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool JIJJJIJJIIIJIIIJIJIJIIJIIIJJIIIJJJJJIJIIJIJJJJI(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool JIIIJJIJIIJJIIJIJIIIIIJIJJJJJJIIIIIIJJIJJJJIIII(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool JIIIIIJJJJIIIIIIJJIIIIIJIJIIIIJIJJJJIJIJIJIJJJJ(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool IJJIIIIJJJIIIIJJJJIIJJIJIJIIIJIIJJIIIIIJIIIJJIJ(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool JIIJIJIJIIJIIIJIIJJIIJJJJIJJJJIJIJJIJIIIJIJIJJJ(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool IJJJIIJIIJIJJJIJJJIIJJIJIJIJJIJJIIIIIJIJIIIJJIJ(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool JJJJJJJIIIJIJJIJJJIJIIJJIIJIJJIJIIJIJJIIJIJJIII(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool IJJJIIJJIJJJIJIJIIIJIJJIIJIIIJJJIJIIIJIJIIJJJJI(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool IIJIJJJJIJIIIJIJJJIJJIJJIIIIJJIIIJJJJIIIIJIIJII(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool JIIIJIIJJJIJIIIIIIIIJJJIIJIIIJIIIIIIJJJIJJIJIJI(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool IIJIJIIIIJIIJJIIIIIJIJIJIIIIJIJJJIJJJJJIJIIJIIJ(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool IIIIIIJIJIIIJJIIIJJJJIIJIIJJJIIIJJJIJJIIJJJIJJJ(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool JIJIIIJJIIJJIJIIIJJJIJJJIJIIIJJJIIJIIIIIJJIIIJI(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}

			internal bool IIJIIJJJJJJJIJIJJJJIJIJJJIJIJJJIIIJIJIJIJIJJIJJ(JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
			{
				return false;
			}
		}

		public static LeanTouch JIJJIJJJJIIJIIJJJJJJJJIJJJJJJIJJIJIIIIJIJJIJJJJ;

		public static List<JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI> JJJIIJIJIIIJIIJJIIJJJJIIIIJJJJIIIJIJIJJIIIIIIII;

		public static List<JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI> JJIJJIIJJIIIJJJJJJIIIIJIIJJJIJJJIIJIIJIIJJIJIJJ;

		public static Vector2 IIJJIIIIJJJIJJIJIJJJIJIIIJIJJJIIIJJIJIJJJJIIJII;

		public static Vector2 JJJIIIJJJJJJJJIIJJJJIJJJIJJIIIJIIIIJJIIIJIIJJII;

		public static Vector2 JJIIIIIJIIIIJIJJIIIIIJIJJIIIJIIIJIIIIJJIIIJJIJI;

		public static float JIJJIJIIIJIIIJJJIIIJIIJJJIIJJJJJIIIJJIJJJJIJJII;

		public static float JJJIJIIJJIIIJJIJIJJIIJIIJJIJJJIIIIIJIJIJIJJJIJI;

		public static float JIIJIIIJIIJIJJIJIJJJIIJJIIIIJJIIJIIJJIJJJJJJJJJ;

		public static Action<JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI> IIIJIJIJJIIJIJJJIIIIIIJIJJIIIJIJIIIJJJIJJJIJJJJ;

		public static Action<JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI> JIJIJIIIIJJIJIJIIJJJIJJIIIIIIIJJIIJJIJIJIIJJJJJ;

		public static Action<JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI> IIIIJJJJIJJJJIIJJIIIJIJJIIJJIIJJIIIJJIJJIIJIIJI;

		public static Action<JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI> IIIIIJIJIIJJJJIJIJIIIIJIIIJJIIJJIIJJJJJJIIIJIIJ;

		public static Action<JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI> JIJJIJJJIJJIIIIIJJIJIIIIIJIJJJJIJIJIJJJJIJJJIJI;

		public static Action<JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI> JJIIJIJIIIJIJJIJIIIJJIJJJIIJJJIIIJIJIIIJIIJIIJJ;

		public static Action<JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI> IJIIJIJJJJJJJJIJIJIIJJIIIIIJIJIIIJJIIJJIIJIIJIJ;

		public static Action<JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI> IJJIJIIJJIJJJJJIJIJJJJIJJJJIIIJJIIJIIJJJIIJIJJJ;

		public static Action<JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI> JIIIJJIJIJIIIJIJJJJIJIJJJJIJJIIIIIIJIIIIJIIIIII;

		public static Action<int> JJIIIIIJIJJIIJIJJJJJIJIIIJJJIJJIIJJJIJJIJIIIIII;

		public static Action<Vector2> JJIJJJIJJIJIJIIJJIJIIIIJJJJIIIJJJIJJJJIJJJJIJIJ;

		public static Action<Vector2> JIJIJJIJIIJIIIIIIJJIJJJJJIJJJIIJIJJJIJIJJIIJJJI;

		public static Action<Vector2> IIJJJIJIJIJIIJIIJJIIJIIJIJJIIIIIJJJIIJIJJJJIJII;

		public static Action<float> IIJJJJIJIJJJIIJJIIJIJIJIIJJJJIJJJJIJIIIIIIIJJII;

		public static Action<float> IIJJJIJIIIJIIIJJJIJIIIIIIJJIJIIJIIIJIJIIJJJIIJJ;

		public static Action<float> IIJIJJJIIIIIIJIJJIIIIIJIJJIIIJIJJIIJJIIIIJJIIIJ;

		public float JIJJJIJJJIJIIJIJIIJIJIJIJJIJIIIJJIJIJIIIJJIJIII;

		public float JJIIIIIJJJJIIJJIIIJIIJJJJJJJJJJIIIIIIIJJJJJIJII;

		public float IIJJIJJJIJJJIIIIJJIIJIJIIJIJJJJJJIJJJIJIIJJJJJI;

		public int IJJJIIIIJIJJIJJJJJIJJIJJJJIJJIIIJIIJJJJIIIIJJII;

		public bool IJJIIJIJIJIIJJIJIJIIIJIJJJIIIIIJJIJIIJIIJJIIIII;

		public float IIIJIJJJIIIIJIJJIJJIIIIIJIIJIJIIIIJIIIIIJJIIIII;

		public float IIJJJIIJIIIIIJJJIIJIJIIIJIIIIIIJIIJIIJJIIJIIIJJ;

		public bool IJJIJJJJIJJJJJJJIJJIIIIJIJIJJIJIJIJJIIIJIIIJIII;

		public KeyCode IIJIJIJJJIJIIIIIJIIJIJJJIJIIIJIIIIJJJJJIJJJIJJI;

		public KeyCode JIIJIJIIJJIIJJJIIJIJIJJJIJIIJJJIIJJIIJIIJIIJIIJ;

		public Texture2D JJIJJJJIJIJJJIIIJJIIJIIJJJIJJIIJJIIIJJIJJIIIJIJ;

		private static int IJIIJIJIJJIJJJIJIIJJIJIJJIJIJIIJIIIJJJIJJJIJJII;

		private int JJIJIIJJIJIJJJIJJIIJIJIIJJIIJJIJIJJJJIJIJJJIJII;

		private float JJIIJIJJJJJJJJIIIIJJJJIJIIJIJJJIJIJIJIIIJJIJJJI;

		private int JJJJIIJJIIIJJIIIJIIIIIJJJIIJIIJIJJIJJIIIJJIJIJI;

		public static float IIJIJIJJJIJIIIJJJJIIJJIIIIIIIJJIJJIIIJIIIIJIIJJ => IJIJJJIIIJJIIJJJIIIJJIJJJIJJIJIIIJJIIIJJJJJIJII();

		public static Vector2 IIJJJIIIJIJJIIJJJIIIIIIJIJJIJIIJJJIJJIIIIIJIJIJ => IIJJIJJIJJIIIJIJJJIIJJIJJJIIJIJJJIIJIJIJIIJJIJJ();

		public static Vector2 JJIJIJJIIIJJJJIJJJIIJJIJIIIJIIIIJJIIJIIJJIIJIJI => JIIIJJJJJIJJJJIIIJJIIIIJIJJIIJJJJJJIIIJJJJJJIIJ();

		public static Vector2 JJIIJJJIJIIJJIIJIJIIIIIJIJJJIJJJIJIJIJJJIIIJIJJ => JJIJJIIJJIJIJJJIIJIJJIIIJIJIJIJJJJJJIJIIIIIIIJI();

		public static bool JIJJIJIIIIJJJJIIIIIJIJIJIJJIIIIIIIJIIJJIJIIJJII => IIJJJIJIIJIIIIJIJIJIIIJJIIJJIIIIIIJJJJJIIJJIIIJ();

		public static bool JIIJIIIIJJJIJJJIIJJIJJIIJJIJIJJJJIJIJJIJIIIIIJJ => IIIIIIIIIJIJJIJIJJIJIJJJIJIIJIIIIJIIJIJIIJIJJIJ();

		private void JJJJJIIJJJJJJIIIJJIIIIIIJIIJIIIIIIJJIJIIJJIIJJI(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, Vector2 IJJIJIJJIIJIIJJJIJIJIJIJIJIIJIIIIIIIJIIJIJJJIJJ)
		{
		}

		public static Quaternion IJJIJIJIJIJJJJJJIJIIIJIJJIJIJIJIJJIIJIJIJIJJJII(Quaternion JJJIJIIJJJIJIIIIJJIJIJJIIJIIJIIJIJJJIJIIJJIJIJI, float IJIIJIIJIIIJIJIJIIJIIIIJIIIIJJIJIIIIIJJJIJIIJJJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public static float IIIIIJIIJJJIJJJIIJIIJJJJJIIIJJIJIJJJIIIIIIIJJIJ(Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
		{
			return 0f;
		}

		private void JJJJIJIIIIIIJJJJIJIJJJJJIJJIJJJJJJIJIIJJIIIIJJI(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, Vector2 IJJIJIJJIIJIIJJJIJIJIJIJIJIIJIIIIIIIJIIJIJJJIJJ)
		{
		}

		private void JJIIIIJJIJJIIJIIJIJJJIJJIIIJJIIIJJIJIJIIJIJIIIJ()
		{
		}

		private void IIJIJJJIJIJJJIIIIJJIIIJJJIIJJJIJIJJJIIIJIJIJIJI()
		{
		}

		public static void JIJJJIJJIJJIJIJIJJIJJJJIIJJIIIJIIJIIIIJJJJJJIJI(Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI, float IJIJIJIJJJIIJJJJJIJJJJJIJJIIJJJJJJIJIJJJJIJJIJI)
		{
		}

		public static void IJJJJIIJJJIJJIIJJJJJIIIJJJJIIIIIIJIIIIJIIJIJJII(Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI, float IJIIJIIJIIIJIJIJIIJIIIIJIIIIJJIJIIIIIJJJIJIIJJJ, Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
		}

		protected virtual void OnGUI()
		{
		}

		public static bool IIJJJIJIIJIIIIJIJIJIIIJJIIJJIIIIIIJJJJJIIJJIIIJ()
		{
			return false;
		}

		public static void JIJJJIJIIIIJJJJIJIJJJIIIIIIIIIJJJIIIJJJIJIJJIJI(Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI, float IJIJIJIJJJIIJJJJJIJJJJJIJJIIJJJJJJIJIJJJJIJJIJI, Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
		}

		private void IJIJIJJIIIIIIJJIIIIJJIIJJJJJJIIIIJIIIIIIIIJJIJI()
		{
		}

		protected virtual void Update()
		{
		}

		protected virtual void OnEnable()
		{
		}

		public static Vector2 JIIIJJIJJJJIIJJJIIIIIIIIIJJJJJIJJIJIJIIIIJIJIJI()
		{
			return default;
		}

		public static bool IIIIIIIIIJIJJIJIJJIJIJJJIJIIJIIIIJIIJIJIIJIJJIJ()
		{
			return false;
		}
		public static Vector2 IIIIJIIJIJIJIIJJIIIIJIJIIJJJIJJJJJJJJIJJIIIIIIJ()
		{
			return default;
		}

		public static Vector2 JIIIIIIIIJIJJJJJIIIJIIIJIIJJJIIJJIJJJIJJIIIJIJI()
		{
			return default;
		}
		public static Vector2 JJJJJIJIIIIJJIJIIJIJJJJIIIIIJIIIJJIJIIIJIIJIIIJ()
		{
			return default;
		}

		public static Vector2 IIJJIJJIJJIIIJIJJJIIJJIJJJIIJIJJJIIJIJIJIIJJIJJ()
		{
			return default;
		}

		private void IJJJIJJJJJJIIJJJJJIJIIJIJJJJJJJJJIJIIJIJIJIJIJJ()
		{
		}

		protected virtual void IJIJIJIJIJJJIIJJIIIJIJIIJIJJIIJIIJJIJIIIJJIJIJJ()
		{
		}

		public static float IIIIIJIJJJJJIIIIIIIIJJJJIJJIJJJIIIJJJJJJIJIIJIJ(Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
		{
			return 0f;
		}

		private void JIJJJJJIIJJJIIJJJJJJIJIIJIIJJIIIIIIJIIIJJJJJIIJ()
		{
		}

		public static float IJIJJJIIIJJIIJJJIIIJJIJJJIJJIJIIIJJIIIJJJJJIJII()
		{
			return 0f;
		}

		private void IJIJIJIIJIJJJJJIIIJIJIJIIIJIIIIIIJJIIIJIJJIIJII()
		{
		}

		public static void JJJJJIJIIIJJIIIIIJJJIIIJJJJJJIJJIJJJJIIIIIIIJII(Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI, Vector2 JJIIIIIJJIIIJJIJIIIIJIJJJJJIIJIJJIJIJJIIJJIJJJJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
		}

		public static void IJJIJIJIJIJJJJJJIJIIIJIJJIJIJIJIJJIIJIJIJIJJJII(Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI, float IJIIJIIJIIIJIJIJIIJIIIIJIIIIJJIJIIIIIJJJIJIIJJJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
		}

		public static void IJJIJIJIJJIJIJIJJJJIJIIIJJJIIJJJJIJJIIJIJIIIJII(Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI, float IJIIJIIJIIIJIJIJIIJIIIIJIIIIJJIJIIIIIJJJIJIIJJJ, Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
		}

		private void IJIJIIJIJIJJIIJJIIJIJJJJIJJIJIIIIIIJJJIJJJJIIJI()
		{
		}
		public static bool JJJJJIJIIIIJIJIJJIJIIIJIJIIIIIJJIJJIJJIIIJIIIIJ()
		{
			return false;
		}

		public static Vector2 JIIIJJJJJIJJJJIIIJJIIIIJIJJIIJJJJJJIIIJJJJJJIIJ()
		{
			return default;
		}

		public static void IIIJJIIJJJJIIJIIJJJJIIIIIJJIIJJIJJIJIIJIIIIJIJJ(Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI, float IJIIJIIJIIIJIJIJIIJIIIIJIIIIJJIJIIIIIJJJIJIIJJJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
		}

		public static Vector3 JIIIIIJIJIIJJJIIIJIJIJJIJIJJIIIJIIJJIIJIIJJIJJI(Vector3 IIIJJIIIJJIJIJIIIIIJIIJJJJJJJIJIJJJIIIIIIIIJJII, Vector2 JJIIIIIJJIIIJJIJIIIIJIJJJJJIIJIJJIJIJJIIJJIJJJJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public static void JIIIIIJIJIIJJJIIIJIJIJJIJIJJIIIJIIJJIIJIIJJIJJI(Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI, Vector2 JJIIIIIJJIIIJJIJIIIIJIJJJJJIIJIJJIJIJJIIJJIJJJJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
		}

		private void IIIJIJJJJIJIIIJJIJIIIJIIJJJIIIIJJJIIIJIIIIIJJIJ()
		{
		}

		public static void JIJJJIJJIJJIJIJIJJIJJJJIIJJIIIJIIJIIIIJJJJJJIJI(Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI, Vector3 JJJJIJIIJIJJIIJJJIIJIJJIJIIIJJJIJIJIIJJIIJIJIJJ, Vector3 IJIIJJIJIJIJIIJJJIJIIIJIJIIJIJJIIIIJIIIJIIIIIJJ, float IJIJIJIJJJIIJJJJJIJJJJJIJJIIJJJJJJIJIJJJJIJJIJI)
		{
		}

		private static Vector3 IJIIJJJJJIJJIJIIIJJJIJIJJIIJIIIJJJJIJIJJJJJJIII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, Vector3 JJJJIJIIJIJJIIJJJIIJIJJIJIIIJJJIJIJIIJJIIJIJIJJ, Vector3 IJIIJJIJIJIJIIJJJIJIIIJIJIIJIJJIIIIJIIIJIIIIIJJ)
		{
			return default;
		}

		public static float IJJJIIIJJJIIIIIIIJIJJJJIIIIJIJJJJJIIIJJIIJJIIJI(Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
		{
			return 0f;
		}

		public static Quaternion IIIIIJJIJJJIJJJIJJJJIJJJIIIIIIJJIJIJIJJJIJIIIII(Quaternion JJJIJIIJJJIJIIIIJJIJIJJIIJIIJIIJIJJJIJIIJJIJIJI, float IJIIJIIJIIIJIJIJIIJIIIIJIIIIJJIJIIIIIJJJIJIIJJJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public static Vector2 JJIJJIIJJIJIJJJIIJIJJIIIJIJIJIJJJJJJIJIIIIIIIJI()
		{
			return default;
		}

		protected virtual void JJIIJIJIIJJIIJJIIJJJIJJIIJJJJJJJJJJJJIIIIJIIJII()
		{
		}

		private void IJJIJIJIJIIIJJIIJJJIIJJJJJJIJJJIJJJIJIIIIIIIIJI()
		{
		}

		private void JJJIJJIIIIJIJIJJIJIIIIJJIIIIIJIJIJJIJJIIJIIJIJI(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, Vector2 IJJIJIJJIIJIIJJJIJIJIJIJIJIIJIIIIIIIJIIJIJJJIJJ)
		{
		}

		private void JJIJJJIIIIJIIIJJIIIJIJJJIIJIIIJIJIIIJIJJJJIIJIJ()
		{
		}

		private static Vector3 JIJJIIIJIIJJIIJJIIIIIJJJIIJIJJJIJJIIIIJIJJIIJIJ(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, Vector3 JJJJIJIIJIJJIIJJJIIJIJJIJIIIJJJIJIJIIJJIIJIJIJJ, Vector3 IJIIJJIJIJIJIIJJJIJIIIJIJIIJIJJIIIIJIIIJIIIIIJJ)
		{
			return default;
		}
	}
}
