using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace CodeStage.AntiCheat.ObscuredTypes
{
	[Serializable]
	[StructLayout((LayoutKind)0, Size = 32)]
	public struct ObscuredULong : IEquatable<ObscuredULong>, IFormattable
	{
		private static ulong cryptoKey;

		private ulong currentCryptoKey;

		private ulong hiddenValue;

		private ulong fakeValue;

		private bool inited;

		public static ulong IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(ulong JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0uL;
		}

		public bool IJIJIIJJIJJJJJJJJIIIJJJJIJJIJJIJIIJIJJJJIJIJJII(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}
		public static ObscuredULong IIIIIIJJIJJIJIJIJJJIIIIIIIIJIIJIIJIJJJJJJJIIJJJ(ObscuredULong JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public string ToString(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		private ObscuredULong(ulong JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			currentCryptoKey = 0uL;
			hiddenValue = 0uL;
			fakeValue = 0uL;
			inited = false;
		}

		public static void IJIJJJIJJIIIIIIIJIJIJJIIIIIIJIIIIIIJIIIJJJJJJIJ(ulong JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public override int GetHashCode()
		{
			return 0;
		}

		public static ulong JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(ulong JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0uL;
		}

		public bool Equals(ObscuredULong JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public void JJJIIJIJJJIIJJJJJIJJIJIIJJJIJJIIJIJJJIJJJIIJJJI(ulong JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		public ulong JJJJJJIIIJJIIIJJJJJJJJJJJIIJIJJIIIJIIIJIJJJJJII()
		{
			return 0uL;
		}

		public static ulong JIIIJIJJIIIIJJIIJJJJIJIIJIIJIIIIJJIJIIIJJIJIIJJ(ulong JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, ulong IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0uL;
		}

		public static void JJJJJIIIIIJIIJIJJJIJIIJJIIIIJIIJIJIIIJJIIIJIJJI(ulong JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public string JJIJJIIJJIIJIIIIJIIJJJJIJIJJIIIIJIJIJIJIJIIIIJJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		private ulong IIIJJIJJJJJJJIIIJIIIJIJJIJJIJIIJJIIIIJJIJIJIJJJ()
		{
			return 0uL;
		}

		public static ulong JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(ulong JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, ulong IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0uL;
		}

		public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public void IJJIIIJIJIIJIIJIJIIJJIJJIIIJJJJIJIIJIJJIJIIIIJI(ulong JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		public static ulong JJJJIIJIIIJJIJJIJIJJIIIJIIJJJIIJIIIIIJIJJIJIJII(ulong JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0uL;
		}

		public string IJJJIIIIIJJIIJJJJIJIIIJIJIJJIJIJJJIJJJIJIIJIIIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}
		public static implicit operator ObscuredULong(ulong JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public void JJJJJIIJJJJJIIJJJJJJJJIIJIIIJJIIJIJIIJIJIJIJJJI()
		{
		}

		public static void IJJJIJJIJIJJJIJIJJIJJIJIJIIIJJJIJJIIIIJIJJJJIIJ(ulong JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public override string ToString()
		{
			return null;
		}

		public static ulong IIJJJJIJJIJIJJIJJJIIIIIJJIIJIIIIJIIJIJJIIIJIJIJ(ulong JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0uL;
		}

		public static ulong IIJIIIIIJJIIJJJJJIJIIIJJIJIJJIJIIIJJJIJIJJIIIJJ(ulong JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, ulong IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0uL;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}
		public static ObscuredULong JJIJIJIJJJJIIIJJJIJJJJJIJJJJJIIIJJJIIJIJJJJIIJJ(ObscuredULong JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}
		public static implicit operator ulong(ObscuredULong JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0uL;
		}

		public void JJIIJJIIIIIIJIJIJJIJIJJIJIJIIJJJIIJJIIIJJIIJJII()
		{
		}

		public static ulong IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(ulong JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, ulong IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0uL;
		}
	}
}
