using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace CodeStage.AntiCheat.ObscuredTypes
{
	[Serializable]
	[StructLayout((LayoutKind)0, Size = 16)]
	public struct ObscuredUInt : IEquatable<ObscuredUInt>, IFormattable
	{
		private static uint cryptoKey;

		private uint currentCryptoKey;

		private uint hiddenValue;

		private uint fakeValue;

		private bool inited;
		public static implicit operator uint(ObscuredUInt JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0u;
		}

		private uint IIIJJIJJJJJJJIIIJIIIJIJJIJJIJIIJJIIIIJJIJIJIJJJ()
		{
			return 0u;
		}

		public int IIJIJJIJJJIIJIIIIIIJJJIIJJIIIJIIIIJIIIIIJIIJJIJ()
		{
			return 0;
		}

		public static uint IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(uint JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, uint IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0u;
		}

		public void JJIIJJIIIIIIJIJIJJIJIJJIJIJIIJJJIIJJIIIJJIIJJII()
		{
		}

		public uint IJJIIIJIIIJJIIIIIJJIIJJJJJIIJJJJJJJJJJIJJJJJJIJ()
		{
			return 0u;
		}

		public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public static void IJIJJJIJJIIIIIIIJIJIJJIIIIIIJIIIIIIJIIIJJJJJJIJ(uint JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public string ToString(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public void JJJIIJIJJJIIJJJJJIJJIJIIJJJIJJIIJIJJJIJJJIIJJJI(uint JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}
		public static uint IIJIJJJIIIJIIIIIJJIIJJJIIJJJJJIJJIJJIIJIIIJIJII(ObscuredUInt JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0u;
		}

		private ObscuredUInt(uint JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			currentCryptoKey = 0u;
			hiddenValue = 0u;
			fakeValue = 0u;
			inited = false;
		}

		public static uint JIJIIIJIJJJJJJIIJIJJIJIIJIJJIIJIIJJIIJIIIJIJIIJ(uint JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, uint IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0u;
		}
		public static implicit operator ObscuredUInt(uint JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public string IIIIIIJJJIJIJJIIJJJIIJIIIIJJJJIIIJIJIIJJJIJIIII(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		private uint JJJJJJJJJIIIIJIJIJJJJIIIIJJJJIIIJJJIJJJJIJJJIJI()
		{
			return 0u;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		public string IIJIJIIIIJJJJIJIJJIJJIIIJIIIIJIIIJJJJJJIIIIJJJJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		public bool Equals(ObscuredUInt JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		private uint IJJIIJJJIJJJIJJIIIJJJIIIIIJJJJJIIIJIIIIIIJIJIJI()
		{
			return 0u;
		}

		public bool JJIJIIIIIJIJJIIIJIIJJJIJJJIJJIJJJJJIJIIJIIIIJII(ObscuredUInt JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public void IJJJIIJIIIIIJJJJIIIIJIJIIIJJIIJIIJIJJIJIJIIJJJJ()
		{
		}

		public static uint JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(uint JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0u;
		}

		public uint JJJJJJIIIJJIIIJJJJJJJJJJJIIJIJJIIIJIIIJIJJJJJII()
		{
			return 0u;
		}
		public static ObscuredUInt IIIIIIJJIJJIJIJIJJJIIIIIIIIJIIJIIJIJJJJJJJIIJJJ(ObscuredUInt JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}
		public static ObscuredUInt JJJIIIJJJJIJIJIIIIIJIIJIJIJIIIJIJJIIJJIJIJJJIIJ(ObscuredUInt JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public static uint JJIIJJJJIJJJJIJJJIIJJIIIJIIIIJIIJIIJJIJIIIJJJII(uint JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0u;
		}

		public static uint IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(uint JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0u;
		}

		public static uint JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(uint JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, uint IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0u;
		}
		public static ObscuredUInt JJIJIJIJJJJIIIJJJIJJJJJIJJJJJIIIJJJIIJIJJJJIIJJ(ObscuredUInt JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public override int GetHashCode()
		{
			return 0;
		}
		public static ObscuredUInt JJJJJJJJJJIJIJIIJJIJIIJJJIJJJJJIJJIIJIIIJJJIIJI(ObscuredUInt JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public string JIJIIJIJJIIJIJJIIJIJIIIJJJJIJIJIIIJJJJJJIIIIIJI()
		{
			return null;
		}

		public void JJJJJIIJJJJJIIJJJJJJJJIIJIIIJJIIJIJIIJIJIJIJJJI()
		{
		}
		public static ObscuredUInt IJIJJJIJJIIIIJIJJIJIIIIIIJJIIIJIIIIIIJIIJJIIIII(uint JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public override string ToString()
		{
			return null;
		}
		public static ObscuredUInt IIIIJIJJIIIIJJIIIJJJIIIIJJJIIJIJJIIJIIJJIIIJIJI(ObscuredUInt JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public int JIJJIJIJJJJIJIJJJIIJIJIIJIJIIIIJIIIJJJJJJJJIIII()
		{
			return 0;
		}
		public static ObscuredInt IJJIIJIJIJJJIJJIJJIIJIJJJJJJIIJIIIJJJJJJJIJJIJI(ObscuredUInt JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public void JIIJIIIJIIJIJJIIJJJJIIJJIIJJIIIJIIJIIJJIIIIIIII()
		{
		}

		public static uint IIJIJIIJJIIJIJJIJJJJIJJIJJJIJIIJIJIIIJJIIJIIJIJ(uint JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, uint IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0u;
		}
	}
}
