using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using CodeStage.AntiCheat.Common;
using UnityEngine;

namespace CodeStage.AntiCheat.ObscuredTypes
{
	[Serializable]
	[StructLayout((LayoutKind)0, Size = 40)]
	public struct ObscuredDouble : IEquatable<ObscuredDouble>, IFormattable
	{
		[StructLayout((LayoutKind)2, Pack = 1, Size = 8)]
		private struct IJJJIJIIIJJJJIJJJJIJJIJJJIIJJJJJIJIIJJJJJIJJIII
		{
			[FieldOffset(0)]
			public double JJIJIIJIJIJIJJJIJIIIJIJIIJJJIIIIJJIIIIIIJIIJIJI;

			[FieldOffset(0)]
			public long JIIJJJJJIJIJJIIIJIIIJJIIIIJJIJIIIJJJJIJIJIIIJJJ;

			[FieldOffset(0)]
			public ACTkByte8 IIIJJJJIJIIIJJJIIJIJJIIJJIIIJJIIJIJJJIIIJJJIIJI;
		}

		private static long cryptoKey;

		[SerializeField]
		private long currentCryptoKey;

		[SerializeField]
		private byte[] hiddenValueOld;

		[SerializeField]
		private ACTkByte8 hiddenValue;

		[SerializeField]
		private double fakeValue;

		[SerializeField]
		private bool inited;

		public static long JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(double JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0L;
		}
		public static ObscuredDouble JJIJIJIJJJJIIIJJJIJJJJJIJJJJJIIIJJJIIJIJJJJIIJJ(ObscuredDouble JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public void JJIIJJIIIIIIJIJIJJIJIJJIJIJIIJJJIIJJIIIJJIIJJII()
		{
		}

		public static double JIIJJJIJJJIJJJIIIJIIJIIJJIJIJIJJJIIJIJIJIIIJIIJ(long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, long IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0.0;
		}

		public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public string ToString(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}
		public static ObscuredDouble IIJIIJIJIJJJIIIIJJIIJJIIJJJIJIIJIIIIIIJIJJIJIII(ObscuredDouble JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}
		public static implicit operator ObscuredDouble(double JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public static void IJIJJJIJJIIIIIIIJIJIJJIIIIIIJIIIIIIJIIIJJJJJJIJ(long JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public void JJJIIJIJJJIIJJJJJIJJIJIIJJJIJJIIJIJJJIJJJIIJJJI(long JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		public static double IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, long IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0.0;
		}

		public void IJIIJJJJJIIJJIIJJIJIJJJJJJIIJJJIIIIIIJJJJIIJIIJ(long JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		public string IIJJJJIJIIJJIIIIIJJJJJJJIIJJIIIJIJJIJJJIIJJIIJI()
		{
			return null;
		}

		private static ACTkByte8 IJIIIJIIJJIJJIIIJJJJJJJJIJJJIJJJIJJJJIIIIJJJIIJ(double JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, long IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return default;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public bool Equals(ObscuredDouble JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public override int GetHashCode()
		{
			return 0;
		}

		private static ACTkByte8 IJIIIJIIJJIJJIIIJJJJJJJJIJJJIJJJIJJJJIIIIJJJIIJ(double JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}
		public static ObscuredDouble JJJJJIIJIJJIJJIJJIJIJIJJJJIJJJIJJIIJJJJJJJJIIIJ(ObscuredDouble JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public string JJJJIJJIIJJIIIIJJJIIJJIJIIJJJJIJJJJJIIJIJJIJIII()
		{
			return null;
		}

		private ObscuredDouble(ACTkByte8 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			currentCryptoKey = 0L;
			hiddenValueOld = null;
			hiddenValue = default;
			fakeValue = 0.0;
			inited = false;
		}

		public bool IJIJIIJJIJJJJJJJJIIIJJJJIJJIJJIJIIJIJJJJIJIJJII(ObscuredDouble JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public string IIJJIJJJJJIIJIIJIJIIIJJIJJIIIJJJIIJJJIIIIIIIJII()
		{
			return null;
		}

		public long JJJJJJIIIJJIIIJJJJJJJJJJJIIJIJJIIIJIIIJIJJJJJII()
		{
			return 0L;
		}

		public static long JIIIJJJIIIIIIJJIJJIIJIIJJJIJIJJJJJJJJJJIJIIIIJJ(double JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, long IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0L;
		}

		public static double IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0.0;
		}

		private double IIIJJIJJJJJJJIIIJIIIJIJJIJJIJIIJJIIIIJJIJIJIJJJ()
		{
			return 0.0;
		}
		public static ObscuredDouble IIJIJJJJJIIJIJJJJJIIJIJJJIIJIJJJIJIIJIJJJIIJJJI(double JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public static long JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(double JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, long IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0L;
		}

		public override string ToString()
		{
			return null;
		}
		public static double IJIJJJIJJIIIIJIJJIJIIIIIIJJIIIJIIIIIIJIIJJIIIII(ObscuredDouble JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0.0;
		}

		public static long JIIJJJIJIIJJIJIIJIIIIIJIIIIIIIIIIIIJIJJJIJJJJJJ(double JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, long IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0L;
		}
		public static double JIIIJJIIIIJJJJJJIJJIJIJJIJJIJJIIIJJJJIJIJIJJJJJ(ObscuredDouble JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0.0;
		}

		public void JJJJJIIJJJJJIIJJJJJJJJIIJIIIJJIIJIJIIJIJIJIJJJI()
		{
		}

		private static ACTkByte8 JJJIIJJJJJJIJJJJIIIIIJJIIJJIJJJIIJIJJIJJIIJIIIJ(double JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public static long IIJJIIIJJJIJIIJJJIJJJJJJJJIIJIIIIIIJJJJJJJIJIJI(double JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0L;
		}
		public static ObscuredDouble IIIIIIJJIJJIJIJIJJJIIIIIIIIJIIJIIJIJJJJJJJIIJJJ(ObscuredDouble JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}
		public static implicit operator double(ObscuredDouble JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0.0;
		}

		public long IIIIIIJJIJJJJJIIJJIIIIJIIJJIIIJJJJIIIJJJIJIIJJJ()
		{
			return 0L;
		}

		public bool IIIJJIJJJJJIJIJJIIIIIJJJJIIIIJJJJIIJJIIJJIJJIJI(ObscuredDouble JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}
	}
}
