using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using UnityEngine;

namespace CodeStage.AntiCheat.ObscuredTypes
{
	[Serializable]
	[StructLayout((LayoutKind)0, Size = 20)]
	public struct ObscuredBool : IEquatable<ObscuredBool>
	{
		private static byte cryptoKey;

		[SerializeField]
		private byte currentCryptoKey;

		[SerializeField]
		private int hiddenValue;

		[SerializeField]
		private bool fakeValue;

		[SerializeField]
		private bool fakeValueChanged;

		[SerializeField]
		private bool inited;

		public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}
		public static bool IJIIJIJIJIIIIJJIIIIJJJJIJJJJJIIIIJIIIIJJIIIJJII(ObscuredBool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return false;
		}

		public static bool IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return false;
		}

		public void JJIJJJJJIJIIJIIIJIIJJIJJJJIIIIIJIIJJIIIJJIIJIIJ(int JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		private bool IIJIIJJJIJIJIJIJJIIJIJIIIJJIJIJJIIIIJIIIIIJJJJJ()
		{
			return false;
		}

		public void IJJJJIIIJIJJJIIJIIJJJJIJJIJJJIJIIIJIJJIIJIJIJIJ()
		{
		}

		public int IIJIIIJJJIIJJIIIIJJJJIIJJIIJIJJJJJIJIJIJJIJJJJJ()
		{
			return 0;
		}

		public static int JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0;
		}
		public static implicit operator bool(ObscuredBool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return false;
		}

		public static bool IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return false;
		}

		public bool Equals(ObscuredBool JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public bool IJJJJJJIJJJIJIJJIJJJJIJIIIJJJIIJIIIJIJIIIIIIIII(ObscuredBool JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public void JIIJIIIJJJJJIJJIJIIJJIJIJIIJIIIIJIJJJIJJIIJJIJI(int JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		public override int GetHashCode()
		{
			return 0;
		}

		public static void JJJJJIIIIIJIIJIJJJIJIIJJIIIIJIIJIJIIIJJIIIJIJJI(byte JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		private ObscuredBool(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			currentCryptoKey = 0;
			hiddenValue = 0;
			fakeValue = false;
			fakeValueChanged = false;
			inited = false;
		}

		public void JJIIJJIIIIIIJIJIJJIJIJJIJIJIIJJJIIJJIIIJJIIJJII()
		{
		}
		public static implicit operator ObscuredBool(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public void JJJJJIIJJJJJIIJJJJJJJJIIJIIIJJIIJIJIIJIJIJIJJJI()
		{
		}

		public void JJJIIJIJJJIIJJJJJIJJIJIIJJJIJJIIJIJJJIJJJIIJJJI(int JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		public static void IJJIIJIJJJJIIJJIIIJJJJJJIJJJIIIJIJJJJIJIIIJJJJJ(byte JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public bool JIJIIJIIJJIJIJIJIIJIIIJIIJJIIJIJJJJJIJJJIIIJIIJ(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public void IJIIIIJIJJIIJIJJIJIIJIIIIIJIJJIIJJJIJJJJIIIJJJJ()
		{
		}

		private bool IIIJJIJJJJJJJIIIJIIIJIJJIJJIJIIJJIIIIJJIJIJIJJJ()
		{
			return false;
		}

		public static int JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0;
		}

		public bool JIIJIIJJIIIJJJIJJIJIJIIJIIJIIIJJIJIJJJIJJIJIJII(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public static bool IIIJIIJIJIJIIJJJIIIJJIJJJJIJJIIIJIIIJIIJIJIIJJJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return false;
		}

		public static void IJIJJJIJJIIIIIIIJIJIJJIIIIIIJIIIIIIJIIIJJJJJJIJ(byte JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public int JJJJJJIIIJJIIIJJJJJJJJJJJIIJIJJIIIJIIIJIJJJJJII()
		{
			return 0;
		}

		public string IIJJIJJJJJIIJIIJIJIIIJJIJJIIIJJJIIJJJIIIIIIIJII()
		{
			return null;
		}

		public override string ToString()
		{
			return null;
		}
	}
}
