using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using CodeStage.AntiCheat.Common;

namespace CodeStage.AntiCheat.ObscuredTypes
{
	[Serializable]
	[StructLayout((LayoutKind)0, Size = 48)]
	public struct ObscuredDecimal : IEquatable<ObscuredDecimal>, IFormattable
	{
		[StructLayout((LayoutKind)2, Pack = 1, Size = 16)]
		private struct IIIIIIJIJIJJIJJIJIJJIJIJIJIIIIJIJJJIJIJJIJIIIII
		{
			[FieldOffset(0)]
			public decimal JJIJIIJIJIJIJJJIJIIIJIJIIJJJIIIIJJIIIIIIJIIJIJI;

			[FieldOffset(0)]
			public long IIIJJIIJJIIIIIIJIJIIIIJJJIJIJJIJIJIIIJIJIJJIIJJ;

			[FieldOffset(8)]
			public long IIIJJJIIIIJIIJIIIIIJJIJJIIIIJJIJIIJIIJJIIIJJIIJ;

			[FieldOffset(0)]
			public ACTkByte16 JJIJJJJIJJIJIJJJJJIJJIJIJJIJIJJJIJJJJIJIJIIIIII;
		}

		private static long cryptoKey;

		private long currentCryptoKey;

		private byte[] hiddenValueOld;

		private ACTkByte16 hiddenValue;

		private decimal fakeValue;

		private bool inited;
		public static ObscuredDecimal IJIJIIIIIIJIJJJJJJJJJJIIJJIIIIJJIIJIJJJIIIJJJII(decimal JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public override string ToString()
		{
			return null;
		}

		public void JJJJJIIJJJJJIIJJJJJJJJIIJIIIJJIIJIJIIJIJIJIJJJI()
		{
		}
		public static ObscuredDecimal IJJIIJIJIJJJIJJIJJIIJIJJJJJJIIJIIIJJJJJJJIJJIJI(ObscuredFloat JIJIJJJIJJIIIIIJIIIIIJJJJJJJIIIIJIIIJJJJIJJIIJI)
		{
			return default;
		}
		public static ObscuredDecimal IIIIIIJJIJJIJIJIJJJIIIIIIIIJIIJIIJIJJJJJJJIIJJJ(ObscuredDecimal JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public void IJIIJJIJJIIJJJJJJJIJJJIJIJJJIJIIIJIJIJJIJIJJJJI(decimal JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		public void JIIJJIJJIJJJIJIJJJIJJJIIIJIIIIIJIIJIIJIJJJJJIIJ()
		{
		}

		public string IIIJIIIIIIJJJIJIIIJJIIJIJJIIJJJIIJJIIIJJJIIIJJJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		private static ACTkByte16 IJIIIJIIJJIJJIIIJJJJJJJJIJJJIJJJIJJJJIIIIJJJIIJ(decimal JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, long IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return default;
		}
		public static decimal IJJJJJJJIJIIIJIJIJJJJIIJIIJJJJIIIJJIJJIJJIJIIJI(ObscuredDecimal JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0m;
		}

		public string IIJJJJIJIIJJIIIIIJJJJJJJIIJJIIIJIJJIJJJIIJJIIJI(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public bool IJIIIIIIJIJIIIIJJJIJIJIIIIJIJIJJIIJIJIIJIIJIJJI(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}
		public static decimal IJIJIJIIJIIJIIJIIIJJJIIIJIIJIIIJIJIJJIJJJJJJIII(ObscuredDecimal JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0m;
		}

		public void JJIIJJIIIIIIJIJIJJIJIJJIJIJIIJJJIIJJIIIJJIIJJII()
		{
		}

		public override int GetHashCode()
		{
			return 0;
		}
		public static implicit operator ObscuredDecimal(decimal JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public static decimal IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(decimal JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, long IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0m;
		}

		public static void JJJJJIIIIIJIIJIJJJIJIIJJIIIIJIIJIJIIIJJIIIJIJJI(long JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}
		public static ObscuredDecimal JJIJIJIJJJJIIIJJJIJJJJJIJJJJJIIIJJJIIJIJJJJIIJJ(ObscuredDecimal JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public static decimal JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(decimal JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0m;
		}
		public static ObscuredDecimal JJJJIIJIIIJIJIIJIIIJJIJJJJIJIJIJJIJIIIIJJIIIIIJ(ObscuredDecimal JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		private static ACTkByte16 IJIIIJIIJJIJJIIIJJJJJJJJIJJJIJJJIJJJJIIIIJJJIIJ(decimal JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public void JJJIIJIJJJIIJJJJJIJJIJIIJJJIJJIIJIJJJIJJJIIJJJI(decimal JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		private decimal IIIIIIJJIIJIJIJJIIJJIIJIIIJIIJJJJIIJIJJJIJIJJIJ()
		{
			return 0m;
		}

		public static void IJIJJJIJJIIIIIIIJIJIJJIIIIIIJIIIIIIJIIIJJJJJJIJ(long JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public string IJJJIIIIIJJIIJJJJIJIIIJIJIJJIJIJJJIJJJIJIIJIIIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		private decimal IJIIJJJJIIJIIJJIIIJJIIJIIIJJIIIJIJJIIIJIJJJIIJI()
		{
			return 0m;
		}
		public static ObscuredDecimal IIIJJJIJJIJIIJIIIJIIIJJIJJJIJJJIIJIJIJJJJIIJJJJ(ObscuredFloat JIJIJJJIJJIIIIIJIIIIIJJJJJJJIIIIJIIIJJJJIJJIIJI)
		{
			return default;
		}

		public string ToString(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public bool JIIIIJJJJIIIIIIIIIJJIIIJJJJJIIJJJIJJIIJJIJIIJJI(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		public static void JJJIIJIIJJIJIIJIIJJJJJIIJIIJIJJJIIIIJJJIIJIIJJI(long JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public string IJJIIJIIJIIIJIJJIIIIJIJJIIIIJIJJIJJJIJIJJIJIIII(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		private ObscuredDecimal(ACTkByte16 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			currentCryptoKey = 0L;
			hiddenValueOld = null;
			hiddenValue = default;
			fakeValue = 0m;
			inited = false;
		}

		public static decimal IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(decimal JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0m;
		}
		public static implicit operator decimal(ObscuredDecimal JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0m;
		}

		private decimal IIIJJIJJJJJJJIIIJIIIJIJJIJJIJIIJJIIIIJJIJIJIJJJ()
		{
			return 0m;
		}
		public static ObscuredDecimal IJIIJJIJIJJIIJIIJJJJJJIIIJJIJIJJIIJIIJIJJIIIJII(ObscuredDecimal JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public bool Equals(ObscuredDecimal JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}
		public static ObscuredDecimal JJIJJJJIIJJJJIIIIIIJIIIJJIIIJJIJJIJJJIIJJJJIJII(ObscuredFloat JIJIJJJIJJIIIIIJIIIIIJJJJJJJIIIIJIIIJJJJIJJIIJI)
		{
			return default;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public decimal JJJJJJIIIJJIIIJJJJJJJJJJJIIJIJJIIIJIIIJIJJJJJII()
		{
			return 0m;
		}

		public static decimal JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(decimal JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, long IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0m;
		}
	}
}
