using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using UnityEngine;

namespace CodeStage.AntiCheat.ObscuredTypes
{
	[Serializable]
	[StructLayout((LayoutKind)0, Size = 32)]
	public struct ObscuredVector3
	{
		[Serializable]
		[StructLayout((LayoutKind)0, Size = 12)]
		public struct RawEncryptedVector3
		{
			public int x;

			public int y;

			public int z;
		}

		private static int cryptoKey;

		private static readonly Vector3 initialFakeValue;

		[SerializeField]
		private int currentCryptoKey;

		[SerializeField]
		private RawEncryptedVector3 hiddenValue;

		[SerializeField]
		private Vector3 fakeValue;

		[SerializeField]
		private bool inited;

		public float x
		{
			get
			{
				return 0f;
			}
			set
			{
			}
		}

		public float y
		{
			get
			{
				return 0f;
			}
			set
			{
			}
		}

		public float z
		{
			get
			{
				return 0f;
			}
			set
			{
			}
		}

		// C# has no syntax for parameterized property 'Item'.
		public float get_Item(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
		{
			return 0f;
		}

		public void set_Item(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}

		private float JIIJIIJIJJJJJIIJIJIIJJJIIJIJIJJJJIIJIIJJJJIJIIJ(int JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
			return 0f;
		}
		public static bool JIIJIJIIIIIJJJIJIJJJIIJIIIJIJJJIJIIJIIIJJJJJJII(ObscuredVector3 IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, ObscuredVector3 IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
		{
			return false;
		}
		public static bool JIIIIIJJJIIIJIIJIJIIIIJJIIIIIJJJIIJIIJIIJJJJIJI(ObscuredVector3 IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, ObscuredVector3 IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
		{
			return false;
		}

		public static Vector3 IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(RawEncryptedVector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}
		public static bool JJIIJJJJJJJJJIJIJJIIIJJJIJIIJIJJJJIJJIJJJJJIJII(ObscuredVector3 IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, Vector3 IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
		{
			return false;
		}

		public static RawEncryptedVector3 IJIIJIJJJJIIJJJIIIIJIJJJIJJIIIIJJJIIIJIIJJIJIJI(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}
		public static ObscuredVector3 IIIIJIJIJJIIJJJIIIIIJJIIIJJJIJJIJIJIJIIJJIIJJJJ(Vector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, ObscuredVector3 JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
		{
			return default;
		}
		public static implicit operator ObscuredVector3(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}
		public static ObscuredVector3 IJIIJJJIIIJIIIIJJJJJJIIJIJJIJJIIIJIJJJJJIIJIJJJ(ObscuredVector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, ObscuredVector3 JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
		{
			return default;
		}
		public static ObscuredVector3 IIIIIJIIIIIIJJIIJIJIJJJIIIJIJIJIJIJJIIJIIJJIJJJ(ObscuredVector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, ObscuredVector3 JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
		{
			return default;
		}
		public static ObscuredVector3 IIJIIJJIIIIIIIJJJIJIJIJJIIJIJJJIJJIJJIJJIJIJIIJ(ObscuredVector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, Vector3 JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
		{
			return default;
		}
		public void IJJJIIIJJIIIJIJIIIJJIIJIJJIJIJJIJJJIJJIJIJIIJJJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}
		public float JIIJIIIJJIJJJIIJJIJJJIJIIIIIJJIJIJJIIIIJJJJIJII()
		{
			return 0f;
		}

		public static RawEncryptedVector3 JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return default;
		}
		public static bool JIIIIIJJJIIIJIIJIJIIIIJJIIIIIJJJIIJIIJIIJJJJIJI(Vector3 IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, ObscuredVector3 IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
		{
			return false;
		}

		public RawEncryptedVector3 JJJJJJIIIJJIIIJJJJJJJJJJJIIJIJJIIIJIIIJIJJJJJII()
		{
			return default;
		}
		public static bool JIIJJJJIIJIIJIJJIIIIIIIJIJJIIIJJJIJJJJJIJIJJIJI(ObscuredVector3 IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, Vector3 IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
		{
			return false;
		}
		public static ObscuredVector3 IIJIIJJIIIIIIIJJJIJIJIJJIIJIJJJIJJIJJIJJIJIJIIJ(Vector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, ObscuredVector3 JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
		{
			return default;
		}

		private ObscuredVector3(RawEncryptedVector3 JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
			currentCryptoKey = 0;
			hiddenValue = default;
			fakeValue = default;
			inited = false;
		}
		public float IIIIIJIIJIJIJJJIJJJJIIIIIJIJIJJIJIIJJJJIIJIJJII()
		{
			return 0f;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}
		public static ObscuredVector3 JIJJIIJJIIIIJJIJJJIIJJIIIIIIIJIIJIIIJJIIIIJJJIJ(ObscuredVector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, Vector3 JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
		{
			return default;
		}
		public static bool JIIIIIJJJIIIJIIJIJIIIIJJIIIIIJJJIIJIIJIIJJJJIJI(ObscuredVector3 IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, Vector3 IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
		{
			return false;
		}

		public static void IJIJJJIJJIIIIIIIJIJIJJIIIIIIJIIIIIIJIIIJJJJJJIJ(int JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		private bool JJJJIIJJJIJIIIIJJJIIJIIJJIIJIIJIIJJJJIIJJIIIJIJ(Vector3 IIIJIIJJIIIJJJJIIJJJJJJJIJJIIIIJJIJJIIIJJIIIIJJ, Vector3 JIJIJJIJJIJIIIIJIIIJJIIIIIIJIJIIJJJIIIIJIIIIJJI)
		{
			return false;
		}

		private int IJJJJIIJJIJIJIJJIJIIJJJJJJJIJIJJJJIIJIIJIIJIIJJ(float JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
			return 0;
		}

		public static RawEncryptedVector3 JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}
		public static ObscuredVector3 IJIJJJIIJJJJJIIIIIIJIIIJIJIIJJJJJJJJIIIIJIIJIJI(ObscuredVector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ)
		{
			return default;
		}
		public static ObscuredVector3 IIIJIJIIJIIJJJJJIIJJIJJIIJJIJJJIJIJJIJJIIIJIJJJ(ObscuredVector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ)
		{
			return default;
		}

		public static RawEncryptedVector3 IIJIJIIJJIIJIJJIJJJJIJJIJJJIJIIJIJIIIJJIIJIIJIJ(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return default;
		}

		private Vector3 IIIJJIJJJJJJJIIIJIIIJIJJIJJIJIIJJIIIIJJIJIJIJJJ()
		{
			return default;
		}
		public static ObscuredVector3 IIIIIJIIIIIIJJIIJIJIJJJIIIJIJIJIJIJJIIJIIJJIJJJ(ObscuredVector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, Vector3 JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
		{
			return default;
		}
		public static implicit operator Vector3(ObscuredVector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public bool IJIJIJJIIJJJIIJIIJJIIJJIJJJJIJJJJIJJJJJIIJIJIJI(object IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
		{
			return false;
		}

		public int IJIIJIIJJJIIIIJJJJJIJJJJJIJIIIJJIIIIIIJIIIIJJJI()
		{
			return 0;
		}

		public override string ToString()
		{
			return null;
		}

		public void JJIIJJIIIIIIJIJIJJIJIJJIJIJIIJJJIIJJIIIJJIIJJII()
		{
		}

		public override bool Equals(object IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
		{
			return false;
		}
		public static ObscuredVector3 IJIIIJIIIIIIIIIIIJJJIJJJIJIIIIJJIIJIJJIJJJJJJIJ(float JJIJIIJIJIJIJJJIJIIIJIJIIJJJIIIIJJIIIIIIJIIJIJI, ObscuredVector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ)
		{
			return default;
		}

		public static Vector3 IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(RawEncryptedVector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return default;
		}
		public static ObscuredVector3 IIIIIJIIIIIIJJIIJIJIJJJIIIJIJIJIJIJJIIJIIJJIJJJ(Vector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, ObscuredVector3 JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
		{
			return default;
		}

		public void JJJIIJIJJJIIJJJJJIJJIJIIJJJIJJIIJIJJJIJJJIIJJJI(RawEncryptedVector3 JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}
		public static bool JIIJIJIIIIIJJJIJIJJJIIJIIIJIJJJIJIIJIIIJJJJJJII(Vector3 IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, ObscuredVector3 IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
		{
			return false;
		}

		public override int GetHashCode()
		{
			return 0;
		}
		public static ObscuredVector3 IIJIIJJIIIIIIIJJJIJIJIJJIIJIJJJIJJIJJIJJIJIJIIJ(ObscuredVector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, ObscuredVector3 JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
		{
			return default;
		}

		public void JJJJJIIJJJJJIIJJJJJJJJIIJIIIJJIIJIJIIJIJIJIJJJI()
		{
		}
		public static ObscuredVector3 IJIJJJIJJIIIIJIJJIJIIIIIIJJIIIJIIIIIIJIIJJIIIII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}
		public static bool JIIJIJIIIIIJJJIJIJJJIIJIIIJIJJJIJIIJIIIJJJJJJII(ObscuredVector3 IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, Vector3 IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
		{
			return false;
		}
		public static ObscuredVector3 IJIIIJIIIIIIIIIIIJJJIJJJIJIIIIJJIIJIJJIJJJJJJIJ(ObscuredVector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, float JJIJIIJIJIJIJJJIJIIIJIJIIJJJIIIIJJIIIIIIJIIJIJI)
		{
			return default;
		}
		public static ObscuredVector3 JJIIIIJIJJJJIIIIJJJIIJJJJJJJIJJJJIIJIIJIJIJJJJJ(float JJIJIIJIJIJIJJJIJIIIJIJIIJJJIIIIJJIIIIIIJIIJIJI, ObscuredVector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ)
		{
			return default;
		}
		public static ObscuredVector3 IIJIJIIIJIIIIIJIJIIJJIJJIIJJIJJJIIJJJIJJJJIIJII(ObscuredVector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, float JJIJIIJIJIJIJJJIJIIIJIJIIJJJIIIIJJIIIIIIJIIJIJI)
		{
			return default;
		}

		private int JJJJJJIIIJJIIJIIIIIJIJJJIJIIJJJIJIJJIIIIJJJJIJJ(float JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
			return 0;
		}
	}
}
