using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace CodeStage.AntiCheat.ObscuredTypes
{
	[Serializable]
	[StructLayout((LayoutKind)0, Size = 12)]
	public struct ObscuredUShort : IEquatable<ObscuredUShort>, IFormattable
	{
		private static ushort cryptoKey;

		private ushort currentCryptoKey;

		private ushort hiddenValue;

		private ushort fakeValue;

		private bool inited;

		public static ushort JJIJIIIIJJIIIJIJIIIJJIIJIJIIIJJJJIIJIJIJJJJIJJJ(ushort JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0;
		}

		public string JIIJIIJIJJJIIIJJIIIJJIIIJJIIIIIIJIJIJIIIJIJJIII(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		public bool JJIIJJJJIJIJIIJIJIIIIJIJIJIIJJIIIIJJIJJIJJJJJJI(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public string IIIJIIIIIIJJJIJIIIJJIIJIJJIIJJJIIJJIIIJJJIIIJJJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		public void IJIJIIIIIIJIIIJJJIIIJIIIJIJJJJJJJJJJJJJIJIIIIJJ()
		{
		}

		public static ushort JJJJIJJIIIJIJIJJIJIIJIJIJJJIIIIIIJIIJJJIJJJJIJJ(ushort JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, ushort IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0;
		}

		public void JJJJJIIJJJJJIIJJJJJJJJIIJIIIJJIIJIJIIJIJIJIJJJI()
		{
		}

		public static void IJIJJJIJJIIIIIIIJIJIJJIIIIIIJIIIIIIJIIIJJJJJJIJ(ushort JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public bool Equals(ObscuredUShort JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public override string ToString()
		{
			return null;
		}

		private ushort IIIJJIJJJJJJJIIIJIIIJIJJIJJIJIIJJIIIIJJIJIJIJJJ()
		{
			return 0;
		}

		public ushort JJJJJJIIIJJIIIJJJJJJJJJJJIIJIJJIIIJIIIJIJJJJJII()
		{
			return 0;
		}

		public bool IIJIIJJIIIJIJIIJIIJIJIJJJIIJIIJIIJJJIIIIIIIIIIJ(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}
		public static ObscuredUShort JJIJIJIJJJJIIIJJJIJJJJJIJJJJJIIIJJJIIJIJJJJIIJJ(ObscuredUShort JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public static ushort IIIJJJIJJJJIIIIJJIJIJIIJJJIIJJIIIIJJIIIJJIJJIII(ushort JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public static ushort IIIJJJIJJJJIIIIJJIJIJIIJJJIIJJIIIIJJIIIJJIJJIII(ushort JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, ushort IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0;
		}

		public void IIJJIJJJIIIIJJIIIIIJJIIJJIIIIIIIJIJIJIIJJJJJJJJ()
		{
		}

		public bool JIIIIIJJJIJJJJIJIIIJIIJJJJJJIIIJJIJIJJIIJIIIIII(ObscuredUShort JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public void JJIJJJJJIJIIJIIIJIIJJIJJJJIIIIIJIIJJIIIJJIIJIIJ(ushort JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}
		public static ObscuredUShort JJJJJIJJIIIJJIJJJJIJJIJIJIJIJIIIIJJIJIIIIJIIIIJ(ObscuredUShort JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}
		public static ObscuredUShort JJJJIJIJJIIIIIJIIIJIIIIIIJJJIIJIJIJJIJJJIIJJJII(ObscuredUShort JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public override int GetHashCode()
		{
			return 0;
		}

		public void IJJJIJIJIIIIIIJIJIJIJIIIIJJIIIJIIJJJIJIIJJIJJJI()
		{
		}

		public string JIJJJIJJIJIIIIIJIIIJJJIIJIJIIIIJIJJIIJJIIIJIJJJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public bool IJIJIJJIIJJJIIJIIJJIIJJIJJJJIJJJJIJJJJJIIJIJIJI(ObscuredUShort JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}
		public static ObscuredUShort IJIJJJIJJIIIIJIJJIJIIIIIIJJIIIJIIIIIIJIIJJIIIII(ushort JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		private ObscuredUShort(ushort JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			currentCryptoKey = 0;
			hiddenValue = 0;
			fakeValue = 0;
			inited = false;
		}

		public void JJIIJJIIIIIIJIJIJJIJIJJIJIJIIJJJIIJJIIIJJIIJJII()
		{
		}

		public string JJIJJIIJJIIJIIIIJIIJJJJIJIJJIIIIJIJIJIJIJIIIIJJ()
		{
			return null;
		}

		public string ToString(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		public void JJJIIJIJJJIIJJJJJIJJIJIIJJJIJJIIJIJJJIJJJIIJJJI(ushort JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		public void IJJIIIIJJIIJJIIJIIJIJJIJJJJJIIJIIIIIIJJIJIIIIJI()
		{
		}
		public static implicit operator ObscuredUShort(ushort JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}
		public static ObscuredUShort IIIIIIJJIJJIJIJIJJJIIIIIIIIJIIJIIJIJJJJJJJIIJJJ(ObscuredUShort JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}
		public static implicit operator ushort(ObscuredUShort JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0;
		}

		public int JIIIIJIIIIJIJJIIIIIJJJJJIJJIJIIIIJJIJIJJJJJJIIJ()
		{
			return 0;
		}

		public void IIIIJIIIIIJJJIIJIJJJIIJJJJIJJIJIIJJJJJIJIIJJJJJ(ushort JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}
	}
}
