using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using UnityEngine;

namespace CodeStage.AntiCheat.ObscuredTypes
{
	[Serializable]
	[StructLayout((LayoutKind)0, Size = 32)]
	public struct ObscuredLong : IEquatable<ObscuredLong>, IFormattable
	{
		private static long cryptoKey;

		[SerializeField]
		private long currentCryptoKey;

		[SerializeField]
		private long hiddenValue;

		[SerializeField]
		private long fakeValue;

		[SerializeField]
		private bool inited;
		public static implicit operator long(ObscuredLong JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0L;
		}

		public static long IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, long IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0L;
		}

		public override int GetHashCode()
		{
			return 0;
		}

		public static void IJIJJJIJJIIIIIIIJIJIJJIIIIIIJIIIIIIJIIIJJJJJJIJ(long JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		private long IIIJJIJJJJJJJIIIJIIIJIJJIJJIJIIJJIIIIJJIJIJIJJJ()
		{
			return 0L;
		}

		public string IJJJIIIIIJJIIJJJJIJIIIJIJIJJIJIJJJIJJJIJIIJIIIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		public override string ToString()
		{
			return null;
		}

		public static long IIJIJIIJJIIJIJJIJJJJIJJIJJJIJIIJIJIIIJJIIJIIJIJ(long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, long IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0L;
		}

		public static long JJIJJIJIJJIIJJIIIIIIIJIJIIJIJIJJJJIIJJIIJIJJJII(long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, long IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0L;
		}
		public static ObscuredLong IIIIIIJJIJJIJIJIJJJIIIIIIIIJIIJIIJIJJJJJJJIIJJJ(ObscuredLong JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public static long IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0L;
		}
		public static long IIIJJJIIIJJJIIJJJIIIJJJJJIJJJJIJJJIJJJJJJIIIJJI(ObscuredLong JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0L;
		}

		public bool Equals(ObscuredLong JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public static long JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0L;
		}

		public void JJJIIJIJJJIIJJJJJIJJIJIIJJJIJJIIJIJJJIJJJIIJJJI(long JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}
		public static implicit operator ObscuredLong(long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public string ToString(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public long JJJJJJIIIJJIIIJJJJJJJJJJJIIJIJJIIIJIIIJIJJJJJII()
		{
			return 0L;
		}

		private long IJIIJJJJIIJIIJJIIIJJIIJIIIJJIIIJIJJIIIJIJJJIIJI()
		{
			return 0L;
		}

		public bool IIIJJIJJJJJIJIJJIIIIIJJJJIIIIJJJJIIJJIIJJIJJIJI(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public string IIJIIJJJJIIIJIJJJIIJJIJIIJIIJJIJIJIJJJJIJIJJIJI(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}
		public static ObscuredLong IIJIIJIJIJJJIIIIJJIIJJIIJJJIJIIJIIIIIIJIJJIJIII(ObscuredLong JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}
		public static ObscuredLong JJIJIJIJJJJIIIJJJIJJJJJIJJJJJIIIJJJIIJIJJJJIIJJ(ObscuredLong JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public void JJJJJIIJJJJJIIJJJJJJJJIIJIIIJJIIJIJIIJIJIJIJJJI()
		{
		}

		public static long JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, long IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0L;
		}

		public static long JIIIIIJIIIJIJJJIJIIIIIJJIIJJJIJIIJIJJIJIJJJIJJJ(long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0L;
		}

		public string JIIIJJJJIIJIIJJIIJIJJIIJJIIJIIJJIJJIJIJIIIJJIIJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public void JJIIJJIIIIIIJIJIJJIJIJJIJIJIIJJJIIJJIIIJJIIJJII()
		{
		}

		private ObscuredLong(long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			currentCryptoKey = 0L;
			hiddenValue = 0L;
			fakeValue = 0L;
			inited = false;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}
		public static ObscuredLong JIJIJJJIJJJJJIIIIJIJIIIJIIJIJIJJIIIIIIIJJJIJIII(long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}
	}
}
