using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using UnityEngine;

namespace CodeStage.AntiCheat.ObscuredTypes
{
	[Serializable]
	[StructLayout((LayoutKind)0, Size = 24)]
	public struct ObscuredVector2
	{
		[Serializable]
		[StructLayout((LayoutKind)0, Size = 8)]
		public struct RawEncryptedVector2
		{
			public int x;

			public int y;
		}

		private static int cryptoKey;

		private static readonly Vector2 initialFakeValue;

		[SerializeField]
		private int currentCryptoKey;

		[SerializeField]
		private RawEncryptedVector2 hiddenValue;

		[SerializeField]
		private Vector2 fakeValue;

		[SerializeField]
		private bool inited;

		public float x
		{
			get
			{
				return 0f;
			}
			set
			{
			}
		}

		public float y
		{
			get
			{
				return 0f;
			}
			set
			{
			}
		}

		// C# has no syntax for parameterized property 'Item'.
		public float get_Item(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
		{
			return 0f;
		}

		public void set_Item(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}

		public int IIJIJJIJJJIIJIIIIIIJJJIIJJIIIJIIIIJIIIIIJIIJJIJ()
		{
			return 0;
		}

		private ObscuredVector2(RawEncryptedVector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			currentCryptoKey = 0;
			hiddenValue = default;
			fakeValue = default;
			inited = false;
		}

		public static RawEncryptedVector2 JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return default;
		}
		public static ObscuredVector2 IJJJIJIJIJJJIIJIJJIJIIJIJJIIJIJJIJJIIJJJIJJJIII(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		private Vector2 JIJJIIIIJIIIJJJJJIJIJJIIJIIJIIIJJIIJJJIJJIIIJJJ()
		{
			return default;
		}

		private Vector2 IIIJIJIJIIIJJIIJJJJJIIJJJIJJJIIJIJIJIJIIJIJJIJJ()
		{
			return default;
		}

		public static Vector2 IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(RawEncryptedVector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return default;
		}

		public static RawEncryptedVector2 JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		public void JJJIIJIJJJIIJJJJJIJJIJIIJJJIJJIIJIJJJIJJJIIJJJI(RawEncryptedVector2 JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		private bool IIJIJJJJJIIIIIJIIJJIJJJJIIJIIIJIIIJIJIJJJIIIIII(Vector2 IIIJIIJJIIIJJJJIIJJJJJJJIJJIIIIJJIJJIIIJJIIIIJJ, Vector2 JIJIJJIJJIJIIIIJIIIJJIIIIIIJIJIIJJJIIIIJIIIIJJI)
		{
			return false;
		}
		public static Vector2 JIIJIJJJJJJIIIJJJJIJIJJIJIIIJIIIJIJJIJJJJIJIJJJ(ObscuredVector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public int JIJJIJIJJJJIJIJJJIIJIJIIJIJIIIIJIIIJJJJJJJJIIII()
		{
			return 0;
		}

		public RawEncryptedVector2 JJJJJJIIIJJIIIJJJJJJJJJJJIIJIJJIIIJIIIJIJJJJJII()
		{
			return default;
		}
		public float IJJJIIJIJJIIJIIJJIJJJJJIIIIJJJJJJIJJJJIIIJIJJII()
		{
			return 0f;
		}

		public void JJJJJIIJJJJJIIJJJJJJJJIIJIIIJJIIJIJIIJIJIJIJJJI()
		{
		}

		public static Vector2 IJIJJJJJIIJJJJJIIJIJJJJIJIJJJIJJIJIIJJIJJIIJIIJ(RawEncryptedVector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public override string ToString()
		{
			return null;
		}

		public void JJIIJJIIIIIIJIJIJJIJIJJIJIJIIJJJIIJJIIIJJIIJJII()
		{
		}

		public static void IJIJJJIJJIIIIIIIJIJIJJIIIIIIJIIIIIIJIIIJJJJJJIJ(int JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public string JIIIJJJJIIJIIJJIIJIJJIIJJIIJIIJJIJJIJIJIIIJJIIJ()
		{
			return null;
		}
		public float JJJJIJIIJJJJIIIJJJJJJJJJIIJIIJJIJIIIJJIJJJIJJJJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
		{
			return 0f;
		}
		public static implicit operator Vector3(ObscuredVector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		private Vector2 IIIJJIJJJJJJJIIIJIIIJIJJIJJIJIIJJIIIIJJIJIJIJJJ()
		{
			return default;
		}

		private bool JIIIJIIJJIJIIIJIIJJJIJIIIIIJJIIJIIJIIJJJIIJIIIJ(Vector2 IIIJIIJJIIIJJJJIIJJJJJJJIJJIIIIJJIJJIIIJJIIIIJJ, Vector2 JIJIJJIJJIJIIIIJIIIJJIIIIIIJIJIIJJJIIIIJIIIIJJI)
		{
			return false;
		}

		public string IIIIIJIIIJJIJJJJIJIJIIJJIIJJJIJJIIJJIIIJJIIIIII(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		public void IJJIIIJIJIIJIIJIJIIJJIJJIIIJJJJIJIIJIJJIJIIIIJI(RawEncryptedVector2 JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		private float JJIIIIIJJIIJIJJJIIIJIJJIIJJIJIIIJIJIIIIJIJJIIJJ(int JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
			return 0f;
		}

		public static RawEncryptedVector2 IIJJJJIJJIJIJJIJJJIIIIIJJIIJIIIIJIIJIJJIIIJIJIJ(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return default;
		}

		public RawEncryptedVector2 IIIIIIJJIJJJJJIIJJIIIIJIIJJIIIJJJJIIIJJJIJIIJJJ()
		{
			return default;
		}

		public string IJJIIJIIJIIIJIJJIIIIJIJJIIIIJIJJIJJJIJIJJIJIIII()
		{
			return null;
		}
		public static ObscuredVector2 IIJIJJJJJIIJIJJJJJIIJIJJJIIJIJJJIJIIJIJJJIIJJJI(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}
		public static Vector2 IIJIIIJIIIIJIIIJIJJJJIJIIIJIIIJJIJIIIJIJIIIIJIJ(ObscuredVector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		private bool JJJJIIJJJIJIIIIJJJIIJIIJJIIJIIJIIJJJJIIJJIIIJIJ(Vector2 IIIJIIJJIIIJJJJIIJJJJJJJIJJIIIIJJIJJIIIJJIIIIJJ, Vector2 JIJIJJIJJIJIIIIJIIIJJIIIIIIJIJIIJJJIIIIJIIIIJJI)
		{
			return false;
		}
		public void IJIJJIJJIJJIJJIIIIIJIJJIJJIJJJJJJJIIIIJIJJJJJIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}

		private float JIIJIIJIJJJJJIIJIJIIJJJIIJIJIJJJJIIJIIJJJJIJIIJ(int JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
			return 0f;
		}
		public static implicit operator Vector2(ObscuredVector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}
		public static implicit operator ObscuredVector2(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public override int GetHashCode()
		{
			return 0;
		}

		private int IJJJJIIJJIJIJIJJIJIIJJJJJJJIJIJJJJIIJIIJIIJIIJJ(float JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
			return 0;
		}
	}
}
