using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace CodeStage.AntiCheat.ObscuredTypes
{
	[Serializable]
	[StructLayout((LayoutKind)0, Size = 8)]
	public struct ObscuredSByte : IEquatable<ObscuredSByte>, IFormattable
	{
		private static sbyte cryptoKey;

		private sbyte currentCryptoKey;

		private sbyte hiddenValue;

		private sbyte fakeValue;

		private bool inited;

		public sbyte IJIJIJJIJIJJJIIJIIIIJJJJIIJJIJJJIJIIJIJIIIJJIJI()
		{
			return 0;
		}
		public static sbyte IJIJJJJJJIIJIJJJJJIJIJJJIIJIIIIIIIIIJIJJIJIIIJJ(ObscuredSByte JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0;
		}
		public static implicit operator sbyte(ObscuredSByte JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0;
		}

		public bool JJIJIIIIIJIJJIIIJIIJJJIJJJIJJIJJJJJIJIIJIIIIJII(ObscuredSByte JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}
		public static implicit operator ObscuredSByte(sbyte JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		private sbyte IIIJJIJJJJJJJIIIJIIIJIJJIJJIJIIJJIIIIJJIJIJIJJJ()
		{
			return 0;
		}

		public bool Equals(ObscuredSByte JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public void JJIIJJIIIIIIJIJIJJIJIJJIJIJIIJJJIIJJIIIJJIIJJII()
		{
		}

		private ObscuredSByte(sbyte JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			currentCryptoKey = 0;
			hiddenValue = 0;
			fakeValue = 0;
			inited = false;
		}

		public void JJJIIJIJJJIIJJJJJIJJIJIIJJJIJJIIJIJJJIJJJIIJJJI(sbyte JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		public string IJJJIIIIIJJIIJJJJIJIIIJIJIJJIJIJJJIJJJIJIIJIIIJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public sbyte JJJJJJIIIJJIIIJJJJJJJJJJJIIJIJJIIIJIIIJIJJJJJII()
		{
			return 0;
		}
		public static ObscuredSByte JJIJIJIJJJJIIIJJJIJJJJJIJJJJJIIIJJJIIJIJJJJIIJJ(ObscuredSByte JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public string ToString(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public void JJJJJIIJJJJJIIJJJJJJJJIIJIIIJJIIJIJIIJIJIJIJJJI()
		{
		}

		public int JIJJIJIJJJJIJIJJJIIJIJIIJIJIIIIJIIIJJJJJJJJIIII()
		{
			return 0;
		}

		public string IJJJIIIIJJIJIIJIJIJJIIJJJJJIIIIJIIIIJIIJJJIIJJJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}
		public static ObscuredSByte JJJJIIJIIIJIJIIJIIIJJIJJJJIJIJIJJIJIIIIJJIIIIIJ(ObscuredSByte JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public bool JIIIIJJJJIIIIIIIIIJJIIIJJJJJIIJJJIJJIIJJIJIIJJI(ObscuredSByte JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		public void IJIIIIJIJJIIJIJJIJIIJIIIIIJIJJIIJJJIJJJJIIIJJJJ()
		{
		}

		public static void IJIJJJIJJIIIIIIIJIJIJJIIIIIIJIIIIIIJIIIJJJJJJIJ(sbyte JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}
		public static sbyte IIJIIIJIIIIJIIIJIJJJJIJIIIJIIIJJIJIIIJIJIIIIJIJ(ObscuredSByte JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0;
		}
		public static ObscuredSByte IIIJJIIIJIIJJIIIJJIJJJJIJJIIJJIIJJJJJIIJIJIIIJI(ObscuredSByte JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public override string ToString()
		{
			return null;
		}
		public static ObscuredSByte IIIIIIJJIJJIJIJIJJJIIIIIIIIJIIJIIJIJJJJJJJIIJJJ(ObscuredSByte JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}
		public static sbyte IIJIJJJIIIJIIIIIJJIIJJJIIJJJJJIJJIJJIIJIIIJIJII(ObscuredSByte JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0;
		}

		public string IJJIIJIIJIIIJIJJIIIIJIJJIIIIJIJJIJJJIJIJJIJIIII()
		{
			return null;
		}

		public void JJIIJIIIJJIIIJJJIIJJJIJIIJIJJIJJJIIIJJIIJJJIJIJ()
		{
		}

		public string IIJIJIIIIJJJJIJIJJIJJIIIJIIIIJIIIJJJJJJIIIIJJJJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		public static sbyte IIIJJJIJJJJIIIIJJIJIJIIJJJIIJJIIIIJJIIIJJIJJIII(sbyte JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0;
		}

		public static sbyte IIJIIIJIIJJIJJIJJJIJIIIJIJIJJIIIIJIIIJIJIIJIIII(sbyte JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, sbyte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0;
		}

		public bool JJIIJJJJIJIJIIJIJIIIIJIJIJIIJJIIIIJJIJJIJJJJJJI(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public string JJIJJIIJJIIJIIIIJIIJJJJIJIJJIIIIJIJIJIJIJIIIIJJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}
		public static ObscuredSByte IIJJJIIIJIIJIIJIIJIIJIJJIJJIJIIJIIJJJJJIJIJJJIJ(ObscuredSByte JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public static sbyte IIIJJJIJJJJIIIIJJIJIJIIJJJIIJJIIIIJJIIIJJIJJIII(sbyte JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, sbyte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0;
		}
		public static ObscuredSByte JJIJIJJIIJIIIIIJJIIIJJIIIJJJJJIJIJIIIJJIJIIIIJI(ObscuredSByte JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public override int GetHashCode()
		{
			return 0;
		}
	}
}
