using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace CodeStage.AntiCheat.ObscuredTypes
{
	[Serializable]
	[StructLayout((LayoutKind)0, Size = 12)]
	public struct ObscuredShort : IEquatable<ObscuredShort>, IFormattable
	{
		private static short cryptoKey;

		private short currentCryptoKey;

		private short hiddenValue;

		private short fakeValue;

		private bool inited;
		public static ObscuredShort JJIJIJIJJJJIIIJJJIJJJJJIJJJJJIIIJJJIIJIJJJJIIJJ(ObscuredShort JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		private short IIIJJIJJJJJJJIIIJIIIJIJJIJJIJIIJJIIIIJJIJIJIJJJ()
		{
			return 0;
		}

		public static short IIIJJJIJJJJIIIIJJIJIJIIJJJIIJJIIIIJJIIIJJIJJIII(short JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, short IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return 0;
		}

		public void JJIIJJIIIIIIJIJIJJIJIJJIJIJIIJJJIIJJIIIJJIIJJII()
		{
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public bool JIJIIJIIJJIJIJIJIIJIIIJIIJJIIJIJJJJJIJJJIIIJIIJ(ObscuredShort JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public void JIIJJIIJJIJJJJIJIIIJIJIJIIIIJJJJJJIIIIJIJIIIIJJ()
		{
		}

		public void JJJIIIJIJIJIJIIIIIIJIIIIJJIJIJJJJJIIJIIJIIJIJJI()
		{
		}

		public override string ToString()
		{
			return null;
		}

		public static short IIIJJJIJJJJIIIIJJIJIJIIJJJIIJJIIIIJJIIIJJIJJIII(short JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0;
		}

		public void JJJJJIIJJJJJIIJJJJJJJJIIJIIIJJIIJIJIIJIJIJIJJJI()
		{
		}

		private ObscuredShort(short JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			currentCryptoKey = 0;
			hiddenValue = 0;
			fakeValue = 0;
			inited = false;
		}

		public string IIJJJJIJIIJJIIIIIJJJJJJJIIJJIIIJIJJIJJJIIJJIIJI(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public static void IJIJJJIJJIIIIIIIJIJIJJIIIIIIJIIIIIIJIIIJJJJJJIJ(short JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}
		public static short IIJIIIJIIIIJIIIJIJJJJIJIIIJIIIJJIJIIIJIJIIIIJIJ(ObscuredShort JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0;
		}

		public bool Equals(ObscuredShort JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}
		public static implicit operator short(ObscuredShort JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return 0;
		}

		public static void IJJIIJIJJJJIIJJIIIJJJJJJIJJJIIIJIJJJJIJIIIJJJJJ(short JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public void JIJJIJIJJJJJJJIJJIJIIJJIIIJIJIJJJIJJJIIJJJIJJIJ()
		{
		}

		public override int GetHashCode()
		{
			return 0;
		}

		public static void JJIIIIJIJJJIJIJJIIJIJJJIIJIIJIIIIJIJIIJJJJIJIIJ(short JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public string IIIJIIIIIIJJJIJIIIJJIIJIJJIIJJJIIJJIIIJJJIIIJJJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public short JJJJJJIIIJJIIIJJJJJJJJJJJIIJIJJIIIJIIIJIJJJJJII()
		{
			return 0;
		}

		public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public string JJJJIJJIIJJIIIIJJJIIJJIJIIJJJJIJJJJJIIJIJJIJIII()
		{
			return null;
		}
		public static implicit operator ObscuredShort(short JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public void JJJIIJIJJJIIJJJJJIJJIJIIJJJIJJIIJIJJJIJJJIIJJJI(short JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}
		public static ObscuredShort JIJIIJIJJIIJJIJJIJIIIJJJIIIJJJJJJIIIIIJIJIIJIJI(ObscuredShort JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public string ToString(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public void JIIJIIIJJJJJIJJIJIIJJIJIJIIJIIIIJIJJJIJJIIJJIJI(short JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
		{
			return null;
		}

		public static void IJJJIIIJIIIJIIJJIIIIIIIJIJJJJJJJIJIJJJIJIIJIIJI(short JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}
		public static ObscuredShort IIIIIIJJIJJIJIJIJJJIIIIIIIIJIIJIIJIJJJJJJJIIJJJ(ObscuredShort JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}
		public static ObscuredShort IIIJJJIIIJJJIIJJJIIIJJJJJIJJJJIJJJIJJJJJJIIIJJI(short JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}
	}
}
