using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace CodeStage.AntiCheat.ObscuredTypes
{
	[Serializable]
	[StructLayout((LayoutKind)0, Size = 8)]
	public struct ObscuredChar : IEquatable<ObscuredChar>
	{
		private static char cryptoKey;

		private char currentCryptoKey;

		private char hiddenValue;

		private char fakeValue;

		private bool inited;

		public static char IJJIIIIJJJJJIIIJIIIIIIIJIJJIIJIIIIJJIJIJJIIIJJI(char JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return '\0';
		}

		public static void IJIJJJIJJIIIIIIIJIJIJJIIIIIIJIIIIIIJIIIJJJJJJIJ(char JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}
		public static ObscuredChar JJJJIJIJJIIIIIJIIIJIIIIIIJJJIIJIJIJJIJJJIIJJJII(ObscuredChar JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}
		public static ObscuredChar IIIIIIJJIJJIJIJIJJJIIIIIIIIJIIJIIJIJJJJJJJIIJJJ(ObscuredChar JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}

		public void JJJJJIIJJJJJIIJJJJJJJJIIJIIIJJIIJIJIIJIJIJIJJJI()
		{
		}

		private ObscuredChar(char JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			currentCryptoKey = '\0';
			hiddenValue = '\0';
			fakeValue = '\0';
			inited = false;
		}

		public string JJIJJIIJJIIJIIIIJIIJJJJIJIJJIIIIJIJIJIJIJIIIIJJ()
		{
			return null;
		}

		public bool Equals(ObscuredChar JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public char IJJIIIIIJJIJIJJIIJJJJJIIJJJIIIJIJJJJIJIJIIJIIJJ()
		{
			return '\0';
		}

		public void JJIIJJIIIIIIJIJIJJIJIJJIJIJIIJJJIIJJIIIJJIIJJII()
		{
		}

		public void JJIIJIIIJJIIIJJJIIJJJIJIIJIJJIJJJIIIJJIIJJJIJIJ()
		{
		}

		private char JJIIIJJJIIIIJJJIJJJJIJJJIIIJIIIIIJJIIIJJJIJIIJJ()
		{
			return '\0';
		}
		public static ObscuredChar JJIJIJIJJJJIIIJJJIJJJJJIJJJJJIIIJJJIIJIJJJJIIJJ(ObscuredChar JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
		{
			return default;
		}
		public static char IJIJIIIIIIJIJJJJJJJJJJIIJJIIIIJJIIJIJJJIIIJJJII(ObscuredChar JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return '\0';
		}

		private char IIIJJIIIIIIJIJJJIJIIJIIJJIJJIJIIIIIIIIIJJIJJJII()
		{
			return '\0';
		}

		public static char IIIJJJIJJJJIIIIJJIJIJIIJJJIIJJIIIIJJIIIJJIJJIII(char JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return '\0';
		}

		public int IJIIJJJJIJIIJJJJIIIJIJJJJJIJIIIJIJJIJIIJJJIJIJI()
		{
			return 0;
		}

		public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
		{
			return null;
		}

		public override int GetHashCode()
		{
			return 0;
		}
		public static implicit operator ObscuredChar(char JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public char IJIJJJJJJJJJIJJJJJJJJJJJIJIIIIIJIJJIIJIJIJIJIJI()
		{
			return '\0';
		}

		public static char IIIJJJIJJJJIIIIJJIJIJIIJJJIIJJIIIIJJIIIJJIJJIII(char JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, char IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
		{
			return '\0';
		}

		public void IIIIJIIIIIJJJIIJIJJJIIJJJJIJJIJIIJJJJJIJIIJJJJJ(char JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}
		public static ObscuredChar IJJJJIJIJIJIIJIJJJJIIJIJIIIIJJJIIIJJJIIIIIJJIIJ(char JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return default;
		}

		public static void JJJJIIIJJIIJIIJIJJIJJJIJIIJIJIJIIJIJJIJJIIIJJJI(char JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public static void JJIIIJIIIJJJIIIIJIIJJJJJIIIJIIJIJIIJJIJJJIIJIJJ(char JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
		{
		}

		public void JJJIIJIJJJIIJJJJJIJJIJIIJJJIJJIIJIJJJIJJJIIJJJI(char JIJIIJJJJJJJIJIJJJJIIJJIJIIIIJJJIIJIIIIJJIIIJII)
		{
		}

		public override string ToString()
		{
			return null;
		}

		private char IJIJJJIJJJIIIJJJIJIIIIIIIJIIIJJJIIJIJIIJJJIJJJJ()
		{
			return '\0';
		}

		public int IIJJIJIIIIIIJIJJJJJIIJIIJJIIJIIJIJJIJJIIIIIIJIJ()
		{
			return 0;
		}

		private char IIIJJIJJJJJJJIIIJIIIJIJJIJJIJIIJJIIIIJJIJIJIJJJ()
		{
			return '\0';
		}
		public static implicit operator char(ObscuredChar JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
			return '\0';
		}

		public bool IJIJIJJIIJJJIIJIIJJIIJJIJJJJIJJJJIJJJJJIIJIJIJI(ObscuredChar JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}

		public char JJJJJJIIIJJIIIJJJJJJJJJJJIIJIJJIIIJIIIJIJJJJJII()
		{
			return '\0';
		}

		public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
			return false;
		}
	}
}
