using UnityEngine;

public class AFKManager : MonoBehaviour
{
	public bool JIIIJJIJIJIIJIIJIIJJJJIJIJJIIJIJIIJIJIIIIJIIJJJ;

	public float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ;

	private float IJJIJIIJIIIIJJIIIJJJIIIJIIIIJJIIJIIJIIJJJJJJIII;

	private static AFKManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void IIIJJIJIIIIJIJIJJJJJIIJJIJIJIIIIIJJJIJIJJIJIIII()
	{
	}

	private void IJIJJJJJIJJIIJJJJJIJIJJIJJJJJJIJIIIIIIJJJJIIIIJ()
	{
	}

	private void IIJJIIJIIJIJIIIIJIJJJIIJIJIIJJIIJIIJJJJJIJJIJIJ()
	{
	}

	private void JIJJJIIIIIJIJJIIJIJIIIIJIJIIJIIIIJJJIIJJJIJJJIJ()
	{
	}

	private void IJIJIJIIJJIIIJJIJIIIJIJJIIJJJIIJJJJJIJJIIIJJIIJ()
	{
	}

	private void IJJJJJJIJJIIIIJIJIJJJIIIJJIIIIJJIJIIJIIIIJJJJIJ()
	{
	}

	private void JIIIJJIJIJJIJJJIIIIJJJIJIJIJIIIJJJJIJJIIIIJJIII()
	{
	}

	public static void IIIJIJJJJIIJIJIJIIIIJJJJJJJJJIJJIIJIIIJJJIJIJIJ()
	{
	}

	public static void IJIIJIJJJIIIIJIJJIIIIIJJJJJIJIJJIIIJIJIIIJIJIII()
	{
	}

	private void Awake()
	{
	}

	private void Update()
	{
	}

	private void JIJJIIJIIJJIIIIJIJIIIJIJJIIIIIJJJIIIJIIJJIIJJJI()
	{
	}

	private void JJIJIJJJIIIIJJJJJJJJJIJIIJIIIIJJIIJJIIIJIJIIJIJ()
	{
	}

	public static void IJJIIJJJIIIJJJIJIJJJJJJJIJIJJIIJIJIJIJIJIIIJJJI()
	{
	}

	public static void IIJIJJJIJIIJIJJIIIIIIJIJIIIJJIIIJJIIIIJIIJIJIIJ()
	{
	}

	public static void IIJIIJJIIIIIIJIIJIJIIIIJJIIJJJJJIJJJIIIJIIJJJJI(float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	private void JIIIJIIJJJJIJIJJJIIIIIJIJJIIIIJJJJJJJJIJIIIIJJI()
	{
	}
}
