using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class AndroidUpdateManager : MonoBehaviour
{
	private enum IIJIIJIJJIIIJJIIJJIJIJJIIIJIIIIIIIIJIIJJIJIJJIJ
	{
		FLEXIBLE = 0,
		IMMEDIATE = 1
	}

	private class IIIIIIIJIIJJJIJJJJJJIIIJIJJJJIIIIJIJIJJIIJIJIII : AndroidJavaProxy
	{
		public void IJIIIJJIIIJIIIIJIIJJIIJIIIJJIJIIIIIIJIIJJIJIIJJ()
		{
		}

		public void JJJJJIIIJJIIJJIIJJIJJIIIIJIJJIIIJJJJJIIJJJJJJJI(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI, bool JJJJIIJIJIJJIIJIJIIIIJIIIIIIIIJIIJIJJJJIIJJIJJJ, bool IIIIIIJIIJJJIJIJJIIIIJJIJIJIIIIJJIIJIJJIJIIIJJJ)
		{
		}

		public void JJJJIIIJIIIIJJIJJIJJIJIJIIIJIJJIIJIIJJJIIJIIIJI(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI, bool JJJJIIJIJIJJIIJIJIIIIJIIIIIIIIJIIJIJJJJIIJJIJJJ, bool IIIIIIJIIJJJIJIJJIIIIJJIJIJIIIIJJIIJIJJIJIIIJJJ)
		{
		}

		public void IJJIIJJJJJJIIIJIJJJJJIIIIIIJIIIJIJIJJJIJIIIIJIJ()
		{
		}

		public void JIJIIJIJIJIIJJJJJIJJIIIIJJIIJIIIIJJIJIIIJJIJJJI()
		{
		}

		public void JJJIJIIJIJJIJIJIJJJJJJIIJJIIJJIIIIIIJIIIJIJIIJI(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI, bool JJJJIIJIJIJJIIJIJIIIIJIIIIIIIIJIIJIJJJJIIJJIJJJ, bool IIIIIIJIIJJJIJIJJIIIIJJIJIJIIIIJJIIJIJJIJIIIJJJ)
		{
		}

		public void IJIIIJJJIIJJIIIJIIJIJJIIJIIJIIIIIJIJIIIIJIIJJII(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI, bool JJJJIIJIJIJJIIJIJIIIIJIIIIIIIIJIIJIJJJJIIJJIJJJ, bool IIIIIIJIIJJJIJIJJIIIIJJIJIJIIIIJJIIJIJJIJIIIJJJ)
		{
		}

		public void JJJIIIJJIJIIIJIIJIIJIIJIIIJIJJJIIJIIJIJIIJIIJII()
		{
		}

		public void IJIJIIJJJIJJIJJJIIJJIIIJJJJJIJJIJJJIJJIIIJIJIJI(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI, bool JJJJIIJIJIJJIIJIJIIIIJIIIIIIIIJIIJIJJJJIIJJIJJJ, bool IIIIIIJIIJJJIJIJJIIIIJJIJIJIIIIJJIIJIJJIJIIIJJJ)
		{
		}

		public void JJJIIIJJJIJIIIIJIIIJJIJIIIJJJJIJJJIIJJIJIIIIJII()
		{
		}

		public void IIJIIIJIIJIIJJJIJJIJIIJJJJIJIJIJIIJIJJIIIJJIIIJ()
		{
		}

		public void IJIJJJJIJJJJIIIJIIIIJJJJJJIIJJIJIJJJJJIJJJJIJJJ(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI, bool JJJJIIJIJIJJIIJIJIIIIJIIIIIIIIJIIJIJJJJIIJJIJJJ, bool IIIIIIJIIJJJIJIJJIIIIJJIJIJIIIIJJIIJIJJIJIIIJJJ)
		{
		}

		public void IJJJIJIJJIJIJJIJIIJJJJIJJJJJIIJJJJIJJJIIJJJIIIJ(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI, bool JJJJIIJIJIJJIIJIJIIIIJIIIIIIIIJIIJIJJJJIIJJIJJJ, bool IIIIIIJIIJJJIJIJJIIIIJJIJIJIIIIJJIIJIJJIJIIIJJJ)
		{
		}

		public IIIIIIIJIIJJJIJJJJJJIIIJIJJJJIIIIJIJIJJIIJIJIII()
			: base((string)null)
		{
		}

		public void IJIJJIIJJJIJIIJJIIIIIIIJIJIJJJJJJIIJJIIJJJIJJIJ()
		{
		}

		public void IIJIIIJIIJJJIIIJJIJIIJJJJIJIIIJIJJJIJIJIJIIJIJJ()
		{
		}

		public void JJIIJIJJIIIJIJIIJJJIJJIIJIIIIIJIIIJIJJIIJJJIJII(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI, bool JJJJIIJIJIJJIIJIJIIIIJIIIIIIIIJIIJIJJJJIIJJIJJJ, bool IIIIIIJIIJJJIJIJJIIIIJJIJIJIIIIJJIIJIJJIJIIIJJJ)
		{
		}

		public void IIIJJIJJIJIJIIJJJIJIJJJJJIJIIIIIJIJIIIJIIIJJJJI(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI, bool JJJJIIJIJIJJIIJIJIIIIJIIIIIIIIJIIJIJJJJIIJJIJJJ, bool IIIIIIJIIJJJIJIJJIIIIJJIJIJIIIIJJIIJIJJIJIIIJJJ)
		{
		}

		public void IJJIIJJIJJJJIIJJIJIJIJIIJJJIJJIIIIJIIJIIJIIIJII()
		{
		}
	}

	private static Action<int> JJJJJJIIIIIIIJIJIJIIIJJJIIJJIJJJJJIIJIJIJIJJIJI__BackingField;

	private static Action JJJJIJIJIJIJIJIJIJIIJIJJJJIJIIIIJJIIJJJIJIJJJJI__BackingField;

	private static AndroidUpdateManager IJIIIJIIIIIJIIIJIJJJJJIJJJIJIJJIJJIJJIJIJJIIJJI;

	public string JJJJJIJIIIIJIIIJIIJJIIIIIIJJJJIJIIIJIIIJJIIIJJJ;

	[SerializeField]
	private IIJIIJIJJIIIJJIIJJIJIJJIIIJIIIIIIIIJIIJJIJIJJIJ updateType;

	private AndroidJavaObject IJIIIJJJJJIIJIJJIJJJJJJIIJIJJJJJIIIJJJIIJIJJJII;

	private AndroidJavaObject IJIIJJJIJJJJIJJIIJJIIJJIIJJJIIJIJIJJJJJJIIJIJII;

	public static AndroidUpdateManager JIJJIJJJJIIJIIJJJJJJJJIJJJJJJIJJIJIIIIJIJJIJJJJ
	{
		get
		{
			return JJJJJJJIIJJJJIIJIJIIIIJIJIJJIJJIIJIIIIIIJJIJIII();
		}
		private set
		{
			IJJIJIIJJIJIJIJIIJJIIJJIJJJIJJIJIJJJJJJJIJIJIJI(value);
		}
	}

	public static event Action<int> JJJJJJIIIIIIIJIJIJIIIJJJIIJJIJJJJJIIJIJIJIJJIJI
	{
		add
		{
			IJJJIJIJJIJIJIJJJIIJJJJIIJJIJJJIJIJJIJJJIIJJIJJ(value);
		}
		remove
		{
			JJIIJIIIIJJIIIJIJIIIJIJIIIIJJIIIJIJIJJIIIJIIJII(value);
		}
	}

	public static event Action JJJJIJIJIJIJIJIJIJIIJIJJJJIJIIIIJJIIJJJIJIJJJJI
	{
		add
		{
			IJIJIIJIJJIJJJIJJIIJJJIJJIIJJJIJJIIIJJIJJIJIIJJ(value);
		}
		remove
		{
			IIIIJIJIJIJIJJJJJIJJIIIIJIJIJJJJIIIJJIIIJJJJJIJ(value);
		}
	}

	private static void IJJIJIIJJIJIJIJIIJJIIJJIJJJIJJIJIJJJJJJJIJIJIJI(AndroidUpdateManager JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static void IJJJJJIJJJJIIIJJIIIJIIJIJJJIJJJJJIIJIIJJJJJJIIJ(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static void JJIJJJJIJJJJIJIIIIJIJIJJJJIIJJJIIIIJJJIJIIIIIIJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJIIJJJJIJIJJJJJIIIIJJJJJIIIIJIJJIIIJIJIIJIIIJI()
	{
	}
	public static void JJJIIIIJIJIJJIJJJJIJIIIJIIIIJJJIIJJIIJJIJIJJIJI(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void Awake()
	{
	}

	private void JIJJIIIJJIJIIIIIJIIJIIIIJJJIJIIIIJJJJJJJJIIIIIJ()
	{
	}
	public static void IJIJJIJJJJJIJJJIJJJJIIJJIIIIIJIJJIIJIJIIIIJJJII(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void OnDestroy()
	{
	}
	public static void JJJIJJIJJIIIJIJIJJJJJJIJJIIJIJIIJIJIIIJJJJJIIJI(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JJIIJIIIIJJIIIJIJIIIJIJIIIIJJIIIJIJIJJIIIJIIJII(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void IJJJIJIJJIJIJIJJJIIJJJJIIJJIJJJIJIJJIJJJIIJJIJJ(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static void JJJJIJIJIIJIJJIIJIIIJJIJJIIIIIJIJJJIIIIJIJJIIJJ(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static AndroidUpdateManager JJJJJJJIIJJJJIIJIJIIIIJIJIJJIJJIIJIIIIIIJJIJIII()
	{
		return null;
	}
	public static AndroidUpdateManager IJIIIJJJIIJIJIJIJJIIIIJJIJJIIIJIJIIIIIIIJIIIIIJ()
	{
		return null;
	}

	private void IJJJJIIJIIJIIJJIJJIJIJIIJIIJJIJJJIJIIJJJJJJIIII()
	{
	}

	private AndroidJavaObject JIJJIIIJJJJJIJIIIJIIJJIIIJJIJIIIIIIJIIIIIIIJJJI()
	{
		return null;
	}

	public static void IJIJIIJIJJIJJJIJJIIJJJIJJIIJJJIJJIIIJJIJJIJIIJJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static void JJIIJJJIIJJJIJJIJIJIIJIIIIIIJIIIJJJJJIIJIIIIJJI(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static void IIIJIIJJJIIJJIIJJJJJIIIIIIIIJJIJJIIJJJJIIIJIJIJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void Start()
	{
	}
	public static void IIIJJJIIJIIJJIIIJJIJJIIJJJJJIJJIIIIJIJIIJIIJIII(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static void JJJIJJIJIJIIJJIJJIIJJIIJIIJIJJJIJJJIIIJIJIIIJIJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static void JJJIIJIJIJJIJIJJIIIJJJIJIIJIIJJJIIJIIIJJJJJJJII(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJJJJIJJJJJIIIJJJIJJIJIIIIJIIJIIIJIJJJJJIJIIJJJ()
	{
	}

	private AndroidJavaObject JIIJIIJIIIJIJIJIIIIIIJIIIIJJIJIJIJIIIJIJIJIIIJJ()
	{
		return null;
	}

	public void IIJJIJJJIJJJIIJJJJIIIJJIIIIJJJJJIJJJJJIIJJIIIJJ()
	{
	}
	public static void JIIJJJIIJJIJJIIJJJJIJIIIIJJJJIJIJJIIIIJJIJIJJII(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIJIIJIJJIIJIJJJJIIIIIIJIIIJJIIJJJIJJIIJJJIIIJ()
	{
	}
	private static void JIJIIJJJJJIJIIJIIJJIIIJJJIJJIIJIJIIJJJJJJJJJIJI(AndroidUpdateManager JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void IIIIJIJIJIJIJJJJJIJJIIIIJIJIJJJJIIIJJIIIJJJJJIJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
}
