using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class AndroidPermissions : MonoBehaviour
{
	public string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ;

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private bool IIJIIIJJIIIJIIJIJJJJJIJIIJIIJIJIJIJJIIJIJIJJIII()
	{
		return false;
	}

	private void IIIIJJIJIIJJJJJJJJIJIIJJJIIJJJIIJJIIJIJIIIIIIJI(string[] JJIIIJIJJIIIIJIJIIJIJIJIJIJJIIIIJJJIJIIJJIIIIIJ, IIIIJJJJIJJIIJIIJJJIJIIIIJJIIJIJIJJJIJIJJJJIJJJ.IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] IJIJJIIJJJJIJJIJJIJJJJJJJIIIIJIIJIIJIJIJIIIJJIJ)
	{
	}

	private void IIIJJJJIIIIIJIIJIIIIIJJIIJJIJJJIIJIIIIIIIJJIJIJ(IIIIJJJJJIJIIJIIIIIJIIJJJJJIJJJIJIIJJJIIIJJIIJJ JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
	{
	}

	private bool JJJJIIJJJIJJJJJJIJJJJIIJIIIIJJJIJIJIJIJIIIIIIIJ()
	{
		return false;
	}

	private void Start()
	{
	}

	private void JIIIJIJIJJIIIJIIJJJJIIIIIIIIJIJIJJIJIIJIJIIIIJI()
	{
	}

	private void IIIIJIJJIJIIIJIJIJIIJJIIJJIJJIJIIJJJIJIJIIJJJII()
	{
	}

	private void JJIIJIJJIJJIJIJIIJIJIIJIJJJIIJJJJJIIJJIJJJJJJJI(string[] JJIIIJIJJIIIIJIJIIJIJIJIJIJJIIIIJJJIJIIJJIIIIIJ, IIIIJJJJIJJIIJIIJJJIJIIIIJJIIJIJIJJJIJIJJJJIJJJ.IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] IJIJJIIJJJJIJJIJJIJJJJJJJIIIIJIIJIIJIJIJIIIJJIJ)
	{
	}

	private bool JIIIIJIIJIJIIIIJJIIIJJJIIIIJJJJJIIIJJJJJJIIJJJJ()
	{
		return false;
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void IIIIIJIIJJIIIJIJJIJIIIIIIJJJIIIJJIIIIJJJIJJIJJI()
	{
	}

	private void JJJJIIJIIIIIJJIIIIIIJJIIJIIIJIJIJJIIIJIIIIJJIIJ(string[] JJIIIJIJJIIIIJIJIIJIJIJIJIJJIIIIJJJIJIIJJIIIIIJ, IIIIJJJJIJJIIJIIJJJIJIIIIJJIIJIJIJJJIJIJJJJIJJJ.IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] IJIJJIIJJJJIJJIJJIJJJJJJJIIIIJIIJIIJIJIJIIIJJIJ)
	{
	}

	private void IIIJIJJJJJIIJJJIJIIIIIIJIIIJIIJIJIIIJJJJJJJIIJJ()
	{
	}

	private void IIJIIIIIJIIIIJIIIIJIJJJIJJIIIJIJIJJJIJJIJJIIIII(IIIIJJJJJIJIIJIIIIIJIIJJJJJIJJJIJIIJJJIIIJJIIJJ JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
	{
	}

	private void JJJJIIJIIJJJIIJIJJIIIJIJIIIJIJIJIJJIJIIIJIJJJJJ()
	{
	}
}
