using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;
using UnityEngine.Events;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class AndroidNativeFunctions : MonoBehaviour
{
	public delegate void IIIJJIIIIJJIJIJIIIIIJJIIJJIIIJJJJIJIJJJJJIJIIII();

	private class JJIIIJJJIJIIIJJIJIJIIIJJIJIIJIJIJIJJIIIJIJIJJIJ : AndroidJavaProxy
	{
		private UnityAction<IIIIJJJJJIJIIJIIIIIJIIJJJJJIJJJIJIIJJJIIIJJIIJJ> IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ;

		public void JJIJIIJIJJJIJJJIJJJIIJJJIIIJIIIIIJIJJIJIIJJIJJJ(AndroidJavaObject obj, int which)
		{
		}

		public void IIIJJJJJJIJIJIIIIJJJJJIJJJJIJJJIJIJJJJIIIIJJJII(AndroidJavaObject obj, int which)
		{
		}

		public void onClick(AndroidJavaObject obj, int which)
		{
		}

		public void IJIJIIJJIJJJJIIJJJIIIIIJJJJJIJIJJIJJJIJIJJJIJJJ(AndroidJavaObject obj, int which)
		{
		}

		public void IIJIIIJJIIIJIJIIJJIJIIJJJIIIIJIIJIJJJJIJIIIIIJI(AndroidJavaObject obj, int which)
		{
		}

		public void IJIJIIJIJJJJIIIJIIJJIJIIIIIIJIIIIJIJJJIIIJIJIJJ(AndroidJavaObject obj, int which)
		{
		}

		public void IJJIJJJIIIIJJJJIJIIIJJJJIJIJJJJIJIIJJJJIIJIJIIJ(AndroidJavaObject obj, int which)
		{
		}

		public void JJIJJIJJJIIJJIJJJJIJJJIJIJIIIIIIJIJIIIJJJJJIJII(AndroidJavaObject obj, int which)
		{
		}

		public void JJIIIIIIJJJJJIIJJJIJJIIIJJJJJIIIIJJIIIJIIIIJIJJ(AndroidJavaObject obj, int which)
		{
		}

		public JJIIIJJJIJIIIJJIJIJIIIJJIJIIJIJIJIJJIIIJIJIJJIJ(UnityAction<IIIIJJJJJIJIIJIIIIIJIIJJJJJIJJJIJIIJJJIIIJJIIJJ> IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ)
			: base((string)null)
		{
		}

		public void JJIIIIJJJIIJIJIJIJJIJJJJIIJJJIJJIIIIIIJJIJIJJJI(AndroidJavaObject obj, int which)
		{
		}

		public void IIJIIJIJJIJIIJIJJJIIIJIIIIIJJIJIJJIJJIIIIIJIJJI(AndroidJavaObject obj, int which)
		{
		}

		public void IJJJJJJJIIJJJIIIIJJJIJIJJJIIIJJJIJJJJIJJIIJJJIJ(AndroidJavaObject obj, int which)
		{
		}

		public void JIIIIJIIJJIJIJIIJJIIIJIIIIJIIIIIIIJIJJJIIIJJIJJ(AndroidJavaObject obj, int which)
		{
		}

		public void IJIIIJIIJJJJJJIJIJIJIJJJIIJJJIJIIJIIIIIJIJJJIJI(AndroidJavaObject obj, int which)
		{
		}

		public void JIJJIJIIIJJIJJIJIIIJJJJJIIJIJIJJJIJIIJJJIJIIJJI(AndroidJavaObject obj, int which)
		{
		}

		public void IJJIIIJJIIJJJIIIJJJJJIIIJJJIIJJJJJIIIJIJIIIIJII(AndroidJavaObject obj, int which)
		{
		}

		public void IJJIJIJJIIIIJIIJJJJJJIJIJIIIJIIJIJJIIJIJJJIJIIJ(AndroidJavaObject obj, int which)
		{
		}

		public void JIJJJIJIJIIIJJJJIIJJIJIJJJIIIJJJIJIJIJJIIIIIJJI(AndroidJavaObject obj, int which)
		{
		}
	}

	private class JJJIJJJIJJIIIIJJJIJJJJIIJIIJJIIIJIJIIJIIIJJIIJI : AndroidJavaProxy
	{
		private UnityAction<IIIIJJJJJIJIIJIIIIIJIIJJJJJIJJJIJIIJJJIIIJJIIJJ, string> IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ;

		private AndroidJavaObject JJIJIIJIJIJIIIIJIJJJJJIJJIIJIJIIIIIJJIIJJIIJIII;

		public void JIIIIJIIJJIJIJIIJJIIIJIIIIJIIIIIIIJIJJJIIIJJIJJ(AndroidJavaObject obj, int which)
		{
		}

		public void IIIIJIIIJIIJIJJIIIIIJJIIJJIJJJIIJIJJIIIIJIIIJIJ(AndroidJavaObject obj, int which)
		{
		}

		public void IIJIIJIJJIJIIJIJJJIIIJIIIIIJJIJIJJIJJIIIIIJIJJI(AndroidJavaObject obj, int which)
		{
		}

		public void IJJIIIJJIIJJJIIIJJJJJIIIJJJIIJJJJJIIIJIJIIIIJII(AndroidJavaObject obj, int which)
		{
		}

		public void JJIIIIJJJIIJIJIJIJJIJJJJIIJJJIJJIIIIIIJJIJIJJJI(AndroidJavaObject obj, int which)
		{
		}

		public void IJJJJJJJIIJJJIIIIJJJIJIJJJIIIJJJIJJJJIJJIIJJJIJ(AndroidJavaObject obj, int which)
		{
		}

		public void IJJIJIJJIIIIJIIJJJJJJIJIJIIIJIIJIJJIIJIJJJIJIIJ(AndroidJavaObject obj, int which)
		{
		}

		public void IJIJIIJJIJJJJIIJJJIIIIIJJJJJIJIJJIJJJIJIJJJIJJJ(AndroidJavaObject obj, int which)
		{
		}

		public JJJIJJJIJJIIIIJJJIJJJJIIJIIJJIIIJIJIIJIIIJJIIJI(UnityAction<IIIIJJJJJIJIIJIIIIIJIIJJJJJIJJJIJIIJJJIIIJJIIJJ, string> IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, AndroidJavaObject IIIJJJJIJJIIJJJIIIIJJIIJIIIJIIIIJJJJIIJIIIJIIJI)
			: base((string)null)
		{
		}

		public void IIIJJJJJJIJIJIIIIJJJJJIJJJJIJJJIJIJJJJIIIIJJJII(AndroidJavaObject obj, int which)
		{
		}

		public void JJIJIIJIJJJIJJJIJJJIIJJJIIIJIIIIIJIJJIJIIJJIJJJ(AndroidJavaObject obj, int which)
		{
		}

		public void IJIIIJIIJJJJJJIJIJIJIJJJIIJJJIJIIJIIIIIJIJJJIJI(AndroidJavaObject obj, int which)
		{
		}

		public void JIIIJIJJIJIJIIIIJIJJIJIJJJJIJIJIIIJJJJJJJJIIIJI(AndroidJavaObject obj, int which)
		{
		}

		public void JJIIIIIIJJJJJIIJJJIJJIIIJJJJJIIIIJJIIIJIIIIJIJJ(AndroidJavaObject obj, int which)
		{
		}

		public void IJIJIIJIJJJJIIIJIIJJIJIIIIIIJIIIIJIJJJIIIJIJIJJ(AndroidJavaObject obj, int which)
		{
		}

		public void IJJIJJJIIIIJJJJIJIIIJJJJIJIJJJJIJIIJJJJIIJIJIIJ(AndroidJavaObject obj, int which)
		{
		}

		public void IIIJJIJIJJIJJJJJJIIIIJIIIIJIIIIIJJIIJIJJIIIJJIJ(AndroidJavaObject obj, int which)
		{
		}

		public void JIJJJIJIJIIIJJJJIIJJIJIJJJIIIJJJIJIJIJJIIIIIJJI(AndroidJavaObject obj, int which)
		{
		}

		public void IIJIIIJJIIIJIJIIJJIJIIJJJIIIIJIIJIJJJJIJIIIIIJI(AndroidJavaObject obj, int which)
		{
		}

		public void JIJJIJIIIJJIJJIJIIIJJJJJIIJIJIJJJIJIIJJJIJIIJJI(AndroidJavaObject obj, int which)
		{
		}

		public void JJIJJIJJJIIJJIJJJJIJJJIJIJIIIIIIJIJIIIJJJJJIJII(AndroidJavaObject obj, int which)
		{
		}

		public void onClick(AndroidJavaObject obj, int which)
		{
		}
	}

	private class IIJJIIJJIJJJJJIIIJIIJIJJIIJJIJJIIJJJJIJIIJJJJII : AndroidJavaProxy
	{
		private string[] JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ;

		private Action<string> IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ;

		public void IIJIIJIJJIJIIJIJJJIIIJIIIIIJJIJIJJIJJIIIIIJIJJI(AndroidJavaObject obj, int which)
		{
		}

		public void IJIJIIJIJJJJIIIJIIJJIJIIIIIIJIIIIJIJJJIIIJIJIJJ(AndroidJavaObject obj, int which)
		{
		}

		public void JJIIIIJJJIIJIJIJIJJIJJJJIIJJJIJJIIIIIIJJIJIJJJI(AndroidJavaObject obj, int which)
		{
		}

		public void JJIIIIIIJJJJJIIJJJIJJIIIJJJJJIIIIJJIIIJIIIIJIJJ(AndroidJavaObject obj, int which)
		{
		}

		public void IJIIIJIIJJJJJJIJIJIJIJJJIIJJJIJIIJIIIIIJIJJJIJI(AndroidJavaObject obj, int which)
		{
		}

		public void JIJJIJIIIJJIJJIJIIIJJJJJIIJIJIJJJIJIIJJJIJIIJJI(AndroidJavaObject obj, int which)
		{
		}

		public void IJJIIIJJIIJJJIIIJJJJJIIIJJJIIJJJJJIIIJIJIIIIJII(AndroidJavaObject obj, int which)
		{
		}

		public void JJIJIIJIJJJIJJJIJJJIIJJJIIIJIIIIIJIJJIJIIJJIJJJ(AndroidJavaObject obj, int which)
		{
		}

		public void IIIJJJJJJIJIJIIIIJJJJJIJJJJIJJJIJIJJJJIIIIJJJII(AndroidJavaObject obj, int which)
		{
		}

		public void IJJIJIJJIIIIJIIJJJJJJIJIJIIIJIIJIJJIIJIJJJIJIIJ(AndroidJavaObject obj, int which)
		{
		}

		public void onClick(AndroidJavaObject obj, int which)
		{
		}

		public void IJJJJJJJIIJJJIIIIJJJIJIJJJIIIJJJIJJJJIJJIIJJJIJ(AndroidJavaObject obj, int which)
		{
		}

		public void JIIIIJIIJJIJIJIIJJIIIJIIIIJIIIIIIIJIJJJIIIJJIJJ(AndroidJavaObject obj, int which)
		{
		}

		public void JJIJJIJJJIIJJIJJJJIJJJIJIJIIIIIIJIJIIIJJJJJIJII(AndroidJavaObject obj, int which)
		{
		}

		public void IJIJIIJJIJJJJIIJJJIIIIIJJJJJIJIJJIJJJIJIJJJIJJJ(AndroidJavaObject obj, int which)
		{
		}

		public void IJJIJJJIIIIJJJJIJIIIJJJJIJIJJJJIJIIJJJJIIJIJIIJ(AndroidJavaObject obj, int which)
		{
		}

		public IIJJIIJJIJJJJJIIIJIIJIJJIIJJIJJIIJJJJIJIIJJJJII(Action<string> JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII, string[] IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ)
			: base((string)null)
		{
		}

		public void JIJJJIJIJIIIJJJJIIJJIJIJJJIIIJJJIJIJIJJIIIIIJJI(AndroidJavaObject obj, int which)
		{
		}
	}

	private sealed class IIIJJIJJIJIIIIIIIIIIIIIIJIJJJIJJJJIJIJJJIJIIIIJ
	{
		public string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ;

		public string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII;

		public string JJJIJIJIJIIJJJJIJIIJIIIJJJIJIIJIJJIJIIJJIIIIIJJ;

		public UnityAction<IIIIJJJJJIJIIJIIIIIJIIJJJJJIJJJIJIIJJJIIIJJIIJJ> IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ;

		public string JJIIJJJJJJJIJJIJIIIJIIJIJJIIIIIIJJJIJJIIJJIIJII;

		public string IIIIJJIJIJJJJIJJIJIIIJIIIIJIIJIJIJIIJJIIJJJIIIJ;

		internal void JIIJJJIIIJJIJJJIIJJJJIJIIJJJIIIIIIJIJIJJJIIJIJJ()
		{
		}

		internal void JJIJIJJJJIIJJIIJIIJIIJIJIJIIJJJJIJIIJJIJJJJJIIJ()
		{
		}

		internal void JJIIIJJIJJJJIJIJIIIIIIIJJJJJIIJIIIIJIIJJJIJJIJI()
		{
		}

		internal void IJIJJJJIJJIIJIJIJIIJIJIIJJJJIJJJJIIIJIJJJIJJJJJ()
		{
		}

		internal void JIJJJIIIJIIJIIJIJJIJIIJJJJJIJIJIJJJJIJJIJIIJIJI()
		{
		}

		internal void JIIJIIIJIJIJJJIIIJJIIJIJJIIJJIJJJJIIJJIJJIIIIJI()
		{
		}

		internal void JIIIIJIIIIIJJJJJJIJJJIJIIJIJJJJJIIJJJIIJIIJJJIJ()
		{
		}

		internal void JJIIIJJJIJJIIJJIIJIJIJJJIIJJIJJJJIJJJJJIIIJJIJJ()
		{
		}

		internal void IJJIJJJJIJIIJIJJJJIIIIIIIJJIIIIJJJJJJJJJIJIJJJJ()
		{
		}

		internal void IJJJJJIIJIIJJIIIIIJIIJIIJJIIIJIJJIIIJIJJJIJIJIJ()
		{
		}

		internal void JJIJIJJIIJJJIJJJIJIJJIJIJJIJJIIJIJJIIIJIIJIIIJJ()
		{
		}

		internal void JIJIJIJIJIIJIJIJJIIIJJIJIIJJJIJJJJIIIIIJJIJIJJI()
		{
		}

		internal void JIIIIIIIIIIJJIJJIIJIIJIIJIJIJIIJIJIJIIJIIIIIIIJ()
		{
		}

		internal void JIJIJJIJJIIIJIIJIIIIJJJJIIJJIJIIJJIIJIIJIIIIJJI()
		{
		}
	}

	private sealed class IJJIIIJIJIIIIIIJIIIJIIJIIJIJJIIIJJJIJIJJIIIJJIJ
	{
		public string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI;

		public string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ;

		public string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII;

		public string JJJIJIJIJIIJJJJIJIIJIIIJJJIJIIJIJJIJIIJJIIIIIJJ;

		public UnityAction<IIIIJJJJJIJIIJIIIIIJIIJJJJJIJJJIJIIJJJIIIJJIIJJ, string> IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ;

		public string JJIIJJJJJJJIJJIJIIIJIIJIJJIIIIIIJJJIJJIIJJIIJII;

		internal void JJJJIIJJIJIJJIJIIIJJIJJJIIJJJJIIJJIJJIJIJJJJIIJ()
		{
		}

		internal void IIIIIJIJIJJIJIIJIIIIJJJIIJJIIJJIIJIJJIJIJJJJJJI()
		{
		}

		internal void JJJJIJJJJJIJIJJIJJIIIIIJIJJJJJJIIIIJIIIIJIJJIIJ()
		{
		}

		internal void JIJJJJIIJIJJJIJJJJJJJIJIJJIIIIIJJIJJJJJIJIJIJJJ()
		{
		}

		internal void IJJIJJIJIJJJJJIIJJJJJIIIJJJJIJIJIIJJJJIIIIJIIJI()
		{
		}

		internal void IIIIJIIJJJIJIIIJIJJIIIJIJIIIJJJIJJIIJIJJIJJJJIJ()
		{
		}

		internal void JIJJJJIJIIIJJIJIJJIJJIIIJJJIJIJJJJJIJIIJJJIIIJJ()
		{
		}

		internal void JIJIIIIJIIIIJIJJIJJIJIJIIJIIJIJIJIIJJIJJJIIJJII()
		{
		}

		internal void JIJJIJIIJIJJIIIJIJIIIJJJJIJIIJJIIIIIIJIJIIJIJJI()
		{
		}

		internal void JJIIJIJJJJIJJJJJIJIIIIJJIJIJIIJIJJIIJIIJIJJIJII()
		{
		}

		internal void IIJJIIIJJJIJIJIJJIJJJJIJJIJJJIIJJIIIIJIIIJIJJIJ()
		{
		}

		internal void IJJJIJIIIIIIIJIJIJIJJJJIJIJIJJIJJIJJJJIIIIJIJJJ()
		{
		}
	}

	private sealed class IJJIJJJIIIIJJIIJIIIIJJJJJIJJJIIJJIJJIIJIIJIIJJI
	{
		public string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII;

		public string[] JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ;

		public Action<string> IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ;

		internal void JIIIIJJJJIJIJIIJIIIJIIJJIIIJJJJIJJJJIIJIJIIIIIJ()
		{
		}

		internal void JJIJJIJJJJJIJJIIIJIIJJIJIJIIIJIJIIJJJIIJJIJJIJI()
		{
		}

		internal void IIIJJIJIJJIIIJIIIIJJIIJIJJJIJJIJIIIIIIJJIIIJIJJ()
		{
		}

		internal void IJIJIIJIIIJJJJIIJJJJJJIJIIJJJJJJIJIJJJIJJIIIJJI()
		{
		}

		internal void IJJJJJJJIIJJIJJIIIJJJIIJIIJJIIIJIIJJJIIJJJIIIIJ()
		{
		}

		internal void IIJJJIIIIJIIIIJJIJJIIIIJIJIIJIIIJIJIJIJIIIIIIIJ()
		{
		}

		internal void JIIIJIIJJIJJJIIIJJIIIIJJIJIJIIIIIJIIJJIJJIIJIJJ()
		{
		}

		internal void JJJJIIJJIIJIIJJIJJIJJIJJIIIIIIIJJJIIJIJIJIJIIIJ()
		{
		}

		internal void IIJJIIIIIIJJJJIJIIIJIJJIIJIJIIJJIIIIJIJJJJIJJIJ()
		{
		}

		internal void JJIIJIIJJIIJIJIIIIIIIIJIIIJJJIJIJIIJJIIJJJJJJIJ()
		{
		}

		internal void JJJIIJJJJJIJIJIIJIJJIJJJJJJIJJJJIIJIJJJIJIJJIIJ()
		{
		}

		internal void JIJJJJJJJIIIJJJJJJJJIJIIIJIJIIIIJJIIIIJIJJIJJIJ()
		{
		}

		internal void IIIJJJIIIJJIJJIIJIJIJIIJJIJIJIIJJJJJJJIJJIJJJIJ()
		{
		}

		internal void IJJIIJIIJIJIIIJIJJJJIIJIIJJIJIJIIJJJJJJIJJIIIII()
		{
		}

		internal void JJIIJJIIIJIIIJJJJJJIIIIIJIJJIIJJJJIJJJJJJJIJJIJ()
		{
		}

		internal void IIIJJJJJIJJIJJIJJIIJIIJIIIIJJIJJIIJIJIJJIIIIIII()
		{
		}
	}

	private sealed class JJJIJIJIJIIIIIJIIJIJIIIJIIIJJJJIJIIIJJJIJJIJIIJ
	{
		public string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ;

		public bool JJIIIIIJJIJIJJJIIIJJJIIIJIJIJJIJJIJJJJJIJJIIIIJ;

		internal void IIIIJJIIJIJIJIJJJIJJIJJJJJJJIIJJIJJIJIIJIJIIJII()
		{
		}

		internal void IJIJIIJIJJJIJJIIIIIJJJJIIJIIIJIIJJJIIJIIJJIIIIJ()
		{
		}

		internal void JIJIIIJIJIJIJIJIJJJJIJIJJIJIIIJJJIIJJIJJJJJIJJJ()
		{
		}

		internal void IJJJJIIJIIIIIJJIJIIJJJIJJIJJJIIIJIIJJIIJIJJJIJI()
		{
		}

		internal void IJIIJJJJIIJJJIIJJIJJJJJJIIJJIIJJIIJJIJIIIIJJIJI()
		{
		}

		internal void JIJIJJIJIIIIIJIJIIIJIJIIJIIIJIIJIIJJIJIIJIIJJII()
		{
		}

		internal void JIIIJIIJIIJIJIJJIIIJIJIJJJIIIIJIIIJIJJIJJJJJIII()
		{
		}

		internal void JJIIJJIIJIIIJJIJIJJJIJJJIJJIIIJJJIIJIIIIJJIJJIJ()
		{
		}

		internal void JJIIJJIIJJIJIJIIJIJIIJJIIJJIJJJIIJJJJJIJIIIJJJI()
		{
		}

		internal void IIJJIJIJIIJJJJJIIIIIJIJJJIIIIIIIJIJJJIJIIJIIJJJ()
		{
		}

		internal void JIJJIJJIIJIIIJIIJJJIJJIIIJIIIJIIJJIIIJJJJJIIJJI()
		{
		}

		internal void IIJIJIJIJJJJJIIJIIJIJIIJIJJJJIIIIJJJJJJIIJIJJII()
		{
		}

		internal void IIJIJJIJIIIIJJJIJJJJJIIIJJIIJJIJJJIJJIJIJIIIJJJ()
		{
		}

		internal void IJJIJIJJJJIJIIJJJJIIJIJIJIIIIIJJIJJJJJIJJIIJIII()
		{
		}
	}

	private sealed class IJIJJIIIIIIJJJIJIIIIJJJJJIIJIJJIJIIIJJIJJIIJJIJ
	{
		public string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ;

		public string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII;

		internal void IJIIJIIJIIJJIIJIJIJJJJIJIJIJJIJJIIIIIIJJIJJIIIJ()
		{
		}

		internal void JJIIJJIJIIIJJIJIJJIIIJIJJJIIJIIJJIIIIJJJJJIJIJI()
		{
		}

		internal void IJIIJJIJIJJJJIJIJJIIIIJJIJJIJJJIJJIIIIIJIJJJJII()
		{
		}

		internal void IIIIIJIJIIIIIJIJJJIJJIJIIIJIIIIJJIIIJIIIIJJIJII()
		{
		}

		internal void IIJJIJIJJJJJIJJIIIIIJIIIIJIIJJJJIIJIIIIIJIIIIIJ()
		{
		}

		internal void JJIJJIIIIJIJJIJJIIJJIIJIJJIJJIIJIIJIJJIJJJJIIII()
		{
		}

		internal void IIIIJIJIIJIIIIJJIIJJIJIJIIIJJJIIJIIIIJJJJJIIIJJ()
		{
		}

		internal void JJIIJIIIJIIJIIIJJJJJIIIJIJIJJIIIJIJJIIJJIJIIJIJ()
		{
		}

		internal void JJJJJIIIIJIJIJJIJJJJJIJJJIIJIIIJJJIIIIJJIJJIJII()
		{
		}

		internal void JJJIJIIIJIJIIJJJIJJJIIIIIJJJIIJIJIIJJIIJJJIJIJI()
		{
		}

		internal void IJIIJJJIIIIIIIJIJIJIJIIJIIJJJIJJJJJIJJIJJIJJIJI()
		{
		}
	}

	private static bool IIIJIJIIJJJJJIIIJJJIJIJIJIIIJJJJJJIIIJIIIIJIJJI;

	private static AndroidNativeFunctions JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private static AndroidJavaObject JJIJIIJIIIIIJIJIIJIJJJJIIJIIIJJJJJJIJIJJJJIIJJJ;

	private static AndroidJavaObject IJIIIJJJJJIIJIJJIJJJJJJIIJIJJJJJIIIJJJIIJIJJJII;

	public static AndroidJavaObject IJJIIIIIJJJJJIJIIJJIJIIIIJIIIIJIJJJIJIJJIIJJJJI => IIIJIIIJIIJJIJJJJIIJJIJJIJIIIJJJIIJJJJIIIJIJIJI();

	public static void JJIJJJIJIJIIIIIIIJIIJIIJJJIIJIIIIIIJJIJJJJIJJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string JJJIJIJIJIIJJJJIJIIJIIIJJJIJIIJIJJIJIIJJIIIIIJJ, string JJIIJJJJJJJIJJIJIIIJIIJIJJIIIIIIJJJIJJIIJJIIJII, UnityAction<IIIIJJJJJIJIIJIIIIIJIIJJJJJIJJJIJIIJJJIIIJJIIJJ, string> IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ)
	{
	}

	public static IJJIJIIIIJIJJJIJJIIJIIJIJIJIIJIIIIJJIJJIJIJIIJI IIJIIJIJIIIIIIIIIJIIIIJIIJJIIJJJJIJJIJIIIJIJIJJ()
	{
		return null;
	}

	public static string IJJJIJJJIIIJIIJIJJJIJIIJIJJJJJJJJJJJJIJJIJIIIIJ()
	{
		return null;
	}

	public static bool IJJJJJIIJIIJJIJJIJIJJIJIIIIIIJJJIIIIIIJJIIJIIJI(string JIJIIIJIIJJJJIJJIIJJIJIIJJJIIJIJIJIIJIIIIJIIIJJ)
	{
		return false;
	}

	public static string JJIIIIIJJJJJIJIJJJIJJIJIJIJIIIJIIIIJJIIJJJJJJII()
	{
		return null;
	}

	public static List<IIIIIJJIJIIJIIIJJIIIIJJIJIIIJJJIJIJJJJIJJJJIJIJ> JJJIJJJJIIIIJIIJIIIJIIIJJJJIIJIIJIIIIJIJJIJJJJI()
	{
		return null;
	}

	public static string JIIJIJJJIIIIIIJJIIIIJIIJJIJJIJJJJJIJJJJJJIIJJII()
	{
		return null;
	}

	public static void IIJJJJJIJJJIIJJJJIIJJJIIIJJIJIJIJJIIJIIJIJIIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JJJIJIJJIIIJIJJIJIJJIJJJIIIJIIIIJJJJIJIIIJJIIIJ, string IJJIJIJJJJIJIJIJJIJJIJIIJJIIIIJIIIJIJIJJIIIIJIJ)
	{
	}

	public static string JIJIIJJIJJIIIIJJIJJIJJJIJIJJJIIJJJJJJJIIJJJJJJJ()
	{
		return null;
	}

	public static AndroidJavaObject IIIJIIIJIIJJIJJJJIIJJIJJIJIIIJJJIIJJJJIIIJIJIJI()
	{
		return null;
	}

	public static string[] IIJJJJJIIIJJJJJJJIIIIJJJIIJJJJIIIIIIJIIJIJJIIJJ()
	{
		return null;
	}

	public static bool IJIJIJIIIJJIIIIIIIIIJIJJJIIIIIJIIIJIJIIJJJJJIJI()
	{
		return false;
	}

	public static bool JIJIJIJJIIJJIIIJJIIJJJJIIJJIIIIJIJJIJIIIJJJIIIJ()
	{
		return false;
	}

	public static void IIIIIJJJJJJJJIIJJJIJIIJJIIIJJIIIIIJJIJJJIJJIJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JJJIJIJJIIIJIJJIJIJJIJJJIIIJIIIIJJJJIJIIIJJIIIJ, string IIIJJIJJJIJIIIJIIIJJIIIJJJIJIIIJIJIJIJJJJJJIJIJ)
	{
	}

	public static List<IIIIIJJIJIIJIIIJJIIIIJJIJIIIJJJIJIJJJJIJJJJIJIJ> IIIJJJJJJIIIIIIJJIJIIJJIJJJJJIJIIJIIIIIIJIIIIJI()
	{
		return null;
	}

	public static void IIIIIIIJIIJJIJJIIIJJJIJIIJJJIIJJIIIJJIJJIJJJJIJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII)
	{
	}

	public static void IIIIIIIJIJIJJJIJIIIJIJIIIIJJIJIJJJJIIJJJJJJJJII(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IJIIIJJJIIIJIIIJJIJJIIJIJIJIJIIIJIJIIJJJIJJIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JJJIJIJJIIIJIJJIJIJJIJJJIIIJIIIIJJJJIJIIIJJIIIJ, string IIIJJIJJJIJIIIJIIIJJIIIJJJIJIIIJIJIJIJJJJJJIJIJ, Texture2D IJJIIJIIJJIIJIIIIJIJIJJJIIIIJJIIJIJJIJIJIJJIIJI)
	{
	}

	public static string IIJJJIJJJJJJIJJJJJIJIJIJJIIIIIIIJIJJJIIJIJIIJJJ()
	{
		return null;
	}

	public static void JIJJIIIJIIIJJIIJIJIIIIJIIJJJJJJJIJJIIJIJJJJJJIJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static bool JJIIJJJJJIIIJIJJJJIIJIJJJJJIJIIIJIJJIJJJJIJIJJI()
	{
		return false;
	}

	public static IIIIIJJIJIIJIIIJJIIIIJJIJIIIJJJIJIJJJJIJJJJIJIJ JIJIJJJIIJIJIJJJIIJIIJJJJIJIIJJJJJJIIIJIJJIJJIJ(string JIJIIIJIIJJJJIJJIIJJIJIIJJJIIJIJIJIIJIIIIJIIIJJ)
	{
		return null;
	}

	public static void IJIIIIJJJIIIJJJIIJJJIIJIJIIJJJJIJIJIIJJJJIIJIJI()
	{
	}

	public static void JJIIIIIIJIIJIJIIIJJJJIIJIIJJJJJJIIIIIJJIJIJJIIJ(string JIJIIIJIIJJJJIJJIIJJIJIIJJJIIJIJIJIIJIIIIJIIIJJ)
	{
	}

	public static string JJIJJJIJJIJJJIJJIIIIJIJIIIJIIIJIIIJJIIJIJJIIIJI()
	{
		return null;
	}
	public static AndroidJavaObject IJJIJJIJIJIIJIIIIIJIJIJIJIJIIJIJJIIJJJIJIIIJIJI()
	{
		return null;
	}

	public static List<IIIIIJJIJIIJIIIJJIIIIJJIJIIIJJJIJIJJJJIJJJJIJIJ> IJJIJJIIJJJJIIJJJJJJIIIIIIJJIIJJJJIJJIJIJJJIJJJ()
	{
		return null;
	}

	public static string IIJIJIIIJIJJIJJIIIJJJJJJIJIJJIIJIIJJIJIJJIIJJIJ()
	{
		return null;
	}

	public static void IIIIIIIJIJIJJJIJIIIJIJIIIIJJIJIJJJJIIJJJJJJJJII(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ, bool JJIIIIIJJIJIJJJIIIJJJIIIJIJIJJIJJIJJJJJIJJIIIIJ)
	{
	}

	public static bool IIJJIJJIJIJJJIJIJJIIJIIJIJIIJIIIIIIJJIIIIIJJIJJ()
	{
		return false;
	}

	public static string IJJIIIIJIJJJJIJIIJIJJIIJIJIJIIIJIJJIIIJJJIJIJIJ()
	{
		return null;
	}
	public static AndroidJavaObject JIJJJJIJJIIIIJJJIIJIJJJIIIJIIIIJJJIIJIJJJIIIIJI()
	{
		return null;
	}

	public static bool IIJJJJJIJJJJIJIJJIJJJJJJIJJIJIIIJIIIJJIJJJJJIIJ(string IIJIJJJJIJJIJJJIJIIIJIJJIJIJIIJIJIIIJIJIIIIIIJI, string JJJJIIJIIIIJIJIJJJJJIIJJIIJJIJJJJJJJIIJIJJJIIIJ, string IJIJIJIJIIIJIIIIJJIIJJJJIIIJIJJIIJIIJJIIJJIIIJI)
	{
		return false;
	}

	public static string IJIIIJIIIJIJIJJJJIJJIIIJJIJIIJJIJJJJIIIIIJJJJJJ()
	{
		return null;
	}

	public static void JIIIIJIIIJJJIIIJJJJIJIIIIJIIJIJIIJIJJIJIIIIJJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JJJIJIJJIIIJIJJIJIJJIJJJIIIJIIIIJJJJIJIIIJJIIIJ, string IIIJJIJJJIJIIIJIIIJJIIIJJJIJIIIJIJIJIJJJJJJIJIJ, string JIIJIJIJJIJIJIIJIJIIIJIIJJJJIIJIJIJIJIJIJJJJJJJ)
	{
	}

	public static string JIJIJIJJJJJIJJIJJIJJJIJJJIIIIJIJIJJJIJJJIIIIJJJ(string JIJIIIJIIJJJJIJJIIJJIJIIJJJIIJIJIJIIJIIIIJIIIJJ)
	{
		return null;
	}

	public static int JJJIIIJIIJJIJJIIJJIIJIJIJIJJIIJJIJIIIIIJIJIJIII()
	{
		return 0;
	}

	public static bool JJIIJJIIJJJJIJJIIJJIIJJJIIJIJIJJJIJJJIJJJJIJIII()
	{
		return false;
	}

	public static int IJIIIJJJJJIJIIIIJJJJIIIIJJIJIJIJIIIIJJIIJIJIIJJ()
	{
		return 0;
	}

	public static void JIJJIIIJIIIJJIIJIJIIIIJIIJJJJJJJIJJIIJIJJJJJJIJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII)
	{
	}

	public static string JIJIJJIIJIJIJIJJIJIJIJJIJIIJIJIIIJIIJJIJJJIIIJI(string JIJIIIJIIJJJJIJJIIJJIJIIJJJIIJIJIJIIJIIIIJIIIJJ)
	{
		return null;
	}

	public static bool IJIJJJIIIIIIJJJIJIIIJJJIIJJJJIIJJJJIJIIIIJJIJII()
	{
		return false;
	}

	public static string[] JIIIJIJJJIIJJIJIIJIJIJIIIIJJIIJJIJIIJIIIIIIJIJI()
	{
		return null;
	}

	public static IIIIIJJIJIIJIIIJJIIIIJJIJIIIJJJIJIJJJJIJJJJIJIJ JIJIJJJIIJIJIJJJIIJIIJJJJIJIIJJJJJJIIIJIJJIJJIJ()
	{
		return null;
	}

	public static void JIIJIJIJIJIJIJIIIJIJIJIIJIIIIIJIIJJIIIJJIJIJJJJ(string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string[] JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, Action<string> IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ)
	{
	}

	public static void IJIIJIIJJJJJJIJIIJJJIJJIIJJJIIJIIJIIIJIIIIIIIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JJJIJIJJIIIJIJJIJIJJIJJJIIIJIIIIJJJJIJIIIJJIIIJ, string IIIJJIJJJIJIIIJIIIJJIIIJJJIJIIIJIJIJIJJJJJJIJIJ, Texture2D IJJIIJIIJJIIJIIIIJIJIJJJIIIIJJIIJIJJIJIJIJJIIJI)
	{
	}

	public static string JIIJIIIIJIIJIJIIIIJJJIJJIJJJIJJIJIIJJIJJJJJIJIJ()
	{
		return null;
	}

	public static void JIIIIIJIJIJJIIJJJJJIIJJJJIIJIJJJIJIJJJIJJJJJIJI(string JIJIIIJIIJJJJIJJIIJJIJIIJJJIIJIJIJIIJIIIIJIIIJJ, bool JIIIJIJJJIIJIJJJIJJJIIIIIIJJJJJIJIJIJJIIJJIJIJI)
	{
	}

	public static bool JIJJIJJJJJJJIIIIJIIIIIIJJJIIIJIJIIIIIJIIIJIJJIJ()
	{
		return false;
	}

	public static bool JJJIIJIIIIIIJIJJJJJIIJIIJJJJJIJIJIIJIJJJJJIIJIJ()
	{
		return false;
	}

	public static string[] JJJJJJIJJIJJIIIJJIJIIJIJIJIIJIIJJIJIJJIIIJJJIJI()
	{
		return null;
	}

	public static string[] IIIIIJIJIJJJJJIJIIIIIIJIJJJJIJJIIIJIJJIIIIIIIJI()
	{
		return null;
	}

	public static int JJJIJIIJJJIIJIIJJJJIIIIJIJJIIIIIJIIIJJIJIJIJJII()
	{
		return 0;
	}

	public static int IIJJJIIIJIJIJJIIIIIIJIJJIIIJIJIIIJIJJIJIJJIIIII()
	{
		return 0;
	}

	public static string IIIIJIIIIJIIIJJJJIIJJIJJJIJIJJIIJJJIJIJIIIJJJIJ(string JIJIIIJIIJJJJIJJIIJJIJIIJJJIIJIJIJIIJIIIIJIIIJJ)
	{
		return null;
	}

	public static bool IIJJJJIJJIIIIIJIJJJIJJIJIJJJIJJJIJIJIIJIIIIIJIJ(string IIIIIIJJIJIIJIJJIJIIIIJJJJJIJJJJIIJIIJJJIJJIJII)
	{
		return false;
	}

	public static string[] JIJIIIIIJIIIJJJJJJJIJJIIIJJJIJJIIIIJIIIIJJIIJJJ()
	{
		return null;
	}

	public static void JIIJJIJIJJIJIJJJIJIJIIIIJIIIIJIJIJIIIIIJIJIJJIJ(string JIJIIIJIIJJJJIJJIIJJIJIIJJJIIJIJIJIIJIIIIJIIIJJ, bool JIIIJIJJJIIJIJJJIJJJIIIIIIJJJJJIJIJIJJIIJJIJIJI)
	{
	}

	public static int JIJIJIJJJIJIJIJJIIJJJJJIJJJJJIJIIIJIJJJIIJJJJIJ()
	{
		return 0;
	}

	public static void JJJIIJIIJIJIJJIJIJJIIJJIJIIIIJIIJJIJIJIJJJJJJJI(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string JJJIJIJIJIIJJJJIJIIJIIIJJJIJIIJIJJIJIIJJIIIIIJJ, string JJIIJJJJJJJIJJIJIIIJIIJIJJIIIIIIJJJIJJIIJJIIJII, string IIIIJJIJIJJJJIJJIJIIIJIIIIJIIJIJIJIIJJIIJJJIIIJ, UnityAction<IIIIJJJJJIJIIJIIIIIJIIJJJJJIJJJIJIIJJJIIIJJIIJJ> IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ)
	{
	}

	public static void JIIJJJIIJIJJJJIIIIJIIIIIIJIIJIJIIIJIJJIJIJJIJIJ(int IIIJJJIIIJJJJIJJJIJIJJIIIIJIIJJJIJJIJIJIIJIIIJJ)
	{
	}
}
