using UnityEngine;

[ExecuteInEditMode]
public class AnimatedWidget : MonoBehaviour
{
	public float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ;

	public float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII;

	private UIWidget IJIJIJJIJJJJIIJJIJJIJIJJJIJJIIJJIIJIJIIIIJJIJJJ;

	private void JJJIJJJJJIIJIJJJIJIIIIJJIJJJIJIIJJIIJIIJJJJIIJI()
	{
	}

	private void IIJJJIJJIJIIIIIJIIIJIJIIIIJIIJJIIJIJIJIIJIIJIIJ()
	{
	}

	private void JJJIJIIJJIIJJJIIIJJIIIJJJIJJIIJJIIIJIIJJIJIJJJJ()
	{
	}

	private void JIIJJIIJIIJIIJIIIIIJIJJJIIJJJJIJJJJIJJIIJJIJJJI()
	{
	}

	private void JJJIIJIJJJIIIJIJJIJIJJIJJIJIJJJIJJIJIJJIIJIJJIJ()
	{
	}

	private void OnEnable()
	{
	}

	private void JIJIIJJIIIIIIIJJIJIJIJJJIJJIJIIJJIJJJIJIIIJIIJJ()
	{
	}

	private void IIIIIJIIJJIIIIJIJIJIJJIIIIIIJIIJIIIIJJJJJJJIIJI()
	{
	}

	private void LateUpdate()
	{
	}

	private void JJJIIIIJIIJJIIJIIIJJJIIJIIIIIJIJJIJIIIIJIJJIIJJ()
	{
	}

	private void JJJIIIIIJIJIIJIJIJIIIJIJJIJJIJIIJIJIIJJIIJJJJJI()
	{
	}

	private void IJIJJIJJJJIIJIIJIJIIIJIIJIJJJIJIIIIIIIJIIJIIIJI()
	{
	}

	private void JIJJJJIJIIJJJJIJIJIIIJIIJJIJIIJJIJIIIJIIIIIJJJI()
	{
	}

	private void JJIIIJIJIJJJJIJJJIIIIJIJJJIJJIJJJIIIJIIIIJIJIJI()
	{
	}

	private void JJIJJJIIJIIJIIJJJJJIIIIIJIIJIIIJIIJIJIJJIJJIJIJ()
	{
	}

	private void JJJIIJJIJIJJJJIIJJJJJIJJIIIJJJIJIJJIIIJIIJIIJII()
	{
	}
}
