using UnityEngine;

[ExecuteInEditMode]
public class AnimatedAlpha : MonoBehaviour
{
	public float IJIIJJIIJIJJJIJIJJJIIJJIIIJJJIIIJJJJIIJJIIJIIIJ;

	private UIWidget IJIJIJJIJJJJIIJJIJJIJIJJJIJJIIJJIIJIJIIIIJJIJJJ;

	private UIPanel IJJIIJJJIIJJJIIIIJIIJIIIJIIJIJIJIJIIJIJIIJJIJJJ;

	private void LateUpdate()
	{
	}

	private void JIIJJIIJIIJIIJIIIIIJIJJJIIJJJJIJJJJIJJIIJJIJJJI()
	{
	}

	private void IJIIIJIJJIIJJIJIJJIIJIIIJJJIIJJIIIJIJIIIIIJJJII()
	{
	}

	private void IIJJJIJIIIJIIIJJJJIIIIJIJJIJIIIIJJJIIIJIIIIIJII()
	{
	}

	private void JIIIJIJJJIIIIJIIJIJIIIIIJJIJIIJIJIIIIJJIJJJJJII()
	{
	}

	private void JJJIJIIJJIIJJJIIIJJIIIJJJIJJIIJJIIIJIIJJIJIJJJJ()
	{
	}

	private void JIJIJIIIJIIJJIIIIIJJIJIIIIJJJIJIJJIJIJIIIIJIJJI()
	{
	}

	private void JIIJJJIJJIJIJJIIJIIIIJJJJJIIIIJJJJJJIIJIJJJIJJI()
	{
	}

	private void IJJJIIJJIIIJJJJJJIIIIJIIIJIJIIJJIJJIJJJIIJJIJII()
	{
	}

	private void JIJIIJIJIIJJJJJIIJJIJJJIIJIJIIJIJIJJJIIJJJIIIJJ()
	{
	}

	private void IJIJIJIIJJIIIJJIJIJIJJIJIIIIJJIJIIIIJIIJIIJIIII()
	{
	}

	private void IIJJJIJJIJIIIIIJIIIJIJIIIIJIIJJIIJIJIJIIJIIJIIJ()
	{
	}

	private void OnEnable()
	{
	}

	private void JIJJJIIIIIIJJIIIIIJJIIIJJIJIJJJJJJJJIJIJIIJIJII()
	{
	}

	private void JIIIJJJJIIIJJJIJJIJJJJIIIJIIIIIIJIIJIIIIIIJIJII()
	{
	}

	private void JJJIJJJJIJJIJJIIIIIIJJJJJIJJJJJJIJJJIIJIJJIJJII()
	{
	}

	private void JIJJIJIJIJIJJIIIJIIIIJJIIIJIJJIJIJIJIIJIIJJJJJJ()
	{
	}
}
