using UnityEngine;

[ExecuteInEditMode]
public class AnimatedColor : MonoBehaviour
{
	public Color IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ;

	private UIWidget IJIJIJJIJJJJIIJJIJJIJIJJJIJJIIJJIIJIJIIIIJJIJJJ;

	private void OnEnable()
	{
	}

	private void IIIJJIJJJJJJJJIIJJIJJJIJJIIIIJIIIJJIIIIIIJJJJJJ()
	{
	}

	private void IIJJJIJJIJIIIIIJIIIJIJIIIIJIIJJIIJIJIJIIJIIJIIJ()
	{
	}

	private void LateUpdate()
	{
	}

	private void JIIJJJIJJIJIJJIIJIIIIJJJJJIIIIJJJJJJIIJIJJJIJJI()
	{
	}

	private void JJIJJJJIIIJJIIJJIJJIIJJIIJJJJJIIJJJJIJIIIIJIJII()
	{
	}

	private void IJIIIJIJJIIJJIJIJJIIJIIIJJJIIJJIIIJIJIIIIIJJJII()
	{
	}

	private void JJJIJJJJIJJIJJIIIIIIJJJJJIJJJJJJIJJJIIJIJJIJJII()
	{
	}

	private void IJJJIIJJIIIJJJJJJIIIIJIIIJIJIIJJIJJIJJJIIJJIJII()
	{
	}

	private void IIJJJIJIIIJIIIJJJJIIIIJIJJIJIIIIJJJIIIJIIIIIJII()
	{
	}

	private void JIJIIJJIIIIIIIJJIJIJIJJJIJJIJIIJJIJJJIJIIIJIIJJ()
	{
	}

	private void JJJIIJJIJIJJJJIIJJJJJIJJIIIJJJIJIJJIIIJIIJIIJII()
	{
	}

	private void JJIIIJJIIJIJJIIJIIIJJJJJIJJIJJIJIIJIIIIIJIJIJJI()
	{
	}

	private void JJIJJJIIIIIJIIIIIJIIJIIIJJJIIJJIJIJJJJIIJJIJJII()
	{
	}

	private void JJJIIIIJIIJJIIJIIIJJJIIJIIIIIJIJJIJIIIIJIJJIIJJ()
	{
	}

	private void JIIIJIJJJIIIIJIIJIJIIIIIJJIJIIJIJIIIIJJIJJJJJII()
	{
	}

	private void JIJJJIIIIIIJJIIIIIJJIIIJJIJIJJJJJJJJIJIJIIJIJII()
	{
	}

	private void IIJJJJJIIJJJJJJJJJIIIIJIIJJJIIIIIJIIIJIIJIJJIJJ()
	{
	}

	private void JIJJJJIJIIJJJJIJIJIIIJIIJJIJIIJJIJIIIJIIIIIJJJI()
	{
	}

	private void JJIIIJIJIJJJJIJJJIIIIJIJJJIJJIJJJIIIJIIIIJIJIJI()
	{
	}
}
