using UnityEngine;

public class AnimMaterial : MonoBehaviour
{
	public Material IJIIJJJJJIIIJJJJIIIJJJJJIJJIJIJJIIIJJIIJJIIIIII;

	public Vector2 JIIJJJIIIJJIIIIJIJJJIIIJJIIIJJIIJIJJJJJJIJJJJJI;

	private bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ;

	private void OnDisable()
	{
	}

	private void JJJIIIIIIIJJJIIJIIIIJJJJIIIIIIIIJJJJJJJIIIJIIJJ()
	{
	}

	private void IIIIIIJIJIIJJJIJJJJJIIJIJIJJJJIIJJIJJIIIJJIIJII()
	{
	}

	private void JIIJJIIJIIIIIJIIIIJJIIJJJIIJIJIJJIIIIIIJJIJJIII()
	{
	}

	private void JJJJJJJIIIJIIJIIIJIIIIJIJIJIJJJJJJIJIIJIJIJJIII()
	{
	}

	private void IIIJIJJIJJIJIJIJIJIIIIJIIJJIIIJJJIJJJJIIJIIJIIJ()
	{
	}

	private void IIJIJIIIJJJIIIJJJJIJIIIIJIJIJJIIIJIJIIIIJIJIJJI()
	{
	}

	private void IIIJJJJJJJJJIJJIJJIIJJJJJJIJIJJJIJIIIJIIIIJJJJJ()
	{
	}

	private void IJJJIIJJJJIIJIIIJJJJIJJJIJJIIJIJJIIJJIIIIIIIIJI()
	{
	}

	private void OnBecameVisible()
	{
	}

	private void OnBecameInvisible()
	{
	}

	private void IJIJIJIIIIJIIIJJIJIIJJJJIJJIJJJJIIIJJJIJIJIIJIJ()
	{
	}

	private void IJIJJJJJIIJIIJIJIIIJJJIIIJIJIJIJJIJIJJJJJIJJJJJ()
	{
	}

	private void IJJIJJJJJJJJJIJIIIIIIIJJJJJJIIJJIJJJIIJIIIIJIII()
	{
	}

	private void Reset()
	{
	}

	private void IIJJIJJJIIJJIIIJIIIIIIJJJJJIIJJJJIJIJJIJIJJIJII()
	{
	}

	private void IJJJJJJIIIIIJIIJJIIJJIJJJIJIIIIJJJIJJJIJJIJIIJJ()
	{
	}

	private void Update()
	{
	}

	private void JIJJJIJIIJIJIIIJIJIJIJJIIIIIJIJIIIIJIJJIIIJJJIJ()
	{
	}
}
