using System;
using System.Collections.Generic;
using UnityEngine;

public class AnimRecord : MonoBehaviour
{
	[Serializable]
	public class Point
	{
		public Transform target;

		public bool pos;

		public bool rot;

		public List<Vector3> posList;

		public List<Vector3> rotList;
	}

	public bool JJJJIIIIJJIIIJJJIIIJIIJJJJJJIIJJJIIIIIJJJIJJIIJ;

	public List<Point> IIJIIJIJJIJIJIIJJIIJIIJJJJIIIIJJJJIJJIIJIIJJJJJ;

	private int JIJJJJIJIJJIJJJJJJIJJJJIJJIIJIJJIIIJJIJIIIJJIJI;

	public int IIIIIIJJJJIIIIJJJIIIJIJIJJIIJIJIIIJJIJJIJIIIJIJ;

	public bool JJJJIIJJJJIIIIJJJJIIIIJIJJJJJJJIJJIIJIIIJJJIIJI;

	public int JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ;

	private Rect JJJIIIIIJIJIIJJJIIIJJJJJJJIIIJIJJJIIIJJIJJJIIJI(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
		return default;
	}

	private void JIIIJIIIJJJIIIIIJIIIIJJIIJIIJIJIIJJJJIIIJIIJJJI()
	{
	}

	private void Update()
	{
	}

	private Rect IIIIIJJJJJIIJJJJJJJJJIIJIJIJJIJJIJJIIIJJJIIJJJI(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
		return default;
	}

	private void JJIJIIJJJJIIJIJIIJIJJJJJIIJIJIIIIJIJIIJIJIJJJJI()
	{
	}

	private void JIIJJIIJIJIJIIJIIJJJIIIIJIIIIIJJIIIJJJJJIIJIIJJ()
	{
	}

	private void JIJJIJIJIIJJJJJIIJJJIJIIJJIJIJJIJJJIIJJIIIJIIIJ()
	{
	}

	private void IIIJJIJJJIIJIIIIJJIIIIJJIJIIJJJJJIJIJIJIJIJJIII()
	{
	}

	private void JIJJJIIIIIJIJJIIJIJIIIIJIJIIJIIIIJJJIIJJJIJJJIJ()
	{
	}

	private void IIIJJIIJIJIIJJJIIIJIIJJJJIJIJIIIIJIJJIIJJIJJIJJ()
	{
	}

	private void JJIJIIIIIJJIJJJIJIJIIIJJJJIJIJJJJJIIIIJJIJJIIJJ()
	{
	}

	private void IJIIJJIJJJIJJJJIJJIJJIJIJJJJIIJJJIIJIJJIJJIIIIJ()
	{
	}

	private void OnGUI()
	{
	}

	private void IJJIIJIIIIJIIJJIJIIIJIJIIJIJIJJJIJIIIJJJIIJJJII()
	{
	}

	private void JJIJJJIIJIJIJIJIJJJJJIIJIJIIIIJJIIIJIIJJJJJIJIJ()
	{
	}

	private Rect IJIJJIIJIIIIIJIJIIIJIIJJJJIIIJJIJIJIIIJJJJIJIJJ(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
		return default;
	}

	private void IIIIIJIIJJIIIIJJIJIJIIIJIIJIIIJJIIJIJJJIJIIJIIJ()
	{
	}

	private Rect JJIJJJJIIJJIIIIJJIIJJJJIJIJIJJJJJJIJIJIIIJJJIII(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
		return default;
	}

	private void JJJJIIJJIIIJIJIIIIJJJJIJJJIJJIJIIJIIJJIJIJJJIII()
	{
	}

	private void IJIJIJIIIIJIIIJJIJIIJJJJIJJIJJJJIIIJJJIJIJIIJIJ()
	{
	}

	private void IJJIJJIIIJJIJJJIIJIIJIIJIJIIJIJIJJIJIIIIIIIJIJI()
	{
	}

	private void IJJJJIJJJIJJJJIJIJJJIIJJJJIJJJJIIIIJIIIJIIIJIII()
	{
	}

	private void JJJIIJJIIJJJIJJIJJJJJIIIIJIIJJJIIJIIJIIIJJJJIII()
	{
	}

	private void JIIJJIIJIIIIIJIIIIJJIIJJJIIJIJIJJIIIIIIJJIJJIII()
	{
	}

	private void JIJJIJIIIIJJJJJJJJJIJJIIIIIIJJJIIIJIIIJJJJIIIIJ()
	{
	}
}
