using UnityEngine;

public class AudioListenerManager : MonoBehaviour
{
	public AudioListener IIJJJIJJIIJIIJJJIIIJJJJIJJIJIJJIIIIJJJIIJIIJJJJ;

	private Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ;

	private static AudioListenerManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void IIJIJIIJJIIIIIJJIIIIJIIJIJIJIIJIJJJJIJJJJJIJJJI(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII)
	{
	}

	private void Awake()
	{
	}

	public static void JJJJIIIIIJIIJJJIJJIJJJJJIJJIIIJJIJJIJJIIIJJIIJI(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII)
	{
	}

	public static void JIJJIIJIIIIJJJIJIIJJIJIJIIJJIJJJJIIIJJIIIJJJIIJ(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII)
	{
	}

	public static void JJIJIIJJIIJJJIJIIJIJIJJJJJJJIJJIJIIJIJIIJJIIIJJ(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII)
	{
	}

	private void IIIJIJJJIIJIIIJIIJJJIJJIJIIJJJIJJIIIJJJJIIJJJIJ()
	{
	}

	private void JJIJIIIJIJIJJJJIJIIJJJJJIJJJJJIJIJIJIIJIIJIIIJJ()
	{
	}

	private void IJIJJJJJIJJIIJJJJJIJIJJIJJJJJJIJIIIIIIJJJJIIIIJ()
	{
	}

	public static void JJJIJJJJJIIIIIJIIIJIJIJIIIIIIJJJJJJJIIJIJIJJIJJ(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII)
	{
	}

	public static void JIIJIJJIJJJIIJIIJIJIJIIIIIJJIJJIJIJIIJIJJIJIJJJ(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII)
	{
	}

	private void IJJJJIJJIJJIIJJIJIJIJIIJJJJIIIJJJJJIJIJIJIJJJII()
	{
	}

	private void IIJJIIIJJIJIIJIJIIIJIIJIIJIJJIIJJIIIIJIJJIIIJJI()
	{
	}
}
