using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class AutoClickerDetector : MonoBehaviour
{
	public GameObject JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ;

	public Transform IIJIJIJIJJIIIIIIIJJJIJIJIIIIJJJJIJJJJIIIJJIIIJJ;

	private int IJIIJJJIJJJIIJJIJIJIIJJIJIIIJJIJJIJJJIIJIJIJJIJ;

	private Vector2[] JIIIJJJJJIJJJIIJIIIIJIJIIJJJIJIIJIIJIJIJJIJJJIJ;

	private int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ;

	private int JJIIJIJJJIJIIJIIJIJIJIJIJIJJJIIJJIIIIIJJIJJIIJI;

	private byte JIIJJIJIIIJIIJJJIIIIIJIIIIJIJJJJIIJJJIIIJIIIJJI;

	private Touch IJJJJJJIIIJJIJJIJJIJJIIJIIJJJJJIJJJJIIJJJJIIJJI;

	private Vector2 JIIIIIIIIJIJIIJJIIIJJJIJJIIJJJIJIJJJIJIJJIIJJIJ;

	private static AutoClickerDetector JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void IIJIJJIJIIJJJJJJIJIIIIIJJJJIIIIIIJIJJJJJJJIIJII()
	{
	}

	public static void IJJIIJIIJJIIIJJJIIIJIJIIJIIIJJJIJIIJIIJJIJJJIJJ(int IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ, int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
	{
	}

	private void IIJJIIJJIJJJIJJIIJJIIIJJJJIIIIIJJJJIJIIJIJJIIJJ(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void Start()
	{
	}

	public static void IIJJIIJJIJJJIJJIIJJIIIJJJJIIIIIJJJJIJIIJIJJIIJJ()
	{
	}

	public static void IIJIJIIJIIJIJJJJJIJJIJJIJJJIJJJIIIJJIJJJIIIJJJI()
	{
	}

	public static void JJJIJJIIIIIIJJIJIJJJJIIJJIIJIJIJIJJJJIJJIJIIIIJ(int IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ, int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
	{
	}

	public static void JIJIJIIIIJIJJIJIIIIJIJIJIIJJIJIIIIJIIIJIJIIJIJI(int IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ, int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
	{
	}

	public static void JJIJIIJIIJIJJIJJIJJIJIIIIIJJJJIJJJIIIIIJJJJIIII()
	{
	}

	private void JIIJJIIJIIIIIJIIIIJJIIJJJIIJIJIJJIIIIIIJJIJJIII()
	{
	}

	public static void JJJIJIIJIIIJJIJIIIJIJIIIIJJIIJJIIJIJJJIIJIIJIJJ(int IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ, int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void Update()
	{
	}

	public static void IIJJIIJJIJJJIJJIIJJIIIJJJJIIIIIJJJJIJIIJIJJIIJJ(int IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ, int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}
}
