using System;
using System.Runtime.CompilerServices;
using Photon;
using UnityEngine;

public class BombManager : Photon.MonoBehaviour
{
	private sealed class IJIJIJJJIJJJJJJJIIIJJIJJJIIJIJIJJJJIJJIJIIIIIJI
	{
		public BombManager JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII;

		internal void JIIIJJIJIIJIJIIJJJIIIJIIJJJJIJJIIIJJIJJIJJIIIJI()
		{
		}

		internal void JIIJIIIJJIJJJIJIJJJJJJIJJJJIIJIIJIIIIJIJIJIIJII()
		{
		}

		internal void IIJJJJIJIJIJIJJJJIJJIIJJJJJJIJJIIIIIJIIIIIJJIII()
		{
		}

		internal void IIJJJIIJIJJIIIIJJIIIJIIIJIIJJJIJJIJJJJJIJJIIIJI()
		{
		}

		internal void IJIIIIJIJIIJIIJJJJIIIJJJIIJIIIJIIJJIIJIJIIIIIJJ()
		{
		}

		internal void IJJJJJJIIIJIIJIJJJIJJIJJIIJIJIJIJJJIIIIJJJIIIII()
		{
		}

		internal void JIJIJJJJJJIJJIIIIIIJJIIJJIJIIIIJJJJIJJJJJIJJJIJ()
		{
		}

		internal void JIJJIJIJIIIIJJIJJIJJJJJIIIJJJJJJJIIIIIIJIJJIIIJ()
		{
		}

		internal void JJJJJJJJIJIJIIIJIJIJJIIJIJJJIIIJIJJJIJJIJJJIJII()
		{
		}

		internal void IIJIJIIIIIIJIIJIJJIJIIIJIJIIJIIIIIIJIIJIIIIIIJJ()
		{
		}

		internal void IIJIIJJJIIIIJIIIIJIIJIIJJIIJJIJJJJIIJJJIIJIJIJJ()
		{
		}

		internal void JIJIIIJIIIJIIJJJJJJJJJJIIIIIIJJJIIIIJIJIIIIJJIJ()
		{
		}

		internal void JIJIIIIIJIJIJJIIJIIJIJIIJJIIJJJJJIJIIJJIIIIJIIJ()
		{
		}

		internal void JIJIJIIIJJIIJIIJJIIJJJIJIJIJIIIIJIIJIIJJJIIJIIJ()
		{
		}

		internal void IJIJJIIJIJIIIJIIIJIIIJIJIIIJJJIJIIIJIJIIIJJJJIJ()
		{
		}

		internal void IJIJJIJJIJJIJIJJJJIIIIIJJJIJJIJJIJIIIJIIIIJIIII()
		{
		}

		internal void IJJJJIIIIIIIIJJJIIIJJJJJIJJIIJIJIIJIIIIJIJIIJIJ()
		{
		}

		internal void JIIIIJIIJIJJJIIJIIJIJIIJIIIIIJIIJIJIJJIIIJIIIII()
		{
		}

		internal void IJJIJIIIIIIJJIJIIIIJJJJIIJIJIJIIIIIIIIIJIJIJIJJ()
		{
		}

		internal void IJJIJJJIJJJJJIJIIIJIJJIIJJIIIIJJIIIIJJIJJIIJJJJ()
		{
		}

		internal void IJJJJJIIJIJJIJJJJIIJIJIIIIJJIJIIIJIJIJJIJJIJJIJ()
		{
		}
	}

	public GameObject IJIIIIJIJJJIJIIIIJJJIIIIIJJJIIJIIIJIJIJIJIJJIJI;

	public Transform JIIJIIJIJJJIJIIJIJJIJJIIIJJJJJIJJIJJIJIJJIJJIJI;

	public Transform JJIJJIIIIJIJIJJIIJJIJJIJJIJJIIJIJJJIJIJIJIIJIIJ;

	private int IJJIJJJJIJJJJIJJJJJIIIJIIJJJIIJJIIJIIJIIIJIJJJI;

	private int JJIJIJJJJIJIJIIJIJIJJJIIJJJIJJJJIIIJIIIIIIJJJJI;

	private int IJIJIIIJJIIIJIJIJJIIIIJIJIIIJJIJIIIIJJJJIJJJJII;

	public static bool IIJIIJIIJIIIJIIIIJJJJJIIJIJJJIIJJIJIJIJIIJJIJJI;

	public static bool JIIIIIIIIJJIIJIIIJIJIJIIJIIIIIIJIJIJIIJJIJIJJII;

	private bool IJIIJIIIIJJIJIJIJJJIJIJIIIIIIIIIJIJJIIJJJIJJIJI;

	public BombAudio IJJIIIIIIIIIJJJJJIJIIJIJJIJJJJJJJJIIJIIIIJJJJII;

	public ParticleSystem IIIJJJIIJJIIIIIIJIJIJJIJIIJIJIIJIJIJIJJJIIJJJJJ;

	public AudioSource IIIIJIIIIJIJIIIIIJIJIJJIIJJIIJJIIJIIIIJJIJIIJII;

	private ControllerManager JJJJJJIJJIIIIJJJJJJIJJJIJIIJJIIJIJJJIJIJIJIIJJJ;

	public Transform IIJJIJIIIJIIIIJJIJJJIJIIJJJIJIJIIJIIJIIIIJJJIIJ;

	public GameObject JJIIJIJJIIJJIJJJIIIJJJIJJJIJJIIIJJJJIJJIIIIIJJI;

	private Vector3 IIJJIJJIIIIJJIJIJIJIJJIJJJIIIJIIJJIJJJJIJJJIIII;

	private UISprite JJJIJJJIIJJIIIJIIJJJIIIJIIIIIIIJIIJIJIIIJJJIJIJ;

	public static DropBomb JJJJJJIJJJIJJIJIIIJJJIIJJIJIJJJIIJJIJJJJJJJIIJJ;

	public static float IIJIIIJJJJJJJJJIIIIIJIIJJJIIJJIJIJIJJIIIJJJIIII;

	private float IJIIJJJJJIIIIJIIIIJIIIJJJJJJJIJJJJJJIIIJJJIJIJI;

	private static Action<int> IJJIIJIIIJIJJJIIJJJJIIIIJJIIJIIIIJIJJIIJJIJJIII__BackingField;

	private static BombManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public UISprite JJJJIIJIIIIIIIJJIIJJIJJIIJIIJIJJIIJJJIJJIJIJJII => IIIJIIJJIJIJJIIIJIIJJJJJJJIJIJJJJIIJIJIJJJJJIIJ();

	public static int IIIIIIJJIIIJIIJIJIIJIJIJIIIIJIJIJIJJIIIJJIJJIII => IJJJIIIIJIIIIIJJIIIJIJIIJJJJJIJJJJJJJIIIIIJJIJJ();

	public static event Action<int> IJJIIJIIIJIJJJIIJJJJIIIIJJIIJIIIIJIJJIIJJIJJIII
	{
		add
		{
			IIIJIJJJIJIIIJIIJIIIJIIIJJJIIJJJIIJIJJIJJJIJJII(value);
		}
		remove
		{
			JJIJJIJJJJJJJIIIIJIIJJIJJIIIJJIIIJJJIJIIJIJJIJI(value);
		}
	}

	private void JIIIJIIIJIJJIIIIJJIIIIJJJIIJIJIIJJIJJIJIJIJJJIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIJIIJIJIJIIIJIJJJIJIIJIIIIIJJIJJIJJIJIIJIIJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static int IJJJIIIIJIIIIIJJIIIJIJIIJJJJJIJJJJJJJIIIIIJJIJJ()
	{
		return 0;
	}

	private void JIJIIIJJIJJJJIJIJIJJIJIIJIJIIJJIJIJIIJJIIIJJJJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IIJJJIJIJJIJIIIJIIJJIIJIIIIIJJJIIIIJJIJIJIIIJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IIJIIIJIJJJJIIIIIIJIIIJIJIJIJJIIIIIIJJIJJIJJIII()
	{
	}

	public UISprite IIIJIIJJIJIJJIIIJIIJJJJJJJIJIJJJJIIJIJIJJJJJIIJ()
	{
		return null;
	}

	private void Awake()
	{
	}

	private void JIIIJIIJJJJIJIJJJIIIIIJIJJIIIIJJJJJJJJIJIIIIJJI()
	{
	}

	private void IIJIIJJJIIJJJIIIJJIJIJJIIJJIIIJIJJJIJJIJIJJIJJI()
	{
	}

	private void IIIIIIIIIIIJJIJIJJJIJJJJIJIIJIIIJIJIJJJJJIJJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}
	public static void JIIJJIJIJIIJIIJIIIJJIJIJJJJJJJJIJIJJJJJJIIIJIJI(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void IJIJIJIIIIJJIJIJJJIJJJIIIIIIJJIJJIIJJJIJJJJIIIJ()
	{
	}

	public void OnBombEnter()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIJIIJJJJJIIIJJIIJJJIJJIIJIIIIJJJJJIJJJIIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void IJIIJJJIJIIIJJJJIJIIJJIJIJIJIIJJIJIJJJJJIIJJIIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	public void OnPlantExit()
	{
	}

	private void IJIIIIJJJJIIJIIIIIIJIIIIJIIIIJIJJJIIIIJJJJIIJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public static void JIIIJJIIIIIIJIJIIJIIJJIIJIIJIJJJJIIJIJIIIJIJIII(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, Vector3 IIJIJIIJIIIIIIIJIJIIJJIJIJIJIIJJIJIIIIIIJJIIIII)
	{
	}

	public static void JIIIJJIIIIIIJIJIIJIIJJIIJIIJIJJJJIIJIJIIIJIJIII(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	private void IJJIIIJJJJIJIIIJIJIJIJIJJIIIJIIJJIJIIJJIJJIIIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void OnPlantEnter(int trigger)
	{
	}

	private void Update()
	{
	}

	private void OnEnable()
	{
	}

	public void IJJIIIIJJJIIIJIIIJJIIJJIJIJIIJJIJJJJJJIIIIIJJII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJIJIJJIIJJIJJJJIIJIJIIJIJJIJIIJJJIJJIIIIJIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void IIJJJJJIIIIJIJIIIJIIJJJIJIIIJJIJJIJIJIJIIIJIIJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIJIJJJJJIJJJJIIIIJJJIIJIIJIIIIIIJIIIJIIJIJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void JIIJIJJJJIJJIIJJIJIJIJIIJJIIIJJJJIIJIIIIJIIIJJJ()
	{
	}

	private void OnDisable()
	{
	}

	public void OnStoreEnter(int team)
	{
	}
	public static void JIJJIJIJJIJIJIIJJIIJJJIIIJIIIIJIIIIJIIIJIJIIJII(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJIJJJIIIJJIJJJJJIIIJIJJJJIIJIIIJJIJJJIJJJIIJJJ()
	{
	}

	public static void IIIJIJJJIJIIIJIIJIIIJIIIJJJIIJJJIIJIJJIJJJIJJII(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JJIJJIJJJJJJJIIIIJIIJJIJJIIIJJIIIJJJIJIIJIJJIJI(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJIJIJJJIJJIJJJIJIJJJIJIJJJJIIJIIJIIJIIJJJIIIJI()
	{
	}

	private void JJJIJJIJJIJJJJIIJIJJIIJJJJIIJJIJJIJJIJIIIJJIIJI()
	{
	}

	public void OnBombExit()
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJIIJIIIIJJJIIIIJJIJIIIJJJJIJIJJJIJJIJJIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJIIIIJJIIIIJIJJJIJIIIIJJIIIJJIIIIJIIIJJJJIIII()
	{
	}

	public void IJJJJIIIIIIJJJIJJIJIIIIJJJIIIIJIJIJIIJIJJIIIJIJ()
	{
	}

	public void IIIJIIIIJJJIIIIIJIJJJJJJIIJIIJIJIIIIJIJJJIIJIJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJIJIJIIIIJIIIIIJIJIIJIIIJIIIJJJJJJIIJIJJIIJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJIJJJIJIJJJJIJJIJIJIJJIIJIJJIJJJIIJJJJJIIIIJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIJJJIIJIJIIIJJJIJIIIIIIJIJJIIJIIJJIIIIJJIJIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}
	public static void JJIIIIIJIJIIIJIIIIIIJIIJIIJJJJJIJIJIIJJJJJIJJJI(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void Start()
	{
	}

	public void OnStoreExit()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIJIIIIIJIIIIIIJJIIIJIJJIJJJIJIIIIJJJJJIIIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIJIIJJJJJJIJIJJJIJIIJJJIJJJJIIJJIIJIJIJJJJIJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}
}
