using System.Runtime.CompilerServices;
using UnityEngine;

public class BombAudio : MonoBehaviour
{
	public AudioSource IIJJIJIJIIJIIJIIIIJIIIIIJIJIIIIIIIIIIJIJIJIJJIJ;

	public AudioClip IIJIIJIIJJIIJJIIJJJIIIJIIIJIIIIIIIJIJJIJJIIIJJJ;

	public Light IJIJJIJJJJIJJIIJIJIJIJIIIIJIJIJJJJIJJJIJJJJIIJI;

	private int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ;

	private float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

	private int IJIIJJJIJJJIIJJIJIJIIJJIJIIIJJIJJIJJJIIJIJIJJIJ;

	public void IJJJIIJIJIIIJJIJJIJJIJIIJIJJIJJJIJIJJJIJIJIJIII(float JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
	{
	}

	public void IIIIIJIIIJIJIJIIIJJJJJJIJJIIJJIIIJJIJIIJJIIIIII()
	{
	}

	[CompilerGenerated]
	private void IIJIIIIIIJJJIIIJIIIIIIIIJIJJIIJJJJJJIIJJJIIJIIJ()
	{
	}

	public void JIJJIIJIIJJJJJIJIIJJIJIIJIJJIIJJIJIIIIIJJJIIIJJ(float JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
	{
	}

	[CompilerGenerated]
	private void IIIIIJJJIIJJJJJIJIIJIIIIJJJJIJJJIJIJJIIJJJIJJJJ()
	{
	}

	public void IJJJIJIJIJJJIIJJIJIJIIJIIIIIIIJJIJJIIJIJIIIIIJI()
	{
	}

	private void IIIJJIJJIJIIIIIJIJIIJJJIJIIIIJJIJJJIIIIJIIJIJIJ()
	{
	}

	private void IIJJIIJJIJIJJJIIJIIIJIIJIJJJJIIIJIIJIJIJJIJIIII()
	{
	}

	public void JIJJIIIIIJIIIIIIIJIIIJIIJJJIJJIJIJIJIJIIIJJIJIJ()
	{
	}

	private void JJIIJJJIJJIJIJJJJIIIIIIIIJJJIJJJJJJJIJIJJJIIIJI()
	{
	}

	private void OnEnable()
	{
	}

	private void JIJJIJJIIJJIJJIJIJJIIJIJJJJJIIJIIIJJIIIJJIJIJII()
	{
	}

	public void JJJJJJIJJJJJJJJIIJIIJJJJJIIJJIJJJJIJIJIJIIJIJII(float JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
	{
	}

	public void IJIJIJIIIIJJIJIJJJIJJJIIIIIIJJIJJIIJJJIJJJJIIIJ()
	{
	}

	private void JIIJIIJJJIJIIIIIJIIIIIJJIJIIJJIIJJJIJIJIIJIIIIJ()
	{
	}

	public void IJJIJIJIIJIJJIIJJJJIJJJJIJJJJIIJJIJJJIJIIIJJIJI()
	{
	}

	[CompilerGenerated]
	private void IJIJJIIJIIIIIJIIIJJJJIIIJJIIIJJJIIJJIJIJJIIJIIJ()
	{
	}

	private void Update()
	{
	}

	private void OnDisable()
	{
	}
}
