using System.Runtime.CompilerServices;
using ExitGames.Client.Photon;
using Photon;
using UnityEngine;

public class BunnyHop : Photon.MonoBehaviour
{
	private Vector3 IJJIIJIIIJIIJIJJJIIIIIIIIJIJIJJIIJJJJJIJIIJJIJI;

	private Quaternion IJJJJIIIIIIJJJIIIJJJIIJJIJIIIJJJIJIJJJIIIJJJJII;

	private static BunnyHop JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void Start()
	{
	}

	public static void IIJJJJIIIJIIIJIIJIJJIIIIIIIIJJJJIJIJIJJJIJJIJIJ(int IJJIIIJJIJIIIIJIJJJJIJIIIIJIIJIJJJJJIJIIJIJJJJJ, int JIIJIIIJJJIJJJIIJJIIIIJIJIJJIJJIIJIIJIJIIJJIIJI)
	{
	}

	private void OnEnable()
	{
	}

	public static void IIIIIIJJJJJJIJJJJJJJIIIJIJJJIIIIIJIIIJIIIJJIIII()
	{
	}

	public static void JIJIIIJJIJJJIIIIJIIJJJIJJJJJIIIIIIIIJIJJJJJJJIJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void JIIJJIJIIIIIIIIIIJJIIJIJJJIIIIIIIJIIIJIIIJIJJII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void JIIJIJIJIIIJJJJJJJJJJJIIIIJJIJJJIIJIJJIJIIJIJIJ()
	{
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public static void JIIJIIIJIIJJJIIJIJIIIJIIIJIIJIJJIIIJJIJIJJJIIJJ(float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI, int JJJJIIIIIJIIIJJJJIIIIIJJIIIIIJIJIIJJJIJIJJIJJII)
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void OnPhotonCustomRoomPropertiesChanged(Hashtable IIJIJJJJJIIJJIIIIJJIIIJJJIIJIJIJIIJIIJJJJIIIJIJ)
	{
	}

	private void IJJJIIIJIJIJIJJJIIIIJJIIJIJJIJJIIJJJIIJJJIJIJII()
	{
	}

	private void Awake()
	{
	}

	private void IIIJJIIIIJJIJIJJJJJJIJJJJJJIJIIJJIJJIJIJJJIJJJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJIJJJIIJIIIIIIIIIJIIJJJJIIJIJJJJIJIJJIIJIIJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIIJJIJIIJIJJJIIIIIJJJIIIIIIIIJIJJJJJJIIIIIIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJIIJIJJIIJIJJJIIIJIIIIJJJJIIJJIIJJJIIJJIJJJJII()
	{
	}

	private void IJJIIJJIJJJJJJJJJJIJIIJIIJIIJJJJIJIIJJJIJJIIJII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void IIIIIIIJJJIJIIIIIIJJIIIJIIIJJIJJJJJIIIJIJJJIIII(Hashtable IIJIJJJJJIIJJIIIIJJIIIJJJIIJIJIJIIJIIJJJJIIIJIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIJIJIJIIIJIIIJJJIIIIIJIIIJJIJJIIIIIIIIIJIJJJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIJIJJIIIJJIJIIJJIJIIIJIJJIJIIIIIJIJJJIIJIJIIJ()
	{
	}

	private void OnDisable()
	{
	}

	private void IJJJJIJJJJIJIJJIIJIJJIIIJJJJIJIIIJIIJJJIJIJIJII()
	{
	}

	private void JIIJIJIIIIIIIIIJIJJIIIJIJJJJJIIJIIJJIJJJIJIIJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	[CompilerGenerated]
	private void JIIIIJJJJJIIJJJJIJJJIJJJIIIIIJJJIIIIJIIJIJIJIIJ()
	{
	}

	public static void JIIJJIJIIIIJJJIJIJIIIJJIJJJJJJJJJJIIIIJIIIJJIJJ()
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void IJJIJJIJJJJIIIIJIJIIJIJIIJIIIIIJIJIJIIIIIIJIJJJ()
	{
	}
}
