using UnityEngine;
using UnityEngine.Events;

public class ButtonEventTrigger : MonoBehaviour
{
	public UnityEvent IIIJIIIIIJIJJIIJJJIJJJJJJJIIJJJIIJIJJIIIIJIIJIJ;

	public bool IIIIJIJJIIJIIIJJJIIIJJJIJJIJJIJIJIJJJIJIIJIIJIJ;

	public JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ;

	private bool JIIJJJJIIIIIIJIIIJIJIJIJIIJJIJIJIIIIJJJJIIIIJJJ;

	private bool JJIIJJIIJJIJIJIJJJIIJJJIIIIJIJIIIIIIJIIIIJJIJJJ;

	private void IJJJIIJIIJJIJIIJIIJJJIIJIJJJJIJJJIJIIJIIJJJIIJI(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void JIJJIIIJIJIIJJIJIJJJIIJIJIJJJJIJJJJJJJIIJJIJJJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJJIIJJIIJJIIJJJJJJIIIJJJJJIJIIJIJIIJIIJIIIIJII()
	{
	}

	private void IJJJJJJJIJIIIIIIJIJIJJJIJJJJIJJIJIJJIJJIJIJJIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIIIJIIIJIJJJJIJIIJJJJJIJJIJIIJJJJJIJIJJIJIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJJJJIIIIJJIIIJJIJJJJJJIJIIJJJJJJJJIJJIIJIIIJIJ()
	{
	}

	private void JJJIIJIJJJIIIJIJJIJIJJIJJIJIJJJIJJIJIJJIIJIJJIJ()
	{
	}

	private void OnDisable()
	{
	}

	private void IJIJJJIJIIIJJJJJIIJIJJIJJJIJIIIIIIIJJIJIJIIJJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIJIIIJJJJIIIJJJJIJIJJJJJJJIIIIJIJIIJIIIIIIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJIJJJIIJIIJIJJIJIJIIIJIJIJJIIIIIIJJIJIJIJIJIJJ()
	{
	}

	private void OnTriggerExit(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJIJIIIIJIJJJJIJJIIJJIIIIIJIIIJJIIJJIJJJIIIIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void OnEnable()
	{
	}

	private void IJIIIIJJJJIIJIIIIIIJIIIIJIIIIJIJJJIIIIJJJJIIJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}
}
