using UnityEngine;

public class CameraStatic : MonoBehaviour
{
	public CameraManager IIJIIJIIJIIIIIJJIIIIIIJJJJJJJJIIJIIJJIIJJJJIJIJ;

	private Transform IJIJIIIJIIJJJJJIJJJIIJIJJJIJJJIIJIIJIIIJJJJIIJI;

	private void IIIJIJJIJJIJIJIJIJIIIIJIIJJIIIJJJIJJJJIIJIIJIIJ()
	{
	}

	private void JJIJJIJIJIIIJJIIIIIJJIJIIIIJJJIJIIJIIIJJIIJIJJI()
	{
	}

	private void IJIIIIJJJJIIJIIIIIIJIIIIJIIIIJIJJJIIIIJJJJIIJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void JJIJIJIJJJJJIIJJIIIJJIJIIIJJIIJJJIIIIJIJJIIIIJI()
	{
	}

	public void IJJIJIJJJIJIJJIJIJJIJJJIJJIIIIJJJIJJJIJIJJJJIIJ()
	{
	}

	public void JJIIIIJJIIIIJIIIJJJJJIJJIIIIJIJIIIJJIIIJIIJIIJI()
	{
	}

	public void IIIJJJJJJJJIJIIJJJIJJIJJJJJJIJJIJJJIIJIJJIJIJJI()
	{
	}

	private void JJJJJJIIJJIJIIJIJJIIJIJIJJJIIJIIJJJIIJJIJJJIIII()
	{
	}

	public void JIJIIIIIIJIIIIJIIJJIIIIJJJIJIIIIIIIIJIIIJIIIIII()
	{
	}

	private void IJIIIJJIJJIIJIJIJJJJIIJIIJIIJIJIIJIIJJIJIJIJIII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public void JJIIIIIJJJIJIJJJJJIIIJJIJJJIIIIJIJJJJIIIJIIJJII()
	{
	}

	private void IIIJIJIIJJIJJIJIIIJJIIJIJJIIJIJIJIJJJJJIIIJIJJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public void IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI()
	{
	}

	private void OnDisable()
	{
	}

	public void JIJJIIJJJJIIJIIIIJJIIJJJIJJJJJJIJJJIIJIJJJIJIJJ()
	{
	}

	public void JJJIJIJIIIJJJJJJIIIJJIIJIIIIJIJIIJIJJIJJIIIIIII()
	{
	}

	private void JIIIJJIIJIIIJJIIJJJJIJJIIIJJJJIJJJJJJJJJJIJJIIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public void JJJJJIJJIJJIJJJJJJJJJIIJIJIIIJJIJJJIJJIJIJIIIJI()
	{
	}

	public void IIJJJIIIIIJIJJJIJIIJJJIIIIIIIJJJIJJIIIIJIJIIIJJ()
	{
	}

	private void IIJJJJJIIIIJIJIIIJIIJJJIJIIIJJIJJIJIJIJIIIJIIJI()
	{
	}
}
