using UnityEngine;

public class CameraDead : MonoBehaviour
{
	public CameraManager IIJIIJIIJIIIIIJJIIIIIIJJJJJJJJIIJIIJJIIJJJJIJIJ;

	public Rigidbody IJIIIIJIJJIJJJIIIJIIJIIJJJIIIIIJIJJIJJJIIIJIIJJ;

	public Transform IJIJIIIJIIJJJJJIJJJIIJIJJJIJJJIIJIIJIIIJJJJIIJI;

	public BoxCollider JIJJIJJIIIJIIIIJIIIJJJJJJJJIJIJJIIJJIIJIJIIJIJI;

	public void JIJIJJJJJIIIIIIIJIIIIIIJJJIIIJJIIIIJJIIIJIIIJII(object[] JIJIJIJIIIIJIJIIIIIIJJIJIJJIIJJIIIJJIIJJIJJIJJJ)
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	public void JJJIJIJIIIJJJJJJIIIJJIIJIIIIJIJIIJIJJIJJIIIIIII()
	{
	}

	public void IIIJJJJJJJJIJIIJJJIJJIJJJJJJIJJIJJJIIJIJJIJIJJI(Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Vector3 IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}

	public void JIIIIJJJJIIJJJJJIJJJJJIIJIIJJJIJJIIJIJJIIIJJJII()
	{
	}

	public void IIJIJIIJIIJIIJIJJJJJJJJJIJJJIIJIJIIIIJIJIIJIIIJ(object[] JIJIJIJIIIIJIJIIIIIIJJIJIJJIIJJIIIJJIIJJIJJIJJJ)
	{
	}

	public void IIJIJJIJJJJJJJJIIIIJJJJJJIIJJJJJJJJIJJIJJJJIIJJ(object[] JIJIJIJIIIIJIJIIIIIIJJIJIJJIIJJIIIJJIIJJIJJIJJJ)
	{
	}

	private void IJIIJJIJJJIJIJJJIIJIJIIJJJJJIJIJJJJIIJIIJIJJJJI()
	{
	}

	public void IIJJJIIIIIJIJJJIJIIJJJIIIIIIIJJJIJJIIIIJIJIIIJJ(Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Vector3 IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}

	public void JIJIIIIIIJIIIIJIIJJIIIIJJJIJIIIIIIIIJIIIJIIIIII()
	{
	}

	public void IJIJIIJIIJIJIJJIIIIIJJJIJIIIIJIJJIJJJJIJIJIJIII(Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Vector3 IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}

	public void IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI(object[] JIJIJIJIIIIJIJIIIIIIJJIJIJJIIJJIIIJJIIJJIJJIJJJ)
	{
	}

	public void JIJIJIIJJJIJIIIJIIIJIIJIIJJJJJIIJIIIIIJJIJJIJJJ(Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Vector3 IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}

	public void IJJIIIIIIIJJIIJIJJJJIJJIIIJJIIIJIIIJIJIJJJJIJJI()
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	public void IJIIJIJJJJJIJIIJJIJIJIIIJJJJJJIIIJJJJJJJIIJJIII()
	{
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	public void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII()
	{
	}

	public void JJIIIIJIIJIJIIIJJIJIJJJJJIJIIIJIJJJIJIIJIIJIIJI()
	{
	}

	public void IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI(Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Vector3 IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}

	public void JJIIIIJJIIIIJIIIJJJJJIJJIIIIJIJIIIJJIIIJIIJIIJI()
	{
	}

	private void Start()
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	public void IIIJJIJJJJIJIIJJJJIIJJIIJJIJIJJIIJIJIIJJIIIIJIJ()
	{
	}
}
