using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class CameraFirstPerson : MonoBehaviour
{
	public class IJIIIJJJIJJIJIIJJIIIIIIJJJIJJJJIJJIJJIIIJJJIIJJ
	{
		public FPWeaponShooter JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ;

		public int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ;

		public IIJJJJJJJJIIJJIIJJIJIIJIJJIIJIJJJJJIJJIJIJJIJJI IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII;
	}

	public CameraManager IIJIIJIIJIIIIIJJIIIIIIJJJJJJJJIIJIIJJIIJJJJIJIJ;

	[HideInInspector]
	public Camera JJIIIJJIJIJIJIIIIJIJJJIIJJJIJJJJJJIIJIIIJIIIIII;

	public GameObject IIJIJIIIJIJJIJJIJIIIIJJJIIJJJJIJIJJJIJIJIIJIIJI;

	public Vector3 IJJJIJIJIIJJJIJJJIJIIJJIJIJJJJJIIJJIIJJIJJJJIIJ;

	private ControllerManager IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

	private int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ;

	private List<IJIIIJJJIJJIJIIJJIIIIIIJJJIJJJJIJJIJJIIIJJJIIJJ> JIJIJIJIJJJJJJJIJJJIJIIIJJJIIIJIJJIIIIJJIJJIIIJ;

	private IJIIIJJJIJJIJIIJJIIIIIIJJJIJJJJIJJIJJIIIJJJIIJJ JJIIIJJJJIJIJJIIIIJJJJJIIIIIIJJIIJIJIJIIJIIJIII;

	private Transform IJIJIIIJIIJJJJJIJJJIIJIJJJIJJJIIJIIJIIIJJJJIIJI;

	private bool JIIJIJJIIJIJIIIJIIIJIJJIIJJJIJIJIJIIIJIJJIJIIJJ;

	private int JJJIIIIJJIIIJIIJJIIIJIIJIIJIJJIJIIJIJIJIJIJIJJJ;

	private float IJJJIIIJIIJJIIIIJJJJJIJJIJIIIIIIJJJIJJJIIIJJJJI;

	private void Start()
	{
	}

	private void JIJIJIIIJJIIIIJIJIJIIIIJJJIJIJIIJIJIJJIJJIJJJII(bool IIIJIIJJIJIJIIIJJJIJJJIIJJIIJIJIIIIIJIIJIJIIJJJ)
	{
	}

	private void IJIJIJIIIIIIIJIIIJIJJIIIJIIIIJIIIJJIIIJIJIJJIIJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII()
	{
	}

	private void IJIIJIIIJIIJIJJJIIJIJJIJIJIJIIJJIIJIJIIJJIJIIJJ(ControllerManager JJIJJIJJJIIIIIIIJIIIJIJIJIIJJIJIIIJIIJIJIJIJIIJ)
	{
	}

	private void JJJIJJIJJJIJJIJIIIIJIJIJJIJJJIIIJIIJIIJJJJJIJJJ()
	{
	}

	private void JJJIIJJIJIJJJJIIJJJJJIJJIIIJJJIJIJJIIIJIIJIIJII()
	{
	}

	public void JIJIJIJJIIJIJJJIJJIIJIIJIJIIJJIIJIJIIIJJIIJJIJJ()
	{
	}

	private void JIJJIJJIIJJIJIJIIJJJJJJIIJJJJIJJJIJJIIIIIIJJJJI()
	{
	}

	private void IIJJIJJJJJIJJJJIJJIIJIIIJJJJJJJIIIJJJIIJJIIJJJI(bool IJJJIIJJIIIIJIJIJJJJIIJIJIIJIJIJIIIIIIIJIIJIIII)
	{
	}

	public void IJJIIIIIIIJJIIJIJJJJIJJIIIJJIIIJIIIJIJIJJJJIJJI()
	{
	}

	private void JIIIJIJJJJIJJIJJIIJJJIIJIIIIIJIIJJJJIIJIJJJIJJI()
	{
	}

	public void JJIIJJJIJJJIIJJJJIIJIIJIJJIIIJIIJIJJJIJIIIIJJIJ()
	{
	}

	public void JIJIJJIJIJIJIJJIJJIJIJJIIIJJJJIIJJJIIIJIJJJJIIJ()
	{
	}

	[CompilerGenerated]
	private void JJIIIIJIIJIIIIIJIIIIIJIIIJJJIIJIIIJJJJJJJJIJJII()
	{
	}

	public void JJJIJIJIIIJJJJJJIIIJJIIJIIIIJIJIIJIJJIJJIIIIIII()
	{
	}

	private void JIJJIJJIIIJIIJIJJJJIIJIJJJJJIJIJJIIIJJIJJJIIIJJ()
	{
	}

	private void OnDisable()
	{
	}

	private void JIIIIIIIJIJJIJIIIIJIIJIIJIJIJJJJJJJIJJIJJJJJJJJ()
	{
	}

	private void IJIIIIIIJJIJIJIJIJJIJJJJJIIIJJIJJJJIJJJIJIJIIJI(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
	}

	public void JJIIJJJIJJJIIJJJJIIJIIJIJJIIIJIIJIJJJIJIIIIJJIJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	private void JJIJJIJJJJJJJIIIJIIJIIJJJJIJIJJJIIIIJIJIJIIJIJJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
	}

	private void JJIIJJIIIJJIIIIJJJJJJJIJIJJIJJJJIJIJJIJJJIJJIJI()
	{
	}

	private void JIJIJIIIJIIJJIIIIIJJIJIIIIJJJIJIJJIJIJIIIIJIJJI()
	{
	}

	private IJIIIJJJIJJIJIIJJIIIIIIJJJIJJJJIJJIJJIIIJJJIIJJ JIIIJJIJJJJIIJIJIIIJJIIIJJIJJIJJIIJIIJJJIJIIIII(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return null;
	}

	private void IIJJIJJJJIJIJJIIIIIIJIJIIIJJIJJIIJIJIJIIIIJJJJJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, bool IJJJIJJIIIJIIIIIIJJJJJJJIIJIJJJJIJJIJIIJJIIJIII)
	{
	}

	private void IJIJIIJJJIIJJJIIIIJJIJIJJJIJJIIJJJJIIJIIJIJIJJJ(bool IIIJIIJJIJIJIIIJJJIJJJIIJJIIJIJIIIIIJIIJIJIIJJJ)
	{
	}

	private void JJIJJJIJJIIJIJIJIIIIJIIIIIIIIJIJIJJIJJIJJJIIJJJ()
	{
	}

	private void IIJIJIIIJJIIJJJIJJJIJJIJJIIJJIJIJIIIIJJIJJJJIIJ()
	{
	}

	private void JJIIIJIJJIJIJJIIJJIIJIIJIJJIJIJJIJJJIJIJIIJIIJJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	private void JIJJJJJIIIJJIJIJIIIIIIIIIJJIIIJIJIJJJJJIJJIIJJJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
	}

	public void IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI()
	{
	}

	private void IJJJIJIIJJJIIIJJJJIJJIJJJJJIIJJIJIJJJJIIIJJJIII(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	private void IIIIJIIIJIIIJJJJIIJIIIIIJIIJJIJIJJJIJIIJIIIJJJJ()
	{
	}

	private void IIJJIJJJJJIJJJJIJJIIJIIIJJJJJJJIIIJJJIIJJIIJJJI()
	{
	}

	public void IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	private void IJIIIIJJJJIIJIIIIIIJIIIIJIIIIJIJJJIIIIJJJJIIJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void OnEnable()
	{
	}

	private void JJJJJIIIJJIJIJJJIJIIJIJJJJJJIJJJIIJJIJJIIIIIJIJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, bool IIIJIIJJIJIJIIIJJJIJJJIIJJIIJIJIIIIIJIIJIJIIJJJ)
	{
	}

	public void IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI(object[] JIJIJIJIIIIJIJIIIIIIJJIJIJJIIJJIIIJJIIJJIJJIJJJ)
	{
	}

	private void IJIIIJJJIIJIIIIIJJJIJJJIJJJJJIIJIJJIIJIIJJIIJJJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
	}

	public void JIJIIIIIIJIIIIJIIJJIIIIJJJIJIIIIIIIIJIIIJIIIIII()
	{
	}

	private void JIJIIJJJIIJIIIIIIIIIJIIJIJIIJJIJJJIJIIIJJJIIJII(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public void IIJJIJJIIIIJJIIIJJIIIJIJIIIJJIJIIIJIJJJIJIIIJIJ()
	{
	}
}
