using UnityEngine;

public class CameraSpectate : MonoBehaviour
{
	public CameraManager IIJIIJIIJIIIIIJJIIIIIIJJJJJJJJIIJIIJJIIJJJJIJIJ;

	public float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ;

	public float IIIJJIJIIIJIJIIIJJJIJJIJIJJJJJJIJIJJJIIJJJIJIIJ;

	public float IIJJJIIJJJIIIJJIIIJJJIJJIIJIJIJIIIIJJJIIJIIJIJJ;

	public float IJIIJIIIJIJJIJJIIIJIJJIJJIJIIIIJIJIJJJJJIIIIJII;

	private int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ;

	private Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

	private Vector2 JIJIJJJJJIIIJIJJIJIIJJIIJJIJJIJJIJJJIJJJIJIIJJJ;

	private Vector3 JJIIJJIJJJIIJIIIIIJIJIJJIJIJIJIJJJJIIJIIIIIIJJI;

	private Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII;

	private RaycastHit JJIIJJJJIIJIIIJIIIJJJIIJIJIIIJIJJIJJIIIJIJIJJJJ;

	private Transform IJIJIIIJIIJJJJJIJJJIIJIJJJIJJJIIJIIJIIIJJJJIIJI;

	private int JJJIIIIJJIIIJIIJJIIIJIIJIIJIJJIJIIJIJIJIJIJIJJJ;

	public void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII()
	{
	}

	public void JJJIJIJIIIJJJJJJIIIJJIIJIIIIJIJIIJIJJIJJIIIIIII()
	{
	}

	private void IJIIJIIIJIIJIJJJIIJIJJIJIJIJIIJJIIJIJIIJJIJIIJJ(ControllerManager JJIJJIJJJIIIIIIIJIIIJIJIJIIJJIJIIIJIIJIJIJIJIIJ)
	{
	}

	private void JJIJJJIIJIIJIIJJJJJIIIIIJIIJIIIJIIJIJIJJIJJIJIJ()
	{
	}

	private void IJIJJJIJIIIJIJJJIJJIIJJIJIIJIJIIIIJJIJIJIIJJJJI()
	{
	}

	public void IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI(object[] JIJIJIJIIIIJIJIIIIIIJJIJIJJIIJJIIIJJIIJJIJJIJJJ)
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void IJIJJIJIJJIJIJJJJJJIIJIIJJJJIJIIJJIIIJJIJJIJIJJ()
	{
	}

	public void IIIJJJJJIJIIIJIJJJIIIJJJIIJJIIJIJJIIIJIIIJJIJJI(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	private void OnDisable()
	{
	}

	private void JIIIJIJJJJIJJIJJIIJJJIIJIIIIIJIIJJJJIIJIJJJIJJI()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	public void JIJIJJJJJIIIIIIIJIIIIIIJJJIIIJJIIIIJJIIIJIIIJII(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public void JJIIJJJIJJJIIJJJJIIJIIJIJJIIIJIIJIJJJIJIIIIJJIJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	private void IJIIIIIIJJJIJIIJJJJIIJIIJJIJJIIJIIJIJJIIIIIIJIJ(ControllerManager JJIJJIJJJIIIIIIIJIIIJIJIJIIJJIJIIIJIIJIJIJIJIIJ)
	{
	}

	private void OnEnable()
	{
	}

	private void IIJJIIIJJJIIIIIIIIIJIIIIJJJIIIJJJIIIIIIIJJJIIIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IIJJJJJIIIIJIJIIIJIIJJJIJIIIJJIJJIJIJIJIIIJIIJI()
	{
	}

	private void Start()
	{
	}

	private void IIIJJJIJIIIJJIJIIJJIIIIJIIIJJJIIIIIJIIIJJIIJJII()
	{
	}

	private void IJJIIIJJJIJIJIIJIIIJJIIJJJJJIIJJIIIIIJIIIIIIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IJIIIIJJJJIIJIIIIIIJIIIIJIIIIJIJJJIIIIJJJJIIJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public void JJIIJJJIJJJIIJJJJIIJIIJIJJIIIJIIJIJJJIJIIIIJJIJ()
	{
	}

	public void IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public void IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI()
	{
	}

	private float IJJJJIIIJIJJIJJIIJIIIJIIJJIIIIJJJJIJIJIJJIIIIII(float IIJJJIJIJJJIIJIIIJIJJJIJJIIJIJIIJJIIJIJJIJJJJIJ, float JJJJIJIIJIJJIIJJJIIJIJJIJIIIJJJIJIJIIJJIIJIJIJJ, float IJIIJJIJIJIJIIJJJIJIIIJIJIIJIJJIIIIJIIIJIIIIIJJ)
	{
		return 0f;
	}
}
