using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class CameraManager : MonoBehaviour
{
	private static Action<int> JIJJJIJIJIIJJIIIIJIJIJJJIJJIJJIIIJJJIJIIIJJJJIJ__BackingField;

	public IJIJIIJIIJIJJIJJIJIJIJIIJJJJIJJIJJJJJIJIIJJJIIJ IIIJIJJJIJJIJJIIJJIJJJJJJJJIJJIJJJIIJJJJJIJIJIJ;

	public Camera JIJIJJJIJJIJIJIIIJIIIIIJJIIJJIIIIIIIIIJJJJJIIIJ;

	public Transform IJIJIIIJIIJJJJJIJJJIIJIJJJIJJJIIJIIJIIIJJJJIIJI;

	public Transform JIIJJIJJIIJIJJJIIIIJJIJIIIJIIIIIJIIJJIIJIJJIJJI;

	public CameraDead IJJJIJJIIIJIIIIIIJJJJJJJIIJIJJJJIJJIJIIJJIIJIII;

	public CameraStatic JJJJIJIJJIIIJJIIJIIJJIIJIIIJIIIIJJJJJJJIJJIIIII;

	public CameraSpectate JJJIJIIIJIJIIJIJIJIIIJJJIIIJIIJJJIIIIIIIJIIJJII;

	public CameraFirstPerson IIIJJIJIIJJJJJIIJJIJIJJJJJIJJJIJJIIIJJJIJIIIIIJ;

	private int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ;

	private static CameraManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static bool JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ;

	public static bool JIIJJJJJJJJIIJJJJJIJIJIIIJJIIJJIJIIJJIJIIIIJJII;

	public static int IJJIJIJJIJIIJIJJIIIIIJIJJJIIIJIIIJIJIJIIJJJIIIJ
	{
		get
		{
			return JIIIJJJIJJJJIJJJIJIIJJJJIIIJJIIJIIJIIJJIJIJIIJI();
		}
		set
		{
			IIIJIJJJIJJJJIIJJJIJIJIJJIJJIIIJJJIJIIJIIJJIIII(value);
		}
	}

	public static IJIJIIJIIJIJJIJJIJIJIJIIJJJJIJJIJJJJJIJIIJJJIIJ JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI => IJJJIJIJIIIJJJIIIJJIJIJJJJJJJIIIIIIIIJIIIIJJJIJ();

	public static Camera JJJIIJIJIIJJJIJJIIJIIJJJIIIIIJJJJJIIIIIIIJIIJJI => IIIIJJIJJJIIJIIIJIIIIJIJJIIJIIIJIIIIIIJJJIJJIII();

	public static Transform IJJIJIJIJJIJIJIIJIJJIJJJIIJIIJIJJIJJIJJIIJIIJJI => JIJIJIJJIIJIJJJJIJJJIIJJIJIIJJIJJJJJJIIJIJJIIJI();

	public static CameraManager JIJIIIJIJIIJIIIIJIIIIJJIJJIJIJJJIJJJJIJIIIIJIII => IJJIJIIJJIJJJIJJIJIIIJJIIIJJIJIIIIJJIIIJJJIIJJJ();

	public static event Action<int> JIJJJIJIJIIJJIIIIJIJIJJJIJJIJJIIIJJJIJIIIJJJJIJ
	{
		add
		{
			IJIJIJIIJJIIJJJIJIIIIIIIJIIIIJJIJJIJIJJJIJJIJJJ(value);
		}
		remove
		{
			JIIJJIIJJIJIIJIIIIJJIIJIJJIIIIIIIIJJJJIJJIJIJJI(value);
		}
	}

	public void JJIIIIIIIIJJJJIJIIIIIIJJJJJJIJJJIIJJJIIJJIJJIIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	public static void JIIJIIIJIJIJIIIIJJIIJJIJIJJIIIJJJIIJIJIJJJIJJJI(IJIJIIJIIJIJJIJJIJIJIJIIJJJJIJJIJJJJJIJIIJJJIIJ JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI, object[] JIJIJIJIIIIJIJIIIIIIJJIJIJJIIJJIIIJJIIJJIJJIJJJ)
	{
	}

	public static Transform JIJIJIJJIIJIJJJJIJJJIIJJIJIIJJIJJJJJJIIJIJJIIJI()
	{
		return null;
	}

	private void Awake()
	{
	}

	public void IIIIJJJJIIJIJJIJIIJIJIIIJJJJIJJJIJJJIJIJIJIIIJJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private void IIJJIIIIJIIJJJJJIJIIIJJIJJJJIIIIIIIIIJIJIIIIIII()
	{
	}

	public void JIIIJIJIIIJIIJJIIJIJJIJJIIIIJIJJIIJIJJIJIIIJJII(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	public static void JIIJJIIJJIJIIJIIIIJJIIJIJJIIIIIIIIJJJJIJJIJIJJI(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static CameraManager IJJIJIIJJIJJJIJJIJIIIJJIIIJJIJIIIIJJIIIJJJIIJJJ()
	{
		return null;
	}

	public static void IIIIIJIIIJIJIJJIIIJIJIJJJIIIIJIIJJIJIIIJJIIIJIJ(IJIJIIJIIJIJJIJJIJIJIJIIJJJJIJJIJJJJJIJIIJJJIIJ JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI, object[] JIJIJIJIIIIJIJIIIIIIJJIJIJJIIJJIIIJJIIJJIJJIJJJ)
	{
	}

	public static void IIIJIJJJIJJJJIIJJJIJIJIJJIJJIIIJJJIJIIJIIJJIIII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void IIIJJJIJJJJJJJJJJJJIIIIIIJIIJJJJJJJIJIIIJJJIIJJ(IJIJIIJIIJIJJIJJIJIJIJIIJJJJIJJIJJJJJIJIIJJJIIJ JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI, params object[] JIJIJIJIIIIJIJIIIIIIJJIJIJJIIJJIIIJJIIJJIJJIJJJ)
	{
	}

	private void OnDisable()
	{
	}

	private void LateUpdate()
	{
	}

	public static Camera IIIIJJIJJJIIJIIIJIIIIJIJJIIJIIIJIIIIIIJJJIJJIII()
	{
		return null;
	}

	private void JIJIJIIJJIIJJIJIIIIIJJJJJJJIIJIIIJJJIIIJIJJIIJJ()
	{
	}

	public static void JJIIIJJIJIJJJIJIJJIJJIIJIJJIJJJJJIIIIIJJJJIJJJJ(IJIJIIJIIJIJJIJJIJIJIJIIJJJJIJJIJJJJJIJIIJJJIIJ JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI, object[] JIJIJIJIIIIJIJIIIIIIJJIJIJJIIJJIIIJJIIJJIJJIJJJ)
	{
	}

	public static IJIJIIJIIJIJJIJJIJIJIJIIJJJJIJJIJJJJJIJIIJJJIIJ IJJJIJIJIIIJJJIIIJJIJIJJJJJJJIIIIIIIIJIIIIJJJIJ()
	{
		return IJIJIIJIIJIJJIJJIJIJIJIIJJJJIJJIJJJJJIJIIJJJIIJ.None;
	}

	private void IJJJIIJJJJJIIJJJIJJJJIJJJJIJIJIIJIJJJJJIIIJJIII()
	{
	}
	public static void JJJIIIJIJJIIJJJJIJIJIIJIJJIJIJIJJIJIIIJIIJJIJJJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static void JJJJIIJJJJJIJJIJJIIIJIIIJIJJIJIIIIJIIIJIJIJIIIJ(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static Transform IIJJJJIJJIIIJIJJIJJJIJJIJJIIJJIIJIJJJIJJJJJJIJI()
	{
		return null;
	}

	public static void IJIJIJIIJJIIJJJIJIIIIIIIJIIIIJJIJJIJIJJJIJJIJJJ(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static int JIIIJJJIJJJJIJJJIJIIJJJJIIIJJIIJIIJIIJJIJIJIIJI()
	{
		return 0;
	}
}
