using UnityEngine;

public class CaptureTheFlagManager : MonoBehaviour
{
	private enum IJIJIJJJIJJJJIIIJJJIIIIJJJIIIIJJIIIIIIJIJIJJJJJ
	{
		Base = 0,
		Lost = 1,
		Stolen = 2
	}

	private class IJJIJIJIIIJJIIJIJIJJIIJIIIJIJIIIJJIIIIJIJIJIIIJ
	{
		public GameObject JIIIIIIJIJIJIIJJJIIIJIJIJIIJJJIJIIIJIIIJIIIIIII;

		public GameObject IIJJJIIJIJIIIIIJIJIIIJJJJJIJJJJJIIJJIIIIIIIIIIJ;

		public int IIIJIJJIIIJJIJJJIJJIIJIIIJIJJJJIJJJJIJIJJIJIJJI;

		public IJIJIJJJIJJJJIIIJJJIIIIJJJIIIIJJIIIIIIJIJIJJJJJ JJIIIIIJJIIJJIJJIIIIIJIJIIIIJIIJJJJIIIIIIIIJIII;
	}

	public GameObject IIJJJIJJJIJIJIJIIIIJIIJJJIIJJIJJIJJIIJJIIIJIJIJ;

	public static CaptureTheFlagManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private IJJIJIJIIIJJIIJIJIJJIIJIIIJIJIIIJJIIIIJIJIJIIIJ[] JIIJIIJIIJIJJIIIIJIJIJJJIJIJJIJIJJIIIJIJJJIIIJI;

	private void IJJIJIIJIIIJIJJJJJIJIIIJJIJIJIIJIJJJIIJIJIIIIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJJJJIIJIJIIJIIIIIJIIJJIJIIJIJJIJJIJIJIIIIIJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private int JJIJJIJJJIIJJJIIJJIJJJIIJJJJJIIIIJJJIIIIIIIIJJJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
		return 0;
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJIIIJIJIJJJJJIJIIIIIJIIJIJIJIJIJIIJJJIJJIJJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private Vector3 IJJJIIJJJJJJJIIJJJIJJIJIIIIIJIJJJIIJJIIJIIIIJJI(Vector3 IJIJIJJJIIJJIJJJJIJIJIJJJIJIIJJIIIJIIJJJJIIJIJI)
	{
		return default;
	}

	public void JIJIIIJJJJIJIIIJJJJJIJIIJJIIJIJIIJJJIIJJIIIJIII(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIIJJIIIIIJIIIIJIJJIJJJJIJJJJIIJJJJJIJIIIIIIJIJ)
	{
	}

	private void IIJJJIJIIIJIIIJJJJIIIIJIJJIJIIIIJJJIIIJIIIIIJII()
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void Awake()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIIIIIJJJJIIJJIJJIJJIJIIIIJJJJJJJJJIIIJJJJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private int JJIIIIIJIIJJJIIIIJIIIJJJJJJIJIJIIJJIJIIIIIJJIJJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
		return 0;
	}

	private void IIJIJIIIJIJJJJIJJJIIJIJJJIIIIIJIIJIIJIJIJIIIIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void OnPhotonPlayerConnected(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJIJIIIIIJJJIIJJJJIJJJIJJJIIJIJJJIJJJIIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJJIIIJIJJJJIJJIJJIIJIIJJJIIJJIJJJIJJIJIIJJIJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJJIJIIJIJIJJJJIIJIIIJJIJJJIIIIJJJIIJIJJIIIJIJ()
	{
	}

	public void JIIJJJIIIJJIJJIJIIJJIIIIIJIIJJIIIIJJIJIJJJIIJIJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IJJJJIJJIJJJJIIIIIIIJJIJIIIJIIIJIIIJJIJJIJIIJII)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJJJIIJJIJIJIJJIJIIIIJJIJJIIIJIIIIJIIJIJIIIIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJJJJJJJJIIIJIIIJJJIIIIIIJJIIIJJJIIIJJJIIIIIJI(int IJJIIJIJIJIIIJIJIJIIJIJJJJJJIJJIIJJIIIJJIJJJIJI, int JIJIJIIJJIJIIIJJIIJJIIIIIJJIIIIIJIIJJJJIJJJIIJJ)
	{
	}

	private void OnDisable()
	{
	}

	private void JIJJJIIIIJIJIIJIJIJJIIJIIIIIIJIIIJIIJIJJJJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnEnable()
	{
	}

	private void JJIJIIIJJIJIJJIIJJIIIIIJIIIIJIJJJJIIIJJJIJJJJJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void IIIIIIIJJJJIIJJJJJIIJJJJIJJJIIIIIJIIIIIJIIJJIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJIIIJIJIIJJJIJIJIJJJJJJJIIIJJJIJIJIIJJIIIIIIJ(int IJJIIJIJIJIIIJIJIJIIJIJJJJJJIJJIIJJIIIJJIJJJIJI, Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Quaternion IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIJIIJIJIJIIIJJIIJIJJIJJIJIJJIIJJJIIJJJJIIJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJJJIIIJIJJIJIJJIIIJJIIJIJJJJIIIJJIIIJJJIIIIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJIIJJJJIJJJJJIIJIIJIIIJJIIIJJJJIJIJJJJIJJJIJIJ(int IJJIIJIJIJIIIJIJIJIIJIJJJJJJIJJIIJJIIIJJIJJJIJI, Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Quaternion IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII)
	{
	}

	private JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ JJIIIIJJIIJJJJJIIJJJIIIJJIIJJJIJJIJJIIIIJIIJIJI()
	{
		return JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ.None;
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIIJJIIJIIIIIIJIJJJIIJJIIIIIIIJIJJIJIJIJIIIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void Start()
	{
	}

	private void IJIJJIJIJJJJJIJJJJIJIJJIIIIJIJIIJJJIJJJJIJJIJII(int IJJIIJIJIJIIIJIJIJIIJIJJJJJJIJJIIJJIIIJJIJJJIJI, int JIJIIIIIIIJIIIJJIJJIIJJIJJJIIIJIJIJIIJJIIJJJJJJ)
	{
	}

	private Vector3 IIJIJIJJIIIIJJIIIJIJIJJJJIJIIJIJIIIJJIIIIJIIIII(Vector3 IJIJIJJJIIJJIJJJJIJIJIJJJIJIIJJIIIJIIJJJJIIJIJI)
	{
		return default;
	}

	private void IJJJJIIJJJIJJIIIIIJJIIJJJJJIJJIJJIIIJIJJJIJIJJJ(int IJJIIJIJIJIIIJIJIJIIJIJJJJJJIJJIIJJIIIJJIJJJIJI, int JIJIJIIJJIJIIIJJIIJJIIIIIJJIIIIIJIIJJJJIJJJIIJJ)
	{
	}

	private void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJIJJJJJJJJJJJJJIIJJIJJJIIJIJJIIJJJIIIJJIJIJJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void IIJIIIJIJJJJIIIIIIJIIIJIJIJIJJIIIIIIJJIJJIJJIII()
	{
	}

	private void IJJJIIIJJJJJIJJJJJIJIIJJIJJIIJIJIJJJJIIJIJJJJJI(int IJJIIJIJIJIIIJIJIJIIJIJJJJJJIJJIIJJIIIJJIJJJIJI, int JIJIIIIIIIJIIIJJIJJIIJJIJJJIIIJIJIJIIJJIIJJJJJJ)
	{
	}
}
