using System.Runtime.CompilerServices;
using Photon;

public class CaptureTheFlagMode : MonoBehaviour
{
	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IIIJIJIIJIJJIJJJIJJIIJJIIIJIJIJIJJJIJJIJIJJIIII;

	public static CaptureTheFlagMode JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	[CompilerGenerated]
	private void IIJIJJIJIJIIIIIJJJIJIIIIJJJJJIJIJIIIJJJJJJIJJIJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIJJJIJJJJIJIJIIJIIJJJIIJIJIIIIIJIJIJIJIJIJJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void IIIJJJIJJJJJIJJJIIIIJJIJIIIJJIIJIJIJIIJJJJJJIIJ()
	{
	}

	private void IIJIIJIIIJIJIJJIJIJJIJIIJJJIIIIJJIIJIIJJJJJJIJI(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void OnEnable()
	{
	}

	private void Awake()
	{
	}

	private void JJJIJJJJIJIJIJIJIJIJJIJIJJJIIJJIIJJJJIIJIIJJIJI()
	{
	}

	private void OnDisable()
	{
	}

	private void JJJJIIIIIJIJJJIJJIIIIIJIIJIIJJIJIJJJJJJIIJJJJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void IJJJIIIJIJIJIJJJIIIIJJIIJIJJIJJIIJJJIIJJJIJIJII()
	{
	}

	private void JIIJJIJIIIIIJIIIIIIIJJJJIIJIJJIIIJJIIIJJIIJIJJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void IIJIJJIIJJJIIIIIJJIIJIJJJJJJIIJIIJJJIIJIIIIJIJI(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void IIJIIJIJJIIJIJIJIJIJIIIJJIIIIJIJJJIIJJJJJJIJJJI(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void JJJIJJJJJIIJIJJJIJIIIIJJIJJJIJIIJJIIJIIJJJJIIJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJJJIIIIJIIIIIJJIIJIIIJIJJJJJJJJJIIJIIIIIIJIJJ()
	{
	}

	private void JIIJJIJJIJJJIIIIIIIIIJIJIIJIJIJJIIIIJJJJJIJJIJI()
	{
	}

	private void JIIIIIIJJIIJJJIJJIJJJIIJIJJJJIIIJIIJIJIJJIIIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIIIJIJIJIIJIIIIJIJJIIIIIIIIJJJJIIJIJJJJIIJIII()
	{
	}

	private void IIIJJIJJJJJJJJIIJJIJJJIJJIIIIJIIIJJIIIIIIJJJJJJ()
	{
	}

	private JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII[] IJJIJJJIJJJIIJJIIIJIIIIIIIJIIJJJIJJIIJIJIIIIIJJ()
	{
		return null;
	}

	[CompilerGenerated]
	private void IJIIIJIIJIIIJIJJIJIJJJIJIJJIIIJIIJJIJIJIIJJJIJJ()
	{
	}

	private void JJJIJJJIJIJJJJIJJJJIIIIJJIIIJJJIJJJIIJJIJJIIJII(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void Start()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIIIJIIIJJJJJJIJIIIIJJJJIIJIIIJJIJIJIIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJIJIJJIJJJIIJJIJJJJJIIJJIJIIIIJIIJIIJIJJJJJJJI()
	{
	}

	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII()
	{
	}

	[CompilerGenerated]
	private void IIIJIIJJJJIJIJIIJJJJJJIJJJJIJIJJIIIIIJJJIIIJJJJ()
	{
	}

	private void IIIJJIJIIJJJIIJIIIJIJJJIJJIIIIJJIIJJJJJIIIJJJII()
	{
	}

	private void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	public void IJIIIJJIIJIIJIJJJIIIIJJJIJJJJIJIIIIIJJIIJIIJIIJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ JJIJIJJIJIJIJJIJJJJIIJJIIJIIIIIIJIJJJJIIJJIIJIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJJIJIJIJIJJJJJIJJIIIIIIIJJIIIJJIIJJJIJIIJJJII()
	{
	}

	[CompilerGenerated]
	private void IIIJJJJIIIJIJJIJJIIJIJIJIIIIJJJIIIJIIIJJIJJJJIJ()
	{
	}
}
