using UnityEngine;

public class CaptureTheFlagTrigger : MonoBehaviour
{
	public enum JIJIIJJJJIIIIIIJIJJJJIJJJIJIIIJIIIIIIIIIIJIJJII
	{
		BaseOfFlag = 0,
		Flag = 1
	}

	public JIJIIJJJJIIIIIIJIJJJJIJJJIJIIIJIIIIIIIIIIJIJJII IJIJIJJJJJJIIJJIIJJIJJJJIJIIJIIIJIIIJIJIJJJJJJI;

	public JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IJIIJIIJJJIJJIJIJIIJIJIJIIIIJJIIJJIIIJIJIJIJIJI;

	private void JJIJJJJJJJIIJJJJIIIJJJJIJIIJIIIIIJIIIJIIJIJIJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIIIIJIJJIIIIJIIIIJIJJJIJJJJJIJIIJIIJJJIIJJIIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJIJJIIIJIJIJIIJJIJJJIJIJJIJIIIIJIIIJIJJIIIJIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIJJJIJIJIIIJIJIJIIIJIIIJIJJIJIIJIJIIJIIIJJJJIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJJJIJIJJIIIJJIJJJJJJJIJIJIIIIJJJJIIJIJJJIIJJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIIIJIJIJJIIJIIIIJIJIJIJIJIIJIJIJJIJJJJJIIIJIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIJJIIJIIIJJJIIJJJJJJJIJIJIJJJIIIIIJIJJIIIIIJIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJIIJIJJJJJIJJJJIIJIJJJJIJJJIIJJJIJJJIIJJIIIIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIIJJIIIIIIJIIJIJIIJJIJJJIJIJJJIJJJJIIJJJIJJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJJIJJIIIJIJJIIIIJIJJIJIJJJIJJIIIJJIJJIJJJJJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}
}
