using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class CheckManager : MonoBehaviour
{
	private sealed class IJIJIIIJIIJJJIJIJIIJJJJJIJIIJJJIJJIIJJIIIJIJIIJ
	{
		public string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI;

		internal void IJJIIIIJIIIJIIIIJJIIIIJIIIIJJJJJIIJIIJIIJJJJJII()
		{
		}

		internal void JIJJJJIIJJIIIIJIIIIIJIJIJJIJJJJJIJJJIJIJJJIJIII()
		{
		}

		internal void IJIIJJIIJJJIJJJIJIIIIJJIJIJJIJJJJIJJIJJIIIJJJJJ()
		{
		}

		internal void JJIIJJIIJIIIIIJJJIIIJJIJJIJJIJJJJJJJIJJJIIIJJII()
		{
		}

		internal void IJIJJIJJJIJJJIJIJJJIJIIJJJJIIIJJIIJIJIIJIJJIIJI()
		{
		}

		internal void JJJIJIIJIJIJJIJJIJJIIIIJJJIIJIIIJIIJIJIJJJJJJIJ()
		{
		}

		internal void IIJJIJIJJIIIJIIJIJJIIJJIJJJIIIJIIIJJJIIJJJIJIJJ()
		{
		}

		internal void JJJJJIIIJIIIIJJIIIIIIJJIJJIIIIIJJJIIIIJJJJIJJIJ()
		{
		}

		internal void JJJJJJIJIJJJIIIJIIIIJJJIIIJJJIJIJIJJIIJIIIJJIJI()
		{
		}

		internal void IIIJIJJJIJJIIIIIIIIJJJJJIJJJIJJJIIIIJJIIIIJJIII()
		{
		}

		internal void JIJIJIJJJIIJIJJJIJJIIJJJIJJJJJJJJJJIIIJJJJIJJII()
		{
		}

		internal void JIIJJIIIJJJIJJIJIIIIIJIJJJIJJIIIJIIJJJIIJJJJIJJ()
		{
		}

		internal void JIIIJJJIIIJIIJJJIIIIJJJIIJJJJJJJIIIIJJIJIIIJIIJ()
		{
		}

		internal void IIJJIIIJJIJJIIJIIJJJJJIJIIIJJIIJIIJIJIJIJJIJJIJ()
		{
		}
	}

	private sealed class IIIIIJJIJJIIIIJJIIJJIJJJJJJJJIIJIIIIJJJIJJIJIJJ
	{
		public string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI;

		public string JIJIJJJIIIIJIJJIJJJIIJIIIIIIIIJJJJJJIIJJIIIJJJI;

		internal void JJJIJIIJIJIJJIJJIJJIIIIJJJIIJIIIJIIJIJIJJJJJJIJ()
		{
		}

		internal void IJIIIIJJJJIIIIJIIIJIJJIJJJJIJIIJIIJJIIIJIIJJIJJ()
		{
		}

		internal void IJIIJJIIJJJIJJJIJIIIIJJIJIJJIJJJJIJJIJJIIIJJJJJ()
		{
		}

		internal void IJJIIIIJIIIJIIIIJJIIIIJIIIIJJJJJIIJIIJIIJJJJJII()
		{
		}

		internal void IIJJIJIJJIIIJIIJIJJIIJJIJJJIIIJIIIJJJIIJJJIJIJJ()
		{
		}

		internal void JJIIJJIIJIIIIIJJJIIIJJIJJIJJIJJJJJJJIJJJIIIJJII()
		{
		}

		internal void JIIJJIIJIJJIJJIJJIJIIJJIJJIJJJJJIJJIJJJJJJJIJJJ()
		{
		}

		internal void IIJJJJJIJJIIIJJIIJJIJJIJIJIJJIIJJIJIJJJJJJJIJJJ()
		{
		}

		internal void IIIJIJJJIJJIIIIIIIIJJJJJIJJJIJJJIIIIJJIIIIJJIII()
		{
		}

		internal void JJJJJJIJIJJJIIIJIIIIJJJIIIJJJIJIJIJJIIJIIIJJIJI()
		{
		}

		internal void IIJJIJIJIIJIIIIIIIJIJIIIJIIIIIJIJJIJJJJJJJIJIJJ()
		{
		}

		internal void JIIIJJJIIIJIIJJJIIIIJJJIIJJJJJJJIIIIJJIJIIIJIIJ()
		{
		}

		internal void JIJIJIJJJIIJIJJJIJJIIJJJIJJJJJJJJJJIIIJJJJIJJII()
		{
		}

		internal void IJIJJIJJJIJJJIJIJJJIJIIJJJJIIIJJIIJIJIIJIJJIIJI()
		{
		}

		internal void IIJJIIIJJIJJIIJIIJJJJJIJIIIJJIIJIIJIJIJIJJIJJIJ()
		{
		}

		internal void JJJJJIIIJIIIIJJIIIIIIJJIJJIIIIIJJJIIIIJJJJIJJIJ()
		{
		}

		internal void JIJJJJIIJJIIIIJIIIIIJIJIJJIJJJJJIJJJIJIJJJIJIII()
		{
		}

		internal void JIIJJIIIJJJIJJIJIIIIIJIJJJIJJIIIJIIJJJIIJJJJIJJ()
		{
		}

		internal void IIIIJIIIJIJJIIIJIIJIJIIJJJJJJJJJJIIJIIIIIJIIIJI()
		{
		}
	}

	private sealed class JJJIJJIJJJIJJJIIJIIJIIJJIJIIJJIJJJJIJJJJJJJIIII
	{
		public string[] JJJIIJJJIJJJJIJJJJIJJJJJIIJJJJIIJIJIIJIJIIJIJJI;

		public string IIIJIIJIJJIJJJIIJIIJJIIIIJJIJJIJJJJJIIJIJJIJJJJ;

		public TimerManager.Callback JIJJJJIJJJJIJIIJJJIIJIJJIIIJIIIIJIIIIIJJJIJIJIJ;

		public Action JIIIJIIIIIIJIIJIIJJIJJJJJIIJJJJJJJJJIIIIIJIIJJI;

		internal void JIIJIIIIJJIJIJJJJJJJIIIIIIIIIIIJJJIJIIJIJJJJJIJ()
		{
		}

		internal void JJJJJIIJJIIJIIJJJJJIJJJJJIJIJIJIIIIIJJJJIJJJJJI()
		{
		}

		internal void IJJIJIJIJIJIIJJIJIJJJJJJJJJJJIIIJIJIJJJIIIJJJII()
		{
		}

		internal void JIIJIJJJJJJJJIIJJJIIJJJIIJIJJIJJIJJJJIJJJIJIIJJ()
		{
		}

		internal void JJJIJIJJIIJIIIIIJIJJIIIJJJIIJIIJJIJJIIIJJJJIJJI()
		{
		}

		internal void IJIJJJJIJJJJIIIJJJJJJIIIJJJJIJIJJIIIIIIIJJJIJIJ()
		{
		}

		internal void IIJIIIJIJIIIJIIIIJIIIIJJJIJIJIIIIIIIIJJJIIJJJJJ()
		{
		}

		internal void IIJIIIIJJIJJIIIJIJIJIJJJIJIIIJIJJIIJJIIIIIJIJJI()
		{
		}

		internal void IJJJJJJIJIJIJJIIIJJJIJJJJJJIJIIJIIJIJJJJJIJJIJI()
		{
		}

		internal void JIJJIIJJJIIIJJIJJIJIJJJIJIIIJJJIJIJIJIJJIIJJIJI()
		{
		}

		internal void JJJJIJIJJJJIJIIIIJJIJIJIIIJIJIJIJJJJIIIJJJIJIJJ()
		{
		}

		internal void IIJIJJIJIIIJIJJJJIIJIJIIJIJJIJJJIIJIIJJIIJIJJJI()
		{
		}

		internal void JJJIIIJIJJJIJJJIJIJJJJJIJJIIJIJIIJJJIJJIJJJJIII()
		{
		}

		internal void IJJJJIJJIIJJJIIIIJJIJIJJIJJJIJJJJIIIJIIIJIJIIJI()
		{
		}

		internal void IJIJIJJJJJIJJIIJJIIIJIIIJJJIIJJJIIIJIJIIIJJIJIJ()
		{
		}

		internal void IJJIJIJJJIIIJIIJIJIJIJJIIIJJIIJIJIIJIJJIIIJIIJI()
		{
		}

		internal void JIIIIJIJIIJJJJIIJIIIJJIIIJIJJIJJJJJIIJJJJJIJJIJ()
		{
		}

		internal void JIJIJIIJIIIIIJIJJIIIJJJJJJIIJJJIJIIJJJIIIIIJIII()
		{
		}

		internal void IIIIIIJJJIJJIIJJJIJIIJIJIIIIJIJJIJJJIIJJJJIIIJJ()
		{
		}

		internal void IJJJJJIJIJIIIIJJJJJJJJIIJJJJJJJJJJJIJIJIJIJIJII()
		{
		}

		internal void JJJJJJJJJIIJJIIJIIJJIJJJIJJIJIIJIJIIJIIJJJJJJIJ()
		{
		}
	}

	public static bool JIIJJIJIIIJIIJJJIIIIIJIIIIJIJJJJIIJJJIIIJIIIJJI;

	private List<string> IIJJJJJJJJIIJJJJJJIJIJIJJJIJIIIJIJIJIJIJIJIJJIJ;

	private void IJIIIJIJJJIJJJJIIIJJJIJJIIJIIJJIIIIJJJIJIJJIIIJ()
	{
	}

	private static bool JIJJJJJJJIJJIJIJJJJIIIIJJIIJIIIJIIIJIIJIIIJIJIJ(string IIJIJIIIIIJJIIIJJIIJJJIJJIIJJIJJJIIIIJJIJJIIJIJ, string IIIJJIJIJJJJJIIIIJIJJIJIIIJJJJJJIJIJIIJJJJIIIJJ)
	{
		return false;
	}

	public static void IIJJIJJJJIIJJJJJIJJIJIIJIIIJJJJIIIJIJIJJIJJJIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	[CompilerGenerated]
	private void IIIJJJJIIIIIJIJJIJJIIIJJIIJJJIIJIIIJJIIIIIIJIII()
	{
	}

	private void JJJJJJIIIIIIIJJJJJIIIIJJIIIIIIIJJJJIIIIIJJIJJJI()
	{
	}

	private void OnApplicationPause(bool JJJJIJJJJIIIIIJIJIJJIIIIJIIJJJIJIIIJJJIJJIIIIIJ)
	{
	}

	private void JIIIIIJJJIIIJIIJJIIIJIIIIIJIIJJIJIJJIIJIIIIIJJI()
	{
	}

	public static void IIJJIJJJJIIJJJJJIJJIJIIJIIIJJJJIIIJIJIJJIJJJIII()
	{
	}

	private void IJJJIIIJJJIIIJJJJIIIIIJIIIIJJJIIJJIIIIIJIJIIJIJ()
	{
	}

	private void Start()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	public static void IIIIIIJJIIJJIIJIIIJJJJJIIJIIIIJJJJJIIJIIIJJJIII()
	{
	}

	private static bool JJIIIIJIIIJJIIJJIIJIIJIJIIJJIJIIJJIIJJIIIJJJJJI(string IIJIJIIIIIJJIIIJJIIJJJIJJIIJJIJJJIIIIJJIJJIIJIJ, string IIIJJIJIJJJJJIIIIJIJJIJIIIJJJJJJIJIJIIJJJJIIIJJ)
	{
		return false;
	}

	private static bool IIJIIJJJIIIJIIIJJIJIJIJJJIIIJIJIJJIIJJJJJIJIJII(string JIJIIIJIIJJJJIJJIIJJIJIIJJJIIJIJIJIIJIIIIJIIIJJ)
	{
		return false;
	}

	private static bool IIIIIJIIJIIJIJJIIJIJJJIJIJIIIIIJIIIIIIIIIIJIIJI(string JIJIIIJIIJJJJIJJIIJJIJIIJJJIIJIJIJIIJIIIIJIIIJJ)
	{
		return false;
	}

	public static void IJJJJIJJJIJJIJJJJIJJJIJIJIIIJJIIJIIJJJIJIIIJIJI()
	{
	}

	public static void JJJJJIIIIJJIIIIIIIJIJJJJJJIJJJJIIJIIJJJIIIIIIJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void JJJJIJJIIJJJJJIIIJIJIJJJJJIIJJIJJJIIIJIJIIIIIJJ()
	{
	}

	private static bool JIIIIJJJJJJJIIIIJJIIJIJIJJIIJJJJIIJJIIIIJIJJIIJ(string JIJIIIJIIJJJJIJJIIJJIJIIJJJIIJIJIJIIJIIIIJIIIJJ)
	{
		return false;
	}

	public static void IIJJIJJJJIIJJJJJIJJIJIIJIIIJJJJIIIJIJIJJIJJJIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIIIIJIJJIJJJIIJIIIIIIIIJJJJJJIIJJIIIJJJI)
	{
	}

	public static void IIIJJIJIIIIJIJIJJJJJIIJJIJIJIIIIIJJJIJIJJIJIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void IJJIIIIJJJIIIIJIIIJIJIJJJJIIIJIIJJIIIJIIIIJJJIJ()
	{
	}

	public static void IIIIJIJJIIIIIJIIJJIJIIIJIIIJIIJIIIJJIJIJIIJIIII()
	{
	}

	public static void IIIIJJJJIJIJIJIIJJJJJIIIIJJIJJJIJJIJIIJIJJJJJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void IIIJJIJIIIIJIJIJJJJJIIJJIJIJIIIIIJJJIJIJJIJIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIIIIJIJJIJJJIIJIIIIIIIIJJJJJJIIJJIIIJJJI)
	{
	}

	public static void IIIJJIJIIIIJIJIJJJJJIIJJIJIJIIIIIJJJIJIJJIJIIII()
	{
	}
}
