using System.Collections.Generic;
using UnityEngine;

public class Chunk : MonoBehaviour
{
	private class IIIJJJIJJJIJIJIIIJIIJIJIJIJJIJIJIJJJIJIIIIIJJIJ
	{
		public short IJJIJJJJJIIIIIIIIIJJJJJJJJIJIIJJJIIIIJJIJIJJJIJ;

		public BoxCollider JIJIIJIJIIJJIJJJIJJIJJJIIJIJIIJJJIIJIJIJIIJJJJJ;

		public BoxCollider IIJJIJJIJIIIIIIIIIJIIJJJJIJIJIJIIIJIJJJJJIIJIII;

		public IIIJJJIJJJIJIJIIIJIIJIJIJIJJIJIJIJJJIJIIIIIJJIJ(short IIIJIJIJJIJIIJJJJIIJIJJJIIJJJIJJIIJJJIJIIIJJJII)
		{
		}
	}

	private sealed class JJIIIIIIIIJJIJJIIIIJJJJJJIIJIIIIJJJIIIJJJIJIIII
	{
		public Chunk JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public byte IJJJJIIIIIIJJIJJIJIJIIIJJIJJJIIJJIIJJIIJIJIIIJJ;
	}

	private sealed class IIJJIIIIIJJIIIJIIIIJIIJJJJIJIIJIIIJJJIJJIIIIJII
	{
		public int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ;

		public JJIIIIIIIIJJIJJIIIIJJJJJJIIJIIIIJJJIIIJJJIJIIII IJJIJIIIIJIJIJJJJJIIJIIJJIIIIIIJIIIIJJIIIIIJIII;
	}

	private sealed class IJIIIIIJIIIJJIJJIJJIIJIIJIIJJJIIJIIJIIIJIIIJJII
	{
		public int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI;

		public IIJJIIIIIJJIIIJIIIIJIIJJJJIJIIJIIIJJJIJJIIIIJII JJIIIJJJJIIJJJIJIIIJIIIJJJJJIIJIJJJJJIJIJIJIIIJ;
	}

	private sealed class IIJJIJJIIIIIJIIIJIIIIIIIJIJJJJJIJIIJIIJIIJJJIJJ
	{
		public int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII;

		public IJIIIIIJIIIJJIJJIJJIIJIIJIIJJJIIJIIJIIIJIIIJJII IJIJIIJJIJJJJJJIJJIJIIIIIIJJIIJIIIIJJIIJIIIJIJI;

		internal void JJJJIJJJJJIIJJIIIIIIIIJIJJIJJJIIIIIIIJJIJJJJJIJ()
		{
		}

		internal void JIJJJJJJJIIIIIJJIJIIIJIJIIIJIIJIJJIJIJIJJJIIJJI()
		{
		}

		internal void JIIIIJJIJJJJIJIIIJJIIIJJJJIJIIJIJJIIIIJIJJJJJJJ()
		{
		}

		internal void JIJJJJIIJJIIJJIJIJJIIJJJJJIIJIIIJJJIIIIIJIJJJJJ()
		{
		}

		internal void JJIIJIJJIJJIJIJIIIJIJJJIJJJIJIJJIJIJJJIIIJIJJIJ()
		{
		}

		internal void IJJIIJIIIJJJJIIIIIJIIJIJJJJJJIJIJJIJJIJIJIIJIIJ()
		{
		}

		internal void IJJJJIIIIIJIJJIIJIJIIIJIJIIIJJJIJJJIJIJIJJIIJII()
		{
		}

		internal void IJIIJIJJIJJJJJIJJJJIIIJJJIJJJJJJIIIJIIJIJJJJIJJ()
		{
		}

		internal void IJJIJJJJIIIJIIIIIIJIJJIJIJIJIJJIJIJIJIJIIJIJIJI()
		{
		}

		internal void JJJIIJIIJJJIJJJIIIIIIJIIIIJIIIIIJJJJIIIJJJIJJIJ()
		{
		}

		internal void JIJJIJJIIJIIIIIIIJJIIIJJIJIJJJJJIJJIJIIJIJJIIJJ()
		{
		}

		internal void IJJIJIIIJJJIJJIJJJIIJJIJIJIIJIIJIJJJJIIIJJIJIJI()
		{
		}

		internal void JIIJJJJJIIJIIJIJIJJIJIIJIIIJJIJJJJJJIIIIIJJJIII()
		{
		}

		internal void JIIJJIIJIJJJJJIJJJJIIIIJIJJJJJIJIJJIIIIIJIIJIII()
		{
		}

		internal void JIJJIIIJJJJIJIJIJJIIIIIIIJIIJIJIJIIIJJIIIJJJIJI()
		{
		}

		internal void JIIJIIJIJIJIJIIJJIJIJJIJJJIIIJJIJJJJJIJIJJJIJJI()
		{
		}

		internal void IJIJIJIIIJJJJIJIJJJIJIIIJIIJIIIIJJJIJJJJIIIIJJJ()
		{
		}

		internal void IIJIJJJJIJIIIJIIJJIJJJJJIIJIJJJIJIJIJJIJJIJJIII()
		{
		}
	}

	public byte[,,] JJJIJIJJIIJJIIIJIJJIIJJIIJIIJJIJJIJJJIIIIIIJIJI;

	public byte IJIJIJJJIIJJJJIIJIJJIIJIIIJJJIIJJIJIIIJIJIIIJII;

	public byte JIIJJIIIIIJIJIJJJIIIJIJJJIIJIIIJIJIJJJJJJIIIJII;

	public byte JIIIIJJJJJIIJIIIIJJJIJIJJJJJJJJJJIJIIIIIIJJIIIJ;

	private MeshFilter JIJJJIJIJIJJJIJIIIIIIJIJIJJIIIIJJJJIIJIJJIIJIIJ;

	private Mesh IJIJIJIJJJIIJJIIJJIIJIJIJIJJIJIJIIIJIIIIJIJIIJJ;

	private IIIJJJIJJJIJIJIIIJIIJIJIJIJJIJIJIJJJIJIIIIIJJIJ[,,] JIJIJJIJJIIIIIIJJJJIJIJIIJIIIIIJJJJJJJJIIJJJIJI;

	private bool IIJJJJJJJJJJJJJJJIJJJIJIIJIJIJJIIJJJJIJIJJJJIIJ;

	public short IIIJIJIJJIJIIJJJJIIJIJJJIIJJJIJJIIJJJIJIIIJJJII;

	private List<Vector3> IIJIJJJIIJIIJIJIJIIJJJJJIJIIJIJJIJJJJJJIJJJJJJJ;

	private List<int> JIJIJJIIIIJJIJIIIIIIIJJIIJIIIIJIIJIIIIJIJIIIJJJ;

	private List<Vector2> IJJJIIJJJIJIJIIIJJIJIJIJIJJJJIIJIJJIJIJIJJIIJJJ;

	public short JIIIJJJJJJIJJIJJJJJIIJIJJIIJJJIJJIJJJIJJIJJIIII(BoxCollider IIJJIJJIJIIIIIIIIIJIIJJJJIJIJIJIIIJIJJJJJIIJIII)
	{
		return 0;
	}

	public byte IJIJIIJJJIJJIIJIJIIJIIJIJIJJIJJJIJIIJIIJJIIIJII(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII)
	{
		return 0;
	}

	private BoxCollider IJIJIIJIJIIIJJJIJJJJJIJIIJIJJJIIJJIJJJJIIJIJJII(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII, bool JJIIJJIIJJIJIJIJJJIIJJJIIIIJIJIIIIIIJIIIIJJIJJJ)
	{
		return null;
	}

	public void JJJJJJJIIIJIJIIJIJJJIJIJJIJIJJIJJJIIIIJJIJJJJJI()
	{
	}

	public byte IIIIJJIJJJIJJIJIIJIIIJJIJJIJJJIIJJIJJJIIIIJJJJI(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII)
	{
		return 0;
	}

	public void JJJJIIIJJIJJIJJJJJIJIJIIIJIIJJIJJJIIJIJIIIIJIIJ(byte IJIIJJJJJJJJJIJJJJIIIIIIIJIIIIIIIJIIJIJJJIIJIJJ, Vector3 JIJJIJJJIIJIJJIJIIJIJIIJIIJIJIJJJJIJJIIJJIIIJJI, Vector3 IJJIJJJJIJJJJIJJIIIJJIIJJJJJIIJJJIJIIIIJIJJJIJJ, Vector3 IJIIJJJIIJIIJJJIIIJIIIJIJIIJJJJIIJJIIIJJJIJIIII, bool IIJIIIIIJJJIIIJJJJIIIJIIJIJJJJJIIIIIJJJIIJJJIIJ)
	{
	}

	public void IIJJIIIIIJIJJIJJIIIIIJJJIJIIJJJJJIIJIIJIIIIJIII()
	{
	}

	public bool JIIJJIIIIIIIIIJJIJIJIIIIJIIJJIJIIIJJJJIJJJIIJII(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII)
	{
		return false;
	}

	private BoxCollider IIIIJJIIIIJJJIIIIIIJIJIIJJJJJJIIIIJJIIJIJJJJJJJ(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII, bool JJIIJJIIJJIJIJIJJJIIJJJIIIIJIJIIIIIIJIIIIJJIJJJ)
	{
		return null;
	}

	public void IIIIIIIJJIJJJIIIJJJJIIIIIJJIJIIIIJIIIIIJIIJIIIJ()
	{
	}

	public bool JJIJIJJJJJJJJIIIJIJIIJJJJIJJJIJJIIJJJJJJJJIIJII(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII)
	{
		return false;
	}

	public void JIJJIIJIJIJJJIJJIJJIJIIJIJJJJJJJJJJIIJIIIIIIJII(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII, byte IJJJJIIIIIIJJIJJIJIJIIIJJIJJJIIJJIIJJIIJIJIIIJJ)
	{
	}

	public short IJJIJJJJJJIIIJJIJIIIJJIIIIJJJJJJIIJIIJJJJJIIJJI(BoxCollider IIJJIJJIJIIIIIIIIIJIIJJJJIJIJIJIIIJIJJJJJIIJIII)
	{
		return 0;
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	public byte JIJIIIJJJJIJJIJIIJIIIJJJJJJJIIJIJJJIIJJIJIIIJII(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII)
	{
		return 0;
	}

	private void IIIJJJJJIIIJIIJJIIIIJJJJJIIIIJIIIIIJIJIIJJJIIIJ(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII)
	{
	}

	public void IIIJIIJJIIJJIIJIIIJJJJJJJIIIJIIJJJIJJIIIIJIJIJI()
	{
	}

	public void JIJJIIJIJIJJJIJJIJJIJIIJIJJJJJJJJJJIIJIIIIIIJII(short IJJIJJJJJIIIIIIIIIJJJJJJJJIJIIJJJIIIIJJIJIJJJIJ, float IIJJJJJJIIIIJJIIJJJJIIIJJIJIJJJIJJIIJIJIIIJJIJI, byte IJJJJIIIIIIJJIJJIJIJIIIJJIJJJIIJJIIJJIIJIJIIIJJ)
	{
	}

	public void IIIJJJJJJJIIJIIJJJJIIIJIIIJIIJIJJIIIJIJJJJIIJJJ(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII, byte IJJJJIIIIIIJJIJJIJIJIIIJJIJJJIIJJIIJJIIJIJIIIJJ)
	{
	}

	public void JIJIJIIJJJIJIJJIJIIJIIJJIJJIIJJIIJJJJIJIJJIIJII(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII, byte IJJJJIIIIIIJJIJJIJIJIIIJJIJJJIIJJIIJJIIJIJIIIJJ)
	{
	}

	public bool JIIJJJJJJJIJIJJIIJIJIIJJIJJJIIJJIIIIIIIIIIJJIIJ(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII)
	{
		return false;
	}

	public void IIIJJIJJJJIJIIJIIIIIIIIIJJIIJJIJJJIIIJIJJJJIJIJ()
	{
	}

	public void IIJIIJJIJIIIIIIJIJJIJJIJIJIIJIIIIIIIJJIIJJIJIJJ()
	{
	}

	private void IIJIJIIIIIJJIIIIIJJIJIIIJIJIJIIIJIJJIIIJJJJIIJJ()
	{
	}

	public void JIJIJIJJJJJJJJJJJIJIJIJJJJIIIIJJIIJJIJIIIJIIJIJ(byte IJIIJJJJJJJJJIJJJJIIIIIIIJIIIIIIIJIIJIJJJIIJIJJ, Vector3 JIJJIJJJIIJIJJIJIIJIJIIJIIJIJIJJJJIJJIIJJIIIJJI, Vector3 IJJIJJJJIJJJJIJJIIIJJIIJJJJJIIJJJIJIIIIJIJJJIJJ, Vector3 IJIIJJJIIJIIJJJIIIJIIIJIJIIJJJJIIJJIIIJJJIJIIII, bool IIJIIIIIJJJIIIJJJJIIIJIIJIJJJJJIIIIIJJJIIJJJIIJ)
	{
	}

	public void IIIIJJJJJJJIIIJJJIIJIJJJJJJIIJIJJJJJJIIJJJIJIJJ(byte IJIIJJJJJJJJJIJJJJIIIIIIIJIIIIIIIJIIJIJJJIIJIJJ, Vector3 JIJJIJJJIIJIJJIJIIJIJIIJIIJIJIJJJJIJJIIJJIIIJJI, Vector3 IJJIJJJJIJJJJIJJIIIJJIIJJJJJIIJJJIJIIIIJIJJJIJJ, Vector3 IJIIJJJIIJIIJJJIIIJIIIJIJIIJJJJIIJJIIIJJJIJIIII, bool IIJIIIIIJJJIIIJJJJIIIJIIJIJJJJJIIIIIJJJIIJJJIIJ)
	{
	}

	public void IIIJIIIIIJIJJJJIJJJJJIJIIJIJJJJJIJJJIIIIJJJJIIJ(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII, byte IJJJJIIIIIIJJIJJIJIJIIIJJIJJJIIJJIIJJIIJIJIIIJJ)
	{
	}

	public void JJIIIJIJJJIJIIIIJJJIJIJIJJIIIIIIJIJIIIIIJJIJIII()
	{
	}

	private void Start()
	{
	}

	public void IJJJIIIIIJIIIJIIIIIIIIIJJJJIJJJIIIIJIIIIJIIJJIJ(short IJJIJJJJJIIIIIIIIIJJJJJJJJIJIIJJJIIIIJJIJIJJJIJ, float IIJJJJJJIIIIJJIIJJJJIIIJJIJIJJJIJJIIJIJIIIJJIJI, byte IJJJJIIIIIIJJIJJIJIJIIIJJIJJJIIJJIIJJIIJIJIIIJJ)
	{
	}

	public void IJJJJJJIJJIIIIIIIIJJJIIJJIIIJJIJJIJJJJJJIJIIIJI(short IJJIJJJJJIIIIIIIIIJJJJJJJJIJIIJJJIIIIJJIJIJJJIJ, float IIJJJJJJIIIIJJIIJJJJIIIJJIJIJJJIJJIIJIJIIIJJIJI, byte IJJJJIIIIIIJJIJJIJIJIIIJJIJJJIIJJIIJJIIJIJIIIJJ)
	{
	}
}
