using System.Runtime.CompilerServices;
using UnityEngine;

public class ChunkCube : MonoBehaviour
{
	public Transform JIJIJJIIJJIJJIIJIJIJIIIJIIIJJJIIIJJJIJIJIJIJJII;

	public float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ;

	public float IIIIJIIJJIJJIJIJJJIIJIJJIJIIJIJIIIJJJJJIJJIIJIJ;

	public Transform JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII;

	private RaycastHit IIJIJIJJJIJIJJIJIJIIJJIJIJIJJJIJIJJJJJJJJJJJIJJ;

	private Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII;

	private Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ;

	private bool JIIIIIIIJIJJJJJJIJJJIJJIJIJIJIJJIIJIIIJIIIJJJII;

	private bool JIJIJIIJJIJIJJJIJIIJIIIIJIIIJJIIIJJJJJJJJJIIIJI;

	private void IIIJIJIIJJIJJIJIIIJJIIJIJJIIJIJIJIJJJJJIIIJIJJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IJJIIJJIIJJIIJJJJJJIIIJJJJJIJIIJIJIIJIIJIIIIJII()
	{
	}

	private void Start()
	{
	}

	private void OnEnable()
	{
	}

	private void IJIIIIJJJJIIJIIIIIIJIIIIJIIIIJIJJJIIIIJJJJIIJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void IIIJJIJJJJJJJJIIJJIJJJIJJIIIIJIIIJJIIIIIIJJJJJJ()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void JJJIIJJIJIJJJJIIJJJJJIJJIIIJJJIJIJJIIIJIIJIIJII()
	{
	}

	private void JJIJJJIIIIIJIIIJJIIIJJIJIJJIIJJJIJJJIIIIJJJIJII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void JJIJJIJJJIJIJJJJJIJJIJJJJIIIIJIIIIJJJIIIIIIIJII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void JIJJJIIIIIIJJIIIIIJJIIIJJIJIJJJJJJJJIJIJIIJIJII()
	{
	}

	private void IIJIJJJJJIIJIIJJIJIJJIJJIJJIIJJIIJJJJIIIJIIJJII()
	{
	}

	private void Update()
	{
	}

	private void IJIJJIIJJIIJIIJJJJJIJJJJIJJJIJJIJIIJJIIJJIJIIJJ()
	{
	}

	private void JIJIJJJJJIJIIIJIIJJJJIJIIJJIIJJIIJIIIIIIIIJJJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IJJJIIJIIJJIJIIJIIJJJIIJIJJJJIJJJIJIIJIIJJJIIJI(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	[CompilerGenerated]
	private void IIJIJIIIJIIIIJJIIIIJJJIIIJJIJJIJJJJJJJJIIJIIJIJ()
	{
	}

	private void IIJJIJIJJJJJIJJIIJIJIJJIIJIJIIJJIIIJJIIIJIIIJJI()
	{
	}

	private void IJIJJJIJIJJJIJJJIIJJIJJIJIIJIIIJJIJJIJIJIIIJIII()
	{
	}

	private void IJIIJJIJJJIJJJJIJJIJJIJIJJJJIIJJJIIJIJJIJJIIIIJ()
	{
	}

	private void JJJIIIIIIIJJJIIJIIIIJJJJIIIIIIIIJJJJJJJIIIJIIJJ()
	{
	}

	private void IJIJIJIIJJIIIJJIJIIIJIJJIIJJJIIJJJJJIJJIIIJJIIJ()
	{
	}

	private void OnDisable()
	{
	}

	private void JJJIJJJJJIIJJJIIIJJIIIJIIIIJIIIIIJJIIIJJIJJIIII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IIJJIIIJJJIIIIIIIIIJIIIIJJJIIIJJJIIIIIIIJJJIIIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}
}
