using UnityEngine;

public class ClimbSystem : MonoBehaviour
{
	private JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ JJJJJJJJIJIJIIJJJIJIJJJJJJIIJIJIIJJJJJIIJIJIJII;

	private JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ IJJJJJJIJIIIJJIIIJIJIJJIJIIIJJIJJJIIJJJJJIIJIII;

	private BoxCollider IJJIJIJJJJJJJIIIIJJJIJJJJJJIIJIIIIIJJIIIIJIJJJJ;

	private Bounds JJIJIIJJJJJIJJJIIIIJIIIIIJIJIIIJIJIIJIIIIJJJJJJ;

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void IIIJJIIJIJJIIJJIJIIIJIJIJIJJIIJJJJJJIJIIJJIJIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJIJJIJJJJJJIIJIIJIJIJJIJJJJJJJIIIJJJJIIIJJJIII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIIIJIIIJIJJJJIJIIJJJJJIJJIJIIJJJJJIJIJJIJIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void OnTriggerExit(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void OnApplicationFocus(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}

	private void IJIIJJIIIIIIJIJJIJIJIIJJJIIJJJJJIJIJIIJIJIJIIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void Start()
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void IJIJJJJJJJIIJJJIJIIJJJJIIJJJIJIIJIJJJIIIIIIIJIJ(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJJJIJIJJIIJIIIIIJIJIIIJJIIIIJIJJJIJJIJJJIIIJJ(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}

	private void IIIIIJIJIJJJJIJIJJIJJJIIJJJJIIJJIIIJJJJIIJJJJJI(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}

	private void IJJJJJJJIJIIIIIIJIJIJJJIJJJJIJJIJIJJIJJIJIJJIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJJJIJJJJIJJIIJIJIJJIIJIIIIJIIJJJIJIIJIIJIIIII(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}
}
