using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Photon;
using UnityEngine;

public class ControllerManager : Photon.MonoBehaviour, JIIIJJJIJIJJIJIJJIJJIJJJJJJJJIJIIIJJIIJJJJIJJJI
{
	[HideInInspector]
	public PlayerInput IJIIJJJJIJIJJJJIJIJJJJIJIIIIJIIIJIJJIJJIJJIIIIJ;

	[HideInInspector]
	public PlayerSkin IJJIIJIJIJIIJJIIIJJIIJIIJIIIJJJIJJJIJIJJJJJIJII;

	private Vector3 JIJIJIIIIIIIJIJIJIJJJIJIIIIIJJIJIIIIJIJJIJIIIJI;

	private int JIJJIIJJIIIJJIJIIJJJJJIIIJIIJIIJJJJIIIIJIIJJJJI;

	private byte JIJJJIIIJIIJIIIJIIJIJJJJIJJJJJIIIJJIIIJIJJIIIII;

	private bool JIIJJJJJIIJIJIJJIIIJJIJIIJJJIJJJJIJIIJJIJIIJJJI;

	public static List<ControllerManager> JJJJIIIIJJIJIJIJJJJIIIIJJJJJJJJJJJJIIIIJIIJJIJJ;

	private static Action<int, int, int> IJIIIIIIJJIJIJIJIJJIJJJJJIIIJJIJJJJIJJJIJIJIIJI__BackingField;

	private static Action<int, bool> IIJJIJJJJIJIJJIIIIIIJIJIIIJJIJJIIJIJIJIIIIJJJJJ__BackingField;

	private static Action<int, JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ> JIJIJIJJJIIIJJIIIJIIIJIJIIJIIIJIJJIIIIJJJJIIIIJ__BackingField;

	private static Action<int, byte> JJIIIIIIJIIIIIJIIIIIIJJIJIIIJIIIIJJJIIJIIJJIIJJ__BackingField;

	private static Action<int> IJIJIJIIIIIIIJIIIJIJJIIIJIIIIJIIIJJIIIJIJIJJIIJ__BackingField;

	private static Action<int> JIJIIJJJIIJIIIIIIIIIJIIJIJIIJJIJJJIJIIIJJJIIJII__BackingField;

	private static Action<int> IJJJIJIIJJJIIIJJJJIJJIJJJJJIIJJIJIJJJJIIIJJJIII__BackingField;

	private static Action<int, bool> JJJJJIIIJJIJIJJJIJIIJIJJJJJJIJJJIIJJIJJIIIIIJIJ__BackingField;

	public static event Action<int, int, int> IJIIIIIIJJIJIJIJIJJIJJJJJIIIJJIJJJJIJJJIJIJIIJI
	{
		add
		{
			IJIJIJIJIIJIJJIJIJJIJIIIIJJIJJJIJIJIIIJIJJJJIII(value);
		}
		remove
		{
			IJIIJJIJIJIJIJIJIJJIIJIJJJIIJJIIJJJJJJJIIIJIJII(value);
		}
	}

	public static event Action<int, bool> IIJJIJJJJIJIJJIIIIIIJIJIIIJJIJJIIJIJIJIIIIJJJJJ
	{
		add
		{
			IIIIIJIJJJJIJIJJIJIIIJJIIIJJIJJIJIJJJIJIIJJIJIJ(value);
		}
		remove
		{
			IIIJIJIIIIJIIJIJIIJJIIIIJIIJJJIIJJIIJIJJJJJIIJI(value);
		}
	}

	public static event Action<int, JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ> JIJIJIJJJIIIJJIIIJIIIJIJIIJIIIJIJJIIIIJJJJIIIIJ
	{
		add
		{
			JJIIJJJJIIIIJIIJIIIJJIIJIIIIIIJIIJJIIJJJIJIJJIJ(value);
		}
		remove
		{
			JJIJIIJIIJIJIJJIJIJJIIIJIJIIIIIJIJJJIJIIIIJJJJI(value);
		}
	}

	public static event Action<int, byte> JJIIIIIIJIIIIIJIIIIIIJJIJIIIJIIIIJJJIIJIIJJIIJJ
	{
		add
		{
			JJJIIIIJJIJIJIIIJJJIIJJIJJIJIIJIIIIJIJJJJJIJJJJ(value);
		}
		remove
		{
			JIJJJIIJIJIJJIIJJIJIJIIIJIIIIJJJIJIJIJJJIJJJJJJ(value);
		}
	}

	public static event Action<int> IJIJIJIIIIIIIJIIIJIJJIIIJIIIIJIIIJJIIIJIJIJJIIJ
	{
		add
		{
			JJJJIJJJJIJJJJIJIJJJIIIJJIJIIIIJIJJJJIJJIIJJJIJ(value);
		}
		remove
		{
			IJJIJIJIJIJJIIIJJJJJIJIJIJJIIJIJJJIIIJJIIJJJIII(value);
		}
	}

	public static event Action<int> JIJIIJJJIIJIIIIIIIIIJIIJIJIIJJIJJJIJIIIJJJIIJII
	{
		add
		{
			JIJJIIJJJJJIJJJJJIJIJIIJJJIIJJJJIIJIJIIIJJJIIJI(value);
		}
		remove
		{
			IIIJJIJJIJJJIJJIIIIJIJIJIIIIIIJIJIIIIIIJJIJIJII(value);
		}
	}

	public static event Action<int> IJJJIJIIJJJIIIJJJJIJJIJJJJJIIJJIJIJJJJIIIJJJIII
	{
		add
		{
			IJJJIIIJIIIIIIJJIIIJJJIIJJIJJIJIIIIJJIJIJJJIIJJ(value);
		}
		remove
		{
			JIIJIJJIIJIJJIJJIIJIJIIJIJIIIJIJIIIJJJIIJIJJIII(value);
		}
	}

	public static event Action<int, bool> JJJJJIIIJJIJIJJJIJIIJIJJJJJJIJJJIIJJIJJIIIIIJIJ
	{
		add
		{
			JJIJIIIIIIJJJIIJJIJIIIJJJJJIIJIJIJIJIIIJIJJJIII(value);
		}
		remove
		{
			JIJJJIIJJIJIIIJIIIJJJJIJIIIJJJJIJJJJJIJJIJIJJIJ(value);
		}
	}

	private static byte[] IIJIIJJJJJJIJIIIIIIIJJJJJJJIIJJIJJIIIJJJJIIIJIJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
		return null;
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJIJJJJIJIJJIJJIIIJIJJJIJJJIIIIJIJIIIIIJIIJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void JJIJIIIIIIJJJIIJJIJIIIJJJJJIIJIJIJIJIIIJIJJJIII(Action<int, bool> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JJJJIJJJJIJJJJIJIJJJIIIJJIJIIIIJIJJJJIJJIIJJJIJ(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JIJJJIIJIJIJJIIJJIJIJIIIJIIIIJJJIJIJIJJJIJJJJJJ(Action<int, byte> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JIJJJIIJJJJIIJIIIJIJJJJJIIIIJIJJIIIIJJIJJJIJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJIIIIJIIIJJJJJJIIIIIJIIIIJIIIJJJJIJIIJJIIIJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void JIIIIIJIJJIIJJJIIJIIJJIIJJIJJJJIJJIJIIJJJIIJIJJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	public void JJJIIIIIJIJIJIIJIIIIJIIJJJIJJJJIIIJIJJIIIJIIIII(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public void JIJIIJJJIJIIJJJIIJIJIIIIIJIIIJIIJJIIJIJJJIJIIII()
	{
	}

	public void IIJIIIIIIJIIJIIJIJIJIJIIIJIIJIIIIJIIIJIIIIJIJJJ()
	{
	}

	private void Awake()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJIIIIIJIJJIIJJJJIJIJJIJIIIJJJIJIJIJJIJJJIIIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IJJIJIJIJIJJIIIJJJJJIJIJIJJIIJIJJJIIIJJIIJJJIII(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJIIIIIIJIJIIJIIJJIIJIIJIJJJJIIJIJIIIJIJIII(Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ)
	{
	}

	public static void JIJJJIIJJIJIIIJIIIJJJJIJIIIJJJJIJJJJJIJJIJIJJIJ(Action<int, bool> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	public static void IIIIIJIJJJJIJIJJIJIIIJJIIIJJIJJIJIJJJIJIIJJIJIJ(Action<int, bool> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static void IJIIJIJJIIJJJJJJIIJIIJJJIIIJIJIJIIJIJIJIJIJJIIJ(Action<int, int, int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void IIIJIJIIIIJIIJIJIIJJIIIIJIIJJJIIJJIIJIJJJJJIIJI(Action<int, bool> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIJJJJJJJIJIJIJIIIJJIIIJJIIJIJIIIJIIJIIIIJJJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}
	public static void JJIJJIIIIIIIIJIJIIIJJIIIIIJJJIIJJIIJIJIJJIIJIIJ(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJIIJIIJJJIIJIIJIJIIJJJIIJIIJJJIIIIJJJIIIJJJIJI()
	{
	}

	public void IJIJIIIJIJIJJJIJIIJIJJIIIIIJJIIIIJJJIIJJIJJJJJI(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ, byte JIIJIIJJJJJIIIJIJJIIJIIIIIIJIJIIJJIIIJIIIIJIIJI, byte JJJJIIJJJIJJIIIJIIIIJJJIIIJJJJIJJJJIIIJJIIJIJIJ, byte JIJJIJJJJIJIIIIJJJJIIJIJIIIIJJIIJIIIIIJIIIIIJJJ)
	{
	}

	public void IJJJJJJIIJIJIJJIJJJJJIIIJJJIJJJIIIJJIIJIIIIIIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IJIJIJIJIIJIJJIJIJJIJIIIIJJIJJJIJIJIIIJIJJJJIII(Action<int, int, int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIJIIIJJJJIIJIJJJJIJIIJJIIJIIIJIIIJIIJIIJIIIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}
	public static void IJJIIIIIJIJIJIIJIIIJIJIJIJJIIJIJJJIJIIIJIIJIIIJ(Action<int, int, int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JJIJIIJIIJIJIJJIJIJJIIIJIJIIIIIJIJJJIJIIIIJJJJI(Action<int, JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void OnPhotonSerializeView(JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ IJJJJIIJIIIIJJJIJIJJIIJIIIJIJIIIIIIJIIIIJIJIIJI)
	{
	}

	public void JIJIIIJJIJIJIJJJJJIIJJIIJJIIIIIJIIIIIIIIIJIJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IIIJJIJJIJJJIJJIIIIJIJIJIIIIIIJIJIIIIIIJJIJIJII(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static ControllerManager JJJIJJIJIIJJIJIJIJJJJIJJIIJJJIIIJIJIIJJJJIJIIIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return null;
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJIJIJJIIJJIJJJJIIJIJIIJIJJIJIIJJJIJJIIIIJIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void JIJJJJIIJIJIJJIJIJJJJJJJIJJIJIIIJJJIIJIJJJJIIJJ(Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}
	public static void JIIJIIIIJIJIJIJJJIIJIIIJIJIJIIJJJJJIJJIJJJJIJIJ(Action<int, int, int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIJIIIIIIJJIIIIIIJIJJIJIIIJJIJJJJJJIIIIJIJIIIJI(IIIJJIJJIIJIIIJIIIJIIJIIJJIJJIJIJJIJJIIJIJIJIJI IJIIIJJJJIJJJJJJJIIJIJIJJIIJJIIJJJJIJJIIJJIJIJI)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIJIIJIJIJIJIJJIJIJIJJJJJIIIJIJIJJJIIIIJIJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJJIJJIIIIIIJJIJJJJJIJJIJIIJIIIJIIIJIJIJJJIJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIIJJIIJJJJJJJIJIJJIIIIJJIJIIIJJIJJIIJIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IJJJIIIJIIIIIIJJIIIJJJIIJJIJJIJIIIIJJIJIJJJIIJJ(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIJJJJIIJIJIJJIJIJJJJJJJIJJIJIIIJJJIIJIJJJJIIJJ(Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII, bool JJJJJJJIJIJIJJIIJIIJIIJJIJJIJJIIIJIJJIJJJIJJJIJ)
	{
	}
	public static void JIJJIIJIIJJIJJIJJJIJJJIJJIIIJJIIIJIIIJJIJJIJJJJ(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void IIJIIIIIJIJJIIJJJJIJIJJIJIIIJJJIJIJIJJIJJJIIIJJ(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, Vector3 IJJJJJJJIJIIIIIJJIIIIJIIIIJJJIIJJIJJJIJJIIIIJJI)
	{
	}

	public void JJIIJIJIIJIIJJJIJJIJIJIIIJJIIIJJJIIJIJIJIJIIJII(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIJJIJIIIJJIIIIIJIJJIIJIIIJJJJIJJIIIIJJJIIIJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void JJJIIIIJJIJIJIIIJJJIIJJIJJIJIIJIIIIJIJJJJJIJJJJ(Action<int, byte> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIJIJIIIJJJJJIIJIJJJJIIIJIIJIJJIJIIIJIIJJJJIJJI(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, Vector3 IJJJJJJJIJIIIIIJJIIIIJIIIIJJJIIJJIJJJIJJIIIIJJI)
	{
	}

	public void JIIIIIJIIJIJJJJIJJIIJIJJIJJIJIIJIJJJJIIJJIIJJII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void IJJIIJJIIJIJIIJJJIIIJIJIIIIIIIJJJJJIJIIJIIIJJII(Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Vector3 IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII)
	{
	}

	private void JJJIIJIIIJIIJJIIJJIIIJIIIIJJJJIIIJJIJIIJIIIJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void JIJJIIJJJJJIJJJJJIJIJIIJJJIIJJJJIIJIJIIIJJJIIJI(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIJJJJIIJIJIJJIJIJJJJJJJIJJIJIIIJJJIIJIJJJJIIJJ()
	{
	}

	public void IIIJIJIIJJIIJJIJJJIIJJJJJJIJJIIJJJJIJJJIIJIIIJJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	public void IIIIIJIJJIIJJJIJJJIJIJJJJJJJJIJIIIIJIJJIIJIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void JIJIJJIJIIJIJIJIIIIIIIJIIJJIIIIIJJJIIIIIJIJJJJI(byte IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII, byte IJJJIIIIIIIIIIIIJJIJJIIJJIIIJIIJJJJIIJJIJIJIJJI)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIJIIIIIIIJJJJJJIJJJJJJIJJIJJIJJJIIIIIJIIJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void JJIIJJJJIIIIJIIJIIIJJIIJIIIIIIJIIJJIIJJJIJIJJIJ(Action<int, JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIIJIIJJJIJJJJIJJIIJIJIIIJJJIIJJJJJIIJJIIJIJIJ(IIIJJIJJIIJIIIJIIIJIIJIIJJIJJIJIJJIJJIIJIJIJIJI IJIIIJJJJIJJJJJJJIIJIJIJJIIJJIIJJJJIJJIIJJIJIJI)
	{
	}

	public void IJJJJIJJIIJJJIJIIJJJIIIIJJJJJIJIJJJIJIIJJJIIJIJ(Vector3 IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIIJJIIJJIIIJIIIIIIJJJIIIIIJIJIJIIJIJJIJIIIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJIIIIJIJIIIIJJJIJIJJIJJIIIJIIJJJIIJIIJIIJIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIJIIJJJIJJIJIJJIIJIIJJJIJJIJJJIIIIJIIIJIJIJJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIJJIIIIIIJJIIJIIIJJIJJIIIJJJIIJIJIIIJIIJJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void IJIJIIIIIJIIJJIIIJIIIJIJIIJIIJIJJIIIIJJIIIJJJIJ()
	{
	}

	private void IJIJJIIJJIIJIIJJJJJIJJJJIJJJIJJIJIIJJIIJJIJIIJJ()
	{
	}

	public void JJIJIIIIJJIIJJJIIJIJJJJIIJJIIIIJIIJIJIIJJJIIJII(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
	}

	public void JJJIIIJJJIIJIJJJJIJJIIJIIIIJJIIJJIIIIJJJJJJIIIJ(PlayerWeapons.JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ IJJIJJJIIJIJIIIJJIIJJIJJJIIIIIJJIJJJIJJIIIJJJII)
	{
	}

	public void JJJJIJIIIIIIIJIJIIIJJJIJJJIIJJIJJJIIIIJJIIJJJJJ(Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}

	private void OnDisable()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	public void JJIJJIIJJJIJIIJJIJIIJIJJJJJJJJIJIIIIJIIJJIIJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IJIIJJIJIJIJIJIJIJJIIJIJJJIIJJIIJJJJJJJIIIJIJII(Action<int, int, int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIJJJJJJIJIJJJJIIJJIJJJIJJIIJJJIIIJIJJJJJIJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIJIJIJIIJJJJIJJIJJJIIJJIJJIIJJJJJJJJJJJJIIJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void IJIJIIIJIJIJJJIJIIJIJJIIIIIJJIIIIJJJIIJJIJJJJJI(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void JJJIIJIIIJIIJIIIIJJIIJIJJJIIJJIJJIJJIJIIJJIIJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void JIIJIJJIIJIJJIJJIIJIJIIJIJIIIJIJIIIJJJIIJIJJIII(Action<int> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void OnEnable()
	{
	}
}
