using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class CryptoTransform : MonoBehaviour
{
	[Serializable]
	public class Data
	{
		public Transform transform;

		public JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ position;

		public JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ rotation;

		public JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ scale;
	}

	public JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ;

	public JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII;

	public JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ IJIJIJIJJJIIJJJJJIJJJJJIJJIIJJJJJJIJIJJJJIJJIJI;

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IIIJIIIIJJJIIJJIJIIIIJIIIJJIIJIIIIJIIIIJJJIIJII;

	public bool IJIIJIJJIJJJJIIJJIJIJJIJIJIIIJJIIIJIJJIIJJJIIJI;

	public List<Data> JIIJIJJIIIIJIIJJIJIIJJIIIIIJJJJJJJJIIJIIIJIJJIJ;

	private Transform JJIJIIJIIJJJJJIIIJIIIJJJIJJJIIIIJJIJJJIIIJJIIII;

	private Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	private Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}

	private void IIIIIIIJIIJIJJIIIJIJJJJJIJIIJIIIJJIJJJJIJJIJJJI(bool IIIIIIIJJIIIIJIIIJJIIJJIIIJJJJJIJJIJJJIJJJJJIII)
	{
	}

	private void IIJIJIIIIIJJIIIIIJJIJIIIJIJIJIIIJIJJIIIJJJJIIJJ()
	{
	}

	private void OnEnable()
	{
	}

	private void JJIJJJIIJIIJIIJJJJJIIIIIJIIJIIIJIIJIJIJJIJJIJIJ()
	{
	}

	private void IIJJIIJJIJJJIJJIIJJIIIJJJJIIIIIJJJJIJIIJIJJIIJJ()
	{
	}
	private Transform IJIJJJIJIIIJIJIJIJJIIIJJJIJJIJIJJJJJJJJIJJIJIIJ()
	{
		return null;
	}

	private void JJIJIIJIIJIJJIJJIJJIJIIIIIJJJJIJJJIIIIIJJJJIIII()
	{
	}

	private void JIJIIJJIIIIIIIJJIJIJIJJJIJJIJIIJJIJJJIJIIIJIIJJ()
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private void IIJJJJJIIJJJJJJJJJIIIIJIIJJJIIIIIJIIIJIIJIJJIJJ()
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}
	private Transform JIIJJIIIIIIJJJIIIIJJIIJIJJJIIIIJIJJJJIIIIJIJIIJ()
	{
		return null;
	}
	private Transform IJJJJJIJIIIIIJIJJJIIJIJJIJJJIJJJIIJJJIIJIIIJJIJ()
	{
		return null;
	}

	private void OnApplicationFocus(bool IIIIIIIJJIIIIJIIIJJIIJJIIIJJJJJIJJIJJJIJJJJJIII)
	{
	}

	private void IJIJJJJIIJIJIJIJJJIIIIJJIIJJIIJIJJIIJJJJIIJJJJJ()
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void Start()
	{
	}
	private Transform JIJIJJJJJJJJIJIJIJIIJIJIIJJJIJIJJJIJIIIIIJIJJII()
	{
		return null;
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void IJIIIJIJJIIJJIJIJJIIJIIIJJJIIJJIIIJIJIIIIIJJJII()
	{
	}
}
