using UnityEngine;

[ExecuteInEditMode]
public class CryptoBoxCollider : MonoBehaviour
{
	public JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ JJJJJJJJIJIJIIJJJIJIJJJJJJIIJIJIIJJJJJIIJIJIJII;

	public JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ IJJJJJJIJIIIJJIIIJIJIJJIJIIIJJIJJJIIJJJJJIIJIII;

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IIIJIIIIJJJIIJJIJIIIIJIIIJJIIJIIIIJIIIIJJJIIJII;

	private BoxCollider JJIJJIJIJJJJJJIJIJIJJIIIJJIIJIJIJJJJJJJJIJJIIIJ;

	public BoxCollider JIIIJJIJIJIJIIIJJJIIJIJIIJIIIIJIJJJIJIJJJJIJIJJ => IJIIIIIIIJIJJIJIJIJIIJJJJJJJJIIJJJJJIIIJJJJIJII();

	private void Start()
	{
	}

	public BoxCollider IJIIIIIIIJIJJIJIJIJIIJJJJJJJJIIJJJJJIIIJJJJIJII()
	{
		return null;
	}

	private void JIJIJIIIJIIJJIIIIIJJIJIIIIJJJIJIJJIJIJIIIIJIJJI()
	{
	}

	private void IJJIIJIIIJIIIIJIJJJJJJJIJJIJIIJJIIJIJJIJJIIIJJJ(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void IJIJJJIIJIIJIJJIJIJIIIJIJIJJIIIIIIJJIJIJIJIJIJJ()
	{
	}

	private void IIJIJJIJIIJJJJJJIJIIIIIJJJJIIIIIIJIJJJJJJJIIJII()
	{
	}

	private void OnApplicationFocus(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}

	private void OnDisable()
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void JIIJJJIIIIJIJJJJIIJJIJIIIJJIJIJJJIJIIJIJJJIJIII(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}

	private void IIIIIJIIJJIIIIJIJIJIJJIIIIIIJIIJIIIIJJJJJJJIIJI()
	{
	}

	private void IJIJIIIJJJIIJIJJJIJIJIIJIIIIJIJJJIIIJJJJIIIJJJI(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}

	private void OnEnable()
	{
	}

	private void IJIIIJIJJIIJJIJIJJIIJIIIJJJIIJJIIIJIJIIIIIJJJII()
	{
	}

	private void JJJIIJJIJIJJJJIIJJJJJIJJIIIJJJIJIJJIIIJIIJIIJII()
	{
	}

	private void IIJJIIJJIJJJIJJIIJJIIIJJJJIIIIIJJJJIJIIJIJJIIJJ()
	{
	}

	private void IJJJJIJIIJIIJJIIJIJIJJJJJJJJJJJJIJJJJIIIJIJIIJI()
	{
	}

	private void IIJJJJJIIIIJIJIIIJIIJJJIJIIIJJIJJIJIJIJIIIJIIJI()
	{
	}

	private void JJIJIIJIIJIJJIJJIJJIJIIIIIJJJJIJJJIIIIIJJJJIIII()
	{
	}
}
