using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class CryptoCapsuleCollider : MonoBehaviour
{
	public JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ JJJJJJJJIJIJIIJJJIJIJJJJJJIIJIJIIJJJJJIIJIJIJII;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII IJJIIIJJIJIJIIJJIJJIIIJJIIJIIJJIIIIJIJJIJIIJJJI;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII;

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IIIJIIIIJJJIIJJIJIIIIJIIIJJIIJIIIIJIIIIJJJIIJII;

	private CapsuleCollider JJIJJIJIJJJJJJIJIJIJJIIIJJIIJIJIJJJJJJJJIJJIIIJ;

	public CapsuleCollider JJJIJJJIIIJIIJIIJIIJIIIIJJIIJIJIJIJJJJJIIIIIJJI => IJJIIJIJIIIJJIIJIIJJIIIJJIIIIIIJJIIIIJJJIJJJJII();

	private void Start()
	{
	}

	private void IJIJJJJIIJIJIJIJJJIIIIJJIIJJIIJIJJIIJJJJIIJJJJJ()
	{
	}

	private void IIJIJJIJIIJJJJJJIJIIIIIJJJJIIIIIIJIJJJJJJJIIJII()
	{
	}

	private void OnApplicationFocus(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}

	private void IIJJIIJJIJJJIJJIIJJIIIJJJJIIIIIJJJJIJIIJIJJIIJJ()
	{
	}

	private void OnDisable()
	{
	}
	public CapsuleCollider JJIJJIJJIIJJIJIIJJIIIJIIIIIIJIIJJIJJIJIJJJJJJIJ()
	{
		return null;
	}
	public CapsuleCollider JIIJJJJJJJJJJIJJIIJJIIJJJIIIIIIJIJIIJJIJIJIIIJJ()
	{
		return null;
	}
	public CapsuleCollider JIIJJIJJIIJIIJJIJIJIIIJIIIIIIJJJIJJIIIIJJIIJIIJ()
	{
		return null;
	}

	public CapsuleCollider IJJIIJIJIIIJJIIJIIJJIIIJJIIIIIIJJIIIIJJJIJJJJII()
	{
		return null;
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	private void IJJIIJIIIJIIIIJIJJJJJJJIJJIJIIJJIIJIJJIJJIIIJJJ(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	private void IJJJIIJJIIJIJIJIIJIJIIJJJJJIJJJIJIJJIJJJIIJJJJJ()
	{
	}

	private void IJJIIJIIJJIIIJJJIIIJIJIIJIIIJJJIJIIJIIJJIJJJIJJ()
	{
	}

	private void IIIJJJIIIJJJJIJJJIIIJJJJJIIJJIJIJJJIIJJJJIJIJIJ(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}
}
