using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class CullArea : MonoBehaviour
{
	private const int JJIIIJJIJJJJJIJIJIIJIJJJJIIIIIIJIJIIJIJJJIJJJJI = 250;

	public const int JJJIJJIJIIJIIJIIIIIIIIJJIJJJJIJIJIIIIIJJJIIJJJI = 3;

	public readonly byte IIJJIIJIJJIIIJIJJJJJJJJJIIIIJJIJIJIJIIJJIJJJIII;

	public readonly int[] IIJJIJIJJJJJJIJJJJJJIIJJJJJJJIIJJIJJIIIJIJJIJJI;

	public readonly int[] JIIJIIJIIIJJIJJIJIJJJIJJIJIJIIIJJIIIJIJJIIIIJII;

	public readonly int[] JIJIJJIIJIIJJJJIJJIIIIJJIIJIJIJIIJIIIJJIIIIJIJJ;

	public Vector2 IJIIJJJIJIJIIIIJJJIJJIIIIJJJIIIIJJIJJJJIJJJIIJJ;

	public Vector2 JJJIIJIIJJJJJJJIJIIJIJIIJJJIJIJJJIJJIIIIJIJIIIJ;

	public Vector2[] JIJIJJJIJIIJJJJJIJIIJJJIIIIIJIIIJIIIJIIIJJJIIIJ;

	public int IIIIJIIJIIJJIJJJJJJIIJIIJIIIIIJJIIIJIJJIIIIIIJI;

	private int IIIIJJIIJIJIIIIJJJIIJJIJJJIIJIIJIJJJIIIJIIIJJJJ;

	private IIIIJIJJIJJJIJJJJJIJIJIJIIJJIIJJIJIIJIIJJJIJJJJ IJJIIJIJJIJJIJIJIIJJJIJIJIJIIIIJIJJIIIIJIIIIIII;

	private Dictionary<int, GameObject> IIJJJJIIJIJIIJJIJJIIIIJJJJIJJIIIIJIIIJIJIIIJJII;

	public bool IJIIIJIIJIJJIIJIJJJJIIJJIJIIIJJIIJJIJJIIJIJJJIJ;

	public bool JIIIIJJJJJJIJJJIIIIIIJJIJIIIJJIIJIIJJJIJIIJIJIJ;

	private byte IJJIIIIJJJIIJIJIIJJIJJIJJJIJJIIIIJJIIIJIIIJJJJJ;

	public int IJIJJJIIIIJJJJJIIJIIIIIIIJJJIJJIIJIJIJIIJIJIIIJ
	{
		get
		{
			return JJIIJIIIIJJIIIIIIIIIJJJJIIIJIJJIIJIJIIJIJIJIJJJ();
		}
		private set
		{
			JIJJJJIIJJJJIIJJIIIIIJIJJJJIJIIIIJIJIIIIIIJIIII(value);
		}
	}

	public IIIIJIJJIJJJIJJJJJIJIJIJIIJJIIJJIJIIJIIJJJIJJJJ IIIIJIJJIJJJIJJJJJIJIJIJIIJJIIJJIJIIJIIJJJIJJJJ
	{
		get
		{
			return IIJJJJIIJIJIIJJJIJJIJJJJJJJJIIJJIJJIIJIJIJJIJIJ();
		}
		private set
		{
			JIIJJIJJIIJJJIIIJJJIJJIIJJJJIIJJJIIJJIJIJJIJJIJ(value);
		}
	}

	public Dictionary<int, GameObject> IIIIJIJIIIIIIIIJJJIJJIIJIIJJJIIIIIJIJIJIIIIIJII
	{
		get
		{
			return IJIJJIJJIIJJJJIIIIIIJJJJIJIJIIJJIIIIIJIJIIJJIJJ();
		}
		private set
		{
			JJJIJJIJJJJJJIJJIIJJJIJJJIJIJIIJJJIIIJIIJIJIIIJ(value);
		}
	}

	private void IJJJJIJIJIIJIIJIIJJIIJJIIJIIJJJIIJIIIJJIIIIIJJI()
	{
	}

	public void OnDrawGizmos()
	{
	}
	private void IJIIJIJJJIIJIJJJIIJJJJJIIJIIJJJJJJIIIIJJIJIIJJI(IIIIJIJJIJJJIJJJJJIJIJIJIIJJIIJJIJIIJIIJJJIJJJJ JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	private void IIIIJJJJJIJIIJIIIIJJJIJIJIIIJIJJIIJIJJIJIIIIIIJ(Dictionary<int, GameObject> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJIIIJIIIIJJJJIIJJJJJIJJIJIIIIIJJJJJJJJJIIJJIJI()
	{
	}

	private void JIJJIIJJIJJJJJIIJIIJIJIIJJIJIJIJJIJIJJJIJIIIIIJ()
	{
	}
	public IIIIJIJJIJJJIJJJJJIJIJIJIIJJIIJJIJIIJIIJJJIJJJJ IJIIJJJIJJIIIIIJJIIJIJIIIIIIIJIIJIJJJIIIJJJIIII()
	{
		return null;
	}
	public Dictionary<int, GameObject> JJJJIIIJIJIIIIIIJJIJJIIIIJJJIJIJIIJJJIJJJJIIJIJ()
	{
		return null;
	}

	public IIIIJIJJIJJJIJJJJJIJIJIJIIJJIIJJIJIIJIIJJJIJJJJ IIJJJJIIJIJIIJJJIJJIJJJJJJJJIIJJIJJIIJIJIJJIJIJ()
	{
		return null;
	}

	private void JIJJJJIIJJJJIIJJIIIIIJIJJJJIJIIIIJIJIIIIIIJIIII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public Dictionary<int, GameObject> JJIJIJJIJIIIIJIJJJJIIJIJIJIIIIJIIIIIIIIIJIIJJJI()
	{
		return null;
	}

	public List<byte> JJJJIIIIIJIIJIJIJJJJIJIJJJJJIIJIJJIJJJJJJJIJIIJ(Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ)
	{
		return null;
	}

	private void JIIIIJJIIIIJIJJIJIIJIIIIJIIIIIJIIIIJIJJIJIIIIIJ()
	{
	}

	private void Awake()
	{
	}

	private bool JIIIJIJIJIIJIIIIJJJIJIJIIIJIJJIJIJIJIIJJJIIIIII()
	{
		return false;
	}

	private bool JIJJIIIJIIJJIIIIIJIJIJIJIIIJJIIJJJIJIJJIIIIIJJI()
	{
		return false;
	}

	public List<byte> JJIIJJIJJJIIIJIJIIJJIJIIJJIJIIIJJJJIJJJJJIJJIII(Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ)
	{
		return null;
	}

	private bool IIJJJJIJIIJIIJJJIJIJIJJJIIJIIJJJIIJJJIJJJIJJJJI()
	{
		return false;
	}

	private void IJIJJJJJIJJIIJJJJJIJIJJIJJJJJJIJIIIIIIJJJJIIIIJ()
	{
	}
	public Dictionary<int, GameObject> IIJIJJJIIIIIJJIIIJJJJJIJJJIJJJJJJJJIJJJIJIIIJII()
	{
		return null;
	}

	public int JJIIJIIIIJJIIIIIIIIIJJJJIIIJIJJIIJIJIIJIJIJIJJJ()
	{
		return 0;
	}

	private void JIIJJIJJIIJJJIIIJJJIJJIIJJJJIIJJJIIJJIJIJJIJJIJ(IIIIJIJJIJJJIJJJJJIJIJIJIIJJIIJJIJIIJIIJJJIJJJJ JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JIIJIJJIIJIIJIJJJJIIJIIJIIJJJIIJIIIJJIJJIIIJJJJ(JIJIJIJIIJIIIJJIJIJJIIJIIIIJJIIIJIIIIJJIJIIIIJJ IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, int JIIIIJIJIJJJIJJJIJIJIIIIJJJIJJJIIJJJJJJJIJIJIIJ)
	{
	}

	private void IJJIIJJIIJJJJJIJIIIIIIIJIJJJJJIJIIIIJJJJIJJJIII(JIJIJIJIIJIIIJJIJIJJIIJIIIIJJIIIJIIIIJJIJIIIIJJ IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, int JIIIIJIJIJJJIJJJIJIJIIIIJJJIJJJIIJJJJJJJIJIJIIJ)
	{
	}

	private void JIIIJIIJIJJIJJJIJJIJIJIIIJJIIIIIIJJIJIJJIIIJIIJ(JIJIJIJIIJIIIJJIJIJJIIJIIIIJJIIIJIIIIJJIJIIIIJJ IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, int JIIIIJIJIJJJIJJJIJIJIIIIJJJIJJJIIJJJJJJJIJIJIIJ)
	{
	}

	private void JJJIJJIJJJJJJIJJIIJJJIJJJIJIJIIJJJIIIJIIJIJIIIJ(Dictionary<int, GameObject> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private bool JIIIJJIJJJIIIJJJIJJJIIJJJJIIIIIIJIJJIJIJIJJIJIJ()
	{
		return false;
	}
	public IIIIJIJJIJJJIJJJJJIJIJIJIIJJIIJJIJIIJIIJJJIJJJJ JJJJIIIIIIIIJJJIJIJJJJIIJJJIJIIJIIJIJIIIIIJIJII()
	{
		return null;
	}

	public Dictionary<int, GameObject> IJIJJIJJIIJJJJIIIIIIJJJJIJIJIIJJIIIIIJIJIIJJIJJ()
	{
		return null;
	}
}
