using UnityEngine;

public class DeadTrigger : MonoBehaviour
{
	private sealed class IJJJIJIIIJIJIJJJIJIIJIJIJIIJIJIJIIIIIJJJIIJJIIJ
	{
		public IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ;

		public DeadTrigger JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		internal void IIJIJIJJIJJIIJJJJIIIIIJIJJJIIJJJJIJIJIJIIIIIIJJ()
		{
		}

		internal void IIIJJIJJIJIJJJIIIIIIJJIJJIJJJIIJIJJIJJJIIJJIJII()
		{
		}

		internal void IJJIJIJJIJJJJJIJJIIIIIJIJJJIIJIJIIIJIJJIJJIJIJJ()
		{
		}

		internal void JIIIIIJIIJIIJJIIIJIJIJJJIIIIJIJJJIJJIJJIIIJJJJJ()
		{
		}

		internal void IJJIIJIJIJJJIIJJIJIIJIJJJIIIJIJIJJJIJJIJIJJIJJJ()
		{
		}

		internal void JIIJIIIIIIJJJJIIJIJIIIIJIJJJJJIJJJJIJJIIIIIIJIJ()
		{
		}

		internal void JIIIIJIJJJIIIIIJIJIIJIJIJJJJJIIIIIIIIJIIIJIIIJJ()
		{
		}

		internal void JIJIJJJJJJJJJJIIIIIJJIIIJJJIJIIIIJJIIIIJIIIJJIJ()
		{
		}

		internal void JJIJIJIIIJIIJIJIIJIJJJJJJIJJJIIIJIIJJJJJIIJIJJI()
		{
		}

		internal void JJJJJIIJJJJJJIIJIIJIIIIIIJIJIJIJIIIIJIIJIJIJIJI()
		{
		}

		internal void IIJIJIIJJIJJJJJIJJIJIJIJIJIIIJIIJIJIIJJJIJJIIJJ()
		{
		}

		internal void IJJJJIJJIIIJJJJJJIIJIIIIIJJIIJJJIIIJIJIIIJIIJII()
		{
		}

		internal void JJIJIIJJJIJIJIJJIJIJJIJIJJJJJIIJIJJJJJJJIJIJJIJ()
		{
		}

		internal void IIJIJIJIIJJJIJJJJJIIIJJJIIIIIIIIIJIIIIIJIIJIJJI()
		{
		}

		internal void JJIIJJJJIJIJJJJIJIJIJJJJIJJJJIIIJJIIJJIIIJIIJII()
		{
		}

		internal void IJIJJJJJIIIIJJJIJIIIIJJIJIIIIIIIJIIJIIJIJIIJIIJ()
		{
		}

		internal void JJJJIJJIIJJJIJJIJIJJIIJJIIJIIIIIIJJIJJIJIIJIIII()
		{
		}
	}

	public bool JJJJIIIIIJIIJJJJJIIJJIJJJIJIIIJIIIJIJJIIJJJJJJI;

	private BoxCollider IJJIJIJJJJJJJIIIIJJJIJJJJJJIIJIIIIIJJIIIIJIJJJJ;

	private Bounds JJIJIIJJJJJIJJJIIIIJIIIIIJIJIIIJIJIIJIIIIJJJJJJ;

	private bool JJIIJJIIJJIJIJIJJJIIJJJIIIIJIJIIIIIIJIIIIJJIJJJ;

	private void IJJJIJIJJIIIJJIJJJJJJJIJIJIIIIJJJJIIJIJJJIIJJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void Start()
	{
	}

	private void IIIIIJIJJIIIIJIIIIJIJJJIJJJJJIJIIJIIJJJIIJJIIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void JJIIJIJJJJJIJJJJIIJIJJJJIJJJIIJJJIJJJIIJJIIIIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private void IIIIJIJIJJIIJIIIIJIJIJIJIJIIJIJIJJIJJJJJIIIJIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIIJJIIIIIIJIIJIJIIJJIJJJIJIJJJIJJJJIIJJJIJJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIJJIIJIIIJJJIIJJJJJJJIJIJIJJJIIIIIJIJJIIIIIJIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void IJIJJIIIJIJIJIIJJIJJJIJIJJIJIIIIJIIIJIJJIIIJIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}
}
