using System.Runtime.CompilerServices;
using Photon;

public class DeathRun : MonoBehaviour
{
	private static DeathRun JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void Awake()
	{
	}

	private void IJIJIIJJJJJJJJJIIJIJJIJIJIJIJJIJJJIIIJIJIIJJIIJ()
	{
	}

	private void IIIJJJJJIJIIJIJJIIJIIJIIJIJJIIIJJIJIJJJIJIIJIJI()
	{
	}

	private void OnDisable()
	{
	}

	private void IJIJIIJJIJIJIIJJJJIJIJIJIIJJJJIJJIJIJJIJJJIJIJI()
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void IJIIJIIIJIIJIJIJIIJIJJJIIIJIJJJJIJJJJIJJJIIIIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJJJIIIIJIIIIIJJIIJIIIJIJJJJJJJJJIIJIIIIIIJIJJ()
	{
	}

	private void IIJIJJIIIJIJIJIIIJIJIIJJIJIJIJIIIIIIJIIIIIJJJIJ()
	{
	}

	private void IIJIIIJJJJJJJJIJJJJIJJJIJIJIJIIIIIIIJJJIIIIJIJI()
	{
	}

	private void IJJIJJJJJIJIIIJJJIJIJIIIIJJIJIIJIIJIJJIIIJJIJIJ()
	{
	}

	private void JJIJIIIIJIJIJJIIIJIJIIJJJJJJIIIJIJJIIJJJJJJIIJJ()
	{
	}

	public static void IIJJIIIJIIJJJJJJJJJJIJIIJJIIIJIJIIJJIJIJIIIIIII(byte IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void IIIJIJJJJIIJJJJIJIIJIJJJIIJIIJJJIIJJIJIIIJJJJII()
	{
	}

	private int IJIJJJIJJIIJIJIJJJIIJJJJJIJJJJJIIIIIJIIJJIIIIII(int JJIJIJJJIIJJIJJJJIJJIIIJIJJJJIJJJJJJJJJIJIIJJJJ)
	{
		return 0;
	}

	[CompilerGenerated]
	private void JIIIJJIIIIIIIJIIIJJJIJIIIJJIJJIIJIIJIJIIJIJJJJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIJIIJIJIJJJJJIIJIIIJIJJIJJJIJJJIIJJIIJIIIIJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void JJJIJIJIJIJJIIJIIJIJJJJIJIIJJJJIJIIJIIJJJJJIIIJ()
	{
	}

	private void JIIJJIJIIIIIIIIIIJJIIJIJJJIIIIIIIJIIIJIIIJIJJII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIIIIJIIIIIJJJJJIJJIIIJIJIJIIIJIJJJIJJIJJIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void IIIJJJJIIIIIJIJJIJJIIIJJIIJJJIIJIIIJJIIIIIIJIII()
	{
	}

	private void IJJJJJJIJJIIIIJIJIJJJIIIJJIIIIJJIJIIJIIIIJJJJIJ()
	{
	}

	private void IJIJIJJIJJJIIJJIJJJJJIIJJIJIIIIJIIJIIJIJJJJJJJI()
	{
	}

	private void JIIIIJIJIJIIJIIIIJIJJIIIIIIIIJJJJIIJIJJJJIIJIII()
	{
	}

	private void IJJJIJJIJJJIJIJJJIJIIJIIJIJIIJJJJJIIJJIJIIIJJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void IIIIJIIJIJJIIJJIJJJJJJJJIIJIJJIJJIIIJJIIIIJIIII()
	{
	}

	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII()
	{
	}

	public static void IIJIJJJJJJJIJJJJIIIJJJIJJIJJJJIIJIJJJIIIIIIJJIJ(byte IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII()
	{
	}

	private void Start()
	{
	}

	private void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void JIIIJJJJIIIJJJIJJIJJJJIIIJIIIIIIJIIJIIIIIIJIJII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJIJJJIIJIJIJIJJIIJJJIIIIIJIIJIIJJJJIIJJJIJJIJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJIIJJIJIJIJJIJJIIJJIIIIIIJIJJJJJIJIJJIJIJIJJJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIIIJIIIJJJJJJIJIIIIJJJJIIJIIIJJIJIJIIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnEnable()
	{
	}

	private void JJIJJJIJJJJJIIJJIIJIIIIIIJIIJIJJIIIJJJJJIIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJIIJIJJJJIJJJJJIIJIJJIIJIIIIIJIIJIJJIIJIIIJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJIIIJIIJJJIIIIJJJIJIJJIJJIIIJJJJJJIIJIJIJJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void IJJIIIJIIIIJJIJIIIJJJJIJIIIIIIIJIIJJJJJIJIIIJJJ()
	{
	}
}
