using System.Runtime.CompilerServices;
using Photon;

public class Deathmatch : MonoBehaviour
{
	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IIIJIJIIJIJJIJJJIJJIIJJIIIJIJIJIJJJIJJIJIJJIIII;

	private IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIIIIJJIIIJIJIJIJIIIJIIIJIJJJIJJIIIJJIJIJIIIJJJ;

	private IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JJJIIJJIIJIIIIJJIIJJIJIIIIIJJIJIJIJJIIIIJIIIIJI;

	private void JIJIIIJJIIJIIIJIJIJIJIIJIIIIIJJJJIIJIIIJIJJJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void IJIJIJJJIJIIJIJIIIJIJIJJJIIJJIJJIJIIJIIJJIIIIJI(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	public void JJJJJJJJIJIIIJJIJIIIIIIJJJJIJIJIIIIJIJIJJIIJIJI(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	private void JIJIJIIIIIIIIIJJJIIIJIJIJJJIIIJJJJJIIJIIJJJJIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJJJJJIJJJJIJIJIJIIIJJJJJIJIJIIJIJIIJIIJJJJIIJ()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void JJJIIIJIJIJJJIJJIIJIIJIIJIJJJJIJIIJJJIJIJIJIJJJ()
	{
	}

	[CompilerGenerated]
	private void JIIIIJJJJJIIJJJJIJJJIJJJIIIIIJJJIIIIJIIJIJIJIIJ()
	{
	}

	private void JIJIIIJIJJJJIIJIJJJJJJIIIIJIJIIJJJJIJJIJIIIJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void Awake()
	{
	}

	private void JIIJJIJIIIIIIIIIIJJIIJIJJJIIIIIIIJIIIJIIIJIJJII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJIIIIJJIJJIJJJIIIIIJJJJJIIIJJIIJIIJJJIJIJJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIJJIIIIIJJJJJIJIJJIIIIIIIJJIJJJJJIJIIIJIJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJIJIIIIJIJJIJIJJIIIJIIJIJIJJJIJJIJJJJJJJJJJIJJ()
	{
	}

	private void JIJIJIIIIIJJIJJIJJIJJIIJIJIJIIIIIIIIIIJIJIJJIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	public void JIIJIIJJJIJJJIIJJIJJJJJIJJJJIIIJJIJJJJJJJJJIJJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	private void JJIJIIJJIJIJJJIJJIIIIIIIIJJJJJJJJIJIIJIJIIJIJII()
	{
	}

	[CompilerGenerated]
	private void JJJJIJJIJIJIJJIIJIJIJIIIJJIIJJIIIJJIIIIIIIJIJII()
	{
	}

	private void IJJJIIIJIJIJIJJJIIIIJJIIJIJJIJJIIJJJIIJJJIJIJII()
	{
	}

	private void IIJJIIIIIJJJJJIIJJJJJIJIJIIIJIJJJIJIIJIJIJJIIII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void Start()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIIIJIIIJJJJJJIJIIIIJJJJIIJIIIJJIJIJIIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void IIJJJJIIJIJIJIJJIJJIJJJJIIJJJJJJIJJIIJIJIIIIJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	private void JIIJJJIIJJIIIIIJIJJIJIIJJIIJIJIJIIJJIIIJIJJIIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJJIJIIJIIIJJIIIJIJIIIIIIJIIIIIIJJIIJJIJJJIIJI()
	{
	}
}
