using System.Runtime.CompilerServices;
using UnityEngine;

public class DecalsManager : MonoBehaviour
{
	public float IJIIIIJIIIJJIIIIIIJIJIIJIIJJIJIIJIJJJIIIJIJJIIJ;

	public MeshFilter IIIIIJIIJJJJIJIIIIIIJJJJJIJIIJIIJJJIIIJIIIJJIIJ;

	public int IIIIJIIIJIIJIJJJIIIIIJIIIIJJIIJIJJIIIJJIJIIJIII;

	private int JJJJJJJIJIIJJIIJIJIIIJJJIJJIIIIJJIJIJIJJJJJJIJI;

	private Mesh IJJJJIIJIJIIJJJIJIIIIIIJJJIJJJIIIJIJIJIIJIJIJJJ;

	public Transform IIIIJJJIJIIJJJJIJIIJJJJIIIIJIIJJJJJIIJJIIIIJJJJ;

	private int JIIJIJIIIJIIJIJIIJJIIJJJJJIJIIJIJJJIIIIIJIIIJII;

	private static DecalsManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private Vector3[] IIJIJJJIIJIIJIJIJIIJJJJJIJIIJIJJIJJJJJJIJJJJJJJ;

	private int[] JIJIJJIIIIJJIJIIIIIIIJJIIJIIIIJIIJIIIIJIJIIIJJJ;

	private Vector3[] IJJIIJJIJIIJIIIIJJIJJIIJJIJJIJIIIJJJIIIIJIJJIII;

	private Vector2[] IJIIIIIJIJJJJJJIIIIJJJIJJIIJIJIJIIJJJJJJIIJIJJJ;

	private static Vector3 JJIIJJJJJJIIJJJIIJJJJJIJIJJIIJJJJJIJIIIIIIIIIJJ;

	private static Vector3[] IJJJIIIIIIJJIIJJIIJIJJIIIJJJJIJIJJIIJIIIIIJIJJJ;

	public static void IIIIIJJJIJIJJIIJJIIIJJIJIIJJJIJJJIIJJIJJIIJIIJI()
	{
	}

	public static void JIJIIIJJJJIIJIIIIJJIJIIIIIJJJJJJIJIIIIIIIJIIIJJ(IIIJJIJJIIJIIIJIIIJIIJIIJJIJJIJIJJIJJIIJIJIJIJI IJIIIJJJJIJJJJJJJIIJIJIJJIIJJIIJJJJIJJIIJJIJIJI)
	{
	}

	private static Vector3 JIJIJJJIIJIIIJIIIIJJIJIJIIJIIJJJJJIJJJIIJIJJIIJ(Quaternion IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII)
	{
		return default;
	}

	public void JIIIIIJIJIIJIIIIIJJJIIIJJIIIIJIIIIJIIJIJIJJIJJJ(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	private void JJIIJJJJJJIIIIIIJJJJJIJIJIJJIJIJJIIIIIJJIIJIIJI()
	{
	}

	public void IIJIIJIJJJJJIIJJJJIJIJIJIIIJJIJIJJIJJJJIJJJJJII(Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII, Vector3 IIJIJIIJIIIIIIIJIJIIJJIJIJIJIIJJIJIIIIIIJJIIIII)
	{
	}

	private static Vector3 JIIIJIIJJIIJJJIJIJIIIIJIJJIJIIJIIJIIJIIJJIJJJIJ(Quaternion IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII)
	{
		return default;
	}

	public static void IIJIIIIIIJJIIIIIIJIJJIJIIIJJIJJJJJJIIIIJIJIIIJI(IIIJJIJJIIJIIIJIIIJIIJIIJJIJJIJIJJIJJIIJIJIJIJI IJIIIJJJJIJJJJJJJIIJIJIJJIIJJIIJJJJIJJIIJJIJIJI)
	{
	}

	private void IIIJIJJJIIJIIIJIIJJJIJJIJIIJJJIJJIIIJJJJIIJJJIJ()
	{
	}

	private static Vector3 IIIIIIIIJJIIIJJIIJIJIIIIJJIJIIIIIIIIJJIJIIJIJII(Quaternion IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII)
	{
		return default;
	}

	private static Vector3 IJIIIIJIIJIIIJIIIIJIJJIIIJIJIJJIJIJIJIIJJIIIIJJ(Quaternion IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII)
	{
		return default;
	}

	private void IJJIIJIJIJJIJIJJIIIJIJIJIIIIJIIJIIJIJIIIJIIJJIJ()
	{
	}

	private void IIJIIJJIIJJJIIIJJJJIJIIJIJIJJJIJIJIIIIIJIIJJJJJ()
	{
	}

	private void Awake()
	{
	}

	public static void JIIJIJJIJIIJJIIJJJJJIIJIIJIJIJJIIJJIJJJIJIIJIIJ()
	{
	}

	public void JIIJIIIIJJIIIJJJJJIIIJJIJJIJJIIJJJJJJIJIIIJJIIJ(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	public void IIJIIJJJIIIIIIJJIJIIJJIIJJJJJJJJJJIIIIIJIJJJJIJ(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	private void IJIIJJIJJJIJIJJJIIJIJIIJJJJJIJIJJJJIIJIIJIJJJJI()
	{
	}

	private void JIJIJJIJIJJIIIJIIIJIJIIJIIIIIJJJJIJJIJIIIIIJJIJ()
	{
	}

	public static void IIIIJIIJJJIJJJJIJJIIJIJIIIJJJIIJJJJJIIJJIIJIJIJ(IIIJJIJJIIJIIIJIIIJIIJIIJJIJJIJIJJIJJIIJIJIJIJI IJIIIJJJJIJJJJJJJIIJIJIJJIIJJIIJJJJIJJIIJJIJIJI)
	{
	}

	private static Vector3 IJJIIJIJJIIIJIIIIIIIIIIIJJIIIIIIJJJJJIJIIJJIJIJ(Quaternion IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII)
	{
		return default;
	}

	private void JJJIJIJIIIIIIJJIIJJIJJIJJJJJIIIJJIIIIJIJJJIJIIJ()
	{
	}

	private void IJIIIIJIIJJJJJJIIIIIIJJIIIJIIJJIIIJJJIIJJIIJJJJ()
	{
	}

	public static void IJJJIIJIIIIJIJIJIJJIJIIJIJIIJJIJJJIJJJJJIIJJJII()
	{
	}

	[CompilerGenerated]
	private void JJJIIIJIIJJJJJJJIJIJIJJJJIIJJJIJIIIIJIJJJIIJJII()
	{
	}

	private void IJIJIJIIIJJJJJIIJJIIJIJIJJJIIJJIIIIJJJJIIIJJIII()
	{
	}

	public void IJJIJJIJJIIIIIJIJJJIJJJIJJIJIIJIIJIIJIIJIJIJIJI(Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII, Vector3 IIJIJIIJIIIIIIIJIJIIJJIJIJIJIIJJIJIIIIIIJJIIIII)
	{
	}

	private void Start()
	{
	}
}
