using System.Runtime.CompilerServices;
using Photon;

public class EscortMode : MonoBehaviour
{
	private sealed class IIIIJIJJJJJIIJIJIJIIJIJJIJIJIJJJJJJJIJJIIJJIIIJ
	{
		public EscortMode JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII;

		internal void IJIJJIIJIJIIIJIIIJIIIJIJIIIJJJIJIIIJIJIIIJJJJIJ()
		{
		}

		internal void IJJJJIIIIIIIIJJJIIIJJJJJIJJIIJIJIIJIIIIJIJIIJIJ()
		{
		}

		internal void IIJJJIIJIJJIIIIJJIIIJIIIJIIJJJIJJIJJJJJIJJIIIJI()
		{
		}

		internal void JIJIIIIIJIJIJJIIJIIJIJIIJJIIJJJJJIJIIJJIIIIJIIJ()
		{
		}

		internal void JIJIJIIIJJIIJIIJJIIJJJIJIJIJIIIIJIIJIIJJJIIJIIJ()
		{
		}

		internal void IJJJJJJIIIJIIJIJJJIJJIJJIIJIJIJIJJJIIIIJJJIIIII()
		{
		}

		internal void IIJIJIIIIIIJIIJIJJIJIIIJIJIIJIIIIIIJIIJIIIIIIJJ()
		{
		}

		internal void JIJIJJJJJJIJJIIIIIIJJIIJJIJIIIIJJJJIJJJJJIJJJIJ()
		{
		}

		internal void JJJJJJJJIJIJIIIJIJIJJIIJIJJJIIIJIJJJIJJIJJJIJII()
		{
		}

		internal void IIJJJJIJIJIJIJJJJIJJIIJJJJJJIJJIIIIIJIIIIIJJIII()
		{
		}

		internal void IJIJJIJJIJJIJIJJJJIIIIIJJJIJJIJJIJIIIJIIIIJIIII()
		{
		}

		internal void IJIIIIJIJIIJIIJJJJIIIJJJIIJIIIJIIJJIIJIJIIIIIJJ()
		{
		}

		internal void JIIIIJIIJIJJJIIJIIJIJIIJIIIIIJIIJIJIJJIIIJIIIII()
		{
		}
	}

	private sealed class IJIJJJJJIJJJJJIIIIIJJJJJIJJJIIIJJIJIIJIJJIIJIIJ
	{
		public float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

		public double JIJJIJIIJIIJIJJJIIIJIIJJJJIIIIJJJIIJJJIIJIJIJJJ;

		public EscortMode JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		internal void JIJJIJJJJJJJJJIJJJJJJJJIIJJIIJJJJJJIIIJJIJIJIJJ()
		{
		}

		internal void IJIJJJJIIIJJJIJJJJIIIJIJIJIJIJJIJIIJJIIIIJJJJII()
		{
		}

		internal void IJJIIJIIJJJIJIIIIJIIIIIIIJJIIJJJJJIIIIJJJIIIJJI()
		{
		}

		internal void JJJIJIIIIIJJJIJIIJIJJIJJIIJJIIIJIIIJIIJJIIIIIIJ()
		{
		}

		internal void JJIJIJIIIIJJJJJJIJJIIIIIJIJJIIJIJIIJJIIJIIJIIII()
		{
		}

		internal void JIIJIJJJIJIIJJIIIIIJJIJJIIIIJJIIJIJIIJIIJJIIJII()
		{
		}

		internal void IJIIJJJIIIIIJIIIIJJIIIJIIJJIJJIJJIJIIIJIJJJJJJJ()
		{
		}

		internal void IIIIJJIIIIJIIIIJIJIJJIIJJIIIIIJIJIIIIIIIIIJIJJI()
		{
		}

		internal void IJJJIIJIJJIIJJIIIIIJJJJJIJIIJIIIJJIIIIIIIIJJIJJ()
		{
		}

		internal void IIIJJJIJIIIJJJIIIIIJJJIIIJIJJJJJJJIJJIIIJIJIJJJ()
		{
		}

		internal void JIJIJIJIIIIJIIIIIJIIIIIIIIJIIIIJIIIIJIJIJJIJIII()
		{
		}

		internal void JIIIJIIIJJIJIJIIJIJIJJJIJIJIIJJJIJJIIIJIIJIJIII()
		{
		}

		internal void JJIIJJIJJIIJJJJJIJIJIIIIIIJJJIIIIIIIIIJIJIJJJII()
		{
		}

		internal void IIJJJJJJJIJJJJIJJIJIIIJIJJJJIJIJIJJIIIJJIIJJIIJ()
		{
		}

		internal void IJJJJIIJJJJJJJIJIIIJJIJIIJJJJJJJJJJIIJJJIIIJJIJ()
		{
		}

		internal void IIIIIJIIJIIJIIIJIIIJIIIIIJIIIIJIIJIJJJJJIJJIIIJ()
		{
		}

		internal void IJJIJIIIJIIJIJIJIJJIJJJIJJJIIJJIJJJIJJJIIIJJIIJ()
		{
		}

		internal void IIIJJJJIJIIJIIIJIIIJJIIIJIJIIJIIJJJJIJIJIJJIJJI()
		{
		}

		internal void JJJIIIIJIJJJIJJJIIJIIJJIJIIIJIIIIIJJIJJJJJJJJIJ()
		{
		}

		internal void IJIJIIJJJIJJIIIJJJIJJJIJIIIJJIIIIIJIJIIIIJJJJII()
		{
		}

		internal void JIIIIJJJIJJIIJJJIIJIIIJIIJIIJJIJIIIIJIIIIIIIIJI()
		{
		}
	}

	public static bool IJJIIJJIJIIJIIIIIIIJIJJJIIIJIIIJJIIJIJIJIIJIIJI;

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void Awake()
	{
	}

	private void JIIJIJJIIIJJIJIIJJIJIIIJIJJIJIIIIIJIJJJIIJIJIIJ()
	{
	}

	private JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII[] IJJIJJJIJJJIIJJIIIJIIIIIIIJIIJJJIJJIIJIJIIIIIJJ()
	{
		return null;
	}

	private void JJIIJIJJIIJIJJJIIIJIIIIJJJJIIJJIIJJJIIJJIJJJJII()
	{
	}

	private void IIIIIJIIJJJIIJJIIIIIIIJJIIJIJJJIIJJJJIIIIIJJJIJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void OnDisable()
	{
	}

	private void Start()
	{
	}

	private void IJJJIIIJIJIJIJJJIIIIJJIIJIJJIJJIIJJJIIJJJIJIJII()
	{
	}

	private void OnEnable()
	{
	}

	[CompilerGenerated]
	private void JJIIJIIIIIJIIIJIIIJIJIJJIJJIIIJJJJIIJIJJJIIIJIJ()
	{
	}

	private void JJJIJJJIJIJJJJIJJJJIIIIJJIIIJJJIJJJIIJJIJJIIJII(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void JIIJIIIIJIJJJIIIIIJJIJJJJJJIIIJIIJJIJIJIJIJIIIJ()
	{
	}

	private void IIJJIJIJJIIIIJJJIJIIJIJJJJIJJIJIIIIIJJJIIJIIJII()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void JIJIIIJJIIJIIIJIJIJIJIIJIIIIIJJJJIIJIIIJIJJJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void IJIJJJIIJIIJIJJIJIJIIIJIJIJJIIIIIIJJIJIJIJIJIJJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIJJIIIIIJJJJJIJIJJIIIIIIIJJIJJJJJIJIIIJIJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJIJIIJJJJIJJJJJJIIJIJIIJJJJIIIIIIIIIJJJJJIJJJ()
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	[CompilerGenerated]
	private void IIIJIJIJIJJIJJIJJIJIIJJJIJJJJJJIJJIJJIJIIJJJJJJ()
	{
	}

	private void JJIIJIJJIJJJIJIJIIJIIIJJIIIIJJJJIJJJIJIJIIIIIJJ()
	{
	}

	private void IJIJIJJIJJJIIJJIJJJJJIIJJIJIIIIJIIJIIJIJJJJJJJI()
	{
	}

	private void JIJIJIIIIIJJIJJIJJIJJIIJIJIJIIIIIIIIIIJIJIJJIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIJIJJJJJIJJIJIJIIIIIIIJIJIJJIIJJIJIIIIIJIJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIIIJIIIJJJJJJIJIIIIJJJJIIJIIIJJIJIJIIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void JIIJIIIIJJIJJIIIJJIJJJIIJIJIJJIJIIIIIIJIJJIIJJJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJJIJIIJIJIJIIJIIJJJJJIJJJIIJJIJJJIJJIIIJIIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJIIIIJIJJIIJJJIIIJIJIJJIJIIJJJJJIJJIIJIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}
}
