using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.CompilerServices;
using UnityEngine;

[Serializable]
public class EventDelegate
{
	[Serializable]
	public class Parameter
	{
		public UnityEngine.Object obj;

		public string field;

		[NonSerialized]
		private object mValue;

		[NonSerialized]
		public Type expectedType;

		[NonSerialized]
		public bool cached;

		[NonSerialized]
		public PropertyInfo propInfo;

		[NonSerialized]
		public FieldInfo fieldInfo;

		public object value
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		public Type type => null;
		public void JJIIJJJJIJIJIIIJJJJIIJIIIIIIJIIJJIJIIIIIIIJIIJI(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}
		public object JIIJJIIIIIJIJJIJJIJIIIIIJJIIJIJIJJIIJJIIJJJIJJI()
		{
			return null;
		}
		public Type JIJJJJJIJJIJJIJIJJIIJJJIIJJIJJIIIJIIIIIJJJIJIII()
		{
			return null;
		}
		public Type IJIJIIJIJJIJIJIIIJJIIJIJJJIJIIJIJIJJJIJIJIIIIJI()
		{
			return null;
		}

		public Parameter(object JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
		{
		}
		public void JJJJJJJIJIIIIIIIJIIJIIIIJIIJJJIIIIIIIIJJIJJIJJI(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}

		public Parameter()
		{
		}
		public void JIJIIJJIIIIJIJJJJIJJJJJIIJJJJJIJJJJJIIJJJJIJIII(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}
		public void JIIIJJJIIJJIIIJJJJJIJJJJJJJIIJJJIIJJJJIIIJJJIJI(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}
		public Type IJJIIIJJIJIJIJIIIJJIJIIJIJJIJJIIJIJIJIIJJIIIIJI()
		{
			return null;
		}

		public Parameter(UnityEngine.Object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, string JJJJIJIIJIJIJIIIIJIJJJIIIIJJJJIIIIJIIJJIJIJIIJJ)
		{
		}
		public object IIIIIIIJIIIIJJIJIJIIJJJJIJJJJJIIIJJJJIIIJJJJIIJ()
		{
			return null;
		}
		public object JIJIIJJIIJJIIJIIJJIIIJJJJJIJIJIJIIJIIIJIJJJIJII()
		{
			return null;
		}
		public Type IIJJJIIJIIIIIJIJIIJIIIIIIIJIIIIJJIJJIIJJJJJJIII()
		{
			return null;
		}
		public void IIIIIIJIJJIJJJJJJJJIJJIJIJJIJIIJJJIJJIIIJJIIJIJ(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}
		public void IIJJJIIJIIJIJIIIJIJJJJIIJJJJIIIIIIJIIJJIIJJJIII(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}
		public object IIJIJIJJIIJIJIIIJJIJJIIJIIIIIJJJJJJIIIJJJIJJIIJ()
		{
			return null;
		}
		public object JIIJIIIIIIJIJIJJJJIJIJIJIIIJJJIJIJJIIIIIIIJJIII()
		{
			return null;
		}
	}

	public delegate void IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ();

	[SerializeField]
	private MonoBehaviour mTarget;

	[SerializeField]
	private string mMethodName;

	[SerializeField]
	private Parameter[] mParameters;

	public bool oneShot;

	[NonSerialized]
	private IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ mCachedCallback;

	[NonSerialized]
	private bool mRawDelegate;

	[NonSerialized]
	private bool mCached;

	[NonSerialized]
	private MethodInfo mMethod;

	[NonSerialized]
	private ParameterInfo[] mParameterInfos;

	[NonSerialized]
	private object[] mArgs;

	private static int s_Hash;

	public MonoBehaviour target
	{
		get
		{
			return null;
		}
		set
		{
		}
	}

	public string methodName
	{
		get
		{
			return null;
		}
		set
		{
		}
	}

	public Parameter[] parameters => null;

	public bool isValid => false;

	public bool isEnabled => false;

	public static bool JIJIJIIIIIIJIIIIJIJJJIJIJJIJIJIIJJIJIIIIJJJJIJI(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
		return false;
	}

	private static bool IIJIIIJJIJIIIIJIJJJIJJIJIIJIJIIIIJJIIJJIIJJIIJI(IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
		return false;
	}

	public virtual string JIJJJIJJIJIIIIIJIIIJJJIIJIJIIIIJIJJIIJJIIIJIJJJ()
	{
		return null;
	}

	public virtual string JIJIIJIJJIIJIJJIIJIJIIIJJJJIJIJIIIJJJJJJIIIIIJI()
	{
		return null;
	}

	public static EventDelegate JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
		return null;
	}

	public static bool JIJIJJIIJIJJIIJIIIJJJJJIIIJIIIJIIIJIIJJJJIIJIIJ(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, EventDelegate IIJIIIJJIIJIJJJIIJIJIIIIIJJIJIJIIIJIJIIIIIJIJII)
	{
		return false;
	}
	public void JJJIIJJIIIJJJJIIJIIIIIIIJJJJJIJJJIIJIJJJIIIIIIJ(MonoBehaviour JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static bool IIIJIIJIJIIIIJIIJJJJIJJIIJIIIJJIJIJJIJIJIJIJJII(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
		return false;
	}
	public void IIJIIIIIIIJJIJIJJIIJJJJJJIIIIIIIJJJJJJIIJIIJJJJ(MonoBehaviour JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}

	public bool IIJIJJIIJJIJIIIJIJIJJIIIIIIJIJIJIJJJJIJJIJIIIIJ()
	{
		return false;
	}

	public EventDelegate(IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ JIIIJIJJIJJIIJIJIIIIIJJIJJJJIIJIJJIIIJIJJJJJJIJ)
	{
	}

	private void JJIJJJIJIJIIIIIIIJJJJIJJJIIIJJIIIIIJJJJJJJIJIJI(IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ JIIIJIJJIJJIIJIJIIIIIJJIJJJJIIJIJJIIIJIJJJJJJIJ)
	{
	}

	private static bool JIJIJIIIIIIJIIIIJIJJJIJIJJIJIJIIJJIJIIIIJJJJIJI(IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
		return false;
	}

	public static EventDelegate IIJJIJIIIJJJJIJJJJIJJIIJJJJIIIJJJIIIIIJJIIIJJIJ(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
		return null;
	}

	public override int GetHashCode()
	{
		return 0;
	}

	public static EventDelegate JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI, bool JIJJIIIJIJJIIIIJIIJJJJIIIIIIJIJIIJJIJIIIIJJJJIJ)
	{
		return null;
	}

	public static bool IIIJJJJIIJJJIJIIIIJJIIIJJIJIIJIJJJIJIJIIIJJJIIJ(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, EventDelegate IIJIIIJJIIJIJJJIIJIJIIIIIJJIJIJIIIJIJIIIIIJIJII)
	{
		return false;
	}

	private void IIIJIIIJIIJIIIJIIJJJIIIJJJJJJIJIIIJJIIIJIJJJJJI()
	{
	}
	public string JJJJJIJIIJJIJJJIJJIIIJIIIIIJJJJJJIIJIIJJJJIIIJI()
	{
		return null;
	}

	public static void IIJIJJIIJJIJIIIJIJIJJIIIIIIJIJIJIJJJJIJJIJIIIIJ(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
	}

	public static void IJIIIJJJJIIJIIIJIJJJJIIIJIJJJIJIJIIIJIIIIIIIIJI(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
	}

	public static void JIIJJJIIIJJJJJIIIIJIIIJIJJIJIJIIJJIIJJIIJIIIJII(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, EventDelegate IIJIIIJJIIJIJJJIIJIJIIIIIJJIJIJIIIJIJIIIIIJIJII)
	{
	}

	public override string ToString()
	{
		return null;
	}

	public static bool JIJIIIJJIJIJJJIIIIJIIIJIIJJJIJJIJIJIJIJIIIJJIJI(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
		return false;
	}

	public static bool JIJIIIJJIJIJJJIIIIJIIIJIIJJJIJJIJIJIJIJIIIJJIJI(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, EventDelegate IIJIIIJJIIJIJJJIIJIJIIIIIJJIJIJIIIJIJIIIIIJIJII)
	{
		return false;
	}

	public void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}

	public EventDelegate(MonoBehaviour IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, string IJJJIJJIJIJJJJJJJJIIJJJJJJJIJIJIJIIJJIJIJIIJJIJ)
	{
	}

	public static EventDelegate JJJJJIJIJIIIIJJJJIIIJIIJJIJIJJJJJJIIIIIIIIIJIIJ(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI, bool JIJJIIIJIJJIIIIJIIJJJJIIIIIIJIJIIJJIJIIIIJJJJIJ)
	{
		return null;
	}

	private static string IJIJIIIIJJIJJIJJIJJJJJJJJIIJJJIIIIJJJJJIJJJJJIJ(IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
		return null;
	}

	public static EventDelegate JIJIIIJIIJJIJJIJJIIIIIJJJJJIJIJIJJJIJJIJJJJIIII(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
		return null;
	}

	public void JJIJJJIJIJIIIIIIIJJJJIJJJIIIJJIIIIIJJJJJJJIJIJI(MonoBehaviour IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, string IJJJIJJIJIJJJJJJJJIIJJJJJJJIJIJIJIIJJIJIJIIJJIJ)
	{
	}

	public static EventDelegate JJIJJJIJIJIIIIIIIJJJJIJJJIIIJJIIIIIJJJJJJJIJIJI(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
		return null;
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, EventDelegate IIJIIIJJIIJIJJJIIJIJIIIIIJJIJIJIIIJIJIIIIIJIJII)
	{
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, EventDelegate IIJIIIJJIIJIJJJIIJIJIIIIIJJIJIJIIIJIJIIIIIJIJII, bool JIJJIIIJIJJIIIIJIIJJJJIIIIIIJIJIIJJIJIIIIJJJJIJ)
	{
	}
	public bool JIJJJIJJJIJIIJIIIIJJJIIJJJJJIJIJIJIIIIJJIIIIJJJ()
	{
		return false;
	}
	public void JJIIJJJJJIIIIJJJIJIIIJIIIJJJJJJIJJIIIJJIIJIJJII(MonoBehaviour JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void IJJJJIJJJJIJJIIIJJIJJJJJJJJIIJJIIJJJIJIIIIIJJIJ(IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ JIIIJIJJIJJIIJIJIIIIIJJIJJJJIIJIJJIIIJIJJJJJJIJ)
	{
	}

	public EventDelegate()
	{
	}

	public static void JJIJJJIJIJIIIIIIIJJJJIJJJIIIJJIIIIIJJJJJJJIJIJI(List<EventDelegate> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ, EventDelegate JIIIJJJIIJIIIIIIJIIIIJJIIJIJIIIIJJIJJIIJIJJJJJJ)
	{
	}
}
