using UnityEngine;
using UnityEngine.Events;

public class EventTrigger : MonoBehaviour
{
	public UnityEvent IJJJIIIIJIIIIJJJIJJIIJJIIIIIJJJJJJJIIJJIIIIJJJJ;

	public UnityEvent JIJIJIIIIJIIIIJIIIIJJJJIIIJIIIJIIJIJIIIIIJJJIIJ;

	private BoxCollider IJJIJIJJJJJJJIIIIJJJIJJJJJJIIJIIIIIJJIIIIJIJJJJ;

	private void JIJIJIIIJJJJIIIJJJJIJIJJJJJJJIIIIJIJIIJIIIIIIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void Start()
	{
	}

	private void IJIIJJIIIIIIJIJJIJIJIIJJJIIJJJJJIJIJIIJIJIJIIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJIJJIJJJJJJIIJIIJIJIJJIJJJJJJJIIIJJJJIIIJJJIII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void IIIJJIIIJJJIIJIIIIIJJIIIJIIIJJJJIIIJIIIIIJIIIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIIIJIIIJIJJJJIJIIJJJJJIJJIJIIJJJJJIJIJJIJIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJJJIJIJJIIIJJIJJJJJJJIJIJIIIIJJJJIIJIJJJIIJJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void OnTriggerExit(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIIIIJIIJJIIJJIJJIJIIJJJIIIIJJJJJIIIJJJIJJJIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIIJJIIJIJJIIJJIJIIIJIJIJIJJIIJJJJJJIJIIJJIJIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJJJJJJJIJIIIIIIJIJIJJJIJJJJIJJIJIJJIJJIJIJJIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIIJJJJJJIJIJJIJJJJJIJJJJJJIIJJIIJIJIIJJJIJIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJIJJJIJIIIJJJJJIIJIJJIJJJIJIIIIIIIJJIJIJIIJJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}
}
