using UnityEngine;
using UnityEngine.Events;

public class EventListener2 : MonoBehaviour
{
	public UnityEvent IIJIIJJJIJJJJIJJJJJIIIJJIIIJIIIIJIJJIIJJJJJIIJI;

	public UnityEvent JIJJJIIJIIJIJIIIIJIIIIIJJJIJJIJIIJIIIJJJIIJIIIJ;

	public UnityEvent IIIJIIJJIJJIIJJIIIJIIIJJJJIJIIJIJIJJJIIJIJJJJIJ;

	public UnityEvent JJJJJJIIJIJIJJJJIIIIJJIJJJJIJJIIJIIJJIIJIIJJJIJ;

	private void JIIJIIIIJIJJJIIIIIJJIJJJJJJIIIJIIJJIJIJIJIJIIIJ()
	{
	}

	private void IIJIIIIIIIJJJIJJJJIJIJJJJJIJJJIJJIJJIJIIIJIIJJJ()
	{
	}

	private void IIJJJJJIIIIJIJIIIJIIJJJIJIIIJJIJJIJIJIJIIIJIIJI()
	{
	}

	private void JIJIJJJIIJIJJIJIIJIIJIIIJIIJIIJJIIIIIJIIIJIIIJI()
	{
	}

	private void IIIJJIJJJJJJJJIIJJIJJJIJJIIIIJIIIJJIIIIIIJJJJJJ()
	{
	}

	private void IIJJJIIJIIJJIIIJJJJIIJJJJIJJJJJIIIJIIIJIIJIIIII()
	{
	}

	private void OnBecameVisible()
	{
	}

	private void OnEnable()
	{
	}

	private void IIJJIIIIJIIJJJJJIJIIIJJIJJJJIIIIIIIIIJIJIIIIIII()
	{
	}

	private void JJJJJJJIJIIIIJJJJIIIIIJJJIJIIIIIIIIJIJJJIIJJIJJ()
	{
	}

	private void IJJIIJJIIJJIIJJJJJJIIIJJJJJIJIIJIJIIJIIJIIIIJII()
	{
	}

	private void JIJJJIJIIJIJIIIJIJIJIJJIIIIIJIJIIIIJIJJIIIJJJIJ()
	{
	}

	private void OnBecameInvisible()
	{
	}

	private void OnDisable()
	{
	}

	private void JJJJJJIIJJIJIIJIJJIIJIJIJJJIIJIIJJJIIJJIJJJIIII()
	{
	}

	private void IJJJIIJJJJIIJIIIJJJJIJJJIJJIIJIJJIIJJIIIIIIIIJI()
	{
	}
}
