using System.Runtime.CompilerServices;
using Photon;

public class FootballMode : MonoBehaviour
{
	private void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	[CompilerGenerated]
	private void IJJIIIJIIIIJJIJIIIJJJJIJIIIIIIIJIIJJJJJIJIIIJJJ()
	{
	}

	[CompilerGenerated]
	private void JJJIIJJJIJJJIIJJJJJJIJJIJIJIJIJIIJJIIJJIIIIJIJJ()
	{
	}

	public static int IIIJIJIJIIIIIIJJJIIIJJIJJIJIIJIJIIJIIIIJJIIIIIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	public static int IIJIJIJIIIJJJJJJIIIIJJIJJJJIIJJIIIJJIJJJIJIJIIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnEnable()
	{
	}

	private void IJJJJIIIIJIIIIIJJIIJIIIJIJJJJJJJJJIIJIIIIIIJIJJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIJJJJIIIJJJIIJIIIJIIJJJJIIIIIJIIIJIIIIIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII()
	{
	}

	private void JJJJIJJJJJJJJIIJIIJJJIJJIJJJIJIIIIIJJIIIIIIIJJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJIJJJIJIJJJJIJJJJIIIIJJIIIJJJIJJJIIJJIJJIIJII(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void Start()
	{
	}

	private void JJJJJIIIJJJIJIIIJIIIIJIJJIIJIIJIIJJJIIIJIIIIJIJ()
	{
	}

	private void IIJJIJIJIJIJJJJJIJJIIIIIIIJJIIIJJIIJJJIJIIJJJII()
	{
	}

	private void IIIIJJIIJJIIIJIJIIJIIJIJIJIIJIIIJJIIJIJJIIJJIII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void IIJIIIIJJJIJIJIJIJJIIJIJJIJJIJIIIIIJJIJJJIIJIJI()
	{
	}

	private void JJJJJJJIIJJIIJJIJIIJJJIIJIJJJJIJIIIJJJIIJJIIIJJ()
	{
	}

	public void JIIJIJIJJIJJJJJJIIIIJIIIJJJJJIJIJJIJJIIIIJJIIII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII, JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIIJJJIJJIJJIJJIJJJJIIJIJIIIJJIIIIIJJIIJJIJIJJI)
	{
	}

	private void IJIJIJJIJJJIIJJIJJJJJIIJJIJIIIIJIIJIIJIJJJJJJJI()
	{
	}

	private void IJIJIJJJIIJIJIIIIJIIIJJIIJJJJJIJIJIJIJIIIIIJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void JJJIIIIIJJIIIJIIIJIIIIIIJJIJJIIJIIJJJJIJIJIIJIJ()
	{
	}

	public void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII()
	{
	}

	[CompilerGenerated]
	private void JJJIJIJIJIJIJJIIIJJJJJJJIIJJJJJIJIJIJJIIJJJIIJI()
	{
	}

	private void JIIIIJIJIJIIJIIIIJIJJIIIIIIIIJJJJIIJIJJJJIIJIII()
	{
	}

	private void OnDisable()
	{
	}

	public void JIJIJJIIIJJJJIJIIJIJJJIIJIIIJJIIJIIJJIIIJIIJJJI(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII, JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIIJJJIJJIJJIJJIJJJJIIJIJIIIJJIIIIIJJIIJJIJIJJI)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJIJJJIJJJIIIJJIJIIIIIJIIIJJJJIIIIJJIIIIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static int JJJJIJJIIIIJIJJIJJIIIJIJIIIIIJJJJJIIJJJJIJIJIIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	[CompilerGenerated]
	private void IIIJJJIJJIIIJJIJJJJIJJJJIJJJIIIJIJIIJJIIJJJIIJJ()
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void IIIIIJJJJIJIIJJIIJIJIJIIJIIIJJIIIJJJIIJIIIIIJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJIIJJJIIIJJIJJIJIJJJJJIJJIIIIIJJIJJIIJJIIJIIJJ()
	{
	}
}
