using UnityEngine;

public class FootballManager : MonoBehaviour
{
	public GameObject IIJJJIJIIJIJJJJIJIJIJIIJJJJIIIJJIIJJJIJJJJIIIJI;

	public Vector3 IJJIIJJIIJIIIIIIJJIJJIJIJJJJJIJJJIIJJIIJJJIJJJJ;

	private static FootballManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void JIIJIIIJJIIIIIIIIJIJIIJIIIIJJIJIJIJIJJJIJIIIJJI()
	{
	}

	public static void JIJIIJIJJJIIIJIIIJJIIIIJIIIJIJJIIIIIJJIIIIIJIII()
	{
	}

	public static void IJIJIJIJIIIIJIIJIJIJIJJJJIIJIIJIIIJIJJIIIJJJJIJ()
	{
	}

	private void Awake()
	{
	}

	private void JJIJJIIIJIJIJIJIJIIJIJIJJJJIIIIJJIIIJIIIJIIIIJI()
	{
	}

	public static void IJJJJJJIJIJJIJIIIIIIIJIJJIIIJJJIIIIJJIIIIIJJJIJ()
	{
	}

	private void IJJIJJJJJIJIIIJJJIJIJIIIIJJIJIIJIIJIJJIIIJJIJIJ()
	{
	}

	private void JIIIJJIJIJJIJJJIIIIJJJIJIJIJIIIJJJJIJJIIIIJJIII()
	{
	}

	public static void JJJIJIIJIIJIJJJJJJJJIIIJJIIJIJJIJIJJIJJIJJJJIJI()
	{
	}

	public static void JJIJIIJIJJJIJIJIIIJIIJJIIJIIIIIJIJIJIJJIJJJJIJI()
	{
	}

	public static void JIJIJIIJIJIJIIIJIJJJIIIIIIIJJIJJIIJJIJIJIJJJJJI()
	{
	}

	private void JJIJIIIJIJIJJJJIJIIJJJJJIJJJJJIJIJIJIIJIIJIIIJJ()
	{
	}

	private void IIIJIJJJIIJIIIJIIJJJIJJIJIIJJJIJJIIIJJJJIIJJJIJ()
	{
	}

	public static void IIJJIJIJIIIJIIJIJIIJJJIJJIIIJJJJIIIIJIJJJIJIIJJ()
	{
	}

	private void IIJIIJJJIIJJJIIIJJIJIJJIIJJIIIJIJJJIJJIJIJJIJJI()
	{
	}

	private void IJJJJIJJIJJIIJJIJIJIJIIJJJJIIIJJJJJIJIJIJIJJJII()
	{
	}

	public static void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}
}
