using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.CompilerServices;
using UnityEngine;

public class GameConsole : MonoBehaviour
{
	public enum JIJJJIJIIJIJJIJIJIIIIIJIIIIIJJJIIJJJJJJJJJIJIJI
	{
		None = 0,
		Int = 1,
		Float = 2,
		Bool = 3,
		String = 4,
		Vector2 = 5,
		Vector3 = 6,
		Color = 7
	}

	public class IIIIIJIIJJJIIIIIIJJIJJJIJIJJIIIJIJIJJIJJJJIIJJI
	{
		public JIJJJIJIIJIJJIJIJIIIIIJIIIIIJJJIIJJJJJJJJJIJIJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI;

		public MethodInfo JJIJIJJJIIIIIJIJJJIIJJIJIIIJIJIIJIJIIJJJJJIJJJJ;
	}

	private KeyCode IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ;

	private GUIStyle JIJIIJIJIJJIJJIIJJJIIIIJJJJIJJIIJIJIIIJIIIJJJII;

	private GUIStyle JIIJJIIJJJIJIJJIJJIIJIIJJJIIIIJIIIIJJJIIIJIJJJJ;

	private GUIStyle IJJIIIJJJJJIIIJIIIJJJJJJIIIIJIIIIJJJIIJJIIJIIII;

	private GUIStyle JIJJJIIJIIIJJIJJJIIJIJIIIJIJJIJJJIJIJJIJJJIIJJJ;

	private Texture2D JJJJJIJJJJIJIJIIJJJIIJIJIIJJIJIIIJIIIIIIJIIJIJJ;

	private Texture2D IIIJJIJIIJIJIJIIIJIIJJJJJJJIJIJJJJIIJIJIJJJJJJJ;

	private Vector2 JJIJJJIIIJJIIJIJJJIIJIIJIIIIJJJJJIJIJJJJJJIJJJJ;

	private static Dictionary<string, IIIIIJIIJJJIIIIIIJJIJJJIJIJJIIIJIJIJJIJJJJIIJJI> IIIJJJIIIJJIIIIJIIJJIIJIIIJIJJJIJIIIIJIJIJJJIIJ;

	private List<string> JJIJIJIJIIIIIJJJJJIJIJIJJIIJIIJJIJIIJIIJIJJIIIJ;

	private int IJIIJIJJJJIIJJIIJIJIJJIJIIIJJJJIIJJJJIJIJJIIIJJ;

	private List<string> IJIIIJIJJIIIJIJJJIIIIIIJIJIJJIJJJIIIIIJIIIJJIIJ;

	private string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI;

	private bool JJJJIJJIJJJJJIJJIIJIIJIJJIIJIJJJIIJJJJIJJJIIIJI;

	private Rect[] JJIJIJIIJIIIIJIJIJJJJIJIIIIJIJIJIIIIIJIJJIIIJJJ;

	private Rect IJIJJIIJJIJJJIJIIJJIJJJIJIIIJIJJJJIIIJJJJJIJJJJ;

	private static GameConsole JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static string JIIIIIJJIJJJIJJIIJIJIJJJIIJIIIJIJJIIJIIJIIJIIJJ;

	public static bool JJIJJIJIIJJIIIJIJIJJIIIJIJIIIJJIIJJJJJIIJIIJIII
	{
		set
		{
			JJJIIJIJJJIJJJIIIIIIJJIJJJIIJIIJIJIJIJJJIJIIIJI(value);
		}
	}

	public static void IJIJJIIIJJIJJJJJIIIIIJJJIIIJJJJIJJIIJJIIJIJIJIJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static T IIJJJIIIIJIJJJJIIJIJJJJJJIJJIIIIIIJJIIJJJIJJJJI<T>(string IIIIJJIJIJIJIIJIIJIJJIIIJJJIJJIIIIJJJJJIJIJIIII, T IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return default;
	}

	private void Start()
	{
	}

	private void JIJJIIJJIJJJIJIIIJIIIJIIJIIIIIIIJJIJIJIIIJIJIJI()
	{
	}

	private Texture2D IJJIIIIJJIJIJJIJJIJIJIIIIIJIIIIJIJIIIIIIIIIIJII(Color IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ)
	{
		return null;
	}

	private void JIIIIIJIJJIIIIIIIJJIIJJJJIIJJJJJJIIJIJJJJIIIIJJ()
	{
	}

	public static void JJIJIIIIIJJIJJJIJIJIIIJJJJIJIJJJJJIIIIJJIJJIIJJ(string IIIIJJIJIJIJIIJIIJIJJIIIJJJIJJIIIIJJJJJIJIJIIII, int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JJJIIJIJJJIJJJIIIIIIJJIJJJIIJIIJIJIJIJJJIJIIIJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JJIJIIIIIJJIJJJIJIJIIIJJJJIJIJJJJJIIIIJJIJJIIJJ(string IIIIJJIJIJIJIIJIIJIJJIIIJJJIJJIIIIJJJJJIJIJIIII, Color32 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JIJJIJIJIJIIIIJIIIJIJIJIIIIJJJJIJIIJJIJJIJIJIII(bool JJIIJJJJJIIJIIIJJIJIIJIJJIIIIIIIJIJJIIIJJJJJIJI)
	{
	}

	private void IIJJJIIJIJJIJIJJJIJIJIIJIJIIJJJIIJIIJIJIIIIJIJJ()
	{
	}

	private string IJIJJJJIJIIIIJIIIJIIJIJJIJIIIIIJJJJJIJJJIIJIJJI(JIJJJIJIIJIJJIJIJIIIIIJIIIIIJJJIIJJJJJJJJJIJIJI IJIJJIIIJIJIIIJIJIIJIJJIJIIIJJIJJIIIIIIJIIJJJII)
	{
		return null;
	}

	public static void JJIJIIIIIJJIJJJIJIJIIIJJJJIJIJJJJJIIIIJJIJJIIJJ(string IIIIJJIJIJIJIIJIIJIJJIIIJJJIJJIIIIJJJJJIJIJIIII, float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private bool JJIJJIIJIIJIJJIJIIIIIJJIJIJJIJJIJIJJJIIJJIJIJIJ(string JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ, string IIIJJIJIJJJJJIIIIJIJJIJIIIJJJJJJIJIJIIJJJJIIIJJ)
	{
		return false;
	}
	public static void JJIJIIIJJIJIIIIJJJJJIIIIJIIIIJJIJJJIJIIJIJJIIJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void IIIIJJIJIJJIJJIJJIJIIIJJIJJIJIJJIJIIJJIJJIJJJIJ()
	{
	}

	private void IJIJJJIJIIJJJJIJIJJJJJJJJJJJIJIJJIIJIJJIIJJJJJI()
	{
	}

	public static void JJIJIIIIIJJIJJJIJIJIIIJJJJIJIJJJJJIIIIJJIJJIIJJ(string IIIIJJIJIJIJIIJIIJIJJIIIJJJIJJIIIIJJJJJIJIJIIII, bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private static JIJJJIJIIJIJJIJIJIIIIIJIIIIIJJJIIJJJJJJJJJIJIJI JJIJIJIIIIIJIIJJJJIJJIIJJJJIJIIIJJIJJIIIJIIJJII(Type JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return JIJJJIJIIJIJJIJIJIIIIIJIIIIIJJJIIJJJJJJJJJIJIJI.None;
	}

	private Rect IIJJIIIIJJJJIIIIIJIIJIIIIJIJJJIJJIIJJJJIJIIJIII(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
		return default;
	}

	public static T IIJJJIIIIJIJJJJIIJIJJJJJJIJJIIIIIIJJIIJJJIJJJJI<T>(string IIIIJJIJIJIJIIJIIJIJJIIIJJJIJJIIIIJJJJJIJIJIIII)
	{
		return default;
	}

	public static void JIJJIJIIJIIIIJJJJIIIIJJIJIJJJIJJIIJIJIIJJJJIJII(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private bool JIIIIIIJJIIIIIJIJJIJIJIIIJIJIIIJIJJJIIIIIJJJIII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, out object JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, JIJJJIJIIJIJJIJIJIIIIIJIIIIIJJJIIJJJJJJJJJIJIJI IJIJJIIIJIJIIIJIJIIJIJJIJIIIJJIJJIIIIIIJIIJJJII)
	{
		JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ = null;
		return false;
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private bool IIJJIJIJJJJJIIIIIIJJIJJIIIJJJJJJIIIJJIJIIIJIJIJ(string JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ, string IIIJJIJIJJJJJIIIIJIJJIJIIIJJJJJJIJIJIIJJJJIIIJJ)
	{
		return false;
	}

	public static void IIIJJJIJIJIJIIJJIIIIJIJIIJIJJIIJIIIJJJJIJIIIIJJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private string IIJIIIIIIIIIIIJIIJIIIIJJJIIIIIIJIIJJIIJJIIIJIII(JIJJJIJIIJIJJIJIJIIIIIJIIIIIJJJIIJJJJJJJJJIJIJI IJIJJIIIJIJIIIJIJIIJIJJIJIIIJJIJJIIIIIIJIIJJJII)
	{
		return null;
	}
	public static void JIJIJJIJIIIJIJJIJJJJJIJIJIJJIIIJIJIIIIIJIIIJIII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private string IJJJIIIJIIJIJIJJIIIJIIIIJJJJJIJIIJIIIJJJJIJIIIJ(JIJJJIJIIJIJJIJIJIIIIIJIIIIIJJJIIJJJJJJJJJIJIJI IJIJJIIIJIJIIIJIJIIJIJJIJIIIJJIJJIIIIIIJIIJJJII)
	{
		return null;
	}

	private bool JIIJJJJJJIJJIIJJIJJJIJJJIIJJJJIIIIJIIJIJJJIIIJJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, out object JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, JIJJJIJIIJIJJIJIJIIIIIJIIIIIJJJIIJJJJJJJJJIJIJI IJIJJIIIJIJIIIJIJIIJIJJIJIIIJJIJJIIIIIIJIIJJJII)
	{
		JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ = null;
		return false;
	}

	private bool IIJIJIIJJIJIIJIJJJJJIIIJJIIJIJJIIIIIIIJIJIIJJIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, out object JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, JIJJJIJIIJIJJIJIJIIIIIJIIIIIJJJIIJJJJJJJJJIJIJI IJIJJIIIJIJIIIJIJIIJIJJIJIIIJJIJJIIIIIIJIIJJJII)
	{
		JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ = null;
		return false;
	}

	private static JIJJJIJIIJIJJIJIJIIIIIJIIIIIJJJIIJJJJJJJJJIJIJI IIIIJIJJIJIJJJJJJJIIJJIJIIIIJIJJIIJJJIIJIIIIIJI(Type JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return JIJJJIJIIJIJJIJIJIIIIIJIIIIIJJJIIJJJJJJJJJIJIJI.None;
	}

	private bool IIJIJIIJJJJJJIIJIIJJJIJJJJJJIJIJJJIJIJJIIJIIIII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, out object JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, JIJJJIJIIJIJJIJIJIIIIIJIIIIIJJJIIJJJJJJJJJIJIJI IJIJJIIIJIJIIIJIJIIJIJJIJIIIJJIJJIIIIIIJIIJJJII)
	{
		JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ = null;
		return false;
	}

	public static void JIJIIIIJJJJJJJIIIJJIIJJIIJIJJIIJJJJJIIJJJJIIJII(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void Awake()
	{
	}

	private void IIIIJIJJJJJJIIJIJJJIIJJJJIJIJIIJIIJJJJJJIIIIIJI()
	{
	}

	public static void JIJIJIJIIJJIIJJIJJIJIIJIIIIIJJJJJIIJIIIJIIIJJJJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void IJIJIIJIIJIJJIJJJIJIIIJJIIJJIJJJIIJJIJJIJJIIJIJ()
	{
	}

	private void OnGUI()
	{
	}

	private void Update()
	{
	}

	private Rect IIJJIIIIJJJJIIIIIJIIJIIIIJIJJJIJJIIJJJJIJIIJIII(Rect IJJIIJIJJJJJJJJJIIJIIJJJIIJIIJIJJIIIJJIIIJJJIJI)
	{
		return default;
	}
	public static void IIIIJJJIIJIIJIJIIJIIJIIIJIIJJJJJJIJJJJIIIJIJJJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static void IJIJIIIJIIJJJJIJJIIJIJIIJIJJJIJIIJJJIJIJIJJJJIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
}
