using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class GDPR : MonoBehaviour
{
	public GameObject JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ;

	public GameObject JJIIIJIJJIJJJIJJJJJJIIJIIJIJJJIJIJJJJIJIJIIIIIJ;

	private void IJJJJIIIIJJIIIJJIJJJJJJIJIIJJJJJJJJIJJIIJIIIJIJ()
	{
	}

	private void JJJIIIIJIIJJIJJJJIIJJJJJIIIJJIIJIJIJIIIIJJIIIJI()
	{
	}

	public void JIIJJJIIIJIIIJJIJIJJJIIIJJJIJIIJIJIIJIIIIJIJJJJ()
	{
	}

	public void JIJJIIJJJJIJJJIJIJJIJIIJIJJIIIIJIJJJJJIJJIIJJII(bool isTraining)
	{
	}

	public void OnAccept()
	{
	}

	private void JIJIJJIJJJIJJJIJJIJIIIJJJJJIJIJIJJIIJIJIJJIIJJJ()
	{
	}

	private void OnJoinedRoom()
	{
	}

	public void JJJIJIJJJIJJIJIJIJIJIIIJIJJIIIIJJIJIIJJJIJIIIJI()
	{
	}

	private void JJIJIIJJJJIIIJIJJIJJIJIJJIJIIIIJIIJJJIIJIIIIJII()
	{
	}

	private void OnDisable()
	{
	}

	public void IJIIIJIIJJJIIJJIJIIJIJIJIJJIIJJJIIIIIJIJJIIIJJI()
	{
	}

	private void JJJJIIIJIIJJJIJIIJIJIJJJIIJJJIJJIIIJJIIIIJIIJIJ()
	{
	}

	private void IIIJJJJIIIIJIJIJIIIIIIJIJIIJIJIIJIIJJJIJIIIIJJJ()
	{
	}

	public void OnClickTraining(bool isTraining)
	{
	}

	public void OnPrivacyPolicy()
	{
	}

	private void OnEnable()
	{
	}

	public void IIIIJIIJJIIIIIJJJIIJJJIJIJIIJIIIIJIIIJIJIJJIIII()
	{
	}

	public void JIIIIIIJJJJIJIIIIIIJJIJIIJJJJJIJIIJJIJJJJJIJJJI()
	{
	}

	private void Start()
	{
	}

	public void JIIIJIJJJJJIJIJJIIJIIJJJIJJIIJJJJJIIIIIJJJJIJJI()
	{
	}

	private void JIIIJJJIIIIIIJJIJIJIIJIJIIJIJIJIIJJJIJIIJIJJJIJ()
	{
	}
}
