using UnityEngine;

public class GlassObject : MonoBehaviour
{
	public GameObject IIJIIJJJJJIIIJIJJJJJIIJIIIJJIIIJIIJJIJJJIIIJJII;

	public GameObject IJJJIJJIJJJIIIIIIIIJIIJIJJJIIIIJIIJJIIIIIIJIJIJ;

	public Transform[] JIIJIJJJIIJJIJJJIIJJIJJIJIIIIIIJIIJJJIJIIJJJJIJ;

	private float[] JJJIJIJIJIJJIJIIJIJIIJJIIIJJJJIIJJJIIJIIIIIJJII;

	public Vector2 IJIJIJJIJJIIIJIIIJIIJIJIIJJIJIIIJIIJIIIJJJJIIIJ;

	private float JJJIIJJJJIJIJIJJIJJIIIJJIJIJIJJJIJJIJIJIJJIIIII;

	private bool JIJIJIIJJIJIJJJIJIIJIIIIJIIIJJIIIJJJJJJJJJIIIJI;

	public void IIJIJJIJJJJJJJJIIIIJJJJJJIIJJJJJJJJIJJIJJJJIIJJ()
	{
	}

	public void IIJJJIIIIIJIJJJIJIIJJJIIIIIIIJJJIJJIIIIJIJIIIJJ()
	{
	}

	private void JJIJJJIIJIJIJIJIJJJJJIIJIJIIIIJJIIIJIIJJJJJIJIJ()
	{
	}

	public void IIIIIJIJJIIJIIJJJJIJIJIJIJJJJJIIJIIJIJJJJJIIIII()
	{
	}

	public void JJIIIIIJJJIJIJJJJJIIIJJIJJJIIIIJIJJJJIIIJIIJJII()
	{
	}

	public void JIJIJIIJJJIJIIIJIIIJIIJIIJJJJJIIJIIIIIJJIJJIJJJ()
	{
	}

	private void JIJJJIIIIIJIJJIIJIJIIIIJIJIIJIIIIJJJIIJJJIJJJIJ()
	{
	}

	public void IJIJIIJIIJIJIJJIIIIIJJJIJIIIIJIJJIJJJJIJIJIJIII()
	{
	}

	public void IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI()
	{
	}

	private void IJIJJJJJIIJIIJIJIIIJJJIIIJIJIJIJJIJIJJJJJIJJJJJ()
	{
	}

	public void JJJJJIJJIJJIJJJJJJJJJIIJIJIIIJJIJJJIJJIJIJIIIJI()
	{
	}

	private void JIIIJIIJJJJIJIJJJIIIIIJIJJIIIIJJJJJJJJIJIIIIJJI()
	{
	}

	private void JIJJJJIIIJIIIIJIJJJJIIJJJIIJJIIJJJIIIIIIIJIIIJI()
	{
	}

	public void IIIIJIJJIIJJIIJIJIJJJJIJJIIIIIJJIJJIIIIJIJIIIJI()
	{
	}

	private void JIIIJIIIJJJIIIIIJIIIIJJIIJIIJIJIIJJJJIIIJIIJJJI()
	{
	}

	public void JIIJJJJJIJJJJJJJJJIJIJJIIIIJJIJJIJIJIJJIJJJIJII()
	{
	}

	public void JJJIJIIIIIJJJIJJIIJIIIJIIJJJJJIIIIIIIIJIIIIJIIJ()
	{
	}

	public void IIIIIIIIIIIIIJJJIIIIJIJJIJIIIJIIJIJJIIJIJJJIIJJ()
	{
	}

	public void IIIJJJJJIJIIIJIJJJIIIJJJIIJJIIJIJJIIIJIIIJJIJJI()
	{
	}

	private void JIJJIJJIIJJIJJIJIJJIIJIJJJJJIIJIIIJJIIIJJIJIJII()
	{
	}

	private void Update()
	{
	}

	private void JJJIIIIIIIJJJIIJIIIIJJJJIIIIIIIIJJJJJJJIIIJIIJJ()
	{
	}
}
