using System.Collections.Generic;
using Photon;
using UnityEngine;

public class GrenadeObject : Photon.MonoBehaviour, JIIIJJJIJIJJIJIJJIJJIJJJJJJJJIJIIIJJIIJJJJIJJJI
{
	public static List<GrenadeObject> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ;

	public float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

	public float JIIJJJIIIJJIIIIJIJJJIIIJJIIIJJIIJIJJJJJJIJJJJJI;

	public float IJJIIIJJIJIJIIJJIJJIIIJJIIJIIJJIIIIJIJJIJIIJJJI;

	public ParticleSystem JIJIIIIIIJIIIIIJJJJIIIIIJJIIJJJJJIIIJIIJJJJJIJJ;

	public Transform IIIJJJJIIJIJJJJIJJJIIJIJIIIJIIJJJIJIJIJJJIJJJJI;

	public GameObject JIIIJIJJJIJJIJIJIIIJJJJIIJIJJJIIIJJIIIJIJIIJIII;

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ;

	public Rigidbody IIJJIJIIIJJJJIJIJIIJJJIIJIIJIIJIJJJIIIIIIIJIJJI;

	public GameObject IJIIIJIIJJIIJIJIIIJIJJIJJJIIIIIJJIIIIIIJJIIIIII;

	public TrailRenderer JIIIJJJIIJIIIIIJIJIIJJJJIIIIIIJJIIJJJJJJJJIIJIJ;

	private bool IIIJIIIJJIIJIJJIJJJJJIIJJJIIIJIIJIJJIJIJIIJIJJJ;

	private Vector3 IIJJIJJIJIJJIIIJIJIIJIIIIJJIJJIJJJIJJJJIJIIIIII;

	private Quaternion IJJIIIIIIJIJJIIIIJJJJIIIJJIJIJJJIIJJJIJJJJIJJJJ;

	private bool JJIIJIJIJJJJJIIJJJIIJJJIJIJJIIJJJJIJIIIIIIIIIJI;

	private bool JIJIJIIJJIJIJJJIJIIJIIIIJIIIJJIIIJJJJJJJJJIIIJI;

	private int IJIJJJIJIJJIJJJIIJJJJJJIJIJJJIJJJJIJJIJIJJJIJJI;

	private void JJIJJIJJIIIJIIIJJJIIIJIIIJJIJIIJJIJIJJJJIJIJJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void OnPhotonSerializeView(JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ IJJJJIIJIIIIJJJIJIJJIIJIIIJIJIIIIIIJIIIIJIJIIJI)
	{
	}

	private void IJJIJJJJJIJIIIJJJIJIJIIIIJJIJIIJIIJIJJIIIJJIJIJ()
	{
	}

	private void JJJJIJIJIIJJJJIIIIJJJIIIIJJIIIJJIJJIIJIIIIIIJIJ()
	{
	}

	private void JJJIIJJJJJJJJIIIIJJIJIIIJIJJIJIIIJIIJJJIJIIJJII()
	{
	}

	private void JIJJIJJIJJJJIJIJIJJIJIIIIJJJIIJJJIIIIJJJIJJJJII()
	{
	}

	private void OnEnable()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIJIJJJJJIJJIJIJJJIJJJIIJJIIIJJIIJJJJJJIIIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void IIJJIIJJJJIIIIJJJIJIJIJJJJIJIIJJJJJJJIJIJJJJIJJ(JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ IJJJJIIJIIIIJJJIJIJJIIJIIIJIJIIIIIIJIIIIJIJIIJI)
	{
	}

	private void JJJIIJIJJJIJIIJJJIJIIIJIJIJIIJIIIIIJIJIIIJIJIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIIJIIIJJIJJJJJJJJJJJIJIJJIIJJJJIJIIJIJJJJJJIII()
	{
	}

	public void IIIJIJJIIIJJIIIIIIJIJIIJIIJJIIIJJJIIJIJJJIJIIII(JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ IJJJJIIJIIIIJJJIJIJJIIJIIIJIJIIIIIIJIIIIJIJIIJI)
	{
	}

	private void Update()
	{
	}

	private void IIIJIJJIJJIJIJIJIJIIIIJIIJJIIIJJJIJJJJIIJIIJIIJ()
	{
	}

	private void IJIJJJJJIJJJJJIJIIIIJIIJIIJJIJJJJIIJJJJJJIJJJIJ()
	{
	}

	private void IIIJJIJJJJJJJJIIJJIJJJIJJIIIIJIIIJJIIIIIIJJJJJJ()
	{
	}

	private void OnDisable()
	{
	}

	private void Awake()
	{
	}

	public void IIJIIIIIJIJIIIJIJIIJIIIIJJIIJJIJJIJJIJIJIJJIIIJ(JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ IJJJJIIJIIIIJJJIJIJJIIJIIIJIJIIIIIIJIIIIJIJIIJI)
	{
	}

	private void JJJIJJJJJIIJIJJJIJIIIIJJIJJJIJIIJJIIJIIJJJJIIJI()
	{
	}

	private void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}
}
