using System.Runtime.CompilerServices;
using Photon;

public class HotKnifeMode : MonoBehaviour
{
	private sealed class JJJIJIIIIIJJIIIIIJIJJJJIIIIJJIIJJJIJJIJIIJJIJII
	{
		public PlayerInput IJIIJJJJIJIJJJJIJIJJJJIJIIIIJIIIJIJJIJJIJJIIIIJ;

		internal void IIJIIJIIIIIJIIJJJIJJJIIJJIJIIIIJJIIIJJJJJJJIJJI()
		{
		}

		internal void IIIIJJIJIIJIIIJIJIJJJIJIIIIIIJIJJIJIJJJJIIJJIJJ()
		{
		}

		internal void IIIJJIJIJJJJIJIJJJJJIIIIIJJIJJJJIJIIIJIIJJIIIIJ()
		{
		}

		internal void JJJJIIJJJIIJJJIIIJIIIJIJIJIIIIJIJJIIJIIJJIIIIJI()
		{
		}

		internal void IIJIJJIJIJJJJIJJIIJJJIJJIIIIJIIIJIIIJJJIIJJJJJJ()
		{
		}

		internal void JIJIJJJIJIIJIJJJIJJIIIIIIIJIJJIIJIJIIIIJIJJIJJI()
		{
		}

		internal void JJIJIIJJIIJIJIJJJJJJIIJJIIJIJIIJIIIIIIIIJIJJJII()
		{
		}

		internal void IJJJIJIIIJIJJIIIJJIJJJIIIJJIJJIIIIJIJJIIIIJJIII()
		{
		}

		internal void JJJJJIIJIIIIIIJJIJJJJJIIIJJIIIJJIJJJJIIJJJJIIII()
		{
		}

		internal void IIJJIJJIIIIJJIIIIIIJIIJJJIJJJIIIJJJIIJIIIIIJJJJ()
		{
		}

		internal void IJJJIIJJIJIIJJJJIJIIIJIIJIJJJIIIJIIIIJJIJIIJIJI()
		{
		}

		internal void JJJJIIJJJJIJIIIIJIJIJIIIIJJIJIIJIJJIIJJIJIJIJJI()
		{
		}

		internal void IIIJIJIIJIIIIIIIIIJIIIJIIIIJJJJJIIJIIJJJJJIJIIJ()
		{
		}

		internal void IIJIJIJIIIIJIJJIIIIIJIJIIJIJJJIJIIIJIIJJJIJIJJI()
		{
		}

		internal void IJJJIJIIIIIJJIJIIIIIIJIJIJJJJIJIIJIIIJJJJIIIJJI()
		{
		}

		internal void JIJIIIIJIIJJIJIIJJIIJIJIJJJJIJJIIJIJJJJIJJIJIII()
		{
		}

		internal void JIJIIJIJIJJJIJIIIJIJJIJJJIIIIIIIJJJIJIJIJIJJIII()
		{
		}

		internal void IJJJJJIJJIJIJJIJJIIIIJJIIJJIJJIJJIIIIJJJIIJIIJJ()
		{
		}

		internal void IIJIJJJJIIJJJJJJJIIIJIJJJJJIIIIIJJIIIIIIIIJJIIJ()
		{
		}

		internal void JJIIJIJIIJIJIIIJIIJJIJIIIIIIIJJJJJIJJIIIJIJJIIJ()
		{
		}

		internal void IJIIJJIIIIJIJJIJJIJJIIJJIIJJJJJJIIJIJIJJJIJIIII()
		{
		}
	}

	private int JIIJJJIJJIIIIJJIIJJIJJJJIIJJIIIJIJJIJJJJIJJJIJJ;

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIJJJJIJIJJJIIIJJIJIIIIIIJIJIJIJJIJIIIJIIIJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJIIIJIIJJIJIIIIIJJIJIIIJJIIIIJIJJIJIIIIJIJIJII(bool JJIIJJIIIJJJJIJJIIIJIIIIIJJIJIIIIIIIJIJJJIJIIII)
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void JJIJIIJJIJJJJJIIIIIIIIJIIIJIJJJJIIIJIIIIIIIIJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII(bool JJIIJJIIIJJJJIJJIIIJIIIIIJJIJIIIIIIIJIJJJIJIIII)
	{
	}

	private void JJIIJJJJIJIJJJIIIJJIJIIIIIIJIJIJIJJIJIIIJIIIJJJ(int JIIIIIJIIIJIIJIJIIIIJJJIJJIJJJIJJIJIJJJJIIIJJIJ)
	{
	}

	[CompilerGenerated]
	private void JJJIJIJIJIJJIIJIIJIJJJJIJIIJJJJIJIIJIIJJJJJIIIJ()
	{
	}

	private void JJJJIJIJJIJIIJIJIJIIIJIIJJIIJIIJIIIJJJJJJIIIIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void IIIIJJIJIIIJJJJJJJJIIJIJIJIJIIIJIIJIJJIIJJJJIJI()
	{
	}

	private void IIJIJIJIJJIJIIJJJJIIJJIIIIJJJJJIIJIIJJJIJIIJJIJ()
	{
	}

	private void IJIJIJJIJJJIIJJIJJJJJIIJJIJIIIIJIIJIIJIJJJJJJJI()
	{
	}

	[CompilerGenerated]
	private void IJJJJIIIJJIIJJJIIJJJJJIIIIJIIIIIIIIJJIIJJIJJJIJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJIIJIJJIIJJIIJIJIJIIJJJIJJJJJIIJJIJJIJIIIJJIJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void OnDisable()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIJIJJIIJIJJJIIIJIIIIJJJJIIJJIIJJJIIJJIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnEnable()
	{
	}

	private void JJJJJIJIJIJJJIJIIIIIJJJJIIIJJIIIJIJIJIIJJIIJJIJ()
	{
	}

	private void IJJJJIIIIJIIIIIJJIIJIIIJIJJJJJJJJJIIJIIIIIIJIJJ()
	{
	}

	private void JJIJIJIJJJJJIIJJIIIJJIJIIIJJIIJJJIIIIJIJJIIIIJI()
	{
	}

	private void JIJIJJIJIJIIJIJIJIIJIIIIJIJIJJIJJJJIJJJJIIJJIJI(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	[CompilerGenerated]
	private void IIIJJJJIIIIIJIJJIJJIIIJJIIJJJIIJIIIJJIIIIIIJIII()
	{
	}

	[CompilerGenerated]
	private void IIIIJIIJIJJIIJJIJJJJJJJJIIJIJJIJJIIIJJIIIIJIIII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJIJIJJJIIJJJJIIIIIJIJJJIIJJJJJIJJJIIJJIIIJJJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void JIIIIJIJIJIIJIIIIJIJJIIIIIIIIJJJJIIJIJJJJIIJIII()
	{
	}

	private void JIIJIJJIIIJJIJIIJJIJIIIJIJJIJIIIIIJIJJJIIJIJIIJ()
	{
	}

	private void IIJJIJIJIJIJIIIJIIJIJIJIIIJJJIIJIJJJJJJIJJJIIJJ()
	{
	}

	private void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII()
	{
	}

	private void Start()
	{
	}

	private void Awake()
	{
	}
}
