using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Photon;

public class HungerGames : MonoBehaviour
{
	private sealed class JIIJJIIIIJIIJJIJIIIJJIIIIIIIJJJIIJJIIJJJIIJJJIJ
	{
		public HungerGames JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII;

		internal void JIJIIIIIJIJIJJIIJIIJIJIIJJIIJJJJJIJIIJJIIIIJIIJ()
		{
		}

		internal void IJJJJIIIIIIIIJJJIIIJJJJJIJJIIJIJIIJIIIIJIJIIJIJ()
		{
		}

		internal void IJIJJIJJIJJIJIJJJJIIIIIJJJIJJIJJIJIIIJIIIIJIIII()
		{
		}

		internal void IIJIJIIIIIIJIIJIJJIJIIIJIJIIJIIIIIIJIIJIIIIIIJJ()
		{
		}

		internal void JIJIJJJJJJIJJIIIIIIJJIIJJIJIIIIJJJJIJJJJJIJJJIJ()
		{
		}

		internal void IJIJJIIJIJIIIJIIIJIIIJIJIIIJJJIJIIIJIJIIIJJJJIJ()
		{
		}

		internal void JJJJJJJJIJIJIIIJIJIJJIIJIJJJIIIJIJJJIJJIJJJIJII()
		{
		}

		internal void IIJJJJIJIJIJIJJJJIJJIIJJJJJJIJJIIIIIJIIIIIJJIII()
		{
		}

		internal void JIIIIJIIJIJJJIIJIIJIJIIJIIIIIJIIJIJIJJIIIJIIIII()
		{
		}

		internal void IJIIIIJIJIIJIIJJJJIIIJJJIIJIIIJIIJJIIJIJIIIIIJJ()
		{
		}

		internal void JIJIJIIIJJIIJIIJJIIJJJIJIJIJIIIIJIIJIIJJJIIJIIJ()
		{
		}
	}

	private sealed class IIIIIIJIIJJJIJIIIJJJJIJIJJIJIJJIJIIIIIJIJJIJJJJ
	{
		public HungerGames JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public byte[] JIJJJIJJJJJIIJJJJJIIJJJIJIIIJJJIIIJIIJIIJIJIJIJ;

		internal void JJIJJIIIJJJIIIIIIIJIJIIIIJIIIJIJIIIIJJIIIJIJJJJ()
		{
		}

		internal void JJIJIJIIIIJIJIIIIJIIIJJIIJJIJIIIJIJIIJIJIJJJIJJ()
		{
		}

		internal void IIIJIIJJIIJIJJIJJIJJIJIJJIIJIIJIIIIIIJJJJJIJJJI()
		{
		}

		internal void IJJIIJJIJIIJJJJJJJJIIJJJIJJJJIIIJJIIJJIJJJJIJJI()
		{
		}

		internal void IJIIIJJIJIIIIIJJIJJIJJJIIIJIIJIJIIJIIIJJIIIJJIJ()
		{
		}

		internal void JIIJJJJIIJIIJJJIIIIIJIJIIJIIIIJJJJIIJJJJIIJJIIJ()
		{
		}

		internal void IIIJIIJIIJIIIIJIIIJIIJIJJJJJJIJJJJJIJIIJJIJIIJJ()
		{
		}

		internal void IIJJIIJJIJIIJIIIJIJIJJJJJJIJJIJJJJJJIJIIIIJIIII()
		{
		}

		internal void IJIIJJIJIIIJJJJIJIIJIIIIJJIJIIIJJJJIJIIJJIJIJIJ()
		{
		}

		internal void IJIJIIIIIIJIJJJIIIIJJIIJIIIIJJJIJIIIJIIIIJIIIII()
		{
		}

		internal void IJIJJIJIIIJJJIIIJIJIIIIJIJIIIJIJIIJJJJJJIIIJIIJ()
		{
		}

		internal void JIIJIIIIIJJJIJJIIJJIJJJJIIIJIJIJJIIIIJJIIIJIIJI()
		{
		}

		internal void IIIJJJJIJIJIJIIIIIJIIJJIJJIIIIJIIIJJIIJIJIIJIJI()
		{
		}
	}

	private List<byte> JJIIJIJJJIIIIJIJJJIJIIJJIIIIIJIIIIIIIJJIIJIJJJJ;

	private static HungerGames JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void IIIIIJIIJJJIJJJJJJJIJJIIIIIJJIJIJIIIJIIIJIIJIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIJJIJIIJIJJIJIIIJJJIIIIIJIIIIJJIIIJJIJIIIIJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void JJIJIJJJIIIJIJJIIIJJIIJIJJIJJJIJJIJJJIIJIJIJJJJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJIIIIIJIJIJIJJJIIIJJJIJJIIJIJJIJJJIIIIJJJIIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIIIJIIIJJJJJJIJIIIIJJJJIIJIIIJJIJIJIIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJIJIIIIIIJJJJIIIJIJIIIJIIJIIJIIJIJIIIJIJIJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIIJJJJJJIJJIJIJJJIIJIIJJJIJJJJJJIJJJJIJIIIJJIJ()
	{
	}

	private void IIJIIJJIJIJIIIJJIIJIIJJJIJIIIIJIJJIIJJJJJJIIIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJIJIJIIJJIJIIIIIIJJIIJIJIIJIIJJJIJIJJIJIJJIJJ()
	{
	}

	private void JIIJIJJJJIJIJJJIIJJJIJIJIJJJIJIIIJJIJJJIJJJIIJI()
	{
	}

	private void IIIIJJIJJJJJJJIJIIJJJJIIJIIJIIIIIJJJJJIIIIJIJII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void IIJJIIIIJIIJJJJJIJIIIJJIJJJJIIIIIIIIIJIJIIIIIII()
	{
	}

	private void OnDisable()
	{
	}

	private void JJJIJJJIIIIIJJIJIIJIJJJIIIIIJJJIJIJIIJIIIIJIIJI()
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	public static void IJJIIJIIJJIJIJJIJIIJIJIJIJIJJJJJJIIIIIIIJIIIJII(byte[] JIJJIJJJIIJJIIJIIIIIJIJJJJIJJJIIIJIJIIJJIJIIIII)
	{
	}

	private void Start()
	{
	}

	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII()
	{
	}

	private void IJJIJIJIJIJIJJIIIIJJIJIIIIIIIIIIIJJIJIIIJIIJIII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void IIJIIJJJIJJJIIIIJIIIIIJIIIJJJJIJJIJJIJJJIIIIJIJ()
	{
	}

	private void IJJJJIIIIJIIIIIJJIIJIIIJIJJJJJJJJJIIJIIIIIIJIJJ()
	{
	}

	private void JJIJIJIJJJJJIIJJIIIJJIJIIIJJIIJJJIIIIJIJJIIIIJI()
	{
	}

	public static void JJJIIIJJJIIJIJJJJIJJIIJIIIIJJIIJJIIIIJJJJJJIIIJ(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
	}

	private void JJIJJJIIJIIJIIJJJJJIIIIIJIIJIIIJIIJIJIJJIJJIJIJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJJIIIJIJJIJIIJJIIJIJJJIIJIIJJJIIJJJIIJIIJIIJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJIJIIJIJIJIJIJIIIJJIIIJJJIJIIJJIJIJJJIJJIIIJII()
	{
	}

	[CompilerGenerated]
	private void IIJIJJIJIJIIIIIJJJIJIIIIJJJJJIJIJIIIJJJJJJIJJIJ()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void Awake()
	{
	}

	private void JIIIJJIJIJJIJJJIIIIJJJIJIJIJIIIJJJJIJJIIIIJJIII()
	{
	}

	private void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJIJIJIJIIJJIIJJIJJIIIJJJJIIIIIIJIJJIJJJIJJJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJIJJJIIJIJIIIIJIJJIJIJJJJIJIIIJIJIJJJIIIIIJIJJ()
	{
	}

	private void OnEnable()
	{
	}

	private void IJIJIJJIJJJIIJJIJJJJJIIJJIJIIIIJIIJIIJIJJJJJJJI()
	{
	}

	private void JIJIJIIJJJIJJIJJIIIIJIJJJIJJIJIIIJIJJJJJIIJIJJJ()
	{
	}

	public static void IJIIJIJIJJJJIJJIIJJIIIIIIIJJJIJJJIIIJJIIIIJIJJJ(byte[] JIJJIJJJIIJJIIJIIIIIJIJJJJIJJJIIIJIJIIJJIJIIIII)
	{
	}

	private void JIIIIJIJIJIIJIIIIJIJJIIIIIIIIJJJJIIJIJJJJIIJIII()
	{
	}

	public static void JJIJIJJJIIJIIIJJIIIJJJJIJIIIIIJJJJJIIIIJJJJIIJJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	[CompilerGenerated]
	private void JJIIJJJIIIJIJJIIJJJIIJIIIJJJJJIIIJIJIIIJJJIIIII()
	{
	}

	[CompilerGenerated]
	private void JIJJIJIJJIIJIIJJJIJIIJIIJIIJIIJIIJJIJIJJIIIIJJJ()
	{
	}
}
