using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class HungerGamesRandomDisabled : MonoBehaviour
{
	public List<HungerGamesBox> JIIJIIIIIJJJJIIIIJJJJIIJJJIJIJJJJIIJIIJJIIIIIJI;

	public int JIJJJIIJJIIJIJIJJJIIJJIIJJIIIJJJIJJIIIIIJJIJJII;

	private void JJIIIIJJIIJJJJIIJIJIIJJJJJJJIJJJJJIJJJIIIJJIIII()
	{
	}

	private void JJIIJIIIIIIIJIIIIIJIJIIJJJJJJIIIIIJJIJJJJJJJIJJ()
	{
	}

	private void IJIJJIIJJJIIJJIIIJJIIJIIJIJIJJIIJJJIIJIJJJJJJIJ()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void IIJIJIIIIIJJIIIIIJJIJIIIJIJIJIIIJIJJIIIJJJJIIJJ()
	{
	}

	private void IIJJIJIIIIIIJJJIIIIIIJIIIJJJIIIIJIIJIIIJIJJIJIJ()
	{
	}

	private void JIJIIJIJJJIIIJIIIJJIIIIJIIIJIJJIIIIIJJIIIIIJIII()
	{
	}

	private void JIJJIIJJIJJIIJIJJJIJJIIJIJIJJJJJIJJIIIJIJIJJIII()
	{
	}

	private void IJIIIIJJIIJJIIJIJJIIIIIJJIIIJJIJIJJJIIIJJIJIIIJ()
	{
	}

	private void JJJIIIIJJJJIJIIIJIJJIJIJJJJIJJJIJIIJJIIJIIIIIII()
	{
	}

	private void IJJIIIJJIJIJJJIIIJIIIJIJJJIJIJIIIIIIJJIIIIJIJIJ()
	{
	}

	private void JIJJJJJIIIIIJJJIJJIIIJJIJIJIJIIJIJIIJIJIJIJIJJJ()
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void JJJJIJIIJIJIJJJJIIJIIIJJIJJJIIIIJJJIIJIJJIIIJIJ()
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void JIJJJIIJIJIIJIIJIJIIIIIIIJJIJJJIIJJJJJJIIIIIIIJ()
	{
	}

	private void JJIJJJIJJIJIJIIIJJJIJIIJIJIJIJJJIIIIJIIIJJJJIIJ()
	{
	}

	private void IJIJIJJJIIIJIIIJIIIIJIIIIJJJIIJJIIIIIJIIJJIJJJI()
	{
	}

	private void JJIIJIJIJJJIIJIIJJJIIIIJJIJJIJIIJIIIJIIIIJJIJII()
	{
	}

	private void Start()
	{
	}

	private void IJIIJJIJJJIJIJJJIIJIJIIJJJJJIJIJJJJIIJIIJIJJJJI()
	{
	}

	[CompilerGenerated]
	private void IIIJIIJIJIJJJJIIJIJIJJIIJIJIIJJIIJIJJIJJJIIIJJJ()
	{
	}
}
