using System;
using System.Collections.Generic;
using UnityEngine;

public class HungerGamesBox : MonoBehaviour
{
	[Serializable]
	public class JJIJJIJIJJIJJJIJJJIIJJJJIJJIIJJJJIIIIJIJIIIIIJJ
	{
		[JIIJIJJJIJJJJJJIIJIJIIIJIJIIJJJIJIJIIIIIJIIJJJJ]
		public int IJJIJJJIIJJJIIIJIJIJIJJIIIJJJIJIJJIIIIIJIIJIJJJ;
	}

	public int IJJJIIJIJIJJJIIIIJJIIJJIIIIIIIIIJJIJIJIIJIJIIIJ;

	public bool IJJIJJIIIIIIJIJJIIJJJJIJJIIJJJIIJIJIJJJIJJIJJJI;

	public List<JJIJJIJIJJIJJJIJJJIIJJJJIJJIIJJJJIIIIJIJIIIIIJJ> IJJIIJIIJJIIJJJIJJIJIJJIIIIIJIJJIIIJJIIJJJJJIIJ;

	public DropWeaponStatic JJJIJJJIJJIIIIIJJJIIIJIIJIIJJJIJIJJJIIJIJJJIJII;

	private GameObject JIIIJIJJJIJJIJIJIIIJJJJIIJIJJJIIIJJIIIJIJIIJIII;

	public void IJIIIIIIJIIJIJJIJIJJIIIJIJIIIIIJJIJIJIJIJJJJJIJ()
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	private void IJIJJJJJJIIIJJJJJIJIIIJIIJJIJIIJIIJJJJIIJJJIIJI()
	{
	}

	private void IIJIJIJJJIIIJIIJIJIJIIJIIIIJJIIJJJJIIJJIIIIJIII(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, int IJJJJIJIIJJJIJIIJJJJJJIJJIIJIIIIIJJJIIJJJJJJIJI)
	{
	}

	private void JJJJJIIJJJJIIJJJIIIJIJIJIJJJJIIIJJJIIIJIJIIJIIJ()
	{
	}

	private void IIJJJIIJIJIJIIIIJIJIIIIJIJJIJJJJJJJJJJIJJJIJIJI()
	{
	}

	private void IIIIIIJIIIJJJIJIIIJIJJJJJIIIJJJIIIIIIJJIJIIIJII()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void IIJIJIIIIIJJIIIIIJJIJIIIJIJIJIIIJIJJIIIJJJJIIJJ()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void IJJJIIIIJIIIJIJJIIIIIJJJIIJJJJIJIJJJJIJJJIJJIIJ()
	{
	}

	private void IIJJJIIIJIIJJJIIJIIIJIIIIIIIJJIJIIJIJIIIIJJJJII(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, int IJJJJIJIIJJJIJIIJJJJJJIJJIIJIIIIIJJJIIJJJJJJIJI)
	{
	}

	public void JIJIIJJIIIIIIIJIJIJIIIIJIJJIIJIJIIIIIIJJJJIIIJI()
	{
	}

	public void IIJJJIJJIIJJJIIJIIIIIJIIJIJJIIJIIJJJIJJJIIIIIJI()
	{
	}

	private void JIIJIIIJJIIIIIIIIJIJIIJIIIIJJIJIJIJIJJJIJIIIJJI()
	{
	}

	private void JJIJIJIJJIJJJJJIJIIJJIJIJIIIJJJIJJIJIIIJIIJIJJJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, int IJJJJIJIIJJJIJIIJJJJJJIJJIIJIIIIIJJJIIJJJJJJIJI)
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	public void IIIJIJIIIIIIIIIJJJIJIJJIIIJJIJIIIIJIIIIIJJIJIIJ()
	{
	}

	private void IIIJJIIJIIJJIJIJJJJJJIIIJIJIJIJIIJJIIJIIJIJJIIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, int IJJJJIJIIJJJIJIIJJJJJJIJJIIJIIIIIJJJIIJJJJJJIJI)
	{
	}

	public void JJIIJIIIIIIJIIIIJIIIJJJIJIJJIIJJIJJIJJIIJIJIJJJ()
	{
	}

	private void Start()
	{
	}

	private void IIJJJJIJJIIJJJIIJIJJJJIIIJIIIIIJIJJJIIIIJIJIIIJ()
	{
	}
}
