using System.Diagnostics;
using UnityEngine;

public static class IIIIJJJIJJJJIJJIJJJIIIIJJJIJIIJIIJIIJJJIIIIJIJJ
{
	[DebuggerStepThrough]
	[DebuggerHidden]
	public static float IIIIIIIJIIIIIJJIJIJJIJIIJJJJIJIJIJJIIIJJJIJJJIJ(float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI)
	{
		return 0f;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static int JJIJJJIJJJIJIIJIIJIIIJIIJJIJIIIIJJJIIIIIJJJJIJI(int JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ, int IJIIJJIJIJIJIIJJJIJIIIJIJIIJIJJIIIIJIIIJIIIIIJJ)
	{
		return 0;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public static int IIIIJIJIJIIJJIJIJJIJJIJIIJIJIIJIJIJJJJIJIJIIIII(int JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ, int IJIIJJIJIJIJIIJJJIJIIIJIJIIJIJJIIIIJIIIJIIIIIJJ)
	{
		return 0;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static float IJIJIJIJJJJIIJJJIIJJJJIJIIJJIJJIIJJJIJIJJIJIJIJ(float IIJJJIJIJJJIIJIIIJIJJJIJJIIJIJIIJJIIJIJJIJJJJIJ)
	{
		return 0f;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static float JIJJJIIIJIIJJJIJJJIJJJIIIIIJIJJIJJIJJIJIJIIIIII(float JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
		return 0f;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public static int JJJJJJIJJIIIJJIJJIJIJJJJIIIJJJJIJIJJJIIJJIIIJIJ(char JJIJIIJJIIJJIIIIIJJIJIIJJJJJJIJIJIIIJJJJJIIJIJI)
	{
		return 0;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static char JIIJIIIIIJIIJIJJIIJJIJIIIIJIIJIJIIJJJIJIJJIJJJI(int IIIIIJJJIJJIIIJIIIJIIJIIIJJJJIIIIIIIIIIIIIJIIJI)
	{
		return '\0';
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static string IIJIIJIJIJIIJJJIIIJJJIIIJJIIIJIJIIIIJIIJJIIIIJI(int IIIIIJJJIJJIIIJIIIJIIJIIIJJJJIIIIIIIIIIIIIJIIJI)
	{
		return null;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public static string IJJJIIIIJIJJIIJIIIIIIJJJIJJIIIJIJIJIIJIJIIIJJII(int IIIIIJJJIJJIIIJIIIJIIJIIIJJJJIIIIIIIIIIIIIJIIJI)
	{
		return null;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public static string JIJIJJIIIJJJIJIJJJJJJIIJIJIJIJIJIIJJJIIIJJJJIII(int IIIIIJJJIJJIIIJIIIJIIJIIIJJJJIIIIIIIIIIIIIJIIJI)
	{
		return null;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public static int JJJJIIIJIJJJIJJIIJIIIJIIIIJJJIJIJIIJIJJIJIJJIJJ(Color IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
	{
		return 0;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public static Color IJJIIJJJJIIJIJIIIJIJIJIIJIIIIIIIJIIIIIIIJIIJJII(int JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
		return default;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public static string JIJJIJJIJJIIIIJJJIJIIJIJIJIJIJIIIJJJIIIJIJIJJJI(int JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ, int JIIIIJJIJJIIIJIJJIIIIJJIJIJJJJJJJJIIJJIIIIIIJII)
	{
		return null;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static Color JIIIIIJIJIJIIIJIIIJJIIJIJIIIIJJJIIJIJJJIJJIIIII(uint JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
		return default;
	}

	public static Rect IIIJJIJIJIJJJJJIIJJJIJJIJIJIJIIIIIJIIIJJIIIIIII(Rect IJJIIJIJJJJJJJJJIIJIIJJJIIJIIJIJJIIIJJIIIJJJIJI, int JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, int JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
		return default;
	}

	public static Rect JJJJIIIIJJIJIJIIJIJIIJIJIIJJJJJJJIJJJJJJJJJIJJI(Rect IJJIIJIJJJJJJJJJIIJIIJJJIIJIIJIJJIIIJJIIIJJJIJI, int JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, int JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII, bool JIIJJIJIJIJIIIJJJIIJJJJIJJIJJIIIIIIJJJIJIJIJIII)
	{
		return default;
	}

	public static Rect JIIIJIIIIIJIJIJJIIIIIJIJIIJIJIJIIIIJIJIIIIJIJJI(Rect IJJIIJIJJJJJJJJJIIJIIJJJIIJIIJIJJIIIJJIIIJJJIJI)
	{
		return default;
	}

	public static Rect JIIIJIIIIIJIJIJJIIIIIJIJIIJIJIJIIIIJIJIIIIJIJJI(Rect IJJIIJIJJJJJJJJJIIJIIJJJIIJIIJIJJIIIJJIIIJJJIJI, int JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, int JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
		return default;
	}

	public static Vector2 JJJIIIJIJIJIJIJJJJJJJJJIIIIJJJIJJIIJIIIIIJIIJIJ(Vector2 JJJJIIJJJJJIIJIIIIJJIIIJIIIJIJJJJJJIIIJIJJJIJJJ, Vector2 IIIIIJJIJIIIIJIJIJIJJIIIIJJIIJJJIIIIJJJJIJJJIJI, Vector2 IIIJJJJIIJIIIIIIJIJIIJJIJJIJIIJJIJIJJIIIJJIJIJJ, Vector2 JJIJIIIIJIIIJJJIJJIJJIJIIIIJJJIIIIJIJIIIJJJJJJI)
	{
		return default;
	}

	public static Bounds JJJJJJIIJJJIIIJIIIIJJIJJJJIIJJIIIIJIJIIIIJIJJII(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ)
	{
		return default;
	}

	public static Bounds JIJJJJIIIIIJIJJJIIJIIJJJJJJJJIIJIJIIIIIIJIIIJII(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ)
	{
		return default;
	}

	public static Bounds JIJJJJIIIIIJIJJJIIJIIJJJJJJJJIIJIJIIIIIIJIIIJII(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ, bool JJJIJIIIIIIIJIIJIIIJJJJIIJIJIJJJIJIIIJIIJIJIIII)
	{
		return default;
	}

	public static Bounds JIJJJJIIIIIJIJJJIIJIIJJJJJJJJIIJIJIIIIIIJIIIJII(Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ, Transform IIJJIJIJJJJJIIIIIJJIJIJIJJIIIJIJJJIJJIIJIIJIIJI)
	{
		return default;
	}

	public static Bounds JIJJJJIIIIIJIJJJIIJIIJJJJJJJJIIJIJIIIIIIJIIIJII(Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ, Transform IIJJIJIJJJJJIIIIIJJIJIJIJJIIIJIJJJIJJIIJIIJIIJI, bool JJJIJIIIIIIIJIIJIIIJJJJIIJIJIJJJIJIIIJIIJIJIIII, bool IIIIIIIIJIIIJIIJJIJIJIJJIIJIIIJJIIIIJIJIJIJIIII = true)
	{
		return default;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	private static void JIJJJJIIIIIJIJJJIIJIIJJJJJJJJIIJIJIIIIIIJIIIJII(Transform IIJJIJIJJJJJIIIIIJJIJIJIJJIIIJIJJJIJJIIJIIJIIJI, bool JJJIJIIIIIIIJIIJIIIJJJJIIJIJIJJJIJIIIJIIJIJIIII, bool IJJIIIIJIJIJIIJJJJJIIJIIJIIIJIJIJJJIIJIJJJIIJJJ, ref Matrix4x4 IJIJJJIJIJIJIJIIIIIIJIIIIJIIIJJJIIIJIIIJJIIJIJI, ref Vector3 IIIIIJIIIIIIJIJIJIJJJIJIJJJJJJJJJIIIIIIJIJIJJII, ref Vector3 IIIIIIIJJIJJIIJIJIIJJIIIJJJJIJJJIIJJJJIJJJJJIII, ref bool IJIJJIJJIIJIJJJIIJJIIJJIJIJIIJJIIIJJJIJJIJIIJII, bool IIIIIIIIJIIIJIIJJIJIJIJJIIJIIIJJIIIIJIJIJIJIIII)
	{
	}

	public static Vector3 IIJJIIIJJIIJIJIJJIIIIJJIJJIJJJIIJIJJIIJJIJJIIJJ(ref Vector3 JIIIIIJJJIJJJJIIIJJIIIIIJJIJJJJJIJIIIJJIIIJIIIJ, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI, float JIJIIIJIJJJJJJJJJIIJJIIJJJIIIIIIJIJJJJJIJIIIJIJ)
	{
		return default;
	}

	public static Vector2 IIJJIIIJJIIJIJIJJIIIIJJIJJIJJJIIJIJJIIJJIJJIIJJ(ref Vector2 JIIIIIJJJIJJJJIIIJJIIIIIJJIJJJJJIJIIIJJIIIJIIIJ, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI, float JIJIIIJIJJJJJJJJJIIJJIIJJJIIIIIIJIJJJJJIJIIIJIJ)
	{
		return default;
	}

	public static float IIJIJJIJIIIIIIIJJIJIIIIIJJJJIJJJJJJJJIJJIIJJIIJ(float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI, float JIJIIIJIJJJJJJJJJIIJJIIJJJIIIIIIJIJJJJJIJIIIJIJ)
	{
		return 0f;
	}

	public static float IIJIJJIJIIIIIIIJJIJIIIIIJJJJIJJJJJJJJIJJIIJJIIJ(float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI, float JIJIIIJIJJJJJJJJJIIJJIIJJJIIIIIIJIJJJJJIJIIIJIJ)
	{
		return 0f;
	}

	public static Vector2 IIJIJJIJIIIIIIIJJIJIIIIIJJJJIJJJJJJJJIJJIIJJIIJ(Vector2 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Vector2 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI, float JIJIIIJIJJJJJJJJJIIJJIIJJJIIIIIIJIJJJJJIJIIIJIJ)
	{
		return default;
	}

	public static Vector3 IIJIJJIJIIIIIIIJJIJIIIIIJJJJIJJJJJJJJIJJIIJJIIJ(Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI, float JIJIIIJIJJJJJJJJJIIJJIIJJJIIIIIIJIJJJJJIJIIIJIJ)
	{
		return default;
	}

	public static Quaternion IIJIJJIJIIIIIIIJJIJIIIIIJJJJIJJJJJJJJIJJIIJJIIJ(Quaternion IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Quaternion JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI, float JIJIIIJIJJJJJJJJJIIJJIIJJJIIIIIIJIJJJJJIJIIIJIJ)
	{
		return default;
	}

	public static float IJIJIJIJJIIIJJJIJJIIJIJJIIIIJIJJIIIJJJIJIJJIJII(float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIJJJJJIIIIIJIIIIIIJJJJIJJJIJIJJIIJJJJIIIJIII)
	{
		return 0f;
	}

	private static float IIIIJJJIJIIIIJJJIIJIIIIIIIJIIJJJIIIJIIIJIJIIIII(Vector2 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII, Vector2 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, Vector2 JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0f;
	}

	public static float JJIJIIIJIIJJIJJIJJJJJIIJJIJIIJJJIJIIJJJJIIJJIJI(Vector2[] JIIIJIIJIIJJJIIJIIJJIJIJIIIIIIJJJIJIIIJJJJIIJIJ, Vector2 JJJJIIIIIJIJJJIJIJJJJIJIIJIIIIIJIJJIIJJIIJIJJJI)
	{
		return 0f;
	}

	public static float JJIJIIIJIIJJIJJIJJJJJIIJJIJIIJJJIJIIJJJJIIJJIJI(Vector3[] IJIIIJIIIIIJJJIIJIJJJIJIIJJJJIJJIIIJIJIJJIIIIIJ, Vector2 JJJJIIIIIJIJJJIJIJJJJIJIIJIIIIIJIJJIIJJIIJIJJJI, Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ)
	{
		return 0f;
	}

	public static Vector2 IJJIJIJIIIJJIJIJJJJJIIIIIIJJIJIJJJIJJJJJIIIIIJJ(UIWidget.JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII JJIJIJIJIJJJIIJIJJIIJJIIIIIJIIJJJIJIIIJJJJIJIJJ)
	{
		return default;
	}

	public static UIWidget.JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII JIJJIJJIJIJIJIJIJJIJIJJIIJIIJJJJJJJJJJIJIIIJJJJ(Vector2 IJJIJIIIIJIJIJJIIIIIIIJIIIJJIIIIJIJIJJIJIJIJIJJ)
	{
		return UIWidget.JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII.TopLeft;
	}

	public static void JJJJIJJIJJIJJJIIJJJIJJJIJJJJJJIJIIJJJJIIJIIIIIJ(UIRect JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII, float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI)
	{
	}

	public static void JJJJJIJIJIIIJIJIJJJIIIJIIJIJJIIIJIIJJJJJIIJJJIJ(UIRect IJJIIJIJJJJJJJJJIIJIIJJJIIJIIJIJJIIIJJIIIJJJIJI, float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI)
	{
	}

	public static void IIJIJIJIIIJJIIIIJJIIIJJIJIIIIIJJIIJJJIIIJJIJJJI(UIWidget JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII, UIWidget.JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII JJJJJIJIJJIJIJIIIJJIIIJJJIIIJJJJJJIIIJIJIIJJJJJ, float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIIIJJJIIJJJIIIIIJJJJJJJIIJJJJIIJJJIIJIIJIIJJJJ, int JIJJJJJIJJIIJJJJJJJJIJIIIIJJIJIJJJJIJJIIJJIIIIJ)
	{
	}

	public static void IIJIJIJIIIJJIIIIJJIIIJJIJIIIIIJJIIJJJIIIJJIJJJI(UIWidget JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII, UIWidget.JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII JJJJJIJIJJIJIJIIIJJIIIJJJIIIJJJJJJIIIJIJIIJJJJJ, float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIIIJJJIIJJJIIIIIJJJJJJJIIJJJJIIJJJIIJIIJIIJJJJ, int JIJJJJJIJJIIJJJJJJJJIJIIIIJJIJIJJJJIJJIIJJIIIIJ, int JJJJJJJJJIJJIIIIJJJJJIIIIIJJIJIIIJJIIIJIJJIIJIJ, int IIJIJJIJIJJIIIJIIJJIJJIIJJJJIJJJIJJJJIIIJIIJIII)
	{
	}

	public static void JIIIIIIJJJJJJIIJJIIJJIIIIIJJIIJJJJIIJIIJJIIJJII(UIWidget JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII, float JIJIIIIJJIIIIIJJJJJJIIIIJJIIIIJIIIIJJIJJJIIIIII, float IIIJJIIIIJIIIJIIJJIJIIJIIIJIIJJIIIJJJIIJIJJJJIJ, float IJIIJJJIIJIIJJJIIIJIIIJIJIIJJJJIIJJIIIJJJIJIIII, float IIIJIJJIIIJJIIIIIIJIJIJJIIJIIIJIJIIJIJIIJJJIIJJ)
	{
	}

	public static void JIIIIIIJJJJJJIIJJIIJJIIIIIJJIIJJJJIIJIIJJIIJJII(UIWidget JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII, float JIJIIIIJJIIIIIJJJJJJIIIIJJIIIIJIIIIJJIJJJIIIIII, float IIIJJIIIIJIIIJIIJJIJIIJIIIJIIJJIIIJJJIIJIJJJJIJ, float IJIIJJJIIJIIJJJIIIJIIIJIJIIJJJJIIJJIIIJJJIJIIII, float IIIJIJJIIIJJIIIIIIJIJIJJIIJIIIJIJIIJIJIIJJJIIJJ, int JIIIJJJIIJJJIIIIIJJJJJJJIIJJJJIIJJJIIJIIJIIJJJJ, int JIJJJJJIJJIIJJJJJJJJIJIIIIJJIJIJJJJIJJIIJJIIIIJ)
	{
	}

	public static void JIIIIIIJJJJJJIIJJIIJJIIIIIJJIIJJJJIIJIIJJIIJJII(UIWidget JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII, float JIJIIIIJJIIIIIJJJJJJIIIIJJIIIIJIIIIJJIJJJIIIIII, float IIIJJIIIIJIIIJIIJJIJIIJIIIJIIJJIIIJJJIIJIJJJJIJ, float IJIIJJJIIJIIJJJIIIJIIIJIJIIJJJJIIJJIIIJJJIJIIII, float IIIJIJJIIIJJIIIIIIJIJIJJIIJIIIJIJIIJIJIIJJJIIJJ, int JIIIJJJIIJJJIIIIIJJJJJJJIIJJJJIIJJJIIJIIJIIJJJJ, int JIJJJJJIJJIIJJJJJJJJIJIIIIJJIJIJJJJIJJIIJJIIIIJ, int JJJJJJJJJIJJIIIIJJJJJIIIIIJJIJIIIJJIIIJIJJIIJIJ, int IIJIJJIJIJJIIIJIIJJIJJIIJJJJIJJJIJJJJIIIJIIJIII)
	{
	}

	public static int JIJIIIIJJIIJJIIJIJIJIIJJIJIIJIIJJJIIIJIIJJIJJJJ(float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
		return 0;
	}

	public static Vector2 JIIJIIIIJIJJJIJIJIIIJJJIJIJIIIIJJIJIJJJIIIJJJJI(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
	{
		return default;
	}

	public static Vector2 IIIJJJIIIJIJJIJIJIIIJIJIJIIJJIIIJJJIJIJJJJJJJIJ(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
	{
		return default;
	}

	public static Vector3 JJJIIJIJIJJIJJJIIIIJIJIIIIIIJIJIIJIIIJIJJJIJIJJ(Vector3 IIIIIIIJIIIJJIJIJJJJJJJIIIJJJJJIIIIJJIJIIJJIIJI, Camera IJJJJJJIIIJJJJJIIIJIIJJJIJIIIIJJJJJIJIIIJIIIIII, Camera JIIIIIIJIJIIIIJIJJIJIIJIJIIJIJJJJJJJJJIJIIIJJJI, Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
	{
		return default;
	}

	public static void IJIIIIIIIJIJIJJJJIJIJJJIIJIIIIJIJJIJIIIIIJJJIJI(this Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ, Vector3 IIIIIIIJIIIJJIJIJJJJJJJIIIJJJJJIIIIJJIJIIJJIIJI, Camera IJJJJJJIIIJJJJJIIIJIIJJJIJIIIIJJJJJIJIIIJIIIIII, Camera JIJIJJJJIJJJIIIJJIJIJIJJJIIIJIJIIIJJJJIIIIIIIII)
	{
	}

	public static void IJIIIIIIIJIJIJJJJIJIJJJIIJIIIIJIJJIJIIIIIJJJIJI(this Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ, Vector3 IIIIIIIJIIIJJIJIJJJJJJJIIIJJJJJIIIIJJIJIIJJIIJI, Camera IJJJJJJIIIJJJJJIIIJIIJJJIJIIIIJJJJJIJIIIJIIIIII)
	{
	}

	public static void IJIIIIIIIJIJIJJJJIJIJJJIIJIIIIJIJJIJIIIIIJJJIJI(this Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ, Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII)
	{
	}
}
