using UnityEngine;

public static class IIIIJJJJIJJIIJIIJJJIJIIIIJJIIJIJIJJJIJIJJJJIJJJ
{
	public enum IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ
	{
		Denied = 0,
		Granted = 1,
		ShouldAsk = 2
	}

	public delegate void IJJJJJJIIJJJJJJJJJIJJIJIJIJJJJJJIJIIJIIJJIIJIJI(string IIIIIIJJIJIIJIJJIJIIIIJJJJJIJJJJIIJIIJJJIJJIJII, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ);

	public delegate void IIJJIIJIJJJJIJIJJJIJIIIIIJIJIIIJIIJJIJJJJIJIIJJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ);

	private sealed class JJJJIJJIIIIIJJJJJJJIJJIIIIIJIIJJIJJJIIJJJIJIJJI
	{
		public IJJJJJJIIJJJJJJJJJIJJIJIJIJJJJJJIJIIJIIJJIIJIJI IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI;

		internal void IIIJJJIIIJJJIIIJJJJIJIIIIIJJIIIJJIJIJIIIIIJIIIJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIIJJIJIIIIIJIJIIIJJJIJIIJJJIJJJJJJJJJIIIJJJIJJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IIIJJJJJJIJJIJIJIIIIIIIJIJJJIIIJIIJIJJIJJJIIJJJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIJIIIJJJJIIIIIJJIIIJIIIIJJIJIJJJJIJIJIIJJIJJJJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JJJIIIIIIIIIJIJIJJIIIIIJJIJIIJJJIJIJJIIIIIJJIIJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JJJJJIJIIJIIIIIJIJJIIIIJIJJJIIJJIJJIIIJIJJIIIJJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IJJIIJIIJJJJIJJJJJJIJIIJIJJJJJIIJJIJJJJIJJJIJIJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IIJIJJIJIJJJIIJIJIJJJIJJJIIIIJJIJIIJJIJIJJIJJJJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIIJIIIJJIJJIIIJJJIJIIJJJJJIIJIJIJIIIIIIJIJJIJJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IJIIJJJIJIIIJIIJIJIJJIJIJIJJJIJIJIIJJIIIJIIIIIJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IIIJJJJIJIJIIJJIJJJJIJJJIJIJIJJIIIJJIJIIJJIJJIJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIIJIJJJIIIIIJJJIJIIJIIIJIJIJIJIIJIIJJJIJIJIIJJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JJIJIJJJJIJJIJIJIJIIIIIJIJJJIJJIIJJIJIIJIJIIJIJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JJIIIJIJIJJJJIJIJIJJIJIJJJIJJJJIIJJIJIIJIJJIJII(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIIIIJIIJIJIJIJJIJJJJJJJJIJJJIIIIJIJIJIIJIIJJIJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IIJJIIJJJJIIJJIJJIIJJIJJIJIJJIIIIJJIIJJIIIIJIII(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JJJIIIIIJJJIJJIJJJIJJIIIJIIIIJJIJJJIIJJJJIIIIJI(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IJIIIJJIIJJIIJIJIJIIJJIJJJIIIIJIIJJIIIIIJJJJIJI(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}
	}

	private static AndroidJavaClass IIIJJJJIJJJJJIIJIJJJJJJIIJIIIIJIJIIIJIIJJIJIJII;

	private static AndroidJavaObject JJIJJJIJIIJJJIIJIJIJIIJJJIIJIJIJJJJIIJJJJJJJIJI;

	private static AndroidJavaClass JIJJIJJJJIIJJIIJJIJIJIJIJJJIJJJJJIJJIJIIJIIIIJJ => IJIIIIJJIIIIIJJIJIJIIIJIIIIIIIIJJJIIIJIIJIIIIJI();

	private static AndroidJavaObject JIIIJIIIIJJIIIJIIIJIJIIIIIJJIJIJJJJIIJIJJIIJIIJ => JIJJJIJJJJIIIIJIIJIJIIJJIIJJIIJIJJJJIJIIJIIJIIJ();

	private static AndroidJavaClass IJIIIIJJIIIIIJJIJIJIIIJIIIIIIIIJJJIIIJIIJIIIIJI()
	{
		return null;
	}

	private static AndroidJavaObject JIJJJIJJJJIIIIJIIJIJIIJJIIJJIIJIJJJJIJIIJIIJIIJ()
	{
		return null;
	}

	public static void IJIIJJJIIIIJIIJJIJIIIIIJIJJJIJJJJIIJIJJJIIJIJII()
	{
	}

	public static IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ IIJJJJIJJIIIIIJIJJJIJJIJIJJJIJJJIJIJIIJIIIIIJIJ(string IIIIIIJJIJIIJIJJIJIIIIJJJJJIJJJJIIJIIJJJIJJIJII)
	{
		return IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ.Denied;
	}

	public static IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JJJJIIJJJIJJJJJJIJJJJIIJIIIIJJJIJIJIJIJIIIIIIIJ(params string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ)
	{
		return null;
	}

	public static IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ JIIIIIJIJJJJIIIJJJIIJIIIIIJJIIJIIIJIIIJJJJJJIII(string IIIIIIJJIJIIJIJJIJIIIIJJJJJIJJJJIIJIIJJJIJJIJII)
	{
		return IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ.Denied;
	}

	public static IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] IIIIIJIIJJIIIJIJJIJIIIIIIJJJIIIJJIIIIJJJIJJIJJI(params string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ)
	{
		return null;
	}

	public static void IJIIJJIJIJIJIIJIJJJJJIIJJIIJJIJJIIJIIJIJIIIJIII(string IIIIIIJJIJIIJIJJIJIIIIJJJJJIJJJJIIJIIJJJIJJIJII, IJJJJJJIIJJJJJJJJJIJJIJIJIJJJJJJIJIIJIIJJIIJIJI IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
	}

	public static void IIIIJJIJIIJJJJJJJJIJIIJJJIIJJJIIJJIIJIJIIIIIIJI(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, IIJJIIJIJJJJIJIJJJIJIIIIIJIJIIIJIIJJIJJJJIJIIJJ IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
	}

	public static IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] IIJIIIJJJIIJJJJIIJIIJIJJJIJJJJIJJIJIIJIIIIIIIII(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ, string JIJIIJIJIIJIIIIJJJIIIIJJJJJIJIJIIJIIIIIJIJJJJII)
	{
		return null;
	}

	private static IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ JJJJJJIIJJJJIIJJJJIIIIJJIJIJJIIJJJIIIIJIJJJJIJJ(string IIIIIIJJIJIIJIJJIJIIIIJJJJJIJJJJIIJIIJJJIJJIJII, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ.Denied;
	}

	private static string IIJIJIJIIJIJIIJIJJIIIIIJJJJIJJJJIIJJJJIIJJIIJIJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ)
	{
		return null;
	}

	private static bool IIIJJJJJJJIJJJIJJJJIIJIJJIIJIIIJJIJJJIJIJJIIJJI(string IIIIIIJJIJIIJIJJIJIIIIJJJJJIJJJJIIJIIJJJIJJIJII, IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return false;
	}

	private static void JIIJIIJIIIJIJJJIJJJJJJIIIJJJJIIIIIIIJJIIJJIJJJJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ)
	{
	}

	private static IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ[] JJJIJIIJJJJJJIJIJJJIJJJJJJJJIJJJJIIJJIJJJJJJJIJ(string[] JJIJJJJJIIJIJIIJJIJJJJIIJIIIJIIIJIIJJJIIIJJIJIJ)
	{
		return null;
	}

	private static IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ IIJIJJJJJIJIIIIJJJIJIIJIIIJIJJJJIJIIJJJIJIJIIIJ(this char JJIJIIJJIIJJIIIIIJJIJIIJJJJJJIJIJIIIJJJJJIIJIJI)
	{
		return IJIJIIIIJIIIJIJIJJIIIIJJIIIIJIJIJJIJIJJIIJIIJIJ.Denied;
	}
}
