public class IIIIIJIIIJIJIJIIJIIIJJIJIIJJIIIIIIIJIJIIJJIIJJI
{
	public int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ;

	public int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ;

	public int IJJJIIIIJIIIJIIJJJIJJIJIIIIIJIIIIIJIIJJIJIIJIJJ;

	public int[] IIIJIJJJIJJIJIIIJIIJJJIIIIIJIJIJIIIIIIIJJJIIIII;
}
