using System.Collections.Generic;
using UnityEngine;

public interface IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII
{
	Material IIJJJJJJIJJIIIJIIJJIJIIJJJIJIJJIIIIIJIIJJIJJJII { get; set; }

	List<IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ> JJJIIIIJIIJJJJJIIIJIIIJJIIJJIIJIJJIJIJIIIIJJJJJ { get; set; }

	Texture IIJIJIIIJJJIIIJJIIJJIJIIIIIIJJJIIJIJIJJIIIJIIIJ { get; }

	float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII { get; set; }

	bool JIJJJIIJIIIJIJIJIIJIIIIJJIJIJIJIJIJIJJIJJJJIIJI { get; }

	IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JJJJJJIJJIJJJIIJIIIIJIJJJJJJJIJIJIJIJJIJIIIJJII { get; set; }

	Material spriteMaterial { get; set; }


	List<IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ> spriteList { get; set; }


	Texture texture { get; }

	float pixelSize { get; set; }


	bool premultipliedAlpha { get; }

	IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII replacement { get; set; }


	IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ JJJJIJJIIIIIJIJJIJJJJIJIIJJJJIJJIJIIIIJIJIJIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ);

	global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<string> JIJJJIJJIJIJIIJJJIIJJIJIIJIJIIIIIIIJIIJJJJIJIJJ();

	global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<string> JIJJJIJJIJIJIIJJJIIJJIJIIJIJIIIIIIIJIIJJJJIJIJJ(string IIJJJIIIIIIIJJIIIJJJJJJIIJIIIJJIIIIIIJIJJJJJIJI);

	bool IIJJIIIIIJJJIJJJJJIIJJIJIIJIJIIIJIJJJJJIJJJJIJJ(IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JJJIIIJJJIIIIIJIJIJJIIIJIIIIIIIJIIIJIIIIIIJJJJI);

	void IIJIIIJIJIJJJJIJJIIJIIJJIIJJJJJIIIIIIJIJIJIIIIJ();

	void IIJJJJJIIJJIJJIIIIJIIIJIIJJIIIJJJJJIIJIJJIIIJIJ();
}
