public static class IIIJIJIJJIIJIJIIJJIIJJIJIIIIJIJIIJIIIJJIJJJIJIJ
{
	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	public static void JJIJIIIIIJJIJJJIJIJIIIJJJJIJIJJJJJIIIIJJIJJIIJJ()
	{
	}

	public static void IIJJJIIIIJIJJJJIIJIJJJJJJIJJIIIIIIJJIIJJJIJJJJI()
	{
	}
}
