using System.Runtime.CompilerServices;
using UnityEngine;

public class IIIJIJIIJJIJJJJJIJJIJIJIJJJJJIIIJIJJIJJIIIJJJII
{
	public enum JIJJIJIJJIJJJIIIIIJIIIIIIJIIJJIIJJIJIIJJJIIJIJJ
	{
		Position = 0,
		PositionAdditive = 1,
		Rotation = 2,
		RotationAdditive = 3,
		Scale = 4,
		ScaleAdditive = 5
	}

	protected delegate void JIIJIIIJIJIJJJJJIJIIJIIJJIIIIIJJJIJJJJJJJJIJIJI();

	protected JIJJIJIJJIJJJIIIIIJIIIIIIJIIJJIIJJIJIIJJJIIJIJJ JIIIIJJJJJIIIIJIJIJIIJIJIIJJJIIJJJJIJJJJIJIIIJI;

	protected bool JIIIIIJIIIIIIJIIJIIIIJJJJJJIJJJIIJJIJJJJIJJIIJI;

	protected JIIJIIIJIJIJJJJJIJIIJIIJJIIIIIJJJIJJJJJJJJIJIJI IJJJIIIJIJIJIJIJJJIJJJIJIIIJIJIIJJJJIIJIJIJIJJI;

	public Vector3 JJJIJIIJJIIJIIIJIIJJJIIJJIJIJIJIIJIIJJJJJIJIIJJ;

	protected Vector3 IIIIJIIIJJJJJJIJIIJJIJIIIJIIIJJIIJIIJIIIJIJJJJJ;

	public Vector3 IIJIJIJIJJIIJJIJIJJIIJJIJIJIIJIIJJJIIJJJJIIJJIJ;

	public Vector3 IIIJJJJJIJJJIIJJIJIJIIIIJJJJJJIJIIJIJIIJJJIIJII;

	public Vector3 IJIIJIIIJJJJJIIJIIJIIJIJJIIIJIJIIIIJJJIJJJJIIJI;

	protected float IIIIJJJJIJIIIIIIIJJIJIIIJIIJJIIJIIJJJJJIJJIJIIJ;

	protected float IIJIJIIJJJJJIJIJIJJJIIIIJJJIJJJIJJJIJIJIIJJIJJJ;

	protected float JIJJIJIIJIIJIIIJJJJJJIIIIIIJIIJJIJJIIJJJIIJIJIJ;

	protected Vector3[] JJJIIIIIJIIJJIJIIJJJIJIIIIJJIIIIJJJJJIJIJIIIIJI;

	public float JJIIIJIIIJIIJJIJIJIIJJIJJJJIIJJIJJJJIIIIIJJIJJJ;

	public float IJIIIJJIJJIIIJIIIJIIJIJIIJJIIIJJIJIJIJJIIIIJIII;

	public Vector3 IIIIJIIJIIIJIJIIIJIJIIIJJJIIIIJJJJJJJJIIJIIJJIJ;

	public Vector3 JIJIJIJJJIIJJJJJIJIIJJJJIJIIJIIJJJJJIJIJIIIJJIJ;

	protected Transform IJJIIJIJJIIIIIIJIJJIIJJIJIIJIIIJIJJJIIIIJJJJIJJ;

	public Transform JJIJIIJIJJJJJJIIIIJIJIJIIIIJJJIIIJIIJIIJIJJJJIJ
	{
		set
		{
			IIJJIJIIIIJIIJIJJJIJIIJJJJIJJJIJIJIIJJIIJIIIIJI(value);
		}
	}

	private void IIIJIIJIJJIJJIIJJIJIIIJJJJJIJIJJJJJIJIIJIJJIIJJ()
	{
	}

	private void JJJIJJJIIJIIJIIIJJJIJIJIIJIJIJIJJIJJIJJIIJJIIJJ()
	{
	}
	public void IIJJJIJJJJIIIIJIJIIJIIIJIIJIIJIIJJJIJJIIIJJIJII(Transform JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJJIIIIIIIJJIJJJJIIIJJIJIJIJJIIJJJJJIJIIIIJIIJ()
	{
	}

	private void JJJIJIJJIIJJJIIJJJIIJJJIJIJJJJIJJJIIIJIJIIJIJJJ()
	{
	}

	private void JIJIIIJIJIJIIJIIJIIIIIIIJIJIIIIIIJIIJJIJJIIIJJJ()
	{
	}

	private void IJJIIIJIJIIJJJJJIJJJIJIIIJIJJJIJJIIIIIIIIIIJJII()
	{
	}

	public void JJIIJIIIJJJIIJIJJJJIIJIIIJIJJIIIIIJIJIJJIIJIIIJ()
	{
	}

	public void IIJJJIIJIIJIJIIIJIJJIJIIIIJIJIJIIIIJIIIIJIIJIJJ(Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII, float IJIJIJIJIIJJJIJJJJJIJJJJIJJJIJIJJIIIIIJJIJIIJJI)
	{
	}

	protected void IIIIJJJIJIJJIIIJIJJIIIIIJJIIIIIJIIIIJJIJIJIJIJJ()
	{
	}

	private void JIIJIJIJIJIIJJIIJIIJIJIJIJIIIJIIJJIIJIJIJIIIJII()
	{
	}

	public void IJJJIJIJIJJJIIJJIJIJIIJIIIIIIIJJIJJIIJIJIIIIIJI(bool IIIJJJIJIJIIJJJJIJIIJIIIJJJIIIIJJJJIIJIIIJIJIJJ = false)
	{
	}

	public void IIIJIIJIIJIJIIJIIIJIJIIIJJIJIIJIIIJIIIJIIJJJJJI()
	{
	}

	public void JIIJJIJJIIIIJJJJJIIJJJIJJJIIIJJJIJIJIJIIIIIIJII(Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}

	protected void IIJJJIIIIJIJIJIIIIJJJIIIIJIJIJIIJJJJJJJIIJJJJJI()
	{
	}

	protected void JJJJJJIJIIIJJJJJIIIJJIJJJJIJJJJJIIIIJIJJJJJIIII()
	{
	}

	private void JIJJIJIJIIJJIJIIJJJJJJJIJJIJIIJJIIJIIIIJJIJIJII()
	{
	}

	public void JIIJIIIIJIJJIJJIJJIIIJIIJJIJJIJIJIJJIIJJIIJIIJI(float IJIIIIJIJIJJJJJJIJIIIIJIJIJIJJJJIJIJIJIIJJJIJIJ)
	{
	}

	public void IIJJIJIIIIJIIJIJJJIJIIJJJJIJJJIJIJIIJJIIJIIIIJI(Transform JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected void IIIIJJJIIIJJIJIIJJJJJJJJJJJIIIIIIJJIJIIJIJJIIJJ()
	{
	}

	public void IJIIIJJIJJJIJIJJJIJIIJIIIIIIIIJJIIIIIIJIJIIIJJI(Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}

	private void IIJIJIIJIJJIJJIIJIIIIJJIIIIJJJJJIIJIJJIJJJIJIIJ()
	{
	}

	protected void IIIIIJIJJJIJJIJJJIIJIJJJJJIIJIJJIIIJJIJJIIJIIJJ()
	{
	}

	private void JJJIJJIIIIIIIIIIJIJJIJJJJIIIJJIIJJJJIIJIIJIIJJI(Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}

	public void IJIIJJJIJJIIIIJJJJIIJIIJIJJJIIIIIIIIIIIJIIJIJIJ()
	{
	}

	public void JIIJJIIJJJIJIIIJJJIIJIIIJJJJIIJIJIJJIJIIIIJJJIJ(bool IIIJJJIJIJIIJJJJIJIIJIIIJJJIIIIJJJJIIJIIIJIJIJJ = false)
	{
	}

	public void IIIIIJIIJIJJJIJIIIIIJJJIIIIJIIJJJIIIIJJJIIJJIJJ(bool IIIJJJIJIJIIJJJJIJIIJIIIJJJIIIIJJJJIIJIIIJIJIJJ = false)
	{
	}

	public IIIJIJIIJJIJJJJJIJJIJIJIJJJJJIIIJIJJIJJIIIJJJII(Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI, JIJJIJIJJIJJJIIIIIJIIIIIIJIIJJIIJJIJIIJJJIIJIJJ JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI, bool IJJJJJIJJIIIJJJJJJJIJIIIIIJIIIJJIJIJJIIJJIJIIII = true)
	{
	}

	private void JIIIIJIIJIIIIJJIIIJIIIJJJJJIJJJIIJJIJJJIIJJIJJJ()
	{
	}

	public void IJIIIJJJJIJJIIJJJIJJJJJIJJJIJJJIIJIIJIJIJIIIJIJ()
	{
	}

	public void JIJJJJIIIJIIJJJIIIJJJJIIJJIIIJJJJJJJIJIIIJJJJJI()
	{
	}

	public void IJIIJIJIJIJIIIIJJJJIIJIJJJIIJJIJIIJIIIIJJJIIIIJ()
	{
	}

	private void IJJIJJJIIJIJIIJIJJJJJIJJJJIJJIJJIJJIIIIIIIJIIIJ()
	{
	}

	private void IIJIJJJIIJIJIJIIJJIJJIIIIJJJIJJIJJIIJIJJJJIIIII()
	{
	}

	private void IJIIJIJJJIJIJJIIIJJJJJIJIIIJIIIIJIIIJJIIIJIIJII(Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}
}
