using System.Runtime.InteropServices;
using UnityEngine;

public class IIIJIJJJIJJJIIJJJJJJIJJJIJIJJJIJIIJIIIJIJJIIIJJ
{
	[StructLayout((LayoutKind)0, Size = 4)]
	private struct IIJIIIIIJJJJJIIIIJIIJIIIIJJJIJJJJJJJIIJJJIJJJJI
	{
		public byte JJJIIJJIJJIJJJIJJIJJIJJIJIIIJIIIIIJIJJJIJIIIIII;

		public byte IIIJJIIJIJJIJIIIJIJJJJIIIIIIJIIJJIIJIJJIIJJJJJJ;

		public byte JIIJJIIIIIJJIJJIIJIIIJIIJIJJIJJIIIJIIIJJJIJIIIJ;

		public byte JJIJIJJIIJJIJIJJIIJJIJIJIJIIJJIIJIJIIIIIIJIIJJI;
	}

	[StructLayout((LayoutKind)2, Pack = 1, Size = 4)]
	private struct JJIIJIJIIIIJJJIJIJIJIIIJIJJIIIIJIJJIJJIJJJIIIIJ
	{
		[FieldOffset(0)]
		public float JIJIJJJIJJIIIIIJIIIIIJJJJJJJIIIIJIIIJJJJIJJIIJI;

		[FieldOffset(0)]
		public IIJIIIIIJJJJJIIIIJIIJIIIIJJJIJJJJJJJIIJJJIJJJJI JJIJIJJIIJJIJIJJIIJJIJIJIJIIJJIIJIJIIIIIIJIIJJI;
	}

	public global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<byte> JIIIJJIJIJIJJJIIJIJJJJJIJIJIIIIJIIIIJJIIJIJJIIJ;

	private JJIIJIJIIIIJJJIJIJIJIIIJIJJIIIIJIJJIJJIJJJIIIIJ IIIIIJJJIIJIJJJIJIJJJJIJIIJJJIIJJJJIJIJJIJJJIII;

	public void IIIJJJIJIJIJIIJJIJIIJJJIJIJJJIIJIIIIJJJIIIJJIJI(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIJJJIIIJIJIJJIIIJJJIJJIIJIJIJIJJIIJJIJJJIJIII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(byte JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIJJJIIIJIIJJJIJJJIIIIIIIJJIJIJJJJJIJIIJIJJJIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJIIIJIJJJIIIIJIJIJJJJIJJIIIJIIIJIJJIJIIJJIIJJ()
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIJIIJIJIJJJJJIIJJJIIJIIJIJIIJIJJIIJIJJJJIIJIIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIIJJJIJJIIIJIIIJJJIJJJIIIJIJIIIIIIJIJJIIJJJIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJIJJIIIIJIIIIIJIIJJJJIJIIIJJIJJIIIIIJIIJIJIIJJ(byte[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(int[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public IIIJIJJJIJJJIIJJJJJJIJJJIJIJJJIJIIJIIIJIJJIIIJJ(int IJJJJJJIJIIIJJIIIJIJIJJIJIIIJJIJJJIIJJJJJIIJIII)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJIJIIJJIJJJJIJIJIJIIIIJIJJJJIJIIIJJJIJJJIIJJIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(byte[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public byte[] JIJIIJIJIJIJIJIJIIJJJJIIIJIIJIJIJJIJJIIJIJJIJIJ()
	{
		return null;
	}

	public void IJJIJJJIJJIJIIIJIIIJJIJIJIIIJJIJIIIJIJIIIIIIIJI(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(short[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJIIJJIIJIJJIJIJJIIIIIIJIIIJJIJJJJJIJIIIIIIJIJJ(byte[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public IIIJIJJJIJJJIIJJJJJJIJJJIJIJJJIJIIJIIIJIJJIIIJJ()
	{
	}

	public byte[] IJJJIJJJIIJJJJJIIJJIIJJIJIJIJIJIIIJJIIJIJIJJIJJ()
	{
		return null;
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(short JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIIIIJJIIJIJJJIJJJIJIIJJJIJIIJIIIJIJJIIIJIIJII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}

	public void IJIJIIJIIJIJIJJJJIIJJJJJIIIJJJIIJJIJIJIJIJIIIII(Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJIJJIIIJJJIJIIJIJJJJJJIIJIIJJIIIJIJJIJIIIIIIJJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJJJIIJJIIIJIJJIJIJJJJIJJIJIJIJJIJJIJJJIIJIIJI()
	{
	}

	public void IIIJJJJJIIJJJIIJJIIIJJJIJIIIJIIJJIJJIIIIIJJJJJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIIIJJIIJIIJIJIIIJJJJIIIJIJJJJIIIJIJIJIJJIIIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
}
