using UnityEngine;

public class IIIJJJIIIJIJIIJJIIIIJJIJJIIIIJIJIJIJJJJIIIJJIJI : AndroidJavaProxy
{
	private IJJIIIJIJJIIJJJJIIJJJIIJJIJIIIJIIIIIIIJIIIJIJIJ IIJJJIJJIIJIIJJJIIIJJJJIJJIJIJJIIIIJJJIIJIIJJJJ;

	private void onInterstitialLoaded(bool isPrecache)
	{
	}

	private void JIJIJJIIIIJJIJIIJIIJIIIIIJJJIIJIJJIJIJIJJIJJIJI(bool isPrecache)
	{
	}

	private void onInterstitialClosed()
	{
	}

	private void onInterstitialExpired()
	{
	}

	private void IJJIIIIJJJIIJJJJIJJJIJIIIJJJIIJJIIIIJJJIIJJIJII()
	{
	}

	private void JIJIIIJJIJJJIIIJJJIJJIJIIIJJIJIJIIIIJJIIJJJJJIJ()
	{
	}

	private void onInterstitialClicked()
	{
	}

	private void IJJIJIIIIIJIIIIIIJIIJIIIJIJJIJIJJJJJIJIJIJIJJJI()
	{
	}

	private void JIIJIJJIIIIJIIJIIIJIJJIIJIIJIIIIIJJJIIIJJIIIJJI(bool isPrecache)
	{
	}

	private void IJIIJIJIJIJJIJIJIJJJIIIIIJJIJIJIJJJIJIJJIIJIJJJ()
	{
	}

	internal IIIJJJIIIJIJIIJJIIIIJJIJJIIIIJIJIJIJJJJIIIJJIJI(IJJIIIJIJJIIJJJJIIJJJIIJJIJIIIJIIIIIIIJIIIJIJIJ IIJJJIJJIIJIIJJJIIIJJJJIJJIJIJJIIIIJJJIIJIIJJJJ)
		: base((string)null)
	{
	}

	private void IJJJJIIJJJJJIIJIIJIJIJIIIIJIJIJIJIIJIIJJIJJJJJI()
	{
	}

	private void IIIJIJJIJJIIJIIIJJIJJIJJIJIJJJIJJJJIJJIIIIIIJJI(bool isPrecache)
	{
	}

	private void IJJIJIIIJIIIJIJIJIIJJJJIIJJIJJIIJIIIJIIJIJJIIII()
	{
	}

	private void IIIJIIIIJIIJJJIJJIJJIIJIIJIIJJJJJJJIJJIJIJIJIJJ()
	{
	}

	private void JJJJJJIIJIIJIIIJIJIIIIJIIJJJJIJJIIJIJIJJIIJJIIJ()
	{
	}

	private void onInterstitialShown()
	{
	}

	private void onInterstitialFailedToLoad()
	{
	}

	private void JIJIIIJJIIIJJIJJIIJIIIJIJIJIJJIIIIIJJIIIJJIJIJJ()
	{
	}

	private void JIJIIJIJIIJJJIIIIJIIJIIJJIIJIJJIJJIJJJJJIIJIIJI()
	{
	}

	private void IIJIIJJIIIIJJJJJJIIJIJJIJJIJJJIJJJIJIJIIIIJIIJJ()
	{
	}

	private void JIIJIJIJJIJJIIJJJIIIJJIJJJIJJIJIIJJJIJJIIJIJIII()
	{
	}

	private void IIIJIJJIIIIJJJIJJIJJJJJIIJJIIIJIJIIJJJJJIIJJJJJ()
	{
	}
}
