using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[Serializable]
[StructLayout((LayoutKind)0, Size = 8)]
public struct IIJIIJJIIIIIJJJIIIIIIJIIIJJJIIIJIIJIIJIJJIJJJJI : IEquatable<IIJIIJJIIIIIJJJIIIIIIJIIIJJJIIIJIIJIIJIJJIJJJJI>
{
	public byte JJIJIJIJIIJJIJJJJIJJJJIIIIIJJJIIJIJJJIJJIJIIJII;

	public byte IIIIIIJIJJIIJJJJJJJIIJIIIIJJIIJIIJJIIJJIIIIIJJJ;

	public bool IIIIJIJJJJIJIIJJIIIJIIJIJJJJIJJIJIIJJIJIJJJIIII;
	public static bool IIIIIJJIIJJIJIJIJIIIIIIIJIIJIJIJIJIJIJIJJIIJIJI(IIJIIJJIIIIIJJJIIIIIIJIIIJJJIIIJIIJIIJIJJIJJJJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return false;
	}

	public string IJJIIJIIJIIIJIJJIIIIJIJJIIIIJIJJIJJJIJIJJIJIIII()
	{
		return null;
	}

	public string IIIJIIIIIIJJJIJIIIJJIIJIJJIIJJJIIJJIIIJJJIIIJJJ()
	{
		return null;
	}
	public static implicit operator bool(IIJIIJJIIIIIJJJIIIIIIJIIIJJJIIIJIIJIIJIJJIJJJJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return false;
	}

	private bool IJIJIIJIIIIJIIJIJIIIJIJJJJJIJJIIIIIIIJJIIIIIIJI()
	{
		return false;
	}

	public override string ToString()
	{
		return null;
	}

	public void JJJIJIJIIIJJIJIIIIIIIJIJJIJJIIIJJIJIIIJJJJJJIJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJJIJJIIJJIIJIIJJIJJIJIIJIIJIIJJJIJJJIJJJJIIJJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public string JJJJIJJIIJJIIIIJJJIIJJIJIIJJJJIJJJJJIIJIJJIJIII()
	{
		return null;
	}

	public int IJIIJJJJIJIIJJJJIIIJIJJJJJIJIIIJIJJIJIIJJJIJIJI()
	{
		return 0;
	}

	private bool IIIJJJJIJIJIJJJIJJIJIJIJIIIIJIJJIIJIIJIIIJIJIIJ()
	{
		return false;
	}

	public int IIJJIJIIIIIIJIJJJJJIIJIIJJIIJIIJIJJIJJIIIIIIJIJ()
	{
		return 0;
	}

	public bool Equals(IIJIIJJIIIIIJJJIIIIIIJIIIJJJIIIJIIJIIJIJJIJJJJI JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}

	public void JIIIJJJJIIIIJJIJIIIJJJIIJJJIIJJJIJJIJIIIIIIIIIJ()
	{
	}

	private bool JJIIIJJJJJJIJJJJJJIIJIIIIJJJJIIJJIIJJJJJIJIJIII()
	{
		return false;
	}

	private bool IIJJIIJIJJIJIJJIIJIJIJJJJJJJJIJJIJIJJIIIJJJIJIJ()
	{
		return false;
	}
	public static IIJIIJJIIIIIJJJIIIIIIJIIIJJJIIIJIIJIIJIJJIJJJJI IJIJJIJJJJIIJIJJIIIIIIIJIIJJIIJIJIIJIIJIIIJJIJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}

	public override int GetHashCode()
	{
		return 0;
	}

	public void IJJIJJIIIJJJIIJIIJIIJIJJIJJIIJIIJJIJJIJJJJIJJIJ()
	{
	}

	private bool IIIIIIJJIIJIJJJIJIJJIJIJIIJJIIJIIJJJIIJJIIIIIII()
	{
		return false;
	}

	public bool JIIJIIJJIIIJJJIJJIJIJIIJIIJIIIJJIJIJJJIJJIJIJII(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}

	private IIJIIJJIIIIIJJJIIIIIIJIIIJJJIIIJIIJIIJIJJIJJJJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		JJIJIJIJIIJJIJJJJIJJJJIIIIIJJJIIJIJJJIJJIJIIJII = 0;
		IIIIIIJIJJIIJJJJJJJIIJIIIIJJIIJIIJJIIJJIIIIIJJJ = 0;
		IIIIJIJJJJIJIIJJIIIJIIJIJJJJIJJIJIIJJIJIJJJIIII = false;
	}

	public void JJIJJJIIJJIIJIIJIIJIIIIJIIJJJJJJIIJIIJIJJJIIJJJ()
	{
	}

	private bool IIJJJIJIJJIIIIIIJIJJJIIIJJIIIJJIIIIIIJIJJJIJIII()
	{
		return false;
	}

	public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}
	public static IIJIIJJIIIIIJJJIIIIIIJIIIJJJIIIJIIJIIJIJJIJJJJI IIJJJIIJIIJIIJJIIJIIJJJIJJIIIIJIJIIJJIJJJJJIIII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}

	public void JJIJIIIIIIJIJJIIIJJJJIIIIJJJIIIIIJJIJIIIIJJJJII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private bool JJIIIJIIIJIIJJIJJJJJJJJIJJJIIJJJJJJIIIIJJJIJJII()
	{
		return false;
	}
	public static implicit operator IIJIIJJIIIIIJJJIIIIIIJIIIJJJIIIJIIJIIJIJJIJJJJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}

	private bool IIIIIJIJJJJJIIJIIIIIIJIJIIIJJIJIIJIJIIIIJIIJJII()
	{
		return false;
	}
}
