public static class IIJIIJJIJJIIIIIIJJJIIIIJJJIIIJIIJIIJIIJIIJIJJII
{
	public static string JJIJIJJIJIJIIIIIIJJIJIJIIJIJIIJJJIIJIIIIIIIJJIJ(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return null;
	}
}
