using Firebase.Messaging;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public static class IIJIJJIIJJJIJIJJIIJJIIIIJIIJJIIJIIIJJIJJIJJIIIJ
{
	private sealed class IIIJIJIJJJIJIJIJJJJIJJJIIJIIIIIIJIJIIJJIJIIIIIJ
	{
		public int IIJJIJIJIJJIIJJIJJJIIIIIIIJJIIJIJJJJIIIJIJJJJJJ;

		public string JJJJIJIIIJJIJIIJJJIJIIIIJIJJIIIJIJIJJIIIJIJJIJJ;

		internal void JJIJIIIIIIJJJIIJIIJJIIJJJIIJJJIJJJJJJIJIJIIIIJI()
		{
		}

		internal void IJIJIIIJIIIJIIJJIJIIJIJJIIIJIJIJIJIJIIIIJIJJIJI()
		{
		}

		internal void IJJJIJJIIJJJJJJIJJIIIJIJJIIIIJJJIIIIIIIJIIJJIII()
		{
		}

		internal void JIJJIIJJIJIJJJJIJIJIJIIIIIIIIJJJJIJIJJIIJIJIJII()
		{
		}

		internal void JJIIJJIJJIJJIIJJIJJIJIIIIIIJIIIJIJIJJIIJJIJIJIJ()
		{
		}

		internal void JJJIJJJIIIJJIJJIJIIIJIIJJIIIJJIJIIIIJJIIIJJJIJI()
		{
		}

		internal void JJIJIIIJJIJJIJJIIIJIIJIIIJIIIJJIJJJJIJIJIIIIIII()
		{
		}

		internal void IJIIIIIJJJIIIJJJIJJIJIJJIIJIIIIIIJJJJIIJJJJIJJJ()
		{
		}

		internal void IIJJJIIIIJIIIIJJJJIIIJIIJIIIJIJIJIJJIIJIIIIIIJJ()
		{
		}

		internal void IIIJJJIJJIJIIJIIJIIJJIJJJJJJIJJJIIIIIIJJJJJIJIJ()
		{
		}

		internal void JJIIIIJIIJJIIJIJJIJJJIIIJIJIIJJJIIIJIIJJIIIJJIJ()
		{
		}

		internal void JIIIIJJIIJIJJJJIIIJIJJJIIIIJJJIJIIIJJIIIIJIJJJI()
		{
		}

		internal void JIIJIJJJJIIIJJJJJJJJIIJJJIJJJIJIJJIJJJIIIJJJJJJ()
		{
		}

		internal void IJIJJIIJJIIJIJIIJIJIJJIIIIJIJIIIJJIIJJIJIIJIIII()
		{
		}

		internal void JJIJIJJJJIIIJJJIIIJJIIJIJIJJJJJJIJIIIIIJIJIJJJJ()
		{
		}

		internal void IIJIJJJIIIJIJIJIJIJIIJIJJJJJIJIIIIIIIJIIIJIJIIJ()
		{
		}
	}

	public static string JIJJJIIIIJJJJJJJIJJJIJIJJIIJJIIJJIIIJIIIJJIJJJI;

	public static void Start()
	{
	}

	private static void IJIIIJIJJJIIJIJIJJJIIIJJJIIJIJJJJIIIIIIIJIIIJJJ(object JJIJJJJIJJIJJJJIJJIIIIJJJIIJJJJIJIJIIIIIJJIIIIJ, TokenReceivedEventArgs IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	private static void IIJJJJIIJJIIIIJIJIIIJIIIJJJJIIJJIIJJIIIJIJIJJJI(object JJIJJJJIJJIJJJJIJJIIIIJJJIIJJJJIJIJIIIIIJJIIIIJ, MessageReceivedEventArgs JJJJIJJJIJIJJJJJIIJIJJJIJJJIIIJJJJJJIIIIJIJJJII)
	{
	}
}
