using System;

public class IIJIIJJJIJIJIJJIJIJJIJJJJIIIJIIIJJIIIIJIIJJJIII
{
	public const int JIIJJJIIJJJIJIJJIIJJIIJIIJJIIIIJIIJJJIJJIIIIIJI = 0;

	public const int IIJJIIJJIJIJJIJJJIJIJJIJIIIIIJJJIJJIIJIJJIIIJJJ = -3;

	[Obsolete]
	public const int IIJIIIIJIIIIIIJJIJJIIIJIJJIIJJIIIJIJIIJJJJJJIJJ = -2;

	public const int JJJIJJIIIIJJJJIJJJJIJIJJJJIJIJIIJJIIIJJIJJIIJJI = -2;

	public const int IJJIJJJJIIJJIJIJJIJJIIIIJJIJIJJIIIIIIJJJIIJIIJI = -1;

	public const int IIJJJJJJIJJJIIIJJJJIJIJJIIJIJIJJIJJJIIIIIJJIJJI = 32767;

	public const int JIJJIJJJIJIIIJJIJIJIIJJJJIIJJJIIJJJIIIIJJJJIJIJ = 32766;

	public const int IIJJIIIIIJIJJIJIJJJJJIIJJIJIIJJIIIIIIIJJJIJIIJI = 32765;

	public const int IIIJIJIIJIJJJIIJIJIJJJJIJJJJJJIIIIIIIIJJJJIJJIJ = 32764;

	[Obsolete]
	public const int JIJIJIIIJJJIJIJIIJJJJIJJJIJJJIIIJJIIJJIIIJJIIJI = 32763;

	public const int IJJIIJJIIIIJIJIJIJJIIIJJIIJIIIJJIIIIJIIJIJIJJIJ = 32762;

	public const int JIIIIJJJJIIJJJIIJIJIIJJIIJJIJIJIJIIJIIIJJIIIJJJ = 32761;

	public const int IJJIIJJIJJIIIJIIIJJJJIJJIIJIJJIIIJJJIJJJJJJIJJJ = 32760;

	public const int IIJIJJJIIIIJIJIJIJIJJIIJIJJJIJJIJJJJIIIJJJJIJIJ = 32758;

	public const int JIIIIJJIJJJJIIJIIIIIIIIJJIJJIIJJIJIJJIIIJJIJJJI = 32757;

	public const int IJJIIIJJIJJIJIJJJJJIJJIJJJIIIJIJJIJJJJJIIJIIIJI = 32756;

	public const int JJIIIIIJIJJIJJJJIJJIIJJJJJJJIIJIJIJIJIJJIIIJIIJ = 32755;

	public const int JIIIJJIJIJIJIJIJIIJJJJIJIIJIIJIJIJJJJJIJIJIIIJJ = 32753;

	public const int IIJIJIJJIJIIJJIIJIIIIJJIJIJIJJIJJJJIIIIIJJIIJIJ = 32752;

	public const int JJIIJJIJJJJIJIIIJJJJIIIJIIIIIIJJIIJIJJJIJJIIJII = 32751;

	public const int JJIJIJIIIJIJIJIIIJIJIIJIIJJJJIJIIJJJIJJIIJJJIIJ = 32750;

	public const int IJIJJJJIJIIJJIJJJIJJIJIJJJJJIIJJIJJIIJIIIJJJIIJ = 32749;

	public const int IJJJIJJIIJIJIIIJIIIJIJIIJIIJJJIIJIJIIIJJIIJJIJJ = 32748;

	public const int IJJJJIIJIJJJIIIIIIIIJJJJIIJIIJJJJIJJJIIJIJJIIJI = 32747;

	public const int IJIJJIIIJIJJJIIIIIIJJIJIJJJJJJJIJIIIIIIIIIJJJII = 32746;

	public const int JIIJIIIIIIJJIIJIJIJJIIIIJIIIJIJJIIIJIIJJJIIIJIJ = 32745;

	public const int IJIIJIIIJJIJIIJJJIIJIIJIIJIIJJIIJJJIJJIIIIJIIII = 32744;

	public const int JJJJJIIIIIIJIIJJIIJJIIJJIIIJJIJJIIJJJJJJJIIJIIJ = 32742;

	public const int JIJJJIJIIJIJIIIJIJIJJJIJIIJIIIJJIIIJIJIJJIJJIIJ = 32741;
}
