using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using UnityEngine;

public static class IIJJJJJIIIJIJJJJIIIIIIJJJJJIIIIJJJJJIJIJIJIJIJJ
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JJJJIJIIIIJIIIIJJIIJJIJJJIJJJJJJIIIJIIIJIIJJJJI
	{
		Automatic = 0,
		Left = 1,
		Center = 2,
		Right = 3,
		Justified = 4
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JIJJJIJIJIJJJIIIIJJJJJIIIIIJJIJIIJJIIIIJIIIIJJI
	{
		None = 0,
		Normal = 1,
		Colored = 2,
		NoOutline = 3
	}

	public class IIIJIJIIIJJJJJIIJJIJJIJJJIJJJJIIJJIJIJJIIJJIIJI
	{
		public Vector2 JJIJJIIJIJIIJJIJJJIJJJJIJIIJIIIIIJJIIJIIJJIIIJJ;

		public Vector2 IIJIJJIJJJJIIIIJIIIJIJJJIIJJJIJIIJJIJIIIJJIIJJJ;

		public Vector2 JJJJJJJJIJIIIJJJIJIJIJJIIJJIJIIIIIJJIIJIJJIJJJJ;

		public Vector2 JIJJIIJJIIJIIJIIJIJIJJJIJJIJIJIJJIJJIIJJIJJJIJI;

		public Vector2 JJJIJJJIJIJJJJIIIIJJJJJJJJIJIIJJJJIIIIIJIIIIIII;

		public Vector2 IJJJJIJIJIIIJJJIJJIIJJJJJJIJJJJJIJJIJIJJIJJIJII;

		public float JJIIIJJIJIIJIJIJIJJIJIIJJJJIIJIJJJJIJJJJIJIJJII;

		public int JIIJIJJJIJIJIIJJJIJIIIIIIJJJIIIJJIIIIIIJJIIIJJJ;
	}

	public static JJIJJJJJIIJIIIIJIIJJJIIIIIJIIIJIJIJIIJJJIJJJIJI IJJIJIJIIJJIJJIIJIIIJIJJIIIJJJJJIJIIIIJIJJIJJJJ;

	public static Font JJJIJJJJJIJJJIIIJJJIIIIJIIIIIJIIJJIIJJJIIJIIJJI;

	public static IIIJIJIIIJJJJJIIJJIJJIJJJIJJJJIIJJIJIJJIIJJIIJI JJIJJIIJJIIIJJJIIIIIJIIJJJJJJIIJJJIJJIJJIIIIJJJ;

	public static int IIIJIIIJIJIJIIIIJJIIJJJJIIJJJIIJIIIIJIJJIIIIIJJ;

	public static float IJIJIIIIJIJIJIJJIJIJJJIJJJIJIJIIJIJJJIJIJJJJIII;

	public static float IJIJIJIIJIJJJIJIIJJJIJIJIJIIIIIJJIIIJIJJJIIJJJJ;

	public static FontStyle JJJIIJJIIIIIIIJIIJJJJIJJJIIJJIIIIJJIJIIIJJJJJII;

	public static JJJJIJIIIIJIIIIJJIIJJIJJJIJJJJJJIIIJIIIJIIJJJJI IJJJJJIJJJIJJJJIJJIJIJIIJJJJIJIJJJJIIJIIJIJIJJI;

	public static Color IIIJJJJJIIJIJJIIIJJIIIJIIIIIIIIIJJJJJIJIIIIIIII;

	public static int JIJIJJIIJIIIJIIJJIJIIIIJIIIJIIJJIJJIIJIIIIIJIIJ;

	public static int JIIJIIJJIIJJJIJJJJIIIIIIJIIJJIJJJJIJIIIIJIIJIJJ;

	public static int JJIJJJJJIJIIIIJJJJJJIJJIIJIJJJJJIIIIIJJIJIIIIIJ;

	public static int JJIIIIIIJJJJIJIJJJJJJIIIIJJIJJIJIJJJJIIJJIIJJIJ;

	public static int IIIIIJIJIJIJIJIJIIIJJJIIJJIIJIJJJIJIJIJIIJJJJIJ;

	public static bool IJIIIJJIIJJJJJJIJJIJIJJIIJJJJIIJJJJIIJJIIJIIIJI;

	public static Color IIJIIIJJIIJIJJIJJIIIIJIIIJIIJIJIJIIIIJJIIJIJIII;

	public static Color JIIIJIJIJJJJJJIJIJJJIIJJJJJIIJIJIJJJJJJIIIIJJIJ;

	public static bool JIIIJJJJJIJIJJIIIJIIIJIIIJJJIJIJIIIIIIIJJJIJIII;

	public static float IIIIJIJIIIIIJIIJJIIIJIIIJJIJJIJIJIIJJJIIIIJJIII;

	public static float IJIJIJJJJIIIJIJJJIJIJIIJJIJJIJJJJIJJIJJIJIJIJIJ;

	public static bool JJIIIJJIJJJIJJIIIJIIJJIIJIIJJIIJJJIIIIIIIIJJJJJ;

	public static JIJJJIJIJIJJJIIIIJJJJJIIIIIJJIJIIJJIIIIJIIIIJJI IIIJIIIJJJJIIJJIIIIJIIIJJJIIIIIJIIJIIIJIJIJIIJJ;

	public static int IIJIJIJJIIJJJIJIJIJIIJJJJIIJJIIIIIIIIIIIJJIIIII;

	public static float JIIIIIJIJJJJIJIJJIIIJJJIJIIJIIIIIIJJJJJJJIJIJJJ;

	public static float IJJIIJIJIJJIIJIIIJIIIIIJIIIIIIIJIIJIIIIJIJIIIII;

	public static float JJIIJIJIJIJJJIIJJJIJJIIIIJIJJJIJIJIJJJJJIJJIJJI;

	public static bool IIIIJIIIJIJIIJJJIIJJJIIJIIJJJIIJJJJIIJIIIJIIIIJ;

	private static Color JJIJJJIIJIJJJIJJIJIIIIJIIIIIJIIJIIJIJJJJIIIJIJJ;

	private static global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<Color> IJIIIJIJJJIJJJIJJIIJIJIIIJJIIJIJIJIJIJIJIJJIIII;

	private static float IJJIIJJIJJJJIIIIIIJJIJIIIIJJIJJIJIJIIIIIJJJJIII;

	private static CharacterInfo IJIJIJIIJIJJIJJIIIIJJIJIIIJJIIIIIJJJJJJJJJJIIII;

	private static global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<float> JJJJIJIIIJJIJJIJIIJIJJJJIJJIJJIJJJIIJJIIIJJIJJI;

	private static Color IJIJIJJJJIJIJIIIIJIIJIIJIIIJIIIJIIIIJIJJJIIIJJJ;

	private static Color IJJJIJJJJJJJIIJIIIJIIIJJIIIJJJJJJIJIJIIIJJJIJJI;

	private const float JJJIIIJIIJIJJIJIJJIJJJIJJIJIJJIIJIJIIIIJJJIIJIJ = 0.75f;

	private static float[] IJJIJIIJJIJIIIIJIJJIIJJJJJIIJIIIIJJJIJJIIIJJIII;

	public static bool IIJJJIIJJJJJIIJIJJJIIJIIIJJJIJJJJJIIJIJIJJIJIJI => IIJJIJIJJJIIJIIJIJIJIJIJJJJIJJIJJIJJIJIJIIIJIJI();

	public static bool IIJJIJIJJJIIJIIJIJIJIJIJJJJIJJIJJIJJIJIJIIIJIJI()
	{
		return false;
	}

	public static void IJIIIJIIIJJJJJJIJJJIJIIIIJIIIJJJJJJIJIJIJIJIIJI()
	{
	}

	public static void IJIIIJIIIJJJJJJIJJJIJIIIIJIIIJJJJJJIJIJIJIJIIJI(bool JJIIIIIJIJIIJJJJJJIIJJIIIIIJIJJJIJJJIJIJJJJIIJJ)
	{
	}

	public static void IIJIJJJIJIJJJJJJIIIJJIJJIJIJIIJIIIIIJJJJIJJJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static IJJIIIIJIJJJIJJJJIIIIJJJIJIJIIJJJIIIIIJJIJIJJII JJJJJIJIIJIIIIJIJIJJIIJIJJIIIJIIIJJJJIIJIJIJJIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, int JIIJIIIJJIJJIJJIIJIJJIIJIIIIJIIJIIIIIJIJJIJJIII)
	{
		return null;
	}

	public static float IIJJIJJIJJJIIIIIIJJIIIIIJJJJIIIJJJIJJIJIJJIJIJI(int JJIJIIJJIIJJIIIIIJJIJIIJJJJJJIJIJIIIJJJJJIIJIJI, int IJIIJIJJIJJJIJIIIIJJJIJIJJIIIIJIIJJJJJJJJIJIIJJ, float IJIJIIIIJIJIJIJJIJIJJJIJJJIJIJIIJIJJJIJIJJJJIII)
	{
		return 0f;
	}

	public static IIIJIJIIIJJJJJIIJJIJJIJJJIJJJJIIJJIJIJJIIJJIIJI IIJJIIJIJIIIIIJJJIIJIJJJJIJJIIJJIJIJIIJIIJJJIIJ(int JJIJIIJJIIJJIIIIIJJIJIIJJJJJJIJIJIIIJJJJJIIJIJI, int IJIIJIJJIJJJIJIIIIJJJIJIJJIIIIJIIJJJJJJJJIJIIJJ, float IJIJIIIIJIJIJIJJIJIJJJIJJJIJIJIIJIJJJIJIJJJJIII = 1f)
	{
		return null;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static float JJIIIJIIJJJJJIJJJIIIIJJJIIIJIIIJIJJIIIJJJJJIIJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return 0f;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static Color IJIIJIIIIIIJIIJJJJIIJIJJJIIJJIIJIJJJJIIJJJIIJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, int IJJIJIIIIJIJIJJIIIIIIIJIIIJJIIIIJIJIJJIJIJIJIJJ = 0)
	{
		return default;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static Color JIIIIIIIIJIJJJJIJJJJIIJJJJIIJIJJJIJIIIJJIIIIJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, int IJJIJIIIIJIJIJJIIIIIIIJIIIJJIIIIJIJIJJIJIJIJIJJ = 0)
	{
		return default;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static Color JJIIIIIIIIJIJJJIJJJIIIIIJIIIIIIJIIIIIJIIJJIJJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, int IJJIJIIIIJIJIJJIIIIIIIJIIIJJIIIIJIJIJJIJIJIJIJJ)
	{
		return default;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public static string JJJJIIIJJJJJIJIIJIIIIIIIIJIIJIIIJJIJIJJIJJJIIII(Color IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
	{
		return null;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static string JJJJIIIJJJJJIJIIJIIIIIIIIJIIJIIIJJIJIJJIJJJIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, Color IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
	{
		return null;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static string IIJIJJJIIJJJJIJJJJIIIIJJIJJJJJIIJIJIIIJIIJJJJIJ(float IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ)
	{
		return null;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public static string IIIIIIJJIJJJIIIJJIJJIJJJJIIIIIIJIJJIIIJIJJJIJII(Color IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
	{
		return null;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public static string JIIJIJIIIIJIJJIJIIJIIJJIJIJIJJIIIIIIIIIIIIIIIII(Color IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
	{
		return null;
	}

	public static bool JJJIJJJIJIJIJIIJIIJIJIIIJJIJIJJIJJIJIJIJJJIIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, ref int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return false;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static bool IIJIJJJJJJIIIJJJJIIIIIIIJJIJJIIIIJJIIIIJIJIJIJJ(char JJIJIIJJIIJJIIIIIJJIJIIJJJJJJIJIJIIIJJJJJIIJIJI)
	{
		return false;
	}

	public static bool JJJIJJJIJIJIJIIJIIJIJIIIJJIJIJJIJJIJIJIJJJIIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, ref int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<Color> JJJIJIIIIIIIIJIJJJIIIJJIJIJJIIJIJIJIJIJJIIJJJIJ, bool JJIIIJJIJJJIJJIIIJIIJJIIJIIJJIIJJJIIIIIIIIJJJJJ, ref int JIIIIIIJIIIIIJJIJIIIIJIJJJIJIIJJJJJIJJJJJIIJIII, ref bool JIIIJIIJIIIJIJIIJJIIIJJJIIJJJIJIJJIIIJJIIJJJJJI, ref bool IIJIJIJIIJJJJJIJIJIIJJJIIJJJJIIJIIIJIIJIIIJJJJJ, ref bool IJJIJIJIIIJIIIIJIJJIJJJIJIIIIJIIIIIIJIIIJIIJIIJ, ref bool IJIIIJJIIJIIJIIIIIJJJJJIIIJIJJJIIIIIJIIJIIIIIJJ, ref bool JJIJIJIJJIIIIIJJIIJIJIJJIIIIJIJJIJJJJIIJIJIIJJJ)
	{
		return false;
	}

	public static string IJIIJJJIIIIJJIIIJJJJJJJJJIJIJJIJIIJJJJJJJJIIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
		return null;
	}

	public static void IJIIIJIJIIIIJIIJJJJJJIIIJIIIIJIJJJIJJJJIJJIIIII(List<Vector3> IJJIIJJIIJIJIJIIIIIJIJIIJIJJJJIJIJIIJJIIIJJIJIJ, int IJIIIJJJJIJIJJJIJIIIJIJIJJIJIIIIIIJIJIIJIJJIIIJ, float JIJJJIJIJJJJIIJIJJIIJIJIIJJIJIIJJJIJIJJIIIIIJIJ, int IIJJIJIIIIIJJJJIJIJIJJIJJIIIJIJIIJJIIIJIIJJJJII = 4)
	{
	}

	public static int IJIIIJJJIIIIJIIIIIIIJJIIIIJIJJIIIIIIJIJIIJJIIJI(List<Vector3> IJJIIJJIIJIJIJIIIIIJIJIIJIJJJJIJIJIIJJIIIJJIJIJ, List<int> IJJJJIIIIJIJIJJIIIJJIJJJJJIJJJJIJIIIJIIJIIJIIJJ, Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
		return 0;
	}

	public static int JJIJJIIIJJIIJIJIIJIIIJJJIIJIJIJJJJJJIIIJJIIJIJJ(List<Vector3> IJJIIJJIIJIJIJIIIIIJIJIIJIJJJJIJIJIIJJIIIJJIJIJ, List<int> IJJJJIIIIJIJIJJIIIJJIJJJJJIJJJJIJIIIJIIJIIJIIJJ, Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
		return 0;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static bool IIJIJJJIJIIIJJIJIIIJJJIJIJIIJJJJIIIIIJIJIIJJIII(int JJIJIIJJIIJJIIIIIJJIJIIJJJJJJIJIJIIIJJJJJIIJIJI)
	{
		return false;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static void IIIIJJIIIJJJJIJJIIJJIJJJJIIJIJJJIJIIIIJJIJIJJJJ(ref StringBuilder IJJJIJJJIJJIIJJIJIJJJIIIJIJJJJJJIIJIJIIIJIJIJJI)
	{
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	private static void JJIJIIIIIIJJJIIJIIIIIIJIIIJIIJIIJIIJIJJIJJIJJJJ(ref StringBuilder IJJJIJJJIJJIIJJIJIJJJIIIJIJJJJJJIIJIJIIIJIJIJJI)
	{
	}

	public static Vector2 IIJIIIIJJIIIIJJIJJIJJJIIJIIIIJJJJJIIJIJJIIJJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
		return default;
	}

	public static int JIIJJJIJIIIJIIIIJIJIJJIIJJIJJIIJJIIJIIJJJJIJIJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
		return 0;
	}

	public static string JJJIIJIIJIJIIIJIIJJJJIIIJIIJIIJIJJIIJIIJJIJIIJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
		return null;
	}

	public static bool IIIJJJIJIJJIJIJJJJJJIIJIJIJJJJIIJJJJIJIJJIJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, out string JJJJJJJJJJJIJJJJJIJIIIJIJIIJJIIJIJIIIJJJJJJJIJJ, bool JJJIJIJIIIIJJJJIIJJJJJIIIJJJJIIIIJIIJJJIIIIJJJJ = false)
	{
		JJJJJJJJJJJIJJJJJIJIIIJIJIIJJIIJIJIIIJJJJJJJIJJ = null;
		return false;
	}

	public static bool IIIJJJIJIJJIJIJJJJJJIIJIJIJJJJIIJJJJIJIJJIJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, out string JJJJJJJJJJJIJJJJJIJIIIJIJIIJJIIJIJIIIJJJJJJJIJJ, bool IIIJIJJIJIJIJJJIJIIIJJJIIJJJJIJJIJJIJIIJJIJIJII, bool JJJIJIJIIIIJJJJIIJJJJJIIIJJJJIIIIJIIJJJIIIIJJJJ, bool IJJIIIIIIJJIIJJJIJIJIIJJJJJJIJIIIJJIIIJJJJIIJJJ = false)
	{
		JJJJJJJJJJJIJJJJJIJIIIJIJIIJJIIJIJIIIJJJJJJJIJJ = null;
		return false;
	}

	public static void IJIIJJJIJJIIJIIIJJIJIJIJJIIJIIIJJJIIIIJIIJIJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, List<Vector3> IJJIIJJIIJIJIJIIIIIJIJIIJIJJJJIJIJIIJJIIIJJIJIJ, List<Vector2> IJJJIIJJJIJIJIIIJJIJIJIJIJJJJIIJIJJIJIJIJJIIJJJ, List<Color> IJIJIJJJJJJJIIIIJJIIIIJJJIIJJJJIJIJJJJIIJIJIJII)
	{
	}

	public static void IJJIJIJIJIJIJIIJJJIJIJIIIJJJIJIIJJJIIJIIIJJIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, List<Vector3> IJJIIJJIIJIJIJIIIIIJIJIIJIJJJJIJIJIIJJIIIJJIJIJ, List<int> IJJJJIIIIJIJIJJIIIJJIJJJJJIJJJJIJIIIJIIJIIJIIJJ)
	{
	}

	public static void JIJJIJJIJJJJIJIJJIJIJJJIJIJJJIJIJIJIJJJIJJJJIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, List<Vector3> IJJIIJJIIJIJIJIIIIIJIJIIJIJJJJIJIJIIJJIIIJJIJIJ, List<int> IJJJJIIIIJIJIJJIIIJJIJJJJJIJJJJIJIIIJIIJIIJIIJJ)
	{
	}

	public static void IIJJJIJIJIIJIIJIIJIIJJJIIIJIIJIIIIIJJJJIJJJIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, int JIIIIJJJIIJIIIIIIIJIJIIJIIIJJJJIIJJJJIJJIIIJIJI, int IJIIJJIJIIJJJIJIIIJJIIJIIIIJIJJJJJJIJJIJJJIJJJJ, List<Vector3> JIIIJIIJJIIIJIIIJJIJJIIIIIJIJIIIJJJJJJJIIIIIIJJ, List<Vector3> IIIJJIJJJIIJJIJJIJJIIJIJIJIJJJIIJJIIIJJJIIJJJJJ)
	{
	}

	public static bool JJJJJIIIIJJJIJJJIIIIIJIIJIJJJJJJJJIJJIIJJIIIIJJ(ref string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, ref int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, string JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI, string JIIIIIJJJIIIIJJJJIJIJIIJIIJIIIIIIJIJIIJIIJJJJJI = null, string JJIIJJIIJJIIIIJJJJIJJJJIIJIIIIIIIIJIJIJJIJIIIJI = null)
	{
		return false;
	}

	public static bool IJIJJJIJIJJIJIJJIJJIJIIIIIIIIJJIIJIJJJJJJJJIIII(ref string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, ref int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, string JJJJJJIJJJJJIJIJJIJJJIIJJJJJIJIIIIJIJIIJJIJJJJJ, string JIJJJIJIJJJJIJIJIIIJIJJJIJJJIIIJJJIJIIJJJIIJIJJ, string JIIIIIJJJIIIIJJJJIJIJIIJIIJIIIIIIJIJIIJIIJJJJJI = null, string JJIIJJIIJJIIIIJJJJIJJJJIIJIIIIIIIIJIJIJJIJIIIJI = null)
	{
		return false;
	}

	public static void IJIJJIJJJJIJIIJJIJJJJIIJJIJIJJJJIJIJIIJIJJJIJJJ(ref string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIIIIIJJJIIIIJJJJIJIJIIJIIJIIIIIIJIJIIJIIJJJJJI = null, string JJIIJJIIJJIIIIJJJJIJJJJIIJIIIIIIIIJIJIJJIJIIIJI = null)
	{
	}
}
