using System.Runtime.CompilerServices;

public struct IIJJIIIJIIIJJJIJJJJJJJIIJIIJJIIIIJJJIIJIJIIIJIJ
{
	private readonly int IJJJJIJIIIJJIJJJIIJIJIJIJJIJJJJJIIJJIJIJIJJIIJI;

	public readonly JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJIJJJJIJJIJJJJIJJIIIIJJJIIJJJJIJIJIIIIIJJIIIIJ;

	public readonly PhotonView JIIJJJJIJJJIJIJJJJJJJIIJJIJIIJIJJIIJJIIJIJIJJIJ;

	public double JIJJIJIIJIIJIJJJIIIJIIJJJJIIIIJJJIIJJJIIJIJIJJJ => IJIIIJIJJJJJJIIIJJJIJJJIJJJIIJJJJIJIIIJJIJIIIJJ();

	public string JJIJJIIJJIIJIIIIJIIJJJJIJIJJIIIIJIJIJIJIJIIIIJJ()
	{
		return null;
	}

	public string JIIJIIJIJJJIIIJJIIIJJIIIJJIIIIIIJIJIJIIIJIJJIII()
	{
		return null;
	}
	public double IJJJIIIIJJJIJIJJJIJJIIIIIJJJJIIIIIIJJIIJJJIIJIJ()
	{
		return 0.0;
	}

	public string IIIJIIIIIIJJJIJIIIJJIIJIJJIIJJJIIJJIIIJJJIIIJJJ()
	{
		return null;
	}
	public double JJIJIJJIIIIIJJIJIJJJJIIJIIJJJJJJIIJJIIIJIJJJJII()
	{
		return 0.0;
	}

	public string IJJIIIIIJIJIJIJIIIJIJJIJIJIIJJIJJJJIJIJJIIIIIIJ()
	{
		return null;
	}
	public double JIIIJIJJJIIIJIJJJIIJIJIJIIJIIJIIJIJJIJIIIIIJIII()
	{
		return 0.0;
	}
	public double JIJJIJJIJJJIIIJIIJJIIJIJIIIJIJIIJIIJIJJJJJIJJII()
	{
		return 0.0;
	}

	public string JJJIIIIIIJIJJIJJIJIIIJJJIIIIJJJJIIIJIIIIIIIIIJI()
	{
		return null;
	}

	public override string ToString()
	{
		return null;
	}

	public IIJJIIIJIIIJJJIJJJJJJJIIJIIJJIIIIJJJIIJIJIIIJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII, int JIJJIJIIJIIJIJJJIIIJIIJJJJIIIIJJJIIJJJIIJIJIJJJ, PhotonView IIJIIIJIIIIJJJJIIIIIJIIIIIIIJIJIIJIJJIJIJJIJIII)
	{
		IJJJJIJIIIJJIJJJIIJIJIJIJJIJJJJJIIJJIJIJIJJIIJI = 0;
		JJIJJJJIJJIJJJJIJJIIIIJJJIIJJJJIJIJIIIIIJJIIIIJ = null;
		JIIJJJJIJJJIJIJJJJJJJIIJJIJIIJIJJIIJJIIJIJIJJIJ = null;
	}

	public string IIIJIIIIIIJJIJIIJJIIJJIIJJJJJJIJJIIJJIJJJIIIJJJ()
	{
		return null;
	}

	public string IIJJIJJJJJIIJIIJIJIIIJJIJJIIIJJJIIJJJIIIIIIIJII()
	{
		return null;
	}
	public double IJIJJIJJJJJJJIIIJJJJIJIIIJJIJJJJIIIIJJIJIIIIIIJ()
	{
		return 0.0;
	}

	public string JIJIIJIJJIIJIJJIIJIJIIIJJJJIJIJIIIJJJJJJIIIIIJI()
	{
		return null;
	}
	public double JIIJIIJIIJIIIIIIIIIIIIJJIIJJJJIJIIIIJIJIJJJIJIJ()
	{
		return 0.0;
	}

	public string JJJJIJJIIJJIIIIJJJIIJJIJIIJJJJIJJJJJIIJIJJIJIII()
	{
		return null;
	}
	public double IIJIJJJJJIIIIIJJIIJJIJJJJIJIJIIJJIIJIIIIIIJIIJI()
	{
		return 0.0;
	}
	public double IIJIJIIJIJJIIIIJIIJIIJJIIJJIJIJIJJJJJJJIJIJJJII()
	{
		return 0.0;
	}
	public double IJJIIIIJIIJIIIIJIJIIIIJJJJIJIJJJIIJJIJIIJJJJJII()
	{
		return 0.0;
	}

	public double IJIIIJIJJJJJJIIIJJJIJJJIJJJIIJJJJIJIIIJJIJIIIJJ()
	{
		return 0.0;
	}
	public double IJIJIIJIJIIJIIIJIIJJJIJJIIIIJJIIJIJIJJIIIJJJIII()
	{
		return 0.0;
	}
}
