using System.Collections;
using System.Collections.Generic;
using System.Text;

public static class IIJJJJJJIJJIIJJIIIJJIIJJJJJIIIIJIIIIIIJIIIIIJJI
{
	private enum IIIIIIJIIIIIIJJJJJJIJJJJIIIIJJIJIJIJIIIIIJJJJJJ
	{
		NONE = 0,
		CURLY_OPEN = 1,
		CURLY_CLOSE = 2,
		SQUARED_OPEN = 3,
		SQUARED_CLOSE = 4,
		COLON = 5,
		COMMA = 6,
		STRING = 7,
		NUMBER = 8,
		TRUE = 9,
		FALSE = 10,
		NULL = 11
	}

	private const int IJJIJJIJJIJIIJJIIJIJJJIJJJJJJIIJIJIIIJIJIIJJIJI = 2000;

	private static int IJIIIIIIIIIJIIJJJIIJJJIJIIJIJJJIIJJJIJJIJJJJIJI;

	private static string JJIIIIJJJIJIIJIIIJIJIIJIJJJIJIIJJJIJIIIIIJIJIJI;

	public static object IIIJJIIJJJJJIIJIIJIIJJIJJJJIIJIJJJJJJIJJIJIIIII(string IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ)
	{
		return null;
	}

	public static string JJIJIJJIJIJIIIIIIJJIJIJIIJIJIIJJJIIJIIIIIIIJJIJ(object IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ)
	{
		return null;
	}

	public static bool JJIIJJJIIJIIIIJIJIIJIIJJIIIJJIJIJIJIIJIJIIJIJII()
	{
		return false;
	}

	public static int IIJJJJJIJIJIJIJJIIIJIIJIJJJJJJIIJIJIJJJIJIIJIJI()
	{
		return 0;
	}

	public static string IIJJJJJJJIIJJJIIJJJIIIJIIJIJIJIIJJIIJIIIJIIIJJI()
	{
		return null;
	}

	private static Dictionary<string, object> IIIJJJJIIJIJJIJIJJIIIJIIIIJJIJIIJJIIIJJJIJJIIII(char[] IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ, ref int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}

	private static List<object> JJIIJJIJIIJIJJIIJIJIIIJIJJJIIJJIJIJIIJJJIJJJJII(char[] IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ, ref int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}

	private static object IIJJIJIJIJIJJJJJJIJJJIIJIJJIIIIIJIIJIIIJJIIIJII(char[] IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ, ref int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, ref bool IJJIIJIIJJIJIJJJJJIJJIJIJIIJIIIJIJIIIIJJJIJIIJI)
	{
		return null;
	}

	private static string JIIJIJJJJJJIIJIIJJJIJIIIJIJIJIJIJJIIIIIJIIIIJJI(char[] IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ, ref int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}

	private static object JJJIJJJIJIIJIJIJJIJJIIJJJIIIIIJJJIIIIJIJIIJJIJI(char[] IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ, ref int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}

	private static int IJJIJIIJIIIIIJJIIJJJIJIIJIJIJIIJIJIIJJIJIIJIJIJ(char[] IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ, int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return 0;
	}

	private static void IIJJJIJIIJIIJJJJIIJIJJIIJJIIIIJJJJJJIJIJJIJIJIJ(char[] IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ, ref int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}

	private static IIIIIIJIIIIIIJJJJJJIJJJJIIIIJJIJIJIJIIIIIJJJJJJ IIJJJJIJIJJIJJIJJIIJIJIIIJJJIIJJJJJJJIJJJIJIJJI(char[] IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ, int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return IIIIIIJIIIIIIJJJJJJIJJJJIIIIJJIJIJIJIIIIIJJJJJJ.NONE;
	}

	private static IIIIIIJIIIIIIJJJJJJIJJJJIIIIJJIJIJIJIIIIIJJJJJJ IJJIIIIIJIIJJJIJJJIIIIJIIIIJIJJJIIJJIIIIJIJJJIJ(char[] IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ, ref int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return IIIIIIJIIIIIIJJJJJJIJJJJIIIIJJIJIJIJIIIIIJJJJJJ.NONE;
	}

	private static bool IIJJJJJJJJJIJJJIJJIJJIIJJJJJJIJIIJIJJIJJIJIJIJI(IDictionary IJJIIJIJIIJJIIJJIIJJIJJJJIIIIJIIIJIJIIIIIJIJJIJ, StringBuilder IJJIJIJIIIJIIIIJJIIJIJIIJIIIJJJIJIJIJIIIJJIJJJJ)
	{
		return false;
	}

	private static bool JIJIIIJJIIJJJJJIIIIJIJIIIJJJJIIIJJJJIJIJIIIIJIJ(IList JJJIJJIIIIIIJJIJIIIIJJJIIJJIJIJIJJIJIJJJJJJJIII, StringBuilder IJJIJIJIIIJIIIIJJIIJIJIIJIIIJJJIJIJIJIIIJJIJJJJ)
	{
		return false;
	}

	private static bool IJIIJIJIIJJJJJIIIIIJJJIIIJJIJJIIIIIJIIIJJIIIJIJ(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, StringBuilder IJJIJIJIIIJIIIIJJIIJIJIIJIIIJJJIJIJIJIIIJJIJJJJ)
	{
		return false;
	}

	private static void JIIJIIIJJJJIJJIJIJIJJIIIIJIIJIIJJIJIIJJJJJIIJII(string JJIJIJJJJIJJIJJJJIJIIIIJJJJJJJJIIJIJIIJIJIJJIIJ, StringBuilder IJJIJIJIIIJIIIIJJIIJIJIIJIIIJJJIJIJIJIIIJJIJJJJ)
	{
	}

	private static void IJJJIIJJIIIIJIJIIIJIJIIJIJIIJJJJIIJIIJIJJIJJJII(double IIJJIJIIIJIJIIIIJJIIIJJIIIIIIJJJJIJIIJJJJJIJIIJ, StringBuilder IJJIJIJIIIJIIIIJJIIJIJIIJIIIJJJIJIJIJIIIJJIJJJJ)
	{
	}
}
