using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[Serializable]
[StructLayout((LayoutKind)0, Size = 12)]
public struct IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI : IEquatable<IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI>, IFormattable
{
	public int JJIJIJIJIIJJIJJJJIJJJJIIIIIJJJIIJIJJJIJJIJIIJII;

	public int IIIIIIJIJJIIJJJJJJJIIJIIIIJJIIJIIJJIIJJIIIIIJJJ;

	public bool IIIIJIJJJJIJIIJJIIIJIIJIJJJJIJJIJIIJJIJIJJJIIII;

	public override string ToString()
	{
		return null;
	}
	public static implicit operator IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI(IJJIIJJIIJIIIJIJIIJIJIIJIIJJJIJJIIIJIJJJJJIJJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}

	public bool Equals(IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}
	public static implicit operator IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}

	public string JJJIIIIIIJIJJIJJIJIIIJJJIIIIJJJJIIIJIIIIIIIIIJI(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
	{
		return null;
	}

	public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}
	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IJIJIJIIJIIIJIIIIIJIIJIJJJJIIIJIIIIIIIJJJJIJJII(IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}
	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IJIIJIJIJIIIIJJIIIIJJJJIJJJJJIIIIJIIIIJJIIIJJII(IJJIIJJIIJIIIJIJIIJIJIIJIIJJJIJJIIIJIJJJJJIJJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}
	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IIIIIIJJIJJIJIJIJJJIIIIIIIIJIIJIIJIJJJJJJJIIJJJ(IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}

	public static int IIJJJIJJIJIJIIJIIIJIIIJJIIJJJIJIIIIIIJJIJJJJJIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public void JJJIJIJIIIJJIJIIIIIIIJIJJIJJIIIJJIJIIIJJJJJJIJI(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public string IIJJJJIJIIJJIIIIIJJJJJJJIIJJIIIJIJJIJJJIIJJIIJI()
	{
		return null;
	}

	public int IJIJIIJIIIIJIIJIJIIIJIJJJJJIJJIIIIIIIJJIIIIIIJI()
	{
		return 0;
	}

	public string JIJJJIJJIJIIIIIJIIIJJJIIJIJIIIIJIJJIIJJIIIJIJJJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
	{
		return null;
	}

	public string JIIIJJJJIIJIIJJIIJIJJIIJJIIJIIJJIJJIJIJIIIJJIIJ()
	{
		return null;
	}

	public string ToString(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
	{
		return null;
	}
	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JJIJIJIJJJJIIIJJJIJJJJJIJJJJJIIIJJJIIJIJJJJIIJJ(IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}
	public static int IIJJJIIJIIJIIJJIIJIIJJJIJJIIIIJIJIIJJIJJJJJIIII(IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return 0;
	}

	private IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		JJIJIJIJIIJJIJJJJIJJJJIIIIIJJJIIJIJJJIJJIJIIJII = 0;
		IIIIIIJIJJIIJJJJJJJIIJIIIIJJIIJIIJJIIJJIIIIIJJJ = 0;
		IIIIJIJJJJIJIIJJIIIJIIJIJJJJIJJIJIIJJIJIJJJIIII = false;
	}

	public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
	{
		return null;
	}
	public static implicit operator IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII(IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}
	public static implicit operator int(IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return 0;
	}

	public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
	{
		return null;
	}

	public int IJIJJJIJJJIJIIIIJJIJJIJJJIIIJJJJIJIJJJIIIIIIJJI()
	{
		return 0;
	}
	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IIIJJJIIIJJJIIJJJIIIJJJJJIJJJJIJJJIJJJJJJIIIJJI(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}

	public int JJIIIJIJJJIIIJIIJIIIIIIJIJJJJIJJJIIIIJJJIJIJIIJ()
	{
		return 0;
	}

	public override int GetHashCode()
	{
		return 0;
	}

	public void JJIJJJIIJJIIJIIJIIJIIIIJIIJJJJJJIIJIIJIJJJIIJJJ()
	{
	}

	public string IJJJIIIIIJJIIJJJJIJIIIJIJIJJIJIJJJIJJJIJIIJIIIJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
	{
		return null;
	}

	public static int JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public static int JIJIIJJIJIIIJJIIIIJIJJJIJJIJIIJJIJJIIJJIJJIJIII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public string JIIJIIJIJJJIIIJJIIIJJIIIJJIIIIIIJIJIJIIIJIJJIII(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
	{
		return null;
	}

	public static int JJJIJJIJJJIIJJJIJJIJIJIJJIIJIIIJJIIJIJJJJJJIJJI(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public int IIIIIJIJJJJJIIJIIIIIIJIJIIIJJIJIIJIJIIIIJIIJJII()
	{
		return 0;
	}

	public string IJJJIIIIJJIJIIJIJIJJIIJJJJJIIIIJIIIIJIIJJJIIJJJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
	{
		return null;
	}
}
