using System;

public class IIJJJJJJJJIJJJIIJIIJJIJIJJIJJJJIIIIIJJJJIIJIIII : Attribute
{
	public string[] IIIJJJIIIJJIIIIJIIJJIIJIIIJIJJJIJIIIIJIJIJJJIIJ;

	public IIJJJJJJJJIJJJIIJIIJJIJIJJIJJJJIIIIIJJJJIIJIIII(params string[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
}
