using UnityEngine;

public static class IIJJIIJIIJIJIJIIJJJJJJJIIJIIJJIIIJJIJJJIIIIIIIJ
{
	private static IJIIIJIIJJJJJJIJJJIIJJJIIIIIIJIJIJJJJIIJJIIJIII IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ;

	private static bool IJIIJIIJJJJJIJJIIIJIJIIIIJJJIJIIIJJIIIIIJJJJJJJ;

	private static string IJJJJIJIJJIIIIIJJJIJJIIJJJJIIIIJJIJIIIIIIIJIIIJ;

	private static bool JJJJJIJJIIIIIJIIIJIIIIJIIJJJIJJJIJJIJJIJIJJJIII;

	private static IJIIIJIIJJJJJJIJJJIIJJJIIIIIIJIJIJJJJIIJJIIJIII IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII => IIJIIIJJIIJJIJJIJJIIJIIIJIJIJIIIJJIJJJJIIJJJJJJ();

	private static IJIIIJIIJJJJJJIJJJIIJJJIIIIIIJIJIJJJJIIJJIIJIII IIJIIIJJIIJJIJJIJJIIJIIIJIJIJIIIJJIJJJJIIJJJJJJ()
	{
		return null;
	}

	private static void IIIJJIJJJJIJIIJIIIIIIIIIJJIIJJIJJJIIIJIJJJJIJIJ()
	{
	}

	public static void JJIJIIIIIJJIJJJIJIJIIIJJJJIJIJJJJJIIIIJJIJJIIJJ()
	{
	}

	public static bool JIIIJJJIJJIJIJJIJIJJJIIJIJIJIIJJJJIIJJJIJIJIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return false;
	}

	public static void JJJIIIIJIIIIIJJJJJIIIJJIJJJIIIJIJJIJIJIJIIIIJJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
	}

	public static int JIJIIIJIIIJJJIIJJIIIJJIIJJIIJJIIJJIJJJJIJJJIIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public static int JIJIIIJIIIJJJIIJJIIIJJIIJJIIJJIIJJIJJJJIJJJIIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, int IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return 0;
	}

	public static void JIIIIIIIIIJJJJJJIJJJJJJIJJJIJJJIJJJIIJIJIIJIIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static float JJIJJJIJIIJJJIIJIIIJIIJIJJIJIIIJIJIJJJIIJJJIIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0f;
	}

	public static float JJIJJJIJIIJJJIIJIIIJIIJIJJIJIIIJIJIJJJIIJJJIIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, float IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return 0f;
	}

	public static void JIJIIIJJJIIJIIJJIIIJIJJJIIIIIIIIIJIJJJJJJIJIJJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static bool IJIJIJJJJJJJIIIJJJIIIJJIJIIJJIJJJJIJJJJJIIIIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return false;
	}

	public static bool IJIJIJJJJJJJIIIJJJIIIJJIJIIJJIJJJJIJJJJJIIIIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, bool IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return false;
	}

	public static void JJIJIIJIIIJIIIJIIIJJIJJIJIIIIJJJJJIIJIIIJIIJJJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static string IIJJIIJIIIJJIIIJJJIIIJIIIJIJJIIJIJIIIJIIIJIJJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public static string IIJJIIJIIIJJIIIJJJIIIJIIIJIJJIIJIJIIIJIIIJIJJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return null;
	}

	public static void IJIIJJJJJJIIJIIIIIJIIJIIIJIJIIJIJJIJJJJIIJJIIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static Vector3 JIIJIIJJIJIIIJJIJIIIIIIJJIJJIJIJIJJIIIIIJIIIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return default;
	}

	public static Vector3 JIIJIIJJIJIIIJJIJIIIIIIJJIJJIJIJIJJIIIIIJIIIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Vector3 IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return default;
	}

	public static void IJJJIIJIJJJJJIIIJIIIIJJJIJIJJIIIJIJJIIIIIJIJIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static Vector2 IJIJJIIJIIJJIJIJIIJJIJIIJIIJIJIIJIJJIJIJIIJJIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return default;
	}

	public static Vector2 IJIJJIIJIIJJIJIJIIJJIJIIJIIJIJIIJIJJIJIJIIJJIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Vector2 IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return default;
	}

	public static void JJIIIJJJIJIIIJIIIJIJIJIJIJIIIJIIIJIJIJJIIIIIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static Rect JIJIIIJIJIIJJJIIIIJIJIJJJJJIIIIIJJIIIJJJIJJIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return default;
	}

	public static Rect JIJIIIJIJIIJJJIIIIJIJIJJJJJIIIIIJJIIIJJJIJJIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Rect IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return default;
	}

	public static void IIIJIJIIIJIIJJIJIJIJJIIJJJJIIJIIJIJIJJJJIJJJJJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Rect JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static Color IIJIJIJIJIIIIIIIIJJJIJJJIJIIIIJJJJIIJIJJJIJJJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return default;
	}

	public static Color IIJIJIJIJIIIIIIIIJJJIJJJIJIIIIJJJJIIJIJJJIJJJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Color IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return default;
	}

	public static void IJJJJIJIJIJIIJJJJJIIJJJJJJIJIJIIJIIJJJJJJJJJIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Color JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
}
