using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

[Serializable]
public class IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII
{
	public JJJJIJJJJJIIJJJJJIIIIJIIJIIIIJIIJJIJJIIJJIIIJIJ IIJIIIJJJJJIIIJJIIIJJJJJJJIIJJIIIIIIIIJIJJJIIIJ;

	public string IIJJIJIIJIJJIIJIJJIIJJIJJIIIJIJJJJJJJJIJIIIIIJJ;

	public string IJJJJJIIIIIJIJJJJJIJIJIJJJIIIJIJJIJJJIJIJJJIIII;

	public TextAsset IIJIJJJJJIIIIIIJJIJJJJJIJJIJIJJJIJIJIIIJJJIJIJJ;

	public JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI JJJIJJJIJIJJIIJJJIIJIJIIJJJJJJIJIJIIJIJIIIIIJIJ;

	public List<int> IIIIJIIJIJIJJJJIIJJIJJIIIIIJJJJIJIIIJIIJIIJIIJJ;

	[NonSerialized]
	protected bool JJJIJJJIIIIIJJIIIJJJIIIIIIJJIJIIIJJJJIIJJJIJIJJ;

	[NonSerialized]
	protected List<IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII> JIIIJIIIJJIJIIIJIJIIIJJIJJJIJIJIIJJJIIJJJJIIJII;

	public bool JJJJIIIJJJIIIJIIIIIJIJIJJJJIJJJIIJIJIJJJJJIIJJI
	{
		get
		{
			return JJJJJIJIIJIJIJIIIIIJJJIJJIJJIIJIIIJJJIJJIJIIIJI();
		}
		set
		{
			JIJIJIJJJIJJJJIJJIIJIJIJJJJJIJIIIJJIIIIJJIJIJJI(value);
		}
	}

	public bool JJIIJIJIJIIJIJIJJJIJIJIJJIJJJIJJJIIJIIJJJIIJIJI => IJIIIIIIJIJIJIIIIIIJJJJIIIIIJIIJJIIJIIJJIJIIIII();

	public int IJJIIJIJJJJJIIJIIIJIJIJJJIJJIIJIIJIJIJJIIIJJJIJ => JIIIJIIIJJIIIIIJIJJJJJIJJIJJIJIIJIIJIIJIIIJIJII();

	protected List<IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII> IJJIIJIIJJJJJJIJIJIIIJIJJJJJJJIIJIIJIIJIJJIIIII => JJIJJJIIIIJJJIJIJIJJIIJIJIIJJIJJJIJJJIJIJIJJIJJ();

	public void JIJIIIIIIJJJIJIJIJJJJIIJJJIIIJJIJJIIJJIIJIJIJII(IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII JJIIJIIJJJIIIIIIJJJIJJIIIJIIIJJIJJIJJIIIJIJIIII)
	{
	}
	public bool IIJIIJJJIJIJIJIJIJJIIIIIJIJIJJJIJJJIJJJJJJJJJII()
	{
		return false;
	}

	public void JIJIJIJJJIJJJJIJJIIJIJIJJJJJIJIIIJJIIIIJJIJIJJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	protected List<IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII> JIJJIJIIJJJJIIIJJJJJJIJIJJIIIIJIJIIJJIIIJJIIIJI()
	{
		return null;
	}
	protected List<IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII> JIJJJJJJIJIJIJJIJIJJJIIIJJIJJJIIJJJJIJIJJIIIJJJ()
	{
		return null;
	}
	public bool JIJIIJIJJJJIJIIIIJIIIIJIJJJIIIIJIJIIIJIIJIJIJJI()
	{
		return false;
	}

	public bool JJJJJIJIIJIJIJIIIIIJJJIJJIJJIIJIIIJJJIJJIJIIIJI()
	{
		return false;
	}
	public bool IJIIJJJJIJIIJJJJJJJIIJIJJJIIJIJJIJJIIJJJJJIJJIJ()
	{
		return false;
	}

	public int JIIIJIIIJJIIIIIJIJJJJJIJJIJJIJIIJIIJIIJIIIJIJII()
	{
		return 0;
	}
	public int JJJJIJIIIJJJIIJJJIJIIIJJJJIJJJJIJIJJJIJJJJJIJIJ()
	{
		return 0;
	}
	public void IIJJJJJIJIJIIJIJJIJJIIJIJIIIJIIJJIIJJIIIIIJIJJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected List<IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII> JJIJJJIIIIJJJIJIJIJJIIJIJIIJJIJJJIJJJIJIJIJJIJJ()
	{
		return null;
	}

	public IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII(string JIIIIJIIJIIIJJIJIJIJIJIJIIJJIJJJIJIJIIIJJIIJJIJ, string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ = "Untitled", string IJJJJIJIJJIIIIIJJJIJJIIJJJJIIIIJJIJIIIIIIIJIIIJ = null, TextAsset JIJIJJJJIJJIJIJIJIJJIIJIJJJIJIIJIIJJIIJIIIJJIIJ = null)
	{
	}

	public void JJJIIJIIIIJJIJJIIJIJIIJIJJJJJJIIJJIJIIJJIIIJJJI(IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII JJIIJIIJJJIIIIIIJJJIJJIIIJIIIJJIJJIJJIIIJIJIIII)
	{
	}
	public void IJJIIIJIJJIIJJJJJIIJIIIJJJJJJIJIIIIJJJJJJIIJIJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public int IJIJIJJIIJJJIIIIJJIIJIJIJJIIJJJIJJJJIIIJJIJIIII()
	{
		return 0;
	}

	public void JIJJIIIJJIIJIJIIJJIJIJIJIJJIIIJIJIJIJIJIIJJJJJJ(IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII JJIIJIIJJJIIIIIIJJJIJJIIIJIIIJJIJJIJJIIIJIJIIII)
	{
	}
	protected List<IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII> IIJIJJJJIIIJIJIIIIIIJJIJIIIIJIIIIIIIIJIJJIIJIIJ()
	{
		return null;
	}
	public bool JJIIIIIIJIIJJJIJIJIIIJIJIIIIJIIIIIIJJIJJIJIIJII()
	{
		return false;
	}
	public bool JJIJJJIJJJIIJJIIIIJJJIJJJIJIIJJIIJJJIIIJJIJIJJI()
	{
		return false;
	}

	public bool IJIIIIIIJIJIJIIIIIIJJJJIIIIIJIIJJIIJIIJJIJIIIII()
	{
		return false;
	}

	public void IJIIIIIIJJJJIJJIJIJIJIJIIJJIJIJJJIJJIIIJJJJIJJI(IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII JJIIJIIJJJIIIIIIJJJIJJIIIJIIIJJIJJIJJIIIJIJIIII)
	{
	}

	public void JJJJJJJJIIJIJIIJIIJIIIIIIIIJIJJJIIIIJIJIIJJJJJJ(IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII JJIIJIIJJJIIIIIIJJJIJJIIIJIIIJJIJJIJJIIIJIJIIII)
	{
	}
}
