using System;
using BestHTTP;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class IJIIJJIIIJIIJJJJJJIJIIJIJJIJIIJJIIJJJJJIIJJIIJJ
{
	private sealed class JIIIIJJJIJJJIIJIJIJIIJJIJIJIIJIIIIIJIIIIIJIIJIJ
	{
		public int IIIJJIJIIJJJJIIIJIIJIIIIIIIJJIIJIJJIJIIIJIIIIJJ;

		public Action IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI;

		internal void JIJIJIJJIIJJIJIJJJIJJIIJIIIJIJIJIJIIIIIIIJJIIII()
		{
		}

		internal void IIJIIJJJJJJJIJIJIIIIIIIJIJIJIJJJJJIIIIIJJJJIJJI()
		{
		}

		internal void IIJJIJIIIJJJIIJIIJIJJJIJIIIJIIIJIIIJIJJJJJJJIIJ()
		{
		}

		internal void IIIJIIJJJIJIJJJJIIIJIJJIIIIIJIIJJIIIJJIIIIIIJII()
		{
		}

		internal void JIIJJJIIIJIJJJJJJIJJJIJIIJIIJIIIIIJJJJIJIJIIJIJ()
		{
		}

		internal void JJIIIJIIIIIJIJIJIJIJJJJIJJJJIIJIIIIIIJIJJJJIJJI()
		{
		}

		internal void JIJIJIJJIJJIJJIIIJJIJIJJIJIIIIIIIIIJJJIIJIIJIIJ()
		{
		}

		internal void JIJIIJJIIIIJIIJJJJJJJJJJJJIIJJIIIIIIIIIIJIJJJJI()
		{
		}

		internal void IIJJIIIJJIJIJJJJJJIJJJJJJJIJJIJIIIJIIIJIJIJIJJI()
		{
		}

		internal void JIIJIJJJJIIIIJIJJIIIIJJIIJIIIIIIIIIJIIIJJJIJJJJ()
		{
		}

		internal void IJIJJJIJIIIJIJIJJIJJIJJIJIIIIJJJJJIJJIJJJJIJJII()
		{
		}

		internal void JJJIIJIJIJJJIIJJIIJIIJIIJJJIJIIIJIIJJJJJJIJJJJI()
		{
		}

		internal void IJJIIJIIIJJIIIJJJIJJJJJJIIIJJJIJJIIIIJJIJIJJIII()
		{
		}

		internal void JJIIJJJJJIIJIJJJJIJJIIIJIJJIJIIJIJJJJJJJJJIJJIJ()
		{
		}

		internal void JIJJIIJIIIJIIJIJIIJJJJJIJJIJIIJIJIIJIIIJIIIJJJJ()
		{
		}

		internal void JJIJIJIJJIIJJJIIIIIIIJIJJIIIIIJJIIJJJIJJIJIIIIJ()
		{
		}

		internal void JJIJIJIJJIJIJJIIIIJIIIJIJJJJJJIJJJIIJJIJIJJJJIJ()
		{
		}

		internal void IJIIJIIIIJJIJJJIJJJIIJJJIIIJJJJIIIJJIIIIJIJIJJJ()
		{
		}
	}

	private sealed class IJJJJJIJJIJIIJIIIJIJJIJJJJJIIJIIIIIJJJIJJIJIIIJ
	{
		public WWW IIJIJIJIIIJIJJIJJJIJJIIIJJJJIJJIIJJJJJJJIIJIIJI;

		public JIIIIJJJIJJJIIJIJIJIIJJIJIJIIJIIIIIJIIIIIJIIJIJ IJJIJIIIIJIJIJJJJJIIJIIJJIIIIIIJIIIIJJIIIIIJIII;

		internal void JJIJIIIJJIIIIJIIIIIIIJJJIIIIJIIIJIIIJIIIJJJJJIJ()
		{
		}

		internal void JJJJIJJJIJJJIIJIIJJIJJIIIIIJJIJJJIIIIJIJJJJIIJJ()
		{
		}

		internal void JJIJIJIJJIJIIJJJIIJIJJIIIJIIIIIIJJJIIJIJJJIJJIJ()
		{
		}

		internal void IJIIJIJJJJIJJIJJJIIJJIIIIJJJJJIJIJIIJJJJJJJIIJI()
		{
		}

		internal void JJIJJIJIJIJIIJJIIJIJJJIJIJJIIIIIJJIIIIJJIIJJIJJ()
		{
		}

		internal void JIIIIIJIJJIIJIJJJJJIIJJJIIJIIJIJJIIIIIJJJIIIJII()
		{
		}

		internal void JIJJIJJJIIIIJIJIIJJJIIIIJIJIIJJJJJJIIJJIIIJIIII()
		{
		}

		internal void JIIJJJIIJJJIJJIJJIIJJIJIIJIIJIJIIIJIJIJIJIJJIII()
		{
		}

		internal void IIJJJJIJJJJIJJIJJJIJJJIJJIIJIIIIIJIJJIJJIIJIIIJ()
		{
		}

		internal void JJJJIIIIIJIJIIJJJJIJIIIIJIJIIJIIJJIIIJJJJIIIIIJ()
		{
		}

		internal void IIIIJJJIIJJIIIIIJJIIJJJJIJIIIIJIIIJJIIIIJJJIIII()
		{
		}

		internal void IJIIJIIJJJIIIJIJIJJJIJJJJJJJJIIJJIIJJJIJIIIIIIJ()
		{
		}

		internal void JIJJJIJJIJJIIIJIIIJJJIIJIJJJJJIJJJJJJJIJIIJIIIJ()
		{
		}

		internal void IIIIJJJIIJIJJJJJJJJIJJIJIIJIJJIJIIIIIJIJIJJJJIJ()
		{
		}

		internal void JJJJJJJJJIJJIIJIJJIIIIIIJJIIJJJIJJJJIJJIJJIJIJJ()
		{
		}

		internal void IJIJJJJIJIJIJIJJIIJJJJIJIIJJIJJJJJJIIIIIIJIJIIJ()
		{
		}
	}

	public static JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ JJJJIJIIIJJIJIIJJJIJIIIIJIJJIIIJIJIJJIIIJIJJIJJ;

	public static Action JJJIJJIIJJIIIJIJJIJJJJJJJIIJJJIIJIJJJIIJIJIIJJJ;

	private static void IJJIIIJJJJIIJIJIIJJIIJIIIIJIJJJJIIIIIIJIIJIIJJJ(HTTPRequest JJIIIIIJIJIIJJJJJJIIJJIIIIIJIJJJIJJJIJIJJJJIIJJ, long JJIJJJIJIJJJIJIIJIJIIJIIIJIJJIJJJIIIIIIIIIJIIIJ, long IIIJJJIJIJJJJIJJIIIJJJIIIIJIJJIJJIIJJJJIJIJIIII)
	{
	}

	public static void IJJIIIIIIJIJIJIIJIIIJJJIJJJIIIJIJIIIJJIJJJJIJJJ()
	{
	}

	public static void IIIIIIJJIJIIIIIJIJJIJIIIJJIIIIJJJJIJIIIIIIJJIII()
	{
	}

	private static void IJIJJJIJIIJIIJIIJIJJIIIIJIIIJIJJIIIIIJJJIIIJJJI(Action IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
	}

	private static void IIJIJJJIJIJIIIIJJIJIIJIJIJJIJIJJJIJIJJIIIJIJJII(Action IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
	}

	private static void IIJIJIJIJIJIIJIIIIJJJIIJJIIJIIIJIIIIJIIIJIJIIIJ()
	{
	}

	private static void IJIIJJIIIJJIIIIJIIIJIIJJJJIIIJJIJJIJIJIJJIJIJJJ(HTTPRequest JJIIIIIJIJIIJJJJJJIIJJIIIIIJIJJJIJJJIJIJJJJIIJJ, long JJIJJJIJIJJJIJIIJIJIIJIIIJIJJIJJJIIIIIIIIIJIIIJ, long IIIJJJIJIJJJJIJJIIIJJJIIIIJIJJIJJIIJJJJIJIJIIII)
	{
	}

	private static void IIJJJIJJIJIJJJJJIIIIIIJJJIIJJIIJJJIIIJIIJJJJIJJ()
	{
	}

	private static void JIJJJIIIJJIJJIJIJIJIIJIIJJJIJIJJIIIIIIJJIJJIJII(HTTPRequest JJIIIIIJIJIIJJJJJJIIJJIIIIIJIJJJIJJJIJIJJJJIIJJ, long JJIJJJIJIJJJIJIIJIJIIJIIIJIJJIJJJIIIIIIIIIJIIIJ, long IIIJJJIJIJJJJIJJIIIJJJIIIIJIJJIJJIIJJJJIJIJIIII)
	{
	}

	private static void IJJJJJJIIJIJIJJJIIJIJIIIIIIJIIJIIIIIIIJIIIIIIIJ(Action IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
	}

	public static void IIIIIIJJIJIIIIIJIJJIJIIIJJIIIIJJJJIJIIIIIIJJIII(bool JIIIIJJJIIJIJJJIIIIIJIIJIJJIJIIJIJJJIJJIIIIIJJI)
	{
	}

	public static void JJIIJJJIJJIJIIIIIJIIJJJIJJIIJJJIIIIJIIIJIJJIIIJ()
	{
	}

	public static void IIIIIJIJIJIJJIIJJJIJJIJJIIIIJIIJJIJIJJIJIIJJJII(bool JIIIIJJJIIJIJJJIIIIIJIIJIJJIJIIJIJJJIJJIIIIIJJI)
	{
	}

	private static void IJIIIJJJIIJIJJIIIIIJIIIIIIIJJIIIJIJIIIJJJJIJIII()
	{
	}

	public static void JJJIIJIIIIIIIJIIJIIIIIIJJJJJIIIJIJJIIIIIJIIIIJJ()
	{
	}

	public static void JJJJIIJJIJIIIIJIIIIJJJIIJJJJJIJJIIIJJIIJIJIIJIJ()
	{
	}

	public static void JJIIIIIJJJJJIJIJJIJJJIIJJJJIJJJIIJIIIJJJJIJIJJJ()
	{
	}

	public static void JIJJIJJJJJIJIJIIIJIIJIIJIJJIJIJJJIJIIJIJJJJJJJJ()
	{
	}

	public static void IIJJJIIJJJIIJJIIJJIJJJJIJIIIJJJIIJJJJJJIJJJJIIJ()
	{
	}

	private static void JIIJJIJIIJJJIIIIJIIIJJJJIIIIJIIJJIIJIIJIIIJIJIJ()
	{
	}
}
