using System;
using UnityEngine;

public static class IJIIIIIIJIJIJJIJIIIJJJIJIIIIJIJIIJJJIIJJJIJIJIJ
{
	internal enum JJIIIJJJJIJJIIJIJIIIIIIIJIIJJIIIJJJIJIIJJJJIJII : byte
	{
		Unknown = 0,
		Int = 5,
		UInt = 10,
		String = 15,
		Float = 20,
		Double = 25,
		Long = 30,
		Bool = 35,
		ByteArray = 40,
		Vector2 = 45,
		Vector3 = 50,
		Quaternion = 55,
		Color = 60,
		Rect = 65
	}

	public enum JIJJIIIIIJIIJIIJIJIJJJJJJJIIIIJJJIJIJJIJJIIIIII : byte
	{
		None = 0,
		Soft = 1,
		Strict = 2
	}

	private const byte JJJJIIJIIIJJIIJIJJJIIIJJIIIIIIJJIJJIJJIJJIIJJJJ = 2;

	private const string JJIJJJJIIIIIIJJIIIJIJJIJJIJIJIIJJIIJJJJJJIJJJJJ = "{not_found}";

	private const string IIIJIJJJJIIIIIIIIIJIIIIJIJIJJIJJIIJJIJJIJJJIJJJ = "|";

	private static bool IJIIIIIIIIJIIIJIJIJIJIIIJIIIIIIJIJJJIJIJJJJJIJJ;

	private static string JJIJIJIJIIJJIJJJJIJJJJIIIIIJJJIIJIJJJIJJIJIIJII;

	private static string JIJIIJJJJJJJIJJIJIJIJIJJIIJIJIJJJJJJJJJIJIIJJJJ;

	private static uint JJJJJIJJIJIJJIJIJJIIJIJJIJJJJJJIJJJJJIJIIJIJJII;

	public static Action IIIJIJIJJIJJJJIJJIIJIIJIIIJIJJIJIIIIJJIJIIIIIIJ;

	public static bool IJJIJIJIJJJJIIIIIJJJJIIJIJJJJIJIJIJIIIIIJIJIIII;

	public static Action IJJJIIIJIIJIIIJJJIJIIIIJIJJIIIJJIJIJIIJJIJIIJJI;

	public static JIJJIIIIIJIIJIIJIJIJJJJJJJIIIIJJJIJIJJIJJIIIIII IIJJIJIIJJJIIIIJJIIJJIIJIIIIJJIIJIJJIJIJIJJJJJI;

	public static bool JIIJJJIIJJJIJJJIIIIJJJIJJJJIJIIJJIJJJJIIIIJJIII;

	public static bool JIJJIIIJJJIJJIJIJIJJJJJIJJIJJJIIJJIJJJIJJIJJJIJ;

	private const char JIJJJIJIJJJIJIIIJIJIJJJJJJJIIIIJIIIJJIIJJIJJIIJ = ':';

	private static string JIIIJJJIJIIIIIIIJJJJJIIIIJJIIJJJIIJIJJJJJIJIJJJ;

	public static string IIIJIIJJIJJIJJJJIIIIJJJIJIIIJIIIIJIJJJIJIJJJIJJ
	{
		get
		{
			return JJIIJJIIIJJJIIJIJIJIJJJJJIIJIJJIJIJIJJIJIJJJIII();
		}
		set
		{
			JJIIJJJJJIJIIIJJIIJIJIJJIJIIJJIJIIIIIIIIIIIIIJJ(value);
		}
	}

	public static string IIIIJIJJJJJJIJIIJIIJJIIJJJIIJJJJIIJIIIIIJIJJJJJ
	{
		get
		{
			return IIIIIJIJIJIJJIIIIJJIJJIJIJJIIJIIIIIIJJJJJJIIJIJ();
		}
		set
		{
			JJIJIIJJIIJJIJJJIJIIJIJIIIIIIIIJIJJJJJIJIJJJJJJ(value);
		}
	}

	[Obsolete]
	internal static string JIJIJIJIJJIIIJJJJJIIIJIJIJIJIJJJJJIIJJIJIJJJIJJ
	{
		get
		{
			return JIJJIJJIJJJJIJIJJIJJIJJJJIJJJJJIIIIJJJIIIJJIJII();
		}
		set
		{
			IJIJIJIIIJIJJJIIIJJIIIJJJIIJIJJIIJIJIIIJJJJIJJJ(value);
		}
	}

	private static uint JIJJIJJJIJJIIJJIIJIIJIJIIJJJJIJJIJJIIIIIIIJJIIJ => IIJIJJJJIJIJIIIIIIIIIJIIIIJJIJIIJJIIJIIIIJJJIJI();

	private static string IJIJIIIIJJIIIJIIJJJIJJIJIIIJJJIIIJIIIIJIJJJIIIJ => IIIJJJIJIIJJIIJIIIJJJIIJJIIIJJJIIJJJJIIIIIIJJJJ();

	public static void JJIIJJJJJIJIIIJJIIJIJIJJIJIIJJIJIIIIIIIIIIIIIJJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static string JJIIJJIIIJJJIIJIJIJIJJJJJIIJIJJIJIJIJJIJIJJJIII()
	{
		return null;
	}

	public static string IIIIIJIJIJIJJIIIIJJIJJIJIJJIIJIIIIIIJJJJJJIIJIJ()
	{
		return null;
	}

	public static void JJIJIIJJIIJJIJJJIJIIJIJIIIIIIIIJIJJJJJIJIJJJJJJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	internal static string JIJJIJJIJJJJIJIJJIJJIJJJJIJJJJJIIIIJJJIIIJJIJII()
	{
		return null;
	}

	internal static void IJIJIJIIIJIJJJIIIJJIIIJJJIIJIJJIIJIJIIIJJJJIJJJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private static uint IIJIJJJJIJIJIIIIIIIIIJIIIIJJIJIIJJIIJIIIIJJJIJI()
	{
		return 0u;
	}

	public static void JJJJJIIJJJJJIJIJIJIJJJIJIJIJIJIJJIIIIJJJIJIIIJJ()
	{
	}

	[Obsolete]
	internal static void IJIJJJIJJIIIIIIIJIJIJJIIIIIIJIIIIIIJIIIJJJJJJIJ(string JJJIIIIJJJIIJIIJIJIJJIIIIJIIJIIIIJJIIIJJJJJJIIJ)
	{
	}

	public static void JIIIIIIIIIJJJJJJIJJJJJJIJJJIJJJIJJJIIJIJIIJIIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static int JIJIIIJIIIJJJIIJJIIIJJIIJJIIJJIIJJIJJJJIJJJIIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public static int JIJIIIJIIIJJJIIJJIIIJJIIJJIIJJIIJJIJJJJIJJJIIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, int IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return 0;
	}

	internal static string IIJIJIIJJJJIJJIJJJIJIJJIIJJJIJJJJJIJJJJIJJIIIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	internal static int IJIJJJJJIJIIJJJJIJJIJJIIIIIJIIJIJIIIIIJJIIIIJJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJJIIIJJIJIIIJIIJJJIIIIIIJIIJIIJJJJIIJIIJIJIIII, int IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return 0;
	}

	public static void IIIIJJIIJIJIIIIJIIIJJIJIIIIJJJIIJJIIJJIIIJIIJJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, uint JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static uint JIIJIIJIIJJIIIIIIIIJJIIJJJJJJJIJJJJJJJJIIIJIJJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0u;
	}

	public static uint JIIJIIJIIJJIIIIIIIIJJIIJJJJJJJIJJJJJJJJIIIJIJJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, uint IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return 0u;
	}

	private static string JJJIIIJIJJJIIIIIJIJIJJJIIJIJJJIIIJIIJIIIJIIIJJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, uint JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	private static uint JIJIJIJIIIIJJIIJJIIIJIIJJJIIIIIIIJIIIJJJIIJIIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJJIIIJJIJIIIJIIJJJIIIIIIJIIJIIJJJJIIJIIJIJIIII, uint IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return 0u;
	}

	public static void IJIIJJJJJJIIJIIIIIJIIJIIIJIJIIJIJJIJJJJIIJJIIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static string IIJJIIJIIIJJIIIJJJIIIJIIIJIJJIIJIJIIIJIIIJIJJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public static string IIJJIIJIIIJJIIIJJJIIIJIIIJIJJIIJIJIIIJIIIJIJJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return null;
	}

	internal static string IIJIJIJIJIIJIIIJJIJIJIIJIJJJIIIJIIJIIIIIIJIIIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	internal static string JJJJIIJIJJIJJIIJJJIIIIIJIJJIJIJJIJIIIIIJIJIIJIJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJJIIIJJIJIIIJIIJJJIIIIIIJIIJIIJJJJIIJIIJIJIIII, string IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return null;
	}

	public static void JIJIIIJJJIIJIIJJIIIJIJJJIIIIIIIIIJIJJJJJJIJIJJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static float JJIJJJIJIIJJJIIJIIIJIIJIJJIJIIIJIJIJJJIIJJJIIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0f;
	}

	public static float JJIJJJIJIIJJJIIJIIIJIIJIJJIJIIIJIJIJJJIIJJJIIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, float IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return 0f;
	}

	internal static string JIJIJIJIJIIIIJIIIJIIJJIJJJIIIIIIJIJJIIJIIIIIJIJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	internal static float JIIJIIJIIIIJIJIJIIIIJJIJIJIIIJJJJIIIJJJJIJIJIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJJIIIJJIJIIIJIIJJJIIIIIIJIIJIIJJJJIIJIIJIJIIII, float IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return 0f;
	}

	public static void IIJJJIIJIIJJJIIJIIJIJJJJJIJIIIJJJJIJIIJIJJIJJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, double JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static double IJJIJJJJJJJIJIIIJIIJIJJIJJJIJIJJJJJIJJJIIJJIIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0.0;
	}

	public static double IJJIJJJJJJJIJIIIJIIJIJJIJJJIJIJJJJJIJJJIIJJIIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, double IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return 0.0;
	}

	private static string IJIIJJJIJIIJIIJJIJJJIJJJJIIJIIIJJJIIJJJJIIJIIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, double JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	private static double JIIIIIIIJJJIIIJIIJIIIJJIJIIIIJIJIIJJIJJJJIJJIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJJIIIJJIJIIIJIIJJJIIIIIIJIIJIIJJJJIIJIIJIJIIII, double IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return 0.0;
	}

	public static void JIJJIIJJJIIJIIIIIIJIIIIJJIJJJIIIJJJJIIIJJJJIIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static long JIJIJJIIIIIJIJJJIIJIIIIJJJJJJJIJIJJJJIIIJJJJJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0L;
	}

	public static long JIJIJJIIIIIJIJJJIIJIIIIJJJJJJJIJIJJJJIIIJJJJJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, long IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return 0L;
	}

	private static string IJJJJJIJIJIJJIJJIIIJIJIJJIJIJJIIJJIIJJIJJIJJJJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, long JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	private static long JIIJJJIIJIIJIIIJIIJIIJIJIIJIIJJIJIIIIIJJIJIJIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJJIIIJJIJIIIJIIJJJIIIIIIJIIJIIJJJJIIJIIJIJIIII, long IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return 0L;
	}

	public static void JJIJIIJIIIJIIIJIIIJJIJJIJIIIIJJJJJIIJIIIJIIJJJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static bool IJIJIJJJJJJJIIIJJJIIIJJIJIIJJIJJJJIJJJJJIIIIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return false;
	}

	public static bool IJIJIJJJJJJJIIIJJJIIIJJIJIIJJIJJJJIJJJJJIIIIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, bool IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return false;
	}

	private static string JJIIIIJJJIJIIJIJIJJIIIIJIJJIJJIJIJIIIJJIIJIJIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	private static bool JIJIJJIJJJJJJIJIJIJJIJJIJJIIJIJJIJJJIJIJIJIJIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJJIIIJJIJIIIJIIJJJIIIIIIJIIJIIJJJJIIJIIJIJIIII, bool IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return false;
	}

	public static void JIJJJIJIJIJIIJIIJIIIIJIJJIIJJIJJIIJJJJIJIIIIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, byte[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static byte[] IIJIJJIIJJJJJIJIJJJJIIJJIJJJIJJIIJIIJIIJJIJIJJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public static byte[] IIJIJJIIJJJJJIJIJJJJIIJJIJJJIJJIIJIIJIIJJIJIJJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, byte IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI, int JJIIIJIIIJIIJIIJIJJIIJJJIJJIIIJIJIIJIJIJJJJJJJI)
	{
		return null;
	}

	private static string IIJJIJJJJIJIIIIIIJJJIJIJIIJIIJJJIIIJIJIJJIIIIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, byte[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	private static byte[] JJJIJJJJJIIIIJJJIJIJJIIIIIJJIJIIJIIIIIJJIJIIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJJIIIJJIJIIIJIIJJJIIIIIIJIIJIIJJJJIIJIIJIJIIII, byte IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI, int JJIIIJIIIJIIJIIJIJJIIJJJIJJIIIJIJIIJIJIJJJJJJJI)
	{
		return null;
	}

	private static byte[] IIIIIJJJJIIIJIJIJIJIJJJJJIIJIIIJIIIIJIIJJJJJJIJ(byte JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IIIJJJIJIJJJJIJJIIIJJJIIIIJIJJIJJIIJJJJIJIJIIII)
	{
		return null;
	}

	public static void JJIIIJJJIJIIIJIIIJIJIJIJIJIIIJIIIJIJIJJIIIIIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static Vector2 IJIJJIIJIIJJIJIJIIJJIJIIJIIJIJIIJIJJIJIJIIJJIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return default;
	}

	public static Vector2 IJIJJIIJIIJJIJIJIIJJIJIIJIIJIJIIJIJJIJIJIIJJIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Vector2 IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return default;
	}

	private static string IJIJIJIIIJIJIIIJIIJIJIIJJJJIIIJJJIIJJJIIJJJJIIJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	private static Vector2 JIIIJIJJJJJJIIJJIJJIJJJIJIJJJIJIJIIIJJJJJIIJJJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJJIIIJJIJIIIJIIJJJIIIIIIJIIJIIJJJJIIJIIJIJIIII, Vector2 IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return default;
	}

	public static void IJJJIIJIJJJJJIIIJIIIIJJJIJIJJIIIJIJJIIIIIJIJIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static Vector3 JIIJIIJJIJIIIJJIJIIIIIIJJIJJIJIJIJJIIIIIJIIIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return default;
	}

	public static Vector3 JIIJIIJJIJIIIJJIJIIIIIIJJIJJIJIJIJJIIIIIJIIIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Vector3 IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return default;
	}

	private static string IIJJJJIIJIJJIIJJJIJIJJIIJIJJIIIIIJJIJJIJIIIJJJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	private static Vector3 JIJIJJJJIIJJIJJJIIJIJJJJIIIIIIJIJIJIIJJJJIJIIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJJIIIJJIJIIIJIIJJJIIIIIIJIIJIIJJJJIIJIIJIJIIII, Vector3 IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return default;
	}

	public static void JIIJIJJJIJJIIJIIJJIIIJIJIJJJJJJIJIJIJIJJIJJIIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static Quaternion JJJJIIIJIIIIJIIJIJIJIIIIIIJIJJIIIJJIIIIJJJIIJJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return default;
	}

	public static Quaternion JJJJIIIJIIIIJIIJIJIJIIIIIIJIJJIIIJJIIIIJJJIIJJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Quaternion IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return default;
	}

	private static string JJJJJJJJIIIIIIJJIIJIJJIJIJJJIJIJJJIJJJJIJJIIIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	private static Quaternion JIJJIJIIJIJIJIJIIIJJJIIIIIJJJJIJIJIJIIJJJJIJIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJJIIIJJIJIIIJIIJJJIIIIIIJIIJIIJJJJIIJIIJIJIIII, Quaternion IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return default;
	}

	public static void IJJJJIJIJIJIIJJJJJIIJJJJJJIJIJIIJIIJJJJJJJJJIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Color32 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static Color32 IIJIJIJIJIIIIIIIIJJJIJJJIJIIIIJJJJIIJIJJJIJJJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return default;
	}

	public static Color32 IIJIJIJIJIIIIIIIIJJJIJJJIJIIIIJJJJIIJIJJJIJJJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Color32 IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return default;
	}

	private static string JIJJJJIJIIIJIJIIJIIIJJIJIJJJJIJIIIJIIIJJJJIJJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, uint JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	public static void IIIJIJIIIJIIJJIJIJIJJIIJJJJIIJIIJIJIJJJJIJJJJJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Rect JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static Rect JIJIIIJIJIIJJJIIIIJIJIJJJJJIIIIIJJIIIJJJIJJIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return default;
	}

	public static Rect JIJIIIJIJIIJJJIIIIJIJIJJJJJIIIIIJJIIIJJJIJJIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Rect IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return default;
	}

	private static string IIIIJJJJIIIJJIIJIIIIJJJIJIJJJIJJIIJIIJIJJIIIIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Rect JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	private static Rect IJJIIJJIJJIIJJIJIIJIIJJJJIIJJIIJJJIJJIIJIIJJIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJJIIIJJIJIIIJIIJJJIIIIIIJIIJIIJJJJIIJIIJIJIIII, Rect IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI)
	{
		return default;
	}

	public static void IIJIIJJJJIIJJIIJJJIJJJIJJIJIJJIJIJIIIJIIIJJJIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string JJJJJIJJIIJIJJIIJJJIJJIIJIIJIJJJIIIIJIIIJIJJJIJ)
	{
	}

	public static string JIJIJJJIIJJJIJIJIJJJJJIJIJJIIJJIIIIJIIJIIIJJJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	internal static JJIIIJJJJIJJIIJIJIIIIIIIJIIJJIIIJJJIJIIJJJJIJII JIIIJIJJIJIJIJJIJIIJIIIIIJIIIIJIIJIIIJIJIIJJJJI(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return JJIIIJJJJIJJIIJIJIIIIIIIJIIJJIIIJJJIJIIJJJJIJII.Unknown;
	}

	internal static string JJIJJJIIIIIIJIJJJIJIIIIJIJIJIJJIIJIJIJJIIIJJIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public static bool JIIIJJJIJJIJIJJIJIJJJIIJIJIJIIJJJJIIJJJIJIJIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return false;
	}

	public static void JJJIIIIJIIIIIJJJJJIIIJJIJJJIIIJIJJIJIJIJIIIIJJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
	}

	public static void JIIIIIJJJIIIIIJJJIIIIIJIIJIIIIIJJJIJJJJJIJIJIJJ()
	{
	}

	public static void JJIJIIIIIJJIJJJIJIJIIIJJJJIJIJJJJJIIIIJJIJJIIJJ()
	{
	}

	private static string IJJJIJJIJJIIIJIIJJJIJIJJIIIJIJJJIJIJJIIJJIJIJJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IIJJJJJJJJIIJJJJIJJJJIIJIIJIIJJJJJIIJJJJJJJIJJI)
	{
		return null;
	}

	private static string IIIIIIJIIIJIIJIIIJIJJJIJIJJIJIIIIJIIIJJJIJIJIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, byte[] JJIJJIIIJJJIJIJIJJJJIIJJIJIIJJJIJIJIIIIIIIJIIII, JJIIIJJJJIJJIIJIJIIIIIIIJIIJJIIIJJJIJIIJJJJIJII JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return null;
	}

	internal static byte[] JIJIJIIJIIIIJIIJIIIJIIIIJJJJJJIJJJIJIIJJIIJIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IJJIIIJJIJIIIJIIJJJIIIIIIJIIJIIJJJJIIJIIJIJIIII)
	{
		return null;
	}

	private static uint IJIIIJJJJIJJIIIJIIIJJJJIJJJJJIIJIJIIIJIJIIIIIJJ(string JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
	{
		return 0u;
	}

	private static void JJIJJIJIJIJJIJIIJIJJJJIIIJIIJJIJJJIJIJJJIJIIJIJ()
	{
	}

	private static void JIJIIIJJJIJIJIJIIIJJIJIJIIIIIIIJIJIIJIJIIIJJIJI()
	{
	}

	private static string JJIJIIJJIJJIJIJJIIIIIJIIJJJIJJJJIJJJJIIJJIJIJJI()
	{
		return null;
	}

	private static byte[] IJJJJJIIIJJIIJJIJJIJIJJJIJJIJJJJJJIIJIIJJIJIJJI(byte[] JIIIJJIJIJIJJJIIJIJJJJJIJIJIIIIJIIIIJJIIJIJJIIJ, int JJJIIIJIJIJJJJJJJJIJIIIJJJIIJJIJJIJIIJJIIIIJIJI, string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	private static string IIIIIIIIJJJIIJJJJJJJIIJIIIJIJJIJJJIIJIJIJJIIIJJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	private static string JIJJJJIIJJJIJJIJJIIJIIIJJJIJIIIIIIJIIIJJIIIIJJJ(string JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI)
	{
		return null;
	}

	private static string IIIJJJIJIIJJIIJIIIJJJIIJJIIIJJJIIJJJJIIIIIIJJJJ()
	{
		return null;
	}
}
