public static class IJIJIIJIIIJIIIIJIJJJIIIIJIIJJIIJIIJIJJJIIIIJIIJ
{
	public static void IIJJIJJJIJJIIIIJJJIJJJIJJJJIJIJJIJIIJJIJJJJIJJJ()
	{
	}

	public static void IJIIJIIJJJIJIIJJIJIIJJIJJIIIIIJIJJJJIJJJJJJJIJJ()
	{
	}

	public static void JIJIIIJJJJJIJIJJJJJIJIIJIJIIJJIIJJIIIIJJJIIIJII(float IIJJJJJJIIIIJJIIJJJJIIIJJIJIJJJIJJIIJIJIIIJJIJI)
	{
	}
}
