using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[Serializable]
[StructLayout((LayoutKind)0, Size = 12)]
public struct IJIJJIJIIIIJIJIJJIIJIIJJIIIIIJJJJJIIIIIIIJJJIII : IEquatable<IJIJJIJIIIIJIJIJJIIJIIJJIIIIIJJJJJIIIIIIIJJJIII>
{
	public byte[] JJIJIJIJIIJJIJJJJIJJJJIIIIIJJJIIJIJJJIJJIJIIJII;

	public byte[] IIIIIIJIJJIIJJJJJJJIIJIIIIJJIIJIIJJIIJJIIIIIJJJ;

	public bool IIIIJIJJJJIJIIJJIIIJIIJIJJJJIJJIJIIJJIJIJJJIIII;

	public int IIJIJJJIIIIJIJIJJIIJJIIJIIJJIIIJJIIIIJIJJIIIIJJ => IJJIIJJJJJIJIIJIIIIJJIJIJIIIJJIIJJJJJJIIIJIIJII();

	public override string ToString()
	{
		return null;
	}

	private string IIIIIJIJJJJJIIJIIIIIIJIJIIIJJIJIIJIJIIIIJIIJJII()
	{
		return null;
	}
	public static implicit operator string(IJIJJIJIIIIJIJIJJIIJIIJJIIIIIJJJJJIIIIIIIJJJIII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}
	public static implicit operator IJIJJIJIIIIJIJIJJIIJIIJJIIIIIJJJJJIIIIIIIJJJIII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}

	public static byte[] IIJIJIIJJIIJIJJIJJJJIJJIJJJIJIIJIJIIIJJIIJIIJIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, byte[] IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public string JIJJJIJJIJIIIIIJIIIJJJIIJIJIIIIJIJJIIJJIIIJIJJJ()
	{
		return null;
	}

	public override int GetHashCode()
	{
		return 0;
	}

	public int IJJIIJJJJJIJIIJIIIIJJIJIJIIIJJIIJJJJJJIIIJIIJII()
	{
		return 0;
	}

	public static string IIJJIIJIIIJJIIIJJJIIIJIIIJIJJIIJIJIIIJIIIJIJJII(byte[] JIIIJJIJIJIJJJIIJIJJJJJIJIJIIIIJIIIIJJIIJIJJIIJ)
	{
		return null;
	}

	public string IIJIJIIIIJJJJIJIJJIJJIIIJIIIIJIIIJJJJJJIIIIJJJJ()
	{
		return null;
	}

	public string IIJJJJIJIIJJIIIIIJJJJJJJIIJJIIIJIJJIJJJIIJJIIJI()
	{
		return null;
	}

	public bool IJJIIJJJIJIJJJIIIIJJIIJJIJIJJIJIJJIIJJIIIJJIIJJ(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}

	public bool Equals(IJIJJIJIIIIJIJIJJIIJIIJJIIIIIJJJJJIIIIIIIJJJIII JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}

	public static string IIJJJIJJIJIJIIJIIIJIIIJJIIJJJIJIIIIIIJJIJJJJJIJ(byte[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, byte[] IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public int IJJIJJJJJJJIJIJIIIIJJIJJIJJJJJIJIJJIIJIJJIJIJJI()
	{
		return 0;
	}

	public void JJJIJIJIIIJJIJIIIIIIIJIJJIJJIIIJJIJIIIJJJJJJIJI(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static byte[] JJJIJJJIIJJIJJIJIJJIIJJIIJJIIJJJJJJJJJIIJJJJJJJ(string IJIJIIJIJJIJIIIJIIIIJJJJIIJIJIIIJJJIJIJJIJIIIJJ)
	{
		return null;
	}

	public bool JIIJIIJJIIIJJJIJJIJIJIIJIIJIIIJJIJIJJJIJJIJIJII(IJIJJIJIIIIJIJIJJIIJIIJJIIIIIJJJJJIIIIIIIJJJIII JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}
	public int JJIJJJJIIIIIJIJIJIIIJJJJIIJJJIIIIIJJIIJJIJIJJJJ()
	{
		return 0;
	}

	public bool JIJIIJJIIJJIJIJJIIIJIJIJIJJIIJJJIIJJJIIIJIIIJIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return false;
	}

	public static byte[] JJJIIJJJJJIIIJJIIJJJIJIJJIJJJJIJIIIJIIIJJIIJIJI()
	{
		return null;
	}

	public static byte[] JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, byte[] IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public bool IIJJIJIJJJJJIIIIIIJJIJJIIIJJJJJJIIIJJIJIIIJIJIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return false;
	}

	public bool JJIJJIIJIIJIJJIJIIIIIJJIJIJJIJJIJIJJJIIJJIJIJIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return false;
	}

	public static string JJIIJIJJJIIJJIJJJJIIJIJJIIIIJIIJIJJJIIIIJJJJJII(byte[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, byte[] IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	private IJIJJIJIIIIJIJIJJIIJIIJJIIIIIJJJJJIIIIIIIJJJIII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		JJIJIJIJIIJJIJJJJIJJJJIIIIIJJJIIJIJJJIJJIJIIJII = null;
		IIIIIIJIJJIIJJJJJJJIIJIIIIJJIIJIIJJIIJJIIIIIJJJ = null;
		IIIIJIJJJJIJIIJJIIIJIIJIJJJJIJJIJIIJJIJIJJJIIII = false;
	}

	public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}
}
