using System;
using System.Collections;
using System.Runtime.CompilerServices;

internal sealed class IJIJJJJIJIJIIIIIIIJJIJIJJIJJJJJIIIJIIIIJJJIJJJJ : IList, ICollection, IEnumerable
{
	private readonly IList JIIJIJJJIJJJIIIIJJIJJJJIJJIIIIIIIJIIJJJJIIJJJII;

	public int Count => 0;

	public bool IsReadOnly => false;

	public bool IsFixedSize => false;

	public bool IsSynchronized => false;

	public object SyncRoot => null;

	public object this[int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ]
	{
		get
		{
			return null;
		}
		set
		{
		}
	}

	public int JJIJJJIIJIJIJIIIJJJIIIJIJJJJIIJIIJJJIJJIJIJJIII => Count;

	public bool JJIIJIIIIIIIIJJIIIJJJJIJJJIJJJIJIIJJJJIIJJIIJJJ => IsReadOnly;

	public bool IJIJJIIIIJJIIIJIJIIIIIIJJIIJIJIJJIIIIJJIJJIIJJJ => IsFixedSize;

	public bool JJIJJJIJJJIJJJIJIIJJIIJIJIIJJIIJIIJJJJJIIJJJIII => IsSynchronized;

	// C# has no syntax for parameterized property 'JIJIIJJIJIIJJIJJIIIJIIIJIIIJJJJJJIJJIJJJIIJIIJJ'.
	public object get_JIJIIJJIJIIJJIJJIIIJIIIJIIIJJJJJJIJJIJJJIIJIIJJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return this[IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ];
	}

	public void set_JIJIIJJIJIIJJIJJIIIJIIIJIIIJJJJJJIJJIJJJIIJIIJJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		this[IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ] = JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI;
	}

	public object IJJIIJJIJJIIIJIIIIJJJJJJJIJIJIJJIJIIIIIJIJJIIJI => SyncRoot;

	public bool Contains(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return false;
	}

	public void Insert(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public int IndexOf(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return 0;
	}

	public void JJIIIIIJIJJIIIJIIJIIIJJJIIIJIIIJJJJIIIIIJJJIJIJ()
	{
	}

	public void RemoveAt(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}

	public IEnumerator GetEnumerator()
	{
		return null;
	}

	public int Add(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return 0;
	}
	public object JJIIIIIIJJJIJJIIIIIJJJJIIJJJIJJIJIIJJJJJJIJIJJI()
	{
		return null;
	}


	public bool IIJJIJJIIJJJJJJJIIJIIIJJIIJIIIJJJIJIIIIIJIJIJJI(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return false;
	}
	public object JJJIIJJIJIIIJJJJJJJIIJIJIJIIIIJJIIJJJIIJJJIJIJJ()
	{
		return null;
	}

	public bool IIJIIIJIIIJIJJJIJJJJJIIJJIIJJJIJJJJJJJIJIJJIJIJ(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return false;
	}

	public void IJJJIIIIIJIJJIJIJJIIJJJJIJJIIIJJIJIJJIIIIJIIIIJ(Array JJIIJJIJIJJIJIIIJJIJIIIJIJIIIIIIIIIJIJIJIJJJIJI, int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}
	public bool JJIIJJIIIJIIJJJIJIIIIJIIJJJJIIJIIIJJIJJIJJIJJJI()
	{
		return false;
	}

	internal IJIJJJJIJIJIIIIIIIJJIJIJJIJJJJJIIIJIIIIJJJIJJJJ(IList JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
	}

	public void JJJJJIIIIJJIIIJIIIJIJIIJJIJJJIJJJJJJJIJJIJJJJII(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}

	public int IIJJJIJJIIJJJJJIIJIJJIJIJIJIIIIJJIIIIJJIIIJJJJI(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return 0;
	}



	public void IJJIIIJJJIIJIIJJJJIIIIJIIIIJIJIIJJIJIJJJIJIJJJI(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIJIJJJJIJIIJIIIIIIJJJJJJJIJJJIJIJJIIIIJJJIIIJJ(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public object JJJJJJIJJIJIIIJJJIIJJIIIJIIIIIJIIIJIIIJIIIJIJJI(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}

	public void Remove(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJIIIJJJJIJIIJJJIJIIJJJJIIIJJIIJIIIIIJIIJJIIJII(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}
	public bool IJIIIJIIJJJIJJIIIIIIIJIIJJJJIJJJJJJJIIJIJJIJJII()
	{
		return false;
	}
	public object JJJJJIIJJJIIIJIJJJJIIIJJIIJIIJIJIJJJJIIJJIIJIII(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}
	public bool JIJIIJJJJJJIIJJIIIIJIIIIJJIIIIJIJJJJJIIIIIIJJIJ()
	{
		return false;
	}

	public void CopyTo(Array JJIIJJIJIJJIJIIIJJIJIIIJIJIIIIIIIIIJIJIJIJJJIJI, int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}
	public bool JIIIJIIIIJJJIIJIJJIJIJIJIIJJJJJIIIJIIJJIJJIIIJI()
	{
		return false;
	}


	public IEnumerator IIJJJIJJJIIJJIJIIIIJIIJJJJIJIJJIIIJJJJJJJIJIJII()
	{
		return null;
	}
	public bool IIJJIJJIIIIJJIIJIIJJJIJJJIJJJIIIIIJJJIJJJJJIIIJ()
	{
		return false;
	}

	public void Clear()
	{
	}
	public object JJJJIJJJJJIIIJIIJIIIJIJIJJIJIIJIJIJJJJJJIJJIIJJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}
}
