using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using UnityEngine.Networking;

public class IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII
{
	private sealed class IIJIIIIJJJIIJIJJIIIIIJIIIJIJIIIJIIIIIJJJJJIJIJJ : IEnumerator<object>, IEnumerator, IDisposable
	{
		private int IJJJJJJJJIIJIIIIIJIIJJJIJJIIJIJJJJJIJJJJJIIIIII;

		private object IJJJJJIIIJJIIIIIIJIIIJIJJJIJIJIIJJIJIIIJJIIIJIJ;

		public string JIIIJJJJIIIJIIIJJJJIJIIIJIIIJJIIJJIJJIIIIIIIJJI;

		public Action<string> IJJIIJIIJJIJIJJJJJIJJIJIJIIJIIIJIJIIIIJJJIJIIJI;

		public IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public Action<string> IJJJIIIIIIIIJIIJIJIIIIJJJJJIIIJJIIJJIIJIJJIIIII;

		private UnityWebRequest IJJJJIJIIIIJJJJIIIJJIIJIIJIIJIJJJIIIIIIJIIIIJII;

		object IEnumerator<object>.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		object IEnumerator.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		private void JJIIJIJJJJIIIIIIJIIJJJJJJJJIIJIJJJIJIJJJJIIJIJI()
		{
		}

		private bool MoveNext()
		{
			return false;
		}

		bool IEnumerator.MoveNext()
		{
			//ILSpy generated this explicit interface implementation from .override directive in MoveNext
			return this.MoveNext();
		}

		private bool JJIIIJJJJIIIJJJJIJIJJIIJIJJJIJJIIJIJJJIIIJJJIIJ()
		{
			return false;
		}

		[DebuggerHidden]
		public IIJIIIIJJJIIJIJJIIIIIJIIIJIJIIIJIIIIIJJJJJIJIJJ(int IJJJJJJJJIIJIIIIIJIIJJJIJJIIJIJJJJJIJJJJJIIIIII)
		{
		}
		private object IJJJIIJIJJJJIIIIIJJIIIIJJJIJIJIIJIIJIIJIIJIIJJJ()
		{
			return null;
		}

		private void IIJIJIIIIIIIIJJIIIIIJIIIIJJIIJIIIIIIIJJIJIJJJII()
		{
		}

		private void JJIJIIIIJJIJJJJJJJIJJIJIIJIJIJIIIIJJIIIJJIJIIJI()
		{
		}
		private object IJIIIJJIJJJIJIIIJJJJIIJJJJIIJJIIJIIIJIJIIJIJIJJ()
		{
			return null;
		}

		private bool JIIIIJIJIJJJIJJIJIJIJIJIIIJIJIIIIJJIJJJJJIJIJII()
		{
			return false;
		}
		private object JJJJJIIJJIIIIIIIIIIIJIIIIIJJJIIIIJIIJJJJIJJIJJJ()
		{
			return null;
		}

		[DebuggerHidden]
		void IEnumerator.Reset()
		{
		}

		private void JJIIIJJJJJJJJIIJIJIIIJIIIIIJIIIIJIIJJIIIIIJIJII()
		{
		}

		private void IIJJJJJIJIIJIJIIIIJJIIJJJJJIIJIJJIJJIJJIJJIIJJI()
		{
		}

		[DebuggerHidden]
		void IDisposable.Dispose()
		{
		}

		private void JJIIJJJIJIIIJIIJIIJIJJJJIIIIJJJIIIJIJJIJIIIJIJJ()
		{
		}
	}

	public string JJIIIJIIIJJJIJJJJIIIJJIIIJIJJIIJJJIIJJIIIIIJIIJ;

	public string IJIIJJIIJJJIJIIIIJJJIIIIJIJIJJJJIJIJJJIIJJIJJJJ;

	public string JJIJJIIIIJJIIIJJJIJIJJJIIJIJJIIIIJIJIIJIIIIIJIJ;

	public IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII IJJJIJIJJJJIIJIIJIIJIJJIIJIJJIJJIIIIIIIJIJJJIJJ;

	public string JIIIIJJIIJJIIJJIJIIIJIJJIJJIJIIIIIIIJIJIJJJIIIJ;

	private static bool JJJJIJJJIIJIIJIIIIJJIIIJIJIIJJJJJIIJJJIIIIIIJIJ;

	public string JJIIIIJJJJJIIJIIJJJIJIIJJJIJJJJIJJJIIIIJIIIIJJI => IJIIJJJJJIJJIIIIIJIIIIIJJIIJIJIJJIJIJJJIJIJIJIJ();

	public void IJIIJIJIJJJIIJIIIIIJJIJIIIIJIJIJIIJJIJJJIIJIJJJ()
	{
	}

	public IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII IJIIIIIIIIJIIJIIJIJIIIIIJIIJIJJJJJIJJJJIIJIIIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public void IIIIIJIJJJJJIIJIIIIIIJIJIIIJJIJIIJIJIIIIJIIJJII(Action<string> IJJIIJIIJJIJIJJJJJIJJIJIJIIJIIIJIJIIIIJJJIJIIJI, Action<string> IJJJIIIIIIIIJIIJIJIIIIJJJJJIIIJJIIJJIIJIJJIIIII)
	{
	}

	public void JJIJIIIJIJJJIJJJIIIIJJJJIJIJJJJIIIIIIJJJJIJJJIJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
	}

	public string IJIIJJJJJIJJIIIIIJIIIIIJJIIJIJIJJIJIJJJIJIJIJIJ()
	{
		return null;
	}

	public void JIIJJIJJIJIIJJIIJIIJIJIIJIIIJIIIIJIJIIIJJIJIJJI(JJJJJIJIIIIJJIJIJJJJIJIIIJIJIIJJJJIIIIJJJIIIJJI JJJIIJJIJIJJIJJJIJIJIIJIIIIIJJIJJJJJIJJJJIIIIJJ, Action<string> IJJIIJIIJJIJIJJJJJIJJIJIJIIJIIIJIJIIIIJJJIJIIJI, Action<string> IJJJIIIIIIIIJIIJIJIIIIJJJJJIIIJJIIJJIIJIJJIIIII)
	{
	}

	public void IIIIIJIJJJJJIIJIIIIIIJIJIIIJJIJIIJIJIIIIJIIJJII(string JJJIIJJIJIJJIJJJIJIJIIJIIIIIJJIJJJJJIJJJJIIIIJJ, Action<string> IJJIIJIIJJIJIJJJJJIJJIJIJIIJIIIJIJIIIIJJJIJIIJI, Action<string> IJJJIIIIIIIIJIIJIJIIIIJJJJJIIIJJIIJJIIJIJJIIIII)
	{
	}

	public IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII JJJJJJJIJIIJIJIJJIIJJIJJJJJJJJIIJJIJIJJIIIJJIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public void IIIJJJJIJIJIJJJIJJIJIJIJIIIIJIJJIIJIIJIIIJIJIIJ(Action<string> IJJIIJIIJJIJIJJJJJIJJIJIJIIJIIIJIJIIIIJJJIJIIJI, Action<string> IJJJIIIIIIIIJIIJIJIIIIJJJJJIIIJJIIJJIIJIJJIIIII)
	{
	}

	public void IIIIIJIJJJJJIIJIIIIIIJIJIIIJJIJIIJIJIIIIJIIJJII()
	{
	}

	public void JIJJJIIIIJIJIIIIJIJJIJJJJIJIJJJJJJIJJIIJJIJIIII(string JJJIIJJIJIJJIJJJIJIJIIJIIIIIJJIJJJJJIJJJJIIIIJJ, Action<string> IJJIIJIIJJIJIJJJJJIJJIJIJIIJIIIJIJIIIIJJJIJIIJI, Action<string> IJJJIIIIIIIIJIIJIJIIIIJJJJJIIIJJIIJJIIJIJJIIIII)
	{
	}

	public void IJIJJJIJJJIJIIIIJJIJJIJJJIIIJJJJIJIJJJIIIIIIJJI(JJJJJIJIIIIJJIJIJJJJIJIIIJIJIIJJJJIIIIJJJIIIJJI JJJIIJJIJIJJIJJJIJIJIIJIIIIIJJIJJJJJIJJJJIIIIJJ, Action<string> IJJIIJIIJJIJIJJJJJIJJIJIJIIJIIIJIJIIIIJJJIJIIJI, Action<string> IJJJIIIIIIIIJIIJIJIIIIJJJJJIIIJJIIJJIIJIJJIIIII)
	{
	}

	public void JJIIIJIIIJIIJJIJJJJJJJJIJJJIIJJJJJJIIIIJJJIJJII(JJJJJIJIIIIJJIJIJJJJIJIIIJIJIIJJJJIIIIJJJIIIJJI JJJIIJJIJIJJIJJJIJIJIIJIIIIIJJIJJJJJIJJJJIIIIJJ)
	{
	}

	public IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII IIJIIIJJJIIJJJIIIIIJJIJIJJJIIIJIJIIJJIIJIJIJJIJ()
	{
		return null;
	}

	public IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII JIIIJIIJJJIIJJJIJIJJIIIIJJIIJJJIIJJIIJIIJIIJJJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public void IIIIIJIJJJJJIIJIIIIIIJIJIIIJJIJIIJIJIIIIJIIJJII(JJJJJIJIIIIJJIJIJJJJIJIIIJIJIIJJJJIIIIJJJIIIJJI JJJIIJJIJIJJIJJJIJIJIIJIIIIIJJIJJJJJIJJJJIIIIJJ)
	{
	}

	private IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII(IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string IIIJIIIIJIIJJJJIIJJJJJJJJJJIIIIJJJIIJIIJJIJJIJI)
	{
	}

	public IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII(string JJJJJJJIIJIJJJJJIJJIJIJJIJIIIJJIIIJJJJJJIIJIJII)
	{
	}

	public static string IJIIJIJJJJIJJIJIJJIJIIJIIIIJJIJJJIJJIIIIIJIIIII()
	{
		return null;
	}

	public static string JIJIJIJJIIIIIJIIIIIJJIIJJJIJIIJIIIJIIIIIJJJJIJI()
	{
		return null;
	}

	public IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII()
	{
	}

	private IEnumerator IJJIIIJIJIIIJJIJJJJJIIIIJIIJIIIJIJJJJJJJIIIJJJJ(string JIIIJJJJIIIJIIIJJJJIJIIIJIIIJJIIJJIJJIIIIIIIJJI, Action<string> IJJIIJIIJJIJIJJJJJIJJIJIJIIJIIIJIJIIIIJJJIJIIJI, Action<string> IJJJIIIIIIIIJIIJIJIIIIJJJJJIIIJJIIJJIIJIJJIIIII)
	{
		return null;
	}

	public IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII IIJJJJJJJIIIIIIJJIJJIJIIIJIJIJJIIJIJJIIIIIJJJIJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII IJJJJIJIIIIJJJIIIJJIJJJIJJJIIIIIJIIIJIJIIIIJIJJ()
	{
		return null;
	}

	public void IIJJIJIIIJIJJJJJJJIJIJIJJJIIJJJIJJIIJIIJJIJJJIJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
	}

	public static string IJIIJJIIIIJJIJIIJJIIJJJJJJJIJIIJIIJIJIIIJIJIIJJ()
	{
		return null;
	}

	private IEnumerator JIJJIIIJJIIIJJIIIIIIJIIIJJIJJIJJIIJJIJJIIIIIJJI(string JIIIJJJJIIIJIIIJJJJIJIIIJIIIJJIIJJIJJIIIIIIIJJI, Action<string> IJJIIJIIJJIJIJJJJJIJJIJIJIIJIIIJIJIIIIJJJIJIIJI, Action<string> IJJJIIIIIIIIJIIJIJIIIIJJJJJIIIJJIIJJIIJIJJIIIII)
	{
		return null;
	}

	public void IIIIIJIJJJJJIIJIIIIIIJIJIIIJJIJIIJIJIIIIJIIJJII(JJJJJIJIIIIJJIJIJJJJIJIIIJIJIIJJJJIIIIJJJIIIJJI JJJIIJJIJIJJIJJJIJIJIIJIIIIIJJIJJJJJIJJJJIIIIJJ, Action<string> IJJIIJIIJJIJIJJJJJIJJIJIJIIJIIIJIJIIIIJJJIJIIJI, Action<string> IJJJIIIIIIIIJIIJIJIIIIJJJJJIIIJJIIJJIIJIJJIIIII)
	{
	}

	public IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII(string JJJJJJJIIJIJJJJJIJJIJIJJIJIIIJJIIIJJJJJJIIJIJII, string IIIJIIIIJIIJJJJIIJJJJJJJJJJIIIIJJJIIJIIJJIJJIJI)
	{
	}
	public string IJJJIJIJIIIJJIJJJJIJIIIJJIJJIJJIIJIJIJIIJIJJJJJ()
	{
		return null;
	}

	public IJJIJIJJIIJJJJJIIIIJIJJJIIIIIIJIJJJIIIIJJJJJIII IIIIJJIIIJJIIIIJIJJJIJJJIJJJIJJJJJJIIJIJJJJJIIJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}
}
