using System.Runtime.InteropServices;
using UnityEngine;

public class IJJIIIIJJIIJIIIIIJJIJIJJIIJJIIJIJIJIIIJIJIJIJIJ
{
	[StructLayout((LayoutKind)0, Size = 4)]
	private struct IJIIIIIIIJIJJJJIJIIIIJJIJIJIIIIJIIJJJJIIJJIIJJJ
	{
		public byte JJJIIJJIJJIJJJIJJIJJIJJIJIIIJIIIIIJIJJJIJIIIIII;

		public byte IIIJJIIJIJJIJIIIJIJJJJIIIIIIJIIJJIIJIJJIIJJJJJJ;

		public byte JIIJJIIIIIJJIJJIIJIIIJIIJIJJIJJIIIJIIIJJJIJIIIJ;

		public byte JJIJIJJIIJJIJIJJIIJJIJIJIJIIJJIIJIJIIIIIIJIIJJI;
	}

	[StructLayout((LayoutKind)2, Pack = 1, Size = 4)]
	private struct JIIJJIIIJJIJJIIIIIJJJJIJJIIJJIJJIIIIIIIIIIJJIIJ
	{
		[FieldOffset(0)]
		public float JIJIJJJIJJIIIIIJIIIIIJJJJJJJIIIIJIIIJJJJIJJIIJI;

		[FieldOffset(0)]
		public IJIIIIIIIJIJJJJIJIIIIJJIJIJIIIIJIIJJJJIIJJIIJJJ JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII;
	}

	public byte[] JIIIJJIJIJIJJJIIJIJJJJJIJIJIIIIJIIIIJJIIJIJJIIJ;

	public int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ;

	private JIIJJIIIJJIJJIIIIIJJJJIJJIIJJIJJIIIIIIIIIIJJIIJ IIIIIJJJIIJIJJJIJIJJJJIJIIJJJIIJJJJIJIJJIJJJIII;

	private IJIIIIIIIJIJJJJIJIIIIJJIJIJIIIIJIIJJJJIIJJIIJJJ IIJJJIJIJJIIIIIIJJJIJIJJIJJIJJJIJIIJIJJIJIJIIJI;

	public IJJIIIIJJIIJIIIIIJJIJIJJIIJJIIJIJIJIIIJIJIJIJIJ()
	{
	}

	public bool JJJJJJJIJJJIIIIIIJJJJIIIJIJJJIIIIJIJJIIIJJIJIJI()
	{
		return false;
	}

	public byte[] JJIJJIJJJJIJIIJIIJJJIJJJJJJJJIJIJJIIJIJIJIJIIIJ()
	{
		return null;
	}

	public string IJIIIJIIJIJJIIIJIJIJJJJJIJIJIJIJIJIJJJIIIJIIIII()
	{
		return null;
	}

	public short[] JIJIJIIIJIIJJIJJJJIIJIJIJIIIJIIIIJJIIIIJJJJIIJI()
	{
		return null;
	}

	public string JIIJJJJIIIIJJJIJIIIIIIJJJIIJIJIJJIJJIJJIIJJJIJI()
	{
		return null;
	}

	public int JJJIJIIIJIJJIIIJIIJJIJJJJIIIJIJIIIJJJIIJJIIJJJJ()
	{
		return 0;
	}

	public string JJIJIIJJIJIJIIJJJIIJJIJIIIIIJJJJIJIJJJJJJJIIJJJ()
	{
		return null;
	}

	public Vector3 JJIJJJIJIIJJJJJIJJJIIIIIJJJIIJJIJIIIIJIIJIIJJJI()
	{
		return default;
	}

	public byte JIIJIJJIIIIIJJJJIIJJIIJIJJJJJIIIJJIJJIIIIIJJJIJ()
	{
		return 0;
	}

	public Quaternion JJIIIIIIIIJJJJIJIJIIIJJJIJJJIJJIJIJJJJIIJIJJIIJ()
	{
		return default;
	}

	public bool IJIJIJJIIJIJIJIIJJIIIJJIIJIIJIIIIJJIJIJJJIJJIII()
	{
		return false;
	}

	public float IIIIJIIIJIJIJIIJIJJJIJIJIJJJJIIJJJIJIIIIJJIJIIJ()
	{
		return 0f;
	}

	public int JIJIIIJJIJIIIIJJIJJIIJIIIIIIJIJIJJIJJIIJJIJIIIJ()
	{
		return 0;
	}

	public Quaternion JJIIIJJJJJJIIJJIJIIJJIJJJIJIJIIIJJIIIJJJIIJIJII()
	{
		return default;
	}

	public void IIIIIIIIJJJJJIJIJJIIJIIIIJIIJIJJJIIJJIJIJJIIJJJ()
	{
	}

	public Quaternion IIJJJIIIJIIIIIIIIJJJIJIIJIJJJJIJIJIJJJIIJJJIIJJ()
	{
		return default;
	}

	public byte[] IJJJIJIIJIIJJJJIJJJIIJJIIIIIIJIIJIIIJJIJJJJJJJI()
	{
		return null;
	}

	public short[] JIJJIJJJIJIJIJIJIIIIJIIIJIJIJJJJIIIIJIIIIJJIJJI()
	{
		return null;
	}

	public void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}

	public IJJIIIIJJIIJIIIIIJJIJIJJIIJJIIJIJIJIIIJIJIJIJIJ(byte[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Quaternion JJIJJIIIJIIIJIJJIIIJJJJIJJJJJJIIIIJIIJJJJJJIIII()
	{
		return default;
	}

	public string IJJJIJJIJIJIIJJJJIJJIIJIJIJJJIJJJIJJIJJJIJJIIJI()
	{
		return null;
	}

	public void JIIJIIIJIJJIJJJIIJJJJJIIJJIJJIJJJIJJIJJIIIIIIJI()
	{
	}

	public Quaternion JIIJJJJIIIIJIIIJIJJIIJIIIIIJIIJIJJIJIIJIIJIJJJI()
	{
		return default;
	}

	public float JJJIIJJIJIJJJJJIJJIJJIJJIIJIIIIIJJIJIJIIJIIIJII()
	{
		return 0f;
	}

	public byte[] IIIIJIJJJIIJIJJIJJIIIIIJIIJJIIJIJIJJJJJIIIJJJJJ()
	{
		return null;
	}

	public short JIIJIJIIJIJJIIIJIIJJJJIIIIJIJJJJJJJIJIIIIIIIJJJ()
	{
		return 0;
	}

	public Vector3 IIIIIIIIIJJIJJJIIJIIJJJIIJJIIIIJIJIIJJJIIJJIJJJ()
	{
		return default;
	}
}
