using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using UnityEngine;

[Serializable]
[StructLayout((LayoutKind)0, Size = 24)]
public struct IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ : IEquatable<IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ>
{
	public int JJIJIJIJIIJJIJJJJIJJJJIIIIIJJJIIJIJJJIJJIJIIJII;

	public int IIIIIIJIJJIIJJJJJJJIIJIIIIJJIIJIIJJIIJJIIIIIJJJ;

	public int IJJIIIJJJJJJIIIIJJIIIIJJIJJJJIIJJIJJJIJJJJIJJIJ;

	public int IJJJJIJJIJJIJIJIIJIIIJIIJJJIIIIIIJIIJIJJJIIJIJJ;

	public int IIIIJIIIIIJJIIJJIJJJJJIJIJIIJIJJJJIIIIIJIJIJIIJ;

	public bool IIIIJIJJJJIJIIJJIIIJIIJIJJJJIJJIJIIJJIJIJJJIIII;

	public float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ
	{
		get
		{
			return IJJIIIIIIIJIJIJIJIJJJIJJJJIJJIIJJJIJJJJIJJIJIII();
		}
		set
		{
			JIIJJIIJJIIJJIJIJIJIIIJJJIIJIIJJIIIJJJJIJIIJIJJ(value);
		}
	}

	public float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI
	{
		get
		{
			return IJJIIIIIJIIIJJIJIIIJIIJJIIIJIIJJJIIIIIJJIJIIIJI();
		}
		set
		{
			IIJIIIJJJJJJJIIJIJIJIJJJJIIJJIIJJJJIJIJJIIIIIJI(value);
		}
	}

	public float JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII
	{
		get
		{
			return IJJIIIIIJIIJJIIIJJIJIIIIJIIJJIIIIIIJJJJIJJJJJJI();
		}
		set
		{
			JJJJIIJIJJIIJJIJJJJJIJIJIIJJJIIJJIJJIJJJIIJJIIJ(value);
		}
	}

	public float JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII
	{
		get
		{
			return IJIIIIIJJJJIJJIIJJJJJJIJJJJJJJJJIJJIJJIJJJIIJJJ();
		}
		set
		{
			IIJIJJIIIJJIJJJIJJJIIJJJIJIJJIJJIIIJIJIJJJJJJJI(value);
		}
	}

	private Vector4 IIIIIJIJJJJJIIJIIIIIIJIJIIIJJIJIIJIJIIIIJIIJJII()
	{
		return default;
	}

	public override string ToString()
	{
		return null;
	}
	public static Vector4 JIJIJJJIJJJJJIIIIJIJIIIJIIJIJIJJIIIIIIIJJJIJIII(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}
	public static implicit operator Vector4(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}
	public static implicit operator IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ(Vector4 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ JJJJJIJIIJJIJJJIIIJIIJJJJJIJIIIJIIIJIIJIJIIIIII(Vector4 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return default;
	}

	public float IJJIIIIIIIJIJIJIJIJJJIJJJJIJJIIJJJIJJJJIJJIJIII()
	{
		return 0f;
	}
	public void IJJIIIIJIIIIJJJJIJIJJJJJJJIJJJJJJIJIIJIIIJJJJII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJJIIJIJJIIJJIJJJJJIJIJIIJJJIIJJIJJIJJJIIJJIIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIJIIIJJJJJJJIIJIJIJIJJJJIIJJIIJJJJIJIJJIIIIIJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void JJIIJIJIIJJIJJJIJJJIIIJIIJJJIJIJJIIIIJIJIIJJIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public override int GetHashCode()
	{
		return 0;
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIIIIJIIIIIIJJIIJIJIJJJIIIJIJIJIJIJJIIJIIJJIJJJ(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, Vector4 JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return default;
	}
	public static bool JIIJIJIIIIIJJJIJIJJJIIJIIIJIJJJIJIIJIIIJJJJJJII(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, Vector4 IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
	{
		return false;
	}
	public float IIJIIJIJIJJIJJIJJJJJIIIIJIIIIJJJJIJJJIJJJJIJJJJ()
	{
		return 0f;
	}
	public static bool JIIIIIJJJIIIJIIJIJIIIIJJIIIIIJJJIIJIIJIIJJJJIJI(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
	{
		return false;
	}

	private IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ(Vector4 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		JJIJIJIJIIJJIJJJJIJJJJIIIIIJJJIIJIJJJIJJIJIIJII = 0;
		IIIIIIJIJJIIJJJJJJJIIJIIIIJJIIJIIJJIIJJIIIIIJJJ = 0;
		IJJIIIJJJJJJIIIIJJIIIIJJIJJJJIIJJIJJJIJJJJIJJIJ = 0;
		IJJJJIJJIJJIJIJIIJIIIJIIJJJIIIIIIJIIJIJJJIIJIJJ = 0;
		IIIIJIIIIIJJIIJJIJJJJJIJIJIIJIJJJJIIIIIJIJIJIIJ = 0;
		IIIIJIJJJJIJIIJJIIIJIIJIJJJJIJJIJIIJJIJIJJJIIII = false;
	}

	public void JIIJJIIJJIIJJIJIJIJIIIJJJIIJIIJJIIIJJJJIJIIJIJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, float JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII, float JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII)
	{
		JJIJIJIJIIJJIJJJJIJJJJIIIIIJJJIIJIJJJIJJIJIIJII = 0;
		IIIIIIJIJJIIJJJJJJJIIJIIIIJJIIJIIJJIIJJIIIIIJJJ = 0;
		IJJIIIJJJJJJIIIIJJIIIIJJIJJJJIIJJIJJJIJJJJIJJIJ = 0;
		IJJJJIJJIJJIJIJIIJIIIJIIJJJIIIIIIJIIJIJJJIIJIJJ = 0;
		IIIIJIIIIIJJIIJJIJJJJJIJIJIIJIJJJJIIIIIJIJIJIIJ = 0;
		IIIIJIJJJJIJIIJJIIIJIIJIJJJJIJJIJIIJJIJIJJJIIII = false;
	}

	public void JJJIJIJIIIJJIJIIIIIIIJIJJIJJIIIJJIJIIIJJJJJJIJI(Vector4 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJIJJJIIJJIIJIIJIIJIIIIJIIJJJJJJIIJIIJIJJJIIJJJ()
	{
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJIIIJIIIIIIIIIIIJJJIJJJIJIIIIJJIIJIJJIJJJJJJIJ(float JJIJIIJIJIJIJJJIJIIIJIJIIJJJIIIIJJIIIIIIJIIJIJI, IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ)
	{
		return default;
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIJIIJJIIIIIIIJJJIJIJIJJIIJIJJJIJJIJJIJJIJIJIIJ(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, Vector4 JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return default;
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJJJIJIJIJJJIIJIJJIJIIJIJJIIJIJJIJJIIJJJIJJJIII(Vector4 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}
	public static bool JIIJIJIIIIIJJJIJIJJJIIJIIIJIJJJIJIIJIIIJJJJJJII(Vector4 IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
	{
		return false;
	}
	public static bool JIIIIIJJJIIIJIIJIJIIIIJJIIIIIJJJIIJIIJIIJJJJIJI(Vector4 IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
	{
		return false;
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJIJIIIIIIJIJJJJJJJJJJIIJJIIIIJJIIJIJJJIIIJJJII(Vector4 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}
	public float IJJJIJJJJJJJJIIIJIIJIJJIJJJJIIIIIIIJJIIIIJIIIJJ()
	{
		return 0f;
	}

	public bool Equals(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIJIIJJIIIIIIIJJJIJIJIJJIIJIJJJIJJIJJIJJIJIJIIJ(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return default;
	}

	public void IIJIJJIIIJJIJJJIJJJIIJJJIJIJJIJJIIIJIJIJJJJJJJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIIJIJIIJIIJJJJJIIJJIJJIIJJIJJJIJIJJIJJIIIJIJJJ(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ)
	{
		return default;
	}

	public float IJJIIIIIJIIIJJIJIIIJIIJJIIIJIIJJJIIIIIJJIJIIIJI()
	{
		return 0f;
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIJIJIIIJIIIIIJIJIIJJIJJIIJJIJJJIIJJJIJJJJIIJII(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, float JJIJIIJIJIJIJJJIJIIIJIJIIJJJIIIIJJIIIIIIJIIJIJI)
	{
		return default;
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJJJIIIIJIIJJJIIJIIIJJJJJJJJJJJJIJJJIJJJJIJIJJJ(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return default;
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ JJIIIIJIJJJJIIIIJJJIIJJJJJJJIJJJJIIJIIJIJIJJJJJ(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, float JJIJIIJIJIJIJJJIJIIIJIJIIJJJIIIIJJIIIIIIJIIJIJI)
	{
		return default;
	}
	public static bool JIIJIJIIIIIJJJIJIJJJIIJIIIJIJJJIJIIJIIIJJJJJJII(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
	{
		return false;
	}

	public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIIIIJIIIIIIJJIIJIJIJJJIIIJIJIJIJIJJIIJIIJJIJJJ(Vector4 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return default;
	}
	public void JIIJJJJIJJJIJIJIJJIJIIJIIJJJIIJJIJIIIIIIJIIJJJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static bool JJIJJJIIJJJIJJIIJJJJJJIIIJIJIIIIIIJIJIJIJIIJJJJ(Vector4 IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
	{
		return false;
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIJIIJJIIIIIIIJJJIJIJIJJIIJIJJJIJJIJJIJJIJIJIIJ(Vector4 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return default;
	}

	public float IJIIIIIJJJJIJJIIJJJJJJIJJJJJJJJJIJJIJJIJJJIIJJJ()
	{
		return 0f;
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJIIIJIIIIIIIIIIIJJJIJJJIJIIIIJJIIJIJJIJJJJJJIJ(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, float JJIJIIJIJIJIJJJIJIIIJIJIIJJJIIIIJJIIIIIIJIIJIJI)
	{
		return default;
	}
	public static Vector4 JIIIJJIIIIJJJJJJIJJIJIJJIJJIJJIIIJJJJIJIJIJJJJJ(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}
	public static IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIIIIJIIIIIIJJIIJIJIJJJIIIJIJIJIJIJJIIJIIJJIJJJ(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return default;
	}

	public float IJJIIIIIJIIJJIIIJJIJIIIIJIIJJIIIIIIJJJJIJJJJJJI()
	{
		return 0f;
	}
	public static bool JIIIIIJJJIIIJIIJIJIIIIJJIIIIIJJJIIJIIJIIJJJJIJI(IJJJIJIJIIJJIIIJJJJJJIIJIJJJIIJIJJJJIIJJIIJIIJJ IIJJIJJIJJJIIIIIJIJIIJIIIJJJJJJIJIIJJJIIJJIIJIJ, Vector4 IIJJJJJIIIJJJIIJJIIIJJIJJIJIIIJJIIIIJJIJIIJIIJI)
	{
		return false;
	}
}
