using System;

public class IJJJIJIIJIIJIIJIJIJIJIIJJJIJJIIIJIIIJJJIJJIJIIJ
{
	[Obsolete]
	public const byte IIJJIJJIJIJIJJIJIJJIJIIJIJIJIJIJJIJIJJJIJIIJIII = 250;

	[Obsolete]
	public const byte IIIIIIJJIJIIIIIJIJJIJIIIJJIIIIJJJJIJIIIIIIJJIII = byte.MaxValue;

	public const byte IIJIJJJIIJJJIIJIJJIIJJIJJIIIIJJIIJJIJJIIJIIIIII = 231;

	public const byte JIJJIIIIIJJIJJJIJIJIIIIJJJIJIIJIJJIIJIIIJJJIJJJ = 230;

	public const byte JJJJIIJIJIIJJIIIJIJIIIJJJJJJJJIJJIIIJJJJJJIJJIJ = 229;

	public const byte JIJIIIJIIJIJIIJJJJJIJJIJJIIJIJJIIJIIJIIJIIJIJJI = 228;

	public const byte IJJJJIJJIIIIIJJJJIJJJJJJJIIJIJJIIIJIJJIIIJIJIJI = 227;

	public const byte JIIJIIJJJJJIJJJIJJIJJIIJJJIIIJJJJIJIJJJIIIIJJJJ = 226;

	public const byte IJIIJIJIIIJJIIIJJIIIIJJJIJIIIIJJIJIJJIJJJIJJIIJ = 225;

	public const byte JIJJIIIIIJIJIIJJJIJJJJIJJIJIJIIIIJIIJJIIJIIIJII = 254;

	public const byte IIIJJJIJJJIJJIJIIIIJIJIIJJJJIIJIIJJIJIIJIJJIJJI = 253;

	public const byte IJJIJJJJIIJIJIIJIJIJIJIIIIIJIJIIJJIIJIJIJIIIIJJ = 252;

	public const byte IIIJIJIIIIJJJJJIJIJIJJIIJJJJIJIIIIJIIIIIJIIJJII = 251;

	public const byte JIIIIJIIIIIJIJJIIIJJJIIIIIIIIIJJJIJJIJIJJJIJIJI = 248;

	public const byte IJJIIJIIIIJIIIIIJJJJJJJJIJJJIJJIIIIJIIIIIJJIJJI = 222;

	public const byte JIJIJIIJIIJJJJJJJIJIIIJJIIJJJJJIIJJJJIJIJJIIIII = 221;

	public const byte IIIIIJIIIJJJIJJJIIJIJJJJIIJJJJJIIIJIIJJJJJJJJJI = 220;

	public const byte IIIJIIIJIJIJIJJIIJIJJJIIJIIIJJIJIIJIJIJIJIJJIJI = 219;

	public const byte IIJJJIJIIJIJJIIIJJJIIJJJIJIIIIIIIIJJJIIIIIIIIII = 218;

	public const byte IIJIJJIIJJIJIIIIJIJIIJIIJJIIIIIIJJIIIIJJIJJJJJI = 217;
}
