public class IJJJJIIIIJIJJJIJIIJJIIIIIIJIIIIIIJJJIJJJJJJIIJI
{
	public const string JIJIIIIIIIIJJIJJIJIJJJIIJJIJIJJIIJIIIIJIJJJJIII = "adcolony";

	public const string IJJIIIJJIJJJIJJJJIJJIIJJIIIJIIJJIJJIJJJJIJIJIIJ = "admob";

	public const string JIIJIIIIIIJJIJJJJIJIJIJIIJJIIIJJJIJJJJIJJIIIJJI = "amazon_ads";

	public const string JJJJJIJJJIIIJJJIIIIJJJIJIJIJIIJIJIIJJJIIIJJIIJJ = "applovin";

	public const string IIIJJIJIJIIJIIJJIIJJIJJJJIIJIJJIJIJIIJJJJIJIIJJ = "appnexus";

	public const string JJIIIIJIIIJJIIJJIIIJIJIIJIIIIJIJIIIIJJJIIJIIJJI = "appodeal";

	public const string JJJJIIJIJJJJJJIJJIJJJIJJJIJJJIJJIJJJJIJIJJIJIJI = "appodealx";

	public const string IIJJIIIIIIIJIJJJJJIJIIIIJIJIIJJJJIIJJIIIJJJJIII = "chartboost";

	public const string IIIJIIIJJJJIJJJJJIJJIIJIJJJIJIJIIJIIIJJIJJIJIIJ = "facebook";

	public const string JJJIIJIIIJIJIIIJIJJIJIJJJIIJIJJJJIJJJIIJIIIJIIJ = "flurry";

	public const string JIJJJJIIIIIIIJIIJJJIJIIJJIJIJIJIJJIIIJJJJIJJIJI = "inmobi";

	public const string IJIIIJJJIJJIJJJJIIJJIIJJJJIIIJIIIIJIIIJIJJIIJIJ = "inner-active";

	public const string JIIJIIIIIJJIJJIJIIIIIJIJIIJIIIJIJJJIJJJIJIIJJJI = "ironsource";

	public const string IIJIJJIJIIJJJIJJIIIJIJJIIIJJIIJJIJIIJJJIIJIIIJI = "my_target";

	public const string JJJIIJIIIIJJJJIJJIIJJJJIJJJJIJIIJIIJJIIIJIJIIII = "mintegral";

	public const string IIJIJJIIIJIJIIJIJJIIJIIJIIIIIJIJIJJIJJJIJIJIJIJ = "mopub";

	public const string JJJIJIIJIJJIJIJJIIJIIIJIIIIJJIIIJIJIJJIJJJJJIJJ = "mraid";

	public const string IJIIJJJIJIIJIJJIJJIIIJJIIJJIJIJIJIJJJJIJJJIJJIJ = "mraid_va";

	public const string JIIIJIIIJIIIJIJJJJJIIJJJIJIJJIIJJJJIJIIJIIJJJJJ = "nast";

	public const string IIJJJJIIJIJJJIJIJJIIJJIJJJIIJIIJIJJIJIIJIIJJJJI = "ogury";

	public const string IIIIJIJIJIIJJJJJJJIJJIJJIIJIIJJJIIJIIJIIIJIIIIJ = "openx";

	public const string IJJJIJJJIJIIJJIJJJIJJIJIJJIJIIIIIIIJJJIJIJIJJIJ = "pubnative";

	public const string JJIJIJJIJJJIJJJJJIIIJIIJIJJJJIIIJJIJJJIIJIJIIIJ = "smaato";

	public const string IIIJIJIIIJJIIJJJJIJIJIJJIIJIIIIIJIJIJIIJJIIIIIJ = "startapp";

	public const string JIIIJIIJIIIIIIJJJIIJIIJJIIIIJIJJIJJIJJJJJJJIIJJ = "tapjoy";

	public const string JIJJJIJIJJJIIJIJIIJJJJJJIJIJIIJJIIJIJIJJIIIJJJJ = "unity_ads";

	public const string IIJIJIIIIIIJJJJIJJIJJJIJIJJJJIJIIJJJJJIIJIJIIIJ = "vast";

	public const string JJIIJJIJIJIIIJIIJIIIIJJIJIJIIIJIIIJIJIIJJIJJJJJ = "vpaid";

	public const string JIJJIIJJJJIIJIIIIIJJIJIIJJJJIIJIIJIIIJJIIJJIIIJ = "vungle";

	public const string JJJIJIJJIJJJJIJIIJJIIIIJJIJJJIIIJJIIJJJJIIIJIJJ = "yandex";
}
