using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[Serializable]
[StructLayout((LayoutKind)0, Size = 12)]
public struct IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII : IEquatable<IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII>, IFormattable
{
	[StructLayout((LayoutKind)2, Pack = 1, Size = 4)]
	private struct IJIJIIJJJJJIJIIJIIIIJJIJJIIJJIIIIJIIJIIIIJJJIII
	{
		[FieldOffset(0)]
		public float JIJIJJJIJJIIIIIJIIIIIJJJJJJJIIIIJIIIJJJJIJJIIJI;

		[FieldOffset(0)]
		public int JJIIIJJJJIJIJJIJIJJJJJIJJJIIJIJJJIIIJJIJIJJIIII;
	}

	public int JJIJIJIJIIJJIJJJJIJJJJIIIIIJJJIIJIJJJIJJIJIIJII;

	public int IIIIIIJIJJIIJJJJJJJIIJIIIIJJIIJIIJJIIJJIIIIIJJJ;

	public bool IIIIJIJJJJIJIIJJIIIJIIJIJJJJIJJIJIIJJIJIJJJIIII;

	private static IJIJIIJJJJJIJIIJIIIIJJIJJIIJJIIIIJIIJIIIIJJJIII IIIIIJJJIIJIJJJIJIJJJJIJIIJJJIIJJJJIJIJJIJJJIII;

	public bool Equals(IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}

	public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
	{
		return null;
	}
	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JJJIIJJJIIJIJIIJIIJJJJJIJJJJIIJJIIIJJJJJJIJIIII(IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}
	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JJIJJJJIJIIJIIIIJJIJJJJIIIIIIIJJJIJJIIIIJIJJJII(IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}

	public string ToString(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI, IFormatProvider IIIJIIJIIJJJJJIIIIIJIJJJIIJIIIJIJIIJIJIIIIIJIJI)
	{
		return null;
	}
	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII IIIIIIJJIJJIJIJIJJJIIIIIIIIJIIJIIJIJJJJJJJIIJJJ(IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}

	public override string ToString()
	{
		return null;
	}

	public void JJIJJJIIJJIIJIIJIIJIIIIJIIJJJJJJIIJIIJIJJJIIJJJ()
	{
	}

	public static float JIIIJIJJJIIIIIJIIJIIJIJIIJJIJIJJJIJIJJIIIJIJJJI(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0f;
	}
	public static implicit operator IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}
	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JJJIIIJJJJIJIJIIIIIJIIJIJIJIIIJIJJIIJJIJIJJJIIJ(IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}
	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JJIJIJIJJJJIIIJJJIJJJJJIJJJJJIIIJJJIIJIJJJJIIJJ(IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}

	private IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		JJIJIJIJIIJJIJJJJIJJJJIIIIIJJJIIJIJJJIJJIJIIJII = 0;
		IIIIIIJIJJIIJJJJJJJIIJIIIIJJIIJIIJJIIJJIIIIIJJJ = 0;
		IIIIJIJJJJIJIIJJIIIJIIJIJJJJIJJIJIIJJIJIJJJIIII = false;
	}

	public void JIIIJJJJIIIIJJIJIIIJJJIIJJJIIJJJIJJIJIIIIIIIIIJ()
	{
	}

	public void IJIJIIIJJIJIJJJJJIJJJIJIJIJIJIIIJJJIJIJIJJJIIJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public float JIIJIIJJIIJIIIIIJIIJJIJJIIJIIJIIJJIIIIJIJIIIJIJ()
	{
		return 0f;
	}

	public string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(string JJJJJIIJIJJIJJIJIJIIJIJJJIIIJJIJJIIIIIIJJIIIJJI)
	{
		return null;
	}

	public int JJIIIJIIIIJJIIJJIJJIJIJIJJJJJIJJIJJJIIJJIJIJJJI()
	{
		return 0;
	}

	public float IIIIIJIJJJJJIIJIIIIIIJIJIIIJJIJIIJIJIIIIJIIJJII()
	{
		return 0f;
	}

	public override int GetHashCode()
	{
		return 0;
	}
	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII IJJJJIJIJIJIIJIJJJJIIJIJIIIIJJJIIIJJJIIIIIJJIIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}

	public string IJJJIIIIIJJIIJJJJIJIIIJIJIJJIJIJJJIJJJIJIIJIIIJ()
	{
		return null;
	}

	public static float IIJJJIJJIJIJIIJIIIJIIIJJIIJJJIJIIIIIIJJIJJJJJIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0f;
	}

	public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}

	public bool JIIJIIJJIIIJJJIJJIJIJIIJIIJIIIJJIJIJJJIJJIJIJII(IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}

	public float JIJJJIIIIJIJIIIIJIJJIJJJJIJIJJJJJJIJJIIJJIJIIII()
	{
		return 0f;
	}
	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII IIJIIJIJIJJJIIIIJJIIJJIIJJJIJIIJIIIIIIJIJJIJIII(IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}

	public void JJJIJIJIIIJJIJIIIIIIIJIJJIJJIIIJJIJIIIJJJJJJIJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static implicit operator float(IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return 0f;
	}

	public static int JIIJJJJIJIJIJIIIJJJJIIJIIJIJJJJIJJJIIIJJIJJJIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}
}
