using UnityEngine;

public class InputTouchLook : MonoBehaviour
{
	private Rect JIIIJJJJIJIIJJIJJJJIIJJJJJIJIIJJJIJIJIJJJIIIJIJ;

	private bool IJIIJJJJIIJJIJIJJIIJJIIIJJIIIJIIJIJJJJIIJIJIIJI;

	private int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ;

	private float IJIJIJJIIIJIIJJJIIJJJIIJIIIJIJIJJIIIIJJJIIJJJJJ;

	private Touch IJJJJJJIIIJJIJJIJJIJJIIJIIJJJJJIJJJJIIJJJJIIJJI;

	private bool JIIJIJIJIIJIIJJJIIJJIJIJIJIIIIJJIIJIJIJJIJIIIJI;

	private Vector2 IJJJJIIJJIJIIJIIIIJIJIIIJJIIIJIIIJIJJIJIJIJIIII;

	private float JIJJJJJIJJJJIJIJIJIJJIJIJJJJIJJJIJJJIIJIJJIJIII;

	public AnimationCurve JIJIJIJJJIJJIJJIIJIJIJJIJIJJJIIJJIJJIIJIJIJIIJJ;

	private Vector2 JIIIJJJJIJIIIIJJJJIJJJJIIJJIIIJJJJIIIIJJIJJIJJI;

	private float JIJJJIJIIJIJJJIJJIIIIIIIJIJIJJJJJIJJJIJIIJJIJII;

	private Vector2 JIJIIJJIIJJIIIJJJIIIJJIIJIIJJIJIJIIIJJJJJIIJIIJ;

	public static Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI;

	private void JJIJJJIIJJIIJIIJIIJIIIIJIIJJJJJJIIJIIJIJJJIIJJJ(Vector2 JIIJJJJJJIIJJIJIIIIIIJIIJIIIIIIJJJJJIJIIIJJJIJI)
	{
	}

	private void IIIJJJIJIIIJJIJIIJJIIIIJIIIJJJIIIIIJIIIJJIIJJII()
	{
	}

	private void IJJJIIJJIIJIJIJIIJIJIIJJJJJIJJJIJIJJIJJJIIJJJJJ()
	{
	}

	private void JJIJJJIIJIJIJIJIJJJJJIIJIJIIIIJJIIIJIIJJJJJIJIJ()
	{
	}

	private void JIJJIJIJIIJJJJJIIJJJIJIIJJIJIJJIJJJIIJJIIIJIIIJ()
	{
	}

	private void OnDisable()
	{
	}

	private void JIIIJIIJJJJIJIJJJIIIIIJIJJIIIIJJJJJJJJIJIIIIJJI()
	{
	}

	private void JJIIIJJJJJIJIIIJJJJIJIIIIJIJJIIIJIJJIIIJIIIIJII()
	{
	}

	private void IJJIJIJIIIIJIJIIJIJIIJIJIJJIIJIJIIJIJIIIIIJIJIJ()
	{
	}

	private void IJIJJIIJJIJIIIJIJIIJJIJIIJJJIJJIIIJJJJJIJJJIIII()
	{
	}

	private void JIIJIIIIJIJJJIIIIIJJIJJJJJJIIIJIIJJIJIJIJIJIIIJ()
	{
	}

	private void IJIJJJIIJIIJIJJIJIJIIIJIJIJJIIIIIIJJIJIJIJIJIJJ()
	{
	}

	private void IIIIJJJJIIJIJJJJIJJJJIJJIJJJIJIJIJIJIJJIIJJIJII()
	{
	}

	private void JIIIJIIIJJJIIIIIJIIIIJJIIJIIJIJIIJJJJIIIJIIJJJI()
	{
	}

	private void IIIIIJIJJIIJIIJIIIJIIJIJIJJIIIJJIIJJIJIIJIIJIJI()
	{
	}

	private void JIIIIJJJIIIIIIJIIIJJIIIJIIIJIJJIIJJIJJJJIJJJIJI()
	{
	}

	private void JIIIJJIIJIJJJJIJJIIJJIJIIIJJIIIJJIJJJIJIIJIJIJJ()
	{
	}

	private void Start()
	{
	}

	private void JJIIIJJJIIJJIJJJJJIJJJJIIJIIJJJIJJIIIJJJJJJIJIJ()
	{
	}

	private void JJJIIIIIIIJJJIIJIIIIJJJJIIIIIIIIJJJJJJJIIIJIIJJ()
	{
	}

	private void Update()
	{
	}

	private void JIJIJIIIJIIJIIIJIJIJIIJIIJJJIJJIJIIIJJIJJIJJJJJ(Vector2 JIIJJJJJJIIJJIJIIIIIIJIIJIIIIIIJJJJJIJIIIJJJIJI)
	{
	}

	private void JIJIJJJIIJIJIJIIIIIIJJIIIJIIIJIJJIJIIJJIJJJIIII()
	{
	}

	private void IJJJJIIIIJJIIIJJIJJJJJJIJIIJJJJJJJJIJJIIJIIIJIJ()
	{
	}
}
