using System.Runtime.CompilerServices;
using UnityEngine;

public class InputButton : MonoBehaviour
{
	public bool JJIJJIJIIJJIIIJIJIJJIIIJIJIIIJJIIJJJJJIIJIIJIII;

	public string IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ;

	private bool IJJJJJJJJIJJJIJIIJIJJJJJJIIIIIJIIIIJJIIIIJJJIJJ;

	private float IJIIJJIIJIJJJIJIJJJIIJJIIIJJJIIIJJJJIIJJIIJIIIJ;

	private UIWidget JJJJIIJJJIIJIIIIJIIIJIIJIJIIJIJJJJJIIJIJIJIJIII;

	public UIWidget JJIJJJIIIIIIIJIIIIIJJIIJIJIIIJJJJIJIJJJIJJIJIJI => JIIJIIIIJJJIIIJJIIIIJIIJIIJJJIIIJIJJIIJIIJJJJJI();

	private void JIJIJIIIJIJIJJJJIIIJIJIJJIJJIJJJJIIIIIIJIJIIJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	private void IIIIJJIJIIJIJIJIJIJIIJJIIIIIJIJIJJJJIJIJIJJJJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	private void JIIIIJJJIIIIIIJIIIJJIIIJIIIJIJJIIJJIJJJJIJJJIJI()
	{
	}

	private void IJJJIIJJIIJIJIJIIJIJIIJJJJJIJJJIJIJJIJJJIIJJJJJ()
	{
	}

	public void IJJIJIJJJJJJJIIIJIJIIIIJJJJIIJJIIJJJJIIIIJJJJII(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void JJJIJIIJJIIJJJIIIJJIIIJJJIJJIIJJIIIJIIJJIJIJJJJ()
	{
	}
	public UIWidget JJIIJIJJJIIJJIJIJJJJJJIJJIIIJJJIIJJIIJJJJIJJJJJ()
	{
		return null;
	}

	public void JIIIJJIIJIIIIIIJIIJJIJIJJJIIJJIIIIJJJJJIIIJJIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void IJIIJJJJJIIJIJIJJJJJIJIJIJJJIIIIIIIIJIIJJJIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	[CompilerGenerated]
	private void JJJIJJJJJJIIJIJIJIJJJJJIJIJIIJIIJJIIIJJJJIIIIJI()
	{
	}

	public UIWidget JIIJIIIIJJJIIIJJIIIIJIIJIIJJJIIIJIJJIIJIIJJJJJI()
	{
		return null;
	}

	private void JIJIIJJIIIIIIIJJIJIJIJJJIJJIJIIJJIJJJIJIIIJIIJJ()
	{
	}

	private void JIJIIJIJIJIIIJIIJJIIJIJJJJIIJIJIIJIJJIJIJJJIJII()
	{
	}

	private void JJIIIJJIJJJJIJJIJJIIIJIIJIJJIJIJJJIJJIIIJJJJIJJ()
	{
	}

	private void IIJJIIJJIIIIIJIJIIIIIJIIIIIIJIIIJIJJJIJIIIIJIII()
	{
	}

	private void OnDisable()
	{
	}

	private void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	private void JIJIJJIIJIJJIIJJJJJJJJIJJJJJJJIJIJJIJIJJIIJIIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	private void OnEnable()
	{
	}

	private void JJJJJIJJIIIIJJJJIIJJIIIJJJIJJJJJJIJJIIIIIJIJIJI()
	{
	}
	public UIWidget JJJIJJJIIIIIJIJIIJIIIJIJIJIJJJJIIJJJIJJIJJJIJII()
	{
		return null;
	}

	private void JJIJJJIIJIIJIIJJJJJIIIIIJIIJIIIJIIJIJIJJIJJIJIJ()
	{
	}

	public void JJJJIJIIJIJIIJJIIIIIJIIIJIJJJIJJIIIIIJJJJIJJJJJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void Start()
	{
	}

	public void IIJIIIJJJJIJIJJIIJJJIIJIIJIJJJIJIJIJIIJIJJIJJII(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}
	public UIWidget IJIJIJJIJIIIJIJJJIJIIJJJJIIJIIJJIIJJJIIIJJJJIII()
	{
		return null;
	}

	private void IIJJIJIJJJJJIJJIIJIJIJJIIJIJIIJJIIIJJIIIJIIIJJI()
	{
	}

	private void IIJJIJJIJIIJJIJJIJJIJJJIIJIJIJIIJJJJIJIJJIIJIII()
	{
	}

	private void IJIIJIIIIJJIIIIIIIIJIJJIIIJJJIJJIJIIIJJJJJIJIJI()
	{
	}
}
