using System.Runtime.CompilerServices;
using UnityEngine;

public class InputManager : MonoBehaviour
{
	public delegate void IJJJJJJJJJJJIIJIJJIIJIJJIJIJIJIJIJIIJIJJIIIIIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ);

	public static IJJJJJJJJJJJIIJIJJIIJIJJIJIJIJIJIJIIJIJJIIIIIJI IJJJJIJIJJJIJJJJIJJIJIIJJIIJIIJJJJJIIJIJIIIJJII;

	public static IJJJJJJJJJJJIIJIJJIIJIJJIJIJIJIJIJIIJIJJIIIIIJI IIIIJJJIIIIJIIIJIJJIIJJIJIJIIJIIIIJJJJIIIJIIIJI;

	public static IJJJJJJJJJJJIIJIJJIIJIJJIJIJIJIJIJIIJIJJIIIIIJI IIJJJJIIIJJIIJIIIJJIIIJJJJJJIIIJJJJJJIIJJJJIJJI;

	private static InputManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static Vector2 IIIIJJJIJIJJIIIJIJJIIIIIJJIIIIIJIIIIJJIJIJIJIJJ => JJJJJIJIIIIJIIJJJJJIJIJJJJIJIIJIJIIJJJJJIIIIIII();

	public static Vector2 JJJIJIJJIIJIJJJJIIIJIJIIIJIJIJJJIIJIIIIIIJIIJII => IJJIJJJIIIIIJJJJIIJIIJIIIJJIJIJIIIJJJJJJIJJIJJJ();

	public static Vector2 JJJJJIJIIIIJIIJJJJJIJIJJJJIJIIJIJIIJJJJJIIIIIII()
	{
		return default;
	}
	public static Vector2 JJJIIIJIIJJIIJJJIIIJIJIJIIJJIIIJJIIJJJJJJJIJJII()
	{
		return default;
	}

	public static Vector2 IJJIJJJIIIIIJJJJIIJIIJIIIJJIJIJIIIJJJJJJIJJIJJJ()
	{
		return default;
	}
	public static Vector2 JIIJJJIJJIIJJJJIIJIJIJJJIIIJJIIIIJJJJJJIIJIJIII()
	{
		return default;
	}

	public static void IIIJJIJJJJIJIIJIIIIIIIIIJJIIJJIJJJIIIJIJJJJIJIJ()
	{
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	public static void JIIJJJIJIJJJJJJIIJIIJIJIIJIIJJJJIIIIJJIIIJJIIIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void Start()
	{
	}

	public static void JJJJIJIIIJIIJJIIIJJIJJIIIJIJJIJJIJJJIJJJJIJIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public static void JJIIJIIJJIJIIIIJJJIJIJIJIJIJJIJIIJIJIIJIIJJIIJI()
	{
	}

	public static void IJIJJIIJJIIJJJJIJJIIIIIIJJIIJIIIIJJIIIJIIJJJIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}
	public static Vector2 IJIIJJJJIIJIIIIIIJIIIIIIJIIIJIJJJJJIIIIIIJJJIIJ()
	{
		return default;
	}
	public static Vector2 JJIJJJJIJJJJJJJIIJJJIIIIIJIIIIJJJIJIIJJIIJIIJII()
	{
		return default;
	}

	public static void IJIIJJIJIIJIJIJIIJIIJIJIIJIJJJJJIJJIJIJIJIIJIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public static void IJJJIJIIJJJJJJJIIIIIJIJIIJJIJJIIIIJIJJJJIJIIIIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public static void JJIIJIJJJJIIJJIJIJJJIJIJJIJIIIIIJIJIJIIIJIIJJII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}
	public static Vector2 JIJIIIJIIJJJJJJIJIIJIIJJJIJIIJJJIIIIIIIIIIJIIJJ()
	{
		return default;
	}
}
