using UnityEngine;

public class InputJoystick : MonoBehaviour
{
	public enum IIJJJIJIIIJJJIJJIJJIJIJIJJJIIJJIJIJJIJIJJJJJJIJ
	{
		Dynamic = 0,
		Static = 1
	}

	public Camera IIJJIIIJIJJJIIIJJJJJJIIJIIIJJIIIIIJIJJJIIIJIIII;

	public UISprite IJJJIIIIIJJIIJJJIJIIIIJJJIIJJJIIJIIIJIIIJIIJIII;

	public UISprite JJJJJIJJJJIJIJIIJJJIIJIJIIJJIJIIIJIIIIIIJIIJIJJ;

	public float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ;

	public string IIIJJJJJIJJIIJIJJJIJIIIIIJIJJJJJJJJIJJJIIIIJJJJ;

	public string IJIIJIJIJJIIJIJIJJJIJIJJIJIIJIJJIIIJJJJJJJJJIJI;

	public IIJJJIJIIIJJJIJJIJJIJIJIJJJIIJJIJIJJIJIJJJJJJIJ JJIIIJIIIIJIJJJJJIIIJIJJIIJJJJJIJJIJIJIIIJJJJJJ;

	private int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ;

	private Rect JIIIJJJJIJIIJJIJJJJIIJJJJJIJIIJJJIJIJIJJJIIIJIJ;

	private Vector3 JJIJJIJIIIJIIJJJJJJJJJIIIIJIIJIJJJJJIIJIIIJJIJI;

	public static bool JIJIIJIIIJJJJIIJJJIIJIJJIJJJJIJJJJIJIJJIIJIIIII;

	private float JIIIIJJJIJJIIJJIIIIJIIJIJJIJIIJIIJJIIIJIIIIIJIJ;

	private float JIIIJJJIJJIJIIIIJIIIIJIJJJIJIIJJJIIIIIIJJIIJIIJ;

	private float IJIIJJIIJIJJJIJIJJJIIJJIIIJJJIIIJJJJIIJJIIJIIIJ;

	public static Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI;

	private Vector3 JIIIJJIIIIIJIIJJIJIJJJIIJJJIJIIIJIJIIJJJIJJIJJJ(Vector3 JIIIIJJJJIIIIJJIJIIIJIJJJIJIIJJIJJIJJIJIIIJIIJJ, Vector3 IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI)
	{
		return default;
	}

	private void IJIJJIIJJIJIIIJIJIIJJIJIIJJJIJJIIIJJJJJIJJJIIII()
	{
	}

	private void Update()
	{
	}

	private Vector3 JIJJIIIJIIJJIIJJIIIIIJJJIIJIJJJIJJIIIIJIJJIIJIJ(Vector3 JIIIIJJJJIIIIJJIJIIIJIJJJIJIIJJIJJIJJIJIIIJIIJJ, Vector3 IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI)
	{
		return default;
	}

	private void JIJIJIIIJIIJIIIJIJIJIIJIIJJJIJJIJIIIJJIJJIJJJJJ(Vector2 JIIJJJJJJIIJJIJIIIIIIJIIJIIIIIIJJJJJIJIIIJJJIJI)
	{
	}

	private void JIJIIIJIJJIJJJJJJJIIIJIIIJJJJJIJIJIJJIJJJJIIIII()
	{
	}

	private void JJJJIJIJIIJJJJIIIIJJJIIIIJJIIIJJIJJIIJIIIIIIJIJ()
	{
	}

	private void IIIJJJIIIJJIJJJJJJIIIIIIIIJIIJJIJIJJJIJJIJIJJIJ()
	{
	}

	private void JJIJIIJIJIJJIIIIJJIJIJIIJJJIJJJJJIIIJIJJIIJJJII()
	{
	}

	private void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ()
	{
	}

	private void IJIJJIJIIJJIJIIJIJJJJIJIIJJIIIJJIIIJJJIIJJIJJJJ()
	{
	}

	private void Start()
	{
	}

	private void JJIJJJIIJJIIJIIJIIJIIIIJIIJJJJJJIIJIIJIJJJIIJJJ(Vector2 JIIJJJJJJIIJJIJIIIIIIJIIJIIIIIIJJJJJIJIIIJJJIJI)
	{
	}

	private void IJIIJIIIIJJIIIIIIIIJIJJIIIJJJIJJIJIIIJJJJJIJIJI()
	{
	}

	private void JJJJIJIJIIJIJJIIIJIJJIJJJJIJJIJJIIJIIIIJIIIJIJI(Vector2 JIIJJJJJJIIJJIJIIIIIIJIIJIIIIIIJJJJJIJIIIJJJIJI)
	{
	}

	private void JIIIIJJJIIIIIIJIIIJJIIIJIIIJIJJIIJJIJJJJIJJJIJI()
	{
	}

	private Vector3 JJIIJIIIIJJIJIJIIJJIJIIJJJJIJIIIJJJJJIIJJJIJJJJ(Vector3 JIIIIJJJJIIIIJJIJIIIJIJJJIJIIJJIJJIJJIJIIIJIIJJ, Vector3 IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI)
	{
		return default;
	}

	private void IJIJIIIIIJJJIIJIJJIJIIJIIJJIIIIJIJJJIIIIIIJJJII()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void OnDisable()
	{
	}

	private void IJIJJJJJIIJIIJIJIIIJJJIIIJIJIJIJJIJIJJJJJIJJJJJ()
	{
	}

	private void IIIJIJJIJJIJIJIJIJIIIIJIIJJIIIJJJIJJJJIIJIIJIIJ()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void IIIJJIJIIIIJIJIJJIJJJJIIIJJIJIIIIJIJIIJIIIIIJII()
	{
	}
}
