using UnityEngine;

public class JIIIJJJIJIJIIJJJJJIJJIIIIJIIIIIIIJIJJIJIJIJIJIJ : PropertyAttribute
{
	public string[] JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ;

	public int IJIJJJJIJJJJIIJJIJJIIJIIIIIJJIJIIJIIIIJJJJIIIIJ;

	public JIIIJJJIJIJIIJJJJJIJJIIIIJIIIIIIIJIJJIJIJIJIJIJ(params string[] JJIIJIIIIIJIJJJJJJIJIJIIJJJJJJJIIIIJIJJIJJIJIII)
	{
	}
}
