using System.Collections.Generic;

public class JIIIIIJIIIJIJIJIIJJJJIIIJIIJIIJJIJJJJIIJJJJJIJJ
{
	private sealed class JJJJJIJJIJIIIJJJIJIIJIJJJJJIJIJJIIJIIIIJJJIIJII
	{
		public string JJIJJIJJIJJJIIJIJIIIJJIIJJIIJJIIJJJIIIIJJIIIIJJ;

		internal void IJIIIIJJJJJIJIIIJIIJIIIJIIIIJIJJIIJJIJJIJIJIJJJ()
		{
		}

		internal void IIIIIIIIIIJIIJIJJJJIIIIIIJIIJIIJIIIJJIIIIIJIIJI()
		{
		}

		internal void IIJJJIJJIJIIIIIIIJIIIJIIIIJIJJIIIJIIJIIJIJJJIII()
		{
		}

		internal void IJIIJJIIJJIJIJIJJJIIIJJJJJIIIIIIJIJJJJJIJJIIIJJ()
		{
		}

		internal void IJIJJIJIIIJJJIIIIIIIJIIIIJJIJIJIJIJJJJJIJIJIJII()
		{
		}

		internal void JIJJJIIJJJJIJJIIJJJIJIIIIIJIIIJIIJJJIIJJJJJJIJJ()
		{
		}

		internal void JIIIIJIIIIJIIJIIJIJJIJIIIIIIJIIJJIJIJJIJJJIIIIJ()
		{
		}

		internal void IIIJIIIJJJIIIIJIIIIJIJJJJJJJIJJJIIJJJJIIJJJIIJJ()
		{
		}

		internal void IJIIIIJJJIJIIJIIJJIJJJJIJIJJJJJIIJJIIJIIJJIJIII()
		{
		}

		internal void JJIIIJJJJIJJIIIIJJIIJIIJIJIJIIJIJJJIIJIIIIIJJIJ()
		{
		}

		internal void IIIIIJIIJIJIJJIJJJIJIIIJIJIIJJJJIJJIIIJIJJIIJJI()
		{
		}

		internal void IIJJIJJIIIIJJJIIIJJJJIIIIJJIIJIJIJJJIJIJJJJIJJI()
		{
		}

		internal void JIIIIIJJIJJJIJIIIJJIJJIJIIJIJIJIIJJJIIJIIJJIJIJ()
		{
		}

		internal void JIJIIIJJJIIJIJJJIIJJJIIIIJIJIJJJIJIJJIIJIIJJJII()
		{
		}

		internal void JIJIJJIJJJJJIIIJIIIIIJJIIIIJIIJJJJIJJIIJJJJIIII()
		{
		}

		internal void IIIJIJIIJIJJIIJIJIIIIJJIJIIJJJJJJJJIJJJIJJJJJII()
		{
		}

		internal void IJIIIJIJJIJIJJJIIJIIIJJIJIJJJJJJJJIJIIJJJJIIJJJ()
		{
		}

		internal void JIIJIIJIIIJJIJIIIJIJIIJJJIJJIJIIJIIIIJJIIJJIJJJ()
		{
		}
	}

	private static GameMode JIIIIJJJJJIIIIJIJIJIIJIJIIJJJIIJJJJIJJJJIJIIIJI;

	private static IJJIIJJIIJIIIJIJIIJIJIIJIIJJJIJJIIIJIJJJJJIJJII JIIIJJJIIIJJJJJIIIJJJJJIIJJIIIIIJIJJJJIIJIJJIII;

	private static IJJIIJJIIJIIIJIJIIJIJIIJIIJJJIJJIIIJIJJJJJIJJII IIIJJJIIJIJIJJJJIIIJJJIJIIJIJJJJJJIIJIJJJJJJJJJ;

	private static IJJIIJJIIJIIIJIJIIJIJIIJIIJJJIJJIIIJIJJJJJIJJII IIJJJIIJIJIJIJJIIIIIJJIJJIIJJJIIIIJJJIIIJIJJJIJ;

	private static IJJIIJJIIJIIIJIJIIJIJIIJIIJJJIJJIIIJIJJJJJIJJII IIIIJJJIIJJJIJJJIJIIIIJJIJIJJJIJJIIIJIIJIIIIJJI;

	private static IJJIIJJIIJIIIJIJIIJIJIIJIIJJJIJJIIIJIJJJJJIJJII IJIJIIIIJIIJIIIJIJJIJIIJIIJJJJIIJJIJJIJIIJIIJJI;

	private static Dictionary<string, int> JIJJJIIIJIJJJJJIJIIIIJJJJIJIIJJIIJIIIJIJIJJJIJJ;

	private static float JJJIIJJJJIJIJIJJIJJIIIJJIJIJIJJJIJJIJIJIJJIIIII;

	private static float JIIIJIIJJIJIJJJIIJJJIJJJJJJIIIIIJJJJJJJJIIJIJIJ;

	public static bool JJIIIIIIJIJIJIJJIIJJIJJIIJJIIJJIIJJIJJJIJJIIJIJ => JJIJIIJIIJIJIIIJJJIJJJIIIIIIIIIJJIJIJIJIIJJJJJJ();

	public static int IIIJIJJIJIIIJJJJJIJJIJJIJJIJIJIJIJIIJJJJIJJIJJI()
	{
		return 0;
	}

	private static void IJJJIIJJIIJJJJIIJJIJIIIJIIJJIJIJJIIIJJJJIIIJIJI(string JJIJJIJJIJJJIIJIJIIIJJIIJJIIJJIIJJJIIIIJJIIIIJJ)
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ()
	{
	}

	public static float JJJJIIIJIJJJJJJIIJIIJJIJIJJIJIIJIIJIJIJIIIJJJJJ()
	{
		return 0f;
	}

	public static void JJIIJJIIIIJJIJJJJJIIIIIIIJIIIJIIIIIJJJJIJJJJJII()
	{
	}

	public static int IIIIJIIIJJJJIJJJJJJJJJJJIJIJIJIIJIIJJIIJJJJIIJJ()
	{
		return 0;
	}

	public static int JIJJIJJJIJIIJJJJIIIJIJIIIIJJIIIIJIIIJJIJIJIJIIJ()
	{
		return 0;
	}

	public static void JIIJIIJJJJIJIIIIIJJJJJJJJJJJJJJJJIJIIIIIJJJIJIJ(int JIIJIIIJJJIJJJIIJJIIIIJIJIJJIJJIIJIIJIJIIJJIIJI)
	{
	}

	private static void IJIIJJJIIJJIJJIIIJIIJJIJIIIIJJJIIJJJIJJIJIJIJIJ()
	{
	}

	public static int JJIJJJIIJIJIJIJJJIJJIJJJIJIJJJIJJIIJJIJIJIIJIJJ()
	{
		return 0;
	}

	public static int JIJIIJIIJJIJJJIJJIJIJJIJJIJJIJIIJIIJIIJIJIJIJJJ()
	{
		return 0;
	}

	public static int JJIIIJIJJIIIJIIJJIJJJJIIIIJIJJIJIJJIJJJIJJIIJJI()
	{
		return 0;
	}

	public static int IJJIJJIIJJJIJJJIIJIIJJIIJJIIJJIJIIJJJIIIJIIIIJI()
	{
		return 0;
	}

	public static void JIJIIJJIIIJJJJJJIJJJIIJIIJJJJIIIJJJIIJJIJJJJJIJ(int JIIJIIIJJJIJJJIIJJIIIIJIJIJJIJJIIJIIJIJIIJJIIJI, bool IJIJIJIJIIJJIJIJJJIJIJJIJJJIJJJIJIIJJJJIJJIJJII)
	{
	}

	public static void IJIIJIIIIJIJIIIIJIIIIIIIIJIIIJIJIJIJIJJJIJJJIIJ()
	{
	}

	public static void IIJJJIIJIJIJIIJIJJIJIIJIJJIIJIIJIIIJIIJIJIJJIJJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
	}

	public static int IJJIJIJJJIJIJIJIJIIJJIIIJIJIIIIJIJJJJIIJIIJIJJI()
	{
		return 0;
	}

	public static void JIJIIJJIIIJJJJJJIJJJIIJIIJJJJIIIJJJIIJJIJJJJJIJ(int JIIJIIIJJJIJJJIIJJIIIIJIJIJJIJJIIJIIJIJIIJJIIJI)
	{
	}

	private static void IJJJIIJJJJIJIJIJJJIJIJJIIIIIJJJIIIJJIIJJJIIIIJJ()
	{
	}

	public static void IIIIIJIIJIJIJIIIIJIJIJJIJIIIJIIIIJJJJJJJJJJIJJI(int IJJIIIJJIJIIIIJIJJJJIJIIIIJIIJIJJJJJIJIIJIJJJJJ)
	{
	}

	public static void IJIJIIIJIIIIJJJIIJJIIIJIIIJIIIJJJIJIIJIIJIJIJII()
	{
	}

	public static int JJIIIIIJIJIIIIJIJJIIIJJIJJJJIJIJJIIIJIIIJJIIJIJ()
	{
		return 0;
	}

	public static float IJJJIJJJIIIJIJIIIIJJIJJJIIJJJJJIJIJJIJIJJJJIJJJ()
	{
		return 0f;
	}

	public static float JJIIJJJIIIJIJIIJIJIIIJJIJIJIIJJJIJJIJJJJJIIJJJI()
	{
		return 0f;
	}

	public static void JJIIIJJJJIIIIIIIIJIIIIJJJIJJJJJJJIJJJJJJIJIIJJJ(int JIIJIIIJJJIJJJIIJJIIIIJIJIJJIJJIIJIIJIJIIJJIIJI, bool IJIJIJIJIIJJIJIJJJIJIJJIJJJIJJJIJIIJJJJIJJIJJII)
	{
	}

	public static bool JJIJIIJIIJIJIIIJJJIJJJIIIIIIIIIJJIJIJIJIIJJJJJJ()
	{
		return false;
	}

	public static int JJIIJIJIIJJIIIJIIIIJJJJJJJJJIJJJJJJIJJIJJIJJIII()
	{
		return 0;
	}

	public static GameMode IJIIJIJIJJJIIJIIIIIIIJJJJJJIJIJJJJJIJIJIIIIJJIJ()
	{
		return GameMode.TeamDeathmatch;
	}

	public static void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}

	public static int JIJJIIIIJJIJJJIJJJIJIJIJIIIIIIJJJJJIIIJJIIJIIJJ()
	{
		return 0;
	}

	public static void JJJIJIIJJJIIIJIIJJJIIJIJIIIIJIJIIIJJIJIIJIIIIIJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
	}

	public static void IJJIIIIIJJJIIJJJIIIIJJIIIIJJJJJJJJJIJJJJJJJIJJI()
	{
	}

	public static GameMode IIIJJIJIJIJJJIIJJIIIIIIIIJJIIJIIJIJIIJJJIIJJIII()
	{
		return GameMode.TeamDeathmatch;
	}

	public static void IIIIIJIIJIJIJIIIIJIJIJJIJIIIJIIIIJJJJJJJJJJIJJI(int IJJIIIJJIJIIIIJIJJJJIJIIIIJIIJIJJJJJIJIIJIJJJJJ, bool IJIJIJIJIIJJIJIJJJIJIJJIJJJIJJJIJIIJJJJIJJIJJII)
	{
	}

	private static void IJIJIIJJIJIIIJJJIIJJIIJJIJJJIJJJIJIIJJIJIJJIJJI(string JJIJJIJJIJJJIIJIJIIIJJIIJJIIJJIIJJJIIIIJJIIIIJJ)
	{
	}

	public static int JJIIJJJJIIIJJIIIIIJJIIJIIJJJIIJJIIJJJIJJIIJJJJI()
	{
		return 0;
	}

	public static float JIIIIIIJJJJJJIJIJIIJIJJIIJIIIIJIIIJIJJIJIJJIIII()
	{
		return 0f;
	}

	public static void IJJJIIJIJJJIIJJIIJIJIJIJJIIJJIIJIIIJIJIIIJIJJJJ()
	{
	}

	private static void JJIJIIJIIJIJJIJJJJJJJIIJIJIJIIJJIJIIJJIIIJJJIII(string JJIJJIJJIJJJIIJIJIIIJJIIJJIIJJIIJJJIIIIJJIIIIJJ)
	{
	}

	public static int IIIJJIIJIIIJIJIIIJJIIJJJJIJJIIJIJIIIIIJJJIJIIJJ()
	{
		return 0;
	}
}
