using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;

public sealed class JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI
{
	private enum JIIJJJIJIIJJJJIJJIJIIIJIIIIJJIIJIJJJIJIJJJIIJJI
	{
		Normal = 0,
		LineComment = 1,
		BlockComment = 2
	}

	private class IJJIIJJJIIIIJIJJJIJJIIJIIJJIJIJIIIJIIJIIJJJIJJJ
	{
		public RuntimeFieldHandle JJIJJIJJIJJJJJIJIJIJJJJJIJIJJIJJJJIIJJIIIIJIIJJ;

		public object JIIIIJJIJJJIJJJJIJIJIJJJJJIIIIJIIJJIIIJIIIIIIJJ;

		public IJJIIJJJIIIIJIJJJIJJIIJIIJJIJIJIIIJIIJIIJJJIJJJ(RuntimeFieldHandle IIJIIIIJIIIJJJJJJJJJJIIIJIJJIIIJJIIJIIJJIIIIJII, object IJIIIJJJJIIIIJJIIJJIJJIIJJIIIIIIIIIIJJJJIJJJJII)
		{
		}
	}

	private static string IIJJJJIJJJJIIIIIJJJJIIIJJIIJJJIJJJIJIIJJJJIIJII;

	private static int JIJJJJIJJIIIJIIIIJIIJIJIIIIJIIIJJIIJIJJJJIJJJJI;

	private static Type IIJJIJJIJJIIIIJJJJIIJJJJIIJIJIIIIIJIIIIJIIJIJIJ;

	public static bool JJJIIJIJJIIIJIIJJIJIJIIIIJIJJIIIJIIIJIIIIJIJIII;

	private static JIIJJJIJIIJJJJIJJIJIIIJIIIIJJIIJIJJJIJIJJJIIJJI IJJIJJIJJIJJJIJIJJJIIIJJIIIIJJJJIJIIIJJJIIIIJII;

	private Type JJJIIJJIIIJJIIIIIJIIJIIJJJIJJJJJJIJIIJJJIJIJIII;

	private List<IJJIIJJJIIIIJIJJJIJJIIJIIJJIJIJIIIJIIJIIJJJIJJJ> JIIIJIJJIIIJJIIIJJJIIIIIJJIJJJIJIJJJIJIIJJJIJIJ;

	public Type JJJJIJJIIJJIJIIJJIIIIIIIIJIJIJJIIIIJIIIJIJJIJJI => JJIIJIIJJIJIJIIIIIIJIIIJIJIJIJIIJIJJIIIIIJJIJIJ();

	public static string JIJJJIJJJJIJJIIIJJJJJJJIJJJIIJIJJJIJJJJIJIIJJIJ(Component JIIIJIIIJIJJJIIJIJJIIJIIIIIIJIIIIIJJIJIIIIIIJJI, string JIIJIJIIJJJJJIIJIJIJJIJIIJJJJIIJJIJJJIJIIIJIJJI)
	{
		return null;
	}

	public static string JJJIJJJJIJIIJIJJIJIJIIIIIJIJJJJJIIIJJJIJJJJJJII(JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI JJJJJIIIIIIIJJJIJJIIIJIJIJJJIIJIJIJJIIIIIIJIJII, Component IIJJJJIJJJIJIIJJJJJJJIIJIJIJIJIIIJJJIIJIJIJIIIJ, string JIIJIJIIJJJJJIIJIJIJJIJIIJJJJIIJJIJJJIJIIIJIJJI, JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI JIIJJJJJJIIJIJIJJIJIIJIJJJIIIJJIIIJIIJJJIIJIIII)
	{
		return null;
	}

	public static Type JIIJJIIIIIJJJJIJJIJIIIJIJJJIIJJJJJJJIIJIJJIIJIJ(TextAsset JIJIJJJJIJJIJIJIJIJJIIJIJJJIJIIJIIJJIIJIIIJJIIJ)
	{
		return null;
	}

	public bool JIJJIIJIIJIIJJJJIJJIIIJJJJJJIJJIIJJJJIJIIIIIIJI(string JIIJIJIIJJJJJIIJIJIJJIJIIJJJJIIJJIJJJIJIIIJIJJI)
	{
		return false;
	}

	public static JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI JJIIIIIJJJJJJJIJJIIJIIIJJJIIIIIJIIJJJJJIJIIJIIJ(Component JIIIJIIIJIJJJIIJIJJIIJIIIIIIJIIIIIJJIJIIIIIIJJI, string JJIJIIJIIJJJIIIJIIJJIJJJJIJIIIJIIIIIJJJJIIIJJJJ)
	{
		return null;
	}

	public static Type IIJJIJJIIJJJIIIIIIIJIIIJJIIIJJJJIJIIIIJIIIIJJJI(string JIIJIJIIJJJJJIIJIJIJJIJIIJJJJIIJJIJJJIJIIIJIJJI)
	{
		return null;
	}

	public static string IJIJJJIJJJJIIJJJJIIIIJJIIIIIIJJIIJIIJIJIJJJJIIJ(Component JIIIJIIIJIJJJIIJIJJIIJIIIIIIJIIIIIJJIJIIIIIIJJI, string JIIJIJIIJJJJJIIJIJIJJIJIIJJJJIIJJIJJJIJIIIJIJJI)
	{
		return null;
	}

	private static int JIIIJJIIJIIIIJIIIJJJIJIJJIIIIIIIIJJJIJIIIJIIIIJ(string[] IJIIIJJJJIIIIJJIIJJIJJIIJJIIIIIIIIIIJJJJIJJJJII)
	{
		return 0;
	}

	private static object IJIIIIJJIJJIJJJJJIJJIJJIJJIIIJIIIIJJJJIJIIJIIIJ(FieldInfo JJJJIJIIJIJIJIIIIJIJJJIIIIJJJJIIIIJIIJJIJIJIIJJ, string[] JIIJIIIIIJIJIJIIJJJJJIJIIJJJJIJJIIJJIJIJJJJJJIJ)
	{
		return null;
	}

	private void JJIIIIJJJIIIIJJIJIJJIJIJIJIJIIJIIIIIJIIIJIJJJIJ(List<string> JIJIIJJJJIIIIIIIJJIJJJJIJIIJIJJJJJJIJIIIJIJIIJJ)
	{
	}

	public static Type IIIJJIIIJIIIIIJIIJJJIIIIIJJJJJJJJIJJJJJIJIJIIJJ(string JIIJIJIIJJJJJIIJIJIJJIJIIJJJJIIJJIJJJIJIIIJIJJI)
	{
		return null;
	}

	public Type JJIIJIIJJIJIJIIIIIIJIIIJIJIJIJIIJIJJIIIIIJJIJIJ()
	{
		return null;
	}

	private static void JJJIIIIJJIIIJIIJIJJJJIIIIJIIJIIIIIJJIIJJIJIIIII(string IJIJIIJIJJIJIIIJIIIIJJJJIIJIJIIIJJJIJIJJIJIIIJJ)
	{
	}

	private static void IJIJJIJIIIJIJJIIJIIJJJJIJJIJIJIJIIIJIIJJIIIJIJJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private static void IIJIIJJJJJIJJJJJJIJJJIJJJJJJJIJIJIJIJIJIIIIJIIJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private static string IJJJJJIJIIIIIIIIJJJIJJJIIIIJJJIIIJJJIJJJJIIJJIJ(string[] IJIIIJJJJIIIIJJIIJJIJJIIJJIIIIIIIIIIJJJJIJJJJII)
	{
		return null;
	}

	public static bool JIJIJJIIJIJJJIJIIJIJIIIIIJJIJJJIIJIJIIJJIJIIJII(Component JIIIJIIIJIJJJIIJIJJIIJIIIIIIJIIIIIJJIJIIIIIIJJI, JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI JIJIIIJJIIJJJJIJIJJJIJJJJIIIIIJIJJJIJJIIJIJJJII)
	{
		return false;
	}

	public static string JJJJJIJIJIJJIJJJIJIIJJJIIIIJIJJJIJIIJIJJIJIJJIJ(string IJJJJIJIJJIIIIIJJJIJJIIJJJJIIIIJJIJIIIIIIIJIIIJ)
	{
		return null;
	}

	public Type JJIIJJJIIJJIJIJJIIIIJJIIIIJIJJIJJIIJIJJIJIIJJJI(string JIIJJJJIIIJIIJIJIIIIIIIJJJJIIIJJIIIJIJIJJJIJJII)
	{
		return null;
	}

	public object JIIIIIJJIJIIJJIJJJJIIJJIIIJIJIIJIIJJJIIJJJIIJIJ(string JIIJJJJIIIJIIJIJIIIIIIIJJJJIIIJJIIIJIJIJJJIJJII)
	{
		return null;
	}

	private static bool IJIJIJJIIIIJJIJIIJJJIJIIIIIJIJJIJJIJIIJIIJJIJJI(string[] IJIIIJJJJIIIIJJIIJJIJJIIJJIIIIIIIIIIJJJJIJJJJII)
	{
		return false;
	}

	private void IJJIIJIJIIJIIJIJJJJJJJIJIIIJJIJIJJJIJJJJIJJJJJJ(List<string> JIJIIJJJJIIIIIIIJJIJJJJIJIIJIJJJJJJIJIIIJIJIIJJ)
	{
	}

	public static string IIIJJIJJJIIJIIIIJJIIIIJJIJIIJJJJJIJIJIJIJIJJIII(JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI IIIIIIIJJJIIIIJIJJJJIJIJIJIIIJJIJJJJJIJJJJJIJIJ, string JIIJIJIIJJJJJIIJIJIJJIJIIJJJJIIJJIJJJIJIIIJIJJI, bool IIJJJJIJIJJJJJJIIJJIIIJJJJIJJIJIJJIJJJJIIJJJJJJ = false)
	{
		return null;
	}

	public static bool IIJJJIIIIJIJJJJIIJIJJJJJJIJJIIIIIIJJIIJJJIJJJJI(Component JIIIJIIIJIJJJIIJIJJIIJIIIIIIJIIIIIJJIJIIIIIIJJI, string JIIJIJIIJJJJJIIJIJIJJIJIIJJJJIIJJIJJJIJIIIJIJJI)
	{
		return false;
	}

	public static JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI JIJJIIJJJIIJIJIIIIJJJJJJIIJIIJJIJIIIIIIIJJIJJIJ(Component JIIIJIIIJIJJJIIJIJJIIJIIIIIIJIIIIIJJIJIIIIIIJJI)
	{
		return null;
	}

	private static float IJJIIIJIJIJIJJIIJIIIJJJJIJJJJJJIIIJJJJIJIJIIIII(string[] IJIIIJJJJIIIIJJIIJJIJJIIJJIIIIIIIIIIJJJJIJJJJII)
	{
		return 0f;
	}

	public bool IJJIIJJJJJJIJJIIIJIJIJJJJJIIIJIJIJJIJJIIJJIJIII(TextAsset IJIJIJIIIJJIIJJJJJJIIJJJJJJJIIJJJIIJIIJIIIIJJJI)
	{
		return false;
	}

	public static string JJIJIIIIIJJIJJJIJIJIIIJJJJIJIJJJJJIIIIJJIJJIIJJ(JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI IIIIIIIJJJIIIIJIJJJJIJIJIJIIIJJIJJJJJIJJJJJIJIJ, string JIIJIJIIJJJJJIIJIJIJJIJIIJJJJIIJJIJJJIJIIIJIJJI, bool IIJJJJIJIJJJJJJIIJJIIIJJJJIJJIJIJJIJJJJIIJJJJJJ = false)
	{
		return null;
	}

	public bool JJIIIIIJJJJJJJIJJIIJIIIJJJIIIIIJIIJJJJJIJIIJIIJ(string JJIJIIJIIJJJIIIJIIJJIJJJJIJIIIJIIIIIJJJJIIIJJJJ)
	{
		return false;
	}

	private static Vector4 IIJJJIIIJJIJJIJJJJJIJIJIIJIJIJIJIJIJIIJJIJIJJJI(string[] IJIIIJJJJIIIIJJIIJJIJJIIJJIIIIIIIIIIJJJJIJJJJII)
	{
		return default;
	}

	private static Vector2 JIIJIIIIIJIJIJJJJIIJIJJIJJJIIIIIIJIIIIJIJIIJJJI(string[] IJIIIJJJJIIIIJJIIJJIJJIIJJIIIIIIIIIIJJJJIJJJJII)
	{
		return default;
	}

	private static string IJIIIJIIIIIJJIIIJJJIJIJIJJJIIJJJJIJIIIJJIJJJIJI(string IJIJIIJIJJIJIIIJIIIIJJJJIIJIJIIIJJJIJIJJIJIIIJJ)
	{
		return null;
	}

	public void JIIIIIJIIIIIIIIJJIJIIJIIJJIIJIJJIIJJIJIJJIIJJIJ(Component JIIIJIIIJIJJJIIJIJJIIJIIIIIIJIIIIIJJIJIIIIIIJJI)
	{
	}

	public static JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI IJJIIJJJJJJIJJIIIJIJIJJJJJIIIJIJIJJIJJIIJJIJIII(Component JIIIJIIIJIJJJIIJIJJIIJIIIIIIJIIIIIJJIJIIIIIIJJI, TextAsset IJIJIJIIIJJIIJJJJJJIIJJJJJJJIIJJJIIJIIJIIIIJJJI)
	{
		return null;
	}

	private static bool JJIJIIJIIIIIJJJIIIIJJJIJIIJJIIJJJIIJJJJJJIJIJJJ(string[] IJIIIJJJJIIIIJJIIJJIJJIIJJIIIIIIIIIIJJJJIJJJJII)
	{
		return false;
	}

	public static JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI JJIJIJJIIIJIIIJIJJJIJIJJIIJIIIJIIJJIJJJIJJJJJII(Component JIIIJIIIJIJJJIIJIJJIIJIIIIIIJIIIIIJJIJIIIIIIJJI, string JJIJIIJIIJJJIIIJIIJJIJJJJIJIIIJIIIIIJJJJIIIJJJJ)
	{
		return null;
	}

	public static string JJIJIIIIIJJIJJJIJIJIIIJJJJIJIJJJJJIIIIJJIJJIIJJ(Component JIIIJIIIJIJJJIIJIJJIIJIIIIIIJIIIIIJJIJIIIIIIJJI, string JIIJIJIIJJJJJIIJIJIJJIJIIJJJJIIJJIJJJIJIIIJIJJI)
	{
		return null;
	}

	public static JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI IJJJIJIIIJIJIIJIJIIJIIIIIIIJIIIJJIIJJIJJIJJIIJJ(Component JIIIJIIIJIJJJIIJIJJIIJIIIIIIJIIIIIJJIJIIIIIIJJI, string JJIJIIJIIJJJIIIJIIJJIJJJJIJIIIJIIIIIJJJJIIIJJJJ)
	{
		return null;
	}

	private static Vector4 JIJIJJIIIIIJJJJJJIJIJJIJJIIJJJJJIIIIJJIJJJIJIJI(string[] IJIIIJJJJIIIIJJIIJJIJJIIJJIIIIIIIIIIJJJJIJJJJII)
	{
		return default;
	}

	private static void JIJJIIIIJJJJJIIIJIIIJJJJJJIIJIIIJJJJIIIIJIJJJJI()
	{
	}

	public static bool JIJIIIJIJIJJIJIJIIJIJJIJJJIIIIIIIIJJJJIIIIIIJII(Component JIIIJIIIJIJJJIIJIJJIIJIIIIIIJIIIIIJJIJIIIIIIJJI, string JIIJIJIIJJJJJIIJIJIJJIJIIJJJJIIJJIJJJIJIIIJIJJI)
	{
		return false;
	}

	private static void JJIIJJJIIIIIJJJIIIIJJIIJIJIJJJJIIIIJIJJIIIJJIIJ(string IJIJIIJIJJIJIIIJIIIIJJJJIIJIJIIIJJJIJIJJIJIIIJJ)
	{
	}

	private static Vector4 JJJJIIIJJIIJIJJIIJJIJIIJIIIJJJIIIJJIIJJIIJJIJIJ(string[] IJIIIJJJJIIIIJJIIJJIJJIIJJIIIIIIIIIIJJJJIJJJJII)
	{
		return default;
	}

	private bool IIJIJIIJJJJJJIIJIIJJJIJJJJJJIJIJJJIJIJJIIJIIIII(string IIJJJIIJIIJIJJJJJIJIIIJJJJIIJJJJIJIJJIJIJJJJJII)
	{
		return false;
	}

	public static bool JJJIJJJIIJIJIIIJJIJIJIIJJJJIIIIJJIJIIJIJJIIIJII(Component JIIIJIIIJIJJJIIJIJJIIJIIIIIIJIIIIIJJIJIIIIIIJJI, JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI JIJIIIJJIIJJJJIJIJJJIJJJJIIIIIJIJJJIJJIIJIJJJII)
	{
		return false;
	}

	private static string IJIIIIIJJJJIIJIJIJJIIIJIIIJJJIIJIJJJIIJJJJJIIIJ(string IJIJIIJIJJIJIIIJIIIIJJJJIIJIJIIIJJJIJIJJIJIIIJJ)
	{
		return null;
	}

	private static Vector3 JJJJIIJJJJIJIJJIIIIJJJJJJJIIIIIJJJJJJIIJJJIIJJJ(string[] IJIIIJJJJIIIIJJIIJJIJJIIJJIIIIIIIIIIJJJJIJJJJII)
	{
		return default;
	}
}
