using System.Runtime.CompilerServices;
using UnityEngine;

public class JIIIJIJIIIJJJJJJJJJJIJIIJJIJJJIJIJIJIJIJJJJIJIJ : AndroidJavaProxy
{
	private object JJJIJIJIIIIIIJIIJJJJIIJJJJJIIJJIIIIIJIJJIIJJIII;

	private string IIJIIIJIIIIJJJIJJIIJJJIJJIJIJJJIJJJIIIIIIJJIIJJ;

	public string IJJJIJJIJIIIJIIIIJIIIIIIIJJIJIJIIIJIJJJIJJIIJIJ
	{
		get
		{
			return IIJJIIJJJIIJJJJJJJJJIIJJIIJJIJIJJJIIIJJJJJIIJJJ();
		}
		private set
		{
			IIIIJIIIJJJIJJJIIIIIJJIIIJJIIJIIJJJJIJIJIJJIIJI(value);
		}
	}
	public string JIIJJJIJIJJJIIIIJIIJIIJIIIIJJIIIIJJIIIIIJIJJIII()
	{
		return null;
	}

	public void JIIJIJJIIIIJJIIJIIJJIIJJIIIJIJJJIIIIIJIIJIJJJJI(string result)
	{
	}
	public string IIIJIIIJIJIJIJJJIIIJJIIIJJJJIIIIJJJIIJJJIIJIIII()
	{
		return null;
	}
	public string IJIIJIIIJIJJIIIJJJIJIIIIIJJIIIIJJJJIJJJIIJJJJIJ()
	{
		return null;
	}

	public JIIIJIJIIIJJJJJJJJJJIJIIJJIJJJIJIJIJIJIJJJJIJIJ(object JJJIJIJIIIIIIJIIJJJJIIJJJJJIIJJIIIIIJIJJIIJJIII)
		: base((string)null)
	{
	}

	public void JIJJJIJIJJIJJJIJJJJJJIJIIIIJJIIJJJJJJIJIJJIJIIJ(string result)
	{
	}
	private void JJIJIJIIJJIIJIIIIJJIIJIJJJIIIIIJIJIJIJJJJIJJJII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public string JIJIIIIJIJIIJIJJIIIIIJIJIJJJJIIIIJJJIIJIIIJIIJI()
	{
		return null;
	}

	private void IIIIJIIIJJJIJJJIIIIIJJIIIJJIIJIIJJJJIJIJIJJIIJI(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	private void JJJIIIJJIIIJJIIIJIIIIJJJIJJIJIJIIJJIJIJIJJIIJJI(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJIJJJJIJJIJIJJJJJIJIIJIIJIIIJJIJJJJIIIJIIJJJJI(string result)
	{
	}
	public string JJIIIJIJIJIIJIIIJIJIIIJJIIJJJIIJIIJJJIIJJJJIJJJ()
	{
		return null;
	}
	public string JJIIIJIJJIIJIIIIJJJJIIIJJIIJJJJJIJIIJIJJJIIJIJJ()
	{
		return null;
	}
	private void IIIIIJJIJJJJJJJIIIIJIIJJJJIJJIIJJIJIJJIIIJJIJIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public string JJIIIIIIIJJIIIIJJIJJJJIJIIJJJIIJJIJIIJJIIIJIIII()
	{
		return null;
	}
	public string JJIIIIIIJIIJJJJJIJJJIJJJIJJJIIJIJJJIJJIJJJIJJII()
	{
		return null;
	}

	public void OnPermissionResult(string result)
	{
	}
	private void IJIIJIIJJJIIJIJIIIIIJIIJIJIJJJIIIIJJJIIIJJJIIJJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJJIJIIIIIJJJIIJIJIIJIIIJJJIJIIIIJJIIJJIIJJJJI(string result)
	{
	}
	public string JJJIIIJIIIJJJIIJJJIJJIIJJIIIIJJJIJIIJIJJJIJIIJI()
	{
		return null;
	}
	public string JIJJIIJJIJIIIIIIIIJIIJJIJIIIIIIIIIIJIIIIJJIIIJJ()
	{
		return null;
	}

	public string IIJJIIJJJIIJJJJJJJJJIIJJIIJJIJIJJJIIIJJJJJIIJJJ()
	{
		return null;
	}
}
