using System.Runtime.InteropServices;
using UnityEngine;

public class JIIJJIIJIIJJJIJIIJIIJIJIIJJIIIJIJIIIJIJJIJIJJJI
{
	[StructLayout((LayoutKind)0, Size = 4)]
	private struct IJIIIIIIJJJIJIJJIIJJIIIJJJIIJIIJIIIIJJIIIIJJJJJ
	{
		public byte JJJIIJJIJJIJJJIJJIJJIJJIJIIIJIIIIIJIJJJIJIIIIII;

		public byte IIIJJIIJIJJIJIIIJIJJJJIIIIIIJIIJJIIJIJJIIJJJJJJ;

		public byte JIIJJIIIIIJJIJJIIJIIIJIIJIJJIJJIIIJIIIJJJIJIIIJ;

		public byte JJIJIJJIIJJIJIJJIIJJIJIJIJIIJJIIJIJIIIIIIJIIJJI;
	}

	[StructLayout((LayoutKind)2, Pack = 1, Size = 4)]
	private struct IIJIJIJJJIIIJJJJIJIJJIIIJJJIIIIJIJIIIJIJIJIJJJI
	{
		[FieldOffset(0)]
		public float JIJIJJJIJJIIIIIJIIIIIJJJJJJJIIIIJIIIJJJJIJJIIJI;

		[FieldOffset(0)]
		public IJIIIIIIJJJIJIJJIIJJIIIJJJIIJIIJIIIIJJIIIIJJJJJ JJIJIJJIIJJIJIJJIIJJIJIJIJIIJJIIJIJIIIIIIJIIJJI;
	}

	private global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<byte> JIJJJIJIJJJIIJIJIIIIJJIJIJIIIIIIJJIIJJJIIIIIIJI;

	private global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<short> JIJIJIIJIJJIIJIIJIIIIJJIIIIJJJIJIJIJIJIIJJIJJII;

	private global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<byte> JIJIJIJIIJIIIIIJJIJIJJIIJIIIJIIJJIJIJIJJJIJJIJI;

	private IIJIJIJJJIIIJJJJIJIJJIIIJJJIIIIJIJIIIJIJIJIJJJI IIIIIJJJIIJIJJJIJIJJJJIJIIJJJIIJJJJIJIJJIJJJIII;

	private IJIIIIIIJJJIJIJJIIJJIIIJJJIIJIIJIIIIJJIIIIJJJJJ IIJJJIJIJJIIIIIIJJJIJIJJIJJIJJJIJIIJIJJIJIJIIJI;

	public int JJIJJJIIJIJIJIIIJJJIIIJIJJJJIIJIIJJJIJJIJIJJIII => JIJJJJJIJIJJIJIJIJIJIIIJIIJJJIIIJJIJIJIJJJIJJII();

	public void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public string IIJJIIJIIIJJIIIJJJIIIJIIIJIJJIIJIJIIIJIIIJIJJII(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, byte[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIJIIIJIIJJIJJIJJIIIIIJJJJJIJIJIJJJIJJIJJJJIIII(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, short JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Vector3 JIIJIIJJIJIIIJJIJIIIIIIJJIJJIJIJIJJIIIIIJIIIJII(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return default;
	}

	private int IIJJJIJJJIIJJIIIJJIIIIIJJIJIJJJIJIIIIIJJJJIJIIJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public byte JIJIIIJJJJIJJIJIIJIIIJJJJJJJIIJIJJJIIJJIJIIIJII(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJJJJIJJIJIJIJIIIJIJJIIIJIIIJIJJIJJIIJIJJJJIIJI(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public int JJJJJJIIJJJJJJIIIIJIIJIIIJIJJJJIIIJIIIJJIJJJIJI(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public string JJJIJIJJJJJJIIJJIJIIIIJIJJJIIIJIIIJIJIIIIIJIIIJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public float JJIJJJIJIIJJJIIJIIIJIIJIJJIJIIIJIJIJJJIIJJJIIJJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0f;
	}

	public void IJIJIIIIJIJIIIIJIJIIJJJIJIJJJIIIIJIIIIJJJIIJJJI(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public short JIJIJJJJIIIJJIIJJJIJIJIJJJJJIJJIIIIJIJIJIJIIIIJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	private int JIIIJIJIJJIIJIIJIJJJIIIIIIIJJIJIJIJIJIIIJIIIIJI(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public void IIJIJIJIJJIIJJJIJJIJJIJIIIJIJIIIIJIIIIIIIJIIIII(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public int JIJJJJJIJIJJIJIJIJIJIIIJIIJJJIIIJJIJIJIJJJIJJII()
	{
		return 0;
	}

	public void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private int JIJIIJJJJIIIJIIIIIJIIIJIJIIIIIJJIIJIIIIJJJIIJII(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}

	public int JIJIIIJIIIJJJIIJJIIIJJIIJJIIJJIIJJIJJJJIJJJIIJI(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public byte[] JJJIJJJIIJJIJJIJIJJIIJJIIJJIIJJJJJJJJJIIJJJJJJJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public byte[] IJJJIJJJIIJJJJJIIJJIIJJIJIJIJIJIIIJJIIJIJIJJIJJ()
	{
		return null;
	}

	public void JIIJJIJJJJJIJJJIIJIJJJIIIJIIIJJIJIJIIJIIJJJIJJI(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public string IJIJIIIJJJJJJIIIJJJJIIIJJIIJJJIIIJIJIJJIIJIIIII(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public void IJIIJJJIIJJIJJIIIJIIJJIJIIIIJJJIIJJJIJJIJIJIJIJ(byte[] JIIIJJIJIJIJJJIIJIJJJJJIJIJIIIIJIIIIJJIIJIJJIIJ)
	{
	}

	public Quaternion JJJJIIIJIIIIJIIJIJIJIIIIIIJIJJIIIJJIIIIJJJIIJJJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return default;
	}

	public void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, byte JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool IJIJIJJJJJJJIIIJJJIIIJJIJIIJJIJJJJIJJJJJIIIIJII(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return false;
	}

	public void IJIJJJIIJJJJJIIIIJIIIIJJJJJJIJJIIIIJIJJJJJJJJII(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool JJJJIIIJJJIJJIJIIIJIIIJJJIJJJIJIJIJJJIJIJIIJJIJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return false;
	}

	public bool IIJIJIJIJJIIIIIIIIJJJJIIJJJJIIJIIJJIJIIJJIIJJII(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return false;
	}

	public void JJJJJIJIJIIIIJJJJIIIJIIJJIJIJJJJJJIIIIIIIIIJIIJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(byte IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, short JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
}
