using System.Diagnostics;

public static class JIIJJIIIIJIJJJIIIIIJIIJJJJIJJIJIIIIJIIJJIIIIJII
{
	private static Stopwatch IIJJIIJJIIJJJIIIIJIIJJIIJIIIJIJJIJJIIIJJIIJIJII;

	public static void IIJJJIIJJIJJIJIJJIJIIIIIIJIIJIIJIJIIJJJJIIIJIJI(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public static void IJJIJJIJJJIJIIJIJJJIIJJIJIIIIIIIIJJJJIJIIIIJIJI()
	{
	}

	public static void IJJJIIIJIJIJIJJJJIIJIIJJJIJIJJJIJIJJJJJIIJIIJIJ()
	{
	}

	public static long JIJIJJJIIIJIIIJIJIJIIIJIIIIJIJJIIIJJIJIIJIJIJII()
	{
		return 0L;
	}
}
