public interface JIIJJJIIJIIIJIJIJIIJJIIIIJJJIJJIJJIJJJJIJJJIJJJ
{
	void JIIJJIJJIJIIIJIIJJIIIJIJJJIJJJJIIJJJJJJJIIIIIJI(bool JIIJIJIIIJJJIJIJIIJJIJIIIIJJJIJJJJJIJJIJIJIJJJI);

	void IIJIIJIIJJJJJJJJIJJIJJIIIJIJJIJIIJIJIJJIIJIJJII();

	void IJIJIJJIJIIIJIIIJJIJJIIJIJJIJIJIIIIIJJIIJIIIJJI();

	void JJIJIIJIIIIJJIJJIJJJIJIJIIIJJIJJIIIJJJJIIIJIIII();

	void JIIIIJJJIIIJIIIJIJIJIIJIIIJIIIJIJIJJIJJIJIIIJIJ();
}
