using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;

public static class JIIJJJIJIIJIJJJIIJIJJIJIJIJJJJJJIIIJIIJIJIIJIII
{
	private abstract class JJJJJIJJJIJIJIIJJJIJIJIIJIJJJIIJJJIJJIIJIIJJJJI
	{
		public abstract bool JJJJIJIIJIIJJJIJIIJJIJIIIIIJIIJJIJJIJJJIIJIIJII();
	}

	private class JIIJJJIIIJJIIJJIIIJIJJIJIIJIIIJJJJIIIIIJIIJIJII : JJJJJIJJJIJIJIIJJJIJIJIIJIJJJIIJJJIJJIIJIIJJJJI
	{
		private bool IIIJIIIIJJJJIJJJIJJIJIJIIIJIJIIIIJJIJJIIIIJIIJI;

		public virtual bool IJIIJIJIJIJJIJJIJJIJJJJIJJJJJIJIIJIIIIIJJIJIIII()
		{
			return false;
		}

		public virtual bool JIJIJJIJIJIIIIJIIJIJJIJIIJIIIIJIIIIJJJJIIJJIIJI()
		{
			return false;
		}

		public virtual bool JIIJIJIIIJJIJIIJJIIJIJJIIIIIJIJJJJIIJIIJJJJJJII()
		{
			return false;
		}

		public virtual bool IJIJJIIIJIIIIIIJJJJJJJIJIJJIJIJJIIIJIIIIJJJIIJI()
		{
			return false;
		}

		public override bool JJJJIJIIJIIJJJIJIIJJIJIIIIIJIIJJIJJIJJJIIJIIJII()
		{
			return false;
		}

		public virtual bool JJIIJIIIIJJJIIJIJIIJJJJJJIJJJIIIIIJIIJIJIIJJIJI()
		{
			return false;
		}

		public virtual bool JJIIJIJIJIIIIIIIJIIIJIIIJJJJJJJIJIJJIIJIJIIJJJI()
		{
			return false;
		}

		public virtual bool JJIJIJJJIIJIJIJIIIJIJIIIIIJIJIIJJJIJIJIJJJJIIIJ()
		{
			return false;
		}

		public virtual bool JJJJIJIJIJJIIIJJIJIIIJJIIJIJJIIIIJIIIIIIIIIJJIJ()
		{
			return false;
		}

		public virtual bool JJJJJIJJJJIJIIJJIIIJJJIJIJIJJIIJJJIIIIIJJIJIJJJ()
		{
			return false;
		}

		public virtual bool JJIJIJIIJIJJJJJIIJIIIJJJJIJJIJJIIJIJIIJIIIIJIJI()
		{
			return false;
		}

		public JIIJJJIIIJJIIJJIIIJIJJIJIIJIIIJJJJIIIIIJIIJIJII(bool IIJIJJIJIIJIJJIIJIIJJIJJJJIJJJIIIJJJIIIJJJJJJJI)
		{
		}

		public virtual bool JIIJIJJIIJJIJJIIIIIIJJIIIJIJIJIJIJIIIJIIIJJIJII()
		{
			return false;
		}

		public virtual bool JJIIJJJJJJJIJJIJJIJJIJJIJIJIJJJIIIIIJIIIIJJJJJI()
		{
			return false;
		}

		public virtual bool JIIJIIJIJIJJJJIIJIIJJJJIJJIIIJJJIJJJIJIJJJIJIJJ()
		{
			return false;
		}

		public virtual bool IIIIJIIJIIIIIIIIJIJJJJIJIJJIIJJJJIIIJIJJIIIJIJI()
		{
			return false;
		}

		public virtual bool JIJJIJJJJJJJJJJIJJIJIIIJIJJIIJJJJJIJJJJJIIJJIII()
		{
			return false;
		}

		public virtual bool JJJJJIJJIIIIJJJJJJJIIJJJIIIJIJJIJIIIJJIJJIIIJII()
		{
			return false;
		}

		public virtual bool IIJIJJJIJJIIIJIIIIIJJJJJIIIJJIIJJJIIIJIIIIIJJJI()
		{
			return false;
		}
	}

	private class IIJIJIIIIJJIIJIJJJJJJJJJJJJJJJIJJJIJIJIJJIJIJJI : JJJJJIJJJIJIJIIJJJIJIJIIJIJJJIIJJJIJJIIJIIJJJJI
	{
		public Func<bool> IJIIJJJIIIJIJIIIIIIJIJJJIJIJIJIJIJJIIJIIJJJIJIJ;

		public virtual bool JJIIJJJJJJJIJJIJJIJJIJJIJIJIJJJIIIIIJIIIIJJJJJI()
		{
			return false;
		}

		public virtual bool JIJIJJIJIJIIIIJIIJIJJIJIIJIIIIJIIIIJJJJIIJJIIJI()
		{
			return false;
		}

		public virtual bool IIJIJJJIJJIIIJIIIIIJJJJJIIIJJIIJJJIIIJIIIIIJJJI()
		{
			return false;
		}

		public virtual bool IIIIJIIJIIIIIIIIJIJJJJIJIJJIIJJJJIIIJIJJIIIJIJI()
		{
			return false;
		}

		public virtual bool JJJJJIJJIIIIJJJJJJJIIJJJIIIJIJJIJIIIJJIJJIIIJII()
		{
			return false;
		}

		public virtual bool JIJJIJJJJJJJJJJIJJIJIIIJIJJIIJJJJJIJJJJJIIJJIII()
		{
			return false;
		}

		public virtual bool JJJJIJIJIJJIIIJJIJIIIJJIIJIJJIIIIJIIIIIIIIIJJIJ()
		{
			return false;
		}

		public virtual bool IJIJJIIIJIIIIIIJJJJJJJIJIJJIJIJJIIIJIIIIJJJIIJI()
		{
			return false;
		}

		public virtual bool JJIJIJIIJIJJJJJIIJIIIJJJJIJJIJJIIJIJIIJIIIIJIJI()
		{
			return false;
		}

		public virtual bool JIIJIJIIIJJIJIIJJIIJIJJIIIIIJIJJJJIIJIIJJJJJJII()
		{
			return false;
		}

		public virtual bool JJIJJJIJJIIJJJIJIJIIIJIJJIJIJIJJIIIIIJIIJJIIJIJ()
		{
			return false;
		}

		public virtual bool JIIJIJJIIJJIJJIIIIIIJJIIIJIJIJIJIJIIIJIIIJJIJII()
		{
			return false;
		}

		public virtual bool JJIJIJJJIIJIJIJIIIJIJIIIIIJIJIIJJJIJIJIJJJJIIIJ()
		{
			return false;
		}

		public virtual bool JJJJJIIIIJIIIJJJJIIIIIIJJJJJIIIJJIIJIJIIJJJIIII()
		{
			return false;
		}

		public virtual bool JJIIJIIIIJJJIIJIJIIJJJJJJIJJJIIIIIJIIJIJIIJJIJI()
		{
			return false;
		}

		public override bool JJJJIJIIJIIJJJIJIIJJIJIIIIIJIIJJIJJIJJJIIJIIJII()
		{
			return false;
		}

		public virtual bool JIIJIIJIJIJJJJIIJIIJJJJIJJIIIJJJIJJJIJIJJJIJIJJ()
		{
			return false;
		}

		public virtual bool JJJJJIJJJJIJIIJJIIIJJJIJIJIJJIIJJJIIIIIJJIJIJJJ()
		{
			return false;
		}

		public virtual bool JJJJJIIIJJJJJIIJJJIJIIIJJJJJJIJIIIIIIIJJIJJJJIJ()
		{
			return false;
		}

		public IIJIJIIIIJJIIJIJJJJJJJJJJJJJJJIJJJIJIJIJJIJIJJI(Func<bool> JJIJIIJIJIJIJJJIJIIIJIJIIJJJIIIIJJIIIIIIJIIJIJI)
		{
		}

		public virtual bool JJIIJIJIJIIIIIIIJIIIJIIIJJJJJJJIJIJJIIJIJIIJJJI()
		{
			return false;
		}

		public virtual bool IJIIJIJIJIJJIJJIJJIJJJJIJJJJJIJIIJIIIIIJJIJIIII()
		{
			return false;
		}
	}

	private sealed class JJIJIIIJIJIIJJJJJIJJJJIJIIIJIJIIJIJIIJIJIJJJIII
	{
		public string JJIJIJIJJJJJIJIIJIIIJJIJIJIJJJJJIIJJIIJIJJIIJJI;

		internal bool JJIIIIJIIJIJJIIIIJIIJIJIJIJIIJIIIIJJIJJJIIJJJJJ(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool JIJIIIIJIJIJJJIJJJIIJJJJIJJIIJIJJJJJJIIIJJJIIIJ(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool JJIIJJIIIJJJIIJJIJIIIJIIIJJIJIJJJIIIIIIJJJIJIIJ(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool IIJIIIJJJIJJIIIJIIIIJJJIIIJIIJJJJJJIJJIJIIIIIII(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool IIIJJJIJIIJIJJJIIJIJIIJJIJJJIJJIJJIJIJJJJIIJJJJ(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool JIIIJIJJJIJJJIIJJJIIIJIJJIIIJJIIIIJJJIIIIJIIJJJ(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool IIIJJJIIJJIIIIIJIJIJIJIJIIIJJIJJJIJJIJIIJJIJIJI(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool IJJIIIJJIIJJIJIIJJIJJIJIJIIJJIIJIJIJJJIJIJIJIII(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool JJJJIJIIJIIJIJJIIIJIIIJIJIJIIJIIIJIJIIJJIIJIIJI(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool JJIJIIIJIIIJIJJIIIJIJJIJJJJJJJJIJJJIIJJJJIIJJIJ(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool IIIJJIJIJJIJJJIIJIJIJIJJIIJIJJIJJJJJJIIJIJJJJJI(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool IJJIJIIIJJJJIIJJJIIIIIIIJIJIJIIJIJJJJJIJIIJIIIJ(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool JJIIIIIJIIIJJIIIIJIIIIIJJIJIIJJJIIIIIIIIIIIJJJI(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool IIJIJIIJJIIIJIIJIIIJIJJIIJJJIJIIIJIIIJIIIIIIIJI(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool IJIJIJIIIIIJJJIIJIIIIIIIIIJJJIJJIIIJIJJIIIJIIJI(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool JJIIIJJIJIIJJJJIIJIIIJIIIIIIJJJJIJJJJJJJJIIIIJI(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool IJJJJJJIIJIIJIIIIJJIJIIIIIJIIIIJIJIJIIJIIIIIIII(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool IJJIIJIIIIIIIIJIIJIIJIJIJJIJIIIIJJIJIJJIJIIJIJI(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}

		internal bool IIJJJJIIIJIIIJIJIJJJIIIIIIJJIIJIJIIJIJIJJJJJJJI(char IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
		{
			return false;
		}
	}

	private sealed class JIIIIIIJIIIIIJIIJJJJJIJJIIIIJJIJIJJIIJIJIJIIJIJ
	{
		public string JIIJJIIJIJJJJIIIJJIJIIIJJJIJJIJIIJIJJIIIJJJIIIJ;

		internal bool JIJJJIIJIJJIIJJJJIJIIIJJIIIIIJIJIJIIJIJIJJJJIJJ(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool IIJIJJIIJJJIJIJJJIJJIJIIJIJJJIJJIIJIJJJJJJJJJJI(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool IJIJIIJJIJJJJIJJJIJIJIJIIJJIJIIJIJJIJJIIIIIIJIJ(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool IJJIJJJJIIJIJIIJJIIJIJJIJJIIJIIJIJIJJIJIJIJJJIJ(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool IJJIIIIJIJJIJIJJJIIJJIIJIIJJIJIJJIIIJIIJJJJIJJI(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool JIIJIJIJIIIJIIIJJIIIIJJJIIJJJIIJJJJJIJIJIIIJJIJ(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool IIIJIIIIJIIJIIIJJIIJJJIIJIJIIIJIJJIIIJIJJJJJJII(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool JJIIJIIJIIIJIIIJIIJIIIIJIIIJIJJIJJIIIJIJIIJIIJJ(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool IIJJIIJJIIJIIIJIJIIJIIIJIIJJIIIIJIJIJIJIJIJJJJJ(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool IIIIJJIJIIJJIJJIJIJIJIIIJIJIJIIJJIIJJIJIJJJJJIJ(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool IIIJIIIIJJJIJIJIIJJIIIJJJJIIIJIIJIIJJJJIJJJIIII(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool IJJJJIJIIIJJIIIJJJIIJIIJJJIJJIJIJJJJIJJJIJIIJJI(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool JIIIIJJIJIIJIIIJJJJIIIIJJIJJJJJIJIIIJJJIIIJIJJJ(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool IJIJIIIIIIIJJIIJIIJIJJIIIJJIJJIJJIIIIIIIIJIJJIJ(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool JJJIIIJIJJIIIIIIJJIIJIIIIJIJJJIJJIIIJJIJIJJIJIJ(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool IJIJIJJIIIJJIIIJJIIIJIJIIJIIIIJIJJJIIJIIIIIIJJJ(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool JJIIIJJIIIJIIIIIIIJJIIIJIJIIIJIJJJIJJIIIJJJJIII(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool IIIJJJIJIIIJJIJIIIIIJJJJJIJIIJIJIIJJIJJIJJJIJIJ(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool IIIIJJJIJIIIJJJIJJIJIIJJJJJJJIIIJIIIJJIJIJJIJII(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}

		internal bool JIJJJJJJIIIJIJIJJIJIIJJJIJJIIJJIJIJJJIJIJJJJJIJ(Assembly JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
		{
			return false;
		}
	}

	private sealed class JIJJJIIJJIIJJIJIIJJJJIJIIJJIIJIIIJIJJJJIIJJIJJI
	{
		public Component IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ;
	}

	private sealed class IJIJJJIJJJJIJJIIJJJIIIIJIJJIIIIIJIIJIIJIJJIJIIJ
	{
		public MethodInfo JJJIJIIIJJIJIJJIJIJJJJIIIIJIJJIJJJIJIJIIJJIIIJJ;

		public JIJJJIIJJIIJJIJIIJJJJIJIIJJIIJIIIJIJJJJIIJJIJJI IJJIJIIIIJIJIJJJJJIIJIIJJIIIIIIJIIIIJJIIIIIJIII;

		internal bool IIIJJIJIJJJJIIJIJJIIJJIJIIIJIIJJIJIIIJJIJIJJIJI()
		{
			return false;
		}

		internal bool JIIIJJIJIIJJJIIJJJIJIIIJIIJIJJJIJJJJIJJIJJJIJJI()
		{
			return false;
		}

		internal bool JIJJJJJIJIIJJIJIJIJIIJJJJJJIIJJIIIJJIIJJJJJJJJJ()
		{
			return false;
		}

		internal bool JJJJIJIIJIIIJJIJIJJJIJIIJJJIIJIIJIJIJJJIIJIJJIJ()
		{
			return false;
		}

		internal bool JJIIIJJJJIIIIIIIJIIJIJJIJJJIJIIJJJIJJJJIJIIJIJI()
		{
			return false;
		}

		internal bool IIIJJJJIJIIIJJIJJJIIJIJJJIJIIIJIJJIJIIIJJJIIJIJ()
		{
			return false;
		}

		internal bool JJJJIJJJJIIIJJIIIJIJJJIJIIJJJIJIJIIJIJIJIIJIIJJ()
		{
			return false;
		}

		internal bool IJJIJIJJIJJJJJJJJIIIIJIJJIJIIIJJJJJIJIJIIIIIJJI()
		{
			return false;
		}

		internal bool IIIIJIIIIJIIIJIIIJJJIIJIJIIIJIIJIIIIIJJJJIJIIII()
		{
			return false;
		}

		internal bool IJIJIJJIIIJJIJJJIIIIJIJIJIIIJJJJIIIIJIIJIJIIJJI()
		{
			return false;
		}

		internal bool IJIJJJJIJJJJJIJJIJIIJIJJJIJIJJIJIIIIIJJIIIIJIJI()
		{
			return false;
		}

		internal bool JJIJIJJJJIIJJJIIIIJJJJIJJJJIJIIIIJJIIIIIJJIJIJJ()
		{
			return false;
		}

		internal bool IJJJJJIIIJJIIJIIIJJIIJJJIIJIIJJJIIJJJJJIJJIIIJI()
		{
			return false;
		}

		internal bool JJIIIJJJJJJJIIJJJJIIIIIJJIIIIJIJIJIIIIIJIIJJIJJ()
		{
			return false;
		}

		internal bool IIIIJIIJJIJJJJIJIIJJIJJIIIIJJIJIJIJJJJJIIJJJIIJ()
		{
			return false;
		}

		internal bool JJJIIJIJIIIIIJJJJJIJJIIJJJJJIIJIIIJJJIJIJJJIIIJ()
		{
			return false;
		}

		internal bool JIJJIIJJIJJIJIIJJJIJIJIIJJJIIJJIIIIJIIJJJIIJIII()
		{
			return false;
		}

		internal bool IJJIJIJIIIJJJJIIJIIJIJIJIJIJJIJIJJIJJJIJIJIIJIJ()
		{
			return false;
		}

		internal bool JIIJIJJJJIIIJIIIJIIJJIJIJJJIIIJJJIJJIIJIIIIJJJI()
		{
			return false;
		}
	}

	private const float JJIIJIIJJJIJIIJJJJIJIIIIJJJJJIIJIJIJJJJJIIIIJIJ = 0.0001f;

	private static Dictionary<Transform, JJJJJIJJJIJIJIIJJJIJIJIIJIJJJIIJJJIJJIIJIIJJJJI> IJIIJIIIIIIJJJIJIIIJIIIJJJJJIJJJIJJIIIJJIIJIIII;

	private static Dictionary<Type, bool> JJJJIIJIIIJJIJJJIJJJIJJIJIJJIJIJIJIIIIJJJJIIJJI;

	private static Dictionary<Type, MethodInfo> JIIIJIIIIIJJIJIIJJJIIJJJJIIIIIJJIJJJJIIIIJJIJJJ;

	public static Color JJJJJIJIJIJJJIJJJJIJIIIJIIIJIIIIJJIIIJIIIJIIJJI(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return default;
	}

	private static Vector3 IIIIJIIJJJIIJIIJJJIJIJIJJIIIIIIIJIIJIIJIIIIJJII(Vector3 JJIIJIIIJIIJJIIIIJJIJIJIIIIJIIJJIJIJJJJIJJJJIII)
	{
		return default;
	}

	private static IJIIIIIIIIIIIJIIJIIJJIIJIJIJIIIJJJIIJJIJIIJIIII IJIJJJJIIJIIIJIJIIJJJJJIJJJIIIJIIIIJIIIJIIIIJJI(Vector3 JJIIJIIIJIIJJIIIIJJIJIJIIIIJIIJJIJIJJJJIJJJJIII)
	{
		return IJIIIIIIIIIIIJIIJIIJJIIJIJIJIIIJJJIIJJIJIIJIIII.None;
	}

	private static IJIIIIIIIIIIIJIIJIIJJIIJIJIJIIIJJJIIJJIJIIJIIII JIJJJIIIIIIJJIJIIIJJJJJIJJJJJIJJIJIIJJIIJIIJJJJ(Vector3 JJIIJIIIJIIJJIIIIJJIJIJIIIIJIIJJIJIJJJJIJJJJIII)
	{
		return IJIIIIIIIIIIIJIIJIIJJIIJIJIJIIIJJJIIJJIJIIJIIII.None;
	}

	public static IJIIIIIIIIIIIJIIJIIJJIIJIJIJIIIJJJIIJJIJIIJIIII JJIJJJIJIIJJJJIIJIIIIJIIJIJJJIIIIIJJIIIJIIJIIIJ(Vector3 IJJIIIJIJIIIIIJJJIJIJIIIJIIJIIJJIIJIIJJIIJJIIII, Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ)
	{
		return IJIIIIIIIIIIIJIIJIIJJIIJIJIJIIIJJJIIJJIJIIJIIII.None;
	}

	public static float JIIIIIJJIIJJJJJJJIJIIJJIJIJIJJIIIIJIJIJIIJJJJII(Vector3 JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ, Vector3 IIJJJIJJJIJIJIJJIIIIIJJJIIIJJIIJJIJJIJJJIIIIJII)
	{
		return 0f;
	}

	public static Vector3 JJIJIIIJIIIJIJIIIIIIIIJJJIIJIIJIJJIJIJIIIJIIIIJ(Vector3 JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ, float JIIJIIJJJIIJIJIIJJJIJJIJIIIJJIIIJIIIIJIIJJJIIJI)
	{
		return default;
	}

	private static Type IIIIIIJIJIIJIJIIIIIIJIIIIJJJJJIJIIIJIJJIJIJIIII(string JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI, string JIIJJIIJIJJJJIIIJJIJIIIJJJIJJIJIIJIJJIIIJJJIIIJ = null)
	{
		return null;
	}

	public static void JJIIJIJJJJJIJJJJJIIIIJJJJIJJIJIJJJJJIJIJIIIIJJI(bool JJIJIIJIIIJJIIIJJIIIIJJJIJIIJIIJJIJIIIJIJJJIJIJ)
	{
	}

	public static bool JJIIIJIIIIJIIJJIIJIJJJJJJJJJJJIJIJJJIJJIIIJIIJJ()
	{
		return false;
	}

	public static Vector3 JJIJIIIJIIIJIJIIIIIIIIJJJIIJIIJIJJIJIJIIIJIIIIJ(Vector3 JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ, Vector3 IIJJJIJJJIJIJIJJIIIIIJJJIIIJJIIJJIJJIJJJIIIIJII, float JIIJIIJJJIIJIJIIJJJIJJIJIIIJJIIIJIIIIJIIJJJIIJI)
	{
		return default;
	}

	public static Vector3 JJIJJJIJIJJIJJIIJIJIIIJJIIIIIIIIJIJIJJJIJIJJIJI(Vector3 JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ, Vector3 IIJJJIJJJIJIJIJJIIIIIJJJIIIJJIIJJIJJIJJJIIIIJII, float JIIJIIJJJIIJIJIIJJJIJJIJIIIJJIIIJIIIIJIIJJJIIJI)
	{
		return default;
	}

	public static Vector3 IIJIJIIJIIIJJJJJJJIJJIJJIIJJJIIIIJJIJIJJIIJIIJI(Vector3 JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ, float JIIJIIJJJIIJIJIIJJJIJJIJIIIJJIIIJIIIIJIIJJJIIJI)
	{
		return default;
	}

	public static Vector3 IIJIJIIJIIIJJJJJJJIJJIJJIIJJJIIIIJJIJIJJIIJIIJI(Vector3 JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ, Vector3 IIJJJIJJJIJIJIJJIIIIIJJJIIIJJIIJJIJJIJJJIIIIJII, float JIIJIIJJJIIJIJIIJJJIJJIJIIIJJIIIJIIIIJIIJJJIIJI)
	{
		return default;
	}

	public static float JIJJJJJJIJJJIIJIJIIIIIJJJJJIJJJJJIIIJJJJJJJIIJI(float JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ, float JIIJJIJIJIJIIIJJJIIJJJJIJJIJJIIIIIIJJJIJIJIJIII)
	{
		return 0f;
	}

	public static float IIJIJIIJIIIJJJJJJJIJJIJJIIJJJIIIIJJIJIJJIIJIIJI(float JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ, float JIIJIIJJJIIJIJIIJJJIJJIJIIIJJIIIJIIIIJIIJJJIIJI)
	{
		return 0f;
	}

	public static float JJIJJJIJIJJIJJIIJIJIIIJJIIIIIIIIJIJIJJJIJIJJIJI(float JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ, float JIIJIIJJJIIJIJIIJJJIJJIJIIIJJIIIJIIIIJIIJJJIIJI)
	{
		return 0f;
	}

	public static Vector3 JIJJIJIIJIIIIJIJJIJJIJJIJJIJJIIIJIJIJIJJJIJIIIJ(Vector3 JIIJJJJJJIIJJIJIIIIIIJIIJIIIIIIJJJJJIJIIIJJJIJI)
	{
		return default;
	}

	public static void IIIIJIJJIJJIJIJIJIIIJIIIJIJIJIIIJIJJJJIJJIIJIJJ()
	{
	}

	public static bool IIJIIIIIIJIJIIIJIIJJIJIIJJIJIIJIIIIJIJJIIJIIJJI(Transform JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
	{
		return false;
	}
}
