using System;
using System.Collections.Generic;
using System.Diagnostics;
using UnityEngine;

public static class JIIJJJIIIJJIIJJIIJJJJIJJIIJJIJJIJIJIJJIIJJJJIJJ
{
	public delegate void IJIIJIJJJIIIJIIJJJIIJIJIJJJJIJIJJJJIIJIIIIIIIII<T>(T JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII) where T : UIWidget;

	[NonSerialized]
	private static AudioListener JIIJJIJJIIIIJIIJIJIIIJJJJIJJIIJIJIJJIIIIIJIJIII;

	[NonSerialized]
	public static AudioSource IIJIJIIIIJJJJJIJJJIIIJIJJIJJIJIIJIJJIIIJJJIIJIJ;

	private static bool JJIIJJIJIJJIJJIJIJIJIJIIIJJIIIIIIIIJJIIIIIJIJIJ;

	private static float JJIIIIIIIJJJIIIIJJJIJJJIIJIIIIJIJIIIJJIJIJIIIJJ;

	private static float IIIIIIJIJIJJIIJJJJJJIIJJJJIIJIJIJIJIJJIJJJJIIJJ;

	private static AudioClip IIJJIIIIJJIIJJIJJIIJIIJJJIJIIIIIIIIJJIJJIIIJIII;

	private static Dictionary<Type, string> IIIJIJJIJIIIJJIJIJJIJIIIJIIIJJIJJIJJIIIJJJIIIII;

	private static Vector3[] IJJIIIJJIJIJIJIJJJJIJIJIJIIJIIIIIJJIIIJJIIIJJIJ;

	public static KeyCode[] JIJJJIJIJJJIIJIJIIIIJJIJIJIIIIIIJJIIJJJIIIIIIJI;

	private static Dictionary<string, UIWidget> IJIJIIIJJIIJJJJIJIJJIJJIIIIJJIIIIIJJIJJJJJIJIJI;

	private static UIPanel JJJJIIJIIJIIJIIIJIJJJIJIJIIIJIIIIIJJJJJJIJJIJII;

	private static GameObject IJIJJIIIJJJIIJJIIIIJIJJIJJIJJIIIIIJJIJJIJIIJJJJ;

	private static ColorSpace IJIJJJJIIJIIJJJIJIJIIJIIIIIJIJJJIJJJIIJJIJJIIIJ;

	public static float IIIJJJIJJJIIIIJIJIJJIJIJJIIJJJIIIIIIJJJJJJJIJII
	{
		get
		{
			return JJJJJIJIIIIJIIIJIIJJJIIIIJJJJIJJIJIJIIIIJJIIIIJ();
		}
		set
		{
			JJJJJIJIJIIJJJIIIJJIIIIJJIIJJIIJJJJJJJJIJJIJJII(value);
		}
	}

	public static bool JIIJJJIJJJJJJJJIJJJJIJIIJJJJIIIJJJIJJJIIIIJJJJJ => JJIIIJJIIJIIJIJIJIJJJIJJIIIIIJIIJJIIIIIJJIIIIIJ();

	public static string IIIIIJJJJIIJIJIIJIJIIJJJJJIJJIJJIIIJIIJJIIIIIIJ
	{
		get
		{
			return IJIIJJJJIIJIJJJIJJIJIJIJJIJJIJJJJJIIJIIIJJJIJJJ();
		}
		set
		{
			IJJIJIJIJJJIIIIJJIIIIIJIIIJIJJJJJJJJIIJIIIJJIIJ(value);
		}
	}

	public static Vector2 JIJIIJJIIJJIIIJJJIIIJJIIJIIJJIJIJIIIJJJJJIIJIIJ => JIIIJJJIJJJIJIIIJIIIJJIJIJIIJIIIJJJJIJIJIIIJJIJ();

	public static float JJJJJIJIIIIJIIIJIIJJJIIIIJJJJIJJIJIJIIIIJJIIIIJ()
	{
		return 0f;
	}

	public static void JJJJJIJIJIIJJJIIIJJIIIIJJIIJJIIJJJJJJJJIJJIJJII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static bool JJIIIJJIIJIIJIJIJIJJJIJJIIIIIJIIJJIIIIIJJIIIIIJ()
	{
		return false;
	}

	public static AudioSource JJIIIJIIJIJJIJIJJIJIJJJIJJIIIIIJIJIJIIIIIJIJIII(AudioClip IIJIIJIIJJIIJJIIJJJIIIJIIIJIIIIIIIJIJJIJJIIIJJJ)
	{
		return null;
	}

	public static AudioSource JJIIIJIIJIJJIJIJJIJIJJJIJJIIIIIJIJIJIIIIIJIJIII(AudioClip IIJIIJIIJJIIJJIIJJJIIIJIIIJIIIIIIIJIJJIJJIIIJJJ, float IIJJIIIJIJIJJJJIIJJJJIIIIIIIIIIJIIIIJIJIIIIIIII)
	{
		return null;
	}

	public static AudioSource JJIIIJIIJIJJIJIJJIJIJJJIJJIIIIIJIJIJIIIIIJIJIII(AudioClip IIJIIJIIJJIIJJIIJJJIIIJIIIJIIIIIIIJIJJIJJIIIJJJ, float IIJJIIIJIJIJJJJIIJJJJIIIIIIIIIIJIIIIJIJIIIIIIII, float IIIIJJJJIJIJJIJJIJIJJJIJIJJIIJIIJJIIIJJIIIJIJJJ)
	{
		return null;
	}

	public static int JJJIIJIJIIJJIJJIJJJIJJIJJIJJIJJIJIIIIJJJJIIIIII(int JJJJIJIIJIJJIIJJJIIJIJJIJIIIJJJIJIJIIJJIIJIJIJJ, int IJIIJJIJIJIJIIJJJIJIIIJIJIIJIJJIIIIJIIIJIIIIIJJ)
	{
		return 0;
	}

	public static string IIJIJJJJJJIJJJIIJJJIIJJJIIIJIJIJJJIIIJJJIIJJIJJ(GameObject JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return null;
	}

	public static T[] JIIJJJIJIIIJIIIJIJJJJJJIIIIIIJIIIJJJJJJJIIJIJJJ<T>() where T : Component
	{
		return null;
	}

	public static Camera JJJJIJJIJIIJJIIJJJJJIIJIIIJJIJJJIJIIJJJIJJIJJJJ(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ)
	{
		return null;
	}

	public static void IJJJIIJIIIJIIIJIJJIIIJJJIJJIJJIJJIJIJJJIIIJIIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	public static void IJJJIIJIIIJIIIJIJJIIIJJJIJJIJJIJJIJIJJJIIIJIIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JJJIJIIIIIIIJIIJIIIJJJJIIJIJIJJJIJIIIJIIJIJIIII)
	{
	}

	public static void IJJIIJIJIIJJJIJIIJIJIIIJJJIJIJJIJJIIIIIJJJJIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	public static void IJJIIJIJIIJJJIJIIJIJIIIJJJIJIJJIJJIIIIIJJJJIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JJJIJIIIIIIIJIIJIIIJJJJIIJIJIJJJIJIIIJIIJIJIIII)
	{
	}

	public static void IJJIIJIJIIJJJIJIIJIJIIIJJJIJIJJIJJIIIIIJJJJIIJJ(BoxCollider JJIJJJJIIJIIIIJJJJIIIIJIIJIIIIJJIIIIIIJIIJJIIJI, bool JJJIJIIIIIIIJIIJIIIJJJJIIJIJIJJJIJIIIJIIJIJIIII)
	{
	}

	public static void IJJIIJIJIIJJJIJIIJIJIIIJJJIJIJJIJJIIIIIJJJJIIJJ(UIWidget JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII)
	{
	}

	public static void IJJIIJIJIIJJJIJIIJIJIIIJJJIJIJJIJJIIIIIJJJJIIJJ(UIWidget JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII, BoxCollider JJIJJJJIIJIIIIJJJJIIIIJIIJIIIIJJIIIIIIJIIJJIIJI)
	{
	}

	public static void IJJIIJIJIIJJJIJIIJIJIIIJJJIJIJJIJJIIIIIJJJJIIJJ(UIWidget JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII, BoxCollider2D JJIJJJJIIJIIIIJJJJIIIIJIIJIIIIJJIIIIIIJIIJJIIJI)
	{
	}

	public static void IJJIIJIJIIJJJIJIIJIJIIIJJJIJIJJIJJIIIIIJJJJIIJJ(BoxCollider2D JJIJJJJIIJIIIIJJJJIIIIJIIJIIIIJJIIIIIIJIIJJIIJI, bool JJJIJIIIIIIIJIIJIIIJJJJIIJIJIJJJIJIIIJIIJIJIIII)
	{
	}

	public static string IJIJJJIIJJIIJJJIIJIIIJJJIJJIJIJIIJJJIJJJIJIIJJJ<T>()
	{
		return null;
	}

	public static string IJIJJJIIJJIIJJJIIJIIIJJJIJJIJIJIIJJJIJJJIJIIJJJ(UnityEngine.Object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return null;
	}

	public static void IIJIJJIIJIJIJIIJJIJJJIJIJJIIIIIJJIIIIJIIJIIJIJJ(UnityEngine.Object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public static void IIIIIJIJIJJJJJIJIIIJJJJJIIJJIJIJJIJJJJIIIJJJIJI(UnityEngine.Object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, string JIIJIJJIJIJIIIIIIIJJIIJJIJJIIIIJIJJIIJJJIIJIJIJ = "last change")
	{
	}

	public static void JJIIIIJJIJIIIIIIIIJJIIJIIJJIIIJIJJJJIJIJIIJJIIJ(GameObject JJJJIJIJJJJIJIJJJJJIIJJJIIIIIIJJIIJIJJJJJJJJJII)
	{
	}

	public static GameObject IIJIJIJJIJJJIJJJJIIJIJIIJIIIJIIJIJIJJIJJIJIIJJJ(GameObject IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI)
	{
		return null;
	}

	public static GameObject IIJIJIJJIJJJIJJJJIIJIJIIJIIIJIIJIJIJJIJJIJIIJJJ(this GameObject IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ)
	{
		return null;
	}

	public static GameObject IIJIJIJJIJJJIJJJJIIJIJIIJIIIJIIJIJIJJIJJIJIIJJJ(this GameObject IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, bool JJJIIJIJIIIIJJIIIJIIJIJJJIIIIJJIJIJJJJIJJIJJIJJ)
	{
		return null;
	}

	public static GameObject IIJIJIJJIJJJIJJJJIIJIJIIJIIIJIIJIJIJJIJJIJIIJJJ(this GameObject IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, bool JJJIIJIJIIIIJJIIIJIIJIJJJIIIIJJIJIJJJJIJJIJJIJJ, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ)
	{
		return null;
	}

	public static GameObject IIJIJIJJIJJJIJJJJIIJIJIIJIIIJIIJIJIJJIJJIJIIJJJ(this Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, GameObject JIIJJIJIJJJJJIJIJJJJJJIJIJJJJIJIJIIJIJJJIIJJIII)
	{
		return null;
	}

	public static GameObject IIJIJIJJIJJJIJJJJIIJIJIIJIIIJIIJIJIJJIJJIJIIJJJ(this GameObject IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, GameObject JIIJJIJIJJJJJIJIJJJJJJIJIJJJJIJIJIIJIJJJIIJJIII)
	{
		return null;
	}

	public static GameObject IIJIJIJJIJJJIJJJJIIJIJIIJIIIJIIJIJIJJIJJIJIIJJJ(this GameObject IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, GameObject JIIJJIJIJJJJJIJIJJJJJJIJIJJJJIJIJIIJIJJJIIJJIII, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ)
	{
		return null;
	}

	public static int IIIJIJJIIJJJJIIJJJJIIJJJIIJIIIIIJJIIJIIIIJIIIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return 0;
	}

	public static int JIIJJJJIIIIIJJJJJJIJJIIJJIIJIJIJJJJJJIJJIIJIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return 0;
	}

	public static int JIIJJJJIIIIIJJJJJJIJJIIJJIIJIJIJJJJJJIJJIIJIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIJIIJJIJIJIIJIJJJJIIIIJJJIJJIJJJIIJJIIIJIJJJIJ)
	{
		return 0;
	}

	public static int JIIJJIIJJIJJIJJIIJIIJIIJIIJIJJJJJIJIIJIIIIJIIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, int IIJIIIIIJIIIJJJIJJJJIJJJIIJJJJIIJIIIIIJJIJJJJII)
	{
		return 0;
	}

	public static void JJJIJJIJIIJJJJJIIJIJJIJIJJJJJIJJJJJJIIIIIIJJJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	public static void IIIIJJJJJJIJIIIJJJIJIJJIIIIJJIJJJIIIIIJJIJJIJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	public static void IJIIJJJJIIJJJJJIIIJJJIJJIJIJIJIJJIIJIIIJIIJJJIJ()
	{
	}

	public static void JJJIIIIJIIIJJIJJIIJJIJIJJIIJIIIIIIIJIIIIIJJIIII()
	{
	}

	public static void JJJIIIIJIIIJJIJJIIJJIJIJJIIJIIIIIIIJIIIIIJJIIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	public static void JJJIIIIJIIIJJIJJIIJJIJIJJIIJIIIIIIIJIIIIIJJIIII(UIWidget[] JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
	}

	public static void JIIJIIIIIJIIIIJJIIJJJIIIJJIJIJJIJIIJJIJIJIJIJJJ()
	{
	}

	public static UIPanel JIJIIJJJIJJIIJIIIJIJJIIJIIIJJIJIJJJJJJJIJJJIJJJ(bool JIJJIIIIJIIJIIJIIIIJJJJIIJJJJJIJIJJJJIJJJIIJIJI)
	{
		return null;
	}

	public static UIPanel JIJIIJJJIJJIIJIIIJIJJIIJIIIJJIJIJJJJJJJIJJJIJJJ(bool JIJJIIIIJIIJIIJIIIIJJJJIIJJJJJIJIJJJJIJJJIIJIJI, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ)
	{
		return null;
	}

	public static UIPanel JIJIIJJJIJJIIJIIIJIJJIIJIIIJJIJIJJJJJJJIJJJIJJJ(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ, bool JIJJIIIIJIIJIIJIIIIJJJJIIJJJJJIJIJJJJIJJJIIJIJI, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ)
	{
		return null;
	}

	public static void JIIJJIJIIIJIJJJIJIJIJIJJJIJIIJIIIIIIJJJIJJIJJJI(this Transform JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ)
	{
	}

	public static T IIJIJIJJIJJJIJJJJIIJIJIIJIIIJIIJIJIJJIJJIJIIJJJ<T>(this GameObject IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI) where T : Component
	{
		return null;
	}

	public static T IIJIJIJJIJJJIJJJJIIJIJIIJIIIJIIJIJIJJIJJIJIIJJJ<T>(this GameObject IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, bool JJJIIJIJIIIIJJIIIJIIJIJJJIIIIJJIJIJJJJIJJIJJIJJ) where T : Component
	{
		return null;
	}

	public static T IIIJIJJJIJJIIJJJJIIJJJJJJIIJJIJJJJIJIIIJIJJIJJJ<T>(this GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, int JJJIJJIIJJJJIJJJJIIJJJIJIJJIJJIIJIJIIIIIIJJJJII = int.MaxValue) where T : UIWidget
	{
		return null;
	}

	public static UISprite JJJJJIIJIJIJJJIJIIIIJJJIIJIIJIJJIJJJJJIJIJJIJJJ(this GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JJJIIIJJJIIIIIJIJIJJIIIJIIIIIIIJIIIJIIIIIIJJJJI, string JIJJIIIIIIIJIIJIJJIJIJJIIJJIIIIIJIJJIJJJIIIJIJJ, int JJJIJJIIJJJJIJJJJIIJJJIJIJJIJJIIJIJIIIIIIJJJJII = int.MaxValue)
	{
		return null;
	}

	public static GameObject JJJIJIIJJIJIIIJIIJJJIJIJJJJIIJJIJIJIJJJIJIIIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return null;
	}

	public static T JIIJJJJIJJJJIIIIIIIIJJJIJIIIIJIJIJJJJIIJIJIIIIJ<T>(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII) where T : Component
	{
		return null;
	}

	public static T JIIJJJJIJJJJIIIIIIIIJJJIJIIIIJIJIJJJJIIJIJIIIIJ<T>(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ) where T : Component
	{
		return null;
	}

	public static void JIJJJJJIIJIJIJIIJJIIIJIIJIIIIIJIJIJJJJIJJIIJJII(UnityEngine.Object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
	}

	public static void IIJIIJJIIIIIIJIJJIIIIJIJIJJIIIIIIJIJJJJIIJJJJII(this Transform JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
	{
	}

	public static void JJIJIIJIJIIIIJJIIIJJIIJIJJIIIIIIIIIIIJIJJJJIIII(UnityEngine.Object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
	}

	public static void IJIIIIJJJJIIJIIIJJIJIIJIIIJJIIIJJIIJJIIIJIIIJJJ(string JJJJIJIJJIIIIIIIIIIIJJIIJIIJIJJJIJJIIJJIJJJJIJI)
	{
	}

	public static void IJIIIIJJJJIIJIIIJJIJIIJIIIJJIIIJJIIJJIIIJIIIJJJ(string JJJJIJIJJIIIIIIIIIIIJJIIJIIJIJJJIJJIIJJIJJJJIJI, object JJJIIJJIJIJJIJJJIJIJIIJIIIIIJJIJJJJJIJJJJIIIIJJ)
	{
	}

	public static bool IIIJIIIIJJIIIIJIJIJIJIIIIJJIJIIJJJJJJJJJJIJIJII(Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, Transform IJIJJIJIIIJJIIIJJJJJIIIIJIIJIIIIIIJJJIJIIIJJJJJ)
	{
		return false;
	}

	private static void IIJJIIJIIJIJJIJJJJJJJIJJJIJIIIIJJIJJJJIIIIIIIIJ(Transform JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
	{
	}

	private static void IIJJIIJIIJIJJIJJJJJJJIJJJIJIIIIJJIJJJJIIIIIIIIJ(Transform JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ, bool JJIJJJIIIIIJIJJJIJJIJIIIJIIJIIIIIJJJJIJIIJIIJJJ)
	{
	}

	private static void IJIIJIJIJIJJJJJJJIJIJIIJIIJIIIIIJJJIJIIJJJIJIII(Transform JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
	{
	}

	public static void JIIIJJIIJIIIIIIJIIJJIJIJJJIIJJIIIIJJJJJIIIJJIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}

	public static void JIIIJJIIJIIIIIIJIIJJIJIJJJIIJJIIIIJJJJJIIIJJIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ, bool JJIJJJIIIIIJIJJJIJJIJIIIJIIJIIIIIJJJJIJIIJIIJJJ)
	{
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	private static void IIJIJJIJJJJJIJJJJJIIIIIIJIJJIIJIIIIJJIIJIJJJJII(Transform JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
	{
	}

	public static void JJIIIIIIJIJIIIJJIJIJJIJJIIIIJIIJJJJIJIIIJIJJIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}

	[Obsolete]
	public static bool JIIIIJJJIIJJIJJJIIJJJJIIIJIIIJIJIIIIJIIIJJJIIII(Behaviour IJJIJIJIIJIIIJJJJIJJIJJIJIJJIJJIIJJIJIIIIIIIIJI)
	{
		return false;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public static bool JIIIJJJJIIIJJIJJJIIIJJJIIJJIIJJJJJJJJJJIIJJIJII(Behaviour IJJIJIJIIJIIIJJJJIJJIJJIJIJJIJJIIJJIJIIIIIIIIJI)
	{
		return false;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public static bool JIIIJJJJIIIJJIJJJIIIJJJIIJJIIJJJJJJJJJJIIJJIJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return false;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static void IJJIJJJJJIIIIJJIJIIJJJJJIIJIIJJJJIIJJJIJIJIJIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}

	public static void IIJIJIJJJJIIJJJIJIJJIJJIJIIJJJJIIIIIJIIJIIIIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ)
	{
	}

	public static Vector3 JJIJJJIJJJIIJJJJIJJIIIIJJIIIJIJIIJIJIJIJJJJJJJI(Vector3 JIIJJJJJJIIJJIJIIIIIIJIIJIIIIIIJJJJJIJIIIJJJIJI)
	{
		return default;
	}

	public static void JIIIJIIIIIJIJIJJIIIIIJIJIIJIJIJIIIIJIJIIIIJIJJI(Transform JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
	{
	}

	public static void JIJJJIIJJJJIIIIIIJIIJIJJIJJJIJIJJJJJIIJIIJIIJII(this Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ, Transform JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ, bool JJJIJIIIIIIIJIIJIIIJJJJIIJIJIJJJIJIIIJIIJIJIIII = false, bool IIIIIIIIJIIIJIIJJIJIJIJJIIJIIIJJIIIIJIJIJIJIIII = true)
	{
	}

	public static void JIJJJIIJJJJIIIIIIJIIJIJJIJJJIJIJJJJJIIJIIJIIJII(this Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ, Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	public static void JIJJJIIJJJJIIIIIIJIIJIJJIJJJIJIJJJJJIIJIIJIIJII(this Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ, Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI, Transform IIJJIJIJJJJJIIIIIJJIJIJIJJIIIJIJJJIJJIIJIIJIIJI, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, bool JJJIJIIIIIIIJIIJIIIJJJJIIJIJIJJJIJIIIJIIJIJIIII = false)
	{
	}

	public static void JIJJJIIJJJJIIIIIIJIIJIJJIJJJIJIJJJJJIIJIIJIIJII(this Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ, Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI, Transform IIJJIJIJJJJJIIIIIJJIJIJIJJIIIJIJJJIJJIIJIIJIIJI, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, out Bounds JJIJIIJJJJJIJJJIIIIJIIIIIJIJIIIJIJIIJIIIIJJJJJJ, bool JJJIJIIIIIIIJIIJIIIJJJJIIJIJIJJJIJIIIJIIJIJIIII = false)
	{
		JJIJIIJJJJJIJJJIIIIJIIIIIJIJIIIJIJIIJIIIIJJJJJJ = default;
	}

	public static bool JJIJIIIIIJJIJJJIJIJIIIJJJJIJIJJJJJIIIIJJIJJIIJJ(string JJIIIJJJJJJIJJJIIJJJJIJJIIIJIJIJIIIJJIIIJIJIIJI, byte[] JIIIJJIJIJIJJJIIJIJJJJJIJIJIIIIJIIIIJJIIJIJJIIJ)
	{
		return false;
	}

	public static byte[] IIJJJIIIIJIJJJJIIJIJJJJJJIJJIIIIIIJJIIJJJIJJJJI(string JJIIIJJJJJJIJJJIIJJJJIJJIIIJIJIJIIIJJIIIJIJIIJI)
	{
		return null;
	}

	public static Color IIJJIIJIIJIIIJJJIJJJIIIIJIJJJIJIJJJIJIJJIIIIJII(Color IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
	{
		return default;
	}

	public static void IIIIJJIIJJJJJJIIJJJIJIIIIJJIJIIIJIIIIIIIJJJJIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	public static string IJIIJJJJIIJIJJJIJJIJIJIJJIJJIJJJJJIIJIIIJJJIJJJ()
	{
		return null;
	}

	public static void IJJIJIJIJJJIIIIJJIIIIIJIIIJIJJJJJJJJIIJIIIJJIIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	[Obsolete]
	public static string JJJJIIIJJJJJIJIIJIIIIIIIIJIIJIIIJJIJIJJIJJJIIII(Color IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
	{
		return null;
	}

	[Obsolete]
	public static Color IJIIJIIIIIIJIIJJJJIIJIJJJIIJJIIJIJJJJIIJJJIIJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, int IJJIJIIIIJIJIJJIIIIIIIJIIIJJIIIIJIJIJJIJIJIJIJJ)
	{
		return default;
	}

	[Obsolete]
	public static string IJIIJJJIIIIJJIIIJJJJJJJJJIJIJJIJIIJJJJJJJJIIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
		return null;
	}

	public static T IIIIIJJIIJIJJJIJIIJIIIJJIIIJJIIIIIIJIIJIIIJIJJI<T>(this GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII) where T : Component
	{
		return null;
	}

	public static Vector3[] JJJJJIJJIJJJJIIIIIIIIJIJIJIJIIIJJJIJIIIIIIIJIII(this Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ)
	{
		return null;
	}

	public static Vector3[] JJJJJIJJIJJJJIIIIIIIIJIJIJIJIIIJJJIJIIIIIIIJIII(this Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ, float JJJIJJIIJJJJIJJJJIIJJJIJIJJIJJIIJIJIIIIIIJJJJII)
	{
		return null;
	}

	public static Vector3[] JJJJJIJJIJJJJIIIIIIIIJIJIJIJIIIJJJIJIIIIIIIJIII(this Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ, Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
	{
		return null;
	}

	public static Vector3[] JJJJJIJJIJJJJIIIIIIIIJIJIJIJIIIJJJIJIIIIIIIJIII(this Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ, float JJJIJJIIJJJJIJJJJIIJJJIJIJJIJJIIJIJIIIIIIJJJJII, Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
	{
		return null;
	}

	public static Vector3[] IIJIIIJJIIJJJJJIIIIJJJJJJIIJIIIIJJIJJIJJIJIIJII(this Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ)
	{
		return null;
	}

	public static Vector3[] IIJIIIJJIIJJJJJIIIIJJJJJJIIJIIIIJJIJJIJJIJIIJII(this Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ, float JJJIJJIIJJJJIJJJJIIJJJIJIJJIJJIIJIJIIIIIIJJJJII)
	{
		return null;
	}

	public static Vector3[] IIJIIIJJIIJJJJJIIIIJJJJJJIIJIIIIJJIJJIJJIJIIJII(this Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ, Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
	{
		return null;
	}

	public static Vector3[] IIJIIIJJIIJJJJJIIIIJJJJJJIIJIIIIJJIJJIJJIJIIJII(this Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ, float JJJIJJIIJJJJIJJJJIIJJJIJIJJIJJIIJIJIIIIIIJJJJII, Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
	{
		return null;
	}

	public static string IIIIJIJJJIJJJJIJJJIIJJJJJIJIJJJJJJIJIJJIJJIIIII(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, string JJIJIJJJIIIIIJIJJJIIJJIJIIIJIJIIJIJIIJJJJJIJJJJ)
	{
		return null;
	}

	public static void IIJIJJIIJJIJIIIJIJIJJIIIIIIJIJIJIJJJJIJJIJIIIIJ<T>(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, string JJJJIJIJJIIIIIIIIIIIJJIIJIIJIJJJIJJIIJJIJJJJIJI) where T : Component
	{
	}

	public static void IIIIIIJJIJJJIIIIIJJIIJIJIIIJIJJIJIIIJJIIJJJJIJJ<T>(GameObject IIIIJIIIJIJJJJIIJJJIIIIIIJJJJJIJJJJJJIIIJIIJIJI, string JJJJIJIJJIIIIIIIIIIIJJIIJIIJIJJJIJJIIJJIJJJJIJI) where T : Component
	{
	}

	public static void IJIJIJIJJJJJIJIJJIIJJIIJIJIIJJJJIIJIJJIIJJIJJII(GameObject IIIIJIIIJIJJJJIIJJJIIIIIIJJJJJIJJJJJJIIIJIIJIJI)
	{
	}

	public static Vector2 JIIIJJJIJJJIJIIIJIIIJJIJIJIIJIIIJJJJIJIJIIIJJIJ()
	{
		return default;
	}

	public static string JIIIJJIIJIJJIIIJIJJJJJJJIJJIIIIJIIJJIJIIIJJIIJJ(KeyCode IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return null;
	}

	public static KeyCode IJJJIJJIIJJJIIIIJIJIIJJIIIJIIJIJIIJIJIIJIJJJIJI(string IJJIJJIIJIJIJJJJJIIIJIIIJJIIIJJIJJJJJJIJJIJJJJI)
	{
		return KeyCode.None;
	}

	public static T JJIJJIIIJJJIJIIIIJIJIJJJIIJIJIJJIJIJJJJJIJJJJIJ<T>(string IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, IJIIJIJJJIIIJIIJJJIIJIJIJJJJIJIJJJJIIJIIIIIIIII<T> JJIIIJJJJJIIJIJIJJIJJJIJJIJJIJIJJIJJJIJIJJIIJII = null) where T : UIWidget
	{
		return null;
	}

	public static Color JIIIIIIJIIIJJJJIJIIIJIJIIIJJIIJIJJIIJJJJJJIJIII(this Color IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
	{
		return default;
	}

	public static Color JIJIJIIJIJJJIJJIIJIIJJIJJIJIJJIIJJJIJJIIIIJJIIJ(this Color IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
	{
		return default;
	}

	public static bool JJJIIJJJIJIJJIJIIJIIJJJJJJJIJIIIJJJJJJIIIIIJJII(IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return false;
	}

	public static void IIIJJIIJJIIIJJIIJIIJIIJJIIIJJJIJIJJIJIJIJJIJJIJ(IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII IJJIJIJJIJIIIJJIIIIJIJJJIJJIJJJJJIJIIIJJIJJJJJI, IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JIJIJJIIIIIIIJJIJJIIIIJIJIIJIJIJJIIIJJJIJJJJIJJ)
	{
	}

	public static bool JJJIIJJJIJIJJIJIIJIIJJJJJJJIJIIIJJJJJJIIIIIJJII(JJIJJJJJIIJIIIIJIIJJJIIIIIJIIIJIJIJIIJJJIJJJIJI IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, JJIJJJJJIIJIIIIJIIJJJIIIIIJIIIJIJIJIIJJJIJJJIJI JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return false;
	}
}
