public class JIJIJJJIJJJJJJJIIJJJIJJJIIJJJIIIJIIIIIIIJJJJIII
{
	public const byte JJIIJJIJJJJIJJJJJJJIJJJJJIIIJJJIJJIJJIJIJJIJJII = byte.MaxValue;

	public const byte IIIIJIIJJIIJJJJJIIJIJJJJJIJJIIIIJIJIJIJJIJJIIJJ = 254;

	public const byte JIJJJIIIIJIJIIJJJIJJJIJIIIJIIJIJIIIJIIIJJIJJJII = 253;
}
