using System.Collections.Generic;
using UnityEngine;

public class JIJIJIJIIJIIIJJIJIJJIIJIIIIJJIIIJIIIIJJIJIIIIJJ
{
	public enum JJJJJIIIIJIJJJIJJIJJIIJIJIJJIIIIIJJIIJJJIIJJIIJ
	{
		Root = 0,
		Node = 1,
		Leaf = 2
	}

	public byte JJIJJIIIIJJJIJJJIIIIIIJIIIIIJJJIJIJIJIIJIIIIJII;

	public Vector3 IJIIJJJIJIJIIIIJJJIJJIIIIJJJIIIIJJIJJJJIJJJIIJJ;

	public Vector3 JJJIIJIIJJJJJJJIJIIJIJIIJJJIJIJJJIJJIIIIJIJIIIJ;

	public Vector3 IJIJJJIJJIJJIIIIIJJJIJIIIJIIIJIIJJJJIIIJIIIJIJJ;

	public Vector3 IJJJJJIJIJIJJIIIJIJJIJIIJJIJIJIJIIIIIJJIJIIJIIJ;

	public JJJJJIIIIJIJJJIJJIJJIIJIJIJJIIIIIJJIIJJJIIJJIIJ IJJJIJJIJIJJJJIIIIIIIIJJIJJJJJIJJJIIIIIJJIJJIII;

	public JIJIJIJIIJIIIJJIJIJJIIJIIIIJJIIIJIIIIJJIJIIIIJJ IJJJIJIJJJJIIJIIJIIJIJJIIJIJJIJJIIIIIIIJIJJJIJJ;

	public List<JIJIJIJIIJIIIJJIJIJJIIJIIIIJJIIIJIIIIJJIJIIIIJJ> JIIJIIJJJJIJIJJJIIJIJIJIIJJIJIJIJJIJJJJIIIJJIJJ;

	private float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ;

	public void IIJJJJIIIJJJJIIIJJIIIIJJJJIIIJIIIJJIIJIJIJJIIJJ()
	{
	}

	public void JJIJJIIIJJJIJIIIIJIJIJJJIIJIJIJJIJIJJJJJIJJJJIJ()
	{
	}

	public void JJIIIIIJIJJIJIJJIIIJIIJIIIIIJIIJJIIJIIJIJIIJIJJ(JIJIJIJIIJIIIJJIJIJJIIJIIIIJJIIIJIIIIJJIJIIIIJJ IJIJJIJIIIJJIIIJJJJJIIIIJIIJIIIIIIJJJIJIIIJJJJJ)
	{
	}

	public void JIIIIJIIJIIIIJJJJJIIJIJIIJJJIJJIIIIIIJJJJIJIIII(List<byte> IJJJJIJJIJJIJIIIIIIJJJIIIIJJIIIJIJIIJIIJIJIIJJJ, bool IIIJJJIJJIJIJJIJJIIIJJJJIIIJIJIIIIIIIIJIJJJIIJJ, Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ)
	{
	}

	public void JIIIJIJIJIJIJJJJIJIJIIIIJIJIIJJJJIJJIJJJIIJJJII(JIJIJIJIIJIIIJJIJIJJIIJIIIIJJIIIJIIIIJJIJIIIIJJ IJIJJIJIIIJJIIIJJJJJIIIIJIIJIIIIIIJJJIJIIIJJJJJ)
	{
	}

	public void IIJIJIJJIJJJIJJJJIIJIJIIJIIIJIIJIJIJJIJJIJIIJJJ(JIJIJIJIIJIIIJJIJIJJIIJIIIIJJIIIJIIIIJJIJIIIIJJ IJIJJIJIIIJJIIIJJJJJIIIIJIIJIIIIIIJJJIJIIIJJJJJ)
	{
	}

	public bool JJIIJIIJIJIIIIJJJJIJIJIIJJJIIIJIIJIIIJJJJIJIJII(bool IIIJJJIJJIJIJJIJJIIIJJJJIIIJIJIIIIIIIIJIJJJIIJJ, Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII)
	{
		return false;
	}

	public bool JIJIIJJJIJJJJJIIIJJIIIJJJIIIJJIJIIJJJIJIJJJIIJJ(bool IIIJJJIJJIJIJJIJJIIIJJJJIIIJIJIIIIIIIIJIJJJIIJJ, Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII)
	{
		return false;
	}

	public void IIJIIIIJJIIJIIIIJIIJJIIJJJIIIIJJIJJIJIJIIIIJIJI(JIJIJIJIIJIIIJJIJIJJIIJIIIIJJIIIJIIIIJJIJIIIIJJ IJIJJIJIIIJJIIIJJJJJIIIIJIIJIIIIIIJJJIJIIIJJJJJ)
	{
	}

	public bool JJIIIJIIJJIJIIIJIIJIJJIJJIIJJIIJJJIIIJJJIJIIIJI(bool IIIJJJIJJIJIJJIJJIIIJJJJIIIJIJIIIIIIIIJIJJJIIJJ, Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII)
	{
		return false;
	}

	public bool JJJIIIIIJIJJIJIJJJIIIIJJJIJIJJJIIIJIJIJJJIJIIII(bool IIIJJJIJJIJIJJIJJIIIJJJJIIIJIJIIIIIIIIJIJJJIIJJ, Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII)
	{
		return false;
	}

	public void JJJJIIIIIJIIJIJIJJJJIJIJJJJJIIJIJJIJJJJJJJIJIIJ(List<byte> IJJJJIJJIJJIJIIIIIIJJJIIIIJJIIIJIJIIJIIJIJIIJJJ, bool IIIJJJIJJIJIJJIJJIIIJJJJIIIJIJIIIIIIIIJIJJJIIJJ, Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ)
	{
	}

	public void IIIJIIIIJIJJJJIIIJJIJIIIIJJJIIIIJIIJJJJIIJIIIJI(List<byte> IJJJJIJJIJJIJIIIIIIJJJIIIIJJIIIJIJIIJIIJIJIIJJJ, bool IIIJJJIJJIJIJJIJJIIIJJJJIIIJIJIIIIIIIIJIJJJIIJJ, Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ)
	{
	}

	public JIJIJIJIIJIIIJJIJIJJIIJIIIIJJIIIJIIIIJJIJIIIIJJ(byte IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, JJJJJIIIIJIJJJIJJIJJIIJIJIJJIIIIIJJIIJJJIIJJIIJ JIJIIIJIIIIIIJJJIIIJJIJJJIIIJJJIIJJIIIJJJJIIJIJ, JIJIJIJIIJIIIJJIJIJJIIJIIIIJJIIIJIIIIJJIJIIIIJJ IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI)
	{
	}

	public void JJJIIJJJIIJIJIJJJIIJIJIIIIJJIJJJJIIJJIIIJJJIJIJ()
	{
	}

	public bool IIJJIJJIJIIJIJJJJIIIJIIJIIIJIJJJJIJJJJJJJJJIIJI(bool IIIJJJIJJIJIJJIJJIIIJJJJIIIJIJIIIIIIIIJIJJJIIJJ, Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII)
	{
		return false;
	}

	public bool JJJJJIIJIIIIIJJJJIIIIJIJJIJIIIJIJJJJIIIIJIJJJJI(bool IIIJJJIJJIJIJJIJJIIIJJJJIIIJIJIIIIIIIIJIJJJIIJJ, Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII)
	{
		return false;
	}

	public bool JJJIIJJIIIIJIIIIJIJJJIIJJIJJJJJIJJIJIIJIIJIIIIJ(bool IIIJJJIJJIJIJJIJJIIIJJJJIIIJIJIIIIIIIIJIJJJIIJJ, Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII)
	{
		return false;
	}

	public JIJIJIJIIJIIIJJIJIJJIIJIIIIJJIIIJIIIIJJIJIIIIJJ()
	{
	}

	public bool IJJJJIIJIIJIJIJIJJIIIJJIIIJIIIJJJIIJJIJIJJIIIJJ(bool IIIJJJIJJIJIJJIJJIIIJJJJIIIJIJIIIIIIIIJIJJJIIJJ, Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII)
	{
		return false;
	}
}
