using UnityEngine;

public class JIJJIJJIJJJJJIIIIIIJJIJIIIIIIIJJJIIJIIJIIJJJJII : AndroidJavaProxy
{
	private JIIJJJIIJIIIJIJIJIIJJIIIIJJJIJJIJJIJJJJIJJJIJJJ IIJJJIJJIIJIIJJJIIIJJJJIJJIJIJJIIIIJJJIIJIIJJJJ;

	private void onMrecShown()
	{
	}

	private void JIJIIIIIIIIJIIIIIIIIJIJIIIIIJJJIJIJIJIIJJJIIJJI()
	{
	}

	private void JIIIIIIJIJIJJJJJIIJIIJJIIJJJIIJJIJJIJIJJJJIIJJJ()
	{
	}

	private void JIIIIIIIIJIJIJJJIIJJIIIJIIIJJJIIJIJIIJJJIIIIJII(bool isPrecache)
	{
	}

	private void IJIIIJJIIIJIJIIJJIJJIIIIJIJJJJIIIJIJJJIIIIIJIJI(bool isPrecache)
	{
	}

	private void IIJJIIJJJJJIIIIIIIIJIIIIIIJJJIJJIIIIJIIJIJJJIII()
	{
	}

	internal JIJJIJJIJJJJJIIIIIIJJIJIIIIIIIJJJIIJIIJIIJJJJII(JIIJJJIIJIIIJIJIJIIJJIIIIJJJIJJIJJIJJJJIJJJIJJJ IIJJJIJJIIJIIJJJIIIJJJJIJJIJIJJIIIIJJJIIJIIJJJJ)
		: base((string)null)
	{
	}

	private void IJIJIIJIIJIJJIIJIJJIJIJIIIJJJJIIJJJJJIIJJJJJIIJ()
	{
	}

	private void IIIJJIJJIIIJJIIJIJJIIIJJJJIJIJIJJJIIJIIJJIJIIII(bool isPrecache)
	{
	}

	private void JJIJJIJJJIJIJJIJJJIIIJIJIJJJIIIJJIJIJIJIJIIJJII()
	{
	}

	private void IIIIJJJJIJIJIIIJIJJJJIIIIIJIIIIIIIIIJJIJJIIJJII()
	{
	}

	private void JJIIIIJJIIIJIJJJJIIJJIJJIJJJIJJJIIJJIJJJIIJIIII()
	{
	}

	private void IJJJIJJIIIIIJIIJIJJIJJJIJJJIIIIIJJIIIIJJJJIIJIJ()
	{
	}

	private void IIJIIIJJJJIJIIIJJJIIIIJJJIIJJIIJJJIJIJJIJJIIJJI()
	{
	}

	private void onMrecExpired()
	{
	}

	private void IIJJIJIIIIJJIIIIIJIIIJJIJJIIIJIIJJJJIJJJIIJJJJJ()
	{
	}

	private void onMrecLoaded(bool isPrecache)
	{
	}

	private void onMrecClicked()
	{
	}

	private void onMrecFailedToLoad()
	{
	}

	private void JJIJIIIIIJIJJJIIIIJJIIJIJIJIIJJIIJIJIIIIIJIJIJJ()
	{
	}

	private void IIIIIJJJIIJIJIJIJIIJIJJIJIIIIJJJJJJJJJIJIJJIIIJ(bool isPrecache)
	{
	}

	private void IIIJJJJIIJIIIJIIJJJIIJJIJIJJJIJJJIJIIJJJIIIJIIJ()
	{
	}

	private void JJJJIJIJIIJIIJIJIIJJJIJIJIJIIJJJJIIJIIIIIIJIJIJ()
	{
	}

	private void JIIIIIJJJIJIIJJJJIJIJJIJJJJJIJJJJIIJJIIIJIIJJJI(bool isPrecache)
	{
	}

	private void IJIJIJIIIIJJJJIJJJIJIIIJJJIJJIIJJJIJIJIIIIIJJII()
	{
	}
}
