using UnityEngine;

public class JIJJIIIIJJJJIIJIJJJIIJJJJIIIJIJJJIJIIIJIIJIJJIJ : AndroidJavaProxy
{
	private IJJIIJIJIIIIIJIIIJJJIIJJJJIIIIJJIJIIJJIJIIIIJJI IIJJJIJJIIJIIJJJIIIJJJJIJJIJIJJIIIIJJJIIJIIJJJJ;

	private void JIIIJIJJJJIIJIJJJIJJJJJIIJIJIIJJJIIJJJIIJJIJIIJ(int result)
	{
	}

	private void writeExternalStorageResponse(int result)
	{
	}

	private void IJJJJJIIJIJJJIJJJIIIJIJIJJIIJJIIIIJJIIJJIJIIJIJ(int result)
	{
	}

	private void IJIIJIIIJIIIJJIJJJIIJJJIIJIJIJIJJIIIIIIIIJJIIJI(int result)
	{
	}

	private void IJIIJIJJIIJIJJIJIJIIIJIJIJJJIIJIIJIIJJJIIJIIIII(int result)
	{
	}

	private void JIIIJIJJJIIIJIIJJIJIJJJIJJJIIJIJIIIIIIJIIIIIIJJ(int result)
	{
	}

	private void IJJJJJIIJJJJIJJJJJJIIJIJIIJIIJJIJJJJIIJIIJJIJII(int result)
	{
	}

	private void IIJIJJJIJJJJIIJIIIJIIIJIIIJIIIJIJIIJIJJJIJJJJJI(int result)
	{
	}

	private void IJIJIJIJIJIIJJJJIIIIJIJJIJJJIJIJJJJJIIIJIJIIIIJ(int result)
	{
	}

	private void IJJJJIIJIJJIJJJIIIJIJIJIIIJJJJJIIJJIJJIJJIIJJJJ(int result)
	{
	}

	private void JJJIJJJJJIJJJIJIJJJIIJJIJJJIJJIIIIJJJIIJJIIIJJJ(int result)
	{
	}

	internal JIJJIIIIJJJJIIJIJJJIIJJJJIIIJIJJJIJIIIJIIJIJJIJ(IJJIIJIJIIIIIJIIIJJJIIJJJJIIIIJJIJIIJJIJIIIIJJI IIJJJIJJIIJIIJJJIIIJJJJIJJIJIJJIIIIJJJIIJIIJJJJ)
		: base((string)null)
	{
	}

	private void JIJJJJIIJIIIJJJJJJIIJJIIJJIIJJIIJIIIIJIJIIJJJJI(int result)
	{
	}

	private void IJJJIJIJJIIIIJJJIJIIJJIIIIIIJIIIIJIJIIJIIJIIIII(int result)
	{
	}

	private void IJIJJIIJIIIIIJIIIIIIIJJIIIIIJIIIJJJIJIJIJJIJJII(int result)
	{
	}

	private void IIJIJJJJJJJJJIIJJJJIIIJIIJJIJIJIIIJIJJIIJJIIJJI(int result)
	{
	}

	private void JIJJIIJJJJIIIIIJIIJJJIJIIIJJJIIIIIJJIIJJIIJIJII(int result)
	{
	}

	private void JJIIIIIJIIJJJIIJJIJIIIJJIIIJJIIJIIJIJJJIJIJIIJJ(int result)
	{
	}

	private void accessCoarseLocationResponse(int result)
	{
	}

	private void IIIIIJIIIJJIIIIJJJJJJJIIIJJIJIIIIJJJIJJJIIJJJIJ(int result)
	{
	}

	private void JIIJIJJJJJJJIJJJJJJIJJIJIIJJJJIJJIJJJIJIIIIJJIJ(int result)
	{
	}
}
