using UnityEngine.SceneManagement;
using System.Collections.Generic;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class JIJJJIIJJIIJIIIJIJIIIJIIIIJIIIJJJJJIIJIJIJIIJII
{
	public static bool IJJIIIIIIJIIIIIJJIIJJIJIJJJIJIJJJJIJJJJJIJJIJIJ;

	private static Dictionary<GameMode, List<string>> IIJIIJJIIIIIJIIIJJIJJIIIIIIJJIIIJJJIIJIIIIJJJII;

	private static List<string> JJJIIIJJIJIIJJJJJIIJIJJJJIIJIJJIIIJIIIIIIJIIIJJ;

	public static bool JIJIJIJIJJJIJIJJJIIIJJIJIJIJIIIJJJJIIIJIIJJIJJJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
		return false;
	}

	public static string JIIJJJJJIIJIIJJJJIIJIJJJJIIIJJJJIJJIJIJJIJJJJJJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI, string JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ)
	{
		return null;
	}

	public static List<string> JJJIJJIIJIIIJJIIJJJIIIJJJJJIJIJJJJJJJJIJIIJIIJJ()
	{
		return null;
	}

	public static void IIIJJIJJJJIJIIJIIIIIIIIIJJIIJJIJJJIIIJIJJJJIJIJ()
	{
	}

	public static void IIIJJJJJJIJIJIIJIJIIIJJIJJIJJIIIJIJIJJJIJJJIJJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	SceneManager.LoadScene(JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ);
	}

	public static bool IJJIIIJJIIIIIIJIIJJIJIJJJIJIIJIIJIJIJJIIJJJJJJI(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI, string JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ)
	{
		return false;
	}

	public static List<string> JIIJIIJJJJIIJJJJJIJIJJJJJJIIIJIJJIJIIJJIJJIIIIJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
		return null;
	}

	public static void JIJJJIIJJIIJIIIJIJIIIJIJIIJIIIJJJJIIIJIJIJIIJII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	SceneManager.LoadScene(JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ);
	}

	public static string JIIIIIJJJJIIJJIIJJIJIJJJJIJIIIJJJIIIJJIIJIJIIJI()
	{
		return null;
	}

	private static string JJJIIIJJIJJIIIIJIIIIJIJIIIIJJIIIJIJIJJJJJIIJIIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
		return null;
	}

	public static bool JIIJJJIIIIJIJIJJJJJIJJJJJJIIIIIJIJIIJIJJIJIJIII(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
		return false;
	}

	public static bool JJJJJJJIJIJIIIIIIIIIJIJJJIJJIIJJJJIIIJJIIJJIIIJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI, string JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ)
	{
		return false;
	}

	public static void IJJIJJJIJIJJIJIIJJIIJIIJJIIJJJJJIIIJJJJJJJJIJJJ()
	{
	}

	public static List<string> IIIIJIJJIJJIIJJIJJIJIIJJJJJIIIIJJJJIJIJJIJJJJJJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
		return null;
	}

	public static string JIIJJJJJIIJIIJJJJIIJIJJJJIIIJJJJIJJIJIJJIJJJJJJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
		return null;
	}

	public static bool JIIIJJIIIIJJIJJJJIJJJIJJJJJJIJJJIJJJJIJJIJJIIII(string JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ)
	{
		return false;
	}

	public static bool JIIJIIIJIJIIJIIIJJJIIJIJJJJIJJIJJJJIJJIJJIIIIJJ(string JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ)
	{
		return false;
	}

	public static void IIJIIJJIJIIIIIIJIJJIJJIJIJIIJIIIIIIIJJIIJJIJIJJ()
	{
	}

	public static bool JIJIJIJIJJJIJIJJJIIIJJIJIJIJIIIJJJJIIIJIIJJIJJJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI, string JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ)
	{
		return false;
	}

	public static List<string> IIJIIIJIJIIJJIJIJIJIJJIJIIIIIJIIIIIJIIIIIJIIJII()
	{
		return null;
	}

	public static void JIIIJJJIJJIJJIIIJJJJIIIJIJJIIJIJJJJJJIIIJJJJJIJ()
	{
	}

	public static void JIIJJJIIIJJJJJIIIJJJIJIIJJIJJIJIIJJIJJJIJIIIIJI(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	SceneManager.LoadScene(JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ);
	}

	public static bool IIJJIIIIJJIIJIJIIIIIIIIJIIIIJIIJJJJJIIIJJJJJJIJ(string JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ)
	{
		return false;
	}

	public static bool IIIJJIJIIJIIJJJIIIJJJIJIIIIJJJJJIJJJIIIJIIJIJJJ(string JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ)
	{
		return false;
	}

	public static string JIJJIJJJJIIJIIIIIIIJIIIJIIIIIJJIIJIIIIJJIIJJIII()
	{
		return null;
	}
}
