using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;
using UnityEngine.EventSystems;

public class JIJJIIIJIJJJIIJIIIIIJIJJIJIJJJIIIIIJJIIIJIIJJJI
{
	public class IJIJJJJIIIIIJIIJJJIIIIJJIJIIJIJJIIIIJIIIIIJIIII
	{
		public float JJIJIIJIJJIJJJJIJJJIJJIJJIJJIJJIJJIIJIJJJIIIJJI;

		public Vector2 JIIIJJJIIJIIJIIIIJIJIJJJIJJJJJJIJIIIJJJIIIJIJIJ;

		public Vector3 IJJIIJJJJIIJIIIIIIIIIJJJIIIJJIJIJIIJJIJIIJIIIII(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 JJIIIJIIJJIJJJIIIIJIJIIIIJJIIJJIJJIIJJJIJIIJIIJ(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 IIIIIIIJIJJJIIJIJJIJJJJIJJJIIIIJJIJIJIIJIIIJJJJ(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 IJIIIIIIJJJIIIIIIIIIIJIJJJIJJJJIIJJJIIJIIIIJJJJ(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 IJJIJIIIIJJJIJJJIIJJIJJJIJIIJJIJJIJIJIIIJJJJJJI(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 JIJIJJIJJIJJIJJIIJIJJIIIJJIIIIIJIIIJIIIIJJIJJII(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 JIIJJJIJJJIJJIJJJJJJJJIJJIIIIJIIIIJJIJJJJIJIJIJ(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 IIIIIJIIJIIIIJIJIIJJJIJIIIJIIJJIIIJJJJIJJJJJJJI(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 JIJIJJIJIIJIIJJIIIJIIJIJJIIIJJJIIIJIJJJIIIIIIII(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 IIJIJJJIJJIIIIJIJIJJIIIJJIIJIJIJIIIIJIJJIJJIIIJ(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 IIJIJIJJIIIJIJJJIJJIJJJIIJJJJIJJJJJJJIIIJIJIJJJ(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 IJIIIJJIIIIJIJIJIJJIIJIJJIJJJIJIIIIJIIIIIJJJIIJ(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 IIIJJJIIJJJIJJJIIJIJJIIJJJJIJIIIJIIJIIIJJIJJIII(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 IIIJIIIJJJJIIJIIJIIIIJIJIJIIJJJIJIJJJIJJIJJIJIJ(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 IIJIJIJIIJIIJIJIJIIJJIIIIIIJJJJIIJIIJIIJJIIJJIJ(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 JJIJJJJJIIJIIJJJIJIIJJJIIIJJIIIIJJIJJJIIJIIJJJJ(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 JJJJJIJIJIIJIJIIIIIIIIIJIIJIJJIIJJJIJJJJJIJJJJJ(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}

		public Vector3 IJJIIIIJIIJIIJJIIIIJIIIJJJIIJJJJJJIIJIJIIJIJIII(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
		{
			return default;
		}
	}

	public int JJJIIJJIIIJJJJIJJIIJJJJJJJJJJJIJIJIJJIJJJIJJJII;

	public float JJIJIIJIJJIJJJJIJJJIJJIJJIJJIJJIJJIIJIJJJIIIJJI;

	public bool JJIJJJIJIJIIIIIIIJJJJIJJJIIIJJIIIIIJJJJJJJIJIJI;

	public bool IIIJJIJJJJJJJIIIJIJIIJIJIIJJIIJJJIIIJIJJJJIJIJJ;

	public bool IIJJIJJJJJIIIJJJIIIJJJIJJIJIIJIIIJIIJJJJIIIJIJI;

	public int JIIJJIIJJIJJIIIIJJJJIIIJJIIIIIIIIJJIJIJIJJIJJIJ;

	public Vector2 JIJIJIJIIIJJJIIIIJJIJIJIIIIIJJJJIIJIIJJIIJJIJII;

	public Vector2 IJJJIIIJJJIJIIJJJJIJIJJJIIIIIJIJJIJJJIJJIJJJJII;

	public float JIJIJJIJIIIIJJIIJJJJJJIIJIJIIIJIIIIJIJJJIIJJJJJ;

	public bool JJJIJIJJIJIJJIIIIJIIIJIJIIIJIIIIIIIJIIIIIIIIJII;

	public bool IJJJIIIJJIJJIIIIIIIJJJJJIIJJIJJIIIJIIJIJJJIJIJJ;

	public Vector2 JIIIJJJIIJIIJIIIIJIJIJJJIJJJJJJIJIIIJJJIIIJIJIJ;

	public bool IJJJIIJJIIJIIIIJIIIJIIJIJJJJJJJIIIIIJIJIJIJIIIJ;

	public List<IJIJJJJIIIIIJIIJJJIIIIJJIJIIJIJJIIIIJIIIIIJIIII> IJIIIIJJJIJIIJJIJIIJJIJIJIJJIIIIJJIIJJIIJJJJIIJ;

	private static List<RaycastResult> JIJIIJIIIIJIJJIJIJIJIIIJJJJJJJIJIJIJIJJJJIJJJII;

	private static List<IJIJJJJIIIIIJIIJJJIIIIJJIJIIJIJJIIIIJIIIIIJIIII> JIJJIJJJIIJJJJJJJJJIJJJJIIIIIJIJJIIIIJJIJJIIJJJ;

	public bool JIIIIJJJIIJJIJJJIIJJJJIIIJIIIJIJIIIIJIIIJJJIIII => IJJJJJIIJJJJIIIIIJJIJIJIIIJJIIIJIIIJJIJIJJIJIIJ();

	public float JJIJJJJJIIIJIJIJIIJJIJIJJIIJJIJJJIJJJIIIJJJJJJI => JIIJJIIJIJIIJIJIIJIIIJIIJIJJJIJJJIIJJJIJIIIIIJJ();

	public bool JJJIIIIJIJIIIIIJIJIIIIJIIJJIIIIJJJIIJJJJIJIJJJI => JIIIJIJJJJIJJIIJIIIIIJIIIIJJJIIJIJJIIIJJJIIJIJI();

	public bool JIIJJJJIJIIJIJIIJJIJIJJIIJIJJIJJIIJIIJJJJIIIJII => IIJIJIJJJJJIIJIIJJJJJIJJIJIJIJIIIIIIIJIIIJIIIII();

	public bool JJIJIJJJIJJIJIIJJIJJJJIJIJIIIJJJJIIIJJIIJJJIIIJ => IIIIJIJIJJIIJJJIIJIJJJIIJJIIIIIJIIIIIIIIJJIIJII();

	public bool IJJIJJJIIIJIIJIIJIJIIJIJJIJJIIIIJJIJJIJIJIJIJJI => IIJJJJJJJJJJIJIIJJJIIJIJJIIJJIIIIJIJIIJIIJJJJIJ();

	public bool IJIIIIJJIIJIJJJIJJIJIIIIJJIIJIJIIIIIJJJIIIJIIII => JJIJIIJJJIIJIJJIJJJIIIIJJJIJIJJJIIJJJJJIIJIIJII();

	public Vector2 JIIIIJIIIJJJJIJIIIIJJIIIIIJIIJJIJJIIIJIIIJJJIIJ => IIIIJJJIJJIIJJIJIIJIJJJIJJJJIIIJJIJIIIIIJIIIIIJ();

	public Vector2 JJIIIIJJJIIIIIIIJIJJJIJIIIJIJIJIJJIJJIIIJJIJJJI => JIJIJJJJIJJJJJJJJJIIJIJJJJJIJIIJIIIIJIIJIJIIJII();

	public Vector2 JIJIJJJJJIIIIJJIJJIIJJIIIIJIJIIIJJJIJIIIIIJJIII => IJJIIIIIIIJJIJJJJIIJJIJIJJIJIIJIIIIJJIJJJIJJJIJ();

	public Vector2 IJJIIJJIIJIJJIJIJJJJIJIIIIIIJIIIIJJIIIJJJIIJIJI => IJIIIJJIIJJJJIJIIIJIIJIIIJJIJIIIJJJJIIIJIJJJIJJ();

	public Vector2 IJJIJIJJIJJIIIIJIIJIJJIIJJIJIIJJJIIIJIIIJIIJIJJ => JIIIJJJJIJJJJJJJIJIIIJIIJIJJIIIIJJIIJIJIJIIIIJI();

	public Vector2 IJIJJIJJIIJJJIJJIJJIJIIJIIJJJJIJJIJJIJIIIIIJJII => JJIIIIIIJIIJJIIJJIJJJIIIJJJIIIJIJJIJIJIIJJJJJJI();

	public Vector2 JIJJIIJIIIJJJJIJIJIJJIIIIIIJJJIIIJIJJJIIIJJJJIJ => JJIJJIJIIIIIIIIJIJJIJIIJIIJIIJIJIJIJJJIIJIIJIIJ();

	public float JIJJJIIIJIJIJIJJIJJJJJJIJIJJJJJJJIIJIIJJIIIIJII => JIIIJIJIIIIIIJJIJJIJJJIIIJIJIIIJIJJJIIJIIIIIIJJ();

	public void IJJJJIIJJIJIIIIIIIJIIJIJIIJIIIJIJJJJJIJIJIJJIJJ()
	{
	}

	public float JIJJJIJJIJIJIIIJJJIJIIIIJJJIJJIIIJJJJIIIIJJIJIJ(Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
	{
		return 0f;
	}

	public Vector3 JJIIIIIIIIJIIIIIIJJJJJJJJJIIIIIIJIJIIIIJIJIJIII(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
	{
		return default;
	}

	public float JJIIIIIJJJIIIIIJJIIIJJJIJIJIJIIJJIIIJJJIIJJJJIJ(Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
	{
		return 0f;
	}

	public Vector3 IIJIJJJIJJIIIIJIJIJJIIIJJIIJIJIJIIIIJIJJIJJIIIJ(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
	{
		return default;
	}

	public bool IIIIJIJIJJIIJJJIIJIJJJIIJJIIIIIJIIIIIIIIJJIIJII()
	{
		return false;
	}

	public void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(Texture IIJIJIIIJJJIIIJJIIJJIJIIIIIIJJJIIJIJIJJIIIJIIIJ)
	{
	}

	public Vector3 IIIIJIIIIJJJJIIIIJIJIIJIIJJJJIIJJIJIIJIJJJJIJII(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
	{
		return default;
	}

	public Vector2 JIJIJJJJIJJJJJJJJJIIJIJJJJJIJIIJIIIIJIIJIJIIJII()
	{
		return default;
	}

	public bool IIJJJJJJJJJJIJIIJJJIIJIJJIIJJIIIIJIJIIJIIJJJJIJ()
	{
		return false;
	}
	public Vector2 IIIJJJJJIJIIJJIJJIJJJJJJJIJJJJJJJJIJJJJJIJJJJJJ()
	{
		return default;
	}

	public Vector2 JJIJJIJIIIIIIIIJIJJIJIIJIIJIIJIJIJIJJJIIJIIJIIJ()
	{
		return default;
	}

	public void JJJIIIJIIIIJIIIJIJJJIJJJIJJJJIIJIIIJJIIIJJIIIJI(int IJIIJJJIJJJIIJJIJIJIIJJIJIIIJJIJJIJJJIIJIJIJJIJ = -1)
	{
	}

	public float IIJJJJIJIIIJJIJIIJJIJIIIJIJJIJJJIIJJJJIJIIIIJJI(Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
	{
		return 0f;
	}

	public Vector2 IIIIJJJIJJIIJJIJIIJIJJJIJJJJIIIJJIJIIIIIJIIIIIJ()
	{
		return default;
	}

	public Vector2 IJJIIIIIIIJJIJJJJIIJJIJIJJIJIIJIIIIJJIJJJIJJJIJ()
	{
		return default;
	}

	public float IIIIJJIJIJJJIJJIJIIIIJJJJJIJJIJIJIJIIJIJIJIJJII(Vector2 IJIJIJJJJIIIJIIJJIJJJIIIIIJIJIJJIIJJIIIIJIJIJII, Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
	{
		return 0f;
	}

	public Vector2 JIJJIJJJIJIJJJIIJJIIJIJJIJIJIJIIIJJJIIIJJJIIIIJ(float JIJIIIJIJJJJJJJJJIIJJIIJJJIIIIIIJIJJJJJIJIIIJIJ)
	{
		return default;
	}

	public float JIJJIIIIJIIIJJIIIJIIIJJIIJJIJJIJJJJJJJJJIIJJJIJ(Vector2 IJIJIJJJJIIIJIIJJIJJJIIIIIJIJIJJIIJJIIIIJIJIJII, Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
	{
		return 0f;
	}

	public bool IJJJJJIIJJJJIIIIIJJIJIJIIIJJIIIJIIIJJIJIJJIJIIJ()
	{
		return false;
	}

	public Vector3 JIJJJIJIJIIIIJJJIJIJJIJJJIJJIJJJIIJIIJJIIIIJJJJ(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
	{
		return default;
	}

	public Ray IJIIJJIJIJIJJJIJIJIJJJIIJIJJJIIJIIJJIJJJJIIJIJJ(Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
	{
		return default;
	}

	public Vector2 JIIIJJJJIJJJJJJJIJIIIJIIJIJJIIIIJJIIJIJIJIIIIJI()
	{
		return default;
	}

	public Vector2 IJIIIJJIIJJJJIJIIIJIIJIIIJJIJIIIJJJJIIIJIJJJIJJ()
	{
		return default;
	}

	public float JIJJIIIIJIIIJJIIIJIIIJJIIJJIJJIJJJJJJJJJIIJJJIJ(Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
	{
		return 0f;
	}

	public float IIJIIJJJJJIIIIIIIIIJIJJIJIIJIJJJJIJIJIIIJJIJIII(Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
	{
		return 0f;
	}

	public float IIIJIIJJIJJJIJJIIIJJIIJJIIJJJJIJJJJJJJJIJJIJIII(Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
	{
		return 0f;
	}

	public void JIJIJIJIIIJIIJIIJJIIJJIJIJJJJJIIJIJJJJIIJJJIJII(int IJIIJJJIJJJIIJJIJIJIIJJIJIIIJJIJJIJJJIIJIJIJJIJ = -1)
	{
	}

	public Vector2 JJJJIIIIJIIIJJIIJIJIJJIJJJJIJIIIJJIJIIIIIJJJJII(float JJIJIIJJIIIIIIJJJJJJJIIIJIJJIJIIJJIIIJIJIJJIIJJ)
	{
		return default;
	}

	public Vector2 JIJJIIJJJIIJJJIIIJJIJIIIIJIJJIIIJIIJJIJJJIJJJIJ(float JIJIIIJIJJJJJJJJJIIJJIIJJJIIIIIIJIJJJJJIJIIIJIJ)
	{
		return default;
	}

	public float JIIJJIIJIJIIJIJIIJIIIJIIJIJJJIJJJIIJJJIJIIIIIJJ()
	{
		return 0f;
	}
	public float IIJIIIJJIIIIJJIIJIJJJJIIIIIIIJIIIIJJIJJIIJJIIJJ()
	{
		return 0f;
	}

	public float JIIIJJJIJIIIIIJIJIJJJJJIIJIJJIIJIJIIIJJIJJJIIJI(Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
	{
		return 0f;
	}

	public float IJIIIJIJJIJIIJJIIJIIJIJJJIIIJJIIIJJJJIIJIJIJJJI(Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
	{
		return 0f;
	}

	public float IIIIJJIJIJJJIJJIJIIIIJJJJJIJJIJIJIJIIJIJIJIJJII(Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
	{
		return 0f;
	}

	public Vector2 JJIIIIIIJIIJJIIJJIJJJIIIJJJIIIJIJJIJIJIIJJJJJJI()
	{
		return default;
	}

	public float IIIIJIIIIIJIIIJIIIJIJJIIJJIJIIJIJIIJJJIJJJJIJJJ(Vector2 JIIIIJIJIIIJIIIIIIJIIIJIIIJIIIJIIJIJJIIIJIJJIJJ)
	{
		return 0f;
	}

	public bool IIJIJIJJJJJIIJIIJJJJJIJJIJIJIJIIIIIIIJIIIJIIIII()
	{
		return false;
	}

	public void JJIIJJJJJIIIIIJJJIIIIIIIJIJJIJIIIIJJIIIJJIIJIJJ(int IJIIJJJIJJJIIJJIJIJIIJJIJIIIJJIJJIJJJIIJIJIJJIJ = -1)
	{
	}
	public bool IJIJJIJIIIJJJJIIJIJIIIIIIIIJIJIIIIJIJIIIIJJIIIJ()
	{
		return false;
	}

	public int JIIJJIIJJJJIJIIJIIIJIIIJIIIIJIJJJJJJIIIJIIJIIJI(float JJIJIIJJIIIIIIJJJJJJJIIIJIJJIJIIJJIIIJIJIJJIIJJ)
	{
		return 0;
	}
	public bool IJIIJIIIJJIJIJIIJJJJIIJIIIIJJJJIJJIIJIIJIJIJJJI()
	{
		return false;
	}

	public bool JIIIJIJJJJIJJIIJIIIIIJIIIIJJJIIJIJJIIIJJJIIJIJI()
	{
		return false;
	}
	public Vector2 JJJJJJIJIJIJIJJJIJIJJJIJJJJIIJJIIIJJJJJIJIIJJIJ()
	{
		return default;
	}

	public Vector2 JJIIIIIIJIJJJIIJIJJJIJJIJJIIJJIIIIIIJIJIJJJIJJJ(float JIJIIIJIJJJJJJJJJIIJJIIJJJIIIIIIJIJJJJJIJIIIJIJ)
	{
		return default;
	}

	public Vector3 IIIJIJJIJJIJJIJJJIIJIIJJJJIIIJIIJJJIJJIJJJJIIIJ(float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
	{
		return default;
	}

	public void IIJIJJIJJIJJJIIJIJIIIIIJIJIIJJIJIIJIIJIIIJJIIIJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, out float IJIJIIIIJJJIIIJJJJIJJJIJIJJJIJIJIIJJIIJIIJJIJJI, out Vector2 IJJIJIJJIIJIIJJJIJIJIJIJIJIIJIIIIIIIJIIJIJJJIJJ)
	{
		IJIJIIIIJJJIIIJJJJIJJJIJIJJJIJIJIIJJIIJIIJJIJJI = default;
		IJJIJIJJIIJIIJJJIJIJIJIJIJIIJIIIIIIIJIIJIJJJIJJ = default;
	}

	public int JIJJIJJIIJIJIIJJJIIJIIIJJIJIIIIJJJIJIJJJIJJJIII(float JJIJIIJJIIIIIIJJJJJJJIIIJIJJIJIIJJIIIJIJIJJIIJJ)
	{
		return 0;
	}

	public bool JJIJIIJJJIIJIJJIJJJIIIIJJJIJIJJJIIJJJJJIIJIIJII()
	{
		return false;
	}

	public void JIJIIJIJJJJIJIIJIIJJIJIJIIIJIIJIIJIJJJIJIJJJJJI()
	{
	}

	public void JJJIIJIJJIJJJJIJIIIIJIIJJIJJIIJIJJJIJIJIJJIIJJI(Texture IIJIJIIIJJJIIIJJIIJJIJIIIIIIJJJIIJIJIJJIIIJIIIJ)
	{
	}

	public float JIIIJIJIIIIIIJJIJJIJJJIIIJIJIIIJIJJJIIJIIIIIIJJ()
	{
		return 0f;
	}

	public Vector3 JJIIIIIIIIJIIIIIIJJJJJJJJJIIIIIIJIJIIIIJIJIJIII(float JJIIIIJIJIJIJJJIIJIJIJIIJIIIIIIIIIJIJJIJJIIIJII, float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ, Camera JJJIJIJJJIIJJIJJJJIJJIIIIJJIIIIJJIJIIIIIJJJJJIJ = null)
	{
		return default;
	}
}
