public static class JIJJJIJIJJJIJIJJJJJJIJIJIIJIIIIJJJJJJJIJJIIJIII
{
	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII JJIIIJJIJIJJIIIJJJJJJIIIJIIJIJJJIIJJJIIJIIJIJIJ)
	{
	}

	public static JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IJIIIIIIIIJJIIJIJJIIIIIJIIJIIIIIJIIJJIIIIJIIIJI(string IIIJJIJJIJJJJIIJJIJIJIJIIIJIIJJIIJJIJIJIIJIIJJJ)
	{
		return null;
	}

	public static bool JIJIIIJJIJIJJJIIIIJIIIJIIJJJIJJIJIJIJIJIIIJJIJI(string IIIJJIJJIJJJJIIJJIJIJIJIIIJIIJJIIJJIJIJIIJIIJJJ)
	{
		return false;
	}

	public static bool JIJIIIJJIJIJJJIIIIJIIIJIIJJJIJJIJIJIJIJIIIJJIJI(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
		return false;
	}
}
