using UnityEngine;

public class JIJJIJIIIIIIJJJIIJJJJJJIJJIJJJIIIIIIJJIJIIJIIIJ : PropertyAttribute
{
	public float IJIJIIIJIIJJIIJJJJIIJIIIIJJJIIIJIIJJIIJJIJJJIJI;

	public float IJIJIIJJIIIJJIIJIIIIIJIIIJJIJJIIJJIJIIJJJJJJIJI;

	public JIJJIJIIIIIIJJJIIJJJJJJIJJIJJJIIIIIIJJIJIIJIIIJ(float IJIJIIIJIIJJIIJJJJIIJIIIIJJJIIIJIIJJIIJJIJJJIJI, float IJIJIIJJIIIJJIIJIIIIIJIIIJJIJJIIJJIJIIJJJJJJIJI)
	{
	}
}
