using UnityEngine;

public sealed class JJIIJJJIIIIIIJIIJJIIJJJIIIIJJIJJJJJJIIIIIIJJIII
{
	public static class IJJIJJJIJIIIJJIIJIJJJIJJIJJIIIJJIJJJJJJIJIJJJII
	{
		public const int IIIJIJIIJJIIJJJIIIIIJJIIIJJIJIIIJIJIIIIIIJJJJJI = -1828716565;

		public const int IJIIIIIJIIJJIIJIJIJJIIIJJIJIIIIIIJJJIIIIJJIJJIJ = -1749041173;

		public const int IJJJJJJIJIJIJIJIJIJJJJIIIIJJJIIIIJJIIJIIIJJIJIJ = 1342177280;

		public const int JJIJIJJIJJIIIJJJIJJJIJJJIJJJJJJJJJIIJIIIJJIJJJI = -738197525;
	}

	public static readonly JJIIJJJIIIIIIJIIJJIIJJJIIIIJJIJJJJJJIIIIIIJJIII JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public const int JIIIJIJJJIIIJJIJJIIIIJJIJJIIJJIIIIJJIIIIIJIIIJJ = 0;

	public const int IIJJJJIJIIJIJJIIJIJIJIJJJJJJJIJJJIIJJJIIJJIIJIJ = 1;

	public const int IIIIJIIJJIJJJIIJJJIIIJJIIJJJJIIJIIJIIIIIIJJJIII = 2;

	public const int JIIJJJIJIJJJIJIIJJJIIJIJJJJIJIJIJJIJIJJIJIIIIJI = 4;

	public const int IIJJIJIIJJJJJIJJJIJIIIJIIJIIIIJJIJIIIJJIIJIIIJI = 24;

	public const int IJIIJIJJJIJJJIJJJJJIIIJJIIJJJIJIIJJIJJJJIJIIIII = 25;

	public const int IIJIJIJJJIIIJIIJIJIJIIJIIIIJJIIJJJJIIJJIIIIJIII = 26;

	public const int IJIIJJJJIJIJJJJIJJIIIIJIJJJJIIIIJIIJJJJIJIIIJIJ = 27;

	public const int IJJJJIIJIIIIJJJIJIJJIIIJJIIJIIIIJIJJIIJIJIIIJJJ = 28;

	public const int JJIJIJIJJJIJJJIJIIIIIJJIJIIJIJIJJIJJIJJIJJIJIIJ = 29;

	public const int JJIJIJJJJJJJJIIJIJJIJIIJIIJJJIJIIJIIJJJJJJJIJIJ = 30;

	public const int IJJIJJJIIJJJIIIJIJIJIJJIIIJJJIJIJJIIIIIJIIJIJJJ = 31;

	public static bool JIIJJIIIIJJIJJIIJJJIJIIIJJIIJIJIIJIIIJIJJJIJJJI(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, int JIJIJIIIJIIIIJIJJJJJJJJJJIJIJIJJIJJJIIJIJIIJIIJ)
	{
		return false;
	}

	public static bool JIJJJJJIJJIIIIIJIJIIJIJIIJJIJJJJIJIIJIJJJJJIIJJ(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, int JIJIJIIIJIIIIJIJJJJJJJJJJIJIJIJJIJJJIIJIJIIJIIJ)
	{
		return false;
	}

	private JJIIJJJIIIIIIJIIJJIIJJJIIIIJJIJJJJJJIIIIIIJJIII()
	{
	}

	public static bool JIJIIIIIJIJIIIIJIJJJJIIIJIIJJJJIIJIJIIIIIIJJJJJ(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, int JIJIJIIIJIIIIJIJJJJJJJJJJIJIJIJJIJJJIIJIJIIJIIJ)
	{
		return false;
	}

	public static bool JJJIJJIIJJIIIJIIIJJJIIJIIJJIJJJJJIIJIIIJIIJIJJJ(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, int JIJIJIIIJIIIIJIJJJJJJJJJJIJIJIJJIJJJIIJIJIIJIIJ)
	{
		return false;
	}

	public static bool IIJJJIJJJJIIJIIIJJJJIJJIIJIJJJJJJIIJIIJJIIIJJII(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, int JIJIJIIIJIIIIJIJJJJJJJJJJIJIJIJJIJJJIIJIJIIJIIJ)
	{
		return false;
	}

	public static bool JIJJJJIIIJJIJIIIJJJJIJJIIIIJIJIJIJIJJIIIJJJJIJI(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, int JIJIJIIIJIIIIJIJJJJJJJJJJIJIJIJJIJJJIIJIJIIJIIJ)
	{
		return false;
	}

	public static bool IIIJJIIIJJIJJJIJJJIIIJJIIJJIJIJJIJIIIJJJIIIJIIJ(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, int JIJIJIIIJIIIIJIJJJJJJJJJJIJIJIJJIJJJIIJIJIIJIIJ)
	{
		return false;
	}

	public static void JJIJJJIIIIIIJJJIJJJIJIIJIJJIJJIIIIJJJJIJJJIJJII(GameObject JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, bool JIJJJJIJIIJJJIIIJIJJJIJIJJJJIIJIJJIIIIJJIIIJJIJ = false)
	{
	}

	public static bool IJJIIIIJIJJIIIJJJIJIIIJJJJJJIIIJJJJJIJIJIJJJIIJ(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, int JIJIJIIIJIIIIJIJJJJJJJJJJIJIJIJJIJJJIIJIJIIJIIJ)
	{
		return false;
	}

	static JJIIJJJIIIIIIJIIJJIIJJJIIIIJJIJJJJJJIIIIIIJJIII()
	{
	}

	public static bool IJJIJJJIIIIIJIJJJJJJJIIIIJIJIJIIJIIIJJIIJJIIIII(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, int JIJIJIIIJIIIIJIJJJJJJJJJJIJIJIJJIJJJIIJIJIIJIIJ)
	{
		return false;
	}

	public static void JIJIIIIJJIIIJIIJJIIIIJJIIJJIIIJJIJJIJJIIIIJJIII(GameObject JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, bool JIJJJJIJIIJJJIIIJIJJJIJIJJJJIIJIJJIIIIJJIIIJJIJ = false)
	{
	}

	public static void JJJJIIIIIJIIJJIJJJJJJIIJIJJJJJIJJIIJIJIIJIIIJII(GameObject JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, bool JIJJJJIJIIJJJIIIJIJJJIJIJJJJIIJIJJIIIIJJIIIJJIJ = false)
	{
	}

	public static bool IIIIIIIIIJJIIIIIJJIIIIJIJIIJJJIJIIJJJJJJJIIJJII(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, int JIJIJIIIJIIIIJIJJJJJJJJJJIJIJIJJIJJJIIJIJIIJIIJ)
	{
		return false;
	}

	public static bool IIJJJJJIIJJIJJJIJIJJIJIIIJJJJJIIJJIIIIJJJJIJJII(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, int JIJIJIIIJIIIIJIJJJJJJJJJJIJIJIJJIJJJIIJIJIIJIIJ)
	{
		return false;
	}

	public static void IJIJJIIJIJJJIIIJJJIIJIIJJJJJJIJJIIIIIIIJJJIJJJJ(GameObject JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, bool JIJJJJIJIIJJJIIIJIJJJIJIJJJJIIJIJJIIIIJJIIIJJIJ = false)
	{
	}

	public static bool IIJIJJJJIIIJJJJJIJIIJIJJJIJJJIJIJIJJIIJJIJJIIJJ(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, int JIJIJIIIJIIIIJIJJJJJJJJJJIJIJIJJIJJJIIJIJIIJIIJ)
	{
		return false;
	}

	public static void JIIIIJIJIJJJIJIIJJIIJIJJIJJJIIJIIJJJIIIIJIJJJII(GameObject JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, bool JIJJJJIJIIJJJIIIJIJJJIJIJJJJIIJIJJIIIIJJIIIJJIJ = false)
	{
	}

	public static void JJIJJJIJIJIIIIIIIJJJJIJJJIIIJJIIIIIJJJJJJJIJIJI(GameObject JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, bool JIJJJJIJIIJJJIIIJIJJJIJIJJJJIIJIJJIIIIJJIIIJJIJ = false)
	{
	}

	public static void IJIIIJJJJJIIIJIIJIIIJIIJIJIJJIIIIIIJIJIIJJJIIJI(GameObject JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ, bool JIJJJJIJIIJJJIIIJIJJJIJIJJJJIIJIJJIIIIJJIIIJJIJ = false)
	{
	}
}
