using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

[Serializable]
public class JJIIJIIIJJIIIJJJIJJIIJIJJIIJJJJJJJIJIIIIIIIJJJI
{
	[HideInInspector]
	public int IJJJIJIIIJIIJJJJJIJIJJIJIIJIJJJJIJIJIIIIJIIJIIJ;

	[HideInInspector]
	public int IIIIIJJIIJJJIJJJIIJIJJIJJIIIIIIIIIIJIIJJJIIJJIJ;

	[HideInInspector]
	public int JJJJIIJJIIJJIJJJJJIJJJIIJJJIIIJIJIIJIJJJIIIJJJI;

	[HideInInspector]
	public int IIIIIIJJJJJIIIJIIIJIJJJIJJJIJIIIJIIJIJJJJJIJJJJ;

	[HideInInspector]
	public string IIJIJIIJJJJIJIIJIJJIIJIJIJIIJJIIIIIIIIJIIIJJIII;

	[SerializeField]
	[HideInInspector]
	private List<JJJIJJIJJJJIJJJJIIIIJIJIIJIIIJIJJJIIJJJIIJIIIIJ> mSaved;

	private Dictionary<int, JJJIJJIJJJJIJJJJIIIIJIJIIJIIIJIJJJIIJJJIIJIIIIJ> JJIIIJIIIIJJJJJJJJIJJJIIIIIJIJJIIIJIIJIIJJIJJJI;

	public bool IIIJIJJJIIJIJIJJJJJJJJJIJJIJIJIJIIIIIIJJJJJJIII => IIIIIIJJIJIIIJIIJIIIIJJIJJJJIJIJIIIIIIIIJJJIJJI();

	public int IIIIJJIIJIIIJIJJJIIJIIJIIIJIJIIJIIIIJIJIIJIIJII
	{
		get
		{
			return IJJJIJJIIIIIJJJJIJJIIJJIJJJJIJJJIJIIJIIIJIJJJJJ();
		}
		set
		{
			IIIJJIJIIIIJJIJIIJIJIIJIIJIIJIIIIJIJIJIIJIIIIJJ(value);
		}
	}

	public int JIJIIIJIIJJJJIJIIJIIIJJJIIIIJJIJIJIIIIIJJIIJIII
	{
		get
		{
			return JJJIIJIJJJJJIIJJJIJJIJJJJIIJJIIJJJIJIJIJIIIJIIJ();
		}
		set
		{
			JIJJJJJIJIIIIJJIJJIIIJJJJIJIIJJJIJJIJIIIIIIIIJI(value);
		}
	}

	public int JIJIIIJJJJJIIJJJIIJIJJIIJIJJJIJJIJIIIIJIJIIIIII
	{
		get
		{
			return IIIJIJIIIIIJIJJIJIIJIJJIIJJIJIJJJIIIJIJJIIJIIII();
		}
		set
		{
			JIIJIIIIJIIJJJJIJJJJIIJJJIJJIIIJJIIJIJJJIIIJIII(value);
		}
	}

	public int IIJIIJIJIIIJIJJIJJJJJJJIJJIIIJJIIIJJIIJJJJIJJJJ
	{
		get
		{
			return IIIIIJIJIIIJJJJJIJJJJJJJIIJIJIJJJIJIIJJJIIIIJJJ();
		}
		set
		{
			IIIIIIIIJIJJIIIIJJJIIJJJJJIIJIIIJJIJIJJJJJIIJJI(value);
		}
	}

	public int JIJJJJJJIJJIJJIIJJJJJIIJIJJIJIIIIIIJJIIIJJIJJIJ => JIIJIIJIJJIIIIIIJIJIJIIJIIIIIIIJIJIJJJJIIJJJJJJ();

	public string JIJJIIIIIIIJIIJIJJIJIJJIIJJIIIIIJIJJIJJJIIIJIJJ
	{
		get
		{
			return IJIIIJJIJJJIJJJIJJJJJIJJJIIJJIIIIIJJIJJIIJIJIJJ();
		}
		set
		{
			IJIIIIIJIIJIJJJIJIJJIJIJJIJJIIIJJIJJJJJIIIIJJIJ(value);
		}
	}

	public List<JJJIJJIJJJJIJJJJIIIIJIJIIJIIIJIJJJIIJJJIIJIIIIJ> IIIIJJJJJIJJJIJJIIJIIIJIJIJJIIIIIJIIJJIIJJIIIIJ => IJIIIJIIIIJIIIIIJJIJJJJIJJJIJJJIIJJJIJJIJIJJIJJ();

	public void IIIJJIJIIIIJJIJIIJIJIIJIIJIIJIIIIJIJIJIIJIIIIJJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public int JJJIIJIJJJJJIIJJJIJJIJJJJIIJJIIJJJIJIJIJIIIJIIJ()
	{
		return 0;
	}

	public void JIIJIIIIJIIJJJJIJJJJIIJJJIJJIIIJJIIJIJJJIIIJIII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIIIIIIJIJJIIIIJJJIIJJJJJIIJIIIJJIJIJJJJJIIJJI(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public JJJIJJIJJJJIJJJJIIIIJIJIIJIIIJIJJJIIJJJIIJIIIIJ IIIIJIIIJJJJJIIIJIIJIIIJIIJJJJJJJJJIIIIIJJJJIII(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}
	public int IJJJIJIJIIIIIJJIIJIJJIIJIJJJIIIIJJIJJJJIIJJIIIJ()
	{
		return 0;
	}
	public int JIIJIJJIIIIJJJIJIJJIJIIIJIJJJIJIIJJIIIJIJJIJIJJ()
	{
		return 0;
	}

	public JJJIJJIJJJJIJJJJIIIIJIJIIJIIIJIJJJIIJJJIIJIIIIJ IIJJIIJIJIIIIIJJJIIJIJJJJIJJIIJJIJIJIIJIIJJJIIJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, bool IJIIIJIJIIJIJJIJIJJIIIIJJIJIJJIIIJJJJIIIIIJJJII)
	{
		return null;
	}

	public JJJIJJIJJJJIJJJJIIIIJIJIIJIIIJIJJJIIJJJIIJIIIIJ IIJJIIJIJIIIIIJJJIIJIJJJJIJJIIJJIJIJIIJIIJJJIIJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}

	public List<JJJIJJIJJJJIJJJJIIIIJIJIIJIIIJIJJJIIJJJIIJIIIIJ> IJIIIJIIIIJIIIIIJJIJJJJIJJJIJJJIIJJJIJJIJIJJIJJ()
	{
		return null;
	}

	public string IJIIIJJIJJJIJJJIJJJJJIJJJIIJJIIIIIJJIJJIIJIJIJJ()
	{
		return null;
	}

	public void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}
	public string IJIJJJIIJIJIJIIJJIJIJIIJJIIJJIJIJJIIIJIIIIJJIJI()
	{
		return null;
	}

	public bool IIIIIIJJIJIIIJIIJIIIIJJIJJJJIJIJIIIIIIIIJJJIJJI()
	{
		return false;
	}

	public int IIIIIJIJIIIJJJJJIJJJJJJJIIJIJIJJJIJIIJJJIIIIJJJ()
	{
		return 0;
	}

	public int IJJJIJJIIIIIJJJJIJJIIJJIJJJJIJJJIJIIJIIIJIJJJJJ()
	{
		return 0;
	}
	public void IJJJIIJJIIIIIJJIIJJIJIJIIIJJJJIJIJIJIIIIJIIJJII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void JIJIJIJIIJIJJIIJIIJIJJIJIIJIJIIJJJJJIIIIJIIJIJJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public int IIIIIIJJIIIIIIIJIIJIIIJIJJJJJIJJJJJJIJIJIJIJJII()
	{
		return 0;
	}
	public int IIIIJIIJIIIIJIJJIIIJJJJJIJIJIIIIJJJIJJJJJJJIIJJ()
	{
		return 0;
	}

	public void JIJJJJJIJIIIIJJIJJIIIJJJJIJIIJJJIJJIJIIIIIIIIJI(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJIIIIIJIIJIJJJIJIJJIJIJJIJJIIIJJIJJJJJIIIIJJIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIJJJJJJIIIIJJIJJJJIIJIIIIIJIJIIJJJJIJJJJIJIII(int JJIIJJIIJIIIIIJIJJJJJIIJIIJJIJJJJIIIJIIJJJIIIJJ, int JIJJJIJJJIIIIJIIIIJIIIIJJIJJJJJIIIIIJIJJIIJJJII, int JIJJIJJIIJIIJJJIIIIIJJIIIIIJJIIJIJIIIJIIJIJJIIJ, int JIJJJIJJIIIJJJIJIIJIJIJJJIIJJIJIJIJIIJIIIIIIJJJ)
	{
	}
	public int JJIIIJJJJIJIIIIJIIIJIJIJIIIIJIIIJIIJJJIJJJIJIII()
	{
		return 0;
	}

	public int JIIJIIJIJJIIIIIIJIJIJIIJIIIIIIIJIJIJJJJIIJJJJJJ()
	{
		return 0;
	}

	public int IIIJIJIIIIIJIJJIJIIJIJJIIJJIJIJJJIIIJIJJIIJIIII()
	{
		return 0;
	}
	public int JJIIIJIJIJJIIIIJIIJIIJJIJJIJJIIIIIIIJJIJIJIIJII()
	{
		return 0;
	}
	public int IIJJIIJJIIIIIIJIIIJJIJIJIIIIIJIIJJJIJIJJJJJIJJI()
	{
		return 0;
	}
	public bool IIIIIJJIIIIJJIIJIIJJIJJJIJJJIJIIJIJIJIJJIJJJIJI()
	{
		return false;
	}
}
