using System;

public class JJIIIIJIJIJJJJJIIJJIJIJIJIIIIIIJIJIJIJIJJIIJJJJ
{
	public const byte JIJJJIJIIJJJIJIJIJIIJIJIJJJIIIIIJIIJJJJIJJIJJJJ = 237;

	public const byte JIJJIIJJJIIIIIIIJIJIIJIJJIIJIJIJIIJIJIJIJIJIJJI = 236;

	public const byte JJIJIJJJJJJIJJJJIJJIIJJIJJJJJJIIIJIJIJIJJJIIIJJ = 235;

	public const byte IJIIIJIIIIJJJJIIIJJIIJJIIJIIIJJIJIIIJIJIJJJJIJI = 234;

	[Obsolete]
	public const byte IJJIJIJIIJIJJIJIIIJIJJJJJJJIJIJJIIJJIJIJIJIIJJI = 233;

	public const byte IIIIJIIJJIIJJJJJIIJIJJJJJIJJIIIIJIJIJIJJIJJIIJJ = 233;

	public const byte IJJIIJJJIJIIIJJJIIJIJIJIJIIJIJIJJJJJIIJJIJIIIIJ = 232;

	public const byte IIJIJJJIJJIIJIIJJIIJIJIJJJJJJJJJIJIIJJJIIJIJJJJ = 231;

	public const byte IIIIIJIIJJIIJIJIIIJIIJIJIIJJJIIJIJJIJIIIIJJIIIJ = 230;

	public const byte JJJJJIJIIJJIJIIIIJIIIJJJJJJJJJIIIIIJIIIJJJIJIJJ = 229;

	public const byte IIJJJJIIJIIIIIJJJIJJIJIJIJIIIIIIJIJJJIJIIJJIJIJ = 228;

	public const byte JJIJJIIJIJJIJJIJJJJIJIJJJJIJJIJJIIJIIJJJIIJIIIJ = 227;

	public const byte JIJJJIIIIJIJIIJJJIJJJIJIIIJIIJIJIIIJIIIJJIJJJII = 225;

	public const byte JJIIIJJJIIIIJIIJJJJJIJIJJIJIIJJJJJJJIJJJIIJIJJI = 224;

	public const byte IIJIJJJIIJIJIJIIJJIJJIIIIJJJIJJIJJIIJIJJJJIIIII = 223;

	public const byte JJJIIIJIIIJIIIIIIIIIIJIJIJIIIJJJJJIJIJIJIJIIJIJ = 223;

	public const byte IIIIJIJIJIIIJIJJJJJIJJJJJIIJJIIIJIIIJJJJIIJJIII = 222;

	public const byte IJJJJJJIJJIJJIIJIIIIJJIJIJJIIJIJIJIJIIJJJJJIJJI = 221;

	public const byte IIJJIJJIJJIJJIJIIJIIIJIJJIJIJIIIIJJIIIIIJIIIJJI = 220;

	[Obsolete]
	public const byte JIIIJJJIIJIJIIIJIIIIIJIJIIIIIJJJJIIJJIIJIIIIIII = 210;

	[Obsolete]
	public const byte JIIIIIJJJIIIIJJIJJIIIIIJIIIIJJJJJIJIIIJIJIIIIJJ = 209;

	[Obsolete]
	public const byte IIIJJIIIJJIJJJJIIJIIJIJIJJJIIIJIJIJIJJJIJJIJJJI = 208;

	public const byte JIIIJIIIJJJIJIIJJJIIIIJJIJJIIIIIJIJJJJIJJJJJIJJ = byte.MaxValue;

	public const byte IJIIIIJJJJIIJIIIJJIJIIJIIIJJIIIJJIIJJIIIJIIIJJJ = 250;

	public const byte IJIJIIIJJIIIIJJJIJJJIIJJIIIJIJIIJJIJJIIJIJIJJJI = 252;

	public const byte JJIIJIIJIJIJIJIJIIIJJJJIJIJJJIIIIIIJJJJIJJJIIII = 254;

	public const byte IIIIJIIJIJJJIIJIIIIJJIIJIJJIJJIIIIJIIJJJIJJIIJJ = 249;

	public const byte IJJIIIJJIJJIJJIIJIIIJJJIIJIIIIIJJJJJJJIIIIJIJIJ = 245;

	public const byte JJJJJIIJJIIJJJIIIIJIIJJJIJJJJIJIIJIIJIIIIIIIJJJ = 245;

	public const byte JJJIIIIJJIIJIIIJJIJJJIJJJIJJJJIIIJIJIJJIIJIJIIJ = 244;

	public const byte IJIIIJJJIIIIJJJIJJJJJIIJJIJJJIJJJIIIIIIJIJIIJII = 248;

	public const byte JJJIJJJIJJJJJIJIIIIJIJIIIIJIIJIJJJJIIJIIJJIIIJJ = 251;

	public const byte JJIIIJIIJIIIJJJIJIIJJIIIJIJIIJJIIJIIIIJIIIJIIJI = 253;

	public const byte JJIJIJJIIIJJIJJJJIIIJIIIIIIJIJJIJJJIIJJJIIJJIII = 246;

	public const byte IIIJIIIJIIJIIIJIIJJJIIIJJJJJJIJIIIJJIIIJIJJJJJI = 247;

	public const byte JIIJJJJIJIIJIIIJIIIJIIIIIJIIJIIJJIIIJJIJJIJJJIJ = 241;

	public const byte IJJJJJIJIJIIJJJJJIIIIIIIIJIJIIIIIJJIIJJIIJJJJJI = 240;

	public const byte JIJIIIJJIJIJJJIIIIJIIIJIIJJJIJJIJIJIJIJIIIJJIJI = 239;

	public const byte IJJIJIIJJJJIIIJJJIJJIJIIIIIIIIJIJJIJJIIIJJJIIII = 239;

	public const byte JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ = 238;

	public const byte JIJJIIIJIJJJJJIIIIJIIIIIIJJJJJIJJJJJIJJJIJJJIJI = 218;

	public const byte IIJIIJJJJJJIIJIIIIJJJJJJIJJIJJJJJIJIIIIIJIJIJJJ = 217;

	public const byte IIJIJJJJIJJJIIIJJJJJJJJIJIIJJJJJIIIJIIIIJJIJIIJ = 216;

	public const byte JJJJIJIIJJIJIJJJIJJJJJJIJJJJJIIJJIJJJIJIIJJJJIJ = 215;

	public const byte JJJJJJJJIIJJIJJJIJIIIJIJIIIJJIJIJIIIIJJIJIIJJII = 214;

	public const byte IJIJJJIJJIJJJJIIIIIJIIIIIIJJJIIIJJJIIJJJJJJIIIJ = 203;

	public const byte IIIJIIJJJIJJJJIJJJJIIIJIIJIIJIIIJJIIJJIIJJIJIJJ = 1;

	public const byte IJIJJJJIJIIIIIJJJJJIIJIJJIIJJIIIIJIIIJIIJIJJIJI = 1;

	public const byte JJIJIJIJJIJJJIIIIIJIIJIIIJIJIJJIJJJIJIIJIIJJIIJ = 2;

	public const byte JIJJJIIIJIJJJJJJIJJJIIIIJIJJJIIIJJJJJJIIJIJJIJJ = 213;

	public const byte JIJJJIIIIJJIJIJJJIIJJIJJJJJIIJJJIJJJJJJIJIIIIII = 212;

	public const byte IJJIJJIJIIJJJJIJIIJJJJJIIIIJJIIIJJIIIJIIJJJIIJI = 211;

	public const byte JIIIIJJJJIJJJIJJJJIJJJIIJIIJJIJJJJIJJJIJJIIJIII = 210;

	public const byte IIJIJIJJIJJIIJJJIIJJIIJJJIJJJIJIJIJJJIJIJJJIIJI = 209;

	public const byte JIIIJIJIIJIJJIJIIJIJIJIIJJIJIIJIIIIJJJJIJJJJJJJ = 208;

	public const byte IJJJIJJJJIIJJJJIIIJIJJJIJJIJIIIIIJIIJIJJJIIIIIJ = 207;

	public const byte JJIJJJIJJIJJIJJIJJIIIJIJIJIJIJJJIJIJJIIIIIIIIJI = 206;

	public const byte JIIIJIIIJJIIJIIIJJJJIIJIIJJJIIIJIJIIIIJJIIJJIIJ = 205;

	public const byte IJJIIIIIJJJJJJIIIJJJIIIIJIIJIJIIJJIJIJIIIIIIJJJ = 204;

	public const byte JJJJJIJIJIIIJIJJIJIJJIIIJIJJIJJIJJJJJJJIJIIJJII = 202;

	public const byte JJJJJIJIJJIIIJIIJJIJIIIIIJJJJIJJIIJIIIIJIIIJIII = 201;

	public const byte JIIIIIIJIIJIIJIJJJJIJIIIIIJIJIJJJJJJJIJIJIIJIJJ = 200;

	public const byte JJIIJIIJIIIJIIJJJIIIJJJJIJJIIJJIJIIIJJJJJJIJJIJ = 195;

	public const byte IIJIJJJJJJJIIIIIIJJJJJJIJIIIIJJJIJJIJIIJIIJJIII = 194;

	public const byte JIJJJJIJIJJJJJIIJJJJIIJJIIJIIIJJJJJJIIIJIJIIIJJ = 193;

	public const byte IJIJJJJIJJJJJIJIJIIIJJJIJJJIIIJIJIIIIIJJJIIIIII = 192;

	public const byte IJIJIIJIJJJJIJJJJJJIJIJJJIJIIIIJJJJIIJJJIIIIJIJ = 191;
}
