public interface JJIIIJIJIIJIIJJIIIJJJJIJJJIIIJIJJJIIIIIJIJJIIJJ
{
	void IJIJIJIIIIJIIIJIIIJIIJJIIJJJJJJJIIJJJIIJIIIJJJI();

	void JJIJJJIJIJIIJIJJIIJIIIIJJJIIJIJIIIIJJIIIIIIIJII();

	void JIJJIIIIJJJJJIJIJIJIIIJIIJIIIJIJIJIJIIIIJJIJIII();

	void JJJJIJJJJIIJIIIJJIJIIJJIIIIJIJIJIIJJJIJJIJJIIJI();

	void IIIJIIJIJIIJIJJIIJJJJJJJIIJIIJJIIIIIJJJJJJJIIJJ();
}
