using System;

public static class JJIIJIJIIIJJJJIIIIJJJJJIJJIIIIIIIIJIJIJJJIIIJII
{
	private static bool JIIIIJIJJJIIJJJJIIIJIIJIIJJIJIJJJJJIIIIJJJJIJII;

	private static UISprite JIJJJIJIIIJJIIJIIIIIJIJIIIJIIJIIIJIJJIJJJIIJIJI;

	private static Action<bool> JJIJIIIJIJJIIJIJIJIIIIIJIIIJIJIIJJJJJIJIIIJJJJJ__BackingField;

	public static bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI
	{
		get
		{
			return JIJIJIIIJIJJIJIJIJJJJIJJIIJIIIIJIIIIJIIIIJJIIJI();
		}
		set
		{
			IIIIJIJJJIJJJJJJIIIIIIIIIJIJJIIIIIJIJIIJIJJIIJJ(value);
		}
	}

	public static event Action<bool> JJIJIIIJIJJIIJIJIJIIIIIJIIIJIJIIJJJJJIJIIIJJJJJ
	{
		add
		{
			JIIIIJJJIJIJIIIJIJIIJIJIJIIIIJJIJIIIIIJIIIJJIJJ(value);
		}
		remove
		{
			IJIJJIJIIIJIJJIJJJJIIJJIJIIJJJJJIJJJIJJIJIJJJII(value);
		}
	}

	public static void JIIIIJJJIJIJIIIJIJIIJIJIJIIIIJJIJIIIIIJIIIJJIJJ(Action<bool> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void IJIJJIJIIIJIJJIJJJJIIJJIJIIJJJJJIJJJIJJIJIJJJII(Action<bool> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static bool JIJIJIIIJIJJIJIJIJJJJIJJIIJIIIIJIIIIJIIIIJJIIJI()
	{
		return false;
	}

	public static void IIIIJIJJJIJJJJJJIIIIIIIIIJIJJIIIIIJIJIIJIJJIIJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
}
