using System;
using System.Collections.Generic;
using System.Diagnostics;
using ExitGames.Client.Photon;
using UnityEngine;

public static class JJIJJJIIIIJJJIJIJIJIIJIJJJIIIIIJJIIJJIIIIJIJIIJ
{
	public delegate void IJJJIJJJIJJIJIJJIJJJJIJIJIIIIJJIIJIJIJIIIJJJJIJ();

	public delegate void IJIIJIIJJIIJIJJIJJJIIJIIJJJJIIIIIIJJIJJIJIIIIII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII);

	public delegate void JIIJJIJIIJIJJJJIIJIIJIIJJJJJIIJJIJIJJJIIIJIJIII(object[] JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ);

	public delegate void JIJJIIJIJJJIJIJIJJJJJIIJJJJJIIJJJJIJJJIJIJIIIIJ(short IJIJJIIJIIIJJIIIJJIJIIJJJJJIJJIIJJIIJIIJJJIJJJI, string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ);

	public delegate void JJJJJJIJJIJIIIJJIJJIIJIJIIIIJIJIJIJIJJJJJJJJIIJ(Hashtable JJJJIJJJIJJJIIJJIJIIJIJIJIIJIIJJJJJJIIIJIIJJJJI);

	public delegate void IIJJIJIJIJIIJIIIIJJIJJJIIIIJJJIIJJJJIIIIJJJIJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI);

	public delegate void JIIJJJJIJJIIIJIJJIJIJJIIJIJIIIIIIIJJIIJIJJIIJJI(JIJJIJIIJIJJIIIJJIIJIJIIJIJIJIJJIIJIJJIJJIJIIJI IIJIIIIIIJJIIJJJJJIJIIJIJJJJJJIIJIJJJIJJIIIIIJI);

	public delegate void IIIJJJIIIJIIIIIJIIIIJIIJJIJJIIIJIIJJIJIJJJJJJJI(byte JIJJJJIIJJIJIJJIJIIIIJJIJIJJIIJJIIIIJIJJIJIJJJJ, object IIJJIJIJJJJJIIIIIJJIJIJIJJIIIJIJJJIJJIIJIIJIIJI, int JJJIJJIJJIJJJJJIIIIIIIIJIIJJIJIIIIJIJIJJIIIIIJJ);

	public static string JJIJJJIIIJJIJJJJJIIIJIIJIJJIJJIIJJIIIIIIJJJJIIJ;

	private static string JJJIIIIIIJJJJIIIIJIJJIIJJIJIIJIIIIJIIJIIIIIIIJI;

	internal static readonly PhotonHandler JIJIJIIIIJJIJIIJIIJIIIIIJJJJIIIJJIJJIIIJIJJJIJI;

	internal static JJJJJIJJJIIJIIIJIJIIIJIIIIJIIIJJJJJIIJIJIJIIJII JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI;

	public static readonly int IJIIJJIIJIJIJIIJIJIJIIIIJIIJJIIIJJIJJJIIIIJIIII;

	internal const string JIJIJJIJIIIJIIIIJJJIJJIIJIJIJJIJJJJJJIIIIIIJJIJ = "PhotonServerSettings";

	public static ServerSettings IJJJJIIIJIIJIJIIIJIJJJJIIIIJIIIIJIIJIJJIIJJIJIJ;

	public static IJJJIJJJIJJIJIJJIJJJJIJIJIIIIJJIIJIJIJIIIJJJJIJ IJIJJJIJIJJIIIIIIIJJIJJJJIJJIJJJIJJIIIIJIJJIJIJ;

	public static IJJJIJJJIJJIJIJJIJJJJIJIJIIIIJJIIJIJIJIIIJJJJIJ JJJJIJJIJJJIJIIJIJIIJIIIIJIJJIJJJJJJJIIIJJIIJII;

	public static IJIIJIIJJIIJIJJIJJJIIJIIJJJJIIIIIIJJIJJIJIIIIII IIIJJJIIJIIIIIJIJJIJJIJIIJIIJIIIJIIJIJIIIJIJIIJ;

	public static JIJJIIJIJJJIJIJIJJJJJIIJJJJJIIJJJJIJJJIJIJIIIIJ IIJJIJIJIIJJIJIJIIIIJJIJJIJIIIJIJIIJIJIJIIIJJJJ;

	public static JIJJIIJIJJJIJIJIJJJJJIIJJJJJIIJJJJIJJJIJIJIIIIJ JIJIIIIJJIJIJJJJJJJIJJIJJIIJJJJIJIJIIJIIJIJJJII;

	public static IJJJIJJJIJJIJIJJIJJJJIJIJIIIIJJIIJIJIJIIIJJJJIJ JJIIIJJIIIIJIIIJJIJJJIIJJIJIIIJJIIIIJIJIIJIIIIJ;

	public static IJJJIJJJIJJIJIJJIJJJJIJIJIIIIJJIIJIJIJIIIJJJJIJ JJIIIJIJJIIJIIIJJJJJIIIJIJIJJIIJIJIIJIJIJJJJJJJ;

	public static IJJJIJJJIJJIJIJJIJJJJIJIJIIIIJJIIJIJIJIIIJJJJIJ IIJJIJIIIIJIJJJJJJJJJIJJIJJJIIIIJIJJJIIIJJJIIII;

	public static JIIJJJJIJJIIIJIJJIJIJJIIJIJIIIIIIIJJIIJIJJIIJJI JIJIIJIIJIIIIIJIJJJIJJIIJIJIIIJIIJIJIIJJJJIIJIJ;

	public static IJJJIJJJIJJIJIJJIJJJJIJIJIIIIJJIIJIJIJIIIJJJJIJ JIJJJJIJJIIJIIJJJJJIIIJIJJIJIJIIJJIIIJIJIJJIJJJ;

	public static JIIJJJJIJJIIIJIJJIJIJJIIJIJIIIIIIIJJIIJIJJIIJJI IJJIIJIJJJIJIIIJIIJIIIIJIJJIIJIIIIIJIIIJIIJJJII;

	public static JIIJJIJIIJIJJJJIIJIIJIIJJJJJIIJJIJIJJJIIIJIJIII JIIJIIIJIJJJJIIIIIIIIIIIIJJIIIJIIIIJIIIIJJIIJJI;

	public static IJJJIJJJIJJIJIJJIJJJJIJIJIIIIJJIIJIJIJIIIJJJJIJ IIJIIJIIJIJIJJIJJIIIIIJIIJIJIIIIIJIIIJIJIIIJIJJ;

	public static IJJJIJJJIJJIJIJJIJJJJIJIJIIIIJJIIJIJIJIIIJJJJIJ IJIIJIJIJJJIIIJJIJIJJIJJJIJJJJIIIIIIJJJJJJIJIII;

	public static IJIIJIIJJIIJIJJIJJJIIJIIJJJJIIIIIIJJIJJIJIIIIII JJJIJIIIJIJJJIIIIJIIJJIJIIJIIJJIJIIIJIJIIJIJJIJ;

	public static IJIIJIIJJIIJIJJIJJJIIJIIJJJJIIIIIIJJIJJIJIIIIII IIJIIIIIIJIIJJJIIJIIJJIJIJJIJIIIJJJJIIIIJIJIIIJ;

	public static JIJJIIJIJJJIJIJIJJJJJIIJJJJJIIJJJJIJJJIJIJIIIIJ IIJJIIJJJJIJIIJJJJIJIIIJJIJJIJIIJJJJJIJIIJIJJJJ;

	public static IJJJIJJJIJJIJIJJIJJJJIJIJIIIIJJIIJIJIJIIIJJJJIJ JJJIIJJJJIIJIJJIJIIJJJJJJIJIJJIIIJIIIIIJJIJJJIJ;

	public static IJJJIJJJIJJIJIJJIJJJJIJIJIIIIJJIIJIJIJIIIJJJJIJ JIIIIJIJJIIJJIJJIJIJIJJJIJIJJIJIIIJJJIJJJJIIIII;

	public static JJJJJJIJJIJIIIJJIJJIIJIJIIIIJIJIJIJIJJJJJJJJIIJ IIIIJJIJIIJIJIIIIJIIIIJIJIIIJJJIIJJIJIJIJJIIJJJ;

	public static JIIJJIJIIJIJJJJIIJIIJIIJJJJJIIJJIJIJJJIIIJIJIII IJJIIIIIJIIIIJJIJIIIJJIJJIIIJIJJJIIIJJJJJJJIIII;

	public static IJJJIJJJIJJIJIJJIJJJJIJIJIIIIJJIIJIJIJIIIJJJJIJ JIJJIJIIIIIJIIJJJIIJJJJJJIIIIJJIJIJIIJJIIJJIJII;

	public static IIJJIJIJIJIIJIIIIJJIJJJIIIIJJJIIJJJJIIIIJJJIJJJ JJIJIIIJJIIJJJIJIJIIJJJJJIJJIJJJIIJJIJJIJIJIJIJ;

	public static JIIJJIJIIJIJJJJIIJIIJIIJJJJJIIJJIJIJJJIIIJIJIII IJJIIJJJJIIIIJIIJJJJIIIJJJJJJIJIIJIIIIIIJJJJJII;

	public static JIIJJIJIIJIJJJJIIJIIJIIJJJJJIIJJIJIJJJIIIJIJIII IJIJIJIJJIIIJJIIIJIJIJJJIIIJIJJJIJJJJJJJJIJJJIJ;

	public static JIIJJIJIIJIJJJJIIJIIJIIJJJJJIIJJIJIJJJIIIJIJIII IJIJJJJIJJJIIJIJIJIIIIJIIIIIIIIJIJJJJIIIJJIIIIJ;

	public static JIIJJIJIIJIJJJJIIJIIJIIJJJJJIIJJIJIJJJIIIJIJIII IJIJJIJIIJIIIIJIIJJIJJIJIIJJIIJJIIIJJJJJJIIJJIJ;

	public static IJJJIJJJIJJIJIJJIJJJJIJIJIIIIJJIIJIJIJIIIJJJJIJ JIIIIJJJIIIIJJJIJIIJIJIIJJJJIJJIIIIJIJIIIJJJIJJ;

	public static bool IJIJIIJJJIJJIIIJIIJIIIJIIJIIJIJJIIIIJIIIIIIJIJJ;

	public static IJIJIJIJJIJJJIJIJIIIIIIJJJIJJJIJIJIJIJJIJJJIJIJ JIJIJJIJIIJIJJJJJIIJIJIIIIJIIIJJJJJJJJIIJJIJIII;

	private static List<JIJIJIIIIIJJIJJJIIIJIIJJIJIIIIJIJIJJJIJJJIJJJIJ> IIJIJJJIIIIJIIJJIIJJIJIJIIJIJIIIJIIIIIIJJIIIJJI;

	public static float JJJIIJIJIIIJJJIIIIIJJJJIIJIJIIJIJJIJJJJJJIJIJIJ;

	public static float IJIIIJIJIIIJIIIIIJJIIIJJJIIIIIJJJIIIJIJJIJJJJJI;

	public static float JJIIJJIIIIJJJIIJIIJJIIIIIJJJJIIIIIIJIJJIIIIJJIJ;

	public static bool IJIJJJJIJJJJIIIIIJIJJIIJJIIJJJJJJJJJJIJIJIJIJII;

	public static bool JIJIJJIJJIJJJIIIJJJJIIJIIJIIIJIJIJJIJIIIJIIJIIJ;

	public static Dictionary<string, GameObject> IJIJIIIIIJIIIJIIJJJJIIJIIIIJJIIIIJJJJJIIIJIJIJI;

	public static HashSet<GameObject> IJJJIJJIJIJJJIJIJJIJIIJJJJIJIIJJJJIIJIIJIJIIIJJ;

	public static Type JJJIJIIJIIJIJIJJIJJIIIJJIIIIIJIJJIIIIJJJJIIIJIJ;

	public static bool JIJJJJIIIIIIIJIIJIJIJJIIJJJJJJIJIJJJJIIJJJIJIIJ;

	private static bool JJJJJJJIIIJIJIIIJIJIJJJJIJJJIJJIJIJIIIIIIJJJJII;

	private static IIJIIJIIJIJJIIJIJJJJJJJIIIJJJIIIIIIJJIIIJJJIJII IJJJJIIJIJIIJJJJJJJIJJJJIIJJIIJIJJJJIIJJJJIIJJI;

	[Obsolete]
	public static int JJJIJIIIJJIJJIIJIIIIJIIJIJJJJIJIJJJJIIIJJJIJJIJ;

	private static bool IIJJJIJIJIJIIJIJIIIJIIIIIIJJJIIIIIJIJJIIIJIJJJI;

	private static bool JJJIJIIJJJJIJJIJJJIIJIJIJIJIIIJIJJIIIJIJJJJJJII;

	private static int JJJJJIJJJJJIIJJIIIIJIJJIIIJJJJJJJIJJJIIIIIJJJJI;

	private static int JJJIJIIIJJIIJIJJIIIIJJIIIJIIJIIJIJJJIJJJJJIJIJI;

	private static bool JJJJJJJJIIIJJJJIIJJJIIIJJIIIIIJIIJIIJIIJJJIIIII;

	private static Stopwatch JJIIJJIIIJIJJJIJIJIIIIJIIJIIIJJIIJIIJIJJJJJIJIJ;

	public static float IJIJIJIJIJIJIIIJJJIJIIIJIIJIJIIJIIIIJIJIJIIJJJJ;

	private static bool JIJJIIJIIJJJJIJIJIIJJIJIJIIIIIIJIIJJIIJIJIIJIII;

	private static IIIJJJIIIJIIIIIJIIIIJIIJJIJJIIIJIIJJIJIJJJJJJJI JIJJIJJJJIJJIJIIIIIIJIIIJIJIJIIIIIIJJJJJIIIIIJJ__BackingField;

	internal static int IJJJJJIIJIIIIIIJIJIJJIJIJIJJIIIIJIJIIIJIJJIJIII;

	internal static int JIIIJJIIJIIJIIJJJJIJIJJJIIIJIJJIJIIJJJIJJIJJJJJ;

	internal static List<int> IIJIJIIIJJJJJIJJIJJJJJJJJIJIIIIJJIJJJJJJJJJIIII;

	public static bool JIJIIJJIIJIJJJIJIIIJJJJIIJJIJJIJIIIIJIJIJJJIJJI;

	public static string IJIJIJIJJJIJIIJJJJJIIIIIJIIJIIJJIJJJJJJJIJIIJJI
	{
		get
		{
			return JIIJIJIJIIJJIJIIJJJJJJIJJIIIJJJIIJJJJJIIIIJJJJJ();
		}
		set
		{
			IJJIIJIIIJIIJIIIJIJIIIJJIIJJIJJIJIIJJJIJIJJIIIJ(value);
		}
	}

	public static string JIJJJJIIJIIJIJIJIJJIJJJIIIJIIIIIJJIJJJJJIIJIJIJ => JJJJIIIIIJIIJJJJIIJIJIJJJIIJJJJJJIJIJJIIJJIIIJI();

	public static IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII IJIIJIJIIJIJIJIJIIIIIIIJJJJIIIIIJIIIJJJJIJIJJIJ => JJIIIJJJIJIJJJJJJIJIJIIIIIJIJIJJIIJJJJJIIIJJJJJ();

	public static bool JJJIJIIIIIIIJIIJIJJIIIJIIIIIJIJIJJJIIJIIJIJIIII => IIIJIIJJIIJIIIIJIIJIIJJJIJJJIIJIIJIIJJIJIIIJIII();

	public static bool IIJIIJJIJIIIIJJJIJJIJIIIJJIJJIIIIIJJIIIJJJIJIJI => JIIIIIIJIJIJIIJIIIIIJIIIJJJIJIIJIJJIIIJIIIJIJIJ();

	public static bool IIIIIIIIJJJJIJJJIJIJIIJIJJJJJIJJJIJIIIJJIJJIJII => JIJJJJIJJIJJIIJIJIIIIIIIJIIIJIJJJJIIJJIJIIIIIII();

	public static IJJJJJIIIIIIIIJJJIIJJIJIJIJJIIIJJJIJJIJJIJIIIJI JJIIJIIIJIJJIJJIIJJIJJIJIJIIJIJIJIJIIJIIJIIIJJI => JJJJJJJJIJJIJIJIIIJIIIIIJJIJJIIJIIJJIJIIJIJJIJJ();

	public static JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ JJJJJJIIIJIJIIJIIIIJIIIIJIIJJJIIIJIJJIIIIJJJJIJ => JIIJIIJIIJJIIJIIJJJIJJIIJIIJJJJJJJJJJIIJJIIIJII();

	public static IIIJIIJJJIJIJIIJIIJJJJJIIIIJJIIJIIJIJIIIJJIJJJJ JJIIJJJJIIIJJJJIJIIJIJIJIJIJIJIIJJIJIIIIJIJJJIJ => JIIJIJJJIIIJIIIIJJIJIIIJIJIIIJJIIIJJJIJIIJJJIJI();

	public static IIIJJIJJIJIIJJJJIIIJJJIIIIJIIJJJIIJJJIJJJJIIJIJ IJIJIIJIJJJJIJJIIIJJIIIJIJJJJJJIIJIJIJIIIJIIJII
	{
		get
		{
			return IJJIJIJJJJJIJJIJJJJIJIIJIJJJIIJJJIIJIJIJJIJIIJJ();
		}
		set
		{
			IIIIIIJIJIJJJIIJIJIJJIIJIIJIIIIJJJJIIIIJIJJJIJI(value);
		}
	}

	public static IIJIIJIIJIJJIIJIJJJJJJJIIIJJJIIIIIIJJIIIJJJIJII JJJJIJIIIJJIJIIJJJIJIIIIJIJJIIIJIJIJJIIIJIJJIJJ => IJJIIJIJJJIJJJIIIJJIJIIIJIJIIJIJIJJJIJJJJJJIIJJ();

	public static JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII => JJIIIIIJJIIJIJJIIJIIIIJJJJJIIJJJJIIJIIJJJIJJJII();

	public static JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJJJIJJJJJIJJJJIJJJJIJJJIJIJJJJJIIJJJJJIJJJJII => IIIIIJIIIJIJJJIIJJJIJJJIJIIIIIIJIIIIIIIIJJIIJJJ();

	public static string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI
	{
		get
		{
			return JJIJIIJJJJJIJJIJJJJIJIJJIIIJJJJJIJIJJIIIJIIIIIJ();
		}
		set
		{
			JJIJJIJJJJJJIJIJIJJJIIIIJJJJIIJIIIJJIJJIJJIJJII(value);
		}
	}

	public static JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII[] IIIIJJJIIIIJJIIJJIJIIJIIJIJIJJJJJIIJIIIJJJJJIJJ => IIJJIIIJJJJJJIJJIIIIJIJIJIJJJIIIIIIIIJJIJJIJJJI();

	public static JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII[] IIIIJJIJIIJIIIIIIJIIJIIIJJIIJJIJIIIJJJIIIIIJIJJ => JIJJIJJIJIJIIJIJIJIJJJJJIJJIJIJIJIJIIJJIIJIIIJI();

	public static List<JIJIJIIIIIJJIJJJIIIJIIJJIJIIIIJIJIJJJIJJJIJJJIJ> IIIJIJJIIIIIJIJIIIIIIIIJIIJIIJJJJJJJIJJJIJJIIIJ
	{
		get
		{
			return IIJJJJJJIIJIJIIIIJIJJIJIJIJJJIJIIJJIJJJIIJIJJJI();
		}
		internal set
		{
			IJJJIJJJJIJJIIIJIIIJIIJJJJIJIIIJJJIJIJJIJIIIIII(value);
		}
	}

	public static int JIIIIIIIIJIIJIIIJJIIIIJJIJJJIJIJJJJIIJIIJJIIIII => IJIIJJIJIJIJJJJIIJIJJJIJIJJIJIIJJIJIIJIJIJJIIIJ();

	public static JIIJIJJJIJJIJJJIJIIIIJIIJJIIIJIIIJJJJIIIIJJJIII JIJJIIJJJIIJJJJJIJJJIIJJIJJIIJJJIJJJIJJJJJJIIII
	{
		get
		{
			return JIIIIJJJIIJJJJJIIIIIJJJIJIIJJJJIIJJJIIJJIJJIJJI();
		}
		set
		{
			JJIIJJJJJIJJJIIJIJJJIIIIIJJJIIJIJIIIJJJJJIJJIJJ(value);
		}
	}

	public static bool JJIJIJIJIIJIIIJJJJIJIJJJIIJJJJIJIIJJJJJJIJJIIJI
	{
		get
		{
			return JJJJJJIJIJJIJIIJJJJJIIJJJIJIIJJJJJJJIJJIJJIIJIJ();
		}
		set
		{
			IIJIIIJIIIJIJIJJIJJIJIIIIJIJJIIJJIIIJIIJIJIIIJJ(value);
		}
	}

	public static bool IJJJIIIJIIIIJIJJIJJJJIIIJJJIJJJJIJIIJIIJIIIIIJJ
	{
		get
		{
			return JJJJIIJIIJIIIIIJJJIJJJJIIJJIJJIIIIJIIJIIJJJJIIJ();
		}
		set
		{
			JIIIIIIIIJIJIJJJJJIJIJIJJIJIJIJJJJIJIJJIJJJIJII(value);
		}
	}

	public static bool JIIIIJJIIJIJIIIIJIIIJJIJIIJJIJJJIIIJJJJIJIIIJIJ
	{
		get
		{
			return IIJIIIIJIIJIIJJIJIJJIJJIIJJIJJJJIJIJJIJIIJIIIJJ();
		}
		set
		{
			IJJIIIIJJJIIJIIJJIIIIJJJJIJJIIJJIJJJIJJJIJIJIIJ(value);
		}
	}

	public static bool IIJIIJJIJIIJJJJJIJJIIJIIJIJIJJJJJIIIJJJIJIIJJJJ
	{
		get
		{
			return JJJIJIIIIIJJJJJJIJIJIIJJIIIJIIJIIJIIIJJIJJIJJII();
		}
		set
		{
			IIIJJIJIJJIIIJIJIJIJIIJIIJIJIJIIJIIIJIIJIIJJJJI(value);
		}
	}

	public static bool JIJJIJJIIJIJIIIJJIIIIIIIJIJJIIIIJJJIIIIIIIIJIII
	{
		get
		{
			return JIJIJIJIIIJJIJJIIJJIIIIIIJIJJJIJIIJJJJJJIIIJIII();
		}
		set
		{
			IIJIIJJJIJIJIJJIIJIJJIIIIJIIJIIIIIJIJIJIIJJJIJJ(value);
		}
	}

	public static List<JJJIJIJIJJJJIIJJIJIJJJJIJJJJJJJIJJIJJIIJIIJIJJI> JJIJIJIIIIIJIIIIJIIJIIIJJIJJJIJJJJIIJJJJJIIJJII
	{
		get
		{
			return IJJIIIIIIJJJIJIIJJIIIIIJIIJJIJJJIIJJJJIJIIIJIII();
		}
		private set
		{
			IJIJIJIJJJIJIIIJIIIJIIJJJIIIJIJJIIIJIIJJJJJJJIJ(value);
		}
	}

	public static bool IIIIJJJIIJIIIJIIIIJIJIJIJIIIJJIJJJIIJJIJIJIIIJJ => IJJIJIIIIJJIIIJIIJJIIIJJJJIIIIJIIIJJIJIJIJJIJII();

	public static IJIJIIJIJJJJIJJIIJIJJIJJIJIJJIJJJJIIJJJJIJJJJJJ IJIIJJIJJIIIIIIJJJIJJJJJJIIJIIIIIJJIJJJJIIJJIII
	{
		get
		{
			return IIIIIJIJJIIIIJIJJIIIJIIJIJIIJJJIJIIIJJIJIIJIJII();
		}
		set
		{
			IIIJJIIIJIJJJJJJJJJJJJJIIIJJJIJJJIIJJIJJIIIIJJI(value);
		}
	}

	public static int IIJJIJJIIJJIIIIJJJIJJIJJIIJIJIIJIIIJJIJJJIIJJII
	{
		get
		{
			return JIIJJJJIJIIIJIIJJIJJJIJJIIJJJIJJIJIIIIIJIJIJIJJ();
		}
		set
		{
			IIJIIJJJIJJJJIIJIJIIJIIJJIJIJIJJJIJIIJIJIIJJIIJ(value);
		}
	}

	public static int JJIJJIJJIJIJJJJIJIIJJIJJJIIIJJIIIIIIJJIJJJIJIJI
	{
		get
		{
			return IJJIJIJIJJIJIIIJIIIIIIIIJIJJIIIIIIIIJIJIJIIIJII();
		}
		set
		{
			IJJJJIJIIJJIIJIIIIJJIIIIIJIIIJIJIIJJJIIIJJIJIJJ(value);
		}
	}

	public static bool IIJJIIIIIJJIJIIJIIIIIJIJJJIIJIIJIJIIJIJJIJIIJJI
	{
		get
		{
			return JIJJJJIIIIJIJIJIJJJIIIJJIJJIJIJIJIIIIIJIJIJJIIJ();
		}
		set
		{
			IJJJIJIJJJIIJIIJIIJIIIJIIIIIJIIJIIJJJIJIJIJIJII(value);
		}
	}

	public static int JIIJIJIIJIJJIJJJJIIIIIJJIIJIIIJJJJIIJIIIIJIJJII
	{
		get
		{
			return IIJJJJIJIIIJJIJIJJJJIJIJJJIJIJIJIJJIJIJJIIJJIII();
		}
		set
		{
			IJJIIIIJJIJIIIJIIIIJIIIIIJIIJIJIIJJJIIIIIIIJIIJ(value);
		}
	}

	public static double JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI => IJIIJIJJJJIJIJJJJJJIJJIIJJJJIIIJIJJIJJJIJIJIJII();

	public static int JIJJJJJJIJIJJJIIJJJJIIJIIIIIJJJJJIJIIJJIJJJJJIJ => IIIJIJJIJJIJJJIJJIJIJIJJJJJIJJIIJIJJJJIIIJIJJJI();

	public static bool JIIIJIIJIIJJJJJJIJIJJJJIJIJJIJJIIIIIJIJJIJJIJII => JIJIJJJIJIIIIJJIIJJIJIJIJJIJIIJJIIIIIJJJIJJIJIJ();

	public static bool JIIJIJJJJIIJIJIIIIIIJIJIJIIJJIJIJIJJJJJIJJJJJIJ => JJIIJJJJJIJJJIJIJJJIJJIJIJIJJJJIJIJJIIJIIJJIIJJ();

	public static bool IIJJIIJJIJIIIJIJJIIJIJJJIJJJJIIJIJJIJIIIIJIJIII => IJIJIIJJJIIJIIJIIJJJIIJJIJIIIJIJIJJJIIJIJJJJIIJ();

	public static int IJIIJIIJIIJIIIIJJJIIIIIJJJJIJJIIJIIJIIJJIJIIIIJ => JIIJIJIIJIJJJJJIIJJIIIIJIJIIJJIIIJJIJJIJIIIIIJI();

	public static int JIIIJJIJIIJIIIIIJIJIIJJJJIJJJIJIIIIJIIIJJJJJJII => IIJIIJIIIJIJJIIIIIIIJJIIJIIIIIJJIJJJJJIJIJJJIII();

	public static int JJJJIJIJIIJIIJIIIIIIJIJJIIJIIIJIJIJIIJIIJJJJJJJ => JIJIJJIJJJJJIIIIJIIIJIIJIIJJJIJJJIIJIJJIIIJIIJJ();

	public static int JIJIIIIJIJIIIIIIIIJIJJJIIIIJIJIJIJIIIIIJJJJJJJI => IJJJIIIIJIIJJIJIJJJJJJJIJJJIIJIIIJIJIJIIJIJIJJJ();

	public static bool JJIJIIJJJJJJIJIJJIIIIJIJIJIJIIIJJJJIIJJIJIIIIJJ
	{
		get
		{
			return JIJIJJIJJIIJJIJIJJJJJIIIIJJIJIIJIIJIIIIIJIIJIJI();
		}
		set
		{
			JIIIIIIJIIJIIJJIJJIJIIIIIIJIIIJJJIJIIJJIJIJIIJI(value);
		}
	}

	public static int JIJIJIIIIJJIJIJIIJIIJIJIJJJIJIJJIIIIIIIIJIJJJJJ => IJJIIIIIIJJJIIIIJJJIIIJIIJIIIIIIJIJJJIIJJIIIJJJ();

	public static bool JIIIIJIJIIJIIJJJIJIJIJJIJJIIIIIIIJJIJIIJJIJIIJI
	{
		get
		{
			return JIJIJJIJIIJJJJJJJJJJJIIIIIJIIJJJIIJIJIIJIIIJIIJ();
		}
		set
		{
			JIJJIIIJJJJJJIJIJIJJJJIJJIJIJJJJJIIIJJJIJJIJJII(value);
		}
	}

	public static int IJIIIIIIIJJJJJIIJJJIJIJJIIIJIJJIJIJJJJJJJIIIJJI => IJIIJIJIIIIIIJIIJJIIJJJIIIJJIJIJIIIJIIJJIJIJJIJ();

	public static int JJJIJIJJIJIJJIJIJIIIJJIIIIIJIIJIJIIIJJIIIIJIIJJ
	{
		get
		{
			return JIIIJJIIJIJIIIJIIJIIIJIJIJJJJJJIIIIIJIJIIIJJJJJ();
		}
		set
		{
			JIJIJIJJIJIIJIIJJJJIIIJJIIJJJJJIIIJIIIJIJJJIIIJ(value);
		}
	}

	public static int IIIJJIJIIJIJJJJJJJIJIIJIJIJJJIIIIIIJJJIIIIJJJJJ
	{
		get
		{
			return JIIIJIIIIJIJIIIJJIIIIIIJJJJIIIJJIIIJJJIJJJIIIJJ();
		}
		set
		{
			IIIJJIJIIIIIIJJJIJJIJIIJIJIIIIIIIIIIIJIIIJJIIJI(value);
		}
	}

	public static bool IJJIIIIIJJIJIJIJJIJIIJIIJIJIJJIJJIJIIJIIIIIIJJJ
	{
		get
		{
			return IIJIJIIIIJIIIIJIJIIIJJIJIJIJJIIIIIJJJIJJIIIJJII();
		}
		set
		{
			IJJIIJJIIIJJJJIJJIIJIIIIJIIIJIIIJJJJJJIIIIJIIIJ(value);
		}
	}

	public static event IIIJJJIIIJIIIIIJIIIIJIIJJIJJIIIJIIJJIJIJJJJJJJI JIJJIJJJJIJJIJIIIIIIJIIIJIJIJIIIIIIJJJJJIIIIIJJ
	{
		add
		{
			JIJJIIIIIIJIIIJIJJIIJJIJIJJJJJJIIIIJIIIIJIIJIII(value);
		}
		remove
		{
			IIJIJIJIJIJIIIJJIJIJJJJIIJJIJIJIJJJIJJIIIIIJJJI(value);
		}
	}

	public static string JIIJIJIJIIJJIJIIJJJJJJIJJIIIJJJIIJJJJJIIIIJJJJJ()
	{
		return null;
	}

	public static void IJJIIJIIIJIIJIIIJIJIIIJJIIJJIJJIJIIJJJIJIJJIIIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static string JJJJIIIIIJIIJJJJIIJIJIJJJIIJJJJJJIJIJJIIJJIIIJI()
	{
		return null;
	}

	public static IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII JJIIIJJJIJIJJJJJJIJIJIIIIIJIJIJJIIJJJJJIIIJJJJJ()
	{
		return IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII.eu;
	}

	public static bool IIIJIIJJIIJIIIIJIIJIIJJJIJJJIIJIIJIIJJIJIIIJIII()
	{
	        // RVA 0x0049af18 (verified against libil2cpp.so disassembly)
	        if (JJJJJJJIIIJIJIIIJIJIJJJJIJJJIJJIJIJIIIIIIJJJJII)
	        {
	            return true;
	        }
	        if (JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI == null)
	        {
	            return false;
	        }
	        if (JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI.IJJJJJIIIIIIIIIIIIIIIJIJIIJIJIJJIIIJJJJJJJJIJII)
	        {
	            return false;
	        }
	        JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ state = JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI.IJJJIIIIJIIJIJIIIIIIJJJJIJIJJJIIIIIIJIJJIIIIIII;
	        return state != JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.PeerCreated && state != JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.Disconnected && state != JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.Disconnecting;
	}

	public static bool JIIIIIIJIJIJIIJIIIIIJIIIJJJIJIIJIJJIIIJIIIJIJIJ()
	{
		return false;
	}

	public static bool JIJJJJIJJIJJIIJIJIIIIIIIJIIIJIJJJJIIJJIJIIIIIII()
	{
	        // RVA 0x0049b47c (verified against libil2cpp.so disassembly)
	        if (!IIIJIIJJIIJIIIIJIIJIIJJJIJJJIIJIIJIIJJIJIIIJIII())
	        {
	            return false;
	        }
	        if (JJJJJJJIIIJIJIIIJIJIJJJJIJJJIJJIJIJIIIIIIJJJJII)
	        {
	            return true;
	        }
	        switch (JIIJIIJIIJJIIJIIJJJIJJIIJIIJJJJJJJJJJIIJJIIIJII())
	        {
	        case JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.PeerCreated:
	        case JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.ConnectingToGameserver:
	        case JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.Joining:
	        case JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.ConnectingToMasterserver:
	        case JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.Disconnecting:
	        case JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.Disconnected:
	        case JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.ConnectingToNameServer:
	        case JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.Authenticating:
	            return false;
	        default:
	            return true;
	        }
	}

	public static IJJJJJIIIIIIIIJJJIIJJIJIJIJJIIIJJJIJJIJJIJIIIJI JJJJJJJJIJJIJIJIIIJIIIIIJJIJJIIJIIJJIJIIJIJJIJJ()
	{
		return IJJJJJIIIIIIIIJJJIIJJIJIJIJJIIIJJJIJJIJJIJIIIJI.Disconnected;
	}

	public static JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ JIIJIIJIIJJIIJIIJJJIJJIIJIIJJJJJJJJJJIIJJIIIJII()
	{
	        // RVA 0x0049b61c (verified against libil2cpp.so disassembly)
	        if (JJJJJJJIIIJIJIIIJIJIJJJJIJJJIJJIJIJIIIIIIJJJJII)
	        {
	            return (IJJJJIIJIJIIJJJJJJJIJJJJIIJJIIJIJJJJIIJJJJIIJJI != null) ? JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.Joined : JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.ConnectedToMaster;
	        }
	        if (JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI == null)
	        {
	            return JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.Disconnected;
	        }
	        return JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI.IJJJIIIIJIIJIJIIIIIIJJJJIJIJJJIIIIIIJIJJIIIIIII;
	}

	public static IIIJIIJJJIJIJIIJIIJJJJJIIIIJJIIJIIJIJIIIJJIJJJJ JIIJIJJJIIIJIIIIJJIJIIIJIJIIIJJIIIJJJIJIIJJJIJI()
	{
		return IIIJIIJJJIJIJIIJIIJJJJJIIIIJJIIJIIJIJIIIJJIJJJJ.MasterServer;
	}

	public static IIIJJIJJIJIIJJJJIIIJJJIIIIJIIJJJIIJJJIJJJJIIJIJ IJJIJIJJJJJIJJIJJJJIJIIJIJJJIIJJJIIJIJIJJIJIIJJ()
	{
		return null;
	}

	public static void IIIIIIJIJIJJJIIJIJIJJIIJIIJIIIIJJJJIIIIJIJJJIJI(IIIJJIJJIJIIJJJJIIIJJJIIIIJIIJJJIIJJJIJJJJIIJIJ JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static IIJIIJIIJIJJIIJIJJJJJJJIIIJJJIIIIIIJJIIIJJJIJII IJJIIJIJJJIJJJIIIJJIJIIIJIJIIJIJIJJJIJJJJJJIIJJ()
	{
		return null;
	}

	public static JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJIIIIIJJIIJIJJIIJIIIIJJJJJIIJJJJIIJIIJJJIJJJII()
	{
		return null;
	}

	public static JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIIIIJIIIJIJJJIIJJJIJJJIJIIIIIIJIIIIIIIIJJIIJJJ()
	{
		return null;
	}

	public static string JJIJIIJJJJJIJJIJJJJIJIJJIIIJJJJJIJIJJIIIJIIIIIJ()
	{
		return null;
	}

	public static void JJIJJIJJJJJJIJIJIJJJIIIIJJJJIIJIIIJJIJJIJJIJJII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII[] IIJJIIIJJJJJJIJJIIIIJIJIJIJJJIIIIIIIIJJIJJIJJJI()
	{
		return null;
	}

	public static JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII[] JIJJIJJIJIJIIJIJIJIJJJJJIJJIJIJIJIJIIJJIIJIIIJI()
	{
		return null;
	}

	public static List<JIJIJIIIIIJJIJJJIIIJIIJJIJIIIIJIJIJJJIJJJIJJJIJ> IIJJJJJJIIJIJIIIIJIJJIJIJIJJJIJIIJJIJJJIIJIJJJI()
	{
		return null;
	}

	internal static void IJJJIJJJJIJJIIIJIIIJIIJJJJIJIIIJJJIJIJJIJIIIIII(List<JIJIJIIIIIJJIJJJIIIJIIJJIJIIIIJIJIJJJIJJJIJJJIJ> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static int IJIIJJIJIJIJJJJIIJIJJJIJIJJIJIIJJIJIIJIJIJJIIIJ()
	{
		return 0;
	}

	public static JIIJIJJJIJJIJJJIJIIIIJIIJJIIIJIIIJJJJIIIIJJJIII JIIIIJJJIIJJJJJIIIIIJJJIJIIJJJJIIJJJIIJJIJJIJJI()
	{
		return null;
	}

	public static void JJIIJJJJJIJJJIIJIJJJIIIIIJJJIIJIJIIIJJJJJIJJIJJ(JIIJIJJJIJJIJJJIJIIIIJIIJJIIIJIIIJJJJIIIIJJJIII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static bool JJJJJJIJIJJIJIIJJJJJIIJJJIJIIJJJJJJJIJJIJJIIJIJ()
	{
	        // RVA 0x0049c544 (verified against libil2cpp.so disassembly)
	        return JJJJJJJIIIJIJIIIJIJIJJJJIJJJIJJIJIJIIIIIIJJJJII;
	}

	public static void IIJIIIJIIIJIJIJJIJJIJIIIIJIJJIIJJIIIJIIJIJIIIJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	        // RVA 0x0049c5d0 (verified against libil2cpp.so disassembly)
	        if (JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI == JJJJJJJIIIJIJIIIJIJIJJJJIJJJIJJIJIJIIIIIIJJJJII)
	        {
	            return;
	        }
	        if (JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI && IIIJIIJJIIJIIIIJIIJIIJJJIJJJIIJIIJIIJJIJIIIJIII())
	        {
	            UnityEngine.Debug.LogError("Can't start OFFLINE mode while connected!");
	            return;
	        }
	        if (JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI.PeerState != PeerStateValue.Disconnected)
	        {
	            JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI.Disconnect();
	        }
	        JJJJJJJIIIJIJIIIJIJIJJJJIJJJIJJIJIJIIIIIIJJJJII = JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI;
	        if (JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	        {
	            JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI.JIJIJJJJJIIIIIIIIIIIIJJJJIIIJJJIIJJJJJJJJIJIJIJ(-1);
	            JJJJJIJJJIIJIIIJIJIIIJIIIIJIIIJJJJJIIJIJIJIIJII.IJIJJJIIJIJIIIJIIJJJIIJIJJJJJIIIIIIIIIJIIIIIIJJ(IJJIIIJJJIIJIJIJJIJJIJJJIIIJIJJIJIJJJJJIIJJIIIJ.OnConnectedToMaster, Array.Empty<object>());
	        }
	        else
	        {
	            IJJJJIIJIJIIJJJJJJJIJJJJIIJJIIJIJJJJIIJJJJIIJJI = null;
	            JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI.JIJIJJJJJIIIIIIIIIIIIJJJJIIIJJJIIJJJJJJJJIJIJIJ(-1);
	        }
	}

	public static bool JJJJIIJIIJIIIIIJJJIJJJJIIJJIJJIIIIJIIJIIJJJJIIJ()
	{
		return false;
	}

	public static void JIIIIIIIIJIJIJJJJJIJIJIJJIJIJIJJJJIJIJJIJJJIJII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static bool IIJIIIIJIIJIIJJIJIJJIJJIIJJIJJJJIJIJJIJIIJIIIJJ()
	{
		return false;
	}

	public static void IJJIIIIJJJIIJIIJJIIIIJJJJIJJIIJJIJJJIJJJIJIJIIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static bool JJJIJIIIIIJJJJJJIJIJIIJJIIIJIIJIIJIIIJJIJJIJJII()
	{
		return false;
	}

	public static void IIIJJIJIJJIIIJIJIJIJIIJIIJIJIJIIJIIIJIIJIIJJJJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static bool JIJIJIJIIIJJIJJIIJJIIIIIIJIJJJIJIIJJJJJJIIIJIII()
	{
		return false;
	}

	public static void IIJIIJJJIJIJIJJIIJIJJIIIIJIIJIIIIIJIJIJIIJJJIJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static List<JJJIJIJIJJJJIIJJIJIJJJJIJJJJJJJIJJIJJIIJIIJIJJI> IJJIIIIIIJJJIJIIJJIIIIIJIIJJIJJJIIJJJJIJIIIJIII()
	{
		return null;
	}

	private static void IJIJIJIJJJIJIIIJIIIJIIJJJIIIJIJJIIIJIIJJJJJJJIJ(List<JJJIJIJIJJJJIIJJIJIJJJJIJJJJJJJIJJIJJIIJIIJIJJI> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static bool IJJIJIIIIJJIIIJIIJJIIIJJJJIIIIJIIIJJIJIJIJJIJII()
	{
		return false;
	}

	public static IJIJIIJIJJJJIJJIIJIJJIJJIJIJJIJJJJIIJJJJIJJJJJJ IIIIIJIJJIIIIJIJJIIIJIIJIJIIJJJIJIIIJJIJIIJIJII()
	{
		return null;
	}

	public static void IIIJJIIIJIJJJJJJJJJJJJJIIIJJJIJJJIIJJIJJIIIIJJI(IJIJIIJIJJJJIJJIIJIJJIJJIJIJJIJJJJIIJJJJIJJJJJJ JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static int JIIJJJJIJIIIJIIJJIJJJIJJIIJJJIJJIJIIIIIJIJIJIJJ()
	{
		return 0;
	}

	public static void IIJIIJJJIJJJJIIJIJIIJIIJJIJIJIJJJIJIIJIJIIJJIIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static int IJJIJIJIJJIJIIIJIIIIIIIIJIJJIIIIIIIIJIJIJIIIJII()
	{
		return 0;
	}

	public static void IJJJJIJIIJJIIJIIIIJJIIIIIJIIIJIJIIJJJIIIJJIJIJJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static bool JIJJJJIIIIJIJIJIJJJIIIJJIJJIJIJIJIIIIIJIJIJJIIJ()
	{
		return false;
	}

	public static void IJJJIJIJJJIIJIIJIIJIIIJIIIIIJIIJIIJJJIJIJIJIJII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static int IIJJJJIJIIIJJIJIJJJJIJIJJJIJIJIJIJJIJIJJIIJJIII()
	{
		return 0;
	}

	public static void IJJIIIIJJIJIIIJIIIIJIIIIIJIIJIJIIJJJIIIIIIIJIIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static double IJIIJIJJJJIJIJJJJJJIJJIIJJJJIIIJIJJIJJJIJIJIJII()
	{
		return 0.0;
	}

	public static int IIIJIJJIJJIJJJIJJIJIJIJJJJJIJJIIJIJJJJIIIJIJJJI()
	{
		return 0;
	}

	public static bool JIJIJJJIJIIIIJJIIJJIJIJIJJIJIIJJIIIIIJJJIJJIJIJ()
	{
		return false;
	}

	public static bool JJIIJJJJJIJJJIJIJJJIJJIJIJIJJJJIJIJJIIJIIJJIIJJ()
	{
		return false;
	}

	public static bool IJIJIIJJJIIJIIJIIJJJIIJJIJIIIJIJIJJJIIJIJJJJIIJ()
	{
		return false;
	}

	public static int JIIJIJIIJIJJJJJIIJJIIIIJIJIIJJIIIJJIJJIJIIIIIJI()
	{
		return 0;
	}

	public static int IIJIIJIIIJIJJIIIIIIIJJIIJIIIIIJJIJJJJJIJIJJJIII()
	{
		return 0;
	}

	public static int JIJIJJIJJJJJIIIIJIIIJIIJIIJJJIJJJIIJIJJIIIJIIJJ()
	{
		return 0;
	}

	public static int IJJJIIIIJIIJJIJIJJJJJJJIJJJIIJIIIJIJIJIIJIJIJJJ()
	{
		return 0;
	}

	public static bool JIJIJJIJJIIJJIJIJJJJJIIIIJJIJIIJIIJIIIIIJIIJIJI()
	{
		return false;
	}

	public static void JIIIIIIJIIJIIJJIJJIJIIIIIIJIIIJJJIJIIJJIJIJIIJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static int IJJIIIIIIJJJIIIIJJJIIIJIIJIIIIIIJIJJJIIJJIIIJJJ()
	{
		return 0;
	}

	public static bool JIJIJJIJIIJJJJJJJJJJJIIIIIJIIJJJIIJIJIIJIIIJIIJ()
	{
		return false;
	}

	public static void JIJJIIIJJJJJJIJIJIJJJJIJJIJIJJJJJIIIJJJIJJIJJII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static int IJIIJIJIIIIIIJIIJJIIJJJIIIJJIJIJIIIJIIJJIJIJJIJ()
	{
		return 0;
	}

	public static int JIIIJJIIJIJIIIJIIJIIIJIJIJJJJJJIIIIIJIJIIIJJJJJ()
	{
		return 0;
	}

	public static void JIJIJIJJIJIIJIIJJJJIIIJJIIJJJJJIIIJIIIJIJJJIIIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static int JIIIJIIIIJIJIIIJJIIIIIIJJJJIIIJJIIIJJJIJJJIIIJJ()
	{
		return 0;
	}

	public static void IIIJJIJIIIIIIJJJIJJIJIIJIJIIIIIIIIIIIJIIIJJIIJI(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static bool IIJIJIIIIJIIIIJIJIIIJJIJIJIJJIIIIIJJJIJJIIIJJII()
	{
		return false;
	}

	public static void IJJIIJJIIIJJJJIJJIIJIIIIJIIIJIIIJJJJJJIIIIJIIIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JIJJIIIIIIJIIIJIJJIIJJIJIJJJJJJIIIIJIIIIJIIJIII(IIIJJJIIIJIIIIIJIIIIJIIJJIJJIIIJIIJJIJIJJJJJJJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void IIJIJIJIJIJIIIJJIJIJJJJIIJJIJIJIJJJIJJIIIIIJJJI(IIIJJJIIIJIIIIIJIIIIJIIJJIJJIIIJIIJJIJIJJJJJJJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	static JJIJJJIIIIJJJIJIJIJIIJIJJJIIIIIJJIIJJIIIIJIJIIJ()
	{
	}

	public static void JIIJJIJJIIJJJIJJJIJIJIIIJJIIJJIJIIJJJJIJJIIJJJI(ConnectionProtocol IIIIIJIIIJIJJJJIJJIJIIJIIIIIJJIJIJIJIJIJIIJJJJJ)
	{
	}

	public static bool IJIIIIIJJJIJJIIIJIJIJJJJJJJJIJIIJJJIJIIJIIIJIII(string IJIJIJIJJJIJIIJJJJJIIIIIJIIJIIJJIJJJJJJJIJIIJJI)
	{
		return false;
	}

	public static bool JIJIIJJJJIJJJIIIIIIIIJJIJJIIJJIJJJIJIIJIIIIJIII(string IIIIJIJJIIIJIIJJIIJIJJIIJIIJIIJIIIIIIIJJJJIIIII, int IJIIJIJIJJJJIIIJJJIJIIJIIIJJJIJJJIIIIIJIIJJJIII, string JIIJJJIJIJJIIJJIJJJIIIIJIJIJJJJJJIJJJJJIJJIJIJI, string IJIJIJIJJJIJIIJJJJJIIIIIJIIJIIJJIJJJJJJJIJIIJJI)
	{
		return false;
	}

	public static bool IIJIIIJIIJIJJIIJIIIIJIIIIJIJJJJIIJJIJJIJIJIJIII()
	{
		return false;
	}

	public static bool JJJJIIJJIIIIJJJJIIIIJIJIJJJJJIJJIIJIJJJIIJIJIII()
	{
		return false;
	}

	public static bool JIIIIJJIJJIIIJJJIIJJJIJJJJIIJIIJJIIJJIIIJIIIJIJ(string IJIJIJIJJJIJIIJJJJJIIIIIJIIJIIJJIJJJJJJJIJIIJJI)
	{
		return false;
	}

	public static bool JIIIIJJIJJIIIJJJIIJJJIJJJJIIJIIJJIIJJIIIJIIIJIJ(string IJIJIJIJJJIJIIJJJJJIIIIIJIIJIIJJIJJJJJJJIJIIJJI, string JIIJJJIJIJJIIJJIJJJIIIIJIJIJJJJJJIJJJJJIJJIJIJI)
	{
		return false;
	}

	public static bool JJJJJIIJIIIIIIIJJIIJIJIIIIIJIIIJJJJJJJIJJJIJJJJ(IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII IIJJIJIJIJJIIJJIJJJIIIIIIIJJIIJIJJJJIIIJIJJJJJJ, string IJIJIJIJJJIJIIJJJJJIIIIIJIIJIIJJIJJJJJJJIJIIJJI, string JIIJJJIJIJJIIJJIJJJIIIIJIJIJJJJJJIJJJJJIJJIJIJI)
	{
		return false;
	}

	public static void JIJIIJJJIJJJIIIJJJIJIIIIIIIIIIJIJJIJJJJJJJIJIIJ(IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII IIJJIJIJIJJIIJJIJJJIIIIIIIJJIIJIJJJJIIIJIJJJJJJ)
	{
	}

	public static void IIIIIIIJJJJIIJIJIIIJIJIIJJJIJJIIIJIJIJIIJIJJJJI()
	{
	}

	public static void IJJIJJJJJIJJJIJIIJJJJIJIIIIJJJIJIJIIIIJJJJJIIJI()
	{
	}

	public static string JJIJIJIJIIJIJIJIJIJIJJIIIIJJIJJJIJIJJJJIJIIIJJJ()
	{
		return null;
	}

	[Obsolete]
	public static void JIJJIJIJIJJIJIJJIJJIIIIIIIJIIJIJJIIIIJJJIIJIJJI()
	{
	}

	private static bool JJJJIJJJIJIIIJIIIJJJIIJIIIIJIJIIIJJJJIIJJJIIIII()
	{
		return false;
	}

	public static void IJIJJJJIJIJIIJJIIJJIIJIJJIIJIJIJIJIJJJJJIJJIIJJ()
	{
	}

	public static bool IJJIIJIIIIJIIIIIJJJJJJJJIJJJIJJIIIIJIIIIIJJIJJI(string[] JIIIJJIJIIIJIJIIJJJIIJJIIIIJIJIJIJJJJIJIJJIIJII)
	{
		return false;
	}

	public static bool IIJJJJJJIIJJIIJJJIJIIIJJJJIJJJIIIJIJJJIJIIIIIIJ(string IIIJJJJJIJIIJJIIIJJIIJJIJIJIJJJIJJJIIJJIIJJIJIJ)
	{
	        // RVA 0x004a2078 (verified against libil2cpp.so disassembly)
	        return IIJJJJJJIIJJIIJJJIJIIIJJJJIJJJIIIJIJJJIJIIIIIIJ(IIIJJJJJIJIIJJIIIJJIIJJIJIJIJJJIJJJIIJJIIJJIJIJ, null, null, null);
	}

	public static bool IIJJJJJJIIJJIIJJJIJIIIJJJJIJJJIIIJIJJJIJIIIIIIJ(string IIIJJJJJIJIIJJIIIJJIIJJIJIJIJJJIJJJIIJJIIJJIJIJ, JIIJIIJIIJIJJJJJIIJJJIIJIJJJIIJIIJJJJIIJJJJJJIJ IJJIIIJIJJJJIJIIJIIIJJJIJIJJJJJJIJJJIIJJJIJJIII, IJIJIIJIJJJJIJJIIJIJJIJJIJIJJIJJJJIIJJJJIJJJJJJ JIIIJIIIJJJJIIJJJIJIJJIJJJIJJIJIJIJJIIIIIIJIJJI)
	{
	        // RVA 0x004a258c (verified against libil2cpp.so disassembly)
	        return IIJJJJJJIIJJIIJJJIJIIIJJJJIJJJIIIJIJJJIJIIIIIIJ(IIIJJJJJIJIIJJIIIJJIIJJIJIJIJJJIJJJIIJJIIJJIJIJ, IJJIIIJIJJJJIJIIJIIIJJJIJIJJJJJJIJJJIIJJJIJJIII, JIIIJIIIJJJJIIJJJIJIJJIJJJIJJIJIJIJJIIIIIIJIJJI, null);
	}

	public static bool IIJJJJJJIIJJIIJJJIJIIIJJJJIJJJIIIJIJJJIJIIIIIIJ(string IIIJJJJJIJIIJJIIIJJIIJJIJIJIJJJIJJJIIJJIIJJIJIJ, JIIJIIJIIJIJJJJJIIJJJIIJIJJJIIJIIJJJJIIJJJJJJIJ IJJIIIJIJJJJIJIIJIIIJJJIJIJJJJJJIJJJIIJJJIJJIII, IJIJIIJIJJJJIJJIIJIJJIJJIJIJJIJJJJIIJJJJIJJJJJJ JIIIJIIIJJJJIIJJJIJIJJIJJJIJJIJIJIJJIIIIIIJIJJI, string[] IIJIIIJJIJIJIIIIIIIJIIIJJJJJJIIIIIIJJIIJJIIIIII)
	{
	        // RVA 0x004a210c (verified against libil2cpp.so disassembly)
	        if (JJJJJJJIIIJIJIIIJIJIJJJJIJJJIJJIJIJIIIIIIJJJJII)
	        {
	            if (IJJJJIIJIJIIJJJJJJJIJJJJIIJJIIJIJJJJIIJJJJIIJJI != null)
	            {
	                UnityEngine.Debug.LogError("CreateRoom failed. In offline mode you still have to leave a room to enter another.");
	                return false;
	            }
	            JIIIIJIIJJJJJJIJIJIIJIJIIIJJIIJJIIJIIIJIJIIIIJI(IIIJJJJJIJIIJJIIIJJIIJJIJIJIJJJIJJJIIJJIIJJIJIJ, IJJIIIJIJJJJIJIIJIIIJJJIJIJJJJJJIJJJIIJJJIJJIII, true);
	            return true;
	        }
	        if (JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI.JJIJIJJJIJIIJIJJIIIIIJJIJIIIJJIIJIIIJIJIJJJJJII != IIIJIIJJJIJIJIIJIIJJJJJIIIIJJIIJIIJIJIIIJJIJJJJ.MasterServer || !JIJJJJIJJIJJIIJIJIIIIIIIJIIIJIJJJJIIJJIJIIIIIII())
	        {
	            UnityEngine.Debug.LogError("CreateRoom failed. Client is not on Master Server or not yet ready to call operations. Wait for callback: OnJoinedLobby or OnConnectedToMaster.");
	            return false;
	        }
	        if (JIIIJIIIJJJJIIJJJIJIJJIJJJIJJIJIJIJJIIIIIIJIJJI == null)
	        {
	            JIIIJIIIJJJJIIJJJIJIJJIJJJIJJIJIJIJJIIIIIIJIJJI = JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI.IIIIJJJIIJIIIJIIIIJIJIJIJIIIJJIJJJIIJJIJIJIIIJJ ? JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI.IIIIJIIIJIIJJIIJJJIJJJIJIJIIIIIIJJJIIIJIIJJIJJJ : null;
	        }
	        IJIJJIJIIJIIIJJJIJIIIIJJJJJIIIJIJIIIJIIJJJIIIJI opParams = new IJIJJIJIIJIIIJJJIJIIIIJJJJJIIIJIJIIIJIIJJJIIIJI();
	        opParams.JIIIJIIIJJJIJIIJJJIIIIJJIJJIIIIIJIJJJJIJJJJJIJJ = IIIJJJJJIJIIJJIIIJJIIJJIJIJIJJJIJJJIIJJIIJJIJIJ;
	        opParams.JIIJIIJIIJIJJJJJIIJJJIIJIJJJIIJIIJJJJIIJJJJJJIJ = IJJIIIJIJJJJIJIIJIIIJJJIJIJJJJJJIJJJIIJJJIJJIII;
	        opParams.IJIIJIIIJIIIJIIJIIIIIIIJIIJJIIIIIIIJIJJJIIIJIII = JIIIJIIIJJJJIIJJJIJIJJIJJJIJJIJIJIJJIIIIIIJIJJI;
	        opParams.JIIJIJIJIJIIIJJJJJIIJJIIJJJJJJIJJJJIIJJIIIJIJIJ = IIJIIIJJIJIJIIIIIIIJIIIJJJJJJIIIIIIJJIIJJIIIIII;
	        return JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI.JJJJIJJJJIIJJIJIJJJJIIJIJJIJJJJIIIIIJIIJIJJIJII(opParams);
	}

	public static bool IJIJJJJJJJJJJIJJJJJJIIIIIJIJJJJIIIIJJJIIJIIJIIJ(string IIIJJJJJIJIIJJIIIJJIIJJIJIJIJJJIJJJIIJJIIJJIJIJ)
	{
		return false;
	}

	public static bool IJIJJJJJJJJJJIJJJJJJIIIIIJIJJJJIIIIJJJIIJIIJIIJ(string IIIJJJJJIJIIJJIIIJJIIJJIJIJIJJJIJJJIIJJIIJJIJIJ, string[] IIJIIIJJIJIJIIIIIIIJIIIJJJJJJIIIIIIJJIIJJIIIIII)
	{
		return false;
	}

	public static bool JJJIIJIJJJIJJJJJIJJIJIIJJJIIIIIJIJJIIIIJJIIIJIJ(string IIIJJJJJIJIIJJIIIJJIIJJIJIJIJJJIJJJIIJJIIJJIJIJ, JIIJIIJIIJIJJJJJIIJJJIIJIJJJIIJIIJJJJIIJJJJJJIJ IJJIIIJIJJJJIJIIJIIIJJJIJIJJJJJJIJJJIIJJJIJJIII, IJIJIIJIJJJJIJJIIJIJJIJJIJIJJIJJJJIIJJJJIJJJJJJ JIIIJIIIJJJJIIJJJIJIJJIJJJIJJIJIJIJJIIIIIIJIJJI)
	{
		return false;
	}

	public static bool JJJIIJIJJJIJJJJJIJJIJIIJJJIIIIIJIJJIIIIJJIIIJIJ(string IIIJJJJJIJIIJJIIIJJIIJJIJIJIJJJIJJJIIJJIIJJIJIJ, JIIJIIJIIJIJJJJJIIJJJIIJIJJJIIJIIJJJJIIJJJJJJIJ IJJIIIJIJJJJIJIIJIIIJJJIJIJJJJJJIJJJIIJJJIJJIII, IJIJIIJIJJJJIJJIIJIJJIJJIJIJJIJJJJIIJJJJIJJJJJJ JIIIJIIIJJJJIIJJJIJIJJIJJJIJJIJIJIJJIIIIIIJIJJI, string[] IIJIIIJJIJIJIIIIIIIJIIIJJJJJJIIIIIIJJIIJJIIIIII)
	{
		return false;
	}

	public static bool IJJIIIJJIJIJJIJJIIJIJIJJIIJJIJJIIJJIJJIJIJIJJIJ()
	{
		return false;
	}

	public static bool IJJIIIJJIJIJJIJJIIJIJIJJIIJJIJJIIJJIJJIJIJIJJIJ(Hashtable IJJJJIJJIJIIIJJJJJIIIJIIJJJJJJIIJJIJJIIIJIIJIJI, byte JJIIJJIJIJJJIJJJJIIIJIIIIIIIIJJJJJJJIIIJIJIJIJI)
	{
		return false;
	}

	public static bool IJJIIIJJIJIJJIJJIIJIJIJJIIJJIJJIIJJIJJIJIJIJJIJ(Hashtable IJJJJIJJIJIIIJJJJJIIIJIIJJJJJJIIJJIJJIIIJIIJIJI, byte JJIIJJIJIJJJIJJJJIIIJIIIIIIIIJJJJJJJIIIJIJIJIJI, IJJIIJIJJIIIIJJJIIJJIIJJJIJJJJIJIIJJIJIIJJJJJII IJIIIIIJJJIJIIJJJJJIJJJJJJIJIIIIIJJIJIIJJJIIJII, IJIJIIJIJJJJIJJIIJIJJIJJIJIJJIJJJJIIJJJJIJJJJJJ JIIIJIIIJJJJIIJJJIJIJJIJJJIJJIJIJIJJIIIIIIJIJJI, string IIJIJIIJIIJJJJIJIJJJJIIJIIJJIJIJIIJIJJJJJIJIJJJ, string[] IIJIIIJJIJIJIIIIIIIJIIIJJJJJJIIIIIIJJIIJJIIIIII = null)
	{
		return false;
	}

	public static bool JJIJIJJJIIIIIJIJJJIIIJJJIIIJJJIIIJJJJJIJIIJJIJI(string IIIJJJJJIJIIJJIIIJJIIJJIJIJIJJJIJJJIIJJIIJJIJIJ)
	{
		return false;
	}

	private static void JIIIIJIIJJJJJJIJIJIIJIJIIIJJIIJJIIJIIIJIJIIIIJI(string IIIJJJJJIJIIJJIIIJJIIJJIJIJIJJJIJJJIIJJIIJJIJIJ, JIIJIIJIIJIJJJJJIIJJJIIJIJJJIIJIIJJJJIIJJJJJJIJ IJJIIIJIJJJJIJIIJIIIJJJIJIJJJJJJIJJJIIJJJIJJIII, bool IJJIIJJIJIIIJJIIIIJIIIIIJIJIIIIIJIJJJJIJJJJJJII)
	{
	        // RVA 0x004a2628 (verified against libil2cpp.so disassembly)
	        IJJJJIIJIJIIJJJJJJJIJJJJIIJJIIJIJJJJIIJJJJIIJJI = new IIJIIJIIJIJJIIJIJJJJJJJIIIJJJIIIIIIJJIIIJJJIJII(IIIJJJJJIJIIJJIIIJJIIJJIJIJIJJJIJJJIIJJIIJJIJIJ, IJJIIIJIJJJJIJIIJIIIJJJIJIJJJJJJIJJJIIJJJIJJIII);
	        JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI.JIJIJJJJJIIIIIIIIIIIIJJJJIIIJJJIIJJJJJJJJIJIJIJ(1);
	        JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI.IJJJIIIIJIIJIJIIIIIIJJJJIJIJJJIIIIIIJIJJIIIIIII = JJJIJIIJIJIIIJJIIJIJIIIIJIIIJIJJIIJJJIIJIIJJJJJ.ConnectingToGameserver;
	        JIJJIIIIJIJIIIIIIJIIJIJIJIJJJJIIJIIJJJJIIJJIIJI.OnStatusChanged(StatusCode.Connect);
	        IJJJJIIJIJIIJJJJJJJIJJJJIIJJIIJIJJJJIIJJJJIIJJI.IJIIJIJIIJIJJJJIIIJJIIJJJIIJJIJJIIJJIIJIIJIIIII = 1;
	        if (IJJIIJJIJIIIJJIIIIJIIIIIJIJIIIIIJIJJJJIJJJJJJII)
	        {
	            JJJJJIJJJIIJIIIJIJIIIJIIIIJIIIJJJJJIIJIJIJIIJII.IJIJJJIIJIJIIIJIIJJJIIJIJJJJJIIIIIIIIIJIIIIIIJJ(IJJIIIJJJIIJIJIJJIJJIJJJIIIJIJJIJIJJJJJIIJJIIIJ.OnCreatedRoom, Array.Empty<object>());
	        }
	        JJJJJIJJJIIJIIIJIJIIIJIIIIJIIIJJJJJIIJIJIJIIJII.IJIJJJIIJIJIIIJIIJJJIIJIJJJJJIIIIIIIIIJIIIIIIJJ(IJJIIIJJJIIJIJIJJIJJIJJJIIIJIJJIJIJJJJJIIJJIIIJ.OnJoinedRoom, Array.Empty<object>());
	}

	public static bool JJJJIIJIJIIJJIIIJIJIIIJJJJJJJJIJJIIIJJJJJJIJJIJ()
	{
		return false;
	}

	public static bool JJJJIIJIJIIJJIIIJIJIIIJJJJJJJJIJJIIIJJJJJJIJJIJ(IJIJIIJIJJJJIJJIIJIJJIJJIJIJJIJJJJIIJJJJIJJJJJJ JIIIJIIIJJJJIIJJJIJIJJIJJJIJJIJIJIJJIIIIIIJIJJI)
	{
		return false;
	}

	public static bool JIJIIIJIIJIJIIJJJJJIJJIJJIIJIJJIIJIIJIIJIIJIJJI()
	{
		return false;
	}

	public static bool IJJJIIJIJIIJJIIIIIJJJJJIIJIJIIIIJJJIJIIIIJIJIIJ(bool IIJIIIIIIJJIJIJIIIJJIIIJJIJIIJJJIIIJIIIJJJIJIJI = true)
	{
		return false;
	}

	public static bool IJIIIJIJJJIIIJJJIJJJIJIJIIJIJJIJJIIIIJIJIIIIIIJ(IJIJIIJIJJJJIJJIIJIJJIJJIJIJJIJJJJIIJJJJIJJJJJJ JIIIJIIIJJJJIIJJJIJIJJIJJJIJJIJIJIJJIIIIIIJIJJI, string IIJIJIIJIIJJJJIJIJJJJIIJIIJJIJIJIIJIJJJJJIJIJJJ)
	{
		return false;
	}

	public static JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ[] JJJIJJJJIIIIJJJIJIJJIIJJJJJJJJJIIIJIJJIJJIJJJIJ()
	{
		return null;
	}

	public static void IJJIJIJJIJIJJIIIIJIIIIJJJJJIJJJJIJJIIIIIIJJJJJJ(Hashtable JJIIJJIJIJIIIJIJIIIIIJIJIJIIJJJIJJIIIJIIJJJJIII)
	{
	}

	public static void IIJIJJJIJIJJIJJIIJIIIIIIJJJJIIIIJJJIJIIJIIIIIIJ(string[] IIIJJJJIJIIJJJJJJJJJJIIJIJIJIJIJIJJIIIIJIJIJJJJ)
	{
	}

	public static bool IIIJJJIJJJIJJIJIIIIJIJIIJJJJIIJIIJJIJIIJIJJIJJI(byte JIJJJJIIJJIJIJJIJIIIIJJIJIJJIIJJIIIIJIJJIJIJJJJ, object JJIJIJJIIIJJJIIJIIIJIIIIIIIIIIIJIJJJJJIJJIJJJII, bool IIJIIJIIIJJIJJJJJIIJJIIJJJJJIJJJIIJJJJIJJIJJJIJ, JIJIJIJJIIJJJJJJIJIIJIIJJIJJJIJJJIJJJJIIJJIJJII JIIIIJJIJIJIIIJIJIIIIJIIJIJIJIIJJIJIIIJJIJIIJJI)
	{
		return false;
	}

	public static int JIIIJIIIIJJIJIJIIJIJIJJIJIIIJIJIIJIIJIIJIIIJJIJ()
	{
		return 0;
	}

	public static int IIJJIIIIIIJJIJIJJJIIIJJIJIIJJIJJJIIJIIJJIJIJJII()
	{
		return 0;
	}

	private static int JIIIJIIIIJJIJIJIIJIJIJJIJIIIJIJIIJIIJIIJIIIJJIJ(int IJJJIJJJIJIIIJJJJJIIJIIIJJJIJJJJIJIJJJIJIIIJJJI)
	{
		return 0;
	}

	private static int[] IIIIIIIIJJIIJIJIIJJIIJJJIIJIJJIIIIIIJJIIIIIJJJI(int IIJIIIIJIIJIIIIIJJJIJIIJJJIJJJIJIIIIIJIIIJIJIJI)
	{
		return null;
	}

	public static void JJIJIJJJJJIIJIIJIJJIJIJJJJJJJIIIIJIJJJIIJIJIJIJ(int IJIIJJJIIIJIJIJJIIIIIIIJIIJJIIJIIIIJIIJJIIIJIIJ)
	{
	}

	public static GameObject IJJJJIIIIIJJJJJJIIIJIJIJIJJIJJIIIIIIJJIIJIIJJIJ(string IIJJJJIIJJIJIIIIIJJIIIJIIIJJJJIIJJIJIIIIJIIJJIJ, Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Quaternion IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, byte IIIJIJJJJJJIJIIIIJIJIIJJIJIJIJJIIIIIIIJJJIJJJJI)
	{
		return null;
	}

	public static GameObject IJJJJIIIIIJJJJJJIIIJIJIJIJJIJJIIIIIIJJIIJIIJJIJ(string IIJJJJIIJJIJIIIIIJJIIIJIIIJJJJIIJJIJIIIIJIIJJIJ, Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Quaternion IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, byte IIIJIJJJJJJIJIIIIJIJIIJJIJIJIJJIIIIIIIJJJIJJJJI, object[] IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
		return null;
	}

	public static GameObject IJJIJIJIJJJJJJJIJIJJIJIJJJIIJIIIIJIIJJIIIIIJJII(string IIJJJJIIJJIJIIIIIJJIIIJIIIJJJJIIJJIJIIIIJIIJJIJ, Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Quaternion IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, byte IIIJIJJJJJJIJIIIIJIJIIJJIJIJIJJIIIIIIIJJJIJJJJI, object[] IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
		return null;
	}

	public static int JIIJIIJJJIJIIIIIJIJIJJIJJJIJIJJIJIIJIIIJIIJJJJJ()
	{
		return 0;
	}

	public static void JJIIIIJIJJJIJIJIIIIJIIJIIJIJJIIJIIJIIJIIIIJJIJI()
	{
	}

	public static void JJJIJIIJJIIJJJIJJIIIIJIIJJIJJIJJJIJIIIIIJJJJIJJ()
	{
	}

	public static bool JIJIJJJIJIJIJIJJJIJJJJIJJIIIJJIJIIIIJIIIJJIJIII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJJJIIJJJIIIJIIIJJJIIJJJJJIJIIIIIIIJIJIIIIJJJIJ)
	{
		return false;
	}

	public static bool JJJJJIIIIJIIJJIJIJJJJIIIIIIJIJIJIJIJJJIJIIIIIII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJIJJIIIIIJJIJJJJIJJJJIJIIIJIIIIIIIIJIJIIIIIJJ)
	{
		return false;
	}

	public static void JIJJJJJIIJIJIJIIJJIIIJIIJIIIIIJIJIJJJJIJJIIJJII(PhotonView IIJJIIJIIJIJIJIJJIIJIJJJJIIJJIIJJJJIJJIJIJIIJJI)
	{
	}

	public static void JIJJJJJIIJIJIJIIJJIIIJIIJIIIIIJIJIJJJJIJJIIJJII(GameObject IJIJIJIJJIJIIIJIIJJIIIJIIIIIIJJJIJJJIIJJJJJIJIJ)
	{
	}

	public static void IJJJJJIJIIJJJIIJIJJJIIJJIIJJIJJJJJJIJJJIIJJIJJI(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJJIJJIIJIIIIJJIIIIIJIJJJIJJIJIIIJJJIJIJJIJJII)
	{
	}

	public static void IJJJJJIJIIJJJIIJIJJJIIJJIIJJIJJJJJJIJJJIIJJIJJI(int JIIJJJIIIIJIIJIIJIIJJIJJJIIJIJJIIJJIJJJJIIIIIJJ)
	{
	}

	public static void IJJIJIIIIIJJIIJIJJIJIIIIIJJJJIJJIJJJJIIJIJIJJII()
	{
	}

	public static void JIJJIJJIIJIIJIIJIJJIJJIJIJIIIIJIJJIIIJIIIIJIJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJJIJJIIJIIIIJJIIIIIJIJJJIJJIJIIIJJJIJIJJIJJII)
	{
	}

	public static void JIJJIJJIIJIIJIIJIJJIJJIJIJIIIIJIJJIIIJIIIIJIJIJ(PhotonView IIJJIIJIJIIJJIJIIJIJJIJIJJIJJJIIIJIJJIJJJJIIJJJ)
	{
	}

	public static void IJIIIJJIJJJJIJIJIJJIIIJJJIIJIJJJIIJIJJJJJJJJJJJ(int IIJIJJJJIIIJIJIJIJJJIJJJIIIJIIJJIJJIIIJJIIIIIII)
	{
	}

	internal static void IIIJJJIIJIIIIJIIJJIIJJIIJIIIJIJIIIJJJIJJJIIJJII(PhotonView IIJIIIJIIIIJJJJIIIIIJIIIIIIIJIJIIJIJJIJIJJIJIII, string IJJJIJJIJIJJJJJJJJIIJJJJJJJIJIJIJIIJJIJIJIIJJIJ, JIIIIJIJJIIIIJIIJIIIJIJIIIJJJJIIIJIJIIJJIIJIIJI IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, bool JIJJJJJJIJJIIIJIIJIIIJIJIIIIJIJJIIJIIIJIIJIJJII, byte[] IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	internal static void IIIJJJIIJIIIIJIIJJIIJJIIJIIIJIJIIIJJJIJJJIIJJII(PhotonView IIJIIIJIIIIJJJJIIIIIJIIIIIIIJIJIIJIJJIJIJJIJIII, string IJJJIJJIJIJJJJJJJJIIJJJJJJJIJIJIJIIJJIJIJIIJJIJ, JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJJIJJIIJIIIIJJIIIIIJIJJJIJJIJIIIJJJIJIJJIJJII, bool IJIJJJIIIIIIJJJIJIIIIJJJJJJJIJIJIJJIIIJIIJIIIII, byte[] IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	public static void IIIJIIIJJIJIJJIIJJIJIJJJJIJIIIIJJIJJJIJJJJIJJII(Type JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
	}

	public static HashSet<GameObject> JIIJJIJJIIJJJJIIIIIIIIIIIJIIJJIIIIIJIJIIJJJJIII(Type JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return null;
	}

	[Obsolete]
	public static void JJIJIJIIIJIIJIJJIIIJIIIJJIIJIIIJIJJJIJJJIJJIJJJ(int IIIJIJJJJJJIJIIIIJIJIIJJIJIJIJJIIIIIIIJJJIJJJJI, bool IJJJJIIIIJIJIIIIIJJIJIJJIIIJJIIIIIJIIIJJJIIIIII)
	{
	}

	public static void JJJJIJJJIJIJJIJJJIIIIIJIIJJJJJIIJJJIJJIJIJIJIII(byte IIIJIJJJJJJIJIIIIJIJIIJJIJIJIJJIIIIIIIJJJIJJJJI, bool IJJJJIIIIJIJIIIIIJJIJIJJIIIJJIIIIIJIIIJJJIIIIII)
	{
	}

	[Obsolete]
	public static void JJIJIJIIIJIIJIJJIIIJIIIJJIIJIIIJIJJJIJJJIJJIJJJ(int[] JIJIJJIJIJJIIJJIJJJIIJJJIJJIIIJIIIIIIIJIIIJIJJI, int[] IIIIIIJJIJJIJIJIIIJJIJJJIJJJIIIIJIIJJJJJJJIIIIJ)
	{
	}

	public static void JJJJIJJJIJIJJIJJJIIIIIJIIJJJJJIIJJJIJJIJIJIJIII(byte[] IIIIIIJJIJJIJIJIIIJJIJJJIJJJIIIIJIIJJJJJJJIIIIJ, byte[] JIJIJJIJIJJIIJJIJJJIIJJJIJJIIIJIIIIIIIJIIIJIJJI)
	{
	}

	[Obsolete]
	public static void IJIIIIIIIIJIJJJIJJJIIJJIIIIIIJJJIIIJJJJIJJIJIII(int IIIJIJJJJJJIJIIIIJIJIIJJIJIJIJJIIIIIIIJJJIJJJJI, bool IJJJJIIIIJIJIIIIIJJIJIJJIIIJJIIIIIJIIIJJJIIIIII)
	{
	}

	public static void IJIIIIIIIIJIJJJIJJJIIJJIIIIIIJJJIIIJJJJIJJIJIII(byte IIIJIJJJJJJIJIIIIJIJIIJJIJIJIJJIIIIIIIJJJIJJJJI, bool IJJJJIIIIJIJIIIIIJJIJIJJIIIJJIIIIIJIIIJJJIIIIII)
	{
	}

	[Obsolete]
	public static void IJIIIIIIIIJIJJJIJJJIIJJIIIIIIJJJIIIJJJJIJJIJIII(int[] JIJIJJIJIJJIIJJIJJJIIJJJIJJIIIJIIIIIIIJIIIJIJJI, int[] IIIIIIJJIJJIJIJIIIJJIJJJIJJJIIIIJIIJJJJJJJIIIIJ)
	{
	}

	public static void IJIIIIIIIIJIJJJIJJJIIJJIIIIIIJJJIIIJJJJIJJIJIII(byte[] IIIIIIJJIJJIJIJIIIJJIJJJIJJJIIIIJIIJJJJJJJIIIIJ, byte[] JIJIJJIJIJJIIJJIJJJIIJJJIJJIIIJIIIIIIIJIIIJIJJI)
	{
	}

	public static void JIIIIIIJIIIIJIIIIJJIIJJIJIJJJJJJIIIJIJIIIIIIJJJ(short JIIIIIJJJIIIIJJJJIJIJIIJIIJIIIIIIJIJIIJIIJJJJJI)
	{
	}

	public static AsyncOperation IJIIIJJJJIJIJIJJIIJIJJJIIJIJIJIJIIJJJIIIIJIIIII(int IJIIIIJIIIIJJIIIJIJIJIIJJJIJJJIIJIJJJJJIIJJJJJJ)
	{
		return null;
	}

	public static void JIJIIJIJIIIIJIJJIIJIJIJJIIIJIIJIIIJJJIIJJJIJIJJ(string IIJIIIIIJJIIIIJIJJJJJJJJJIIJJJJIIJJJIJJJJIJJIJJ)
	{
	}

	public static AsyncOperation IJIIIJJJJIJIJIJJIIJIJJJIIJIJIJIJIIJJJIIIIJIIIII(string IIJIIIIIJJIIIIJIJJJJJJJJJIIJJJJIIJJJIJJJJIJJIJJ)
	{
		return null;
	}

	public static bool IIIJIIIJIJIJIJJIIJIJJJIIJIIIJJIJIIJIJIJIJIJJIJI(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, object JIJIJIJIIIIJIJIIIIIIJJIJIJJIIJJIIIJJIIJJIJJIJJJ)
	{
		return false;
	}

	public static bool JIIJIIJIIIIIIJJIIJIJIJJIIIJJIIJIJIIJIJIJJJIIIIJ(byte JIJJJJIIJJIJIJJIJIIIIJJIJIJJIIJJIIIIJIJJIJIJJJJ, object IIJJIJIJJJJJIIIIIJJIJIJIJJIIIJIJJJIJJIIJIIJIIJI, int JJJIJJIJJIJJJJJIIIIIIIIJIIJJIJIIIIJIJIJJIIIIIJJ)
	{
		return false;
	}
}
