using System.Collections.Generic;
using UnityEngine;

public static class JJIJIIJIJIIJIJIIIIIJIJIJJJJJIJJJJIJJIIIJIIJJIJJ
{
	public static void IJIIIIIIIIIIIJJJJIJJIIJIIJIJJIJIIIJJIJIIJJIJIJI(AudioSource IIJIJIIIIJJJJJIJJJIIIJIJJIJJIJIIJIJJIIIJJJIIJIJ, List<AudioClip> IJJJIIIJJJJJJJJJIJIIIJJIJIIJJIIJJJIJIIJJIIJIJII, Vector2 JIIIJJJIJJJJJIIIIIJJIJIJJIJIIIJJJIJJJIJIIIIIJIJ)
	{
	}

	public static void IJIIIIIIIIIIIJJJJIJJIIJIIJIJJIJIIIJJIJIIJJIJIJI(AudioSource IIJIJIIIIJJJJJIJJJIIIJIJJIJJIJIIJIJJIIIJJJIIJIJ, List<AudioClip> IJJJIIIJJJJJJJJJIJIIIJJIJIIJJIIJJJIJIIJJIIJIJII)
	{
	}
}
