using System.Collections.Generic;
using UnityEngine;

public interface JJIJJJJJIIJIIIIJIIJJJIIIIIJIIIJIJIJIIJJJIJJJIJI
{
	JJIIJIIIJJIIIJJJIJJIIJIJJIIJJJJJJJIJIIIIIIIJJJI IJJIJJJIJJJIJJIIJJJJJJIJIIIIIIJJIJIJIIJJJJJJIIJ { get; set; }

	int JIJIIIJJJJJIIJJJIIJIJJIIJIJJJIJJIJIIIIJIJIIIIII { get; set; }

	int IIJIIJIJIIIJIJJIJJJJJJJIJJIIIJJIIIJJIIJJJJIJJJJ { get; set; }

	bool IIIJJJIJJJJIIIIIJIJJIJJIJJIJIIIIIIIJIIJJIJIIJJJ { get; }

	List<IJJIIIIJIJJJIJJJJIIIIJJJIJIJIIJJJIIIIIJJIJIJJII> JIIJJJJIJJIJIJIJJJIJJJJIJJJJIJIIIIIJIIJJJIIIJJJ { get; set; }

	IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JJJIIIJJJIIIIIJIJIJJIIIJIIIIIIIJIIIJIIIIIIJJJJI { get; set; }

	Material IJIIJJJJJIIIJJJJIIIJJJJJIJJIJIJJIIIJJIIJJIIIIII { get; set; }

	bool JJIIIJJJJIIJJIJIJJIJIIIJIJJIIJJIIJJIIJIJJIIIIIJ { get; }

	bool JJJIJJIIIJIIIIIJIJJJJJJIJJIJJIJIIIJIIIJJJIJJJIJ { get; }

	Texture2D IIJIJIIIJJJIIIJJIIJJIJIIIIIIJJJIIJIJIJJIIIJIIIJ { get; }

	Rect IIIIIIIIIJIIIJJJIIJJJJIIIJIIJIIIIJJJJIJIIJJIIJJ { get; set; }

	string JIJJIIIIIIIJIIJIJJIJIJJIIJJIIIIIJIJJIJJJIIIJIJJ { get; set; }

	bool IIIJIJJJIIJIJIJJJJJJJJJIJJIJIJIJIIIIIIJJJJJJIII { get; }

	int JIJIIIJJJIJJIJJIIIJIIJIIJJJJJJIJIIJJJIJIJJIIJII { get; set; }

	IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ JIIIJIIJJIIIJIJJJJJIJIIJIJIJJIIJIJJJIIJJJJJJJIJ { get; }

	JJIJJJJJIIJIIIIJIIJJJIIIIIJIIIJIJIJIIJJJIJJJIJI JJJJJJIJJIJJJIIJIIIIJIJJJJJJJIJIJIJIJJIJIIIJJII { get; set; }

	bool IIJJJIIJJJJJIIJIJJJIIJIIIJJJIJJJJJIIJIJIJJIJIJI { get; }

	Font JJJIJJJJJIJJJIIIJJJIIIIJIIIIIJIIJJIIJJJIIJIIJJI { get; set; }

	FontStyle IIJJJJJJIIIIIIIIJJIJIJIJIJJIIJJJIIJJIJIJIJIJIII { get; set; }

	JJIIJIIIJJIIIJJJIJJIIJIJJIIJJJJJJJIJIIIIIIIJJJI bmFont { get; set; }

	int texWidth { get; set; }

	int texHeight { get; set; }

	bool hasSymbols { get; }

	List<IJJIIIIJIJJJIJJJJIIIIJJJIJIJIIJJJIIIIIJJIJIJJII> symbols { get; set; }

	IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII atlas { get; set; }

	IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ JJJJIJJIIIIIJIJJIJJJJIJIIJJJJIJJIJIIIIJIJIJIIJJ(string JIJJIIIIIIIJIIJIJJIJIJJIIJJIIIIIJIJJIJJJIIIJIJJ);

	Material material { get; set; }

	bool premultipliedAlphaShader { get; }

	bool packedFontShader { get; }

	Texture2D texture { get; }

	Rect uvRect { get; set; }

	string spriteName { get; set; }

	bool isValid { get; }

	int defaultSize { get; set; }

	IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ sprite { get; }

	JJIJJJJJIIJIIIIJIIJJJIIIIIJIIIJIJIJIIJJJIJJJIJI replacement { get; set; }

	bool isDynamic { get; }

	Font dynamicFont { get; set; }

	FontStyle dynamicFontStyle { get; set; }

	bool IIJJIIIIIJJJIJJJJJIIJJIJIIJIJIIIJIJJJJJIJJJJIJJ(JJIJJJJJIIJIIIIJIIJJJIIIIIJIIIJIJIJIIJJJIJJJIJI JJIJIJJJIIJJIJJIIJIIIIJIIJJIIJIIIJJIIJJJIJJIIJJ);

	void IIJIIIJIJIJJJJIJJIIJIIJJIIJJJJJIIIIIIJIJIJIIIIJ();

	void JIIIIJJIIIJIIIIJJJJIIIIJJIJJIJJIJJIIIJJJJJIIJJI();

	IJJIIIIJIJJJIJJJJIIIIJJJIJIJIIJJJIIIIIJJIJIJJII JIIIIJJJJIJIJJJJJJIJIJJIJJIIJJJIIIJJJJIIIIJIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, int IJJIJIIIIJIJIJJIIIIIIIJIIIJJIIIIJIJIJJIJIJIJIJJ, int JIIJIIIJJIJJIJJIIJIJJIIJIIIIJIIJIIIIIJIJJIJJIII);

	void JIJJJIIIJIJJJJIJJJIIIJJJJIJIJJIIIIIIIIJJIJJIJJI(string JJIIJJJJJIIJIIIJJJIJJIJJJJJIJIJIJJJIIJJIIIIIIJI, string JIJJIIIIIIIJIIJIJJIJIJJIIJJIIIIIJIJJIJJJIIIJIJJ);

	void JIJIJJIJJJJJJIJJJIIIJJIJJIIIIJIJJIIJJIIJJJJJIJJ(string JJIIJJJJJIIJIIIJJJIJJIJJJJJIJIJIJJJIIJJIIIIIIJI);

	void IIJJJIJJJJJIIIJJIIIIIJIIJJIJJJIIIJJJJJJIJJJIIJJ(string IJJIJIJJIJIIIJJIIIIJIJJJIJJIJJJJJIJIIIJJIJJJJJI, string JIJIJJIIIIIIIJJIJJIIIIJIJIIJIJIJJIIIJJJIJJJJIJJ);

	bool JJJJIIJIJIIIIIJJIJJJIJIIIIJIIIIJJJIJIIJIJIJJIJI(string IJJJIJJJIJJIIJJIJIJJJIIIJIJJJJJJIIJIJIIIJIJIJJI);
}
