using System.Runtime.CompilerServices;
using UnityEngine;

public class JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ
{
	public IIIJIJJJIJJJIIJJJJJJIJJJIJIJJJIJIIJIIIJIJJIIIJJ IIJJIJIJJIJJJIJJIJIJJJIIIJIJIJIIJJIIJIIIJIIJJII;

	public IJJIIIIJJIIJIIIIIJJIJIJJIIJJIIJIJIJIIIJIJIJIJIJ JIJIIIIIJIIIIIJIIJJIIJJIJJJIJIJJJIJIJJJIIIJJJII;

	private bool JIJJIJJIJIJIIIJJIJIIIIJIJIJJJJIIJJJIIIIIJJIIJII;

	public bool IIJIJIIJJJJIIIJIJIJJIIIIIIIJIJIIIIJJIIIIJIJJIIJ => JJIIJIJJJJJJIJJJJJIIJIJIIJJIIJJIJIIJIIJIJIJIJJJ();

	public bool IJJIIJJIJJIJJJJIIJJIJIIJJJJJIIJJIJIIJJJJJIIJIJJ => JJIJIIJIJJJIJJIJJIJIJJIJJIIIJJJIIIIIIIJIIIIIIII();

	public int JJIJJJIIJIJIJIIIJJJIIIJIJJJJIIJIIJJJIJJIJIJJIII => JIJJJJJIJIJJIJIJIJIJIIIJIIJJJIIIJJIJIJIJJJIJJII();

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJIIIJJIIJIIJJJJIJJJJJJJIIJJJIIIIIIIJJJJJJJIJJI(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public byte[] JIIIIJJIIIIJJIJIJIIJJIIIJIJIJIIJJJIJJIJIIIIJIII()
	{
		return null;
	}

	public void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}

	public JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ(bool JIJJIJJIJIJIIIJJIJIIIIJIJIJJJJIIJJJIIIIIJJIIJII)
	{
	}

	public void JIIJJJIIIJIJIJJIIIJJJIJJIIJIJIJIJJIIJJIJJJIJIII(Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public int JIJIIIJJIJIIIIJJIJJIIJIIIIIIJIJIJJIJJIIJJIJIIIJ()
	{
		return 0;
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(byte[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJJIJJJIJJIJIIIJIIIJJIJIJIIIJJIJIIIJIJIIIIIIIJI(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public byte[] IIIIJIJJJIIJIJJIJJIIIIIJIIJJIIJIJIJJJJJIIIJJJJJ()
	{
		return null;
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public int JIJJJJJIJIJJIJIJIJIJIIIJIIJJJIIIJJIJIJIJJJIJJII()
	{
		return 0;
	}

	public short JIIJIJIIJIJJIIIJIIJJJJIIIIJIJJJJJJJIJIIIIIIIJJJ()
	{
		return 0;
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(byte JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool JIIJIJIJIIIIIIJIIIIIIJJIJIIJIJJIJJIJIJJIIIJJIII()
	{
		return false;
	}
	public bool IIJIIJIIJIJJIJIJJJJJJIIIJJIIIIIIIIIIIIJIIIJJJIJ()
	{
		return false;
	}
	public bool IJJJJIJIIJJIIIIJIIIJIJJJIJJJIJJJJIJJJJJJIJIIIJI()
	{
		return false;
	}

	public byte[] IJJJIJIIJIIJJJJIJJJIIJJIIIIIIJIIJIIIJJIJJJJJJJI()
	{
		return null;
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(short JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(int[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJIIJJJIIJJIJJIIIJIIJJIJIIIIJJJIIJJJIJJIJIJIJIJ(byte[] JIIIJJIJIJIJJJIIJIJJJJJIJIJIIIIJIIIIJJIIJIJJIIJ)
	{
	}

	public float JJIIIJIIIJJJJIJIIIJJJJJIIJJJJJJIIIIJIIIJIJIIIII()
	{
		return 0f;
	}

	public bool JJIIJIJJJJJJIJJJJJIIJIJIIJJIIJJIJIIJIIJIJIJIJJJ()
	{
		return false;
	}

	public short JJJIIJIIIIJJIIIJJIIIIIIJJJJJIIJIJIIIJJIIIIIJIII()
	{
		return 0;
	}
	public int IIIJIIJJIIJIJJIJIIJJJIJJIIJIJJJIIJJIIIIIIIIIJJJ()
	{
		return 0;
	}

	public void JIIIJJJJIIJJJJIIIJIJIIJIJJJJJIJJIJJIIIJJJJIJIIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public byte JIIJIJJIIIIIJJJJIIJJIIJIJJJJJIIIJJIJJIIIIIJJJIJ()
	{
		return 0;
	}

	public bool JJJJJJJIJJJIIIIIIJJJJIIIJIJJJIIIIJIJJIIIJJIJIJI()
	{
		return false;
	}

	public float IIIIJIIIJIJIJIIJIJJJIJIJIJJJJIIJJJIJIIIIJJIJIIJ()
	{
		return 0f;
	}

	public bool IJIJIJJIIJIJIJIIJJIIIJJIIJIIJIIIIJJIJIJJJIJJIII()
	{
		return false;
	}

	public Quaternion JIIJJJJIIIIJIIIJIJJIIJIIIIIJIIJIJJIJIIJIIJIJJJI()
	{
		return default;
	}

	public bool JJIJIIJIJJJIJJIJJIJIJJIJJIIIJJJIIIIIIIJIIIIIIII()
	{
		return false;
	}

	public void JIJJJJJIIJIIIJIJJJJIIJIJJJJIJJJJJIJIJIJIIIIJIJI(int[] JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Vector3 JJIJJJIJIIJJJJJIJJJIIIIIJJJIIJJIJIIIIJIIJIIJJJI()
	{
		return default;
	}

	public void JIJIIJIJIJJJJJIIJJJIIJIIJIJIIJIJJIIJIJJJJIIJIIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public int IJIIJJJIIIIIJIJIJIIIJJIJIIIJIJJJJIIIIIIIIJJIIJJ()
	{
		return 0;
	}

	public bool JJJIJJIIIJIIIIJJIJJIJIIIIJIJIJIIIJIJJIIJIIJJJII()
	{
		return false;
	}

	public byte[] IJJJIJJJIIJJJJJIIJJIIJJIJIJIJIJIIIJJIIJIJIJJIJJ()
	{
		return null;
	}
}
