using System;

public class JJJIJJIJIIJIIIJIIIIIIIIJJIJIIIIJJIIIIJJJIIJJIII
{
	public const byte IIIIJIJIJIIIJIJJJJJIJJJJJIIJJIIIJIIIJJJJIIJJIII = 230;

	public const byte JJJIIIJJIIIJJJIJIIJIJIJJIJIJJJIJIJIIIIIIJJJIIII = 229;

	public const byte IJJIIJIIIIJIJJIJIJIIIIJIIIJIJIIIJJJJIIIIIIIJIJJ = 228;

	public const byte JJIIJIIJIIIIJIJIJJJIIJIJIIJJJIJIIIJJIIJJIJIJIJI = 227;

	public const byte JIIIIIJIIIJIIIJIJJJJJJJIIJIJIIJJJJJIJIIJJIIJIJI = 226;

	public const byte IJJIJJIJIIJJJJIJIIJJJJJIIIIJJIIIJJIIIJIIJJJIIJI = 224;

	[Obsolete]
	public const byte JIIIJJJIIJIJIIIJIIIIIJIJIIIIIJJJJIIJJIIJIIIIIII = 210;

	public const byte IIIIIIJJIJIIIIIJIJJIJIIIJJIIIIJJJJIJIIIIIIJJIII = byte.MaxValue;

	public const byte JIJJIIIIIJIJIIJJJIJJJJIJJIJIJIIIIJIIJJIIJIIIJII = 254;

	public const byte IIIIJJJIIJIJIIIJIIJIIIIJJJIIJIIIJJJIIJJJJIIJJII = 253;

	[Obsolete]
	public const byte IJJIJJJJIIJIJIIJIJIJIJIIIIIJIJIIJJIIJIJIJIIIIJJ = 253;

	public const byte JIJIJIIJIJJJIJIJJIIJJIJIIJJJIJIIIIJJJIIIJIJJJJJ = 251;

	public const byte IIIJIIJIIJIIIJIIJIIJJIIJJJJJJJJIJJIJIIJIJIIJIIJ = 250;

	public const byte JJIJJIIJIJIIIIJJIIIJJJJJJIJIJJJIIIJJIIJIJJJIIII = 223;
}
