using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;

public class JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<T>
{
	public delegate int IIJIIJJIJJIIIJJIJIJIIJIJJJIIJJIJJJJJJJJJJIJJIJJ(T JIJIIIIJJIIIIIJJJJJJIIIIJJIIIIJIIIIJJIJJJIIIIII, T IJIIJJJIIJIIJJJIIIJIIIJIJIIJJJJIIJJIIIJJJIJIIII);

	private sealed class JJIIJJJJJIIIIJIIJIJIIIIIJIJJIIJIIJIJIIIIIJJIIJI : IEnumerator<T>, IEnumerator, IDisposable
	{
		private int IJJJJJJJJIIJIIIIIJIIJJJIJJIIJIJJJJJIJJJJJIIIIII;

		private T IJJJJJIIIJJIIIIIIJIIIJIJJJIJIJIIJJIJIIIJJIIIJIJ;

		public global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<T> JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		private int JJJIJJJJJIIIJJIJJJIJJIIIIIJIJJJJJIJIJJIIIJJJJJI;

		T IEnumerator<T>.Current
		{
			[DebuggerHidden]
			get
			{
				return default;
			}
		}

		object IEnumerator.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		private void JJJJJIJJIIJJIIIJJJJJJIIIJIIJJJJJJIIJIIIJJJJIJJI()
		{
		}

		[DebuggerHidden]
		void IEnumerator.Reset()
		{
		}

		[DebuggerHidden]
		void IDisposable.Dispose()
		{
		}

		[DebuggerHidden]
		public JJIIJJJJJIIIIJIIJIJIIIIIJIJJIIJIIJIJIIIIIJJIIJI(int IJJJJJJJJIIJIIIIIJIIJJJIJJIIJIJJJJJIJJJJJIIIIII)
		{
		}
		private object IJIIJJIJJJIJJIIIJJIJIJJJJJIJJIJJIJIIJIIIJJJIJIJ()
		{
			return null;
		}

		private void IIJIIIJJJJJJIIIIJJJJJIJIJJIIJIJIJJIJIJIJIJIJIIJ()
		{
		}
		private object JIIJJIJJJJJIJJJIJIIIJIIIJJIJJJJIIJIIJIIJIJJJIJJ()
		{
			return null;
		}

		private void IIIIJJJJIJIIJIJJJIJJJJIIIJIIJJIIJJIJJJJJIIIJIII()
		{
		}

		private void JIIJJJJJJJIJJIJJJIIIIIJJJIIJIIIIJJIJIJJJIIJJIJJ()
		{
		}

		private void JJJJJIJJJJJJJJIJJJJJJIIIJJJJIJJIJJJJJIIJJIIJIIJ()
		{
		}

		private void JIJIJJIJJJIJIJIIJJJIIIIJIIIJJJIJIJIJIIJJJIJIIII()
		{
		}

		private bool JIIIJJJIIJIIIJIJJJIJIJJIJIJJJIIIIJIJJIIIIJIJIJJ()
		{
			return false;
		}

		private void IIIIJIIJIIIIJJJJIJIIJIIIJIIIIJJIJIJJIIJIJJJIIJJ()
		{
		}

		private bool JJIJJJIIJJJJIJIIJIJIIIIIJJJJIIIIIJJIJJIIIIIIJII()
		{
			return false;
		}

		private void JJIJIIIIJJIJJJJJJJIJJIJIIJIJIJIIIIJJIIIJJIJIIJI()
		{
		}
		private object IIIIJIJIIJIIIJJIJIJJJIIIJIJIIIIIJJIJJIJIJJIJJJI()
		{
			return null;
		}
		private object IIIJIJJIIIIIIIJJIIIIJJIJJIJJIJIIJIJJJIIJJJIIJII()
		{
			return null;
		}

		private bool JJIIIIJJIIIJJJIJIJIJJJJJJIIIIJIIJIIJIIJIJJIJIJI()
		{
			return false;
		}

		private bool IJIJIJIJIJJIJIIJJJIJIJIIIJIJIIIIIIJJJJIIJIIJJIJ()
		{
			return false;
		}

		private void JJJJIJIJJIJJJIJIIIIJJJJIJIJJIIIIJJIJIIIIJIJJJII()
		{
		}

		private bool IIJJIJJJJJJJJJIIJIJJIJJJJJIIIJIIIJIJIIIIJIJJJJJ()
		{
			return false;
		}

		[DebuggerStepThrough]
		[DebuggerHidden]
		private bool MoveNext()
		{
			return false;
		}

		bool IEnumerator.MoveNext()
		{
			//ILSpy generated this explicit interface implementation from .override directive in MoveNext
			return this.MoveNext();
		}
		private object JJJJJIIJJIIIIIIIIIIIJIIIIIJJJIIIIJIIJJJJIJJIJJJ()
		{
			return null;
		}
	}

	public T[] JJJIJIJIJIJIJIJIJJJIJJIIJIJJIIIIIIJJJJIJIJJIIJI;

	public int IJJJJJJIJIIIJJIIIJIJIJJIJIIIJJIJJJIIJJJJJIIJIII;

	// C# has no syntax for parameterized property 'JIJIIJJIJIIJJIJJIIIJIIIJIIIJJJJJJIJJIJJJIIJIIJJ'.
	// Its 'property:' attributes below are ignored by the compiler (CS0657).
	public T get_JIJIIJJIJIIJJIJJIIIJIIIJIIIJJJJJJIJJIJJJIIJIIJJ(int JJIIIJJJJIJIJJIJIJJJJJIJJJIIJIJJJIIIJJIJIJJIIII)
	{
		return JIJJIIIJJIIIJIIIJIIIJIIIJIIIJIJJIJJJIIIIJJJIJII(JJIIIJJJJIJIJJIJIJJJJJIJJJIIJIJJJIIIJJIJIJJIIII);
	}

	public void set_JIJIIJJIJIIJJIJJIIIJIIIJIIIJJJJJJIJJIJJJIIJIIJJ(int JJIIIJJJJIJIJJIJIJJJJJIJJJIIJIJJJIIIJJIJIJJIIII, T JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		IJIJIJIJJJIIIJJIJJJJIJIIIJIIIIIIIIJIIJJJJIJIJII(JJIIIJJJJIJIJJIJIJJJJJIJJJIIJIJJJIIIJJIJIJJIIII, JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI);
	}

	private void JJIJIJJIIJJJJIJJJIIJJIJIIJIJIIIJJJIIIIIIIJIJJIJ()
	{
	}

	public void IJIIJIJJIIIIJJIIJJJIJJIJJIJIIIJJIJJIJJIIJIJIJIJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}

	public void IJIIJIJIIIIJJIJIJJJIJJIJJIJJJJJJIIIJIJIJJIIIIJJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ, T JJIIIJJIJIJJIIIJJJJJJIIIJIIJIJJJIIJJJIIJIIJIJIJ)
	{
	}

	public bool JJIJJIIJIIJIJJIJIIIIIJJIJIJJIJJIJIJJJIIJJIJIJIJ(T JJIIIJJIJIJJIIIJJJJJJIIIJIIJIJJJIIJJJIIJIIJIJIJ)
	{
		return false;
	}

	private void IJJJIJJJJJJIIJJIJJIJIIIIIJIJJIJJIIJJIIIIIJIJJIJ()
	{
	}

	private void JJJJJIJIJJIJJJJJIIJIIIJJJIIIIJJJJJIJIIIIJJIJIIJ()
	{
	}

	public void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(T JJIIIJJIJIJJIIIJJJJJJIIIJIIJIJJJIIJJJIIJIIJIJIJ)
	{
	}

	public T JIJJIIIJJIIIJIIIJIIIJIIIJIIIJIJJIJJJIIIIJJJIJII(int JJIIIJJJJIJIJJIJIJJJJJIJJJIIJIJJJIIIJJIJIJJIIII)
	{
		return default;
	}

	private void IIJJJIIJIJJIIIJJIIIIIIIIIJJJJIJJJIJIJIJJJJJJJIJ()
	{
	}

	public void JIIJIIIIIJJJJIJJIJIJIIIIIJJJIJJJIJJJJJJIIJJIIII()
	{
	}

	public void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}

	private void IIIJJJJIIJJJJIJJIIJJJJJJJJJIIJIJJIIJIJJJJIJIJIJ()
	{
	}

	public T[] IJJJIJJJIIJJJJJIIJJIIJJIJIJIJIJIIIJJIIJIJIJJIJJ()
	{
		return null;
	}

	public void JIJJIJJIJJJJIJIJIJJIJIIIIJJJIIJJJIIIIJJJIJJJJII()
	{
	}

	public void IJJJJIIIJIJJIIJIJIJJJIJJJIJIIJIJIIJIJIIJJJJJIJJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}

	public void JJJJJIIJJIIIJIJJIJIJJJJIJJIJIJIJJIJJIJJJIIJIIJI()
	{
	}

	public void JJJIIIJIJJJIIIIJIJIJJJJIJJIIIJIIIJIJJIJIIJJIIJJ()
	{
	}

	public void IJIJIJIJJJIIIJJIJJJJIJIIIJIIIIIIIIJIIJJJJIJIJII(int JJIIIJJJJIJIJJIJIJJJJJIJJJIIJIJJJIIIJJIJIJJIIII, T JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJJJIIJJIJIJJJJIIJJJJIIJJJJIJJJJIJIJJIIIIIIJJJ()
	{
	}

	public void JIJIJJIIJJJIIIIJIJJJJJJIJIJIIIIJIJJJJJJJJIJIIJI()
	{
	}

	private void IJIIIJIIIJJIJJJIJJIIIJIJIJJIJJJIJJIJIIJIJJIJJJI()
	{
	}

	private void IIIJJJJJJIIIIJJIJJJJIIJIIIIIJIJIIJJJJIJJJJIJIII()
	{
	}

	public bool JIJIIIJJIJIJJJIIIIJIIIJIIJJJIJJIJIJIJIJIIIJJIJI(T JJIIIJJIJIJJIIIJJJJJJIIIJIIJIJJJIIJJJIIJIIJIJIJ)
	{
		return false;
	}

	public void JJJIIIIIJJJIIJJJJJJIIJIJJIJIIJIIJJJIIJIIJJJIIIJ()
	{
	}

	public int IJIIIJJIJIJIIIJIIJIJIJJJJIJJIIJIJIIJIIIIIIJIIJJ(T JJIIIJJIJIJJIIIJJJJJJIIIJIIJIJJJIIJJJIIJIIJIJIJ)
	{
		return 0;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public void IJIIJJIIIIJJIIIIIIJJIJIJJJIIJJJIJJIJIIIIJJIJIJJ(IIJIIJJIJJIIIJJIJIJIIJIJJJIIJJIJJJJJJJJJJIJJIJJ IJIJIIIJJJIIJIJJJJIJIJIJJIJJIIJIIJIJIJIJIIJIJJJ)
	{
	}

	public T IJJJJJIJIIIJJJIIIJJJIIIIIIIIJIIIJJIIIJJIIJIIJJJ()
	{
		return default;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public IEnumerator<T> IJIJJJJIJJIJJJIIIJIIJJJIIJIJIJIJJIIJIIJJIIIIJIJ()
	{
		return null;
	}
}
