using System;
using System.Runtime.CompilerServices;
using ExitGames.Client.Photon;

public class JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII : IComparable<JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII>, IComparable<int>, IEquatable<JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII>, IEquatable<int>
{
	private int JJJJJIIIIJJIJIIJJJJIJJJIJIJIIJJJJJJIIIIIJJIJJJI;

	private string IJJIIJIJIJJIIJJJJIJJJIJJIIIJIJJJIJIJIJIIIJIIIII;

	private string IIJJJIJJIJIIJIIJIIIJIJJIJJJIIIJJJIJJJIJJJIJJJIJ;

	public readonly bool IIJJIJJJJIJJIIJJJJJJIIJJJIJIJIJIJIJIIJJJJIIJJJI;

	private bool IJIIIJIJJIJJJIJJIIJIIJIIIIJIJIJJJIJJIJJJIJJJJJJ;

	private Hashtable JJIIJIJIJJIIIIIIJIIIIJIJIIIIIIIJJIJJIJIIIIJIJIJ;

	public object JJIIIIIIIIJIIJJIIIJJJJJJIIJJIIJIJJIIIIJIJJIJIJJ;

	public int IJJJIIJIJIJJJIIIIJJIIJJIIIIIIIIIJJIJIJIIJIJIIIJ => JJIJJJJJIIIJJIIJJJJJJIJIJJJJJIIIIIJIIIJIJJJIJJJ();

	public string JJJJJIJIJIIIJIJJIJIJJIIIJIJJIJJIJJJJJJJIJIIJJII
	{
		get
		{
			return IJJIJJJJIJJIIJJIIJIJIIJIJIJJJJJJIIIJJJIIIJJJJJJ();
		}
		set
		{
			JJJJJJIJJJIIJJIJJJIIJJJJJJJJJIJJJJIJJJJIIJIIJJI(value);
		}
	}

	public string JIJJJIIIIJIJIIJJJIJJJIJIIIJIIJIJIIIJIIIJJIJJJII
	{
		get
		{
			return IIJJIIIJJIJIJJJJIIIJIJJJIJJJJIJIJJIJJIJJJIIJIJJ();
		}
		internal set
		{
			JJJJJIJJIIIJIIIJIIIIIIJJJJIJJJJJIJIJIIJJIJIIJIJ(value);
		}
	}

	public bool IIJJIJJIIJJJIJIJIJIJJIJJIJJJIIJJJIJIJIIIIJJIJII => JJIIIJIIJIJJJIIJJIJJIIJIJJJIJIJIJJIIIIIIJJJIIJJ();

	public bool IIIIJIIJJIIJJJJJIIJIJJJJJIJJIIIIJIJIJIJJIJJIIJJ
	{
		get
		{
			return IIJJJJJIIIJIJJJIIIIJIJJJJJJJJIIJJJIIJIJIIJJJJJJ();
		}
		set
		{
			JJIIIJIJIJIIJJIIIJIJJIJIJIIIJJJIJIIIJIIIJJIJJJJ(value);
		}
	}

	public Hashtable JJIJIIIIJIIJIIJJJJIIIIJIJIJIJJIIJIJIIIIJJJJIIII
	{
		get
		{
			return IIIJJIIIIIIJJIJIJIJJIIIJJJIIIJJJJIJIIJJIJJIJJII();
		}
		internal set
		{
			JIJIJJJIJJJJJJIIJIIIJJJIIIIIJIIJIIJIIIIJIJJJJIJ(value);
		}
	}

	public Hashtable IIIJJJIIIIJIIJJIIIJJIJIIIJIJIJJJIJIIIIIJIIIIJII => JIJIIJIJIJJJIJIJJJJIJIJIJJIIIJIIJIJJIIJJJJIJJIJ();

	[Obsolete]
	public string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ
	{
		get
		{
			return JJIIIJJJIIJJJJJJIIIIJJJJIJJIIJJIIIIIIIJJJIIIJJI();
		}
		set
		{
			IJJJIJIIIJJJIIJIJIIJIJJIJIIIIIIJIJJIIIIJJJIJJJI(value);
		}
	}

	[Obsolete]
	public string IJJIJIIIIIIIIJIJJJIIJJJJIIIIIJIIIJIIIIIJJJJIJJJ
	{
		get
		{
			return JJJIIIIIIIIJIIIIIJIIJIIJIJJJIIJIIJIJIIJIIIIJIJI();
		}
		internal set
		{
			IIIJJIJIIJJIIJJJJJJJJJIIIJJJJIIIJIJJJIJJJIJJIJJ(value);
		}
	}

	[Obsolete]
	public bool JIIIIJIIIJJIJIJIJIIJJIJJJJIJIJIIIIJJIIJJIJIIIJI => IIJJIJJIIJIJIIIIJIJIJIJJJIIIIJJJIJJIJIJIIIIJIII();

	[Obsolete]
	public bool JIIIJIIJIIJJJJJJIJIJJJJIJIJJIJJIIIIIJIJJIJJIJII => JIJIJJJIJIIIIJJIIJJIJIJIJJIJIIJJIIIIIJJJIJJIJIJ();

	[Obsolete]
	public bool JJJJIJIIIJJIIIJJJJJJJIJJIJJIIJIIJIIIIIIJJIIIJIJ
	{
		get
		{
			return JJJJJIIJIJIIIJJJIJIJJJJIJIIIJIIJIIJIJIIJIJJIJII();
		}
		set
		{
			IJIJIIJIJJIIJIIIIJJIIJJIIJIIIIIJIIJIJJJJJIIIJIJ(value);
		}
	}

	[Obsolete]
	public Hashtable JJIIJJIJIJIIIJIJIIIIIJIJIJIIJJJIJJIIIJIIJJJJIII
	{
		get
		{
			return JJJIJJJJIJJJJIJJIJIIJJJIJJIIJJIIIJJJIIIJJJJIJII();
		}
		internal set
		{
			JIIIIJJIIJJJJIIIJJJIJIJJIJIIIIIIJJJJIIIIJIIJIII(value);
		}
	}

	[Obsolete]
	public Hashtable IJJJIIIJIIJIJIJJJIIJJJJJIIJJJJJJIIIIJIIIIJIIIII => JJJJJJIIJIJJJIIJIIJJJJIJIIIIJIJIJIIJIIJJJJIIJJJ();

	public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII(bool JIIIIJIIIJJIJIJIJIIJJIJJJJIJIJIIIIJJIIJJIJIIIJI, int JJJJJIIIIJJIJIIJJJJIJJJIJIJIIJJJJJJIIIIIJJIJJJI, string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public bool JJJJJIIJIJIIIJJJIJIJJJJIJIIIJIIJIIJIJIIJIJJIJII()
	{
		return false;
	}
	public bool IIJJIIIJJIIIJIIJIJIIIJIJIJIJJJJJIIIJJIJJIJIJJII()
	{
		return false;
	}

	public string IJJIJJJJIJJIIJJIIJIJIIJIJIJJJJJJIIIJJJIIIJJJJJJ()
	{
		return null;
	}

	public int JJIJJJJJIIIJJIIJJJJJJIJIJJJJJIIIIIJIIIJIJJJIJJJ()
	{
	        // RVA 0x00c44b8c: returns actorID (+0x08).
	        return JJJJJIIIIJJIJIIJJJJIJJJIJIJIIJJJJJJIIIIIJJIJJJI;
	}
	public int JIJJIIJIIIIJJJJIJIIJJIJIJIIIJIJJJJJIIIIJJIJIIIJ()
	{
		return 0;
	}

	public void IJIJIIJIJJIIJIIIIJJIIJJIIJIIIIIJIIJIJJJJJIIIJIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool Equals(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
		return false;
	}

	public bool IIJJIJJIIJIJIIIIJIJIJIJJJIIIIJJJIJJIJIJIIIIJIII()
	{
		return false;
	}

	public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJIJJIJJJJJIIJJIIJJIJJIJIIJIJJIJJIJJJIIJJJIJIIJ(int IJIIIIIJIIIJIJJJJIJJJIIIJJIJIJIJJIJIJIJIJIIJIII)
	{
		return null;
	}

	public override bool Equals(object JIIIIJJJJIIIIJJIJIIIJIJJJIJIIJJIJJIJJIJIIIJIIJJ)
	{
		return false;
	}

	internal void JIJIJJJIJJJJJJIIJIIIJJJIIIIIJIIJIIJIIIIJIJJJJIJ(Hashtable JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	internal void JIIIIJJJIIIIJJJIIIIIJJJIJIJIJJIIJJIIJIIIIJJIJJJ(int JJJIIIIIJIIIIIIJJIJIIJIJJIIIIJJJJJIJIIJIIIIIIIJ)
	{
	}

	internal void IIJIIIJIIIIIJIIJJIIIIIIJJJJJIJJJIIIJJIIJJIIIIII(Hashtable IIJIIIJJIJJJJJJJJIJJJIJJJIIIJIJIIIJJJIJJJJJIJIJ)
	{
	}

	public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJIJJIIJIJIIIJIIIIIIJJJIIJJJIIIJIJIJIJIIJIJIII()
	{
		return null;
	}

	public bool Equals(int IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
		return false;
	}

	public string IIIJIIIJJJJIIJIIIJJJIIIIJJJJJIJJIJJIIJIIJJIIJJJ()
	{
		return null;
	}

	public bool JJIIIJIIJIJJJIIJJIJJIIJIJJJIJIJIJJIIIIIIJJJIIJJ()
	{
		return false;
	}
	public Hashtable IIIIJIIJIIJJIIIIIJJIJIIIIJJIJJIJJJIIIJJJJJIIJIJ()
	{
		return null;
	}

	internal void JIIIIJJIIJJJJIIIJJJIJIJJIJIIIIIIJJJJIIIIJIIJIII(Hashtable JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool IIJJJJJIIIJIJJJIIIIJIJJJJJJJJIIJJJIIJIJIIJJJJJJ()
	{
		return false;
	}

	public static JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIIIIIIJIJJJIIJJIJIIJIJIJJIJJIJJJIJJJJIJJIIJ(int IJJJIIJIJIJJJIIIIJJIIJJIIIIIIIIIJJIJIJIIJIJIIIJ)
	{
		return null;
	}

	public override int GetHashCode()
	{
		return 0;
	}

	public void IJJJIJIIIJJJIIJIJIIJIJJIJIIIIIIJIJJIIIIJJJIJJJI(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected internal JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII(bool JIIIIJIIIJJIJIJIJIIJJIJJJJIJIJIIIIJJIIJJIJIIIJI, int JJJJJIIIIJJIJIIJJJJIJJJIJIJIIJJJJJJIIIIIJJIJJJI, Hashtable IIJIIIJJIJJJJJJJJIJJJIJJJIIIJIJIIIJJJIJJJJJIJIJ)
	{
	}

	internal void IIIJIJIJJIIIJIJIJIJJIJIJJIIIJJIIJJIJJJIIJIIIJII(int JJJIIIIIJIIIIIIJJIJIIJIJJIIIIJJJJJIJIIJIIIIIIIJ)
	{
	        // RVA 0x00c45f08: verified against PUN 1.101 InternalChangeLocalID.
	        if (IIJJIJJJJIJJIIJJJJJJIIJJJIJIJIJIJIJIIJJJJIIJJJI)
	        {
	            JJJJJIIIIJJIJIIJJJJIJJJIJIJIIJJJJJJIIIIIJJIJJJI = JJJIIIIIJIIIIIIJJIJIIJIJJIIIIJJJJJIJIIJIIIIIIIJ;
	            return;
	        }
	        UnityEngine.Debug.LogError("ERROR You should never change PhotonPlayer IDs!");
	}

	public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJJIJIJIIJIJJJJJIIJIJJJJJJJJIIIIJIIIIJJIJJIIJJI(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJIIJIJJIJIIIIJJIJJIIIIIJJIJJJJIJIJJIJJJJIJJIJ)
	{
		return null;
	}

	public void IIIJIJJJJIIIIIIIJIJJIJJIJIIIIIJJJJIIIIJJIJJJJIJ(Hashtable IJJIIIJIJJIJIJJJIIJIJIIIIJJIIJJJJJJIIJIJJJIIIJJ, Hashtable IJJJJJJJIIJJIIJIJIIIJJIIIIIIJIIJJIIJIIIIIIIJIIJ = null, bool JIJJIJJJJJIJIJJJJIJJIIJIIJIJJIIJIIIJIIIJIJJJIIJ = false)
	{
	}

	public override string ToString()
	{
		return null;
	}

	public string JJJIIIIIIIIJIIIIIJIIJIIJIJJJIIJIIJIJIIJIIIIJIJI()
	{
		return null;
	}

	public void JJIIIJIJIJIIJJIIIJIJJIJIJIIIJJJIJIIIJIIIJJIJJJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIIIIIIIIJJIIJIJJIIIIIJIIJIIIIIJIIJJIIIIJIIIJI(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return null;
	}

	internal void IIIJJIJIIJJIIJJJJJJJJJIIIJJJJIIIJIJJJIJJJIJJIJJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	internal void JJIIIJJJIIIJJIJJJIJJJIIIJJIJJIIIJJIIIIJIIJIJIII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public int CompareTo(int IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
		return 0;
	}

	public string JJIIIJJJIIJJJJJJIIIIJJJJIJJIIJJIIIIIIIJJJIIIJJI()
	{
		return null;
	}

	public int CompareTo(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
		return 0;
	}

	public Hashtable JJJIJJJJIJJJJIJJIJIIJJJIJJIIJJIIIJJJIIIJJJJIJII()
	{
		return null;
	}

	public void JJJJJJIJJJIIJJIJJJIIJJJJJJJJJIJJJJIJJJJIIJIIJJI(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIIJIIJIIJIJIJIIJIIJIJJJIIIJJIIIIJIIJJJIJJJIJI(int IJJJIIJIJIJJJIIIIJJIIJJIIIIIIIIIJJIJIJIIJIJIIIJ)
	{
		return null;
	}

	public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJIJJIJJJJJIIJJIIJJIJJIJIIJIJJIJJIJJJIIJJJIJIIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJIIJIJJIJIIIIJJIJJIIIIIJJIJJJJIJIJJIJJJJIJJIJ)
	{
		return null;
	}

	internal void JJJJJIJJIIIJIIIJIIIIIIJJJJIJJJJJIJIJIIJJIJIIJIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Hashtable JJJJJJIIJIJJJIIJIIJJJJIJIIIIJIJIJIIJIIJJJJIIJJJ()
	{
		return null;
	}

	public Hashtable JIJIIJIJIJJJIJIJJJJIJIJIJJIIIJIIJIJJIIJJJJIJJIJ()
	{
		return null;
	}

	public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIIIIIJIIJIIJJJIIJJJJJJIJJIIIJJJIIJJJJIJJIIJJJ()
	{
		return null;
	}

	public Hashtable IIIJJIIIIIIJJIJIJIJJIIIJJJIIIJJJJIJIIJJIJJIJJII()
	{
		return null;
	}

	public void JIIIIIIJJJJJJJJJJIIJIIJJIJJJIIJJJIJJIIJJIJJIIJI(Hashtable IJJIIIJIJJIJIJJJIIJIJIIIIJJIIJJJJJJIIJIJJJIIIJJ, Hashtable IJJJJJJJIIJJIIJIJIIIJJIIIIIIJIIJJIIJIIIIIIIJIIJ = null, bool JIJJIJJJJJIJIJJJJIJJIIJIIJIJJIIJIIIJIIIJIJJJIIJ = false)
	{
	}

	public string IIJJIIIJJIJIJJJJIIIJIJJJIJJJJIJIJJIJJIJJJIIJIJJ()
	{
		return null;
	}

	public bool JIJIJJJIJIIIIJJIIJJIJIJIJJIJIIJJIIIIIJJJIJJIJIJ()
	{
		return false;
	}

	public virtual string JJIJJIIJJIIJIIIIJIIJJJJIJIJJIIIIJIJIJIJIJIIIIJJ()
	{
		return null;
	}

	internal void JIJJIJJIJJIJIIJJIIIIIIIIIJJIIJJIIIJIIIIJJIJJJJI(Hashtable IIJIIIJJIJJJJJJJJIJJJIJJJIIIJIJIIIJJJIJJJJJIJIJ)
	{
	}
}
