using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using ExitGames.Client.Photon;

public class JJJJIJIJJIIIIJIIIJJIJJJIIIJJJIJIJIJJJIIIJIJIIIJ
{
	private sealed class JIJJIIJJIIIIJJIIJJIJIIJIJJIJJIJJJIIIJJIJIIJIIJI : IEnumerator<object>, IEnumerator, IDisposable
	{
		private int IJJJJJJJJIIJIIIIIJIIJJJIJJIIJIJJJJJIJJJJJIIIIII;

		private object IJJJJJIIIJJIIIIIIJIIIJIJJJIJIJIIJJIJIIIJJIIIJIJ;

		public JIIIIJJJJIJJJIJJJJIJJJIIJIIJJIJJJJIJJJIJJIIJIII IIJJIJIJIJJIIJJIJJJIIIIIIIJJIIJIJJJJIIIJIJJJJJJ;

		public JJJJIJIJJIIIIJIIIJJIJJJIIIJJJIJIJIJJJIIIJIJIIIJ JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		private PhotonPing IJIIJIIJIJJIJJIIIJIJIIIIIJIJIJIIIIJIIJIIJJJIIJI;

		private float JIIIJIIIJIIIIIJJIIIJJJJIIJIJJIJJJJIJIJIJJIIIIJI;

		private int JIIIIIIIJIJJJJJIJIJIJIIIJIJJIIIIIIJJIJJJIIJJIII;

		private string IIJIIIJIIIIJJIIJJIJJJJJJJIIIIJJIJIJJJIIJIJIJJII;

		private int IJIJIIIIJIIJIIIJJIJIJJJJJIJIJIIIIIJJJJJJIJIIIJI;

		private bool JIJIIJJJIJIJJJJIIJIJIIJJJJJIIJIJJJJJIIIJIJIIIJJ;

		private Stopwatch IIJIJJIIJJJJJJIJIIJJJJIJIIIJJIIIJIJJJJJIJJIIIJI;

		object IEnumerator<object>.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		object IEnumerator.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		private bool MoveNext()
		{
			return false;
		}

		bool IEnumerator.MoveNext()
		{
			//ILSpy generated this explicit interface implementation from .override directive in MoveNext
			return this.MoveNext();
		}

		[DebuggerHidden]
		void IDisposable.Dispose()
		{
		}

		private void JIJIJJIJJJIJIJIIJJJIIIIJIIIJJJIJIJIJIIJJJIJIIII()
		{
		}

		private bool JJJJJIIJJJJIIJJIIIIJIJIJJJJIJIIIJJIIJJIIJIIIIJI()
		{
			return false;
		}

		private void IIIJJJIIJIJIIJIIJJJIIJJJJJIIIIIJIIJJJIIJIIJJIIJ()
		{
		}

		[DebuggerHidden]
		public JIJJIIJJIIIIJJIIJJIJIIJIJJIJJIJJJIIIJJIJIIJIIJI(int IJJJJJJJJIIJIIIIIJIIJJJIJJIIJIJJJJJIJJJJJIIIIII)
		{
		}

		private bool IJIIJJJJJIIIIIJJJJJJJIIJJIIIIJJIIIJJIIIJIJIJJJJ()
		{
			return false;
		}

		private void JJJIIIJIJIJJIJIJJJIJIIJIIJJIIIIIJJIIIIJJIJJIJIJ()
		{
		}

		private bool JIIIIJIJIJJJIJJIJIJIJIJIIIJIJIIIIJJIJJJJJIJIJII()
		{
			return false;
		}

		private void IIIIIIJJIIIIIIJIJIIJIJJIIJJIJJIIJIIJJIJJIJJIIJJ()
		{
		}

		private void IIJIJIIIIIIIIJJIIIIIJIIIIJJIIJIIIIIIIJJIJIJJJII()
		{
		}
		private object IJJIJJJJIIIJJIIJIIIIJIJJIIIJIIJIJIJIJIIIIJIIIJJ()
		{
			return null;
		}
		private object IJIIJJJJIIJJIIIIIIIIJIIIJIIIIJIIIJIJIIJJIIIIIJJ()
		{
			return null;
		}
		private object JJJJIIJJJJJJIJJJJIJIIIIJJIIJIIJJJIIJIJJIIIJIJII()
		{
			return null;
		}
		private object IJJJJIJIIJIJJJJJJIIIIIIIJJIIIJIJIIIIJJIIJIIIJJJ()
		{
			return null;
		}

		private void JIJJIJIIIJIIIIJJIJIJJIJIJIIIIJIIJJIIIJIIJJJIJII()
		{
		}

		private void IJJJJIIJJIJJIJIIIIJJIJIJJIJIJIIJIJJJIJIIIJIJIJI()
		{
		}

		[DebuggerHidden]
		void IEnumerator.Reset()
		{
		}

		private bool JJIJJJIIJJJJIJIIJIJIIIIIJJJJIIIIIJJIJJIIIIIIJII()
		{
			return false;
		}
		private object IJIIIJIIIIIJJJIJIIIIJIJJIIJJJJJJJIJJJIIJIIIIJII()
		{
			return null;
		}

		private void JJIIJIJJJJIIIIIIJIIJJJJJJJJIIJIJJJIJIJJJJIIJIJI()
		{
		}

		private bool JIIIJIJIJIIJIIIJJIIJIIJJIJJIJJIJJIIIIJJIJJIIJIJ()
		{
			return false;
		}
		private object JJJJJIIJJIIIIIIIIIIIJIIIIIJJJIIIIJIIJJJJIJJIJJJ()
		{
			return null;
		}

		private bool IJJIIIIIIJIIIJIIJIJJJIIIJJJIJJJIIIIIJIJJIIJIJJJ()
		{
			return false;
		}
	}

	public bool JIJJIJIIJJJIIIJJIIJIJJIJIIIJIJJJIJJJIIJJIJIIJIJ;

	public static int JJJIJJJJJJJJJIIJJIJJIJIJIIJIIJIJJIIJIIIJIJJJJIJ;

	public static bool IIJIIJJIJIIIJJJJJIIJJJIJJIIIJJJJJJJJJIIJJJJIIIJ;

	public static int IJJJJIIJJIIJIJIIJJJIJJJIJJIIJIIJIJIJIJJIJIIIJIJ;

	private const string IIJJIJIIIIIIJIIIIIJJIIIJIJJIIIJIJIJJJIJIJJJJIIJ = "wss://";

	private int IJJJIJIJIIIJIIIIIIJIJIIIIJIJIJJIJJIJJIJIIIIIIJI;

	public JIIIIJJJJIJJJIJJJJIJJJIIJIIJJIJJJJIJJJIJJIIJIII JJJJJJIJIJJIIJIIJJIIIIIIJIJJJIIIIIJIJIIIIJJJIII => IIIIJJIJJJIIIJJJIJJIJJIJJIIIIIIJIIJIJJIJJIIIIIJ();

	public bool IIJIJJJIIIIIIIIIIIJIIIIJJJJIIIIIJIIJJJIJJJIJJJJ => IJJIJIIJIIIJIJJJIIJJJJIJIIJIIJJJJIJJIJJJIIJJJJJ();

	public static string IJIIJJIJJIIIJJIJIIJJIIJJJIIIIJIIIIJIIJJIIIIJIIJ(string JIIIIJJIJIJJIJJJIJJJJJJJIJIJJIJIIJIIIIIJIIIIIJI)
	{
		return null;
	}
	public bool IJIIJJIJIIJJJJJIIIIIJIIIIIIIJJJJIIJJJJJJIJJIJJJ()
	{
		return false;
	}

	public IEnumerator JIJJIJJIJIJIIIJIIJJIJIJIIJIIIJJIJJIIJIJJJJJIIII(JIIIIJJJJIJJJIJJJJIJJJIIJIIJJIJJJJIJJJIJJIIJIII IIJJIJIJIJJIIJJIJJJIIIIIIIJJIIJIJJJJIIIJIJJJJJJ)
	{
		return null;
	}

	public IEnumerator JJIJJIIJIIJIIIIJIJJIIJJIIJIIJJJJJJIJJIJIIIIIJII(JIIIIJJJJIJJJIJJJJIJJJIIJIIJJIJJJJIJJJIJJIIJIII IIJJIJIJIJJIIJJIJJJIIIIIIIJJIIJIJJJJIIIJIJJJJJJ)
	{
		return null;
	}
	public JIIIIJJJJIJJJIJJJJIJJJIIJIIJJIJJJJIJJJIJJIIJIII JJJJIIIIJIIIIJIJIJJIJJIIIJIIJIJIIJJJJIIIIJIJJJI()
	{
		return null;
	}

	public static string IIJIJJIIJJIIJJIIIJJIIIJJIJIJIIIIIIJJJIJIJIIJJJI(string JIIIIJJIJIJJIJJJIJJJJJJJIJIJJIJIIJIIIIIJIIIIIJI)
	{
		return null;
	}

	public IEnumerator JJIJJIJJIJIJIJIIIJJJJIJIIIJJJJIJJJJIIJJJJIIJIIJ(JIIIIJJJJIJJJIJJJJIJJJIIJIIJJIJJJJIJJJIJJIIJIII IIJJIJIJIJJIIJJIJJJIIIIIIIJJIIJIJJJJIIIJIJJJJJJ)
	{
		return null;
	}
	public bool IJJIIJIIIJJIJJIJIJIJIIIIJJIIIJJIJIJJIJIIJIJJJIJ()
	{
		return false;
	}

	public bool IJJIJIIJIIIJIJJJIIJJJJIJIIJIIJJJJIJJIJJJIIJJJJJ()
	{
		return false;
	}

	public static string IJIJJIJJJIJIIJJJJJJJIJIIIJJIIIJJJIIIJJJJIIJJJJI(string JIIIIJJIJIJJIJJJIJJJJJJJIJIJJIJIIJIIIIIJIIIIIJI)
	{
		return null;
	}
	public bool JIJIIIJJIIJJJIIJIJJJJIJIIJJIIIIJJJJJJIIIJIJIIII()
	{
		return false;
	}
	public bool JIIIIIIIJIJJIJJJJIIJIJIJJJJJIJJJIJJJJIJJJJJJJIJ()
	{
		return false;
	}

	public IEnumerator IJJJJJIIIJIJIJJIIIIIIIJIJJIJJIIJJIJJJIIJJJIIJII(JIIIIJJJJIJJJIJJJJIJJJIIJIIJJIJJJJIJJJIJJIIJIII IIJJIJIJIJJIIJJIJJJIIIIIIIJJIIJIJJJJIIIJIJJJJJJ)
	{
		return null;
	}

	public static string IIJJIJJIJJJJIJJJIJIJJJJJJJIJJIIJJIJIJIJIJJJIJJI(string JIIIIJJIJIJJIJJJIJJJJJJJIJIJJIJIIJIIIIIJIIIIIJI)
	{
		return null;
	}
	public bool JIIIIIJJJJIJIIIJIIIJJIJIIIJIJIJJIIJJIJIJJIJIIJJ()
	{
		return false;
	}

	public IEnumerator JIJJIIJJIJJJIIJIIIIJIIIIIJJIIIJJIIIIJIJIIJJJJJI(JIIIIJJJJIJJJIJJJJIJJJIIJIIJJIJJJJIJJJIJJIIJIII IIJJIJIJIJJIIJJIJJJIIIIIIIJJIIJIJJJJIIIJIJJJJJJ)
	{
		return null;
	}

	public static string IIIIJIJJIJJJIIJJJJJIJJJJIJJJJIJJIIJIIJJJIJJJIJI(string JIIIIJJIJIJJIJJJIJJJJJJJIJIJJIJIIJIIIIIJIIIIIJI)
	{
		return null;
	}
	public JIIIIJJJJIJJJIJJJJIJJJIIJIIJJIJJJJIJJJIJJIIJIII IJJJIJJIJJIIJIJIIJIIJIIIIJIIIIJIJJIJIIJJIJIIJJI()
	{
		return null;
	}
	public JIIIIJJJJIJJJIJJJJIJJJIIJIIJJIJJJJIJJJIJJIIJIII JIIJJJJIIIJIJIJIJJIJIJIJJIIIJIIJIIJJJJJJJIJIIJJ()
	{
		return null;
	}
	public bool IIJIIIJJJIIJJIJIJJJIIIJJIIJJIIIIIIIIJIJJIIJJJJJ()
	{
		return false;
	}

	public IEnumerator IIJIJJIJJIJIJIJIIIIJIIIIIIJIIJIJIJIJIJIIIJJIIII(JIIIIJJJJIJJJIJJJJIJJJIIJIIJJIJJJJIJJJIJJIIJIII IIJJIJIJIJJIIJJIJJJIIIIIIIJJIIJIJJJJIIIJIJJJJJJ)
	{
		return null;
	}

	public JIIIIJJJJIJJJIJJJJIJJJIIJIIJJIJJJJIJJJIJJIIJIII IIIIJJIJJJIIIJJJIJJIJJIJJIIIIIIJIIJIJJIJJIIIIIJ()
	{
		return null;
	}
}
