public static class JJJJIIJJIJJIIJIIIIJIIJJIIJIIIIIJJJJIJJJIJJJIIIJ
{
	public const byte JIIIIJJJJJIIIIJIJIJIIJIJIIJJJIIJJJJIJJJJIJIIIJI = 0;

	public const byte JIJIJIIIIJIJIJJIJIJIIJIIJJJJJJIIJIJIJIJIJJJJJJI = 1;

	public const byte JIJJIIJIJIJJJJIIIIJJJIIIIIIJIIIJJJIIIJIIIIIIIIJ = 2;
}
