using System.Runtime.CompilerServices;
using Photon;

public class JuggernautMode : MonoBehaviour
{
	private sealed class JIIJJIIIJJIIIJJIIIJIIJIIIJJIJJJJJJIJJIJIJIJJJJJ
	{
		public JuggernautMode JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII;

		internal void IJIIIIJIJIIJIIJJJJIIIJJJIIJIIIJIIJJIIJIJIIIIIJJ()
		{
		}

		internal void IJJIJIIIIIIJJIJIIIIJJJJIIJIJIJIIIIIIIIIJIJIJIJJ()
		{
		}

		internal void JIIIIJIIJIJJJIIJIIJIJIIJIIIIIJIIJIJIJJIIIJIIIII()
		{
		}

		internal void IJJJJIIIIIIIIJJJIIIJJJJJIJJIIJIJIIJIIIIJIJIIJIJ()
		{
		}

		internal void JJJJJJJJIJIJIIIJIJIJJIIJIJJJIIIJIJJJIJJIJJJIJII()
		{
		}

		internal void IIJJJJIJIJIJIJJJJIJJIIJJJJJJIJJIIIIIJIIIIIJJIII()
		{
		}

		internal void JIJIJIIIJJIIJIIJJIIJJJIJIJIJIIIIJIIJIIJJJIIJIIJ()
		{
		}

		internal void IIJJJIIJIJJIIIIJJIIIJIIIJIIJJJIJJIJJJJJIJJIIIJI()
		{
		}

		internal void JIJIJJJJJJIJJIIIIIIJJIIJJIJIIIIJJJJIJJJJJIJJJIJ()
		{
		}

		internal void IJJJJJJIIIJIIJIJJJIJJIJJIIJIJIJIJJJIIIIJJJIIIII()
		{
		}

		internal void JIJIIIIIJIJIJJIIJIIJIJIIJJIIJJJJJIJIIJJIIIIJIIJ()
		{
		}

		internal void JIJIIIJIIIJIIJJJJJJJJJJIIIIIIJJJIIIIJIJIIIIJJIJ()
		{
		}

		internal void IJIJJIJJIJJIJIJJJJIIIIIJJJIJJIJJIJIIIJIIIIJIIII()
		{
		}

		internal void IJIJJIIJIJIIIJIIIJIIIJIJIIIJJJIJIIIJIJIIIJJJJIJ()
		{
		}

		internal void IIJIJIIIIIIJIIJIJJIJIIIJIJIIJIIIIIIJIIJIIIIIIJJ()
		{
		}
	}

	private sealed class JJIIIIJJIIJIIJIJIIJJIJJIIJIIJJIJJJJIJJJJIIJIJJI
	{
		public float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

		public double JIJJIJIIJIIJIJJJIIIJIIJJJJIIIIJJJIIJJJIIJIJIJJJ;

		public JuggernautMode JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		internal void JIJJIJJJJJJJJJIJJJJJJJJIIJJIIJJJJJJIIIJJIJIJIJJ()
		{
		}

		internal void IJIJIIJJJIJJIIIJJJIJJJIJIIIJJIIIIIJIJIIIIJJJJII()
		{
		}

		internal void IJJJIIJIJJIIJJIIIIIJJJJJIJIIJIIIJJIIIIIIIIJJIJJ()
		{
		}

		internal void IIIJJJJIJIIJIIIJIIIJJIIIJIJIIJIIJJJJIJIJIJJIJJI()
		{
		}

		internal void JIIIIJJJIJJIIJJJIIJIIIJIIJIIJJIJIIIIJIIIIIIIIJI()
		{
		}

		internal void JJIJIJIIIIJJJJJJIJJIIIIIJIJJIIJIJIIJJIIJIIJIIII()
		{
		}

		internal void IIJJJJJJJIJJJJIJJIJIIIJIJJJJIJIJIJJIIIJJIIJJIIJ()
		{
		}

		internal void IJJJJIIJJJJJJJIJIIIJJIJIIJJJJJJJJJJIIJJJIIIJJIJ()
		{
		}

		internal void IJJIIJIIJJJIJIIIIJIIIIIIIJJIIJJJJJIIIIJJJIIIJJI()
		{
		}

		internal void IJIIJJJIIIIIJIIIIJJIIIJIIJJIJJIJJIJIIIJIJJJJJJJ()
		{
		}

		internal void IJJIJIIIJIIJIJIJIJJIJJJIJJJIIJJIJJJIJJJIIIJJIIJ()
		{
		}

		internal void JJJIIIIJIJJJIJJJIIJIIJJIJIIIJIIIIIJJIJJJJJJJJIJ()
		{
		}

		internal void JIJIJIJIIIIJIIIIIJIIIIIIIIJIIIIJIIIIJIJIJJIJIII()
		{
		}

		internal void IJIJJJJIIIJJJIJJJJIIIJIJIJIJIJJIJIIJJIIIIJJJJII()
		{
		}

		internal void IIIIIJIIJIIJIIIJIIIJIIIIIJIIIIJIIJIJJJJJIJJIIIJ()
		{
		}

		internal void JJIIJJIJJIIJJJJJIJIJIIIIIIJJJIIIIIIIIIJIJIJJJII()
		{
		}

		internal void IIIIJJIIIIJIIIIJIJIJJIIJJIIIIIJIJIIIIIIIIIJIJJI()
		{
		}

		internal void JJJIJIIIIIJJJIJIIJIJJIJJIIJJIIIJIIIJIIJJIIIIIIJ()
		{
		}

		internal void JIIIJIIIJJIJIJIIJIJIJJJIJIJIIJJJIJJIIIJIIJIJIII()
		{
		}

		internal void IIIJJJIJIIIJJJIIIIIJJJIIIJIJJJJJJJIJJIIIJIJIJJJ()
		{
		}

		internal void JIIJIJJJIJIIJJIIIIIJJIJJIIIIJJIIJIJIIJIIJJIIJII()
		{
		}
	}

	private sealed class JIIJJJJIJJIJIJIIJIJIIIIIIIIIJJJJIJIIIIIIJIIIJIJ
	{
		public PlayerInput IJIIJJJJIJIJJJJIJIJJJJIJIIIIJIIIJIJJIJJIJJIIIIJ;

		internal void IJIJJJJIJIJIJJIJIIIIIIJIJJJJIIJIIIIJIJIJIIJIIII()
		{
		}

		internal void IIIJIIJIIIIJJJIJJJIIIJIJJJJIIIIJIJJIJJIIJIIJIII()
		{
		}

		internal void IIJJIJIJJJJIIJIJJIIIIJIIIIJJJJJIIIJJIIIJJIIIJJJ()
		{
		}

		internal void IJIJIIJJIJJJJIJIJJIIIJJJIJIJJJJJJJJIIIIIIIIIIJJ()
		{
		}

		internal void JJIJJJIIIIJJIJIIJJJJJIIJJJJJIJJIIIIJJIIIIJIJJII()
		{
		}

		internal void JIJIJJIIJJJJJJJIJIJJJJIIIIJJJIIJIJJIIIIIIJJIIII()
		{
		}

		internal void IIIJIIIIIIJJIJJJIIJIIIIJJIJJJIIJJIJJJIJJIJJJIJI()
		{
		}

		internal void JIIJJJJJIIIJJJJIJIJIIIJIJIIIIIJJIJIJIJIIJJJIIJJ()
		{
		}

		internal void JJIJIJIIJJIIIIIIJJJJIIJIJJIJJJIJJJJIJJIJIIIJJJJ()
		{
		}

		internal void IIJIJIIJJJJIIIIIJIIIIIIJIJIIIIJJJJIIIIJIIIIJIIJ()
		{
		}

		internal void IJIIJJJIIJJIJIIIIJJJJIIIJJJIIIJIIJJJIIIIIJJIJJI()
		{
		}

		internal void IJJJIJJIJIJIIIJIIJJIIIIIIIIJIIJJIJJJIJJJIJIIIJI()
		{
		}

		internal void IJIJIJJIJIJIIIIIJIJIJIIIIJIJJIIIIJIJJJJJIJJIIIJ()
		{
		}
	}

	private int JJIIIJIJIIJIJIJJIIJIIJJIIJJJJJJJJIJIJIJJJJIJJIJ;

	private void JJJIIJIJJJIIIJIJJIJIJJIJJIJIJJJIJJIJIJJIIJIJJIJ()
	{
	}

	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII()
	{
	}

	private void Awake()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnEnable()
	{
	}

	private void IIJIIIJJJJJJJJIJJJJIJJJIJIJIJIIIIIIIJJJIIIIJIJI()
	{
	}

	private void IJIJIJJIJJJIIJJIJJJJJIIJJIJIIIIJIIJIIJIJJJJJJJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIIIIJIIIIIJJJJJIJJIIIJIJIJIIIJIJJJIJJIJJIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void JJJIJIJIJIJJIIJIIJIJJJJIJIIJJJJIJIIJIIJJJJJIIIJ()
	{
	}

	[CompilerGenerated]
	private void IIIJIJIJIJIJIJIIJJIJIJIIIJIIIJIJJJJJJIJIIIIIJIJ()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void OnDisable()
	{
	}

	private void JJIIIJIIJJIIIJIIJIIIJJIIIIJJJIIJJJJJIIJJJIIIJIJ()
	{
	}

	[CompilerGenerated]
	private void IJJIIJJJJJJIJIIJIIJJIJIIJIJIIJJJIIIIIJIJIIJIJIJ()
	{
	}

	private void JJIIIJJJJJIJJIJJJIJJIIJJIIIIIIIJIIIIJJIJIJJJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJIIJJJJJJIIIIJJJIJIIJIIJIJIJIIIIIIJJIJIJIJIJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJJJIIIIJIIIIIJJIIJIIIJIJJJJJJJJJIIJIIIIIIJIJJ()
	{
	}

	private void Start()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJJIJIIJIJIJIIJIIJJJJJIJJJIIJJIJJJIJJIIIJIIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIIIIIJIIIJIIJIIIIIIJIJJJJJIJIJIJJJIJIJIJIIJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIJIJJIIIJJIJIIJJIJIIIJIJJIJIIIIIJIJJJIIJIJIIJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJJIIJIIJIIIIIIJIIIIIIJIIIJIJJJIIJJJIJIJJJJIJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJJIIJJJJIJJJJIIIJJJJJIIJIJJJIJIIIJIJJJIIIIIJI(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII()
	{
	}

	private void IJJIJIJIJIJIJJIIIIJJIJIIIIIIIIIIIJJIJIIIJIIJIII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void IIIJJJJIIIIIJIJJIJJIIIJJIIJJJIIJIIIJJIIIIIIJIII()
	{
	}

	private void IIJJIIJJJIIIJJIIJJJIIIIIIJJJIIJJJJJIIJJJJIIIJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJJJJIIIIIJJIIJIIJJJJIIJJJJJJIJJJJIIJJIJJIJIJI(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private bool JJJIJIJIIIIIIIIIJIIIJJIIJJIJJJIIIJJIIIIJJJJJJJJ()
	{
		return false;
	}

	[CompilerGenerated]
	private void IIIIJIIJIJJIIJJIJJJJJJJJIIJIJJIJJIIIJJIIIIJIIII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIIIJIIIJJJJJJIJIIIIJJJJIIJIIIJJIJIJIIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIIIJIJIJIIJIIIIJIJJIIIIIIIIJJJJIIJIJJJJIIJIII()
	{
	}

	private void IJJJJJIIIJJIJJIIJIIJIJIJJIJJIJIJIIJJJJJJIJIIJII()
	{
	}

	private void JJJJJJIIJIJJIJJJIJJJIJIJJIJJIJIIIJIIJIJJIIIJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIIIIJIJJIIIIIIIJJIIJJJJIIJJJJJJIIJIJJJJIIIIJJ()
	{
	}

	private void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}
}
