using System.Runtime.CompilerServices;
using Photon;

public class KingHillMode : MonoBehaviour
{
	private sealed class JIJJIIIJIIJIIIJJIJJIIJIIIIJIIIIJIIJJIIIJIIIIIJJ
	{
		public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII;

		internal void IJJIJJJIJJJJJIJIIIJIJJIIJJIIIIJJIIIIJJIJJIIJJJJ()
		{
		}

		internal void IJJJJIIIIIIIIJJJIIIJJJJJIJJIIJIJIIJIIIIJIJIIJIJ()
		{
		}

		internal void IIJJJJIJIJIJIJJJJIJJIIJJJJJJIJJIIIIIJIIIIIJJIII()
		{
		}

		internal void IJIJJIIJIJIIIJIIIJIIIJIJIIIJJJIJIIIJIJIIIJJJJIJ()
		{
		}

		internal void JIJIJIIIJJIIJIIJJIIJJJIJIJIJIIIIJIIJIIJJJIIJIIJ()
		{
		}

		internal void IIJJJIIJIJJIIIIJJIIIJIIIJIIJJJIJJIJJJJJIJJIIIJI()
		{
		}

		internal void JIJIIIJIIIJIIJJJJJJJJJJIIIIIIJJJIIIIJIJIIIIJJIJ()
		{
		}

		internal void JJJJJJJJIJIJIIIJIJIJJIIJIJJJIIIJIJJJIJJIJJJIJII()
		{
		}

		internal void IJJJJJIIJIJJIJJJJIIJIJIIIIJJIJIIIJIJIJJIJJIJJIJ()
		{
		}

		internal void IJIJJIJJIJJIJIJJJJIIIIIJJJIJJIJJIJIIIJIIIIJIIII()
		{
		}

		internal void IJJIJIIIIIIJJIJIIIIJJJJIIJIJIJIIIIIIIIIJIJIJIJJ()
		{
		}

		internal void JIIIIJIIJIJJJIIJIIJIJIIJIIIIIJIIJIJIJJIIIJIIIII()
		{
		}

		internal void IIJIJIIIIIIJIIJIJJIJIIIJIJIIJIIIIIIJIIJIIIIIIJJ()
		{
		}

		internal void IJIIIIJIJIIJIIJJJJIIIJJJIIJIIIJIIJJIIJIJIIIIIJJ()
		{
		}

		internal void IJJJJJJIIIJIIJIJJJIJJIJJIIJIJIJIJJJIIIIJJJIIIII()
		{
		}

		internal void JIJIIIIIJIJIJJIIJIIJIJIIJJIIJJJJJIJIIJJIIIIJIIJ()
		{
		}

		internal void JIJIJJJJJJIJJIIIIIIJJIIJJIJIIIIJJJJIJJJJJIJJJIJ()
		{
		}
	}

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IIIJIJIIJIJJIJJJIJJIIJJIIIJIJIJIJJJIJJIJIJJIIII;

	private bool JIIJJJIIIIJIJIIJJJJJJJJIJJIIJIIIIJJIJJIJJIJIJIJ;

	private static KingHillMode JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void JIIJJIIJJJJJJJIIIJJIJIJIIJIIIIJIIJJIJJJJJIJJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIJIIIIJJJIJIJJIJJIJIJIIJIJJIJJJJJJJIIIIJJJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJIIIIJJIJJIJJJIIIIIJJJJJIIIJJIIJIIJJJIJIJJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIIIJIIIJJJJJJIJIIIIJJJJIIJIIIJJIJIJIIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJIJIIJJIIJJJIIIJJIIIJJJIJJIIJJIIIJIIJJIJIJJJJ()
	{
	}

	private void IJIJJJIJJJIJJJJJIJJIJIIJIJIIJIIJJIIIJIIIIIIJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJIIJIIIJIJIJJIJIJJIJIIJJJIIIIJJIIJIIJJJJJJIJI(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private void OnEnable()
	{
	}

	private void JJJIJJJIJIJJJJIJJJJIIIIJJIIIJJJIJJJIIJJIJJIIJII(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIJJIIIIIJJJJJIJIJJIIIIIIIJJIJJJJJIJIIIJIJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void Start()
	{
	}

	private void OnDisable()
	{
	}

	private void JJJIJJJJJIIIJJIIJIJIIIJIJJJIJJJIIJIIIJIIJIIJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJIJIJJIIIIJJJJIIJIIIJJJJJIJIJIIJJIIIIJJIJIIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIIJJJIJIJJJJIIIJIJJIIIJIIJIIIIJJJIIIIIIJIJIJIJ()
	{
	}

	private void IIIIIJIIJJJIIJJIIIIIIIJJIIJIJJJIIJJJJIIIIIJJJIJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void Awake()
	{
	}

	private void IJIJIJJIJJJIIJJIJJJJJIIJJIJIIIIJIIJIIJIJJJJJJJI()
	{
	}

	private void JIJJIIIJJIJIIIIIJIIJIIIIJJJIJIIIIJJJJJJJJIIIIIJ()
	{
	}

	private void JJIIIJIIIIIIIIIJIJIIJIIIJIIIJIIJJIIJIIIIIJJJIJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	[CompilerGenerated]
	private void IJIIIJIIJIIIJIJJIJIJJJIJIJJIIIJIIJJIJIJIIJJJIJJ()
	{
	}

	[CompilerGenerated]
	private void IIJJJJJIIIIIJJIIIJIJIIIJJJJIIIIIJIIIJIIIJIJJJJJ()
	{
	}

	private JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII[] IJJIIJIIIIJJIIJJIIIIJIJJIIJJIIIIIIIIJIIJIIJJJII()
	{
		return null;
	}

	private void IJJJIIIJIJIJIJJJIIIIJJIIJIJJIJJIIJJJIIJJJIJIJII()
	{
	}

	private void JIIJJIJIIIIIIIIIIJJIIJIJJJIIIIIIIJIIIJIIIJIJJII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	public static void IIJJJJIIJIJIJIJJIJJIJJJJIIJJJJJJIJJIIJIJIIIIJIJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII[] IJJIJJJIJJJIIJJIIIJIIIIIIIJIIJJJIJJIIJIJIIIIIJJ()
	{
		return null;
	}

	private void JIIJIIIIIJIJIIJIIJJJIIJIIJJJIIIIJIJIJJJJJIIIIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJIIIJJJIIJIIIIIJJIJIJJJJIIIIJIIIIIJJJJIIJIJIIJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void JJIJIIIIJJJIJJIJIIIIIJJJIIJJJJIJJJIJJIIIJJIJIJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void IJIIIJIIIIIJJJIJIIIJJIJIJIIJIIJJIJIIJJJJJJIIJJJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}
}
