using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class LODObject : MonoBehaviour
{
	public bool IJIJJIJIIIJJJJIJJIJIJJIIJIJIJJJIIJJIIJIIJJJJJJI;

	public Renderer[] JIJJIJJIJIIJIJIIIJIJJIIJJJIJJJJJJIIIIIIIIJJJJIJ;

	public Renderer[] JJJIJIJJJJJJIJIIJIIIIJIJJIJJJIJIJJIIJJJJJIJJIJJ;

	private bool IIIJJJJIJJJIJJJIJIIIIIIIJIIJIIJIJIJJJIIJJJIIJII;

	private Transform JJIJIIJIIJJJJJIIIJIIIJJJIJJJIIIIJJIJJJIIIJJIIII;

	private int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ;

	public nTimer IIIIIJIIJIJIIIIJIJIJJIIIJIJJIJJIJIIJJJIJIJIJJJJ;

	public static bool IIIJIIJJIJIJIIIJJJIJJJIIJJIIJIJIIIIIJIIJIJIIJJJ;

	private static float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ;

	public static Transform IIJJJIIJIJIIJIIJJJJJIIIJJIIJJIIIJIIJJJIJJJJIIJI;

	private Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();
	private Transform IJJJJIJIIIJJJIIIJIIIJJIIJJJIIIJIJIJIJJIIJIJJIJJ()
	{
		return null;
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	public static void IJIJIJIJJJJJJIJIJIJIIIIJJIIIJIJIIJIJIIJIJJIIJJI(float JIJJJIIIJJIJIJIJJJJIJIIIJJIIJJJIJIIJJIIIJJJJIJJ)
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	private void IIIJJJIJJJIJIIIJJJIIJIJJJJIIJIJIIJIJJJIJIJJJJJJ()
	{
	}

	public static void JJIIIIJIIIIIJJIIIJJIJJJJJIJIJIIJJJJIJJJIIIJIIIJ(float JIJJJIIIJJIJIJIJJJJIJIIIJJIIJJJIJIIJJIIIJJJJIJJ)
	{
	}

	public static void IIIJIIIIJIJIIIIIIIJJIJIJIIJJJJJJIJIIIIIJJJIJJJJ(float JIJJJIIIJJIJIJIJJJJIJIIIJJIIJJJIJIIJJIIIJJJJIJJ)
	{
	}

	public static void JIIIIJJJIJIJJJJIJJIJIJIIIJIJIIIJIIJIJIJJJIIIIJI(float JIJJJIIIJJIJIJIJJJJIJIIIJJIIJJJIJIIJJIIIJJJJIJJ)
	{
	}

	public static void JIJJJJIJJJIJJIIIJJIIJJJJJJIJIJJJIIIIJIJJJJJJIJJ(float JIJJJIIIJJIJIJIJJJJIJIIIJJIIJJJIJIIJJIIIJJJJIJJ)
	{
	}

	private Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}

	public static void JJJIIJJJJJIJJJIIIIIJIIIJIIJJIIIIIIJIJIJJJIJJJJI(float JIJJJIIIJJIJIJIJJJJIJIIIJJIIJJJIJIIJJIIIJJJJIJJ)
	{
	}

	public static void JIJJJIJIIJIJIJJIJIIIIJIIJJIIIJJIIJIJIIIIIIIJJIJ(float JIJJJIIIJJIJIJIJJJJIJIIIJJIIJJJIJIIJJIIIJJJJIJJ)
	{
	}

	private void JJJIJIJIIIIJJJIIJIIJIJJIIIJIJJIIIJIIIIJJIJIJJJJ()
	{
	}

	private void JIIIIJIIIIJJJJIIIIJIJIIJJJJJJJJIIJJIIJJIJJIJIII()
	{
	}

	public static void JJIIIIIIJIJJJJIIJIIJJIIIJIIJJIIJJIIIIIJJIIJIJII(float JIJJJIIIJJIJIJIJJJJIJIIIJJIIJJJIJIIJJIIIJJJJIJJ)
	{
	}

	private void JJJIJIJJJIIIJIIIJJJJIJJIJJJJIIJJIJJIIIIIJIIIJJI()
	{
	}

	private void JJIIIJIIIJJIIJJIJIIJIIIIJJIIJJJIIIJJJIIIIIJIJJI()
	{
	}

	private void JIIJJJIIIJIJIJJIIIJJIJIJIIIIIIIIIJJJIIIJJJJJIII()
	{
	}
	private Transform IIIJJIJJJIIJJIIIJJJIJJIJJJIIIJIJIIIJIIIIIIIIIIJ()
	{
		return null;
	}

	private void Start()
	{
	}
}
