#pragma warning disable 0618
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class Logo : MonoBehaviour
{
	private sealed class IJIIIJJJIJIIIIJIJJIIJIIIIIIIIIIIIIIIIIJIJIJJIII : IEnumerator<object>, IEnumerator, IDisposable
	{
		private int IJJJJJJJJIIJIIIIIJIIJJJIJJIIJIJJJJJIJJJJJIIIIII;

		private object IJJJJJIIIJJIIIIIIJIIIJIJJJIJIJIIJJIJIIIJJIIIJIJ;

		public Logo JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		object IEnumerator<object>.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		object IEnumerator.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		[DebuggerHidden]
		void IEnumerator.Reset()
		{
		}
		private object JJJJIJIJJIIIJJJIIIJJJJIJJIIJJIIJIIJJJIIIIIIIIJI()
		{
			return null;
		}

		[DebuggerHidden]
		public IJIIIJJJIJIIIIJIJJIIJIIIIIIIIIIIIIIIIIJIJIJJIII(int IJJJJJJJJIIJIIIIIJIIJJJIJJIIJIJJJJJIJJJJJIIIIII)
		{
		}

		private bool MoveNext()
		{
			return false;
		}

		bool IEnumerator.MoveNext()
		{
			//ILSpy generated this explicit interface implementation from .override directive in MoveNext
			return this.MoveNext();
		}

		[DebuggerHidden]
		void IDisposable.Dispose()
		{
		}
		private object IJIIIJJIJJJIJIIIJJJJIIJJJJIIJJIIJIIIJIJIIJIJIJJ()
		{
			return null;
		}

		private void JIIIJJIIIIIIJIJIJIIJJIIIIJIJIIIJJIJIJJIIIIJIIJJ()
		{
		}
		private object JIIJJJJJJIJJJIIIJJJIIJJIIJIIIJIIJIJIJIJIJJJIIJI()
		{
			return null;
		}

		private bool IIIJIIIJIIIJJIIJJJIJIJIIJJJJIJIIIJJIJIJIJIIIIJI()
		{
			return false;
		}

		private void JIIJJIJIIIIJIIJJIIIIJIIIIIIJJJJJJJJIJIJJIJJIJJJ()
		{
		}
		private object IIIJJIJIIJJJJJIJIJJIIIIIJIJIIJIJJIJIIIJIJIIIIJJ()
		{
			return null;
		}

		private void JJIIJIJJJJIIIIIIJIIJJJJJJJJIIJIJJJIJIJJJJIIJIJI()
		{
		}

		private void JJJJIJIJJIJJJIJIIIIJJJJIJIJJIIIIJJIJIIIIJIJJJII()
		{
		}

		private bool JIIIJJJIIJIIIJIJJJIJIJJIJIJJJIIIIJIJJIIIIJIJIJJ()
		{
			return false;
		}
	}

	private sealed class IJJJIIIJJJJIJIIIIIIJIIJIIIJIJIIJIIIJIIJIJJJIJIJ : IEnumerator<object>, IEnumerator, IDisposable
	{
		private int IJJJJJJJJIIJIIIIIJIIJJJIJJIIJIJJJJJIJJJJJIIIIII;

		private object IJJJJJIIIJJIIIIIIJIIIJIJJJIJIJIIJJIJIIIJJIIIJIJ;

		public string IJJJJIJIJJIIIIIJJJIJJIIJJJJIIIIJJIJIIIIIIIJIIIJ;

		public string IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ;

		public Logo JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		private WWW IJJJJIJIIIIJJJJIIIJJIIJIIJIIJIJJJIIIIIIJIIIIJII;

		object IEnumerator<object>.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		object IEnumerator.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		private void JIIJIJJIIIIIJIIJJJJJJJJJIJIJJJIJIJIJIIJJJJIIJIJ()
		{
		}

		private void JIIJJJJJJJIJJIJJJIIIIIJJJIIJIIIIJJIJIJJJIIJJIJJ()
		{
		}

		[DebuggerHidden]
		public IJJJIIIJJJJIJIIIIIIJIIJIIIJIJIIJIIIJIIJIJJJIJIJ(int IJJJJJJJJIIJIIIIIJIIJJJIJJIIJIJJJJJIJJJJJIIIIII)
		{
		}

		private bool JJIIIJJJJIIIJJJJIJIJJIIJIJJJIJJIIJIJJJIIIJJJIIJ()
		{
			return false;
		}

		private void IIJJJIJJJIJIJIJIIIIIIIJJIIIJJJIIJJJIJJJIJIJIJJJ()
		{
		}
		private object IJIIJJIJJJIJJIIIJJIJIJJJJJIJJIJJIJIIJIIIJJJIJIJ()
		{
			return null;
		}
		private object JIJIJIJJJJJIJJJJIIJJJJJJJJJJIJJJIIIJJJJIIIIJJJI()
		{
			return null;
		}

		private void JJJJJIJJJJJJJJIJJJJJJIIIJJJJIJJIJJJJJIIJJIIJIIJ()
		{
		}

		private bool JJJJIJJJJJIJIJJJIJIJJJJIJJJJJJIIIJIJJJJIJIIJIII()
		{
			return false;
		}

		private bool MoveNext()
		{
			return false;
		}

		bool IEnumerator.MoveNext()
		{
			//ILSpy generated this explicit interface implementation from .override directive in MoveNext
			return this.MoveNext();
		}

		private bool JIIIIJIJIJJJIJJIJIJIJIJIIIJIJIIIIJJIJJJJJIJIJII()
		{
			return false;
		}

		private void IIJJJJJIJJJJIJIIJJIIIJJIJIJIJIIJJJIJIIJIIIJJJIJ()
		{
		}
		private object JJJJJJJIIJJJIJJIJIIIIIJIJIIIIIJJJIIJIIIJJJIJIII()
		{
			return null;
		}
		private object IJIJIJIJIJJJIIIIIJJIJJIJJJJJJIIIJIIJIJIIIJIIJII()
		{
			return null;
		}

		private void IIJJJJJIJIIJIJIIIIJJIIJJJJJIIJIJJIJJIJJIJJIIJJI()
		{
		}

		private void JJIIJJJJIJIJJIJIJJIIJJIJJJJJJIIJJJJJIJJJJIIJJIJ()
		{
		}

		[DebuggerHidden]
		void IDisposable.Dispose()
		{
		}
		private object JJIIJIJIJIIJIJJIIJJJIJIIJIJIIIIIIJIJJJJIJIIJIJI()
		{
			return null;
		}
		private object IJIIIJIIIIIJJJIJIIIIJIJJIIJJJJJJJIJJJIIJIIIIJII()
		{
			return null;
		}

		[DebuggerHidden]
		void IEnumerator.Reset()
		{
		}

		private void IJJJJJIIJJIJJIJJJJIIIIJIJIJIJIIJJJJJJIIJIIIIIIJ()
		{
		}

		private void JJIJIJIJIJJIIIJJIIJJIJIIJIJIJIIIIIIIIJIJIIIIIII()
		{
		}
		private object JIJIJJJIJJIJJJJJJJIIIJIIIIJIJJJIJIIJIJIIJIJJIJJ()
		{
			return null;
		}

		private void IJIIJJIIJIJJJIIIIIIIIJIJJJJJJJJJJIJJIIJJJJJJJII()
		{
		}
	}

	public UILabel IIJJJJIJIJJJJIJJJIIIJJJIIJJIJJIJJJJIJJIIJJIIIJJ;

	public UILabel JIIIJIJJJJIJJJIJIJIJJIJIIIJIIJIJIJJIJJJJIIIIJIJ;

	public List<IJIJJIJIIIIJIJIJJIIJIIJJIIIIIJJJJJIIIIIIIJJJIII> IIJIIJJJJIIJJIJIIIIIJIIIIJJJJJIIIIIJJJJJJJIIJJI;

	public IJIJJIJIIIIJIJIJJIIJIIJJIIIIIJJJJJIIIIIIIJJJIII[] JIIJJIJJIIJJIIIIJIJJIJIIIIIIIIIIIJJJIIIIIJJJIII;

	public static List<IJIJJIJIIIIJIJIJJIIJIIJJIIIIIJJJJJIIIIIIIJJJIII> JJJIJIJJIJIIIJJIIJIJIIJIJJJIIIJIJJJIIIIJJJIIJIJ;

	private IEnumerator IIIIIJIIIIJIIJJJJIJJJIJJJJIIJIJIIJIIIJJJJJIJJJJ(string IJJJJIJIJJIIIIIJJJIJJIIJJJJIIIIJJIJIIIIIIIJIIIJ, string IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return null;
	}

	private void JIJJIIJIIJJIIIIJIJIIIJIJJIIIIIJJJIIIJIIJJIIJJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIIIIJIJJIJJJIIJIIIIIIIIJJJJJJIIJJIIIJJJI)
	{
	}

	private IEnumerator IIJJIIJJIJJJIJJIIJJIIIJJJJIIIIIJJJJIJIIJIJJIIJJ(string IJJJJIJIJJIIIIIJJJIJJIIJJJJIIIIJJIJIIIIIIIJIIIJ, string IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return null;
	}

	private void Start()
	{
	}

	private IEnumerator IIJJIIJJIJJJIJJIIJJIIIJJJJIIIIIJJJJIJIIJIJJIIJJ()
	{
		return null;
	}

	private bool IIJIIIIIJJIJIIIJJIJJJJJJJIJIIJIIIIJJIIJIJJJIJIJ()
	{
		return false;
	}

	private void IIIJJIJIIIIJIJIJJJJJIIJJIJIJIIIIIJJJIJIJJIJIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private IEnumerator IIJIJJIJIIJJJJJJIJIIIIIJJJJIIIIIIJIJJJJJJJIIJII(string IJJJJIJIJJIIIIIJJJIJJIIJJJJIIIIJJIJIIIIIIIJIIIJ, string IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return null;
	}

	private void JJIJIJJJJIIJIIIJJIIIIJJIIIIIJJIIJIIIJIIJJIIJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private bool JIIJJIJIJJJJJIJJIJJIIJJJJJJJJIJIJIIJJIIIJJJIIII()
	{
		return false;
	}

	private bool IJIJJJJJIJJIJIIJJJIJIIIJIJIIIJJIJIJIIJJIJIIIIJI(string IIJIJIIIIIJJIIIJJIIJJJIJJIIJJIJJJIIIIJJIJJIIJIJ, string IIIJJIJIJJJJJIIIIJIJJIJIIIJJJJJJIJIJIIJJJJIIIJJ)
	{
		return false;
	}

	private void IIIJJIJIIIIJIJIJJJJJIIJJIJIJIIIIIJJJIJIJJIJIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIIIIJIJJIJJJIIJIIIIIIIIJJJJJJIIJJIIIJJJI)
	{
	}

	private bool JIJJJJJJJIJJIJIJJJJIIIIJJIIJIIIJIIIJIIJIIIJIJIJ(string IIJIJIIIIIJJIIIJJIIJJJIJJIIJJIJJJIIIIJJIJJIIJIJ, string IIIJJIJIJJJJJIIIIJIJJIJIIIJJJJJJIJIJIIJJJJIIIJJ)
	{
		return false;
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private bool IJIIIIJIIIIJJIJJIIJIIIIIJJJIJJJJIJIJJJIIIIIIJJJ(string IIJIJIIIIIJJIIIJJIIJJJIJJIIJJIJJJIIIIJJIJJIIJIJ, string IIIJJIJIJJJJJIIIIJIJJIJIIIJJJJJJIJIJIIJJJJIIIJJ)
	{
		return false;
	}

	private IEnumerator JJJIJJIIIIIIJJIJIJJJJIIJJIIJIJIJIJJJJIJJIJIIIIJ()
	{
		return null;
	}

	private IEnumerator JJIJIIJIIJIJJIJJIJJIJIIIIIJJJJIJJJIIIIIJJJJIIII()
	{
		return null;
	}

	private bool JIIIIIJJJJIJJIJJJJIIJIIJIJJIJJIIIJIJIJJJIJJIIIJ()
	{
		return false;
	}

	private bool JJJJIIJJJIJJJJJJIJJJJIIJIIIIJJJIJIJIJIJIIIIIIIJ()
	{
		return false;
	}

	private bool JIJIJIIIJIJJJIJJJJJJIIJIIJJJJJJJJIJJIJJJIIJIIJI()
	{
		return false;
	}

	private bool JJIJIJIIIIIIIIIIIIIJJIJJIJIIJJJIIIIJIJIIIIJIJJJ()
	{
		return false;
	}

	private bool JIIIIIJIJIJIIIJIIIIIIIIJJJIIIJJJJIIJJIJIIIJJJJI()
	{
		return false;
	}
}
