using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;
using UnityEngine;

public class Loom : MonoBehaviour
{
	[StructLayout((LayoutKind)0, Size = 8)]
	public struct JJIJIJIIJIIIIIJJIJIIJJIJJIIJIIJIJJJIIJIJIIIJIJI
	{
		public float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

		public Action IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ;
	}

	public static int JJJJJIIJJJJJIJJIJJIIIJIJJJIJIJIIJIJIJIJJIIIIIJJ;

	private static int IIIIJJIIJJJIIJJIJJIIJJIJIIJJIJJIIIIIJJJIIJIIIIJ;

	private static Loom JJIIIIJJIJIJIJJIJJIJJJJJJIIJJJJJIJIJJJIJJJJIIJI;

	private int JIJJJIJIJJIJJIIIIJIJIIJJJJJJJIIJJJJIIJJJJJIJIIJ;

	private static bool IJJIJJIIJJJJIIJJIIJJJIJJJJJIJIIJJIJJJIJJJJIJIJJ;

	private List<Action> IJIJJIJJJIIJIJJIJIJIIIIIIJIIJIJIJIJIJJJIJIJJIII;

	private List<JJIJIJIIJIIIIIJJIJIIJJIJJIIJIIJIJJJIIJIJIIIJIJI> JJJJIIJJJJJIJIIJJIIJJJIJJJJJIIJJJJJJIJIJJIIJJIJ;

	private List<JJIJIJIIJIIIIIJJIJIIJJIJJIIJIIJIJJJIIJIJIIIJIJI> IJJJJJJIJJIJIIJJJJIIIIIJJIIIIIIJIIJJIJIIIIIIJJJ;

	private List<Action> IJJIJIJIJJJJIJJJIJIIIIJJJJIJIJJIIJJIJIIIIIIJIJI;

	public static Loom JIJIIIJJIIJJIIIJIJIJJJIIJIIIJJIIJJIIJIIIIJIJIIJ => IIIJJIJJJIJIIJIJIIIIJJIIIJJIIIIIJIJJJIJIJIIIJJI();

	public static void IIJJIIJIJIJIJJJIIIJIJJIJIJIJIIJIIJIIIIJIJJJJJII(Action IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ)
	{
	}

	private void Awake()
	{
	}

	private static void IJJJIIIJIIIJJJJIIIIJIIIIJIJIIJIJIIJJIJIJIIIJJJI(object IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ)
	{
	}

	public static void JIIIJJIIIIJJIIJJJJIIJIIJJIIJIIJIJJJIIIIJJJJJIJI(Action IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ)
	{
	}

	public static void JJIIJJJJJJIIIJJIIIIIJIIIJJJJIIIJIIIIJJIJJIIJIII(Action IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ)
	{
	}

	private static void JIJJJJIJJJIJJJIJJJIIIIIJIIIJJIIJJIJJIJJJJIIJIJI()
	{
	}

	private static void IIIIIIJIJJJJJJIJJIJIIIIIIIJIJIIJIJIJIIIJJIJIJII(object IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ)
	{
	}

	public static Thread IJIJIJIIJIJIJIIJIIJIJIIJJJIIIJJIIIJJIIJJIIIIIIJ(Action IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ)
	{
		return null;
	}

	private static void IIIJIIJJJJIJIJJIJIIIIJIJJJJIIIIJIIIIJIIIJJJJIJJ()
	{
	}

	public static Thread JIIJIJIIJIJIJJJIJJJJIJJJIJIIJJJJJIIIIIIJIJJIIII(Action IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ)
	{
		return null;
	}

	private void Update()
	{
	}
	public static Loom JIIIJIIJIJIIIJIJJIJIJJIJIIIIIJIIJJIIJJJJIIIJIJJ()
	{
		return null;
	}

	private void Start()
	{
	}

	public static Loom IIIJJIJJJIJIIJIJIIIIJJIIIJJIIIIIJIJJJIJIJIIIJJI()
	{
		return null;
	}
	public static Loom JIIJJJIJIIIJIJJJIJJJIJJIJIIIJIIIJIJIJJIIJJIIIJJ()
	{
		return null;
	}

	private void OnDisable()
	{
	}

	private void IIIJIJJIJJIJIJIJIJIIIIJIIJJIIIJJJIJJJJIIJIIJIIJ()
	{
	}

	public static void JIIIJJIIIIJJIIJJJJIIJIIJJIIJIIJIJJJIIIIJJJJJIJI(Action IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ, float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
	}

	public static void IJIJJIJIJIIIIJIIJJIIJJIJIJIJJIIJIJIJIIJJIIJIJJJ(Action IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ, float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}
}
