using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mAboutGame : MonoBehaviour
{
	public void Vkontakte()
	{
	}

	public void Discord()
	{
	}

	public void IIIIIJIJIJIJIJIJJJIIJJIJJJJIIIIIJIIJIIJJJJIIIJJ()
	{
	}

	public void IIJIIIIJJJJIIJIJIJJJJIIIJIJIJJJIIJIJIJJIIJIIIII()
	{
	}

	public void JIJJJIIJJJJIIJJIJJIJJJIIJJIJIJJIJJIIIJIIIJJIIII()
	{
	}

	public void IIJIJIIJIIJIIIJJIJJJIIJIJIJIIIJIIIJJJIJIJIJJIIJ()
	{
	}

	public void Facebook()
	{
	}

	public void JIIIJIJIJIJIJJIJIJIIJIJJJIIJJIJIJIJIIJIJIJIJJII()
	{
	}

	public void JJIJIIIJIJIJIJIJIIJIJJJJJIIJIJIJIIIIJIIJJJJIJJI()
	{
	}

	public void JJIIIIJJJIJJIIJIIIJJIJIJJIJIIJIJIJJJIIJIJJJJJIJ()
	{
	}

	public void JIJIJIJJJJJIJJJIJJJJIJIJIJIJIIJIJIIJJJJJJIJIIIJ()
	{
	}

	public void IIJIJJJIJIIIIJJIJIIIIIJIJIIJJJIIIIJIJIIIIIJJIIJ()
	{
	}

	public void Twitter()
	{
	}

	public void Share()
	{
	}

	public void JJJJJIJIIIIIJIJJJJIJJIJIIJIJIJJJJJJIIJJIJJJIIIJ()
	{
	}

	public void JIJIIIJIJJJJIJIJJJJJIIJJIIIIIIJIJIJIIJJJJIIJIII()
	{
	}

	public void JJIJJIIIJIIIIIJIIJIJIIJJIJJIIJJJIIJJIIIIIJJJJIJ()
	{
	}

	public void PrivacyPolicy()
	{
	}

	public void IJIIJIJIIIJJIJIIIIIIJIIJJJIIIJIIJIIJJJIJJJJJIJJ()
	{
	}

	public void YouTube()
	{
	}
}
