using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Google;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mAccount : MonoBehaviour
{
	private sealed class JIJJIIJIIIIJJJJIIIJJJJJIIJJIJIJJJJIIJJJJIJJIJJI
	{
		public mAccount JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public Action<string> IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ;

		internal void JJJIJJJJJIJJJIJJIJJIIIIJJJJJIJIJJIJJIIJJIIJIIII()
		{
		}

		internal void IIJJJIIJIIJJIIIJJIJJJIIIJJJJJJIIJJJJJJIJJIJJJIJ()
		{
		}

		internal void JJJIIJJJIIIIIJJJJIIIIIJJIJIIJJIJJJIJIIJJIJJJJJJ()
		{
		}

		internal void IJIJJIJIIIIIJJJIJJJIIJJJJJJJIIJIJJIIIJIIJJIJIJI()
		{
		}

		internal void IIIJJIJIIJJIIIIJIIIIIIJJJJIJIIIJJIIJJIIJJJJJJJI()
		{
		}

		internal void JIIJJIJIJJJJIJIJIIJJIJIJIIIIIIJIIIJJIJIJIIIIJIJ()
		{
		}

		internal void IJJIJIJIJIJJJJJIJIIJJJIIJJIJIJJIJJIIIJJIJIIIIIJ()
		{
		}

		internal void IJJJJJJJJJJJIJJJJIJJJIJJJIJIJJJJIJIJIJJIJJJIIJI()
		{
		}

		internal void IJJIJIIIJJJJIJIJJIJIIJJIIJIJJJJIIIIIJIIJIIIIJJJ()
		{
		}

		internal void JIJIJJJIIJJJJIIIJIJJJIIJJJIIJIIJJJJIIIJJJIJIIII()
		{
		}

		internal void IJJIJJJIJJIJJJIIJIIJIJIJIIIIJIIJIIJIIJIJJJJIIII()
		{
		}

		internal void IJIIJJJJJJIJIJIJJIJJJIIIJJIJJJJJIIIIJJJJJJJIIIJ()
		{
		}

		internal void IIJJIIJJJIJJJJIJIJJJIIIIJIJJIJIIJJJIJIIJJJJJJIJ()
		{
		}

		internal void JIJIIJJIJIJJIJJIIJIJIJIIIIJIIJIIIIIIJIJJJIIJJJJ()
		{
		}
	}

	public IJIJJIJIIIIJIJIJJIIJIIJJIIIIIJJJJJIIIIIIIJJJIII IJIJJIIIJJJIJIIIJJJJIJJIIJJIJIIIIJIJIIJJIJJJIIJ;

	private bool JJJJJIIIIIJIJJIIIIIIIIIJJJIIJJJIJJIIJIJJIIJJJJI;

	private bool IIJJJIJIJIIIIJIJIJJIIJJIJJIIJJJJJIJIJIJIJIJIJII;

	private void IIJIJJJIJIJIJIJJIIIIJJIIJIJIIIIIIJIJJJJJIIIJJJJ(bool JJIIJJIJIIIIJIIJJIIJJIJIJIIIIIJIJIJJJIJIIJJJIII)
	{
	}

	private void JIJJIIJJIIIJJJJJIJJIIJJJIIIIJIJIJIIIIJIJJIJJJJI(Action<string> IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ)
	{
	}

	private void IJJIJJJJJJIJIJJJIJIJJJJJJIJIJJJIJIJJJIJIJIJIIJJ(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
	}

	[CompilerGenerated]
	private void JJIIJIJJJJJJIJJIIIJIIIIIIIIIJJIIIJJJIJJJIIIIJIJ(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
	}

	private void JIIIIIIIJJIIIJJIIIJJIIIJIIJJJIIJJJJJIJIIIJIJIJJ(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
	}

	private void IJIJIIIJIIIJJIJJJJJJIIJJIJJJIJJIJIJJJIIJJIIJIJJ()
	{
	}

	private void JJIJIJIIIJIJIJJIJIJIIJIIJJJIJJJJJIIJIIJJIIIIJII(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
	}

	private void IJIJJIIIIIIIJJJJIJJIJIIJIIIIIJIIJIJIIIJIJJJIIII()
	{
	}

	private void JIIJJIIIIIIJJJIIIIIJIJJJIJJIIIIIIJIIIJIJJIJIIIJ(string JJIJJIJJIJJJIIJIJIIIJJIIJJIIJJIIJJJIIIIJJIIIIJJ)
	{
	}

	private void JIJIIJIJIIJJJIIJIIIJJIJJIJJIJJIIJIIIIIIJJIIIIJJ()
	{
	}

	private void JIIJJJIIIJIIJIIIIJIIJJIJJJJJJIJIJIJJIJIIIJIIIJJ()
	{
	}

	private void JJJIJIIJIJJJJIJJIIIJIIIIIIJJJIIJIIJIJJIIIJIJJIJ(string JJIJJIJJIJJJIIJIJIIIJJIIJJIIJJIIJJJIIIIJJIIIIJJ)
	{
	}

	[CompilerGenerated]
	private void IIJIJIJJIJJJIIIIJIJIJJJJIJIIIIIJJJJIJJJIIJIJJJI()
	{
	}

	private void IJJIJJIIIIJJIIIJJIJJIJIJIIJJIJIIJJJJIJIIIIIIJJJ()
	{
	}

	private void IJJJIJIJIIIIIIJJIJJIIIIJJIJIIIIJJIIIIJJJJIJJIII()
	{
	}

	[CompilerGenerated]
	private void IIJIJIIJIJIJJIJJIIIJIJIJIJJIIJJJJIJIJJJIJIJJJJI()
	{
	}

	[CompilerGenerated]
	private void IIIJIJJJJJIJIIIIJJIJIJJIJIJJIJIIJIIJIJIIIJIIJII(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
	}

	private void IIJIJIIJJIIJJIJIJIJJJIIIIIJIJJIIJIJJJIIIIJJIIJJ()
	{
	}

	private void IIIJIJJJIIJIIJJJJIIJIJJJJIIJJJIJJJIJIJJJJJJJIII(string JJIJJIJJIJJJIIJIJIIIJJIIJJIIJJIIJJJIIIIJJIIIIJJ)
	{
	}

	private void IJJJJIIJIJJIJIIJIJJIIJIIIJIIIJIJIIJJIIJJJIIJJJI(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
	}

	[CompilerGenerated]
	private void JJIIJIJIIIJIIIIIJIJJIIIJIJIIIJJJIIIJIJIIIJIJJJI(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
	}

	private void IJIJJIJIIJJJJJJIIIJIJIIJIJJJIJJIJJJJIIIIJIJJIII(Task<GoogleSignInUser> JIIJJJIJIIJJJIIIJIIIIJJJJIJIJJIIJIJIJJJIIIIIJJJ)
	{
	}

	private void JIIIJJJIIIIIIJIIJIIJIJIIIIIJJJIIJIIJIIJJIIJIJJJ(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
	}

	[CompilerGenerated]
	private void JIIJIJIIIIIJJIJJJJJJJJIJIIIIJIJIIJIIIJIJIIIIIJJ(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
	}

	private void Start()
	{
	}

	private void JJIIIJJIIIIJJIIJIIJIIIJJIJJIJIIJJJJIIIJJIIIJIJI()
	{
	}

	private void JIIJJJIJIIJJIIJIIIIIIJIIJJIJIJJIIJJJJJJJJJJJIJJ()
	{
	}

	private void JIIJIIJIJIIIIIIIIJIJJIIJJIIJIJIJJJJIJIIIIIIJJII(bool JJIIJJIJIIIIJIIJJIIJJIJIJIIIIIJIJIJJJIJIIJJJIII)
	{
	}

	private void IJIJJIIIJIIJJIJIJJJJJIJIIJJIIIJIIIIJJJIJIJJIJIJ(Action<string> IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ)
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void JJJJIIJJJJIIJIJIIJIIJIIIJIJIJIJIIJIJIJJIJIIIIIJ(string JJIJJIJJIJJJIIJIJIIIJJIIJJIIJJIIJJJIIIIJJIIIIJJ)
	{
	}

	private void JIJIJIJJIJJJJJJIIJJIIIJIIJJJIJJJIIIJJJJJIIJIIII()
	{
	}

	private void JJIJJIIJJJJJIJJJJJIJIJIJJIIJJIJJIJIJIJJJIIIIJIJ()
	{
	}
}
