using UnityEngine;

public class mAddonMenu : MonoBehaviour
{
	public delegate void JJIJJIJJJIIJJJJJJJIJIJIIJIJJJJIIJIJIJJIJJJIIIJI(string JJJJJIJJIIJIIJIJJIIJJIJIJIIJJJJIJIIJJJIIIJJJJJJ);

	public UILabel[] IIJIJIIJJIJJJIJJJIJIJIJIJIJJIIIIIJIJJJJJIIJJJIJ;

	public UISprite JJJJJIJJJJIJIJIIJJJIIJIJIIJJIJIIIJIIIIIIJIIJIJJ;

	public UIGrid IIIIIIJIJJJIIIIIIIIIJIJIIIIIJIIIJIJJJJIIJJJJIJI;

	public UIPanel JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ;

	private string[] JJIIJJJIIJJIJIIIIJJJIIIJIIJJIIJJJIIJIIJJJJJJJII;

	public static JJIJJIJJJIIJJJJJJJIJIJIIJIJJJJIIJIJIJJIJJJIIIJI JIIJIIJJIIJJIIJJIJJIJIIIJIJIJJJIIIJJJJJIIIJJIJI;

	private static mAddonMenu JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void JIJIJIIJIJJJIJIJIJJJJIJJJIIIIJJIJJIIIIIIJJJJJJJ(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, string[] IIJIJIIJJIJJJIJJJIJIJIJIJIJJIIIIIJIJJJJJIIJJJIJ, bool JIIIJJIIJIJIJJIJJJJJJIJIJJIIJJJJJJIJIIIJIJJIIJJ)
	{
	}

	public static void JIIIJIJIJIIJIIJJJIJJJJIJIIIIIIJIJJJJJIIIIIIJIII(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, string[] IIJIJIIJJIJJJIJJJIJIJIJIJIJJIIIIIJIJJJJJIIJJJIJ, bool JIIIJJIIJIJIJJIJJJJJJIJIJJIIJJJJJJIJIIIJIJJIIJJ)
	{
	}

	public static void IJIJIJIJIIIJJIJJIIIIJIIIIJIIJIJJIIJIIIIJJIJIIII(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, string[] IIJIJIIJJIJJJIJJJIJIJIJIJIJJIIIIIJIJJJJJIIJJJIJ, bool JIIIJJIIJIJIJJIJJJJJJIJIJJIIJJJJJJIJIIIJIJJIIJJ)
	{
	}

	private void OnEnable()
	{
	}

	private void JJJIIJIJJJIIIJIJJIJIJJIJJIJIJJJIJJIJIJJIIJIJJIJ()
	{
	}

	public static void IJJIJIJJIJIJIJIIIIIIIJJJJIJJJJJJIIIIJIJIJIJIIJI(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, string[] IIJIJIIJJIJJJIJJJIJIJIJIJIJJIIIIIJIJJJJJIIJJJIJ, bool JIIIJJIIJIJIJJIJJJJJJIJIJJIIJJJJJJIJIIIJIJJIIJJ)
	{
	}

	public static void IJJJIJIJJIJJJIJJJJIIIIJIJJIIIIJIIIIJIIJJIJIJJJI(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, string[] IIJIJIIJJIJJJIJJJIJIJIJIJIJJIIIIIJIJJJJJIIJJJIJ)
	{
	}

	private static void JJJIJIIJJJJIIJJIIJJJJJIJJJIIJIJIJIJIJJIJJIIIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}

	private static void JJJJJIJJJJIJJIJIJJIIIJJJJJJJJIJJIJJIIJJJIJIJIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}

	public static void JIJIJIIIJIJIJIJIJJIIJJJJIIJJJJJIJJJJJIIIJIIJIJI()
	{
	}

	private static void IIIIJJIJIIJIJIJIJIJIIJJIIIIIJIJIJJJJIJIJIJJJJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}

	public static void IIIIIJIJIJJIIIJIIIJJJJIJJIIIIJIJJJIJJIIIIJJJIJI(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, string[] IIJIJIIJJIJJJIJJJIJIJIJIJIJJIIIIIJIJJJJJIIJJJIJ, bool JIIIJJIIJIJIJJIJJJJJJIJIJJIIJJJJJJIJIIIJIJJIIJJ)
	{
	}

	public static void JJIJIIJIJJIIIIJJIJJIIJJJIJIIIIJJJIJJJIIJIIJIJJI()
	{
	}

	public static void IJIJIJIJIIIJJIJJIIIIJIIIIJIIJIJJIIJIIIIJJIJIIII(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, string[] IIJIJIIJJIJJJIJJJIJIJIJIJIJJIIIIIJIJJJJJIIJJJIJ)
	{
	}

	private static void IIJJIJJIJIIIIJJIJIJJIJIJIJJJJJJJIJIJIJJIIIJJIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}

	public static void JIIJIIJJJIIJIJJJIIIJIJJIJIIJIIJJIIJIJJIIJIIJJJI(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, string[] IIJIJIIJJIJJJIJJJIJIJIJIJIJJIIIIIJIJJJJJIIJJJIJ, bool JIIIJJIIJIJIJJIJJJJJJIJIJJIIJJJJJJIJIIIJIJJIIJJ)
	{
	}

	public static void IJJJJJJIJJJJJIIIIIIJJIJIJJIIIIJJIIJJJJJJIIIJJII(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, string[] IIJIJIIJJIJJJIJJJIJIJIJIJIJJIIIIIJIJJJJJIIJJJIJ)
	{
	}

	private static void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}

	public static void IIIJJIJJJJJJIIJJIJIIIJIIJIIIJIIIIJIIIJIJJIJIIJJ(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, string[] IIJIJIIJJIJJJIJJJIJIJIJIJIJJIIIIIJIJJJJJIIJJJIJ, bool JIIIJJIIJIJIJJIJJJJJJIJIJJIIJJJJJJIJIIIJIJJIIJJ)
	{
	}
}
