using System.Runtime.CompilerServices;
using UnityEngine;

public class MainTutorial : MonoBehaviour
{
	public Transform IJJJIJJJJJIIJJJJJJIIIIIJJIIIIJJJJJJIIJJJJJIJIII;

	public GameObject IIIJJIIJJJIJJJIJIJJJIIJIIIIJIIJJIJJIIIIJIJIIJIJ;

	public GameObject JJJJIIIJJIJIJJIIJJIIJIJJJJIIIJIJJIJJJJJIJIJIJJI;

	public GameObject JIJIIIIIJJIIJJJIIIIJJIIIIIIIJIJIJIIJJIJIIIJJIJI;

	public TutorialTarget IIIJIIJJJJIIIIJIJJJJIIIIIJIJIJIJJIJJJIIIJJIJIIJ;

	public TutorialTarget JIIJIIJIIIIIIJIJJJIJJJIIIIJIJIIIJJJIIIIJIIIIJII;

	public TutorialTarget IIJJIIJJIJIJJIJIJIJJJJJJJJIJJIIJJIJJJJIIJJIIIII;

	public GameObject IJIJJJIJJJIJIJJJIIJJIIIIIJIJIIJJIIIIIIJIJIIIIII;

	public GameObject IIIIIJIIIIJJJJIIIIJJJJJIJIIIIIIIIIIJIIJIJIJJJII;

	private void IIIIIIIJJIIIIIIIIIIIJIIJJJIJJIIIJJIJJJIJJJJIJIJ(string IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void JIJJJJJJJJIIJIIJJIIJIJJJIIJIIIJJJIJJJIJJJJJJIJJ()
	{
	}

	private void JJJIIJJIJJIIJIIJJIJJIJJIJIIIIIJJIJIIIIIJIJIIIIJ()
	{
	}

	public void Tutorial06()
	{
	}

	[CompilerGenerated]
	private void JJIJIIJJIJIJIIJIJIJJIJIJIIIIJJIJJIJIJJJJIIJIJIJ()
	{
	}

	private void IJIIIJJJIJJJIJIIJIJIJJIJIIJJIIJIJJJIJJIIIJJJIJJ()
	{
	}

	[CompilerGenerated]
	private void IJJJIJIIJIIJIIJJJIJIIJJIIIIIJJIIIJIJIIJIJJJJJJI()
	{
	}

	public void Tutorial03()
	{
	}

	private void IJIJJIJIJIIJIIIIJIIJIIIJJJJIIIJJIIJIJJIJIJJJIIJ()
	{
	}

	private void OnDisable()
	{
	}

	private void IIIIIJJIJJJIJJJJIJIJIJIJJJJJJIJIJIIJJJJIIIJJIJI(string JJJIIIIJIJIIIJIJIIIIJJIIJIJIIIIIJIIJIJIJJJJJIJJ)
	{
	}

	private void JJJJJJJIIJJJJJIIIJIIJJIIIIJIJJIIJJJJJJJJJIIIIIJ(string IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	public void Tutorial04()
	{
	}

	private void JJIIJIJJIJJJJJIIJIJIIJIJJIIIJIJJIJIIJIJIJIIJJJJ(string JJJIIIIJIJIIIJIJIIIIJJIIJIJIIIIIJIIJIJIJJJJJIJJ)
	{
	}

	private void IJIIJIJJIJJJIIJIIIJJIJIIJJIIIIJIIIJIIJIJIIIJJJI(string IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void JJJIIJIIIIJIJIIIIJIIJJJIIJJIIJJJJJIJIIIJIJIJJJI()
	{
	}

	[CompilerGenerated]
	private void JJIJJIIIJJIJIIIIJIIIJIIJJIJIJIJIJIIIJIIIIIIJJJJ()
	{
	}

	private void JIJJJIJJIJJIIIJJJJIJIIJIIJIJIJJJJJIIIJIJIIJIJJJ(string IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void IJIJJIJIJIJJJIIJIIJJJIJJIIJIJIJJIJIIJJIJIJJJJJI(string IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void JJJJIIIIJIJIIJJJJJJIJJIIIIIJJIJIJIIIIJJIJJJJIJJ(string IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	public void Tutorial02()
	{
	}

	public void Tutorial05()
	{
	}

	private void JIIIJJIJIIIIIJJIJJJIJIJIIJIJJJJIJJIJIJJIIJIIJIJ()
	{
	}

	public void IIIIJIIIJIIJJIIJIJJJJIJIJIJIJJIIIIIIIJJIJJJIJIJ()
	{
	}

	private void JIIJIIIIIIJJIIIJJJIIIJJIJIIJJIIIIIIJIJJIJJJJIIJ()
	{
	}

	private void IJJIIJIJJIJJIIJIJJIIIJIIJIJJJJIJJIJJJJJIJJJJIII()
	{
	}

	private void JIIJJJIIIIJJJJIIIJIIJJIJIIIJJIJIJIJIJIJJJIJJIJI(string IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void IJJJIJIIIIJJJIIIIIIIJJIIIJJJJJJIIJJIJJIIJJIJJIJ()
	{
	}

	public void IIJIIJJIJJJIIJJIJJJJIJIIJIJIJJJJIJIJIJIJIJJJJJJ()
	{
	}

	[CompilerGenerated]
	private void IIJIJIIIJIIIIJJIIIIJJJIIIJJIJJIJJJJJJJJIIJIIJIJ()
	{
	}

	private void IIJJJJJIJIIJIIIJIIJIIJJJJJJJJIIJJJIJJJIJJIIIIIJ(string IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void IJJJJJJIIIIIJIIJJIIJJIJJJIJIIIIJJJIJJJIJJIJIIJJ()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	public void Skip()
	{
	}

	private void JJIIJIIIIJIIJJIJIIIIIIJIJIJIJIIIIIJIJIIIJIIIIIJ(string IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	[CompilerGenerated]
	private void IJIJIJJJJIJIJIJJJJIJJJIJJJJIJIJJJJJJIJJIJIIIIJI()
	{
	}

	[CompilerGenerated]
	private void IIIIIIJIIIJIIJIIJIJJJIIIIIIIIIJJJIJIJJIIJIIJJJJ()
	{
	}

	private void IJIJIIJJIJJIIIIJIIIIIIIJJJJJIIJJJJJJIJJJJJJIIII()
	{
	}

	public void IJIJJIIJJJIIJJIJIIJJIIJJJIJJIIIIJJIJIJJJJJJJJIJ()
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	private void Start()
	{
	}

	public void DeactivedTarget(int target)
	{
	}
}
