using UnityEngine;

[ExecuteInEditMode]
public class MapPositionTrigger : MonoBehaviour
{
	public JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ;

	private void IIIIJIJIJJIIJIIIIJIJIJIJIJIIJIJIJJIJJJJJIIIJIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJJJIJIJJIIIJJIJJJJJJJIJIJIIIIJJJJIIJIJJJIIJJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIIIIJIJJIIIIJIIIIJIJJJIJJJJJIJIIJIIJJJIIJJIIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJIIIJJJIJJIIJIIIJIIIJIIIIJIIJJIJIIJIIJJIIIJIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJIJJIJJJJJJIIJIIJIJIJJIJJJJJJJIIIJJJJIIIJJJIII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIJIJIJJIJIIIJIJJIJIIIJIIIJJJJJIIIJJIIIJIJIIIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIJJIIJIIIJJJIIJJJJJJJIJIJIJJJIIIIIJIJJIIIIIJIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJJIJJIIIJIJJIIIIJIJJIJIJJJIJJIIIJJIJJIJJJJJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJIJJIIIJIJIJIIJJIJJJIJIJJIJIIIIJIIIJIJJIIIJIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJIJJJJJJJIIJJJJIIIJJJJIJIIJIIIIIJIIIJIIJIJIJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIIJJIIIIIIJIIJIJIIJJIJJJIJIJJJIJJJJIIJJJIJJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJIIJIJJJJJIJJJJIIJIJJJJIJJJIIJJJIJJJIIJJIIIIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIJJJIJIJIIIJIJIJIIIJIIIJIJJIJIIJIJIIJIIIJJJJIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}
}
