using System;
using System.Runtime.InteropServices;
using UnityEngine;

public class MaxScoreManager : MonoBehaviour
{
	[Serializable]
	[StructLayout((LayoutKind)0, Size = 16)]
	public struct IIJIIIJJJIIJIJJJJJJJIJJIIIJJJIIIJIIIIIJJJIJIIII
	{
		public GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIJJIIIIJJIIJJJIJIIIJIIJIJIJJJJJIJJJJIJJIIJIJII;

		public IIJIIIJJJIIJIJJJJJJJIJJIIIJJJIIIJIIIIIJJJIJIIII(GameMode JIIJJJJJJJJIIIJJJIIJJJJIIIIJJIIJJIIIIJIIIJJJJJJ, int IJJJIJJJIJJIIJJIJIJJJIIIJIJJJJJJIIJIJIIIJIJIJJI)
		{
			JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI = GameMode.TeamDeathmatch;
			JIJJIIIIJJIIJJJIJIIIJIIJIJIJJJJJIJJJJIJJIIJIJII = default;
		}
	}

	public IIJIIIJJJIIJIJJJJJJJIJJIIIJJJIIIJIIIIIJJJIJIIII[] IJIJJJJJIJJIJJIIJIJJJJJIJIJJJIJIIJIJJJJJJJJIJII;

	private static MaxScoreManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static int JIIIJJJIJIJJIIIJIIJJJJIIJJJJIIJIJIJIJJJIJIIIIJJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
		return 0;
	}

	private void IJJJJJJIJJIIIIJIJIJJJIIIJJIIIIJJIJIIJIIIIJJJJIJ()
	{
	}

	private void JJIJJIIIJIJIJIJIJIIJIJIJJJJIIIIJJIIIJIIIJIIIIJI()
	{
	}

	public static int IJJIJJJIIIJJIIIIIJJIJJJJIJJIIIJJJJJIIJJJIJIIJIJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
		return 0;
	}

	public static int IJIIIIIIIIJJIIJIJJIIIIIJIIJIIIIIJIIJJIIIIJIIIJI(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
		return 0;
	}

	private void Awake()
	{
	}

	public static int JJIJIJIJJJIJIIIJIJJIIIIIIJJIIIJIJJIJJIJJJIIJJJJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
		return 0;
	}

	public static int JIJIJJIJJJIJJIIIJIIIJJIIJJJJIJJIIJIIJJJJJJJJIII(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
		return 0;
	}

	private void JIJJIIIJJIJIIIIIJIIJIIIIJJJIJIIIIJJJJJJJJIIIIIJ()
	{
	}

	private void JIJJJIIIJJJIJJJIJJIIIJJJIJIJJIJIIIJIJJIIJJIJIIJ()
	{
	}

	private void JJIJIIIJIJIJJJJIJIIJJJJJIJJJJJIJIJIJIIJIIJIIIJJ()
	{
	}

	public static int JJIIJIIJIIIJJIIJIIJJIJJIIIIJJJJJIIJJIIJIIIJJJII(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
		return 0;
	}

	private void JIIIIIJIJJIIIIIIIJJIIJJJJIIJJJJJJIIJIJJJJIIIIJJ()
	{
	}

	public static int IIJIIIIJJIIJIJIIIJJJJJJJJIJJJIJJJIJIJIJIJJJIJJJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
		return 0;
	}

	private void JIIIJJIJIJJIJJJIIIIJJJIJIJIJIIIJJJJIJJIIIIJJIII()
	{
	}
}
