using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mCaseWheelManager : MonoBehaviour
{
	private bool JIIIJJIJIJIIJIIJIIJJJJIJIJJIIJIJIIJIJIIIIJIIJJJ;

	private float IJJJJIJJIJJJIIJIIIJJJJJJIJJJIIIIIJIJJJJIJIIJJJI;

	public AnimationCurve IJIIJIJIIJIJJIIJJIJIIIJJJIIIIIJJIIIIIJIJJJJIJJI;

	public float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ;

	public float IIJJJJJJIJIJIIIJIJJJJJIJJIJJIJIJJJJIJJJIIIIIIJI;

	public Vector2 JJIJIIIIJJIIJIJJJJIJJJIJJIJJJIJJIJIIIIJIIJJJIII;

	private float JIIJJIJJJIJJJIIIJJJIJIJJJIJJJIIJIIIJJJIJJIJJIJJ;

	public AudioSource IJIJIIJJIIIJJIJIIIIJJIJJJIJIIJIJJIJJJIJIJJIIJII;

	public float JJIJJJJIIJJIIJJIJIJJIIJIJIIJJJJIJIJIIJIIIIJJJJI;

	private float IIIIIJIJJIJIJIJJIJIJIIJJJJJJIJIIIJIIJIIJJIJJIJI;

	public mCaseWheelItem[] IJIIJJJJIJJIJJJIJJIIJJIJJIJJJJJJIIIIIIJIJIIIJIJ;

	public mCaseWheelItem JJJJIIJJJJIIJJJJJJIIIJJJIJIJJJJIJJJIIIJIJJJIJIJ;

	public Transform JIIIIJIJJIIJIJJJIIJIJJIJJIJJIJJJJIIIJIIIJIIIIII;

	public UIAtlas JIIJJIIJJIJIIIIJIIIJJJJIIIJJJIIJJJJIJIIJIJIJIII;

	public UIAtlas IIJJIIJJJIJJJJJIIJIJJIJJIJJIJJJJIIJJJIJIIIJIIJI;

	public Texture2D[] IJJJJIJIJJIIIIJJJIJJJIIIJJJIIJJIJJIIIJJJIJJJJJJ;

	public Texture2D[] JIIJJIJIIJJJJIJJJJJJIJJIIJIJIJJJJJIIJJJIIJIJIJJ;

	public static TimerDelegate JJIJIIJJIIIIJJIIJIJJJIJIJJIIJIJIJIIIIJIJJJJIIIJ;

	private static mCaseWheelManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private static Color IIIJJIIIJJIIJIJJIJIJJJJJJIJIJIJJJIJIJJIIJIIIIJI(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	public static void JJIJJJIJJJJJJJJIIJIIJIIJIIIJIJIJIJJIIIIJIJJJJJJ(int JIIJJIJJJIJJJJJIJIJIJJIIJJIIJIJIIJJIJJJJIIJIJJI, bool IIJJIIIIJIJIJJJJIIIJIJJJJJJJJIIJIIIJIIIIIJJJIJJ, int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private static Texture2D IIJJIIIJJIJJIJJIJJJIJJJIIIJJIJIJJJJIIJIJIJJIIIJ(bool IIJJIIIIJIJIJJJJIIIJIJJJJJJJJIIJIIIJIIIIIJJJIJJ, int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	private static Color JIIIIJIJIJJIJJJJIJJIJJIIIIJJJJIJJIJJJIJJIJIIJJJ(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	public static void IJJIIIIIJIJIJJIIJIIJIJJIJIIIJIJJIJIIIJIJJJJJIIJ(int IJJIIIJJIJIIIJIJJIJJJIJIJJJIJJIJIJIJIJJJJIJIIJJ)
	{
	}

	public static void IJJJJJIJJJJIJIIIJIIJJJIJIJJIJIIJIIIJJJJJIJJIIJI(bool IIJJIIIIJIJIJJJJIIIJIJJJJJJJJIIJIIIJIIIIIJJJIJJ, int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JJIIJIJJIJJJJJIIIJIJIJJIJIIJJJJIIJIJJJIIIIIIIIJ(int JIIJJIJJJIJJJJJIJIJIJJIIJJIIJIJIIJJIJJJJIIJIJJI, int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, int IIJJJJJIIIIJIIJJJIIJIIIJIIIIJIJJJJIIIIJJJJJJJJI)
	{
	}

	private static Color IJJIIIJJJIJIJJIIJJJIIIIJIIJJIIJJJJJJIIJJJJJJJIJ(JIIJIJJJIJIJJIJIIJJIJIIIJIIJJIIIJIIIIJJIJJIJJJI IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	public static void JJJIIIIIIIIJJJJIJIIIJIIIJIIIIIIIJJJJJIIJIIJJIJI(int JIIJJIJJJIJJJJJIJIJIJJIIJJIIJIJIIJJIJJJJIIJIJJI, int IJJIIIJJIJIIIJIJJIJJJIJIJJJIJJIJIJIJIJJJJIJIIJJ)
	{
	}

	public static void IJJIIIIIJIJIJJIIJIIJIJJIJIIIJIJJIJIIIJIJJJJJIIJ(int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
	}

	public void OnSpeed()
	{
	}

	private static Texture2D IIJIIJJJJJIJJIJJIJJIJJJIIJIIJIIJIIIJIIIIJIIIIJI(bool IIJJIIIIJIJIJJJJIIIJIJJJJJJJJIIJIIIJIIIIIJJJIJJ, int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return null;
	}

	public static void JJIJJJIJJJJJJJJIIJIIJIIJIIIJIJIJIJJIIIIJIJJJJJJ(mCaseWheelItem JIJIIJJIIIJJIIIIIIJIIJJIIIIJIIIIJIJIIJIIIJJIJIJ, bool IIJJIIIIJIJIJJJJIIIJIJJJJJJJJIIJIIIJIIIIIJJJIJJ, int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void Start()
	{
	}

	public static void JIIIJIIJIIJIJJJIIJIJIIIJIJIJJIIJJIIJIIIJIIJJIII()
	{
	}

	public static void IJJJIJJJIIIJJJJJIJJIIIJIJIJJJJJJIIJIJIIIIJJJIJJ(int IJJIIIJJIJIIIJIJJIJJJIJIJJJIJJIJIJIJIJJJJIJIIJJ)
	{
	}

	public void JIIJJJJIJJJIIJIIJJJIJJJIJIIJJJIJIJIJJJIIIJJIIJI()
	{
	}

	public static void IJJIIIIIJIJIJJIIJIIJIJJIJIIIJIJJIJIIIJIJJJJJIIJ(bool IIJJIIIIJIJIJJJJIIIJIJJJJJJJJIIJIIIJIIIIIJJJIJJ, int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void IIJJJIJIIIIIJIIJIJJIIIJIJJIIJIJIJJJJJIJJIIIJIIJ(bool IIJJIIIIJIJIJJJJIIIJIJJJJJJJJIIJIIIJIIIIIJJJIJJ, int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JJIJJJIJJJJJJJJIIJIIJIIJIIIJIJIJIJJIIIIJIJJJJJJ(int JIIJJIJJJIJJJJJIJIJIJJIIJJIIJIJIIJJIJJJJIIJIJJI, int IJJIIIJJIJIIIJIJJIJJJIJIJJJIJJIJIJIJIJJJJIJIIJJ)
	{
	}

	public static void JJIJJJIJJJJJJJJIIJIIJIIJIIIJIJIJIJJIIIIJIJJJJJJ(int JIIJJIJJJIJJJJJIJIJIJJIIJJIIJIJIIJJIJJJJIIJIJJI, int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, int IIJJJJJIIIIJIIJJJIIJIIIJIIIIJIJJJJIIIIJJJJJJJJI)
	{
	}

	public static void JJIJJJIJJJJJJJJIIJIIJIIJIIIJIJIJIJJIIIIJIJJJJJJ(mCaseWheelItem JIJIIJJIIIJJIIIIIIJIIJJIIIIJIIIIJIJIIJIIIJJIJIJ, int IJJIIIJJIJIIIJIJJIJJJIJIJJJIJJIJIJIJIJJJJIJIIJJ)
	{
	}

	public static void JJIJJJIJJJJJJJJIIJIIJIIJIIIJIJIJIJJIIIIJIJJJJJJ(mCaseWheelItem JIJIIJJIIIJJIIIIIIJIIJJIIIIJIIIIJIJIIJIIIJJIJIJ, int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, int IIJJJJJIIIIJIIJJJIIJIIIJIIIIJIJJJJIIIIJJJJJJJJI)
	{
	}

	private void Update()
	{
	}

	public static void IIJJIIJJJJJJJIJJIIJJJJIJJJIIIJJJIJIJIIJIJIJIJII(bool IIJJIIIIJIJIJJJJIIIJIJJJJJJJJIIJIIIJIIIIIJJJIJJ, int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JIJIJJIIIJJIJJJJIIJJIJJIJJJJIJJJJIIJIIJIJJJJJII(int JIIJJIJJJIJJJJJIJIJIJJIIJJIIJIJIIJJIJJJJIIJIJJI, bool IIJJIIIIJIJIJJJJIIIJIJJJJJJJJIIJIIIJIIIIIJJJIJJ, int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
}
