using UnityEngine;

public class mCaseSkinInfoElement : MonoBehaviour
{
	public UISprite IJJJJIIIIIJJIIJJIJIJIIJJIIIIJIJIJIIIIJJJIJJJJJI;

	public UISprite IJJIJIJJJIJJJJJIJIIIIJIIIJIJIJJJJJJIIJJIJIIJJJI;

	public UISprite IJIJIJIJJIJIJJIJIJJJJJJIIIIJIJIIJIJIIJIJJJJJJJI;

	public UILabel IJJJJIIIJIJJJJIIJJJIJJIIJIIJJJJJJIIIIJJIIJIIJIJ;

	public UITexture JIIJIJIJJJJJIJJJJIJIIIIIIJIIIJIJIJIJIJJIIIJJIJJ;

	public UITexture IIIIJIJIJJIJJIJIIJJIIIIJJJIIIIJJIIIIJIIJIIIIIII;

	public GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII;

	public int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI;

	public int IIJJJJJIIIIJIIJJJIIJIIIJIIIIJIJJJJIIIIJJJJJJJJI;

	public void IIJJIJJIJIIIJJIIJIIIJIIIIIJIJIIIIIJIIJIJJJJJIIJ()
	{
	}

	public void IJJIIIIJJJIIIIJJIIIIIJJJIIIIJIJIJIIJJJIJIIIIJII()
	{
	}

	public void IIJIIIIIJJJIJJJIJIJIJJIIJIJJIIJIIJIJIIIIJJIIIJI()
	{
	}

	public void JJIJJJIIIJIJJJIJIIIIJIIJIJIJJJIJJJJJIIJIIIIIIJI()
	{
	}

	public void IIIIIIJIIJJIIJJJJJIIJIIJIIJJIJJJJJIJIJJJJIIJIIJ()
	{
	}

	public void OnClick()
	{
	}

	public void JJIJIJJJIJJIJIJIJIIJIJIJJIJIJIJJJJIJJJIJJIJJJJJ()
	{
	}

	public void IJJJJIJIJIJJJIIJJIJJJJIJIJIJIIJJJIIIIIIJJJIJJJI()
	{
	}

	public void JJJIJIJIJJJIJJIJIIJIJIJJJJJIIIJIIIIJIJJIJJJIIIJ()
	{
	}

	public void IJIIJJIJIIJIIJIIIJJJIJJIIIIJIIIJIIJJJJIIJIJJJIJ()
	{
	}

	public void JIIIIJIJIIJIJJJIJJIIJIIJIJIIJIIJJIJJJIJIIJIJJJI()
	{
	}

	public void JJJIJJJIIIJIJIJIIIIIJJJJJJJJIJJJIIIIIJIIJJJJJIJ()
	{
	}
}
