using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mCaseSkinInfoManager : MonoBehaviour
{
	private sealed class IJJJIJIJIIJJJIIJIIJIJIJJIJIIJJIIJIJJIIIIJJIIIJJ
	{
		public int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ;

		public int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ;

		internal void IIJJJIJIJJIJJJJIIJJIIJIIIIIIJJJJIIJIIIJIIJJIIII()
		{
		}

		internal void JIJJIJIIIIIJJIIJIJJIIIJJIIIIIIJJIJIJIIIIIJJIIII()
		{
		}

		internal void IIIIJJJIIIIJIIJIIIIIJIJIJIJJIIJIIIJJJJJIJIIJJJI()
		{
		}

		internal void IIIJIIJJJJIIJIJJJJIJIIIJJJIJIJIJIJJJIJIJJIIIJII()
		{
		}

		internal void JJIIJJIJJJJJIIIJJJIJIJIJIJIJJIIIIJJJJIJIJIIIJII()
		{
		}

		internal void JJJJIIJJIIJJJJJIIJIIJJJJJJIIJIJJIIIIJIJJIJIIIJJ()
		{
		}

		internal void IJIJJIJJIJJJIJIIIIJJIIIJJJIJJIIIIIJJJIIJIIIIJJI()
		{
		}

		internal void IJJJJJIJIIIIIIJIJJJJJIJIJJJIJIIIJIJIJIJJJJIIIJJ()
		{
		}

		internal void IIIJIJIJIIJIIJJIJIJJJIJJJJIIIJJIIIIJJIIJJJJIIJJ()
		{
		}

		internal void IJJJJJIIIJIIJIJJIJIJIJJJJJJIIJIIJJIJIIJIJJIIJJJ()
		{
		}

		internal void IIIJJIIJIIJJJJIIJIJIJJJIJIJJJIIIIJIIIIJJJJJIIJI()
		{
		}

		internal void IIJIJIIIIIJIIIIJIJJIJJJIIJJJJJIJJIIJIIJIIJJIJJJ()
		{
		}

		internal void JJJIIJIJIJJJIIJJJIIIIJIIIIIIIIJIIJIJJIJIIJIIIII()
		{
		}

		internal void JIJIJJJJIJJIJIIJJIIIJJJIJJJIJJJJIIIIIJJJJJJJIII()
		{
		}

		internal void JIJIIIJIIJIIJIIIIJIJJJIJIIJJIIJJIJIJIIJJIJJJIJI()
		{
		}
	}

	public UITexture IIIJIJJIJJIIJIJIIJJIIJJIJJIIJIIJIIIJJJJIJIIIIJI;

	public UILabel JIIIIJIJIJIJIIJJJIIIIJIJJJIIIJIIIIIJJJJIIJIJIII;

	public UITexture JJJIIIIJIJJJIJJIIJIJIJIJIJJIJJIJIJJIIJIIIJIJJIJ;

	public mCaseSkinInfoElement[] IIJJIJIIIIIJJJJIJIJIJJIJJIIIJIJIIJJIIIJIIJJJJII;

	public Color JIJIJJIIIIIJJJJIIJJIIIIJIJIJIJIJIIIJJIJJJJIJIJI;

	public Color IJIIIJJIIIJJJJJJIIJJIJJIJJJJIJIJJJIIIIIJIJJJIII;

	public Color IJJIJJIIIJIJJJIIJJIIIJIIJIJIIJIJJIIIIIIIIJIJJII;

	public Color JJJIIIIJJJJIJJJJIIIJJIJIJIJIJJJIJJJJIJJJJJJJIII;

	public Color JJJJIJIJJIIIJIIIIJIIIIJIJIIIIIJJJJIIIIIIJJIIJJJ;

	public float JJIIJIJJJJJIIIIJJJIIJJIIJJJIIIJIJJIJIJIJJIJJIJJ;

	public GameObject IJIJJJIIIIJJIIJJJIJIJJIJIIIIIJIJIIJIJJIIIJIJJIJ;

	public GameObject JJJJIJJIJIIJJIIJJJIIJJJJIJJJJJIIJJJIIIIJJIIJJII;

	public UIWidget JJIJJJIJIIJIJIIIJIIJIJIIIJIJIJJJIJJJJIIIIJJIIJJ;

	public UILabel JJJJIIJJIJJIJIIJIJIIIJIIJJIJIIJIIIJIJJIJIIIIIJJ;

	public UILabel JIIIJIIJIJJIIJJJJIIJJJJIIIJJIIJJJIIIJJIJIJJIJIJ;

	public UITexture IIJJIIJJJIIIIJJIJJJJIJJIIJIIJIIIJIJJJIIIJJJJJIJ;

	public UILabel IIIIIJIIJJJIIJIJIIIIJJJJJJIIIJJIJIJIJJIJIJIJIJI;

	public UITexture IJIIJIIIJJIIJJJJIJIIIJIJJIIJJIJIJIIIIIIJIIJIIIJ;

	public UISprite IIIIIJIIJJIJJIJJJIIIJJIJJJIJIJIIIJJJIIJJJJJJIJI;

	public GameObject IJIIIIJJIIJIJIJIIIIIJJIJIJIJJIIIIJIJJIJIIJJIIII;

	public GameObject IJJIJJIIIJIIJJIJIIJJJJIJIIIJJJJJIIIIIIIJIJIIJII;

	public Texture2D JIIIJJIIJJIJIIIJIJIIJIJIIIIJJJIIIIIJJIIIJJJJIJI;

	public Texture2D JJJJIJJJJIJJJIJIIIIJIIIJJIJIIJJJIJJJIJIJJJJIJJI;

	public Texture2D[] JJIIJJIJIIIIJJIJIJJIIIIIIIIIJJJJJIJIJJJIIIIIIII;

	public Texture2D[] JJJIJIJIJJIIJJJJIJIIIIIJJJJJJJJJJIIJIJIIIIJJJII;

	private List<int> JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI;

	private List<int> IIJJJJJIIIIJIIJJJIIJIIIJIIIIJIJJJJIIIIJJJJJJJJI;

	private int JIIIJIIJJIJJJJIJIIJJIIJJJIIJJJIIIJJJIJJJJIIIIII;

	private static mCaseSkinInfoManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void IJJJIJJJIJIIJIIIIJIJJJIJJIJIJJJJIJJJIJJIIJIJIJI(int JJJJIIJIIJIIIIJIIJIIIIJJJIIJIIJIIJIJIJIJJJJIIIJ, string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private static Color IIIJJIIIJJIIJIJJIJIJJJJJJIJIJIJJJIJIJJIIJIIIIJI(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	private void Start()
	{
	}

	public static void JIIIJJIJJJIJIJIIJJJIIJJJIIJIJJIJJJIJJIJIIIIIJII(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	public static void IIJJJIIIJJIIIJIJIJIJJJJIIJJIIJIJJJJJIIIJIIJJJII(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private void IJJJJJIJIIIJIIIJIJIIJJIJJJJIIJIJJJJIJJJJJJIIIIJ()
	{
	}

	private void IJJIIJJIJJJIJIJJJIIIIIJJJIIJJIJJJJIIJIIIJJJIIIJ()
	{
	}

	public static void IIJJIJIJIJJJIJIIJJJIJJJIIJIJJIJIIJIJJJIIIIJJIJI(int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
	}

	public void JIIJIJJIJIJJJIJIIJIIJIJIIIJIIIIIIJIJIIJIIIJJIII()
	{
	}

	private void IIIIJJJJIIJJIJJIJJIIIIJJIJJIIJIJIJIJIIJIIJIJIJI(int JJJJIIJIIJIIIIJIIJIIIIJJJIIJIIJIIJIJIJIJJJJIIIJ, string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	[CompilerGenerated]
	private void IJIJIIIIJIJJIJIJJIJJJIIIJJIJIIJJIIIJJJIIJJIJIII()
	{
	}

	private void IIIJIJIJJJIIJJJJIJJIJJIIIIIIJIIJJIIJIIJIJJIJIJI()
	{
	}

	private void IIJIIJIJJJJIIJJJJIJJIJIIIJIIIJIJIJIIIIJIIIIIIIJ()
	{
	}

	private void JIJJIIIJIJIJIIIIJIIJIJIIIJIJJIJIIIIJJIIIJJIIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 JJJIIJIIIIIIJJJIIJJJJIJIIJJIJIIIIJJIIJJJJJJJJJI)
	{
	}

	private void JIIIJIJIJIJIIJJIJIIJJJJJIJIIIIIJJIJJIJJIIJJIIJJ()
	{
	}

	private void JIIIIJIJJIJJIIIJIJIJJJIIJIJJJIIJJJIIJIIIIJJJJJJ()
	{
	}

	private void JIJIJIIIIIJIJJIIJIIIIIJIJJIIJIIJIJIIIIIIJJJJJJI()
	{
	}

	public void OpenCaseRewarded()
	{
	}

	[CompilerGenerated]
	private void JJJJJIJJIIIIJJIIJIIIIIIIIIJIIJJJJJIIIJIJJIJIJJI()
	{
	}

	private void IIJIIJIJJJIJJJIIJJJJJIIJJIJJIJIIJJIIJJJJJIJIJIJ()
	{
	}

	private void JIJIJIJJJJIJIIIJIIJJJIJIIJJIJIIIJJIIIIIIIJJJJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 JJJIIJIIIIIIJJJIIJJJJIJIIJJIJIIIIJJIIJJJJJJJJJI)
	{
	}

	private void JIIJJIIIJJJIJIIIIIIJIIIIJJJIJJIJJJIJIIIIIIIJJJI()
	{
	}

	private void JIJIJJJIJJIJJJIIJJIJIIIIIIIJIJIIIJJIIJIIIJJIIJJ()
	{
	}

	private void IIIIJIJJJIJJIJJIJJJJJJIIIJJIIIJIIJIJJIIJIIJJIIJ()
	{
	}

	private void IIIIIJJIIJJIJIJIJJJJIIJJJIIIIJIIIIJIIIIIJJJJJJJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	public void OnBackPreview()
	{
	}

	private void JJJIJIJJJIJIIJIIIIIJIIIJIJJIJJIJJJIJIIIJJJIJIIJ()
	{
	}

	private void IJJIIIIJIIIJIIIJJJJJJIIJIIJIJIJIJJJJIJIIIIIIJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 JJJIIJIIIIIIJJJIIJJJJIJIIJJIJIIIIJJIIJJJJJJJJJI)
	{
	}

	private void IJIIJIIJIJJIJJIJJJIJIIJIJJIJJJJJJIIIJJIIJJIJJIJ()
	{
	}

	private void IIJJIJIJJJJJIJJIIJIJIJJIIJIJIIJJIIIJJIIIJIIIJJI()
	{
	}

	private void JJJJJJIIJIIIIIJJJJIIJJJIJJJJJIJJIIIJIJIIIIIJIII()
	{
	}

	private void IJIJIJIIJJJJIJIJJIJJIIIIIIJJIJIIIIIIJIIIJIIIIJJ(int JJJJIIJIIJIIIIJIIJIIIIJJJIIJIIJIIJIJIJIJJJJIIIJ, string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public void OpenCase()
	{
	}

	private void JIJIJJJJIIJIJJJJJIIJIJJIIIIJIJIIJJIIIIJJIIIJIJI()
	{
	}
}
