using System.Runtime.CompilerServices;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mCaseMoneyGoldManager : MonoBehaviour
{
	private static mCaseMoneyGoldManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private bool IIJJIIIIJIJIJJJJIIIJIJJJJJJJJIIJIIIJIIIIIJJJIJJ;

	private int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI;

	private void IJIJIJIIJJIIIIIJIJIJJJJJIIIIJJIIIJJJIIIJIJJJJIJ()
	{
	}

	private void JJIJIIJJJIJJIIJJIIJJIIJIJIIIIJIJIJJIIJIIJJJJJII()
	{
	}

	private void JIJJIIIJJIJIJJJIJJJIIJJJJJIJJJIIJJIJIIJIIJIIJJJ()
	{
	}

	private void IIIIIJIJJJIIJIJJIIJJIIIIIIJJIIIJIJJIIJIJJJIJIII()
	{
	}

	private void JIIJIJIIJJIIIIIIIJIJJJJJJJIJJJIJJIJIIIJIIIIIIIJ()
	{
	}

	private void IJJIIIIIJIJIJJIIJIIJIJJIJIIIJIJJIJIIIJIJJJJJIIJ(bool IJIIIJIJIJIJIIJJJJIIJJIJJIIJIIIIIIIJIJIIIIIJIJJ, int JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	private void Start()
	{
	}

	public static void JJIIJJIJIJJJIIIJIJIJIJIJJIIJJJJJIIJIIJJJIIIIJIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	[CompilerGenerated]
	private void JIJIJJJIIJJIIIIJIIIJIJIJJIIJIIJJIIIJIJIJIJIJIJI()
	{
	}

	private void JJJIIJIIJJIJIJIIJJJJJJIJJIJIJIIJJIJJJJIIJJJJJJJ()
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void JIIIJJJJJIIIJIJJIIJIIJIJJIJJJIIJJIJIJIIJJJJJIJI()
	{
	}

	public static void JIIIJIIJIIJIJJJIIJIJIIIJIJIJJIIJJIIJIIIJIIJJIII(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private void JIIJJJIJIIIJJIJIIJIIJJIJIJJJJIJIIIIJJIIJJIIJJJI()
	{
	}

	private void IIJIJIJJJIJJIJIIJJJJJIIIJIJIJIIIJJJIIIJJIJIJJII(bool IJIIIJIJIJIJIIJJJJIIJJIJJIIJIIIIIIIJIJIIIIIJIJJ, int JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
	}

	private void IIIJJIIIJIJJJJJIJJJIIJIJJIJJJIJJJJIIJJJIJIIIIJJ(bool IJIIIJIJIJIJIIJJJJIIJJIJJIIJIIIIIIIJIJIIIIIJIJJ, int JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
	}

	private void JJIJJJIIIIIIIJIJJIIJIJIIIIJJIJJIIIJIJJIJIIIIJIJ()
	{
	}

	public static void IJIJJIIJIJJIIIJJIIIJIJJJJIJJJIJJIJJJJIIJJJJJJJI(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	public static void JIJJIJJIIJIIJIJIIIJIJJIIJIIIIJIIIJIIIIJIIJIIJJI(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}
}
