using UnityEngine;

public class mCaseIconManager : MonoBehaviour
{
	public Texture2D[] IJJIJIIJIJIJIIJIJJIJJJJIIJJJJIIJIJIJJIJIIIJJJJJ;

	public Texture2D[] IIIIJJIJJJJJIIIJJJJIIJIJIJJIIJIIJJJIIJJJJIIIJJI;

	public Texture2D IIJIJJIIJJIIIIJIJIJJIJIIJJIIJJIIIIJJIJIIJJIIIJJ;

	private static mCaseIconManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static Texture2D IJJJJIIIIJIJIJJIIIIJIIJIJJIJIIJIIJJJIJIIJIJIJIJ(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, int IIJJJJJIIIIJIIJJJIIJIIIJIIIIJIJJJJIIIIJJJJJJJJI)
	{
		return null;
	}

	public static Texture2D IIIIJJIJIIJIJIIJIIJIIIJIJJIIJIJIJJIIJJIJIJJJIIJ(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, int IIJJJJJIIIIJIIJJJIIJIIIJIIIIJIJJJJIIIIJJJJJJJJI)
	{
		return null;
	}

	public static Texture2D JJIIIJJIIIIIIJJIIJIJJJJIJJIJJJJJJJIIIIIJJJIJJII(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, int IIJJJJJIIIIJIIJJJIIJIIIJIIIIJIJJJJIIIIJJJJJJJJI)
	{
		return null;
	}

	public static Texture2D JJJIJJIIJIIJIJJIJJJIIIJJJIIJIIJJJJJJIJIJJIJIJJJ(int JJJJIJIJIIIJJJIIJJJJJIIJJIJIIIIJIIIJIIIIJJIIJJJ)
	{
		return null;
	}

	public static Texture2D JJJIIJIJJIJJJJJIIJIIJIJIJIIIIIIJJJJIIIIIIIJJIIJ(string IJJIJIJIIIIJJIJIIJJJIJIJJIIIJJIJIJJIJJJJIJIIIJJ)
	{
		return null;
	}

	public static Texture2D IIIIJJIJIIJIJIIJIIJIIIJIJJIIJIJIJJIIJJIJIJJJIIJ(string IJJIJIJIIIIJJIJIIJJJIJIJJIIIJJIJIJJIJJJJIJIIIJJ)
	{
		return null;
	}

	public static Texture2D IJJJIJJIJJIJIIJJJIIJJJJJJJJJIJIJIIJJJIJJJJJJIII(string IJJIJIJIIIIJJIJIIJJJIJIJJIIIJJIJIJJIJJJJIJIIIJJ)
	{
		return null;
	}

	public static Texture2D JJIIJIJIJIIJIJIJJIJJJIIJJJIJJIJIIJJIJJJIIJJIIII(int JJJJIJIJIIIJJJIIJJJJJIIJJIJIIIIJIIIJIIIIJJIIJJJ)
	{
		return null;
	}

	public static Texture2D JJIIJJJJJJIJIJIJIJJJJJIIIJIJJJJJIIJJJJIIJIJIIJI(int JJJJIJIJIIIJJJIIJJJJJIIJJIJIIIIJIIIJIIIIJJIIJJJ)
	{
		return null;
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	public static Texture2D IJJJJIIJIJIIJJIIIJIIIIIJJJIJJJJJIJIJIIIJJJIJIJI(int JJJJIJIJIIIJJJIIJJJJJIIJJIJIIIIJIIIJIIIIJJIIJJJ)
	{
		return null;
	}

	public static Texture2D IJJJIIIJJJJJIIIJJIJIJJIIJIIJIIJIIIJJJIIIIIIIIJJ(int JJJJIJIJIIIJJJIIJJJJJIIJJIJIIIIJIIIJIIIIJJIIJJJ)
	{
		return null;
	}

	private void Start()
	{
	}

	public static Texture2D JJJJIIJJIIJJJIJJJIJIIIJJJJJJJJIJJIIIIIJIJJJIJII(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, int IIJJJJJIIIIJIIJJJIIJIIIJIIIIJIJJJJIIIIJJJJJJJJI)
	{
		return null;
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	public static Texture2D IJJJIIIJJJJJIIIJJIJIJJIIJIIJIIJIIIJJJIIIIIIIIJJ(string IJJIJIJIIIIJJIJIIJJJIJIJJIIIJJIJIJJIJJJJIJIIIJJ)
	{
		return null;
	}

	private void IIJJIJIJJJJJIJJIIJIJIJJIIJIJIIJJIIIJJIIIJIIIJJI()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	public static Texture2D IJJJIJJJJIIIJIIIIJIJIJIJJIIIJIIIIIJIJJIIJJIJJII(string IJJIJIJIIIIJJIJIIJJJIJIJJIIIJJIJIJJIJJJJIJIIIJJ)
	{
		return null;
	}

	public static Texture2D JIIIIJJIIIIIIIJJIJJIJJIJJJIIIIJIIIIJJJIJJJIJIJJ(int JJJJIJIJIIIJJJIIJJJJJIIJJIJIIIIJIIIJIIIIJJIIJJJ)
	{
		return null;
	}

	public static Texture2D IIJIIIJIIJIJJJIIIIJIIJJJJJIIIJJIJIJIIJJJJJIIIIJ(string IJJIJIJIIIIJJIJIIJJJIJIJJIIIJJIJIJJIJJJJIJIIIJJ)
	{
		return null;
	}

	public static Texture2D JJIIJIIJJJIIJJJIIIIJJJJJJIIIJIIJIJIIIJIJJIJIIJJ(string IJJIJIJIIIIJJIJIIJJJIJIJJIIIJJIJIJJIJJJJIJIIIJJ)
	{
		return null;
	}

	public static Texture2D IIIIJJIJIIJIJIIJIIJIIIJIJJIIJIJIJJIIJJIJIJJJIIJ(int JJJJIJIJIIIJJJIIJJJJJIIJJIJIIIIJIIIJIIIIJJIIJJJ)
	{
		return null;
	}

	public static Texture2D IJIJJJJJJJIIJIJJIJIJIIIJJJIJJIJJIJIIIJIIIJJJJII(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, int IIJJJJJIIIIJIIJJJIIJIIIJIIIIJIJJJJIIIIJJJJJJJJI)
	{
		return null;
	}
}
