using System.Runtime.CompilerServices;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mCaseStickerManager : MonoBehaviour
{
	private sealed class JIIJJJIIIJIJJIIJIJJJIJIIJJIIJJIJIIIIIIJJJIJIJJJ
	{
		public mCaseStickerElement JIIIJIIJJIJJJJIJIIJJIIJJJIIJJJIIIJJJIJJJJIIIIII;

		internal void JIIIJJJIJJJJJIIIJIIIJJJJJJIJJIIIIIIIJIIIIJIIJJJ(int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
		{
		}

		internal void JJJIIJJJJIJJIIJIIIIIJIJIJIJIIJJIIJJJJIIJIIJJJJI(int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
		{
		}

		internal void JIJIIJIIIJIJIJJJIJIIIIJIIIJJIIIJJIIIIIJIJJIJIJI(int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
		{
		}

		internal void IJJIIIIIJIIIIIJJJJJIIIJIIIIIJJIIJJJIJJJJJIJJIIJ(int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
		{
		}

		internal void JJIIJJJIIIJIJJIJJJIJIJJIJJIJJJIJJJIJJJIIJIJIJIJ(int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
		{
		}

		internal void IIJIJJIIIIIJIJIIJJIIJJJIIJJJJIJIJIJIJIJJJJIJJJJ(int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
		{
		}

		internal void JIIIIIIJJIJJJIIIJIIIIIIJIIIIJJIIJIJIIIIIIJIJJJI(int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
		{
		}

		internal void JIJIJIJIIJIIJIIIIJJIJIIIIJIIIJJJJJIJJIJJJJJJIJJ(int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
		{
		}

		internal void JJIIJJIJJIJIIJIIIJIIIJIIJJIJIIIIIJJIJIIIJIIJIII(int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
		{
		}

		internal void JJJJIJJJIJIJJIIJIJIJJJIIJJJIJIIIJJIJIJIIIIIIJJJ(int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
		{
		}

		internal void IJIJJJJIJIJJIJJJIIJJIJJJIIJJJJIJJIJJJJIIJIJIJJJ(int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
		{
		}

		internal void IIIJIJIIJJIJIJJIJIIJJJJIIJIJIIJIJIIJJIJIIIJIJII(int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
		{
		}

		internal void IIIIJIIJJIJJIJIJIJJIIIIIIIJIJIJIJIIJIJJJIJIIJIJ(int JJJIIIIJJJJIJJJJIJJIJJIJJJJIJJJIIIJIIIIIIJJIJJI)
		{
		}
	}

	public GameObject JIIJJIIIIJJJIIJIJJJJJIIJJIIIJJJIJIJJJJIIIIJIJIJ;

	private int IJJIIIJJIJIIIJIJJIJJJIJIJJJIJJIJIJIJIJJJJIJIIJJ;

	private static mCaseStickerManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void JJIIJIIJJIIJJIJJIJJIIJJJJJJIIIJIJIJIJJJJJIIJIJI()
	{
	}

	private void JJIJJJIIIIIIIJIJJIIJIJIIIIJJIJJIIIJIJJIJIIIIJIJ()
	{
	}

	public void IJIJIJIJIIIJJIJJIIIIJIIIIJIIJIJJIIJIIIIJJIJIIII()
	{
	}

	private void IJJJJJIJJJJIJIIIJIIJJJIJIJJIJIIJIIIJJJJJIJJIIJI(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private void Start()
	{
	}

	private void JJJJJIIIJJJIJJIIJJJJJIJIIJIJIJJJIIJJIIJIIIJIJJJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private void IJJIIIIIJIJIJJIIJIIJIJJIJIIIJIJJIJIIIJIJJJJJIIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private void IIIJIIIIIJJIIJJIIJIIJJIJIJIJJIIIIIJJIIJJIJJIJIJ()
	{
	}

	public void JJIIJIJJIJIJJJJIIJIIIJIJIJIJJIJIIIIJJJIJIJIIJJJ()
	{
	}

	private void JJJIIJIIJJIJIJIIJJJJJJIJJIJIJIIJJIJJJJIIJJJJJJJ()
	{
	}

	public static void JIIIJIIJIIJIJJJIIJIJIIIJIJIJJIIJJIIJIIIJIIJJIII(mCaseStickerElement JIIIJIIJJIJJJJIJIIJJIIJJJIIJJJIIIJJJIJJJJIIIIII)
	{
	}

	[CompilerGenerated]
	private void JJJJJJJIJJJJIJJIJJJJJIJIJIIIJIIJIIIJJJJJIIJIIJI()
	{
	}

	private void JIIIIJJIJIIJIJJIJJJIIJJJJJIIJIIJJIJIIIIJIIIJJIJ()
	{
	}

	private void JIJJIIIJJIJIJJJIJJJIIJJJJJIJJJIIJJIJIIJIIJIIJJJ()
	{
	}

	private void JIIJIIJIJJIIIJIIJIJIJJIJJJIIJIJJJIJIJIIJJIJJIJI()
	{
	}

	private void IIIIIIJIIJIJJJIJIIIJJIIJJIIIJIJJJJIJJJIIIIIIIJI()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}
}
