using UnityEngine;

public class mCaseSkinElement : MonoBehaviour
{
	public int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ;

	public UILabel IJJJJIIIJIJJJJIIJJJIJJIIJIIJJJJJJIIIIJJIIJIIJIJ;

	public UITexture JIIJJIIIIIJJIIJIJIIIIIIIIIJJJIIJIJJJIJJJIIIJJJJ;

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void Start()
	{
	}

	public void JJIJJJIIIJIJJJIJIIIIJIIJIJIJJJIJJJJJIIJIIIIIIJI()
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	public void JJJIJIJIJJJIJJIJIIJIJIJJJJJIIIJIIIIJIJJIJJJIIIJ()
	{
	}

	public void OnClick()
	{
	}

	public void IJIIJJIJIIJIIJIIIJJJIJJIIIIJIIIJIIJJJJIIJIJJJIJ()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	public void IJJJIJJIIJIIIJIIJJJJIIJJJIJJIJIJJJIIJIIIIIJJJII(int JJJJIJIJIIIJJJIIJJJJJIIJJIJIIIIJIIIJIIIIJJIIJJJ)
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	public void JJJIJJJIIIJIJIJIIIIIJJJJJJJJIJJJIIIIIJIIJJJJJIJ()
	{
	}
}
