using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mCaseStickerElement : MonoBehaviour
{
	public int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ;

	public string IJJJJJIIIIIJIJJJJJIJIJIJJJIIIJIJJIJJJIJIJJJIIII;

	public JJJJJJJIIJIIJIIIJJIIJJJIIJIIIIJJJJIJIJJJJJIJJJI JIJIJIIJIIIJJJIIIIJJJIJIIJJIJJJIJJIJJJIJJIIJIIJ;

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIJJIIIJJJJJIIJJIIIJJIIJIIIJJJJJJIIJIJJIJJJIJIJ;

	public UILabel IJJJJIIIJIJJJJIIJJJIJJIIJIIJJJJJJIIIIJJIIJIIJIJ;

	public UILabel IIIIIIJIIJIJJIJJJJJIJIJJIJJIJJJIIIIJJJJIJJIIJJI;

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JJIJIJJIJIIIIJJJIJIJJIJJJJIIIIJJIJJIJIJIIIJJJIJ;

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IIIIIJIJJJJJIIIJJIJJJJIIJJJJJJIIIIIJIIJIJJJIJIJ;

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JJJJJIIJIJJIJIIJIIJJJJIIJIJIIJJJJJJJIIJIJIIIIJJ;

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	public void IJJJJIJIJIJJJIIJJIJJJJIJIJIJIIJJJIIIIIIJJJIJJJI()
	{
	}

	private string JIIJJIJJIJIIJIIJJIIJJJIJIIJIJIIIJJIIIJJIJJIJIJI()
	{
		return null;
	}

	private string JIJIIJIIIIIJJIIJIIIJJIIJJIIJJJJIJIIIJIIIJIIIJII()
	{
		return null;
	}

	public void IJJIIIIJJJIIIIJJIIIIIJJJIIIIJIJIJIIJJJIJIIIIJII()
	{
	}

	private string IJJIIJJIIIJJJIJIJJJJJIJJJJJJJIIJJIJIIJIIJJJIJJJ()
	{
		return null;
	}

	private string JIIJJIJIIJIIIJJJJIJIIIIIJJIJJJIIIJJIIJJIJIJJJJJ()
	{
		return null;
	}

	private string IIJIJIJIJIJIIIJIJIJJIIJIJIIJJIIJIJIJIJJIJJJJIJI()
	{
		return null;
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void Start()
	{
	}

	public void OnClick()
	{
	}

	public void IJIIJJJJIJIJJJIIIJJIIJIIIJJJIIJIIIIIIIIJJJJIJJI()
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	private string JJIJIIJJIIJIIJJIIJJJIIJIIIIIIJIJIJIJJIJIJJIIJIJ()
	{
		return null;
	}
}
