using UnityEngine;

public class mCaseWheelItem : MonoBehaviour
{
	public UISprite IIJJIJIIJIIIIJIJJIIJJIJIJJIJJIIJJJJIIIJIIIJIIJJ;

	public UISprite IIJJIIJIJJJJIJIJJIIJIJJJJIJIIIJIJJJIJIIIIIIIIIJ;

	public UILabel IJJJJIIIJIJJJJIIJJJIJJIIJIIJJJJJJIIIIJJIIJIIJIJ;

	public UILabel JJIJJJIIIIIIIJIIJJIIJJIIJJJIIJIJIJIIJJJJJIIJJIJ;

	public UISprite IJIIIJJJJJJIIJJJIJJJJIJIJIIJJJJIIJJJIIIJIIIIJIJ;

	public UITexture JIIJIJIJJJJJIJJJJIJIIIIIIJIIIJIJIJIJIJJIIIJJIJJ;

	public UITexture IIIIJIJIJJIJJIJIIJJIIIIJJJIIIIJJIIIIJIIJIIIIIII;
}
