using System.Collections.Generic;
using System.Runtime.CompilerServices;
using BestHTTP.ServerSentEvents;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mChatManager : MonoBehaviour
{
	public UIInput JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI;

	public UITextList JJIIJIIIIIJIJJJJJJIJIJIIJJJJJJJIIIIJIJJIJJIJIII;

	private float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

	private float JIIJJIJJIJJJIJIJJIIJJIIJJIIIJJJIIJIJJIJIJJJJJJI;

	private EventSource IIIJIIJJJIJIJIIJIIIJJJIIIIIIIIIIIIJIJJIIIJIIJII;

	private IJIIIJIIJJJJJJIJJJIIJJJIIIIIIJIJIJJJJIIJJIIJIII IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ;

	private bool IIIJJIIJJJJJIJIJJJJJIIIIIJIIJIJJIIJJIJJJJJIJJJI;

	private List<string> IIIIJJJJJIJJJJJIIJJIJJIJJIJJIIJIIJIIIIIJJJJIJJJ;

	private bool JIJIIIJJIJJJIJJIJIJIIJJIJIIJIIIJJJIJJJJIIIIIJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
		return false;
	}

	private bool IIIJIJIJIJIJIIJJJJJJIJIIJJIIIIJJIJJIIJIIIIIJJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
		return false;
	}

	private void IIJJIIJJJIIIIIIJJJIJIJIJJIIJJIJJIIIIIIJIJJJIJJJ(EventSource IIJJIJIJIIJIIJIIIIJIIIIIJIJIIIIIIIIIIJIJIJIJJIJ, Message JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void IJIIIIIIIJIIIIJIIJIIJJJIJJIJJIJJIIJIIIIIIJIIJJI(EventSource IIJIJIIJJJIJIIIJJJIJIIIIIIJJIIIJIIJJIIJIJIJJJIJ)
	{
	}

	private void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public void IJIIIIIIJIIJIIJIJIJJIIJJJIJIJJIIJIJIIIIIIJJIIJI()
	{
	}

	public void OnSubmit()
	{
	}

	public void IIIIIJIJIJJIIIJIIIJJJJIJJIIIIJIJJJIJJIIIIJJJIJI()
	{
	}

	public void JIJJJJIIIJIIJJJJJIJJIIJJIIIIJIJJJJIJJJIJIJJJJJJ()
	{
	}

	private bool JIIIIJJJJIJJIJJIJJJIJIIJIIJIJJIIIIJIJIIJJIIJIII(EventSource IIJJIJIJIIJIIJIIIIJIIIIIJIJIIIIIIIIIIJIJIJIJJIJ)
	{
		return false;
	}

	[CompilerGenerated]
	private void IIIIIJIJIIIJJJIJIJIJJIIJJJIIJJIJIIJJJJIJJIJIIJI(EventSource IIJIJIIJJJIJIIIJJJIJIIIIIIJJIIIJIIJJIIJIJIJJJIJ)
	{
	}

	public void JJIIJIJJIJIJJJJIIJIIIJIJIJIJJIJIIIIJJJIJIJIIJJJ()
	{
	}

	public void IJJIJIJJIJIJIJIIIIIIIJJJJIJJJJJJIIIIJIJIJIJIIJI()
	{
	}

	public void Open()
	{
	}

	private void IIJJIJJIIJJIIIJJIIJJIIIIJIIJIJIJJIIIJJJIJJIJIII(EventSource IIJIJIIJJJIJIIIJJJIJIIIIIIJJIIIJIIJJIIJIJIJJJIJ)
	{
	}

	private bool JIJJJJJJIJJJIIJIIJJIIJIJJIJJJIIIIIJJJIIJJJJIIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
		return false;
	}

	public void Close()
	{
	}

	public void JIJJIJIJJJIJJJIIJJJIJJIIJJJJJJIJJJIJJJJIJIIIIJJ()
	{
	}

	private bool JJJIJIIJIIJIIIJJJIIIIJIJJJIIIJJJIIJJIIIIIIIIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
		return false;
	}

	public void JIJIIJJIIIIJIJJJIJJJIIIIIJIIJIIJIJIIIIIJJJIIJII()
	{
	}

	private void JIIIIJIIJJIIJIJJIJJJJIJIJIIJIJIIJJIJIIJJIIJJIII(EventSource IIJJIJIJIIJIIJIIIIJIIIIIJIJIIIIIIIIIIJIJIJIJJIJ, Message JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}
}
