using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mChangeName : MonoBehaviour
{
	public static bool JIJJIJJJIIJJIIJJJJJJJIJJJIIIJIIIJJIIJJJJJIJIJIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IJIIJIJJJJIIIJJJJJIJIJIJIIIJJJJJIIJIJIIIIIJIJIJ)
	{
		return false;
	}

	public void JJIIIJJIJJIIJJJIJJJIJIJJJJJJIIIJIJJIIIIJJJJJJII()
	{
	}

	private void JJIJIIJIIJJIIJIIJJJIJJJIIIIJJJJJIIJJJJIIIJJIJJI()
	{
	}

	private void IJJJJIIJIJJIJIIJIJJIIJIIIJIIIJIJIIJJIIJJJIIJJJI(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
	}

	public static bool IIIIIIIJIJJJIJJJJIIIIJJIJJIJIIJJIIJIJJJJJJIIIJI(string JJIJIIJJIJJIJIJIIIJJJIJIJIJIIIJJJIJJIJIIIJIJIJI, bool IJIIJIJJJJIIIJJJJJIJIJIJIIIJJJJJIIJIJIIIIIJIJIJ)
	{
		return false;
	}

	public void JIJJJIIJJIJJJJIJIJJIIIIJIIIJIIJIIJJJJIIJJJIIJJJ()
	{
	}

	private void IJIIJIJJJIIIIJIIJJIJJJIJJIJIJIIIJIIJIJJJJIIIIIJ()
	{
	}

	private void IIIIIJIIIIIIIJJJJJIJJJJJJIIJJJIIIJIJIIJJIIIJJJI()
	{
	}

	public void JIIJJJIJJIIIIJIJJJIIIJJIIIJJIJJIJJJJJIJIIJJJIJJ()
	{
	}

	private void JJJIJJIJJJIJIIJIIJIIIJIIIJIIIIIIIIJJJIIJIJJIJJJ()
	{
	}

	private void IIIJIIJJJJIJIIJJJIJJJJIJIIJJJIIJIIJIIJIIJIJIIJJ()
	{
	}

	private void IJIIJIJIJJIIIJJIJIIIJIIIIJIJJJJIIJJJIJIJIIJIJIJ()
	{
	}

	public void IJIJIIJJIJJIIJIIIJJIIIJIJJIIIIIJIJJJJIJIIIJJIIJ()
	{
	}

	private void OnSubmit()
	{
	}

	private void JIIIIIJJJIIJIJJIIIJJIIIJJIJJIJIJJJIIJIIIIIJIIJJ(string JJIJJIJJIJJJIIJIJIIIJJIIJJIIJJIIJJJIIIIJJIIIIJJ)
	{
	}

	private void JJIIJIIJJJIJIIJJIIJJJJIIJIIIJJJJJIJIJIJJIJIJJJJ()
	{
	}

	private void JJJJIJJIJJJIJJIIIIIIIJIIJIJIIIIIIIJJJJJIIIJIIJI()
	{
	}

	private void IJJJJIJIJJIJIIJJJJJIIJIIIIJIIIJIJJJIJJJIIJJJIJJ()
	{
	}

	public static bool IIJJJJIJJIJIIIIJIIIIIIIJJJIIIJJIJIIIJJJIIIJJJIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IJIIJIJJJJIIIJJJJJIJIJIJIIIJJJJJIIJIJIIIIIJIJIJ)
	{
		return false;
	}

	private void JJJIJIIJIJJJJIJJIIIJIIIIIIJJJIIJIIJIJJIIIJIJJIJ(string JJIJJIJJIJJJIIJIJIIIJJIIJJIIJJIIJJJIIIIJJIIIIJJ)
	{
	}

	private void JJIIJJJJIIIIIIIIIJJIJJJJIIIJIJIJIIJJJJIIIIJJIJI()
	{
	}

	public static bool JIIJIIJJIJIIIJIIIJIIJIJIJIIIJIIIJJJJIJJJJIJIJII(string JJIJIIJJIJJIJIJIIIJJJIJIJIJIIIJJJIJJIJIIIJIJIJI, bool IJIIJIJJJJIIIJJJJJIJIJIJIIIJJJJJIIJIJIIIIIJIJIJ)
	{
		return false;
	}

	public static string IJJIJIJIIIIIJJJIIIJJJJJJIIJJIIJIJIIIIIIJIIIJJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IJIIJIJJJJIIIJJJJJIJIJIJIIIJJJJJIIJIJIIIIIJIJIJ)
	{
		return null;
	}

	private void IIIIIJIIIJIIJJJJIIIJJJIIJIJIJJIJJJJJIJIJJIJJIJJ()
	{
	}

	public static string IIIJIJJJIJJIJIJIJIJIJIIJJIJJIJJIIIIJIJJJIJIIIJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IJIIJIJJJJIIIJJJJJIJIJIJIIIJJJJJIIJIJIIIIIJIJIJ)
	{
		return null;
	}

	private void IJIIIJJJIIJJIIJJIJJJJIIIJJJJIIIJJJIJIJIIIJJJIJI(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
	}

	public void ChangeName()
	{
	}
}
