using UnityEngine;

public class mCheckCustomMap : MonoBehaviour
{
	private string JJIJJIJIIJJIIJJIJIJJJIIIJIIIIJJJIIIJJIIIIIJJJIJ;

	private void IIJJJJJIJJIIJIIJJIJIJJJIIJJJIIIIIJJIJJIIJJIJJJI()
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void IJJJIIIJIJIJJJIIJJJJJIJIJJIIJJJJJJJIIIIJJJJIIIJ()
	{
	}

	private void JIIIJIIJJJJIIJJJIIJJJIIIJIIIJIIJIIJIJJJIIIIJJIJ()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void IJIIJIIIJIIJIIJIJIJIIIIIIIJIIIIIIIJJJIIIJJJJIJJ()
	{
	}

	private void JIIIIJJIIJJIIJJJIIJJIIJJJIIJJIIIJJJJIIJJJJIJIIJ()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void IJJJIIJIIJJJIIJJJJJJIIIJJIJIIIIJJIIIJJJJJIIJJII()
	{
	}

	private void OnConnectedToPhoton()
	{
	}

	private void IIJIJJIIIIJJIIJIIJJIJIIIIIIIJJJJJJJJIIIJJIJIIJI()
	{
	}

	private void IJIJIIIJJIJIIJIJJJIIJJIIJIIJIJJIIJIJIIJJIJIIJJI()
	{
	}

	private void JIIIJIJJIJJIJIIIJIJIIIJIJIJIJIIIJJIIJIIIIJIIIJI()
	{
	}

	private void IIJIIJIJJIIIIIJIJJIJJJIIJJIJIJIJIIJJJIIJJIJJIII()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void Start()
	{
	}
}
