using UnityEngine;

public class mClanManager : MonoBehaviour
{
	private static bool JIIIJIIIIJIIJJJJIIJIJIIJJJIIJJIJIJIJJJIJIJIJIJI;

	public void JJIIJIJJIJIJJJJIIJIIIJIJIJIJJIJIIIIJJJIJIJIIJJJ()
	{
	}

	public void JIIJJIIJIIJJJIIJIJJJIIJJIIIIIIJIJJJIJIIJJIJJJIJ()
	{
	}

	public void JIJJIJIJJJIJJJIIJJJIJJIIJJJJJJIJJJIJJJJIJIIIIJJ()
	{
	}

	public void IJJJJJJIJJJJJIIIIIIJJIJIJJIIIIJJIIJJJJJJIIIJJII()
	{
	}

	public void IJJJIIIIIIJIJJIJIJIIIIIIJIIIJIIJJJIJJJJJJJJJIJI()
	{
	}

	public void JJJIJJIJJJJIIIJIIJJIJJJIIJIIJIJIIJJJJIJJIJIJIJI()
	{
	}

	public void Open()
	{
	}

	public void IJJIJIJJIJIJIJIIIIIIIJJJJIJJJJJJIIIIJIJIJIJIIJI()
	{
	}

	public void JIIIJIJIJIIJIIJJJIJJJJIJIIIIIIJIJJJJJIIIIIIJIII()
	{
	}

	public void IIIIJJIIJJIIJJJJJJJJIJIIIIJJIIJIIIIJJJJJJIIJIJJ()
	{
	}

	public void JIJIJIIJIJJJIJIJIJJJJIJJJIIIIJJIJJIIIIIIJJJJJJJ()
	{
	}

	public void JJIIJJIIIJJJJIJIIJJIIJJIIJIJIIJJIIJJIIIIJIJJJJI()
	{
	}

	public void JJJIIIIJJJJJIJJJJJIJIIJJIJJIJIIJIJJJIJIJJIIJJJJ()
	{
	}

	public void IIIIIJIJIJJIIIJIIIJJJJIJJIIIIJIJJJIJJIIIIJJJIJI()
	{
	}

	public void JJIJIIIJJJIIJJJIIJIJIIJJIJIJIJIIJIIJJIIIJIIIIJI()
	{
	}

	public void JIIJIIJJJIIJIJJJIIIJIJJIJIIJIIJJIIJIJJIIJIIJJJI()
	{
	}

	public void JJJIJIIIIIJIIJJIJIIJIIIJJJIJIJJJJJIJIJIJJIIIJII()
	{
	}

	public void JJIJIJIJJJJJIJJJIIIJJJJIJIIJIIIIIIJIJIJIIJIIJII()
	{
	}

	public void IIIJJIJJJJJJIIJJIJIIIJIIJIIIJIIIIJIIIJIJJIJIIJJ()
	{
	}

	public void IJJJIJIJJIJJJIJJJJIIIIJIJJIIIIJIIIIJIIJJIJIJJJI()
	{
	}
}
