using BestHTTP.ServerSentEvents;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mClanChat : MonoBehaviour
{
	public GameObject JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ;

	public UILabel IJJJJIIIJIJJJJIIJJJIJJIIJIIJJJJJJIIIIJJIIJIIJIJ;

	public UIInput JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI;

	public UITextList JJIIJIIIIIJIJJJJJJIJIJIIJJJJJJJIIIIJIJJIJJIJIII;

	private float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

	private float JIIJJIJJIJJJIJIJJIIJJIIJJIIIJJJIIJIJJIJIJJJJJJI;

	private EventSource IIIJIIJJJIJIJIIJIIIJJJIIIIIIIIIIIIJIJJIIIJIIJII;

	private IJIIIJIIJJJJJJIJJJIIJJJIIIIIIJIJIJJJJIIJJIIJIII JIJIIIIIJIIJIJIIJIIIIIIIIJJJIIJJIIIJJIJIIJIJJIJ;

	private bool IIIJJIIJJJJJIJIJJJJJIIIIIJIIJIJJIIJJIJJJJJIJJJI;

	private static mClanChat JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private bool JIIIJIJJIIJJIJJIJIJIIJJJJJIJJIJJIIIIJIJJJIIJIIJ(EventSource IIJJIJIJIIJIIJIIIIJIIIIIJIJIIIIIIIIIIJIJIJIJJIJ)
	{
		return false;
	}

	private bool JIIIIJJJJIJJIJJIJJJIJIIJIIJIJJIIIIJIJIIJJIIJIII(EventSource IIJJIJIJIIJIIJIIIIJIIIIIJIJIIIIIIIIIIJIJIJIJJIJ)
	{
		return false;
	}

	public void JIJIJIIIJIJIJIJIJJIIJJJJIIJJJJJIJJJJJIIIJIIJIJI()
	{
	}

	public void JJIJIJJJIJJJJIIJJJIJJJJIJIJIJIJJJJIIIJJJIJIJIJI()
	{
	}

	private bool JJIIJJIJJIIJIJIIJIJJIJIIJIIIJIJJIIIJJJJJIIJJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
		return false;
	}

	public static void IIJIIIIIJIJJIIIJIIIIJJJIJJJJJJIJIJJIJIIJJIIIIJI()
	{
	}

	public static void UpdateData()
	{
	}

	public void Close()
	{
	}

	public void OnSubmit()
	{
	}

	private bool JJJJJJJIIJIJIJIIIJIJIJJIIJJIJIJIIJIJJIIJIIIIJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
		return false;
	}

	private string JIIIJJJJJIJIJIIIJJJIJIJIJIJIJIJIIIIJJJJJIIJIIII(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}

	private void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void IJIJIJIJIIIJJIJJIIIIJIIIIJIIJIJJIIJIIIIJJIJIIII()
	{
	}

	private void IIJJIIJJJIIIIIIJJJIJIJIJJIIJJIJJIIIIIIJIJJJIJJJ(EventSource IIJJIJIJIIJIIJIIIIJIIIIIJIJIIIIIIIIIIJIJIJIJJIJ, Message JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private bool JIJJJJJJIJJJIIJIIJJIIJIJJIJJJIIIIIJJJIIJJJJIIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
		return false;
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void JJJJJJIIIIIJIJJIIIIJIIIJJJJIJJIIIJJIIJIJJJIJJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void IJJIIIJJJIJIJIJIIJJIIIJIJJJIIIIJJIJIJIIJJIIIIIJ(EventSource IIJJIJIJIIJIIJIIIIJIIIIIJIJIIIIIIIIIIJIJIJIJJIJ, Message JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private string IIJIJJJIJIJIIIIIIIJJJJJIIIIIIJIIIJIIJJJJIIJIJII(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}

	private bool IIIJIJIJJIJIIJIIIJIJJIIIJIIIIJIJJIIJJJIIIJIIIII(EventSource IIJJIJIJIIJIIJIIIIJIIIIIJIJIIIIIIIIIIJIJIJIJJIJ)
	{
		return false;
	}

	private void Start()
	{
	}

	public void JJIIJJIIJIIJIIJJIJIJJJIIIIIIIJIJIJIJIIIIJIIIJIJ()
	{
	}

	public static void JJJJIJIIIJIJIJJJJJIIJJIIIIIJJIIJJJJIIJJJIJIIIIJ()
	{
	}
}
