using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class mClanPlayers : MonoBehaviour
{
	private sealed class IJIIJIIJIIJIIIIJJJIIIJIJIIIIIIIJIJJJIIJJJIIIJIJ
	{
		public mClanPlayerElement IIIJIJJIJIIJIJJJIJIIIIJIIIJJIJIJIJJJJIJJJJJIIIJ;

		internal void IIIIJJIJJJIIJIIJIIJIIIIJJIJIIIJIIIIIJIIJJIJIJIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JJIIJJJJJIIIIIIJJIIIJIIIIIJIIIJIJIIJJJJJIIJIIJJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JJJIIIIJIJJIIJJJJJJJIIJIJJIIJIIIIIIJJJIIIJJIIJJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIIJJIIIIJJIJJIJIJJIJJJJJIJIIIJJJIIIJJJIJIIJJIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIIIIIIJIJIJJIIJIJIJJIIIIJJJIIJJIJJJJIJJJJIIJJJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JJIIJJIJIJIJJIIJJIIJJIIIIIJIIIIJIJJJIIIJJJIIIJI(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IJJJJIJIJIIJJJJJJIJIJJIIJIIIIJIIJJJIJIIIJIIJJJI(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIIJIIIJIIIJJIJJIIJIIIIJJIJJJIIJJJJIJIIJJJIJIJJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IJIJIIIIJJIIJIIJJIIIJJJIJIJJIIIIJJIIIIJJJJIJIIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIJJJJIIJJJJIJJIJIJJIJIJJJIIIJIIIJJIJIIJJIIJJIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IJJJIJJJIIIJJIIJIIIIJIJJIIJIIJJJIIJIJIJIIJIIIIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IJIIJIJJIIJIJIJJJIIJIJIJJIIJJJIIJIIIJJJIJJJJJII(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIJIIIIIJJIJIIIIIIJJIIJIIIIIIIIJIJJIJIJIJIIIJII(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IIJJIJIIIIIIIIJJJJIJJIIIJJIJIJIIJJIJJIIIJIJJIIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IIIIIJIIIIJIIJJIIIIJJIJJJJIJIIIJJIIJJIJIJJIJIII(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IJIJIJJJJJJIJIIIJJJJIIIIIIJIJIJJJIJIJJIJIIIIIJI(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IJJIIIIJJJJIIJIJJJIIJIJIIIIJJJIJJIIJJJIJIIIIIII(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIJIJIIJIIIIJIJJJJJIJIIIJIIJIIJJJJIIJIJIIIJIJJJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JJJIIIJJIJJIIIJIIIJJJIIJJIIIIJIIIJJIJJJJIIJJJII(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIIJJIJIJIJJIJIJIJJIJIIIJJJJIIIJIJJJJIIJJIJJJII(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}
	}

	private static Dictionary<int, string> IJIIIIJJIIJJIJIJIJIJJIIIIJIJJJJJIIIJIIIIJJJIIJJ;

	public GameObject JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ;

	public UIGrid IIIIIIJIJJJIIIIIIIIIJIJIIIIIJIIIJIJJJJIIJJJJIJI;

	public GameObject IIJIJJJIJIIJIIIIJIJIIJIIJIJJIIJIIJJJJJIJIJIJJIJ;

	public GameObject JIIJIIIJJIIJIIJIJJIIJJIJJJIJIIJJJJJJJJIJJJIJJJJ;

	public UIPanel JJIJJIIJIIIJIIJIIJJJJIJJIIJJIIIIIJJJJIJIJIIJJJI;

	public UILabel JJIIJJIJJJJIIIIIJIIJJIIJIIIJIIJIJJIJIJIIIJJJIII;

	public UILabel IIJJIIIJIJJIIJIIIJIIJIJIIJJIJIIJJIIJJIIJJJIJJII;

	public UILabel IJJJIJIJJJIIJJJJIJIIIJJIJIJJIJJIIJIJJJIJIJIIIIJ;

	public UILabel IIIJJJJJJIIIIIIIJJIIIIJIIIIJJJJJIIIJJJIJJIIIIII;

	public UILabel JIJIJJJIIIIIJIIJJJIIJJJIIJJIJIJJJIJIJJJIJJJIJII;

	public UILabel IIIJIIJJIIIIJJJIJJJIJJIIJIJIJIJJIIIIIJIJIIJIJJJ;

	public UILabel IIJJJJIIJJIJIIJJJJIJIIIIJIIJIJJJIJJIJIIJIIJIJJJ;

	public UILabel JIIIJJIJIJIIJJIIIJIIIJIIJJJIIJJIJIJJIIJJJJJJIIJ;

	public UILabel IJIJJIIJJJIJJJJJIJJJIJIJIJIJJIIJJJIJJJJIIJIJJII;

	public mClanPlayerElement IJIJJJIIIIJJJIJIIJIIIIIIIJJJIJIIIIIJIJIJJJJIIIJ;

	private mClanPlayerElement IJJIJIJJIJIIJIJJIIIIIJIJJJIIIJIIIJIJIJIIJJJIIIJ;

	private List<mClanPlayerElement> JIIJIJJJJJJJIJIIIJJJJJJJJIIJIJIIJIIIJIIIJIIJIJJ;

	private List<mClanPlayerElement> JIIJJJJIIIJIJIIJJIIJIJIJIIIJJJIJJIJIJIJJJIJIIJI;

	private static mClanPlayers JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	[CompilerGenerated]
	private void IIIJIIIJJJJIJJIJIJIJIIJJJIIJIIIJJIJJIIJJJJIJJJJ()
	{
	}

	private string JIIJIJJJJJJJIIIIIJIJIIIJJJJIJIJIIJJJJJIIJIIJJIJ(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}

	[CompilerGenerated]
	private void IJJJIIIIJJJJJJJJIIIJIIIIIIIIIJIIIIJJIIJJJJJJJJI()
	{
	}

	private void IIJJIIIJJJJIJIJJIIJIIJIIIIJIJJIJIJIJJJIJIIIIJIJ()
	{
	}

	private void IIIIJIJJIIJJJJJIIJIJJJJIIJJIJIJIJJJIIIJJJJJIJJI(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
	{
	}

	public void JJIJIIIJJIJJJIJJJIJJIJJIIIIJIJIJIIIJIIJJIIIIJJJ(int[] JIJJJIJJJJJIIJJJJJIIJJJIJIIIJJJIIIJIIJIIJIJIJIJ)
	{
	}

	public void JJJIJIJJJIJJJJIIIJIJJIJJJJIJIIIJIIIIJJJIJIJIIIJ()
	{
	}

	public void JJIJIIIIIIJIJJJJJIIJIJIIIJIJJJJIIJJIIJJIJIJJJIJ()
	{
	}

	public static void IIIIJIJJIIJJJJIIJIJIJIIIIIJJJJIJJJJJIIJIIIIJIJI(mClanPlayerElement IIIJIJJIJIIJIJJJIJIIIIJIIIJJIJIJIJJJJIJJJJJIIIJ)
	{
	}

	public void DeletePlayer()
	{
	}

	private void IJJJIIJJJJJIIJJJIJJJJIJJJJIJIJIIJIJJJJJIIIJJIII()
	{
	}

	public void JJJIJIJIJJIJJIIIIIIIIIIJJIJJJJJIJJIIIIIIIJIIIIJ()
	{
	}

	private void Start()
	{
	}

	private void IJJJJIJIJJJIJJIJIJIIIJJIJIJJIJIIJJJJIJJIIJIJIJI()
	{
	}

	public void IJJJIJJIIJIIIJIIJJJIJJIJJIIIIJJIJIJJIIIJIIIJJJI(int[] JIJJJIJJJJJIIJJJJJIIJJJIJIIIJJJIIIJIIJIIJIJIJIJ)
	{
	}

	public void Open()
	{
	}

	public static void JJJJJJIJIIIJIJIJIIJIIIJIJIIJIIJJIIIJIIJIIJJJJIJ(mClanPlayerElement IIIJIJJIJIIJIJJJIJIIIIJIIIJJIJIJIJJJJIJJJJJIIIJ)
	{
	}

	public void JJIJIJIJJJJJIJJJIIIJJJJIJIIJIIIIIIJIJIJIIJIIJII()
	{
	}

	public static void JIJIIJJIIIJIIJJIIIJIIIIIIIJJJJJIIJJIJJJIJIJJJII(mClanPlayerElement IIIJIJJIJIIJIJJJIJIIIIJIIIJJIJIJIJJJJIJJJJJIIIJ)
	{
	}

	private void JIIIIJJIJJJJIIIJIJIIJJJJJJIIIJIIJJJIJJJJJJJIJIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
	{
	}

	public void IIIIIJJIIIIJIJJIJJIJJIJIIIIIJJIJIIIJJIIJJIIIIJJ(int[] JIJJJIJJJJJIIJJJJJIIJJJIJIIIJJJIIIJIIJIIJIJIJIJ)
	{
	}

	[CompilerGenerated]
	private void IIJJIIJIIJIIJJJIIJIJJJJJIIJJJIIIIJJJJIJJIIIIIJJ()
	{
	}

	public void IIIJIIIIIJIIIJJJJIJJJJIJJJIJIIJJJJIJIIJIJIJJIIJ()
	{
	}

	private mClanPlayerElement IIIIIJIIJIIJIIIJJJJJIIIJIIJIIIIIJJIIJJJJJJJIJIJ()
	{
		return null;
	}

	private string IIJIJJJIJIJIIIIIIIJJJJJIIIIIIJIIIJIIJJJJIIJIJII(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}

	public void LeaveClan()
	{
	}

	[CompilerGenerated]
	private void IJIJJIIJIIIJJJJJJJIIIJJIJIIIJJIJIJJJIIIJJIJIIII()
	{
	}

	public static void JIJIIJJIIJJJJJIJJJJJIIJJIJIIJJJJIIJJIJJIIJIJJII(mClanPlayerElement IIIJIJJIJIIJIJJJIJIIIIJIIIJJIJIJIJJJJIJJJJJIIIJ)
	{
	}

	public void IIJJIJIIJIIJIJIIIJJJIJJIIJJIIJJIIIIJJIIIIJIJJJJ()
	{
	}

	[CompilerGenerated]
	private void JIIIIIJIJJIJIIJJIIJIIIJIJIIIIIJJIIIIIJJJJIJIIIJ()
	{
	}

	public void IJJJIJJJIJJJIIIIJIJJJJIIJJIJIJJIJIIIIIIJIJIIJIJ(int[] JIJJJIJJJJJIIJJJJJIIJJJIJIIIJJJIIIJIIJIIJIJIJIJ)
	{
	}

	[CompilerGenerated]
	private void IIIJJJJJIJIIIIIIJJIIJIJIJJIIJIJIIIJIIJIJIJJIJIJ()
	{
	}

	private mClanPlayerElement IJJJIIIJJJIJJJIJJJJIIIIIIIIJJJIJIIJJJJJJJJIIJJI()
	{
		return null;
	}

	private void JJIIIIJIIIJIIIIJJJIJIIJIIIIIIIIJIJIIIIJIJJJJJJJ()
	{
	}

	public void JJJJIIIIIIIJJIJJIIJJIIIIIJIJIIIJJJJJIJJJJIIJJIJ()
	{
	}

	[CompilerGenerated]
	private void IJIJJIIJJIJIJIIIJIIIJIIIJJIIJJIIIIJIIIJIJIIIJJJ()
	{
	}

	public void DeleteClan()
	{
	}

	private string JIJIJIJIIJJJIIIJJIIIIJJIIIIIJIJIJJJIJJIIJIJJJII(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}
}
