using System.Runtime.CompilerServices;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mClanCreate : MonoBehaviour
{
	public GameObject JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ;

	public UIInput IJJIJJIIIJIIIIJIJJJIIIJJJIIIIJJJIJIIJIIJJJIIJIJ;

	public UIInput IIJIJIIIIIIIIIIIIIIJIIJIJIJIJIIIJJJJJIJJIIIJJIJ;

	private static mClanCreate JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	[CompilerGenerated]
	private void JIJIIJJIJJJIJIIIJIIIIIJIJIIJIIIJJJIIIJIJJIJIJII()
	{
	}

	public void JJJJIJJJJIIJIIIIJIIJIIJJJIIIJJIJJJJIIJIIIJJIJIJ()
	{
	}

	private void JJIIIJJIJJIJIIIJJIJJIJIJJJJJJJIJIIJIIJJIJIIJJII()
	{
	}

	public static void IJJJIJIJJIJJJIJJJJIIIIJIJJIIIIJIIIIJIIJJIJIJJJI()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	public void JIJJIIJJJJIIIIJIJJJIJJIIIIJIIIJIJIJIIIJIIJJIIJJ()
	{
	}

	public void CreateClan()
	{
	}

	private void IJIJJJJIIIIJJIIJIJJIIJJIIIIJIJJIJJJIIJIJJJJJJIJ()
	{
	}

	public void IIIJIJIJJIIIJIJJIJIJJJJIJJIJJIJJIJJIIJJIJIJIIII()
	{
	}

	public void OnSubmit()
	{
	}

	private void Start()
	{
	}

	private void JJIJJIIJIJJJIIIIIIIIJIIIJJIIJIJJJIIJIJIIIIJIJII()
	{
	}

	public static void IJIJIJIJIIIJJIJJIIIIJIIIIJIIJIJJIIJIIIIJJIJIIII()
	{
	}

	private void IIIJJIIJJIIIJIJIIJIJIIIIIIJIJIIIJIJIIJJIJJJIIJJ()
	{
	}

	public void IJIIJIJJJIIJJIJJJJIIIJJJIIIIIJJIJJJJIJJIIIJIJJJ()
	{
	}

	private void IIIJJJJJIJIJJJIJJIJJJJIJIJIIJIJJIIIIIIIJIIIIJJJ()
	{
	}

	public void IIIJJIJIIIJJIIIJIJIIIJJJIJIIIIIIIJJJJJIJIJIJJII()
	{
	}

	public void Close()
	{
	}
}
