using System.Runtime.CompilerServices;
using UnityEngine;

public class mClanPlayerElement : MonoBehaviour
{
	public UIWidget IJJIIIIIIIJIIJJIJJJIJIJJJIJJIIIIIIIIIIIJJIIJIIJ;

	public UILabel IJJJJJIIIIIJIJJJJJIJIJIJJJIIIJIJJIJJJIJIJJJIIII;

	private int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ;

	public int IJJJIIJIJIJJJIIIIJJIIJJIIIIIIIIIJJIJIJIIJIJIIIJ => JJIJJJJJIIIJJIIJJJJJJIJIJJJJJIIIIIJIIIJIJJJIJJJ();
	public int JJJIJIJIIIIIJIJIJJJIIJIIJIJJJJJJIJJJJJIJJIJJIII()
	{
		return 0;
	}

	public void IIJJIJJIJIIIIJJJJJIJIJJJIJIIJJJIIIIIIJJIJIIJJIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private void IIJJIIIIJIIJJJJJIJIIIJJIJJJJIIIIIIIIIJIJIIIIIII()
	{
	}

	private void IIJJJJJIIJJJJJJJJJIIIIJIIJJJIIIIIJIIIJIIJIJJIJJ()
	{
	}

	private void OnClick(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}
	public int JIIIIIJJJJIJJIIIIJJJIJIJIIJIJIIJIJIJIIIIJJIJJJI()
	{
		return 0;
	}

	private void OnEnable()
	{
	}

	private void IIJJJIJIIIJIIIJJJJIIIIJIJJIJIIIIJJJIIIJIIIIIJII()
	{
	}

	private void JIJIJIIIJIIJJIIIIIJJIJIIIIJJJIJIJJIJIJIIIIJIJJI()
	{
	}

	private void JIIIIJIJIIJIJJJIJJIIJIIJIJIIJIIJJIJJJIJIIJIJJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void JJJIIIIJIIJJIIJIIIJJJIIJIIIIIJIJJIJIIIIJIJJIIJJ()
	{
	}
	public int JJJIJIJIJJJJIIJIIJJJJIIJJIIJIJJJIJJJJIIIIIIJIII()
	{
		return 0;
	}

	private void OnDisable()
	{
	}

	public void IIJJIIIJIIJIJIIJIIIIIJJJJIIJIIJJIIJJIIIIJIJIIJJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}
	public int JJIIJJJJIIJJIJIIJIIIIJIJJJJIJJJIJIJIIIIJIJIIIJJ()
	{
		return 0;
	}

	private void IJIJJIIJJIIJIIJJJJJIJJJJIJJJIJJIJIIJJIIJJIJIIJJ()
	{
	}

	public void IJJIJJJIJJJJIIJIIIIIJIIJJIJJJJIIJJIIJIJJIJJIJIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	public void IJIIJJJIIJJIJJIIIJIIJJIJIIIIJJJIIJJJIJJIJIJIJIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private void JJJIJJJIIIJIJIJIIIIIJJJJJJJJIJJJIIIIIJIIJJJJJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}
	public int JJJJIIIIJJIIJIJJJIIIJJIJIJIIJJJIIIIIIJIJIJJJIJI()
	{
		return 0;
	}

	public void IJIJJJJIJIIIIIIIJIIIIJJIJJJIIIJJIJJJIIJJIIJJJII(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}
	public int IJJJIIIJIJJJJIJJJIIJJIJIJIIIJIIJJJIJJJJIIJIIIII()
	{
		return 0;
	}

	public int JJIJJJJJIIIJJIIJJJJJJIJIJJJJJIIIIIJIIIJIJJJIJJJ()
	{
		return 0;
	}

	private void IIJJJIJJJJIIIJIJIIJJIIIIIJJJIIIIIIJIIIJIJIIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void IJIIJJIJIIJIIJIIIJJJIJJIIIIJIIIJIIJJJJIIJIJJJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}
}
