using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mCraftingManager : MonoBehaviour
{
	private sealed class JJJIJJJJIIIJJIJJIJIJIJJIJJJJJJJJIIIIJIJIIIJIJJI
	{
		public JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ;

		public mCraftingManager JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		internal void IIIJIIJJJIJIJIIIJJIIJJJIJJJJIJIJJJJIIIIJJJJJIJI()
		{
		}

		internal void IJJJIJJJIIJJIIIIJIIIIJJIJIJIIIIJJJIIJJJIJIIIJJI()
		{
		}

		internal void IJIJIJJIJIJJJJIIJJIIIIIJIJIIJJIJJIJIJIJIIJIJIIJ()
		{
		}

		internal void JJIIJJJJJIIJJIJIIIIIJIIJJIIJJJJJIJIJIIJJJIIJJJJ()
		{
		}

		internal void JIIJIJIJJIIIIIIIJIJIIIJIJJJJIIIJJIIJJJIJIJIIJIJ()
		{
		}

		internal void JIJIIJIIJIJIJIJIIJIIIJJIIIJJIIIIJJJIJIJJIJJJJII()
		{
		}

		internal void JJIJJJJJIIJJIIJJJJJIJIIIIIJIIIIIIIJJJIIJJJJIIIJ()
		{
		}

		internal void JIJIJIJIIJIJIJJIJJJJIJJIIIIIJJJIIJIJJIIIIIJJJJJ()
		{
		}

		internal void IJJJIIIIJIIIIJJJJIIIJIIIIIIJIJIJIJIIIJIIIIIIIIJ()
		{
		}

		internal void JJJJJIIJJIIJJIJJJIJJJIIJJJIJJJIIJJJJIJJJJJJIIII()
		{
		}

		internal void JIIIJJJJJJJIIIIJIJJJIIIJIJIJIJIJJJIJJJJIIJJIJII()
		{
		}

		internal void JIIJJIJIJJIIJIJIJJIJIIJIJIIJJIJJIIJIIIJJIIIJJII()
		{
		}

		internal void IJIJIJIIIIJJIIJJIIIJJJIIIJJJJJJIIJJIIIJIJIIIIII()
		{
		}

		internal void IJIIIIIJJIJJIJJJIIJIIIIJJIJIIIIJIIJIIIJIJJIIIJJ()
		{
		}

		internal void IJIIJIIIIJIIIJIJIJJIIIJJIIJIIJJIJIIIIIJIIIIJIJJ()
		{
		}
	}

	public mCraftingElement[] IIJJIJIIIIIJJJJIJIJIJJIJJIIIJIJIIJJIIIJIIJJJJII;

	public UILabel IIIIIJJIIJJJIIJJJIJJJJIIIIIIJJIIIIIJJJJJJIJIJIJ;

	public UITexture IIJJJIIJIIJIJIIIJIIJJIJIJIJIJIJJJIIJJIJJIJIIJJJ;

	private List<JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII> IJJIJIIIIIIIJIJIJJJJJIJIJJIJJJJJJJJJJIIIJJJIJIJ;

	private int IJJJIIJJJJIIJIJJIIIJJJJJJIJIJJIJJIIJJIJIIIJJJJI;

	private List<JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII> IJIJJJJIJJJJIIJJIJJIIJIIIIIJJIJIIJIIIIJJJJIIIIJ;

	private static mCraftingManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static int JJIJJJIIJIJIJIIIJJJIIIJIJJJJIIJIIJJJIJJIJIJJIII => JIJJJJJIJIJJIJIJIJIJIIIJIIJJJIIIJJIJIJIJJJIJJII();

	public void OnLeftList()
	{
	}

	public static void IJJJIJIJJIJJJIJJJJIIIIJIJJIIIIJIIIIJIIJJIJIJJJI(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
	}

	public static void IJJJIIJIIJIJJIJIIJIJIJIJIIIJJIIIJJJIJIJIIIIJJJJ()
	{
	}

	[CompilerGenerated]
	private void IJJIJJJJJJJIJJJJIJIIJIIJJIJIIJIIJJJIIJIIJIIJJJJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
	{
	}

	public static void JIIIJIJIJIIJIIJJJIJJJJIJIIIIIIJIJJJJJIIIIIIJIII(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
	}

	private void Start()
	{
	}

	public static void JIJIIIJJIJIJJJIIIIJIIIJIIJJJIJJIJIJIJIJIIIJJIJI(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
	}

	public void OnRightList()
	{
	}

	public static void JJIJIJIJJJJJIJJJIIIJJJJIJIIJIIIIIIJIJIJIIJIIJII(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
	}

	public static void IIJIIJIIJIJJIJIIIJJJIJJIJJJIIIIIJJIJJIIJIIJIIIJ()
	{
	}

	public void JJJJJJIIJJJJJJIIIJJJIJIJJJIJJJIIJIJJJJJIJIJIJJJ()
	{
	}

	private void JJIIJJJIJIJIJJIIJJJJJIIJIIIJJJJJIJJJJJJIJIIIIIJ()
	{
	}

	public static bool JIJIIJJIIJJIJIJJIIIJIJIJIJJIIJJJIIJJJIIIJIIIJIJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
		return false;
	}

	private static void IIIIJIIJJJIJIIJIIJJJJJJIJIIIJIJIJIJJIIIIIIIJJIJ()
	{
	}

	public static void IIIJJIJJJJJJIIJJIJIIIJIIJIIIJIIIIJIIIJIJJIJIIJJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
	}
	public static int IIIJJIIJIJJJIJJJJJJJIJIIJIJIJJIIIJIJIIJJJIIJJJJ()
	{
		return 0;
	}

	private void IIIIJIJIIJIJIJJIJJJIIJJIIJIJIIIJIIJIJJIJJJJIJJI()
	{
	}

	public void IJIIJJJIIJIJIJIJJIJJJIIIJJJIIIJJJIIJIIIIIJJJIIJ()
	{
	}

	public static int JIJJJJJIJIJJIJIJIJIJIIIJIIJJJIIIJJIJIJIJJJIJJII()
	{
		return 0;
	}

	public void OnCraft()
	{
	}

	public static void IJIJIJIJIIIJJIJJIIIIJIIIIJIIJIJJIIJIIIIJJIJIIII(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
	}

	public static void IIIJJIJJJIIJIIIJJIJJIJIIIIIIIJJJIJJJJIIIJIIJJII(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
	}

	private static void IIJJIJJIIIJJIIIIJIJIJIIJJJIIIJJIIIIJJJJIJIJJJIJ()
	{
	}

	public static bool JJIJJIIJIIJIJJIJIIIIIJJIJIJJIJJIJIJJJIIJJIJIJIJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
		return false;
	}

	public static void JIJIJJIIJIJJIIJIIIJJJJJIIIJIIIJIIIJIIJJJJIIJIIJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
	}
	public static int IJIIJJJIIIIIJIJIJIIIJJIJIIIJIJJJJIIIIIIIIJJIIJJ()
	{
		return 0;
	}

	public static void IJIIIJIJIIJIJJIIIIIIJJIIJJIIIJJIIJIJJIJJJIJIJIJ()
	{
	}
}
