using System.Runtime.CompilerServices;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mCreateServer : MonoBehaviour
{
	public GameMode JIJJJIJJIJIIJIIIIJIIJIIJIJJIJIIIJJJJJJIIIJJIJIJ;

	public UIPopupList JIJJIIJJJJJJJIIIIJJIIIIIJJIIIJJIJJIIIJIIJIJIIIJ;

	public UIPopupList JIIJIJJJIIJJJJIJJJJJIIJJJJIIJJIIIIIIIJJJIIIIIIJ;

	public UIInput JIJIIIJIIIIJIIIIJIIJIIIJIJJJJJIIIIJJJJIJIJJJIJI;

	public UISprite[] IJJIJIJJIJIJJJJIIJIJJIJIJIIJIJJIIIJIIJIIJJJJIIJ;

	public int IIIJIIIJJJJJJIIJJJIIJJIJIIJIIIJIIIIIIIJJJIJJIJJ;

	public UILabel[] IIJIJJIIJJIIJJIIJJJJJJJIIJJJJIJJIIJJJIIJIIJIJIJ;

	public UIInput IIIIJJJJIIIIIIIJJJIIJJJJIIIIJJIJIJIJJJIJJIJIJII;

	public GameObject IIJIIJJIJIJIJJIJJIIIIIJJIJIJJIJJIIIIIIIJIJIJJJJ;

	public UIToggle JJIJJIJIIIJIJIIJIIIIIIJJJJJIIIIJJJIIJJJIIIIJIII;

	public static mCreateServer JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI => IJIJIIJJJJIIJJJIJJJIIIJIJJJIIIIJJJIIJIIIJJJJJII();

	public static string JJJIJIJJIIJJIIIJIJJIIJJIIJIIJJIJJIJJJIIIIIIJIJI => JJJIIIIJIJJJIJJIIJIJJIJJJJJIIJJJIJIJIIJJIJIJIJJ();

	public static string IIJIIIJIIIIJIIJJJIIJIJIIIIJJIIJIIIJJJJIJIJIJIII
	{
		get
		{
			return JJIJJIJIJJIJIJJJIJIIIJIJJIJJIIJIIJJJJIIJIJIIIII();
		}
		set
		{
			IIJIJJJJJIIIIIIJJIJJIIIIIJIJJJIJIIIJIIIJIIJJJIJ(value);
		}
	}

	public static int JJIJIJJJIIJJIJJJJIJJIIIJIJJJJIJJJJJJJJJIJIIJJJJ => IIIJIIIIJJJJJJIIIJJIJIIIJJJIIJJIIJJIJIIIJJIIJJI();

	public static string JIIIIJJJIIJIJJJIIIIIJIIJIJJIJIIJIJJJIJJIIIIIJJI => JIJJJIIJIIIJJJJIJIJJJJIIJIIJJJJJJIIJJJIIIJIJJJJ();

	public static bool IJIJIJIJIJJJJIJIIJJIJIIIJJIJJJIIIIIJIIIJJIIJJJJ => JIIJJIIIIJIJIIIIIIJIJJIIIJJJJJJJIIJJJJIIIIIJIII();

	public void IJIJIIJJIIIJJJJIJIIJIIJJIIIJIJJIJIIIIJIIIIJJIJJ(int[] list)
	{
	}

	public void CheckServerName()
	{
	}

	public void SelectGameMode()
	{
	}

	public static string JIJJJIIJIIIJJJJIJIJJJJIIJIIJJJJJJIIJJJIIIJIJJJJ()
	{
		return null;
	}

	public static GameMode IJIJIIJJJJIIJJJIJJJIIIJIJJJIIIIJJJIIJIIIJJJJJII()
	{
		return GameMode.TeamDeathmatch;
	}

	public static int IIIJIIIIJJJJJJIIIJJIJIIIJJJIIJJIIJJIJIIIJJIIJJI()
	{
		return 0;
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	public void CreateServer()
	{
	}

	public void SetMaxPlayer(GameObject go)
	{
	        if (go == null) return;
	        IIIJIIIJJJJJJIIJJJIIJJIJIIJIIIJIIIIIIIJJJIJJIJJ = int.Parse(go.name);
	        if (IIJIIJJIJIJIJJIJJIIIIIJJIJIJJIJJIIIIIIIJIJIJJJJ != null)
	        {
	            IIJIIJJIJIJIJJIJJIIIIIJJIJIJJIJJIIIIIIIJIJIJJJJ.transform.localPosition = go.transform.localPosition;
	        }
	}

	public static bool JIIJJIIIIJIJIIIIIIJIJJIIIJJJJJJJIIJJJJIIIIIJIII()
	{
		return false;
	}

	public static void IIJJJIIIJJIIIJIJIJIJJJJIIJJIIJIJJJJJIIIJIIJJJII()
	{
	}

	public void SetMaxPlayers(int[] list)
	{
	}

	public static string JJJIIIIJIJJJIJJIIJIJJIJJJJJIIJJJIJIJIIJJIJIJIJJ()
	{
		return null;
	}

	public void SelectMap()
	{
	}
	public static void JIIJJIJIIIIJIJJIJIIJIJJJIJIJJJJIIJJIJIIIIIJJJIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJIIJIIJJJIJJIJJJIIJIJJJIJJIIIIJJIIIJIJIJJJIJI(GameObject go)
	{
	}

	private void Start()
	{
	JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ = this;
	}

	public static string JJIJJIJIJJIJIJJJIJIIIJIJJIJJIIJIIJJJJIIJIJIIIII()
	{
		return null;
	}

	public void JJIJIJIIJIIJIJIIIIIIJJIJIIJIIIIIJIIJJIIIJIIIJII()
	{
	}

	public void IJJJIJIJJIJJJIJJJJIIIIJIJJIIIIJIIIIJIIJJIJIJJJI()
	{
	}

	private void IJIJIJJJIJIJJJJIJIJJJIJJIIJJIIIJJIJJJIIIIIIJJJJ()
	{
	}

	public void SetDefaultMaxPlayers()
	{
	}

	public void JIIIIJJIJJIIJIJIJIIIIIJIIIJIJJIJIJJJIJJJIIIJJJJ()
	{
	}

	public static void IIJIJJJJJIIIIIIJJIJJIIIIIJIJJJIJIIIJIIIJIIJJJIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIJIIIIJIIIIIIIJJIIIIIJJJJJJJIIJIJIJJJJIIIJJIJ()
	{
	}

	public void IIJJIJIJIIIJJIJJIJJIIIIJIJJIJIJJJJJJJJIIJJJIIII(GameObject go)
	{
	}
	public static GameMode JJIIIJIJJIJJIJIJJJJJIJJJJJIIIIIJJJIIIIJJJIIJJJJ()
	{
		return GameMode.TeamDeathmatch;
	}

	private void IJIIJJJJJIJJJJJIJJIJJJIIIIIJIJJIIIIJJIJIJJIJIIJ()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	public void Open()
	{
	JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ = this;
	}

	public void IIIIJJJIIIIJIIIJIIJIIJIJJIJIIIJIIJJJJIJJIJIJIII()
	{
	}

	public void JIIJIJJJIJIJJJIJIIIIIJJJIIIJJJJIIJIJIJJIJJJJJII()
	{
	}
}
