using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class MeshEditor : MonoBehaviour
{
	public Mesh JIIJIIIIIIJIIJIJIIIIIIIIIJIJIJIIJJIJIIJIJJIIJJI;

	private Mesh IIIJIJJIIIIIJIIJIJIIJIIJJIIIJIIJJIJJIJJJIIJJJIJ;

	private MeshFilter IIIJJJIJJJIJJJIJJIIJIIIJIJIIIIJJIJJJJJIIJJIJIJJ;

	public Vector3 IJJIIJJIIJIJIJIIIJIIJIIIIIJIIJIIIIJJIJJIJJIIIJJ;

	public Vector3 JJIJIJJIJIIIIIJIIJJJJJJIIIJIIIIIJIIJIIJIIJJIJJI;

	public bool IIIIIIIIJIJJIIIIIIIIIIIIIJIIIIIJIIIIIIIIIIJJIIJ;

	public bool JIJJJIIIIIIIIIJIIIJJIIJJJIJIJJIIJJIJIJJIJIJIJJJ;

	public bool JIJJJIJJJJIJIIIJJJJJJJJJIIJIJIIIIIIIIIIJJJJJIJI;

	public bool IJIIIIJJJJIJJIIIJIIIIJIIIJIIJJIJJJIJJIIJIIJIJII;

	public Rect JJIIIJIIIJJJIJJJIJJIIIJJIJJJIJJJJIJJIJJJJIIIIJI;

	public Color IIIJIJJIJIJIIIIJJJIJIIJIIJJIIIIIJIIJIJJJIIJIIJJ;

	private GameObject IIIJIJIIIIIJJIIJIIIJJJIIJIJIIJIJIIJJJJIJJJJIIII;

	private Transform JJIJIIJIIJJJJJIIIJIIIJJJIJJJIIIIJJIJJJIIIJJIIII;

	private MeshRenderer IJJIJIIIJIIIJJJJJIJIJJIJIJIIIIJIIIIJJIJIJJIJJII;

	public GameObject JIIIJIJJJIJJIJIJIIIJJJJIIJIJJJIIIJJIIIJIJIIJIII => JIJJIIJIIIJIJIIJJIJIJJJIIIJIIIJJIIIJIJJJIIIJJJJ();

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	public Vector3 IJIJIJIJJJIIJJJJJIJJJJJIJJIIJJJJJJIJIJJJJIJJIJI
	{
		get
		{
			return JIJIIJIIJIIJIIJJJIJIIIJIJIJJIIIJJIIJIJJJJJIJJJI();
		}
		set
		{
			IIIJIIIJIJIJIJIJJJIIIJJJIJIJJJJJJJJIIJJIIJIJJII(value);
		}
	}

	public Vector3 JJJJJIJIJJIJIJIIIJJIIIJJJIIIJJJJJJIIIJIJIIJJJJJ
	{
		get
		{
			return IJIJJJJJJIJJIJIJIJIJIIJIJIIJIJJIIIJIJIJIIJJIIJI();
		}
		set
		{
			IJIIJJJIIJIJJJJJJJIJJIJJIIIIIIIJIJJJJIIJJJJIJJI(value);
		}
	}

	public bool JIIJJJJJJIJIIJIJIIIIJJJIJIIIIJIIIIJIJIIJJJJIIJJ
	{
		get
		{
			return JJIJJJIJJIJIIIJJIIJJIIJJIJJJIJIIIIIIJJJIIJJJJIJ();
		}
		set
		{
			JJIIJJJIJJJJJJIIIIIIIJJJJJJIIIIIIIJJIIJIIIJIIJJ(value);
		}
	}

	public bool JIIIJIJIIIJJJJIIIJJJIIIIJIJJIIJIIJIJJIJIJIIJJJI
	{
		get
		{
			return JIIIIJJJIJJJJJJIJIIIIJJIJIJJIIJJJIIIJJIIJIJIJJI();
		}
		set
		{
			JIIIIJIJJIIJJJIIJIJIJJJIIJJJIJJJJIJIJJJJIJJIJJI(value);
		}
	}

	public bool IIIJJJIJIJJJJJJJJIJJIJIJIIIIIJJIJIIIJJIIIIJJJJI
	{
		get
		{
			return IIJIIIJJIIIIIJJJJIIIJIIIIJJIIJJIIIJJJJIIIJJJIIJ();
		}
		set
		{
			JJIJIIIIJIIJIIJIIIJJIIJJIIJIIIJJIIJIIIJIJIJJJJJ(value);
		}
	}

	public bool JIJJJJJJIJJJIJJJIIIJIIJJJIIIJIJIJIJJJJIIJIJJJJJ
	{
		get
		{
			return IJIJJJIJIJJJIJIJIJIJJIJIIIIJJIIJIIIJJJJIJIJJIII();
		}
		set
		{
			IIIJJIJIJIIIIJIJIJIIIJIIIJJIJIIIJJIJJIJJIJIIIJJ(value);
		}
	}

	public Color IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ
	{
		get
		{
			return JIIJJIIIIJIIJJJIIIIJIIJJIJIJJJJIJIJIJIJJJJIIJJI();
		}
		set
		{
			JIJIIJJJJJIIJJIJIJIIIIJJJIIJJIJJIIJJIJIIJJJIIII(value);
		}
	}

	public Rect IIIIIIIIIJIIIJJJIIJJJJIIIJIIJIIIIJJJJIJIIJJIIJJ
	{
		get
		{
			return JIJIJJJIIIIIIIIJIJIIIIIJIIJJIJIIJJJIIJJJIJJJIII();
		}
		set
		{
			JJIJIJIIJJIJJJIJJIJIIIJIIJIIJIJJJIIJIJIJJJJIIII(value);
		}
	}

	public MeshFilter JIJJJIJIJIJJJIJIIIIIIJIJIJJIIIIJJJJIIJIJJIIJIIJ => JIJJIIIIIJJIIIJJJIIJIJJJIIJJIIJIJJJIIJIJIIIIIJJ();

	public MeshRenderer JJJJJJIJJIJIIIJJJIIIJJIJIJJJIIIIIIIJIJJJIIJJIJI => JIIIIJJIIJIIJIJIIJIIIIIJJJJJIIIJIJIIJIIJJJIIJII();

	public MeshFilter JIJJIIIIIJJIIIJJJIIJIJJJIIJJIIJIJJJIIJIJIIIIIJJ()
	{
		return null;
	}
	public void IJIJJJJJIJIJJJIJIJJJIIIJJIJIIIJJJIIIJJJJJIIJJJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Color JIIJJIIIIJIIJJJIIIIJIIJJIJIJJJJIJIJIJIJJJJIIJJI()
	{
		return default;
	}

	public void JIIIIIIIIJJJIIIJJJJJJIIIJIIJJIIJIJIIJJJIIIJJIIJ()
	{
	}
	public bool JJIJIJJIJIIJIIIIIIJJIIIJJIIJJJJIIJIJIIIJIIJJJII()
	{
		return false;
	}

	public MeshRenderer JIIIIJJIIJIIJIJIIJIIIIIJJJJJIIIJIJIIJIIJJJIIJII()
	{
		return null;
	}
	public void IIIIIJJIJJJIJJJJJJIJJJIJIIJJJIIJIJIJIJJIIIIIJJJ(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public MeshFilter JIIJIIJJJJIIJIIJIIIIIJJIJJJJJJIIJIJIJIIIIJJIIII()
	{
		return null;
	}

	public void IJJIIIIJIIJJJIJJJIIJJIJJJJIJIIJJJJJJIJIJJJJIIJJ()
	{
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}

	private void Reset()
	{
	}
	public void IIIJJIIIJIIIIJIIIIJIIIJIIIIIJJJIJIJIIIIIIIJJIJI(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool JIIIIJJJIJJJJJJIJIIIIJJIJIJJIIJJJIIIJJIIJIJIJJI()
	{
		return false;
	}

	public void IIIJJIJIJIIIIJIJIJIIIJIIIJJIJIIIJJIJJIJJIJIIIJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJIIJJJIIJIJJJJJJJIJJIJJIIIIIIIJIJJJJIIJJJJIJJI(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJJIJJJIJJIJJIJJJIIIJJIJIJJIJJJJIJIJIIJJIIIJIJJ()
	{
	}

	public void IJJIIJIJIJJIJIJJIIIJIJIJIIIIJIIJIIJIJIIIJIIJJIJ()
	{
	}

	public Vector3 JIJIIJIIJIIJIIJJJIJIIIJIJIJJIIIJJIIJIJJJJJIJJJI()
	{
		return default;
	}
	public void IIIIIJIIJJJIIIJIIJIJJJJJIIJJIJJJJIJJJJJIJJIJIJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Rect JIJIJJJIIIIIIIIJIJIIIIIJIIJJIJIIJJJIIJJJIJJJIII()
	{
		return default;
	}

	public Vector3 IJIJJJJJJIJJIJIJIJIJIIJIJIIJIJJIIIJIJIJIIJJIIJI()
	{
		return default;
	}
	public bool JJIIJIJJIJJJIIJJJIJIJJJJJJIJIJIJIIIJIJJJJIJIIJJ()
	{
		return false;
	}
	public void IIJJJIIJIJJIJJIJJIIJJJJJIJIJIJIJIIIJJJJJIJIJIJI(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public bool JJIIIJIJJIJIJJIJIIIJIJIJJIIJIJJIIIJJIJJIIJJIJJJ()
	{
		return false;
	}

	public void JIJIIJJJJJIIJJIJIJIIIIJJJIIJJIJJIIJJIJIIJJJIIII(Color JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void IIIIIJIJIJIIIIIIIIJIIIIIJIIJIJJIJIIIJIJJJIIJIJI()
	{
	}

	public void JIIIIJIJJIIJJJIIJIJIJJJIIJJJIJJJJIJIJJJJIJJIJJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJIJIJIIJJIJJJIJJIJIIIJIIJIIJIJJJIIJIJIJJJJIIII(Rect JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJIIJJJIJJJJJJIIIIIIIJJJJJJIIIIIIIJJIIJIIIJIIJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool IIJIIIJJIIIIIJJJJIIIJIIIIJJIIJJIIIJJJJIIIJJJIIJ()
	{
		return false;
	}
	public MeshFilter IIJJIJJIIJIIJIJJJJJIIIJIJIIJJIIIJIIJJJJIJIJIJJI()
	{
		return null;
	}

	private void IIJJIIJJJJJJIJJIJIJIIIJIJIIJIIJIIJJJIIIIIJIIJIJ()
	{
	}

	public void IIJJIIIIIJIJJIJJIIIIIJJJIJIIJJJJJIIJIIJIIIIJIII()
	{
	}

	private void OnEnable()
	{
	}

	public void IIIJIIIJIJIJIJIJJJIIIJJJIJIJJJJJJJJIIJJIIJIJJII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJIIIJIIIIIIJIIJJIIJIIJIJIIJJIJJIJJIJIJJJIIIJII()
	{
	}

	public void IJJIJJIJJJIIJIJJJJJIIJJIIJJJIIJJIIIIIIJIJJJIJII()
	{
	}

	public void JJIJIIIIJIIJIIJIIIJJIIJJIIJIIIJJIIJIIIJIJIJJJJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool IJIJJJIJIJJJIJIJIJIJJIJIIIIJJIIJIIIJJJJIJIJJIII()
	{
		return false;
	}

	private void JIIIJJIJIIJJIJJIJIJIIIIJIIIJJJJJJJJIJJJJIIJIJJJ()
	{
	}

	private void JJIJIIIJIIIIIJJIIIIIIJJJJJIIJJJJIJJJIIIJJIIJJJI()
	{
	}

	public bool JJIJJJIJJIJIIIJJIIJJIIJJIJJJIJIIIIIIJJJIIJJJJIJ()
	{
		return false;
	}

	public void IIJIJJJJJJJJIJIIIJJIIJJIJIIJJJJIIIJIJJJIJIJJJIJ()
	{
	}
	public Rect IJIIIJJJIIIJJJIIJJIJJJIIJIIIJIJJIIJJIJJIJJIIIJJ()
	{
		return default;
	}
	public GameObject IIJJIIIIIIIIJIIIIJJJIJJJIJJJIIIJJJJJIJJIIJIIIIJ()
	{
		return null;
	}

	public void JJJJIIIIJJIIIJJIIJIJJIIJJJIIIIIIJJJIJIIJIJJJIJI()
	{
	}
	public void JIIJIJJJIIJJJIJIIIJJJJIIJJIJIJIIIIIIIJIIIJJIIJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public GameObject JIJJIIJIIIJIJIIJJIJIJJJIIIJIIIJJIIIJIJJJIIIJJJJ()
	{
		return null;
	}
}
