using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class MeshAtlas : MonoBehaviour
{
	public static UIAtlas IJJJJIJJIJIJIIJJJJJJIIIJJJIJIJIJJIIIIJJIJIIIIJJ;

	public static string JJJJJJIJIIJJIIIIIJIIIIIIJJJIIIIJJIIIIJJJJIIJJJI;

	public Mesh JIIJIIIIIIJIIJIJIIIIIIIIIJIJIJIIJJIJIIJIJJIIJJI;

	private Mesh JIJJIIJJJJIJJJIJIJJJJIJJJJJJJIJIJIJJJJJJIIJIJJJ;

	private MeshFilter IIIJJJIJJJIJJJIJJIIJIIIJIJIIIIJJIJJJJJIIJJIJIJJ;

	private MeshRenderer IJJIJIIIJIIIJJJJJIJIJJIJIJIIIIJIIIIJJIJIJJIJJII;

	public Vector3 IJJIIJJIIJIJIJIIIJIIJIIIIIJIIJIIIIJJIJJIJJIIIJJ;

	public Vector3 JJIJIJJIJIIIIIJIIJJJJJJIIIJIIIIIJIIJIIJIIJJIJJI;

	public Rect IIJJIIJIIIJIJJIJJJJIJIJIJIJJJIJIIIJIJIJJJIIJIII;

	public bool IIIIIIIIJIJJIIIIIIIIIIIIIJIIIIIJIIIIIIIIIIJJIIJ;

	public bool JIJJJIIIIIIIIIJIIIJJIIJJJIJIJJIIJJIJIJJIJIJIJJJ;

	public bool JIJJJIJJJJIJIIIJJJJJJJJJIIJIJIIIIIIIIIIJJJJJIJI;

	public bool IJIIIIJJJJIJJIIIJIIIIJIIIJIIJJIJJJIJJIIJIIJIJII;

	public Color IIIJIJJIJIJIIIIJJJIJIIJIIJJIIIIIJIIJIJJJIIJIIJJ;

	public Material JIIIIJJIJJIJIJIIJJJJIIIJJIIJIIJJIIJIJIIJJJJIIJJ;

	public Material JJJIJJJIJIJIIIJJIJJIIIIJIIJJIJIIIJJIJIJIJJIIIIJ;

	public UIAtlas IIJIIJJJIIIJJJJIJIIJJJIIJIJIIIIIIIIJJIJIIIJJIIJ;

	public string IIJIJIIJJJJIJIIJIJJIIJIJIJIIJJIIIIIIIIJIIIJJIII;

	private GameObject IIIJIJIIIIIJJIIJIIIJJJIIJIJIIJIJIIJJJJIJJJJIIII;

	private Transform JJIJIIJIIJJJJJIIIJIIIJJJIJJJIIIIJJIJJJIIIJJIIII;

	public GameObject JIIIJIJJJIJJIJIJIIIJJJJIIJIJJJIIIJJIIIJIJIIJIII => JIJJIIJIIIJIJIIJJIJIJJJIIIJIIIJJIIIJIJJJIIIJJJJ();

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	public Vector3 IJIJIJIJJJIIJJJJJIJJJJJIJJIIJJJJJJIJIJJJJIJJIJI
	{
		get
		{
			return JIJIIJIIJIIJIIJJJIJIIIJIJIJJIIIJJIIJIJJJJJIJJJI();
		}
		set
		{
			IIIJIIIJIJIJIJIJJJIIIJJJIJIJJJJJJJJIIJJIIJIJJII(value);
		}
	}

	public Vector3 JJJJJIJIJJIJIJIIIJJIIIJJJIIIJJJJJJIIIJIJIIJJJJJ
	{
		get
		{
			return IJIJJJJJJIJJIJIJIJIJIIJIJIIJIJJIIIJIJIJIIJJIIJI();
		}
		set
		{
			IJIIJJJIIJIJJJJJJJIJJIJJIIIIIIIJIJJJJIIJJJJIJJI(value);
		}
	}

	public Rect JIJIIIIJJJIJJJJJJJJIIIJJIJJJIIJJIIJJJIJJJIIJJIJ
	{
		get
		{
			return IIIJJJJIJJIIIIJJJJIJJIJJIIJIIJJIJJIIJIIJJJIIJJJ();
		}
		set
		{
			IIJJJIJIIIJIJIIJJJIIIIIIIIJJIIIIIIIIJJIIIJJIJIJ(value);
		}
	}

	public bool JIIJJJJJJIJIIJIJIIIIJJJIJIIIIJIIIIJIJIIJJJJIIJJ
	{
		get
		{
			return JJIJJJIJJIJIIIJJIIJJIIJJIJJJIJIIIIIIJJJIIJJJJIJ();
		}
		set
		{
			JJIIJJJIJJJJJJIIIIIIIJJJJJJIIIIIIIJJIIJIIIJIIJJ(value);
		}
	}

	public bool JIIIJIJIIIJJJJIIIJJJIIIIJIJJIIJIIJIJJIJIJIIJJJI
	{
		get
		{
			return JIIIIJJJIJJJJJJIJIIIIJJIJIJJIIJJJIIIJJIIJIJIJJI();
		}
		set
		{
			JIIIIJIJJIIJJJIIJIJIJJJIIJJJIJJJJIJIJJJJIJJIJJI(value);
		}
	}

	public bool IIIJJJIJIJJJJJJJJIJJIJIJIIIIIJJIJIIIJJIIIIJJJJI
	{
		get
		{
			return IIJIIIJJIIIIIJJJJIIIJIIIIJJIIJJIIIJJJJIIIJJJIIJ();
		}
		set
		{
			JJIJIIIIJIIJIIJIIIJJIIJJIIJIIIJJIIJIIIJIJIJJJJJ(value);
		}
	}

	public bool JIJJJJJJIJJJIJJJIIIJIIJJJIIIJIJIJIJJJJIIJIJJJJJ
	{
		get
		{
			return IJIJJJIJIJJJIJIJIJIJJIJIIIIJJIIJIIIJJJJIJIJJIII();
		}
		set
		{
			IIIJJIJIJIIIIJIJIJIIIJIIIJJIJIIIJJIJJIJJIJIIIJJ(value);
		}
	}

	public Color IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ
	{
		get
		{
			return JIIJJIIIIJIIJJJIIIIJIIJJIJIJJJJIJIJIJIJJJJIIJJI();
		}
		set
		{
			JIJIIJJJJJIIJJIJIJIIIIJJJIIJJIJJIIJJIJIIJJJIIII(value);
		}
	}

	public MeshFilter JIJJJIJIJIJJJIJIIIIIIJIJIJJIIIIJJJJIIJIJJIIJIIJ => JIJJIIIIIJJIIIJJJIIJIJJJIIJJIIJIJJJIIJIJIIIIIJJ();

	public MeshRenderer JJJJJJIJJIJIIIJJJIIIJJIJIJJJIIIIIIIJIJJJIIJJIJI => JIIIIJJIIJIIJIJIIJIIIIIJJJJJIIIJIJIIJIIJJJIIJII();

	public UIAtlas JJJIIIJJJIIIIIJIJIJJIIIJIIIIIIIJIIIJIIIIIIJJJJI
	{
		get
		{
			return IIJJJIJJIIIIIIJJIIJJIIIJIJJIIIJIJJIIIJIIJJIIJII();
		}
		set
		{
			JJIIIJIIIJIJJJJJJJJIJJJJIIIIJIJIIIJJJIJIIIIIJJJ(value);
		}
	}

	public string JIJJIIIIIIIJIIJIJJIJIJJIIJJIIIIIJIJJIJJJIIIJIJJ
	{
		get
		{
			return IJIIIJJIJJJIJJJIJJJJJIJJJIIJJIIIIIJJIJJIIJIJIJJ();
		}
		set
		{
			IJIIIIIJIIJIJJJIJIJJIJIJJIJJIIIJJIJJJJJIIIIJJIJ(value);
		}
	}

	public void JJJJIIIIJJIIIJJIIJIJJIIJJJIIIIIIJJJIJIIJIJJJIJI()
	{
	}

	public void IJIIJIIJJJIIIIIIJJJIIIJJIJIJJJIIIJJJIIIJIIIJJIJ()
	{
	}

	public GameObject JIJJIIJIIIJIJIIJJIJIJJJIIIJIIIJJIIIJIJJJIIIJJJJ()
	{
		return null;
	}

	public void JJIIJJJIJJJJJJIIIIIIIJJJJJJIIIIIIIJJIIJIIIJIIJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Vector3 JIJIIJIIJIIJIIJJJIJIIIJIJIJJIIIJJIIJIJJJJJIJJJI()
	{
		return default;
	}
	public void JIIIIIIIIIIIIJJJIJIJJJIIIIJJJIIIJIIJIJJIIJIJIII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void Reset()
	{
	}
	public string JJIIIIJIIIJIJJJIJJJIJJIIJIIJJJJJIJIIIJJIJIIJIII()
	{
		return null;
	}

	public MeshRenderer JIIIIJJIIJIIJIJIIJIIIIIJJJJJIIIJIJIIJIIJJJIIJII()
	{
		return null;
	}

	public void IIJIJJJJJJJJIJIIIJJIIJJIJIIJJJJIIIJIJJJIJIJJJIJ()
	{
	}
	public UIAtlas JIIJIJJIJJJJIJIIIJJJJJJIJJJIIJIJIJIIJIIIIJIJIIJ()
	{
		return null;
	}

	public void IIJJJIJIIIJIJIIJJJIIIIIIIIJJIIIIIIIIJJIIIJJIJIJ(Rect JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Color JIIJJIIIIJIIJJJIIIIJIIJJIJIJJJJIJIJIJIJJJJIIJJI()
	{
		return default;
	}

	public bool JIIIIJJJIJJJJJJIJIIIIJJIJIJJIIJJJIIIJJIIJIJIJJI()
	{
		return false;
	}

	public void JIIIIJIJJIIJJJIIJIJIJJJIIJJJIJJJJIJIJJJJIJJIJJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public Color JJJIIIIIIIIIIIJIIJJJIIIJIJJIJJIJIIIIIJIIJIJJIJI()
	{
		return default;
	}

	private void IJJJJIIJIIJJIIIIIJJIJIIIJIIIIIIIJIIIIIJJIIIIIJJ()
	{
	}

	private void IIIIIJIJIJIIIIIIIIJIIIIIJIIJIJJIJIIIJIJJJIIJIJI()
	{
	}

	public void JIJIIJJJJJIIJJIJIJIIIIJJJIIJJIJJIIJJIJIIJJJIIII(Color JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public string IJJJIIIJIJIJIJIJJJIIJIIIJIJJJJIJJJJJIIJJJIJJJJJ()
	{
		return null;
	}

	public void IIJJIIIIIJIJJIJJIIIIIJJJIJIIJJJJJIIJIIJIIIIJIII()
	{
	}

	public UIAtlas IIJJJIJJIIIIIIJJIIJJIIIJIJJIIIJIJJIIIJIIJJIIJII()
	{
		return null;
	}

	public void JJIJIIIIJIIJIIJIIIJJIIJJIIJIIIJJIIJIIIJIJIJJJJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Vector3 IJIJJJJJJIJJIJIJIJIJIIJIJIIJIJJIIIJIJIJIIJJIIJI()
	{
		return default;
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}
	public bool JIIJJJIIIIJJIIJJJIIJIJIIJJJJIJIIIIJJIIIIIJJJIJJ()
	{
		return false;
	}

	public void IIIJJIJIJIIIIJIJIJIIIJIIIJJIJIIIJJIJJIJJIJIIIJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJJIIJIJIJJIJIJJIIIJIJIJIIIIJIIJIIJIJIIIJIIJJIJ()
	{
	}

	public void IJIIIIIJIIJIJJJIJIJJIJIJJIJJIIIJJIJJJJJIIIIJJIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Rect IIIJJJJIJJIIIIJJJJIJJIJJIIJIIJJIJJIIJIIJJJIIJJJ()
	{
		return default;
	}

	public string IJIIIJJIJJJIJJJIJJJJJIJJJIIJJIIIIIJJIJJIIJIJIJJ()
	{
		return null;
	}

	public MeshFilter JIJJIIIIIJJIIIJJJIIJIJJJIIJJIIJIJJJIIJIJIIIIIJJ()
	{
		return null;
	}

	public void IIIJIIIJIJIJIJIJJJIIIJJJIJIJJJJJJJJIIJJIIJIJJII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool JJIJJJIJJIJIIIJJIIJJIIJJIJJJIJIIIIIIJJJIIJJJJIJ()
	{
		return false;
	}

	private void OnEnable()
	{
	}

	public void JJIIIJIIIJIJJJJJJJJIJJJJIIIIJIJIIIJJJIJIIIIIJJJ(UIAtlas JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JIIJJJIIJJIJJJIJJJJIJJJIIJIIJIIIIJJJJJJJIIJIJJI()
	{
	}

	public bool IIJIIIJJIIIIIJJJJIIIJIIIIJJIIJJIIIJJJJIIIJJJIIJ()
	{
		return false;
	}

	public bool IJIJJJIJIJJJIJIJIJIJJIJIIIIJJIIJIIIJJJJIJIJJIII()
	{
		return false;
	}

	private void JJIJIIIJIIIIIJJIIIIIIJJJJJIIJJJJIJJJIIIJJIIJJJI()
	{
	}

	private void IIIJJIJJJJJJJJIIJJIJJJIJJIIIIJIIIJJIIIIIIJJJJJJ()
	{
	}

	public bool IJIIIJJIIIIIIJIIIJIIJIIJJJIJJIJIJJIIJIJJIIJJIJI(string JIJJIIIIIIIJIIJIJJIJIJJIIJJIIIIIJIJJIJJJIIIJIJJ)
	{
		return false;
	}

	public void IJIIJJJIIJIJJJJJJJIJJIJJIIIIIIIJIJJJJIIJJJJIJJI(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JIIIJJIJIIJJIJJIJIJIIIIJIIIJJJJJJJJIJJJJIIJIJJJ()
	{
	}
	public MeshRenderer JIIJIJJJIIJIJJIIIIIIJJJIJJIIIIIJIIJIJJIIJIJIIJI()
	{
		return null;
	}
}
