using System.Runtime.CompilerServices;
using UnityEngine;

public class mFireSounds : MonoBehaviour
{
	public PlayerSounds IJJJIIIJJJJJJJJJIJIIIJJIJIIJJIIJJJIJIIJJIIJIJII;

	public float IIJJIIIJIJIJJJJIIJJJJIIIIIIIIIIJIIIIJIJIIIIIIII;

	private void IJIIIJJJIIIJJJJJJJJIJJIIJJIIJIIJIJJIIIIJJIJJIIJ()
	{
	}

	[CompilerGenerated]
	private void IJIIIJJIJIIIJJIJJJIIIIIJJJJIJIIJIIJJJIJIIJJIIJJ()
	{
	}

	private void IJJIJIJJIJIIIIIJIIJIIIIJJIJJJJIIJJIIJJJJIIIIJII()
	{
	}

	[CompilerGenerated]
	private void JJIIIIIIJJIIJJIIJJIJJJJJIJIIJIJJIJIIJIJJIIJIIII()
	{
	}

	private void IJIJJIJJJJIJJJIJJJJJJJIJJJIIIJJIJJIJJIIJJJIIJIJ()
	{
	}

	private void JJIJIJJJJIJJJIJIJJIJJJJJIJIJJIIIIIIIJIJIJIIIIJI()
	{
	}

	private void IJJIIIIIIJJIIIIJIIIIJJJIJJJJJJJJIIIJIIJJIJJJJIJ()
	{
	}

	private void IIIIJIIIJIJIJIJJJIIIJJJJIIIJIJJIJJIIJJJJJJIIIJI()
	{
	}

	[CompilerGenerated]
	private void IIJIJIIJJIJIIIJJJIIIJIIIIIIJJIIIIJIJIIJJIJJJJII()
	{
	}

	private void JJJJJJJIIIIIIJIJJIIIIJJJIIJIIIJIIJJIIIIJIJIIJII()
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private void Start()
	{
	}

	[CompilerGenerated]
	private void IJJJJJIIIIJJIIJIIJIJIJIIJIIJJIJIIIJJJJIJIJJJIIJ()
	{
	}

	[CompilerGenerated]
	private void JJJIJIIJJJIJJIIIIIJIIIJIIJIIIIJJIIJIIIJJJIIIIJJ()
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	[CompilerGenerated]
	private void IIIJJIJIIJJJIIIJIJIIIJIIJIJIIJJJIIJJJJJJJJJIIII()
	{
	}

	[CompilerGenerated]
	private void JIIJIIIIJIJIIJJIIJJJJIJJJJJJJJIJIIIIIJIIIJJIJJJ()
	{
	}

	private void IJIIIIJJJIJJIIIJIJIJJIIIIIIIJIIJJJIIIIIJIIIIJJJ()
	{
	}

	private void IJJIJIIIJIJIJJJIIIJJIJIIJIJIJIJIJJJJIIJJIJIIJJJ()
	{
	}

	private void JJJIJIJJIIIIIJJJJIJJJJJJJIJJIJJIJJJJIIJIJIJIIII()
	{
	}

	private void IJIJJIJJJIJJJJIIJIIJJJIIJIJIJJIIJIJIJIIJIIJIIJI()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	[CompilerGenerated]
	private void JIIJJJIIJIJJJIIJJIJIIIIIIJIIIIJIJJIJIJIJJIIJJIJ()
	{
	}

	private void JJIJJJIIIJIIJIJJJJJIJJJIJJIJIIIJIIJIJJJJJJIIJII()
	{
	}

	private void IIJJIJIIJJIIJJIIIIJJIJJJJJIIIJJJJJIJIJJJIJJJIJJ()
	{
	}

	[CompilerGenerated]
	private void JJJJIJJJJIJIIIJIJIIJIJJJJIJIIJJIIIIIIIIJIIIIJJJ()
	{
	}
}
