using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Photon;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mFriendsManager : Photon.MonoBehaviour
{
	private sealed class IIJIJIJJIIJIIIJJIIIIJIJIJIJJJJIIJIIJJIJJJIJIIIJ
	{
		public mFriendsElement IIIJIJJIJIIJIJJJIJIIIIJIIIJJIJIJIJJJJIJJJJJIIIJ;

		public mFriendsManager JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		internal void IJIJIIIIJJIIJIIJJIIIJJJIJIJJIIIIJJIIIIJJJJIJIIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIIIIIIJIJIJJIIJIJIJJIIIIJJJIIJJIJJJJIJJJJIIJJJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IJJIIIIJJJJIIJIJJJIIJIJIIIIJJJIJJIIJJJIJIIIIIII(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIJIIIIIJJIJIIIIIIJJIIJIIIIIIIIJIJJIJIJIJIIIJII(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIIJJIJIJIJJIJIJIJJIJIIIJJJJIIIJIJJJJIIJJIJJJII(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IJJJJIJIJIIJJJJJJIJIJJIIJIIIIJIIJJJIJIIIJIIJJJI(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JJIIJJIJIJIJJIIJJIIJJIIIIIJIIIIJIJJJIIIJJJIIIJI(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IJJJIJJJIIIJJIIJIIIIJIJJIIJIIJJJIIJIJIJIIJIIIIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IIIIIJIIIIJIIJJIIIIJJIJJJJIJIIIJJIIJJIJIJJIJIII(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JJIIJJJJJIIIIIIJJIIIJIIIIIJIIIJIJIIJJJJJIIJIIJJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IJIIJIJJIIJIJIJJJIIJIJIJJIIJJJIIJIIIJJJIJJJJJII(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JIIJJIIIIJJIJJIJIJJIJJJJJIJIIIJJJIIIJJJIJIIJJIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JJJIIIIJIJJIIJJJJJJJIIJIJJIIJIIIIIIJJJIIIJJIIJJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void JJJIIIJJIJJIIIJIIIJJJIIJJIIIIJIIIJJIJJJJIIJJJII(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IIIIJJIJJJIIJIIJIIJIIIIJJIJIIIJIIIIIJIIJJIJIJIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IJIJIJJJJJJIJIIIJJJJIIIIIIJIJIJJJIJIJJIJIIIIIJI(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}

		internal void IIJJIJIIIIIIIIJJJJIJJIIIJJIJIJIIJJIJJIIIJIJJIIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
		{
		}
	}

	private static Dictionary<int, string> JJJJIJIIJIIJJIIIJJIIIJJIIJJJJJJJJIIIIJJJIJJJIII;

	public GameObject JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ;

	public UIGrid IIIIIIJIJJJIIIIIIIIIJIJIIIIIJIIIJIJJJJIIJJJJIJI;

	public UIGrid IJJIIIIJIIIIJIIIIIIIIJJIJIJIJJJIIIIIJIIIJJIIIIJ;

	public UIPanel IJJJIIJIJIJIJJIIIIIJIJJJIIJJIJIIJJJIJIJIIJIJJII;

	public GameObject IJIIIJJIIIIJJIIJIJJIJJJIIIJIJIIJJJJJJJIJIIJIJII;

	public UISprite JJIJIIIJIIIIIJIJIJIJIIIIJJIJIIIJJIIJIJIJIIIIJIJ;

	public UILabel JJIIJJIJJJJIIIIIJIIJJIIJIIIJIIJIJJIJIJIIIJJJIII;

	public UILabel IIJJIIIJIJJIIJIIIJIIJIJIIJJIJIIJJIIJJIIJJJIJJII;

	public UILabel IJJJIJIJJJIIJJJJIJIIIJJIJIJJIJJIIJIJJJIJIJIIIIJ;

	public UILabel IIIJJJJJJIIIIIIIJJIIIIJIIIIJJJJJIIIJJJIJJIIIIII;

	public UILabel JIJIJJJIIIIIJIIJJJIIJJJIIJJIJIJJJIJIJJJIJJJIJII;

	public UILabel IIIJIIJJIIIIJJJIJJJIJJIIJIJIJIJJIIIIIJIJIIJIJJJ;

	public UILabel IIJJJJIIJJIJIIJJJJIJIIIIJIIJIJJJIJJIJIIJIIJIJJJ;

	public UILabel JIIIJJIJIJIIJJIIIJIIIJIIJJJIIJJIJIJJIIJJJJJJIIJ;

	public UILabel IJIJJIIJJJIJJJJJIJJJIJIJIJIJJIIJJJIJJJJIIJIJJII;

	public GameObject IIIIIJIJJIIJIIIJJJIJJJJIJIJIIJIJJJIJIIJJJJJJIJI;

	public UILabel JJIJJIJIIJJJJJIIJIIJJJIIIIJJJJJIIIIIIIIJIIIJIII;

	public UILabel IJJJIJJIIJIJIIJIJIIJIJIJIJJIJJJJJJIJIIIJJJJJIJI;

	public UILabel IIJIIJJIJJJIIIIIJIJJJJJJIJJJIJJIJIJIJJIIJJJJIII;

	public UILabel IIJJJJIIIIJIIJIIIIIJIJJJJJIJJIIIIIJJIJIJJJIIIII;

	public UILabel IIIJJJIJIIJIJIJIJIJJIJIIIJJIIJIIIJIIIIJIJJIJIJJ;

	public UILabel JJJIIJJJIJIIJJIIJIIJIIIJJJJJIJIIIIIJJJJIIIJIJJI;

	public UILabel IIIIIIJIIJIJJIJJJJJIJIJJIJJIJJJIIIIJJJJIJJIIJJI;

	public mFriendsElement IJIJJJIIIIJJJIJIIJIIIIIIIJJJIJIIIIIJIJIJJJJIIIJ;

	public Color IJIIJJJIIJJIJIJJJIIJJIJIJIJJJJIIJIIIIJJIIJIIJJI;

	public Color IIIJJJJJIJJIJJIIIJJIIIIIIIIIIJJJJIJIJJIIIIJIJIJ;

	private mFriendsElement IJIJJIIIJJJIJJIIIIJJJJIIJJJIIJJJJJIIIIJIIIIIJJJ;

	private List<mFriendsElement> JIIJIJJJJJJJIJIIIJJJJJJJJIIJIJIIJIIIJIIIJIIJIJJ;

	private List<mFriendsElement> JIIJJJJIIIJIJIIJJIIJIJIJIIIJJJIJJIJIJIJJJIJIIJI;

	public static List<string> JIIJIJJJIIJIIJIIJJJIJJJJJJIIIJJIJJJJJIJJIIJIJJI()
	{
		return null;
	}

	public void UpdateList()
	{
	}

	[CompilerGenerated]
	private void IJIIIJJJIJIJJIIIIJIJJJIJJIJIIJIJIIJIIIIIIIIIJII()
	{
	}

	public static void IJIJJIIJIIIIJIJIIIIJIIIIIJIIIJJJJJIIJIIJJIJJJII(int[] JIJJJIJJJJJIIJJJJJIIJJJIJIIIJJJIIIJIIJIIJIJIJIJ)
	{
	}

	private string IIJJJJIIIIIJIJIIJJIJJJJIJIIIIIJIIIJJJIIIIIJJJIJ(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}

	private void JJJIJIIIIIJJIIJJJIIIJIIJJIIJIIIIJJJJIJIJIJIJJJI(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
	{
	}

	public void JIIIJIJIJIIJIIJJJIJJJJIJIIIIIIJIJJJJJIIIIIIJIII()
	{
	}

	public void JIJIIJJIIJJJJJIJJJJJIIJJIJIIJJJJIIJJIJJIIJIJJII(mFriendsElement IIIJIJJIJIIJIJJJIJIIIIJIIIJJIJIJIJJJJIJJJJJIIIJ)
	{
	}

	private void JJIIIJIJJJJJJJJIJIIIJIIJIIJIJIJJIIJIIIIJJJJIIJJ()
	{
	}

	private void IJJJIIJJJJJIIJJJIJJJJIJJJJIJIJIIJIJJJJJIIIJJIII()
	{
	}

	private string IIJIJJJIJIJIIIIIIIJJJJJIIIIIIJIIIJIIJJJJIIJIJII(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}

	private void IIIJIJJJJIJIJJIJIIIIJJIIIIIIIIJIJIIIIIIJJJIIJIJ()
	{
	}

	private void OnDisable()
	{
	}

	public static void IIIIIJIJJJJIIJIIIJIJJJJIJIIIJIIIIIIIIJIIIIIJJJJ(int[] JIJJJIJJJJJIIJJJJJIIJJJIJIIIJJJIIIJIIJIIJIJIJIJ)
	{
	}

	private void OnEnable()
	{
	}

	public void Refresh()
	{
	}

	private JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ IIJJIIIIIJJJJIIJJIJIJIJJIIIJJJJIIJJIIJIJIJJIJJI(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
		return null;
	}

	private string JIIJIJJJJJJJIIIIIJIJIIIJJJJIJIJIIJJJJJIIJIIJJIJ(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}

	private void IIIIIIJIJJJIIIJJIIJIJIJJIJJIIJJIIIJJJIJJJJJIIJJ()
	{
	}

	private void OnUpdatedFriendList()
	{
	}

	private mFriendsElement IIIIIJIIJIIJIIIJJJJJIIIJIIJIIIIIJJIIJJJJJJJIJIJ()
	{
		return null;
	}

	private void IIIJJIJJJJJJJJIIJJIJJJIJJIIIIJIIIJJIIIIIIJJJJJJ()
	{
	}

	public void Connect()
	{
	}

	private string JJJJIJIIIIJIJJIIJIIIJJIJJIIIIJJIJJJIJJJJJJIIJJI(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}

	private void JIJIIIIJJJIJJJIJJIJIJJIJIJIJIJIIJJJJIJIJIIJJJII()
	{
	}

	private void JJJJIJJJIJJJIIJIJIIJIIJJJIJIIIJIJIIIJJJIIIJIJII()
	{
	}

	public void DeletePlayer()
	{
	}

	public static List<string> IIJJIJIJJIJIJJJIJIJJIIJIJJJJJIJJJIJJIIIJIIIIIII()
	{
		return null;
	}

	public void Open()
	{
	}

	private void JIJIJIIJJIIIJJIIIIIIIJJJJIIJJJIIIJIJIJIIIIIJIIJ()
	{
	}
}
