using System.Runtime.CompilerServices;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mFriendsElement : MonoBehaviour
{
	public mFriendsManager IIIIIJIJIJIJJJJIJIJIJIJJIIJIJIIIJJIIIJIJIJJIIJJ;

	public UIWidget IJJIIIIIIIJIIJJIJJJIJIJJJIJJIIIIIIIIIIIJJIIJIIJ;

	public UILabel IJJJJJIIIIIJIJJJJJIJIJIJJJIIIJIJJIJJJIJIJJJIIII;

	public UISprite JIJJIJIIIIIIJJIIJJIIJIIIIJIJJIJJJJJJIIJIJJIJJJI;

	public UILabel IJJJIJIIJIJJIJJIIIJJIJIIJJIJJIJIIIJIJJIIJJJJJIJ;

	private int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ;

	public JIJIJIIIIIJJIJJJIIIJIIJJIJIIIIJIJIJJJIJJJIJJJIJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI;

	public int IJJJIIJIJIJJJIIIIJJIIJJIIIIIIIIIJJIJIJIIJIJIIIJ => JJIJJJJJIIIJJIIJJJJJJIJIJJJJJIIIIIJIIIJIJJJIJJJ();

	private void IIJIIIJIJIIJIIIJIIIJJIJJIIJIJJJIIJJJJIJJIIJIJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	public void IJIIJJJIIJJIJJIIIJIIJJIJIIIIJJJIIJJJIJJIJIJIJIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private void JJIJJJIIJIIJIIJJJJJIIIIIJIIJIIIJIIJIJIJJIJJIJIJ()
	{
	}

	public void JJJJJJIIIJIJJJJJJIIJJJIIJJJIJIIJJIJIJIJJJJIJJJJ(JIJIJIIIIIJJIJJJIIIJIIJJIJIIIIJIJIJJJIJJJIJJJIJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI)
	{
	}

	public void IJJIJJJIJJJJIIJIIIIIJIIJJIJJJJIIJJIIJIJJIJJIJIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	public void JJJIIIIIJIJIJJIJIIJJJJJJIJJJJIJJJIIIJJIJIJIIIJJ(JIJIJIIIIIJJIJJJIIIJIIJJIJIIIIJIJIJJJIJJJIJJJIJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI)
	{
	}

	private void JJIJIJIJJJJJIIJJIIIJJIJIIIJJIIJJJIIIIJIJJIIIIJI()
	{
	}
	public int JIJIIJIIJJIJIJJJJIJIIJJIJJJJJIJIJIJJIJIIJJIJIJJ()
	{
		return 0;
	}

	private void JJIJIJJJIJJIJIJIJIIJIJIJJIJIJIJJJJIJJJIJJIJJJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void IJIJJIIIIIJIJIJIIJJIIJJJJIIIJIJIIJJJJIIIJJIIJII()
	{
	}

	private JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ JJJJIJIIIJJJIIIIJIIIJIJJJIIJIJIIIJJIIJJJIJIIJJI(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
		return null;
	}

	private void JJJIIIIJIIJJIIJIIIJJJIIJIIIIIJIJJIJIIIIJIJJIIJJ()
	{
	}

	public void JIJJJIIJIJIIIIIJJIIJJJJIJJJJIIJIJIIIIIJIIJJJIII(JIJIJIIIIIJJIJJJIIIJIIJJIJIIIIJIJIJJJIJJJIJJJIJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI)
	{
	}

	private void OnDisable()
	{
	}

	private void JJJIJJJJJIIJIJJJIJIIIIJJIJJJIJIIJJIIJIIJJJJIIJI()
	{
	}

	public void IJIIJIJIIJIJJIJJIJJIJJJJIIIJJJIIJJIIIJJJIIIIIIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	public void JJJJIJIJIIIIJJJJJIIIIJJJIIIIJJJJIJJJJJIJJIJJJJI(JIJIJIIIIIJJIJJJIIIJIIJJIJIIIIJIJIJJJIJJJIJJJIJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI)
	{
	}

	public void JJIJJJJJIJJIIIJIIIIJIIIIJJIIIJJIIJJJJIIJIIJIJJJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private void IIJJJIJJJJIIIJIJIIJJIIIIIJJJIIIIIIJIIIJIJIIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}
	public int JJJJIIIIJJIIJIJJJIIIJJIJIJIIJJJIIIIIIJIJIJJJIJI()
	{
		return 0;
	}
	public int IIJJJIIIJJIJIIJJIIIIJIIJIJIJJJIIJJJJJJIIIIIJIJJ()
	{
		return 0;
	}

	private JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ IIJJIIIIIJJJJIIJJIJIJIJJIIIJJJJIIJJIIJIJIJJIJJI(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
		return null;
	}

	public int JJIJJJJJIIIJJIIJJJJJJIJIJJJJJIIIIIJIIIJIJJJIJJJ()
	{
		return 0;
	}

	private void OnEnable()
	{
	}

	private void IJJJJJJIIIIIJIIJJIIJJIJJJIJIIIIJJJIJJJIJJIJIIJJ()
	{
	}
	public int IJIJJJIIIIIIJJJIJJJIJJIJJIJJIIJIIJJJIIJIIJIIIJI()
	{
		return 0;
	}

	private void OnClick(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}
}
