using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Photon;
using UnityEngine;

public class mg_100TrapsManager : Photon.MonoBehaviour
{
	[Serializable]
	public struct IIJIIIJJIJJJJIIJJJJJJIIJIJJIIJIJJJJIIJJJIIJIIJI
	{
		public GameObject IIIIJIJIIIIIIIIJJJIJJIIJIIJJJIIIIIJIJIJIIIIIJII;

		public Transform IJJJIJJJJJIIJJJJJJIIIIIJJIIIIJJJJJJIIJJJJJIJIII;
	}

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JJIJJIIJJIJJIIIJJIJIIIJIJJIJIIIJIJJIIJIJJJIJJJI;

	public List<IIJIIIJJIJJJJIIJJJJJJIIJIJJIIJIJJJJIIJJJIIJIIJI> IIIIIJIIJIIIJJJIJIJJIIJJIIJIIJJIJJIJIJIIIIIIJJJ;

	private float JJIJIJIJJJIIIJJJJIIJIIIIIIIIIIJJIIIIIIJIJIIJJIJ;

	private byte JJJIJIIIJIIJJJIJIJJIJIJJIJIJIJIJIJJIJIJIJIJIJII;

	private PhotonView JJJIJJIJJJJJIIIIJJIJIIJIIIIJJJIJIIIIJIIIIJIJJIJ;

	private void JJIJJJIIJIIJJIJJIIIJJJIJJIIIIJJJIJJIIJJIJJIJJII()
	{
	}

	private void IIIJIIIIJIIJJIJJIJJJIJIJIJJIIIIJJJJJIIJIJJIIIJI()
	{
	}

	private void JIIJIJIJIIIJJJJJJJJJJJIIIIJJIJJJIIJIJJIJIIJIJIJ()
	{
	}

	private void IIIIIJJIJJJIIIIJJIIIJIIIIIJIJJJIJJJJJJIJIIIJJJJ()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	[CompilerGenerated]
	private void JJIJJIIIJJIIJIJIIJJIIIIJIIIIIIJIIIJJJJIJJIIJIJI()
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void JIJJJJIIJJIIJJIIJJJIIIIIIIJIIJJJIIIJIIIJIIJJIIJ()
	{
	}

	public void IJIJIIJJIIIIJIJJIIIIIIIJJJJJJIIIIJJIJIIIIIIIJJI()
	{
	}

	private void IIIIIJJIJJIIJJJJIJIIIIJIJJJJJIJJIIIIJJJIIJIIIII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void IJIIIJIJIJIJIJJJIJIIIJJIJIJIIIJIJIIIJIJJIIIIJJJ()
	{
	}

	private void JJJJIIJJJIIIIJJIIIJIIJJIIIIJIJIJJJJIJIIIJJJJJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void JJIIJJIJIIIJJIIIIJJIIIIJIIIJJJIJJJIJJJJJJIIJIII()
	{
	}

	public void IJIJIJIIIJJJIIIIIJIJIJIJJJIJJJJJJJIIIJJIIIJIIJJ()
	{
	}

	private void IJIJJJIJIJIJIJIJIJIIIJIIIJJIJIJIJJIJIIJJJJJIJJJ()
	{
	}

	private void IJJJIIIJIJIJIJJJIIIIJJIIJIJJIJJIIJJJIIJJJIJIJII()
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	public void NextLevel()
	{
	}

	public void IJIJJIJJIIIJJJJIJJJIIJIIIJIIJJJIJJJJIJJJJJIIIIJ()
	{
	}

	[CompilerGenerated]
	private void IIIIJIJJIJIJIIIIJIIIIIIIJIJJIJJJJIJJJIIIIJJJIIJ()
	{
	}

	public void JJJJJJIIIJIIIJIJJJIIIIJJIIJIJJJJIJJIIJIJJIJIIIJ()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void Start()
	{
	}

	private void JJIJIIJIIIJJJJIJJJJIIJJJJIIIJJJJJJJIIIIJJJIIJIJ()
	{
	}

	private void IIIJJIIJIJIJJIIIIJIIJIJJIIJJIIJJJJIIIJIJIIJJJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void JJIJIJIJJJJJJIIJIIJIIIIIIIJIIIJIJIIIIJIIIJJJJJJ()
	{
	}

	private void IIJIJJIIIIIJJJJIJIJJJJJIIIJJJIIIJJJIJJJIJIJIJJJ()
	{
	}
}
