using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mInAppItem : MonoBehaviour
{
	public enum IIJIJJIIIIIIIIIJIIIIIIJIIJJJIJIIIJJJIJJJJJJJJJJ
	{
		Purchase = 0,
		Consume = 1
	}

	public IIJIJJIIIIIIIIIJIIIIIIJIIJJJIJIIIJJJIJJJJJJJJJJ JIJIIJJIJIIJJIJJIIIJIIIJIIIJJJJJJIJJIJJJIIJIIJJ;

	public string IIJIIJJIIIIIIIJIJJJJJJIIJJIJJJIIIIIJJJIIIIIIJJJ;

	public UILabel JJJIJIIJJJJJIJJIJJIJJIIIIJIIJIJJIJJIJIJJIJJIIJJ;

	private GameObject IIIJIJIIIIIJJIIJIIIJJJIIJIJIIJIJIIJJJJIJJJJIIII;

	private void JJIJJIJIJIIIJJIIIIIJJIJIIIIJJJIJIIJIIIJJIIJIJJI()
	{
	}

	private void JIIIJJJJIIIJJJIJJIJJJJIIIJIIIIIIJIIJIIIIIIJIJII()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void OnDisable()
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private void IIJJJIJJJJIIIJIJIIJJIIIIIJJJIIIIIIJIIIJIJIIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void OnClick(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void Start()
	{
	}

	private void IIIJIIJJJIJIIIIIIIIIJJJJIIIIIJIIIJIIIJJIJIIJIII()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void JIJIJIIIJIIJJIIIIIJJIJIIIIJJJIJIJJIJIJIIIIJIJJI()
	{
	}

	private void IIIIIIJIIJJIIJJJJJIIJIIJIIJJIJJJJJIJIJJJJIIJIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void IJJJJIIIIJJIIIJJIJJJJJJIJIIJJJJJJJJIJJIIJIIIJIJ()
	{
	}

	private void JIJJJIIIIIIJJIIIIIJJIIIJJIJIJJJJJJJJIJIJIIJIJII()
	{
	}

	private void IJIJJIIJJIIJIIJJJJJIJJJJIJJJIJJIJIIJJIIJJIJIIJJ()
	{
	}

	private void IJIJJJIIJIIJIJJIJIJIIIJIJIJJIIIIIIJJIJIJIJIJIJJ()
	{
	}

	private void IJIIJJJJIJIJJJIIIJJIIJIIIJJJIIJIIIIIIIIJJJJIJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void JJIJIJJJIJJIJIJIJIIJIJIJJIJIJIJJJJIJJJIJJIJJJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void OnEnable()
	{
	}

	private void IIJJJJJIIJJJJJJJJJIIIIJIIJJJIIIIIJIIIJIIJIJJIJJ()
	{
	}

	private void IIJIIIIIJJJIJJJIJIJIJJIIJIJJIIJIIJIJIIIIJJIIIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void IIIIIJIIJJIIIIJIJIJIJJIIIIIIJIIJIIIIJJJJJJJIIJI()
	{
	}
}
