using System.Collections.Generic;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mInventoryManager : MonoBehaviour
{
	public mInventoryElement[] IIJJIJIIIIIJJJJIJIJIJJIJJIIIJIJIIJJIIIJIIJJJJII;

	public UIPopupList JJJIIJIJJIIJIJJIIJJIJIJJJIIIIJJJJIIIJJJJJIIIIJI;

	public UIPopupList JIJIIJIJIIIIIIJIIJIIJIIJIIIIJJIIIIIIJJJIJJJIIII;

	public UIPopupList IIIJJIJJJIJJJIJIJJIJJJIJIIIJIJIIIJJIJJJJIIJJJIJ;

	public UILabel JIIIJIIIJJIIJJIIJIIIJJIIJJIIIIIIJJJIJJIIJIJIJIJ;

	public UILabel JIIJJJIJJIIJIJIJIIJJJIIJJIIIIIJJJJIJJJJJIJIJJJJ;

	private string IIJJJJJIIIIJJJIJIIIIIIIJIJJIJJIJJJIJIIJIIJJJIII;

	private List<JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII> JIJJJIIJJJJIIIJJIJJIIJJJIJJIJIJIIJIJIIJIIIIJIJI;

	private int IJJJIIJJJJIIJIJJIIIJJJJJJIJIJJIJJIIJJIJIIIJJJJI;

	private bool JJIJJJIIJJIJIJIJIJIIJIJIIIJJJIJIJJJIIJIJIIJJIIJ;

	private static mInventoryManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void Start()
	{
	}

	public void IIIJJIIJJJIJIIJIJIIJIJIIJIIJIJJJJJJJIJIJIJIIIJI()
	{
	}

	public static void IJIIJIJIIJIJIIIIJJIIJIIIIIJJJIIIIJJIIJIIIIIIIIJ()
	{
	}

	public static void IJJIJIJJJJIJIJIIJJIJIJIJIJJIIIIJJJIIIIJJIIJIJJJ()
	{
	}

	private void IIJJIIIJIJIJIIIJJIJJJJJJJJJJJIIJJIJJIJIIIIJJJII()
	{
	}

	private void IJJIIJJIJIJJIIIJJIIJIIJIIIIIIIJJIIIIIIIIIJIJIJJ()
	{
	}

	public void IIIJIJJIIIIIJJJJIIJIIIIJJJJIIJJJJIJJIIJIJIJJJJI()
	{
	}

	public static void IJIJJJJJJIIIIIIIJJIIIJJIJIJIJJIIIIIIIIJJIIJIIJI()
	{
	}

	public static void IJJJIIJIIJIJJIJIIJIJIJIJIIIJJIIIJJJIJIJIIIIJJJJ()
	{
	}

	private void IIIJJJJIIJIIJJJJIIJIIJJJIJJJJIIIJIJJIIJIJIIJJII()
	{
	}

	public void IJJJJJJIJJJJJIIIIIIJJIJIJJIIIIJJIIJJJJJJIIIJJII()
	{
	}

	public void UpdateData()
	{
	}

	private void IJJJIJJIIIJIIIJIJJJJIJJJJJIIIJIIIJIIJJJJIJJIIJJ()
	{
	}

	private void IIIJIJIJJJJJIJJIJJJJJIIIIIIIJJJJJIIJJIJIIJIIJII()
	{
	}

	private void IJIIIJIJIJIJIIJJJIJIIIIIJJIJJJIIJJIIIJIJJIIJIJI()
	{
	}

	public void IJJIIIIJJIIIIIIIIIJIIIJIJJJJIIJJIIIJIIJJJJIIIIJ()
	{
	}

	public void OnLeftList()
	{
	}

	public void Open()
	{
	}

	private void IIIIIIJIIIIJIIJJIIIJIIIIJIIJIIJIJIJJJIIIIJIIJIJ()
	{
	}

	public void OnRightList()
	{
	}
}
