using UnityEngine;

public class mInventoryElement : MonoBehaviour
{
	public GameObject IIIJIJJIJIIJIJJJIJIIIIJIIIJJIJIJIJJJJIJJJJJIIIJ;

	public UISprite IJIIIJJIIIJJIIIIJIJIIIJJJJJJJIIIJIIJIJJJIIJJIJJ;

	public UISprite IJJIIIJJJJJIJJJIIIIJIJJJIIIIJJIIJIJJIIIJIIJIJJJ;

	public UISprite IJIJIJIJJIJIJJIJIJJJJJJIIIIJIJIIJIJIIJIJJJJJJJI;

	public UILabel IJJJJIIIJIJJJJIIJJJIJJIIJIIJJJJJJIIIIJJIIJIIJIJ;

	public UILabel JJJIJJIIJJIJIJJIIJIJIJIIJJJIIJJJJIJIJJIIJIIJIII;

	public UISprite JIIJJJJIJJIJIIJIJJIIJIJJIIJJIIIJIJIIIIIIJJJJIJJ;

	public UISprite JJIIJIJJJJIIIJIIJIJIIJJIJJIJIJIJIJJIIIJJIIIIJII;

	public UIGrid IJJIJIIIJJIIIIIIIIIIIIIIIIJIIJJJIJIJIIJIJJIJJJI;

	public UISprite[] JJIIJIJJIJJJJJJIJIIJIJIJIJIIJIJJJJJJIJIJJIIIJII;

	public JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ;

	private static float JIJIIIJJIIIJJJIJJJIIIIIIIJIIIJJIIIJJJJIIJIJIIJI;

	public void JJJIJJJIIIJIJIJIIIIIJJJJJJJJIJJJIIIIIJIIJJJJJIJ()
	{
	}

	private static Color JIJIJJJJJJJIIJJIIIJJJJJIJIJJIIJJJIIJIIJJIIIIIII(JIIJIJJJIJIJJIJIIJJIJIIIJIIJJIIIJIIIIJJIJJIJJJI IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	public void JJJIJIJIJJJIJJIJIIJIJIJJJJJIIIJIIIIJIJJIJJJIIIJ()
	{
	}

	public void IIJIIIJIJIIJIIIJIIIJJIJJIIJIJJJIIJJJJIJJIIJIJJI()
	{
	}

	public void JJIJJJIIIJIJJJIJIIIIJIIJIJIJJJIJJJJJIIJIIIIIIJI()
	{
	}

	private static Color IIIJJJJJJJJJJIJJIIIIJIIIIIIJIJJJIJJIIJJJJIJJJII(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	private static Color JIJIJJJJIJJJIIIJJIIIIJJJJIJJJJJIJJJIJJIIIIJJIII(JIIJIJJJIJIJJIJIIJJIJIIIJIIJJIIIJIIIIJJIJJIJJJI IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	public void OnClick()
	{
	}

	public void IIIIIIJIIJJIIJJJJJIIJIIJIIJJIJJJJJIJIJJJJIIJIIJ()
	{
	}

	public void JJIIIJIIIIIIJIJJJIJJIIIJIJJIIJJIJIIJIIJIIIIIIIJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	private static Color IIIJJIIIJJIIJIJJIJIJJJJJJIJIJIJJJIJIJJIIJIIIIJI(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	public void JJIJJJJIJIIIIIJIIIJIJJJIIJIIIIJJIIJIIJJJIIJJIII(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	public void IJJIIIIJJJIIIIJJIIIIIJJJIIIIJIJIJIIJJJIJIIIIJII()
	{
	}

	public void IJIIJJJIIJJIJJIIIJIIJJIJIIIIJJJIIJJJIJJIJIJIJIJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	private static Color IJJIIIJJJIJIJJIIJJJIIIIJIIJJIIJJJJJJIIJJJJJJJIJ(JIIJIJJJIJIJJIJIIJJIJIIIJIIJJIIIJIIIIJJIJJIJJJI IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	private static Color JIIJJJJJJJJJJIJIIJJJJIIIJJIIJIJJIJIJIJJJJIIIJII(JIIJIJJJIJIJJIJIIJJIJIIIJIIJJIIIJIIIIJJIJJIJJJI IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	public void IIJIIJIIIJJIIJJIIJJJIIJIJIIJIJIJJJJIJIJIJIJJJIJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	public void IIJIIIIIJJJIJJJIJIJIJJIIJIJJIIJIIJIJIIIIJJIIIJI()
	{
	}
}
