using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class mInventoryStickersManager : MonoBehaviour
{
	private JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ;

	public UIScrollView IJIIIJJJJJIIIJJIIIJIIJJJJIIIIJJJJIIIJIIJIJIIJII;

	public UISprite IJIIJJJJJIIJJJIJIJJIJIJJIIJIIIJJJJJIIIJIIIIJIII;

	private List<UISprite> JJJIIJJJJJIJIIJJJJJJJJJJIIJJJIJJIIIIIJIIIIIJIIJ;

	private List<UISprite> JIJIJIJIIJIJIIJJIIJIIJIJJIIIJIIJIJJJIIJIIJIIIII;

	private int JJJJJJJIIJIIJJJIIJJIIJIIIJJJJJJJIJJJJJJJJIJJJII;

	public UILabel JIJJJJJJIJJIIJJJJJIJIIJJIJJJJJJIIJJIJIIIJJJJJJI;

	public UIWidget JIIIIIIJJJJJIJJIJIJIIJJIIJJJJJIJJIJJJJIJIJJIJII;

	public UIWidget JIJIIJJIJJJIJIJIIJJJIJIJJJIIIJIJIJIIIJIJIJIJIJJ;

	public UIWidget IIJIJJIJJJIJIIJIIJJJIIIJJJIJJIJIJJJJIIJJJJIJIII;

	private int IJIJJIJIJIJIIIJJJJJIJJJIJJJIIIJIIJJJJJJIJIIJJJJ;

	private int[] IIIJIJJJIJJIJIIIJIIJJJIIIIIJIJIJIIIIIIIJJJIIIII;

	private int IIJJJIIJIJJJIJJJIIJIIJJJIJIJIIIJIJIIJIIJIJJJIII;

	private bool IJIIJIIJJJJIIJIJJIJJIJIIJIIIIIIJIIJIIJIIIIJJIIJ;

	private static mInventoryStickersManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	[CompilerGenerated]
	private void JJJIJIIIIJJIJIJIJIJJJIIJJIIIIIIIIIIIIJJJJIIJJIJ()
	{
	}

	private void IIJJJJJJJIIIIJIIIIIIJJJIJIJIIJIJJIJIIIIJJJIJJJI()
	{
	}

	private void IIJIIIIIJIIIJIJJJJIIIIJIIIIJIIJIJIIIJJIJIJJIIII()
	{
	}

	private void IIIJJJJJIIIJIIJJJIIIJJIJIJIIIIJIJIJIIJJIJIIIIJI()
	{
	}

	public void JJJIIJIJJIJIIJIIJIJIIIIJJJJIIJJIJJIIIIJJIIJJJJI()
	{
	}

	public void JJIJIIJIIJIJJJJJIJJIJJIJIJJIJIJIIIIJJJIJIIIJIII()
	{
	}

	private void JIJIIIIJJIIJIJJJJIJIIIJJJJIJJIIIJJJJIIJJIIJJIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 JJJIIJIIIIIIJJJIIJJJJIJIIJJIJIIIIJJIIJJJJJJJJJI)
	{
	}

	public void SetSticker()
	{
	}

	public void LastStickerPos()
	{
	}

	private void Start()
	{
	}

	public static void IIIIIJIJIJJIIIJIIIJJJJIJJIIIIJIJJJIJJIIIIJJJIJI(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	private void IIJIJJIJIJJJJIJIJJIJIIIIJJJJIIIJIIIIJJJIIJJJJII()
	{
	}

	public void IIJIIIIJIIIJJJJJIIIIIJIIJJIJIJJJJIIJIIIJIJJIIIJ()
	{
	}

	public void NextStickerPos()
	{
	}

	private void IJIIJIJJIJIJIIJJJIIJIJIJIIJJIIJIJIIJIIIIJJJIJJI()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	public void DeleteSticker()
	{
	}

	private void JJJIJIJJJIJIIJIIIJIIJJIIIIJIJJIIJJIIJIJIJIIIJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 JJJIIJIIIIIIJJJIIJJJJIJIIJJIJIIIIJJIIJJJJJJJJJI)
	{
	}

	private void JIIJJJIIJIIIIIJJIIJJIJJJJIIIJIJJIIIJJJJIIJIIJJJ()
	{
	}

	public void SelectSticker(GameObject go)
	{
	}

	public void Close()
	{
	}

	[CompilerGenerated]
	private void IJIIIJIIIJIJIIJJJJJJIJJJIIIIIIIJJJJJIJJIIJJIJJI()
	{
	}

	private void JJIIJJIIJJJIIIIIIIJIJIIJJJJIIIJJIJJJIIIJIIJJJJI()
	{
	}

	private UISprite JIIJIIJIIJIJJJIIIJIIJJJJIIJIJJJJIIJJIIJJJIIJIJI()
	{
		return null;
	}

	[CompilerGenerated]
	private void IJJIJJJJIIIIIIJIJJIIJJJJIIJJJIJJJJIIJIJIJJIJJJJ()
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	public static void IJIJIJIJIIIJJIJJIIIIJIIIIJIIJIJJIIJIIIIJJIJIIII(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	private void JIJJIIIJIJIJIIIIJIIJIJIIIJIJJIJIIIIJJIIIJJIIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 JJJIIJIIIIIIJJJIIJJJJIJIIJJIJIIIIJJIIJJJJJJJJJI)
	{
	}

	[CompilerGenerated]
	private void IJJIJJIJIIIIJJIIJJIJJJJJIJJIJIJJJIIIJJIIJJJJJJJ()
	{
	}
}
