using System.Runtime.CompilerServices;
using DG.Tweening;
using UnityEngine;

public class mLoadingEffect : MonoBehaviour
{
	public UITexture IIJIJIIIJJJIIIJJIIJJIJIIIIIIJJJIIJIJIJJIIIJIIIJ;

	public float IIIIJJJIJIJIIIIJIIIJJIIIJJJJIJIIIIJIJJJIIIIJIJJ;

	private Tweener IIIJJIIJIIIIIJJJIJIIIJJIJIJIJIIIIIJIIJJIIJIIIJJ;

	private Tweener IIIIJIIJJJIJJJJJJIIJJJJJIJJIIIIJJJJIIJIJIIIJJII;

	private void JIJIJIIJJJIIIJJIIIIIJJJJJJIIIIIJIIJJIIIJIIJJIJJ(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
	{
	}

	private float IIIIJJJJIJJJJJJJJIJJIJIJJIJJJIIIJJJJJIJJJJJJIII()
	{
		return 0f;
	}

	private void OnEnable()
	{
	}

	private void OnDisable()
	{
	}

	[CompilerGenerated]
	private void JJJJIJJJIJJIJJIIJJIIIJIIIIJJIJJIJJJJJJJJJJIJIII(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
	{
	}

	private void IIJJIIIIJIIJJJJJIJIIIJJIJJJJIIIIIIIIIJIJIIIIIII()
	{
	}

	private void IIIJJJIJIIIJJIJIIJJIIIIJIIIJJJIIIIIJIIIJJIIJJII()
	{
	}

	private void JJIIJIIJIIIIIIJJIJJIJIIIJIJJIIJJIIJIIJIJJIJJJIJ()
	{
	}

	private void IJJJIIJJIIJIJIJIIJIJIIJJJJJIJJJIJIJJIJJJIIJJJJJ()
	{
	}

	private void JIJIJIIIJIIJJIIIIIJJIJIIIIJJJIJIJJIJIJIIIIJIJJI()
	{
	}

	private float JIIIJJJIIJJJIJIIJJIIJJJJJIJIIJJIIJIJJIJJJIIIIJJ()
	{
		return 0f;
	}

	[CompilerGenerated]
	private float JIIIIJJJIIIJIIJIIIJJJJJIIJIJJJIJIJIIIIJIJIIIJJJ()
	{
		return 0f;
	}

	private void JJIJIJIJJJJJIIJJIIIJJIJIIIJJIIJJJIIIIJIJJIIIIJI()
	{
	}

	private void JJJIJIIJJIIJJJIIIJJIIIJJJIJJIIJJIIIJIIJJIJIJJJJ()
	{
	}

	private void IJJIIJJIIJJIIJJJJJJIIIJJJJJIJIIJIJIIJIIJIIIIJII()
	{
	}

	private void IJIJJIIIIIJIJIJIIJJIIJJJJIIIJIJIIJJJJIIIJJIIJII()
	{
	}

	private void JJJIIIIIJIIJJIJIJJJJIIJIIIIIIJJJJJJIJIJIIJJJIJJ()
	{
	}

	private void JIJIIJJIIIJJJJIJJJJIJJJIIIIJIJIJJIIIIJIJIJIJIJJ(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
	{
	}

	private void JIIJIJIIIJJJIIJIIIIIJIJJJIJJIJIIIJJJIJIIJIJIJIJ()
	{
	}

	private void IIJJJJJIIJJJJJJJJJIIIIJIIJJJIIIIIJIIIJIIJIJJIJJ()
	{
	}

	private void JIJJIIIIIIJIIIIJIJJIJIIIJIIIIIJIJIJIJIJJJIJJJIJ()
	{
	}
}
