using System.Runtime.CompilerServices;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mMapCamera : MonoBehaviour
{
	public float JJJIJIJIJIJJIJIIJIJIIJJIIIJJJJIIJJJIIJIIIIIJJII;

	public float IJIJIIIJIJIJIIIJIJJIJIIJJJJIIIIIJJIJIJJIJIJJJII;

	public MeshAtlas[] IJJJIJJJIIIJJJJJJIIJJJIJJIIJJIJIIIIJJIJJJJJJIIJ;

	public MeshAtlas[] IIJIJIIIIJIIJIIIJIIIJIJIIIJJIIIIIIIIIJIIIIIIJII;

	public MeshAtlas[] IIIIIIJIJIJIIIJIIIJIIJIIIIJIIIIJIIIIJIJIJJIJIJJ;

	public MeshAtlas[] JJIIIIIJIIJJIJJJJJJJIIJJJIJIJIJJJJJJJIIIIIJJJJI;

	public MeshAtlas[] JJIIIJJJIIIJIIIJJJJJIIIIJIIJJJJJIJIIJIJIJJJIJJJ;

	public MeshAtlas[] JJIIIJJIJIJIIJJJJJIJJJJIJIJIIIIJJJIJIIJJIJIJJIJ;

	private Transform JJIJIIJIIJJJJJIIIJIIIJJJIJJJIIIIJJIJJJIIIJJIIII;

	private Vector3 IJJIJIIIIJJJJJJJJIJIIIIJJJJJJIIJJIJIJIJIIJJJJIJ;

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void Start()
	{
	}

	private void IJIJIJIIJJIIIJJIJIJIJJIJIIIIJJIJIIIIJIIJIIJIIII()
	{
	}

	[CompilerGenerated]
	private void JIIIIJIJJIJJIIJIJJIIJIIJJIJJIIIIIJIIJIIJIJJIJIJ()
	{
	}

	private void LateUpdate()
	{
	}

	private void JJJIIIJIIJIJIIIIIIIJJJIJIJJIIJIIJIIJIIJJIJJJJJI()
	{
	}

	private void IJIIJJIJIJIIIIIJIIIIJIJJIJIIIJIIJIIIJIJJIJJIJII()
	{
	}

	private void IIIJIIJJJJIJJIIJIIIJJJIIJJJJJJJJJIIJIIJIJIIIJIJ()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void IJIIIIJIIIIIJJIJJIIIIJIJIIIIIIJJJJIJJIIJIJJJJII()
	{
	}

	private void IJJJJJJJIIJJIJJIJJIJIIJIIIIJJJIIIJIIIIIIJIIJIIJ()
	{
	}

	private void JIJIIJIJIIJJJJJIIJJIJJJIIJIJIIJIJIJJJIIJJJIIIJJ()
	{
	}

	private void JJJIIIIIJIJIIJIJIJIIIJIJJIJJIJIIJIJIIJJIIJJJJJI()
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void IIIJJJJJJIIJIIIJJIJIIIIJJJIIJIJJIJIIIIJIIIIIJJI()
	{
	}

	private void JIIIJIJJJIIIIJIIJIJIIIIIJJIJIIJIJIIIIJJIJJJJJII()
	{
	}
}
