using System.Runtime.CompilerServices;
using UnityEngine;

public class mMarketFilter : MonoBehaviour
{
	public UIPopupList IIIIIJJIIIIIJIJJJIJJJJJIJIIJIJIJJJJJJIIJIIIIJJI;

	public UIPopupList JIJIIJIJIIIIIIJIIJIIJIIJIIIIJJIIIIIIJJJIJJJIIII;

	public UIPopupList JIJIIJJIIJJIIIJIIIJJJJIJJJJIIIIJJIJJJJJIIIIIIJJ;

	public UIPopupList JIIIIIIIJJJJIIJIIIIJIJJJIIIIIIIJJIIIIJJIIJIIIJI;

	public UIInput IIJJIJJIIJJIJJJJIIIJIJJIJIIIIIIIIIJJJJJIJJIIIJJ;

	public UIInput IIJIIJIJIJJJJJJIIIJJIJJJJIJJIIJJJJJJJIJJJJIIIIJ;

	public UIGrid IIIIIIJIJJJIIIIIIIIIJIJIIIIIJIIIJIJJJJIIJJJJIJI;

	private bool JJIJJJIIJJIJIJIJIJIIJIJIIIJJJIJIJJJIIJIJIIJJIIJ;

	private static mMarketFilter JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static int JJIIIJIIIJJIIJIJJJJJIJIIJJIJJJIJIJIJJIJIJJIIJIJ => IJJIJIJIIJIIJJJJIJIIIIJJJJIIJJIIIIJJJJIIIJJJIJI();

	public static int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ => IJJIJIIIJJIIIJJIIIIIIIJIJJIJIIJJJJJIJJIIIIJIJIJ();

	public static int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ => JIIJIIIIJIJIIJJIJJJJIJJIJJJIJJJJIJIIIIJIJJIIJJJ();

	public static int IIIJJJIJJIIJIJJIJIJIJJIIIJJIIIJIIJIJJJJIJIIIIJI => IIJIJIIJIIIJIIIJJIJJIJIJIIIJIIIIJJIJIIJJIJJIJII();

	public static int JJJIIJIIIJIIIJIJIIJJJIIIJIJIIJJIJJJIIIIIJIIIJJJ => JJJIJIJJJJJJJIIIJIJJIIIIIJIIIJIIIIIJJIJIIJIIIJJ();

	public static int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ => JIJIIJIIJIIJIJJIJIJIIIIJJJJJIJIJJJJIJJIJIIIJIJJ();

	public void OnSubmitMinPrice()
	{
	}

	public void SelectItem()
	{
	}

	public static int JJJIJIJJJJJJJIIIJIJJIIIIIJIIIJIIIIIJJIJIIJIIIJJ()
	{
		return 0;
	}

	public void IJIJJIIIIJIJJJJIJJJIJJIJIIJIJJIIJIIJIJJIIIIIIJI()
	{
	}

	public static int IIJIJIIJIIIJIIIJJIJJIJIJIIIJIIIIJJIJIIJJIJJIJII()
	{
		return 0;
	}

	public void IIIJJIJJJJJJIIJJIJIIIJIIJIIIJIIIIJIIIJIJJIJIIJJ()
	{
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}
	public static int IJJJIIJJJIIJIJIJJIIJJIIJIJJJIJJIIJIJIIJIIIIIJJJ()
	{
		return 0;
	}

	public void SelectWeapon()
	{
	}

	public static int JIIJIIIIJIJIIJJIJJJJIJJIJJJIJJJJIJIIIIJIJJIIJJJ()
	{
		return 0;
	}
	public static int IJIIIJIJJJJIJIIIIIJIJJJIJJIIIJJIJIIJIJJJJIIIIJJ()
	{
		return 0;
	}

	public void Open()
	{
	}

	public void JJIIJJIJIJIIIJJJIIIIIIIIIJIJIIJJJJJJJJIIIIJIJJJ()
	{
	}

	public void IIJJJJIJIJJJIJIIIIJIJJJIJJJJIJJIJJIIJJIIJIJIJJI()
	{
	}

	public static int JIJIIJIIJIIJIJJIJIJIIIIJJJJJIJIJJJJIJJIJIIIJIJJ()
	{
		return 0;
	}

	public void OnSubmitPlayerID()
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	public void JIIJIJIJJIIIJJJJJIIIJJJIJIIJIJJIJJIIJJIJJJIIIIJ()
	{
	}
	public static int JIIJIJJJJIJIJIIIJJIIIIJIJJIJIJJJIJIIJIJIJIIJIIJ()
	{
		return 0;
	}

	public void IJIIIIJJJJJJIIJIJJJIJJJJIJJJJJJJIJJJJJIIIIIJJJJ()
	{
	}

	public void JIJIJIJJIJIIJJJJIJIIJIIJJIJJIJIIJIIJJJIJJIJIJJI()
	{
	}

	public void IJIIJIIJJJJJIIJIIIJJIIJJIJIJIIJJJIJIIIJJIIJIIIJ()
	{
	}

	public static int IJJIJIIIJJIIIJJIIIIIIIJIJJIJIIJJJJJIJJIIIIJIJIJ()
	{
		return 0;
	}
	public static int JJJJJIIIIIJIIJIJIIJJJJIJJJIIIIJIJJIIIJJJIIJIIII()
	{
		return 0;
	}
	public static int JJIJIIIIJJJJJIIJIIJJJIIJIJIJJJJIIJIIJJJIIJJIIJI()
	{
		return 0;
	}

	public static int IJJIJIJIIJIIJJJJIJIIIIJJJJIIJJIIIIJJJJIIIJJJIJI()
	{
		return 0;
	}
	public static int JJJJIIJJIJIIIIIJJJJJJIJIJIIIIIJJJIJIIJJIIJIJIJJ()
	{
		return 0;
	}

	private void IIJJIJIJJJJJIJJIIJIJIJJIIJIJIIJJIIIJJIIIJIIIJJI()
	{
	}
	public static int JJIJJIJIJIIJJJIIIJJIIJIIJIIJIIJIJJJJIIJIJIJJJJI()
	{
		return 0;
	}

	private void Start()
	{
	}
	public static int JJJJIIIJIIJJIJJIJJIJIIJJJIJJIJIIIIJJIJIJIJJJJJJ()
	{
		return 0;
	}
}
