using UnityEngine;

public class mMarketplaceElement : MonoBehaviour
{
	public GameObject IIIJIJJIJIIJIJJJIJIIIIJIIIJJIJIJIJJJJIJJJJJIIIJ;

	public UISprite IJIIIJJIIIJJIIIIJIJIIIJJJJJJJIIIJIIJIJJJIIJJIJJ;

	public UISprite IJJIIIJJJJJIJJJIIIIJIJJJIIIIJJIIJIJJIIIJIIJIJJJ;

	public UISprite IJIJIJIJJIJIJJIJIJJJJJJIIIIJIJIIJIJIIJIJJJJJJJI;

	public UILabel IJJJJIIIJIJJJJIIJJJIJJIIJIIJJJJJJIIIIJJIIJIIJIJ;

	public UILabel JJJIJJIIJJIJIJJIIJIJIJIIJJJIIJJJJIJIJJIIJIIJIII;

	public UISprite JIIJJJJIJJIJIIJIJJIIJIJJIIJJIIIJIJIIIIIIJJJJIJJ;

	public UILabel IIJIJIIJJIJJIIIIJIJIIIIJIJJIIJIJJIJJIJJJJJJIJII;

	public UIGrid IJJIJIIIJJIIIIIIIIIIIIIIIIJIIJJJIJIJIIJIJJIJJJI;

	public UISprite[] JJIIJIJJIJJJJJJIJIIJIJIJIJIIJIJJJJJJIJIJJIIIJII;

	public JJIJJJJJIJJJJJJIIIJJJJJIIJIIJIJIIJJJJIIIIIJJJJI JIJJIIIIIJIIIIIIIJIJJIJJJIJIIJIJJIIJIJIJJJIIJII;

	private static float JIJIIIJJIIIJJJIJJJIIIIIIIJIIIJJIIIJJJJIIJIJIIJI;

	private static Color IIIJJIIIJJIIJIJJIJIJJJJJJIJIJIJJJIJIJJIIJIIIIJI(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	private static Color JJIIIJJJIIJIIJJJJJIJJJIJIJIIIJJIJIJIJJIJJJIIJJI(JIIJIJJJIJIJJIJIIJJIJIIIJIIJJIIIJIIIIJJIJJIJJJI IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	public void IIJIIJIIIJJIIJJIIJJJIIJIJIIJIJIJJJJIJIJIJIJJJIJ(JJIJJJJJIJJJJJJIIIJJJJJIIJIIJIJIIJJJJIIIIIJJJJI IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	private static Color IIJJJIJJJIJIIJIIJJIJIIJJIIIIIJIIIJIJJJIIJIJIJJJ(JIIJIJJJIJIJJIJIIJJIJIIIJIIJJIIIJIIIIJJIJJIJJJI IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	public void OnClick()
	{
	}

	private static Color IJJIIIJJJIJIJJIIJJJIIIIJIIJJIIJJJJJJIIJJJJJJJIJ(JIIJIJJJIJIJJIJIIJJIJIIIJIIJJIIIJIIIIJJIJJIJJJI IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	private static Color JIJIJJJJJJJIIJJIIIJJJJJIJIJJIIJJJIIJIIJJIIIIIII(JIIJIJJJIJIJJIJIIJJIJIIIJIIJJIIIJIIIIJJIJJIJJJI IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	public void IIJJIJJIJIIIIJJJJJIJIJJJIJIIJJJIIIIIIJJIJIIJJIJ(JJIJJJJJIJJJJJJIIIJJJJJIIJIIJIJIIJJJJIIIIIJJJJI IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	public void JIIJIJJIJIIJIJJIIIJIJIJIJJJJJJJIIJJIIJIJIJJJIJJ(JJIJJJJJIJJJJJJIIIJJJJJIIJIIJIJIIJJJJIIIIIJJJJI IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	private static Color JIJIJJJJIJJJIIIJJIIIIJJJJIJJJJJIJJJIJJIIIIJJIII(JIIJIJJJIJIJJIJIIJJIJIIIJIIJJIIIJIIIIJJIJJIJJJI IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	private static Color IIJJJJIIIIIIJJIIIIJJJIJJJIIIIIIIJIJJJJIJIIIJJII(JIIJIJJJIJIJJIJIIJJIJIIIJIIJJIIIJIIIIJJIJJIJJJI IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	public void IJIJIIJJIIJIJJIIIJJJIJIJIJJIIIIIJIIJIJJIJJJJIII(JJIJJJJJIJJJJJJIIIJJJJJIIJIIJIJIIJJJJIIIIIJJJJI IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	private static Color IJJIIJIJJIJJJJIIIJIIJIIJJJJJIIJIIJJJJIIIJJJIJII(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	public void IIJJIJJIJIIIJJIIJIIIJIIIIIJIJIIIIIJIIJIJJJJJIIJ()
	{
	}

	public void IJIIJJJIIJJIJJIIIJIIJJIJIIIIJJJIIJJJIJJIJIJIJIJ(JJIJJJJJIJJJJJJIIIJJJJJIIJIIJIJIIJJJJIIIIIJJJJI IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	public void IJJIIIIJJJIIIIJJIIIIIJJJIIIIJIJIJIIJJJIJIIIIJII()
	{
	}
}
