using System;
using System.Collections.Generic;
using UnityEngine;

public class mMessageManager : MonoBehaviour
{
	public class IIJIJIIJIIIIJJIJJIIJIIIJIJJJJIIJIJJJJIIJIIIJIJI
	{
		public string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII;

		public string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI;

		public string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI;

		public string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI;

		public Action IIJJJIIIJJJJIJJIIIIJIJJJJJJJJJJJIIJJIIJIIIJIIII;

		public Action IJIIJJJIIIJJIJJJJIJJIJJJJIIJIIJIIJJJJJJIIJIJJIJ;
	}

	public List<IIJIJIIJIIIIJJIJJIIJIIIJIJJJJIIJIJJJJIIJIIIJIJI> IIJIIIIIIJIIJJJJIJIJJIIJIJJIIJIJIJIJIIIJJJIIJII;

	private bool JJJIJIJJJIJIJJIIJIIIJIJIJIJIJJIIIJJJIIJJJIIIJJJ;

	private static mMessageManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void IJIJJIIIJJIIJIJJIIJIIJIIJJJIIJJIJJIJIIIIIJJIJIJ()
	{
	}

	private void JJJIIJIJJIJJJJIJIIIIJIIJJIJJIIJIJJJIJIJIJJIIJJI()
	{
	}

	private void Awake()
	{
	}

	public static void IJIJJIIJJIIJIJJJJJIJJIJIIJJIJIIIIJIIIJJJJIIJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	public static void IJIJJJIIJJJJJIIIIJIIIIJJJJJJIJJIIIIJIJJJJJJJJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	private void IJJJJIJJIJJIIJJIJIJIJIIJJJJIIIJJJJJIJIJIJIJJJII()
	{
	}

	private void JIIIIIIIIJJIJJIJJIJIJJIJIJJIIIIJIJIJIIJJJJIJIJJ()
	{
	}

	private void IIJJJJIIJIJJJIIJJJJIIIJIJJIIIIJJJJJJJIJJJJIJIJI()
	{
	}

	public static void JJJIIJIIJJIJJIJIIIJJIIJIJJIIIJIJIIIIJJJIJJJJJIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	private void IJJJJJJIJJJJJIJJIIJJIIIIIIJIJIJIIIIIJIJJIIIIIJI()
	{
	}

	private void IIIJJIIIJIIJJIJJJJIIIJIJJIJIIJJIJIJIJIIIIIIIIJI()
	{
	}

	public static void IJJJJIJJIJIJIJIIIJIJJIIIJIIIJIJJIJJIIJIJJJJIIJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	private void JIIJJIJJJIJJJIIJJJJIIIJJIIIIJIIJJIIIIJIIIJIIIJJ()
	{
	}

	private void IJJJJIJIIJJJJJIIJIJJIIJJIJJIIIJJJIJIJIJJIIIIJII()
	{
	}

	private void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ()
	{
	}

	private void IJIJJIIJJJIIIIJIIJJJIIIIJIIIJIJIIJIJIIIJJJIJIII()
	{
	}

	private void IIIJIJJJIIJIIIJIIJJJIJJIJIIJJJIJJIIIJJJJIIJJJIJ()
	{
	}

	private void JIJIIIJIJJIJJJJJJJIIIJIIIJJJJJIJIJIJJIJJJJIIIII()
	{
	}

	private void IIIJJIJIJJJIIIIIIIJIIIJIJIIJIIJIIJJIJJJJIJIIJJJ()
	{
	}

	private void IIIJIJJIIIIJIJIJJJJJJJJJIJIJJJIIIJIJIJIJJIIIJJI()
	{
	}

	private void JIJJJIIIJJJIJJJIJJIIIJJJIJIJJIJIIIJIJJIIJJIJIIJ()
	{
	}

	private void JJJJJJIIJJJJIJJJJIJJIJJJIJJIIJJIIJIIJJIJIJJIIJJ()
	{
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}
}
