using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mOthers : MonoBehaviour
{
	private sealed class JJIIJJIJIIJJJIIJIIIIIIIIIJJIIJJIIIJJIIIIIJIIJJI
	{
		public string IJIIJIJJIIIJJJJIJJJJIIIJIIJIJJIIJJJIJJIJIJJJJJI;

		internal void JJJIJJJJJIJJJIJJIJJJJIJJJIJJJJIJIJJJJIIIJJIIIIJ()
		{
		}

		internal void IJJIIJJIJIJJJJJIJIIIIJIIJIIIIIIJIJJJIIJIIJIJIII()
		{
		}

		internal void JJJJJIJIJJIIIJJIJJJJJJJIJJIJJJIIJJIIIJIIJJIJIJI()
		{
		}

		internal void JJJJJIIJIJIJIJIIJJIJIJJJIJJIJJJJJJIJJIJJIJIJIII()
		{
		}

		internal void IIJJIJJJIJIIIJIJJJJIJIIJIIJIJJIIIJIIJIJIJIJJJJI()
		{
		}

		internal void JJJJIIIJJIJJIIIIJIIIJIJIIJJIIIIIIJIJJIJJIJJJJJJ()
		{
		}

		internal void IJJIIJIJJJJIIJIJIIJJIJJJIIIIJJIJIIJJJJJIIIJJIJI()
		{
		}

		internal void IIIJJJIJJJJJIIJJIIIJJJIIJJJJIIJIJIJIIIJIIIJIIJI()
		{
		}

		internal void IIIIIIIJIIIJJIIIJIIJJJJIIIIIJIJJJJJJJJJIIJIJIII()
		{
		}

		internal void IIIJIJJJJIIIJJIIJIJIIJIIJJJIJIIJJJJIIJIIIIJIJJI()
		{
		}

		internal void IIJJIJIJIIJIIIIJIIIIJIIIIJJIIJJIJJIJJIIIIIJJJJJ()
		{
		}

		internal void IJIJJJIJIIIIIIIIIJIIIJIJJJIJIIJJJIIIIJJJJIJIJJI()
		{
		}
	}

	private sealed class IJJIJIIJIIIJJIJIJIIJIJIJIIIJJIJIJIJJIIIIIIIIIJI
	{
		public string JIIIJJJJIIIJIIIJJJJIJIIIJIIIJJIIJJIJJIIIIIIIJJI;

		internal void JJJIIJJIJIJJJJJJJJIIJJIIJIIJJJIJIIJIIJJJIIIIIJI()
		{
		}

		internal void JJIIIJJIIIIJJJJJJJJJIIIJJIIJIJJIJIIJIIJIIIIIJJI()
		{
		}

		internal void JIIIJIIJJJJIIJIJIJJJJIJJJIJJIIJIIJIJIJIIIJIIJIJ()
		{
		}

		internal void IJIJJIJIIJIJIJIIJJJIJJIJJIIIJJJIIJIJJIJIIJIIJIJ()
		{
		}

		internal void JJIIIIJJIIIIJIIIJJJIJJJIIIJJJJJIIJIIIIJIJJIJJIJ()
		{
		}

		internal void JIIJIIIJJIJIIIJIJIJIJIIJJJJJIJJJJIJJIIIIJJJIIJI()
		{
		}

		internal void JIIIJIJIJJIJJIIIJJJJJIIJIIIIJIIJJIJIIIIJJJIJIIJ()
		{
		}

		internal void IIIJIJJJIJIJJJIIIIIJJJIIJJJIJJJIIIIJIIIIJIJJIIJ()
		{
		}

		internal void JIJJJJIIJIIIJIJIJIJIIJJIIJJIJJJJIIIIIJJJIIJIJIJ()
		{
		}

		internal void IJJIIIIJIJJIIIIJJJIIJIIJIIJIIJIJIJIJIIJJJIIJIJJ()
		{
		}

		internal void JIJJIIJJIJJJIJIIJJIJJJIJIJJJJIJJIJIIIIJJJIIJJIJ()
		{
		}

		internal void IIJIIJJJIIJIIIIJIJIIIJIJIIIIJJJJIJIJIIJJIJIJIIJ()
		{
		}

		internal void IJIIJIIIIJIIJIJJIJIIIIJJJIJIJIIJIIIIJJJIIJJIJIJ()
		{
		}

		internal void JJIJJJJIJJIIJJIIIIJJIIJIJJJIJIIJJIJIIJJIJJJIJJI()
		{
		}

		internal void JJIIJIIIIJIJJIJJIIIIJJJJIJIJJIIJJJJIIIJJIJJIIIJ()
		{
		}

		internal void JJIIIJIJJJJIJJIIJJJIJIIJJJIIIIJIJIJJIJIIJIIJIJI()
		{
		}

		internal void JJJIJJIIIJJIIIJJIIJIIIIIJIIIIJJIJIJIJIJIIJIJJJJ()
		{
		}

		internal void JIIJJIJJIIIJJJIJIIJJJJIJJIJJIIJJIJJJJJJIJJIIJII()
		{
		}

		internal void JIIJIIJIIIJJJJJJIJJJIIJJIJIJIJJIIIIJIJJIJJIJIII()
		{
		}

		internal void IIIIJJIJJJJJJJJIJJIIIJJIIJIJIJIJJJIJJIIIIIJIIJI()
		{
		}

		internal void IJJJIIJIJJJIIJIIIIIIIIIJJJJJIJIIJJJIIJIJIIIIJJI()
		{
		}
	}

	public AudioClip JJJIJIJJIJIIIIJIJJJIIJIIIIJIJJIIJJIJJJJJIJJIJJI;

	private AudioSource IIJIJIIIIJJJJJIJJJIIIJIJJIJJIJIIJIJJIIIJJJIIJIJ;

	private void IIJIIJIJJIIIIIJIJJIJJJIIJJIJIJIJIIJJJIIJJIJJIII()
	{
	}

	private void JJJJIIIJIIJJIJIIJJIIIJJIJJJIIIJIJJJJJIIIJIIIJJJ()
	{
	}

	public void AccountUpdate()
	{
	}

	public void OpenStore()
	{
	}

	private void Start()
	{
	}

	private void JIIJIIIJJJJJJIIJJIIIIIIJJIJIJIIJIIIJIJIIIJJJIIJ()
	{
	}

	public void ShowOthersGames()
	{
	Application.OpenURL("https://play.google.com/store/apps/dev?id=6363329851677974248");
	}

	private void JIJJJJJIIIIJJIJIJIJIJIIIJJJIIJJIJJIIJIIJJJIIJII()
	{
	}

	private void IIIJIIIJIJIJJJJIIIIIIJIJJJJIJJIJJIJJIIJIJJIJJJJ()
	{
	}

	public static void JIIIIIIJIJJJJJIIJJJIIJIIIJIIIIJJIJJJIIJJJJJIJII(string JIIIJJJJIIIJIIIJJJJIJIIIJIIIJJIIJJIJJIIIIIIIJJI)
	{
	}

	public static void IJJIIJIJJIIIJJIIIJJIIIIIJJIIIIIIJJJIIJJJIJIJJII(string JIIIJJJJIIIJIIIJJJJIJIIIJIIIJJIIJJIJJIIIIIIIJJI)
	{
	}

	public void ExitGame()
	{
	Application.Quit();
	}

	private void IJIJJIJJJJIIIJJIJIJIJJIIIJJIIJJIIIIJJJJJJIJIIJI()
	{
	}

	private void JIIIJIJIIJIJJJIIIIIJJIIJIIIIIJIIJIIJIJJJIJIIJJJ()
	{
	}

	private void JIIJJIIJJIIJIIJIJJIIJJIJIJJJJJIIIJIIIJIJJIIJJIJ()
	{
	}

	public void JJIIIJIJIJJJJJJJIIIIIJJIIIJJJIIIJIJIIIIJIIIIJIJ(string text)
	{
	}

	public void IIJJJIJIJJIIIJIJJJJJJIJJIIIIJIJIJIJJIJJJJIIJJJI()
	{
	}

	public void JJJIIIJIJJIJJIJIJIIIIJIIJIJIIIJIJJJJIJIJJIJJJJI()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	public void JIIIJJIJIIJIJIIJIIJJJJJJJJIIJJJIJJIIJJIIIJJIIII(string text)
	{
	}

	private void JIIJIIJJJIIIIIJIJJJIIJIIIJJIJIIJIIJJIIIJIIIIJJI()
	{
	}

	public void ComingSoon()
	{
	}

	public void ShowToast(string text)
	{
	UIToast.IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJII(text);
	}

	public void IJJIJIIJJJJIJIJJJIIIIJJIJIJJIJJJJIJJJJJJJIJJJIJ()
	{
	}
}
