using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class mPanelManager : MonoBehaviour
{
	private sealed class JIIJIIJIIIIIJJIJIIJIIJIJIIJIJJJJJJJJJJIJJJIJIIJ
	{
		public UIPanel JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ;

		internal void IJIJJIJJJJIJJJJIJIIIIIJJJIJJIIIIJJIIJIIJJJIJIII()
		{
		}

		internal void JJJIJIIIIIIJJJIIJIIIJIIJIJJIIJJIJJIIJJIJIIJIJJJ()
		{
		}

		internal void IJIIIJJJIIIIJIJIIIIIJIIIJIJIIJIJJJIJJIJJIJIIIII()
		{
		}

		internal void JIIJJJJIIJJJIJJJIJJIJIIJIIJJJJJIIJJJIIIIJJJJJJJ()
		{
		}

		internal void IIJJIJJJJJJJIJJIJJJJIIJJJIIIJIJIIJIIIJJJJJIJJII()
		{
		}

		internal void JIIJIJIJJIIJJJJIJJJJJIIIJJIIJIJJIIIIJJIJIJIJIIJ()
		{
		}

		internal void JJJJJJJJIJJJIIJIIJJIJIIJJIJIIIJIJIJIIIIJIIJIJJJ()
		{
		}

		internal void IIJJJJIJJIJIIJIIJIJIIIJJJIJJIJIIJJIIIJJJIIIIIIJ()
		{
		}

		internal void JJIIJIIJIIJIJIJJIJJIJIIJJIJIJJJJJIJJJJIIIJJIIJJ()
		{
		}

		internal void JJIJIIIJJIIJIIJJIIIJIJIIIIIIJIIIJJIJJIJJIIIIIII()
		{
		}

		internal void IJJJJJJIIIIIIJIJIIIJJIJIIIJJJJJJJJJIIIJJJJIIJII()
		{
		}

		internal void JIIIJIIIJJJIIJIJJJJJJIJJIIIIJJIIJJIIIJIJJJIIIJJ()
		{
		}

		internal void IIJIJJJJJIJIIJIIIIIJJJIJJIJJJIJJIJIIIJIJJJIJIIJ()
		{
		}

		internal void IIJJIJJJJJJIIIJIJIJJIJIIJIIIJJJJJJIIJJIIJJIIIIJ()
		{
		}

		internal void IIIJJJIJJJJIIJJJJIJIIIJJJJIIJJIIIJJJIIJIJIIJIJI()
		{
		}
	}

	public List<UIPanel> JIJIJIIJIIIIJIJIIIJIJIIIJIJJIJIIIJJIJIIJJIIIIIJ;

	public UIPanel IJJJIJIJJIJIIJIJJJIIJJJJIJIIJIIJIIIJIIJJIIJJIII;

	public UIPanel JJJIJIIIJJJJJIJJIIIIJJJIIIIIIIJJIIIJIIIIJIIIJII;

	public bool IJJIIJJJJIJIIIJIJJJJIJIJJJIIJIIJJIJJJIJIJJIIJII;

	public float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ;

	public static float IIIJJIJJJJJIIIJIJIIJJJJIJIIIIJIIIIJJIJIJJJJIIJJ;

	private UIPanel IJIJJIJIJJIIJJJIJIJJJIJJJJIJIJJJIJJJIIJJJJJIIII;

	private UIPanel IIIIIIIIJJIJJIIJJJJJIJIJJJJJJIIJIJJJIJIJJJIJJIJ;

	private bool IJJIIIJJJIJJJIJIJJIJIJJJJIIIIJIJJIJJIIJJJJJJIJJ;

	private static mPanelManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static UIPanel IJIIIJIIJJJIIIJJJIIJJJJJJIIJIJJJIJIIJJIJJJJIJII => IJIJJJJJIIJIJIJIIJJIJIIJJJIJIIJJJIJIJIIJIIJIIJJ();

	public static UIPanel IJJJJIIJIJIJJIIIIJJIIIJJJJIIIJIJIJIJJJJIIIIIJII => IIJJIIIJJJJJJJIJJIIJIJJJIIJIIIIIJJJJIJIIIIIJJII();

	public static bool JJIJIJJJIIJJJJIIIIJIJIIJIIJJJIIJIIIIJJIIIJJIIII
	{
		get
		{
			return JJIIIIIIIJIIIJIJIJJJIJIIIJJJJJJJIJJIJJJIJJIJJJI();
		}
		set
		{
			IJIJJIIIIIJJIJJJJIIIJJIJJIIIJJJJIIIJJIJJIIIIJIJ(value);
		}
	}

	public void IIIIIIJJIIIIIIIIJIJIJJJJIJJJJJIIJJIJJJJIIIIJJIJ(GameObject go)
	{
	}
	public static UIPanel JJIJJIJJJJIIJJJIJJIIJIIJJIJJJIJJIIJJIJJJIJJIIIJ()
	{
		return null;
	}

	public void JJJIJJJIIJJJIJIIJIJJIJIJIIIJIIJJJIJIJJIIIIIIIJJ(GameObject go)
	{
	}

	public void ShowAnim(GameObject go)
	{
	Show(go);
	}

	public void IIJIJJIIIJIJJIIJIJJIJJJIIIIJIJIIIIJJIJJIIIIJIJJ(GameObject go)
	{
	}

	public static bool JJIIIIIIIJIIIJIJIJJJIJIIIJJJJJJJIJJIJJJIJJIJJJI()
	{
		return false;
	}

	public void SetPlayerData(bool active)
	{
	}

	public void HideAnim(GameObject go)
	{
	if (go != null) go.SetActive(false);
	}

	public static void IIJJJIIJIJJIJJIJIJJIIIJJJIJIJIIIJIJIIIJIJJJJIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	public void IJIIIJIIJIIIIJJJIJJIIJJIIJIIJJJIJIIIJJJIIJJIJJJ(bool active)
	{
	}

	public static void JIJJIJIIIIIJJJJJIIIIIJJJIIJJIIJJIIIIJJJIIJJIIII(float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public void Show(GameObject panel)
	{
	if (panel == null) return;
	        foreach (UIPanel item in JIJIJIIJIIIIJIJIIIJIJIIIJIJJIJIIIJJIJIIJJIIIIIJ) if (item != null) item.gameObject.SetActive(item.gameObject == panel);
	        panel.SetActive(true);
	}

	public void JJJJJIJJIJJJIIJIIJIJIIIJJJIJJIJJIJIJIJIJIJJIIJI(bool active)
	{
	}

	public static UIPanel IJIJJJJJIIJIJIJIIJJIJIIJJJIJIIJJJIJIJIIJIIJIIJJ()
	{
		return null;
	}

	public void Show(string panel)
	{
	if (string.IsNullOrEmpty(panel)) return;
	        foreach (UIPanel item in JIJIJIIJIIIIJIJIIIJIJIIIJIJJIJIIIJJIJIIJJIIIIIJ) if (item != null) item.gameObject.SetActive(item.gameObject.name == panel);
	}
	public static bool JJIIIJJIIIIIIJJIIJIJJIIIIJIJIIJJJIJJJIIIIIIIJIJ()
	{
		return false;
	}

	public void ShowLast(string go)
	{
	}
	public static UIPanel IIJIJJIJJJIJIJIIIJIIIIIIJJIJIJJIJJIIJJJIIIIIJJJ()
	{
		return null;
	}

	public void ShowLast(GameObject go)
	{
	}

	public static void IIIJJIJIIIIJIJIJJIJJJJIIIJJIJIIIIJIJIIJIIIIIJII()
	{
	}

	public static UIPanel IIJJIIIJJJJJJJIJJIIJIJJJIIJIIIIIJJJJIJIIIIIJJII()
	{
		return null;
	}

	public void IJIIIJJIJIIIIJJJJJIIIJIIJIJJJJJJIIIIIIJJIIIIJJJ(bool active)
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, bool IJJJIJIJJIJIIJIJJJIIJJJJIJIIJIIJIIIJIIJJIIJJIII)
	{
	}

	public static void JIIIIIJJJIIJIIIIIIJJJJJIIIJJIJJIJJJIJJIIIJIIJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	public static void JIJJJJJJIJIJJIIJJJJJIJIIIJIJJJIJIIIJIJJJIIJIJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}
	public static UIPanel IJIIIIJJJIIIJJJIIIJIJJIIIIIJIJIIIJJJIIJIJJJJIIJ()
	{
		return null;
	}

	public void JIIJJJJJIIIIJJJJIIJIJIIIJIJJJJIIIIIIJIJIIJIJJJI(GameObject go)
	{
	}

	public static void IIJIJIJIJJJIIJJJIJIJJJIJJIIJJJIIIJIJJJIJJJJIJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void Awake()
	{
	JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ = this;
	        if (JIJIJIIJIIIIJIJIIIJIJIIIJIJJIJIIIJJIJIIJJIIIIIJ == null) JIJIJIIJIIIIJIJIIIJIJIIIJIJJIJIIIJJIJIIJJIIIIIJ = new List<UIPanel>();
	}

	public void JJIJJIJJIIIJIIJIJIJIIIJIIJIIJJIJJIIJIJJJIIIIJII(GameObject panel)
	{
	}

	public static void JIIJIIIIIJJIIIIIJIIJJJIJJJIIJJJIJJIJJJJIJIIJIJJ(float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public void JJIJIIJJJJIIJJIJJJIIJJJIIIIIIJIIIJJJIJIIJJJJJJI(string go)
	{
	}

	public static void IJIJJIIIIIJJIJJJJIIIJJIJJIIIJJJJIIIJJIJJIIIIJIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJIJIIJIJIJJIIIIJJIJIJIIJJJIJJJJJIIIJIJJIIJJJII(GameObject panel)
	{
	}
}
