using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mPlayerData : MonoBehaviour
{
	public UILabel IIIJJJJIJJIIJJIJIIIJJJJJIJIIIJJIIJIJIIJJJJJIJJI;

	public UILabel IJJJIIJIIIJIIIJJJJJIJJJIJIJIIIIJIJJJIIJIIJIJJJI;

	public UIProgressBar IIJIJIIIJJIJIIIIJIJJIIJIJJIJJJIJJIIIJIJJJIJIJJI;

	public UILabel JJJIIJIJIIIJJJJIIJIJIIJIJJIIIIJIIIIIJIIIJJJIJIJ;

	public UILabel JJIIJJJIJJIIIJJIIJIIJIJIIIIJJIIIJIIJJIJIJIIJJIJ;

	public UITexture JIIJIIJJJJIJJJIIJJIJJJIJIJJIJIJJJJIIIJIIIJIJIJJ;

	private void IJIJJIJJJIJJIIIJJIIIJJIJIJJJIIIJJJJJJJJIJJIIJJI()
	{
	}

	private void IIJIIJJJJIIIJIIIJIJJIIJIJIIIJIJIJJJJJJJIIIIIJJI()
	{
	}

	private void IJIIIIJJJIIIJJIIIIJJJIJJJIIJIJIJIJJJIIIJJIIIIJJ()
	{
	}

	private void IJJIJJIIIJJJJJJIIIIIJJJIIJJJIIJIJIIIJJIJJIIJJII()
	{
	}

	private void JIIIJJIJJIJJJJIJJJJIIJJIJJIJJJJIJJJIJJIJIJIIJJI()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void IJIJIJJIJJIJJIIIJIJIJJJIIIJIJJJIIJIJJJJIIJJIJJJ()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	private void IIIIJIIJIIIIIIIIJJIJIIJIIIIJIJIIIJIIJJIIIJJJIJJ()
	{
	}

	private void IIJIJJJJJIIJIIIIIIJJIJJJJIIIJIIJJIJIIIJIJJIJJIJ()
	{
	}

	private void Start()
	{
	}

	private void JIIIJIJIJIJIIJJIJIIJJJJJIJIIIIIJJIJJIJJIIJJIIJJ()
	{
	}

	private void JJJIJIIJIJIIIJJIJIIJIIJIIIJIIJIJIJIIIJIIIJIJJII()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void JIIIIIJJIIIIJIJIIIIIJJJJJJIJJIIJIJJJJJIIIIIJIIJ()
	{
	}

	private void JIJJJIIJJIIIIIJJJJJJJIJJIJIIJIIJJIIIIJIIJIJJJJJ()
	{
	}

	private void IJIIIJJIJIJJJJJJIJJJJIJIJJJIJJIIJIJJJJJIIIJJJJJ()
	{
	}

	private void IJJJIIJJJJJJIIJIIJIJIIJIJJIJJJIJJIIIIJIIJIIJIJI()
	{
	}

	private void IIJJIJJIIJIJJJIJIIIJJIJIIIJIIIJJIIIIJJJJJJIJJII()
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void IIJJIJIJJJJJIJJIIJIJIJJIIJIJIIJJIIIJJIIIJIIIJJI()
	{
	}

	private void JIJJJJJJIJIJJJJJJIIJIIJJJJIIJIIIIIJIJIIIIJIJJIJ()
	{
	}
}
