using UnityEngine;

public class mPlayerCamera : MonoBehaviour
{
	public GameObject IJJJJIJJIJIJIJJIIJJIIJJIJJJIJJIIJJIIJIJJJJJJIIJ;

	public MeshAtlas IJJJJJIJIIIJJIJJJJJIJJIIIIIJJIJJJJJJJJIIIJIIJII;

	public MeshAtlas[] IIIJIIIJIIJIJJJIIIIJJIIIJIIIIIIIIJJJJIJIIIIIIJI;

	public MeshAtlas[] IJJIIIJIIIJJJJIIIJIJJIJIIJIJJIJJIJJIJIIIJJJIJJI;

	public Transform IIJJJIIJJJIJJIIIIJIJIIJIJIJJIIIIIJJIIJIIIIJIIJJ;

	public float JIIIJIIJJJJJJIJIJIIIIIJJJIJIIJJJJIJJJIJIJJJJIIJ;

	private Camera IJJJIJJJJIIIIIIJJIJJJJJJIIIIJIIIJIIJIIJIJJIJIJJ;

	private static mPlayerCamera JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void IIJIIJJJIIJJJIIIJJIJIJJIIJJIIIJIJJJIJJIJIJJIJJI()
	{
	}

	public static void IJJIJIJIIJJIJIIJIJIIJJIJJIIJJIIJIJJJJIJIJIIJIJI(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ, string JIIJIIJJJJJIIIJIJJIIJIIIIIIJIJIIJJIIIJIIIIJIIJI, string JJJJIIJJJIJJIIIJIIIIJJJIIIJJJJIJJJJIIIJJIIJIJIJ, string JIJJJJIJJIJJJJIJIIIJJIIJIJJJJIIIJJIIJJIIIJJJIII)
	{
	}

	public static void JJIJIIJIJJIIIIJJIJJIIJJJIJIIIIJJJIJJJIIJIIJIJJI()
	{
	}

	public static void IIIJIIIIJIIIIIIIJJIIJJJIIIIJJIIJIIJIIJJIJJJJJIJ(Vector2 JIJIJJJJJIIIJIJJIJIIJJIIJJIJJIJJIJJJIJJJIJIIJJJ)
	{
	}

	public static void JJIIIJJJJIIIIJIJIJJJIIJJIJJIJJJJJJJIIIJIJIIJJJJ()
	{
	}

	public static void IJIIIJIIJIIJIJJIJIJJIJJJJIJIIIJJIIIIIJIJIIJJIJJ()
	{
	}

	public static void IJJJIIIJJJJJJIIJIIJIJJJJIIJJJIJIJJIJIIIIIIIIJJI()
	{
	}

	private void Awake()
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ()
	{
	}

	private void IJIJJJJJIJJIIJJJJJIJIJJIJJJJJJIJIIIIIIJJJJIIIIJ()
	{
	}

	public static void JJIIIIJJJJIJIJJJJIIIJJIJIJIJIIJJIJJJJIJIIIJIJJI()
	{
	}

	public static void IIIJIJIJJIJIJJIJJJJIJJIIJJIIJIIJIIJJJJIJJIJIIJI()
	{
	}

	private void JIIIIIJIJJIIIIIIIJJIIJJJJIIJJJJJJIIJIJJJJIIIIJJ()
	{
	}

	public static void IIJJIIJJIJIJIJIJIJJJIJJJJJJJJIIIJJIJJJIJJJIJIJJ()
	{
	}

	public static void JJIIJIJJJJIIJIJJJJJIIIJIIJIJIJJIJIIIIIIJJJJIIIJ()
	{
	}

	public static void JJIJIIJIIJIJJJJJIJJIJJIJIJJIJIJIIIIJJJIJIIIJIII()
	{
	}

	public static void IJJJJJJIJIJJIIIJJIIIIJJIJJIJIJIJJJJIJIJIIJIIJJJ()
	{
	}

	public static void JIJIIJJIIIIJIJJJIJJJIIIIIJIIJIIJIJIIIIIJJJIIJII()
	{
	}

	public static void JJIIJIJIJIJJJIIJJIJIIIIJJJJJJIIJJJJJJJIJJIIJIIJ()
	{
	}

	private void IJJJJJJIJJIIIIJIJIJJJIIIJJIIIIJJIJIIJIIIIJJJJIJ()
	{
	}
}
