using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mPlayerStats : MonoBehaviour
{
	public UITexture IJIIJJJJIJIIJIIJJJIIJJIIJIJIIJJIIIIIIIJIJJIIJII;

	public UILabel IJIJIIJIJIJIJIJJIJIJJIJIIJJIIJIIIJIIIJJJIJJJIJI;

	public UILabel IIIIIJIJJIJIJIJIIIJJJIJIJIIJJJJJJJIIJIJJJIJJJII;

	public UILabel JIIIIJIJIIIJIJIJJJJIIJJIJJJIJIIJJIIIIJJIJIJJIII;

	public UILabel JIJIIJJJJIIJIIIJIJJJIIJIJIJIJJJIJJJJIJIJIJJJJII;

	public UILabel IJJIIIJIIIJIIJJJJIIIIJJJIIJJIIJJJJIIJJJIIJJJIJJ;

	public UILabel IJJIJIJJJIJIIIIJIIIIIJJJJIIIIIIJIIIIJIIIIIJIJJI;

	public UILabel IJIJJJJIIJJJJJIJIJIJIJJIJJIJIIJJIJJJJIJIJIIJJIJ;

	public UILabel JIIIIIJJJJJIIIIIJIIJJJJJJJIJIJIIJJJJIIIJIJJJIJI;

	public UILabel JJJIIJIJIIIJJJJIIJIJIIJIJJIIIIJIIIIIJIIIJJJIJIJ;

	public UILabel JJIIJJJIJJIIIJJIIJIIJIJIIIIJJIIIJIIJJIJIJIIJJIJ;

	public GameObject JJJJIJJJJJIJIJJJJIIIIIIJJIIJIIIJIIIIIJJIIJJJJJI;

	public void IJJJIJIJJIJJJIJJJJIIIIJIJJIIIIJIIIIJIIJJIJIJJJI()
	{
	}

	private int IIIJIJIJJJIIJJJJIIJIIIJIIIIIIIJIIIJIIJJIIJIIJIJ(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return 0;
	}

	private int JJJIJJIJIIJIJIIIJIJIIIJIJIJIJIJIIJJJIIIIJJIJJJI(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return 0;
	}

	private int IJIJIJJIJIIIJIJIJJJIJIIJIIJJIIJIIIIJIIIIIJIIJIJ(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return 0;
	}

	private string JIIIIIJJIIJJIIJJJIJIJIJJJJJJJIIIIJJJJJIJIJIJIIJ(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}

	public void IJJIJIJJIJIJIJIIIIIIIJJJJIJJJJJJIIIIJIJIJIJIIJI()
	{
	}

	public void IJJJIIIIIIJIJJIJIJIIIIIIJIIIJIIJJJIJJJJJJJJJIJI()
	{
	}

	public void JIJJIJIJJJIJJJIIJJJIJJIIJJJJJJIJJJIJJJJIJIIIIJJ()
	{
	}

	private int JIIIIIIIIIJIJJIIJIJJIJIIJIIIJJJIIIJIJJJJIJIJJIJ(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return 0;
	}

	private int JIIJJJIIIIJJIJIJIIJIJIIJJIJIIIIIJJIIJIJIJJJIJJI(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return 0;
	}

	private string IIJIJJJIJIJIIIIIIIJJJJJIIIIIIJIIIJIIJJJJIIJIJII(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}

	private int JJIIIJIJIIIIIIIIIIIIIJIIJJIJIJIJJIJIIJIIIJIIJIJ(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return 0;
	}

	public void Open()
	{
	}

	private int IJJJIJIIIIJIIJIIIJJJIIJJJJIIIIJJIJJJIJJIIIIIJJI(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return 0;
	}

	private string IIJJJIJIJJJJIJIIJJJIJIIIIIIJJIIJJJIIJIIIJJJJIIJ(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}

	public void IIIIIJIJIJJIIIJIIIJJJJIJJIIIIJIJJJIJJIIIIJJJIJI()
	{
	}

	private int JJIIJIIJIJJIJJJJIJIIIIIJJIIIIIIJIJIJIIIIIJIJIJJ(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return 0;
	}

	private string JIIIJJJJJIJIJIIIJJJIJIJIJIJIJIJIIIIJJJJJIIJIIII(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}

	private int IIJIJIJJIIIJJIJIJIIJJJIJJIJIJJJJJIIIJIJJIJIIIJI(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return 0;
	}

	private int JJJIJJIJJJJJJJIIIIJIJJJJIIJJJJIJIIIJIIJIJIJIJJJ(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return 0;
	}

	private string IIJJJJIJIIIIIJJIJIIJJJJIJJIIJJIJJJJJJJJIJIJIJJI(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}

	public void JJIIJIJJIJIJJJJIIJIIIJIJIJIJJIJIIIIJJJIJIJIIJJJ()
	{
	}

	private string JJJJIJJJIJJJIIIIIJJJIJJIJJJJJJIIJJJJIIIIJIIJJII(long JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
		return null;
	}
}
