using System;
using UnityEngine;

public class mPopUp : MonoBehaviour
{
	private sealed class JJJJIJIJJIIIIIJJIJIIIIIJIIIIIIJJJIJJJIIJJIJJIIJ
	{
		public string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ;

		internal void IIJJIIJJJIJIJIIJIIIJJJIIIIJIIJIJIJJJIIJJIIJIJJJ()
		{
		}

		internal void IIIJJIIJIIJJJIJIIJJJIIIIIJJIJIJIJJJJJJJIJJJIIJJ()
		{
		}

		internal void JJIIIIJJJIIIJJIIJJIIIJIIIJJIIJIJJJIJIIJIIJIIJII()
		{
		}

		internal void IIJJJIJIIIIJJJJIIJIJIIIIIIJJJJIIIIJIJJJJIIJJJJJ()
		{
		}

		internal void IIIIJIIIIIJJJJIJJIIIJIJJIJIIIJJIIJJJIIIIJIJJJIJ()
		{
		}

		internal void IIIIIJIJJIJJJJIIIJIJIJIJJJIJJIJIIIIJIJJIIIIIJII()
		{
		}

		internal void IJJIIJJJIIJIJJJJJJIJIJIJJIIJIIJIJJJJIJIJJJJIJII()
		{
		}

		internal void IJIIIJJIJJJIJIJJJIIIJJJIIJJJJJJIJIIIIJIIJJIIIJJ()
		{
		}

		internal void JIIIIIIJIJIIJIJIJJIIJJJJIIIIJIJIIJJJIJJIIIJJJII()
		{
		}

		internal void JJIJJJJIIJIJIIIIJJIJJIIJIJJJJIJIIIJIIJJIIIJJIJI()
		{
		}

		internal void IIIIJJIIJJIIIJJIJIIIJIIJIJJIJJJJIIIJJIIJJIIIIIJ()
		{
		}
	}

	public UIPanel JIJIJIJJIJIJJJJIIIJJIIJJJJJIIJJIJIIJJIIIIIIJIJI;

	public UILabel JIJIJIJJIJJJIJIJIIIIJJJIJJJIJJIJJIJIIIJIIIJJIJJ;

	public UILabel IIIJJJJIJIIIIJJIIIIJIIJIJIIJJIIIIIIJJIJJIIJIJIJ;

	public UILabel IIIIIJIJIIJJJIIIIIIIJIJJIJIIIIIIJJIIJIJJIJIIJII;

	public UILabel IIIIIJJJJIIJJJIIJIIIIJJIJIJIIIJJIJJJJIJIIIJJIIJ;

	public static bool JJJJJJJJIIJIIJIJIIIJJJJIIJJJJJJJIJJIIJJJJIJJJII;

	public UIPanel IIIIIJJJIJIIJIJIJIIIJJJIIIJIJIIJJIJIIJJJJIJIIII;

	public UILabel IIIIJIJJIJJJJJJJIIIJIIIIIJJIIIJIJJIJIJIIJIIIIIJ;

	public static bool JJIJIIJIJIJJJJIJIIJJJIJIJIIIIJIIIJIJIJIJIIJIIII;

	public UIPanel JIIIIJJIIIJIIIJIJIJJJJJIJIIJIJIIIIIJIJIIJIJJJJJ;

	public UILabel JJJIIIIJJJJIJJIIIJJIIJIJJJJIIIJJIJJIJJIJIIJJJJI;

	public UILabel JJJIIJIIIIIJIIIJJIIIJJIIJIJIJIIIJIJJJIIIJIJJJII;

	public UIInput JJJIIJJJJIIJIJIJJJJIIJJIIJIJIIJJJJIJJJJJIIJIJIJ;

	public UILabel IJIJJIIJJIJJIJIJIJIJJIIIJJIIIIJIJJIJIIIIJIJJIIJ;

	public UILabel JJIIJIIIJJIIIJJIJJIIIJJJJIIJIIIIJJJIIIJJJIIJIII;

	private Action IIIJIIJJJIIIIIJJJIJJIJJJJIIJJIJJJIIJJIJIJJIIIJI;

	private Action IJJIJIIIJIJIJIIJJJIJIJIJJJIIIJIIIIIJJIJIIIJIJIJ;

	public static bool JIJIJIJJIJJJJJJIIIJIIIIJJIJIIIIJJIIIJIIIIJJJJIJ;

	public GameObject JJJIJJIJIIIJJJJIIIJIIJJJIJJIJJIIIIIJIIJJJIJJIJJ;

	public UILabel IJJIJJIIIJJJJJIIIIIIJJIJIIIIIJIIJIIIIJIIJJIIIII;

	private Action IIJIJJJIIJIIJJIJJIIJIJIIJIIIIIJJJIJIIIIIJIIJIII;

	private Action IIIIJIJJJIJIIIJJJIIIJIJJIIIIIJIJJJIIIJJIJIJJIJI;

	private static mPopUp JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void IJJJIJJJJJIIIIIJJJIIIJJIJJIIIJJIIIJJIJJIIJIJIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void JJIJIJJIJIJIJJIIJIIJIIIIIJIIJJJJIIJIJJJIIJJJJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, int JJIJJJJJIIIJJJIIIJIIIIIIJIIIJJJJJJJJIJJJJJIJIIJ, UIInput.IIJJIIJIJJIJJIJJJIJIIJIIJIIIIIIJIJIIJIJJIIIJJIJ IJJIJIIJIJJJJIJJIIIJIIIJJJIJJIJIIJJIIJIIIIIJJII, Action IIJJJJIJIJJJJIIJIIJJJIIJIJJIJIJJJIIJIIIJIJIJJII, Action JIJJJJIIIJJIJJIIJIIJJJIIIJIIJIJIJJIJJIJIIJIIIII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	public static void JIIIJIIJIIJJJIIIIJIIJJIJIJIJIIIIJIJIJIIJJJIIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void Awake()
	{
	}

	private static void IJJIIJJIJJIIJJIIIJJJJIIIIJIIJIIIJIJJJIIIJJJJIJI()
	{
	}

	public static void IJJJIIJJJJIJIJIJJJIJIJJIIIIIJJJIIIJJIIJJJIIIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	public void JJIIJIJIJIIJIJIJJIIIIIIJIJJJJIIIIJJIIJIIJJIJJJJ()
	{
	}

	public static void JIIIJIJJJJIJIIJIJIJJIJIIIIIIIIIIIIJJJJIJIIJIIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public static string JJIJJIJJJIIJIIIJIIJIJIIJJJIJJIIIIIJJIIJJIJJIJII()
	{
		return null;
	}

	public static string IJJJJJJJIIIJIJIJJJIJIIJJIIJJJJJIIJIIIIJIJIIIIII()
	{
		return null;
	}

	public static void JJJIJJIJIJJIIJIJIJJIJJIIJIJIJJIJJJJIIJJIIJJJIIJ(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ, bool IJJJIJIJJIJIIJIJJJIIJJJJIJIIJIIJIIIJIIJJIIJJIII)
	{
	}

	public void OnInputSubmit()
	{
	}

	public static string JJIIJIIJIJJIJIJJIIIIIIJIIIIIIJJJJIJJJJIIIJJJJII()
	{
		return null;
	}

	public static void IJIJIJJJJJJIJJJJJIIIJIIIJIJJJJIJJIJJIJJIJJJJIJJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI, string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public void JIJIJIJIIIIJJJJJJIJIJJJIIJJJIIIJJIIJJIJIIIJIIIJ(int button)
	{
	}

	public static void JIIJJJJJJIIIIIJIJIIJJJIIJIJJJIJJIIIIJIJIJIJIIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
	}

	private static void IIIJJIJIIIIJIJIJJIJJJJIIIJJIJIIIIJIJIIJIIIIIJII()
	{
	}

	public static void IJJJJJIIIJIIIIJJIJIIIIIIIJIIJJIIJJJIIIIIIIIJIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public void OnClickButton(int button)
	{
	}

	public static void JJJIJJIJIJJIIJIJIJJIJJIIJIJIJJIJJJJIIJJIIJJJIIJ()
	{
	}

	public static void IJJJIIJJJJIJIJIJJJIJIJJIIIIIJJJIIIJJIIJJJIIIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IJJIJIJJIIJJJIJJJJIJJIIJJJIJIJJIJIIIIJJIIIJIJJI, Action JJJJIIIJIIJIJJJJJJJIJJIIJIIJIJIJJIJIJIJJIIIJJIJ)
	{
	}

	public static void JJJIJJIJIJIJIIIIIIJIIJIIIJJIIJIIIJIJIIIJJIJIJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, int JJIJJJJJIIIJJJIIIJIIIIIIJIIIJJJJJJJJIJJJJJIJIIJ, UIInput.IIJJIIJIJJIJJIJJJIJIIJIIJIIIIIIJIJIIJIJJIIIJJIJ IJJIJIIJIJJJJIJJIIIJIIIJJJIJJIJIIJJIIJIIIIIJJII, Action IIJJJJIJIJJJJIIJIIJJJIIJIJJIJIJJJIIJIIIJIJIJJII, Action JIJJJJIIIJJIJJIIJIIJJJIIIJIIJIJIJJIJJIJIIJIIIII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	public static void JJJJJJIIJJIIJJJJIIIIJJIIJIIJIIIJIJJIIJIJJIJIIJI(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI, string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void JJJJJIIIIIIJIJJJIJIJJIJIJIIJIJIJIJIJIIIJIIIJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void IJIJIJJJJJJIJJJJJIIIJIIIJIJJJJIJJIJJIJJIJJJJIJJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public static void IIIJIJJIIJJIJJJJIIIJJIIIJIJIIIJIJIIJJJJJJJIIIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public static void IJJJJJIIJIJJIIJJJIIJJJIJJIJIIJJJIJJJJIIIJIJIJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, int JJIJJJJJIIIJJJIIIJIIIIIIJIIIJJJJJJJJIJJJJJIJIIJ, UIInput.IIJJIIJIJJIJJIJJJIJIIJIIJIIIIIIJIJIIJIJJIIIJJIJ IJJIJIIJIJJJJIJJIIIJIIIJJJIJJIJIIJJIIJIIIIIJJII, Action IIJJJJIJIJJJJIIJIIJJJIIJIJJIJIJJJIIJIIIJIJIJJII, Action JIJJJJIIIJJIJJIIJIIJJJIIIJIIJIJIJJIJJIJIIJIIIII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	public static void IJJIJJIIIIIJIIIIJIIJIIIIIJIIJIIIIIJIJJJIIIJIJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IJJIJIJJIIJJJIJJJJIJJIIJJJIJIJJIJIIIIJJIIIJIJJI, Action JJJJIIIJIIJIJJJJJJJIJJIIJIIJIJIJJIJIJIJJIIIJJIJ)
	{
	}

	public static void JJIJJIJJJIJJIJJIIIIIIJJJJJJIIJJJJIJIIJJJJIJJJJJ(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
	}

	public static void IJJIJJIJIIIIIJJJJIJIJJIJIJIJJIIIJIIIIJIIJIIIJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	public static void JIIIJIJJJJIJIIJIJIJJIJIIIIIIIIIIIIJJJJIJIIJIIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI, string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static string IIJJIJIIJJJJJIIIIIIIJJIJIIJIIIIIIJIJJJIJIJJJIII()
	{
		return null;
	}

	public static void JIIJJJJJJIIIIIJIJIIJJJIIJIJJJIJJIIIIJIJIJIJIIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void IJJJIIIJJIIJJIJJJIJJJIIIIJJIJJJIJJIJJJJIJJJJIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IJJIJIJJIIJJJIJJJJIJJIIJJJIJIJJIJIIIIJJIIIJIJJI, Action JJJJIIIJIIJIJJJJJJJIJJIIJIIJIJIJJIJIJIJJIIIJJIJ)
	{
	}

	public void OnInputChange()
	{
	}

	public static void JJJJIJJIIIJIJIIIJIIIIJIIIJIJIJJJJIIIJIIJJJJIJIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void JJJIJJIJIJJIIJIJIJJIJJIIJIJIJJIJJJJIIJJIIJJJIIJ(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
	}
}
