using System.Runtime.CompilerServices;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mQuickPlay : MonoBehaviour
{
	public GameMode JIJJJIJJIJIIJIIIIJIIJIIJIJJIJIIIJJJJJJIIIJJIJIJ;

	public UIPopupList JJIJJJJIJIJJJIJIJJJIIIIJIIIJIIIIJIJIIJIIJIIJIII;

	public UIPopupList IIJJJJJJJIJIIJJJIIIIJIJJIJJJIJJJIJIJIJJIIJJJJJI;

	public UILabel[] IIJIJJIIJJIIJJIIJJJJJJJIIJJJJIJJIIJJJIIJIIJIJIJ;

	public UISprite[] IJJIJIJJIJIJJJJIIJIJJIJIJIIJIJJIIIJIIJIIJJJJIIJ;

	public UIGrid IIIIIIJIJJJIIIIIIIIIJIJIIIIIJIIIJIJJJJIIJJJJIJI;

	private int JJIJIJJJIIJJIJJJJIJJIIIJIJJJJIJJJJJJJJJIJIIJJJJ;

	private JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ JIIJJIIIIIIJJJJJJJIJJJIIIIJIJJIJIIIIJIJIIJIJIJI;

	private bool IJJIJJJJJIIIIIJJJJIJIJJIJJJJIJIJJJJJJIJJIIIJIJI;

	public void SelectGameMode()
	{
	}

	private void IJIJIJJJIIIJIJIJJJIIIJIIJIJJIJIJIIIJIJIJIIIJIIJ(string JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI, string JJJIJIJJIIJJIIIJIJJIIJJIIJIIJJIJJIJJJIIIIIIJIJI, int JJIJIJJJIIJJIJJJJIJJIIIJIJJJJIJJJJJJJJJIJIIJJJJ)
	{
	}

	private void JIIIJJIIJJJIJJJIJIJIIJJJJJIJIIJIJIJJJIIJIJIJIII()
	{
	}

	public void JIJJJIIJJJIJIIJJIIJJJJIJIJIIIIIJIIIIJJIIJJIJJII()
	{
	}

	private void IJIIJJJJJIJJJJJIJJIJJJIIIIIJIJJIIIIJJIJIJJIJIIJ()
	{
	}

	public static int IIIJIJIJIJIJIJJIJIJIJJJJJJIIJJIJJIJJIIIIJJJIIII(JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	public void JIIIJJIIIJIIIJIIIIIIJIJJJJJJJIIJIIJIIIJJJIIJIJJ(int[] list)
	{
	}

	public void JIJIIJJJJIIJIIIJIIIIIJIJIIIJIIJIIIJJIIIJJJJJJIJ()
	{
	}

	public void SetMaxPlayer(GameObject go)
	{
	}

	public void IIIIJJJJIIIIJIJJJJJJJIJJJJIJIJIIIJIJIIIJJJIIJJI()
	{
	}

	public void QuickPlay()
	{
	}

	public static int IIJJIJIIJIJJIIJJIJIJIJJJJIIJJIIJJJJIIIJJIJJIJIJ(JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	public void IIIIIJIJIJJIIIJIIIJJJJIJJIIIIJIJJJIJJIIIIJJJIJI()
	{
	}

	public void JJIJJIJJIIIIJJIJIIJJIIJIJJJJJIJIIJIJIJIJIJIIJIJ()
	{
	}

	public void JIJIIJIIJIJJJJJIIIJJJJJIIJJIJJIIIIJIIIJIJIJIJJJ()
	{
	}

	private void JIIJJIJIIJIJJIJIJJIIJIJIJJJJIJIIJIJJJIIIIIJIJJJ(string JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI, string JJJIJIJJIIJJIIIJIJJIIJJIIJIIJJIJJIJJJIIIIIIJIJI, int JJIJIJJJIIJJIJJJJIJJIIIJIJJJJIJJJJJJJJJIJIIJJJJ)
	{
	}

	public void SelectMap()
	{
	}

	public void JIJIIJIIJJJJJIJIIJIIIIJJJIJJJJIIJIIJJIIJJJJJJII()
	{
	}

	public void JJJJJIJIIJJJIJIIIIIIIIJIIJJIIIJIIJIIJIIIJIIJIII()
	{
	}

	private void IIIIIIJIJJJIIIJJIIJIJIJJIJJIIJJIIIJJJIJJJJJIIJJ()
	{
	}

	public void Open()
	{
	}

	public void SetMaxPlayers(int[] list)
	{
	}

	private void JIIIJIIJIIJIJJJIIJIJIIIJIJIJJIIJJIIJIIIJIIJJIII()
	{
	}

	private void IJIIIIJIIJIIJIJJJIJIJIJIJIJIJIIIIJIIIIJJIJJIJJJ()
	{
	}

	public void IIJIJIJJJIJJJJJJJIJJJIJIIIIJJJIIIIIJJJJJJIIJJII()
	{
	}

	public void SetDefaultMaxPlayers()
	{
	}

	private void JJIIJJIJIJJJIIIJIJIJIJIJJIIJJJJJIIJIIJJJIIIIJIJ()
	{
	}

	[CompilerGenerated]
	private void JJJIJIJIIJIJJIJIJJJIIJJIIIIJJJJIJJIIIJJIIJIJIJI()
	{
	}

	public void IJJJIIJJJIIJJJJJIJJJJIJJJIIJJIJJJJJJJIJJIJJIIJI(GameObject go)
	{
	}

	private void IIIIIIIJJIIJIIIIIIIJIIJIIJIJIIIJJIJIIIJIIJIIIIJ()
	{
	}

	public void JIIJIJIIIIIJJJJJIJIJIIIJJIIJJJJJJJIJIIJIJIJJJJI(GameObject go)
	{
	}

	public void JIJJIJIIIIJIIIJJIIJIJJJIIIJJJJIJIIJIJJIJJIJIJJJ()
	{
	}
}
