using System.Collections.Generic;
using UnityEngine;

public class mSelectMode : MonoBehaviour
{
	public GameObject IIJIIIJIJJIIJJJIJJJIIIIJJIJIIIIJJIIIIIJIJJJJJJJ;

	public GameObject JJIJIIIIJJIIIIIJIJIIJJIJJJJJIJIJIIIIJIJIJIJIIJI;

	public UIScrollView JJJIIIIIJJJJIIJIJJIJJIJIJJIIIJIIIJIJJIIJJJIIIJI;

	public UIGrid JIIIIIIJJIIIJJJJIIIIIIIIJJJJIJJJIJIIIIJJIIJIIII;

	public GameObject IJJIIIIIJJIIJJIIIIJJJIIJJJJJJJIJIJIIJJIJJIJJIJI;

	public mSelectModeElement IJJJIJIJJJIJIJIJJIJJIIIJJJIIJJIJIJJJIJJIIIJIJJJ;

	public UIScrollView JIIJIIIJJIIIJJIIJJJIIIJIIIIIIIJJIJIIIIJJIJJJJJI;

	public UIGrid IJIIIJJJIIJIJIIJIIIIJIJIIJJJIIJJIJIIIJJIJIIJJJI;

	private List<mSelectModeElement> IIIIJJIIJIJJJJIJJJIIJIIIIJIIIJJIJJIJJJJJJJJIJJJ;

	private List<mSelectModeElement> IJIJJJJIIIIJJJIJJJIJIIIIJJIIIJIIIJJIIIIIIJIIJII;

	private GameMode JIJJJIJJIJIIJIIIIJIIJIIJIJJIJIIIJJJJJJIIIJJIJIJ;

	private List<mSelectModeElement> IIIJJIIIJIIIJIJJJIJJIIIIJJJIIIIJIJIIIJJIJJIJIJI;

	private bool JIJJJJIIJJJIJIJJIJIJIJJIJIIIJJIJIIIIIJJIJIJIIJI;

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	public void Open()
	{
	}

	public void IJJIJJIJJIIJIJJIIIIIJJIJJJJIJJJIJIIJIJIIIIIJIJJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
	}

	public void JJIJIJIJJJJJIJJJIIIJJJJIJIIJIIIIIIJIJIJIIJIIJII()
	{
	}

	public void JJIJJJJJIIIJIJIJJIIIJIIIJJIJJIIIIIJJJIJJJIIJIII(mSelectModeElement element)
	{
	}

	public void Play()
	{
	}

	public void JIIJIIJJJIIJIJJJIIIJIJJIJIIJIIJJIIJIJJIIJIIJJJI()
	{
	}

	public void JJJJJJIIJIIIIIJJIJJIJJIJIIJJJIJJIJJIJJJIJIJJIJI(UILocalize localize)
	{
	}

	public void JJJIIIIJJJJIJJJJIIIIJJIJJJJIIJJJJJIIJIIIJIJIJJJ()
	{
	}

	private mSelectModeElement IJJIJJJJJIIJJIIIJIJIJIIIJIJIJJIIJIIJJIJJJJJIIII()
	{
		return null;
	}

	public void IJJJJIIJJJIJJJJIJIIJJIIJJJIJJIJJJJIIIJIJIIJJJIJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
	}

	public void IJIJIJIJIIJJJIJIIJIJJJJJJIIJJIIIIIIJJJIJIIJJIJJ()
	{
	}

	public void SelectMap(mSelectModeElement element)
	{
	}

	public void SelectMode(UILocalize localize)
	{
	}

	public void IJJJIJJIJIIJJIIIJIIIJJJJJIJIIJJJIJJJIIIJIIIJIII()
	{
	}

	public void IIJIJIJJIIIIIIIIIIJJJIJJIIJIJIJJIJJIJJIIJJIJIJJ(UILocalize localize)
	{
	}

	public void JJIJJJJJJIIJIJJIIIJIJJJIIIJJJJJJIJIIJIJJIIIIIIJ(mSelectModeElement element)
	{
	}

	public void JIJIJIIJIJJJIJIJIJJJJIJJJIIIIJJIJJIIIIIIJJJJJJJ()
	{
	}

	private mSelectModeElement JJIJJJIJJJIJIIJIIJIJIIJIJIJJJJIIJIJIJIJIJJIIIJI()
	{
		return null;
	}

	public void JIJJJIIIJJJJIJJJIJJJJJIIIIJIIJJIJIIJJIJIIJIIIJJ()
	{
	}

	private void Start()
	{
	}
}
