using System.Collections.Generic;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mServerInfo : MonoBehaviour
{
	public UILabel JJIIIJIJJJIIIIJJIIIIJIJIIIIIIIJJIIIJJJJIIJJJIJI;

	public UILabel IJIIJIIIJIIIIIJIIIJIIJJIIIIJIIJIJIJJJJJJIIIJIJI;

	public UILabel JIIJJJJJJJJJJJIIJIIIJJJJIIJIIJIIIJIJJJIJJJIIJJI;

	public GameObject IJJJIJIJJIJIIJJJIJJJJJIJJIIIJJJJIJJJIIIIIJIJJIJ;

	public UISprite JJJJIJIJIIIJIJJIIIJIIJIIJJJIIJJJIIIJJIIIJIIJIII;

	public UITexture JJIJJJJIIJJJIJJIIIIIIIIIIJJJJJJIJIIJJIJIJIJJJII;

	private static Dictionary<string, Texture> JJJIIJIIJJJIJIIJIIIJJIJIJIIJIJJJJJIIJIIIIIJJJIJ;

	private static string JJIJJIJIIJJIIJJIJIJJJIIIJIIIIJJJIIIJJIIIIIJJJIJ;

	private JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ JJJJIJIIIJJIJIIJJJIJIIIIJIJJIIIJIJIJJIIIJIJJIJJ;

	private void JIIIIJIJIIJIJJJIJJIIJIIJIJIIJIIJJIJJJIJIIJIJJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void IIIIIIIIIJIJJJIJJIIJIJJJIJIJJJIIIJIJJIJIIIIJJJI(string JJJIJIJJIIJJIIIJIJJIIJJIIJIIJJIJJIJJJIIIIIIJIJI)
	{
	}

	private void OnEnable()
	{
	}

	private void IIJJJIJJJJJJIJIJIIIJIIIJIJJIIJIJIIJIJIIIIIIJIII(string JJJIJIJJIIJJIIIJIJJIIJJIIJIIJJIJJIJJJIIIIIIJIJI)
	{
	}

	private void OnClick(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	public void IJIJJJJIJIIIIIIIJIIIIJJIJJJIIIJJIJJJIIJJIIJJJII(JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI)
	{
	}

	public void IJIIJJJIIJJIJJIIIJIIJJIJIIIIJJJIIJJJIJJIJIJIJIJ(JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI)
	{
	}

	private void JJJIIIIJIJIJIJIIJJJJJJIJIIIIJJIIJIJJIIIIJJJIIII()
	{
	}

	private void OnDisable()
	{
	}

	public void IJJIIJIIIIJJIIIIIJIJIJJIJJJIIJIIIIIIIJIIIJJJIJJ(JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI)
	{
	}

	private void JIJJJJJJJJJIJJJIIJJIIJIIIIJIJJIJIIIIJJIJIIJIIJI(string JJJIJIJJIIJJIIIJIJJIIJJIIJIIJJIJJIJJJIIIIIIJIJI)
	{
	}

	public void JIJIIJJIIIIIJIJIIJIJJJIIJIJIIIIIJJJIIIIJIJIIIJJ(JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI)
	{
	}

	private void JJIIIJIJJJJJJJJIJIIIJIIJIIJIJIJJIIJIIIIJJJJIIJJ()
	{
	}

	private void IIJJIJJIJIIIJJIIJIIIJIIIIIJIJIIIIIJIIJIJJJJJIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void JIIIIJJIJJIIJIJJIJJJJJIJJJJJJJIJJJIJJIJJIIIJIIJ(string JJJIJIJJIIJJIIIJIJJIIJJIIJIIJJIJJIJJJIIIIIIJIJI)
	{
	}

	public void IIJIIJIIIJJIIJJIIJJJIIJIJIIJIJIJJJJIJIJIJIJJJIJ(JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI)
	{
	}
}
