using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mServerSettings : MonoBehaviour
{
	public GameObject JJJJIIJJJJJJJIIIJIIIIIJJJJIJIIIIJIIIJJJJIJJJIII;

	public GameObject IJIJJJIJIJIIIIJJJIIJIIJIIIIJJIIJIIIJJJIJIJIIJJJ;

	public UIPopupList IIIJJJJJJJIJJJIJJIIJIIIIIIJJJJJJIJIJIJJIIJIIIJJ;

	private static mServerSettings JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void Start()
	{
	}

	private void IJJIJJJIJIJIJIIIJIJJIJJJJIJJIJJIIIJIIJJIIIIIJJI()
	{
	}

	public void Close()
	{
	}

	public void JIIJJIIJIIJJJIIJIJJJIIJJIIIIIIJIJJJIJIIJJIJJJIJ()
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	public void JJIIIIJJJJIJIJJJJIIIJJIJIJIJIIJJIJJJJIJIIIJIJJI()
	{
	}

	public void Open()
	{
	}

	public static int IJIJIIJJIJJJIIIJJIIJIIIIIJIJJJIJIIJJIIIIIJJJIII()
	{
		return 0;
	}

	public static int JIIJJJIJIIIIIIIIJIIJIIJIJJIJIIIJIJIJIJIIIJIJJJI()
	{
		return 0;
	}

	public static void IIJJIIJJIJJJIJJIIJJIIIJJJJIIIIIJJJJIJIIJIJJIIJJ(GameMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI, string JJJIJIJJIIJJIIIJIJJIIJJIIJIIJJIJJIJJJIIIIIIJIJI)
	{
	}

	private void IIJJJJIIIJIJJJIIIIJIJJIJIIJJJJIIJJJIIIIJJJJIJJJ()
	{
	}

	public static int JIJIIJIIIIJJIIJIJJIIIJJIIJIJIIJIJJIJIIJIIJJJIJJ()
	{
		return 0;
	}

	public void JIJIIJJIIIIJIJJJIJJJIIIIIJIIJIIJIJIIIIIJJJIIJII()
	{
	}

	public void JJIJIJIJJJJJIJJJIIIJJJJIJIIJIIIIIIJIJIJIIJIIJII()
	{
	}

	public void IJJJIIIIIIJIJJIJIJIIIIIIJIIIJIIJJJIJJJJJJJJJIJI()
	{
	}

	private void JIJIJIJIIIIJJIJJIJIIJIIJIIIJIIIJIJIJJIIIJIIIIII()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}
}
