using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mServerList : MonoBehaviour
{
	private sealed class IJJJJJJIIIJJJIJJIIIIIJIJIJJJJJIJIJIJIJJJJIIJJIJ : IEnumerator<object>, IEnumerator, IDisposable
	{
		private int IJJJJJJJJIIJIIIIIJIIJJJIJJIIJIJJJJJIJJJJJIIIIII;

		private object IJJJJJIIIJJIIIIIIJIIIJIJJJIJIJIIJJIJIIIJJIIIJIJ;

		public mServerList JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public bool JJJIJIIJJIJIIJIIJJJIIJJIIIJIJIIIJJIIJJIIIJIIJIJ;

		private JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ[] JJIJJIIIIIJJJIJIJIIJJIIJIIIJIIJJJIJIIJJJIJJJIII;

		private int IJJIJJJIJIIIIJJIIJIJJJJJJJJJIJJIIJIJIJJIJJJJJIJ;

		private int JIJIJIIJJJIIJIIIJIJIJIIJIIIJJJJJIJIJJIIIIIJJJJI;

		private int JIIJIJIJJJIIIIJIJIIIIJJIIIJIJJIJIIJIIJIIIIIJJIJ;

		private int IJIJIIIIJIIJIIIJJIJIJJJJJIJIJIIIIIJJJJJJIJIIIJI;

		object IEnumerator<object>.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		object IEnumerator.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		private bool MoveNext()
		{
			return false;
		}

		bool IEnumerator.MoveNext()
		{
			//ILSpy generated this explicit interface implementation from .override directive in MoveNext
			return this.MoveNext();
		}

		private void IJIIJJIIJIJJJIIIIIIIIJIJJJJJJJJJJIJJIIJJJJJJJII()
		{
		}
		private object IJIIIJIIIIIJJJIJIIIIJIJJIIJJJJJJJIJJJIIJIIIIJII()
		{
			return null;
		}

		private void IIJIIJJJJJIJIJJIIIIJJIJIJIJIJIIJIIJJIIIJIIJJJIJ()
		{
		}

		[DebuggerHidden]
		void IEnumerator.Reset()
		{
		}
		private object JJJJJIIJJIIIIIIIIIIIJIIIIIJJJIIIIJIIJJJJIJJIJJJ()
		{
			return null;
		}
		private object IJJJIIJIJJJJIIIIIJJIIIIJJJIJIJIIJIIJIIJIIJIIJJJ()
		{
			return null;
		}
		private object IIJIIIIJJIJJIIIIJJJJJJIIJJIJIJJJJJIIJJJJJIJJJJJ()
		{
			return null;
		}
		private object IJIIIIIJIIIIJJJJJIIJJIIIIIJIJJJIIJIJJIJJIJJIJJI()
		{
			return null;
		}

		[DebuggerHidden]
		public IJJJJJJIIIJJJIJJIIIIIJIJIJJJJJIJIJIJIJJJJIIJJIJ(int IJJJJJJJJIIJIIIIIJIIJJJIJJIIJIJJJJJIJJJJJIIIIII)
		{
		}

		[DebuggerHidden]
		void IDisposable.Dispose()
		{
		}
		private object IJIIIJJIJJJIJIIIJJJJIIJJJJIIJJIIJIIIJIJIIJIJIJJ()
		{
			return null;
		}
		private object IJJIJJJJIIIJJIIJIIIIJIJJIIIJIIJIJIJIJIIIIJIIIJJ()
		{
			return null;
		}

		private void JJIIIJJJJJJJJIIJIJIIIJIIIIIJIIIIJIIJJIIIIIJIJII()
		{
		}
		private object JIIJJIJIJJIJJIIIIJIJIJIJIIJJIIIIJIIJIJJJJJIIIJI()
		{
			return null;
		}
		private object JJJJIIJJJJJJIJJJJIJIIIIJJIIJIIJJJIIJIJJIIIJIJII()
		{
			return null;
		}
		private object JIIJJJJJJIJJJIIIJJJIIJJIIJIIIJIIJIJIJIJIJJJIIJI()
		{
			return null;
		}
	}

	private int JIJJJIJJIJIIJIIIIJIIJIIJIJJIJIIIJJJJJJIIIJJIJIJ;

	public UILabel IIIIIIJIIJIJJIJJJJJIJIJJIJJIJJJIIIIJJJJIJJIIJJI;

	public UIPopupList JIJJIIJJJJJJJIIIIJJIIIIIJJIIIJJIJJIIIJIIJIJIIIJ;

	public GameObject IIIJIJJIJIIJIJJJIJIIIIJIIIJJIJIJIJJJJIJJJJJIIIJ;

	public GameObject IJIIIIIIIJJJJIJJIIIJIIJJIJJJJIJJJIJJIIJIIIJJJJJ;

	public UILabel IIJIIJIJJJJIIJIJIJIJJJIIJIIIIJJJIIIIIJJIIIJIIJJ;

	public GameObject JJIIIJIIIJIJIJIJJIJJJJIIIJJIIIJJJIIJIIIIIIIJJIJ;

	public UILabel JIJJIJIIIIIIJIJJIJJIJJIJIJJIIJIIIJJIIJIJJJIJJII;

	public UIInput IJIJJIJJIJIIIIJJIIIIJJIJIJIJJJIIIIIIJJIJJIJIIIJ;

	public UIScrollView IJJIIIIIJIIJIJIIIIIIIIJIJIIIJIIJIJJIIJIIJIJJIIJ;

	public GameObject IJJJJIJJIIJIIJJIJJIIIIIJIIIJJJJIJJIIIJIIIJJJJIJ;

	private bool IJJIIIJIJIIIIJJJJIJJJJJJJIJIIJIJJJJIJJJJJIIIIJJ;

	public UIToggle JJIJIJJJJIJJJIJJJJJJJIJJJIIJJJJIJIJIJIJJJJJJIIJ;

	public UIToggle IJIIIIIJIJJJJJJIIIIJJJIJIIJJJIJIJIIJJJJIIIJIIJJ;

	public UIToggle JIIIJJJJJIIIIJIJJJIIJIIIIIIJJIIIJJJIJIJIIIIIIJJ;

	public UIToggle IJJIIJIJJIIIJIJIIJIJJIIJJIIIIJIIIIIJIIIJJJJJJIJ;

	public UIToggle JJJJIIJIJJIJIIIIIIIJJJIIIIIIJJJJJJIJIIIIJIIJIIJ;

	public bool IJIJIIJJIIIJJJIJJIJJIJIJIJJIIIIIJJIJJIJJIJIIIJJ;

	public bool IJJIIIIIJJJIIJIJIIIJIIJIJIJJIJJJIJJIIJJIJJIIJIJ;

	public bool IIIIJIJJIIJJIJJJIJJJIIJJIJIJJIIIIIJJIJIIJIJJJJI;

	public bool JIIJIIIJJIIJJJIIJIJIJJJJJJIJJIIJJJJJIIJJIIJIJIJ;

	public bool JIIIIJIIJIIJIJJJIIIJJIIIJJIJIJIIIJIJJJJIJIJJIJJ;

	private List<GameObject> IIIIIIJIJJIJJIIJJJJIJIIIIIIJJJIIIIIIJJJJJJIJIIJ;

	private List<GameObject> IIJIJIJIIIJJJJIJJIJIIJIIIIIJIIJIJIJIIJJIJJIJIII;

	private bool IIJIIJIIJJJIJJIIJJIJJIIIIIJJJJIJIIJIIIJIIIJIJJJ;

	private int JJIJIJJJIIJJIJJJJIJJIIIJIJJJJIJJJJJJJJJIJIIJJJJ;

	private int IJJJJJIIJIJJJJJIIJJJJIIJJJJIJJIJIIIJIJJIJJIJIJJ;

	private int IIJJJIIJIJJIIIJJJIJJJJIJIJJIJJIJJJIIJJIJJIJJJJI;

	private int IJIJIIIIJJJIIJJIJIJIJJJIJJIJJJIIJIIJIJJIIJIIJJJ;

	private JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ[] IJJJJIJJIIJJIIIJIIIIJIIIJIIJJJIJJIJIIJJJIIIJIIJ;

	private int JIJIIIJJJIIIJJJIJJJIIJIJJIIIJJJIIJJIJJIJIIIIIJI;

	private int IJJJIIJJJIJIJJIIJJIJIJIIIJJJJIIJJJJJJIJIJIJJJII;

	private IEnumerator IIIJIIJIJJJJIJJIIIIJIIIIIJIIJJIJIIIIJIIJJIJJIIJ(bool JJJIJIIJJIJIIJIIJJJIIJJIIIJIJIIIJJIIJJIIIJIIJIJ)
	{
		return null;
	}

	private void JIJIJJJJJIIIIJJIJIIIIJIJIJJIJIJJIJJJIJJJJIIIJIJ()
	{
	}

	public void JIJJJJIIIJJIJJIJIIJJJIIJJIIIJIJJJIJJJJIJJIIIJJI()
	{
	}

	public void Open()
	{
	}

	public void IJIJIIJIJJJIIIIIJJIJJJJIJJIIJJIIIJIJJIIJIIIIIIJ()
	{
	}

	private void JIJIIIJIJJJIJJJIIIIJIIIIIJJJIJJIJIIIJIIIIIJJIIJ()
	{
	}

	private Transform JJJJIIJJJJJJIIIJIJJJIIIIJIIJJIIIJIIJIIIJJIIJJIJ()
	{
		return null;
	}

	public void LeftSwitch()
	{
	}

	public void JIIIJIJIJIIJIIJJJIJJJJIJIIIIIIJIJJJJJIIIIIIJIII()
	{
	}

	private IEnumerator IIIIJJJIJJJJIIJIJJIJIJJJJIJIJJIIJJJIIJJIIJJIJJJ(bool JJJIJIIJJIJIIJIIJJJIIJJIIIJIJIIIJJIIJJIIIJIIJIJ)
	{
		return null;
	}

	private void JIJIJIJIJIJIIIIIIIJIJIIIIJJIJIJIIIJJJJIJIIJIJJI()
	{
	}

	private List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> IJIJIIJJIIIJJJIIJIIJJJJIJIIIIJIJIJIIJJIJJIIJJJI(List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
		return null;
	}

	private void JIIIJIIJIIJIJJJIIJIJIIIJIJIJJIIJJIIJIIIJIIJJIII()
	{
	}

	private void IIIIIIJIJJJIIIJJIIJIJIJJIJJIIJJIIIJJJIJJJJJIIJJ()
	{
	}

	public void IJJJIIIJIJJJJIIJJIJIJJIJJJJJJJJIIJIJIIIIIJJJJJI()
	{
	}

	private List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> JJJJJIJJIIIJIJJIIIJIIJIJJIJIIJIIJJIJJJIJIIIJIIJ(List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
		return null;
	}

	public void SettingsClick()
	{
	}

	private List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> IIIJJIIIJIJJIJJIIIJIJIJJJJIJIJJJIJJJJJJJIIIIJII(List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
		return null;
	}

	private void IIIIIJIIIIJIIJIIIJJJIIJIJJJJIJJJJIIJJIJJIIIIIII()
	{
	}

	private List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> JIJJIJIIJIJIIJJIJJJIJIJIIJIJIIJJJJIJJJIJIJIJIIJ(List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
		return null;
	}

	public void JJJJIIIJJIJIIIJIJJIJIJJJIJJIJJIIJIIIIJIJJJIJJIJ()
	{
	}

	private List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> IJJIJJIJIIIIJJJIJJIIJIIIJIJJJIIJJIJJIJIJIJJIIIJ(List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
		return null;
	}

	private void IJIIIJJJJIIIJJJJJIJJJIIJIIIJJJJJIJJIJJJJJIIJIJI()
	{
	}

	private List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> IJIIIIIIIJJJJIJJIIIJIIIIIIJIIIJIJJJIIIIJIJIIIIJ(List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
		return null;
	}

	private List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> IJIJIJIJJIIJJJJJJJJIJJJJIIIJJJIJIIIJJIIIJIJIJJI(List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
		return null;
	}

	private List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> IJIIJIIJJIJIJIJJIJJIIIIIJIIIJIJJIIJJJIIIJIIJJII(List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
		return null;
	}

	public void JIJJJJJJJIJIJJIJJIJIIIIJJJIIJIJIJIJJJIJIJJJJJII()
	{
	}

	public void IJIJIIJJJJJJIJJIIJJIJJIIJJIIJJIJIJJJIJIJIJIIJJI()
	{
	}

	private Transform JJIIJIJIIIIJJJIJJIIIJIIIIJIJJJIJJJIIIIIIIJIIIIJ()
	{
		return null;
	}

	public void SettingsToogle()
	{
	}

	public void RightSwitch()
	{
	}

	private List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> IJJIJIJIJIJIIIJJJJIIIIJJJIIIJJJIIJIIIJIJJIJIIII(JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ[] JJIIJJIJIJJIJIIIJJIJIIIJIJIIIIIIIIIJIJIJIJJJIJI)
	{
		return null;
	}

	public void UpdateServerList()
	{
	}

	private void Start()
	{
	}

	private JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ[] IJJJJIIJIIJIIIJJJIJIIJIJIIIJIIJIJJJJJJJIIJJJJIJ()
	{
		return null;
	}

	private void IIJJJIJIIIJIIJJIIIIJJIJIIJJJIIIIIJJIIIJIJJJJIIJ()
	{
	}

	public void SelectMode()
	{
	}

	private List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> JIJIIJIIIIJJIJIJJJIJIIJIIJIJIJJJJJJIJIIJIJJJJJJ(List<JJIJIIIJJJJIIIJJJJJJIJJJIJJIIIIIIJIIIIJJIIJJJJJ> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
		return null;
	}
}
