using System;
using UnityEngine;

public class mShowElementManager : MonoBehaviour
{
	public UILabel IJJJJIIIJIJJJJIIJJJIJJIIJIIJJJJJJIIIIJJIIJIIJIJ;

	public UILabel JJIJJJIIIIIIIJIIJJIIJJIIJJJIIJIJIJIIJJJJJIIJJIJ;

	public UITexture IIIJIJJIJJIIJIJIIJJIIJJIJJIIJIIJIIIJJJJIJIIIIJI;

	public UISprite IIIJIIIJJIJIJJJIJJIJJIJJJJIIIJJJIIJIIIJIJIJJJJJ;

	public UIWidget IIJIJJIJJJIJIIJIIJJJIIIJJJIJJIJIJJJJIIJJJJIJIII;

	public UILabel IIIIIIJIIJIJJIJJJJJIJIJJIJJIJJJIIIIJJJJIJJIIJJI;

	private Action JIJJJIIJJJIJIIJIIJJJJIJJIJIJJJJIJJIJJIIIIJIJJJJ;

	private static mShowElementManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private bool JJIIIJJIJIIIIIJIJIJIJIJIIJJIJIJJJIIIIJJIIIJJJII;

	public static void JJJIIIJIIJIJJIIJJJJJIJJJJJIIJIJIJIIIIIIJIIIJJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(IIIIIJIIIJIJIJIIJIIIJJIJIIJJIIIIIIIJIJIIJJIIJJI IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII, Action IJJIIIJJIJIIJJJJJIJIJJJJIJJJJJIJIIIIIIJIJJIIJJJ)
	{
	}

	private static Color IJJIIIJJJIJIJJIIJJJIIIIJIIJJIIJJJJJJIIJJJJJJJIJ(JIIJIJJJIJIJJIJIIJJIJIIIJIIJJIIIJIIIIJJIJJIJJJI IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	private void OnEnable()
	{
	}

	private static Color JIJJIJIJIIIJJJJIIJJJIJJIIJJIIJIJJIIJJJIJIJJJJJI(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	private void OnDisconnectedFromPhoton()
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(int IIIJJJIJJIIJIJJIJIJIJJIIIJJIIIJIIJIJJJJIJIIIIJI, Action IJJIIIJJIJIIJJJJJIJIJJJJIJJJJJIJIIIIIIJIJJIIJJJ)
	{
	}

	public void IIIJIIJJIIJIIJIIIIIIIIJIJIJJJIIIIJIIIIIIJJIJIJI()
	{
	}

	public void Close()
	{
	}

	public static void IJJJJJIIJJJJIIIJJIJIJJJJIJIIIIJJJJIIIJIIIJIIIIJ(IIIIIJIIIJIJIJIIJIIIJJIJIIJJIIIIIIIJIJIIJJIIJJI IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII, Action IJJIIIJJIJIIJJJJJIJIJJJJIJJJJJIJIIIIIIJIJJIIJJJ)
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void IJJJIIJJIIJIJIJIIJIJIIJJJJJIJJJIJIJJIJJJIIJJJJJ()
	{
	}

	public static void IIIIIJIJJIIJJIJJJIIIJJIIJJJJJJIIJJIJJJJIIJIIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void Start()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private static Color JIIIIJIJIJJIJJJJIJJIJJIIIIJJJJIJJIJJJIJJIJIIJJJ(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	private static Color JIIJJJJIJIIIJIJJJIIIIIJJJIJJJIJIJJIIJIIIIJIIJII(JIIJIJJJIJIJJIJIIJJIJIIIJIIJJIIIJIIIIJJIJJIJJJI IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	private static Color IIIJJIIIJJIIJIJJIJIJJJJJJIJIJIJJJIJIJJIIJIIIIJI(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	private void JIJJIIIJIJIJIIIIJIIJIJIIIJIJJIJIIIIJJIIIJJIIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 JJJIIJIIIIIIJJJIIJJJJIJIIJJIJIIIIJJIIJJJJJJJJJI)
	{
	}

	private static Color JJIIIIJIJJJJJJIIJJIIIJJIJJJIJIJJJIIIJJIJIIJIJIJ(JIIJIJJJIJIJJIJIIJJIJIIIJIIJJIIIJIIIIJJIJJIJJJI IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	private void JJJJIIIIJIJJIJIJJJJIIJIIJJIIJJJJJJJIJJIJJIJIJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 JJJIIJIIIIIIJJJIIJJJJIJIIJJIJIIIIJJIIJJJJJJJJJI)
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	public static void JIIIIJJIJJJIIIJJJIJIIIIIJJIJJIIIIIJIIIJIIIJJJIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void OnDisable()
	{
	}
}
