using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Photon;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mStoreWeapons : Photon.MonoBehaviour
{
	[Serializable]
	public class JIIIJIIIJJJJJIJIJIIIJIJIIIIJIIIIJIIIIJJIIIJIJJJ
	{
		public GameObject JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ;

		public UILabel IJJJJIIIJIJJJJIIJJJIJJIIJIIJJJJJJIIIIJJIIJIIJIJ;

		public UILabel JIIIJIIJJJIIIJIJJIIJJIIIJIJJIJJJIIIJJIJIJJJJIII;

		public UIProgressBar IIJIJIIIIIJJJJIIJIIJJIJJIJJJIJIJIJIIJIJIIJJIIJI;

		public UILabel IIJJIIIIJIJIJIIJJIIJIJJJJIJJIIIIIIIIIJIIJIJJJIJ;

		public UIProgressBar IJIIJIIJJIJIJIJIJIJJJIIJIIJIIJJIJIIJJJIJJJJIJJJ;

		public UILabel IIJJIJJIJIIJJJJJIJJIJJIJIJIIIJJIIJIIIJIJIIJJIIJ;

		public UIProgressBar JJIIJIJIIJIJIIJJIJJJJIJJJIJJIJIIIJIJIJJIIIJJJJI;

		public UILabel JJJIIIJIIJJIJJIJIIJIJIIJJIIJIJIIIJIJIIIJIIJIJJI;

		public UIProgressBar IJJIJJIIJIJIIIJIIJIJIJIIIJIIIIJIJIIJIIJIIJJIJJJ;

		public UILabel IIJIIIIJJIJJJIIJIIIIIIJIJIIJIIJJIIIIIJJIJJIJIJI;

		public UIProgressBar JJIJJIIJJIJJJJJIJIIIJJJIJJJJIIJJIIIIIIJJJIJIJJJ;

		public UILabel JIIJIIIJIIJIIJJJIJJJJIJIJIIJIJJJIJJIIIIJJIJJIJJ;

		public UIProgressBar IIIIJJJIIIIJIIIJIJJJJIIIIIIIIJJIJIIJJJJJJIIJJJI;

		[Space]
		public float JIJJJIIJIIJJJIJIJJIIJIIIIIJIIIIJJJJJIJJJIIJJJII;

		public float IIIIJJJJIJIIJJIJIJJJJIJJIJIJJIJIJIJIIJJJJIIJJJJ;

		public float JIJJIIIJIJIJIJJIIJIIIIIJIIIJJJJJJIIIIIJIIJJJIII;

		public float JJIJIJIJIJJJJIIJJJJJJIJJIJIJIIIIIJIIIIIIIIJIIIJ;

		public float JIJJJIJIIIJIIIIIJIJJIJJIIIIJJJJJIJIIIJIJIJIIIIJ;

		public float JIJIJIJIIIJJJJJJIIJIIJJIJIIIJJIIJJIJIJIJJJJJIJJ;
	}

	public JIIIJIIIJJJJJIJIJIIIJIJIIIIJIIIIJIIIIJJIIIJIJJJ JJJIIIIIIIJIIJIIJJIIIIJIIIJIJJIJIJJJIIJJIJIIJJI;

	public UIWidget JJJJJIJJJJIJIJIIJJJIIJIJIIJJIJIIIJIIIIIIJIIJIJJ;

	public UIWidget[] IJIJIJJIJIJIIJIJJIIJJIIJJIJIIJIJJIJIIIIJJJJJIJJ;

	public UILabel IJIIIJJJJJIIJIJIJIJJIJIJJJJJJIJIJJIJJIIJJIJJJJI;

	public UILabel IJIJJIIIJJJIJJIJIJIIIJIIIJJJIJJJJJIIIIJIIJJIIIJ;

	public UITexture IIIJIJJJJJJJJJJIJIJJIIIJIIJIJJJIIJJJIJIIIIIIJII;

	public UISprite IJJJJIJJIIIIIJJJJIIJJIJJJIJJJJIJIJJJJIIJIIIIIJI;

	private List<string> JIIJJJJJIIIIJIIJIIJJIJJJIIIJJJIIIJIJJJJJJIJIJIJ;

	private int IJJIJJJIIJJJIIIJIJIJIJJIIIJJJIJIJJIIIIIJIIJIJJJ;

	private JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII JJIJJJJIIIJJIJJJIIJJJJJIJJIIJJIJJIIJIJJIJJJIIJJ;

	private JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIJIIJJJIJIIJJJIIJIIJIIJJIIIIIJIJIIIJJJJJJIJJI;

	private IIJJJJJJJJIIJJIIJJIJIIJIJJIIJIJJJJJIJJIJIJJIJJI IJJIJJJIIJIJIIIJJIIJJIJJJIIIIIJJIJJJIJJIIIJJJII;

	private IJIJJIJIIIJJIJIIIJJJJIIIJJJJJJIJIIJJIJIIJIJJIIJ JIJJIJIIJJJIJIJIJIJJIJIJJJIIIIJIIJIIJJIIIJIJJJJ;

	public UILabel IIIJIJIJJIIIIJJJJJIIIIJIIJIIJJIJJIJJJJIIIIIIJJJ;

	public UILabel JIIJIJIJIJJJIIJIJIIJIJIIIIJIJJIJIIJIJJIJJJIJIJJ;

	public UITexture IJJJJJIIJJIIIIJJJJIIJJIIJIIJJJIIIIJJJJJJJJJIIIJ;

	public UISprite IIIIJJJJJJJJJJJIIIIIJJIIJJIJJJIJJJIJIJIIJIJJJII;

	public GameObject JIIJJIIIIJJJIIJIJJJJJIIJJIIIJJJIJIJJJJIIIIJIJIJ;

	public Texture2D IJIJIJJIIIJIJJIJIIIJJIIJIIJJJIJJJIIJJIJIIJJJJIJ;

	public Texture2D IIIIIJJIIIIJIJJJIIIIIIIIJJJIIIJIJJIIJJJJJIIJJJI;

	private bool IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI;

	private void IJJJJJIJIJJIIIIIIIIIIIIIJIJIJIIIJJIJIIIJJIJJJII()
	{
	}

	private void JIIJIIJJJJJJIIIJJIIJJJJIIIIIJJJIIIIIJIIJIJJIIJJ()
	{
	}

	private void JJIJIIJIJJJIIIJJJJIJJJIJJJJJJJIJIJJIIIIJIJIIIJI()
	{
	}

	private void Start()
	{
	}

	private void JIJIIJIIJIIIJIJJJIIIIIJIJIJIJJJJJIIIJIIIJIJIJJI()
	{
	}

	private void JIIJIJJJJIJJIIJIJIJJIIJJIJJIIJJIIJIIJJJJIIJIIIJ()
	{
	}

	private void JIIJIIJIJJJIJJJJIJJJIJIIJIIIIJJJJJIJJIIIIJJJIII()
	{
	}

	private void IIJIJIJIIJIIIIIJIIIJJJIJIJJJIJJIJIIIJJIIIJJJJIJ()
	{
	}

	public void IIIJJJIIIJJIJJJJJJIIIIIIIIJIIJJIJIJJJIJJIJIJJIJ(int type)
	{
	}

	public void IIJIIJIJJIJIJIJIIIJJIJIJJIJIIIJJJIJIIJIJIIJIIIJ()
	{
	}

	[CompilerGenerated]
	private void JIIIIJJIIJJJJJJIJJJJJIIIJIIIJIIJIIIJJJIIJJJIJJJ()
	{
	}

	private void IJJIIJJIIIJJIIIIIIIJJIJIIIJJJIJJJIJJJJIJIIIIIII()
	{
	}

	public void IJIJIIIJIIIIJJJIIJJIIIJIIIJIIIJJJIJIIJIIJIJIJII(int type)
	{
	}

	private void IJJIJIIIIJIIJJJJJJJJIJJIJIIIJJJJIIJIJJIIIJJIIJJ()
	{
	}

	private void IIJIIIIIJJIJJIIIJJIIIIJIJJIJIIJJIJIJJJIIJJIIJJI()
	{
	}

	private void JJIIJIJIIIJJIJJIJIJJIIJIIJIIIIJIJJJIJIIJIJIJJII()
	{
	}

	[CompilerGenerated]
	private void IJJIIIJJJIIJJJJIJIIJJJJIIJJIIIJIIJIJIIJIJIIIJIJ()
	{
	}

	public void SelectWeapon()
	{
	}

	public void ShareScreenshot()
	{
	}

	private void IIJJIJJJJJIJJJJIJJIIJIIIJJJJJJJIIIJJJIIJJIIJJJI()
	{
	}

	private void JJIIIIIJIJIJJJJJIJJJIJJIIIJJIIJJJIIIJJJJIJIIIJI()
	{
	}

	public void ShowHideWeaponInfoPanel()
	{
	}

	public void JJIIJJIJIJIIIJJJIIIIIIIIIJIJIIJJJJJJJJIIIIJIJJJ()
	{
	}

	private void OnDisconnectedFromPhoton()
	{
	}

	private void IJJJJIJJJJIIIJJIJIIJJIIIIIJJIJJJIIJIJIJJJJIIJII()
	{
	}

	private void OnDisable()
	{
	}

	public void BuyWeapon()
	{
	}

	private void JIIJJJJIJJIJJJJIJJJJJIIJIIIIJJJIIJIJJJJJJJJIJII()
	{
	}

	private void IIJIJJIJJIIJIJJIIJJIIIIIIIJJIIJIIJIJJIJIIJIJIJJ()
	{
	}

	private void IJIIIJJIIJJJIJJIJJJJIIJJJJIJJIIIJJJJIIIIIIJJJIJ()
	{
	}

	private void JIIJIIIJJJJIIJJJIJIJIJJJIJIJIJJJJIJJIIIIIIJJJJI()
	{
	}

	public void LastWeapon()
	{
	}

	private void IJIIJIJJJJIIJJIIJJJIJJIIIIJJJJJIIIJJIJIJJJJIIJJ()
	{
	}

	private void OnEnable()
	{
	}

	public void NextWeapon()
	{
	}

	private void JIIJJJIIIIJJIIJIIIIIJIJIJJJIJIJIJIJJIJJIIJIJIJI()
	{
	}

	public void Show(int type)
	{
	}

	private void JIJJJIIIJJIJIJIJJJIJJIIIJJIIJIIIJJIJIIJJIJIIJJI()
	{
	}

	private void IIJIJJJJIJJIIIIJJJJJIIIIIIIIJIIIIIJJJJIJIJIJIII()
	{
	}

	public void ShowWeaponPanel()
	{
	}

	public void Close()
	{
	}

	private void IIJIJIJJJJIJIJIIJJJJJJJIIJIJIJIJIJIIIJJJJJJIIJI()
	{
	}

	public void JJJJIJIJIJIJJJJJJIIJJIJJIIIIJIJJIJIIJIJIIJIJIIJ()
	{
	}

	private void JIJJIIIJIJIJIIIIJIIJIJIIIJIJJIJIIIIJJIIIJJIIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 JJJIIJIIIIIIJJJIIJJJJIJIIJJIJIIIIJJIIJJJJJJJJJI)
	{
	}

	public void IJJJIIIJJIJJJJJJIIIJIIJIIIJJJJIJIIIIIJJIIIIIJJI()
	{
	}

	public void IJIJJJIIJJIJJJIIIIIIIJIJIIJIJJIJJJIIJJIIJIIJJJJ()
	{
	}

	private void IJIJJIIIJIJIJIJIJJJIIIIJIJIJJJIIIIIIJIIIIJIJIII()
	{
	}

	private string JJJIIJJJIJJIJIIJIIJJIIIJJIIIIIIIJIJJJJIIIJIIJII(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return null;
	}

	private void JIIIIJJIJJIJIIJJJIIIIJJIJIIIJIJIIJIIJIJJIJIJIJI()
	{
	}
}
