using UnityEngine;

public class MurderModeManager : MonoBehaviour
{
	public GameObject IIIIIJIIIIJJJJIIIIJJJJJIJIIIIIIIIIIJIIJIJIJJJII;

	private bool IIIIJIJIJJIJIJJIJJJIIJIIJIIJJIJIIIJIJIIJJJJJIIJ;

	private static MurderModeManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void IIIIIIJIIJIIIIJIJJJIJJIIIIIIJIIJJIJIJIIJIIIIIJJ()
	{
	}

	public static void IJJJIJJIIJJIIIIIJJIIIJJJJJIJJIIJJJJJIJJIJJIJJII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJJIIIIIIIIIJIJJIIJIIJIIJIIIJJIIIJIJIJIJIIJJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void Awake()
	{
	}

	public static void JIIJIJJJJJJIJIIIIJJJJJJJJIJIIIIIJIJIJIJIIIJJJJJ(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, Vector3 IIJIJIIJIIIIIIIJIJIIJJIJIJIJIIJJIJIIIIIIJJIIIII)
	{
	}

	private void JJJJJJJJIJJIJIJJJJIIJJJJJJIIIIJJJIIJIIIJJJIIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJIJIJJJIIIJIIIJIIIIJIIIIJJJIIJJIIIIIJIIJJIJJJI()
	{
	}

	private void Start()
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIJJJJJJJIJIJIJJJIIIIIIIIIIJIIJJIJJJIJJJJJJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void OnTriggerEnterPistol()
	{
	}

	public static void JIIIJJIIIIIIJIJIIJIIJJIIJIIJIJJJJIIJIJIIIJIJIII(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, Vector3 IIJIJIIJIIIIIIIJIJIIJJIJIJIJIIJJIJIIIIIIJJIIIII)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJIJIJJIIJJIJJJJIIJIJIIJIJJIJIIJJJIJJIIIIJIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJIIJIJJJIJJIJJJJJIIJJJJIJIIIJJIJIIJIJJJIIIJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void JIIIJJIIIIIIJIJIIJIIJJIIJIIJIJJJJIIJIJIIIJIJIII(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	private void JJIIIIIJIJIJIJJIJIJIIIJIJJIIJJJIIJJIIJIJIJJIJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IJIJJIJIIIJJJIIJIJJJJJJJJIJIJJIIJIIJIJJJJIJIIII(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, Vector3 IIJIJIIJIIIIIIIJIJIIJJIJIJIJIIJJIJIIIIIIJJIIIII)
	{
	}

	private void JIJJIIIJJJJJJJJIJJJJJJJJJJIIJIJJJIJJJJJJIJIJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void JIJJJIIJJJJJIJIJIJIJJIIJIJJJIIJIIIJJJIIIIIJJJJJ()
	{
	}

	private void JIIIJIIIIJJIIJJJIJJIIJIJJIJJJIJIIJIJIJJJJJIIJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IIIJJJIIIJIIJJJJIJIIJJJIJIJIJIIJIIJIJJIJIIJIJII()
	{
	}

	public static void IIJIIIJIJJJJIIIIIIJIIIJIJIJIJJIIIIIIJJIJJIJJIII()
	{
	}

	public static void JJJJIJIIIIIJJJJIIIJJJIIJIJIIJJJIIIIJIJIJJJIJJJI(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, Vector3 IIJIJIIJIIIIIIIJIJIIJJIJIJIJIIJJIJIIIIIIJJIIIII)
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void IIIJIIJJJJJJJJIJIIJJIJIJIJIJIJIIIJIIIIIJIIJIJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private void IIJJJIJJIJJJJIIJJIJIIJJIJIJIIJJJJJJJJIJJIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IJJIJIIJIJIJJIJIJJJJIJJIIIJJJIIIJIIJIIJIIJIIJJI()
	{
	}

	private void IJIJIJJJIIIIJIJIIJJIIIIIJIIJIIIJJIIJIIIIJJIJJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IJJJIIIJIJIIJIJJJJIJJJIIIIIIIJJIJIJIJIJJIIIIJJI()
	{
	}

	private void IIJIJIIIIIJJIIIIIJJIJIIIJIJIJIIIJIJJIIIJJJJIIJJ()
	{
	}
}
