using System;
using System.Collections.Generic;
using DG.Tweening;
using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mWeaponCamera : MonoBehaviour
{
	[Serializable]
	public class IIIIJIJIIIIIIJIJIJJIIIIIJJIJIJJJIJJJJIJJJIIJJJI
	{
		public string IJJIJJJIIJJJIIIJIJIJIJJIIIJJJIJIJJIIIIIJIIJIJJJ;

		public GameObject IIJJJIIJIJIIJIIJJJJJIIIJJIIJJIIIJIIJJJIJJJJIIJI;

		public GameObject JIJJJJJIJIJIJJJJJIJJJIJIIIJJIJIJIJIJJJJJJJJJIII;

		public MeshAtlas[] IIIIIJIJJJIJJIJIJJIJJIJIIIJJJIJIJJJIIJJJIIIJJIJ;

		public MeshAtlas[] JIIIIJJJJJIJIJJJJIIIIIJIIJIIJJIIJJIIJIJJIIIIIIJ;
	}

	private sealed class IJJIIJJJJIIIIJIJJIIJIIJJJIIIIIJJIJJIJIIIJJIIIIJ
	{
		public MeshAtlas JJJIIIJJJIIIIIJIJIJJIIIJIIIIIIIJIIIJIIIIIIJJJJI;

		internal void JJJJJJIJIIJJJIJJJJIIJJIJIJIIIIJJIIIIIJJIIJIIJIJ()
		{
		}

		internal void JJJIIJIJIIJIJIIIIJJJJJJIIJIIIJIJJJJIJIIIJJIIJIJ()
		{
		}

		internal void JIIJIJIJJIIJJIJJJJJIJJJIJIJIJIIIIIIIJJIIIJIIJJI()
		{
		}

		internal void IIJIIJJIJJJIIIJJJJJIIJJJJIIIIIJIIIJJJIIJIIIJIJJ()
		{
		}

		internal void IJJJJIJIIIIIIJJJJJJJJJJIIIJIJIIIIIJJJJJIIJIIIII()
		{
		}

		internal void JIIJIJIIJIIIJIIJIIJIJJIJIJJIIJJIJIJIJJIIIIIJJIJ()
		{
		}

		internal void JJIJJJJJJJJJJIJIJJJIJJIJIIJIIIJIJJIIIJIJIJJIJIJ()
		{
		}

		internal void IIJJIIJJJJJIIIIIIJJIJIIIJJIIJIJIIJJIJJIIJJJJIJI()
		{
		}

		internal void IJIIJJJIJIJJIJIJJJIJIJJIJIJJJIIIIIJJJJJIJIJJJIJ()
		{
		}

		internal void IJJJJJJIIJJJIIJIJIIIIJJJIIJIIJIIIJJIJJIIJJIJIII()
		{
		}

		internal void IIJIIIIJIIIJJIIJIJJJJIIJIIIIIJIIJJIJJIJJJJIIIJJ()
		{
		}

		internal void IJIJJJJJIJJIJJJJIJIIJJJJJJJJJJJIIIIJIIJIIIIJIJI()
		{
		}

		internal void JJJIIJJJIIIJJIIJIIIJIIIJIIIIJJIJIJIJIJIIJJIIJIJ()
		{
		}

		internal void IIJJJIIJJIJIJIIIIJIJJJJIJIIJIIJIIIIJIIJJJIIIIII()
		{
		}
	}

	public Transform IIJJJIIJJJIJJIIIIJIJIIJIJIJJIIIIIJJIIJIIIIJIIJJ;

	public GameObject JJIJIIJIJJJJIJIIJJIIIJIIJJIJJIIJJJJJJJIIIJJJIII;

	public Transform JJIIIIJJIIIIJJJJJIJIIIIIIIJIJIJIIIIIJIIIIIJJIJI;

	public float JIIIJIIJJJJJJIJIJIIIIIJJJIJIIJJJJIJJJIJIJJJJIIJ;

	public Vector3 IIIJIJJJIJIJJJJJJIIJIIJIJJJJIJJIIJJIJIJIIJJIIIJ;

	public float IJIIJJIIJIIIJIJJIIJIJJJIJIJIJIIIJIJIIIJJJJIJJII;

	public List<IIIIJIJIIIIIIJIJIJJIIIIIJJIJIJJJIJJJJIJJJIIJJJI> IJJIIJIIJJIIJJJIJJIJIJJIIIIIJIJJIIIJJIIJJJJJIIJ;

	private int IIIJIJJIJJIJIIJIJJJJIJJIJIJIIIJIIIJIJIIJJIIJIII;

	private Camera IJJJIJJJJIIIIIIJJIJJJJJJIIIIJIIIJIIJIIJIJJIJIJJ;

	private Tweener JIJJJJIIJJIIIIJJIIIJJJJIIIJIJJIIJIJJJJJIIJIIJIJ;

	private int IJJIJJJJIJJJJIJJIJJJJIJJIIIJJJJJIIJJIIIJIJIJIIJ;

	private static mWeaponCamera JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void JJJIIIIIJJJIJJJIIIJJJJJIJIJJIJIJJJIIIJIIIJJJJJI(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
	}

	public static void IJJIIIIJIIJJJIIJIJIIIIIJJJJJIIIJIJJIIJJIJIJJIJJ(bool JJJIJIJIIJIJIJJIJJJJIJJJJJJIIIJIIJJJIJJIIIJIJII)
	{
	}

	public static void JJIIJIJJIJJJJJJJJJJIJIIIJJIIJIJIJJIJIJIIJIIIIII(string JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ)
	{
	}

	private void Start()
	{
	}

	public static void IIIJJIIIJIJIJIIIIJJJIIJIJJIJIJIIIJIJIJIJJJIJJJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JIJIIJIJIJIJJIJIIJIJIJIJIIJIJJJJIJIIIJJJIJJJJIJ(string JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ)
	{
	}

	public static void IIJIIJIIIJJIJIIIIJJIJJIIIIJJJIJIJJJIIJIJJIJIIJI(int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ)
	{
	}

	public static bool JIIJJJJJIJIJIJJJJJIJJIIIIJIIJJIIJJIJJIJJIJIJJIJ()
	{
		return false;
	}

	public static void IIJIIIIIIJIJJIIIIJJJJIJIJJIJJJJJIIIIJIIIJIIJJJJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void IJIIJJJJIIJJJJIJJJJJIIJIIIIIJIIIIJJIJJJIIJIIJII(int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ)
	{
	}

	public static void IJJIIIIIIJIIJJIIJIJIIIIIJJIIIIIJJIJIIJJJJJJJJJI(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static int IJIIJIJIIJJIJJIJIIJIIJIJJJIIJIIIJIJIJIJIIIJIJII()
	{
		return 0;
	}

	public static void JIIJJIJJIIIIJJJJJIIIIJJIJIIIJJJIJIIIIIJIJIJJIII(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
	}

	public static void IIIJJIJIJIIJJIJJIIJIIJIIJIIJIIJIIJJJJJJIIIJJJIJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
	}

	public static void JJJIIIIIIIIJJJJIJIJJIIIIJIIIJJJIJIJIJIJIJIIJIJJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI, int JIJIIJJJIJIJIJIJIIIIIJJIJJIIJJIIJJJJJIJJIIIIJII)
	{
	}

	public static void IJJIIIJIIIJIIJIJJJJIIJIJJIJJIJJIJJIJJIIIIJJIIJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void Update()
	{
	}

	public static void IJJJJIJJIIJJJIJIIJJJIIIIJJJJJIJIJJJIJIIJJJIIJIJ(Vector3 IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII)
	{
	}

	public static void JIIIIIJJIJJJJJJIJJIJIJJIIJIIJIIJIIIIIJIJJIJJJJJ(Vector2 JIJIJJJJJIIIJIJJIJIIJJIIJJIJJIJJIJJJIJJJIJIIJJJ, bool JJIIJJIIJJIJJIIJJJIIJIJJIIIIJIIJJIJJJJJJJJIIJJJ)
	{
	}

	public static void IJJIJIJIIJJIJIIJIJIIJJIJJIIJJIIJIJJJJIJIJIIJIJI(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
	}

	public static int JIJJJJIIIJJJIJIIJIJJIIJJIIIIJJJJIJIJIJJJJIJIIJJ()
	{
		return 0;
	}

	public static void IJJJJIJJIIIIIJIJJJJJJIJJJIIJIIIJJIIJIIJJJIJIIJI(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
	}

	public static void IJIIJJJJIIJJJJIJJJJJIIJIIIIIJIIIIJJIJJJIIJIIJII(string JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ)
	{
	}

	public static void JJIJJJJIIIIIJJJIIJJJJIJIIJIIIJIJIIJIJJIIJIJJIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void IJIJJIJIJIJJJJJJJIIJIJIJIJJJIJIJIIIIJIIIIIJIIJJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JJIIJJJIJJJIJIJIIJIIJJJIJIIJIJJIIIIIIJJJIIJJIIJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ, int IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	public static void JJJIIIJIJIIJJJJJJIJJIJIJIIJJJJJIIIIJJIIJIJJIJJJ()
	{
	}

	public static void JJIIJJJJIIJIIIIIJJJIIIIJJJIJIJIIIJIJJIIJIIJIIIJ(JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII IIJIIIIJJIIJIIJIIIJIJJJJJIIJIIJIIJIIJJIJJJIIIIJ)
	{
	}

	private void Awake()
	{
	}

	public static void JJIIJJIJJJIIJIJIJJIIIJIJJIJJJIJJJJIIJIJIJIJIJJJ(int IIIJJJIJJIIJIJJIJIJIJJIIIJJIIIJIIJIJJJJIJIIIIJI)
	{
	}

	public static void IIJJJJJIJIIIJIJIIIJIIJIIJJIJJIIIIJJJJIJJJIJIIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void IJIJJIJIIIIJIIIIIIJIJJIIJIJIIIIJJIJJJIIIJIJJIJI(int[] IIIJIJJJIJJIJIIIJIIJJJIIIIIJIJIJIIIIIIIJJJIIIII)
	{
	}

	public static void JJIIJIJJJJIIJIJJJJJIIIJIIJIJIJJIJIIIIIIJJJJIIIJ(bool IJJJIIIIJJIIJJIJIJIJIJIIIIJIJIJIJIIIJJIJIJIIJIJ)
	{
	}

	public static void JJJJJJJJIJJJIIIJJIJIJJJIJJIJIIIIJIJIJIJJIJIIJJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JJIJIIJIJJIIIIJJIJJIIJJJIJIIIIJJJIJJJIIJIIJIJJI()
	{
	}

	public static void JIJIJIJJJIJIJIIIJIJIJIJIJIJJJJIIIJJIJIJJIJIJIIJ(int IIIJJJIJJIIJIJJIJIJIJJIIIJJIIIJIIJIJJJJIJIIIIJI)
	{
	}

	public static void JJIJJJJIIIIIJJJIIJJJJIJIIJIIIJIJIIJIJJIIJIJJIII(float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public static void JIJJIJIIIJIJJIJJIJJJJJIIIIIJIIJJIJIIIIJJJIJIJIJ(bool IJJJIIIIJJIIJJIJIJIJIJIIIIJIJIJIJIIIJJIJIJIIJIJ)
	{
	}

	public static void IIIJIJIJIJJJIJJJIJJIJJJJIIJIJJIJJIJJIJJJIIIJJJJ(int[] IIIJIJJJIJJIJIIIJIIJJJIIIIIJIJIJIIIIIIIJJJIIIII)
	{
	}

	public static void JJIIJJJIJIIIIIIIJJIIJJIIJIIJJIJIJIIIIJIJIJJJJJI(float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public static void IIIJIIIIJIIIIIIIJJIIJJJIIIIJJIIJIIJIIJJIJJJJJIJ(Vector2 JIJIJJJJJIIIJIJJIJIIJJIIJJIJJIJJIJJJIJJJIJIIJJJ, bool JJIIJJIIJJIJJIIJJJIIJIJJIIIIJIIJJIJJJJJJJJIIJJJ)
	{
	}

	public static void IIIIIJJJJJIJIIJIJJIJIJIIJJIJJJJIIJIIJIIIIJIIIIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JJIIJIIJJIJIIJJJJJJJJJIJJIJJIIIJIIJJJJJIIIIJJIJ(Rect IJJIIJIJJJJJJJJJIIJIIJJJIIJIIJIJJIIIJJIIIJJJIJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}
}
