using UnityEngine;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class mWeaponTexture : MonoBehaviour
{
	[JIIJIJJJIJJJJJJIIJIJIIIJIJIIJJJIJIJIIIIIJIIJJJJ]
	public int IJJIJJJIIJJJIIIJIJIJIJJIIIJJJIJIJJIIIIIJIIJIJJJ;

	public float JJJIIJIIJJJJJJJIJIIJIJIIJJJIJIJJJIJJIIIIJIJIIIJ;

	public bool IJJIJJJIIIIIIJJIJIJIJJJJIJJJJJIJIJJIIIJJIIJJJII;

	public UILabel IJIJIIJJJJIIJJIJJJJIIIJIIIJJIJIIJJIIIJJIIIIIIJI;

	private UISprite IIIIIIIJJJJIIJJIIJIIJIJIIJIIIIJJJIJIIIJJIJJIJIJ;

	private void IIIJJIJJJJJJJJIIJJIJJJIJJIIIIJIIIJJIIIIIIJJJJJJ()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void JJJIJJJJJIIJIJJJIJIIIIJJIJJJIJIIJJIIJIIJJJJIIJI()
	{
	}

	private void Start()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void IJIIIIIIIIJJIJIJIJJIIIJJIIJJJJJJJIJJIIIJJIJJIJJ()
	{
	}

	private void JJIIIIIIJIJIJIIJIJJIIIIJIJJIIJJIIJIIIJJIIJJIJIJ(JJIJIIJJIJIJJIIJIJJJIJJIIIIIIJIJJJJIJIIJIIIIJJJ IIIJIJJJIIJJIIIIJIJJIIIIJJIIJIJIJJIJIIJIIJIJJJI)
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private void JIJIIJIIIJJIJIIIIJIJIJIIJJJIIIIIIIIIJIIIJIJJJII(JJIJIIJJIJIJJIIJIJJJIJJIIIIIIJIJJJJIJIIJIIIIJJJ IIIJIJJJIIJJIIIIJIJJIIIIJJIIJIJIJJIJIIJIIJIJJJI)
	{
	}

	private void IJIJIIIJIIJIIJIJJIJIIIIIIIJJJJJIIJJJJJJJIIIIIJJ()
	{
	}

	private void IIIIIIIIIJIJIJJIJIIIJJIIJJJIIIIJIJIIJJIIIIIJIIJ(JJIJIIJJIJIJJIIJIJJJIJJIIIIIIJIJJJJIJIIJIIIIJJJ IIIJIJJJIIJJIIIIJIJJIIIIJJIIJIJIJJIJIIJIIJIJJJI)
	{
	}

	private void JJIIJIIJJJJIIIIJIJIJIIJJJJJIIIIIIJIIJIJIJJJJIJI()
	{
	}

	private void IJIJIJIJIIIJIJIJJIIJJIJIIJJIIJJIJJJIJIIJJJJJIII()
	{
	}

	private void OnEnable()
	{
	}

	private void JIJIIJJIIIIIJJIJJJIIIJJJJIIIJIIJJJJIIIJIJJIIJII(JJIJIIJJIJIJJIIJIJJJIJJIIIIIIJIJJJJIJIIJIIIIJJJ IIIJIJJJIIJJIIIIJIJJIIIIJJIIJIJIJJIJIIJIIJIJJJI)
	{
	}

	private void JJIJJJIIJIIJIIJJJJJIIIIIJIIJIIIJIIJIJIJJIJJIJIJ()
	{
	}
}
