using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class nBoxCollider : MonoBehaviour
{
	public JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ JJJJJJJJIJIJIIJJJIJIJJJJJJIIJIJIIJJJJJIIJIJIJII;

	public JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ IJJJJJJIJIIIJJIIIJIJIJJIJIIIJJIJJJIIJJJJJIIJIII;

	public PlayerSkinDamage JJIJIJIIIJIJJIIJJJJIJJJJIIIJIIJJIIJIJJIJJIJIJJJ;

	[HideInInspector]
	public float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ;

	private Transform JJIJIIJIIJJJJJIIIJIIIJJJIJJJIIIIJJIJJJIIIJJIIII;

	private JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ[] IIJJIIJJIIIIJIIJJJIIJIJIIJIJIJIJIJJIIJIIJIIIJJJ;

	private Vector3[] JJIJJJJIIJIIIIJJJJIIIIJIIJIIIIJJIIIIIIJIIJJIIJI;

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	public void JIIIIJJJIJIJJIJIIJIIIIIIJJJJIIJJJJJJIJIJJJIIIII()
	{
	}
	public Transform JIIJJIIIIIIJJJIIIIJJIIJIJJJIIIIJIJJJJIIIIJIJIIJ()
	{
		return null;
	}

	public void IIIJIIIIJJIIIJIJIIJIIIJJIIIIJJJIJIIIIJIJIJJJJJJ()
	{
	}
	public Transform IJIIIJIJIJIJJJJIIIIJJIJIIJJJIIJIJIJIJJJIIJJJJJI()
	{
		return null;
	}

	public void IIIIIIIJJIIJJIIIIJIJJJIJIJIJIIJJJIIIJJJJJJJJIJJ()
	{
	}
	public Transform IJIIJIJIJJJIIJIJIIJIIJIIJIIIJJJJJJJIJIJIIJIJJJJ()
	{
		return null;
	}

	public void IJIIIJIIJJJJJJIJJJIJIIJIJJJIIJIIIIIIIIIIJJIJJJI()
	{
	}

	public void IJIIIJJIJJJJJJJIJIIJIJJJJIIJIJJJJIJIIJIIIJJJIJJ()
	{
	}

	public bool IIIJIJJJJJIJJIIIIIJJJIJIJJIJJIJIIJIIIIIIJIJJIII(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
		return false;
	}

	public void IJJIJIJJJJJIIJIJJJJIJIIIIJJJIJIJJIIJIIIJJJJJIJI()
	{
	}

	public bool JIJIIJJJJJJIJIIJIJJIIIIJIIIJIJIJJIJJIJJIJJJIJJJ(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
		return false;
	}

	public bool IIIJIIJIJJIJIIIIIJJJJJJJIJIJJIIIIIJJJJJIIJJIIIJ(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
		return false;
	}
	public Transform JIJIJJJJJJJJIJIJIJIIJIJIIJJJIJIJJJIJIIIIIJIJJII()
	{
		return null;
	}

	public void JJIJIJJJIJJIJIJJIIIIJJIIIIJJJIJIIJIJJIJIIIIJJJJ()
	{
	}

	public bool JJIJIIIJIIIIJIIJIIIJIIJJJJIJJJJJIJIIIIJIJJJIJII(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
		return false;
	}

	public void IJIIJIIIJJIIIJJIIIIJJJIJIJIIIIIIJIJIIJJIJJIIJJJ()
	{
	}
	public Transform JJJJJIJJJIIIJJJJJIJJJIIIIIJJJJJIJJJJJIIIJJIIJIJ()
	{
		return null;
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}
	public Transform JIJIIJIJIIJJIJIJIIIIJIIIJIJJJJJIIIIJJJIIIIJJJIJ()
	{
		return null;
	}
	public Transform JJJIIJJIJJJJIJJIJJIIJIIJIJJJJIIJJJJJJJJIIJJJJJI()
	{
		return null;
	}
	public Transform JJJIIIIJJJIIJIJJIIJJIJJIIJJIIIIIIJJIJIJJIIJIJII()
	{
		return null;
	}
	public Transform IIIJJIJJJIIJJIIIJJJIJJIJJJIIIJIJIIIJIIIIIIIIIIJ()
	{
		return null;
	}
}
