using System.Runtime.CompilerServices;
using UnityEngine;

public class nBoxColliderBounds : MonoBehaviour
{
	public Vector3 JJJJJJJJIJIJIIJJJIJIJJJJJJIIJIJIIJJJJJIIJIJIJII;

	public Vector3 IJJJJJJIJIIIJJIIIJIJIJJIJIIIJJIJJJIIJJJJJIIJIII;

	public Renderer JJJJJJIJJIJIIIJJJIIIJJIJIJJJIIIIIIIJIJJJIIJJIJI;

	[HideInInspector]
	public float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ;

	public bool IJJJIIIJIJJJJJJJJIJJIIJIIJJIJJJJJIIJJIJIJJJIJJI;

	private Bounds JJIJIIJJJJJIJJJIIIIJIIIIIJIJIIIJIJIIJIIIIJJJJJJ;

	private bool IIJIJIIIIJJJJJJJIIJIJJIJJJJJIJJJIIJIIJJJIJIJIIJ;

	private Transform JJIJIIJIIJJJJJIIIJIIIJJJIJJJIIIIJJIJJJIIIJJIIII;

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	public bool JJIIJJIIJIIJJIIIIJIJJJJJJIJJIIJIIJJIJJJJIJJIJIJ(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
		return false;
	}

	private void Start()
	{
	}

	public bool IJJIIIJIJIIJIIJJIIIIIJJIIJIJIJIJJJJIJIIIJJIIIJI(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
		return false;
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	public bool JJIJJIIJIIIJJIJJIJJIJJIJIJJJJIIJJJJIJJJJIJIIJJJ(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
		return false;
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}
	public Transform IJIJJJIJIIIJIJIJIJJIIIJJJIJJIJIJJJJJJJJIJJIJIIJ()
	{
		return null;
	}

	public bool IIJJJJJJIJJIJJIIJIIJIIIJJJIJIIIIJJIJJJIJIJJJIJJ(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
		return false;
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}
	public Transform JJJIIIIJJJIIJIJJIIJJIJJIIJJIIIIIIJJIJIJJIIJIJII()
	{
		return null;
	}

	public bool IIIJIIJIJJIJIIIIIJJJJJJJIJIJJIIIIIJJJJJIIJJIIIJ(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
		return false;
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}
	public Transform JIIJJIIIIIIJJJIIIIJJIIJIJJJIIIIJIJJJJIIIIJIJIIJ()
	{
		return null;
	}

	public bool IIIJIJJJJJIJJIIIIIJJJIJIJJIJJIJIIJIIIIIIJIJJIII(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
		return false;
	}

	public bool JIJIIJJJJJIIJJIIIIIIIIIIIJIJIIJJIIIJJJIIIJIJJII(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
		return false;
	}

	public bool JIJJIJIIJIJJIIIIIJJIIIIJJIIJJIIJJIJIJIJIIJIJJJJ(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
		return false;
	}
}
