using System;
using UnityEngine;

public class nColliderContainer : MonoBehaviour
{
	[Serializable]
	public class JJJIJIIIIJIJJIJIIJIJJJJJJIJIJIIJJIIIJIJJIJIIIJJ
	{
		public nBoxColliderBounds IJIIIJJJJJJIJJIIJJJIJIJIJIIJJJIIIIIIJIJIJIJJIJJ;

		public nBoxCollider[] JJIJJIIJJIJJIJJJIJJIIIIIJIIIIJIIJIJIJJJJJJIIJIJ;
	}

	public static global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<nColliderContainer> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ;

	public static nColliderContainer JJIJJIIIJIJIJJIJJIJIIIJJJIIJJIIIJJJJJIJJIJJJIJI;

	public static nBoxCollider IJJJIJIIJJIJJJJIIIJIIIJJJJIJJIJJJIIJJIJJIJJIIJI;

	public nBoxColliderBounds IIIJIJJIJIJJIJIJIJIJJIJJJIJJJIIJIJJIJIJIJJIIJII;

	public JJJIJIIIIJIJJIJIIJIJJJJJJIJIJIIJJIIIJIJJIJIIIJJ[] JJIIJJJJIIIIIIIIIJIIJJIIIJIIIJJIJJIJJIJIJJIJIIJ;

	public nBoxColliderBounds IIJJIJJIIIIJIJJIJJJIJJJIIJJJIIJIJJJJJIJIJIJIIJJ;

	public PlayerSkin IJJIIJIJIJIIJJIIIJJIIJIIJIIIJJJIJJJIJIJJJJJIJII;

	private bool JJIJJIJIIJJIIIJIJIJJIIIJIJIIIJJIIJJJJJIIJIIJIII;

	private void IJJIIJJIIJJIIJJJJJJIIIJJJJJIJIIJIJIIJIIJIIIIJII()
	{
	}

	public static void IIJJJIJIIJIIIJIIJJJJJJIIJIJIJJJJJIJJJJJJJJIIJJI(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
	}

	private void OnEnable()
	{
	}

	private void IJIJJJJIIJIJJJIJJJIJIIIJIJIJJJIIJJJJIJIJIIIIIJI()
	{
	}

	public static void JJIJJIJIIIIJIIIJIJJIJIIJJJIIJJJIIJIIIIJJIJIJIIJ(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
	}

	private void IIIJJJIJIIIJJIJIIJJIIIIJIIIJJJIIIIIJIIIJJIIJJII()
	{
	}

	private static int IIJIIIIJIIJIIJIJJJIJJJJJJJIJJJIIIJIIJJIIIIJIIJI(nColliderContainer IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, nColliderContainer JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	private static int IJIJIJJJJIJJIJJIIJIIJIIJIJJIIJJJIIIIIJIIIIIJJII(nColliderContainer IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, nColliderContainer JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	public static void JIIIJIIJJJJJJJIIIIIJIIIIJJIJJIJJJJIJJIIJJJIJJIJ(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
	}

	private static bool JIJIJIIIIJJIIJJJIIJIIIIIIIJIJJIIJIJJJJJIIIJIIJJ(nColliderContainer IJIJJJIIIIJJJIJIIJIIIIIIIJJJIJIIIIIJIJIJJJJIIIJ, Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
		return false;
	}

	private void OnDisable()
	{
	}

	public static void JIJJJJJJJIJJIIJJIJIIJIJJJIJIJJIIJIJIJJJIIIIJJJJ(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
	}

	private void OnDestroy()
	{
	}

	private void Start()
	{
	}

	public static void IIJJIIIIIIJJIJIIIIJJIJJIIIIJIIJJJJJIJIIJJIJJIIJ(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
	}

	private void IIJIJIIIJJIIIIJIJJJJJIIJJJIIIJJJJJJJIJJIJJIJJII()
	{
	}

	public static void IIIJJIIJJIJIJJIJJIIJIJJJIIIJJJIIIIIIJJIJJJIIIJI(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
	}

	public static void JJJIIJIJJIIJJIIIIIJJJJIIIJIJJJIJJJJJIIIIIIIJIJI(Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
	}

	private static bool IJIJJIIJJIJJIJJJJJIJIIIJJIJJIIJJIJIIIIJIJIIIIJI(nColliderContainer IJIJJJIIIIJJJIJIIJIIIIIIIJJJIJIIIIIJIJIJJJJIIIJ, Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII, float JJIIIJIJJJIJJJJJJIJIJIJJJIIIIJIJJIIIIJJJJJJJIIJ)
	{
		return false;
	}
}
