using System.Collections.Generic;
using UnityEngine;

public class NetworkCullingHandler : MonoBehaviour, JIIIJJJIJIJJIJIJJIJJIJJJJJJJJIJIIIJJIIJJJJIJJJI
{
	private int JIIIIIIJIJJJJIJJIIJJIJIIIIJIIIJIIJIIJJJIIIIJIIJ;

	private CullArea JIIJJJIJIIIIIIJJIIIIJJJJIJIJIJIJIJIJIJIJIIIIIII;

	private List<byte> IJIIIJJIJIIJJIIJIJIIIIIJJJIIJJIJJIJIIIIIIIJJIJJ;

	private List<byte> IJJJJIJJIJJIJIIIIIIJJJIIIIJJIIIJIJIIJIIJIJIIJJJ;

	private PhotonView JJJIJJIJJJJJIIIIJJIJIIJIIIIJJJIJIIIIJIIIIJIJJIJ;

	private Vector3 JJIIIIIIIJJJJJIIIJIJJIIJJJJJIJJIIJIIIIIIJJJJIJI;

	private Vector3 JIIJIIJJIIIJJIJJJIJJJIIJIIJJJIJIJIJJJIJIIIIIIJI;

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void OnGUI()
	{
	}

	private void IJIIIJIJJIJIJIIJJJJIJIJIJIIJJJJIIIIJIJIJIJJJIII()
	{
	}

	private void JIJIIJJIIIIIIIJJIJIJIJJJIJJIJIIJJIJJJIJIIIJIIJJ()
	{
	}

	private void OnEnable()
	{
	}

	private void JJIJIIJJJJIIJIJIIJIJJJJJIIJIJIIIIJIJIIJIJIJJJJI()
	{
	}

	private bool JJJIJJIIIIIIJIJIIIJJIJIJJJJIIJIJIJIIJJIIIIIJIII()
	{
		return false;
	}

	private void Update()
	{
	}

	public void IIJIIIIIJIJIIIJIJIIJIIIIJJIIJJIJJIJJIJIJIJJIIIJ(JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ IJJJJIIJIIIIJJJIJIJJIIJIIIJIJIIIIIIJIIIIJIJIIJI)
	{
	}

	private void JJJIIJJIJIJJJJIIJJJJJIJJIIIJJJIJIJJIIIJIIJIIJII()
	{
	}

	private bool IJJIJIIIJIIJJIJIIJJIJJIJJJIIJIIJIIJIIIJJJJIIIJI()
	{
		return false;
	}

	private bool JIJIIJIIIIIIJJIIIJIJJJIIJIIJJJIIJIJIIIJJJJIJIJI()
	{
		return false;
	}

	private void IJJJJIIIJIIIJJIIIJJJIJJJJIJIJIIIIJJIJJIIJIIJIIJ()
	{
	}

	private void IIIIJIJIIIIJIIIIJJJJJJIJJJIJIIJIIJIJJIJIJIJIJJI()
	{
	}

	private void JJJJIJIJIIJJJJIIIIJJJIIIIJJIIIJJIJJIIJIIIIIIJIJ()
	{
	}

	private void Start()
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void JJIIJJJIIJIIJJIJIIIIIJIIJIJJJJJIIIJJIJJJIIIJIJJ()
	{
	}

	private void JIJJJJIIIJIIIIJIJJJJIIJJJIIJJIIJJJIIIIIIIJIIIJI()
	{
	}

	public void OnPhotonSerializeView(JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ IJJJJIIJIIIIJJJIJIJJIIJIIIJIJIIIIIIJIIIIJIJIIJI)
	{
	}
}
