using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class NGUIAtlas : ScriptableObject, IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII
{
	private enum JIIIJJIJIIIJIJIJJIJIJJJJJIIJJJIIJIIJIIIIIJJIJII
	{
		Pixels = 0,
		TexCoords = 1
	}

	[HideInInspector]
	[SerializeField]
	private Material material;

	[HideInInspector]
	[SerializeField]
	private List<IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ> mSprites;

	[HideInInspector]
	[SerializeField]
	private float mPixelSize;

	[HideInInspector]
	[SerializeField]
	private UnityEngine.Object mReplacement;

	[NonSerialized]
	private int mPMA;

	[NonSerialized]
	private Dictionary<string, int> mSpriteIndices;

	public Material IIJJJJJJIJJIIIJIIJJIJIIJJJIJIJJIIIIIJIIJJIJJJII
	{
		get
		{
			return spriteMaterial;
		}
		set
		{
			spriteMaterial = value;
		}
	}

	public List<IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ> JJJIIIIJIIJJJJJIIIJIIIJJIIJJIIJIJJIJIJIIIIJJJJJ
	{
		get
		{
			return spriteList;
		}
		set
		{
			spriteList = value;
		}
	}

	public Texture IIJIJIIIJJJIIIJJIIJJIJIIIIIIJJJIIJIJIJJIIIJIIIJ => texture;

	public float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII
	{
		get
		{
			return pixelSize;
		}
		set
		{
			pixelSize = value;
		}
	}

	public bool JIJJJIIJIIIJIJIJIIJIIIIJJIJIJIJIJIJIJJIJJJJIIJI => premultipliedAlpha;

	public IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JJJJJJIJJIJJJIIJIIIIJIJJJJJJJIJIJIJIJJIJIIIJJII
	{
		get
		{
			return replacement;
		}
		set
		{
			replacement = value;
		}
	}

			public Material spriteMaterial
	{
		get { return (mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII) != null ? (mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII).spriteMaterial : material; }
		set { if ((mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII) != null) (mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII).spriteMaterial = value; else material = value; }
	}

			public bool premultipliedAlpha
	{
		get
		{
			if ((mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII) != null) return (mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII).premultipliedAlpha;
			return material != null && material.shader != null && material.shader.name.Contains("Premultiplied");
		}
	}

			public List<IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ> spriteList
	{
		get { return (mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII) != null ? (mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII).spriteList : (mSprites ?? (mSprites = new List<IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ>())); }
		set { if ((mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII) != null) (mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII).spriteList = value; else mSprites = value; }
	}

			public Texture texture => (mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII) != null ? (mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII).texture : (material != null ? material.mainTexture : null);

			public float pixelSize
	{
		get { return (mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII) != null ? (mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII).pixelSize : mPixelSize; }
		set { if ((mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII) != null) (mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII).pixelSize = value; else mPixelSize = Mathf.Clamp(value, 0.25f, 4f); }
	}

			public IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII replacement
	{
		get { return mReplacement as IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII; }
		set { mReplacement = value as UnityEngine.Object; }
	}

	public global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<string> IIIIIIIIIJIJJJIJIJIJJJJIIIIJJIJJIJJIJJJJJJIIJIJ()
	{
		return null;
	}

	public global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<string> JIJJJIJJIJIJIIJJJIIJJIJIIJIJIIIIIIIJIIJJJJIJIJJ()
	{
		return null;
	}

	public IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ JJJJIJJIIIIIJIJJIJJJJIJIIJJJJIJJIJIIIIJIJIJIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	if (string.IsNullOrEmpty(JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)) return null;
	        foreach (IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ item in spriteList)
	        {
	            if (item != null && item.JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ == JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ) return item;
	        }
	        return null;
	}
	public IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JIIJJIIJIJJJJIJJIIIJIIIJIJIJJJJJIJIIJJIJJJJIJJI()
	{
		return null;
	}
	public void IJIJIJJIIJJIIJJIJIIIJJIIIJIJJIJJJJIIJIIIJIIIIJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JJIIJJJJJJJJJIJIIIIIJJJIJIIJIJJJJJJJJIIIIJIJJII()
	{
		return null;
	}

	public global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<string> IJIIJJJIJJJIJJJJIJIJIIIJIJJIIIIJIIIIIJIIIJIIJII(string IIJJJIIIIIIIJJIIIJJJJJJIIJIIIJJIIIIIIJIJJJJJIJI)
	{
		return null;
	}

	public bool IIJJIIIIIJJJIJJJJJIIJJIJIIJIJIIIJIJJJJJIJJJJIJJ(IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JJJIIIJJJIIIIIJIJIJJIIIJIIIIIIIJIIIJIIIIIIJJJJI)
	{
		return false;
	}

	public void IIJIIIJIJIJJJJIJJIIJIIJJIIJJJJJIIIIIIJIJIJIIIIJ()
	{
	}

	public IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ JJIJIJIJJJJJIJIIIJJIIJIIIIIJIIJJJIIJIJIJJJIJIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
		return null;
	}
	public IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JIJIIIJJJJJIJIIJJIJJJJJJJIIIJJJJJIIIJJJIIIIJJIJ()
	{
		return null;
	}
	public void JJJIIJJJIIIIJIIIJJJJIIJJIJJIIJJJIIJIJJJIIIIIJIJ(Material JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<string> IJIIIIIJIIJIIIIIJIJIIIJIJJIJIJIJIJJIIIJJIJIIIIJ(string IIJJJIIIIIIIJJIIIJJJJJJIIJIIIJJIIIIIIJIJJJJJIJI)
	{
		return null;
	}

	public void IIJJJJJIIJJIJJIIIIJIIIJIIJJIIIJJJJJIIJIJJIIIJIJ()
	{
	}
	public void IJJJJJIJJIJIIJIIIIIIIIJJIIJIJJIIIIIIIJJIIIJIJII(List<IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void IIJJIJJIJJIIIIJJJIJJJIJIJIJIIJIJJJJIIJIJJIJJIJJ(Material JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void JIIIIIIJIIJIIIJJIJIIIJIJIIIIJJJJJIIJIJIJIIJIIJI(IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIJIIJJJJIIJJJIJJJJIIIJJJIJJJIIIIJIIIJJJJIIJJJ()
	{
	}
	public void IIIJIIIIIIJJIJIIJJJIIJJJIJIJJIIIJIIIIJJIIJJIIII(IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void JJIJJJIIIJJIJJIJJJIIJJIIJIJJIIJJJJJIIIJIJJJIIIJ(Material JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<string> JIJIJJJIIJJIJJIJIJIIIIJJJIIJIIJJJIIIIIJJIJJIIIJ()
	{
		return null;
	}

	public void IJIJIJJIIIIJIJIIIJJIIIIJJIJJJJJIJJJIJIJJJJJJJJJ()
	{
	}

	public global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<string> JJJJIJJJIIIIIJIIIIIJJIIJJIIJJJJJIIJJJIIIJJJJJJI()
	{
		return null;
	}
	public List<IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ> JJJJJIIIIJJIJIIIJIIJJJJJJJJIJJJIJJJJIJJJJJJJJJJ()
	{
		return null;
	}

	public global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<string> JIJJJIJJIJIJIIJJJIIJJIJIIJIJIIIIIIIJIIJJJJIJIJJ(string IIJJJIIIIIIIJJIIIJJJJJJIIJIIIJJIIIIIIJIJJJJJIJI)
	{
		return null;
	}
	public void JIJJIIJIIJIJIJIIJJJJJIJJIJJJIJJJIJJIJIIIIIIJJIJ(List<IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
}
