using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class NGUIDebug : MonoBehaviour
{
	private static bool IJJIIJIIJIIJJJJJJJIIIIJIIJIJIIJIJJIIJIJIJJIIJJJ;

	private static List<string> JIIJJIJIIJJIIIJJJJIIJJJIJJJIIJJJJIJIJJIIJJJJJJI;

	private static NGUIDebug IIIJJIIIJJIJIJIIJJIIIJIJJJIIJIIIJJJIJJJIJJIIJIJ;

	public static bool JIJIIJJIIJIIJJIIJJJJIJIIJJJIJIJIJJJJJJIIIJJJJII
	{
		get
		{
			return JJIIIIJJJJIIIIIIIIIJIJJJIIJIIIJIIJJIJJJJIIIJJJJ();
		}
		set
		{
			IIJIJIJIIIIIIJIIIJIJJIIJIJJJIIIIJJJIJIJIIJIJIJJ(value);
		}
	}

	public static void IIJIJIJIIJIIJJIJIIIJJJIJIJIIJIIJIJIIJJJIJJJJIJJ()
	{
	}

	public static void IJIJJJIIIJJJIIIIJJIIJIIJIJJIJIIJJIJJJJJIJJIIIJI(object[] IIJJIIIIIIIIIIJIIJJIIIIIIIJIJJIIIIJIIJJIJIJJIII)
	{
	}

	private void IIIIJIJJJJJJIIJIJJJIIJJJJIJIJIIJIIJJJJJJIIIIIJI()
	{
	}

	public static void JJIIJJIJJIJJIIIJIIJJIJIJIJIIIIIIIIIIJIJIIJIIJII(object[] IIJJIIIIIIIIIIJIIJJIIIIIIIJIJJIIIIJIIJJIJIJJIII)
	{
	}

	public static void JIIJJJIJIIIIJIJJJJIJIIJIJJIIJIIIIIIIIJIIIIIIJII()
	{
	}
	public static void IJJIIJJIIIIJJIIJIIJIIIJJJJJIJIJIJIJIIJJJIIJJJII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static bool JJIIIIJJJJIIIIIIIIIJIJJJIIJIIIJIIJJIJJJJIIIJJJJ()
	{
		return false;
	}

	public static void IIJIJIJIIIIIIJIIIJIJJIIJIJJJIIIIJJJIJIJIIJIJIJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JIJIIIIJJJJJJJIIIJJIIJJIIJIJJIIJJJJJIIJJJJIIJII(string IJJJIJJJIJJIIJJIJIJJJIIIJIJJJJJJIIJIJIIIJIJIJJI)
	{
	}

	private void IJIJIJIJIJJJIIJJIIIJIJIIJIJJIIJIIJJIJIIIJJIJIJJ()
	{
	}

	public static void IIJJIJJIIIJJJIIIIJJIJIJIIJJIIJJIJIIIIJIIJIIIIIJ(Bounds JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
	}

	public static void JIJIJJIIJJJIJIJIIIIJJIJJJJJIJJIIIJIJJJIIIIJIIII(Bounds JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
	}

	private static void JJIJJIJIIJJIJJIJIJJIJIIJJIIIJIIIJIIJIIIJIIIIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}
	public static bool JIIJIJJJJJIJIJIJIIJJIIJJIIIIIIIJIIJIIIIIIJIJIII()
	{
		return false;
	}

	private void IJJIIJJJIJJIJIJIJIIIIIIIJJJJIJIJJIJJIIJJIIIIIJI()
	{
	}

	private static void IIJJJJIIJJJJIIJIIIJJJIJIIJJJJIJJJJJIIJIIJIIJJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void JJJJJIIJJJJJJJJJJJJIJIJJJIIIJIIJJJIIJIJJIJIJIJI(object[] IIJJIIIIIIIIIIJIIJJIIIIIIIJIJJIIIIJIIJJIJIJJIII)
	{
	}
	public static bool IIIJIIIIJJJJJJJJIJJIJJIIJJIJIIJJJJJIJIJJIJIJIII()
	{
		return false;
	}

	public static void JJJIJJJIJIJIIJJJJJJIIIIJIJJIIIJJJIJIJJIJIJJIIJI()
	{
	}

	public static void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}

	public static void IJIIJIIIIJIJIIIIIIJIJJJIIIJJIIIIIIJIJJIIJIJIJII(Bounds JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
	}

	private static void IIJIIIIJIJIJJJJJJJJJJJJJJIIIIIIIJIJIJIJJJIJJJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private static void JIIJIJIIIJIJJJIIIIIIJJIIJJJIIJIJIIJJIIIIJIJIJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void JIJIJJJIJIJJIIJJIJJJIIJIIJIJJIIIIIIIJIIJJJJJIIJ()
	{
	}

	public static void IJIIIJJJIJJIIJJIIJJIIIJIIJJIIJJJIIJIIIJJIJIJIJI(Bounds JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
	}

	private void IJJIJJJJIIIJJIJJJJIJIJIJIIIJJIIIJIIJIJIIIIIJIJI()
	{
	}

	private void OnGUI()
	{
	}

	public static void JIJIIIIJJJJJJJIIIJJIIJJIIJIJJIIJJJJJIIJJJJIIJII(params object[] IIJJIIIIIIIIIIJIIJJIIIIIIIJIJJIIIIJIIJJIJIJJIII)
	{
	}

	public static void JIJJIJJIJJJJIJIJIJJIJIIIIJJJIIJJJIIIIJJJIJJJJII()
	{
	}
}
