using UnityEngine;
using UnityEngine.SceneManagement;

[IIIJJIJIIIIJIJJJJIJIIIJIIJJIJJJIIIJJJIIIJJJJJJI]
public class nValue : MonoBehaviour
{
	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int0;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int1;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int2;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int3;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int4;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int5;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int6;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int7;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int8;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int9;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int10;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int12;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int15;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int17;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int20;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int23;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int30;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int32;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int35;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int40;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int50;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int55;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int60;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int80;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int90;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int100;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int120;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int150;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int200;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int300;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int360;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int500;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int900;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int1000;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int10000;

	public static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI int15000;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float0;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float1;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float01;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float02;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float03;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float04;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float05;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float07;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float08;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float12;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float15;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float45;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float60;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float149;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float001;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float005;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float008;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float002;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float013;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float015;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float016;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float017;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float018;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float019;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float025;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float0001;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float0002;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float0004;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float0025;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float0125;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float0375;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float0745;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float00001;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float00016;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float000001;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII float0000001;

	public static IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII gravity;

	private static string IJJIIJJIIIJIIJJIIJIIIIJIJJJJIJIJJJIJJIJIJJIJJIJ;

	private static nValue JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void IIIJJIJIIJIIJIJJIIIJJIJJJIJJJIJIIJIIJIJJIJJJIJI(Scene JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ, LoadSceneMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
	}

	private void IJJIIJIIIJIIIIJIJJJJJJJIJJIJIIJJIIJIJJIJJIIIJJJ(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}

	private void JIJIIJJJJIJIIIJJJJJIIIIIJIJIIIIIJJIJJIIIJIJJIJI(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}

	private void OnApplicationFocus(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}

	private void IJIJJIIJIIIIJJIJJIIIJIJJIJIIJJJIIIJIIIIIJIJJJIJ()
	{
	}

	private void IJIJIIJJIJIJIIIJIJJIJIIJIIIJJIIJIJIIIJJIIJJJIII(Scene JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ, LoadSceneMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
	}

	private void IIJJJIIIJJIJJIJIIJIIJJIIIJJJIIJJIJIJIIJJJIJJJJJ()
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void Start()
	{
	}

	private void IIIJJIJIIIIJIJIJJJJJIIJJIJIJIIIIIJJJIJIJJIJIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	private void JJJIJJIIJIIIJJIJIJIJJIIIIIJJIIJIJIIJJIJJJIJIIJJ()
	{
	}

	private void IJIIIIJIJIJIJJJIIIJJJJIJIJJIJJJIIJJIIIIJJIJIJII()
	{
	}

	private void JJIIJJJIIJIJIIIIJJIIJIIIJJIJIJIJIJIIIJJIIIJJJIJ(Scene JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ, LoadSceneMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
	}

	private void IIIIIJIJIJJJJIJIJJIJJJIIJJJJIIJJIIIJJJJIIJJJJJI(bool IIIJIJIIIIIJIIJIJIJIJJIJIJJJJJJIJIJIIIJIIJIIJJJ)
	{
	}

	private void IIJIIJJIJJJJJIJJJJIIJIIIIIIIJIJIJIIJJIJJIJJJJJJ(Scene JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ, LoadSceneMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
	{
	}

	private void JJIJJJJIJIIJJJIJJIIIIIIIIJIJIIJJJJJJIIJJIJJIJJI()
	{
	}

	private void JJIJIJIIIIIJIIJIIIJJJJJJJJIJIJIIJJJIJIJIIIIJIIJ()
	{
	}
}
