using System.Runtime.CompilerServices;
using ExitGames.Client.Photon;
using Photon;

public class oTDMMode : MonoBehaviour
{
	private sealed class JJJJJIJJIJJJIIIJIIJJIIIIIIJIIIIJJIIIIJJIJIJIJJJ
	{
		public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII;

		internal void JJJJJJJJIJIJIIIJIJIJJIIJIJJJIIIJIJJJIJJIJJJIJII()
		{
		}

		internal void IJIJJIIJIJIIIJIIIJIIIJIJIIIJJJIJIIIJIJIIIJJJJIJ()
		{
		}

		internal void IJIJJIJJIJJIJIJJJJIIIIIJJJIJJIJJIJIIIJIIIIJIIII()
		{
		}

		internal void JIJIJJJJJJIJJIIIIIIJJIIJJIJIIIIJJJJIJJJJJIJJJIJ()
		{
		}

		internal void JIJIJIIIJJIIJIIJJIIJJJIJIJIJIIIIJIIJIIJJJIIJIIJ()
		{
		}

		internal void IIJIJIIIIIIJIIJIJJIJIIIJIJIIJIIIIIIJIIJIIIIIIJJ()
		{
		}

		internal void IIJJJIIJIJJIIIIJJIIIJIIIJIIJJJIJJIJJJJJIJJIIIJI()
		{
		}

		internal void IIJJJJIJIJIJIJJJJIJJIIJJJJJJIJJIIIIIJIIIIIJJIII()
		{
		}

		internal void IJIIIIJIJIIJIIJJJJIIIJJJIIJIIIJIIJJIIJIJIIIIIJJ()
		{
		}

		internal void IJJJJIIIIIIIIJJJIIIJJJJJIJJIIJIJIIJIIIIJIJIIJIJ()
		{
		}

		internal void JIIIIJIIJIJJJIIJIIJIJIIJIIIIIJIIJIJIJJIIIJIIIII()
		{
		}

		internal void IJJJJJJIIIJIIJIJJJIJJIJJIIJIJIJIJJJIIIIJJJIIIII()
		{
		}

		internal void JIJIIIIIJIJIJJIIJIIJIJIIJJIIJJJJJIJIIJJIIIIJIIJ()
		{
		}
	}

	private float JIIJJIJJJIIIIIIJIJIIIJIIJJIIJIIIIIIIJJIIJJIIJJI;

	private void JJJIJJJIJIJJJJIJJJJIIIIJJIIIJJJIJJJIIJJIJJIIJII()
	{
	}

	private void IJIIJJJIJIJIJIIJIIJJJJIJJJIIIJIIIJIJIIJIJJJIIIJ()
	{
	}

	private void Start()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void JJIIJIJJIIJJIIJIJIJIIJJJIJJJJJIIJJIJJIJIIIJJIJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void Awake()
	{
	}

	private void IJIJIJJIJIJIJJJIJIJJJIIJIJJJIIJJIIJIJJIJIIIJIII()
	{
	}

	private void IIIJIJIJJJJJJIIJIJJJJIJJIJJJIIJJIIJJJJIJJJIJIII()
	{
	}

	private void IIJJIIIIJIIJJJJJIJIIIJJIJJJJIIIIIIIIIJIJIIIIIII()
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void JJIIJJIJIJJIJJIJJJIJJJIIJJIIIIIJJJJIIIIJJJJIJIJ()
	{
	}

	private void IJJJIIIJIJIJIJJJIIIIJJIIJIJJIJJIIJJJIIJJJIJIJII()
	{
	}

	private void JJIJJJIJJIJJJJIJJIJJJJJIJIIJJIIIIJIJJIIIJJIIJJI()
	{
	}

	private void IIJIIJJIJJIIIIJJIJIIJJJJIJJIJIJIJJJJIIJJJIJIIIJ()
	{
	}

	private void OnEnable()
	{
	}

	private void IIIIIJJJJJIJJIIJIIIJJJJJIIJIJIIJIIIJJJJJIJJIJJI()
	{
	}

	[CompilerGenerated]
	private void IIIJIJIJIJJIJJIJJIJIIJJJIJJJJJJIJJIJJIJIIJJJJJJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJIIIIJJIJJIJJJIIIIIJJJJJIIIJJIIJIIJJJIJIJJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIJJJJJJJJIIIJIIIIJJIIJIIIJIJIJJIJIJJIIJIJJJIJ()
	{
	}

	private void JJIJIIIIJJJIJJIJIIIIIJJJIIJJJJIJJJIJJIIIJJIJIJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void IJJJJJJIJJIIIIJIJIJJJIIIJJIIIIJJIJIIJIIIIJJJJIJ()
	{
	}

	private void JJJJJIJJJJIIJIIJIJIIIJIJIIIJIJJJJIIJJIJIIIIIIII()
	{
	}

	private void JIJIIJJIIJIJIIJJJJIIIIIJIIIIIIIIJIIJIJJIIJJIJIJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIJJIIIIIJJJJJIJIJJIIIIIIIJJIJJJJJIJIIIJIJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnDisable()
	{
	}

	[CompilerGenerated]
	private void IIIJJJJIIIIIJIJJIJJIIIJJIIJJJIIJIIIJJIIIIIIJIII()
	{
	}

	[CompilerGenerated]
	private void JJIJJJJJIJJJJIIJJJIJIIJJJIIIJJJIIIIJJJJJIJJIIJI()
	{
	}

	private void IIIIIIIIJIJIIJJJIIJIIIIJIJIJIIIJIIIJIIJJJIIIIJJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJJJJJIIJIJIJIIIJIIIJJIJJIJIJJIIJIJIIIJJIIII(float JJIJJIJJJIJIIIIIJJJIIIIJJIJJJJIIJIIIIIIIJIIJJIJ)
	{
	}

	private void IJJIIIIJJJIIJJIJIJIIJIJIIIIIJIIJIJIIJJJJIIIJJJJ(Hashtable IIJIJJJJJIIJJIIIIJJIIIJJJIIJIJIJIIJIIJJJJIIIJIJ)
	{
	}

	[CompilerGenerated]
	private void JIIIJIJJJJJJJIIIIIJJIJJIJJJJJJJJJJJJJJJIJIJIIJI()
	{
	}

	public void IIJJJJIIJIJIJIJJIJJIJJJJIIJJJJJJIJJIIJIJIIIIJIJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	public void JIJIJJJIIJJIJJJIIIIIJIIIJIJIIIIIJIJJJIIJJJIJJII(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void JJJIIIIJIIJJIIJIIIJJJIIJIIIIIJIJJIJIIIIJIJJIIJJ()
	{
	}

	private void OnPhotonCustomRoomPropertiesChanged(Hashtable IIJIJJJJJIIJJIIIIJJIIIJJJIIJIJIJIIJIIJJJJIIIJIJ)
	{
	}

	private void JIJJIIIJJJJIJIIJJJIJJIJIIJIJIIIIIIIIJJIIIIIIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJIIJJJIIJJIIJIJIIIJJJIJJIIIJIJIIJIIIIJIJIJIIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJIJIJJIIJIIIJIIJIJJIJJJIJIJJIJIJIJIJIIJJJIIIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIIIJIIIJJJJJJIJIIIIJJJJIIJIIIJJIJIJIIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}
}
