using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using UnityEngine;

public class PaintManager : MonoBehaviour
{
	private sealed class JJIJJIJIIIJJJIIJIJIJJIJIIIIJIJIJJJIIIIJIJIIJJJJ : IEnumerator<object>, IEnumerator, IDisposable
	{
		private int IJJJJJJJJIIJIIIIIJIIJJJIJJIIJIJJJJJIJJJJJIIIIII;

		private object IJJJJJIIIJJIIIIIIJIIIJIJJJIJIJIIJJIJIIIJJIIIJIJ;

		public byte[] JIIIJJIJIJIJJJIIJIJJJJJIJIJIIIIJIIIIJJIIJIJJIIJ;

		private int IIIJJJJIIJIJJIJIIJIIIJIIIIIJIJIJJIIJJIIJIIIJJIJ;

		private int IJJIJJJIJIIIIJJIIJIJJJJJJJJJIJJIIJIJIJJIJJJJJIJ;

		private int JIJIJJJIIJIIIIJJIIJJJJIJIJJIIJIIIJIJJJIJJJIIIJJ;

		object IEnumerator<object>.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		object IEnumerator.Current
		{
			[DebuggerHidden]
			get
			{
				return null;
			}
		}

		private bool MoveNext()
		{
			return false;
		}

		bool IEnumerator.MoveNext()
		{
			//ILSpy generated this explicit interface implementation from .override directive in MoveNext
			return this.MoveNext();
		}

		private void JJJJJIJJIIJJIIIJJJJJJIIIJIIJJJJJJIIJIIIJJJJIJJI()
		{
		}

		private bool IIJJJIJJIJIJJIJIIJJIJIJJJJIIIIIIIJIJIJIIJIJIJIJ()
		{
			return false;
		}

		private void IIJIJJIIIIJJIJIJIJIJIJJIJJIIIJJJIJIIJIIJJJJJIII()
		{
		}

		private void JIJIIJIJJJJJJIJIIIIIIJJIIIIIIJIJJIJIIJJIJIJIJJI()
		{
		}
		private object JIJJIIIIJIIJJIIIJIJJIIIJIJIIIIIJJJJIJJIJIIJJIIJ()
		{
			return null;
		}

		private void JJIJIIIIJJIJJJJJJJIJJIJIIJIJIJIIIIJJIIIJJIJIIJI()
		{
		}
		private object JIIJIJJJIIJIIJJJJIIIJJIIIIJJIJIJIJJIIJIJIJJIIII()
		{
			return null;
		}

		[DebuggerHidden]
		void IDisposable.Dispose()
		{
		}
		private object IIJIIJJIIJIJJIIJJJIJIIJIIJIIIJIIJIIJJJIJJIJJJJI()
		{
			return null;
		}
		private object JJJJJIIJJIIIIIIIIIIIJIIIIIJJJIIIIJIIJJJJIJJIJJJ()
		{
			return null;
		}

		private bool JJIIIJJJJIIIJJJJIJIJJIIJIJJJIJJIIJIJJJIIIJJJIIJ()
		{
			return false;
		}
		private object IJJIJJJJIIIJJIIJIIIIJIJJIIIJIIJIJIJIJIIIIJIIIJJ()
		{
			return null;
		}
		private object IJJJIIJIJJJJIIIIIJJIIIIJJJIJIJIIJIIJIIJIIJIIJJJ()
		{
			return null;
		}

		[DebuggerHidden]
		void IEnumerator.Reset()
		{
		}
		private object IIIIIJJIIJJIJJJJJIJJJIJJIIIJJJJJIJIIIJJJIJIIIII()
		{
			return null;
		}

		private bool JIIIIJIJIJJJIJJIJIJIJIJIIIJIJIIIIJJIJJJJJIJIJII()
		{
			return false;
		}

		[DebuggerHidden]
		public JJIJJIJIIIJJJIIJIJIJJIJIIIIJIJIJJJIIIIJIJIIJJJJ(int IJJJJJJJJIIJIIIIIJIIJJJIJJIIJIJJJJJIJJJJJIIIIII)
		{
		}

		private void IJJJIIIIJIJJIJJIIIJJJIJJJIJJJIJJJJIJJJJJIJJIJIJ()
		{
		}

		private void JJIJIIJIJIIIJIJIJJJIJIJJJJIIJIJIJIJJIJJJIJJIIII()
		{
		}
	}

	public GameObject IIIJIIIJJIIJJJIJJJIIIIJJIJJJJJJIIIJJJIJJIIJIIII;

	public int IIJJIJIIJIJJJJIJJJIJJIIIJJJIIIIJJIIJIJIJIJIIJIJ;

	public bool IIJIJJJIIJJJIJJJIIJIJIJJIIIIJIJIJJJIJIIIIJIIIJJ;

	public Color32[] IIJJJJJJJIJIIIJIJJIIIIIJJJIJIJIIJIIIJJJIJIIIIII;

	public List<PaintObject> IIJIJIIIIJIJJJIIIIJJJJIJJJJIIJIJJIIJJJIJJIIIJIJ;

	private int JJIIIJJIJIJJIJIIJIJIIJJIIJJJJIJJIIIIJIIIIIIJJIJ;

	private static PaintManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void JJIIIJIIJIIIJJJJIIJIJJJJIIIIIIIIIJJJJIJJJJJIJII(int IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ)
	{
	}

	private IEnumerator JIIIIIIJIJIIIIIJIIIIJJJIIIJJIJIIIJIJJIIIJIJJJII(byte[] JIIIJJIJIJIJJJIIJIJJJJJIJIJIIIIJIIIIJJIIJIJJIIJ)
	{
		return null;
	}

	public static void JJJJJJJIIJIJIJIIIJJIIIJIIJIIIJIIIIJIIIJIIJJJJJJ(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII, int IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ)
	{
	}

	public static void IJIJJIJJJIJJJJIJIJIJIIIJIIJJIJJIJIJIIIIJIJIJIII(int IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ)
	{
	}

	public static void JIJJJJIIJJIIJJIIJIJIIIIIIIJIIIJIJIJIIIJJJJJJIJI(int IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ)
	{
	}

	private void IIIIJJJIIJJJJJJIIIJIJIJIIJJIJJIJJIJIJIJJJJIJIIJ(RaycastHit IIJIJIJJJIJIJJIJIJIIJJIJIJIJJJIJIJJJJJJJJJJJIJJ)
	{
	}

	public static void IJIJIIIJJJIJJJJIJJJIJIIJJJJJJIJIIJJJIIIIIJJJIIJ(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	public static Color32 IIJIJIJIJIIIIIIIIJJJIJJJIJIIIIJJJJIIJIJJJIJJJII(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return default;
	}

	public static void IJJJJIJIJIJIIJJJJJIIJJJJJJIJIJIIJIIJJJJJJJJJIII(int IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ)
	{
	}

	private void JJJJIIJJIIIJIJJIIIJIJIJJIJIJIJIJJIIJJJJIIIIJJJJ()
	{
	}

	private void Awake()
	{
	}

	private void IIIIJIJIIJJJJJIIIJIIJJIIJJJJJJIJJJIJJIJIIIIJIJJ(RaycastHit IIJIJIJJJIJIJJIJIJIIJJIJIJIJJJIJIJJJJJJJJJJJIJJ)
	{
	}

	public static Color32 JIIJJIJJJIJIIIJJIJIIIIJJIIIJIJIJIJJJJIIJJJIIJIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return default;
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	public static void JIIJIIIIIIJIJJJJIIIJJIJJIJIJIIJJIIIIJJJIJIIJIJJ()
	{
	}

	private IEnumerator IIIIJIIIIJIJJJJJJIJJJJJIIIJJJJJJIJJJJJJJIJJIIII(byte[] JIIIJJIJIJIJJJIIJIJJJJJIJIJIIIIJIIIIJJIIJIJJIIJ)
	{
		return null;
	}

	public static void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}

	private void Start()
	{
	}

	public static void JJJIIIJIJIIIIIIJJIJIIJJJJJIIIJJIIIJJJJJJIJIJIJI(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	public static void JJIIJIJJIJJIJJJIJJIJJIIJIJIIJJIIJJJIIJIJJJIIJIJ(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	public static Color32 IIJIIIIJIJIJJJJIJIJIJJJIIJJIIJJJJJIIIIIIIJIJJIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return default;
	}

	private IEnumerator JIJJIIIJJIIJIIJJJIJIJJIIIIIIIJIIJJJJIJIIJIJJJIJ(byte[] JIIIJJIJIJIJJJIIJIJJJJJIJIJIIIIJIIIIJJIIJIJJIIJ)
	{
		return null;
	}

	public static void JJJIJJIIJIJIJIJJJIIJJJJJIJIIIJIIJIJJIJJJIJIIJII(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	private IEnumerator JJIIIJJJJJIJIIJJJJJIJJIIJIJJIJIIJJIIJIIIJJJJJJI(byte[] JIIIJJIJIJIJJJIIJIJJJJJIJIJIIIIJIIIIJJIIJIJJIIJ)
	{
		return null;
	}

	public static Color32 IIIJIIIIIIJJJIIIIJIJJJJJIJIJJIIIIJIJIIJIIJJIIII(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return default;
	}

	public static void JJJIJJIIJIJIJIJJJIIJJJJJIJIIIJIIJIJJIJJJIJIIJII(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, int JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII, int IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ)
	{
	}
}
