using UnityEngine;

public class PhotonStatsGui : MonoBehaviour
{
	public bool IJJJJJJJIJJIIJIJIIJIJIIIIIIIIJJIIIJIIIIIIJJJJII;

	public bool JIJIIJJIJJJIJJIIIJIJIJJJJIIJIIJJIJIIIIIIJJJJIII;

	public bool JJJIIIIJIIJIIIJJJJIIJJIIJIJJIJJIJJIJIJIJJIIIJII;

	public bool IJJIJJIIIIJIIJJJIIIIIIJJJIJIIIJJJJJJJIJIJIIJIIJ;

	public bool JJJIJIJJJJIIIJJJJIJIIIIIIJJIJIIJJJJJIIJIIIIIIJI;

	public Rect IIIIJIIIJIJJJIIJJJJJJJIJIJJIIIJIIJJIJIJIIIJJJJI;

	public int IJIJJJIJIJJJIJIJJIJJJIIJJIJIIIIJIJJIJJJJIIIIIJI;

	public void Update()
	{
	}

	public void OnGUI()
	{
	}

	public void IIIJJIJIJIJJJJJIJIJJIIJJIJIJIIJJIJJIJJJJJIJIJII()
	{
	}

	public void JJIJIIJJJJIIJIJIIJIJJJJJIIJIJIIIIJIJIIJIJIJJJJI()
	{
	}

	public void Start()
	{
	}

	public void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	public void JIIJJIIJIIIIIJIIIIJJIIJJJIIJIJIJJIIIIIIJJIJJIII()
	{
	}

	public void JJIJJJIIJIJIJIJIJJJJJIIJIJIIIIJJIIIJIIJJJJJIJIJ()
	{
	}

	public void IIIIIJIIJJIIIIJJIJIJIIIJIIJIIIJJIIJIJJJIJIIJIIJ()
	{
	}

	public void JJIJIIJIJJIIJJJIIIIJJIIIIIIJJIIJIIIJIJJJIJIJIJJ(int IJJIJIJIIIJJJJIIJIIIIJJJJIJIJIIJIJIIIIIJIJJIIJI)
	{
	}

	public void IIIIJIJJJJJJIIJIJJJIIJJJJIJIJIIJIIJJJJJJIIIIIJI()
	{
	}

	public void IJJIJJJJIIIJJIJJJJIJIJIJIIIJJIIIJIIJIJIIIIIJIJI()
	{
	}

	public void IIIJJJJJIIJJJJIIJJJIIIIJJJJIJJIJIJJJIIIJIJJIJII(int IJJIJIJIIIJJJJIIJIIIIJJJJIJIJIIJIJIIIIIJIJJIIJI)
	{
	}

	public void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	public void JJIIIJIIJIJJJIIIIIIIJIIIJIIIIJJJJIJJIIJJIJIJIJJ(int IJJIJIJIIIJJJJIIJIIIIJJJJIJIJIIJIJIIIIIJIJJIIJI)
	{
	}

	public void IJJIJJJIIIIJIIIIJJIIIIIJIIJIIJIJIIIJIIJIIJIJJJI()
	{
	}

	public void JIJJJJIIIIJJJIIIJJIJIJJJIJIJJJIIIIIIJIIIJJJJIIJ()
	{
	}

	public void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	public void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}
}
