using System.Runtime.CompilerServices;
using ExitGames.Client.Photon;
using UnityEngine;

public class PhotonLagSimulationGui : MonoBehaviour
{
	public Rect IJJIJJJJJIIJJIJJJIIJIIJJIIJJIIIIIIIJIIJJIJJIIJJ;

	public int IJIJJJIJIJJJIJIJJIJJJIIJJIJIIIIJIJJIJJJJIIIIIJI;

	public bool IJJIJJJIIIIJIIJJIIJIJIJJJJJIIIIIIIJJJIIJIIJIIJJ;

	private PhotonPeer IJIJJIIIIIJIIIJJIJJIIIJJJJJIIIIJIIIIJIJIIIJIIJI;

	public PhotonPeer JIJIIJIIJJIJIJIJIIJIJJJIJJJJIJJIIIIIIJJJJIJIJJI
	{
		get
		{
			return IJJJIJIIJJIIJJIJIIIIIIJIJJJIIJIJIJJIJIIIIJJJJII();
		}
		set
		{
			IIJJJJJJJIIJJJIJIJJJJIIIIJIJJIIJJIJJIIIIJIJIIJJ(value);
		}
	}
	public PhotonPeer IIIJJJIJJJJJJIJJIJJIJJIJIIIIJJIJIJJJJJJIJIIIJII()
	{
		return null;
	}
	public PhotonPeer JJJIJJIIIIJJIJJJIIIJIJJJJIJIIJIIIIIIJJJIIJJJIII()
	{
		return null;
	}

	public void IIJJJJJJJIIJJJIJIJJJJIIIIJIJJIIJJIJJIIIIJIJIIJJ(PhotonPeer JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public PhotonPeer IIJJIJIJJJJIJJIIJJJJIJJIJJJJJJJIIJIJJIJJJJJJIIJ()
	{
		return null;
	}

	private void IIIIIJJJIIJIIJJJIJJIIJJJJIIIJIIIIJIJIJIIJJJIIJJ(int JJIJIIJIJIIJJIIJIJIIJJJJIJJIIJJIIIIJIIIJIIJIIJI)
	{
	}

	public void IIJIJIIJIJJIIJIIJJJIIJJIJIIJJJIIJIJIIJJJIIJJIJJ()
	{
	}
	public void JIIJJJIJIIJJJIIJIJJJJIJIJJJIIJJJIJJJIIIJJJIJIJJ(PhotonPeer JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public PhotonPeer IIJJIIJIIJJJIIIIIIIJIJIJIJJJJJJJJJIIJIIIJJIIIII()
	{
		return null;
	}

	private void IJJIIJJJJJJIIJJJJIIJIJJIIIJJIIJIJJJJIIIJJJJIJJJ(int JJIJIIJIJIIJJIIJIJIIJJJJIJJIIJJIIIIJIIIJIIJIIJI)
	{
	}

	private void JJIIIIJIIJIIJIIJJIIJIJIJJJJIJJIJJJJJIJJJIJIIIJI(int JJIJIIJIJIIJJIIJIJIIJJJJIJJIIJJIIIIJIIIJIIJIIJI)
	{
	}

	private void IJJIIJJIIIJJIJIIIIJJJJJJJIJJJIIIJJIJJJIJJJJIIII(int JJIJIIJIJIIJJIIJIJIIJJJJIJJIIJJIIIIJIIIJIIJIIJI)
	{
	}
	public PhotonPeer IJIJJJIJIJJIJIIJIIIIIIJIJIIIIJJJJJIJIJJJJIJJIJJ()
	{
		return null;
	}
	public PhotonPeer IJJIIIJJJIIIJJIJJIIJIJJJIJIIJJIIJJIIIIJIIIIJIJJ()
	{
		return null;
	}

	public void Start()
	{
	}

	public PhotonPeer IJJJIJIIJJIIJJIJIIIIIIJIJJJIIJIJIJJIJIIIIJJJJII()
	{
		return null;
	}
	public PhotonPeer JJJJJJIJJJJIIJJIIIIJIIJJIIJIJJIJJJJJIIJJIJIIIJJ()
	{
		return null;
	}

	private void IJIIIJIIJJJIJJJJIIIJJJIJJJJJIIIJIIJIIIIIJIIIJII(int JJIJIIJIJIIJJIIJIJIIJJJJIJJIIJJIIIIJIIIJIIJIIJI)
	{
	}
	public PhotonPeer JJIJJJJJJIJJIIJIJIJJJJJIJJIIIIIIIIIJIIJJJJIIIJJ()
	{
		return null;
	}

	private void IIIIIIIIJIIJIJIIJJIIIIJIJIJIIJJIJJJJJJIIJJJJIJJ(int JJIJIIJIJIIJJIIJIJIIJJJJIJJIIJJIIIIJIIIJIIJIIJI)
	{
	}

	private void IJJJJJIJIJJJIIJIJIJJIIIIIIJIJIJIJIIJJJJIJIIJJJJ(int JJIJIIJIJIIJJIIJIJIIJJJJIJJIIJJIIIIJIIIJIIJIIJI)
	{
	}

	public void OnGUI()
	{
	}

	private void JJIIIIIIIIJJIIIJJIJJJIIJIJJIJJJIIIJJIJIIJJIIIIJ(int JJIJIIJIJIIJJIIJIJIIJJJJIJJIIJJIIIIJIIIJIIJIIJI)
	{
	}

	private void JIJIJJIIJJJIIIIIJIJJJJJIJJJJJJJJIJJIIJJJIJIJJJJ(int JJIJIIJIJIIJJIIJIJIIJJJJIJJIIJJIIIIJIIIJIIJIIJI)
	{
	}
}
