using System.Runtime.CompilerServices;
using UnityEngine;

public class PlayerSkinRagdoll : MonoBehaviour
{
	public static float JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII;

	public Rigidbody[] IJJJIJJJIIJJJIIIIIIIJIIJJIIJJJIIIJJIIIJIJIIIIJI;

	public PlayerSkinAtlas IJIIJJIIIJJIJJJIIIJJJJJJJIIIIJJIIIJIJJJJIIIJIIJ;

	public Transform IIIJJIIIJIIIJIJJJJJJIIIIJIJIIIJIIIIIJIJIIJJJJJJ;

	public Transform JJIIJIJJIJJJIIIJIIIJIJIIIJIJIJIIJJJJJIIIJJIIIJI;

	[HideInInspector]
	public Vector3 IIIJIJJJIJIJJJJJJIIJIIJIJJJJIJJIIJJIJIJIIJJIIIJ;

	private Transform JJIJIIJIIJJJJJIIIJIIIJJJIJJJIIIIJJIJJJIIIJJIIII;

	private GameObject IIIJIJIIIIIJJIIJIIIJJJIIJIJIIJIJIIJJJJIJJJJIIII;

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	public GameObject JIIIJIJJJIJJIJIJIIIJJJJIIJIJJJIIIJJIIIJIJIIJIII => JIJJIIJIIIJIJIIJJIJIJJJIIIJIIIJJIIIJIJJJIIIJJJJ();

	public void IIJJJIIIIIJIJJJIJIIJJJIIIIIIIJJJIJJIIIIJIJIIIJJ(Vector3 JIJIJJJIJJIIIIIJIIIIIJJJJJJJIIIIJIIIJJJJIJJIIJI, Transform[] IIIIJIJIIIJIJJIIJJIJIIJJIIIJJJIIJJIIJJJIJJIIJJJ)
	{
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}

	public GameObject JIJJIIJIIIJIJIIJJIJIJJJIIIJIIIJJIIIJIJJJIIIJJJJ()
	{
		return null;
	}
	public Transform IJIJJJIJIIIJIJIJIJJIIIJJJIJJIJIJJJJJJJJIJJIJIIJ()
	{
		return null;
	}
	public GameObject JJJIIJJIIIIIIIJIJJIJJJIJJJIJJIJIJJIIJJIIJJIJIJI()
	{
		return null;
	}

	public void IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI(Vector3 JIJIJJJIJJIIIIIJIIIIIJJJJJJJIIIIJIIIJJJJIJJIIJI, Transform[] IIIIJIJIIIJIJJIIJJIJIIJJIIIJJJIIJJIIJJJIJJIIJJJ)
	{
	}

	public void IJJIJIJIIJJIJIIJIJIIJJIJJIIJJIIJIJJJJIJIJIIJIJI(UIAtlas JJJIIIJJJIIIIIJIJIJJIIIJIIIIIIIJIIIJIIIIIIJJJJI, string JIIJIIJJJJJIIIJIJJIIJIIIIIIJIJIIJJIIIJIIIIJIIJI, string JJJJIIJJJIJJIIIJIIIIJJJIIIJJJJIJJJJIIIJJIIJIJIJ, string JIJJIJJJJIJIIIIJJJJIIJIJIIIIJJIIJIIIIIJIIIIIJJJ)
	{
	}
	public GameObject IJJIIJJIJJIJJJIIIIIJJJJIJIIJJIIIJIIJJJJJIIJIJJI()
	{
		return null;
	}
	public Transform IJIIIJIJIJIJJJJIIIIJJIJIIJJJIIJIJIJIJJJIIJJJJJI()
	{
		return null;
	}

	public void JJIJIJIJIJIJIJIJIIJIIIJIJJJIJIJJIIIIJIJIIIJJJII(Vector3 JIJIJJJIJJIIIIIJIIIIIJJJJJJJIIIIJIIIJJJJIJJIIJI, Transform[] IIIIJIJIIIJIJJIIJJIJIIJJIIIJJJIIJJIIJJJIJJIIJJJ)
	{
	}
	public GameObject JIIJJIIJIJJJJJIIJIJIJJJJJIIIJJJJJIJJJIJIJJJJIII()
	{
		return null;
	}

	public void JJJIJIJIIIJJJJJJIIIJJIIJIIIIJIJIIJIJJIJJIIIIIII()
	{
	}

	public void IJIJJIIJIJIJJJIIIJIJIJJIIIJIIJJJIIJJIJIJIJJIJII()
	{
	}

	public void JIJIJJIIJJJIJIJIIIJIIIIJIJJIJIJIJJJIIIJIIIIJIIJ(UIAtlas JJJIIIJJJIIIIIJIJIJJIIIJIIIIIIIJIIIJIIIIIIJJJJI, string JIIJIIJJJJJIIIJIJJIIJIIIIIIJIJIIJJIIIJIIIIJIIJI, string JJJJIIJJJIJJIIIJIIIIJJJIIIJJJJIJJJJIIIJJIIJIJIJ, string JIJJIJJJJIJIIIIJJJJIIJIJIIIIJJIIJIIIIIJIIIIIJJJ)
	{
	}
	public Transform JIJIIJIJIIJJIJIJIIIIJIIIJIJJJJJIIIIJJJIIIIJJJIJ()
	{
		return null;
	}
}
