using System;
using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class PlayerSkinAtlas : MonoBehaviour
{
	[Serializable]
	public class JJIIIJIIJJIJIJIJIIJIIIIJIJJJJJIJJJIJJJJJIIJJJJJ
	{
		public string JIIIJIIJJIIIJIJJJJJIJIIJIJIJJIIJIJJJIIJJJJJJJIJ;

		public string JJJJJJIJIIJJIIIIIJIIIIIIJJJIIIIJJIIIIJJJJIIJJJI;
	}

	public static UIAtlas JIIJIJJIJIIIJIJIIIIIIJIIIIJJIJJJJJIIJIJJJIIIIJI;

	public Mesh JIIJIIIIIIJIIJIJIIIIIIIIIJIJIJIIJJIJIIJIJJIIJJI;

	private SkinnedMeshRenderer IJIJIJJIJJJIIJIJJIIJJIJIIJJJJJJJJJIIJJIJJIIIIJI;

	private Mesh IJIJIJIJJJIIJJIIJJIIJIJIJIJJIJIJIIIJIIIIJIJIIJJ;

	public Material JIIIIJJIJJIJIJIIJJJJIIIJJIIJIIJJIIJIJIIJJJJIIJJ;

	public Material JJJIJJJIJIJIIIJJIJJIIIIJIIJJIJIIIJJIJIJIJJIIIIJ;

	public UIAtlas IIJIIJJJIIIJJJJIJIIJJJIIJIJIIIIIIIIJJIJIIIJJIIJ;

	public string JJJIIJJJJJIIIJIJIIIIJIIIIJJJIJIIJJJJJJJIJJJJJJI;

	public string JIJJJJJIIJJJIJJJIIJJIIIIIIJJIIJJJIJJIIIJJJJJJIJ;

	public string JJIIIIJIIIIIIJJJJIIIIJJIJJJJIIIIJIJJJJJIIIIJIJJ;

	public string JJJJIIJJIIIJJIIIIIJIIJJIJJIIJIIJJJIJIIIJJIIIIJI;

	public string IJIIJIJIIIJIIIJJIJJIIIJIJJJJJIIJJJIJJIIIIIIJIJJ;

	public string JIJIIIJJIIJIJJIIIIJJJJIJIIIJJJIJIJIIJIJJJJIIJIJ;

	public SkinnedMeshRenderer JIIIJIJIIIJJIJIJJJJIJJJIIJJIJIIIIIIIJIJIJJJJJJJ => JIJJJIJIJJJIIIJIJIJJIIJJIJIIJIJJJJJJJIJIIJJIIII();

	public UIAtlas JJJIIIJJJIIIIIJIJIJJIIIJIIIIIIIJIIIJIIIIIIJJJJI
	{
		get
		{
			return IIJJJIJJIIIIIIJJIIJJIIIJIJJIIIJIJJIIIJIIJJIIJII();
		}
		set
		{
			JJIIIJIIIJIJJJJJJJJIJJJJIIIIJIJIIIJJJIJIIIIIJJJ(value);
		}
	}
	public SkinnedMeshRenderer IIIIJJJIJIIJIJJIIIJJIJJJJJJJIIIIJIIIIIIJIJIIJII()
	{
		return null;
	}

	private void JJJIIIIJIIJJIIJIIIJJJIIJIIIIIJIJJIJIIIIJIJJIIJJ()
	{
	}

	public void JJIJIIIJIJIIJIJJIJJIJIJJJIIIIIJIIIJIIJIJIJIJIJJ(IIJJIIIJJJIJJIJIIIIJJJJIIJIIJIIIIIJIJJJJJIJJIJI IIIJJIIIIIJIJJIIIIIIIJJJIIIIJIJIJIIJJJJJJIJIJIJ, string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public string JJJJIJJIIIIIJIJJIJJJJIJIIJJJJIJJIJIIIIJIJIJIIJJ(IIJJIIIJJJIJJIJIIIIJJJJIIJIIJIIIIIJIJJJJJIJJIJI IIIJJIIIIIJIJJIIIIIIIJJJIIIIJIJIJIIJJJJJJIJIJIJ)
	{
		return null;
	}

	private void OnEnable()
	{
	}
	public UIAtlas JIIIIJIIIJIJJIJJJJJIJIJIJJJJJJJJJJIIJIJJJIIIIJJ()
	{
		return null;
	}
	public SkinnedMeshRenderer JJIIIJJJJJJIJJIIJJJJJIJJIIIIJIJIJJIJJJIJIJIJJIJ()
	{
		return null;
	}

	public void IJIIIIJJIJJIIJJIJJIJIIJJJIJJJJJJJIIJIIJIIIJJIJJ()
	{
	}

	public void JJIJIIIJIJIIJIJJIJJIJIJJJIIIIIJIIIJIIJIJIJIJIJJ(string JIIJIIJJJJJIIIJIJJIIJIIIIIIJIJIIJJIIIJIIIIJIIJI, string JJJJIIJJJIJJIIIJIIIIJJJIIIJJJJIJJJJIIIJJIIJIJIJ, string JIJJIJJJJIJIIIIJJJJIIJIJIIIIJJIIJIIIIIJIIIIIJJJ)
	{
	}

	public SkinnedMeshRenderer JIJJJIJIJJJIIIJIJIJJIIJJIJIIJIJJJJJJJIJIIJJIIII()
	{
		return null;
	}

	public void IIJIJJJJJJJJIJIIIJJIIJJIJIIJJJJIIIJIJJJIJIJJJIJ()
	{
	}
	public SkinnedMeshRenderer IIJJJJJIJIIJIJIIIIIJIIIJJIIJJIJJJJIIIIIIJJIJIIJ()
	{
		return null;
	}

	public void IJJJJJIIIIJIJJIIIIIJIJIIIIJIIJIJIIIJIJJIJJJIJJJ()
	{
	}

	public void JIIJJJIIJJIJJJIJJJJIJJJIIJIIJIIIIJJJJJJJIIJIJJI()
	{
	}

	private void JJJIJIJJIIJJIJIJJJJJIJJIIIIIJIJIIJIJIIJIJJJJJII()
	{
	}
	public SkinnedMeshRenderer IJJIJIIJJIJIIJJIIJIIIIJIJIIIJIJJIJJJIJIIIIIJIII()
	{
		return null;
	}

	public void IJIIIJJJJJJJJJJJIJIIIIJIJIIJJIIJIIIJJIJJJIIJIJI()
	{
	}

	public string IIIJIJJJJIJIIJIJIJJJJIIJIIJIIIIJJIIJJJIIJJJIJJI(IIJJIIIJJJIJJIJIIIIJJJJIIJIIJIIIIIJIJJJJJIJJIJI IIIJJIIIIIJIJJIIIIIIIJJJIIIIJIJIJIIJJJJJJIJIJIJ)
	{
		return null;
	}

	public void IIIIJIJIJIIJIIJIIJIIJIIJIJJIIIJIIJIIIJJJJJIIJII()
	{
	}

	public Vector2[] JIIJJJJJIJIIJIIJIIIIJJIIIIIIIJJIIJJIJIJJJIJIIJJ(IIJJIIIJJJIJJIJIIIIJJJJIIJIIJIIIIIJIJJJJJIJJIJI IIIJIJJIJIIJIJJJIJIIIIJIIIJJIJIJIJJJJIJJJJJIIIJ, string JIIIJIIJJIIIJIJJJJJIJIIJIJIJJIIJIJJJIIJJJJJJJIJ, Vector2[] IIJJIJIIIJJIJJIJJJJJJJIIJIIJJIJJJJIJIIIIJJIIIJI)
	{
		return null;
	}

	public void JJJJIIIIJJIIIJJIIJIJJIIJJJIIIIIIJJJIJIIJIJJJIJI()
	{
	}

	public UIAtlas IIJJJIJJIIIIIIJJIIJJIIIJIJJIIIJIJJIIIJIIJJIIJII()
	{
		return null;
	}

	public void IIJJIIIIIJIJJIJJIIIIIJJJIJIIJJJJJIIJIIJIIIIJIII()
	{
	}
	public SkinnedMeshRenderer JIJJIIJIIIIJIIJIJIJIJJJIJJJIIJJJIJIJIIJIIJIIJII()
	{
		return null;
	}

	public void JIJIJIIJIJJIJIIIIJJJIJJIJIJIIIJIJIJIJIJJJIIIIII(string JIIJIIJJJJJIIIJIJJIIJIIIIIIJIJIIJJIIIJIIIIJIIJI, string JJJJIIJJJIJJIIIJIIIIJJJIIIJJJJIJJJJIIIJJIIJIJIJ, string JIJJIJJJJIJIIIIJJJJIIJIJIIIIJJIIJIIIIIJIIIIIJJJ)
	{
	}

	public void IIIIJJIIIJIJJJJJJIJJIJJJJIJIIJIIIJIJJJJIIJIJJJJ()
	{
	}

	public void JJIIIJIIIJIJJJJJJJJIJJJJIIIIJIJIIIJJJIJIIIIIJJJ(UIAtlas JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void Reset()
	{
	}
}
