using System.Runtime.CompilerServices;
using UnityEngine;

public class PlayerSkinDamage : MonoBehaviour
{
	public IIJJIIIJJJIJJIJIIIIJJJJIIJIIJIIIIIJIJJJJJIJJIJI IIJIIIIJIIJJJIJJIJJIJIJIIIJIJIJIJJIJJIJJIJJJIII;

	public PlayerSkin IJJIIJIJIJIIJJIIIJJIIJIIJIIIJJJIJJJIJIJJJJJIJII;

	private Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	public void IJJIIIIJIJJIIIJIIIIJJIIIIIIJJJIIIJJJIIIIIIIJJIJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}
	public Transform IJIJIJJIJIJJJJJJIJIJJJIIIIJIIIJJIJIIIJJIJIIJIJI()
	{
		return null;
	}
	public Transform JJJIIJJIJJJJIJJIJJIIJIIJIJJJJIIJJJJJJJJIIJJJJJI()
	{
		return null;
	}
	public Transform IJIIJIJIJJJIIJIJIIJIIJIIJIIIJJJJJJJIJIJIIJIJJJJ()
	{
		return null;
	}
	public Transform JIJIIJIJIIJJIJIJIIIIJIIIJIJJJJJIIIIJJJIIIIJJJIJ()
	{
		return null;
	}

	public void IIIJJJJIJJJIIJJJIJJIJIJJIJIJJIIJJJJJIIIJJJJJJII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void IJIIJIIJIIIIIIJIIJIJIJJIIJJJJIIIJIJIIJJIJJIIIIJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}

	public void JIIIIIJIIJIJJJJIJJIIJIJJIJJIJIIJIJJJJIIJJIIJJII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}
	public Transform IJJJIIJIIIIJJJJJIJJIJIIIJJIJJIIIJIIIJJJJJJIIJII()
	{
		return null;
	}
	public Transform IJIJJJIJIIIJIJIJIJJIIIJJJIJJIJIJJJJJJJJIJJIJIIJ()
	{
		return null;
	}

	public void JIIJIIJIIJIJIIIJIJIJIIIJJIIJJIJIIIIIIJJIIIJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void JIJIJJJJIIIIJIIIIIIJIIIIIJJJJIJJIIJIJJJIIIJJIII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void IIJJJIJIJIIJJIIIJIJJIJIJIJJJIIIIJJJIIJIJIJJJJJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}
	public Transform JIIJJIIIIIIJJJIIIIJJIIJIJJJIIIIJIJJJJIIIIJIJIIJ()
	{
		return null;
	}

	public void JJJJIIJJJJJIJJIJJIJIIJJIIIJIIIIJJJIIIJIIJJJJIJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}
}
