using System.Collections.Generic;
using System.Runtime.CompilerServices;
using DG.Tweening;
using UnityEngine;

public class PlayerSkin : MonoBehaviour
{
	private sealed class IJIIIIIIIIJIJJJJIJIIJIJIIIIIJJIJJIJJJIJJIJJIJIJ
	{
		public PlayerSkin JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public UIAtlas JJJIIIJJJIIIIIJIJIJJIIIJIIIIIIIJIIIJIIIIIIJJJJI;

		internal void IIJJIIJJJJIJJJJJJIIJJIIJJIIIIIIJIIJJIJIJJJIJIJJ()
		{
		}

		internal void JJJJIIIIJJIIJIJIIIJIIJJIIIIJIIJIIIJJIIIIJJIJJII()
		{
		}

		internal void JJIIJJJIIIJIIJJJJJJJIJIJIIJIJJJIIJIIIJIJJJIJJJI()
		{
		}

		internal void IIJJJJJJIIIIIIJJJJIIJJJIJIIJJIIIJIIJJJIIJJJIIIJ()
		{
		}

		internal void JIJIJIJJIJIJJJJJJJIIJJJJIIIJJIJJJJJJJIJJIIIIIJJ()
		{
		}

		internal void IIIJIJIIJIJJJIIIIIJIIJIIIIIIJJIIIIJJIJIJJJJJJII()
		{
		}

		internal void JJJJJJJJJIIIJJIJIIIIIIIJIIIJIIJJJJJIIJJJIIJJJJJ()
		{
		}

		internal void JIJIJJIIJJIIJIJIIJIJJIIJJJJIJIJIJIIJJIJJIIIJIII()
		{
		}

		internal void JIJJIIJIJJIIIJIIIJIIIIJIIIIIIIJIIIJIJJJIJIIJIIJ()
		{
		}

		internal void IIIIJIJIIJIJIJJJIJIIJIIJIIIJIIJJIIIIIIJJIIJJIIJ()
		{
		}

		internal void JJIJIJIIJJJJIJIJJIJJIJJIIJJJIJIJJJIIIIIJJJIIJJI()
		{
		}

		internal void IIIIIJJIIJIJJIIJIIIIIIJIJIJJIIIJJJJJIJJJJIJJJII()
		{
		}

		internal void JIJJIJIIIJJJJIIIJJJJIIJJIJIIJJJJIIJJJJIIIIIIIIJ()
		{
		}

		internal void IIIIJJJJIIJJIJIJIIJIIIIJIIJIJJJIJJJJJJJJIIIIIII()
		{
		}

		internal void JJIJIJIJJIJJJIIJJJJJIJIIJJJIJJJJJIJIJIJJJJJIIII()
		{
		}
	}

	public bool IJJIJIIJIIIIJJIIIIIJIJJJJJIJIIJIIJIJJJIJIIIJIII;

	public byte JIJJIIIJJJIJIJJJIJJJJJIIJJIIIIIIIIIJJIJIIJIJIJI;

	public byte IIJIIJIIIIIJIJJIIJJJIIJJIIIIJIJIJJIJJIJJJIIJIIJ;

	public JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJJIIIJJJIIJIJIIIIIIIJJJJJJIIIJJIIIJIIIJIJIJJJ;

	private bool JIJJJIJIIIJJJIJIIJJJIJJIJIJJJJIJJJIIIIIIIJJJIIJ;

	public ControllerManager IJJIJJJJJJJJJJJJJIJJJIJJIIIJJJIJIJIIIIIIIJJIIIJ;

	public PlayerAnimator IIJJIIIJIJIIJIJIJIIJIIJIIIJJIIJJIJIJIJIJJJIIIJI;

	public PlayerSkinRagdoll JIJJJIJJJJJIIJIIIJIIIJJJJJIIJIIJIJIIJIJJIJIIIJJ;

	public Transform[] IJIJIIIJJIIIJJIIIJIJJJJJIIJIIJIJJIJIIJJJJJJJIJI;

	public PlayerSkinAtlas JJJJIIJIJIIJJIJIJJIIJJJIIJIIIIJIIIIJIJJIJJIJIII;

	public Transform[] JJJJJIIIIJJJJJJIJIIIJIJJJIIIJIIJIJJJIJJJJIJJJJI;

	public Transform JJIJJJJIJJJJIJIJIIIIJJIIIIIIIJJIJJJIJJJJJJJIIJJ;

	public Transform JIJIIIIJIIIJIIIIIJIIJJJJJJIIIIJIJJJIJJJJJJIJIII;

	public AudioClip[] IJIIIJJIIIIIIIJIIIIIIJJIIIIIIIJJIIJJIIIJIIJJIII;

	public AudioSource JJJIJJIJJIIJIIIIJJJIJIJIIIIIIIIIIIIJJJJJJIJJJJJ;

	public Transform JJJIJIJIIIJIJIIIJIJJJJIJJIIJJJIJJJIIIJIJJJJJJJI;

	public Transform IJJIIIIIIJJJJJIJJJJIIJIJIIIIIJJIJJJIIIJIJJIIJJI;

	public Transform JJIIIIIJIIIJIJJIIJIJJJJIIIJJJIJIIJJIJJJIJIIJIIJ;

	public PlayerSkinDamage[] IJIJJJIIIIJJJIJJJJIIJIJIIJJJIJIIIJJJIJJJJJJIIJI;

	public nTimer IIIIIJIIJIJIIIIJIJIJJIIIJIJJIJJIJIIJJJIJIJIJJJJ;

	public Material IJIJIIIJIIIJJJJJJJIIJIIIJIIIJJJIIJIJJIJIIIIIIIJ;

	public PlayerSounds JIIIIJIJJJJJIJIIJJIIJIIJIIIIIJIJIIIJJJJJJJJIJIJ;

	private bool IIJJIIIIIJIIJIIJIIJJJJJJJJIJJIJIJJIIJIJIJIIJIJJ;

	private static bool JJJIJJIJIJIIJJJJJIJJJJIIIIIJJIJJJIJIIIJIIIIIJII;

	public static bool JJJIIJJIJIIIIJJJIIJIIIIIIIIIJIIIJJJJJIJJIJIJJIJ;

	public float IJIIIIJIIJJJJIJIJIJJIJIJJIIIIJIJJJIIJIJJJJIIJII;

	public Vector3 IIJJIJJIJIJJIIIJIJIIJIIIIJJIJJIJJJIJJJJIJIIIIII;

	public Quaternion IJJIIIIIIJIJJIIIIJJJJIIIJJIJIJJJIIJJJIJJJJIJJJJ;

	public bool JIJIIJJJJJJIJIJIIJJJIIJIJJIIJJJIIIJJIIJIJIJJJIJ;

	private float IIIIJJJIJIJJIIIJIJJIIIIIJJIIIIIJIIIIJJIJIJIJIJJ;

	public bool JJIIJIIIJIIIIIIIJIIJIJIJIJIIJJJIJJIIJIJJIJIIIJJ;

	public float IIIJIIIIJIIIIIIIJJIIJJJIIIIJJIIJIIJIIJJIJJJJJIJ;

	public bool JJJJJJJJIJJJJIJJIJJJIIJIJIIIIJIJJJJIJIJIJIIIJJJ;

	private Tweener JIJJJIIJIJIJJJIIJJJJJIJIJIJIIIJJJJJIIJIJJJJIIIJ;

	private bool IIIIJIIIJJIJIJIJJJJJIIJJJJIJJIJIIJIJJJIJJJJJIJJ;

	private bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ;

	public int JIJJIJJIJJIIJIIIIJJIIJJJJIIJIIIIJJIIIIIIIJIJIJI;

	public int JIJJIJIJJJJJIJIJJIJJJIIJJIJJIJIJJIJJJIJJJIJIJIJ;

	public int JJJJJIJJJIIJJJIJIJJJIJJJIJIIJIIJJIIJIJJIJIIJJJI;

	private bool JJJJJIIIJJIIIJJIIIJJJJJJIIIJIIJJIJJJIIJJJJIJJII;

	public TPWeaponShooter IIJJJJIJJIIJJJIIJIJJJJIIIJIIIIIJIJJJIIIIJIJIIIJ;

	private static List<TPWeaponShooter> JIIIJIIIJJIJIIIIJIJIJJIJIJIIJIJIIJIIJJJJJIJIJJI;

	private List<TPWeaponShooter> IIJIIIIIJJJIJJJIJJJJJIJIJIIJJIIJJJJJJJIJJIJJJII;

	[CompilerGenerated]
	private void IJIIJJJJJJJJIIJJJJJIJJJIIJIIIIIIIIIJJJJIJJJJIII()
	{
	}

	public void JIJIIJJJIJIIJJJIIJIJIIIIIJIIIJIIJJIIJIJJJIJIIII()
	{
	}

	public void IIJIJJJJJJJJJIIIJIJIJIIIJJIIIJIIJIJJJIIIIIIJIII()
	{
	}

	public float IIIJIIJJIJJJJJJIJJIJIJIJIIIJIIJJJJJJIJIJJJJJIJI()
	{
		return 0f;
	}

	private void JIJIJJIJJJIIIJIIIIIIJIIJJJIIIJJJIIJJIIJJJIIIIJI()
	{
	}

	private void JIJJIJIJJJIJJJIJIIJJJIJIIIIJJJIJIJJIJIJJJJIJIJI()
	{
	}

	public void JJJIIIJJJIIJIJJJJIJJIIJIIIIJJIIJJIIIIJJJJJJIIIJ(IIJJJJJJJJIIJJIIJJIJIIJIJJIIJIJJJJJIJJIJIJJIJJI JJIJIIJJJIJIIJJJIIJIIJIIJJIIIIIJIJIIIJJJJJJIJJI, int IIJJJJJIIIIJIIJJJIIJIIIJIIIIJIJJJJIIIIJJJJJJJJI, int IIIJJIJIIIIJJJIIJIIJJIIJJIJJJJJJIIJIJIIJJIJIJJJ, byte[] IIIJIJJJIJJIJIIIJIIJJJIIIIIJIJIJIIIIIIIJJJIIIII)
	{
	}

	public void JJJIIIJIIIIJJJIIIIJJJIJJJIIIIIJJIIJJJJIJJJJJIJJ(float IJIIJJJJIIJJIJIJJIIJJIIIJJIIIJIIJIJJJJIIJIJIIJI)
	{
	}

	private void JJIJJJJIJIIJJIIIJJIIJIJIJJIIJIJJJIJJIJIIJJIIIJI()
	{
	}

	[CompilerGenerated]
	private float IJJJIIJIJJIJIJJIIIIJJIJJJJJIJIIIIIIIJJIIIIIIJIJ()
	{
		return 0f;
	}

	public void IJJIIIIJJJIIJIJJIIIIIIIIIJJJJIIJIIIJIIIJJJJIIJI(Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII, bool JIIJIIJJJJJIIIJIJJIIJIIIIIIJIJIIJJIIIJIIIIJIIJI)
	{
	}

	public void JJIJIIJIJJJJJIIIJIJIJIJJJJJIJJJJIIIIIIIIJJIIJJJ(bool JJJJJIJJIJJJIJIIIJJIJIIIIJJIIJJJIJIIJIIIJIIJIIJ)
	{
	}

	private void IIJIIIIJIIIJJJJIIIIJJJJIJJJIIJJJIJIJJIIJIJJJIJI()
	{
	}

	public void JIIIIJIIJIJJJIJIJJJIIIJJJIJIIIJJJJIIJIJJIIJIIJJ(bool JJJJJIJJIJJJIJIIIJJIJIIIIJJIIJJJIJIIJIIIJIIJIIJ)
	{
	}

	public void JJIJIJIJIJIIJIJIJJIJIJIJJIJJIJJIJIIIJJIJIJJIJIJ()
	{
	}

	public void JJJJJJJIIIIIIJIJJIIIIJJJIIJIIIJIIJJIIIIJIJIIJII(IIIJJIJJIIJIIIJIIIJIIJIIJJIJJIJIJJIJJIIJIJIJIJI IJIIIJJJJIJJJJJJJIIJIJIJJIIJJIIJJJJIJJIIJJIJIJI)
	{
	}

	public void JJJIIIJIJIIJJJJIIIIJIIJJJJIIJJJIJIIJJJIJIIIJJIJ(float IJIIJJJJIIJJIJIJJIIJJIIIJJIIIJIIJIJJJJIIJIJIIJI)
	{
	}

	public void JJJIJJIJIJJIJIIJIIIIIIJIJIIJIJIJJIJJIIIJIIIJJII()
	{
	}

	private Vector3 IJJJIJIIIIIIIJJIIJIJIJJIIIJJJJJJJIIJJJIIIIIJJJI(Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
	{
		return default;
	}

	public void JIIJJJJJIIJIIIIIJIJIIJJIJIIIIIJIJIIJJIIIIJJIIII()
	{
	}

	private TPWeaponShooter JIJIJJIIJJIJIJJJJIIIJIJJJIJIIIJIJJJIIJIJIIJJIJI(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
		return null;
	}

	public void OnEnableRoot()
	{
	}

	private void JJJJJJIJJJIJIJIIIJJIJIJIJJJJIJIIIJJJJJIIJJJIJIJ(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
	{
	}

	private void IJJIIJIJIJJIJIJJIIIJIJIJIIIIJIIJIIJIJIIIJIIJJIJ()
	{
	}

	private void LateUpdate()
	{
	}

	[CompilerGenerated]
	private void IIJJIJJJJJJIJIIIIJIIIJJJJJIIJIIIJIJJJJIIIJIIJJI(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
	{
	}

	public void JJIJIIJJJJIJIIIIJIJIJJJJIIIJIJIJIJJIIIJIJIJJIJJ()
	{
	}

	private void JIIJIIIJJJJIJJIIJJIIIIJJJJIIIJIIJIIIIIJJIJIIIII()
	{
	}

	[CompilerGenerated]
	private void IIIIJJIIJIJJIIIJIIIIIIJJJIJIJIIJIJJJIIJIIIJJIJJ()
	{
	}

	public void JIIIIJJJJIIJJIJIJIJJJIIIIJIIIIIIJJJIIIJJJJIIJJI(float JIJIJJJJJIIIJIJJIJIIJJIIJJIJJIJJIJJJIJJJIJIIJJJ)
	{
	}

	private TPWeaponShooter JIIIJJIJJJJJJJIIJJIIIJIJJJJJIJJIIJJIIIIIIJIJJJI(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
		return null;
	}

	public void JIIIIIJIIJIJJJJIJJIIJIJJIJJIJIIJIJJJJIIJJIIJJII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void IJJIJIJIIJJIJIIJIJIIJJIJJIIJJIIJIJJJJIJIJIIJIJI(int JIIJIIJJJJJIIIJIJJIIJIIIIIIJIJIIJJIIIJIIIIJIIJI, int JJJJIIJJJIJJIIIJIIIIJJJIIIJJJJIJJJJIIIJJIIJIJIJ, int JIJJIJJJJIJIIIIJJJJIIJIJIIIIJJIIJIIIIIJIIIIIJJJ)
	{
	}

	private void IIJIIIIJIIJIJIIIIIJIJIIIIJJJJJIJJIIJIIIJIIIJIIJ()
	{
	}

	public void SetPlayerVisible(bool value)
	{
	}

	public void IIIJIJIJIIIJIIIJIIJJJIIIJJIIIIIIIJIJJJIJIJJJJII()
	{
	}

	private void OnDisable()
	{
	}

	public void IIJJIIIIJJJIJIJIJJJJJIIJJJIIIJIJIJIIJIIIIJJIIII()
	{
	}

	public void OnDisableRoot()
	{
	}

	public void Start()
	{
	}

	public void JJJIJIJIJJJIIJJIJJIIIIJIIJJIIIJIJIJJJIIIJIJJIJJ()
	{
	}

	public void IJJJJIJJIIJJJIJIIJJJIIIIJJJJJIJIJJJIJIIJJJIIJIJ(Vector3 IJJJJJJJIJIIIIIJJIIIIJIIIIJJJIIJJIJJJIJJIIIIJJI)
	{
	}

	private TPWeaponShooter IJJJJJJJJJIJJJIJIIIIJIJJJIIJIJIIJIJJJJJJJJIJJII(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
		return null;
	}

	private void IJJJJIIIIJJIIIJJIJJJJJJIJIIJJJJJJJJIJJIIJIIIJIJ()
	{
	}

	public void JJJIIJJIJJIJIIJJIJJIIJJIJIIIIJJJJJIIIIIJIIIIIJJ(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	public void JJJJIJJJIJIIJJJJIJJJIIIJIJIIIIIIJJJIJIJJJIJJIJJ()
	{
	}

	public void IJJIJJIIJJJJIJIJJJIJIJJJJJJJIIIJIJJJIIJIIJJIJIJ(int JIIJIIJJJJJIIIJIJJIIJIIIIIIJIJIIJJIIIJIIIIJIIJI, int JJJJIIJJJIJJIIIJIIIIJJJIIIJJJJIJJJJIIIJJIIJIJIJ, int JIJJIJJJJIJIIIIJJJJIIJIJIIIIJJIIJIIIIIJIIIIIJJJ)
	{
	}

	public void JIIIJJIIIIIIJIJIIJIIJJIIJIIJIJJJJIIJIJIIIJIJIII(Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	private void JJIJJIJIJIIIJJIIIIIJJIJIIIIJJJIJIIJIIIJJIIJIJJI()
	{
	}

	private void IIJIJIJIJIJIIIIIIIIJJJJIJIJJIJJJIIJJIIIIJJIIIIJ()
	{
	}

	public void IJJJIJJJJJIJIIJJJJJIIIJJJIIIIIJIJJIJIIIIIJIJJJJ()
	{
	}

	[CompilerGenerated]
	private void JIJJJJIIIIJIJIJIJJIJIIJIIJIIIJJIIIJIIJJIJIJJJJI()
	{
	}
}
