using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class PlayerAnimator : MonoBehaviour
{
	[Serializable]
	public class JIIIIJJJIIJJIJJJJIJJJIJIIJJIIJIIJJJIJJIIJIJIJJJ
	{
		public IIIJJIJIJIJJIJIJIIJJJJJJIJIJIIIIIJJJIIJJIIJJJII[] IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI;

		public IIIJJIJIJIJJIJIJIIJJJJJJIJIJIIIIIJJJIIJJIIJJJII[] JJJIJJJJIIJJJIIJJJJIJIIIJJIJJJJIIJIIJIJJJJIJJJJ;

		public IIIJJIJIJIJJIJIJIIJJJJJJIJIJIIIIIJJJIIJJIIJJJII[] JIIJIIIJJJJIIJIJJJJIJJIIIJIIJIJJJJJJJJIIIIIIIII;

		public IJJIJIJIIIJJIIIIJIJIJIIIJJIIJJIIIJIIJIJIJIIJIIJ[] JIJJIJIJJIIIIJJIJIJIJIIIJIIIIIJJIIJJIIIJJIJIIJI;

		public int JJJJJIJJIJIIIJJJJIJJIJIJIIJJJJJJIJJJIJIJIIJJJJJ;

		public int IJIIIJJJIJJIJJIIIIJJIJJIJIIIJJJJIIIIIIJIJJJIIJJ;

		public bool IIJJIJIJJIJJJIJIJJIIJIJJJIJIIIJJIIJIJIIJJJJJIIJ;

		public bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI;

		public float IIIJIIIJIJJJJJIIIJIIIIJIJIJJJJIIJJIJJIIIJJIIJJI;

		private int IIIIJJJJJJIJIJIJIJIIIIIJIIJIIIJIIIIIJIIJIJJIJJJ;

		private int JIJIJIIJIIJIJJJJJJIJIJJJJIIIIJIJIIJIIIIIJJJIIIJ;

		private int IJJJIJIIIJJJJJIJJJIIJIJJIIIJIJJIIJJJJJJJJIIIIJI;

		private int JIJIJIJIJJIJIIIJJJIJIIJJIIIJJIIIJIJIJIIJIIIIIII;

		public void JIIIIIIJJIIIIIIJJJJIIIIIJIJJIJJIIJIIJJJIIIJIJIJ()
		{
		}

		public void JJJJJJJIJIJJIJIJJJIIIIJJIIJJJJJIIIJIIJJIIIIJIII(float JIJIJJJJJIIIJIJJIJIIJJIIJJIJJIJJIJJJIJJJIJIIJJJ, bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ)
		{
		}

		public void JIJIJIIIJJIIJJJIJJJJJIIIIJJJJIJJIJJJJIIJJIIJIJJ(float JIJIJJJJJIIIJIJJIJIIJJIIJJIJJIJJIJJJIJJJIJIIJJJ, bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ)
		{
		}

		public void IJIIJJJJJJJJIJIIJIJJIIJJJIIJJIIIJJJIIJJJJJJIJIJ()
		{
		}

		public void JJJJJJJIIIIJIJJIIIJJJJJJIIIIJIIIIIJIIJJJIJJJIIJ(float JIJIJJJJJIIIJIJJIJIIJJIIJJIJJIJJIJJJIJJJIJIIJJJ, bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ)
		{
		}

		public void JIIIIJJJJIIJJIJIJIJJJIIIIJIIIIIIJJJIIIJJJJIIJJI(float JIJIJJJJJIIIJIJJIJIIJJIIJJIJJIJJIJJJIJJJIJIIJJJ, bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ)
		{
		}

		public void JIIJIJJJIIJJJIIIJJJIJJIJJJJJJJIJIIJJIJJIJJJJIJI(bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ)
		{
		}

		public void IIJIIIJJIIJIIIIJIJJJIIIIJJJIJIIJJJJIJIIIJIJIIIJ()
		{
		}

		public void IJIJJIIJJJJIIIIJJJJJIJIJJIJIIIJJJIIIIJIJIJIIIJJ()
		{
		}

		public void IIIJIIJJJJJJJJJIJIIJJJJIJIIIJIJJIIIJJIJJJIIJJJI()
		{
		}

		public void JIIIIIJIIJJJJJIIJIIIJIJIIIJJJIJIIJJIJIIJIJJJJII(bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ)
		{
		}

		public void JIIJJJIJIJIIJJIIJJIIJJJIIIJIIJJIJJIIJIIIJIJIJII()
		{
		}

		public void JJIJJIJJJJJJIJJJIJIJJIJIIJJIJIJIJJJJIJJIIJJIJIJ(float JIJIJJJJJIIIJIJJIJIIJJIIJJIJJIJJIJJJIJJJIJIIJJJ, bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ)
		{
		}

		public void IIJJJIJJIIIIJJIIJJJIJIJJJJIIIIJJIIIIIJJJIJIJIJJ(float JIJIJJJJJIIIJIJJIJIIJJIIJJIJJIJJIJJJIJJJIJIIJJJ, bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ)
		{
		}

		public void IJJJJJIIIIJIJIIJIJIJIIIIIJIIJIJIJIIJJIIIJIJJIII()
		{
		}

		public void JJIIIJIIJJJJJIIJIIJIJJJIIJJJIIJIIJJJIJIIJIIJJIJ()
		{
		}

		public void IJJJJJIJJJJJJIIJJJJIJJIIIJIJJIIIJJIIJJIJJJIJJIJ()
		{
		}

		public void IIIJIJJJJIIJJIIIJIJIJJIJJIJJJJIIJJJJIJIJJIIIIIJ()
		{
		}

		public void JJJIIIIJIIIJJIJJJIIIJIJIIIJJJJJIJJJJIJIIIJIJJIJ()
		{
		}

		public void IJIIJJIIIJIJJJJJJIIIJIIIJIIIJIJIJJJJJJIIIJJJJIJ()
		{
		}

		public void IJIIJIIJJJJJIJIIIIJJJJIJIJIJIJIIIJIIIJJJJIJJJIJ()
		{
		}

		public void JIIJIIIJIJJIIIJIIJIIJJIIIIIIIJJIIJIIIIIIIJIIIIJ()
		{
		}

		public void IIIIIJJIIJIIIJIIIIIJJIJIJIIJIIJIJJIIIIIJIJIJIII()
		{
		}

		public void JJJJJIIJJIIIJJJIJIJIIIIIJJIIJIIJIJJJIJJIIJJIIJI()
		{
		}

		public void IIIJIJIIJJJIIJIIIIIIJIJJIJIJIIJIIJIJIJIJIIIIIJI(float JIJIJJJJJIIIJIJJIJIIJJIIJJIJJIJJIJJJIJJJIJIIJJJ, bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ)
		{
		}
	}

	[Serializable]
	public class JIIIIIJJJIIIJIIIJIJIIIIJJJIJJIJIJJJIJIJIJJJJIII
	{
		public IIIJJIJIJIJJIJIJIIJJJJJJIJIJIIIIIJJJIIJJIIJJJII[] IJIIIIJIIIJIIIJIJIJIIIJJIIJJJJJJIJIJJJIIIIJIIJI;

		public IIIJJIJIJIJJIJIJIIJJJJJJIJIJIIIIIJJJIIJJIIJJJII[] IJIIIIJIJIJIIIIJIIJIJJJJJIJJJJIJIIJIJIIJJIJJJJI;

		public IJJIJIJIIIJJIIIIJIJIJIIIJJIIJJIIIJIIJIJIJIIJIIJ[] JIIJIIIIJJIJJIIIIJIIIIIJIIIIIIIJJJJJIJIJIIIIJJJ;

		public int IJIJJIJIIJIIJIJJIJIIJIJIIJJJIIIJJJIJIJJJIJIIJIJ;

		public bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI;

		private int IIIIJJJJJJIJIJIJIJIIIIIJIIJIIIJIIIIIJIIJIJJIJJJ;

		private int IIIIIJJJJJJIIJIJIJIIJIJIIIIJJJJIJIJJJIIJIJJJJJI;

		private int JJJIIIJIIIJJJIJIJIIJIIJIIJIIJJJIIIIIIJJIJIIIJIJ;

		private Vector3 JJJIIJJJJIIIIJIJJIJIJJJIJJJIJIJJIIJJJIIIIIJJJJI(Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
		{
			return default;
		}

		public void IIJIJJIJIIIIJIJJJJJIJIJJJIIIIIJJIIJJJJIIIIJJJII(bool JJJJJIJJIJJJIJIIIJJIJIIIIJJIIJJJIJIIJIIIJIIJIIJ)
		{
		}

		private Vector3 JIJJIIJJJJJJJJIIJJIIJJIJIJIJIJIIIIJJIIJJJJIIJIJ(Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
		{
			return default;
		}

		public void JIJJJIJJIIJIIIIJJJJJIIJIJIJIIJJJJJJIIIIJJIIIJIJ()
		{
		}

		private Vector3 JIIJIIJIJIJIJJIIIJIIJJIIJJIJJIIJJIIJJJIJJIJJJII(Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
		{
			return default;
		}

		public void JJJIJIIJJIIIJJJJJIIIIIIJJIIJJIIJIJIJIIIIJIIIJJI(float JIIJJJIIIJJIIIIJIJJJIIIJJIIIJJIIJIJJJJJJIJJJJJI, bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ)
		{
		}

		public void IIIJIJJJJIIJJIIIJIJIJJIJJIJJJJIIJJJJIJIJJIIIIIJ()
		{
		}

		private Vector3 IJIIJJJIJIIIIIIIJJJIIJIIIJJIIIJJJJIJIIIJJIIJJJI(Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
		{
			return default;
		}

		private Vector3 IIJIIJJIIIJIJJJIJIJJJJIJJIJJJJIIIJJJJIIIJJIIIJI(Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
		{
			return default;
		}

		public void JJIJIIJIJJJJJIIIJIJIJIJJJJJIJJJJIIIIIIIIJJIIJJJ(bool JJJJJIJJIJJJIJIIIJJIJIIIIJJIIJJJIJIIJIIIJIIJIIJ)
		{
		}

		public void JJIIJJIJJIIJIIJJJIIIJJIJIIIIIIJJJJIJJIJJJIIJJJI()
		{
		}

		private Vector3 JIIJJJJIIJIJIIJJIIIIIIIJJJJIJIIJJJIJJJIJJIJJJII(Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
		{
			return default;
		}

		public void JIIJIJJIJIIIIJIJIIJIIJJJIJIIJIJJJIJJJIJIJJJIJIJ(float JIIJJJIIIJJIIIIJIJJJIIIJJIIIJJIIJIJJJJJJIJJJJJI, bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ)
		{
		}

		public void IIJIIIIJIIJIJIIIIIJIJIIIIJJJJJIJJIIJIIIJIIIJIIJ(float JIIJJJIIIJJIIIIJIJJJIIIJJIIIJJIIJIJJJJJJIJJJJJI, bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ)
		{
		}

		public void IJIIIJIJIIJIIJIIJIIIJIJJIIJIJJIIIIIIJJJIIIJJJJI(bool JJJJJIJJIJJJIJIIIJJIJIIIIJJIIJJJIJIIJIIIJIIJIIJ)
		{
		}

		private Vector3 IJIJIIIJJIIIJIIJIIJJIJJIJJJIJJJIIIJJIJJJIIJIJII(Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
		{
			return default;
		}

		public void IJIIJJJJJJJJIJIIJIJJIIJJJIIJJIIIJJJIIJJJJJJIJIJ()
		{
		}

		private Vector3 IJJJIJIIIIIIIJJIIJIJIJJIIIJJJJJJJIIJJJIIIIIJJJI(Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
		{
			return default;
		}

		public void JJJIJIIJJJIJJIIIJJJIIIIJIIJJJIJJIIIJIJIIJJIJIJI()
		{
		}

		private Vector3 IJJIJIIIIIIJIJIIJIIIIIJIIIIIIIIJJIIIIIJIJIJJIIJ(Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
		{
			return default;
		}

		public void JIIIIIJIJJIJIJJJJIIIJIJIJJJJJJJJIIJJIIJJIJJJJIJ(bool JJJJJIJJIJJJIJIIIJJIJIIIIJJIIJJJIJIIJIIIJIIJIIJ)
		{
		}

		private Vector3 JIIJIIJIIJJJIJIIJIIJJIIJJIIIIJJIIIJJJJJJJIJIJIJ(Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
		{
			return default;
		}
	}

	[Serializable]
	public class IIIJJIJIJIJJIJIJIIJJJJJJIJIJIIIIIJJJIIJJIIJJJII
	{
		public Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

		public Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ;

		public Quaternion IJJJJJJJIJIIIIIJJIIIIJIIIIJJJIIJJIJJJIJJIIIIJJI;
	}

	[Serializable]
	public class IJJIJIJIIIJJIIIIJIJIJIIIJJIIJJIIIJIIJIJIJIIJIIJ
	{
		public Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

		public Vector3[] IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ;

		public Quaternion[] IJJJJJJJIJIIIIIJJIIIIJIIIIJJJIIJJIJJJIJJIIIIJJI;
	}

	public JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJJJIJIJJIIIIJJJJJIIIIIIJJIIJIJIJIIJIIJIII;

	public JIIIIJJJIIJJIJJJJIJJJIJIIJJIIJIIJJJIJJIIJIJIJJJ JIJJIIJIJJJJIJIJJJJIIJIIJJJJIJIJJIJJIJIIIIIIIII;

	public JIIIIJJJIIJJIJJJJIJJJIJIIJJIIJIIJJJIJJIIJIJIJJJ IJJJIIJJJJJJJIJJJJJJJJIIJJJIJJJJIJJIIIIJJJIJJIJ;

	public JIIIIJJJIIJJIJJJJIJJJIJIIJJIIJIIJJJIJJIIJIJIJJJ JIIIIIJIIIJIIJIJIIIIJJJIJJIJJJIJJIJIJJJJIIIJJIJ;

	public JIIIIIJJJIIIJIIIJIJIIIIJJJIJJIJIJJJIJIJIJJJJIII JIJJIJJJJIJIIIIJJJJIIJIJIIIIJJIIJIIIIIJIIIIIJJJ;

	public Transform IIIIJIIIJIJJJJIIJJJIIIIIIJJJJJIJJJJJJIIIJIIJIJI;

	private float IIIIIIIJIJJIIIJIIIJIIJJJJJIJJIIJIJJIJJIIIIJIIJJ;

	private bool JJJJIJIJIJJJIJIJJIIIJJJIIJJJJJIJIJJJIJJIIIJIIJJ;

	private float IJJJJIJJIIIIIIJIIIIIIIJIJIIJJIIJJIJIJIIJJIIIJJI;

	private bool JIIIJIJIJIJJIJIJJJIJJIIJJJIJJJIJJIIIIJIIJIJIIII;

	private Vector3 IIIJJIIJIIJJJJJJJJJJIJJJJJJJJIIIJJJIJJJJIJJIJII;

	private bool JIIJJIJIJJJJIIIJJJIJJIJIIJIJJIJIIJJIIIIJIIIJJII;

	public float JIJIJJJJJIIIJIJJIJIIJJIIJJIJJIJJIJJJIJJJIJIIJJJ
	{
		get
		{
			return IJIJIJJJIIJIJJJJJJJIIIJJJIIJIJJIJJIIJJJJIIIIIJJ();
		}
		set
		{
			JJIIIIIIIJJIIIIIJIIJJIIIIIIJJJIJJIIJIJIIIIIJIIJ(value);
		}
	}

	public bool JJJJJIJJIJJJIJIIIJJIJIIIIJJIIJJJIJIIJIIIJIIJIIJ
	{
		get
		{
			return IIJJJIJIJIJIJJIJIJJIIJJJJIIJIIJIIJIIIJIJJIJIJIJ();
		}
		set
		{
			JIJJIIIIJJJIIJJIJJJJIJJIJJIJIIIIJJJJIIJIIJIJJII(value);
		}
	}

	public bool IJJJJIIIJJIIIIIJJJIIJIJJIIIJJIIJIIIIJIJJIIJJIJJ
	{
		get
		{
			return IJJJIIJJJIJJJJJJIJJIJJIJIJJIJJIIIJIJJIIJIJJJJJI();
		}
		set
		{
			JIIIJIIIJJIIJIJJJJIIJIIJJJIJIIIJIJIIIIJIIIIJIII(value);
		}
	}

	public float IJIIJJJJIIJJIJIJJIIJJIIIJJIIIJIIJIJJJJIIJIJIIJI
	{
		get
		{
			return JJIIIIIIIIJIIIIIIJIJJJJIIJJIJJIIJJIIIIIIJIIIJIJ();
		}
		set
		{
			JJIJJIJIJJJJIJJIJJJJIJIIIJJIJJIJJIIIJJIJJIIIIJI(value);
		}
	}

	public bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ
	{
		get
		{
			return JIIJIIIIIIJJIIIJJJIJIIIIIJIJIJIJJIIIJIJJJIJJJJJ();
		}
		set
		{
			IJJIIJIJIIIJIIJJIJIJJJJJJIJJJIJJJIJJIIIJIIJJIJJ(value);
		}
	}

	public Vector3 JIJJJIJIJIJJJJJIJJIIJIIJJIIIIIIIIJIJIJJJIIIIJJJ
	{
		get
		{
			return IJJIJIIJJIJIJIJJJIJJJIJJJJIJIIJIIIIJIJIIJIIJIIJ();
		}
		set
		{
			JJJJJJJJIJIJJIJJJJJIJIJIJJJJIIIIJJIJJIIJIJIJIJI(value);
		}
	}

	private void LateUpdate()
	{
	}

	private void IJIJJIIIIIJIJIJIIJJIIJJJJIIIJIJIIJJJJIIIJJIIJII()
	{
	}
	public float JJJJIIIJIIIJIIJIIJJIJIIIJJIIIIJJJIIIJIIJIIIJIII()
	{
		return 0f;
	}

	private void IIJJJIJIIIJIIIJJJJIIIIJIJJIJIIIIJJJIIIJIIIIIJII()
	{
	}

	private void IIJJIIJJJIIJIJJIIIIJIIJIJIIIIIJIJJJJJIJJIIIIIJI()
	{
	}
	public void IJIJJJJIIJIJJIJIJJIIJJJIIIIJIJIJJJIJJIIIIIIJJJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Vector3 IJJIJIIJJIJIJIJJJIJJJIJJJJIJIIJIIIIJIJIIJIIJIIJ()
	{
		return default;
	}

	public void IJIIJJJJJJJJIJIIJIJJIIJJJIIJJIIIJJJIIJJJJJJIJIJ()
	{
	}

	public void JJJJIJJIJIIJIJIJJIJJJIIJIIIJJJJIIIJIIJJIJIJJJII()
	{
	}
	public void IIIIIJJJIIJIIIIJIJIJJJJJJIJJJIJIJJJIIIJJJIIIIIJ(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool IIJJJIJIJIJIJJIJIJJIIJJJJIIJIIJIIJIIIJIJJIJIJIJ()
	{
		return false;
	}

	private JIIIIJJJIIJJIJJJJIJJJIJIIJJIIJIIJJJIJJIIJIJIJJJ JIIJJIJIJIIIJJJIJJJIJJJIIIIIIJIIIJJIIJIJIJJIIJJ()
	{
		return null;
	}

	public void JIJJIIIIJJJIIJJIJJJJIJJIJJIJIIIIJJJJIIJIIJIJJII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void IJJJJJJIIIIIJIIJJIIJJIJJJIJIIIIJJJIJJJIJJIJIIJJ()
	{
	}

	public void IJJIIJIJIIIJIIJJIJIJJJJJJIJJJIJJJIJJIIIJIIJJIJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public bool IJJJJIIJIJJIIJIIIIJJIJIJIJIJIIJIIIIIIJIJIJJIJJJ()
	{
		return false;
	}
	public Vector3 IIIJIJJIJJJIJJIJJIIJIIIIJJJIIJJJJJIIIIJJJIIIIJI()
	{
		return default;
	}

	public void JIIIJIIIJJIIJIJJJJIIJIIJJJIJIIIJIJIIIIJIIIIJIII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void OnDisable()
	{
	}

	private void OnEnable()
	{
	}

	public void JJJJJJJJIJIJJIJJJJJIJIJIJJJJIIIIJJIJJIIJIJIJIJI(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJIIIJJJIIJIJJJJIJJIIJIIIIJJIIJJIIIIJJJJJJIIIJ(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
	}
	public void IIJIIIIIJIJJJJIJIIJIIIJJJJJJJJJJJJIIJJIIJIIIIII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool JIIJIIIIIIJJIIIJJJIJIIIIIJIJIJIJJIIIJIJJJIJJJJJ()
	{
		return false;
	}

	public void JJJJJIIIJJIJIJIIJIIIIIIJJJJIIJIJIJIJIIIJJJJJIJI()
	{
	}

	public void JJIIIIIIIJJIIIIIJIIJJIIIIIIJJJIJJIIJIJIIIIIJIIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void IJJJJJJJJIIJJJJIJIIJIIIIIJJIJJJIJJJIJJJIJJJIJIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIJIJJJJJIIJJJJJIJJIJJJIIJIIJJIJJIJJIJIJJJIJIJI()
	{
	}

	public bool IJJJIIJJJIJJJJJJIJJIJJIJIJJIJJIIIJIJJIIJIJJJJJI()
	{
		return false;
	}

	public float JJIIIIIIIIJIIIIIIJIJJJJIIJJIJJIIJJIIIIIIJIIIJIJ()
	{
		return 0f;
	}
	public void JJIJIIJIIJIIIJJIJIIIIJJJIIJIIIJIIJJJIJIJIJJIIIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void IIIIIJIIJJIIIIJIJIJIJJIIIIIIJIIJIIIIJJJJJJJIIJI()
	{
	}
	public bool IJJIJIIJJJJIJJJJIJJIIIIJJJJIJJIJJJJJJJIJJIJJIIJ()
	{
		return false;
	}

	public void JJIJJIJIJJJJIJJIJJJJIJIIIJJIJJIJJIIIJJIJJIIIIJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JIIJJJIJJIJIJJIIJIIIIJJJJJIIIIJJJJJJIIJIJJJIJJI()
	{
	}
	public void IIIJJIIJJIIIIIIIIIJJIIJIIJIIJIIIJJJJIJIJJJIIJJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public float IJIJIJJJIIJIJJJJJJJIIIJJJIIJIJJIJJIIJJJJIIIIIJJ()
	{
		return 0f;
	}

	private JIIIIJJJIIJJIJJJJIJJJIJIIJJIIJIIJJJIJJIIJIJIJJJ IIJJJIJIJJJJIJIJIJJJJJJIJIIIIJJJJIIIIJJIIIIIIJI()
	{
		return null;
	}

	private void JIJIIJIJIIJJJJJIIJJIJJJIIJIJIIJIJIJJJIIJJJIIIJJ()
	{
	}
}
