using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class PlayerWeapons : MonoBehaviour
{
	[Serializable]
	public class JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ
	{
		public bool JJJJIIIJJJIIIJIIIIIJIJIJJJJIJJJIIJIJIJJJJJIIJJI;

		public bool JJJIIIJJIIIIJJIIIIJIJJJJIJJIIJIJIJJJIIIJIJIIIIJ;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IJJJIIJIJIJJJIIIIJJIIJJIIIIIIIIIJJIJIJIIJIJIIIJ;

		public bool JJIJJIJJIJJIIJIJIIJJJJJJIIJIIIJJJIIJJJIIIIIJJII;

		public bool IJIJJJIIJIJIIJJIIJIIIJJIJJIIJJJIIJJJJIJJJJJIIII;

		public IJIJJIJIIIIJIJIJJIIJIIJJIIIIIJJJJJIIIIIIIJJJIII IJJJJJIIIIIJIJJJJJIJIJIJJJIIIJIJJIJJJIJIJJJIIII;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IJJJJIJJIIJIIIJJJJJJJIIIJJJIJIIIJJJIIJIIJIIJIJI;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IIIIIIJJIJJJJJJJJIIJIIJIJJJJIIIIIJJJIJIJJJIIJII;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIIJJJJIIJJIIJJJJIIJJIJIIIJIJJJJIIIIJIJJIJJIIJJ;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IJJIIIJIJJJJIJIJIIIIIIIIJIIJIJIIJJIJJJJJJIIIJJJ;

		public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JJJIJJJJJJJIJJJJJIIIIIIIIJIJIJJIJIJJIIIIJJIJIJJ;

		public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JJIJIIIIIIIIIJJJJJIJJIJJJIJJJIIIJIJIJJIJIIIJIII;

		public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII IJJIIJIIJJJJJJIIIJIJIJIJJIIIJJIJIIJIJIJJIIJJJIJ;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JJJIJIJIJJIJIIIIJIJJIIJJJJJJJJJIJIIIJJJIJJJIIJI;

		public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIIJIIJIJIJIIIIIJJJJIIJIIIJJIJIIIJJIJIIIJJJJIJI;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JJJIJJJIJJJIIIIIIIIJJJJJIIIIIIIJJIIIJJIJIJIJIII;

		public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIJIJJIIJIJIIJJIIJIJJJIIJJIIJIIJJIIIJIJIIIJJJII;

		public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JJJJJIIIIIJJJJIIIJIIJIIIIJIJIIIIIJJJIIIJJJIIJIJ;

		public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JJIJJIIJIJJIIJJIIJIIJIJIJIIJIIJIJJIIJJIJJJIIJJI;

		public AnimationCurve IJJIIJIIJIIJIJJJJIJIIJJJIJIJJJIJIIIJJJJIIJIJIJI;

		public float IIIIIIJJIJIIIIIJIIJJJJIJJIIJIIIIJIJIJJJJIIJJIJI;

		public bool JJJJJJJJIJJJJIJJIJJJIIJIJIIIIJIJJJJIJIJIJIIIJJJ;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JJIIJIJJJIIJIJJIJJJJJIJIIIIJJIJIJJJJJIIIIJJIJII;

		public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII IIIIJIJJJJJIJIIJIJIJIIJJIJJIJJIIIJIIIJIJJIIJJJI;

		public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIJIJIJJIJIJJIJJJJJIJJJJJJIJJJJIIIJJJIIIJIJJJIJ;

		public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII IIIJIIJIIIIIIJIJJJIJJIIIJJIIIJIJIJJIJJIIIJIJIII;

		public bool JJJJJJIJJJIJIJJJIJJIIJIJIJJIIJJIJJIJJJJIIIJIIIJ;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IIJJJJJIIIIIIJIIJJJJIIIIJIIIJIJIIJIIJIIIIJJJJIJ;

		public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII IIJJJJJJIIJIIJJIIJIIIJIJJIIIIIJJJJJIJIJJIIJIIIJ;

		public JIIJIJIJJJJIIJIJJJIJJJJIIJIJIIIIIIJIIIJJIIJIJJI JIJJIJIJJIJJIJJJJJIJIJIJJJJJJIJIJIIIIIJIJIJJIIJ;

		public JIIJIJIJJJJIIJIJJJIJJJJIIJIJIIIIIIJIIIJJIIJIJJI JIIJIIIIJIJJIJIJJJJIJJIIJJIIIIJJJJIIJIJIJJJJJJJ;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IJIJJJJIJIJJJIJJJIJJIIIJIIJJJIIIIIIIIJJJIJJIJIJ;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JJIIJJIJJIIJIIJJIIIJJIIIJIJJIJJIIIJIJJJIIIIIIJJ;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIJJJIIIIIIIJIJIIJJJIJIJJJIIIIIIIJIIJJIIJJIJIJJ;

		public JJIIJIIJJIIJJIIJJJJIIJIIIJJIJJJIIIJJIJJIIIIJIII JJIIJIJJIJJIJJIJJJJIIIIJJIJIJIIIIIIIJIIIIJJJJJI;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIJIJIIJJIJJJIIJIJIIIJJJIIIJJJIIJIIJJJJIJJJIJJI;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIJJJJJIJIJIJJJJJIJJJIJIIIJJIJIJIJIJJJJJJJJJIII;

		public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI[] JIIIIJJJJJIJIJJJJIIIIIJIIJIIJJIIJJIIJIJJIIIIIIJ;

		public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JJIJJJJJJIJIJJIIJJIJIIIJJIIJIJIJIJJJJIIIJJIIIII;

		public FPWeaponShooter JJIJIIIIIIJJIJJIIJJJJJJIIIJJIJIJIIIJJIJJJIJJIIJ;
	}

	private sealed class IIIJJIIJJJJIIJJJJIJIJJIIJIJIIJJJJIJIJIJJJIIIIJJ
	{
		public PlayerWeapons JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJJJIJIJJIIIIJJJJJIIIIIIJJIIJIJIJIIJIIJIII;

		internal void JJJJIJJJIIJIIIIJIIJJIJIJJIJIIIJJJIIJJIJJJJIIIII()
		{
		}

		internal void JJIIJIIJJJJIJIJJIJJIJIIJJJIJJJIJIIJIJIJJIJIIJJJ()
		{
		}

		internal void IIIIJIJJJJIIJJIJJIJJIIJJJIIIIIIJJIIJJIIJIJJJIIJ()
		{
		}

		internal void JIIJJJIJJJJJIJJJJIIIIJJJIJJIIIJIIIJIJIJJJIIJIII()
		{
		}

		internal void JJJIJJIJIIJIIIJJIIJJJIIIJIIJJIJJJIJJJIIJIJJIJJI()
		{
		}

		internal void IJJJIIIJJJJJJJJJJIIIJIJIJJIJJJIJIIJIJIIJIJJJIJJ()
		{
		}

		internal void IIJJIJJIIJJIIIIIIIIIIIIJJJIJIIIIIIIJJJJJJJJJJJJ()
		{
		}

		internal void JIJIIJJJJIJJIJJJJIJIIIJIJIIIIIIIIIJIIJJIIJJJIJI()
		{
		}

		internal void IJJIIIIJIIJJIIIIIJJIJJJIIJJJJJJJIIJJIJJIIJJJJJI()
		{
		}

		internal void JJJJJIIJJIJIJIIIJIJIJIIJJJIJIJJIJIIJIJIJJJJIIJI()
		{
		}

		internal void JIIJJIIJIIIJIJJIJJIJIJJIJIIIJIJJJJIJIJJIJJIIJIJ()
		{
		}

		internal void JJIIIJIJIIJIIJJIJJIIJIIIJJJIJJIIIIIIJJIIJIJJIIJ()
		{
		}

		internal void IJJIJJJIIIJIJIIJIIJIJJJJIJIIJIJJJJJJIJJIJJJJJII()
		{
		}

		internal void JJIIIJIIIIJJJIJJJIIJIIIJIIIIIJJJJIJIIJIJIJJIIJJ()
		{
		}

		internal void IJIIJJIIIIIIIJIIIIIIJIIJJIJIIJJIIIJIJJJJJJJIJIJ()
		{
		}
	}

	private sealed class IIIIIIIJIIJJJIJIIJIJJJJIJIJJIIIIJIJIIIIIIIIJIIJ
	{
		public PlayerWeapons JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI;

		public int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI;

		public JJIJJIJJIJJJJIIIIJJIIJIIIIIJIIIIJJIJIIIIIIIJJJJ JJIIJIJJIIIJJIIJIJJJIJIIJIJIJIIJJJIJJJJJIJJJJJI;

		public bool JJIIIJJJJIJIJJIIIIJJJJJIIIIIIJJIIJIJIJIIJIIJIII;

		internal void JIJJJJJJJJIIJJJJJJIIJIJIJIJIJJIJJIJIJIJJJIJIIJJ()
		{
		}

		internal void JIJJIIIIJIIJJJIJIJIIJJIJJJIJIJIIJIIJJIIJIJJJJJI()
		{
		}

		internal void JIJJJJJJIIJIIJIIIIJJIJJIIJJIJJIJJIIIIIIJJJIJIJJ()
		{
		}

		internal void IJJJJIJIJIIIJIIIJIIIIJIIJJIIIIJIIIJIIIIJIJJIIJJ()
		{
		}

		internal void JJIJJJJIIIJIIIIIIIJIJJJIIJIJIJJJIJIIJIIJJJIIJII()
		{
		}

		internal void IJIIJIIJIIIJIIJIIJJIJJIJIJJIIIIJIJIJJJIIJIIJIII()
		{
		}

		internal void JIJJJJJIJIIJJIJJJIIJJJJIIIIIIIIJIJIIIIJIJIJJJIJ()
		{
		}

		internal void IJIIJIJJIIIIIIJIIIIJJJIIJJIJJJJIJIJIJJJIIJJIJJI()
		{
		}

		internal void IIIJIJJIJIIJIJJIIJIIIIIJIIJJJIJIIIIIIJIJJIJIJJI()
		{
		}

		internal void IJJJJJIIJJIIIJIJIIIJIJJJJIJIIIJIJJJIIJJIJJJJIJJ()
		{
		}

		internal void JJIIIJJJJJJIIJJJJJJIIJJJJJJIJIIJJJIJIIIJJJIIIJI()
		{
		}

		internal void JIIIIJJIJIJJJIJJJJJJIJIJJJIJIJIIJIIIIJIJJIJJIII()
		{
		}

		internal void JJIIJJIJIJIJJIIIJIJIIIIJIIJJJJIJJJJIIIJIJJJJIIJ()
		{
		}

		internal void JJJJIIIJIIIIIIJIJIJJJIJJJIJJIJIJJIJJIIJIJJIJIJJ()
		{
		}

		internal void IIIJJIJIIIJJIIJJIJIIJIJIJIIIJIJJIIJJJIIJJIIJJIJ()
		{
		}

		internal void IIJJJIJIJJJIJIJJJIJJIJJJJIIIJIIIIIJJIJIIIIJJJJJ()
		{
		}

		internal void JIIIIJJIIIJIIIJJJJJJIIJJJJJIIJJJIJJIJJJIIJJIIII()
		{
		}

		internal void JIJIIIJIIJJIJIJIJIIIJJJIJJJJJIIIIIIIIJIJIIIIJJI()
		{
		}

		internal void JJJJJJJIIIJIJJJIIJIIIJIIJJJJJIIJJIIJIJIJIJIJIII()
		{
		}

		internal void IJIJIJJJJJIJJIJJJJJIIJJIIJJIIIIJIIJJJJJIJJIJIIJ()
		{
		}

		internal void IJJJJIIJIIJJIJJJJJIIJIJJIIJJIIJJIIIIIIJJJJIJJIJ()
		{
		}
	}

	private sealed class JJIJJJJJIIIJJIJIIJJJIJIJIIIJJIJJJJJIIJIIIJIIJJI
	{
		public PlayerWeapons JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ;

		internal void JJJIIIIIJIIJJIIJIJIJJJJIIJJJIJIIIJJIIIJJJIJJJIJ()
		{
		}

		internal void IJIJIJIIIJIIIJJJJJIJIIIJIJIIIJJJIJJJJIJJIIJIIIJ()
		{
		}

		internal void JIIIIJJJJIIJJIIIIIIJIIJJIJJJIIIIJJIIJJJJIIIJJJJ()
		{
		}

		internal void IIJJJIIIIJJIIJIIJJJJJIJJJJIIJIJJJIJJIJJJJIJJJIJ()
		{
		}

		internal void IJIJIIIIJJIIIJIIJJJIJJIIIJIJIJIJJJIIJJIIIIIIIJI()
		{
		}

		internal void IJIJJJIIJIIIIIIIIIJIJJIJIIIIIJIJIIJJJJIIIIIIJII()
		{
		}

		internal void JJIIJJIIIIIIJJIJJJJIIIIJIIJIJIIJIIJJJIIIJIJJJJI()
		{
		}

		internal void IJJIJJJJIJJIIIIIIIIJJIIJJJJJIJJJJIJIJIIIIIIJJIJ()
		{
		}

		internal void IIIIJIJJJIIJIJIJIJIIIJJIJIIJIIJIIIIJJIJJJIIIJIJ()
		{
		}

		internal void IJJJJIIIJJJIJJJJIJIIJJIIJIIJIIJJJJJJJJJJJJIIJJJ()
		{
		}

		internal void IIIJJJJIIJJIJIJJJIIIJJIIJIJJJJIIJJIIIJJIJIJJJJI()
		{
		}

		internal void IJIIJIJIJJIJJIJIIIJJJIJIIIJJJJJIJJIJJJIJIIIJJII()
		{
		}

		internal void JIIIIJIJJIJIIJIJJIJJIJJJJJJJIIJJIIJJIIIIJJJJJIJ()
		{
		}

		internal void IJJIJJIIJIJJJJJJIIJJIJJJJIIIIIJJJIIIIJJIIJJIIJI()
		{
		}

		internal void JJIIIJIJJIIIIJIJJJIIJJJJJIJIIIJIIIIJIIIIJIJJJII()
		{
		}

		internal void IJJIIJIJIIJJJIJJIIJJIJIIJIIIIIJIIIIIJJJIJJJJIII()
		{
		}
	}

	public JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JIJJIJIJJJJIJJJIIJJJJJJIIIIIJJIJIJIJIJIJJIIJIJJ;

	public bool JJIJJIJJIJJIIJIJIIJJJJJJIIJIIIJJJIIJJJIIIIIJJII;

	public bool IJIIJJJJJJIJIJJJJIIJIJIJJJIIJJJJIJIIIJJIJIIJIJI;

	[IIIJJJIJIJIIJJIIIIIIJJJJJJIJIIIJIJIIJIJIIIJJJIJ]
	public bool IJJJJJJJJJJIJJJIJJJJJIIJIIJIIJJJIJJIJJJIIIJIIJI;

	[IIIJJJIJIJIIJJIIIIIIJJJJJJIJIIIJIJIIJIJIIIJJJIJ]
	public bool IIIJIIJJIJIJIIIJJJIJJJIIJJIIJIJIIIIIJIIJIJIIJJJ;

	[IIIJJJIJIJIIJJIIIIIIJJJJJJIJIIIJIJIIJIJIIIJJJIJ]
	public bool IJIJIJJIJIIIIIIIJIIJIJIJJIJIIIIIIIIJJIIJIIJIJJI;

	[IIIJJJIJIJIIJJIIIIIIJJJJJJIJIIIJIJIIJIJIIIJJJIJ]
	public bool IJIJIIIJIIJIIJJIJIJIJIJJIIIJJIIIIJJJJJIIJJIIIIJ;

	private IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIJJIJIJIJIJIJIJJIJIJJIJIIIIJJJJIJJIIIIJJJIJJII;

	public bool IJJIJJIJIIJJIIIJIIJIJJJIIIJIIJJJJIIIJIIIIIJIJJI;

	private bool IIJJJIJJIIJIJJIIJIJJJIIIJIJIIIIIJIIJIIIJIJIIIII;

	private IIJIIIJIJIIJIJIJJJIIIIJIIJJIJJJIIIIIJJIIIJJIIJI IJJIIJIIJJJJJJIIIJIJIJIJJIIIJJIJIIJIJIJJIIJJJIJ;

	private Ray IIJIJJIJIIJIIIJIJIIIIJIIIJIJIJJIIIJJJJJJIIIIJII;

	private RaycastHit JIIJIIJIJJIIIIJJIIIIJIJIIIIIIJIJJJIIJIJJIJIJJII;

	private Transform IIIJJIIIJIJIJJIJJJIIJIIIIJJJIIIJJIIIJIJJIJIJJIJ;

	private IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII IJJIJIIJIIJIIJIIIIJIIIIJJJJIIJJIJIIIIJJJIIIJJJI;

	public JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ IJJJIIJJJJIIIJIIJIJIIJIJIIIIIJJJJIJJJJIIJIJJIIJ;

	public JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ IIIJIIJJJJIJJIJIIIJJIIIJJIJJIIJJIIIJJJIJJIIJJJI;

	public JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ IJJJIIJJIIJJIIJJJIIJJJJJJJJJJJIIJJJJJJIJJIIIJII;

	private bool IIJJJIIJJJIJIJIIIIIIIJJIJJIJIIIJJIIJJIJJIJIIIJI;

	public bool JIJIJJJJIIJJIIJJIIJJIJIIIJJIIIJIJJJJIIJJJJIIIII;

	public float JJJJIJIJJIIIJIIIJJIIJIJIIIIJIJJJJJIIIIJJJIIJJJJ;

	public PlayerSounds JIIIIJIJJJJJIJIIJJIIJIIJIIIIIJIJIIIJJJJJJJJIJIJ;

	public LayerMask JIIIJJJIIJJJIJIIIIJJIJIJIJJJIIIJJIJJIIJIIIIIIII;

	public Camera JIIJJIIJIIJJIIJJIIJIIIJIJJJIIIIIIJIJJIIJJJIJJJJ;

	public Camera IJJJIJIJJJIJIJJIIJJIIIIJIIJIIJIJJJJIJIIIJJIIIJJ;

	public nTimer IIIIIJIIJIJIIIIJIJIJJIIIJIJJIJJIJIIJJJIJIJIJJJJ;

	private float JIIJIIJJIIJIIJJJIJJIIJIIIIIJJJIIIJJIIIIIJIIJIII;

	public nBoxColliderBounds IJJIJJJIJIJJIIJIIIIIJJIIJIIJIJIJIIJJJIJJIJIIIII;

	private List<FPWeaponShooter> IIIIJJJJJJJJIIJJIIIIJJIIIJIIJJJJIJJJJJIJJIIJJII;

	public void JJJJIJJIIIJJJJIIJIJJJIJJJJJJIJJJIJJIIIJJIJJIIIJ()
	{
	}

	private void JJJIIJIIJIIIIJJIIJJIJJIIIJJJJJJJIIIJIJIJJIIIJJJ()
	{
	}

	private void IJIIIIJIIJIJIIJIIIIJJIJJJIIIIJJIJIJJJIJIJJIIIII()
	{
	}

	public void IIJJJJIJJIIJJJIIJIJJJJIIIJIIIIIJIJJJIIIIJIJIIIJ(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ)
	{
	}

	private void IJIIIIJJJJIIJIIIIIIJIIIIJIIIIJIJJJIIIIJJJJIIJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public void JIJIIJJIIIJJIIJIJIIIJJJJJJIJIIJIIIJJIIJIIIIIJIJ()
	{
	}

	public void JJJIIIJJJIIJIJJJJIJJIIJIIIIJJIIJJIIIIJJJJJJIIIJ(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI, int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, bool JJIIIJJJJIJIJJIIIIJJJJJIIIIIIJJIIJIJIJIIJIIJIII)
	{
	}

	public void IIJJJJIJJIIJJJIIJIJJJJIIIJIIIIIJIJJJIIIIJIJIIIJ(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, bool IJIIIIIJIJJJJJJIIJIJIJJIJJJJIIIIJIIIJJIJJJJIIJJ, bool IJJJIIJJIIIIJIJIJJJJIIJIJIIJIJIJIIIIIIIJIIJIIII)
	{
	}

	public void JJJIJJJJIJJIJJIIIJIIIIIJIIJIIJJJIIJIJIIJJJIIJJI(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
	}

	private void JJJJJJJIIIIIIJIJJIIIIJJJIIJIIIJIIJJIIIIJIJIIJII(JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ)
	{
	}

	public void JIJJIJJIIJIJIIJJIJJJIIJIJIJIJJIJJIIJIJJIIJIJIII(bool JIIJIJJIIJIJIIIJIIIJIJJIIJJJIJIJIJIIIJIJJIJIIJJ)
	{
	}

	public byte[] JIIJJJIJIJIIIIJJIJIIIJIJJIJIJIJIJIJIJIIJIJIIJIJ()
	{
		return null;
	}

	private void IJJJIIIIIIIIIJJIIJIIIJIIJIIJJIIIIJJIJIIIJJIIJJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void JIJJIJJIIJIJIIJJIJJJIIJIJIJIJJIJJIIJIJJIIJIJIII(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI, bool JIIJIJJIIJIJIIIJIIIJIJJIIJJJIJIJIJIIIJIJJIJIIJJ)
	{
	}

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI[] IIJIIJJIIJJIIIIJIJJIIJJJJIJIJJIJIJIIJIIJIIIJJIJ(int[] JJIIJJIJIJJIJIIIJJIJIIIJIJIIIIIIIIIJIJIJIJJJIJI)
	{
		return null;
	}

	public void JJJIIIJJJIIJIJJJJIJJIIJIIIIJJIIJJIIIIJJJJJJIIIJ(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI, int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, bool JJIIIJJJJIJIJJIIIIJJJJJIIIIIIJJIIJIJIJIIJIIJIII, JJIJJIJJIJJJJIIIIJJIIJIIIIIJIIIIJJIJIIIIIIIJJJJ JJIIJIJJIIIJJIIJIJJJIJIIJIJIJIIJJJIJJJJJIJJJJJI)
	{
	}

	public void IJIJIIJJIJJIIIIJIIIIIIIJJJJJIIJJJJJJIJJJJJJIIII()
	{
	}

	private void JJJJJIJIIJJJIJJJJJIIJJIIIJIIIIJIIIIIIJJJIJJIJJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void JJIJIJIJIJIIJIJIJJIJIJIJJIJJIJJIJIIIJJIJIJJIJIJ(JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ)
	{
	}

	[CompilerGenerated]
	private void JJIJJIIJIIJIJIJIJIIIJJJIIIIIIJIIJJJJIJIIJIIIIJI()
	{
	}

	private void IJJJJIJIIIJIIJIIJJJIJJIIIIIJJIIIIIJIIJJIJIIIIJJ(JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ)
	{
	}

	private void JJJJIJIIIJJJIIJIIIJJJJIJJJJIJIJJIIJIJJJIJJJJJJJ(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI, IIJJJJJJJJIIJJIIJJIJIIJIJJIIJIJJJJJIJJIJIJJIJJI IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII, JJIJJIJJIJJJJIIIIJJIIJIIIIIJIIIIJJIJIIIIIIIJJJJ JJIIJIJJIIIJJIIJIJJJIJIIJIJIJIIJJJIJJJJJIJJJJJI)
	{
	}

	private void JIIJIIIJIIJIJJJIIIJJJIJIIIIIJJJJJJJIIJIJJIIJJIJ()
	{
	}

	private void JJJJIJIJIIJJJJIIIIJJJIIIIJJIIIJJIJJIIJIIIIIIJIJ()
	{
	}

	private void IJIJJJJJJJJIJJIJIIIJIIIJIIJIIJJJIJJJIJJIIIIIJII(bool IIIIIJJIJIJJJIJJJJJIIJIJJIJJIJJJIJJJIIJIIIJJJII)
	{
	}

	private void IIJJJIIJJIJJIIJJJIJJIIJJIIIJJJJJJJJIJIIIIJJIIJJ(bool IIIIIJJIJIJJJIJJJJJIIJIJJIJJIJJJIJJJIIJIIIJJJII)
	{
	}

	public void IIJIIIIIIJJIIIIIIJIJJIJIIIJJIJJJJJJIIIIJIJIIIJI()
	{
	}

	private void IIJIIIIJIJIIIIIIJJIIIIJIIIJIJJIIIIJIJIJJIIIJJJI(JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ)
	{
	}

	public JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ IIIJJJIIIIIJIJIIJJIJIJJJJJIIJJIIJJIJJIJJJJIIIII()
	{
		return null;
	}

	private void IIJJJJIIIIJIIIJIIJIIJIJJJIIJIJJJJIJIIJJJIIIIJIJ(JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
	{
	}

	[CompilerGenerated]
	private void IIIJIIIJJJIIIIJIJIJIJIJIJIJIJIIJJIJJIIJJJIJIIIJ()
	{
	}

	public void IJIJIIJJIJJIIIIJIIIIIIIJJJJJIIJJJJJJIJJJJJJIIII(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJJJIJIJJIIIIJJJJJIIIIIIJJIIJIJIJIIJIIJIII, int JIIIIIJIIIJIIJIJIIIIJJJIJJIJJJIJJIJIJJJJIIIJJIJ, int IJJJIIJJJJJJJIJJJJJJJJIIJJJIJJJJIJJIIIIJJJIJJIJ, int JIJJIIJIJJJJIJIJJJJIIJIIJJJJIJIJJIJJIJIIIIIIIII, JJIJJIJJIJJJJIIIIJJIIJIIIIIJIIIIJJIJIIIIIIIJJJJ IIIIIJIIJJIJJIIJJJJIJIJJIIJIJJIIJJJIJJIJJIJIJIJ, JJIJJIJJIJJJJIIIIJJIIJIIIIIJIIIIJJIJIIIIIIIJJJJ JIIIIIIIJIIIJJIJIIIIIIJIIJJIIJJJJIJJIJJIIIJIJIJ, JJIJJIJJIJJJJIIIIJJIIJIIIIIJIIIIJJIJIIIIIIIJJJJ JJIIJIJIIIIIJIIIIJJIJIIIJJIIJJJJIIIIJJIJJJJIJII)
	{
	}

	public void IJIJIIIIIJIIJJIIIJIIIJIJIIJIIJIJJIIIIJJIIIJJJIJ()
	{
	}

	private byte[] JIIJJJJIIIJIIIJIIIIIIIJJIIJIIJIIIJIJIIJJIJJIIIJ(IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI[] IIIJIJJJIJJIJIIIJIIJJJIIIIIJIJIJIIIIIIIJJJIIIII)
	{
		return null;
	}

	private void JIIJJJIIJJIIIJJJIJIIJJIJIJJJIJJJJJIIIIJIJJIJJIJ()
	{
	}

	public int[] IIJIIJJIIJJIIIIJIJJIIJJJJIJIJJIJIJIIJIIJIIIJJIJ(IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI[] JJIIJJIJIJJIJIIIJJIJIIIJIJIIIIIIIIIJIJIJIJJJIJI)
	{
		return null;
	}

	private void OnDisable()
	{
	}

	private void JJJJIJIIIJJJIIJIIIJJJJIJJJJIJIJJIIJIJJJIJJJJJJJ(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI, int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, JJIJJIJJIJJJJIIIIJJIIJIIIIIJIIIIJJIJIIIIIIIJJJJ JJIIJIJJIIIJJIIJIJJJIJIIJIJIJIIJJJIJJJJJIJJJJJI)
	{
	}

	private bool JJJIJIJIIJJJIIJIJJJJIJIIJJIJIIIIJIIIIJIIJJIJJJJ(Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII, float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ)
	{
		return false;
	}

	public void IIJJJJIJJIIJJJIIJIJJJJIIIJIIIIIJIJJJIIIIJIJIIIJ(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, bool IJIIIIIJIJJJJJJIIJIJIJJIJJJJIIIIJIIIJJIJJJJIIJJ)
	{
	}

	private void JIJJIJJJIIJJJIJIJIIJIIIJJIJJIJIIJJJIIJJJJJIIIII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void IJJJJJIJIJIIJJIJIJIJIIIJJIJJJIIIJIJJIJJIJIIIIII(JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ)
	{
	}

	public void IIIIIJIIJJIJJJIIIJJIJIJJIIIJIIIJIIIIJJIJJIJIJJI()
	{
	}

	public void JIJJIJJIIJIJIIJJIJJJIIJIJIJIJJIJJIIJIJJIIJIJIII()
	{
	}

	public JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ IIJIJJIJJIIJIJJIIJJIIIIIIIJJIIJIIJIJJIJIIJIJIJJ(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
		return null;
	}

	private void JJIJJJIIJJIIJIIJIIJIIIIJIIJJJJJJIIJIIJIJJJIIJJJ()
	{
	}

	public void IJIJIIJJIJJIIIIJIIIIIIIJJJJJIIJJJJJJIJJJJJJIIII(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJJJIJIJJIIIIJJJJJIIIIIIJJIIJIJIJIIJIIJIII, JJIJJIJJIJJJJIIIIJJIIJIIIIIJIIIIJJIJIIIIIIIJJJJ IIIIIJIIJJIJJIIJJJJIJIJJIIJIJJIIJJJIJJIJJIJIJIJ, JJIJJIJJIJJJJIIIIJJIIJIIIIIJIIIIJJIJIIIIIIIJJJJ JIIIIIIIJIIIJJIJIIIIIIJIIJJIIJJJJIJJIJJIIIJIJIJ, JJIJJIJJIJJJJIIIIJJIIJIIIIIJIIIIJJIJIIIIIIIJJJJ JJIIJIJIIIIIJIIIIJJIJIIIJJIIJJJJIIIIJJIJJJJIJII)
	{
	}

	private void IJIJJJJJJIIIJJJJIIIJIJJIJIIIIIIJJJJIJIJJJIIIIIJ()
	{
	}

	private void Update()
	{
	}

	public void JIJJIJJIIJIJIIJJIJJJIIJIJIJIJJIJJIIJIJJIIJIJIII(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
	}

	private void JIJIIIJJIJJJJIJIJIJJIJIIJIJIIJJIJIJIIJJIIIJJJJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public void IJIJIIJJIJJIIIIJIIIIIIIJJJJJIIJJJJJJIJJJJJJIIII(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJJJIJIJJIIIIJJJJJIIIIIIJJIIJIJIJIIJIIJIII)
	{
	}

	public JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ IIJIJJIJJIIJIJJIIJJIIIIIIIJJIIJIIJIJJIJIIJIJIJJ(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ)
	{
		return null;
	}

	private void Start()
	{
	}

	private void OnEnable()
	{
	}

	private void IIJJJIJJJIIJIIIIIJIJIJJIIJJIIJIJJIIJJJJIJIIJJII()
	{
	}

	public JIIIJJIJJJJJIJJJJIJIJIIJJJIJJIJIIJJJJIJJJJIJJIJ JJIIJJJJJIJJJIIIJJJJJJJJJJJJJIIIJIIJJJIJIIIJIJI()
	{
		return null;
	}
}
