using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class PoolManager : MonoBehaviour
{
	public class IJIIJJIIJIIIIJJIJIIJIJJJIIJIIIIIJIJJJIJIIJJIJJI
	{
		public GameObject JIIJJIJIJJJJJIJIJJJJJJIJIJJJJIJIJIIJIJJJIIJJIII;

		public List<GameObject> IJJIJIIJIIJIIJIIIJIIJIIJIIIJJIJJIIJJJJJJIIJIJJJ;
	}

	private Dictionary<string, IJIIJJIIJIIIIJJIJIIJIJJJIIJIIIIIJIJJJIJIIJJIJJI> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ;

	private Transform JJIJIIJIIJJJJJIIIJIIIJJJIJJJIIIIJJIJJJIIIJJIIII;

	private static PoolManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	public static int JIIJJIIJJIIIIIIJJJIJJIIIIJJIJJJIJIIJIJJIJJIJIJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public static GameObject IJIIJJIJIJIIJJIJIIJJJIIJJJIIJIIIJIJJIIIIJJIIIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, GameObject JIIJJIJIJJJJJIJIJJJJJJIJIJJJJIJIJIIJIJJJIIJJIII, Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Vector3 IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII)
	{
		return null;
	}

	public static bool JIIJJJIJJJJJJIIJJJIIJJIIJJJIJJIIIIJJIIIJJJJIJIJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return false;
	}

	public static int IIJJIIIIJIJJIIIIIIIJJJJJIJIIIJIIIIIJJJJIJJIIJJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public static void JIJJIIJJJJJJJIJIIIIIJJIIIJJIJJIJIIIJJJJIIIJJJJJ()
	{
	}

	public static GameObject IJJJIJJJJJIIJJJJJJIIIIIJJIIIIJJJJJJIIJJJJJIJIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, GameObject JIIJJIJIJJJJJIJIJJJJJJIJIJJJJIJIJIIJIJJJIIJJIII)
	{
		return null;
	}

	public static int IJIJIJIIIIIIIJJJIIIJJIJIJJIIIIIIIJIJIIIIJJIJJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public static void IIIIJIJIIIJIJJJIJIIIJJIJJJIJIJIIJIIJIJIJIIJIJJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, GameObject JIIJJIJIJJJJJIJIJJJJJJIJIJJJJIJIJIIJIJJJIIJJIII)
	{
	}

	private static void IIIJJIJJJJIJIIJIIIIIIIIIJJIIJJIJJJIIIJIJJJJIJIJ()
	{
	}

	public static bool JJIIIIJIJIJIJIJJIJIIJIJJJJIIIIIJJJJJIIJIJJJIJJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return false;
	}

	public static GameObject IJJJIJJJJJIIJJJJJJIIIIIJJIIIIJJJJJJIIJJJJJIJIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, GameObject JIIJJIJIJJJJJIJIJJJJJJIJIJJJJIJIJIIJIJJJIIJJIII, Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Vector3 IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII)
	{
		return null;
	}

	public static bool JIJIJIIIJIJJIIIJIJJIJJJJIJIJJJJIJIIJJIIIIIIJIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return false;
	}

	private static void IJJIJJJIJIJJIJIIJJIIJIIJJIIJJJJJIIIJJJJJJJJIJJJ()
	{
	}

	public static bool JJJIJJIJJIJJIIJJJJJJIIIIJJJJJIIIJJIIIIJJIIIJJJJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return false;
	}

	public static bool IIJJIIIIJIIIJIIJIIJJJJIJIJIIJJJJJJJJIIJIJJIIIIJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return false;
	}

	private Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}

	public static GameObject IJJJIJJJJJIIJJJJJJIIIIIJJIIIIJJJJJJIIJJJJJIJIII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, GameObject JIIJJIJIJJJJJIJIJJJJJJIJIJJJJIJIJIIJIJJJIIJJIII, Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Vector3 IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI)
	{
		return null;
	}

	public static GameObject IJJJJIIIJIIIJIIJJJIIJIJJIJJJIJIIIJIIJJIIJJIIJJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, GameObject JIIJJIJIJJJJJIJIJJJJJJIJIJJJJIJIJIIJIJJJIIJJIII, Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Vector3 IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII)
	{
		return null;
	}

	public static int IIIIIIJJJJJJJIJIIIJIIJJIJJJIJJIJIIIIIIIIIIJJIIJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return 0;
	}

	public static void JJIJIIIIJJIIIIIIJIJIIJJJJIJIJIIIJJJIIJIJJIJJIJI()
	{
	}

	private static void IIIJIIJJIIJJIIJIIIJJJJJJJIIIJIIJJJIJJIIIIJIJIJI()
	{
	}

	public static void IIIIIIJIJIJIIJJIIJJIJIJIJIJJIJJJJIJIJJJJJIIJJIJ()
	{
	}

	public static GameObject IJJIIIIIIIJIJJIIJIIJIJIJJIJJIIJIIIJJJIIIIJJIIJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, GameObject JIIJJIJIJJJJJIJIJJJJJJIJIJJJJIJIJIIJIJJJIIJJIII, Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Vector3 IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII, Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI)
	{
		return null;
	}

	public static GameObject IJJIJJJIJIJIIJJIJJIIIIJJIJIIIIJIJJJIIIJJIJJIJII(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, GameObject JIIJJIJIJJJJJIJIJJJJJJIJIJJJJIJIJIIJIJJJIIJJIII)
	{
		return null;
	}

	public static bool IIJJIJIIIIIJIJJJJJIIIJIIIIIJJIIIJJIIJJIIJJJJIIJ(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return false;
	}

	public static void IJIIJJIIIIJJJIJJIJJJIIIIJIJIJJJJJJIIIJJIIIJJJJI(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, GameObject JIIJJIJIJJJJJIJIJJJJJJIJIJJJJIJIJIIJIJJJIIJJIII)
	{
	}
	private Transform JJJIIJJIJJJJIJJIJJIIJIIJIJJJJIIJJJJJJJJIIJJJJJI()
	{
		return null;
	}

	private static void IIJIJJJIIIIJIIJJIJIJIJJIIIIJIJIIJIIJIIJJIJIIIJJ()
	{
	}
}
