using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using UnityEngine;

[Serializable]
public class PropertyReference
{
	[SerializeField]
	private Component mTarget;

	[SerializeField]
	private string mName;

	private FieldInfo mField;

	private PropertyInfo mProperty;

	private static int s_Hash;

	public Component target
	{
		get
		{
			return null;
		}
		set
		{
		}
	}

	public string name
	{
		get
		{
			return null;
		}
		set
		{
		}
	}

	public bool isValid => false;

	public bool isEnabled => false;

	public object JJJIJIIIIIIIIJJIIIJIJJIJJJJIIJIIIIIJIIIIJJIJIIJ()
	{
		return null;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public object IJIIIIIIIIJJIIJIJJIIIIIJIIJIIIIIJIIJJIIIIJIIIJI()
	{
		return null;
	}

	public static bool IIJJJJJJIJJJIJIJIIJJIIIJJJJJIJJIIJJIIIJIJIJJIJJ(Type IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Type JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII)
	{
		return false;
	}

	public static bool JJIIJJJJIJJJIIIIIIIIJIJIJJIJIIJIJIJIIJJIIIJJIJJ(Type IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Type JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII)
	{
		return false;
	}

	public void JJIIJIIJJJJJJJIJJJJIJIIJIIJJJJIJJJJJJIJJIIIJJII()
	{
	}

	public static bool IJIIIIIJJIIIJIIJJJJJJJIIIJJJIJIIJIIJJJJJJIIIIIJ(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, Type JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII)
	{
		return false;
	}

	public PropertyReference(Component IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, string JIIJJJJIIIJIIJIJIIIIIIIJJJJIIIJJIIIJIJIJJJIJJII)
	{
	}

	public PropertyReference()
	{
	}

	public virtual bool IJIJIJJIIJJJIIJIIJJIIJJIJJJJIJJJJIJJJJJIIJIJIJI(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}

	public void JJIJJJIJIJIIIIIIIJJJJIJJJIIIJJIIIIIJJJJJJJIJIJI(Component IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, string IJJJIJJIJIJJJJJJJJIIJJJJJJJIJIJIJIIJJIJIJIIJJIJ)
	{
	}

	public static string JJJJIJJIIJJIIIIJJJIIJJIJIIJJJJIJJJJJIIJIJJIJIII(Component IIIIIJIIIJIIIJJIIJIIJIJJJJIJIIJIJIIIIIIIJIJIJJJ, string IIJJJIIJIJIJJJJJJIIJIIIJIIJJJIJIIJJIIIJIIIJIIJI)
	{
		return null;
	}

	public override bool Equals(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
		return false;
	}

	public void JJJIIIIIJJJIIJJJJJJIIJIJJIJIIJIIJJJIIJIIJJJIIIJ()
	{
	}
	public void IIJJJIJIIIIIIJIIIJJIIIJJJIIIJIJIJIIJIJJIIJJJIIJ(Component JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual string JIJJJIJJIJIIIIIJIIIJJJIIJIJIIIIJIJJIIJJIIIJIJJJ()
	{
		return null;
	}

	public void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public bool JJIJJJIJIJIIIIIIIJJJJIJJJIIIJJIIIIIJJJJJJJIJIJI(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return false;
	}

	public static bool JJIIJJJJIJJJIIIIIIIIJIJIJJIJIIJIJIJIIJJIIIJJIJJ(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, Type JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII)
	{
		return false;
	}

	public override string ToString()
	{
		return null;
	}

	public Type IIIIIJJIIJIJIJIJIIIIIIIIIIIIJJIJJJIIJJJIJJJJJJJ()
	{
		return null;
	}

	public static bool JJIJIJJJJJJIJJIIIIJIJJJIIJIJIIJIJIJJIIIIJIJJJJI(ref object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, Type IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Type JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII)
	{
		return false;
	}

	public override int GetHashCode()
	{
		return 0;
	}

	public void IIIJIIJIIJIJIIJIIIJIJIIIJJIJIIJIIIJIIIJIIJJJJJI()
	{
	}

	public virtual string IIJIJIIIIJJJJIJIJJIJJIIIJIIIIJIIIJJJJJJIIIIJJJJ()
	{
		return null;
	}

	public static string IJJIJIJJIJIIIJJIJJIIJJIIIJJIIIJJIIIJJIJIIIIJJIJ(Component IIIIIJIIIJIIIJJIIJIIJIJJJJIJIIJIJIIIIIIIJIJIJJJ, string IIJJJIIJIJIJJJJJJIIJIIIJIIJJJIJIIJJIIIJIIIJIIJI)
	{
		return null;
	}

	public static bool JJIIJJJJIJJJIIIIIIIIJIJIJJIJIIJIJIJIIJJIIIJJIJJ(ref object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, Type IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, Type JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII)
	{
		return false;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	private bool IIIJIIIJIIJIIIJIIJJJIIIJJJJJJIJIIIJJIIIJIJJJJJI()
	{
		return false;
	}

	public static bool JJIIIIIIJIJJJIJIIIJIIJJJJIIJIIJJJIJIIIJJJIJJJII(object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, Type JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII)
	{
		return false;
	}

	private bool IJIIJJIIIIIJIIIIIIJIJJIIIIIIJJIJJJJJJIIIIJJJIII(ref object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return false;
	}

	public Type IIIIJIJJJJIJJJJJJJJJIIIIJJJIJIJIJIIJIIIJJIIIIJJ()
	{
		return null;
	}

	private bool JJIIJJJJIJJJIIIIIIIIJIJIJJIJIIJIJIJIIJJIIIJJIJJ(ref object JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
		return false;
	}
}
