using UnityEngine;

[ExecuteInEditMode]
public class PropertyBinding : MonoBehaviour
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JJJJIIIIIJJJJIJIIIIJIIJJIJIJIJIJJJJIJJIIJIJJIJJ
	{
		OnStart = 0,
		OnUpdate = 1,
		OnLateUpdate = 2,
		OnFixedUpdate = 3
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JIIIIJIJIIJJJJJJJJJIIJIJJJJJJIJJJJJIJIJJIIJIJJJ
	{
		SourceUpdatesTarget = 0,
		TargetUpdatesSource = 1,
		BiDirectional = 2
	}

	public PropertyReference IIJJIJIJIIJIIJIIIIJIIIIIJIJIIIIIIIIIIJIJIJIJJIJ;

	public PropertyReference IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

	public JIIIIJIJIIJJJJJJJJJIIJIJJJJJJIJJJJJIJIJJIIJIJJJ IJJIIIIJIIJJJIIJJJJIJIIJIJJJJIIJJJJIJJJJIJJJJJI;

	public JJJJIIIIIJJJJIJIIIIJIIJJIJIJIJIJJJJIJJIIJIJJIJJ IJIIIIJJJJIIIJIIIIJIJIIIJIJJJIIJJJJIIJIJIJJJIJI;

	public bool IJIIJJIIIIIJIIJJJJIJJJIJIIIIIIJJIJJJIIIIJJIJIIJ;

	private object IJIJIIIIJJIJJIIJJJIJIIJJJJJIJIJJIIJIIJJJJJIJJJJ;

	private void JIJIIJIJIIJJJJJIIJJIJJJIIJIJIIJIJIJJJIIJJJIIIJJ()
	{
	}

	private void JJJIIIIIJIJIIJIJIJIIIJIJJIJJIJIIJIJIIJJIIJJJJJI()
	{
	}

	private void JJIIIJIJIJJJJIJJJIIIIJIJJJIJJIJJJIIIJIIIIJIJIJI()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	public void IJIIIIIIJIJJIJIIJIJJIJJIIIJIJJIIIJJJIIIIIJJIJIJ()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	private void JIIJJIIJIIJIIJIIIIIJIJJJIIJJJJIJJJJIJJIIJJIJJJI()
	{
	}

	private void LateUpdate()
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void Update()
	{
	}

	private void JJIJJJIIIIIJIIIIIJIIJIIIJJJIIJJIJIJJJJIIJJIJJII()
	{
	}

	private void OnValidate()
	{
	}

	private void FixedUpdate()
	{
	}

	public void JJJJIJJJJJJIIIJJJJJIIIIIJJIIJIJJJIJJIIIIIIJJIJJ()
	{
	}

	private void JIJJJJIJIIJJJJIJIJIIIJIIJJIJIIJJIJIIIJIIIIIJJJI()
	{
	}

	private void Start()
	{
	}

	private void JIIIJIJJIIJIJJJIIJJJIJJIJJJIJJIIJIIJIIIIJJIIIIJ()
	{
	}
}
