using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Photon;
using UnityEngine;

public class PushMode : Photon.MonoBehaviour
{
	private sealed class IIJJJIJIIJIJJJIJIIJJJIJJJIJIIIIIIJIIJJIJJIIIJJJ
	{
		public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII;

		public PushMode JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		internal void IIJJJIIJIJJIIIIJJIIIJIIIJIIJJJIJJIJJJJJIJJIIIJI()
		{
		}

		internal void JIIIIJIIJIJJJIIJIIJIJIIJIIIIIJIIJIJIJJIIIJIIIII()
		{
		}

		internal void IJJIJIIIIIIJJIJIIIIJJJJIIJIJIJIIIIIIIIIJIJIJIJJ()
		{
		}

		internal void JIJIIIIIJIJIJJIIJIIJIJIIJJIIJJJJJIJIIJJIIIIJIIJ()
		{
		}

		internal void IJJJJJJIIIJIIJIJJJIJJIJJIIJIJIJIJJJIIIIJJJIIIII()
		{
		}

		internal void JIJIJIIIJJIIJIIJJIIJJJIJIJIJIIIIJIIJIIJJJIIJIIJ()
		{
		}

		internal void IJJJJIIIIIIIIJJJIIIJJJJJIJJIIJIJIIJIIIIJIJIIJIJ()
		{
		}

		internal void JJJJJJJJIJIJIIIJIJIJJIIJIJJJIIIJIJJJIJJIJJJIJII()
		{
		}

		internal void IIJIJIIIIIIJIIJIJJIJIIIJIJIIJIIIIIIJIIJIIIIIIJJ()
		{
		}

		internal void JIJIIIJIIIJIIJJJJJJJJJJIIIIIIJJJIIIIJIJIIIIJJIJ()
		{
		}

		internal void IIJJJJIJIJIJIJJJJIJJIIJJJJJJIJJIIIIIJIIIIIJJIII()
		{
		}

		internal void IJIJJIJJIJJIJIJJJJIIIIIJJJIJJIJJIJIIIJIIIIJIIII()
		{
		}

		internal void IJIJJIIJIJIIIJIIIJIIIJIJIIIJJJIJIIIJIJIIIJJJJIJ()
		{
		}

		internal void JIJIJJJJJJIJJIIIIIIJJIIJJIJIIIIJJJJIJJJJJIJJJIJ()
		{
		}

		internal void IJIIIIJIJIIJIIJJJJIIIJJJIIJIIIJIIJJIIJIJIIIIIJJ()
		{
		}
	}

	private sealed class IIIIIIJIJIJJJJJJJJIJJIJJIJIJJIIJJJIIJIJJJJIJIJI
	{
		public byte IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ;

		public PushMode JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		internal void IJIIJIIIJIJIIIIJIJJJJIJIIIIJJJIJJIIJJIIJJJIIIII()
		{
		}

		internal void JIJIJJJIJJJIIIJIIIIJJIIJIIJIJJJIJIIIJIIIIJJJIJI()
		{
		}

		internal void IJIJJIIIIIIJJIJIJIJJJJIJIJIIIJJIJJJIJJIIIJIJIJJ()
		{
		}

		internal void JJJJIJJJIIIIIIJIIIJJJIIIJIJIJJJJIJJIJIIJJIIJIJJ()
		{
		}

		internal void IIIIJJIJIJIIJIJIJIJIIJJJIJIJJJJJJJIJJJJIJJIJIJJ()
		{
		}

		internal void JJJIIIJJIIJJJJJJJJJJIJIJJJIJIIJJJIIIJIIIIIIIIJJ()
		{
		}

		internal void JIIJIJIJJJJIJJIIJIJIIIIIIIJIIJJIIJJJIIJIIJJIIIJ()
		{
		}

		internal void JIIIJJIJIIJJIIIJIIIIJIJIIIJIJIJIJJJIJIIJJJIIIJI()
		{
		}

		internal void IJIJIJIJJIIIJJJJJJJJJJIJIIJIIIIJJIIJJJJJIIIIIII()
		{
		}

		internal void IJIJIIJJJIIIJIIJJJIIIJIIJIIJJJIIJJIIIIIIJIJIIJJ()
		{
		}

		internal void IIJJIJIJIJJJJIJIJJIIJJIIJJIJIIJJJIIIIJIJIIIJIII()
		{
		}
	}

	public GameObject[] JIJIJJIJJIIIIIIJJJJIJIJIIJIIIIIJJJJJJJJIIJJJIJI;

	private List<byte> JJIIJIIIIJJIIIJJJJJJJIJIJJIIIIIIJIJIJIIIIJJIJII;

	private List<byte> JIJIJJJJIIJIJIJIJJJJIJJIIJJJJJJIJJIIIIIIJJJIJJJ;

	public Material IJJJIJJJIJJJIIJIIIIJJJJIIJJIIIJJIJIJIJJJJIJJJJJ;

	public Material IJIIJIJJJIJJIJJIJIJIJJIIJIIIIIJJIJIJIIJJIIIIIII;

	private int IJJJJIJIIIJJJIJJIIIJIJIJJJJIIJJIJIIJJIIJJIJJJJI;

	private int JJIIJIIIJJIIIJIIIIIJIIIIJJIIIJJJIJJIJJIIJIJIJJJ;

	public void JJIIJIJJIIJIJJJIIIJIIIIJJJJIIJJIIJJJIIJJIJJJJII()
	{
	}

	private void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIJJJJIIJJIIJIJIJIJJIIJJIIJIIJJJIIJJJJIJJIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJJIJIJJIJIIJIJIJIIIJIIJJIIJIIJIIIJJJJJJIIIIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJJJIJJJJJJIJJIJJJIIIJJIIJIJIIJIIJIJIJIJIIIIJJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void IIJJIIIJJJJJIJJJIJIIIIIIJJJJJJIIIIIIJIIIIJJIIJJ()
	{
	}

	private void IIIIJJJIJIIIIJIIIIJIIJIIIIJJJJIIIIIIIIIIJIIIJII()
	{
	}

	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII()
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void IIIJIIIJIIJIJIIJJIJJIJIIIJJIIIJIIIJIJJIJIJIJJII()
	{
	}

	private void IJIIJIIIJJIIIIJIJJJIJJIIJIIIJJIIIIJJIIJJIJIIIJI()
	{
	}

	private void IJJJJIIIIJIIIIIJJIIJIIIJIJJJJJJJJJIIJIIIIIIJIJJ()
	{
	}

	private void JIJJIJIJIIJJIIJIIIIJIJIJJJIJJIJJIIJIJJIJIIJIJII()
	{
	}

	[CompilerGenerated]
	private void JJJJIJJIJJIIJJJJIJIJIJIJIJJIJIJJJIJIJJJIIIJIJJI()
	{
	}

	private void JJIIJIIJIJJIIIIIJJIJJIJIIJIJJIIJJJIIJJIJIIJIJIJ()
	{
	}

	[CompilerGenerated]
	private void IIIJIIJJJJIJIJIIJJJJJJIJJJJIJIJJIIIIIJJJIIIJJJJ()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void JJJJIIIJJJIJIJJIJJJJIJJJIJJIJJIIJJJIIIIIIIJIJIJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIJJJIJJJJIJIJIIJIIJJJIIJIJIIIIIJIJIJIJIJIJJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJIIIIJJIIIJJIIJIIJJJIIIJJIIIJJIIIIIIIIIIJIJJIJ()
	{
	}

	private void OnDisable()
	{
	}

	private void OnEnable()
	{
	}

	[CompilerGenerated]
	private void IJIIJIIIJJJJJJJIJJIIJIIJIJIIJIIIJJIIJIJJJIIIIII()
	{
	}

	private void IJIJIIIJJIIIJJIIIIIIIJJJIJIJJJJIJIIJJIJJJIIJJJI()
	{
	}

	private void JIIIIJIJIJIIJIIIIJIJJIIIIIIIIJJJJIIJIJJJJIIJIII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIIIJJJJIJIIIIJIIJJJJJJJIJIJJIIIIIIJIJIIJIJIII()
	{
	}

	private void IJIJIJJIJJJIIJJIJJJJJIIJJIJIIIIJIIJIIJIJJJJJJJI()
	{
	}

	private void Start()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJIJIIIIIIIJJJIJJIIIJJJIIIIJIJIJJIIJJJJJIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	[CompilerGenerated]
	private void JJJIIIIJJIJJIJJIJIJIIIIIJJIJIIIJIJIJIJIIJJJJJIJ()
	{
	}
}
