using UnityEngine;

public class RadiationTrigger : MonoBehaviour
{
	public JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJJIIIJJJIIJIJIIIIIIIJJJJJJIIIJJIIIJIIIJIJIJJJ;

	public int JJIJJIIJJJJIIIJJIJJIJIIJIJIJJIJJIIJIJIIJIJIIJIJ;

	public int IJJIIJJIJJJIJIJIIJJJIIIIIJIJJJJJJIJIJIIIIIIJJII;

	public float IIJJIJJJJIJJJIJIIIIIJIIJJIJIJIIJIIIJJJIJIJJIJJJ;

	private BoxCollider IJJIJIJJJJJJJIIIIJJJIJJJJJJIIJIIIIIJJIIIIJIJJJJ;

	private Bounds JJIJIIJJJJJIJJJIIIIJIIIIIJIJIIIJIJIIJIIIIJJJJJJ;

	private void JIJJIJIIJJIJJIJIJJIJIJIJJJJIJJIJJIIIJJJJJIIIIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIJJIIIJIIIJJIIIJIJJJIJIIJIIIIIJJJIIJIIIJJIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIIJJIIJIJJIIJJIJIIIJIJIJIJJIIJJJJJJIJIIJJIJIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void JIJIIJJJJJJIJIJJIJJJJJIJJJJJJIIJJIIJIJIIJJJIJIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void JJJJJIJJIIIJJIIJJIIIJIIIIIJIIJIJJIIJJJIIIJIIJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIJIJJIIJIIJJIJJJIIIIJIIJIIIIJIJJIJJIJIIIJIJI()
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void OnTriggerExit(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJJJIJIJIJIIJIJJJIJIJJIIIIJIIJJIIJJJIIJIJJJIJJ()
	{
	}

	private void IJJIIJJIJJIJIJJIJJIIJIIJIJJJIJJIJJJIIIJIJJIIJJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJJIIIJJIJIIJIIIJJJJIJIIIJIJIIJJJJIJJJIJJIIJJII()
	{
	}

	private void JIJJIIIJIJIIJJIJIJJJIIJIJIJJJJIJJJJJJJIIJJIJJJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void JIJIIJJIIIIIIJIIJIJIIJJIJJJIJIJJJIJJJJIIJJJIJJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void Start()
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void IIIIJJJIJIIIIIIJIIIIIJJIIJJJJJIJIIJJIIJJIIJIIJJ()
	{
	}

	private void IIJIIIIJIJJIJIJIJJJIJIIIJIJIJIIJJJJIIIJIIIJIIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}
}
