using System.Runtime.CompilerServices;
using Photon;

public class RandomMode : MonoBehaviour
{
	private sealed class JJJJIJJJIJIJIJJIJIJJJIJJJJJIIIIJIJIIIJJJJIJJIJI
	{
		public PlayerInput IJIIJJJJIJIJJJJIJIJJJJIJIIIIJIIIJIJJIJJIJJIIIIJ;

		public JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JIJIJIIJIIIIJIJIIJIIJIJJJIJJIIJIJJJIIIIIJJIJJIJ;

		internal void JIJJIJJJJJJIJJIJJIIJIJJJJIJJJJJIIJJIIJIJIIIIJIJ()
		{
		}

		internal void JIIJJIJIIJIIIJJIJIIJJIJJJJIIJJIJIIIJIJJJIJIJJIJ()
		{
		}

		internal void JJIIIJIJIIJIJIJIJIIIJIJIIIIJIIJJIJJJJJIJJJIIJJI()
		{
		}

		internal void JJIIJIIJIJJJJIJIIIIIJIIIIIJIJIIIJJJIIIIIIIJIJII()
		{
		}

		internal void JJJJIIIIJIJJJJIIIJJIJJJIJIIJIIIIIIIIJIJJIIJIIJJ()
		{
		}

		internal void JIJJIIJJJIIIJJJJJIIJJIIIJIIIJJJIJIJIJJJIJIJJJII()
		{
		}

		internal void JIJIJIIIJJJJJJIIIIIJJIIIJJJIJJIJIJJJIIJIJIJJJII()
		{
		}

		internal void IIJJIJIJJIJJJJIIIJIJIJIIIJJJJJIJIIJIIIIJIJIIIIJ()
		{
		}

		internal void IIIJIJIIJIIIIJJIIJIIJIIIJIIJIIJJIJIJIIIJJJIJIJI()
		{
		}

		internal void JIIIIIIJJIIIIJIIJIJIIIJIIJIJIJJIJIJIIJIIIJIIIJJ()
		{
		}

		internal void JIIIIIIIIIJJIJJJIIIIJIIIJIIJJJJJIIJJIIJIJJIIJIJ()
		{
		}

		internal void JJIJIIJJIIIJIJIIJJIJIIIJIIIJIIJIJIIIJJJIJIIIJJJ()
		{
		}

		internal void JIIIJIIJJIJIIJJIJIIJIJJIJIJJIIJIJJIIJIIIJIIJJJI()
		{
		}

		internal void JJJIJIJJJJIIJJJJIJIJJIIIIIIIIIJJJIIJJIIJIIJIIJI()
		{
		}

		internal void IIIIIIIJIJIIJJJJJJIIJIJIIIJJJIIIIIIIIIJJJIIJIII()
		{
		}

		internal void JIJJJJIJJJIJIIIIJJIIJJJIIIIJIJIIJJJJIIIIJIIJJJJ()
		{
		}

		internal void JIJIIIIIIIIIJIJJJJJIJIJJIJJIJJIIIIJIIIIJIJIJJJJ()
		{
		}

		internal void IIJJJIIJIJJIIJJJJIJIJIIIIIJIIIJJIJIIJIIJJIJIJJI()
		{
		}

		internal void IJJJIJIIJJIIJIIIJIIJJJIJJIIJJIIIJJJIIIJJJIJIIII()
		{
		}
	}

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IIIJIJIIJIJJIJJJIJJIIJJIIIJIJIJIJJJIJJIJIJJIIII;

	private void OnEnable()
	{
	}

	[CompilerGenerated]
	private void IJJJIIIIIIIJIJIJJJJIIIJJIJIIIJJIJIJJIIJJIIIIIII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIJJIIIIIJJJJJIJIJJIIIIIIIJJIJJJJJIJIIIJIJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void Awake()
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void JIIIJJJJIIIJJJIJJIJJJJIIIJIIIIIIJIIJIIIIIIJIJII()
	{
	}

	private void JIJJJJJIIIIJIIIJIIIJJJJIJIJJJIIJIJIIIJJJIIJIJIJ()
	{
	}

	private void JIJJJJIIJIJIIJIIIIIJIIJJIJIIJIJJIJJIJIJIIIIIJII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void IIIIIJIIJJJIJJJJJJJIJJIIIIIJJIJIJIIIJIIIJIIJIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJIIIIJJIJJIJJJIIIIIJJJJJIIIJJIIJIIJJJIJIJJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJIIIJJJIIJIIIIIJJIJIJJJJIIIIJIIIIIJJJJIIJIJIIJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	public void IIJJJJIIJIJIJIJJIJJIJJJJIIJJJJJJIJJIIJIJIIIIJIJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void JIIJIIJJIIJJIIIJIJIIIJIJJIIIIJJIJIJIJIJJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIIIJIIIJJJJJJIJIIIIJJJJIIJIIIJJIJIJIIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnDisable()
	{
	}

	private void IIIIJJIJJIIJIJIIIJJJIIIJJIJJJJJJIIJIJIIIIJIIJII(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void IJJJJIJJIJJIIJJIJIJIJIIJJJJIIIJJJJJIJIJIJIJJJII()
	{
	}

	private void IIJJJIIIJIIJJJIJJIIIIIIIIIIJJIIJIIIIIJIIIIJJIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIIIIJIIJJJIIJJIIIIIIIJJIIJIJJJIIJJJJIIIIIJJJIJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void JJJIJJJIJIJJJJIJJJJIIIIJJIIIJJJIJJJIIJJIJJIIJII(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void IJJJIIIJIJIJIJJJIIIIJJIIJIJJIJJIIJJJIIJJJIJIJII()
	{
	}

	private void JJIIJJIJJJJIIJIJJJIJIJIIIJJIIIJJIIIJIIJJIJIIJJJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void Start()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}
}
