using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Photon;
using UnityEngine;

public class RocketJump : Photon.MonoBehaviour
{
	[Serializable]
	public struct IIIJIJIJIIJIIJJJJJIJJIIJJJIIIJIJIJJIIIIIJIIIIII
	{
		public GameObject IIIIJIJIIIIIIIIJJJIJJIIJIIJJJIIIIIJIJIJIIIIIJII;

		public Transform IJJJIJJJJJIIJJJJJJIIIIIJJIIIIJJJJJJIIJJJJJIJIII;
	}

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JJIJJIIJJIJJIIIJJIJIIIJIJJIJIIIJIJJIIJIJJJIJJJI;

	public List<IIIJIJIJIIJIIJJJJJIJJIIJJJIIIJIJIJJIIIIIJIIIIII> IIIIIJIIJIIIJJJIJIJJIIJJIIJIIJJIJJIJIJIIIIIIJJJ;

	private float JJIJIJIJJJIIIJJJJIIJIIIIIIIIIIJJIIIIIIJIJIIJJIJ;

	private byte JJJIJIIIJIIJJJIJIJJIJIJJIJIJIJIJIJJIJIJIJIJIJII;

	private PhotonView JJJIJJIJJJJJIIIIJJIJIIJIIIIJJJIJIIIIJIIIIJIJJIJ;

	[CompilerGenerated]
	private void IIIIJIJJIJIJIIIIJIIIIIIIJIJJIJJJJIJJJIIIIJJJIIJ()
	{
	}

	private void IJJJIIJJJJJJIJIIJJIIJJJIIJJJJJJJIJIIIJJIIIJIIJJ()
	{
	}

	private void IJJJJIJJJJIJIJJIIJIJJIIIJJJJIJIIIJIIJJJIJIJIJII()
	{
	}

	private void IJJJIJJIIIJIJJIIIJIIJJJJIIJIJJIJJIIJIJIIIIJIIJI()
	{
	}

	private void JJJJIIIIIIJJJIJIIIJJJJIIJJIJJJJJIJJIIJIIIJIJIII()
	{
	}

	private void JJIIIJJIJJJJIJJIJIIJJIIIJJJIIIJJIJJIJJJIIJIJIJI()
	{
	}

	private void JIIJIJIJIIIJJJJJJJJJJJIIIIJJIJJJIIJIJJIJIIJIJIJ()
	{
	}

	private void JJIJIIJIIIJJJJIJJJJIIJJJJIIIJJJJJJJIIIIJJJIIJIJ()
	{
	}

	private void IJIIIJIJIJIJIJJJIJIIIJJIJIJIIIJIJIIIJIJJIIIIJJJ()
	{
	}

	private void IIIIIJJIJJIIJJJJIJIIIIJIJJJJJIJJIIIIJJJIIJIIIII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void JIIJJJJIIIJIIJJIJIIIIJJJJIJIIJJIJJIIJIIJIJIJIJI()
	{
	}

	private void JIJJJJIIJJIIJJIIJJJIIIIIIIJIIJJJIIIJIIIJIIJJIIJ()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void JJIJJJIJIIIIIJJJIJIJIJIIIIIIIIJJJJJJJIIIIIJIJJI()
	{
	}

	private void Start()
	{
	}

	private void IIIJJIJJJIJJIJJIJJJJIIJIIIIJIJJIIIIJJIIIIIJJJII()
	{
	}

	private void JJJJIJJIJJIIJIIJJIJJIIIJJIIJJJJJJIIIJJJIIIJIIII()
	{
	}

	[CompilerGenerated]
	private void JJIJJIIIJJIIJIJIIJJIIIIJIIIIIIJIIIJJJJIJJIIJIJI()
	{
	}

	private void JIJIIIIIJJIJJIIIIJIJIIJIIJJIJIJIIIJJIIIIJJIIIJJ()
	{
	}

	public void JJIIJJJIIIIIJJJIJIJJJIJIJJIJIIJIIIIJIIJIJIJIJJI()
	{
	}

	private void IJJJIJJIJIIIIIJJIIJIJJJIJIJIIJIIIIJIIJJIJIIIJJJ()
	{
	}

	private void IJJJIIIJIJIJIJJJIIIIJJIIJIJJIJJIIJJJIIJJJIJIJII()
	{
	}
}
