using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using ExitGames.Client.Photon;
using UnityEngine;

[Serializable]
public class ServerSettings : ScriptableObject
{
	public enum JIIIJIIJJJIJJIJJJIIJIIJIIIIIIIIIJJJJIIIJIIIJIIJ
	{
		NotSet = 0,
		PhotonCloud = 1,
		SelfHosted = 2,
		OfflineMode = 3,
		BestRegion = 4
	}

	public string AppID;

	public string VoiceAppID;

	public string ChatAppID;

	public JIIIJIIJJJIJJIJJJIIJIIJIIIIIIIIIJJJJIIIJIIIJIIJ HostType;

	public IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII PreferredRegion;

	public JJIIIJIJJIIJIJJIJJJIIJJIJJJIJJJIJIJJIIJJJJJJJJI EnabledRegions;

	public ConnectionProtocol Protocol;

	public string ServerAddress;

	public int ServerPort;

	public int VoiceServerPort;

	public bool JoinLobby;

	public bool EnableLobbyStatistics;

	public IJIJIJIJJIJJJIJIJIIIIIIJJJIJJJIJIJIJIJJIJJJIJIJ PunLogging;

	public DebugLevel NetworkLogging;

	public bool RunInBackground;

	public List<string> RpcList;

	[HideInInspector]
	public bool DisableAutoOpenWizard;

	public static IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII BestRegionCodeInPreferences => IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII.eu;
	public static IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII IIIIJJJIJIIIIIJJIIIIIJJIIJJJIJJJIJIJJJJJJJJIJJI()
	{
		return IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII.eu;
	}
	public static IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII IIJIIIJIIIIJIIJIJIJIJIIIJIIJIJJJJIJIIJIIJIJJJIJ()
	{
		return IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII.eu;
	}

	public void IIJIIJIIIIJIJIIIJIIJIJJJJIJIJIJJJIIIIIJIIJIJIJI(string JIIIJJJIIJIJIIJJIIIJIIIJIJIJIIIJJIIIJJIJJIIJIII, int IIJJIIJIIJJIIJJIIJJJIIJJIJJIJJJJJJJIJJIJIIIJJJI, string IIJJIJJJIIJIIJIJJIJJJIIJIJIJJIJIJJIIJJIIIIJIIIJ)
	{
	}

	public void IIJIJJIIIJIJJJJIIIIIJJIJJIJJIJIJJJJJIIJIIIJIIJJ(string JIIIJJJIJIIIJIJIIIJJIJIJJJJIIJIIJIJIJIIIIIIIJIJ)
	{
	}

	public void IJJJIIJJJJJIJJJJIJJJIJIJIIIIIIJJIIIJIIIIJIJJIJI(string JIIIJJJIIJIJIIJJIIIJIIIJIJIJIIIJJIIIJJIJJIIJIII, int IIJJIIJIIJJIIJJIIJJJIIJJIJJIJJJJJJJIJJIJIIIJJJI, string IIJJIJJJIIJIIJIJJIJJJIIJIJIJJIJIJJIIJJIIIIJIIIJ)
	{
	}

	public virtual string IIJIJIIIIJJJJIJIJJIJJIIIJIIIIJIIIJJJJJJIIIIJJJJ()
	{
		return null;
	}

	public void IIJIJIIIJIJJJJIJJIJIJJJIIJIJJIJJIJJJJIIIJJJJJJJ(string JIIIJJJIJIIIJIJIIIJJIJIJJJJIIJIIJIJIJIIIIIIIJIJ)
	{
	}

	public void IIIJIIIJIIJIJIJJIJIJIIIIJIJIJJIJJIIJIIIIIJJJJJI(string JIIIJJJIJIIIJIJIIIJJIJIJJJJIIJIIJIJIJIIIIIIIJIJ)
	{
	}

	public void JJIIJJJJJIJJIIJJIJJJIIJJIIIJJJJIJJJIJJIJIIJJJIJ(string JIIIJJJIIJIJIIJJIIIJIIIJIJIJIIIJJIIIJJIJJIIJIII, int IIJJIIJIIJJIIJJIIJJJIIJJIJJIJJJJJJJIJJIJIIIJJJI, string IIJJIJJJIIJIIJIJJIJJJIIJIJIJJIJIJJIIJJIIIIJIIIJ)
	{
	}

	public void IIJIIJJIJJJIJJIJJJIJIIIJIIIJJIIIJJJIJIIJJJIJIII(string JIIIJJJIJIIIJIJIIIJJIJIJJJJIIJIIJIJIJIIIIIIIJIJ)
	{
	}
	public static IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII IJJJIIJJJIIIIIJIIJIJIJIIIJIIIJIJIIIJIIIIIIJJIIJ()
	{
		return IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII.eu;
	}

	public static void JJIIJIJIJJJJIJIJJIIJJIIJJIIJJIIJJJIJIJJIIIIIIIJ()
	{
	}

	public static void JIJIIIJIIJJJIJJIIIJIJJIIJJJIJJIJJIIIJIJIIIJJJJI()
	{
	}

	public void IJJIIJJIJJJJIIIJIJJIJJJJJJIIIJIJIJJIJJIJIJIIJJI(string JIIIJJJIJIIIJIJIIIJJIJIJJJJIIJIIJIJIJIIIIIIIJIJ)
	{
	}

	public static void JIIIJIJJJJJJIJIIJJJIIIIIJIJIIJIIJJIJJIJJJJIJIJI()
	{
	}

	public void IIJIJJIIIJIJJJJIIIIIJJIJJIJJIJIJJJJJIIJIIIJIIJJ(string JIIIJJJIJIIIJIJIIIJJIJIJJJJIIJIIJIJIJIIIIIIIJIJ, IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII IJIJJIIJIIIJJIIIJJIJIIJJJJJIJJIIJJIIJIIJJJIJJJI)
	{
	}

	public static bool IIIIIIIIIJIJIIIJJJJJJIJIIJIJIJIIIIIIJJJIIJIJJJJ(string JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
		return false;
	}

	public virtual string IIJJIJJJJJIIJIIJIJIIIJJIJJIIIJJJIIJJJIIIIIIIJII()
	{
		return null;
	}

	public void JJJIIJIIJIIJIIIIJIIIIIIIJJJIIJJJIIJJJJIJJIIIIJJ(string JIIIJJJIJIIIJIJIIIJJIJIJJJJIIJIIJIJIJIIIIIIIJIJ)
	{
	}

	public void JIJIIIIIIIJJJIJIIIJJIIIIIJIIIIJJIIJIIJJJJJJJIII(string JIIIJJJIJIIIJIJIIIJJIJIJJJJIIJIIJIJIJIIIIIIIJIJ)
	{
	}

	public override string ToString()
	{
		return null;
	}

	public static bool IIJIIJJIIIIIIIJJJJIIJIIIJJIJIIIIIIJIJIJJIIJIIJI(string JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
		return false;
	}

	public void JJIJJJJIIJIJJIIJIJIJIJIIJJJJIIJIJIIJJIIJJJJIIIJ(string JIIIJJJIJIIIJIJIIIJJIJIJJJJIIJIIJIJIJIIIIIIIJIJ, IJJIIJJIIJIJJJJIIJIJIIJJIIJIIIIJIJIJJIJJIIJIIII IJIJJIIJIIIJJIIIJJIJIIJJJJJIJJIIJJIIJIIJJJIJJJI)
	{
	}
}
