using System;
using DG.Tweening;
using UnityEngine;

public class ShootingRangeTarget : MonoBehaviour
{
	[Serializable]
	public class IIIJJJJJJJIIJJJJJIJJIIIJJIIJIJIIIIJJJJJIIJJJJJI
	{
		public bool JIJIJIJJJIJIIIJIIIJIIJIJIJIIIIIJJIIJJJJJIJIJJIJ;

		public Vector3 JIIIJIJJJIIIJJIJJIIIIJJIJJIIJJIIIIJJIIIIIJIIIJJ;

		public Vector3 JIJIIJIIJJJJJIIJJJIIIIJJJJJIIJIIIIIJJJJJJJIIIII;

		public float JJJIIJJIIIJJJIJJIIJJJJIJIJJJJJIJIJJIIIJJJJIJJII;

		public bool IIIJIJIIJJIIIJJJJIIJJIJIJIJIIJJIIJJJIJJIIJIIJII;

		public Tweener JJIIIIJIIIIIJJIJJJJJJJJJIIJJIJIJJIJJIJIIIJIJIII;
	}

	[Serializable]
	public class IIJIIIJIIJIJIIIJIJJJJIJJJJIJJJJJIIJIJIIJJIJJIJJ
	{
		public bool JIJIJIJJJIJIIIJIIIJIIJIJIJIIIIIJJIIJJJJJIJIJJIJ;

		public Vector3 JIIIJIJJJIIIJJIJJIIIIJJIJJIIJJIIIIJJIIIIIJIIIJJ;

		public Vector3 JIJIIJIIJJJJJIIJJJIIIIJJJJJIIJIIIIIJJJJJJJIIIII;

		public float JJJIIJJIIIJJJIJJIIJJJJIJIJJJJJIJIJJIIIJJJJIJJII;

		public Tweener JJIIIIJIIIIIJJIJJJJJJJJJIIJJIJIJJIJJIJIIIJIJIII;
	}

	[Serializable]
	public class JIIJJJJJIIIIJJJJIJIIJIJIJJJIIIJIIIIJJJIIJJIIJJI
	{
		public bool JIJIJIJJJIJIIIJIIIJIIJIJIJIIIIIJJIIJJJJJIJIJJIJ;

		public Vector3[] JJIIJJIJIJJIJIJJIJJIIJIIJJJJIIIIIIIIJIIIJIJIIJI;
	}

	public ShootingRangeFreeFire IIIIIJIJIJIJJJJIJIJIJIJJIIJIJIIIJJIIIJIJIJJIIJJ;

	public IIIJJJJJJJIIJJJJJIJJIIIJJIIJIJIIIIJJJJJIIJJJJJI IIJIJJJIIJIJIJIIJJIJJIIIIJJJIJJIJJIIJIJJJJIIIII;

	public IIJIIIJIIJIJIIIJIJJJJIJJJJIJJJJJIIJIJIIJJIJJIJJ JJJIJIJJIIJJJIIJJJIIJJJIJIJJJJIJJJIIIJIJIIJIJJJ;

	public JIIJJJJJIIIIJJJJIJIIJIJIJJJIIIJIIIIJJJIIJJIIJJI JIJIIIIJJIIIIJIIJJIIJJIJIIJIIJIIJJIIJIJJIIIIJJI;

	public int JIJJIIIJJJIJIJJJIJJJJJIIJJIIIIIIIIIJJIJIIJIJIJI;

	private bool JIJIIJIIJJJJJIIJJJIIIIJJJJJIIJIIIIIJJJJJJJIIIII;

	private Transform JIJJJJJIIIIIJIJIJIJJJJJJJIIJIJIJIJIJJIJIIJIIJII;

	public void JJJIIIJJIJIIIIJJJIIJIJIIIIJIJIIIJIJJJIIIJJIIIJJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public void JJIIJJJIIJIIIJJJIIJIIIIJJIIJIJJIIJIIIIIIJJIJJII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	public void IJJIJJJJIJIJIIIIJIJIIIIJIIIIIIJJIIIIIIIJIJJIJJI(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public void JIIIJJIIJIIIIIIJIIJJIJIJJJIIJJIIIIJJJJJIIIJJIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public void JIIIIIJIIJIJJJJIJJIIJIJJIJJIJIIJIJJJJIIJJIIJJII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void Start()
	{
	}

	public bool JIIIJJJJIIIJJIJJJIIIJJJIIJJIIJJJJJJJJJJIIJJIJII()
	{
		return false;
	}

	public void JIJIJIJJIJJIIJJJIJJJIIIIJJJJJIIJIIJJIJJJJJJIJJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void JJIJJIIIIJJJIJIJIIJJIIJJJJIJIJIIJJJIJIJJJIJJIII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void IIJIJIIIIIJJIIIIIJJIJIIIJIJIJIIIJIJJIIIJJJJIIJJ()
	{
	}

	public void IIIJIJJJJJJIIJJIJIIIIJIJIIIJIJJJJJIJIIIIJIJIJJJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public void IIJJJIJIJIIJJIIIJIJJIJIJIJJJIIIIJJJIIJIJIJJJJJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public bool JJIJJJIJJJIIIJIIJIIJJJIJIJJJIIJIJIIIJJJIJIJJJJI()
	{
		return false;
	}

	public void IIIIIIIJJJJIJIJIIJJIIIIJJJJJIIIJIIIIIIIJJJJJIJI(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	public bool IIJIJJIIJJJJJJIJJJJIJIIJIJIJIIJJIIIJJIIJIIJIIII()
	{
		return false;
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	private void JIIIJIJIJIJIIJJIJIIJJJJJIJIIIIIJJIJJIJJIIJJIIJJ()
	{
	}

	public bool JIIIJIIIJJIJJIIIJIJJJJJIIIJJJJIIJJIJJIIJIIIJIJI()
	{
		return false;
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	public void JIIJIIJIIJIJIIIJIJIJIIIJJIIJJIJIIIIIIJJIIIJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}
}
