using System;
using UnityEngine;

public class ShootingRangeSpeedFire : MonoBehaviour
{
	[Serializable]
	public class IIIJJJJIJJIJJJIIIIJIJIIIIIIIJIIJJIIIIJJIJJJJJIJ
	{
		public Transform IJIIIIJJIIJIIIIJIJJJJIIIIJJIJIIJJJJJJIIIIJIIJII;

		public ShootingRangeTarget[] IIJIJJJJJJIIIIJJJIJJIIJIJIJJJIIJIJJIIIJIIIJJIJJ;
	}

	public IIIJJJJIJJIJJJIIIIJIJIIIIIIIJIIJJIIIIJJIJJJJJIJ[] JJJJJIIJJIIJJJIIIIJIIJJJIJJJJIJIIJIIJIIIIIIIJJJ;

	public int IJJJIJJIIIJIIIIIIJJJJJJJIIJIJJJJIJJIJIIJJIIJIII;

	public int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ;

	public bool IJJJJJJJJIIIJIIJJIIJIIIJJJJIIIJIJIIIIJJIJIIJIII;

	public void IJJIJIIIIJIJJJJIIIJIIJJJJIJJJJIIJIJIIIJIJIJJIJI()
	{
	}

	public void IJIJJIJJIJIJJJJIJJJJIJJJJJJIJIIIIJJJJJIIJJJIIJJ()
	{
	}

	public void IJIJJIJIJJJIJIJJIIJJJIJIJIIJJIJIIJIIIIIJIIJIIII()
	{
	}

	public void JJJJJJIIJJIIIIJIJIIJJJJJJJJIJIJJJJIJIJJIIJIIJIJ()
	{
	}

	public void IJIJJJIIJJJIIIIIJJIJIIIIIIIJJJIIIJJJIIJIIIJJIII()
	{
	}

	public void JIIJJJJIJJIIIIJJJJJIIIIJIJIJJJIJJIIIIJIJIJIIJIJ()
	{
	}

	public void JIJIIJJJJJJIJIJIIJJJIIJIJJIIJJJIIIJJIIJIJIJJJIJ()
	{
	}

	public void JJIJIIIJIJJJIJIJJJJIIJJIIJIIJJJJJJJIIIIIJIJJJJJ()
	{
	}

	public void JIJJJJIIJJIJJJJIJIJJIJIJJIIIJIIIIIJIIIJJJJIJJJJ()
	{
	}

	public void JIJJIIJJJIJJIJIIJJIJIJIJIIIJIJJJJIJJIIIJJIJIIJJ()
	{
	}

	public void JIIJIIIIIJIIIIJJJIIIJJJIJJJJIJIJIIJJIJIIJJJJJIJ()
	{
	}

	public void IJJIJIIJIIJJJIIJJIJJJJJIIJJJJJIIIIIJJJJIJJIIJII()
	{
	}

	public void IIIJIJJJIIJJJIIJJJIJJIJJJJJIIJIJIIIIJIJIJJJIJIJ()
	{
	}

	public void IIJIJJJIJIJJJIJJIJJJIJIIIJIJJJJJIIIJIIJJIJJJJII()
	{
	}
}
