using System.Collections.Generic;
using UnityEngine;

public class ShootingRangeFreeFire : MonoBehaviour
{
	public List<ShootingRangeTarget> IIJIJJJJJJIIIIJJJIJJIIJIJIJJJIIJIJJIIIJIIIJJIJJ;

	private List<ShootingRangeTarget> IIJIJJIJIIJIJIIIIIIIIJIIJIIIIIIIIIJJJIIIJIIJIJI;

	private List<ShootingRangeTarget> IIIIIIJIIIJJIJIIIJIIJIIJJIJJIIIJIJIIIJJIJJJJIJJ;

	public int IIIIIIJIJJIJJIJJIJIJIIJIIIJIIIJJJJJJJJIIIIJJIJJ;

	private bool JIJIIJIIJJJJJIIJJJIIIIJJJJJIIJIIIIIJJJJJJJIIIII;

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	public void IIJJJJJIJIIIIJIJJJJIJIJJJJIJJIIIJJIIJJIIIIIIIIJ(ShootingRangeTarget target)
	{
	}

	private void Start()
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	private void IJIIJJIJJJIJIJJJIIJIJIIJJJJJIJIJJJJIIJIIJIJJJJI()
	{
	}

	private void IIIIJJJIJIIIIIIJIIIIIJJIIJJJJJIJIIJJIIJJIIJIIJJ()
	{
	}

	private void IIJIIJIJIIIJJJJIJJIJJJIIIJJJIIIJIIJIJJIIJJJJJJI(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void JIIIJJJJJJIJIIIJIIIIJJIIIIIJJIIJIJJIIIIJIJJIIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	public void IIIJIIJIIJIJIJJJJJIIIJJJJIIIJJIIIIJIIJJJIIJIJJJ(ShootingRangeTarget target)
	{
	}

	public void IIJJIJJIJIJIIIJIJJJJJJIJIJJJIIIIJJJIIIIIJIJIIJJ(ShootingRangeTarget target)
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	public void DeadTarget(ShootingRangeTarget target)
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private void JJJJJIJJJIJIIJIIJJJJIIIJIJIJJIJIIIIIIIJJIJIJIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	public void IJIJIJIIIJIIJIJJJJIJJJIJIIJJIIIJIIJIJJJJIJJIJII(ShootingRangeTarget target)
	{
	}

	private void JIIIJJIIJIIIIIIJIIJJIJIJJJIIJJIIIIJJJJJIIIJJIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void IJJJIIJJJJJJIIJIIJIJIIJIJJIJJJIJJIIIIJIIJIIJIJI()
	{
	}

	private void IIJIIIJJIIJIJJJIJIIIJJJJJIJJIIIIJIIIIJJJIIIJIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public void JJJJIJJJJJJJIIIJJJIJIJJJJIJJIJJIJJIIIJJJJJIIIII(ShootingRangeTarget target)
	{
	}
}
