using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class SkinnedMeshAtlas : MonoBehaviour
{
	public static UIAtlas JIIJIJJIJIIIJIJIIIIIIJIIIIJJIJJJJJIIJIJJJIIIIJI;

	public Mesh JIIJIIIIIIJIIJIJIIIIIIIIIJIJIJIIJJIJIIJIJJIIJJI;

	private SkinnedMeshRenderer JIIIIIJIJIIIJIJIJIIJIJIIJIIIJJJIJIIIJIJIJJJJIIJ;

	private Mesh IJIJIJIJJJIIJJIIJJIIJIJIJIJJIJIJIIIJIIIIJIJIIJJ;

	public Material JIIIIJJIJJIJIJIIJJJJIIIJJIIJIIJJIIJIJIIJJJJIIJJ;

	public Material JJJIJJJJJJIJIJJIJJJIIIIJIIJIJIIJJJJJJJJIJIIJJJJ;

	public UIAtlas IIJIIJJJIIIJJJJIJIIJJJIIJIJIIIIIIIIJJIJIIIJJIIJ;

	public string IIJIJIIJJJJIJIIJIJJIIJIJIJIIJJIIIIIIIIJIIIJJIII;

	public IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ IJIJIIJIIIJIJJJIJJJIJIIJJJJJJJJIIIIIIIJJJJIIJJI;

	private bool JIJIJJJJIIJJIJIJIIJIIJJJJJIIIIIJIJJJJIIIJIIJJJJ;

	public SkinnedMeshRenderer JJJJJJIJIIJIIIIIJIIIJJIJJIIJIIJJJJJJIIJJJJIJIIJ => IIJIIIJJIJJJIJIJJIJIJJJJJIJJIIIJJIIIJJJJIJJJIJI();

	[SerializeField]
	public UIAtlas atlas
	{
		get
		{
			return IIJJJIJJIIIIIIJJIIJJIIIJIJJIIIJIJJIIIJIIJJIIJII();
		}
		set
		{
			JJIIIJIIIJIJJJJJJJJIJJJJIIIIJIJIIIJJJIJIIIIIJJJ(value);
		}
	}

	[SerializeField]
	public string spriteName
	{
		get
		{
			return IJIIIJJIJJJIJJJIJJJJJIJJJIIJJIIIIIJJIJJIIJIJIJJ();
		}
		set
		{
			IJIIIIIJIIJIJJJIJIJJIJIJJIJJIIIJJIJJJJJIIIIJJIJ(value);
		}
	}

	public bool IIIJIJJJIIJIJIJJJJJJJJJIJJIJIJIJIIIIIIJJJJJJIII => IIIIIIJJIJIIIJIIJIIIIJJIJJJJIJIJIIIIIIIIJJJIJJI();
	public bool IIIJJIJJJJIJJJIIIIJJJJIIJIJIJIIJJJIIIIJIJJIJIJI()
	{
		return false;
	}

	private void JIIJIIJIJIIIJIIJIIIIIJIIJIJJIJIIJJIIIIIJIIIJJII(IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ IIIJIJIIIJJIJJJIIJIJJIJJJIJIJIJIJIJJJJIJJJIIJJI)
	{
	}

	public string IJIIIJJIJJJIJJJIJJJJJIJJJIIJJIIIIIJJIJJIIJIJIJJ()
	{
		return null;
	}

	public void IIIIIIIIJIIIIJIJJIIJJIIIJIJIJJJIJIJIIJJJJJIJIJJ()
	{
	}

	public void JJIIIJIIIJIJJJJJJJJIJJJJIIIIJIJIIIJJJIJIIIIIJJJ(UIAtlas JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public SkinnedMeshRenderer IIJIIIJJIJJJIJIJJIJIJJJJJIJJIIIJJIIIJJJJIJJJIJI()
	{
		return null;
	}

	public void JIIIJIJJJIJIIJJJJIJIIIIIJJJIJIJJJIIJJJIJJIJJJII()
	{
	}
	public SkinnedMeshRenderer IJIIJIJJIJIIIIIJJJJJIJIJIJIJJIIJIIJIJJJJJJJJJII()
	{
		return null;
	}

	public void IIIIJJIIIJIJJJJJJIJJIJJJJIJIIJIIIJIJJJJIIJIJJJJ()
	{
	}
	public UIAtlas JJJIJIIJIIJIIJJJIIIIIIJIJIJIJIIIJJJIIJIJIJJJIIJ()
	{
		return null;
	}

	public void IIJIJJJJJJJJIJIIIJJIIJJIJIIJJJJIIIJIJJJIJIJJJIJ()
	{
	}

	public IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ IJIJJIJIIIIJIJJJIIIJJJJIJJIJJIJIJIIIJJJIIIJIJIJ()
	{
		return null;
	}

	private void IIIJJIJJJJJJJJIIJJIJJJIJJIIIIJIIIJJIIIIIIJJJJJJ()
	{
	}

	private void OnEnable()
	{
	}

	public bool IIIIIIJJIJIIIJIIJIIIIJJIJJJJIJIJIIIIIIIIJJJIJJI()
	{
		return false;
	}
	public UIAtlas JJJJJIIJIIJJIJJJJJIIIJJIJIJJIJJJJJIJIIJIIJJJJJI()
	{
		return null;
	}

	public void JIIIIIJIIJJIIIJIIJIIJJJIJIIJJJJIJIJIIJJJIIIIJJI()
	{
	}

	private void IIIIJJIIIIJIJJJIIJIJJJIIJIJJJIIIJJIJIIIJIIIJJJJ()
	{
	}

	public void IJIIIIIJIIJIJJJIJIJJIJIJJIJJIIIJJIJJJJJIIIIJJIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIJJIIIIIJIJJIJJIIIIIJJJIJIIJJJJJIIJIIJIIIIJIII()
	{
	}

	public void JIIJJJIIJJIJJJIJJJJIJJJIIJIIJIIIIJJJJJJJIIJIJJI()
	{
	}

	public void JJJJIIIIJJIIIJJIIJIJJIIJJJIIIIIIJJJIJIIJIJJJIJI()
	{
	}

	private void Reset()
	{
	}

	public void JJIJIJIIJIIIIIIIIIJJIIJJIIJJIIJJIIJJIIIJIIIJJIJ()
	{
	}

	public void IJJJJJIIIIJIJJIIIIIJIJIIIIJIIJIJIIIJIJJIJJJIJJJ()
	{
	}

	public UIAtlas IIJJJIJJIIIIIIJJIIJJIIIJIJJIIIJIJJIIIJIIJJIIJII()
	{
		return null;
	}

	public void IJJIIIIIJIIIIJIJJJJIJJJIJJJIIJJJIIIIIJJJJIIJIJJ()
	{
	}

	public void JIIIJJJJJJIJIJIIJIIJIJIIJJJJJIIIJIJJJIJIIJJJJJJ()
	{
	}
}
