using UnityEngine;

[ExecuteInEditMode]
public class SkyboxManager : MonoBehaviour
{
	public float IIJIIJJJIJIJIIJJIIJIJIJJJIJJJIIIJJJIIJJIJIIIIJI;

	public bool JJIIIIIIIIIIJJJJIIIJIIJIJIJIJJIIJIJJIJJIIIJIIJI;

	public bool JJIJIIIJJJIIIIIIJIJJIJJIIIIJJIJIJIIJIJJIIJIIIIJ;

	public bool IJIIJIIJIJJJJIIIIIIIIIIIJJIJIJJJJIJIJJJJIJIJIII;

	public bool JIJIIIIJJIJIIIIIIIIJIIJJIIJIIIJIJJIIIIJJJJJJJJI;

	public Material IIJJIIJJIJJJJJJIJJJIJIJJIJIJIIJJJIIJJIJIIIJIJII;

	public Transform IJIIJJJJJIIIIJJIIIJIJIIIJIJJJJJIJIIIJJJJJJJIJIJ;

	public Transform JJIIIJIIIJIIJIJJJJIIJIJIIIIIJIJJIJJJJJIIJIIJIJI;

	public GameObject IJIIJIIJIIJJIJJJJIJIIIJIIJJIJJIIIIJIIIJJIIJIIJI;

	public GameObject IJJIJIIIJIJJJJJIJJIJJJJIIIJIIJJJIJIJJJIIIJJIJJJ;

	public GameObject JIJIIJJJIIIJIJJJIJIIIJJJJJJIIIJJIIIJIIJIJIJIJJJ;

	public GameObject IIIIIJIJJJJJIIIJIJIIJIJJIIJJJIIIIJJIJIJJIJJIIII;

	private static SkyboxManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void JIJJIIIJJIJIIIIIJIIJIIIIJJJIJIIIIJJJJJJJJIIIIIJ()
	{
	}

	private void Reset()
	{
	}

	private void Start()
	{
	}

	public static Transform IJJIJIJIJJIIJIJIJIJIJJIIJIJIIJJIIIIIJJIJJJJJIJI()
	{
		return null;
	}

	public static Transform IJJJJIIIJJJIJJIIJJJJJJJJJJJIJIIIJJIIJJIJJJJIJJJ()
	{
		return null;
	}

	private void IJIIJJJJJIIIIIIIIJIIIIIIIIJIJIJJIIJIJJIIIIJIIII()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void JIIIJIJJIJJIIIIJIJJJJIIIJJJIIIIJJIJJIIIJIIIJIJJ()
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void Awake()
	{
	}

	private void JIJJJIIIJJJIJJJIJJIIIJJJIJIJJIJIIIJIJJIIJJIJIIJ()
	{
	}

	private void JIJJIJJJIJJIJIJIJIJJJIJJJJIJJIIJJJJJIIIJIJIIIJJ()
	{
	}

	public static Transform IJJIJJJIIIJIJJJIJIIIIJJJJJIJIJJJIJIJJIIJIIIIIIJ()
	{
		return null;
	}

	public static Transform IJJIJJJJIJJJIJJIJIJJIJIIJIIIIIIIJIIIIIIJIJJIIII()
	{
		return null;
	}

	private void JJJJJJJJJJIJJJJIIIIIJIJIIJIIJJJJIJIIJJIIJIIJIJJ()
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	public static Transform IIJIJJJJIJIJJJJIIIJIJJJIIIJIIJJJIIIJIJJJIJIJJII()
	{
		return null;
	}

	private void IIJIIJJJIIJJJIIIJJIJIJJIIJJIIIJIJJJIJJIJIJJIJJI()
	{
	}

	public static Transform IIIIIIJIIJJJIIIIIJIJJJIIIIIIIJJIJJJIJJJIIIJIJJJ()
	{
		return null;
	}

	public static Transform JJIIJIJIJJJIIIJJIJJIJJIIJIJJJIIJIJJIIJJIIIJJJJI()
	{
		return null;
	}

	private void JIIIIIJIJJIIIIIIIJJIIJJJJIIJJJJJJIIJIJJJJIIIIJJ()
	{
	}

	private void JIIIIJJJIIIIIIJIIIJJIIIJIIIJIJJIIJJIJJJJIJJJIJI()
	{
	}

	private void JJIJIIIJIJIJJJJIJIIJJJJJIJJJJJIJIJIJIIJIIJIIIJJ()
	{
	}
}
