using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class SoundManager : MonoBehaviour
{
	[Serializable]
	public class JJJJJJJIIJIJIIIIIIIJJJJJIIJJJIJIJIJIJIJIIIJJIIJ
	{
		public string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ;

		public bool IJJJIJIIIJIJJJIIJJIIJJJIIIIJIJJIJIJIIJIIIJJIJJJ;

		public AudioClip[] JJIIIJJIJIIJIIJJIIIJJIJJIJIJJJJIIIIIJJJIJJJIIJI;

		public AudioClip IIJIIJIIJJIIJJIIJJJIIIJIIIJIIIIIIIJIJJIJJIIIJJJ => IJJIIIJIJJJJJJIJJIJIIJIIIIIIJIIJIIIJIIIIIJIIJIJ();
		public AudioClip IIIJIIJJIIJIIIJJIIJIJJJIJJJJJJIJJJJJJJIIIJIIIJI()
		{
			return null;
		}

		public AudioClip IJJIIIJIJJJJJJIJJIJIIJIIIIIIJIIJIIIJIIIIIJIIJIJ()
		{
			return null;
		}
		public AudioClip JIIJJJIIIJIIJJIJJJJJJIJIIIIIIIJIIJJIIIJIJIJIIIJ()
		{
			return null;
		}
		public AudioClip JJIJJJJJJIJJIJJJJIIJJJIJIJJIIJJJJJIJIIIJIJIIJJI()
		{
			return null;
		}
		public AudioClip IIJJJIIIIIIJIJIIJJIJIJIJIJIJJJJJJIIJJJIJJIIJJJI()
		{
			return null;
		}
		public AudioClip IJJIJIIJIJIIJJJIJJJIJIIIJJIJJJIJIIIJJIJIIIIIIIJ()
		{
			return null;
		}
		public AudioClip JJIIIIIIJJJJJJIIIJIIJIJIIIJJIJJIJIIJJIJJIIIJJIJ()
		{
			return null;
		}
		public AudioClip JJJJIIIJIIIJIIIJJIIIJJIJJJJJIJIIIJIJIJIJJJIIIII()
		{
			return null;
		}
		public AudioClip IIJJJIIJJIJIIJJIJJIIIIJJJJJJJJIIIJJJJJIJJIJIIII()
		{
			return null;
		}
		public AudioClip JIIIIJJIJIIIJJIIIJJJJJJIIIIIIIJIIJJJIJIJIIIJIJI()
		{
			return null;
		}
		public AudioClip JJJIJJIIJIIJJJJIIJJIJIIIJIJIJIIJIJIJJJJIJIJJJII()
		{
			return null;
		}
		public AudioClip JJJIJJJIJIJJIIIIJIJJIIJJJJJIIIIIJIJIIJJIJIIIIII()
		{
			return null;
		}
		public AudioClip IIIIIIIJIJJJJIIJJJJIJIJJIIIIIJJIJIIJIIJJIJJIJJJ()
		{
			return null;
		}
		public AudioClip IIIJJJIJIIJIJIJJIJJJIIJIJIJIIJJJJJIJJIJJIJIIJJI()
		{
			return null;
		}
		public AudioClip IIJJJJIIIJIJJIIIJIIJJJIIIIIIIJIJJJIJJIIIIJJJIJJ()
		{
			return null;
		}
		public AudioClip IIIIJJIIJJJJIIIIJJJIIJJJIIJJIJJIJJIJJIIJJJIJJJI()
		{
			return null;
		}
		public AudioClip IJJIIIJJJIIJJIJIIIIIIJJJIIIIJJIIIIJIIJJJJIJIIII()
		{
			return null;
		}
	}

	public JJJJJJJIIJIJIIIIIIIJJJJJIIJJJIJIJIJIJIJIIIJJIIJ[] IJJJIIIJJJJJJJJJIJIIIJJIJIIJJIIJJJIJIIJJIIJIJII;

	private List<SoundClip> JJJJJIJIIJJIJIIIJJJIIJIJIJJIJJIIIIIIJJIJIIJJJJI;

	private List<SoundClip> IJJJIJJIJJJIIIJJJJJJIJJIIJIJJIJIJJIIJJJJJJIJIII;

	private AudioSource JJJIJJIJJIIJIIIIJJJIJIJIIIIIIIIIIIIJJJJJJIJJJJJ;

	private static SoundManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static SoundClip IJIJIJIJIIJJJIJIIJIJJJJJJIIJJIIIIIIJJJIJIIJJIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII)
	{
		return null;
	}

	public static SoundClip JIJJIIJIIJJJJJIJIIJJIJIIJIJJIIJJIJIIIIIJJJIIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
		return null;
	}

	public static SoundClip JJJJJJIJJJJJJJJIIJIIJJJJJIIJJIJJJJIJIJIJIIJIJII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, bool IJIIIJJIJJIIJIJJIJJJIJIJIIJJIJJIJIJJIIIIIJIIIIJ)
	{
		return null;
	}

	private static SoundClip JJIIIJIIJJJJIJIIIJIIJJIJIIJJIJJIJIIIIJIJIIJIIJI()
	{
		return null;
	}

	public static SoundClip JJJJIJJJJIJIIIIJIJIJIJJJIJIIJIIIIJJIJIIJJJJIJII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII)
	{
		return null;
	}

	public static void IJIIJIIJIJJIJJJIIIJJIJIIIIJIJJJJJIJJIIIIIJJIJIJ()
	{
	}

	public static void IJIJIIIIIJJJJJJJIIJJIIIJJIIJJIJJIIJJJJIJJJJJIII(SoundClip IIJIIJIIJJIIJJIIJJJIIIJIIIJIIIIIIIJIJJIJJIIIJJJ)
	{
	}

	public static SoundClip IJJIJJJJIJJIJIIJJIIJJJIIJJJIIIIIJJJIJJJJIIIJJJI(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII)
	{
		return null;
	}

	private void Start()
	{
	}

	public static SoundClip JIJJIIJIIJJJJJIJIIJJIJIIJIJJIIJJIJIIIIIJJJIIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII)
	{
		return null;
	}

	public static void IIIJIIIIIIIIJJIIJJIJIJIJIIIIIIJIJJJJJIJIIIJJJJI()
	{
	}

	public static void JIJJJIJIJIIJJJJJIIJJIJIIIIIIIJIJJIIIJJJIIIIJIIJ(SoundClip IIJIIJIIJJIIJJIIJJJIIIJIIIJIIIIIIIJIJJIJJIIIJJJ)
	{
	}

	private void JIIIIJJJIIIIIIJIIIJJIIIJIIIJIJJIIJJIJJJJIJJJIJI()
	{
	}

	public static SoundClip JIJJIIJIIJJJJJIJIIJJIJIIJIJJIIJJIJIIIIIJJJIIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
		return null;
	}

	public static void IIIIJIJIJJJIIIIJIJJIJJJIJJJIIIIIJJIIJJIIIJIJIIJ()
	{
	}

	public static void IIJJIJIJIIIIJIJJJJJIJIIJIIJJIJJJJIJJIJIIIIIJIII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII)
	{
	}

	private void JIIJIJIIIJIIJIIJJJIIIJJIJJIIIIIIJIJIIJIIJIIIIIJ()
	{
	}

	public static SoundClip JIJJIIJIIJJJJJIJIIJJIJIIJIJJIIJJIJIIIIIJJJIIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, bool IJIIIJJIJJIIJIJJIJJJIJIJIIJJIJJIJIJJIIIIIJIIIIJ)
	{
		return null;
	}

	public static SoundClip IJJJJJJJJJIJIIIJJIJIJIJIIIIJIIIJIJIIJIIJJIIIIJI(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
		return null;
	}

	public static void IIJJJIJIJIIIJIIJIIIJJJJIIIJIIIJJIJJIJJJJIIJIJJJ()
	{
	}

	public static void IJIJJIIJIIIIJIIJIJIIIJIJJIJIJJJJIJJJJIJJJIIIJJJ(SoundClip IIJIIJIIJJIIJJIIJJJIIIJIIIJIIIIIIIJIJJIJJIIIJJJ)
	{
	}

	public static SoundClip IJJJIIJIJIIIJJIJJIJJIJIIJIJJIJJJIJIJJJIJIJIJIII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
		return null;
	}

	public static SoundClip JIJJIIJIIJJJJJIJIIJJIJIIJIJJIIJJIJIIIIIJJJIIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IIJJIIIJIJIJJJJIIJJJJIIIIIIIIIIJIIIIJIJIIIIIIII, bool IJIIIJJIJJIIJIJJIJJJIJIJIIJJIJJIJIJJIIIIIJIIIIJ)
	{
		return null;
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	public static void IJJJIJIJIJJJIIJJIJIJIIJIIIIIIIJJIJJIIJIJIIIIIJI(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII)
	{
	}

	public static void JIIIIIIJIIIJIJJIJJJIJIJIIJIIIIIIJIJJJIIIJIIJJJI(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII)
	{
	}

	public static SoundClip JIJJJIIIJJJJIJJJIJJJJJIIIIJIIJJIJIIJJIJIIJIIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, bool IJIIIJJIJJIIJIJJIJJJIJIJIIJJIJJIJIJJIIIIIJIIIIJ)
	{
		return null;
	}

	public static SoundClip JJIJJJJJIIIIIIIJIIJIJIIIIIJIIJIIJIIIIIIJIJIIIJI(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
		return null;
	}
}
