using System.Runtime.CompilerServices;
using UnityEngine;

public class SoundClip : MonoBehaviour
{
	public string JIIJIIIJIJJIIJIIIIIJIIIJIIIIIIJIIIJIJIIJIIJIIII;

	private GameObject JIIIJIJJJIJJIJIJIIIJJJJIIJIJJJIIIJJIIIJIJIIJIII;

	private Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ;

	private AudioSource JJJIJJIJJIIJIIIIJJJIJIJIIIIIIIIIIIIJJJJJJIJJJJJ;

	public void JIJJIIJIIJJJJJIJIIJJIJIIJIJJIIJJIJIIIIIJJJIIIJJ(string JJJJJIIIJIJJJIIIIIJJIIJJIIIJJIJIJJJIIJIIIJJIIJI, AudioClip IIJIIJIIJJIIJJIIJJJIIIJIIIJIIIIIIIJIJJIJJIIIJJJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IIJJIIIJIJIJJJJIIJJJJIIIIIIIIIIJIIIIJIJIIIIIIII, bool IJIIIJJIJJIIJIJJIJJJIJIJIIJJIJJIJIJJIIIIIJIIIIJ)
	{
	}

	public static SoundClip IJJJIJJIJJIIIJIJIJIJIIJJJIIIJJIJJJIIIJIIIJIIIII()
	{
		return null;
	}

	public AudioSource JIJIJJIJIIJJJJIJJIIIJJIIJIJIJJJIJIJJJIIIJIJIJII()
	{
		return null;
	}

	public void IIIIIJIJIJJIIIIIJIIIJIJJIIJJJIIJJJIIIJJJIIIIIIJ(float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII)
	{
	}

	public void IIIJJIJJJJIJIIJIIIIIIIIIJJIIJJIJJJIIIJIJJJJIJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, AudioSource IIJJIJIJIIJIIJIIIIJIIIIIJIJIIIIIIIIIIJIJIJIJJIJ)
	{
	}

	public AudioSource IJIJJIJIJJJIJJJIIIIJJJJJJIIIIIIJJJIJIIIIJIJIJJI()
	{
		return null;
	}

	public void IJJJIJIJIJJJIIJJIJIJIIJIIIIIIIJJIJJIIJIJIIIIIJI(float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII)
	{
	}

	public AudioSource IJJJJIIIJIIIIJIIJJIJIIJIJIIIJIIJJIIIIIIIIJJJJJI()
	{
		return null;
	}

	public void JIIIIIJJJJJJJIIIJJIIIJIJIIJJJJJIJIJIJIJIJIJIJJJ(string JJJJJIIIJIJJJIIIIIJJIIJJIIIJJIJIJJJIIJIIIJJIIJI, AudioClip IIJIIJIIJJIIJJIIJJJIIIJIIIJIIIIIIIJIJJIJJIIIJJJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IIJJIIIJIJIJJJJIIJJJJIIIIIIIIIIJIIIIJIJIIIIIIII, bool IJIIIJJIJJIIJIJJIJJJIJIJIIJJIJJIJIJJIIIIIJIIIIJ)
	{
	}

	public AudioSource IIJJJIIJIIJIIJIJIIIJIJJJIJJJIJJIIIIJIIIJIJIIIIJ()
	{
		return null;
	}

	public void IIJIJJJIIIIJIIJJIJIJIJJIIIIJIJIIJIIJIIJJIJIIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, AudioSource IIJJIJIJIIJIIJIIIIJIIIIIJIJIIIIIIIIIIJIJIJIJJIJ)
	{
	}

	private void IIIJJIIIJJJIIIIIJJIIIJJIJJJJJJJJJIIIJJJJIJIIJJJ()
	{
	}

	public static SoundClip JJIJIJIIIIJJIIJIIIIIIJJJJJIIIJJIIIJJJJIJIIIJIII()
	{
		return null;
	}

	private void IJJIJIIJJJIIJIIIJJJJJIJIIIJJIJIJIJJJJJIIJIIIIIJ()
	{
	}

	[CompilerGenerated]
	private void JIJJJJIIJIIIJIIIJJIJJJIIJJJJIJIJJIIJJJIJIIIJIII()
	{
	}

	public void JJJJIIIJIIIJJIJIJIJIJIJIJIIJJJJIJIJIIIIIJJJJIJJ(float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII)
	{
	}

	public void JJJJJJIJJJJJJJJIIJIIJJJJJIIJJIJJJJIJIJIJIIJIJII(string JJJJJIIIJIJJJIIIIIJJIIJJIIIJJIJIJJJIIJIIIJJIIJI, AudioClip IIJIIJIIJJIIJJIIJJJIIIJIIIJIIIIIIIJIJJIJJIIIJJJ, float JIJJIIJJJIJIJJIIJIIJIIIIJJJJIJJJIIIIIJJIIIIIIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IIJJIIIJIJIJJJJIIJJJJIIIIIIIIIIJIIIIJIJIIIIIIII, bool IJIIIJJIJJIIJIJJIJJJIJIJIIJJIJJIJIJJIIIIIJIIIIJ)
	{
	}

	public void JJIIJJJJIIJIJIIIIJJIIIJJJIJIJIJJJJJJJJJJIIIJIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, AudioSource IIJJIJIJIIJIIJIIIIJIIIIIJIJIIIIIIIIIIJIJIJIJJIJ)
	{
	}

	private void IJIJJIJJJJJIJIJJJJJIJIIIJJJJJJJJJIIJJJJJIJIIIIJ()
	{
	}

	public void IIIJJIIJJIIIIIJJJIIIIIIIJIIIJJJIIJJJIJIJJIJJJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, AudioSource IIJJIJIJIIJIIJIIIIJIIIIIJIJIIIIIIIIIIJIJIJIJJIJ)
	{
	}

	private void IJIIIIJIIJJIIJIJIIIIIJJIJJJIJJJIIIIIIJIJJJJJJJI()
	{
	}

	public AudioSource JJIJIIIIIJIJIJIJIIJIIIJJIIIJJJIJIJJJJIIIIIJIIIJ()
	{
		return null;
	}

	public void JIIIIIIIIJIIJJIIJIJIIJIIJJIIIIJIIIJJIJJJIIJIJJJ()
	{
	}

	public void IJJJIJIJIJJJIIJJIJIJIIJIIIIIIIJJIJJIIJIJIIIIIJI()
	{
	}
}
