using System.Runtime.CompilerServices;
using UnityEngine;

public class SparkEffectManager : MonoBehaviour
{
	public ParticleSystem IIJIIIIIIJIJIJJJIIJIIJJJIJIJJIJIJIJJIJIIIJJIIII;

	private Transform JJIJIIJIIJJJJJIIIJIIIJJJIJJJIIIIJJIJJJIIIJJIIII;

	private bool IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI;

	private static SparkEffectManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private Transform JJIIIIIIIJJJIJJJIIIIJIJJIJIJJJJJJJJJIJJJJJJIJJJ => IJIIJIJIJJJIJJJJJJIIIJIIJIJIIIIIJIJIJIIJIIJJIII();

	public static void JJIIIJJIJJIIJJIJJIJJIIJIJJIIJJJIIIJIIJJJIIJIJII()
	{
	}

	public static void JIJJIIJIIIIJJJIJIIJJIJIJIIJJIJJJJIIIJJIIIJJJIIJ(Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	private void Start()
	{
	}

	public static void JJIJIIJIIIIJJIIJJJJJIIIJIIIIJIIIJJIIJIJIJJIIJIJ()
	{
	}

	public static void IJIJIIIIJJIJJJJJJJIJIIJJJIJJIIIJIIIJJJJIJIJJIIJ(Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII, float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ)
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	public static void JJIJJJJJIIJIIJIIJIIJJJIJIIIJIJJJJIJIJIJIIJIIIJJ()
	{
	}

	public static void IIIIIIIJJJIJIJJJIIIJJIIJIJJJIJIIIIIIJIIJIIIIIII(Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}
	private Transform JIIJIIJIIJIJIIJJIJIIJIJIIIIIJJJIIJIIIJIJIIIIJJI()
	{
		return null;
	}

	public static void IJJIJJIJJJJIIJIJJIIJJJIIIJJJIIIIJIJIIIJJIIJJIIJ()
	{
	}

	public static void JJJJJJJIIIIIIJIJJIIIIJJJIIJIIIJIIJJIIIIJIJIIJII(Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII, float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ)
	{
	}
	private Transform IJIIIJIJJJJJJIJIJIJIJIJJIJJJIJIJIIIIIIJJJJIIJJJ()
	{
		return null;
	}

	private Transform IJIIJIJIJJJIJJJJJJIIIJIIJIJIIIIIJIJIJIIJIIJJIII()
	{
		return null;
	}
	private Transform JJJJJIIIIIIIJJIIIJIIIJIJJJIJIIIIIIIIIJJJJJJJIJJ()
	{
		return null;
	}

	public static void IIJJJIIJJJJJIJJJJIJJIJJJIIIIIJJJJIIIJJJJJIIJJIJ()
	{
	}

	public static void JIIIIIIJJIIJIIJJJJJJIJJJIJIJIIIJJJIJIIIJIIJJIJJ(Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII, float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ)
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}
}
