using System.Runtime.CompilerServices;
using UnityEngine;

public class SpawnPoint : MonoBehaviour
{
	private Transform JJIJIIJIIJJJJJIIIJIIIJJJIJJJIIIIJJIJJJIIIJJIIII;

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	public Vector3 IIJJJJIIIIIIJJJJIIJJJJJIIIIIIIJIIJJIJJJJJIJIIII
	{
		get
		{
			return JJIIIJIJIJIJIIJIIIJIJIIJIJIIIJJJIIJJIIIIJJIIJIJ();
		}
		set
		{
			IIIJJIJIJIJIIJJIJJIJIIJJIIIJIJJIIJJIIIIIIJIIJII(value);
		}
	}

	public Vector3 JIJJIIIJJJJJJIIIJJJJJIIJIIJIIIIJJJIJJJJIIIJIIJI
	{
		get
		{
			return JIIIJIIIIIIJJIIIJJJIIIJJIJJJJIIIIJIJIIJIIJJJIJJ();
		}
		set
		{
			JJJJJJIJJIJIIIJJIJIJIJJIIJIIJJJJIIIIIJIJIIIJIII(value);
		}
	}

	public Vector3 JJJJJJIJJJJJJIIIJJJIJIIIJJJJIJIIIIJJJIIIJIIJJJJ
	{
		get
		{
			return JIIJIJJIIIIJIJJJIJIJIIJIJJJIIJIJIIJIIJIJJJJIJJJ();
		}
		set
		{
			IIJJIIIJIJJIIIIJIIJJJJJJIIJIJJJJIIJIJIJIJIJIJII(value);
		}
	}

	public void IIIJJIJIJIJIIJJIJJIJIIJJIIIJIJJIIJJIIIIIIJIIJII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public Vector3 JIIIIIJJJJJJIIIIIJJIJIJIJIIIIIIIJJJIIJIIIIJJJIJ()
	{
		return default;
	}
	public void IJJJIIJIIIJIJJJJJIIIIIIIJJJIJIIJJIJJIIJJIJIIIJJ(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public Vector3 JIIIJJIIIJIIIJIIJIJIIJIIIIJJJJIIIJIIIJJJJJJJIII()
	{
		return default;
	}
	public void IIIJJJJJJIIJJIJJIIIIJIJIIIIJIIJJIJIIJJJIIIJJIJJ(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void IJJIJJIJIIIIIJJJIJIIIJJIJJIIIIJIJJJJIIIJJIIIJII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}

	public void IIJJIIIJIJJIIIIJIIJJJJJJIIJIJJJJIIJIJIJIJIJIJII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void JIJJJJJIIJIIJJJIIIIJJJJIJIIJIIJJJIJJIJJIIIJIIJJ(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Vector3 JJIIIJIJIJIJIIJIIIJIJIIJIJIIIJJJIIJJIIIIJJIIJIJ()
	{
		return default;
	}
	public void IIJIJIIIJJJIIIJIJIJIIIIJIJIJJJJJIJJJJJJJIJJIJII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public Vector3 JJJIIIJIJJJJJJJJJIIJIJJJIJJJIIIIIJJIIIJJJIIJJII()
	{
		return default;
	}
	public Transform JIJIIJIJIIJJIJIJIIIIJIIIJIJJJJJIIIIJJJIIIIJJJIJ()
	{
		return null;
	}
	public Vector3 JJIIJJIIJIJIJJJJJJIJIIJJJIIJIJIIIJJIIJIIIIIIIIJ()
	{
		return default;
	}

	public void JJJJJJIJJIJIIIJJIJIJIJJIIJIIJJJJIIIIIJIJIIIJIII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void IIJJJIIJJJIIIJIJJIJJJJIIIIIIJIIJJIIJIIJIJIIIJJI(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Vector3 JIIIJIIIIIIJJIIIJJJIIIJJIJJJJIIIIJIJIIJIIJJJIJJ()
	{
		return default;
	}

	public Vector3 JIIJIJJIIIIJIJJJIJIJIIJIJJJIIJIJIIJIIJIJJJJIJJJ()
	{
		return default;
	}
	public void IJIJIIIIIJJIIIJIIIJJJJJJIIJIJJIJJIJIJIJJJJJIIJI(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public Vector3 IJIJJIJIJJIJIJIIIIJIJJJJJIJJIJJIJIIIIJJJJJIIIJI()
	{
		return default;
	}
	public Vector3 JIJJIJIJJIIIJIIJJJJIIIIIIJJIIIIIIJJJIIJJJJIIJII()
	{
		return default;
	}
	public Vector3 IJJIJIIIJIJIJIJJIJJIJIIIJIJJIJJIJIIIIIJIIIIJJJI()
	{
		return default;
	}
	public Transform JIIJJIIIIIIJJJIIIIJJIIJIJJJIIIIJIJJJJIIIIJIJIIJ()
	{
		return null;
	}
	public Transform IIIJJIJJJIIJJIIIJJJIJJIJJJIIIJIJIIIJIIIIIIIIIIJ()
	{
		return null;
	}
}
