using UnityEngine;

public class SpawnManager : MonoBehaviour
{
	public SpawnPoint JJJIIIJIIIJJJIIJJJJIIIJJJIJIJIIIIIIJJIIIIJIJJJJ;

	public SpawnPoint JJJIIIIIJJJIIJJJJJJIIIIIIJIJJJIJJIJIIIIIJIJJJJJ;

	public SpawnPoint[] JIIIIIIIJIJIJJIIJJIIIIJJIIJJIJIIIJIIJJIIJJIJIJI;

	public SpawnPoint IIIIJIJJIJIJIJIIIIIIJJIIJJJIIIJIJJJJJIIJIIJIIJJ;

	private static SpawnManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static SpawnPoint JIJJJJJIJJJJIJIJIIJJIJIJJIJIJJJJJIJJIIIJJJIIJJI(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
		return null;
	}

	private void IJIJJJJJIJJIIJJJJJIJIJJIJJJJJJIJIIIIIIJJJJIIIIJ()
	{
	}

	public static SpawnPoint IIIJIIJIJIIJJIJIIIIIIIJIIJIJJJIJIIJIIIIIJJIIJJJ()
	{
		return null;
	}

	public static SpawnPoint JJIJIJIIIIIIIJJIJIIJJIJJIJIJJJIIJIIIIIIJJJJJJJI()
	{
		return null;
	}

	public static SpawnPoint JIIIIIIJJJIJJIJJIIIJJJIJJJIJJJIIIIIIIJIJJIIIJJI(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}

	public static void IIIIJIIIIJIJJIIJIJIIJIIIJJJIJJIIJJIJJIJIIJJIJII(IJIIIJIIJJJJJJIJJJIIJJJIIIIIIJIJIJJJJIIJJIIJIII IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ)
	{
	}

	public static void IIJJJJJIJIIIJJIJIIIIJIIIIJJIIJIJJIIJIIIIJIJJJII(IJIIIJIIJJJJJJIJJJIIJJJIIIIIIJIJIJJJJIIJJIIJIII IIIIJJJIJIIJJIIIIJJJJIJJIJIJJJJJIJIJJJIIJJIIIIJ)
	{
	}

	public static SpawnPoint IIIIIIJJIIIIIIIIJJJJJIJJJIIIJJIIJJIIIJJJIIJIIJI()
	{
		return null;
	}

	public static SpawnPoint IIIJJIJIIIJJJIJIJIIJIJJJJIJIJIIJIJJIJJIIIJJIJIJ()
	{
		return null;
	}

	private static int JIIIIIJIIJJJJJIJIIIIJJJIIIIIIIJIIJIJIJIIIIIJIIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	private void IIIJIJJJIIJIIIJIIJJJIJJIJIIJJJIJJIIIJJJJIIJJJIJ()
	{
	}

	public static SpawnPoint IJJIJJIIIJIIIIIJJJJJIIJJJIIIJJJJJIJIJIIJIIJJIII(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
		return null;
	}

	private void JJIJIIIJIJIJJJJIJIIJJJJJIJJJJJIJIJIJIIJIIJIIIJJ()
	{
	}

	public static SpawnPoint JJIJIIJIJIJIJJIJJJIJJJIIJJIIIIJIJJJIIIJJJIJIJJJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
		return null;
	}

	public static SpawnPoint IIJJIIJIJIJIJIJJJIIIIIIIJJIIIIIJIJIIIJIJIJJJIIJ()
	{
		return null;
	}

	private static int IJIJJIIIIIJIIIIIJIIJJIJJIIIJIIJJIJJJJIIJIJJIJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	public static SpawnPoint JIIIIIJIIJIIJIJIIJJJJIJIJJJJJIJJIIIJIIJIIJIIJII()
	{
		return null;
	}

	public static SpawnPoint JJJIIIJJJJIJIIIJIJIIIIIJJJIIJIIJIIIJIIIIJJIJJJJ()
	{
		return null;
	}

	public static SpawnPoint IIIIIJIJIJIJIIIJIIJIJJIIJIIJIJIIIJJIJJJJIJIIJIJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
		return null;
	}

	public static SpawnPoint IIJJIJJIIJIJJIJIIIIJIIIJIIJIIIIIJIIJIIIIJIJIJII(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
		return null;
	}

	public static SpawnPoint IJIIJJIIJIJJJIJJIIIIJIJIIIIIJJIIJJJJIJJIJJJJIII()
	{
		return null;
	}

	public static SpawnPoint IIIJJIIIIJJIJIIJIIJJJJIJIIJJIIJIJJJIIJJIJIJJJJJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}

	public static SpawnPoint JJJIIIJJJJIJIIIJIJIIIIIJJJIIJIIJIIIJIIIIJJIJJJJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}

	private void Awake()
	{
	}

	public static SpawnPoint IJJJIJIIIJIIIJJIIIIIJJIIIIJIIIJJJJJJIIIIIJIIIII(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}

	public static SpawnPoint JJJIIJIJIJIJIJIJJIJIJIIIIIIJIIIIJJIIJIIIIJIIIIJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}

	public static SpawnPoint JJIJIIJIJIJIJJIJJJIJJJIIJJIIIIJIJJJIIIJJJIJIJJJ()
	{
		return null;
	}

	public static SpawnPoint IJJJIIIIJJIIIIIIIIIJIJJJJIJJJJIIIJIJJJJIJIIIJIJ()
	{
		return null;
	}
}
