using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Photon;

public class SpleefMode : MonoBehaviour
{
	public SpleefBlock[] JIJIJJIJJIIIIIIJJJJIJIJIIJIIIIIJJJJJJJJIIJJJIJI;

	private List<short> JJIIJIIIIJJIIIJJJJJJJIJIJJIIIIIIJIJIJIIIIJJIJII;

	private List<short> JIJIJJJJIIJIJIJIJJJJIJJIIJJJJJJIJJIIIIIIJJJIJJJ;

	public static SpleefMode JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void OnEnable()
	{
	}

	private void IJJJJIIIIJIIIIIJJIIJIIIJIJJJJJJJJJIIJIIIIIIJIJJ()
	{
	}

	[CompilerGenerated]
	private void JJJJIIIJJJIJIJJIJJJJIJJJIJJIJJIIJJJIIIIIIIJIJIJ()
	{
	}

	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIJJIIIIIIJJIIJIIIJJIJJIIIJJJIIJIJIIIJIIJJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void JIIIIIJIIJIJJJJIJJIIJIJJIJJIJIIJIJJJJIIJJIIJJII(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private void JIJJIIIIJJIJIIJIIJIJJJJJJJIJIIIIJIJIJIIJJJJJIJI(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void IJJIIJJIJJIIIIJJJJIJIJIIIIJJJJIIIIJIIIJIJJIJJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJJJJJIIJJJJJJJJJIIIIJIIJJJIIIIIJIIIJIIJIJJIJJ()
	{
	}

	private void JIIIIJIJIJIIJIIIIJIJJIIIIIIIIJJJJIIJIJJJJIIJIII()
	{
	}

	private void IIJJIIIIJIJJIIIJJIJIIIJIIJIJJJJJIJIJJIIJJJJIJII()
	{
	}

	private void OnDisable()
	{
	}

	private void IIJIIJJJJJIJIIJJJIIJIIIJIIIIIJIJIIJJIIJIIIJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void IJIJJJIIJIJIIIIJIJJIJIJJJJIJIIIJIJIJJJIIIIIJIJJ()
	{
	}

	private void IJIJJIJJJIJIJJJJJIJJIIIJIJIJIIJIJIIJJJIIIIIIJJJ()
	{
	}

	private void IJIJIJJIJJJIIJJIJJJJJIIJJIJIIIIJIIJIIJIJJJJJJJI()
	{
	}

	[CompilerGenerated]
	private void IJJIIJJJJJJIJIIJIIJJIJIIJIJIIJJJIIIIIJIJIIJIJIJ()
	{
	}

	private void JIJJJIIIJJJIJJJIJJIIIJJJIJIJJIJIIIJIJJIIJJIJIIJ()
	{
	}

	private void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void JJIIIIJJIIIJJIIJIIJJJIIIJJIIIJJIIIIIIIIIIJIJJIJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIJJJJIIJJIIJIJIJIJJIIJJIIJIIJJJIIJJJJIJJIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void Start()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJIIJJJJIJIJJJIJIJJIJIIIIIIIIIJIJJJIJIIJJJJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void JIJIJIJJIJJIIJJJIJJJIIIIJJJJJIIJIIJJIJJJJJJIJJJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private void JIIIIJJJJIJIIIIJIIJJJJJJJIJIJJIIIIIIJIJIIJIJIII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJIJIIIIIIIJJJIJJIIIJJJIIIIJIJIJJIIJJJJJIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	[CompilerGenerated]
	private void IJIIJIIIJJJJJJJIJJIIJIIJIJIIJIIIJJIIJIJJJIIIIII()
	{
	}

	[CompilerGenerated]
	private void JIJJJIIJJIIIIJIJJIJIJIIIJJJIJIJIIJIJIIIJIIJIJII()
	{
	}

	private void IJJJJIIIIJJIIIJJIJJJJJJIJIIJJJJJJJJIJJIIJIIIJIJ()
	{
	}

	private void IIJJIIIJJIJJJIJJIIIJJJIIIIIJIJIIIJIIJJJJIIIIIJJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJIIJJIJJJJJJJIJJJJJIIJIJJJIJJIJIIJJJJJJIIJJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJIJIJIJJJIIIJIIJIIIIJIIJIIJIIJJJIIJJJJIIIJIII()
	{
	}

	private void IJIJJJIIJIIJIJJIJIJIIIJIJIJJIIIIIIJJIJIJIJIJIJJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void Awake()
	{
	}

	private void JIIIIIIJJIIJJJIJJIJJJIIJIJJJJIIIJIIJIJIJJIIIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}
}
