using UnityEngine;

public class SpleefBlock : MonoBehaviour
{
	public int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ;

	public GameObject JIIIJIJJJIJJIJIJIIIJJJJIIJIJJJIIIJJIIIJIJIIJIII;

	public Renderer JJIJIJJJJIJIIJIJJJJIIJIJIJJIJIJIIIJIJIJJIJJJIJJ;

	public void IJJIIIIJIJJIIIJIIIIJJIIIIIIJJJIIIJJJIIIIIIIJJIJ()
	{
	}

	public void JIJIJJJJIIIIJIIIIIIJIIIIIJJJJIJJIIJIJJJIIIJJIII()
	{
	}

	public void JIJIJJIJIIJIIIIJJJJJJIJIJIIJJIJIIJIIIJIJIIJJJII()
	{
	}

	public void IIJJJIJIJIIJJIIIJIJJIJIJIJJJIIIIJJJIIJIJIJJJJJJ()
	{
	}

	public void IJIIJIIJIIIIIIJIIJIJIJJIIJJJJIIIJIJIIJJIJJIIIIJ()
	{
	}

	public void JIIIIIJIIJIJJJJIJJIIJIJJIJJIJIIJIJJJJIIJJIIJJII()
	{
	}

	public void JJIIJJJIIJIIIJJJIIJIIIIJJIIJIJJIIJIIIIIIJJIJJII()
	{
	}

	public void IJIJJJJJIJIIJJJJIIIIIIJJJIJIIJJIIIIIJIJJIJJJJIJ()
	{
	}

	public void JJJJIIJJJJJIJJIJJIJIIJJIIIJIIIIJJJIIIJIIJJJJIJI()
	{
	}

	public void JIJIJIJJIJJIIJJJIJJJIIIIJJJJJIIJIIJJIJJJJJJIJJJ()
	{
	}

	public void JJIJJIIIIJJJIJIJIIJJIIJJJJIJIJIIJJJIJIJJJIJJIII()
	{
	}

	public void IIIJJJJIJJJIIJJJIJJIJIJJIJIJJIIJJJJJIIIJJJJJJII()
	{
	}

	public void JIIJIIJIIJIJIIIJIJIJIIIJJIIJJIJIIIIIIJJIIIJIJJI()
	{
	}

	public void JIIJJIIJIJJIIJJJIJJJJJJIJIIIIJJJIJIJIJIJJIJIJJJ()
	{
	}

	public void IIIIJJJIJIJJJJJIJJIJIJIIIIJJJJIJIIIIIIIJIJJIJJI()
	{
	}
}
