using UnityEngine;

public class SpringPosition : MonoBehaviour
{
	public delegate void JIIJJIJIIJIJIJIIIIJIIJIJIIIIIJIJIJIIJIJJJIIIJII();

	public static SpringPosition JIIJIIIIIIIIIIJIJIIIJJIIJJJIIIJJIIIIIIIIJIJIJIJ;

	public Vector3 IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

	public float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI;

	public bool IJJIIJIIIJJJJIJJJJJJIIJIIJJJJIJIIJJJIJIIJIIJJJJ;

	public bool JIJJJJIIJJIIJJJJIJIIIJIJIIJJJJJIJIIIJJIJJJJIJJI;

	public bool JIJIJIJIIJIJIIJIJIIIIIIIIIJJJIIIIJIJIJIIIJJIIII;

	public JIIJJIJIIJIJIJIIIIJIIJIJIIIIIJIJIJIIJIJJJIIIJII IJIIIIIJJIIJJJIIJIIJJIIIIIIIJIJIIJIIIJJJJJIIJII;

	[HideInInspector]
	[SerializeField]
	private GameObject eventReceiver;

	[SerializeField]
	[HideInInspector]
	public string callWhenFinished;

	private Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	private float IIIIIIJIIJIIJJJIJJIIJJJJJJIJJJIIIIJIJJJJJJIIIJI;

	private UIScrollView JIIJJIIIIJIIIJIIJIJJIJIJIIJIJIJIJJJJIJJIJJIJJJI;

	public static SpringPosition JIIIJIIIJJJJJJIIIIJIIJJIJJIIIIJIIJIIIIJIIJIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI)
	{
		return null;
	}

	private void IIIIIIIIJJJJJIIJJJIJJJIJIIJJIJIIIJJIIIJJIJJIJIJ()
	{
	}

	private void JIJJJJIIIJIIIIJIJJJJIIJJJIIJJIIJJJIIIIIIIJIIIJI()
	{
	}

	private void Start()
	{
	}

	private void JJIJJJIIJIJIJIJIJJJJJIIJIJIIIIJJIIIJIIJJJJJIJIJ()
	{
	}

	private void Update()
	{
	}

	private void JIJJJJIIIIJJJIIIJJIJIJJJIJIJJJIIIIIIJIIIJJJJIIJ()
	{
	}

	private void JIIIJIIIJJJIIIIIJIIIIJJIIJIIJIJIIJJJJIIIJIIJJJI()
	{
	}

	private void JIJJJIIIIIJIJJIIJIJIIIIJIJIIJIIIIJJJIIJJJIJJJIJ()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void IJJJIIIJJIJJJJIIIJJJJJIJJJJIIJJIIIIIIIIIJJJIIJI()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void JIJJIJJIIJJIJJIJIJJIIJIJJJJJIIJIIIJJIIIJJIJIJII()
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	public static SpringPosition IIIIIIIJJIJJJIJJJJJIIJJIIIIIJJJJIJJIJJJJJJIIJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI)
	{
		return null;
	}

	public static SpringPosition IJJIIIIIIJIJIJJIJJJIJJJJIIIJIJIJIIIJIIIJIJIIJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI)
	{
		return null;
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}
}
