using System;
using UnityEngine;

public class SpringPanel : MonoBehaviour
{
	public delegate void IJIJIJIIIJJJJJIJIIIJIIIIIJJIIJIJJIIIJIJIIIIJIIJ();

	public static SpringPanel JIIJIIIIIIIIIIJIJIIIJJIIJJJIIIJJIIIIIIIIJIJIJIJ;

	public Vector3 IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

	public float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI;

	public IJIJIJIIIJJJJJIJIIIJIIIIIJJIIJIJJIIIJIJIIIIJIIJ IJIIIIIJJIIJJJIIJIIJJIIIIIIIJIJIIJIIIJJJJJIIJII;

	[NonSerialized]
	private UIPanel IJJIIJJJIIJJJIIIIJIIJIIIJIIJIJIJIJIIJIJIIJJIJJJ;

	[NonSerialized]
	private Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	[NonSerialized]
	private UIScrollView JIJJIIIIIIJJJIIJJJIJIJJIJIJIJIIIIJJIIIJJIJIIJJI;

	[NonSerialized]
	private float JJJJJIIJIIJIIIIJJJIIJJIJJIIIJIIJJJJJIIIJJIIJIII;

	private void IJIJJJJJIIJIIJIJIIIJJJIIIJIJIJIJJIJIJJJJJIJJJJJ()
	{
	}

	public static SpringPanel JIIIJIIIJJJJJJIIIIJIIJJIJJIIIIJIIJIIIIJIIJIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI)
	{
		return null;
	}

	private void JIJJIJIJIIJJJJJIIJJJIJIIJJIJIJJIJJJIIJJIIIJIIIJ()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	public static SpringPanel IIIJJJJIIJIIJJJIJJIIIIJIJIJJIJIJIJJJJJIIJIIIJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI)
	{
		return null;
	}

	private void IIJJIJIJJJJJIJJIIJIJIJJIIJIJIIJJIIIJJIIIJIIIJJI()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	public static SpringPanel JIIIIIJIJJJJIIIIJJJJJIJIJJIIJIJJJJJIIJJIJJIIIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI)
	{
		return null;
	}

	private void IJIIJJIJJJIJIJJJIIJIJIIJJJJJIJIJJJJIIJIIJIJJJJI()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	public static SpringPanel IJIJJIIIJJIIIJIIJIJIIJJJIIJJJIIIIJJJIIJIJJJJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI)
	{
		return null;
	}

	private void JIJJJJIIIJIIIIJIJJJJIIJJJIIJJIIJJJIIIIIIIJIIIJI()
	{
	}

	public static SpringPanel JJJIIIJIIJIJIJJIIIIIJIJIJIIIIJJJJJIJIIIJJIIIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return null;
	}

	private void Start()
	{
	}

	private void JIJJIJJIIJJIJJIJIJJIIJIJJJJJIIJIIIJJIIIJJIJIJII()
	{
	}

	private void JIIJIJJIIJJJJJIJJIJJIJJIJIJJJJIIJIJIJIJJJIIIJIJ()
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	public static SpringPanel JJJJIJJIJIIJIJJJIIJJIJJJIJIIIJJIJIJIJIIIIJIIJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI)
	{
		return null;
	}

	private void Update()
	{
	}

	private void JIIIJIIIJJJIIIIIJIIIIJJIIJIIJIJIIJJJJIIIJIIJJJI()
	{
	}

	protected virtual void JJIJJIJJIJIJJJIIJIJIJIJIIJJIJIJIIIJJIJIIIJJIIII()
	{
	}

	public static SpringPanel JJJIJIJIIJJIIIIIIIJIIIIJJJIIIIIJJIIIIIIJJIIIJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IIIIIIJIJIIIJJJJJIJJJIIJJIIJIJJIIJIJJIJJIIJJJJI)
	{
		return null;
	}

	protected virtual void IJJJIIJIJIJJIIIIIIIIIIIJJJJJJIIJJIIJIIIIIIJIJII()
	{
	}

	public static SpringPanel IJJJIJIJIJJJIIJJIJIJIIJIIIIIIIJJIJJIIJIJIIIIIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return null;
	}
}
