using System.Runtime.CompilerServices;
using Photon;
using UnityEngine;

public class SurfMode : Photon.MonoBehaviour
{
	private sealed class JJIJJIJIIIJIIJJJIJJJJIIJIJIJJIIJIJJIIIIJJIJIIJJ
	{
		public float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

		public double JIJJIJIIJIIJIJJJIIIJIIJJJJIIIIJJJIIJJJIIJIJIJJJ;

		public SurfMode JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		internal void IJJIIJIIJJJIJIIIIJIIIIIIIJJIIJJJJJIIIIJJJIIIJJI()
		{
		}

		internal void JIJIJIJIIIIJIIIIIJIIIIIIIIJIIIIJIIIIJIJIJJIJIII()
		{
		}

		internal void IIIJJJJIJIIJIIIJIIIJJIIIJIJIIJIIJJJJIJIJIJJIJJI()
		{
		}

		internal void IIIIIJIIJIIJIIIJIIIJIIIIIJIIIIJIIJIJJJJJIJJIIIJ()
		{
		}

		internal void JJJIIIIJIJJJIJJJIIJIIJJIJIIIJIIIIIJJIJJJJJJJJIJ()
		{
		}

		internal void IJIIJJJIIIIIJIIIIJJIIIJIIJJIJJIJJIJIIIJIJJJJJJJ()
		{
		}

		internal void IJJIJIIIJIIJIJIJIJJIJJJIJJJIIJJIJJJIJJJIIIJJIIJ()
		{
		}

		internal void IIIIJJIIIIJIIIIJIJIJJIIJJIIIIIJIJIIIIIIIIIJIJJI()
		{
		}

		internal void IIJJJJJJJIJJJJIJJIJIIIJIJJJJIJIJIJJIIIJJIIJJIIJ()
		{
		}

		internal void JJIJIJIIIIJJJJJJIJJIIIIIJIJJIIJIJIIJJIIJIIJIIII()
		{
		}

		internal void IJIJJJJIIIJJJIJJJJIIIJIJIJIJIJJIJIIJJIIIIJJJJII()
		{
		}

		internal void IJJJIIJIJJIIJJIIIIIJJJJJIJIIJIIIJJIIIIIIIIJJIJJ()
		{
		}

		internal void JJIIJJIJJIIJJJJJIJIJIIIIIIJJJIIIIIIIIIJIJIJJJII()
		{
		}

		internal void JIJJIJJJJJJJJJIJJJJJJJJIIJJIIJJJJJJIIIJJIJIJIJJ()
		{
		}

		internal void IIIJJJIJIIIJJJIIIIIJJJIIIJIJJJJJJJIJJIIIJIJIJJJ()
		{
		}

		internal void IJJJJIIJJJJJJJIJIIIJJIJIIJJJJJJJJJJIIJJJIIIJJIJ()
		{
		}

		internal void JIIIJIIIJJIJIJIIJIJIJJJIJIJIIJJJIJJIIIJIIJIJIII()
		{
		}

		internal void IJIJIIJJJIJJIIIJJJIJJJIJIIIJJIIIIIJIJIIIIJJJJII()
		{
		}

		internal void JIIJIJJJIJIIJJIIIIIJJIJJIIIIJJIIJIJIIJIIJJIIJII()
		{
		}

		internal void JIIIIJJJIJJIIJJJIIJIIIJIIJIIJJIJIIIIJIIIIIIIIJI()
		{
		}
	}

	private Vector3 IJJIIJIIIJIIJIJJJIIIIIIIIJIJIJJIIJJJJJIJIIJJIJI;

	private Quaternion IJJJJIIIIIIJJJIIIJJJIIJJIJIIIJJJIJIJJJIIIJJJJII;

	private static SurfMode JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void IJJJJIIIIJJIIIJJIJJJJJJIJIIJJJJJJJJIJJIIJIIIJIJ()
	{
	}

	private void Start()
	{
	}

	private void JIIJIJIJIIIJJJJJJJJJJJIIIIJJIJJJIIJIJJIJIIJIJIJ()
	{
	}

	[CompilerGenerated]
	private void JJJIJIIJIJJJJJJJJIIJJJJJJIIJJJJJIJJJJJJJJIIIIJI()
	{
	}

	private void JJIJIIJJIJJJJJIIIIIIIIJIIIJIJJJJIIIJIIIIIIIIJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIIJJJJIJIIJIIJIJJJJIIJIJJJIJJJJJJIIJIIJJIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void Awake()
	{
	}

	private void IJJIJIIJJIJJJIIIJJIIIJJIJJIIJJIIJJJIJJIIJIIJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJIJJIJIJJJJJIIJJJIJIJIIIIJJJIJIIJIIIJJIJIJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IJJIIJJIIJIJIIJJIJIIJIJIIJJIJJJIJJJIIIJIJIIJIJI(int IJJIIIJJIJIIIIJIJJJJIJIIIIJIIJIJJJJJIJIIJIJJJJJ, int JIIJIIIJJJIJJJIIJJIIIIJIJIJJIJJIIJIIJIJIIJJIIJI)
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void JJIJIIJJIJJJIJIJJJIIIIJIJJIIIJJJJJJJIIIIJJJJIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IIJJJJIIIJIIIJIIJIJJIIIIIIIIJJJJIJIJIJJJIJJIJIJ(int IJJIIIJJIJIIIIJIJJJJIJIIIIJIIJIJJJJJIJIIJIJJJJJ, int JIIJIIIJJJIJJJIIJJIIIIJIJIJJIJJIIJIIJIJIIJJIIJI)
	{
	}

	private void OnEnable()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void JIIIIIJIJJIIIIIIIJJIIJJJJIIJJJJJJIIJIJJJJIIIIJJ()
	{
	}

	private void JIIJIJJIIIJJIJIIJJIJIIIJIJJIJIIIIIJIJJJIIJIJIIJ()
	{
	}

	private void OnDisable()
	{
	}

	private void JIJIIJIIIJJJIJIIIJIIJJIIIJJJJJJJIJIJIIIJJJJIJJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIJIJJIIJIJJJIIIJIIIIJJJJIIJJIIJJJIIJJIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	public static void IIIIIIJJJJJJIJJJJJJJIIIJIJJJIIIIIJIIIJIIIJJIIII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJJIJIIJIJIJIIJIIJJJJJIJJJIIJJIJJJIJJIIIJIIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJIJIIIJJJIJJIIJIIIIIIJJJJJIIJIJJIIIIJJIIJJIJI()
	{
	}

	public static void IIIIIJIIJJJJJJJIJIJJJIIJJIJJJIIIIIJIJJJJJJJIJJJ(int IJJIIIJJIJIIIIJIJJJJIJIIIIJIIJIJJJJJIJIIJIJJJJJ, int JIIJIIIJJJIJJJIIJJIIIIJIJIJJIJJIIJIIJIJIIJJIIJI)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void JIIIIJJJJJIIJJJJIJJJIJJJIIIIIJJJIIIIJIIJIJIJIIJ()
	{
	}

	private void IIJIIJJIJJIIIIJJIJIIJJJJIJJIJIJIJJJJIIJJJIJIIIJ()
	{
	}

	private void JIJIIIIIJJIJJIIIIJIJIIJIIJJIJIJIIIJJIIIIJJIIIJJ()
	{
	}

	private void IIIJIIJIJJIIIIJJIJIIJIJIJJJJIJIJJJJJIIIIJIIIIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void JIJIJJIIIJIJJJJIIIJJJIIIIJIIIJIJIJIIIIIIJJJJIJI(int IJJIIIJJIJIIIIJIJJJJIJIIIIJIIJIJJJJJIJIIJIJJJJJ, int JIIJIIIJJJIJJJIIJJIIIIJIJIJJIJJIIJIIJIJIIJJIIJI)
	{
	}

	private void IJJIIIIJJJIJIJIJJIIIIIIJIIIIJJJIJJIJIJIJJJIJIJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void IJJJIIIJIJIJIJJJIIIIJJIIJIJJIJJIIJJJIIJJJIJIJII()
	{
	}
}
