using UnityEngine;

public class SurfFinish : MonoBehaviour
{
	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIIIJJJIIIJJJJJIIIJJJJJIIJJIIIIIJIJJJJIIJIJJIII;

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IIIJJJIIJIJIJJJJIIIJJJIJIIJIJJJJJJIIJIJJJJJJJJJ;

	private BoxCollider IJJIJIJJJJJJJIIIIJJJIJJJJJJIIJIIIIIJJIIIIJIJJJJ;

	private Bounds JJIJIIJJJJJIJJJIIIIJIIIIIJIJIIIJIJIIJIIIIJJJJJJ;

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void JJIJJIJIJJIIIJJJIJJJIIIIIJJIIIJJIJIJJIJJIJJJJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJIIJIJJJJJIJJJJIIJIJJJJIJJJIIJJJIJJJIIJJIIIIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJIJJIIIJIJIJIIJJIJJJIJIJJIJIIIIJIIIJIJJIIIJIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private void Start()
	{
	}

	private void IIJJIIJIIIJJJIIJJJJJJJIJIJIJJJIIIIIJIJJIIIIIJIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIIJJIIIIIIJIIJIJIIJJIJJJIJIJJJIJJJJIIJJJIJJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIIIJIIIJJIJIJIJJJIIIJIIJIIIJIJJIIIJIIIJIJJJIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJIIIJJJIJJIIJIIIJIIIJIIIIJIIJJIJIIJIIJJIIIJIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIIIJIJIJJIIJIIIIJIJIJIJIJIIJIJIJJIJJJJJIIIJIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void IIIIJJJIJIIIIIIJIIIIIJJIIJJJJJIJIIJJIIJJIIJIIJJ()
	{
	}

	private void JIIIJIJIJIJIIJJIJIIJJJJJIJIIIIIJJIJJIJJIIJJIIJJ()
	{
	}

	private void IIJIJIJJIJIIIJIJJIJIIIJIIIJJJJJIIIJJIIIJIJIIIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJJJIJIJJIIIJJIJJJJJJJIJIJIIIIJJJJIIJIJJJIIJJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void IIIIIJIJJIIIIJIIIIJIJJJIJJJJJIJIIJIIJJJIIJJIIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJJIJJIIIJIJJIIIIJIJJIJIJJJIJJIIIJJIJJIJJJJJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}
}
