using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using UnityEngine;

public class SyncBuffer : MonoBehaviour
{
	[StructLayout((LayoutKind)0, Size = 80)]
	public struct IIIJIJIIIIJIJJIJIIIJJJIIIIIIIIIJIJJJJIIJJJJIJII
	{
		public float JIIJJIJJIJJIJJJJJJIJJJJJJIJIJIIJIIJIJJIIIIJJIII;

		public Vector3 IIJIJJJIIJIJIJIIJJIJJIIIIJJJIJJIJJIIJIJJJJIIIII;

		public Vector3 IJJJJJJIIJJJIIJIJIJIIJJIIJJJJJJIIJIJJJJJJJIJJJI;

		public Vector3 IJIJJIJIIJIIIIIJIJJIIIIJIJIIIIIIIJJJJIJIIJIJJIJ;

		public Quaternion JJJIJIJJIIJJJIIJJJIIJJJIJIJJJJIJJJIIIJIJIIJIJJJ;

		public Vector3 IJJIJJIJJJIJIJJJJIJJIJJJIJIJJIIIIIIJIIIJIJJIIIJ;

		public Vector3 IJJIIJIIJJIJIIIJJJJIJJIJIIJJJIJIIJJIIJIJIIJIJJJ;
	}

	public float IIJIIJIJJIJJIJIIIJIIJJJIIJIJIIJJIJJJJJJIJJJIJJJ;

	[NonSerialized]
	public float JJJIIJIJJJJIIIIIJJJJIIJIIIJJIJJIJJIJIIIIJJJIIII;

	[NonSerialized]
	public float JIIIIJIIJIJJIIIJJIJIJIIJIJJJJJIIJJIJJIJIJIIIIII;

	[NonSerialized]
	public bool JIIIIIJJJJIIJIIJIIIIIJJJJJJJJJJIJJJIIIJIJJIJIJI;

	protected float IJIIJJIIIJJJJJJJJIJJIIJIIIIJJIIJIIJIIIIJJJJIJIJ;

	protected float JJJJJJJJIIJJIJIIIJIIIJJJJIJJIIJJIIIJIJJJJIJJIJJ;

	protected List<IIIJIJIIIIJIJJIJIIIJJJIIIIIIIIIJIJJJJIIJJJJIJII> IIIJJJJIIJJJJJIIIJIJJJJJJJJIIIJIJIJJIJJJIJJIJIJ;

	[NonSerialized]
	public Vector3 JIIIIJIIIJIJIIIJJIIIIIJJJIIIIIIJIJIIJJJIJJJIIIJ;

	[NonSerialized]
	public Quaternion JIJJJIIJJJIJJJJJIJJJIIIIJJIIIJIIJJIIIIIJIJIIJII;

	public virtual bool JIIIIJIIJIJIIJIJJJJIIIIJIJJIIIIIIIIIIIJIIIJJJJJ => JIJIIJIIJIIIIIIIJIJJIJJIIIJJIJJIIJIJJJJIJJJJJIJ();

	public virtual Vector3 IIJIJJJIIJIJIJIIJJIJJIIIIJJJIJJIJJIIJIJJJJIIIII => IIIJIJJIIIIJJJJJIIIJIIJJIIIIIJJJJJIJIIJJIIJIIIJ();

	public virtual Vector3 IJJIIJJJIJIIIJIJIIJJJJJJJIIJJIIIIJIJJIIJJIIJIJI => IIIJIIIIJIIJIIJIJIIJJJIIIJIIJIIJIIIIIIIIIIIIIJI();

	public virtual Vector3 IJJJJJJIIJJJIIJIJIJIIJJIIJJJJJJIIJIJJJJJJJIJJJI => IIJJJJIIJIJJIIIJJIIIIIIJJJIJJIIIJJJIJJJJJIJJIII();

	public virtual Quaternion JJJIJIJJIIJJJIIJJJIIJJJIJIJJJJIJJJIIIJIJIIJIJJJ => IIJIJJIIJJJIIJJIIJJIIIJIJJJJJJJIIJIJIIIJJIJJJIJ();

	public virtual Quaternion IIIJIJIIIJJIJJIJIJJJJIJJJJJIJIJJJJJJJIIJJIJJIIJ => IIIIJJJIIIIIJJJIJJJIIJJIIIJIIJJIJIJJJJJIJJIJJJI();

	public virtual Vector3 IJJIJJIJJJIJIJJJJIJJIJJJIJIJJIIIIIIJIIIJIJJIIIJ => IJJIIJIIJJIJJIIJIIIIIJJJIIIIJJJJJIIJIJIIJIIJJJJ();

	public virtual bool JJJJJIIJJIJJJJJIIJIJIIIJIJJJJJIJJJIJJJIIIIJIJJJ => IIJIJIIJIIIIIJIJIIJIJJJJJJIIIIJIIJIJJIIIIIIIIJJ();

	public virtual IIIJIJIIIIJIJJIJIIIJJJIIIIIIIIIJIJJJJIIJJJJIJII IJIJJIJJJJJIJIJIJJJIIIIIIIJJIIIIIIIIJIIJIIIJIII => JIJIIJIJIJJIIJJJJJJIIJJJIJJIIJIJIIJJJJIJJJIJJIJ();

	public virtual IIIJIJIIIIJIJJIJIIIJJJIIIIIIIIIJIJJJJIIJJJJIJII JJJIJJJIJJIJIIIJIJJJJJIIIJIJIJIJJJIIIJIIIJIIIIJ => JJJJJJJJJIIJIJIJIIIIJJJIIJIIJJJIJIIIJIIIJJJJJJI();

	public virtual IIIJIJIIIIJIJJIJIIIJJJIIIIIIIIIJIJJJJIIJJJJIJII JJJJIIJIIIIIIJJIJJIJIIJIJIJIJJIJJJJIJIIJIIJIIIJ => JIIJJIIJJIJJJJIIIIJJJIJIJJIIIJIJJJIJIJJJIJJIIIJ();

	public virtual IIIJIJIIIIJIJJIJIIIJJJIIIIIIIIIJIJJJJIIJJJJIJII JIJIIJIJIJJIIJJJJJJIIJJJIJJIIJIJIIJJJJIJJJIJJIJ()
	{
		return default;
	}

	public virtual void IIJJIJIJJJIJJJIJIJJJIIJJJIJJJJJJJIJIJJJJIJIIIIJ(float IIIJIJJIIJIIIIJJIIJJJJJJIIIIIJJJIJIIJIIJIJIIJII, Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ, Quaternion IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII = default(Quaternion), Vector3? JIIIIIJJJIJJJJIIIJJIIIIIJJIJJJJJIJIIIJJIIIJIIIJ = null, Vector3? IIJIIJIIJIIIJIJIIJJJIIJIIJIIJIIIIIIIIIIIIJJIJJJ = null, Vector3 JIJJJJJIJJJJIJIJIJIJJIJIJJJJIJJJIJJJIIJIJJIJIII = default(Vector3), Vector3 IIJIJJIIIJIJJIJJJJJJIIJJJJIJJJIJJIJIJJIIJJIIIIJ = default(Vector3))
	{
	}
	public virtual IIIJIJIIIIJIJJIJIIIJJJIIIIIIIIIJIJJJJIIJJJJIJII JJJJJJJJJJJIJJJJIIIJJIJIIIIIJJIIIJIIJJJIJIIIIIJ()
	{
		return default;
	}

	protected Quaternion JIIIJIIIIIJIJJJIIIIIJIJIIIJJJJJIIJIIIJJJJIIJJIJ(Quaternion IJJIJJJJJIIIIIJJJJIIIIIIIIJIJIJJJIIJIIIJJJJIIII, Quaternion IJJIJJIJJJJJJJJJJJJIIIIJJIIJIIIJJJIJIJIJJJJJIJI)
	{
		return default;
	}
	public virtual IIIJIJIIIIJIJJIJIIIJJJIIIIIIIIIJIJJJJIIJJJJIJII IJJIJIIJIIIIJIJIJIJIJIIJJJIIJJJJIIIIJJJJJJJJJIJ()
	{
		return default;
	}

	public virtual bool IIJIJIIJIIIIIJIJIIJIJJJJJJIIIIJIIJIJJIIIIIIIIJJ()
	{
		return false;
	}

	public virtual bool JIJIIJIIJIIIIIIIJIJJIJJIIIJJIJJIIJIJJJJIJJJJJIJ()
	{
		return false;
	}
	public virtual Vector3 JIJIJIIIIIJIJJIIJJIIIIJIIJIJIJIIJJJJJJJJIJJJJII()
	{
		return default;
	}
	public virtual Quaternion JIIIJIJJJIJJJJIJIJJJIIJIJIJIIIIJJIIJIJIIJIJJIII()
	{
		return default;
	}

	public virtual void IIIJJJIJJJJJJIIIJIIJJIJIJJJJJIIJIJJJJIIIIIJIJIJ(float JIJIIIJIJJJJJJJJJIIJJIIJJJIIIIIIJIJJJJJIJIIIJIJ)
	{
	}
	public virtual Vector3 IJJIJIIIIIIIIJIIJJJJJIJIJIJIJJJIIJJIIIJJJJIJJII()
	{
		return default;
	}
	public virtual Vector3 IJIIJIJJIIIJIJJIJIJJIIJIJJIJIIIIJIJIIJJJIJJJIJJ()
	{
		return default;
	}
	public virtual Vector3 JIJJIJIJJIJIJJJJJJIIIJJJJIJJJJJIJJIJIIJIIJIIIII()
	{
		return default;
	}

	protected Vector3 JIIJIJIIJIIIJIIJJJIJJJJJIIJIJIIIIJJJIJIJJIJIJII(Vector3 JJIIJJJJJJIIJJJJJIJIJJIJIJJIJIJJJJIIJJJIJIIIJJI)
	{
		return default;
	}

	public virtual Vector3 IIIJIJJIIIIJJJJJIIIJIIJJIIIIIJJJJJIJIIJJIIJIIIJ()
	{
		return default;
	}

	public virtual Quaternion IIJIJJIIJJJIIJJIIJJIIIJIJJJJJJJIIJIJIIIJJIJJJIJ()
	{
		return default;
	}

	protected Vector3 IJJJJJIIIIJJIIIJJIJIJIJIJJJJIJIIIIIJIIJJJIJIIJJ(Vector3 JJIIJJJJJJIIJJJJJIJIJJIJIJJIJIJJJJIIJJJIJIIIJJI)
	{
		return default;
	}

	public virtual IIIJIJIIIIJIJJIJIIIJJJIIIIIIIIIJIJJJJIIJJJJIJII JJJJJJJJJIIJIJIJIIIIJJJIIJIIJJJIJIIIJIIIJJJJJJI()
	{
		return default;
	}

	public virtual Quaternion IIIIJJJIIIIIJJJIJJJIIJJIIIJIIJJIJIJJJJJIJJIJJJI()
	{
		return default;
	}
	public virtual IIIJIJIIIIJIJJIJIIIJJJIIIIIIIIIJIJJJJIIJJJJIJII IJJIJJIIIIJIIIJIJJJIJJJIJJIIJJIJJJJJIJIJJIJJIIJ()
	{
		return default;
	}
	public virtual IIIJIJIIIIJIJJIJIIIJJJIIIIIIIIIJIJJJJIIJJJJIJII JJJIIJIJJJJJJIJIIJJIJIIIJJIIIIJJIIIIJJIJIJJJJII()
	{
		return default;
	}

	public virtual Vector3 IIIJIIIIJIIJIIJIJIIJJJIIIJIIJIIJIIIIIIIIIIIIIJI()
	{
		return default;
	}

	public virtual IIIJIJIIIIJIJJIJIIIJJJIIIIIIIIIJIJJJJIIJJJJIJII JIIJJIIJJIJJJJIIIIJJJIJIJJIIIJIJJJIJIJJJIJJIIIJ()
	{
		return default;
	}

	public virtual Vector3 IIJJJJIIJIJJIIIJJIIIIIIJJJIJJIIIJJJIJJJJJIJJIII()
	{
		return default;
	}

	public virtual Vector3 IJJIIJIIJJIJJIIJIIIIIJJJIIIIJJJJJIIJIJIIJIIJJJJ()
	{
		return default;
	}
	public virtual Vector3 IIIIIIJJIIIIIIJJJJIJIJIJJIJJJIIIIIIIIIIJIIJIIIJ()
	{
		return default;
	}
	public virtual Quaternion IIJJJJJIIJIIIIIJIIIIJIIJJIIJJJIJIIIIJJJJJJIJIJJ()
	{
		return default;
	}
}
