using System.Runtime.CompilerServices;
using Photon;

public class TennisMode : MonoBehaviour
{
	public SpawnPoint[] IJJJIIJJIIIIIJJJIIIIIIJJJJJIIIIIJIIIIJJJIIJJIJJ;

	private void IIJIIIJJJJJJJJIJJJJIJJJIJIJIJIIIIIIIJJJIIIIJIJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJJJIIIIJIIIIIJJIIJIIIJIJJJJJJJJJIIJIIIIIIJIJJ()
	{
	}

	[CompilerGenerated]
	private void IIIIJIIJIJJIIJJIJJJJJJJJIIJIJJIJJIIIJJIIIIJIIII()
	{
	}

	private void JIJJIIJJIIIIJIIIIIJIJIIIJIJIJJJIIJIIIJIJIIIJIJJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJIJJJIJIJJJJIJJJJIIIIJJIIIJJJIJJJIIJJIJJIIJII(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void Start()
	{
	}

	private void JIJJJJIIJIJIIJIIIIIJIIJJIJIIJIJJIJJIJIJIIIIIJII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private void JIIIIJIJIJIIJIIIIJIJJIIIIIIIIJJJJIIJIJJJJIIJIII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJIJIIIIJIJIJJIIIJIJIIJJJJJJIIIJIJJIIJJJJJJIIJJ()
	{
	}

	[CompilerGenerated]
	private void IJJIIIJIIIIJJIJIIIJJJJIJIIIIIIIJIIJJJJJIJIIIJJJ()
	{
	}

	private void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void IIIJJIJIIJIJJJIIIIIJJJIIIIIIIIJIJJJJJJIIIIIIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnDisable()
	{
	}

	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII()
	{
	}

	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII()
	{
	}

	[CompilerGenerated]
	private void IIJJIJJIIIJIJJIIJIIIJIJIJJIJJJJIJJIIIIIIJIJJJJI()
	{
	}

	private void IIIIIIJIJJIIJIIIIJJIJJJJJIJIJJIIJJJJJIJIIJJIJJJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIIIJIIIJJJJJJIJIIIIJJJJIIJIIIJJIJIJIIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJIJIJJIJJJIIJJIJJJJJIIJJIJIIIIJIIJIIJIJJJJJJJI()
	{
	}

	private void IJIIJIIIJJIIIIJIJJJIJJIIJIIIJJIIIIJJIIJJIJIIIJI()
	{
	}

	private void JJIIIIJIJIJJJJJIJJIJIIIJIIIJJIJIJIIJIIIIIIIJIJJ()
	{
	}

	[CompilerGenerated]
	private void JJJIJIJIJIJJIIJIIJIJJJJIJIIJJJJIJIIJIIJJJJJIIIJ()
	{
	}

	private void IIIIJJIIJJIIIJIJIIJIIJIJIJIIJIIIJJIIJIJJIIJJIII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void OnEnable()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void IIJJIIJJJJIJJJJIIIJJJJJIIJIJJJIJIIIJIJJJIIIIIJI(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}
}
