using UnityEngine;

public class TestFontIcon : MonoBehaviour
{
	public UILabel JJJJJIJJIIJIIJIJJIIJJIJIJIIJJJJIJIIJJJIIIJJJJJJ;

	public int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ;

	public void JIIIIJIIJIJIIJJIIIIIJIIJJIJIIJJJIJJIJIIIJJJIJIJ()
	{
	}

	public void IJIIJIJJIIJIIJIIJJJIJIIIJJJIJIIJIJIJIJJIIIIJJIJ()
	{
	}

	public void IIJJJJIIIIJJIIJIIJIIJJJJIJIIIIIIJIIJIIJJJJIIJJJ()
	{
	}

	public void IJJIJJIJJIJJJIJJJJIIIJJIJJJJIIIJJIJJJJJIIIIJJJI()
	{
	}

	public void IIJJIJIJJIJIIJIJIJIIJIIJIJJJIIIIJJIJJIIIJJJJJIJ()
	{
	}

	public void JIJJJIJJJIIJJIJJJJJJIIIIJJJJJJIIJIIJJIIJIJJIJJJ()
	{
	}

	public void JJJJIIJJIIJJJJJIJJIJJJIJIIIIJIJIIIJIIJJJIJIIJII()
	{
	}

	public void JJJIJIJJJJIJIIJJIJIIJIIIIIJIIIJIIIJJJJJIIJJIIII()
	{
	}

	public void JJJIJIIJJJJJIIIIIJJJJIIIIJJJJIJJJJJJJIJJIIIIJJJ()
	{
	}

	public void IJJJJJJIJJIJIJJIIIJJJJIJIIJIIJIIJIIIJIIJJJJJJJJ()
	{
	}

	public void JIJIJJIIIIIJIIIJJJIJIJJJIIIJJIIIJJJIIIJJIIJJJII()
	{
	}

	public void JJJIIIIJIIIJJJIIJIIIJJJIJJJJJIIJJIJIIJIJIJIJIII()
	{
	}

	public void JJJJJIIJJIJJIIIIJIIIJJJIJIJJJJIIIIJJIIIJJIJJIIJ()
	{
	}

	public void JIIIJJJIJIIJJIJJIJJJIIIJJJJJJJJJJIJJIIJJJJJJIJI()
	{
	}

	public void IIIIIJIIJJJIJIJIIIJJJIJIIJIJJJIIIIJIJIIJIJJIJJI()
	{
	}

	public void JIJIJJJIIIIJIIIIJJJIIJJJJJIJJIJJIIJJJJIJIIJIJIJ()
	{
	}

	public void JIIJIJJJIJIIIJJJIJIJJIJJIJJIJJIIJIJJIIJIIJJIIIJ()
	{
	}

	public void IJJJIJIIIIJJJIIJIJJIJIIJIIJIJJIJJJIIJIJJJIIJIII()
	{
	}
}
