using Photon;
using UnityEngine;

public class ThrowingObject : Photon.MonoBehaviour, JIIIJJJIJIJJIJIJJIJJIJJJJJJJJIJIIIJJIIJJJJIJJJI
{
	public float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

	public float JIIJJJIIIJJIIIIJIJJJIIIJJIIIJJIIJIJJJJJJIJJJJJI;

	public GameObject JIIIJIJJJIJJIJIJIIIJJJJIIJIJJJIIIJJIIIJIJIIJIII;

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ;

	public Rigidbody IIJJIJIIIJJJJIJIJIIJJJIIJIIJIIJIJJJIIIIIIIJIJJI;

	public GameObject IJIIIJIIJJIIJIJIIIJIJJIJJJIIIIIJJIIIIIIJJIIIIII;

	private Vector3 IIJJIJJIJIJJIIIJIJIIJIIIIJJIJJIJJJIJJJJIJIIIIII;

	private Quaternion IJJIIIIIIJIJJIIIIJJJJIIIJJIJIJJJIIJJJIJJJJIJJJJ;

	private bool JJIIJIJIJJJJJIIJJJIIJJJIJIJJIIJJJJIJIIIIIIIIIJI;

	private bool JIJIJIIJJIJIJJJIJIIJIIIIJIIIJJIIIJJJJJJJJJIIIJI;

	private void IIJIJIJJIJIIIJIJJIJIIIJIIIJJJJJIIIJJIIIJIJIIIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	public void IJIJJJIJJJIIJIIIIJJIIIJIJIJJJIIJIJIIIIIIIIJIJJJ(JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ IJJJJIIJIIIIJJJIJIJJIIJIIIJIJIIIIIIJIIIIJIJIIJI)
	{
	}

	private void JJJIIIIIIIJJJIIJIIIIJJJJIIIIIIIIJJJJJJJIIIJIIJJ()
	{
	}

	private void JJIIJJJIIIIJIJIJJIIIIJIJJJJIIIJIIIJJJIJJJIJIIII(IIJJIIIJIIIJJJIJJJJJJJIIJIIJJIIIIJJJIIJIJIIIJIJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI)
	{
	}

	private void Start()
	{
	}

	private void Update()
	{
	}

	private void IJJJJIIJJJJIJIJIJJIJJIJIJJIIJIIJJIIIJIJIJIJJIJI()
	{
	}

	private void JJJJJJJIIJIJJIIIJIIJJJIJIJJJIIJJJIJIIJIJJJJJJIJ(IIJJIIIJIIIJJJIJJJJJJJIIJIIJJIIIIJJJIIJIJIIIJIJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI)
	{
	}

	public void JJJJJJJIJJJIIJJJIJJIIIIIIIIIIJIIIJIJIJJIJJIJJJJ(JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ IJJJJIIJIIIIJJJIJIJJIIJIIIJIJIIIIIIJIIIIJIJIIJI)
	{
	}

	private void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}

	public void IJJJIIIIJIIIIJJJJJIIIJJJIIJJJJIJJIIIJIIJJJJJIII(JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ IJJJJIIJIIIIJJJIJIJJIIJIIIJIJIIIIIIJIIIIJIJIIJI)
	{
	}

	private void IIIIIJIIJJIIIIJIJIJIJJIIIIIIJIIJIIIIJJJJJJJIIJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIJIJJJJJIJJIJIJJJIJJJIIJJIIIJJIIJJJJJJIIIIII(IIJJIIIJIIIJJJIJJJJJJJIIJIIJJIIIIJJJIIJIJIIIJIJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI)
	{
	}

	private void JIJJJIIIIIJIJJIIJIJIIIIJIJIIJIIIIJJJIIJJJIJJJIJ()
	{
	}

	public void OnPhotonSerializeView(JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ IJJJJIIJIIIIJJJIJIJJIIJIIIJIJIIIIIIJIIIIJIJIIJI)
	{
	}

	private void JIJJIJJIIJJIJJIJIJJIIJIJJJJJIIJIIIJJIIIJJIJIJII()
	{
	}

	private void JJIIIJJJJJIJIIIJJJJIJIIIIJIJJIIIJIJJIIIJIIIIJII()
	{
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	public void IJJJIJIIIJIIJIIJJIIJJJIJIIJIJIIIJIJJJIIJIIIJIIJ(JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ IJJJJIIJIIIIJJJIJIJJIIJIIIJIJIIIIIIJIIIIJIJIIJI)
	{
	}

	public void JJJJIJIIIJIJJIJJIIIJIJIJJJIIIIJIJIIIJIJJJJJIJJJ(JJJIIJJJJIIIIJJIIJIJJIJIIJJJIJJJIJIJJIIIIIJJIJJ IJJJJIIJIIIIJJJIJIJJIIJIIIJIJIIIIIIJIIIIJIJIIJI)
	{
	}

	private void IIJIIJIIIJJJIIJJJIIJIJIJJIJIIJJJIIIIJIJIJJJIIII(IIJJIIIJIIIJJJIJJJJJJJIIJIIJJIIIIJJJIIJIJIIIJIJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI)
	{
	}

	private void JJJIIIJIJJJIIIIJIJIJJJJIJJIIIJIIIJIJJIJIIJJIIJJ()
	{
	}

	private void OnEnable()
	{
	}

	private void JIIIJIIJJJJIJIJJJIIIIIJIJJIIIIJJJJJJJJIJIIIIJJI()
	{
	}

	private void OnDisable()
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJJJIJIJJIIIJJIJJJJJJJIJIJIIIIJJJJIIJIJJJIIJJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}
}
