using System.Collections.Generic;
using UnityEngine;

public class TicTacToe : MonoBehaviour
{
	public class JIJJIJIIJJJJJIJJJJIIIJJJIIJJJJIIJJIIIIIJJJIJIIJ
	{
		public int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ;

		public int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI;

		public int JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII;
	}

	public class IIJJJJJJIIJJIIJJJIIIIJIIIJIIIJIIJJIJIJIJJJJIJJI
	{
		public int JIJJIIIIJJIIJJJIJIIIJIIJIJIJJJJJIJJJJIJJIIJIJII;

		public JIJJIJIIJJJJJIJJJJIIIJJJIIJJJJIIJJIIIIIJJJIJIIJ JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII;

		public IIJJJJJJIIJJIIJJJIIIIJIIIJIIIJIIJJIJIJIJJJJIJJI(int JIJJIIIIJJIIJJJIJIIIJIIJIJIJJJJJIJJJJIJJIIJIJII, JIJJIJIIJJJJJIJJJJIIIJJJIIJJJJIIJJIIIIIJJJIJIIJ JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII)
		{
		}
	}

	public UIPanel JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ;

	public Texture JJIIJJIJIIIJJIIIJIIIJIIIIJIIJIIJIJJIIJJIIJJIIJJ;

	public Texture JIIJJIJJJIJIJIJJIJIJJJJJIIJIIIJJIIIJJIIJJJIJJIJ;

	public UITexture[] JIIJJIJIIJJIJIJIJIJIIIJIJJJIJJIJIJIIJIJJJJJIJII;

	private bool JIIJJIIIIJIJJIJJIJJIJIIJIIIIIJJJJIIJJIJJIJIIJIJ;

	private JIJJIJIIJJJJJIJJJJIIIJJJIIJJJJIIJJIIIIIJJJIJIIJ[,] IIIIIIJIJJJIIIIIIIIIJIJIIIIIJIIIJIJJJJIIJJJJIJI;

	public List<IIJJJJJJIIJJIIJJJIIIIJIIIJIIIJIIJJIJIJIJJJJIJJI> JIJJJJIJJIJIIJJJJJJJIIIIJIIIIIJJIIJJJIIIIIJIJIJ;

	private static TicTacToe JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public bool JJIIJJJJIJJIJIIIJIJIIJJIIIIIJIIJJJJIIIJIIJIIJIJ()
	{
		return false;
	}

	public void IJIJIIIIIIIJIJJIJJJIJJIJIIIIJJIIJJJIJIIJJJJJIJJ(int JJJIJJIIJJJJIJJJJIIJJJIJIJJIJJIIJIJIIIIIIJJJJII, int JJJIJJIIJIIJJJJJIIJJJJIJIJJIJJIJJJIIIIIJIJIIJJJ)
	{
	}

	public void JJJIJJJIJJIJIIJIJJJIIJJJIIIJIJIJIIIJJIJIIIJJIJJ()
	{
	}

	public static void JIJIJIIJIJJJIJIJIJJJJIJJJIIIIJJIJJIIIIIIJJJJJJJ()
	{
	}

	public static void IJJJIIIIIIJIJJIJIJIIIIIIJIIIJIIJJJIJJJJJJJJJIJI()
	{
	}

	private void JJIJJIIIIJIJJIIJJIIIJIJIIJJIJIIIJJIJJIIIIIJJIJJ()
	{
	}

	public void IIJJJJJJIJJIIIIIIJJJJJIJIJIJIJJIIJIJIIJIIJJJJII(int JJJIJJIIJJJJIJJJJIIJJJIJIJJIJJIIJIJIIIIIIJJJJII, int JJJIJJIIJIIJJJJJIIJJJJIJIJJIJJIJJJIIIIIJIJIIJJJ)
	{
	}

	public JIJJIJIIJJJJJIJJJJIIIJJJIIJJJJIIJJIIIIIJJJIJIIJ JJIIIIJIIJJJIIJIIIIJIJJIIIIJIJIIIJJIJIJIIJJIIJJ()
	{
		return null;
	}

	public void Click(GameObject go)
	{
	}

	private void Start()
	{
	}

	public bool JJIIJIIIJJJJIJIJIJIIJJJJJIJJJIIIJJIJIJJIJIIIIIJ()
	{
		return false;
	}

	private List<JIJJIJIIJJJJJIJJJJIIIJJJIIJJJJIIJJIIIIIJJJIJIIJ> JJJJJIIIJIIIIJIJIIJJIJJJIJIJIIIJJIJJIJJJIJIJIJI()
	{
		return null;
	}

	private void JIIIIIJJIIIJIIIJIJIJIIIJIIIJJIJJIIIJIJIJJJIJIJI()
	{
	}

	public static void IJIJIJIJIIIJJIJJIIIIJIIIIJIIJIJJIIJIIIIJJIJIIII()
	{
	}

	public int JJJJJJIJJIJJIJIJJJJIJIIJJJJIJIJJIIIJJIJJIIJIIIJ(List<int> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
		return 0;
	}

	private void JJIIJIIIIJIJIIIJJIIJIJJIIIJIJJIIIJIIIIIIIIJJJJI()
	{
	}

	public bool JIJJIJJJJIIIIJIJJIJJIIJIJJJJJJJIIIJJJIJJIJIJJJJ(int JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, int IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI)
	{
		return false;
	}

	private void IJJJIIIIIJJJJJJJIIIIIIJJIIJJJJJIIIJJJJJJIJIIIII()
	{
	}

	public int JJIIIIJJIIIIIJIJIJIIIIIJJJJIIIJIIJJIJJIIJJJIJJI(List<int> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
		return 0;
	}

	public int IIIIIIIIJIJJIIJJIIJJIIJJIIJIIIIJJIIJIJIJIIJJIII(int JJJIJJIIJJJJIJJJJIIJJJIJIJJIJJIIJIJIIIIIIJJJJII, int JJJIJJIIJIIJJJJJIIJJJJIJIJJIJJIJJJIIIIIJIJIIJJJ)
	{
		return 0;
	}

	public void Close()
	{
	}

	public bool IJJJJIIIIIJIJIIIIIIIJJJJIIJIIJIJJIIIJJIIJIIIIJI()
	{
		return false;
	}

	private void IJJJIIIIJIIJJJJJJJIJIIIIJIIIIJJJJIIIIJJIJJIJIIJ()
	{
	}

	private void IJJJIIIIJJJJJJJJJIJIJIJIIJJIIJIJIJIJJIIJIJJIJJJ()
	{
	}

	public int JJIJIIIIIIJIIJJJJIJJIIJJJJIIIIJJJIIIJIIJJJIJIJI(List<int> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
		return 0;
	}

	public bool JIIJIIJJJJJIJIJJIIIIIIJIJJIJIJJIJJIJJJJJJJJIIJI()
	{
		return false;
	}
}
