using System.Collections.Generic;
using UnityEngine;

public class TNTRunManager : MonoBehaviour
{
	public static TNTRunManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private List<short> JIJJJIJIIJJJJJJIIIIIIIIIJJJJIIIJJIJJJJIIJJJIJII;

	public void IIIIJJJJIIIIIJIJJIJJJIJIIIIJJIIJJIIJJIIIJIJIJJI()
	{
	}

	public List<short> IJIJIJIJIIJIIJJJJJJJJIIJJIJIJIJJJJIJIJIIJIJIIIJ()
	{
		return null;
	}

	public bool JIIJJIIJJIJJJJIJJIIIIIJIJIIIIIJIJJIIJJJJIJJJIIJ(int IJJIJJJJJIIIIIIIIIJJJJJJJJIJIIJJJIIIIJJIJIJJJIJ)
	{
		return false;
	}

	public List<short> IJJJIJJIJJJJIIIJJIIIIJJIIIJIIJIJJIIIIJJJIIJIJJJ()
	{
		return null;
	}

	public void JIIIIIJJIIJJIJJJIIJJJJJJIIJJIIJJIIIJJIJIIJIJJIJ(short[] JJJJIIJIIJIIIJIJJJIIIIJIIJIIIIJIIIJIJIJJIJIIJII)
	{
	}

	public List<short> JJIJJIJIIJIJIIIJIIJIIJIIIJIJIIIIJIJIJIIJJJIIJIJ()
	{
		return null;
	}

	public bool IIIIJJJJIJJIIJJJJJIJJJIIJIJIJJJJJJJIJJIJIJIJIJJ(int IJJIJJJJJIIIIIIIIIJJJJJJJJIJIIJJJIIIIJJIJIJJJIJ)
	{
		return false;
	}

	private void Awake()
	{
	}

	public bool JIIJIJIJJIIIIJJIJJJIJJJJJJJJJIIJIJIIIIJIJIJJIII(int IJJIJJJJJIIIIIIIIIJJJJJJJJIJIIJJJIIIIJJIJIJJJIJ)
	{
		return false;
	}

	public void IIJJIIJJIJIJJJIIIJJJIIIIJIJJJIIJIJIIIJIIIIIJIJJ(short IJJIJJJJJIIIIIIIIIJJJJJJJJIJIIJJJIIIIJJIJIJJJIJ)
	{
	}

	private void IIIJIJJJIIJIIIJIIJJJIJJIJIIJJJIJJIIIJJJJIIJJJIJ()
	{
	}

	public void JJIIJIIIJIIIJIIJIJJIJJJIJJIIJIIIIIIJIJJJJJJIIJJ(short[] JJJJIIJIIJIIIJIJJJIIIIJIIJIIIIJIIIJIJIJJIJIIJII)
	{
	}

	public void IJJJIJJIIJIIIJIIJJJJIIJJJIJJIJIJJJIIJIIIIIJJJII(short IJJIJJJJJIIIIIIIIIJJJJJJJJIJIIJJJIIIIJJIJIJJJIJ)
	{
	}

	public void JIJIJIJJIIJIIJJIIJIJJJIJJIIJJIJJIIIIIJJJJIJJIJI()
	{
	}

	public void IJIJJIIJJIIIJJIIIIIIIIIIJIJIIJIIJIIIJIJIJJIJIIJ()
	{
	}

	public bool IJJJJIJJJJJJJJIJJJIJJIIJJIIJJIIIJJJIJIJJJIJIIJJ(int IJJIJJJJJIIIIIIIIIJJJJJJJJIJIIJJJIIIIJJIJIJJJIJ)
	{
		return false;
	}

	public List<short> IJJJJIIIJIJIJJIJIJIJIIJIJIIJJIIJJJJJIIJJIIJJIJJ()
	{
		return null;
	}
}
