using System.Runtime.CompilerServices;
using Photon;
using UnityEngine;

public class TNTRunMode : Photon.MonoBehaviour
{
	public float JIIJJJIIJJIIIJJIIIJIIIJIJIJJJJJJIJIJJJIIJJJJJII;

	public Vector3 JJIJIIJJJJIJIIJIIIJJJIJIJJJIJIJIIIJIJIJJJJJIIJJ;

	public static TNTRunMode JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void Awake()
	{
	}

	private void OnDisable()
	{
	}

	[CompilerGenerated]
	private void JIJJIJIJJIIJIIJJJIJIIJIIJIIJIIJIIJJIJIJJIIIIJJJ()
	{
	}

	private void IIJJIJIJJIIIIJJJIJIIJIJJJJIJJIJIIIIIJJJIIJIIJII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJIIIIIJJIJIIIJJIJIJIIJIIJIJIIJJIIJIJIIJIIIIII()
	{
	}

	private void JIIIIJIJIJIIJIIIIJIJJIIIIIIIIJJJJIIJIJJJJIIJIII()
	{
	}

	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII()
	{
	}

	private void IIIIIIIIIJJJIJIJJJIJIIJIJIJJJIIJIJJJJJIIJJIIJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIIJIIJJIIJJJIJIIIIIIJJJJJIIIIIJJJIIJJIJJJJJJJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void IJJIJJJJJIJIIIJJJIJIJIIIIJJIJIIJIIJIJJIIIJJIJIJ()
	{
	}

	private void IIIJJJJJIJJIJIJIIIIJIIJJJIJJJJIIIIIJIIJIJJIJJIJ()
	{
	}

	private void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJIJJIJJJIJIIIJJIIIJIIIJJIJJIIJJIIJIIJIIIJIJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void JIIJJJIJJJIIIJJJJIIJJJIJJIJJJIJIJJIJIJJIIIJIIII()
	{
	}

	private void IJIIJIJJIIIIIJJJJIIIIJJIIIIJJIIJIIJIIIJIJIJJIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJJJJJIJJIJIIJJIIJJJIIIJIIJJIJIIIJJJIJJIJJIJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnEnable()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJIJJJJIJJJJJIIIJJIIJJIIIIJIJIIIJJJIJJIIJIJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJIIIJIJJIJIIIJJIJJJIIJJIJJJIIJIJJIJJIIIJIJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJJJIJJJJIJIJIJIJJJJJJJIJJJIJIJJJJJJIJJIIIIIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII()
	{
	}

	private void JIJJJJIIJIJIIJIIIIIJIIJJIJIIJIJJIJJIJIJIIIIIJII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	public void IIIIJIIIJIJJJJJIIIIIIJIJIIIJIIJJJIIIJJIIJIIJIII(Transform JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	private void IJJIJJIIIIIIIIIIJIIIJJIJIJJIIJIIIJIIJJIIJJIJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIJJJJJJIIJIJJJJIIJJIIJJIIIJIJIJJIIJJJJIIJIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJIJIIJJIIJJJIIIJJIIIJJJIJJIIJJIIIJIIJJIJIJJJJ()
	{
	}

	private void IIIJIJJJIIJIIIJIIJJJIJJIJIIJJJIJJIIIJJJJIIJJJIJ()
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void Start()
	{
	}

	private void IJIJIJJIJJJIIJJIJJJJJIIJJIJIIIIJIIJIIJIJJJJJJJI()
	{
	}

	private void JJJJJIJJIJJJIIIIJIIIJIJIIIJIJJJIIJJIJIJIIJJIJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void IIIJIJJIJJIJIJIJIJIIIIJIIJJIIIJJJIJJJJIIJIIJIIJ()
	{
	}

	[CompilerGenerated]
	private void JIIJJIJJIIJIJIIJIJIJJIIIIJIJJIIIJIJJIJJJIIIIJJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIJIJJIIJIJJJIIIJIIIIJJJJIIJJIIJJJIIJJIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void JIIIIJJJJJIIJJJJIJJJIJJJIIIIIJJJIIIIJIIJIJIJIIJ()
	{
	}

	private void IJJJJIIIIJIIIIIJJIIJIIIJIJJJJJJJJJIIJIIIIIIJIJJ()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}
}
