using UnityEngine;

public class TNTRunBlock : MonoBehaviour
{
	public int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ;

	public BoxCollider IJIIJJJJIJIJJJJIJJIIIIJIJJJJIIIIJIIJJJJIJIIIJIJ;

	public MeshRenderer JIJIJIIJJJIJIJIIIJIJJJJIIIJIIIJIIJJIIIIJJJJIJJJ;
}
