using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class TPWeaponShooter : MonoBehaviour
{
	[Serializable]
	public class JJJJJIIIJIIJIJIJIIIIJIIJJIJJJJIIJIJJIIJJJJIJIII
	{
		public int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ;

		public int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ;

		public byte[] IIIJIJJJIJJIJIIIJIIJJJIIIIIJIJIJIIIIIIIJJJIIIII;

		public int IJJJIIIIJIIIJIIJJJIJJIJIIIIIJIIIIIJIIJJIJIIJIJJ;
	}

	[Serializable]
	public class JJJIIJJIIJJIJJJIIIIJIIIIJIIIIJIJIIJIJIJIIIJIIJJ
	{
		[IIIJJJIJIJIIJJIIIIIIJJJJJJIJIIIJIJIIJIJIIIJJJIJ]
		public bool IJJJJIIIIJIJIIIIIJJIJIJJIIIJJIIIIIJIIIJJJIIIIII;

		public GameObject IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

		public MeshAtlas[] IIJJJJIJIIIIJIJJJJJIJIIJIIIJIJJJIIIJIJJJJIJJIJI;
	}

	[Serializable]
	public class JIIIIIJIJIJJJIJIJJJIJIIIJJIJJJJJIIJIJJJIJIIIIII
	{
		public bool IJJJJIIIIJIJIIIIIJJIJIJJIIIJJIIIIIJIIIJJJIIIIII;

		public Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI;

		public MeshRenderer JJJJJJIJJIJIIIJJJIIIJJIJIJJJIIIIIIIJIJJJIIJJIJI;
	}

	[Serializable]
	public class JIJIJIJIJJIIJIIJIIJJJIIIIIIJIJIIJJIJJJIJJJJJIJJ
	{
		public bool IJJJJIIIIJIJIIIIIJJIJIJJIIIJJIIIIIJIIIJJJIIIIII;

		public GameObject IIJIIJJIJIJIIJIIJJIIJJIJIIIJJJIIJIIJJIJJIIJJJIJ;

		public JIIIIIJIJIJJJIJIJJJIJIIIJJIJJJJJIIJIJJJIJIIIIII JIIJJIJIJIJIIJJIJJIJJJIIJJIJIJIJJJJJJJIJJIJIJII;

		public JIIIIIJIJIJJJIJIJJJIJIIIJJIJJJJJIIJIJJJIJIIIIII IJJIJIJIIJJIIJJIIIJIJJIIIIIIIIJIIIJJIJJIJIIJJJI;

		public Vector3 IIIIIJJIJIJIIJIJJJIJIIIIJIIJIJJJJJJIIIIIIJIIJJI;

		public Vector3 JIJJIIJIJJJJIIIJIJIJIJIIIJJJIIJJIIJIJIIJJJJIJJI;

		public Transform JJIJIJJIIIJIJJIIJIIIJIJIJIJIIJIIIIJJIIIIIIIIIJJ;

		[IIIJJJIJIJIIJJIIIIIIJJJJJJIJIIIJIJIIJIJIIIJJJIJ]
		public bool IJJIIIJIJIIIIIJIIIIJIIIJIJIIIJIJIIJJIJJJIIJIJJJ;
	}

	[Serializable]
	public class IIIIJIIIIIJJJIIJIIIIJIJJJIJIJJJJIIJJJJJJJIIJIII
	{
		public bool IJJJJIIIIJIJIIIIIJJIJIJJIIIJJIIIIIJIIIJJJIIIIII;

		public ParticleSystem JIJJJIIJIIIIJIIIJJIJIIIIJIIIIJIJIJJJIIIJIJIJIII;

		public Transform JIIIIJJJIJIIJIJJIJJIIJIIJIIIIJIJJIJJIJIIJIJJJJI;

		public float JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII;

		[IIIJJJIJIJIIJJIIIIIIJJJJJJIJIIIJIJIIJIJIIIJJJIJ]
		public float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ;
	}

	public JJJJJIIIJIIJIJIJIIIIJIIJJIJJJJIIJIJJIIJJJJIJIII JJJJJIIJJIIJJJIIIIJIIJJJIJJJJIJIIJIIJIIIIIIIJJJ;

	public MeshAtlas[] IJIIIJJIJJJIIJJJJJJJJJIIJJJIIIJJJJJIIIJJIJIJJJI;

	public JIIIIIJIJIJJJIJIJJJIJIIIJJIJJJJJIIJIJJJIJIIIIII IIJIIIJIIJIIJIIJIJIIJJJJJIIIIIJIIJIJJIIIJJJIIII;

	public Vector3 IJIJJJIIIJIIJJJIIIJIJJIJJIIJJJJIIJIJIIIIIIJIJIJ;

	public Quaternion IJIIJIJIJIIJIJJJIJIJIJJJIIJIIJJJIIIIJIIJIIIIIIJ;

	public JJJIIJJIIJJIJJJIIIIJIIIIJIIIIJIJIIJIJIJIIIJIIJJ JIJJJJJIJIJIJJJJJIJJJIJIIIJJIJIJIJIJJJJJJJJJIII;

	public MeshAtlas[] JIIIIJJJJJIJIJJJJIIIIIJIIJIIJJIIJJIIJIJJIIIIIIJ;

	public JIJIJIJIJJIIJIIJIIJJJIIIIIIJIJIIJJIJJJIJJJJJIJJ IIJJJJJJJJJIJIJJIIIIJJIJJJIIIJJIIJIIJIJJIIJIIII;

	public IIIIJIIIIIJJJIIJIIIIJIJJJIJIJJJJIIJJJJJJJIIJIII JIJJJJJIJIIJIJIIIIJJIIJIJIIJIJIJIJIIJJIJIIIIIJI;

	public bool IIJJIIIIIJIIJIIJIIJJJJJJJJIJJIJIJJIIJIJIJIIJIJJ;

	public nTimer IIIIIJIIJIJIIIIJIJIJJIIIJIJJIJJIJIIJJJIJIJIJJJJ;

	private PlayerSkin IIIJJJJIIIIJIJIJIJIIIJIIJIIJJJIIIIJJIIIJIJJIIJJ;

	private JIIJIJIJJJJIIJIJJJIJJJJIIJIJIIIIIIJIIIJJIIJIJJI JIJJIJIJJIJJIJJJJJIJIJIJJJJJJIJIJIIIIIJIJIJJIIJ;

	private JIIJIJIJJJJIIJIJJJIJJJJIIJIJIIIIIIJIIIJJIIJIJJI JIIJIIIIJIJJIJIJJJJIJJIIJJIIIIJJJJIIJIJIJJJJJJJ;

	private Transform IJJIJJJJJIJIIJJIJJJIIIIJIIIIIIIIIIIIIJIJJIJIJJJ;

	private GameObject JIIIJIJJJIJJIJIJIIIJJJJIIJIJJJIIIJJIIIJIJIIJIII;

	private TimerData JJJIJJJIIIIJIJIIIJIJIIIJJIJIIIIIJJIIJJJIIJIIJJI;

	private TimerData IJJIIIIJIIIJIJJIIIIJJIIIJIIJJIJJIIJIJIJIIJJJIJJ;

	private TimerData JIIJJIIIIIJIJIJIIIIIIIJIJJJIJIJJJJJJJJJIIIJJIJI;

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	public void IJJJIIJIIJJJJIIIJJIIIIIIIJIJIJIIJIIJJJIJIIJIJJI()
	{
	}

	public void IJJIIJIIJJJJIJJJIJIJIJJJJIJIJIIJJIJJIIJJIIJIJJJ(int JIJIIJJJIJIJIJIJIIIIIJJIJJIIJJIIJJJJJIJJIIIIJII)
	{
	}

	public void IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI()
	{
	}

	public void IJIJIJJIIJJJIJIIIIIJJIIJIJIJJJIIIJJIIJJJIJJJIII()
	{
	}

	public void IIIJJJJJIJIIIJIJJJIIIJJJIIJJIIJIJJIIIJIIIJJIJJI()
	{
	}

	public void IJIIJIIJJIJIIJIIJIIJIIIIIIIIIIIJIIIIJJJIIIIIJIJ()
	{
	}

	private bool JJIIIIIIIIIJIJIJIJIJJJJJJJIJIIIIJJIIJJJIJJJJJII(byte[] IJJIJJIIJIIIIJIIJJIIIJIIIIJIIIJIIIIIIJJJJIJIIIJ, byte[] JJIIJJJJJIJIJIJJIJIIIIIJJJJIIJIJJJIIIJIIJIJIIJJ)
	{
		return false;
	}

	public void IJIJJIJIIIIJIIIIIIJIJJIIJIJIIIIJJIJJJIIIJIJJIJI(byte[] IIIJIJJJIJJIJIIIJIIJJJIIIIIJIJIJIIIIIIIJJJIIIII)
	{
	}

	public void JJJJJIIIJJJJJIJJIIIIIIIJJIIJIJIJIIJIJJJJIIIJIJI(int IJJJIIIIJIIIJIIJJJIJJIJIIIIIJIIIIIJIIJJIJIIJIJJ)
	{
	}

	public void IIJJJIJJJJJJIJJJIJJJJJIIJIIIJJIIIIIIIIIJIJIIJIJ()
	{
	}

	public void JIJJIIJIIIIJJJIJIIJJIJIJIIJJIJJJJIIIJJIIIJJJIIJ(Transform IIIJIIJIJIJJJJJJJJIJJJIJIJIIJIJIIJJJIIIIJJJJIJI, Transform JIJJJJJJJIJJIIIIIJIIJJJJIIJJJIJIJJIJIJIJIIIIIJI)
	{
	}

	public void IIIJJIJJJJIJIIJIIIIIIIIIJJIIJJIJJJIIIJIJJJJIJIJ(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, int IJJIJJIJIIIIJJIIIJIJIJJJJIJJIIIIJJIJJIIIJIIIJIJ, PlayerSkin IJJIIJIJIJIIJJIIIJJIIJIIJIIIJJJIJJJIJIJJJJJIJII)
	{
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}

	public void IJJJIIJIJJJIJIJIIJJIJJIIJIJIJIIIIIJIJJIIIJIIJIJ()
	{
	}

	public void IIIJIIIIIIIIJIIJIJIJJIIIIIIJIIJJIIJIJJIIIJIJJJI(int JIJIIJJJIJIJIJIJIIIIIJJIJJIIJJIIJJJJJIJJIIIIJII)
	{
	}

	public void JJJIJIJIIIJJJJJJIIIJJIIJIIIIJIJIIJIJJIJJIIIIIII()
	{
	}

	public void JJIJJJIIIJIJJIIJIJIIIJIJIIJJJIJIJIIJIIIIJIJIJJJ(bool IJJIIIIIIJJIIJIJIJIIJJJJJIIIJIJJJJIJJIIIJIJIJII, IIIJJIJJIIJIIIJIIIJIIJIIJJIJJIJIJJIJJIIJIJIJIJI IJIIIJJJJIJJJJJJJIIJIJIJJIIJJIIJJJJIJJIIJJIJIJI)
	{
	}

	[CompilerGenerated]
	private void JJIJJJIIJIJIJIJIIJIJIJIIJIJIIJIJIJIIIIJJIJJIJII()
	{
	}

	public void JJJIIIIIIIIJJJJIJIJJIIIIJIIIJJJIJIJIJIJIJIIJIJJ(int IJJJIIIIJIIIJIIJJJIJJIJIIIIIJIIIIIJIIJJIJIIJIJJ)
	{
	}

	public void JJJJIJJJIJIIJJJJIJJJIIIJIJIIIIIIJJJIJIJJJIJJIJJ()
	{
	}

	public void IJJIJJJIJIJJIJIIJJIIJIIJJIIJJJJJIIIJJJJJJJJIJJJ(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, int IJJIJJIJIIIIJJIIIJIJIJJJJIJJIIIIJJIJJIIIJIIIJIJ, PlayerSkin IJJIIJIJIJIIJJIIIJJIIJIIJIIIJJJIJJJIJIJJJJJIJII)
	{
	}

	[CompilerGenerated]
	private void JJJJIJJIJIJIIJIIJIJIJJIIJIJIJJIIIJIIJJJJIJJJIII()
	{
	}

	private void JJJIIIJIJJIJJIIIIJJIIIJJJIJJJJJJIJIIJIJIIIJJJII()
	{
	}
	public Transform IJJJJIJIIIJIIIJJJJIJJJJJIJIJIIIJIJIJIJIIJIIIIJJ()
	{
		return null;
	}

	private void IJJJIJJJIJJIJIJJIIJIJIIJIJJJJIJJJIJJIJJJIJJIJJJ()
	{
	}

	[CompilerGenerated]
	private void IIJJIIIJJJJJIIJJJIIJIIJIIIIIIIJIIJIJIIIJIJJIIIJ()
	{
	}

	public void JJIJIJIJIJIIJIJIJJIJIJIJJIJJIJJIJIIIJJIJIJJIJIJ()
	{
	}

	public void IIIIIIIIIIIIIJJJIIIIJIJJIJIIIJIIJIJJIIJIJJJIIJJ()
	{
	}

	public int[] JJIIIJIJIJIIJIJIJIJIIJJJIJIJJIIJIIIJIIJJJJJJIIJ()
	{
		return null;
	}

	public void JIIJIIJIIIIIJIIJJIJIIJJIIIIIIJJJJJIJJIIJJJIJJII()
	{
	}

	public int[] IJIJIIJJJJJIIIIJJIJIJJJJIIJJIIIJIIJJIIJIIIIJJIJ()
	{
		return null;
	}

	public void JJJJJJJIIIIIIJIJJIIIIJJJIIJIIIJIIJJIIIIJIJIIJII(bool IJJIIIIIIJJIIJIJIJIIJJJJJIIIJIJJJJIJJIIIJIJIJII, IIIJJIJJIIJIIIJIIIJIIJIIJJIJJIJIJJIJJIIJIJIJIJI IJIIIJJJJIJJJJJJJIIJIJIJJIIJJIIJJJJIJJIIJJIJIJI)
	{
	}
}
