using System.Runtime.CompilerServices;
using UnityEngine;

public class TrapStart : MonoBehaviour
{
	public GameObject IIJJJIIJIJIIJIIJJJJJIIIJJIIJJIIIJIIJJJIJJJJIIJI;

	private int IIIIIJIIJIJIIIIJIJIJJIIIJIJJIJJIJIIJJJIJIJIJJJJ;

	private void IJJJJIJIIJJJJJIIIJIJJIIJJJIJIJIIIJJIJJIJJIJIJII()
	{
	}

	private void Start()
	{
	}

	private void JJJIIIJJIIIJJJIIIJJIJJIJJJJIJJIJIIJJIJIIIIIJIJI()
	{
	}

	private void JJJIIIJJJJIIIIIIIJJIJJIJIIJIJIIJJIJIIJIIJJJIIJI()
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	[CompilerGenerated]
	private void IIIJIIJIJIJJJJIIJIJIJJIIJIJIIJJIIJIJJIJJJIIIJJJ()
	{
	}

	private void JJJJIJIIJIJIJJJJIIJIIIJJIJJJIIIIJJJIIJIJJIIIJIJ()
	{
	}

	private void JIJJJIIJIJIIJIIJIJIIIIIIIJJIJJJIIJJJJJJIIIIIIIJ()
	{
	}

	private void IIJJIJIIIIIIJJJIIIIIIJIIIJJJIIIIJIIJIIIJIJJIJIJ()
	{
	}

	private void JIJJIIIIJJIJIIIJIIJJIJIIIIJJIJJIIJJJJJJIIJIIJII()
	{
	}

	private void JJIJJJIIIIJIJIIIIIIIJJIJIJIJJJIIJIJIIIIIIIJJIJI()
	{
	}

	private void IIIIIIIIIJJIJJIJJJJJIJJIJJJIJIJIJIJIJJJJIIJIIJI()
	{
	}

	private void IJIJJIIJJJIIJJIIIJJIIJIIJIJIJJIIJJJIIJIJJJJJJIJ()
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void IJIIIJIIJJJIJJIJIJIJIIJJIJJJIJIJIIJIIJIIIIJJIJI()
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}
}
