using DG.Tweening;
using UnityEngine;

public class TrapPath : MonoBehaviour
{
	public Transform IIJJJIIJIJIIJIIJJJJJIIIJJIIJJIIIJIIJJJIJJJJIIJI;

	public Transform JIIJIIJIIIIIIJIJJJIJJJIIIIJIJIIIJJJIIIIJIIIIJII;

	public Transform[] IJJIIIJIIIJJIIIJJJIIJIJJJIJJJJIJIJIJIIIJIJJIIII;

	public float JJJIIJJIIIJJJIJJIIJJJJIJIJJJJJIJIJJIIIJJJJIJJII;

	public float JIIIJJJJJJIIJIIJJIJJIIIIJJJJJIJJIIJIJJIIIJIIJIJ;

	public float IJJJIJIJIJJJJIIJJJJJIJJIIIJIIJIIJIIIIJJJIIIIJII;

	public Color IJIJIJJIJJJJJIJIJJIIJIIJIJIJIIIIJIJJIJJJJIIJJIJ;

	private Tween IJJIIJJJJIJIIIJIJJJJIJIJJJIIJIIJJIJJJIJIJJIIJII;

	private Tween JIIIJJIIJIIJJIJJJIIJJIIJJIJJJJIJIJJJJIIIJIIIIJI;

	private Vector3 IJJIJIIIIJJJJJJJJIJIIIIJJJJJJIIJJIJIJIJIIJJJJIJ;

	private Quaternion IJIJIIJJJIIJIJJJJIJJJJIIIIJIIJJJJJIJJIIIIJIIIII;

	private void IIJIJIIJIIIIIIIIJJIJJJJJIIJIIJJJJJJIJIIIIJIIJJJ(int JIIJIIIJIJJJJIIIJJJIJIJIJIIIJIIJJJIJJIJJIIJJIIJ)
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void JJIIIJJJIIJIIJIJJIIIIJIIJIJIJIIJIIJJJJIIIJIJJIJ(int JIIJIIIJIJJJJIIIJJJIJIJIJIIIJIIJJJIJJIJJIIJJIIJ)
	{
	}

	private void IIJIIIJIIIJJJJJJJJIIIJIIJIIJIIJIIJJJIJIJIIIIIII(int JIIJIIIJIJJJJIIIJJJIJIJIJIIIJIIJJJIJJIJJIIJJIIJ)
	{
	}

	private void JIIJJJJJJJJJIJJIJIIIJIIIIIIIIJIJJJIJIIIIJJIJJII(int JIIJIIIJIJJJJIIIJJJIJIJIJIIIJIIJJJIJJIJJIIJJIIJ)
	{
	}

	private void JIJIIJIJJIIJIIIJIIIIJIIJJJJIIJJJJIIIIIJIJIJIIJI(int JIIJIIIJIJJJJIIIJJJIJIJIJIIIJIIJJJIJJIJJIIJJIIJ)
	{
	}

	private void Start()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	private void JJIJIJJJJIJIJJIIIIJJIJIJIJIIIJJIJIJJIIIJIJJIJIJ(int JIIJIIIJIJJJJIIIJJJIJIJIJIIIJIIJJJIJJIJJIIJJIIJ)
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void IJJJIIIIJIIIJIJJIIIIIJJJIIJJJJIJIJJJJIJJJIJJIIJ()
	{
	}

	private void JJJJIJJIJIIJIJJJIIIJJIIJIIJIIIIIIIIJIJJJJJIJJIJ()
	{
	}

	private void JIJIIIIJJIJIJIIIJIJIJJJJIJIIJJIJJIIJJJIJIJIJIIJ(int JIIJIIIJIJJJJIIIJJJIJIJIJIIIJIIJJJIJJIJJIIJJIIJ)
	{
	}

	private void JJJIIIJIJIJJIJJJJJJJIJIJJJIIJIJJJIJJJJIJIJIJJII(int JIIJIIIJIJJJJIIIJJJIJIJIJIIIJIIJJJIJJIJJIIJJIIJ)
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void IIIJIJIIIIIJJJIJJJJIJIJIJIIIJJJJJIJJJIJIIIIJIJI(int JIIJIIIJIJJJJIIIJJJIJIJIJIIIJIIJJJIJJIJJIIJJIIJ)
	{
	}

	private void JIIIIIJJIJJJIIIJJIIJJIJJJIJIIIJJJIJJJJJJIJIJJJI()
	{
	}
}
