using DG.Tweening;
using UnityEngine;

public class TrapPosition : MonoBehaviour
{
	public int JJIIIJIIIJJJIJJJJIIIJJIIIJIJJIIJJJIIJJIIIIIJIIJ;

	public Transform IIJJJIIJIJIIJIIJJJJJIIIJJIIJJIIIJIIJJJIJJJJIIJI;

	public Vector3 IIJJJIJIIIJIIJJIIJJIIIJIJIIIIIIJJJJIIIIJIIIIJJI;

	public Vector3 IIIJIJJJIJJIJIIIIJIIIIJIJIIIIIIIJJIIJJIIJJJJIJJ;

	public float JJJIIJJIIIJJJIJJIIJJJJIJIJJJJJIJIJJIIIJJJJIJJII;

	public float JJJIIIIJIJIIJIJJIJJJIJJIIJIIIIIJJIJIJJJIIJJJJIJ;

	public float IIJIJJIIIJIJIJJIIJIIIJIJJJJJIIJIIIIIIJIIIJJJJJI;

	public int IIIJIJIIJJIIIJJJJIIJJIJIJIJIIJJIIJJJIJJIIJIIJII;

	private Tweener JJIIIIJIIIIIJJIJJJJJJJJJIIJJIJIJJIJJIJIIIJIJIII;

	private bool JIJIIJIIJJJJJIIJJJIIIIJJJJJIIJIIIIIJJJJJJJIIIII;

	private void IIJIIJIJIJJJIIJIJJJIIIJIIJIIIIJIIJIIIIJIJIJJIJJ()
	{
	}

	private void IJJIIIJIIJJIJJIJJJJIJIIJIJIJIIIJJIJIIJIJIIJJIJI()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void IIIIIJIJJJJJIIJIIIIIIJIJIIIJJIJIIJIJIIIIJIIJJII()
	{
	}

	private void IJIJIJJJIIIJIIIJIIIIJIIIIJJJIIJJIIIIIJIIJJIJJJI()
	{
	}

	private void IIIIIIJJIIJIJJJIJIJJIJIJIIJJIIJIIJJJIIJJIIIIIII()
	{
	}

	private void Start()
	{
	}

	private void JIIIJJIIJJJIIJIJIJIIIJJJIIJJIIIIIJJJIIJIIIIIJJI()
	{
	}

	private void IJIIIIJJJJIIJJJJJJJJIIIJIIIIJIJJIIIJIJIJJJIIIJI()
	{
	}

	private void JIJJIJIJJJIIJJJJIJJJJIJJJJJJIIJIJIIIJIIJIIJIJIJ()
	{
	}

	private void IJJJIIJJJIIJIIJIIJIJJJIJIIJIIJIIIJJJIIJJIIIJIIJ()
	{
	}

	private void JJIIJJJJJJJIJJIIJIJJIJIIIJIJJJJIJIIIJJIIJIIJIII()
	{
	}

	private void JIJJJIIIJIJIJJIJJJJJIJJJIJJJIJIJIIIJIJIIIIJJJJI()
	{
	}

	private void JIJIIIIJJJIJIIIJJIJJIIJIIIJJIIIJIJJJIIJIIIJJJII()
	{
	}

	private void JIJIJIIJJJIJJIJIIIIIIJJJJIJJJJIIIJIIIJIJIJIIIII()
	{
	}

	private void JIIIIIIIIJIJJIIJJJJJIIIIJJIJJIIIIJIJJJJIIIIIJII()
	{
	}

	private void JIJJIIJJIJJJJIJJIIIIIIJJJJJJJJJJIIJJJIIJJJJIIIJ()
	{
	}

	private void IJIIIJJIJIJJJIIIJJIJIJIJIIJIJJIIJJIIJJIJIJJIJII()
	{
	}

	private void IJIJJJIJJJIJIIIIJJIJJIJJJIIIJJJJIJIJJJIIIIIIJJI()
	{
	}

	private void IIIJIIJJIJIIIIIIIJIIIJJJIIIJJIJIJJIIIJJJJJIIIIJ()
	{
	}

	private void JJJJIJIJIJJIIJIJIJIIIIJJIIJIJIJJJJIJJJIIJIIJIIJ()
	{
	}

	private void JJIIIJIIIJIIJJIJJJJJJJJIJJJIIJJJJJJIIIIJJJIJJII()
	{
	}

	private void JIJJIIJJIJIIJJJIJIJIJJJJJIJJJIJIIIJIIIIJIIJIJJI()
	{
	}

	private void IIIIJIIJIJJIJJIIJJJJIIIJJJIJJJJIIJJIIJIIIIIIIJI()
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void IJJJIIIIJIIIJIJJIIIIIJJJIIJJJJIJIJJJJIJJJIJJIIJ()
	{
	}
}
