using System.Runtime.CompilerServices;
using UnityEngine;

public class TrapAddForce : MonoBehaviour
{
	public int JJIIIJIIIJJJIJJJJIIIJJIIIJIJJIIJJJIIJJIIIIIJIIJ;

	public Vector3 IIIIJIIIIIJJJIJJIIIJIJIIIIIIJJJIJJIJJIJJIJIJJJJ;

	public float JIIIJJJJJJIIJIIJJIJJIIIIJJJJJIJJIIJIJJIIIJIIJIJ;

	private bool JIJIIJIIJJJJJIIJJJIIIIJJJJJIIJIIIIIJJJJJJJIIIII;

	private bool IIJIIJJJIIIJJIIIJIJIIIIJJIIIJJIJJIIIJJIJIJJJJII;

	private bool JJIIJJIIJJIJIJIJJJIIJJJIIIIJIJIIIIIIJIIIIJJIJJJ;

	private void JIJJJIIIJIJIJJIJJJJJIJJJIJJJIJIJIIIJIJIIIIJJJJI()
	{
	}

	private void IJJJJJJJIJIIIIIIJIJIJJJIJJJJIJJIJIJJIJJIJIJJIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIIIJJIIJJJIIJIJIJIIIJJJIIJJIIIIIJJJIIJIIIIIJJI()
	{
	}

	private void JJJIJJJJIIJIIIIIJJJJJJJIJIIIJJJJJJJIJIIIIIIIJJJ()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void OnTriggerExit(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIJIJIIIIIJJIIIIIJJIJIIIJIJIJIIIJIJJIIIJJJJIIJJ()
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void IIIIJIJIJJIIJIIIIJIJIJIJIJIIJIJIJJIJJJJJIIIJIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJIIIIJJJJIIJJJJJJJJIIIJIIIIJIJJIIIJIJIJJJIIIJI()
	{
	}

	private void IIJJJIJIJIIIJIJIJIIIJIIIJIJJIJIIJIJIIJIIIJJJJIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJIIJIJJJJJIJJJJIIJIJJJJIJJJIIJJJIJJJIIJJIIIIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJJIIIIJIJJJJIIIIIJIIIJJJIIJJIJIJIIIJIJJJIIJJIJ()
	{
	}

	private void JIJJIIJIIIJIIIIJJJJJJIIJIJJJIIJIJJJJJJJIJJIIJJJ()
	{
	}

	[CompilerGenerated]
	private void IJIIIJJJJIIJIJJIJJJIJJIIIJIJJJJJJIIJJIJIIIIIIII()
	{
	}

	private void IIIIJJJJIJJJJJJJJIIIJIIJIIJJJIIJIJIIIIJJIJIIIJI()
	{
	}

	private void JJIJJIJJJJJJIIJIIJIJIJJIJJJJJJJIIIJJJJIIIJJJIII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJIIIIJIJJIJIIIJIJJJJJIIIJJJJJIIIJJIJJIJIIJIJIJ()
	{
	}

	private void Start()
	{
	}
}
