using System.Runtime.CompilerServices;
using UnityEngine;

public class TrapParticle : MonoBehaviour
{
	public int JJIIIJIIIJJJIJJJJIIIJJIIIJIJJIIJJJIIJJIIIIIJIIJ;

	public ParticleSystem IIJJJIIJIJIIJIIJJJJJIIIJJIIJJIIIJIIJJJIJJJJIIJI;

	public float JJJIIIIJIJIIJIJJIJJJIJJIIJIIIIIJJIJIJJJIIJJJJIJ;

	public float IIJIJJIIIJIJIJJIIJIIIJIJJJJJIIJIIIIIIJIIIJJJJJI;

	private bool JJIIJJIIJJIJIJIJJJIIJJJIIIIJIJIIIIIIJIIIIJJIJJJ;

	private bool IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI;

	private bool JIJIIJIIJJJJJIIJJJIIIIJJJJJIIJIIIIIJJJJJJJIIIII;

	private int IIIIIJIIJIJIIIIJIJIJJIIIJIJJIJJIJIIJJJIJIJIJJJJ;

	private void IIJIIIIJJJIIIIIIIJJJJJJJIIJIIJJJJJIIJIJJIJIIIJJ()
	{
	}

	private void IJIIIIIJJJIIJIIIJIIIIIIJIJJIJJIJJIIJIIJJJJJJIJJ()
	{
	}

	[CompilerGenerated]
	private void JIJJIIIJJIIJIIJJIIIJIIJIJJIJJJJIJJJJIJJJIJJIIJJ()
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void Start()
	{
	}

	private void IJJJJJJJIJIJIIJJIJIIIIIIIIJJJJIIIIJIJJIJJIJIIJI()
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void JIJJJIIIJIJIJJIJJJJJIJJJIJJJIJIJIIIJIJIIIIJJJJI()
	{
	}

	private void OnTriggerExit(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJIIJIJJJJJIJJJJIIJIJJJJIJJJIIJJJIJJJIIJJIIIIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJJIIJJJJJIJIIIJIIIIJJJIJJJIJJIIIIIJJJJJJIJIJJJ()
	{
	}

	private void JJJIIIJJJJIIIIIIIJJIJJIJIIJIJIIJJIJIIJIIJJJIIJI()
	{
	}

	private void JJJJJJJJJJIJIIJIIJIIJJIIIJJJJIIJJIIIJJJIJJJJJIJ()
	{
	}

	private void IIIJIIJIIIIJJJJIJJJIJJJJIIJJJJJJIJIIJJJIIJIJJJI()
	{
	}

	private void IIJIIJIJJJJIJJIJJJIIJIJJJIIIIJJJJIJJIIJIJJJJIII()
	{
	}

	[CompilerGenerated]
	private void IIJJJIIJIIJJIJJJIJIJJIJIJJJJIIIJJIJIIJJJIIJJJII()
	{
	}

	private void IJIJJIIIJIJIJIIJJIJJJIJIJJIJIIIIJIIIJIJJIIIJIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJIIIIJJJJIIJJJJJJJJIIIJIIIIJIJJIIIJIJIJJJIIIJI()
	{
	}
}
