using System.Runtime.CompilerServices;
using UnityEngine;

public class TrapButton : MonoBehaviour
{
	public JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJJIIIJJJIIJIJIIIIIIIJJJJJJIIIJJIIIJIIIJIJIJJJ;

	public int JJIIIJIIIJJJIJJJJIIIJJIIIJIJJIIJJJIIJJIIIIIJIIJ;

	public KeyCode JIJIIJIIIIJIJJIIJJIJJIJIIJJIIIIIJJIJJIJIJIIJJJI;

	public MeshRenderer JIIIIJJIIIIIIJJJJIJIJIIIJJIJIJJIIJJIIJIJJJJIJJJ;

	public Transform JIIIJIJIJJIJJIJIIIJIIJIIJJIJIJIJIJJIJJIJIJIJJIJ;

	public bool IJJIJJJIIJJJIIIJIJIJIJJIIIJJJIJIJJIIIIIJIIJIJJJ;

	[JIIJIJJJIJJJJJJIIJIJIIIJIJIIJJJIJIJIIIIIJIIJJJJ]
	public int IIJJJJIJJIIJJJIIJIJJJJIIIJIIIIIJIJJJIIIIJIJIIIJ;

	private bool JJIIJJIIJJIJIJIJJJIIJJJIIIIJIJIIIIIIJIIIIJJIJJJ;

	private bool IIIIJIIIJJIIJIIJIIJJJJJJIJJJIJJIIJJJIIIIJIJJIIJ;

	private bool IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI;

	public void IJIJIIIJIIIJIJJIIIJJIIIIIIIJIJJJJJJIJIIJIJJJJII()
	{
	}

	[CompilerGenerated]
	private void JIIIIIJJJIIIIIIIIIJIJJIJJIJIIJJIIJIIIIIJIIJJJJJ()
	{
	}

	private void IJJIIJIJIIIJIJJIJIIIJJIIIJIJIIIIJIJJIIIIJIIJIJI()
	{
	}

	private void IJIIIIJJJJIIJIIIIIIJIIIIJIIIIJIJJJIIIIJJJJIIJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void OnTriggerExit(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void OnDisable()
	{
	}

	private void JJIJIJJJJIJIJJIIJJJJIJIIJIJIIIJIJIIJIJIJIJIJJJI()
	{
	}

	public void IJIJIIIJIIIJIJJIIIJJIIIIIIIJIJJJJJJIJIIJIJJJJII(byte IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void JIIJIJJJIJIJIJIIIIIJIIIJIJIJIJIIJJIJJIJJIJIIJIJ()
	{
	}

	[CompilerGenerated]
	private void JIJIJJJJJJIJIJJIIIIJJJJIJIIIJIIIIJIIJIIIIIIIJJJ()
	{
	}

	private void IIIJIIIIIIJJJIIJIJIJIJJJIIJJJJIJIJJIIJIJJJIIIII()
	{
	}

	private void IJJJJIIIIJJIIIJJIJJJJJJIJIIJJJJJJJJIJJIIJIIIJIJ()
	{
	}

	private void IIJIJJJJJJJIJJJJIIIJJJIJJIJJJJIIJIJJJIIIIIIJJIJ()
	{
	}

	private void OnEnable()
	{
	}

	private void JJIJJIJJJIJIJJJJJIJJIJJJJIIIIJIIIIJJJIIIIIIIJII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void Start()
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void JIJJIJJIIIJJIIJJIJJIJIJIIIJIJIJJIJJIIJJIIJIIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IJIIJJIIIIIIJIJJIJIJIIJJJIIJJJJJIJIJIIJIJIJIIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJIIJIJIJJIIIJJJJIIJIJIIJIIJJJJJIJIJIIJIJIIIIII()
	{
	}

	private void IJIIIJJJJIJIJIJIIIJIIJIIIJIIJIIJIJJIJJJIIJJIIIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJJIIIJJJJIIIIIIIJJIJJIJIIJIJIIJJIJIIJIIJJJIIJI()
	{
	}

	private void JJIIIIJIJJJJIJIJIJIIJJJIIJIIIIJIJIIJIJIJJJIIIII()
	{
	}
}
