using System.Runtime.CompilerServices;
using UnityEngine;

public class TrapEnable : MonoBehaviour
{
	public int JJIIIJIIIJJJIJJJJIIIJJIIIJIJJIIJJJIIJJIIIIIJIIJ;

	public GameObject IIJJJIIJIJIIJIIJJJJJIIIJJIIJJIIIJIIJJJIJJJJIIJI;

	public bool JJIIJJIIJJJJJIIIJIIJJIJJIIJIIJJJIIJJIIJJIIIJJJJ;

	public Vector3 IJJJJJIIJIJJJIJIIJJIIJIIIIIIJJIJIIJJIIJJJJIIIJI;

	public bool JIIJJJIJJIIJJJJJIJJIJIIJIIJIIIIIJJIJJIJJIIIIJJI;

	public float JJJIIIIJIJIIJIJJIJJJIJJIIJIIIIIJJIJIJJJIIJJJJIJ;

	public float IIJIJJIIIJIJIJJIIJIIIJIJJJJJIIJIIIIIIJIIIJJJJJI;

	private bool JIJIIJIIJJJJJIIJJJIIIIJJJJJIIJIIIIIJJJJJJJIIIII;

	[CompilerGenerated]
	private void IJJJIJIIIIJIIIJJJIJIJJIJJIIIJJIIIIIJIIJIIIJIIJJ()
	{
	}

	private void JIIJJJJJJIIIIJIIIJJJIIIIIJIJJIJJJIIIIIIIIJIJIJI()
	{
	}

	private void Start()
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void JIIJJJJIJJJJIIIIIJJIJJIJIJJJJJJJJIJJJIIIJJIIJJJ()
	{
	}

	private void IJIJIJIJJIJJJJIIIJIIJJJJJJJJJJIIIJJJIIJIIIJIJIJ()
	{
	}

	[CompilerGenerated]
	private void IIJJIIIJIJJIIIJIIJIIIIIJJIIJIIIJIJIIIIIJIJIJIIJ()
	{
	}

	private void IJIIIIJJJJIIJJJJJJJJIIIJIIIIJIJJIIIJIJIJJJIIIJI()
	{
	}

	private void JJIIIJIJJJIIJIIIIIIIIIIJJJJIJIIIJIIJIIIJIJIJIJI()
	{
	}

	private void IIIIIJIIJIJIIIJJJJIIIJIJJJJJJIIIJJJJJIIJJJJIJII()
	{
	}

	private void JJJIJJJJJJJJJIIJJJJJJIIJJIIJJJJIJIIJJJIJIJIJIII()
	{
	}

	private void JIJIIJJIIIIJIJJJIJIJIJJIJIIJIIIIJIJJIIJJJJJIIJI()
	{
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	private void IIJIIJJJJIJJJIJIIJIJIIJIIJIJIIJJJIJIJIIIIIIIIJJ()
	{
	}

	private void JIJIJIIJJIIJIIIIIJJJIJIIJIJJIIIJJJJJJIJIIIJIIJJ()
	{
	}

	private void IJIJIJIJIJIJIJJJJJJIJJJIJIJIIJJJJJIIJJJIJIJIIJJ()
	{
	}

	private void IIIJJIIJJJJJJIJIJJIIIJIJIJIJJJIJIJIJIJJJIIJIJJI()
	{
	}

	private void JIJIIJIIIJJIJIIIJJIJIJJJIJIJIIJJIIIJJJJJIIIJIJJ()
	{
	}

	private void JIIIIIIIJJJIIIIJJIJIJIJIIIJJIIIIJJIIIIIIJIIJJJI()
	{
	}

	private void IIJJIJIIIIIIJJJIIIIIIJIIIJJJIIIIJIIJIIIJIJJIJIJ()
	{
	}

	private void IIJJJJJIIJIJJIJJIIIIIJIJJJJJIJIIJIJIJJIIIIJIJJI()
	{
	}

	private void JJJIJJJJIIIJIIJIIIJIJJJJIIIIIIJJIIJJJIIJJIJJJJI()
	{
	}
}
