using DG.Tweening;
using UnityEngine;

public class TrapRotation : MonoBehaviour
{
	public int JJIIIJIIIJJJIJJJJIIIJJIIIJIJJIIJJJIIJJIIIIIJIIJ;

	public Transform IIJJJIIJIJIIJIIJJJJJIIIJJIIJJIIIJIIJJJIJJJJIIJI;

	public bool JJIIJJIIJJJJJIIIJIIJJIJJIIJIIJJJIIJJIIJJIIIJJJJ;

	public Vector3 IJJJJJIIJIJJJIJIIJJIIJIIIIIIJJIJIIJJIIJJJJIIIJI;

	public int JIJIJJIJJIIJJIJIJJIIJIJIIIIJIJIIJJIIIJJIJIJIJII;

	private int IIIIIIJJIIJIIIJJJJJJJIIIIIIIJJJIJJIIJJIIIIJIIJJ;

	public Vector3 JIJIJJIIIIJIIJIJIJJJJJJIIJJIIIIJJJIIJJJJJIJIIJJ;

	public Vector3 JJJJIJIJJIIIIIIJJIJIIJJJIIJIJJJJIJJIJJJIJJIIIII;

	public RotateMode JIIIIJJJJJIIIIJIJIJIIJIJIIJJJIIJJJJIJJJJIJIIIJI;

	public float JJJIIJJIIIJJJIJJIIJJJJIJIJJJJJIJIJJIIIJJJJIJJII;

	public float JJJIIIIJIJIIJIJJIJJJIJJIIJIIIIIJJIJIJJJIIJJJJIJ;

	public float IIJIJJIIIJIJIJJIIJIIIJIJJJJJIIJIIIIIIJIIIJJJJJI;

	private Tweener JJIIIIJIIIIIJJIJJJJJJJJJIIJJIJIJJIJJIJIIIJIJIII;

	public bool JIJIIJIIJJJJJIIJJJIIIIJJJJJIIJIIIIIJJJJJJJIIIII;

	private void IJIIIJJIJIJJJIIIJJIJIJIJIIJIJJIIJJIIJJIJIJJIJII()
	{
	}

	private void JJIIJIIIIIIIJIIIIIJIJIIJJJJJJIIIIIJJIJJJJJJJIJJ()
	{
	}

	private void JJJJJJJJJJJJIIIIIJJIJJJIJJIJIJIIJJIJJJIIIIJIIJI()
	{
	}

	private void IJJIJIJIIIIIIIIIIIIIJJIJIIIJJJJIJJJIJIJJIJIJIJJ()
	{
	}

	private void JIIJJIJJIJIIJJIIJIIJIJIIJIIIJIIIIJIJIIIJJIJIJJI()
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void IJIIJJJJIJJIJJJJIIIJJIJIIJJIJIJJIJJIJJIJJJJJJJI()
	{
	}

	private void IJIIJIJIJJJIIJIIIIIJJIJIIIIJIJIJIIJJIJJJIIJIJJJ()
	{
	}

	private void JJIIIJJIIJIJIJIIIJJIJJJIJJJIJIIJIIJJIJIJIJIJJIJ()
	{
	}

	private void IIIIIIJJIIJIJJJIJIJJIJIJIIJJIIJIIJJJIIJJIIIIIII()
	{
	}

	private void IJIIIIJJJJIIJJJJJJJJIIIJIIIIJIJJIIIJIJIJJJIIIJI()
	{
	}

	private void JJIIJJJJJJJIJJIIJIJJIJIIIJIJJJJIJIIIJJIIJIIJIII()
	{
	}

	private void IIIJJIIJJJJJJIJIJJIIIJIJIJIJJJIJIJIJIJJJIIJIJJI()
	{
	}

	private void Start()
	{
	}

	private void IIJIJIIJJIIJIIJJJJJJJIJIIJJIJIJJJIIIIIIIJIJJJJI()
	{
	}

	private void IIIIIJIJJJJJIIJIIIIIIJIJIIIJJIJIIJIJIIIIJIIJJII()
	{
	}

	private void JIJJJIIIJIJIJJIJJJJJIJJJIJJJIJIJIIIJIJIIIIJJJJI()
	{
	}

	private void JJIJJIIIIIJJJJIIJIIJIIJIJIIIJIIJJJJJJIIJIIIIIJJ()
	{
	}

	private void JIIIJIIJIJJIJJIIJIJJIIIJJIJIJJIJIJJJIIJJIIIJIJJ()
	{
	}

	private void JIIIJIJJJIIIIIIIJJIJJJJIIJJIJIIIIJIJJJJIIJIIJJJ()
	{
	}

	private void JIJIJIIJJJJIIJIJIIIIJIIIIIJIIIJJJJJJJIJIJIIIIJI()
	{
	}

	private void JJJIJJJJIIIJIIJIIIJIJJJJIIIIIIJJIIJJJIIJJIJJJJI()
	{
	}

	private void JIJIIJJIIIIJIJJJIJIJIJJIJIIJIIIIJIJJIIJJJJJIIJI()
	{
	}
}
