using System.Runtime.CompilerServices;
using Photon;

public class TunnelDropperMode : MonoBehaviour
{
	private sealed class JIJIIIIIIIIIJIJJJJIJIIIIIIIJIJJJJJJIJJIIIIJIJJJ
	{
		public TunnelDropperMode JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII;
	}

	private sealed class IJJJJJJJIIJJIIJJJJIJIIJJIJIIJJIIIJIJJJIIIIJIJII
	{
		public IIIJIJJJIJJJIIJJJJJJIJJJIJIJJJIJIIJIIIJIJJIIIJJ IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII;

		public JIJIIIIIIIIIJIJJJJIJIIIIIIIJIJJJJJJIJJIIIIJIJJJ IJJIJIIIIJIJIJJJJJIIJIIJJIIIIIIJIIIIJJIIIIIJIII;

		internal void IIJJJJIJIJIJIJJJJIJJIIJJJJJJIJJIIIIIJIIIIIJJIII()
		{
		}

		internal void IJIJJIJJIJJIJIJJJJIIIIIJJJIJJIJJIJIIIJIIIIJIIII()
		{
		}

		internal void JIJIIIJIIIJIIJJJJJJJJJJIIIIIIJJJIIIIJIJIIIIJJIJ()
		{
		}

		internal void IIJIJIIIIIIJIIJIJJIJIIIJIJIIJIIIIIIJIIJIIIIIIJJ()
		{
		}

		internal void JIIIIJIIJIJJJIIJIIJIJIIJIIIIIJIIJIJIJJIIIJIIIII()
		{
		}

		internal void IJJJJIIIIIIIIJJJIIIJJJJJIJJIIJIJIIJIIIIJIJIIJIJ()
		{
		}

		internal void IJIJJIIJIJIIIJIIIJIIIJIJIIIJJJIJIIIJIJIIIJJJJIJ()
		{
		}

		internal void IJJJJJJIIIJIIJIJJJIJJIJJIIJIJIJIJJJIIIIJJJIIIII()
		{
		}

		internal void IIJJJIIJIJJIIIIJJIIIJIIIJIIJJJIJJIJJJJJIJJIIIJI()
		{
		}

		internal void JIJIJJJJJJIJJIIIIIIJJIIJJIJIIIIJJJJIJJJJJIJJJIJ()
		{
		}

		internal void JIJIIIIIJIJIJJIIJIIJIJIIJJIIJJJJJIJIIJJIIIIJIIJ()
		{
		}

		internal void JJJJJJJJIJIJIIIJIJIJJIIJIJJJIIIJIJJJIJJIJJJIJII()
		{
		}

		internal void IJIIIIJIJIIJIIJJJJIIIJJJIIJIIIJIIJJIIJIJIIIIIJJ()
		{
		}

		internal void JIJIJIIIJJIIJIIJJIIJJJIJIJIJIIIIJIIJIIJJJIIJIIJ()
		{
		}

		internal void IJJIJIIIIIIJJIJIIIIJJJJIIJIJIJIIIIIIIIIJIJIJIJJ()
		{
		}
	}

	public static TunnelDropperMode JIJJIJJJJIIJIIJJJJJJJJIJJJJJJIJJIJIIIIJIJJIJJJJ;

	private int JIIIJIJIIIJJIIJIJIJJJIJIJIJJJIIIJIJJIJIJIIIJJIJ;

	private bool IIJIIIIIIIJJJIJIJJIJJIIJIJIIJJJIJJIJIJJJJIJJJIJ;

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIJIJJIIJIJJJIIIJIIIIJJJJIIJJIIJJJIIJJIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnDisable()
	{
	}

	private void IJIIIIIJJIJJJIJJIIJIJJIJJJIJIIIIJIJJIIIJIIIJIII()
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void JIIJIJIJIIIJJJJJJJJJJJIIIIJJIJJJIIJIJJIJIIJIJIJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIJIJIIJJIJJIIJJJJJJIIJIJJIIJIIIJJJIJIIIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJIIJJIJJJJJJJJJJIJIIJIIJIIJJJJIJIIJJJIJJIIJII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void JJIIIIIIIJJJIJIJIIIIIJIJIIJJJIJJIIJIIJIIIIIJIIJ()
	{
	}

	private void JJJIIIJIIIIIIJJIJJIJIIIIIJIJIJIJIIIIIJIIIJIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJJJIJJIJJIIIIJIJIIJJIJIIJIIIIIIIIIIJJIJIIJJJJ()
	{
	}

	[CompilerGenerated]
	private void IIIIJIJJIJIJIIIIJIIIIIIIJIJJIJJJJIJJJIIIIJJJIIJ()
	{
	}

	private void IJIIIJIJIJIJIJJJIJIIIJJIJIJIIIJIJIIIJIJJIIIIJJJ()
	{
	}

	private void IIJIIIJIIIIIIIJJJIIJJJIJJIIJIJIJJIJIJJJJIIJIJJJ()
	{
	}

	private void IJJJIIIJIJIJIJJJIIIIJJIIJIJJIJJIIJJJIIJJJIJIJII()
	{
	}

	private void JIIIJJJIJJJIIJIJIJIJJJJJJJJIJJIIIJIJJIJJIJIIIII()
	{
	}

	private void JIIJIIJIJIJJJJIIIJIIJJIIJJJIJIIIJJIJIJJJJJIJIII()
	{
	}

	private void IIJJIIJIIIIIIJIJIJIJJIJIIIIIJIJIIIJJIIIIJJIIJJJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJJJJJIJJJIIJIJIJIIIJIJIJJJJJJIJJJJIJJJJIJIIJI()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJJIJIIJIJIJIIJIIJJJJJIJJJIIJJIJJJIJJIIIJIIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJIJIJIJJJJJIIJJIIIJJIJIIIJJIIJJJIIIIJIJJIIIIJI()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void OnEnable()
	{
	}

	private void Awake()
	{
	}

	private void IIJIIJJJIIJJJIIIJJIJIJJIIJJIIIJIJJJIJJIJIJJIJJI()
	{
	}

	private void JIJIIJJIIIIIIIJJIJIJIJJJIJJIJIIJJIJJJIJIIIJIIJJ()
	{
	}

	private void IJIIJIJJJJIIJIJIIIIIIIJIJJIJIJIJIJIJIIJJIJJJJJI()
	{
	}

	[CompilerGenerated]
	private void JJIJJIIIJJIIJIJIIJJIIIIJIIIIIIJIIIJJJJIJJIIJIJI()
	{
	}

	private void JIIJIJJIIIJJIJIIJJIJIIIJIJJIJIIIIIJIJJJIIJIJIIJ()
	{
	}

	private void Start()
	{
	}

	private void JJJJIIJJIIJJJIIIJIJJJJJIIIIJJIIJIIIIJIIJIJJIJII()
	{
	}
}
