using System;
using System.Collections.Generic;
using UnityEngine;

public class TunnelDropperGenerator : MonoBehaviour
{
	private enum IIIJIJIIIIIIIJJIJJIIJIIIIJIJJJJJIIIJJJJJIJJJJII
	{
		Vertical = 0,
		Incline = 1,
		Mixed = 2
	}

	private enum JIJJJJIIIJJJJJJJJIIIIJJIJIIIJIIIIIIIIJJIJJJIJII
	{
		Null = 0,
		Finish = 1,
		Tunnel_vertical = 2,
		Tunnel_inclined = 3,
		Barrier = 4,
		DeathTrigger = 5
	}

	private struct JJIJIIJJJIJJIIJIJIJIJIIJJIIIIJJIIJIJIIIIJIJIIJI
	{
		public bool IJJIJJIJIIIJJIIIIIIJJJIIJIIIJJIJJJJIJJJJIIIJIIJ;

		public GameObject JIJJIJIIJJIJJJIJIJJJJIIJIIIIIJIIIJJJJIIJJIIJJJI;

		public JJIJIIJJJIJJIIJIJIJIJIIJJIIIIJJIIJIJIIIIJIJIIJI(bool IJJIJJIJIIIJJIIIIIIJJJIIJIIIJJIJJJJIJJJJIIIJIIJ, GameObject JIJJIJIIJJIJJJIJIJJJJIIJIIIIIJIIIJJJJIIJJIIJJJI)
		{
			this.IJJIJJIJIIIJJIIIIIIJJJIIJIIIJJIJJJJIJJJJIIIJIIJ = false;
			this.JIJJIJIIJJIJJJIJIJJJJIIJIIIIIJIIIJJJJIIJJIIJJJI = null;
		}
	}

	public GameObject IIIIJIJIIIIIIIIJJJIJJIIJIIJJJIIIIIJIJIJIIIIIJII;

	public GameObject IIJJJIJJJIJIJIJIIIIJIIJJJIIJJIJJIJJIIJJIIIJIJIJ;

	public Transform IJJIJJJJJIIIIIJJJIIIIJJIJIJIIJJJIJJIJJJJIJIJJJI;

	public Vector2 IIJIJJJIIIIJIJIJJIIJJIIJIIJJIIIJJIIIIJIJJIIIIJJ;

	public Vector2 IIIIIIIJIJJIIIJIIIJIJJJIIIJJJIJJIJJJJIIIJJIIJJI;

	public static TunnelDropperGenerator JIJJIJJJJIIJIIJJJJJJJJIJJJJJJIJJIJIIIIJIJJIJJJJ;

	private System.Random JIIIJJJIJIJIJIJIJJIIJIJIJJIIIIIJJIIIJJIJIIJIIJI;

	private float[] IJIIIJIIIIIJIIJJIJIIJJJIIIIIIJIIJJIJIIJIJJJIJJI;

	public void IJIIIIIIJIIIJIJIJJJJIIIJIJJJJJJJJJIIIJJJIJIJJJI(int JIIIJIJIIIJJIIJIJIJJJIJIJIJJJIIIJIJJIJIJIIIJJIJ)
	{
	}

	private void IIJIJIJIIJIJIIJIIJIJJIJJIIIIIIJJJJJJJJJJIIIJJII()
	{
	}

	private GameObject JIJJIIJJJIIIJIIJIJIJIIJIJIJJIIJJIIJIJJJJJIJIJJJ(JIJJJJIIIJJJJJJJJIIIIJJIJIIIJIIIIIIIIJJIJJJIJII IJIIIIIIIJIIIIIIIIJJJJIJIJJJJJJIJIJJIJIIIJJJIJI)
	{
		return null;
	}

	private void IIIJJJJIIIJJJIJIIJJIIJJIIJIJIIIJJJJIIIIIJIJJIJI(IIIJIJIIIIIIIJJIJJIIJIIIIJIJJJJJIIIJJJJJIJJJJII JIJJJIJJIIIJJJJIJJIIJJJJJIJIIIIIIJJIIJJJIIJJIIJ, List<JJIJIIJJJIJJIIJIJIJIJIIJJIIIIJJIIJIJIIIIJIJIIJI> JJIJIIIIIIIJJIIIJJIJJIJIIJIIIJIIJJIJIJJJJIIJJJJ)
	{
	}

	private bool IJIJJIIJJIJIJIJIIJIJIJIIJIJJIJJIJIIIJIIJIJJJJII()
	{
		return false;
	}

	private GameObject JJIJIIIIJIIIIIJIJJIJJIJJJIIJIIIIIIJJIIJIIJIIJIJ(JIJJJJIIIJJJJJJJJIIIIJJIJIIIJIIIIIIIIJJIJJJIJII IJIIIIIIIJIIIIIIIIJJJJIJIJJJJJJIJIJJIJIIIJJJIJI)
	{
		return null;
	}

	private float IIIIIJIJJIJJIJIIIIIIIIJIIJIIIIIJJIIIIIJJJJIJIII(float IJJJJIJIJJJIJIIJIIJJJIJJJJIJIJJJJJIJIJIJIJIJJII, float JIIIIJJJIIJIJJIJJJJIJIIIIIJJIJJIJIJIJIJIIJJJJJI)
	{
		return 0f;
	}

	private float JIIIJJJIJIIIIIJIJIJJJJJIIJIJJIIJIJIIIJJIJJJIIJI(float IJJJJIJIJJJIJIIJIIJJJIJJJJIJIJJJJJIJIJIJIJIJJII, float JIIIIJJJIIJIJJIJJJJIJIIIIIJJIJJIJIJIJIJIIJJJJJI)
	{
		return 0f;
	}

	private float IJJJJIJIJIIIJJIJIIJIIIJJJJJIJJJJJJIIIJIJIIIIJJI(float JJJJIJIIJIJJIIJJJIIJIJJIJIIIJJJIJIJIIJJIIJIJIJJ, float IJIIJJIJIJIJIIJJJIJIIIJIJIIJIJJIIIIJIIIJIIIIIJJ)
	{
		return 0f;
	}

	private GameObject IIJJIJIIJIIIJJIIJIJIJJIJJIJIJIIIIIJJJJJIJJIJJII(JIJJJJIIIJJJJJJJJIIIIJJIJIIIJIIIIIIIIJJIJJJIJII IJIIIIIIIJIIIIIIIIJJJJIJIJJJJJJIJIJJIJIIIJJJIJI)
	{
		return null;
	}

	public void IIIIJIIIJIIJJJIIJJJJIJIIIJJJIIJJJJIIIJIJIJJIJII(int JIIIJIJIIIJJIIJIJIJJJIJIJIJJJIIIJIJJIJIJIIIJJIJ)
	{
	}

	private Quaternion IJIIJJJIJIJJIIIIJIIIJJIIJJJJIJJIIJIJJJIIJIJJJII(JIJJJJIIIJJJJJJJJIIIIJJIJIIIJIIIIIIIIJJIJJJIJII JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return default;
	}

	private bool IIIIJJIIIIJIJJJJJJIJIIIJIJIJIIIIJJJJJIJJJIJJJJI()
	{
		return false;
	}

	private void IIJIJJIJIJJIIJIJJJJIIIIIJIIJIIJIIIIJIJIIIJIIIII()
	{
	}

	private Quaternion IIIIJIIJJJIIIIIJJJIJIIIJIJIJIIIIJJJIJJJJIJIIJJJ(JIJJJJIIIJJJJJJJJIIIIJJIJIIIJIIIIIIIIJJIJJJIJII JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return default;
	}

	private float IIIIJIJJIJIJIIIIIIIIJJIIJIIJIJIJIJIIIJIIIIIJIJJ(float JJJJIJIIJIJJIIJJJIIJIJJIJIIIJJJIJIJIIJJIIJIJIJJ, float IJIIJJIJIJIJIIJJJIJIIIJIJIIJIJJIIIIJIIIJIIIIIJJ)
	{
		return 0f;
	}

	private float IIIIJIIIIIJIIIJIIIJIJJIIJJIJIIJIJIIJJJIJJJJIJJJ(float IJJJJIJIJJJIJIIJIIJJJIJJJJIJIJJJJJIJIJIJIJIJJII, float JIIIIJJJIIJIJJIJJJJIJIIIIIJJIJJIJIJIJIJIIJJJJJI)
	{
		return 0f;
	}

	public void JJJIJIJIIIIIIJJJIIJIJIJJJJJIJIIIIIJIJIIJIJJIIIJ(int JIIIJIJIIIJJIIJIJIJJJIJIJIJJJIIIJIJJIJIJIIIJJIJ)
	{
	}

	private bool IIIIJJIJJIIIJJJJIIJIIJJJIIJIIIIIIIJIJJJJJJJJJJI()
	{
		return false;
	}

	private void Awake()
	{
	}

	public void JJJJIJJIJJIIJJJIJJJIJJIIJIIIJIIIJIIJIJIIIIJJJIJ(int JIIIJIJIIIJJIIJIJIJJJIJIJIJJJIIIJIJJIJIJIIIJJIJ)
	{
	}

	private void IJIIIIIIIJIJJIIJIIJJIIIJIJJIJIIIIJJIIJJJIJIIIII()
	{
	}

	private float IIIIIIJJIIIIJIJIIIJIIJIIJIIJJJJIIJJJIIJIIJIIIIJ(float IJJJJIJIJJJIJIIJIIJJJIJJJJIJIJJJJJIJIJIJIJIJJII, float JIIIIJJJIIJIJJIJJJJIJIIIIIJJIJJIJIJIJIJIIJJJJJI)
	{
		return 0f;
	}
}
