using UnityEngine;
using UnityEngine.Events;

public class TutorialTarget : MonoBehaviour
{
	public Vector3 IJIJJJIIIJIIJJJIIIJIJJIJJIIJJJJIIJIJIIIIIIJIJIJ;

	public Vector3 JIIIIIJIIJIJIJJJIJIJJIJJJIJIJIIJJIJIIJIJIIJJJJJ;

	public float JJJIIJJIIIJJJIJJIIJJJJIJIJJJJJIJIJJIIIJJJJIJJII;

	public UnityEvent IIJIJIIIJJJJIIIJIIJJIIIIIJIJJIJIIJIIIJJJIIJIJIJ;

	private bool JIJIIJIIJJJJJIIJJJIIIIJJJJJIIJIIIIIJJJJJJJIIIII;

	public bool JJJJIIIJIJJIIJIIIJJIIIJJJJIJJJJJJIIJJJJJJIIIJIJ()
	{
		return false;
	}

	public void IIJIIJIJIIIJJJJIJJIJJJIIIJJJIIIJIIJIJJIIJJJJJJI(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public void IJJIJJJJIJIJIIIIJIJIIIIJIIIIIIJJIIIIIIIJIJJIJJI(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public bool JIIIJJIIJJJIJIJJJJJIIIJIIIIJJIIIJJJIJIJJIJIJJJJ()
	{
		return false;
	}

	public bool JIIIJJJJIIIJJIJJJIIIJJJIIJJIIJJJJJJJJJJIIJJIJII()
	{
		return false;
	}

	public bool JJJIJIJIJIJJIIIJJIIIIIIJIIJJJJIIJJIJIJJJIJJIJIJ()
	{
		return false;
	}

	public bool JIJIJJIJJIJIJIJJIIIJIIJIIJJIJJJJIIIIJJJJJIIIIJJ()
	{
		return false;
	}

	private void IJJIIIIJIJJIIIJIIIIJJIIIIIIJJJIIIJJJIIIIIIIJJIJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void JIJIJJJJIJJJIIIJJIIIIJJJJJIIIJIIIIIIJIIJIJIIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void JJJIIIJJIJIIIIJJJIIJIJIIIIJIJIIIJIJJJIIIJJIIIJJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public bool IIJIJJIIJJJJJJIJJJJIJIIJIJIJIIJJIIIJJIIJIIJIIII()
	{
		return false;
	}

	private void JIJJIIIIJIIJJIIIJIJIJIJIIIJIJIJJIJJIIJIIIIJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void JIIIIIJIIJIJJJJIJJIIJIJJIJJIJIIJIJJJJIIJJIIJJII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void JJJJJIJJJIJIIJIIJJJJIIIJIJIJJIJIIIIIIIJJIJIJIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void IJIIJIJJJJJIJJJJJJJJIJIIIIIIIJIIJIIJIJJJIJJIJJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void JIIIJJIIJIIIIIIJIIJJIJIJJJIIJJIIIIJJJJJIIIJJIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void JIJIJIJJIJJIIJJJIJJJIIIIJJJJJIIJIIJJIJJJJJJIJJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void JIIJIIJIJJIJIJJJIJIIIJJIIJIJIIJIIIJJJJIJJJIJIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public bool JIJIJJIJJJIIIJJIJJIJIIJJJIJIIJJJJJJIJIIJIJIIJIJ()
	{
		return false;
	}

	private void JJIJIJJIJIJJIIIJIIIJJJJJIJJIIJJIJIIJIJIIIIIJIJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public void IIJIIIJJIIJIJJJIJIIIJJJJJIJJIIIIJIIIIJJJIIIJIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}
}
