using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class TweenOrthoSize : UITweener
{
	public float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ;

	public float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII;

	private Camera IIIJJJIIJIIJIJJIJIJIIJJIIJIIJIJIJIIIJIJIJJIIJII;

	public Camera IIJIJJJIJJJJJIJJIIJIJIIJJJIIIIIIIJIIJJJIJJJJIJI => IJIIIIJJIJJJIIJJJJJJIJJIIIIIJIJJJIJIIIJJIIJIJJI();

	[Obsolete]
	public float JIIIJJIJIIJIJIJJJIIJIJIIJJJIJIJIIJIJIIIIJIIIJJJ
	{
		get
		{
			return IJJJIIJIIIIJIJJIIJIJIJJIJIIIJIJJJJJJJJIJJJIIJII();
		}
		set
		{
			JJJIIJIJIIIIIIIIIIJJJIIJJIJIJIJJIIIIJIJJIIJIJJJ(value);
		}
	}

	public float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI
	{
		get
		{
			return JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII();
		}
		set
		{
			JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(value);
		}
	}
	public void IIIIIJIIIJIIJIIJIJJIIIJIJJJIIJIJIJIJIJIIIIJIJII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual void IJIJIIIIJIIIIJJIIIIJJJJJJIIJIJJIJIJIJIIJIJJJIJI()
	{
	}
	public void JJJIJIJJJJJJIJIJIIIIJJIJJIIIJIJIJJJJIJIJJIIIJJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJIIJIJIIIIIIIIIIJJJIIJJIJIJIJJIIIIJIJJIIJIJJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected override void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public Camera IJIIIIJJIJJJIIJJJJJJIJJIIIIIJIJJJIJIIIJJIIJIJJI()
	{
		return null;
	}

	public float JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII()
	{
		return 0f;
	}
	public void JJIJIJIIIIJJJIJIJIIJJIIJIJIJIJIIIJJJIIIJJJIIJII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public float JIJIJIIIIIJIIJJJIIJIJJJIIJJJJIIIIJIIIJJIJIIJIJJ()
	{
		return 0f;
	}
	public float IJIIIJJJIJJIJJIIJIJIJJIJIIIIIJJIIIJIIIIJJIJIJJJ()
	{
		return 0f;
	}

	public override void JIIIIIIJJJJIJJIIIJIIJJIIIJJIIIJJIJJIIIJJIJJJIII()
	{
	}
	public Camera JJIIIIJIJJJJJIIJIJJIIJIJIIJIJJIIJIJIJJJJJJJJIIJ()
	{
		return null;
	}
	public float JJIIJIIJIJJIJIJJJJJJJJIIJJIIJIJIJJIJJJJIIJJIIII()
	{
		return 0f;
	}

	public void JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public override void JJJIIIIIIIJJJJJIJJJJIIJJJIIIIJIIIIJIJJJIJJJJJJI()
	{
	}

	public float IJJJIIJIIIIJIJJIIJIJIJJIJIIIJIJJJJJJJJIJJJIIJII()
	{
		return 0f;
	}

	public static TweenOrthoSize JIIIJIIIJJJJJJIIIIJIIJJIJJIIIIJIIJIIIIJIIJIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII)
	{
		return null;
	}
	public void IIIIIIJIJJIJJJJJJJJIJJIJIJJIJIIJJJIJJIIIJJIIJIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static TweenOrthoSize JJJIJIJIJIIJJIIJJJIIIJIIJIIJIJJJJIJIIIJJIJIJJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII)
	{
		return null;
	}
	public Camera JJJJIIIJIJIJJJJJJJIIIIIJIJJIJIIJJJJIJIJIIIJJJII()
	{
		return null;
	}
}
