using System;
using System.Collections.Generic;
using UnityEngine;

public class TweenLetters : UITweener
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JIJIIJIJJIJJJJIIJIIIIJIJIJIJJIIIJIIIJIJJJJJJJJI
	{
		Forward = 0,
		Reverse = 1,
		Random = 2
	}

	private class IJJJJIIJJJJJIJJIJIIJIIJJIJIJJIJIJJJJJIJJJIIIJJJ
	{
		public float JIIIIJJJIIJIIIIIIIJIJIIJIIIJJJJIIJJJJIJJIIIJIJI;

		public float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ;

		public Vector2 IJJIJIIIIJIJIJJIIIIIIIJIIIJJIIIIJIJIJJIJIJIJIJJ;
	}

	[Serializable]
	public class JJIIJIIJJIJIIJIIIJIIIIIIIJJJIJJJIIJIJIIIJIJJIIJ
	{
		public JIJIIJIJJIJJJJIIJIIIIJIJIJIJJIIIJIIIJIJJJJJJJJI IJJIIJJJJIIJJIIJJJJJIJJJJJJJIJJJIIJIJIJIJIIJIJI;

		public float IJIJJIJIIIJIIIJIIIJJJIJJJIIIIIJIIIJJJJJIIIIIJJI;

		public bool JIIIJJJJIIJIJIIIJJIJJIIJJIJJIIIJJJJIJJJJJJJJJJI;

		public Vector2 IIJIJIJJJIIJIJIIJJIJJIIIIIJJJJIJIIJJIIIIIJJJJJJ;

		public Vector2 IJIJIIJJIIIIIIJJJIJJJIIJIIIIJIIIIIJIJIJIJIIIJII;

		public Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ;

		public Vector3 IJJJJJJJIJIIIIIJJIIIIJIIIIJJJIIJJIJJJIJJIIIIJJI;

		public Vector3 IJIJIJIJJJIIJJJJJIJJJJJIJJIIJJJJJJIJIJJJJIJJIJI;

		public float IJIIJJIIJIJJJIJIJJJIIJJIIIJJJIIIJJJJIIJJIIJIIIJ;
	}

	public JJIIJIIJJIJIIJIIIJIIIIIIIJJJIJJJIIJIJIIIJIJJIIJ IIJJJIJIIIIJIIJJIJIJJIIJIJIJIIIIIJIJIJJIIIJJIJJ;

	public JJIIJIIJJIJIIJIIIJIIIIIIIJJJIJJJIIJIJIIIJIJJIIJ IJJIJJJIJIIIJIIIIJJJJJIIJJJJJJIJJJIIIJIJJIIIJJJ;

	private UILabel JJJJIIIIIJJJJJJJJJJIJIIJJJJJIJIJJJJJJIIJJJIIIJJ;

	private int JIJIJIIIIIIIJJJJJJIJJIJIJJIJIJIIIJIIJIIIJIJIIJI;

	private int[] JJJIJIIIIJIIIJIIJJIJIIIJIJIJIJJIIIJJIJJIJIJIIJJ;

	private IJJJJIIJJJJJIJJIJIIJIIJJIJIJJIJIJJJJJIJJJIIIJJJ[] IIIIIJIJJJJJIJIIIIIIJIIIIIIIIJIJIIJIJJIIJJIIJIJ;

	private JJIIJIIJJIJIIJIIIJIIIIIIIJJJIJJJIIJIJIIIJIJJIIJ JIIIIIIIIJIJJIIIIJIJIIJJJIJJIIJIJIJIJJJJJJIIJJI;

	private void IIJJIIIJIJIIIIJJIIJIJJIJIJIIIJIIIIIJJIIIJIJIJJI(int IIIIIJJJJIJIIJJIIIJJIJIIJJJJIJIIIIJIJJIJJJIJJIJ)
	{
	}

	private void JJJIJIIIJJJJJIJIIIJIJJIJIJIIIIJJIJIJIIJJIIJIIIJ(int IIIIIJJJJIJIIJJIIIJJIJIIJJJJIJIIIIJIJJIJJJIJJIJ)
	{
	}

	private void OnEnable()
	{
	}

	public override void JIJJIIJIIJJJJJIJIIJJIJIIJIJJIIJJIJIIIIIJJJIIIJJ(bool IIIIIIIJIIIJJJIJIIJIIIIJIJJJIJIJIIJIJIIIJIJJJII)
	{
	}

	public virtual void IIIJIIIJIIJJIIIJJJIJIIJJIJJJIIJJJJJJIJIJIIIJJJI(bool IIIIIIIJIIIJJJIJIIJIIIIJIJJJIJIJIIJIJIIIJIJJJII)
	{
	}

	private void IJIJIJIJJJIJJIJJJJIIIJJIJIJJIJJJJIJJJJJIJIJJJJI(int IIIIIJJJJIJIIJJIIIJJIJIIJJJJIJIIIIJIJJIJJJIJJIJ)
	{
	}

	protected virtual void IIIIIIJIIIJJIJIIIJIIIJIJIJJIJIIJIIIIJIJJIJJJIII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	private void JJIJIJIJJJJJIIJJIIIJJIJIIIJJIIJJJIIIIJIJJIIIIJI()
	{
	}

	private void IIJJJJJIIIIJIJIIIJIIJJJIJIIIJJIJJIJIJIJIIIJIIJI()
	{
	}

	protected override void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	private float JJIJIJIIIJIJIJJIJIIJJJJIJIJIJIJJIIJIJJIJJIIJIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, float JJJIJJJJIJJIIJJJJJIJIJJIIIIJIIIJIJJIIIJJIJJJIJJ, float IIIIJJJJIIIJJIIIIJIIIIIIIIIJIIIJIIIIIIJIJJIIJJI)
	{
		return 0f;
	}

	private void JIJIJIIIJIIJJIIIIIJJIJIIIIJJJIJIJJIJIJIIIIJIJJI()
	{
	}

	private void JJJJIIJJIJIIIJIIIJIIIJJIIJIJJIIIJJJIIIIIJIIJJJI(int IIIIIJJJJIJIIJJIIIJJIJIIJJJJIJIIIIJIJJIJJJIJJIJ)
	{
	}

	private void JJIIJJIIIJIIIJJJJIIIIJIIIIIJJIJJIIIJJIJJIIIJIIJ(UIWidget JJIJJJIIIIIIIJIIIIIJJIIJIJIIIJJJJIJIJJJIJJIJIJI, int IJIJJJJJIJJJJJJJIJJIJIIIIIJJJJIIIIJIIJIIIIIIIJI, List<Vector3> IJJIIJJIIJIJIJIIIIIJIJIIJIJJJJIJIJIIJJIIIJJIJIJ, List<Vector2> IJJJIIJJJIJIJIIIJJIJIJIJIJJJJIIJIJJIJIJIJJIIJJJ, List<Color> IJIJIJJJJJJJIIIIJJIIIIJJJIIJJJJIJIJJJJIIJIJIJII)
	{
	}

	private static Vector3 IJJIIJIIIJIJIIJJJJJJJJJIIIIJJIJIIIJIIJJIJIJIIII(List<Vector3> IJJIIJJIIJIJIJIIIIIJIJIIJIJJJJIJIJIIJJIIIJJIJIJ, int JJJIIIIJJIIJIJJJIIJIJJIIJIJIIIIIIJIIIIJIJIIIJJI, int IIIJJJIJIJJJJIJJIIIJJJIIIIJIJJIJJIIJJJJIJIJIIII)
	{
		return default;
	}

	private void JJJJJJIIJJIJIIJIJJIIJIJIJJJIIJIIJJJIIJJIJJJIIII()
	{
	}

	private void OnDisable()
	{
	}

	private float JIJJIJIIJJIJIIIIIIIJIIJIJIJIIJIIIJIJIIJJIIJIIJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, float JJJIJJJJIJJIIJJJJJIJIJJIIIIJIIIJIJJIIIJJIJJJIJJ, float IIIIJJJJIIIJJIIIIJIIIIIIIIIJIIIJIIIIIIJIJJIIJJI)
	{
		return 0f;
	}

	private void Awake()
	{
	}

	private void IIIJJIJJJJJJJJIIJJIJJJIJJIIIIJIIIJJIIIIIIJJJJJJ()
	{
	}

	private void JIIIIIJIJJIIIIIIIJJIIJJJJIIJJJJJJIIJIJJJJIIIIJJ()
	{
	}

	private void IIJIIJJJIIJJJIIIJJIJIJJIIJJIIIJIJJJIJJIJIJJIJJI()
	{
	}

	private void JIJIIJJIIIIIIIJJIJIJIJJJIJJIJIIJJIJJJIJIIIJIIJJ()
	{
	}

	protected virtual void IIIJJIJJJJIJIIJJJJIIJJIIJJIJIJJIIJIJIIJJIIIIJIJ(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	private void JIJJJJIJIIIIIIJIIIJIIIJJJIJIJJJJIJJJIJIJIIIIJJI(int IIIIIJJJJIJIIJJIIIJJIJIIJJJJIJIIIIJIJJIJJJIJJIJ)
	{
	}

	private void JIIJJIIIIIJIJIJJIJJJIIIJIIIIJIJIIJJJJIJIIIIJJJJ(int IIIIIJJJJIJIIJJIIIJJIJIIJJJJIJIIIIJIJJIJJJIJJIJ)
	{
	}

	protected virtual void JIIIJJJIJJJJIJIJJJIJIJJIJIIIIIIJJJIJIIJIJIIIIIJ(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	private void IJJIJJJIJJIJIIJIJJIIJIJJJIJIIIIJIIIJJIIJIIJIJJJ(UIWidget JJIJJJIIIIIIIJIIIIIJJIIJIJIIIJJJJIJIJJJIJJIJIJI, int IJIJJJJJIJJJJJJJIJJIJIIIIIJJJJIIIIJIIJIIIIIIIJI, List<Vector3> IJJIIJJIIJIJIJIIIIIJIJIIJIJJJJIJIJIIJJIIIJJIJIJ, List<Vector2> IJJJIIJJJIJIJIIIJJIJIJIJIJJJJIIJIJJIJIJIJJIIJJJ, List<Color> IJIJIJJJJJJJIIIIJJIIIIJJJIIJJJJIJIJJJJIIJIJIJII)
	{
	}
}
