using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class TweenRotation : UITweener
{
	public Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ;

	public Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII;

	public bool JJIJJIIJJIIIJJJJIJIJJJIJIJJJIIIJJJJJIJIJIIJIJJJ;

	private Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	[Obsolete]
	public Quaternion IIIIJJIIIJIJJJIIJJJJIIIIJJIIIIJIIJJIJIJIJJJJIII
	{
		get
		{
			return JJIJJIIIJIJIJIJJIIIIIIJIJIJJIJIJJIJJIIJIJJIIIJI();
		}
		set
		{
			IIJIIIIIIJIJJJJIJJJJJJIIIIIJJJJJIJJIJJJJJIJJJJJ(value);
		}
	}

	public Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI
	{
		get
		{
			return JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII();
		}
		set
		{
			JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(value);
		}
	}

	public void JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public override void JIIIIIIJJJJIJJIIIJIIJJIIIJJIIIJJIJJIIIJJIJJJIII()
	{
	}
	public Transform JIJIJJJJJJJJIJIJIJIIJIJIIJJJIJIJJJIJIIIIIJIJJII()
	{
		return null;
	}

	public static TweenRotation JJJIJIJIJIIJJIIJJJIIIJIIJIIJIJJJJIJIIIJJIJIJJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, Quaternion IJJJJJJJIJIIIIIJJIIIIJIIIIJJJIIJJIJJJIJJIIIIJJI)
	{
		return null;
	}

	protected virtual void IIIIIIJIIIJJIJIIIJIIIJIJIJJIJIIJIIIIJIJJIJJJIII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public void IIJIIIIIIJIJJJJIJJJJJJIIIIIJJJJJIJJIJJJJJIJJJJJ(Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public override void JJJIIIIIIIJJJJJIJJJJIIJJJIIIIJIIIIJIJJJIJJJJJJI()
	{
	}
	public void IIIJJIIJJJIIIJIIIIIJIIIIJIJJJJIJIJJIJIJJJIJJIJI(Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected virtual void JIIIIJJJJIIJJJJJIJJJJJIIJIIJJJIJJIIJIJJIIIJJJII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}
	public void IJJJJIJJJJJJIJIIIIIJIJJJJIJIIJJJIJJIIIIIIJIJIJJ(Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJJIIJJIJIIIIJIIJIJJJJJIJIJJJIJIJIIIIJJJIJIIJJI()
	{
	}
	public Transform JIJIIJIJIIJJIJIJIIIIJIIIJIJJJJJIIIIJJJIIIIJJJIJ()
	{
		return null;
	}

	public static TweenRotation JIIIJIIIJJJJJJIIIIJIIJJIJJIIIIJIIJIIIIJIIJIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, Quaternion IJJJJJJJIJIIIIIJJIIIIJIIIIJJJIIJJIJJJIJJIIIIJJI)
	{
		return null;
	}

	private void IJJJIJIJJJIJIJJIIJJJIIJJIIJIJJJJIIJJIJIJIJJIIIJ()
	{
	}

	public virtual void IJIJIJJIJIJIJIJIIIIIJJIIJIIIJJJJIIJJIIIIIJIIIJI()
	{
	}
	public void IJJJJIIJJIJJIJIIIIJIJJJJIJJIIJJJIIJJIIIIJJIJIJJ(Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJJJJJIJIJJJJIJIJIIIJIJIJIIIIIJJJJJIIJJIJIIIIII()
	{
	}

	public Quaternion JJIJJIIIJIJIJIJJIIIIIIJIJIJJIJIJJIJJIIJIJJIIIJI()
	{
		return default;
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}

	protected override void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public Quaternion JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII()
	{
		return default;
	}
	public void JIJIJIJIIIIJIJJIIIIJIJJIJJIJJJJJJIJIJJJJIIIJIII(Quaternion JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
}
