using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class TweenPosition : UITweener
{
	public Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ;

	public Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII;

	[HideInInspector]
	public bool IJJIIJIIIJJJJIJJJJJJIIJIIJJJJIJIIJJJIJIIJIIJJJJ;

	private Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	private UIRect IJJJJIJJIJIJJJJJIJIJIJIIJJJJIIIIJIIJJIIIIJIJIIJ;

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	[Obsolete]
	public Vector3 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ
	{
		get
		{
			return IIIIJIIJJIJJJIJIJJJIIIJIIIJIIJJJIIIJIIJIJIJIJJI();
		}
		set
		{
			IJJIJJIIJIIIJIIIJIIIIJIIJJIJIJJJJIIJIJJIIJIIJII(value);
		}
	}

	public Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI
	{
		get
		{
			return JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII();
		}
		set
		{
			JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(value);
		}
	}

	private void IIJJJJJJJJIJJIIJIIIIJIJIIJIIJJIIIIJJIJJIIIJIJII()
	{
	}

	public override void JIIIIIIJJJJIJJIIIJIIJJIIIJJIIIJJIJJIIIJJIJJJIII()
	{
	}

	public virtual void JJJJIJJIIIJJIIJIIJIJJJIIJIJJIIJIJJJIIIJIJJIJIIJ()
	{
	}

	public virtual void JIJIJIJJJIIIJIIJIJIJIIIJIIIIIIJIJJIIIJIJJIJJJIJ()
	{
	}

	protected virtual void JIIJIJJIJIJJIIJIIJIIIJJIJJIIIJJJIIIIJJIIJIIJIJJ(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}
	public void IIIIIJJJJJJJIJJJJIJIIJIIIJJJIJIJJIJJIIIJIJIJJIJ(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JIIIJJIJIJJIJJJIIIIJJJIJIJIJIIIJJJJIJJIIIIJJIII()
	{
	}

	public void IJJIJJIIJIIIJIIIJIIIIJIIJJIJIJJJJIIJIJJIIJIIJII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual void IIJIIJJJIIJJJJIJIIJJIJJIIIJJJIJJIJJJJJIIIIIJIJI()
	{
	}

	private void JJJIIIJIIIIJIJJJIJJJIJJIJIJIIIIJJIJIIJJIIIIJJJJ()
	{
	}

	public static TweenPosition JIIIJIIIJJJJJJIIIIJIIJJIJJIIIIJIIJIIIIJIIJIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
		return null;
	}

	private void JJJJJJIJIJJJJIJIJIIIJIJIJIIIIIJJJJJIIJJIJIIIIII()
	{
	}
	public void IJJJJIJJJJJJIJIIIIIJIJJJJIJIIJJJIJJIIIIIIJIJIJJ(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJJIIJJIJIIIIJIIJIJJJJJIJIJJJIJIJIIIIJJJIJIIJJI()
	{
	}

	public virtual void JJIIIIJJJIJJIIIIIJIIIJJIIJIJJIIIIIIJIIIJIIJIIII()
	{
	}

	public virtual void JIJJIJJIIJIIJIJIIJIJIIIIIIIJJIIIJIIIIJJIJJJIIJJ()
	{
	}

	public virtual void IJJJJIIJJIIIIIJJJIIJJJJIIJJIJJJJJJIJIIIIJIJJJJI()
	{
	}

	public Vector3 IIIIJIIJJIJJJIJIJJJIIIJIIIJIIJJJIIIJIIJIJIJIJJI()
	{
		return default;
	}

	public override void JJJIIIIIIIJJJJJIJJJJIIJJJIIIIJIIIIJIJJJIJJJJJJI()
	{
	}

	protected override void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public static TweenPosition JJIIIIIJJIJIIJJIIIIIIJJJJJJJJJIIIIJJIIJJIIJIIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
		return null;
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}

	private void Awake()
	{
	}

	public void JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static TweenPosition JIIIJIIIJJJJJJIIIIJIIJJIJJIIIIJIIJIIIIJIIJIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, bool IJJIIJIIIJJJJIJJJJJJIIJIIJJJJIJIIJJJIJIIJIIJJJJ)
	{
		return null;
	}

	public static TweenPosition IJJIIIIIIJIJIJJIJJJIJJJJIIIJIJIJIIIJIIIJIJIIJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
		return null;
	}

	public Vector3 JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII()
	{
		return default;
	}
	public Vector3 IIJJJIIJJIIIIIIJJIJIJJJJIIJIJIJIIJIJIIJJIIIJIJI()
	{
		return default;
	}
}
