using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class TweenAlpha : UITweener
{
	public float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ;

	public float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII;

	private bool JJJJIIIIJJJIIIIIJJJIIJIIJIIJJJJIJJIIJJIJJIIIJIJ;

	private UIRect IJJJJIJJIJIJJJJJIJIJIJIIJJJJIIIIJIIJJIIIIJIJIIJ;

	private Material JIJJIIJIJJJIIJJJIIIJJIIJJJIJIJJIIJIJIIJJJJJIJII;

	private Light IJIJIIIJJIJIIIJIJIJIIIJJIIIJJIJJJIJIJIJJJIIIJJI;

	private SpriteRenderer IIIJJIIIJIJIIIIIIIIIIIIJIIIJJJIIJJIIIIIJJIIJJII;

	private float JJIJIJJIIIJJJJJIJJJIIIJJIIJIJJJJIIJIJIJIJIJIIII;

	[Obsolete]
	public float IJIIJJIIJIJJJIJIJJJIIJJIIIJJJIIIJJJJIIJJIIJIIIJ
	{
		get
		{
			return IJJJJIIJJIJJJJIIIIIJJJIIJJJJJJJIIJJJJIJJJJIIJIJ();
		}
		set
		{
			IIIJIIJIIJJJJIIIJIJJIJJJJJIIIIIJIJIJJIIIJJJIJJJ(value);
		}
	}

	public float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI
	{
		get
		{
			return JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII();
		}
		set
		{
			JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(value);
		}
	}
	public void JJIJJIIJJJJJJJIIIIIIJJIJJJJJIJIJJIIJIJIIIIIIIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual void JIJIJIJJJIIIJIIJIJIJIIIJIIIIIIJIJJIIIJIJJIJJJIJ()
	{
	}

	protected virtual void JIJJIJIIJJJIJIJIJIJIIIJIJIJJJIJIJJJIJJJJJIJIJIJ(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public virtual void JJJJIJJIIIJJIIJIIJIJJJIIJIJJIIJIJJJIIIJIJJIJIIJ()
	{
	}
	public float JIJIIJJIIJJIIJIIJJIIIJJJJJIJIJIJIIJIIIJIJJJIJII()
	{
		return 0f;
	}

	private void IIIJIIIJIIJIIIJIIJJJIIIJJJJJJIJIIIJJIIIJIJJJJJI()
	{
	}
	public float IJJIIJIIIJIJJIJJJIIJIIJIIJJJJIIJIIIJIJIIIIJIIII()
	{
		return 0f;
	}
	public void IIJJJIIJIIJIJIIIJIJJJJIIJJJJIIIIIIJIIJJIIJJJIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual void IJIJIJJIJIJIJIJIIIIIJJIIJIIIJJJJIIJJIIIIIJIIIJI()
	{
	}

	private void JIJJIIIIJIIJJJJIIIJIJIJJJJJJIIJIIIJIJIIIIIIJJIJ()
	{
	}

	public virtual void JJIJIIJJJJIIJJIJIIJIJIIJJJJIIJIJJIIJIIIIJJIJJJI()
	{
	}

	public void IIIJIIJIIJJJJIIIJIJJIJJJJJIIIIIJIJIJJIIIJJJIJJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public float JIIJJJJJIIIIIJIJIIIIIIIJJJJIJIIIJIIJIJJIIIJIJII()
	{
		return 0f;
	}

	public float JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII()
	{
		return 0f;
	}

	public override void JJJIIIIIIIJJJJJIJJJJIIJJJIIIIJIIIIJIJJJIJJJJJJI()
	{
	}

	protected override void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public void JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual void IIJJJIJIIJIJIJJJIIIIIJIIJJJJIJJIJJJIJJJIJJJJIJJ()
	{
	}

	public override void JIIIIIIJJJJIJJIIIJIIJJIIIJJIIIJJIJJIIIJJIJJJIII()
	{
	}
	public void IJJIIJIIJJJJJIJJIJIIJJIIIIIIIJIJIIIIJJJJIIIIJJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual void JJJJIIJIIJJJJJJJIIJJIIIIIIJIIJIJIIIIJIIJJJIJIII()
	{
	}

	public float IJJJJIIJJIJJJJIIIIIJJJIIJJJJJJJIIJJJJIJJJJIIJIJ()
	{
		return 0f;
	}
	public void IIJJIJJIIIIIIIIIIJIJJJIJIJJJIIJIIIJIJJJIJIIIJJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected virtual void IIIIIIJIIIJJIJIIIJIIIJIJIJJIJIIJIIIIJIJJIJJJIII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public static TweenAlpha JIIIJIIIJJJJJJIIIIJIIJJIJJIIIIJIIJIIIIJIIJIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, float IJIIJJIIJIJJJIJIJJJIIJJIIIJJJIIIJJJJIIJJIIJIIIJ, float IIJJJJJJIIIIJJIIJJJJIIIJJIJIJJJIJJIIJIJIIIJJIJI = 0f)
	{
		return null;
	}
}
