using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class TweenScale : UITweener
{
	public Vector3 IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ;

	public Vector3 JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII;

	public bool JJIJIJJIJIIJJJJIJJIJJJIJJJJJIJIIIIJJIIJIIJJJJII;

	private Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	private UITable IIJIIJIJIJIIJIIIIIJJIJIJJJIJIJJJIJJJJJJJJIIJJIJ;

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	public Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI
	{
		get
		{
			return JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII();
		}
		set
		{
			JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(value);
		}
	}

	[Obsolete]
	public Vector3 IJIJIJIJJJIIJJJJJIJJJJJIJJIIJJJJJJIJIJJJJIJJIJI
	{
		get
		{
			return JIJIIJIIJIIJIIJJJIJIIIJIJIJJIIIJJIIJIJJJJJIJJJI();
		}
		set
		{
			IIIJIIIJIJIJIJIJJJIIIJJJIJIJJJJJJJJIIJJIIJIJJII(value);
		}
	}

	public virtual void IJIJIIJJIJJJJIIJJIIJJIJIIJIJJJIIJJIIJJJJIIJJJIJ()
	{
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}
	public void IJIIJJIJIIJJJJIIIIJJIJJIJJIIJIJJIJIIJIJJIJJIIJI(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual void JIIJJJJJIIJJJJJIJIJJIJIJIIIIJJJIIJIJJIJJIIJJJJJ()
	{
	}
	public void JIJJJJJIJJIJJJIJIIIIIJIJJJIJIIJIJJJIJJJIIJJJIIJ(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static TweenScale JJIJJJJJJJIIJIIIIJIIJJIIJJJJIIIJIJJIIIIJJJIIJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, Vector3 IJIJIJIJJJIIJJJJJIJJJJJIJJIIJJJJJJIJIJJJJIJJIJI)
	{
		return null;
	}

	private void IIJIJIJJIIJJIIIIIIIJJIIIJIIIIJJJJJIJIJIJIIJIIIJ()
	{
	}

	public Vector3 JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII()
	{
		return default;
	}

	public override void JJJIIIIIIIJJJJJIJJJJIIJJJIIIIJIIIIJIJJJIJJJJJJI()
	{
	}
	public void JIJIIJJIIIIJIJJJJIJJJJJIIJJJJJIJJJJJIIJJJJIJIII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIJIIIJIJIJIJIJJJIIIJJJIJIJJJJJJJJIIJJIIJIJJII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public override void JIIIIIIJJJJIJJIIIJIIJJIIIJJIIIJJIJJIIIJJIJJJIII()
	{
	}

	public void JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJJIIJJIJIIIIJIIJIJJJJJIJIJJJIJIJIIIIJJJIJIIJJI()
	{
	}

	private void IJIIIIJJIIIIJIIJIIIIIJJJIIIIIIIJIIJJIJIJIJIIIIJ()
	{
	}

	public static TweenScale JIIIJIIIJJJJJJIIIIJIIJJIJJIIIIJIIJIIIIJIIJIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, Vector3 IJIJIJIJJJIIJJJJJIJJJJJIJJIIJJJJJJIJIJJJJIJJIJI)
	{
		return null;
	}

	public static TweenScale IIIIIIIJJIJJJIJJJJJIIJJIIIIIJJJJIJJIJJJJJJIIJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, Vector3 IJIJIJIJJJIIJJJJJIJJJJJIJJIIJJJJJJIJIJJJJIJJIJI)
	{
		return null;
	}

	public Vector3 JIJIIJIIJIIJIIJJJIJIIIJIJIJJIIIJJIIJIJJJJJIJJJI()
	{
		return default;
	}

	protected virtual void IJIJIJIJJJIJJJIJIJJIJIIIJJJIJJIJJJIJIIJIJIJJJJJ(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}
	public Vector3 IJJIIIJIIJIJJJJJIJJIJJJJJIIJIIJJJIJIJJJJIIIJIJJ()
	{
		return default;
	}

	protected override void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}
	public void IIJJJIIJIJJIJJIJJIIJJJJJIJIJIJIJIIIJJJJJIJIJIJI(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual void IIJIIJJJIIJJJJIJIIJJIJJIIIJJJIJJIJJJJJIIIIIJIJI()
	{
	}
	public void JJJJJJJIJIIIIIIIJIIJIIIIJIIJJJIIIIIIIIJJIJJIJJI(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJJJJJIJIJJJJIJIJIIIJIJIJIIIIIJJJJJIIJJIJIIIIII()
	{
	}

	public virtual void IIJJJIJIJJJJJJIIIIIJIJJJJJJJIJIIIJIIIJJJIJJJJJJ()
	{
	}
}
