using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class TweenVolume : UITweener
{
	public float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ;

	public float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII;

	private AudioSource JIIIIIIJJJIIJIIIJJIJJJIIIIJJIIIIIIJJJIJIIIIJIJI;

	public AudioSource IIJIJIIIIJJJJJIJJJIIIJIJJIJJIJIIJIJJIIIJJJIIJIJ => JIIJIJJIJJJIJIIJJIIIIJJIJIJIJJIIJJIJIIJIJIJIJJI();

	[Obsolete]
	public float IIJJIIIJIJIJJJJIIJJJJIIIIIIIIIIJIIIIJIJIIIIIIII
	{
		get
		{
			return IIJIIJIIJIIJIIJIJJJIJJJJJIJJJIJJJIIIIIIIIJJIIII();
		}
		set
		{
			JIIIIIJJIIIJIIIIJJJJIIJIIIIJJIIIIJJJJJIJIIJIJJJ(value);
		}
	}

	public float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI
	{
		get
		{
			return JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII();
		}
		set
		{
			JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(value);
		}
	}
	public float IIIIJJJIJIJIJIJJIIJIJJIIIIIJIIJJIIJJIIJIIIJIIJJ()
	{
		return 0f;
	}

	public static TweenVolume JIIIJIIIJJJJJJIIIIJIIJJIJJIIIIJIIJIIIIJIIJIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, float JJJIIIJIJIJIJJJIJJIIIJIJIIJIIJJJJIIIJIJIIIIIIJI)
	{
		return null;
	}

	public void JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static TweenVolume JJIIIIIJJIJIIJJIIIIIIJJJJJJJJJIIIIJJIIJJIIJIIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, float JJJIIIJIJIJIJJJIJJIIIJIJIIJIIJJJJIIIJIJIIIIIIJI)
	{
		return null;
	}

	public void JIIIIIJJIIIJIIIIJJJJIIJIIIIJJIIIIJJJJJIJIIJIJJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public AudioSource JIIJIJJIJJJIJIIJJIIIIJJIJIJIJJIIJJIJIIJIJIJIJJI()
	{
		return null;
	}

	public float IIJIIJIIJIIJIIJIJJJIJJJJJIJJJIJJJIIIIIIIIJJIIII()
	{
		return 0f;
	}

	protected virtual void IIJJJIIJJIIJJIIJJIJIJJIIJIJJIIJIJJIJJIIJIIIJJJJ(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public float JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII()
	{
		return 0f;
	}

	public static TweenVolume IIIJJJJIIJIIJJJIJJIIIIJIJIJJIJIJIJJJJJIIJIIIJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, float JJJIIIJIJIJIJJJIJJIIIJIJIIJIIJJJJIIIJIJIIIIIIJI)
	{
		return null;
	}

	protected virtual void JJIIIIJIIJIJIIIJJIJIJJJJJIJIIIJIJJJIJIIJIIJIIJI(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public static TweenVolume IIIIIIIJJIJJJIJJJJJIIJJIIIIIJJJJIJJIJJJJJJIIJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, float JJJIIIJIJIJIJJJIJJIIIJIJIIJIIJJJJIIIJIJIIIIIIJI)
	{
		return null;
	}
	public void JJIJIIIJJJJIJJJJIIJIJIIIIJIIJJJIIIJJIIIIJIJJIJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void JJJIIIIIIIIIIJIIJIIJIIIIJIJJJIIJJIJIIIIIJJIJIJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static TweenVolume IJIJJIIIJJIIIJIIJIJIIJJJIIJJJIIIIJJJIIJIJJJJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, float JJJIIIJIJIJIJJJIJJIIIJIJIIJIIJJJJIIIJIJIIIIIIJI)
	{
		return null;
	}

	public virtual void JIJJJIJJJIJIIJJJIJIJJJJJJIJIJIIIJIIJJIIIIIIIIII()
	{
	}
	public void JJJJJJJIJIIIIIIIJIIJIIIIJIIJJJIIIIIIIIJJIJJIJJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual void IIJJJIJIIJIJIJJJIIIIIJIIJJJJIJJIJJJIJJJIJJJJIJJ()
	{
	}

	protected override void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public override void JIIIIIIJJJJIJJIIIJIIJJIIIJJIIIJJIJJIIIJJIJJJIII()
	{
	}

	public virtual void IJIJIIIIJIIIIJJIIIIJJJJJJIIJIJJIJIJIJIIJIJJJIJI()
	{
	}

	public override void JJJIIIIIIIJJJJJIJJJJIIJJJIIIIJIIIIJIJJJIJJJJJJI()
	{
	}
	public float JJIIIJIIIJJJIJJJIJJIIJIJJIJIJJIIJIIJJJJJJIIJIJJ()
	{
		return 0f;
	}

	protected virtual void JIIJIIJIJJIIIJJJJJIJIJJIJJIIJIIJIIJJIIIJJIJJIJJ(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public static TweenVolume JJIJJJJJJJIIJIIIIJIIJJIIJJJJIIIJIJJIIIIJJJIIJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, float JJJIIIJIJIJIJJJIJJIIIJIJIIJIIJJJJIIIJIJIIIIIIJI)
	{
		return null;
	}
	public void IIIIIJIJJIJIIJJIIIJJIIJIJIJIJJJJIIJJIIIIIIJIJJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual void JIIIJJIIJJIJJJJJJJJIIJJIJIIJJJIIJJJJIIJIJJIIJII()
	{
	}
}
