using System.Runtime.CompilerServices;
using UnityEngine;

public class TweenFill : UITweener
{
	public float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ;

	public float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII;

	private bool JJJJIIIIJJJIIIIIJJJIIJIIJIIJJJJIJJIIJJIJJIIIJIJ;

	private UIBasicSprite IJIJIIJIIIJIJJJIJJJIJIIJJJJJJJJIIIIIIIJJJJIIJJI;

	public float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI
	{
		get
		{
			return JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII();
		}
		set
		{
			JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(value);
		}
	}

	public override void JIIIIIIJJJJIJJIIIJIIJJIIIJJIIIJJIJJIIIJJIJJJIII()
	{
	}

	public void JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public override void JJJIIIIIIIJJJJJIJJJJIIJJJIIIIJIIIIJIJJJIJJJJJJI()
	{
	}

	protected virtual void IJJIIIIJJJIJIJIJJIJIIJJIIJJJIIJJJIIIJIJIJJIJJII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}
	public float IJIJIJIJIIJJIIJIJIIIIIJIIIIJIJIJIJIIJIIJJJIJJJI()
	{
		return 0f;
	}

	public static TweenFill IJIJJIIIJJIIIJIIJIJIIJJJIIJJJIIIIJJJIIJIJJJJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, float JIIJIIJIJJIJIJIIJJIIJJIJJJJJJIJJIIJIJIIJIIIJJJJ)
	{
		return null;
	}
	public float IIIIJJJIJIJIJIJJIIJIJJIIIIIJIIJJIIJJIIJIIIJIIJJ()
	{
		return 0f;
	}
	public float IJIIIJIJIIJJIJIJJIIIIJIIIJIJIIIJIIJJJIIJJIIIJII()
	{
		return 0f;
	}

	public static TweenFill JIIIJIIIJJJJJJIIIIJIIJJIJJIIIIJIIJIIIIJIIJIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, float JIIJIIJIJJIJIJIIJJIIJJIJJJJJJIJJIIJIJIIJIIIJJJJ)
	{
		return null;
	}

	public virtual void JIIIJJIIJJIJJJJJJJJIIJJIJIIJJJIIJJJJIIJIJJIIJII()
	{
	}
	public void JJJJJIIIIIIJJIJJJIIIJJIJJIJJJIIIIIJIJJJIJIJJJIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public float JJIIJIIJIJJIJIJJJJJJJJIIJJIIJIJIJJIJJJJIIJJIIII()
	{
		return 0f;
	}

	protected virtual void JIIIJJJIJJJJIJIJJJIJIJJIJIIIIIIJJJIJIIJIJIIIIIJ(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public virtual void IIJJJIJIIJIJIJJJIIIIIJIIJJJJIJJIJJJIJJJIJJJJIJJ()
	{
	}

	protected override void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	private void IIIJIIIJIIJIIIJIIJJJIIIJJJJJJIJIIIJJIIIJIJJJJJI()
	{
	}
	public void IIIIIIJIJJIJJJJJJJJIJJIJIJJIJIIJJJIJJIIIJJIIJIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public float JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII()
	{
		return 0f;
	}

	private void JJJIIIJJIIIIIJJJIJIIJJJIIIJIJJJJIIJIJJIJIIJIJJJ()
	{
	}

	public virtual void JIJJIJJIIJIIJIJIIJIJIIIIIIIJJIIIJIIIIJJIJJJIIJJ()
	{
	}
}
