using System;
using System.Runtime.CompilerServices;

public class TweenHeight : UITweener
{
	public int IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ;

	public int JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII;

	public bool JJIJIJJIJIIJJJJIJJIJJJIJJJJJIJIIIIJJIIJIIJJJJII;

	private UIWidget IJIJIJJIJJJJIIJJIJJIJIJJJIJJIIJJIIJIJIIIIJJIJJJ;

	private UITable IIJIIJIJIJIIJIIIIIJJIJIJJJIJIJJJIJJJJJJJJIIJJIJ;

	public UIWidget JJJJIIJJJIIJIIIIJIIIJIIJIJIIJIJJJJJIIJIJIJIJIII => JJJJIJJIJJIJIJIJIIJJJJIJJIIIIIIJIJJJJJJJJJJJJII();

	[Obsolete]
	public int JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII
	{
		get
		{
			return IJJJJIJJJIJIIIIIJJJIJIJIIJIJJJJJJJJJJIJIIJJJJJI();
		}
		set
		{
			JJJIJIIIJJJJIJIIIIIJIJJIJIJJJJIIJJIJJJIJJJJJJII(value);
		}
	}

	public int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI
	{
		get
		{
			return JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII();
		}
		set
		{
			JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(value);
		}
	}

	public virtual void IJIJIIIIJIIIIJJIIIIJJJJJJIIJIJJIJIJIJIIJIJJJIJI()
	{
	}

	public UIWidget JJJJIJJIJJIJIJIJIIJJJJIJJIIIIIIJIJJJJJJJJJJJJII()
	{
		return null;
	}

	public int IJJJJIJJJIJIIIIIJJJIJIJIIJIJJJJJJJJJJIJIIJJJJJI()
	{
		return 0;
	}

	private void JIIJIIJJIIIIJIJIIJIIIJJIJIIJIJIIIJIIIJJJIIIJIII()
	{
	}

	public override void JIIIIIIJJJJIJJIIIJIIJJIIIJJIIIJJIJJIIIJJIJJJIII()
	{
	}
	public int IIIIJJJJIIJIJJJJIJJIJJIIIJIIIJJIIIJJIIIJIIJIJJI()
	{
		return 0;
	}

	private void JJJJJJIJIJJJJIJIJIIIJIJIJIIIIIJJJJJIIJJIJIIIIII()
	{
	}
	public void IJIJJJIJIJJJIIIIJJJJIIIIJIJIJIJJIJJIIIJJJJIJJIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public override void JJJIIIIIIIJJJJJIJJJJIIJJJIIIIJIIIIJIJJJIJJJJJJI()
	{
	}
	public void JIJIIJIJIIIIJJIIIJJIJJJIIJIIJJJJIIIIJIJJIIIJIIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJIJIIIJJJJIJIIIIIJIJJIJIJJJJIIJJIJJJIJJJJJJII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJJIIJJIJIIIIJIIJIJJJJJIJIJJJIJIJIIIIJJJIJIIJJI()
	{
	}
	public UIWidget IIIIIIJIJIIIJIIJJJJIIIIJJJIJJJJIIJIJIJIJJIIJJII()
	{
		return null;
	}

	public virtual void JIJIJIJJJIIIJIIJIJIJIIIJIIIIIIJIJJIIIJIJJIJJJIJ()
	{
	}

	private void IJJIJJIJIJJIIIJJIJIJIIIIJJJIJIIIIIIIJJIIIJIIIII()
	{
	}

	private void JIIIIIIIIJJJIIJIIIJIJJJJIJIIJJIIJJIJJIJJJJJJIJJ()
	{
	}
	public void IJJJIJJJJJJJIJIJJIJIJIJJJIIJIIJJJIIIJIIJJIIJJIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected override void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public int JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII()
	{
		return 0;
	}

	public void JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static TweenHeight JIIIJIIIJJJJJJIIIIJIIJJIJJIIIIJIIJIIIIJIIJIJIII(UIWidget JJIJJJIIIIIIIJIIIIIJJIIJIJIIIJJJJIJIJJJIJJIJIJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, int JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
		return null;
	}
}
