using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class TweenFOV : UITweener
{
	public float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ;

	public float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII;

	private Camera IIIJJJIIJIIJIJJIJIJIIJJIIJIIJIJIJIIIJIJIJJIIJII;

	public Camera IIJIJJJIJJJJJIJJIIJIJIIJJJIIIIIIIJIIJJJIJJJJIJI => IJIIIIJJIJJJIIJJJJJJIJJIIIIIJIJJJIJIIIJJIIJIJJI();

	[Obsolete]
	public float JJIJIJIIIIJIIIIJJIJIJJJJJIIJJIIIIIJJJIJIJJJIIJI
	{
		get
		{
			return IJIJJIJJIIJIIIIJIJIIJIJIJIJJIJJJIJIIJIIIJIJJJII();
		}
		set
		{
			IJIIJIIIIIIIJJJJJJJIJIJIJIJJIJJJJIIJJIJIIJJJJJJ(value);
		}
	}

	public float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI
	{
		get
		{
			return JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII();
		}
		set
		{
			JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(value);
		}
	}

	public Camera IJIIIIJJIJJJIIJJJJJJIJJIIIIIJIJJJIJIIIJJIIJIJJI()
	{
		return null;
	}
	public Camera JJIJIJJJJJJJIJIJIIIIJIIIJJIJIJJJJIIIIIJJIIIIIIJ()
	{
		return null;
	}
	public void JJIIJJJJIJIJIIIJJJJIIJIIIIIIJIIJJIJIIIIIIIJIIJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJIJJIJIJJJJIJJJIJIIIIJIIJIJJIJIIJJJIIIJIJJJIIJ()
	{
	}

	private void JJJIIJJIJIIIIJIIJIJJJJJIJIJJJIJIJIIIIJJJIJIIJJI()
	{
	}

	public static TweenFOV JIIIJIIIJJJJJJIIIIJIIJJIJJIIIIJIIJIIIIJIIJIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII)
	{
		return null;
	}

	protected virtual void JIJJIJIIJJJIJIJIJIJIIIJIJIJJJIJIJJJIJJJJJIJIJIJ(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public virtual void JIJJJJJIIIIIIIIIJIJIIIIIIIIJJIJJJIIJIIIIIJIJJJI()
	{
	}

	public virtual void JIIJIJIJJJIIIJJIIIJIJJJIJIJIJJJIJIIJJIIJJIIIIIJ()
	{
	}

	public static TweenFOV IIIJJJJIIJIIJJJIJJIIIIJIJIJJIJIJIJJJJJIIJIIIJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII)
	{
		return null;
	}

	private void IIJIJIJJIIIJIJIJIJJIIIIIIJIJIJJIJIIJIJJIIIJIIJJ()
	{
	}

	public virtual void IJJIIIJJJIJJIIJJJIIJJJJIIJJIJIIJJJJIIJJJJIJJIII()
	{
	}
	public float JIIJJJJJIIIIIJIJIIIIIIIJJJJIJIIIJIIJIJJIIIJIJII()
	{
		return 0f;
	}

	protected virtual void IJIJIIJJIJJIJJIIIJIIJIIIIIIJJIJIIJJIIJIIJJJIJJJ(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	public void IJIIJIIIIIIIJJJJJJJIJIJIJIJJIJJJJIIJJIJIIJJJJJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJJJJJIJIJJJJIJIJIIIJIJIJIIIIIJJJJJIIJJIJIIIIII()
	{
	}

	public override void JJJIIIIIIIJJJJJIJJJJIIJJJIIIIJIIIIJIJJJIJJJJJJI()
	{
	}

	public float IJIJJIJJIIJIIIIJIJIIJIJIJIJJIJJJIJIIJIIIJIJJJII()
	{
		return 0f;
	}
	public float JJJJIJJJJIIIIIJJIIIIIIIIJJJJIJJJIJJIIIIIIJIJJIJ()
	{
		return 0f;
	}

	public override void JIIIIIIJJJJIJJIIIJIIJJIIIJJIIIJJIJJIIIJJIJJJIII()
	{
	}

	protected override void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}
	public void IIJJJIIJIIJIJIIIJIJJJJIIJJJJIIIIIIJIIJJIIJJJIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void JJJIJIJJJJJJIJIJIIIIJJIJJIIIJIJIJJJJIJIJJIIIJJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public float JJJIJIIJJJIIJJJJJIIIJJJIJIJJJJIIIJJIJJIIJJJJIIJ()
	{
		return 0f;
	}

	public float JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII()
	{
		return 0f;
	}
	public float IIJIIJJIJIJIJIIIIJIJJJJIIJIIIIJIIIJJIJIIIJIJIJI()
	{
		return 0f;
	}
	public void IIJIIJIIIIJJIJIIIJJJIIJIJIJJJIJIIIJIJIIJIIJIJJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void IIIJJIJJIIJJIJJIJJIJIJJJJJJJIJIIJJIJJJJIIIIIIII()
	{
	}
}
