using System.Collections.Generic;
using System.Runtime.InteropServices;
using UnityEngine;

public class TypewriterEffect : MonoBehaviour
{
	[StructLayout((LayoutKind)0, Size = 12)]
	private struct JIJIJIIIJIJJIIIJJJIIIJJJIIJJJIJIJJIJIJIJIIJIJII
	{
		public int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ;

		public string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI;

		public float IJIIJJIIJIJJJIJIJJJIIJJIIIJJJIIIJJJJIIJJIIJIIIJ;
	}

	public static TypewriterEffect JIIJIIIIIIIIIIJIJIIIJJIIJJJIIIJJIIIIIIIIJIJIJIJ;

	public int IIIJIJJJJIIIJIIJJIIIIIIIIIJJJIIIJJIJIJJJIIJIIJJ;

	public float IIJJJIJIIJIIJJJIIJJIJJJIIIIIIJJIJJJIJJIIJJIJIJI;

	public float IIIJJJIIJJIJJIIJIJIIJJIIIIJJJJIJJIIIIJIIIIIJIII;

	public float IIJIJJJJIJIJIJJJJJJJJIJIJJIIJIIIIJIIIJIJJIJJJJI;

	public UIScrollView IJJIIIIIJIIJIJIIIIIIIIJIJIIIJIIJIJJIIJIIJIJJIIJ;

	public bool JJJJJIIIJJJIJIJIIJJIIIJJJJIJJIJIJJJJIJIIJIJIIII;

	public List<EventDelegate> IJIIIIIJJIIJJJIIJIIJJIIIIIIIJIJIIJIIIJJJJJIIJII;

	private UILabel JJJJIIIIIJJJJJJJJJJIJIIJJJJJIJIJJJJJJIIJJJIIIJJ;

	private string IIIIJIJJIJIIIIIIIJIJJJJIIIJJIJIJIIJJJIIIIJIJJIJ;

	private int JJJIJIJIJIIIIIJIJJJJIJIIIJIJIIJIJJIJJIIJJIIJJJI;

	private float JJJJJIIIIJIJJIIJIIJJIJIIIJIIJJIJIJIJJIIIJJIIIIJ;

	private bool JIIIIJIIJJIJIIJJIIJIIJJIIJJJIJJJIJIJIJJJJJIIIJI;

	private bool JJIJJJJJJIIIIJIJJIIIJIJIJIJJIJJJJJIIIJIIJIIJJJI;

	private global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<JIJIJIIIJIJJIIIJJJIIIJJJIIJJJIJIJJIJIJIJIIJIJII> IIIJIIIIJJJIIIIJJIJJIIJJIJJIJIJJIIIJIIIJJIIJIJI;

	public bool JIJIJIIJJIJIJJJIJIIJIIIIJIIIJJIIIJJJJJJJJJIIIJI => JIIIIIIIJJJJIJIIIIIJIIJIJJIIIIJIJIJIJIIJJIJJJJI();

	private void JJIJIJIJJJJJIIJJIIIJJIJIIIJJIIJJJIIIIJIJJIIIIJI()
	{
	}

	public void IJIJJIJIJJJJJJIJJIJJIIJJIIIJJIIIIIIJJJJIJIJIJJI()
	{
	}

	private void JIIIJJJJIIIJJJIJJIJJJJIIIJIIIIIIJIIJIIIIIIJIJII()
	{
	}

	private void JJJIIIIIIIJJJIIJIIIIJJJJIIIIIIIIJJJJJJJIIIJIIJJ()
	{
	}

	public void JIIJIIIIJJIJJIIIJJIJJJIIJIJIJJIJIIIIIIJIJJIIJJJ()
	{
	}

	private void JIJIIJJIIIIIIIJJIJIJIJJJIJJIJIIJJIJJJIJIIIJIIJJ()
	{
	}

	private void JJIJJJIIJIIJIIJJJJJIIIIIJIIJIIIJIIJIJIJJIJJIJIJ()
	{
	}

	private void JIJIJIIIJIIJJIIIIIJJIJIIIIJJJIJIJJIJIJIIIIJIJJI()
	{
	}

	private void IIIJJJIJIIIJJIJIIJJIIIIJIIIJJJIIIIIJIIIJJIIJJII()
	{
	}

	private void OnDisable()
	{
	}

	public bool JIIIIIIIJJJJIJIIIIIJIIJIJJIIIIJIJIJIJIIJJIJJJJI()
	{
		return false;
	}

	private void JJJJIJIJIIJJJJIIIIJJJIIIIJJIIIJJIJJIIJIIIIIIJIJ()
	{
	}

	private void IIIIIJIIJJIIIIJIJIJIJJIIIIIIJIIJIIIIJJJJJJJIIJI()
	{
	}

	private void OnEnable()
	{
	}

	private void JIJJJJIIIJIIIIJIJJJJIIJJJIIJJIIJJJIIIIIIIJIIIJI()
	{
	}

	private void Update()
	{
	}
}
