using System.Runtime.CompilerServices;
using UnityEngine;

public class UI2DSpriteAnimation : MonoBehaviour
{
	public int IIJIJJJJIJJJIIIIIJIJJIJIIJIIIIIJJJJJJJJJIJIJJJI;

	[SerializeField]
	protected int framerate;

	public bool JIJJJJIIJJIIJJJJIJIIIJIJIIJJJJJIJIIIJJIJJJJIJJI;

	public bool IJIIIJJIJJIIJIJJIJJJIJIJIIJJIJJIJIJJIIIIIJIIIIJ;

	public Sprite[] IJIJIJIJIIJJJIJJJJJIJJJJIJJJIJIJJIIIIIJJIJIIJJI;

	private SpriteRenderer IJIIJJJJIIIIIJIJJIIIJIIJJIJIIJIJIJIIIIIIIJJJJII;

	private UI2DSprite IIJJIIIIJJJIJIIIJJJIJIIIIJJJIJJJIJIIIJIJJJIJIJI;

	private float JJJIIIJJJJJJIJIIIIJJJIIIJJJJIJIIIIIJIJIIJJIIJII;

	public bool JJIIIJIIIIJIIJJIIIJIJJIJJIIIJJJJJIIJIIJJIJIJIIJ => JJJJIIJJJIJJJJIIIJIIIIIJIIIIIIJIJJIIJJJJIIJJIJI();

	public int IIIIJIIIJIJIIIIJJJJIJJIJIIIIJIJJJJJIJJJIIIIIIII
	{
		get
		{
			return IJJIIIIJIIJJJJIIIJIJIJJJIJIJJIIJIIIIIIJIJJJIIJJ();
		}
		set
		{
			IIJIIJJJJJJJJIJIJIIJJJIIJJIJJJIIIIIIIJIJJJJJIII(value);
		}
	}

	public void IJJJIIJJJIJJIIJIJJJIJIIIJIJJIJJJJJIJIIJJIIIIJIJ()
	{
	}

	public void IJIJIJIJJIJIJIJIIJIJJJJIIJIJJIJJIJJJIJJIJIIIJIJ()
	{
	}

	private void Update()
	{
	}

	private void JIIJJJJIJIJIIIIIJJIIJJJIJJIIJJJJJJJIJIJJJIIJJJJ()
	{
	}

	public void JIJJJIIIJJJJIJJJIJJJJJIIIIJIIJJIJIIJJIJIIJIIIJJ()
	{
	}
	public int IJIJIIIIJIIJJJIIJIJIIIIIJIJIJJIIIJJJIJIIJJIJJII()
	{
		return 0;
	}

	public void JIJJIIJIIJJJJJIJIIJJIJIIJIJJIIJJIJIIIIIJJJIIIJJ()
	{
	}

	private void JJJIJJIJIIJIIJIIIJJJJIJIIJJJJJJIJJIJIIIIJJIIIII()
	{
	}

	public void IIIJJJIJJJJIJJJIIJIIJJJJJIJIIJIIIIIIIIJJJIJJJJJ()
	{
	}

	public void IJIJIJIJIIJJJIJIIJIJJJJJJIIJJIIIIIIJJJIJIIJJIJJ()
	{
	}
	public int JJIIIIIIIJJJJJJJJJIJJJIJIIJJJIJJIIIJIJJJIIIJJJI()
	{
		return 0;
	}

	public bool JJJJIIJJJIJJJJIIIJIIIIIJIIIIIIJIJJIIJJJJIIJJIJI()
	{
		return false;
	}

	private void IJIJIJIIIIJIIIJJIJIIJJJJIJJIJJJJIIIJJJIJIJIIJIJ()
	{
	}

	public int IJJIIIIJIIJJJJIIIJIJIJJJIJIJJIIJIIIIIIJIJJJIIJJ()
	{
		return 0;
	}

	private void IIIIJJJIJIIIIIIJIIIIIJJIIJJJJJIJIIJJIIJJIIJIIJJ()
	{
	}

	public void IJIJJIJIJJJJJJIJJIJJIIJJIIIJJIIIIIIJJJJIJIJIJJI()
	{
	}

	public void JJJJIJJJJIJIIIIJIJIJIJJJIJIIJIIIIJJIJIIJJJJIJII()
	{
	}
	public void JIIIIIIJIIJJIJJJJJIJIIIJIIJIJJJJJJJJIIJIIIIIJII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void Start()
	{
	}

	public void IJIIJIIIIIJJJIIJJJIJJJJIJJJJJIJIJJIJJIJIIIIIJIJ()
	{
	}

	public void IJJJIJJIJIIJJIIIJIIIJJJJJIJIIJJJIJJJIIIJIIIJIII()
	{
	}

	public void IIJIIJJJJJJJJIJIJIIJJJIIJJIJJJIIIIIIIJIJJJJJIII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJIJJJIJIJJJIIIIIJJIJIJJIIJJJIJJIJIIIIJJJIJIIIJ()
	{
	}

	private void IJIIJJJIIIIJJJJJJJIJJJJJIJIJIJIIJJJIJJIIIJJIJJI()
	{
	}

	private void JIJJJJIIIJIIIIJIJJJJIIJJJIIJJIIJJJIIIIIIIJIIIJI()
	{
	}
}
