using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class UI2DSprite : UIBasicSprite
{
	[SerializeField]
	[HideInInspector]
	private Sprite mSprite;

	[HideInInspector]
	[SerializeField]
	private Shader mShader;

	[SerializeField]
	[HideInInspector]
	private Vector4 mBorder;

	[HideInInspector]
	[SerializeField]
	private bool mFixedAspect;

	[SerializeField]
	[HideInInspector]
	private float mPixelSize;

	public Sprite JIIJJIIIJJJIJIJJIJJIJIJJIIIIIIIJJJJJJJJJJIJJJJI;

	[NonSerialized]
	private int IIIJJJIIIJJJJIJJJIJJJIIJJJIIIIIJIIJIIJJIJJJIJIJ;

	public Sprite JJIJJIIIJIJJIIJIJJJIJIJJJJJIJJIIIIJJIJJIJIJIJII
	{
		get
		{
			return JJIJJJIJIIIIJJIIIIIJJJJIJIJJJIJIIJIJIIJIIIIIIII();
		}
		set
		{
			JIIIIIJIJIIJJIIIIJJJJJIIJJIIJIIJJIIJIJIJIIJIJIJ(value);
		}
	}

	public override Material IJIIJJJJJIIIJJJJIIIJJJJJIJJIJIJJIIIJJIIJJIIIIII
	{
		get
		{
			return IJJIIIIJIIIJIIJIJIIJJIIJJJIJJJJIJJJJIIJJIJJIIII();
		}
		set
		{
			IJJJJIIIIJJIJJIIJIJJJJJIJIJJJIIJJJJIJIJIIJJIJJJ(value);
		}
	}

	public override Shader IJIJJIJJJIJIJIIIJIIIIJIIJJIIJIIIIIIIIIJJIJJJIJJ
	{
		get
		{
			return IIIIJIJIJJIIIJIJIIIJJJJJIJJJJIJJIJIJIIIIIJIJJJJ();
		}
		set
		{
			IJIIIJJJIJJIJIJIJIIIJIJIIIJIIJJJIIJJIJJIJIIJJIJ(value);
		}
	}

	public override Texture JJIJJJJJJIJJJJJIJIIJJIJJJJIIIJIIJJJJIIIJJIIIIJI => IJIIIJJIJIJIJIIJIIJIIIIJIIIJIIJIJIJIJJJIIJJJIII();

	public bool JJJIJIIIIJJJJIJIJIJJIIIJIIIJJJIIIIJIIIJIJIJIJJI
	{
		get
		{
			return IIJJJJIIJJIIIIJIJJJJJJIJJJIJJJJIJJJJJIJJIJIJIJI();
		}
		set
		{
			IIIIJIJJJJJJIJJJIJJIIIJIIIJJIIJIJIIJJIIJJIIJJJI(value);
		}
	}

	public override bool JIJJJIIJIIIJIJIJIIJIIIIJJIJIJIJIJIJIJJIJJJJIIJI => IIJIJJIJIIIJIIJIJJJJIIJIJIJJIIJIJIJIIJIIJIJIJJI();

	public override float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII => IJJIIJJJJIJIIJIIIJJIIIIIJIIJJIIIIJIJJJIJIIIJJII();

	public override Vector4 JJJIJJJJJIIIJIJJIIIJJJJIJJJIIIJJIIJIJIJIJIJIJII => JIJIIJIIJJJJJIJIIJJJIJJIJJIIIJJIIIIJIIJIJIJIIJI();

	public override Vector4 IJJJJJIIIJJIJJIIJIIJIJJJJJIIJIIIIJIIIJIIJJIJIJI
	{
		get
		{
			return JJIIIIJJJIJIIJIJIIJIJIIIIIIJJIIJIJIJIIJIJIIJIJJ();
		}
		set
		{
			IIIIJJJIIIJIJJJJIIJIJIIIIIIJJIJJIIJJIIIJIJIIIIJ(value);
		}
	}
	public bool IJIIJJIJJIJJIIJIIJJIIJJIIIJJIJIJIJJIJJJJJIJIJJJ()
	{
		return false;
	}

	protected override void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII()
	{
	}

	public override void JJIIJJIIJIJJJJIJIJJIIIJJJIIIJIJJJJJIJIJJJIJJJIJ(List<Vector3> IJJIIJJIIJIJIJIIIIIJIJIIJIJJJJIJIJIIJJIIIJJIJIJ, List<Vector2> IJJJIIJJJIJIJIIIJJIJIJIJIJJJJIIJIJJIJIJIJJIIJJJ, List<Color> IJIJIJJJJJJJIIIIJJIIIIJJJIIJJJJIJIJJJJIIJIJIJII)
	{
	}
	public virtual Vector4 IIJJJIJIJJIJIJIIJJJIIIJIJJJJIJJJIJJJIJJJJIJJIJI()
	{
		return default;
	}

	public override bool IIJIJJIJIIIJIIJIJJJJIIJIJIJJIIJIJIJIIJIIJIJIJJI()
	{
		return false;
	}
	public virtual float IJIJIJIJJIIIJIIIJJIJJJJIIJIIIIIIIJIIJIJJIIIJIII()
	{
		return 0f;
	}
	public virtual Texture IIIIIJIIJJJJIIJJJJIIJJJJJIIJIJIIIJIJJJJJIJJJIII()
	{
		return null;
	}
	public virtual void JIIJIJIJIIJJJJIIJJIJIIJJJIIJIIIIIIJIJIJJJJIJJII(Shader JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void IIJIIIJIJJJJIIJJIJIJJIJIIJJIIIIIJJJIIJIJJIJIIJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public override void IJJJJIIIIJJIJJIIJIJJJJJIJIJJJIIJJJJIJIJIIJJIJJJ(Material JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public override void JIIIJIIIIIJIJIJJIIIIIJIJIIJIJIJIIIIJIJIIIIJIJJI()
	{
	}
	public void IJIIIJJJIIJIJIJIIJJIIIIJIJJJJIIJIIIIIJJIJIJIJIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public virtual void JJIIIIJIIIIJIJJJIJIJJIJJIIIIJIJJJIIIJJIJJJIJJJJ(Material JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public override Vector4 JIJIIJIIJJJJJIJIIJJJIJJIJJIIIJJIIIIJIIJIJIJIIJI()
	{
		return default;
	}
	public virtual Vector4 IIJJJJIIIJIIJIJIJIJJJJJJJJIIJJJJJJIJJIIJJJIJJJJ()
	{
		return default;
	}

	public void IIIIJIJJJJJJIJJJIJJIIIJIIIJJIIJIJIIJJIIJJIIJJJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public Sprite JIJJJIIJIJIJIIIJIIJJJJIIIJJIIIJJJIIIJJJJJIJIJJI()
	{
		return null;
	}
	public virtual Texture JIIIIIIIJIIIIIIJJJIJIIIIJIIJJIJJJIIJIIJIJJIIIII()
	{
		return null;
	}

	public override Texture IJIIIJJIJIJIJIIJIIJIIIIJIIIJIIJIJIJIJJJIIJJJIII()
	{
		return null;
	}
	public virtual float JJJIIIJJJIIIIJIIJIIIJIJJJJIJIIJIJIJJJJJIIJIJJJI()
	{
		return 0f;
	}

	public override void IIIIJJJIIIJIJJJJIIJIJIIIIIIJJIJJIIJJIIIJIJIIIIJ(Vector4 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public override Vector4 JJIIIIJJJIJIIJIJIIJIJIIIIIIJJIIJIJIJIIJIJIIJIJJ()
	{
		return default;
	}

	public override Material IJJIIIIJIIIJIIJIJIIJJIIJJJIJJJJIJJJJIIJJIJJIIII()
	{
		return null;
	}

	public override float IJJIIJJJJIJIIJIIIJJIIIIIJIIJJIIIIJIJJJIJIIIJJII()
	{
		return 0f;
	}

	public void JIIIIIJIJIIJJIIIIJJJJJIIJJIIJIIJJIIJIJIJIIJIJIJ(Sprite JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool IIJJJJIIJJIIIIJIJJJJJJIJJJIJJJJIJJJJJIJJIJIJIJI()
	{
		return false;
	}

	public override Shader IIIIJIJIJJIIIJIJIIIJJJJJIJJJJIJJIJIJIIIIIJIJJJJ()
	{
		return null;
	}

	public override void IJIIIJJJIJJIJIJIJIIIJIJIIIJIIJJJIIJJIJJIJIIJJIJ(Shader JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public virtual Texture JJIIIJJIIIIIJIJJJIIIJIJIIJJIJJJIIIIJIJIJIJIIJJI()
	{
		return null;
	}

	public Sprite JJIJJJIJIIIIJJIIIIIJJJJIJIJJJIJIIJIJIIJIIIIIIII()
	{
		return null;
	}
	public void IJJIJJJJJIIJIIIIJIIIJJJIIJIJIJJJIIJJIIIJJIJJJII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public virtual void JIIJJIJJIJIIIIJIIIIJJIIJIJJIJIJIJIIIIJIJJJJIJII(Vector4 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual void JJJJIJIJJJIJIIJJJJJJJIIIJJIJJJIIJJIJJIJJJIIIJIJ()
	{
	}
	public virtual Vector4 IJJIJIJJJIIJIIIIIJJIJIIJIJIJJJIIJJJIJIJIJJIIIJI()
	{
		return default;
	}
}
