using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class UIAtlas : MonoBehaviour, IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII
{
	[Serializable]
	private class JJJJJIJIJJIIJIJIJJIJJIJIJIJJIIJJJJIJIJJJJJJJIJJ
	{
		public string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ;

		public Rect JJIJJIJIIIIIIJJJIIJIIJJIJJJIIJJJIIIIJJIJJIIIJJI;

		public Rect IJJIJIIJJIIIIJJIJJIJJJJIIJIIJIIIIIJIJJJIIJJIJII;

		public bool JIIJIJIIJJJIIJJJIJJIIIJIJIJIIIJJIIJIIIJJJIJIJII;

		public float IIIIJJJJIJIJIIJJIIIIJJIJJJJJIIIJJJJIIJIJIIJIJII;

		public float JIJJJJJJIJIJJJJIIJIIIJJIIIJIJIIIIJJJIIIIIJJJJII;

		public float IIIIJIIIIJJJJIIJJIIJIJIJJIIIJJIJIIIIJJJIIJIIJJI;

		public float JIIIIIJIJJJIIJIJIIJJJJJJIIJJIIIIJIJJJIIIJJIJJJJ;

		public bool IIJIJIIIIJJIJIIJJIJIIIIIJJJIIJIIJIJIJJJIJIIIJIJ => IIIIIIJIJIIJJIIJIJJIJJJJJIIIIIIJJJIJJJJIJIJIJIJ();
		public bool IIIJIJIIIIIIJIIJIJJIJJJIIJIIIIIJJIIIJJJJJJJJIJJ()
		{
			return false;
		}
		public bool IJIIIIIJJIIJJIJJIIJIIIJIJIIJJJIIJJJJJIIJJJIIJJJ()
		{
			return false;
		}
		public bool IIJJIIIIIJJIIIIJJIJJJJIIJJJIIJJIJJIJIIIJIIJIIJJ()
		{
			return false;
		}
		public bool JJJJJJJIIIJIIIIIIJIJJJIIIIJIJIJJIIIJIIIIJIIIIJI()
		{
			return false;
		}

		public bool IIIIIIJIJIIJJIIJIJJIJJJJJIIIIIIJJJIJJJJIJIJIJIJ()
		{
			return false;
		}
		public bool JJJIJJIIIJIIIJJJIJJJIJJIJJIIIIJJIJIIJIIJIIJIIJI()
		{
			return false;
		}
		public bool IJIIIIJJIJIIJJJIJJIJJJJJIJJJIJIJJJJJIJJIJIJIIJJ()
		{
			return false;
		}
		public bool JIIIJJIIJIJIJJJJJIIJIJIJIJIIIIJJIIJJIJJJJJIIJII()
		{
			return false;
		}
		public bool IIJJIIJJJJIJJJIIIJJIIJJIIIJJIJIJIIIIIIIJIIJJJJJ()
		{
			return false;
		}
		public bool JIJIJJIJIJIIJJJJJJIJIJIJJJIJIIJIIIIJJJIJIIJIIJI()
		{
			return false;
		}
		public bool JIIJJJJJIIJIJJIJIIJJJJIIJIJIIIJJJJJJIJIIJJJJJIJ()
		{
			return false;
		}
		public bool IIJIIJIIIJIIIIJIIIJIIJJJIIIIIJIJIIIJJJJIJJIJIJJ()
		{
			return false;
		}
		public bool JIIIJIIIJIIJIJIIIJIJIJJIIIIJJIJIIJIIIIJIJIJJJII()
		{
			return false;
		}
		public bool JIJIIIIIJJJJJJIJIIJIIJIIIIJJIJJJJIIIJIIJJIIJIJJ()
		{
			return false;
		}
	}

	private enum IJIJJJJIJIIJIIJIJIIIJIIIIJJJIIIJJJJJJIJIJIJJIII
	{
		Pixels = 0,
		TexCoords = 1
	}

	[SerializeField]
	[HideInInspector]
	private Material material;

	[HideInInspector]
	[SerializeField]
	private List<IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ> mSprites;

	[HideInInspector]
	[SerializeField]
	private float mPixelSize;

	[HideInInspector]
	[SerializeField]
	private UnityEngine.Object mReplacement;

	[SerializeField]
	[HideInInspector]
	private IJIJJJJIJIIJIIJIJIIIJIIIIJJJIIIJJJJJJIJIJIJJIII mCoordinates;

	[HideInInspector]
	[SerializeField]
	private List<JJJJJIJIJJIIJIJIJJIJJIJIJIJJIIJJJJIJIJJJJJJJIJJ> sprites;

	[NonSerialized]
	private int IIIJJJIIIJJJJIJJJIJJJIIJJJIIIIIJIIJIIJJIJJJIJIJ;

	[NonSerialized]
	private Dictionary<string, int> IIJIJJJJIIIJJJJJJJIIIJJIJJJIJJIIIJIIJJJIIIIIIII;

		public Material spriteMaterial
	{
		get
		{
			return null;
		}
		set
		{
		}
	}

	public bool premultipliedAlpha => false;

	public List<IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ> spriteList
	{
		get
		{
			return null;
		}
		set
		{
		}
	}

	public Texture texture => null;

	public float pixelSize
	{
		get
		{
			return 0f;
		}
		set
		{
		}
	}

	public IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII replacement
	{
		get
		{
			return null;
		}
		set
		{
		}
	}

	public Material IIJJJJJJIJJIIIJIIJJIJIIJJJIJIJJIIIIIJIIJJIJJJII
	{
		get
		{
			return spriteMaterial;
		}
		set
		{
			spriteMaterial = value;
		}
	}

	public bool JIJJJIIJIIIJIJIJIIJIIIIJJIJIJIJIJIJIJJIJJJJIIJI => premultipliedAlpha;

	public List<IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ> JJJIIIIJIIJJJJJIIIJIIIJJIIJJIIJIJJIJIJIIIIJJJJJ
	{
		get
		{
			return spriteList;
		}
		set
		{
			spriteList = value;
		}
	}

	public Texture IIJIJIIIJJJIIIJJIIJJIJIIIIIIJJJIIJIJIJJIIIJIIIJ => texture;

	public float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII
	{
		get
		{
			return pixelSize;
		}
		set
		{
			pixelSize = value;
		}
	}

	public IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JJJJJJIJJIJJJIIJIIIIJIJJJJJJJIJIJIJIJJIJIIIJJII
	{
		get
		{
			return replacement;
		}
		set
		{
			replacement = value;
		}
	}

	public void IIIJIIJJJJIIJJJIJJJJIIIJJJIJJJIIIIJIIIJJJJIIJJJ()
	{
	}



	private bool JJIIIJIJIJJIJJJIJIIJJJJJJIJIIJIJJJJIJIIJJJIJJJI()
	{
		return false;
	}

	public void IIJIIIJIJIJJJJIJJIIJIIJJIIJJJJJIIIIIIJIJIJIIIIJ()
	{
	}
	public void JJIJJIIJIJIJIJJIJJJJIIJIJIJJIJIJIJJJIIJIIJJIJJJ(Material JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIIIIJIIJIJJJJIIIIIJJIJJJIJJJIIJIJJJJJIIJJIJJI()
	{
	}

	public void JIIIJIJIJJIJIJJJJJJIJIJJJIIJJJIJIIJJIJJJIJJJIIJ()
	{
	}


	public void IJIIJJJJIJJIJIJIIJJIIIJJIIJJIIIIIJIIJIJJJJIJIII()
	{
	}



	public IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ JIJJIJJIJJJIJJIIIIIIJIJIJIJJIJIJJIJJJIIIIIIJIII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
		return null;
	}
	public List<IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ> JIIJJIJIIJJJIJJIJIIJJJIIJIIJJJJIIIJJJIJIJIIJJJI()
	{
		return null;
	}

	public void IIJJIJJIJIJJJIJJIJIJIJJIJIJIJJJJJIJIIJJIIJIIJII()
	{
	}

	public global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<string> JIJJJIJJIJIJIIJJJIIJJIJIIJIJIIIIIIIJIIJJJJIJIJJ(string IIJJJIIIIIIIJJIIIJJJJJJIIJIIIJJIIIIIIJIJJJJJIJI)
	{
		return null;
	}

	public global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<string> JIJJJIJJIJIJIIJJJIIJJIJIIJIJIIIIIIIJIIJJJJIJIJJ()
	{
		return null;
	}





	public IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ JJIJJIJIJIJIJJIJIJJJIIIIJIJIIIJIIIIJIIIJJIJIIIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
		return null;
	}

	public IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ JIJIJIIIJIJIJIIIJJJIJIIJJIIJJIIIJJJJIJIJJJIJIII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
		return null;
	}

	public IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ JJJJIJJIIIIIJIJJIJJJJIJIIJJJJIJJIJIIIIJIJIJIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
		return null;
	}

	public bool IIJJIIIIIJJJIJJJJJIIJJIJIIJIJIIIJIJJJJJIJJJJIJJ(IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JJJIIIJJJIIIIIJIJIJJIIIJIIIIIIIJIIIJIIIIIIJJJJI)
	{
		return false;
	}

	private bool JIJIIIIIJJIIIJIIIIIIJJIIIIIIJJJIIIJJIJJIIJIIJJJ()
	{
		return false;
	}

	public void IIJJJJJIIJJIJJIIIIJIIIJIIJJIIIJJJJJIIJIJJIIIJIJ()
	{
	}
}
