using UnityEngine;
using UnityEngine.UI;

[ExecuteInEditMode]
public class UIBlur : MonoBehaviour, IMaterialModifier
{
	[SerializeField]
	private float blurSize;

	private Material IIIIJIIJIJIIIJJIJIIJIJJIJIIIJJJJJJIIIJIIJJJIIJI;

	private void JIJJJIIIIIIJJIIIIIJJIIIJJIJIJJJJJJJJIJIJIIJIJII()
	{
	}

	private void JIJJJJIIIIJJJIIIJJIJIJJJIJIJJJIIIIIIJIIIJJJJIIJ()
	{
	}

	private void IIIJJIJJJJJJJJIIJJIJJJIJJIIIIJIIIJJIIIIIIJJJJJJ()
	{
	}

	private void JJIJJJIIJIIJIIJJJJJIIIIIJIIJIIIJIIJIJIJJIJJIJIJ()
	{
	}

	private void OnEnable()
	{
	}

	private void IJIJJJJJIIJIIJIJIIIJJJIIIJIJIJIJJIJIJJJJJIJJJJJ()
	{
	}

	public Material JJIJJJJIJIJIJJIIIIIIIJJIIJJIJJJJIJIJJJJIJIIIIIJ(Material IJIJIJIJIIJJJJJJIIJJIJJJJIIIIIIJJJIIIJJJIJIJIJI)
	{
		return null;
	}

	public Material IJJIJIIJIJIJJJIIIJIJIIJIIIJIIJJIJJJJIIIIIJIJJJJ(Material IJIJIJIJIIJJJJJJIIJJIJJJJIIIIIIJJJIIIJJJIJIJIJI)
	{
		return null;
	}

	private void JJJIJIIJJIIJJJIIIJJIIIJJJIJJIIJJIIIJIIJJIJIJJJJ()
	{
	}

	private void JIJJJIIIIIJIJJIIJIJIIIIJIJIIJIIIIJJJIIJJJIJJJIJ()
	{
	}

	private void JJJIIIIJIIJJIIJIIIJJJIIJIIIIIJIJJIJIIIIJIJJIIJJ()
	{
	}

	public Material IIIIIJIIJJJIJJJJIJIJJIJIJIIJIJJIJJJJJIJIJJJIJII(Material IJIJIJIJIIJJJJJJIIJJIJJJJIIIIIIJJJIIIJJJIJIJIJI)
	{
		return null;
	}

	private void JJJIIIIIJIIJJIJIJJJJIIJIIIIIIJJJJJJIJIJIIJJJIJJ()
	{
	}

	private void JJJIIIIIIIJJJIIJIIIIJJJJIIIIIIIIJJJJJJJIIIJIIJJ()
	{
	}

	public Material GetModifiedMaterial(Material IJIJIJIJIIJJJJJJIIJJIJJJJIIIIIIJJJIIIJJJIJIJIJI)
	{
		return null;
	}

	private void JJIJJJIIJIJIJIJIJJJJJIIJIJIIIIJJIIIJIIJJJJJIJIJ()
	{
	}

	private void IIJJJIJIIIJIIIJJJJIIIIJIJJIJIIIIJJJIIIJIIIIIJII()
	{
	}

	public Material IIIIJJJJJIIIJIJJIJIJJIIJIIJIIJJIJIJJIJIIJIIJJJI(Material IJIJIJIJIIJJJJJJIIJJIJJJJIIIIIIJJJIIIJJJIJIJIJI)
	{
		return null;
	}

	private void Update()
	{
	}
}
