using System.Runtime.CompilerServices;
using UnityEngine;

public class UIButtonPosition : MonoBehaviour
{
	public string IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ;

	public bool JJJIIIIJJIIJIJIIJJIJJJJJJIJIJJIIJJIJJJJIJJJJIII;

	public Vector2 IJJJJJJIJIIIJJIIIJIJIJJIJIIIJJIJJJIIJJJJJIIJIII;

	private Vector3 IIIJIJJJIJIJJJJJJIIJIIJIJJJJIJJIIJJIJIJIIJJIIIJ;

	private Vector2 JIJIIIJJJIJJIJJIIIJIIJIIJJJJJJIJIIJJJIJIJJIIJII;

	private UISprite JIIIJIIJJIIIJIJJJJJIJIIJIJIJJIIJIJJJIIJJJJJJJIJ;

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void JJIJJJIIIJJIIIIIJIIIIIJJJIIJIIIJIJIJIIIIIIJIJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JJJIJIIIJIIJJJJJJIJJIJJIIJIJJIJIIIJJIIIIJJJJJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void IIIIIJIIIJIJIJJJIJIJIJIJIIJJIIJJIIIJIIJIIJJIIIJ()
	{
	}

	private void JIJJJIJJIIJIJJJJJJJJJJIJIJJIIIIJIIIIIJIIJIJJIIJ()
	{
	}

	private void JJJJIJIJJJIIIJIIJIJJJIIJJIJIIJJJJJJIJIJIJIJJIJJ()
	{
	}

	private void JIIIIJIIJJJIIJIJJJJIJIIJIIIJIJJIJJIJJJJIIJIIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void IJIJJIIIIIJIJIJIIJJIIJJJJIIIJIJIIJJJJIIIJJIIJII()
	{
	}

	private void IJJJJIIIIJJIIIJJIJJJJJJIJIIJJJJJJJJIJJIIJIIIJIJ()
	{
	}

	private void JJIJJJIJJIJIJIIJJIJIIIIJJJJIIIJJJIJJJJIJJJJIJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	[CompilerGenerated]
	private void JIJJJJJIJJJIIIIIJIIJJJIJIJJIIIJJJIJJJIIJIJIJJJI()
	{
	}

	private void JJIIJJIJJJJJIJIJIJJIIJJJIIIIIIJIJIJIIIIJIIJIJII()
	{
	}

	private void OnEnable()
	{
	}

	private void JJJIIIIIJJJJJJIIJJIJIIIIJJIIIIIJJIIIIIJJIIJIJJJ()
	{
	}

	private void IJIIIJIIJJIJIJIIJJIJJJJIJJIIIJIJIJJJIJJIIIIIJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void JJIJIIJJJJJIIJIJIJJIJIJJJJIIJIIJIJIIJIIIIIJJJJI()
	{
	}

	private void IIJIIJJIJIJIJJJJJJIJIJJJIIJJIIJIJIIIJJJJIJIJJIJ()
	{
	}

	private void Start()
	{
	}

	private void IJJIIIIIJIJJJJJIJJIIJJIJJIJJJJIJJJIIIIJJJJIJIJI()
	{
	}

	private void JJIIIJIIJJIJJJJJJIJIJIIIJJIJIJJJJIIIJJJIJJIIJJJ()
	{
	}

	private void OnDisable()
	{
	}

	private void IJIIJIJJIIJIJJJIIIJIIIIJJJJJIJIJJIIJIIJJIIJJIIJ()
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void JJIIJIIJIIJIJJIIJIJJIJJIJIJIIIJIJIIIJIJJIIJIIJI()
	{
	}

	private void JIIJJJJJJJIJIJJIJIJIJJJIIIJJIIJIIJJIJJIIJIIIJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JIJIIJIJIJIJIJIJIIJIIIIIIJJIJIIIIIIIIJJIJJIIJJJ()
	{
	}

	private void JIIIJJJJIIIJJJIJJIJJJJIIIJIIIIIIJIIJIIIIIIJIJII()
	{
	}

	private void JIJIIJIJIJIIIJIIJJIIJIJJJJIIJIJIIJIJJIJIJJJIJII()
	{
	}

	private void JJJIIIIIIJJJJJJJJJJJJIJJIJJJIIJIIJJJJJIIIIIJJII()
	{
	}
}
