using System;
using UnityEngine;

public class UIButtonOffset : MonoBehaviour
{
	public Transform IIIJJJJJIJJJIIIIIIIIIIJIIIIJJJJIJIJJJJJIIJJJJII;

	public Vector3 IIIIJJJJJJJIJIIIJIJJJIJIIJIIJJJIJJJIIIJIIIJIIII;

	public Vector3 IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI;

	public float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ;

	[NonSerialized]
	private Vector3 JJIIIJJJIIIJIIIIJIJIIJIIJJIIJJIIJJIJIJJJJJIIJII;

	[NonSerialized]
	private bool IIJJIJIJJIJJIJIJIJJJIIIJJJIJJIIIIJJJJIJIJIIJIJI;

	[NonSerialized]
	private bool IJIJJJIIJIIJJIJJIIJIIIJJIJJJIJJJJIIIIJJJIJJJJJI;

	private void JIJIJJIIJIIIJJJJIIJIIJIJJJJIIJJIJJIIJIIJIIJJIIJ(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void JJIIIJJJJJJIJJJJJIJIJJIIIJJIIIIIIIJJIIIJIIIJIJI(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void JIJIJIJJIIJJJJJIIJJJIJJJJJJJIJJJIIJJIIIIIJJJJIJ()
	{
	}

	private void JIJIJJIJIJJIIJJJIJIJJIIIJIJJJJJJJJJIIJIJJJJIIJJ()
	{
	}

	private void Start()
	{
	}

	private void IIJJJIIIJIJIJJJJIIJIJIJIJJJJJIJIJJJJJJJIJJIJJII(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void JIJIJJJJIJIIIJJJIIIIIIJIJJJJIJJJIIIJIIIIIJJIJII(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void JIIJJIIJJIIJJJIIJIIIJIJJJJIJIIIIIIJIIIJIJIIIIIJ()
	{
	}

	private void IJJJJIIJJJIIJJIJJJIIIIIJIJIIIJJJIJJIIJIIJJJIIII()
	{
	}

	private void JIIJIIIIJJJIIIIIIJJIIIIIIJJJIJJJJJIJIJJIIIIIIJI(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void JJJIIJIJJJIIIJIJJIJIJJIJJIJIJJJIJJIJIJJIIJIJJIJ()
	{
	}

	private void JIJJIJIIJJJIJJIIJJIJJIJIJIIJIIIJIIIJIIJIIIJIJJI(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void JJIJIJIIIJIIIJIJJJJIIIIJJIJJJJIIIJIIIJIJIIIIIII()
	{
	}

	private void JJJJJIJJIIJJJJIJIIIIJIJJJJIIIIIJIIIJIJJJJIJJIII()
	{
	}

	private void OnEnable()
	{
	}

	private void IIIIJIJIIJIIIJIIJJJJIIJJJIIIJJIIJIIJJIIJJJIJIJJ(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void JJJIJJJIIIIJJIIJIIJJJIJIIIIIJJIJJIIIIJJIIJIJIIJ(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	private void OnDisable()
	{
	}
}
