using UnityEngine;

public class UIButtonScale : MonoBehaviour
{
	public Transform IIIJJJJJIJJJIIIIIIIIIIJIIIIJJJJIJIJJJJJIIJJJJII;

	public Vector3 IIIIJJJJJJJIJIIIJIJJJIJIIJIIJJJIJJJIIIJIIIJIIII;

	public Vector3 IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI;

	public float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ;

	private Vector3 IJJIIJJIIJIJIJIIIJIIJIIIIIJIIJIIIIJJIJJIJJIIIJJ;

	private bool IIJJIJIJJIJJIJIJIJJJIIIJJJIJJIIIIJJJJIJIJIIJIJI;

	private void JIJIJJIIJIIIJJJJIIJIIJIJJJJIIJJIJJIIJIIJIIJJIIJ(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void IJIIJIJIIJJJJJJIJJJIJIJIJJJJIJJJJJJIJIIIIJIJJII(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void IIJJJIIIJIJIJJJJIIJIJIJIJJJJJIJIJJJJJJJIJJIJJII(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void IJIIJIIIIJJIIJJJJIJJIIIJIIIJIJIIIIIJIJJJJIIJJJJ(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void OnEnable()
	{
	}

	private void IIJJJJJIIIIJIJIIIJIIJJJIJIIIJJIJJIJIJIJIIIJIIJI()
	{
	}

	private void JIJJJJIJIJIJJIJJJJJIIJIJJIIIJIIJIIIJJIJJJJIIJIJ(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	private void JJJIIIJIIJJIJIJIJIIJJJJJJJJJIIIIJJIIJIIIJJIIIII(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void IIJJJIJIIIJIIIJJJJIIIIJIJJIJIIIIJJJIIIJIIIIIJII()
	{
	}

	private void Start()
	{
	}

	private void JIIJIIIIJJJIIIIIIJJIIIIIIJJJIJJJJJIJIJJIIIIIIJI(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void IIIJIJJIJJIJIJIJIJIIIIJIIJJIIIJJJIJJJJIIJIIJIIJ()
	{
	}

	private void OnDisable()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}
}
