using UnityEngine;

public class UIButtonRotation : MonoBehaviour
{
	public Transform IIIJJJJJIJJJIIIIIIIIIIJIIIIJJJJIJIJJJJJIIJJJJII;

	public Vector3 IIIIJJJJJJJIJIIIJIJJJIJIIJIIJJJIJJJIIIJIIIJIIII;

	public Vector3 IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI;

	public float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ;

	private Quaternion IIIIIIJJJIIIJJJIJIIJIIIIJIJJJIIJIJJIIIIJIJIIJJJ;

	private bool IIJJIJIJJIJJIJIJIJJJIIIJJJIJJIIIIJJJJIJIJIIJIJI;

	private void IIIIIJIIJJIIIIJIJIJIJJIIIIIIJIIJIIIIJJJJJJJIIJI()
	{
	}

	private void IIJJJIIIJIJIJJJJIIJIJIJIJJJJJIJIJJJJJJJIJJIJJII(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void JIIJIIIIJJJIIIIIIJJIIIIIIJJJIJJJJJIJIJJIIIIIIJI(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void Start()
	{
	}

	private void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	private void JIJIIJJIIIIIIIJJIJIJIJJJIJJIJIIJJIJJJIJIIIJIIJJ()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private void IJJIJJIJIJIJJIIJJIIIJIJIIJJJIIIIJIJJJJJIJIIIJJI(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	private void IIJJIJJIJIIIIJJIJIJJIJIJIJJJJJJJIJIJIJJIIIJJIJJ(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	private void IIIIJJIJJIJIJJIJIIIIJJIJIJJIIIJIJIJJIJJIJJIIJII(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void IJIJJJIIJIIJIJJIJIJIIIJIJIJJIIIIIIJJIJIJIJIJIJJ()
	{
	}

	private void JIJIJIIIJIIJJIIIIIJJIJIIIIJJJIJIJJIJIJIIIIJIJJI()
	{
	}

	private void JJJIIIIIJIIJJIJIJJJJIIJIIIIIIJJJJJJIJIJIIJJJIJJ()
	{
	}

	private void JJJIIJIJJJIIIJIJJIJIJJIJJIJIJJJIJJIJIJJIIJIJJIJ()
	{
	}

	private void OnEnable()
	{
	}

	private void IIIJJIJJJJJJJJIIJJIJJJIJJIIIIJIIIJJIIIIIIJJJJJJ()
	{
	}

	private void JIJIJJIIJIIIJJJJIIJIIJIJJJJIIJJIJJIIJIIJIIJJIIJ(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void IIIIJIJIIJIIIJIIJJJJIIJJJIIIJJIIJIIJJIIJJJIJIJJ(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void OnDisable()
	{
	}
}
