using UnityEngine;

public class UIButtonMessage : MonoBehaviour
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JJJIJIIJIJIIJIJIIIJIJJIIJIJIIIJJJIIIJIIIJJIIJJJ
	{
		OnClick = 0,
		OnMouseOver = 1,
		OnMouseOut = 2,
		OnPress = 3,
		OnRelease = 4,
		OnDoubleClick = 5
	}

	public GameObject IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

	public string JIIIJJJIIJIIJIIJIJJIJIJJJJJJIIJIJJIJIJJJJIJIJII;

	public JJJIJIIJIJIIJIJIIIJIJJIIJIJIIIJJJIIIJIIIJJIIJJJ IIJJIJJIJIIIIIIIIIJIIJJJJIJIJIJIIIJIJJJJJIIJIII;

	public bool JJJJIJJJIJIJJJIJIIJIIJJIJIJIIJIJIIIIIJIJJIJIIJJ;

	private bool IIJJIJIJJIJJIJIJIJJJIIIJJJIJJIIIIJJJJIJIJIIJIJI;

	private void JJJIIIIJJJJJJIJJIIJIIIJJJJJIIJJIIIJJIIJJJIIIJJJ(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void JIIIJJJIJIJJJJJJJIJJIJJJJIIIIJJJJIJIIIIJJJJJJJJ(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void OnEnable()
	{
	}

	private void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void JIIIJIIJJIJIJIJIJJJJIIJJJIIJJIIJJJJJJJJIJJIIIIJ()
	{
	}

	private void IIIIJIJJIJJJJIJIIJIJJIJJIJIJIJJIJIJJJJIIIJJIJJI(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void JJJJJJIIJJJIIIJIJIJIJJIIIJIJIIIIJJJJJIJJJJJJIJI(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void JJIJIJJIJJJIJIIIIJIIJIIIIJIJJJJIJJIJIJJIIJIIJJI()
	{
	}

	private void JIIJIJIJJJIJIIIIIIJJIIJJJJJJJJIIIJJJIIIJJIJJJJJ(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void Start()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void JJIJJJIIIJIJJJIJIIIIJIIJIJIJJJIJJJJJIIJIIIIIIJI()
	{
	}

	private void IIJJJIIIJIJIJJJJIIJIJIJIJJJJJIJIJJJJJJJIJJIJJII(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void JJJJIIJJJJJIJIIIJIIJJJJJJIIIIIJIIJIIJJJJJJJIJIJ(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void IIJJIJIJJJJJIJJIIJIJIJJIIJIJIIJJIIIJJIIIJIIIJJI()
	{
	}

	private void IJIIJJJJJIIJIJIJJJJJIJIJIJJJIIIIIIIIJIIJJJIJIII(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	private void JIIIJJIIJIIJJIJJJJIJJJIJJIIIJJJIIIJIIIIIIJJIIII()
	{
	}

	private void JIIJIIIIJJJIIIIIIJJIIIIIIJJJIJJJJJIJIJJIIIIIIJI(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void IJIIJJJJJJJIJIJIIIJJIJJIJJIIIJIIJJIJIIIJIIJJIJI(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void IJIIJIIIIIIJIIJJJJIIJJIJIIIIIIJJJIJJJIIIJIJIIIJ()
	{
	}

	private void OnClick()
	{
	}

	private void JJJJIIIIJIIIJIJIIJIIIJIIIJIIJJJIIJJJJJJJIJJIIIJ(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void JJIIJIJJIJIIIJJIJIIIJJIIIJIIIJIIIJJJJJIIIIJIJIJ(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	private void JIIIIJIIJJJIIJIJJJJIJIIJIIIJIJJIJJIJJJJIIJIIIJJ()
	{
	}

	private void JJIIJJIIJJIIIJIJJIJIJJJJIJJJJJJIJJIIJIIJJJJIJII()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}
}
