using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class UIButton : UIButtonColor
{
	public static UIButton JIIJIIIIIIIIIIJIJIIIJJIIJJJIIIJJIIIIIIIIJIJIJIJ;

	public bool JJIIIJIIJIIIIIJIJJJIIIIJIJJJJIIJIIJJIJIIIIJJIJJ;

	public string JJIJJJIJJJJIJJJIJIJJJIIJIJIJJIJJJIJIIIJJIIIIJIJ;

	public string JIIIIJJJIJJJIIJJJIJJJIIIJIIIJIIJIJIJIIJIJJJIJIJ;

	public string IJIJJJJIJIJJJIJJJJIJIIIIJIJJJJIJJJIIIIIJJJIIJIJ;

	public Sprite JJJJJJJIJIIJIJIJIJIJIIJJJIIIIIJJJIJIJIIIIIIIJII;

	public Sprite IIIIIIIJJIIIIJJIIJIIIIIJJJIIIIJJIJJJIIJJJIJIIII;

	public Sprite IJJJJJIIIIIIJJIIJIIJIJIJIIJJJIJIIJJJJJIIJJIIIII;

	public bool JJJJJJIIJIIIIJIJIJJIJJIJIJJJIJJIJIJJIJIJJIIJIJI;

	public List<EventDelegate> IJIIIJIJJJIIJJJIIIIJJJJJIIIIJJIIIIJJIJIIIJIIIJI;

	[NonSerialized]
	private UISprite IJIJIIJIIIJIJJJIJJJIJIIJJJJJJJJIIIIIIIJJJJIIJJI;

	[NonSerialized]
	private UI2DSprite IJIIIJIIJIJJIIJJJJJJIIJIJIIJJJIIJIIJJJIIJIIIJIJ;

	[NonSerialized]
	private string JIIJJIJJIJIJJJJIJIJJIJIIJJIIJIJJJIIJJIJIIJJJIJJ;

	[NonSerialized]
	private Sprite JIJIIIIJIIIJIJJIJJJIIJJIJJIJIIIIIIJIJIJIJIIJJJJ;

	public override bool JJIJIIJIIIJJIIIJJIIIIJJJIJIIJIIJJIJIIIJIJJJIJIJ
	{
		get
		{
			return IJJJJIJIJIIIIIIIIJIIJIIIJIJJIJJIJIJIJIIJIJIJIJI();
		}
		set
		{
			IIIJJJJIIJIJJIIIJJIIJIIJJJJIJJIIJIIJJJJJJJJJJIJ(value);
		}
	}

	public string JIJIJIIIJIJIJIIIIJJIIIIIJIJIIJJJIIJJIIIJJJJIJJJ
	{
		get
		{
			return JJIIJJIJJJJJIIJJIJJJJIJJIJIJJIJJJIJIJJIJIIJJJIJ();
		}
		set
		{
			IIJJJJJJIJJIJJJIJIIJJIIJIIJJJJJIIIIIIIJJIJIIIII(value);
		}
	}

	public Sprite JIIIIJIJIIJIIJIJJJJJIIJIJJJJIJJIIIIIJJJIIJIIJJJ
	{
		get
		{
			return IIJIJIJIJJJIIJJIIIIIJJIIIJIJJIIJIIIJJJIJIIJIIJJ();
		}
		set
		{
			JIIIIJJJJJJIJJIIIJJJJIIJJJJIIIIIJJIJIIJIJIIIJIJ(value);
		}
	}
	public virtual void IJIIJJJJJJIIJIIJJJJJJIJIJJIIJIIIJJIIIJJJIJIJIJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void IIIJJIIIIJIJJJIJJJIJIJIIJJJJIIIJIJIIJJIJIJJIIII(Sprite JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected void JJIJIIIJIJIIJIJJIJJIJIJJJIIIIIJIIIJIIJIJIJIJIJJ(string IIIJIJIIIJJIJJJIIJIJJIJJJIJIJIJIJIJJJJIJJJIIJJI)
	{
	}
	public string IIIIIIJJIIIIIJJJJIIJIJIJIJJIIJIJJJIJJJIJJIIJJJJ()
	{
		return null;
	}

	public override void IIIJJJJIIJIJJIIIJJIIJIIJJJJIJJIIJIIJJJJJJJJJJIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected void JJJIJJJIIIJJIIJJIIIIJIJJIIIJJIJJIJIJIIIJJJJIJII(string IIIJIJIIIJJIJJJIIJIJJIJJJIJIJIJIJIJJJJIJJJIIJJI)
	{
	}

	protected void JJIJIIJJIJIJJJIJIJJJIJJJIJIJJJJIJJJIIIJIIIIJJJI(Sprite IIIJIJIIIJJIJJJIIJIJJIJJJIJIJIJIJIJJJJIJJJIIJJI)
	{
	}
	public void IIJIJIIIIIJIJJIJIJJIJIIJIJIJJJJJIJJJIJIIJJJJIJI(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected virtual void IJJIIIIJJJIIIIJJIIIIIJJJIIIIJIJIJIIJJJIJIIIIJII()
	{
	}

	public Sprite IIJIJIJIJJJIIJJIIIIIJJIIIJIJJIIJIIIJJJIJIIJIIJJ()
	{
		return null;
	}

	protected virtual void OnClick()
	{
	}

	protected override void OnEnable()
	{
	}
	public Sprite IIJJIIJJIIIIJIJIIJJIIIIJIIJIIJJIIJJJIJJIJJIIJII()
	{
		return null;
	}

	protected virtual void JJIJIJJJIJJIJIJIJIIJIJIJJIJIJIJJJJIJJJIJJIJJJJJ()
	{
	}

	public void IIJJJJJJIJJIJJJIJIIJJIIJIIJJJJJIIIIIIIJJIJIIIII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected override void IJJJJIIJJJIIJJIJJJIIIIIJIJIIIJJJIJJIIJIIJJJIIII()
	{
	}

	public string JJIIJJIJJJJJIIJJIJJJJIJJIJIJJIJJJIJIJJIJIIJJJIJ()
	{
		return null;
	}

	protected void JJIJIIIJIJIIJIJJIJJIJIJJJIIIIIJIIIJIIJIJIJIJIJJ(Sprite IIIJIJIIIJJIJJJIIJIJJIJJJIJIJIJIJIJJJJIJJJIIJJI)
	{
	}

	public override void IIIJJJIIJIJIJIJIIIIJJJIJJJIJJJJJIJIJJJIJJJIIJJI(JIIJIIJIIIIIJIIIIIJJIJIJIJJJJJJIIIIJJJJJIJIIIJI IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ, bool IJIIIIIJIJJIIIIJIIIJJIIIJJIJJJIJJIIIIJIJIIIIIII)
	{
	}

	protected virtual void JIIJJIIIIIIJJIJJIJIIIJJIIJIIIJJIJIIJIIJIIIJJIJJ()
	{
	}

	public void JIIIIJJJJJJIJJIIIJJJJIIJJJJIIIIIJJIJIIJIJIIIJIJ(Sprite JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public virtual bool IJIIIIIIIIJJIIIIJJIJIJJJIJIIJIIIJIIIIIJJIIIIIIJ()
	{
		return false;
	}

	public override bool IJJJJIJIJIIIIIIIIJIIJIIIJIJJIJJIJIJIJIIJIJIJIJI()
	{
		return false;
	}

	protected override void JIJIJJIJIJJIIJJJIJIJJIIIJIJJJJJJJJJIIJIJJJJIIJJ()
	{
	}

	protected override void JIIJJJJIIIIIJJIJIIIIJIIIIJJIJJJJJIJJJIJIJJJJJJJ()
	{
	}

	protected virtual void JIJJIIIIIIJIJJIJJIIIIIIJJIJIIJIIIIIIIJIJJJJIJIJ()
	{
	}
}
