using UnityEngine;

[ExecuteInEditMode]
public class UIButtonKeys : UIKeyNavigation
{
	public UIButtonKeys JJIJIIJIJIJIIIIIJIIIIJIJIIIJJIJIJJJJIIIIIJJJIJJ;

	public UIButtonKeys IIJIIIIIJJIIIJIIJJIJIJJIJJIJJJIJIIJIIJJIJIJJIII;

	public UIButtonKeys IIIJJIJJJJJIIJJIJIIJJJJIJJJIIIJJIIJJIIJJJIIIJJI;

	public UIButtonKeys IJJIJIJIIIJIIIIJJJIIIIIIIIJIJJJJJJJIJJJJJJIIJJI;

	public UIButtonKeys IJJIIIIJIIIJIIJIJIJIJIIIJIJJIIJJIIIJJJJIIIJIIJI;

	protected virtual void JJIIIJJIIJIJJIIJIIIJJJJJIJJIJJIJIIJIIIIIJIJIJJI()
	{
	}

	protected virtual void JIJIIJJIIIIIIIJJIJIJIJJJIJJIJIIJJIJJJIJIIIJIIJJ()
	{
	}

	public void JIIIIJIJIIJJIIJJIIIIIIJIIJJIJJIJIIIIJIIJJJIIIIJ()
	{
	}

	protected virtual void JIIIJJJJIIIJJJIJJIJJJJIIIJIIIIIIJIIJIIIIIIJIJII()
	{
	}

	public void JJIJJJIIJIIJIJJIIIIJIIIIJJJIJJIJJJIIJIIIIJJIIIJ()
	{
	}

	public void JIIIIIJJJJJIJJIIIJIIJJIIJJJIIJJIJJJIJJJIJJIJJIJ()
	{
	}

	protected virtual void IJIIIJIJJIIJJIJIJJIIJIIIJJJIIJJIIIJIJIIIIIJJJII()
	{
	}

	public void IJJIIIJIJIJJJJJIIIJJIIJIJJIJIIJJIIJJJJIJIIJIJJJ()
	{
	}

	public void IJJIJJJIIIJIJJJJIIJJJJIJJIJIIJIJJJIIIIJIIJJIJIJ()
	{
	}

	protected virtual void IIJJJIJIIIJIIIJJJJIIIIJIJJIJIIIIJJJIIIJIIIIIJII()
	{
	}

	public void JJJJJJJJIIJJIIJJIIJIIIJIIJIIJIJIJIIJIJJJJIJJIIJ()
	{
	}

	public void IIIJJJJJIIJJJIJJJJIJIJJJJIIIIJIJJIIIIIIJIIJIIJJ()
	{
	}

	protected virtual void IIIIIJIIJJIIIIJIJIJIJJIIIIIIJIIJIIIIJJJJJJJIIJI()
	{
	}

	public void JIJJIJIJJJJIJJIJJJIJIIIIJJJJIJIIJIJJIJJJJJJIIJJ()
	{
	}

	protected override void OnEnable()
	{
	}

	protected virtual void JJJIJIIJJIIJJJIIIJJIIIJJJIJJIIJJIIIJIIJJIJIJJJJ()
	{
	}

	public void JIJIIIIIJJIIIJIIIIIIJJIIIIIIJJJIIIJJIJJIIJIIJJJ()
	{
	}

	protected virtual void JJJIIJJIJIJJJJIIJJJJJIJJIIIJJJIJIJJIIIJIIJIIJII()
	{
	}

	public void JIIJJJIIIIIIJJIIIIIIJJJIJIIIJJJJIJJJJIJIIJIIJJI()
	{
	}

	protected virtual void JJJIIIIJIIJJIIJIIIJJJIIJIIIIIJIJJIJIIIIJIJJIIJJ()
	{
	}

	public void JJJIIJIIJIJIJJJJJJIJIIJJJIIJJIJJJJIJIJIIJJIIIJI()
	{
	}
}
