using System;
using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class UIButtonColor : UIWidgetContainer
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JIIJIIJIIIIIJIIIIIJJIJIJIJJJJJJIIIIJJJJJIJIIIJI
	{
		Normal = 0,
		Hover = 1,
		Pressed = 2,
		Disabled = 3
	}

	public GameObject IIIJJJJJIJJJIIIIIIIIIIJIIIIJJJJIJIJJJJJIIJJJJII;

	public Color IIIIJJJJJJJIJIIIJIJJJIJIIJIIJJJIJJJIIIJIIIJIIII;

	public Color IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI;

	public Color IIJIJJIIIIJJIIIJJIIIJIIJJJIJJIJJIIJIJJJIIJJJIII;

	public float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ;

	[NonSerialized]
	protected Color JIJIJJJIIJIJJIIIIIIIIIJIIJJIJIJJIIJJIIIIJIIJIII;

	[NonSerialized]
	protected Color JIIJIIIJJJJIIJIJJIJIJIIIIIIJJIJIIJIIJJJIIIJJJJJ;

	[NonSerialized]
	protected bool IJIIJIJJIJJJIJIJIIIJIIJJIJIJIIJIIJIIJIIJJIJIJIJ;

	[NonSerialized]
	protected UIWidget IJIJIJJIJJJJIIJJIJJIJIJJJIJJIIJJIIJIJIIIIJJIJJJ;

	[NonSerialized]
	protected JIIJIIJIIIIIJIIIIIJJIJIJIJJJJJJIIIIJJJJJIJIIIJI JIIJIJIJJIJIIJJJJIJJJIIIIJIJIIJIIIJIJIJIIJJIIII;

	public JIIJIIJIIIIIJIIIIIJJIJIJIJJJJJJIIIIJJJJJIJIIIJI IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ
	{
		get
		{
			return IJIIIJIIJIJIIIJJJIIIIIIIIIJIJIJIIIIIIIJIIJIJJIJ();
		}
		set
		{
			IIIJJIJJJJJJJIJJIJIIIIIIIIIJJIJJIIJJJIIIJJJIIJJ(value);
		}
	}

	public Color IJJJJIIJIIIJIIJIJJJIIIJIIIJJJIIIJJIJJIJJJJJJJII
	{
		get
		{
			return IJIJJJIIIJIIJJJJJJJJIJJJIJIJJJIJJIJIIIIJJJJJIJI();
		}
		set
		{
			JIIJIIJJJJJIIIIIIJJJJIIIJIIJIJIJIJIIIJJJJJIIJJJ(value);
		}
	}

	public virtual bool JJIJIIJIIIJJIIIJJIIIIJJJIJIIJIIJJIJIIIJIJJJIJIJ
	{
		get
		{
			return IJJJJIJIJIIIIIIIIJIIJIIIJIJJIJJIJIJIJIIJIJIJIJI();
		}
		set
		{
			IIIJJJJIIJIJJIIIJJIIJIIJJJJIJJIIJIIJJJJJJJJJJIJ(value);
		}
	}

	protected virtual void JIJIJJIJIJJIIJJJIJIJJIIIJIJJJJJJJJJIIJIJJJJIIJJ()
	{
	}

	protected virtual void JIIJJJJIIIIIJJIJIIIIJIIIIJJIJJJJJIJJJIJIJJJJJJJ()
	{
	}

	public void JIIJIIJJJJJIIIIIIJJJJIIIJIIJIJIJIJIIIJJJJJIIJJJ(Color JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual bool IJJJJIJIJIIIIIIIIJIIJIIIJIJJIJJIJIJIJIIJIJIJIJI()
	{
		return false;
	}
	public JIIJIIJIIIIIJIIIIIJJIJIJIJJJJJJIIIIJJJJJIJIIIJI IIIIJIIJJIJJJJJJIIIIIJJIIIIJJJJJIJIIIJIIJJIIJJI()
	{
		return JIIJIIJIIIIIJIIIIIJJIJIJIJJJJJJIIIIJJJJJIJIIIJI.Normal;
	}

	public virtual void IIIJJJIIJIJIJIJIIIIJJJIJJJIJJJJJIJIJJJIJJJIIJJI(JIIJIIJIIIIIJIIIIIJJIJIJIJJJJJJIIIIJJJJJIJIIIJI IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ, bool JIJIJJJIJIIJJIIIIJIIIIJIIJJIIIIJJJJIIIIJIJIIJJI)
	{
	}

	protected virtual void JIJIJIJIIJJIJJIJIIJJJIIIJJIJIJIJJIJJIIIJIJJIIJI(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	protected virtual void IJIIIJIIJIJJIIJIIJIIIJJIIIIIIJIIIIIIJJJIIIJJJII()
	{
	}

	protected virtual void JIJJJJJIJJIJIJJJJIJIIIIJJIJIIJJIIIJIIJJIJIJJIII()
	{
	}

	public void JIIJJIIIIJIJJJJIJJJJJIIIJIJIIJIJIJIIJIIIIIIIJIJ()
	{
	}

	protected virtual void JJIIIJJJJJIJIIIJJJJIJIIIIJIJJIIIJIJJIIIJIIIIJII()
	{
	}

	public void IIIJJIJJJJJJJIJJIJIIIIIIIIIJJIJJIIJJJIIIJJJIIJJ(JIIJIIJIIIIIJIIIIIJJIJIJIJJJJJJIIIIJJJJJIJIIIJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected virtual void OnDisable()
	{
	}
	public virtual void JJJJIIIJJJIIJJIJJIJJJIIJIJJIIIIJIIJJIJJIIIJIJJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void IJJJIIIJJJIJJJJJIJJIIIIIIJIJIJIJJJJJIIJIIJJJIJJ(Color JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public Color IJIIIIIIJIIIIJJJJIJJIJIIJIIIJIIIJJJJJIIIJIJIJIJ()
	{
		return default;
	}
	public void JJIIIIIIIIJIJJIIIJJJJIJJJJIIIIIJJJJIJJJIJJJIJJI(Color JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected virtual void JIIJIIIIJJJIIIIIIJJIIIIIIJJJIJJJJJIJIJJIIIIIIJI(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	protected virtual void JJIJIJIIIJIIIJIJJJJIIIIJJIJJJJIIIJIIIJIJIIIIIII()
	{
	}

	public JIIJIIJIIIIIJIIIIIJJIJIJIJJJJJJIIIIJJJJJIJIIIJI IJIIIJIIJIJIIIJJJIIIIIIIIIJIJIJIIIIIIIJIIJIJJIJ()
	{
		return JIIJIIJIIIIIJIIIIIJJIJIJIJJJJJJIIIIJJJJJIJIIIJI.Normal;
	}

	public Color IJIJJJIIIJIIJJJJJJJJIJJJIJIJJJIJJIJIIIIJJJJJIJI()
	{
		return default;
	}

	protected virtual void IJJIIIIJJIJJJIIJJJJJIJJJIJIIJJJIIIJIIJIJJIIJIII()
	{
	}

	protected virtual void OnEnable()
	{
	}

	protected virtual void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	public virtual void IIIJJJJIIJIJJIIIJJIIJIIJJJJIJJIIJIIJJJJJJJJJJIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected virtual void IIIIIIJIIJIIJIIIJIIIJJIJIJJIJIJIJIJIJJIIIIIJIJI()
	{
	}

	protected virtual void IJJJJIIJJJIIJJIJJJIIIIIJIJIIIJJJIJJIIJIIJJJIIII()
	{
	}

	protected virtual void JIJJIIJJJJIIIIIJJJJIIJJIIIIJIIIJJJJIJIIJJJIIIII(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	public void IIIJJIJJJJJIJJJIJIJIJJIIIIIIJJIJIJIIJJJIJJJJIIJ()
	{
	}

	public void JJJJIIJJIJIIJJIJJIIIJIIJIJJIJJIIJJIIJIIIJIIJJII()
	{
	}

	public void IIIIIJIJIJIIIIIIIIJIIIIIJIIJIJJIJIIIJIJJJIIJIJI(bool JIJIJJJIJIIJJIIIIJIIIIJIIJJIIIIJJJJIIIIJIJIIJJI)
	{
	}
	public void IIJJIIJJIIJIIIIIJJIJIIIIJJJIJIIIIIJIJJIJIIIJIJJ(JIIJIIJIIIIIJIIIIIJJIJIJIJJJJJJIIIIJJJJJIJIIIJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void Start()
	{
	}

	protected virtual void IJIJJIIIIIIIJIIJJJIJIJIIIJJJIJIIIIJJIIJJJIIIJJI()
	{
	}
	public Color JJJJJIJIJIJIJJJIIJIIJIIJIJJIJJIJIIJJIJIJIIJIIJI()
	{
		return default;
	}

	protected virtual void IIIJIJJIIIIIIIJJIJJJJJIJJJJIJIJIJJJIJJIJIJJIJJI(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}
}
