using UnityEngine;

public class UIButtonActivate : MonoBehaviour
{
	public GameObject IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

	public bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ;

	private void JJJIJIJIJJJIJJIJIIJIJIJJJJJIIIJIIIIJIJJIJJJIIIJ()
	{
	}

	private void JJJIJJJIIIJIJIJIIIIIJJJJJJJJIJJJIIIIIJIIJJJJJIJ()
	{
	}

	private void IJJIIIIJJJIIIIJJIIIIIJJJIIIIJIJIJIIJJJIJIIIIJII()
	{
	}

	private void JIIIIJIJIIJIJJJIJJIIJIIJIJIIJIIJJIJJJIJIIJIJJJI()
	{
	}

	private void JJIJIJJJIJJIJIJIJIIJIJIJJIJIJIJJJJIJJJIJJIJJJJJ()
	{
	}

	private void IJIIJJIJIIJIIJIIIJJJIJJIIIIJIIIJIIJJJJIIJIJJJIJ()
	{
	}

	private void JJIJJJIIIJIJJJIJIIIIJIIJIJIJJJIJJJJJIIJIIIIIIJI()
	{
	}

	private void IJJJJIJIJIJJJIIJJIJJJJIJIJIJIIJJJIIIIIIJJJIJJJI()
	{
	}

	private void IIIIIIJIIJJIIJJJJJIIJIIJIIJJIJJJJJIJIJJJJIIJIIJ()
	{
	}

	private void IIJJIJJIJIIIJJIIJIIIJIIIIIJIJIIIIIJIIJIJJJJJIIJ()
	{
	}

	private void OnClick()
	{
	}
}
