using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class UICamera : MonoBehaviour
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JIIIIJIIIIIJIIJIIIJJJIIIJIJIJJIIJIJJJJIJJJIIJJI
	{
		Mouse = 0,
		Touch = 1,
		Controller = 2
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JJJIIIJJJJJJIIJJJJIJJJIJIIJJJIJJJIJJJIIIJIJIJJJ
	{
		None = 0,
		Always = 1,
		BasedOnDelta = 2
	}

	public class JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII
	{
		public KeyCode IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ;

		public Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ;

		public Vector2 JIIIIIIIIJIJIIJJIIIJJJIJJIIJJJIJIJJJIJIJJIIJJIJ;

		public Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI;

		public Vector2 IJIJIIJJJIIIJIIJIIJJJIIIJJIIIIJJIIIJJJJIJJIJIII;

		public Camera IIIJJJIIIJJJJJJJJJJJJIJJJIIJIJJIIJJIJJJJIJIIIJJ;

		public GameObject IJIIIJIIJJJIIIJJJIIJJJJJJIIJIJJJIJIIJJIJJJJIJII;

		public GameObject JIIJIIIIIIIIIIJIJIIIJJIIJJJIIIJJIIIIIIIIJIJIJIJ;

		public GameObject IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI;

		public GameObject IIIJIIIJJIIJJJJIJIJIJIJIJIJIIIJIJIJJJJJIJJIIIII;

		public float JIIIIJIIIJIJIJJIIJJIJJIIIIIJIJIJIJJJIJIIIIIIJJI;

		public float JJJJIIJIJJJIJIJJJJIJJIJJIIJIJJIJJIIJIIJIIIJIJJI;

		public JJJIIIJJJJJJIIJJJJIJJJIJIIJJJIJJJIJJJIIIJIJIJJJ JIJIIIIIIIIIIJIIIJJIIJIIIJJIJJJJJIIIIJJIIJJIJII;

		public bool JIIIJJIJJJIIIJJJIJJIIJIJIIIIIIIIJJIIIJIJJIJIIII;

		public bool IIIJIJIIIJIIIJIJJJJIIJJJJJIJJIJIJJJJIIJJJJJIIJI;

		public bool JIIJIIIIJJJIIJIIIIJIJIIJJIJIIJIJJJJJIJIIJIIJJJJ;

		public int JJJIJJJIJJIIJJIJIIIIIJJIIJIIIIJJIJJIIJJIIIJIJII;

		public float JIJIIIJIJJJJJJJJJIIJJIIJJJIIIIIIJIJJJJJIJIIIJIJ => JJIJIJIJIJIIJIJJIJJJJIJIIIIJJJIIIIJIIIIJIIJIIJI();

		public bool IIIIJIJIJJJIIIJIJIIIIIIJIJIIJJJJIIIJIIJJIJJIJIJ => JIJIJJIJJIIIJJIJJJJIJJIJJJJJIJIIJJIJJJJIJIJJIJJ();

		public bool JIJIJJIJJIIIJJIJJJJIJJIJJJJJIJIIJJIJJJJIJIJJIJJ()
		{
			return false;
		}

		public float JJIJIJIJIJIIJIJJIJJJJIJIIIIJJJIIIIJIIIIJIIJIIJI()
		{
			return 0f;
		}
		public float JIIIIIJIIJJIIJIIJIIIIIJIJIIIIIJIIJIIJIIJJIIIIII()
		{
			return 0f;
		}
		public float IIJJJJJIIJIIJIIIIJJIIIIIIIIIJIJIJIJJJIIJJJIJIJI()
		{
			return 0f;
		}
		public float JJJIJIJIJJJIJJIJIIJJIJIJJJIIJJIJJIJJIJJIIJJIIII()
		{
			return 0f;
		}
		public bool JIJJJJJJJIIJJIIIJIIJIJIIIJJJIJIIJIJIJIIIIJIJIIJ()
		{
			return false;
		}
		public float JIIIJIIIIIJIJJJIJIJJIJIJIIIIJIJIJIIJJIJJIIJJJJJ()
		{
			return 0f;
		}
		public bool JIJJIIIIIIJIJIIJIJJIIJJJJJIJJJJIJIIJJJJJJJIIJJJ()
		{
			return false;
		}
		public float IIIJJJJJIIJJJJIJIJJJIJIJJJJIIJIIIIIIIIIIIJIIIJI()
		{
			return 0f;
		}
		public bool IIIIIIIJJJIJIJJJJJJJIJIIIIJIJIIJIJJIJJJIJJIIJIJ()
		{
			return false;
		}
		public bool JJIJIIJJIIJJIIIIJIIIJJIIJJIJJJJJJIJIIIJJIJJIJJJ()
		{
			return false;
		}
		public bool JIJJIJIIJJIJJJIJIJIJJIIIJIIIJIJIIIJJJIIJIIJIJIJ()
		{
			return false;
		}
		public bool JIJJIJJJIJJJIIIIJJIJIIIIJIIJJIIIIJJIJIIJIIIIIIJ()
		{
			return false;
		}
		public bool JIJIJIJIIIJJJJIJIIIJIIIJJJIJIJJJJIJIIIIJIIIIIJJ()
		{
			return false;
		}
		public bool JIIIJJJJJJJJJJIJIJIIIIJIJJJIIIJJJIIJJJIIIIJIJIJ()
		{
			return false;
		}
		public float IJJJIJJIIJIIJIJJJJJJJJIIIIJJIJJJIJIJJIIJJIIJIII()
		{
			return 0f;
		}
		public float JJJIIIIJIJJIIJIIIIJJIJIJJIIJIIJIIJIIJIIJJIIJIII()
		{
			return 0f;
		}
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IIIJJIIIJIIIIJIJJIIIIJIJJJJIIJJJIIIJJIJJIJJJIJI
	{
		World_3D = 0,
		UI_3D = 1,
		World_2D = 2,
		UI_2D = 3
	}

	public delegate bool IJIJIJJJJIJJJIIIIJJIIJIJIJIJJJJIJIJIIIIJJJIIIJI(KeyCode IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ);

	public delegate float IJJIJJJIIJIIJIJJJJJIJJJJJJIIJJIJJIIJJIIIIJJIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ);

	public delegate bool JIIIIJJJJJIJIJIJJJIJJIIJIJJJIJIJIJIIJJJJIIJIJII();

	public delegate JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII IIJIIIIIIJIJJJIJJIIIJIJIIIJJJJIJIIIIJJIJJJIJJIJ(int IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ);

	public delegate JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII IIIJJJIJIIJJIIIJIJJJIIIIIIIIIIJIIJIJJIJIIIJJIJI(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, bool IJIIIJIJIIJIJJIJIJJIIIIJJIJIJJIIIJJJJIIIIIJJJII);

	public delegate void IJIJIIJJJJIJJJJIIIJJJIJJJJIIJJJJJIIIJIJJIIJIJJJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ);

	public delegate void JJJJJJJIIIIJIIJIIIJIJJJIJJJJJJJIIIIIIIJJIIIJIJI();

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IJIIIIIJIJJIJIJIIJIJIJJIJIIJJJIIJJIIJIJJIIJJJIJ
	{
		Update = 0,
		LateUpdate = 1
	}

	public delegate void IJIIJIJJJIIIIJIIJJIIIJJIIIIJJIIIIJJJJJIJIJJIIJJ();

	public delegate void JIIJIIIJJIJIIIIIJIIIIJIIIJIJIIJJJIIIJJJJJJIJJIJ();

	public delegate void IJIIIIIJJIJIJIJIJIIIJJJIJJJJIIJJIIIIIIIIIIIIIIJ(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI);

	public delegate void JJJIIIIIIJIIJIJJIIJJIJIJIJJIIIIIJIJIJJIJIJIJJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII);

	public delegate void JJIJIIJIIIIJJJJJJJIIIIJJJIJIIIIIIJIJJJJIJIJIIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ);

	public delegate void JIIJIIJIJIJIJIIJIIIJIJJIJJIIIIJIJIIIIJJIJJJJIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI);

	public delegate void IIJJJJIJJIJIJIIIJJIJIIIJJIJIJIIJIJIJJIIIIJIJIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI);

	public delegate void JIIIIJJJJIJIJIJJIJIIIIIIJJIIIIIJJIJJJIJIJJIIJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, GameObject JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ);

	public delegate void JIJJJIJIJJJIJJIIIIJJJIIJIIIJJJJIJJJIJJIIIIIJJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, KeyCode IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ);

	private struct IIJJJJJJJJIJJIJJJIJJIIIIJIIIJJJJIJIIIIIJIIIJJJI
	{
		public int JJJIJJIIJJJJIJJJJIIJJJIJIJJIJJIIJIJIIIIIIJJJJII;

		public RaycastHit IIJIJIJJJIJIJJIJIJIIJJIJIJIJJJIJIJJJJJJJJJJJIJJ;

		public Vector3 JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII;

		public GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII;
	}

	public class JJJIJJIJIJJJJJJJJIJJIJJJIIIIJJJJJIJJJIIIJJJJIJJ
	{
		public int JIIJJJJIIJJJIIIJJJJIJIIJJIJJIJJIIIIIJIIIJJIJIIJ;

		public TouchPhase JIIIJJIJJJIJIJIIIJIIIJJIIJIIIJIJIIIIIJIJJJJJJJJ;

		public Vector2 IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ;

		public int IIIJJJIJIJIJIJIIJJIIIIIIIJIJJJJJJIIIIJIIIJIIIJI;
	}

	public static bool IJIIIJIIIJJIJJJIJIJJIJIIIJIJJIIJIIIJJJIIJIIIIJI;

	public static bool IIJJIJJIIJJIJJIIIJJJIJIIJIJJIJIJIJIJJJIIJIJIIJJ;

	public static global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<UICamera> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ;

	public static IJIJIJJJJIJJJIIIIJJIIJIJIJIJJJJIJIJIIIIJJJIIIJI IIIJIIJIJJIIIIJIIIIJIIIIIJIJJIIJIIIJIIJJJIJIJII;

	public static IJIJIJJJJIJJJIIIIJJIIJIJIJIJJJJIJIJIIIIJJJIIIJI IIIJIIIIJJIIJJJIIJJIJIIJJIJIIIIJIJJIJJIIJIJJJII;

	public static IJIJIJJJJIJJJIIIIJJIIJIJIJIJJJJIJIJIIIIJJJIIIJI IJJIIIIJJJJJIJIJJIIIIJIJJIJJIIIJIJJIIIIJIIJIJII;

	public static IJJIJJJIIJIIJIJJJJJIJJJJJJIIJJIJJIIJJIIIIJJIIJJ IJJIIJIJJIIJJIIIJJJJJIIIIIIJIJIIIJJIJIIJIIIIIJJ;

	public static JIIIIJJJJJIJIJIJJJIJJIIJIJJJIJIJIJIIJJJJIIJIJII IIJIIJIJJIJJIIJIJJJIIJIIIJJJIIIJJJJIJJIJIJIIIII;

	public static IIJIIIIIIJIJJJIJJIIIJIJIIIJJJJIJIIIIJJIJJJIJJIJ JIIJIJJJJJJIJJJJIJJIJJIJIJIIJIJJJIIIJJJJIIJJJJI;

	public static IIIJJJIJIIJJIIIJIJJJIIIIIIIIIIJIIJIJJIJIIIJJIJI IIIJIJJIJIIJJJIIJIIIJJIJJJJIJJJJIJIIIIJJJIJJIJJ;

	public static IJIJIIJJJJIJJJJIIIJJJIJJJJIIJJJJJIIIJIJJIIJIJJJ JJIIIJIJIIIIJJIJIIJJIIJJIIIIJIJJIIIJIJIJJJJIIII;

	public static JJJJJJJIIIIJIIJIIIJIJJJIJJJJJJJIIIIIIIJJIIIJIJI JIJJJIIIJIIJIJJIIIJJIJIJIJIIIJIIIJJIIIIIIIJJJIJ;

	public IIIJJIIIJIIIIJIJJIIIIJIJJJJIIJJJIIIJJIJJIJJJIJI IJJJIJJJIIJIIIJJIJIIJJJIJJIJIIJJJJIIIIIIJJIJIII;

	public bool IJIIJIIJIIJJJIJIJIJJIJJJJJIJJJJJJIIJJIJJIIIJJJJ;

	public LayerMask IJIIJJIJJIJIJJJJIIIIIJIIJIJIJIJJJJJIIJIJJIJIJIJ;

	public IJIIIIIJIJJIJIJIIJIJIJJIJIIJJJIIJJIIJIJJIIJJJIJ IJJIJIIJIIJIIIJJJJIJIJJJJJIJJJJJJJIJJIJIIJIJJIJ;

	public bool JIJJIJIJIIIJJJJJJIJIIIJJIIIIJJIJJIJJIIJJJJJIJJI;

	public bool IIIIIJIIJIJIIIIJJJIJJIJIJIJIJIIJIJJJIJJJIIIIJIJ;

	public bool JIJJJIJIJIJIIJJIJJIIJIJJIIJJJIIJIIIJIJJJIIIIJJI;

	public bool IIJJJIJJJIIIJJJIIIJIIJJJJJJIJIIJJJIIJIJIIIIIIJJ;

	public bool IIIJJIJIJJIIJJJJIJIIIJJIJJJJJJIJJJJIJJJJIJIJIIJ;

	public bool IIIJJJJIIIIIJJJIIJJJJIIIIJIJIIJIIJJJIJJIIJJIJIJ;

	public bool IJJJIIIIJJJIJIJIJJIIIJJIIJJIJJIJIJIJIJIJJIIJJIJ;

	public float JJIIJIJJIJJJJIJIJIJIJIJIJJIIJJIIIJJJIIJIJJIJIJI;

	public bool JIJIJIJJJIJIJIJJIIIIJJIJIIJIJIJJIIIIJJJIIIIIIJJ;

	public float JJIIIIJIIIJIIIIIJJJJIIIIIJIIIJJJIJJIJJIIIJJIJIJ;

	public float IIJIJJIIIJJIJJJJIJIJJJIIJJIJIIJJIJIJJJIIIIIJIJI;

	public float IIIJJJIIJIJJJJJJIJIJIIIIIIIIJIJIJIIIIIJJIIJIJJJ;

	public float JIIIJIJJJIIIIJJJIJIIIJJIJJIJIIIJIJIJIIIIIJIIJJJ;

	public float JIIIJIIJIIIIIJIIIJJJJJIIJJJIJJIIJJJJIJIIJIIIIII;

	public string IIJJIJIJJIIJIJJJJIJIIIIJJJJIJJIJIIIIJJIJJIJIIJI;

	public string JJJIIIIJJIJIIJJJJJJIIIIJJIIJIJJIIIIIJJJJIIIIJJI;

	public string JIJJIJIIIIIJIJIIJJJIJIJJIJJIIJIIJJIIIIIIIJIJJIJ;

	public string IJIIIIJIJIJJJJIIJJIIIIJJIJIJJIIJIIJJJIIIIIIJJIJ;

	public string JJIIIIIJIIIJIIJIJIIIIJJIJJJIIJIIJIJJIJIJJJJIIJI;

	public bool JJIIJJIIIIJIJIJJJIJIJIIIJJIIJJJIJJIIJIIIJJJIJII;

	public KeyCode JIIJIIIIIJJJJIJIJJJJJJJJJIIJIIJIJJIJJJIIIJJIJJJ;

	public KeyCode IIIIJIIJIJIJIIJJJIIJJJJJJIIJIJJIIIIIJIJJIIIJIJI;

	public KeyCode JIJJIJJJJJIIJJJIIJJJIJJJJJJJIJIIJIIIJIIIIIIJIJI;

	public KeyCode JJIIJIJJIJIIIJIIIJJJJIJIJIJJJJIIIIIIJJIIJIIJIII;

	public bool JIJIIJIJJJJJJIJJJIIIIJIIIJIIJIIIJIIJIIIIJIIJJJI;

	public static IJIIJIJJJIIIIJIIJJIIIJJIIIIJJIIIIJJJJJIJIJJIIJJ JIJJIJIJIJIJJIJJIIIIJJJIJIJIIIIJIIJJJJIIJIIJJJI;

	public static bool IIIJJJJIIIJJJJIJIJJJIIJIIJIIJJIJIJJIJIJJJJJIJIJ;

	public static bool JJJJJJIIIJIIIJIIJIJIIJIIJIIIIIJIIJIIIJJJJIIIIJJ;

	public static bool JJIIIJJIIJJIJIIJJIJJJIJJJIIIJIJIIJJIIJIJIIJJJJI;

	private static bool JIIIJIJIJIJJIIIIJIJIJIIIIJIIJJJIIJIIIIIIJJJIJIJ;

	private static Vector2 JIIIJIIIJJJJIJIJIIJJIIJJIJJIIIJJIIJIJJIIIJIJJJI;

	public static Vector3 IIJIJJIIIIJIJIIJJJIJIJIJIIIJJIIJJJIJIIJJJIIJJII;

	public static Ray IIJJIJIIIIJJJIJIJJJIJJJIJIIJIIJIIJIJIIJIIIIJIJJ;

	public static RaycastHit JIJIJIJIIIIJIJIIIJJIIIIJIJIJIJJIIIIIJJIJJIJIIIJ;

	public static UICamera JIIJIIIIIIIIIIJIJIIIJJIIJJJIIIJJIIIIIIIIJIJIJIJ;

	public static Camera IIIJIIIJJIIIJJIJJIIIJIJIJJIJIIJJIIIJJJJJJJJJJIJ;

	public static JIIJIIIJJIJIIIIIJIIIIJIIIJIJIIJJJIIIJJJJJJIJJIJ JJIIJIJIJJIJJJIIIJJIJJIIJIJIIJIIJIJJIJJIJJJIJIJ;

	private static JIIIIJIIIIIJIIJIIIJJJIIIJIJIJJIIJIJJJJIJJJIIJJI IJJIJJJJJIIJJIIIJJIJJIIJJJIIIIJIJJIIJJIJIJJIIJI;

	public static int JJJIJIJJIIIJIJIIIJIIIJIIJJJJJIIJIIJJJJIIIJJIIII;

	private static KeyCode IIIJJIIJIIIIJIJJJIJIIJJJJJJIIIIJJIIJIJIJJJIJJJJ;

	public static JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII JJJIJIJJIIIIIIIIJJJJIJJJJJIIJIIIIJJJJJIIJIIJJJI;

	private static bool JIIJJJIIIJJJJIIIJIJJIJIIJIJJJJJJJJIIIIIJIJIJJII;

	private static GameObject JJIIIJJJIJJIJIIIIIIJIIIIJIIJIJIJJJIJJJIJIJIJIII;

	public static GameObject IIJIJJJJJJJJIIIJIJJIIIIIJIJJJIJIIIJIJJJJIJJIJJI;

	public static JJJIIIIIIJIIJIJJIIJJIJIJIJJIIIIIJIJIJJIJIJIJJIJ IJIIIJIJJJIIJJJIIIIJJJJJIIIIJJIIIIJJIJIIIJIIIJI;

	public static JJJIIIIIIJIIJIJJIIJJIJIJIJJIIIIIJIJIJJIJIJIJJIJ JIIIJIIJIJJJIIJIIIIIJIJIJJJJIJJIIJJJJJIIJIIIJJI;

	public static JJIJIIJIIIIJJJJJJJIIIIJJJIJIIIIIIJIJJJJIJIJIIII JIJJJJJIJJIJJIJIIJJIIIIIJIIJIJIIIIIIJIIIJJIJIJI;

	public static JJIJIIJIIIIJJJJJJJIIIIJJJIJIIIIIIJIJJJJIJIJIIII IIIJJIIIIIIJIJJJJJIIJIIJJJIJIIJJIJJIJJIIIJIIJJI;

	public static JJIJIIJIIIIJJJJJJJIIIIJJJIJIIIIIIJIJJJJIJIJIIII JIIJIIJJIIJJIIJJIJJIJIIIJIJIJJJIIIJJJJJIIIJJIJI;

	public static JIIJIIJIJIJIJIIJIIIJIJJIJJIIIIJIJIIIIJJIJJJJIJJ JJIIJJJJJIIJJJJIIJIIJIIIJJJJIIJIIJIJIJIJIIIIJJJ;

	public static IIJJJJIJJIJIJIIIJJIJIIIJJIJIJIIJIJIJJIIIIJIJIJI JIIIJIJIIIIJIIJIJIJIJIIJJJIIIJIJIIIJIIIJIJJIJIJ;

	public static JJJIIIIIIJIIJIJJIIJJIJIJIJJIIIIIJIJIJJIJIJIJJIJ JJJJIIIJIJIJJIJJJIIJIIJIJJIJIIJJJJJIJJIIIJJIJJI;

	public static JIIIIJJJJIJIJIJJIJIIIIIIJJIIIIIJJIJJJIJIJJIIJII IIIIJIIIJIIIJIJIJIJJIJJJIJJJJIIIJIIJJIIIIIIIJJI;

	public static JIIIIJJJJIJIJIJJIJIIIIIIJJIIIIIJJIJJJIJIJJIIJII IIIIJJIIJJIJIIIIIJIJIIJJJIIJJIJIJJIJJIJJJIIJIIJ;

	public static JJJIIIIIIJIIJIJJIIJJIJIJIJJIIIIIJIJIJJIJIJIJJIJ IIIIIIJIIIIIIJJJIIJJIJJIJJIIIJJIJIJJJJIIJJJIIIJ;

	public static JIIIIJJJJIJIJIJJIJIIIIIIJJIIIIIJJIJJJIJIJJIIJII IIIJIIJJIIIJJIIJIJJJIIIJJJJIJJJIIJJJIJJIJIIIJIJ;

	public static JIJJJIJIJJJIJJIIIIJJJIIJIIIJJJJIJJJIJJIIIIIJJIJ JIJIIJIJJJIIIIIIJIIJIJIIIJJJIIIIIIIIJJIJIJIJIII;

	public static JIJJJIJIJJJIJJIIIIJJJIIJIIIJJJJIJJJIJJIIIIIJJIJ JJJIJJIIIIJIJIIIJJJIJJJIJJJIJIJIIJJIIIIJJIJJJIJ;

	public static IIJJJJIJJIJIJIIIJJIJIIIJJIJIJIIJIJIJJIIIIJIJIJI IIIJJJJIIIJIJJIIJJJJJJIJIJIIJJIJJIJJIJJJJIJIIJJ;

	public static JJIJIIJIIIIJJJJJJJIIIIJJJIJIIIIIIJIJJJJIJIJIIII IIIIJJIJJJJIJIJJJJJIIJJJJJJIIJJIJJIIJJIIJIJJIIJ;

	public static IJIIIIIJJIJIJIJIJIIIJJJIJJJJIIJJIIIIIIIIIIIIIIJ IIIJJJIIJJJJIIJJIJIIIJJJJIJJIJIIIJJIIJIJIIIIIIJ;

	private static JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII[] IIJJIJIIJIIIJIIJIJIJJJIIJIJIIJIJIIIJIJIJIIJJIJI;

	public static JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII JJIJJIJJJIIIIIIIJIIIJIJIJIIJJIJIIIJIIJIJIJIJIIJ;

	public static List<JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII> JIJJJJIJIIIJJJJIIIJJIIIJJIJIJJJIJIIIJJJIIJIIJIJ;

	private static global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<int> IJJJIJJIIJJJIIJJIJJJIIJIJIIJIJJJIJIJIIIIIJIJJJJ;

	private static int JJJJIIJJIIJJIJJJJJIJJJIIJJJIIIJIJIIJIJJJIIIJJJI;

	private static int IIIIIIJJJJJIIIJIIIJIJJJIJJJIJIIIJIIJIJJJJJIJJJJ;

	private static GameObject JIJJIIIIJJIJJJIIIJIJJIIIIJIIIJIIIIIJIJJJIIJIIJJ;

	private Camera IIIJJJIIJIIJIJJIJIJIIJJIIJIIJIJIJIIIJIJIJJIIJII;

	private static float IJJIJJJJJJJJJJIIJJIJIIIIJJIIJIJJJJIJIJJIJJJIIJI;

	private float JIIIJJIJIJIJIJJIJJIJJJIIJJIJJIJJJJJIIIIIIJIJJIJ;

	public static bool IJJJJJJJIJJJJJIJJJJIJJJJJIIIIIIJIIJIJJIJJIIJJII;

	private static int IJIJIIJIJIJIIJIIJIIIIIIJIJJJJIIIJIIJJJJJJIJIIII;

	private static bool IJJJJIIIIIIJJIIJJIIIJIJIIIJJIJIIIJJJJIJIIJIJIJJ;

	private static int JJJJIJIIJJJJIIIJJJIJJIIJIIJIJJIJIIJJIIIIJIIIJII;

	private static bool IJIIJJJIJJJJJIIJIIJIJIJIIJJIIIIJJJIJIIJIIIJJIJI;

	private static int IIJJJIIJJJJJIJJJIIJIIIJJJJJJJIIJIJIIJJIJJIIIIIJ;

	private static bool JJJJJJJIJIIIJJJJIJJJJIJIJJJIJIJIJJIIJJIIIJIJJJJ;

	private static GameObject IJJIIIIJIIJIIJJJIIIJIIJIJIIJJIJIIIIIIJJJJIJJIJJ;

	private static GameObject IIJJIJIJJJJJIJJIIIIIIJIIJJJIIIIIJIIIJIIIIJJJIJI;

	private static GameObject IJJIIIJJJIIIIIIJJIIJIIJJJJIIIJIIIIIIIIJIIIJJIJJ;

	private static IIJJJJJJJJIJJIJJJIJJIIIIJIIIJJJJIJIIIIIJIIIJJJI JIJJIJIJJIIJIJJIJJJJIIIIIIJJJIIIJJIIIIIIIIJJIJI;

	private static global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<IIJJJJJJJJIJJIJJJIJJIIIIJIIIJJJJIJIIIIIJIIIJJJI> JIIIIIIIJJIIJJJJJJIIJIIIJIJIIJIJIJJIJJJIJIIJIII;

	private static RaycastHit[] JIJIIIIJIJIJJIIIJJIIJIJJJJIIJJJIJJJIIJIJJJJIIIJ;

	private static Collider2D[] IJJJIJIIIIIJJIJIJJIJJJIJIIJIIJIJJIIIIIJIJJJJJII;

	private static Plane IJIJJJIIIIJJIIJIJIIJIIJIJIIIIJJJIJJJJJJIIJIJIJJ;

	private static float IIJIJJJJIJJIJJIIJJJIJIIIIIJJIJJJIIIIIIIJIJJIJII;

	private static int JJJIIJJJJIIJJJIJIIJJJIIJJJIJIJJJJJIIIIIIIJJIIJJ;

	private static bool JJIJJJIIIIIIJIJIIJIIJIIJIJIIIJJIJIIIIIIIJIIIIJI;

	[Obsolete]
	public bool JJJIJIIJIJIJIIJIJJIJJJJJIIIJJIJJIIIJJIIJJIJIJII => JIJJIJIIJIIJIIIJIIIJIIJIIJJJIIIJIJJIJJIIJJJIIJI();

	public static bool JIJJJJIIJIJIJJJJJIIJJJJIIIJJJIJIIIIIJJJJIJIIIJJ
	{
		get
		{
			return JJIJJIIIIIJIIJIIIIJIIIJIJIJJIJJJJJJJIIIIIJIJJJJ();
		}
		set
		{
			IJJIIJJIIJIIIJJIJIJIIIJJIIJJJJIJJJIIJJJIJIIJIIJ(value);
		}
	}

	[Obsolete]
	public static Vector2 IJJJJIIJJIJIIJIIIIJIJIIIJJIIIJIIIJIJJIJIJIJIIII
	{
		get
		{
			return IJIIIJIIJIJIIJJIJJJJIJJJJIIIIIIIJIJJJIIJIJJIIJI();
		}
		set
		{
			JJJIIIIIJIJJIJJJJJIJJJJJJJIJIIJIJJIJJIJIJJJIIIJ(value);
		}
	}

	public static Vector2 IIIIJJJJIJJJJJIIJIJJJIIJJIJJIJJIIJIIJIJIJJIIJII
	{
		get
		{
			return JJIIJJIIJIJJJIIJIJIJIIJIIJIIIIIJIIIIJIIIJIIJJJI();
		}
		set
		{
			JJIJJIIJIIJJJJJJIIJJIIIJJJJJJJIJJJJIJIIIJJJIJII(value);
		}
	}

	public static UICamera JIIJIIJJJIIIJIJJJJIJIIJJJIJIJIJIIJJJJJJJJIIJIIJ => JIIJIIJIIIJJJIIJJJJIIJJIJIJIIJJJIJJIIJJIJIIIIIJ();

	public static JIIIIJIIIIIJIIJIIIJJJIIIJIJIJJIIJIJJJJIJJJIIJJI JJIJIIJJIIJJIJIJIIJJJIIJIJJIJJIIJJJIIJIIIJJJJJJ
	{
		get
		{
			return IJJIIIIIJIIJIIIJIIJJIJJJIJIJIIJIJIJIIJJIJIIIIJJ();
		}
		set
		{
			JIIJJJIIIJIJIJJIJIJJJJJJIJIJIIIJIIIIIJJJIJIIIIJ(value);
		}
	}

	public static KeyCode JIJIJJIJJIJIIIJJIIIIIIJIIJIJIIJIJIIIJIIIIIJJJJJ
	{
		get
		{
			return IIJIJIJJJJJJJJIJIIIJIIJJJIIIIIJJIJJJIJJJIIJIIJJ();
		}
		set
		{
			JIIIIIJJIIIIJIJJIJJJIJJIJIIJJJJIJJJIJJJIJJJJJJI(value);
		}
	}

	public static Ray IIIIJIIJIJIJJIIJJIIJIIIIJIJJJIIJIIJIJIIIJJIJJIJ => JIJIIJJIJIJIIJJIJIIJJJIIJJJJJJJIJIIIIIIIJJJIJJI();

	public static bool JIJJIIIJJIJJJJJJJIJIJIIIJIIJJJIJJIJIIJIJIJIJIIJ => IJJJIIJIIIIIIJJJJJIJJIIIJIIIJIIJIJJIIIJJJJIIIJI();

	[Obsolete]
	public static GameObject IJJJJIIIIIIIIJIIJIIJJJJJIJJJJIJIJJIIJIJIJJJJJJI
	{
		get
		{
			return IJJJIIIJJIJIJJIJIIJJJJIIIJIIIJJJJJJJJIJJJIJJIIJ();
		}
		set
		{
			JJIIJJJIJIIIIJJIJIJIJJJIJIIIJJIJJIIIJIIIJIJIIJJ(value);
		}
	}

	public static JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII JJJJIIIJIJIIIJIIIIIJJJJJIIJJJJJJJJIIJJIJJJJIIII => JJJIJJJIJIIIIJIIIIJIIJIIJIJJIJIJIIIJIIIJIIJIIJJ();

	public static JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII IIIJJJIIJJIIIIIJJIIJJIIIJIIJIIIIJIJJJJIJJIJJIJJ => JIJJJIIJIIIJJIIIIJIIJIIJIJJJJJJJIIJJJJIJIJJJIJI();

	public static JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII IJIIJJIIJJJJIJJIIJIIJJJJJIJJJJJJIJIJIJIJIIJJIJJ => IIJIIIJIIIIIJIJIIIJJIIIIIIIIJIJJIJJJJJJIJJJJJII();

	private bool IJIIJJIJIJIIIIJJIIIJJJJIIJJJIJIJIIIJJJIJIJIJJJJ => IIIJIIIIJIJJJIJJJIJJJIIJIJIJJJJIIIJJIIIIJIIIJII();

	public Camera IIJIJJJIJJJJJIJJIIJIJIIJJJIIIIIIIJIIJJJIJJJJIJI => IJIIIIJJIJJJIIJJJJJJIJJIIIIIJIJJJIJIIIJJIIJIJJI();

	public static GameObject JJIJIJJJJIIJIIJIJIIIIJJJJJJJIJIJJJJIJIIJIJIIJJJ
	{
		get
		{
			return JIIJIJIIJJIJJJJIJIJIIIJJIJIJJIIIJIJIIJIJJIIJJJJ();
		}
		set
		{
			JIJIJIIJIIIIIJJIIIIIJJJIIIJJJIIIIIJIIJJJJIJJIIJ(value);
		}
	}

	public static bool IIIIJIJIJJJIIIJIJIIIIIIJIJIIJJJJIIIJIIJJIJJIJIJ => JIJIJJIJJIIIJJIJJJJIJJIJJJJJIJIIJJIJJJJIJIJJIJJ();

	public static bool JIJIJIJJIIJIIJJIJJJJIJIIIIIIJIJJJIJIIIJIIJJJIIJ => IJJIIJJJIIJJIIJJJJJJJIIIJIJIIJIIIJIJIIIIJIIIIJJ();

	public static bool JIIJIJJIJIJJJJIIJIIIJJJJJJIIJJIIJJIIJJJIJIJJIIJ => IJJIIJJIIIJIIJJJJJIIIJIJIIJJIJJJJIJJJJJIJJJIIII();

	public static GameObject JIJIIIIIJJIIIJJIIIIJIJJJIJJIIJIIIIJIIIJIIJJJIJI
	{
		get
		{
			return JIIIIJJJJIIIJJJJJIIIJIIIJIJIIJIJJIIIIIIIIJIIIII();
		}
		set
		{
			IIIIJJJJIJJIIJJJJJIIIIIJJJIIIJJJJIIJIJIIIJJIIIJ(value);
		}
	}

	public static GameObject IIJJJJIIIIIIJJJJIJIIIJJIJJIJJJJJIIIJJJIJJIJJIJI
	{
		get
		{
			return JJJJIIIJJIJJJJJIIIIJIIJIIJJIJJIJIIJIIJJJIIIJJII();
		}
		set
		{
			IIJJIIJIIJJJJIIIIJJIIJJIJIIIIJIIIJIIIJJIJJJJIJI(value);
		}
	}

	public static GameObject IJJJIJIIJJIJJJIIJJIIJIJIJIJJJJJJIIIJJJJJIJIIIIJ
	{
		get
		{
			return IIJJJJIJIJIIJJIJIJIIIJJIIJJJJJIJIIIIIIJIJIJIJII();
		}
		set
		{
			JJIIIJIJJJJJIIJJIIIJIJJJIIIIIJJJIJIIJJJIJIIJIJI(value);
		}
	}

	[Obsolete]
	public static int JJJJJIIIJIJIIJJIJJIIJJIIIIIJIIJIIIJJIIJIIIJJIJI => IIIJIJIJJJIJIJJIJIJJJJJIJIJJIJIJIJJJIIIIJJIJIJJ();

	public static int IIIIJIJJIJIJJIIIJJJIJJJIIIJIJIJJJIIJIJJIJIIJJIJ => IJJIIJJIJJJIJJJIIIIJJIIIJIJJJIIIIIIIIIJIIIIIJIJ();

	public static Camera JIJIJJJIJJIJIJIIIJIIIIIJJIIJJIIIIIIIIIJJJJJIIIJ => IJJIJIIJIJIJJJIIIIJJIJIIIJJJJJJJJJJIIJIIJIIIIJI();

	public static UICamera JIJJIIIIJJJIIIIIJJJIIJJIIIJJJJJIIJIJJIJIIJIIIJI => IIIJJIIIIJJIIJJJJIJIJIIIIIIIJIJJJJIIJIIIIJIJJIJ();

	public static void IIIJIIJIIJIJJJJJIJIJIJJJIJIJJIJJIJIIJIIJJIIIJJI(float IIJJJJJJIIIIJJIIJJJJIIIJJIJIJJJIJJIIJIJIIIJJIJI = 0.5f)
	{
	}

	private void Awake()
	{
	}

	public static bool IJJIIJJIIIJIIJJJJJIIIJIJIIJJIJJJJIJJJJJIJJJIIII()
	{
		return false;
	}

	public static UICamera JIIJIIJIIIJJJIIJJJJIIJJIJIJIIJJJIJJIIJJIJIIIIIJ()
	{
		return null;
	}

	private static int IIJJIIJIJIIJIJIIIIJIJJJJIJIIJIIJJJJIJJIJIJIJIIJ(string JJJJJIIIIJJIIJIJIIJJJIIIIJJJIJJIJJJJJJIJJIIJJJI)
	{
		return 0;
	}
	public static JIIIIJIIIIIJIIJIIIJJJIIIJIJIJJIIJIJJJJIJJJIIJJI IJIJIJJJJJJJIIIJIIIJJJJIJJIJJIJIJJIIJIJJIIJIJIJ()
	{
		return JIIIIJIIIIIJIIJIIIJJJIIIJIJIJJIIJIJJJJIJJJIIJJI.Mouse;
	}
	private bool IIIJJJJJIIJJJIJJJJIJIJJJIJIJJJIJJIIIIJIIJJJIJIJ()
	{
		return false;
	}

	private bool JJJJJIJIIIJIIJJIIJIIIJJJJJJIJJJJIJJIIJJIIJIJIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return false;
	}

	private void IIIIJIIIJJJJIIIIIIJIJIIJJIIIIJIJJJIIIJJIJJJJIII(bool JIJJJJJIJIJJJJJIIJIIJIJIJIJIIJJIJIJIIJIJIIIJJIJ, float JJJIIJIIIIIIJJJIIJJJJIJIIJJIJIIIIJJIIJJJJJJJJJI)
	{
	}

	private void Update()
	{
	}

	public static Camera IJJIJIIJIJIJJJIIIIJJIJIIIJJJJJJJJJJIIJIIJIIIIJI()
	{
		return null;
	}

	private static Rigidbody JIJIJJIIIIJJJIJJIJJIIIJIJJIJJJJJJIIIJIIIIIIIJIJ(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ)
	{
		return null;
	}

	public static bool JIJIJJIJJIIIJJIJJJJIJJIJJJJJIJIIJJIJJJJIJIJJIJJ()
	{
		return false;
	}

	private static int JIJIJJJJIJIJJJJIIIIJIJJIIJJJJJJJJJIJJJJJJIIJJIJ(UICamera IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, UICamera JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	private static Rigidbody2D JJJJIJJIJIJIIIIJIJJJIJIIIJIJJJIJJIIJIJIIJIJJIJJ(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ)
	{
		return null;
	}

	private void OnDisable()
	{
	}

	public static bool IJIJJJIJIJJJJIJIIJJIJIIIJJJIIJIJJJJIJJJIJJJIJIJ(Vector3 JIJJIIJIIIIIIIJJJJJJIIJIJJJJJIJJIJJJJIJJIJIIIJI)
	{
		return false;
	}

	public static void JIJIJIIJIIIIIJJIIIIIJJJIIIJJJIIIIIJIIJJJJIJJIIJ(GameObject JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static GameObject JIIJIJIIJJIJJJJIJIJIIIJJIJIJJIIIJIJIIJIJJIIJJJJ()
	{
		return null;
	}

	public static JIIIIJIIIIIJIIJIIIJJJIIIJIJIJJIIJIJJJJIJJJIIJJI IJJIIIIIJIIJIIIJIIJJIJJJIJIJIIJIJIJIIJJIJIIIIJJ()
	{
		return JIIIIJIIIIIJIIJIIIJJJIIIJIJIJJIIJIJJJJIJJJIIJJI.Mouse;
	}
	public static GameObject IJIIIIJIIIJIIJJJJIJIJJJJJJJJIJJIIIJJIIIIJJJIJIJ()
	{
		return null;
	}

	public static void JIIJJJIIIJIJIJJIJIJJJJJJIJIJIIIJIIIIIJJJIJIIIIJ(JIIIIJIIIIIJIIJIIIJJJIIIJIJIJJIIJIJJJJIJJJIIJJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JJIIIJIJJJJJIIJJIIIJIJJJIIIIIJJJIJIIJJJIJIIJIJI(GameObject JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJJIIJIIIIJIIJIIIIJJJIJJJJJJIJIJJJJIIIIIIIIIJII()
	{
	}

	public static GameObject JJJJIIIJJIJJJJJIIIIJIIJIIJJIJJIJIIJIIJJJIIIJJII()
	{
		return null;
	}

	public void JIIIJIJIIIJIJIIIJJIJIIIIJIIJIJIIJJJIIIIIIIJIIJI(bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI, bool JJIJIJJIIJJJJJIJIJIIIIJJJIJJJJIJJIIJIJIJIIIJIJJ)
	{
	}

	public static bool IJJJIIJIIIIIIJJJJJIJJIIIJIIIJIIJIJJIIIJJJJIIIJI()
	{
		return false;
	}

	public static Vector2 JJIIJJIIJIJJJIIJIJIJIIJIIJIIIIIJIIIIJIIIJIIJJJI()
	{
		return default;
	}
	public static GameObject IIJIIIIJIJIJJJIJJJIIIJIIJIJJIIIJIJJIJJIJIIIIIJJ()
	{
		return null;
	}

	public static GameObject IJJJIIIJJIJIJJIJIIJJJJIIIJIIIJJJJJJJJIJJJIJJIIJ()
	{
		return null;
	}

	public void JIJIIJJJJJJJJIIJIJIJJJIJIIIJJJJIJIIJJIIJIJJIJIJ()
	{
	}

	private void JIJJIJIJJJIJIJIJJJIIJIJIIJIIIIIIJJJIJJJJIIIJIII()
	{
	}

	public static int IIIJIJIJJJIJIJJIJIJJJJJIJIJJIJIJIJJJIIIIJJIJIJJ()
	{
		return 0;
	}

	public static void JIJIIIIJIIJIIIIIIIIJIIIJJIJIJIJJJJJIIIJJJJJJJJI()
	{
	}

	public static int IJJIIJJIJJJIJJJIIIIJJIIIJIJJJIIIIIIIIIJIIIIIJIJ()
	{
		return 0;
	}

	public static bool IJJIJJIIIIJIIIIJJIIJJIIJJIJIJIJJJIJIJIJJIIJIIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return false;
	}

	public static void IIJJIIJIIJJJJIIIIJJIIJJIJIIIIJIIIJIIIJJIJJJJIJI(GameObject JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJJJIJJIIJIJIJJJIJIIIJIIIIIIIJJIIIJIJJJJIIJIIII(bool JIJJJJJIJIJJJJJIIJIIJIJIJIJIIJJIJIJIIJIJIIIJJIJ, float JJJIIJIIIIIIJJJIIJJJJIJIIJJIJIIIIJJIIJJJJJJJJJI)
	{
	}

	public void JJJIJIIJJIIJJIJJIIJJIJIIJIIIIJJIIJIJJJJIJIJIIJJ()
	{
	}

	public static void JJIJJIIJIIJJJJJJIIJJIIIJJJJJJJIJJJJIJIIIJJJIJII(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void IJJJJIIJJIIIIIJJJJJIIIJIIIJIJJJIIIJJIJIJIIIJIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, string JJJJIJIJJIIIIIIIIIIIJJIIJIIJIJJJIJJIIJJIJJJJIJI, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
	}

	public static bool IIIIIIJJIIIJJJIIJIJIIIJIIJJIJIJIJIJJIIIIJJIIIII()
	{
		return false;
	}

	public static JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII JJJIJJJIJIIIIJIIIIJIIJIIJIJJIJIJIIIJIIIJIIJIIJJ()
	{
		return null;
	}

	private void OnEnable()
	{
	}

	public static bool JIJIJIIIJIIIIIJJJIIJJIIIJIIIIJJJJIIJIJJIIIIIJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return false;
	}

	public static bool IJJIIJJJIIJJIIJJJJJJJIIIJIJIIJIIIJIJIIIIJIIIIJJ()
	{
		return false;
	}

	public static bool IIJJJJJIJIIJJJJIIIIJIIJJJIIJIIIJIJIJJIIJIJJIJII()
	{
		return false;
	}

	public static JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII JIJJJIIJIIIJJIIIIJIIJIIJIJJJJJJJIIJJJJIJIJJJIJI()
	{
		return null;
	}

	public void JJIIIIJIIJIJIIJIJIIIJIJIIJIIIJJIIIJIIJJJJJJJJJI()
	{
	}

	public static Vector2 IJIIIJIIJIJIIJJIJJJJIJJJJIIIIIIIJIJJJIIJIJJIIJI()
	{
		return default;
	}

	public static bool IJIIJJIJIIJIJIJIJIIJIIJIJIJIJJIJJIIIJJIIJIJIIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return false;
	}

	private static bool IIIIIIIIIIJIJIJIIIIIJIJIJJIIJJJJIIIJJJJJIJJJIJJ(Vector3 JJJIJJJJJJJJJJJIJJIIJJIIIJIIIIIIJJJJJIJIJJIJIJJ, GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return false;
	}

	private void IJJIJIJIJIIJIJJJIJIJJIJJIJJIIJIIJIJIJIIJJJIJJIJ()
	{
	}

	public static void IIIJIJJJJJIJJIIIIIJJJIJIJJIJJIJIIJIIIIIIJIJJIII(JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII IJJJJJJIIIJJIJJIJJIJJIIJIIJJJJJIJJJJIIJJJJIIJJI)
	{
	}

	public static UICamera JIIJJIJIIJJJIJIIJIJIJJJJIIJIIIJIJJJIIIJJIIJJIJI(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ)
	{
		return null;
	}

	public static UICamera IIIJJIIIIJJIIJJJJIJIJIIIIIIIJIJJJJIIJIIIIJIJJIJ()
	{
		return null;
	}
	public static GameObject JJIJJJJJJJJIIJJIIJIIIJIIJJIIIJIIIIIJJJJJIIIJJII()
	{
		return null;
	}

	public static GameObject IIJJJJIJIJIIJJIJIJIIIJJIIJJJJJIJIIIIIIJIJIJIJII()
	{
		return null;
	}

	public static void JJIIJJJIJIIIIJJIJIJIJJJIJIIIJJIJJIIIJIIIJIJIIJJ(GameObject JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JIIIIIJJIIIIJIJJIJJJIJJIJIIJJJJIJJJIJJJIJJJJJJI(KeyCode JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static GameObject JJIJJIIIIIJJJIJIJJIIIIJJIIJIIJJJJIIIJIJJJJIJJJI()
	{
		return null;
	}

	private void Start()
	{
	}

	public static bool JJIJJIIIIIJIIJIIIIJIIIJIJIJJIJJJJJJJIIIIIJIJJJJ()
	{
		return false;
	}

	public static bool IIJIJJJIJJIJIJJJIJIJIIJIJJIJJIJJIIJIIIJIJIJIJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return false;
	}
	public static UICamera JIIJIJIIIIJJIJJJJJIJIJJIJJJIJJJJIJJIJIJIJJIJIIJ()
	{
		return null;
	}

	public static bool IIJIJIIJIJIJIJJIIJIJJIJJIJIJIJJIIJIIJIJIIJJIIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return false;
	}

	private static int IIJJIIJIJIIJIJIIIIJIJJJJIJIIJIIJJJJIJJIJIJIJIIJ(KeyCode IIJIJIIIJIIJJJJJIJIIJIJJJJIIIIIIJIJJIJJJJIJJIIJ, KeyCode JIJJIIIIJIIJIIIIJIJJIJIJJIIJIJIIIJIJJIIIIJIIJJJ, KeyCode IIJIJJIJIJJJIIIJIIIJJJJJIIJIIIJJIIIIIJIIIJJIIJI, KeyCode JIJIIJIJIJJJIIIIJIIIJIIIIIJIIJJJIJJIIIJIJIJJJIJ)
	{
		return 0;
	}

	public bool JIJJIJIIJIIJIIIJIIIJIIJIIJJJIIIJIJJIJJIIJJJIIJI()
	{
		return false;
	}

	public Camera IJIIIIJJIJJJIIJJJJJJIJJIIIIIJIJJJIJIIIJJIIJIJJI()
	{
		return null;
	}

	public static UICamera JJJJIJJIJIIJJIIJJJJJIIJIIIJJIJJJIJIIJJJIJJIJJJJ(int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ)
	{
		return null;
	}

	private static bool IIIIIIIIIIJIJIJIIIIIJIJIJJIIJJJJIIIJJJJJIJJJIJJ(ref IIJJJJJJJJIJJIJJJIJJIIIIJIIIJJJJIJIIIIIJIIIJJJI IJJJIIJIIIIJIIJIJJJJJJIIJIJJIJIIJJJJJJJIJJJJJII)
	{
		return false;
	}

	private static int IIJJIIJIJIIJIJIIIIJIJJJJIJIIJIIJJJJIJJIJIJIJIIJ(KeyCode IJJIJJJJIJJJJIJJIIIJJIIJJJJJIIJJJIJIIIIJIJJJIJJ, KeyCode JJJIJIJIIJIJIJJIJJJJIJJJJJJIIIJIIJJJIJJIIIJIJII)
	{
		return 0;
	}

	public static void IJJIIJJIIJIIIJJIJIJIIIJJIIJJJJIJJJIIJJJIJIIJIIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII IIJIIIJIIIIIJIJIIIJJIIIIIIIIJIJJIJJJJJJIJJJJJII()
	{
		return null;
	}

	public static Ray JIJIIJJIJIJIIJJIJIIJJJIIJJJJJJJIJIIIIIIIJJJIJJI()
	{
		return default;
	}

	private static int JJJIIJJJIIIJIIIJJJJJIIIJIJJJIJJJJJIJIIJJIIJJIJI(KeyCode IIJIJIIIJIIJJJJJIJIIJIJJJJIIIIIIJIJJIJJJJIJJIIJ, KeyCode JIJJIIIIJIIJIIIIJIJJIJIJJIIJIJIIIJIJJIIIIJIIJJJ, KeyCode IIJIJJIJIJJJIIIJIIIJJJJJIIJIIIJJIIIIIJIIIJJIIJI, KeyCode JIJIIJIJIJJJIIIIJIIIJIIIIIJIIJJJIJJIIIJIJIJJJIJ)
	{
		return 0;
	}

	public void IJIJJIIJIIIIIJJIIJJJIJIIJIJIIJJJIIJIIJJIIIIJIJJ()
	{
	}

	private void JIIJIJJJJJJJJIIIIIIIJIJIIJIJIIJIJJIJIJJIJIJIIIJ(bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI, float JIIJIJIJJJJIJIJJIJIJIIJJIJIJJIJJIIJJIJIIIIJIIII, float JJJIIJIIIIIIJJJIIJJJJIJIIJJIJIIIIJJIIJJJJJJJJJI)
	{
	}

	public static void JJJIIIIIJIJJIJJJJJIJJJJJJJIJIIJIJJIJJIJIJJJIIIJ(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void IIJJIIJJJIIIJJIJJIIJJJIIJJIIJIJJIJJJJJIIJJIIJIJ()
	{
	}

	public static void JJJJJJJJJJIIJJJJIJJJIJIJIJIJIIJJJJIJJIJJJJJJJJI(JJJJJJIIJJJJIIJJIJJJJJJIJIIIJJIJIIJIJIJJIIJIIII IJJJJJJIIIJJIJJIJJIJJIIJIIJJJJJIJJJJIIJJJJIIJJI)
	{
	}

	public static void IIIIJJJJIJJIIJJJJJIIIIIJJJIIIJJJJIIJIJIIIJJIIIJ(GameObject JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void LateUpdate()
	{
	}

	public static GameObject JIIIIJJJJIIIJJJJJIIIJIIIJIJIIJIJJIIIIIIIIJIIIII()
	{
		return null;
	}

	private bool IIIJIIIIJIJJJIJJJIJJJIIJIJIJJJJIIIJJIIIIJIIIJII()
	{
		return false;
	}

	private void JJIIJJIJJJIIJIJJJIJIIJJJIIIJIIIIJIIJJJJJIIIIIJJ()
	{
	}

	public static bool IIIJIJJJJJIJJIIIIIJJJIJIJJIJJIJIIJIIIIIIJIJJIII(Vector3 JIJJIIJIIIIIIIJJJJJJIIJIJJJJJIJJIJJJJIJJIJIIIJI)
	{
		return false;
	}

	public static int IIJIIJJJIJIJJIIJIJIJJJIIIIIJJJIJJJJIIIJJJIJIJJJ()
	{
		return 0;
	}

	public static bool JIIIJIJIJJIJJIJJIIJIIJJIJIJIIIIIJJIJIJIIJJJIJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return false;
	}

	public static KeyCode IIJIJIJJJJJJJJIJIIIJIIJJJIIIIIJJIJJJIJJJIIJIIJJ()
	{
		return KeyCode.None;
	}
}
