using System.Runtime.CompilerServices;
using UnityEngine;

public class UICenterOnChild : MonoBehaviour
{
	public delegate void JJIIIIJJIIJIIJJJJIIIJIIJIJJJJIJIIJIIJJJJIJIJIJI(GameObject IIIJIJJIIJIIIIJJIJJIJJIJIJIIJJJJJJIIIIJIIJIIJJI);

	public float JJIIJJJIIJJJIJJJIIJJIJIIIIIIJIIJJIJJIIJIIIJJJJI;

	public float IJJIJJJJJJJIJJJJIJIJIJIJIIJJJJIIIJIIIJIJIJIJIIJ;

	public SpringPanel.IJIJIJIIIJJJJJIJIIIJIIIIIJJIIJIJJIIIJIJIIIIJIIJ IJIIIIIJJIIJJJIIJIIJJIIIIIIIJIJIIJIIIJJJJJIIJII;

	public JJIIIIJJIIJIIJJJJIIIJIIJIJJJJIJIIJIIJJJJIJIJIJI JJIIJIIIJIIJJIJJJIJIIJJJIIJJJIIJJJIIJIJJIIIIJJJ;

	private UIScrollView IJJJIJJIJIJIJIJJJJJIJIJJJJIIJJJJIJJIIJIJIJJJJJJ;

	private GameObject JJIIJJIJJIJJIIIIIIIJJJIIJIJJIIJIIJJIJJIJIJJJIJI;

	public GameObject IIIJIJJIIJIIIIJJIJJIJJIJIJIIJJJJJJIIIIJIIJIIJJI => JIIJIIIIIIJIJJJJJJIIJJIIIJJJJJJIJIIJIJJIJJIIJII();

	private void IJIJJJJJJJJIJIIIJIIJIJIIIIJIJIIJJIJIJIIIJJJJJIJ()
	{
	}

	private void IJJJIJJIIIIIIJIIJJIJIJJIIIIIIIJIIIIIJIJIIJIJJJI(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, Vector3 JIIIIIJJIJJIJJIIIIIIJJJJJJJIJJJJJJIJIJIJIJJIJIJ)
	{
	}

	private void IIJIJIJIIJJIIIJIJJJJJJIJIJIJJJJIJJIJIJIIIIIJIIJ()
	{
	}

	private void JJIIIIIIJJJIJIIJIJJJJIIJIIIJIJJIJIJJIJJJIIJJIII(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, Vector3 JIIIIIJJIJJIJJIIIIIIJJJJJJJIJJJJJJIJIJIJIJJIJIJ)
	{
	}

	public void JIIIJJJJIJJJIJJJIJIIJIIJJIJIJIJJIIJJJJJJIJIJJJJ(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII)
	{
	}

	private void IIIIIJJJJIIJJJIJIJJIIIIIJJJJJIIIIJJIJIIJJJJJIII()
	{
	}

	public void JJIIIIIIJJJIJIIJIJJJJIIJIIIJIJJIJIJJIJJJIIJJIII(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII)
	{
	}

	private void OnValidate()
	{
	}

	private void JJJJIIIIJIJJJIJIJIIIJJIIIIIIJIIJIJJJJJIIIIIJJJI(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, Vector3 JIIIIIJJIJJIJJIIIIIIJJJJJJJIJJJJJJIJIJIJIJJIJIJ)
	{
	}

	private void IJJIJJIIIIJJIJJIIJJIIIJIIIJJJJIJIJJJIJIJIJIJJII()
	{
	}

	private void IIIIIJIIJJIIIIJIJIJIJJIIIIIIJIIJIIIIJJJJJJJIIJI()
	{
	}

	private void IIJJJJJIIJJJJJJJJJIIIIJIIJJJIIIIIJIIIJIIJIJJIJJ()
	{
	}
	public GameObject IIJIIJJIIJJJJIIIJIIIJIJJIIIJIIJJIIJJIJIIJIIJIII()
	{
		return null;
	}

	private void OnEnable()
	{
	}

	private void IIIIIJIJIJJJJJJIJIIJJIJJJIIJJJIJJIIJIIJIJIIJJIJ()
	{
	}

	private void OnDisable()
	{
	}

	private void JJJIIIIIIIJJIJIIIJJIIJJIIIJIJIJIIIJJJIJJJIJIIJJ()
	{
	}

	private void IJJJIJIIIIJIJJIIJIIJJJIJJJIJIIIJIIIJJJIJIJJIIIJ(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, Vector3 JIIIIIJJIJJIJJIIIIIIJJJJJJJIJJJJJJIJIJIJIJJIJIJ)
	{
	}

	private void IJJJIIIJJJIJIIIJJJIIJIIJIJIJJIJJIIIJIJJIJIJJIII(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, Vector3 JIIIIIJJIJJIJJIIIIIIJJJJJJJIJJJJJJIJIJIJIJJIJIJ)
	{
	}

	private void Start()
	{
	}

	private void JIIJIIJIJIIJIJIIJIIIJJIJIJIIIIIJJJJJJJIJIIIIIII()
	{
	}

	public void IIJIIJIIJJJJJJJJJJJIIJJIJIIIIIJIIJJJIJIJIJJIIII()
	{
	}
	public GameObject JIIIIIJJIIJJJJIIJIIJJIIJIJJIJIIJIIIIJJIIIIIJJJJ()
	{
		return null;
	}

	private void IIJJIJIJIJJIIJJJJJJIIJJIIJJIIJJJIIIIIIJIJIIIIII(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, Vector3 JIIIIIJJIJJIJJIIIIIIJJJJJJJIJJJJJJIJIJIJIJJIJIJ)
	{
	}

	private void JJIIJJJIIJIJIJIIJJJJIJIIJJIJIIIJJJIIIIJIJJIJJJJ()
	{
	}

	public GameObject JIIJIIIIIIJIJJJJJJIIJJIIIJJJJJJIJIIJIJJIJJIIJII()
	{
		return null;
	}

	private void IJIJJIIJJIJIIIJIJIIJJIJIIJJJIJJIIIJJJJJIJJJIIII()
	{
	}

	private void IJJIIJJIIJJIIJJJJJJIIIJJJJJIJIIJIJIIJIIJIIIIJII()
	{
	}
}
