using UnityEngine;

public class UIChangeTeam : MonoBehaviour
{
	public UIWidget IJJIIIJIIIIIJJIJJIIJIJJJJIIJIJJJIIJIJJJJJIJJIII;

	private bool JJIJIIJJIIIIIIIIJIIJJIIIIJJIJIIJIJJJJIJIIIIIJJI;

	private float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

	private bool IIIIJIIIJIIIJIJJIIIIJJIJJIIJIJIJIIIJJIJIIIJIJJI;

	private static UIChangeTeam JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void IIJIIIJIJIJJJIIIJJJJJIIJIIIJJJIIIIIJJJIIJIJIJJI(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI, bool JJIJJIIIJJIJJIJJJJJJIJIJJIJIJIJJJIJIIIIJJIIJIJJ)
	{
	}

	public static void JIIJIIIJIIIJIJIIJIIIIJIIJIIJIJJIIJIIIIJIJIJIJJI(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI, bool JJIJJIIIJJIJJIJJJJJJIJIJJIJIJIJJJIJIIIIJJIIJIJJ)
	{
	}

	private void IIIJJJIJIIIJJIJIIJJIIIIJIIIJJJIIIIIJIIIJJIIJJII()
	{
	}

	private void Awake()
	{
	}

	public static void IIJIIIJIJIJJJIIIJJJJJIIJIIIJJJIIIIIJJJIIJIJIJJI(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public static void IIJIIJIIIIJJIIIJJJJJJIIJIJIIJIIIIJIIJJIIIJJIIJI(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void IJIJIJIJJJIIJJIJJIIIJIJIIJIJIJIIJJJJIIIIJJJIIJI()
	{
	}

	private void OnDisable()
	{
	}

	public static void IJIJJJIIIJIJJIJJJJIIJIJJIJJJJJIIIIJJJIIJIIIJIII(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void JIJIIJJJJJIIIIJJJIIJJIIIIIJIJJJJIIIIIJJIJIIJJIJ()
	{
	}

	public static void JIIIIJJIJJJIIIJIIJIIIJJJIIJIJIJIIJJIIJJJIIJIJII(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public static void IJJIJIJIJIIIIJJIJIIIJIIJIIJIJIIJJIJJJIJIIIJJJIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI, bool JJIJJIIIJJIJJIJJJJJJIJIJJIJIJIJJJIJIIIIJJIIJIJJ)
	{
	}

	private void JIIIJJIJIJJIJJJIIIIJJJIJIJIJIIIJJJJIJJIIIIJJIII()
	{
	}

	private void IIJJIIIIJIIJJJJJIJIIIJJIJJJJIIIIIIIIIJIJIIIIIII()
	{
	}

	private void OnEnable()
	{
	}

	public void ChangeTeam()
	{
	}

	private void JIIIJJJJIIIJJJIJJIJJJJIIIJIIIIIIJIIJIIIIIIJIJII()
	{
	}

	public static void IIIJJJIIIJJIIJJIIIIJIJIIJIIIJIIIJIIJJJJJJJIJJJJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}
}
