using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using UnityEngine;

public class UIChat : MonoBehaviour
{
	public UIPanel JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ;

	public UILabel JJJJJIJJIIJIIJIJJIIJJIJIJIIJJJJIJIIJJJIIIJJJJJJ;

	public UIInput JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI;

	public UISprite JJJJJIJJJJIJIJIIJJJIIJIJIIJJIJIIIJIIIIIIJIIJIJJ;

	private StringBuilder IJJIJIJIIIJIIIIJJIIJIJIIJIIIJJJIJIJIJIIIJJIJJJJ;

	private List<int> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ;

	private static UIChat JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

	private float JIIJJIJJIJJJIJIJJIIJJIIJJIIIJJJIIJIJJIJIJJJJJJI;

	public static bool JJIJJIJIIJJIIIJIJIJJIIIJIJIIIJJIIJJJJJIIJIIJIII;

	public static float IIIIJIIJIIJIIJIJIJJJIJIIJJIJIJIJIIIIIJIJIJJJIIJ;

	public static List<string> IJIIJJJJIJIIIJJIIJIJJJJJIIIIIIIIIJIIIJIIIIJJJIJ;

	private void IJJIIJJJJJIIIJIIIIJJJIJIIIIIJJJJIJIJJJJIIIIJJJI(bool JIJJIIIJJJJIJIJJIJIJIIIJIIIJJJIJJJJJIJIIIJJIJJJ)
	{
	}

	private void IIJJIIIJJJIIIIIIIIIJIIIIJJJIIIJJJIIIIIIIJJJIIIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void JIIIJIIIIJJIJIIIIJJJJIJIJJIIJJIJJJJJJJJIIJJIIJJ()
	{
	}

	public static void IJIJIIIIJIJIIIIJIJIIJJJIJIJJJIIIIJIIIIJJJIIJJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void IIJIIJJJIIIJJJIJJIJJIJIJJJIIJIJJJIJIIIIJJJIIIJJ(bool JIJJIIIJJJJIJIJJIJIJIIIJIIIJJJIJJJJJIJIIIJJIJJJ)
	{
	}

	private void IIIIJJJIJIIIIIIJIIIIIJJIIJJJJJIJIIJJIIJJIIJIIJJ()
	{
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ()
	{
	}

	private void IJIJJJIIIIIIIJJJIJIIIIJIIIJIIJJJIJIJIIIJJJIIJJI(bool JIJJIIIJJJJIJIJJIJIJIIIJIIIJJJIJJJJJIJIIIJJIJJJ)
	{
	}

	private void Start()
	{
	}

	private void IIIIIJIIJJIIIIJIJIJIJJIIIIIIJIIJIIIIJJJJJJJIIJI()
	{
	}

	[CompilerGenerated]
	private void JIJJJJIJJJJIIIJJIJIIIIIJIJIJIJIJJIJIJIJIIIIIIII()
	{
	}

	private void OnDisable()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIIIIJIJIIIJIIJIJJJIJIJIJIJIJIJJIJIIIJJIIJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void OnSubmit()
	{
	}

	private void OnEnable()
	{
	}

	private void JJJJJJIIIIJIIIJJJJJJIJIJIJJIIJJJJIIJJIIIJIJIJJI()
	{
	}

	private void IJIIIIJJJJIIJIIIIIIJIIIIJIIIIJIJJJIIIIJJJJIIJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IIJIJIJJIIJIJJJIJJJJIIIJJIJJIIIIJJJJIJIJJIIJJIJ()
	{
	}

	public void JJJIJJIJIJJIIIJIIJJJJIJIJIJJIJJIIJJIJJIIJIJIIIJ()
	{
	}

	private void JIIJIIIIJIIIJJJJIIIJIJJIIJJJIJJIIJIJJJJIIJIJIJJ()
	{
	}

	public void JJJJIJJIJJJIJJIIIIIIIJIIJIJIIIIIIIJJJJJIIIJIIJI()
	{
	}

	public static void IJIIIJJJJIIJJIJJJIJJIIIJJIIJJIIJJJJIIIIIIJJJIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void IJIIIIIJJJIIIJIJJJJIIJIIIJJJIJIJJIJIIJIJIJIJJJJ()
	{
	}

	public static void IIIIIIJJJJJJIIJIIIJIJJIIIJJIJIIIIJJJIJJIJJIIJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void IJJJJJIIJJJJIIIJJIJIJJJJIJIIIIJJJJIIIJIIIJIIIIJ()
	{
	}

	private void JJIIJJJJJIJIJJJJJJIJIIJJJJJIIJJIJJJJIJJIJJJJJJI(bool JIJJIIIJJJJIJIJJIJIJIIIJIIIJJJIJJJJJIJIIIJJIJJJ)
	{
	}

	private void JJIIIJJJJIIIIJIJIJJJIIJJIJJIJJJJJJJIIIJIJIIJJJJ()
	{
	}

	private void IJIJJJJIIIIJIIJJIIIIJIJJJJJJIIIJIIIIJIJJIJIJIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}
}
