using System;
using UnityEngine;

public class UICloudMessaging : MonoBehaviour
{
	public UISprite JJJJJIJJJJIJIJIIJJJIIJIJIIJJIJIIIJIIIIIIJIIJIJJ;

	public UILabel JJJJJIJJIIJIIJIJJIIJJIJIJIIJJJJIJIIJJJIIIJJJJJJ;

	public float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ;

	public Transform JJIIIJJJJIIJIJIIJIJIJIJIJJIIJJIIIIJJJIIIIJJIIII;

	public Action IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ;

	private static UICloudMessaging JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void JIJJIJIIJJJIJIJIJIJIIIJIJIJJJIJIJJJIJJJJJIJIJIJ()
	{
	}

	private void IJIJIIJJIJJIJJIIIJIIJIIIIIIJJIJIIJJIIJIIJJJIJJJ()
	{
	}

	public void IJIIJJIJIIJIIJIIIJJJIJJIIIIJIIIJIIJJJJIIJIJJJIJ()
	{
	}

	public void IIIIIIJIIJJIIJJJJJIIJIIJIIJJIJJJJJIJIJJJJIIJIIJ()
	{
	}

	public void JIIJIIIJIIIJJJIJIIJIJIJJJIJIIJJJIJIIJJJJJJIJJIJ()
	{
	}

	private void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII()
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	public void IJIIJJJJIJIJJJIIIJJIIJIIIJJJIIJIIIIIIIIJJJJIJJI()
	{
	}

	public static void JJIJIIJIJIJJIIIIJJIJIJIIJJJIJJJJJIIIJIJJIIJJJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, Action IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ)
	{
	}

	public static void IIIJIJIJJIJIJJIJJJJIJJIIJJIIJIIJIIJJJJIJJIJIIJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public void OnClick()
	{
	}

	private void JIIJIJJIJIJJIIJIIJIIIJJIJJIIIJJJIIIIJJIIJIIJIJJ()
	{
	}

	private void IJIJIJIJJJIJJJIJIJJIJIIIJJJIJJIJJJIJIIJIJIJJJJJ()
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	public static void JJIJIIJIJJIIIIJJIJJIIJJJIJIIIIJJJIJJJIIJIIJIJJI()
	{
	}

	public static void JJIJJIJJIIIJIIJIJIJIIIJIIJIIJJIJJIIJIJJJIIIIJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, Action IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ)
	{
	}

	private void IJIIIIJIIIIJIJJJIJJJJJIIIJJIJJIJIIJJIJJJIIJIJII()
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, Action IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ)
	{
	}

	private void Start()
	{
	}

	public static void IJIJIIIJIIIJJJIIIIIIJIIJJJJJJJJIJJJJJJJIIJIIJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, Action IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ)
	{
	}
}
