using System.Runtime.CompilerServices;
using UnityEngine;

public class UIControllerList : MonoBehaviour
{
	public InputButton JJIIIIIIIIIIIJIIIIJIIJJJJIJJIIIJIJIJIIJIJJIIJJI;

	public InputButton JJJJIIIJJJIJIJIJIIJJJJIJJJJIJIIJIIIJJIIIJIIJIJI;

	public InputButton JJJIIJIJIIIIIIJIJJIJIJJJIIIJIJIIJJJIJIIJJIJIJJJ;

	public InputButton IJJIJJJIIIJJIIJJJIIJJJJIIJJIJJJIIJIIIJIIJIIIJJJ;

	public InputButton IJIIJJJIJIIIIJIJJJJJJIJIIIIJIJJJJIJIJIJJJIJJJJJ;

	public InputButton JJJIIJIIIJJIIJJIJIIIIIIIJIIIIJIJIJJIIJJJIIIIIII;

	public InputButton IIIIIIIIIIIJJIJIJIIJIIJIJJIJJJIIJJIJJJJIIIJIIJI;

	public InputButton JJJIJIJIIJIIIJIJJIIIJIIIIIIIIIJJJIIJIJIIJJJJJIJ;

	public UILabel IJJIIJIIJIJIIJIJJJJIJIIIIIJIIJIIJIJIIIIIIIIJIII;

	public InputButton IIJIJJIJIIJJJIJJIIJIIIIIIJIJIJIJJIJIIJJIJIIJJJJ;

	public InputButton IIJJJJIIIJIIIJJIIJJIIJIIIIIJJJJJIJIIIJIJJJIJIJI;

	public InputButton JJIJJIJIJIJJIIIIJIJIIJJIJIJIIJIJJIIJIJJIIIJIIIJ;

	public UIWidget JIJJIJJIJJJIIIJIIJJJIJIJJIIIIJJJIJJIJIJIIJJIJJI;

	public UILabel JJJIIJIJIIIJJJJIIJIJIIJIJJIIIIJIIIIIJIIIJJJIJIJ;

	public InputJoystick IIJIIJIIJJJJJIJJIJIJJIIJJJJIIJIIIIIIIIJJJIIIIIJ;

	public InputTouchLook JJJIIIIIJIJJIIIIIIJIJJJJJJIIJIJJIIJIJJJIIJJIJJJ;

	private static UIControllerList JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static InputButton JJJJJJJIIIIIIJIJJIIIIJJJIIJIIIJIIJJIIIIJIJIIJII => JJIJJIIJJJIJIIIIIIJIIJJJIJJIIIIIIJIJIIJJIIJJIJJ();

	public static InputButton JJIJIJJIIJJJIIJIIJIIIIIIJIIIJIIIIJJJIJIIJJIIJJI => JJIIJJIIJJJIJIIJJIIJJJIIIIIIJJJJIIJIJIJJIJJIJII();

	public static InputButton JJIJIJIJIJIIJIJIJJIJIJIJJIJJIJJIJIIIJJIJIJJIJIJ => JIJJJJIIIJJJJJIIIIJIIIJIIJJIIJIJIJIIJJJJIJIIJJJ();

	public static InputButton IIJIJIIJIJIJJIJJIJIIIIIJIIIJJJIJJIIIJIIJIIJIJIJ => JIIJJIJIIIJIIIJIJJIJJJJIIJJJJJIIJJIIIJJJJIIJIIJ();

	public static InputButton JIJIIIJJJIJJIIJJJJIJIJJJJJJIIIIIIJIJIIIIJJJJJII => JJJJIJIJIIJJJJIIIJJIIIJIIIJIIJIJIIIJJJJJIJIJJJI();

	public static InputButton JIJIIJIJJJIIJIIJIJJJJIIIIJIJJJIIJJJIIJJJIJJJIJJ => IIJIIJJJJJIJIIJIIIJJJIIJJIIJIJJIJJJIJIIIJIIJIIJ();

	public static InputButton IIJJJJIJJIIJJJIIJIJJJJIIIJIIIIIJIJJJIIIIJIJIIIJ => JJIIIJIJJIIJIJIIIIIIJIJJIIIIIJJIIIIJIJJJIJJIIII();

	public static InputButton JIJIJIJJJIJIIIJIIIJIIJIJIJIIIIIJJIIJJJJJIJIJJIJ => IIIJJIIJIJJIJJJJIIJIJIJIIIJIJIJIJJIJIJIJIJIIJJJ();

	public static UILabel JJJJJIJIJJJIJIJIIJIIIIIJIIJJJJIIIIIIJIJJJJJIIII => IJIIIIJIIIIJIJJIJJIIIIIJIJIIIJIJIJIIJIJIJIIIJJI();

	public static InputButton IJIJIJIJJIJIJIJIIJIJJJJIIJIJJIJJIJJJIJJIJIIIJIJ => JJIIIIIIJJIJJJJJJJIJJIJJJJIJJIIJJIIJJJIIIIJIJII();

	public static InputButton JIIJJJJJJJJIIJJIIIJJJJIJJJIJIJIIIIJJIIIJIJIIJIJ => IIIJJIJJJJJJJIJIIIJIIJJIJJJIJIJJIJJIIIJIIIIJJJJ();

	public static InputButton JJJIIJJJJJJJJIIIIJJIJIIIJIJJIJIIIJIIJJJIJIIJJII => IJIIIJJJJJJIJIJIJJIIJJJJIIIJIJJIJIJIIJIIIIIIIII();

	public static InputJoystick IJJIIJIIIJJIJJJJIJJIIJJIJIIJIIJJIIJJIIJIJJIJIJJ => JJJIIJIIIIJIIIIIJJJJJIJIIJIJIJJIJIJIJIIIIJIJJII();

	public static InputTouchLook JIIIJJJJJJJIIIJIJJIJIIIJJJIIJJJJIIJJJIIIIJJJJII => JIIJIIJIIIJJIJIJIJIIIJJIJJIJJIJIJIJIIIJIIIJJJJI();

	public static UILabel IIIJJJIIJIJIJJJJIIIJJJIJIIJIJJJJJJIIJIJJJJJJJJJ => JJIIJJIIJIIIJJIIJJJIJJJIJJJJIJJJJJJJIIJIJJJJIJJ();

	public static UIWidget IIIIJJJIJJJJIIJJJIJIIJIJIIJJJJIIJIJIIJIJJJJIIIJ => IIIIIJJJIJIJIJJJJJJIIIIIIIIIIIIJIJJIJJIIJIJIIJJ();
	public static InputButton IIJIIJJJIJIJIIIIJJJIIJJIJJJJJJIIIIJIIJIJIJJIJII()
	{
		return null;
	}
	public static InputButton IJJJJIIIJJIJIIIIIJJJJJIJIIIIIIIJIJJIIIIIIJIJIJJ()
	{
		return null;
	}

	private void Awake()
	{
	}

	private void JIJJIIIJJIJIIIIIJIIJIIIIJJJIJIIIIJJJJJJJJIIIIIJ()
	{
	}
	public static InputButton IIJJJIJIJIIIJIIIJJJIJJIIIIJIIJIJJJJIJJIJIJJIIJJ()
	{
		return null;
	}
	public static InputButton IIIJIIIIJIIIJJJIJIJIIIIIJIIIIJIJIIJJJJJJIJJJIIJ()
	{
		return null;
	}

	public static UIWidget IIIIIJJJIJIJIJJJJJJIIIIIIIIIIIIJIJJIJJIIJIJIIJJ()
	{
		return null;
	}
	public static InputButton JIIJIIIIJIIJIJJIJJIJJIJJJIIIJIJIJJJJIJJJIJJIJJI()
	{
		return null;
	}

	private void JIJJIJIIJIIIJJIIIJIJIIIIIIJIIIIIIJJIIJJIJJJIIJI()
	{
	}

	public static InputButton JJIIIIIIJJIJJJJJJJIJJIJJJJIJJIIJJIIJJJIIIIJIJII()
	{
		return null;
	}

	private void JIIIIJJJIIIIIIJIIIJJIIIJIIIJIJJIIJJIJJJJIJJJIJI()
	{
	}

	public static InputButton IIIJJIIJIJJIJJJJIIJIJIJIIIJIJIJIJJIJIJIJIJIIJJJ()
	{
		return null;
	}

	private void Start()
	{
	}

	public static InputButton IIIJJIJJJJJJJIJIIIJIIJJIJJJIJIJJIJJIIIJIIIIJJJJ()
	{
		return null;
	}

	public static InputButton JJIJJIIJJJIJIIIIIIJIIJJJIJJIIIIIIJIJIIJJIIJJIJJ()
	{
		return null;
	}
	public static InputButton JIIIJIIJIJIIIIIIJJIIJJIJJJJJIIJJJIIIJJIJJJIIIIJ()
	{
		return null;
	}

	private void JIJJIJJJIJJIJIJIJIJJJIJJJJIJJIIJJJJJIIIJIJIIIJJ()
	{
	}
	public static InputButton JIJJIIJJIJIIIJIIJJIJIIJIIIIJJJJIJJJJIJJIJIJIJIJ()
	{
		return null;
	}

	public static InputButton JJIIJJIIJJJIJIIJJIIJJJIIIIIIJJJJIIJIJIJJIJJIJII()
	{
		return null;
	}

	public static InputTouchLook JIIJIIJIIIJJIJIJIJIIIJJIJJIJJIJIJIJIIIJIIIJJJJI()
	{
		return null;
	}

	public static InputButton JJIIIJIJJIIJIJIIIIIIJIJJIIIIIJJIIIIJIJJJIJJIIII()
	{
		return null;
	}
	public static InputButton JIIIIIIIJJIJIJIIIJJIIIJIIJIIJIIIIJJJJJJJIJJIJII()
	{
		return null;
	}

	private void JIIIJJIIJIJJJJIJJIIJJIJIIIJJIIIJJIJJJIJIIJIJIJJ()
	{
	}

	public static InputButton IIJIIJJJJJIJIIJIIIJJJIIJJIIJIJJIJJJIJIIIJIIJIIJ()
	{
		return null;
	}

	public static InputButton IJIIIJJJJJJIJIJIJJIIJJJJIIIJIJJIJIJIIJIIIIIIIII()
	{
		return null;
	}

	public static InputJoystick JJJIIJIIIIJIIIIIJJJJJIJIIJIJIJJIJIJIJIIIIJIJJII()
	{
		return null;
	}

	public static InputButton JIIJJIJIIIJIIIJIJJIJJJJIIJJJJJIIJJIIIJJJJIIJIIJ()
	{
		return null;
	}

	public static UILabel IJIIIIJIIIIJIJJIJJIIIIIJIJIIIJIJIJIIJIJIJIIIJJI()
	{
		return null;
	}

	private void IJIJJIJIIJJIJIIJIJJJJIJIIJJIIIJJIIIJJJIIJJIJJJJ()
	{
	}

	public static UILabel JJIIJJIIJIIIJJIIJJJIJJJIJJJJIJJJJJJJIIJIJJJJIJJ()
	{
		return null;
	}
	public static InputButton JJIIJIIJJIIJJJIIIJJJJJIIIIIJJIIJJIIJJIJIJIIIJJJ()
	{
		return null;
	}
	public static InputJoystick IIIIIIJIIJJJJIJIIIIIIIIIJJJIIIIIIJJIJIJJJIJJJJJ()
	{
		return null;
	}
	public static InputButton IIJJJIJJJIJJIIIIIJIIJIIIJJJIJIJIJIJJJJIJJJIIJIJ()
	{
		return null;
	}

	public static InputButton JIJJJJIIIJJJJJIIIIJIIIJIIJJIIJIJIJIIJJJJIJIIJJJ()
	{
		return null;
	}

	public static InputButton JJJJIJIJIIJJJJIIIJJIIIJIIIJIIJIJIIIJJJJJIJIJJJI()
	{
		return null;
	}
}
