using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class UIControllerSettings : MonoBehaviour
{
	private static Action JIJJJIIIIJIIJIIIJIIJJIJIIIJIIIIJIIIJJJIJJJIJJII__BackingField;

	private static Action IJJJJJJJJJJIIIIJJIJJJIIIIIJJIJIIJIIJIIIIJIJJIIJ__BackingField;

	public UISprite IIIIJJJIJJJJIIJJJIJIIJIJIIJJJJIIJIJIIJIJJJJIIIJ;

	public UISprite IJJIIJIIIJJIJJJJIJJIIJJIJIIJIIJJIIJJIIJIJJIJIJJ;

	public UISettings IJJJJIJJIIJIIJJIJJIIIIIJIIIJJJJIJJIIIJIIIJJJJIJ;

	public static event Action JIJJJIIIIJIIJIIIJIIJJIJIIIJIIIIJIIIJJJIJJJIJJII
	{
		add
		{
			JJJIJIIIIIIJIJIJJJJJJJJIJJIIIIIJIIIJJIIIJIJIIIJ(value);
		}
		remove
		{
			IJIJIJIJIJJJJJJIIJJIIIIJJJIJJJIIIJJIIJIJIJIIJIJ(value);
		}
	}

	public static event Action IJJJJJJJJJJIIIIJJIJJJIIIIIJJIJIIJIIJIIIIJIJJIIJ
	{
		add
		{
			IIIIIJIJJIJJIJJIJIIIIIIIJJJJJIIIJJIJIIJIJJJJJJI(value);
		}
		remove
		{
			JJJJIIIJIJIIIJJJJJIJJIJJIJJIIIIJIIJJIIIIJIJJIIJ(value);
		}
	}

	public void IIIIJJJIJIIIJJJIJJIJIIJIIJIIJIIIJJJJJIJIIIJJJJJ()
	{
	}

	public void JJJIIIJJIIJJIJJIIIIJIIIJJJJJJJIJIIJIIIIIJJIJJJI()
	{
	}

	private void IJIIJJJJJIIIJJIJIIIIIIIIIJIJIIIIIJIIIIJJIJJJIII()
	{
	}

	public void JIJIIJJJJJJJJIIJIIIJIJJJJJJIJJJIJJIIJIJJIJJIJJI()
	{
	}

	public static void IJIJIJIJIJJJJJJIIJJIIIIJJJIJJJIIIJJIIJIJIJIIJIJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void IIIIIJIJJIJJIJJIJIIIIIIIJJJJJIIIJJIJIIJIJJJJJJI(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static void JJIIJIJJJJIJJJIIIJJIIJIIIIIJIIIIIIJJJJIIJIJJJIJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JJJIJIIIIIIJIJIJJJJJJJJIJJIIIIIJIIIJJIIIJIJIIIJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJIIIJIJJJIJJIJJJJJIJJJJJJIIJJIIJIJIJIJIIJIIIIJ()
	{
	}
	public static void JIIJIJJJIJJJJJJJJJJIIIIIJIJIIJJIJIIIJIIJJIJIJIJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIJIIIJJIJIJIIIIIJIJIIJIJIIJJJJIIIJIIIIIIIIIJII()
	{
	}

	public void OnOpen()
	{
	}

	public void IJIJJJJJIIIIJJJJIJIJIJIJJIJIIIIJIIJIJJIJJJIIJIJ()
	{
	}

	public static void JJJJIIIJIJIIIJJJJJIJJIJJIJJIIIIJIIJJIIIIJIJJIIJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static void IIIJJJIJJIIJJJIJIIJJJJJJIIJJJJIJJIIIIJIJIIIIJII(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJJJIIIJJIJIJIIJIIIIIIJJJJIIJIJIJIJIIIJJJJJIJI()
	{
	}

	private void IIIIIJIIJJIIIIJIJIJIJJIIIIIIJIIJIIIIJJJJJJJIIJI()
	{
	}

	public void OnDefault()
	{
	}

	private void OnEnable()
	{
	}

	public void OnBack()
	{
	}
	public static void JIJIJJIIIIIIJJIIIJJIJIJIIJJIJIJIIJJJJIIIJIIJIIJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJIIIIJIJIJIJIIJJJJJJIJIIIIJJIIJIJJIIIIJJJIIII()
	{
	}

	private void JIJIJIIIJIIJJIIIIIJJIJIIIIJJJIJIJJIJIJIIIIJIJJI()
	{
	}

	[CompilerGenerated]
	private void JJJJJIJIJJIJJIIJIIIJIIIIJIIJJJIIIIIIIJIJJIJIJIJ()
	{
	}
}
