using System;
using System.Collections.Generic;
using UnityEngine;

public class UIColorPicker : MonoBehaviour
{
	public static UIColorPicker JIIJIIIIIIIIIIJIJIIIJJIIJJJIIIJJIIIIIIIIJIJIJIJ;

	public Color JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI;

	public UIWidget IIJIIIIJJJJJJJIJJIJJIIIIIJJJIIIJIIIIIJJIJIIJJJJ;

	public List<EventDelegate> JIIJJJJJJJIIJJIJJJIIJJJIIIJJJIIJJJJJIIJJJIJJJII;

	[NonSerialized]
	private Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	[NonSerialized]
	private UITexture JJJIJJIJIIIJIIIIJJIJJIIJJIIIJJIIIIJIIIIJIJJIJJJ;

	[NonSerialized]
	private Texture2D JJJJIIIIJJIJJIIJIIJIIJJJJIIJJJIIJJJIJJJIJIJJJJI;

	[NonSerialized]
	private UICamera IIIJJJIIJIIJIJJIJIJIIJJIIJIIJIJIJIIIJIJIJJIIJII;

	[NonSerialized]
	private Vector2 JJIIIJJJIIIJIIIIJIJIIJIIJJIIJJIIJJIJIJJJJJIIJII;

	[NonSerialized]
	private int JJJJIIJJIIJJIJJJJJIJJJIIJJJIIIJIJIIJIJJJIIIJJJI;

	[NonSerialized]
	private int IIIIIIJJJJJIIIJIIIJIJJJIJJJIJIIIJIIJIJJJJJIJJJJ;

	private static AnimationCurve IJIJJJJIIIJIJJIJJJIIIJJJIIIJJJJIIIIJJIJJIIIIIJI;

	private static AnimationCurve IJIIJJJJJJJJJIJJIJJJJIJJIJJJIIIJIIIIIJJJIJIIIJI;

	private static AnimationCurve JIIIIIIJJIJIIIIIIJJIIJJIIJJJJIIIIIIIJJIIIJIJJJJ;

	private void JIIJJIIJJIIJIIIIIIIJIJJIIIIIJIJIIIJJJIIJJIJJJII()
	{
	}

	public void IIIIIIJJIIJIJJIIIJJIJJJJJJIJJJJIJIIIJJIIJJIJJIJ(Vector2 JIIJJJJJJIIJJIJIIIIIIJIIJIIIIIIJJJJJIJIIIJJJIJI)
	{
	}

	private void JJJIIIIIIJJJIIJIJJIJIJIJJIIIIIJJIJJIIJIJIIIJJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IJJJJJJJJIJJJIIJJJIIIJJIIJIIIJJIIJIIIJIIJJJJIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void IJJIJJIJIJIJJIIJJIIIJIJIIJJJIIIIJIJJJJJIJIIIJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	private void IIJJIIIIJIIJJJJJIJIIIJJIJJJJIIIIIIIIIJIJIIIIIII()
	{
	}

	private void JJIJJJJIIIJIIJIJJIJJIJIJIIIJIIIIIIIJJJIJIIIJJII()
	{
	}

	public void IIIJIIIJIJIIIJIIJIIJJIJJIJIIJIIJJIJIJJJJJIIJIJJ(Vector2 JIIJJJJJJIIJJIJIIIIIIJIIJIIIIIIJJJJJIJIIIJJJIJI)
	{
	}

	private void JJIJJJIJJIJIJIIJJIJIIIIJJJJIIIJJJIJJJJIJJJJIJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IIJJIIIIJJIIIJJJIIIIJJIIIJIJIJJIIJJJIJJIIIIIJJJ()
	{
	}

	private void Start()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	public static Color JIIJJIIJJIIJIIIIIIIJIJJIIIIIJIJIIIJJJIIJJIJJJII(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI)
	{
		return default;
	}

	public Vector2 IJJJIJJIJIJJJIIIIIIIJIIIJJJJJJJIJJJIIIJIIJIJIIJ(Color IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
	{
		return default;
	}

	private void IJIJJIIIIIJIJIJIIJJIIJJJJIIIJIJIIJJJJIIIJJIIJII()
	{
	}

	private void IJJJIIIIJJJJJIJIJIIIIIIJIJIJIJIJIJIIJIJJJJJJJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	public void IJJJIJJIJIJJJIIIIIIIJIIIJJJJJJJIJJJIIIJIIJIJIIJ(Vector2 JIIJJJJJJIIJJIJIIIIIIJIIJIIIIIIJJJJJIJIIIJJJIJI)
	{
	}

	private void IJJIIJJJJJIJJIIIIJJIJJJJJIIJIJJIIIIIJIIJJIIJIJI()
	{
	}

	private void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	private void OnDestroy()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void OnDisable()
	{
	}

	private void JJIIJJIJJJJIIJIJJJIIIIIJJJIIJJJIIJJJJJJJIIJIIJI()
	{
	}

	private void JIIIIIJIIIIJJJJIJIIJIJJIJIIIIIIJJJJJIJJIIJIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void OnEnable()
	{
	}
}
