using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;
using UnityEngine;
using UnityEngine.UI;

public class UIConsole : MonoBehaviour
{
	public enum JIJIJJJIJJJJJJJJIJJIJJIIIJJIIJJIJIIJJIJJIIJJJII
	{
		None = 0,
		Int = 1,
		Float = 2,
		Bool = 3,
		String = 4,
		Vector2 = 5,
		Vector3 = 6,
		Color = 7
	}

	public class IJIJJIIJJJJJJIJJIJJIIIJJJJJJIIJJJIIJJIIIJJIJJJJ
	{
		public JIJIJJJIJJJJJJJJIJJIJJIIIJJIIJJIJIIJJIJJIIJJJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI;

		public MethodInfo JJIJIJJJIIIIIJIJJJIIJJIJIIIJIJIIJIJIIJJJJJIJJJJ;
	}

	public GameObject IIIIJIIIJIJJJJIIJJJIIIIIIJJJJJIJJJJJJIIIJIIJIJI;

	public Text IJIJJIJJJJJIJJJJIIIIIJJIIIJJJIJIJJJJJIIJIIJJJJJ;

	public InputField JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI;

	public GameObject IJIIJJIJJJIIIJJJIJJIJIJIJIJIJJJIIIIJJIJJIJIIIII;

	public Text IJIIJIJIIIJIJJIJJJJJJIIIIJIIIJIJJJIIIIJJIIIJJIJ;

	public RectTransform JIJJIJIIIIJJJIIIIJIJJJJJJJJJIIJIIIIIJIIIJJJJJJI;

	private List<Text> IIJJJIJIIJJJIJJIJIIIJJJJJIIJJIJJIJJJJIJIIJIJJIJ;

	private List<Text> JIIJIIIIJJJIJJIIJJIJIJIJIIJJIIIJJIIJJJIJJIJIJJI;

	private static Dictionary<string, IJIJJIIJJJJJJIJJIJJIIIJJJJJJIIJJJIIJJIIIJJIJJJJ> IIIJJJIIIJJIIIIJIIJJIIJIIIJIJJJIJIIIIJIJIJJJIIJ;

	public static bool JJIIJJJIJJJJIJIIJIIIJIJIJJJJIIIIJJIIIIJIIIJJIJI;

	private StringBuilder IIJIIIIIIJIIJJJJIJIJJIIJIJJIIJIJIJIJIIIJJJIIJII;

	private StringBuilder IJJIJJJJIIIJJJIIJIIJJIJIIJIJJIJJIJIJIJJJIIIJIII;

	public void OnClear()
	{
	}

	private void IJIJIIJIIJIJJIJJJIJIIIJJIIJJIJJJIIJJIJJIJJIIJIJ()
	{
	}

	private void JJIIIIIJIJIJJJJJIIJIIJJJJJJIIIIIJIIJJJIIIJIJJJI(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ, string JJIJIIJJIJIJJIIIIJIJIJJIJIIJIJJJJJJJJJIIIIIIIJJ, LogType JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
	}

	public void OnSubmit()
	{
	}

	private string[] JIJJIIIJJJIJJIIJJJIJJIIIIJJJJIJJIIJJJIIJIIJIJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
		return null;
	}

	private Text IJJJIJIIIIJIJJIIIJIJIJIJJIIJIJIJIIIJJIIJJIIJJJI()
	{
		return null;
	}

	private void IJJIIJIIIJJIJIJIIIIIJJIIJJIIIIJJIIJJJJJIJJJIJIJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ, string JJIJIIJJIJIJJIIIIJIJIJJIJIIJIJJJJJJJJJIIIIIIIJJ, LogType JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
	}

	public void OnInputValueChanged()
	{
	}

	private static JIJIJJJIJJJJJJJJIJJIJJIIIJJIIJJIJIIJJIJJIIJJJII IIIIJIJJIJIJJJJJJJIIJJIJIIIIJIJJIIJJJIIJIIIIIJI(Type JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return JIJIJJJIJJJJJJJJIJJIJJIIIJJIIJJIJIIJJIJJIIJJJII.None;
	}

	private static JIJIJJJIJJJJJJJJIJJIJJIIIJJIIJJIJIIJJIJJIIJJJII JJJJJIIJIIIJJIJJIJIIIIIJIIJIIJJJJIIIJIIJJIJIJJI(Type JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return JIJIJJJIJJJJJJJJIJJIJJIIIJJIIJJIJIIJJIJJIIJJJII.None;
	}

	private void Update()
	{
	}

	private void IIIIJIJJIIIJJJJJIIIIIJIJJJJIJJIJIJJIJJIJIJIJJII()
	{
	}

	public void OnSelectCommand(Text text)
	{
	}

	public void JIJIIIIJJJJJJJIIIJJIIJJIIJIJJIIJJJJJIIJJJJIIJII(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIIJIJJIJJJJJJJJJJIIJIJJJIIJIJJIIIIJIIIIIJIJJJJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ, string JJIJIIJJIJIJJIIIIJIJIJJIJIIJIJJJJJJJJJIIIIIIIJJ, LogType JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
	}

	private void JIIJIJJIIIIJJJJIIJJJJJJJIIIIIIIJIJJIJJIIJIIJIJI()
	{
	}

	public void IJIIIJJIIJJIJIJJIIJIIIIJJJJJJIJJIJIIIIIIJIJJJJJ()
	{
	}

	private void JJIJIJIJIIJJJIIIJIJJIIJIJIIIJIJIJIIJJIJJJIJIJII()
	{
	}

	private void JIIIJJJIJJJJJJJIIJIIIJJJJJJJJJIIJJJIJJIJJIJIIJJ()
	{
	}

	private void IJJJJIIIJIIJJJJIIJIIJIJJIJJJJIIJIIJIIJJIIJJJJII()
	{
	}

	private bool IIJIJIIJJJJJJIIJIIJJJIJJJJJJIJIJJJIJIJJIIJIIIII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, out object JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, JIJIJJJIJJJJJJJJIJJIJJIIIJJIIJJIJIIJJIJJIIJJJII IJIJJIIIJIJIIIJIJIIJIJJIJIIIJJIJJIIIIIIJIIJJJII)
	{
		JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ = null;
		return false;
	}

	private void Start()
	{
	}

	public void IJIJJJIJJIJJIIIJJIJJJIIJIIIJIJJIIIJJIJJJJIJJIJI(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void IIIIJJJIIJIIJIJJJJJIIIJJIJIIJJJIIIIIJIIJIJJIIJI(Text text)
	{
	}

	public void JIJIIIIJIIIJJIIIIJIIJIIIJJIJIIJIIJJIJJJJIIIIIII(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private Text JJJIIIIJIJJJJJJJIJJJJJIJIIJJIIJIIIIIJJIIJJIIIJI()
	{
		return null;
	}

	public void JIJJIJIIJIIIIJJJJIIIIJJIJIJJJIJJIIJIJIIJJJJIJII(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private static JIJIJJJIJJJJJJJJIJJIJJIIIJJIIJJIJIIJJIJJIIJJJII IJJJIIJJJIJIJJJJJJJJJJJIJIJJJIIJIIJJJIJIJJIIJII(Type JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return JIJIJJJIJJJJJJJJIJJIJJIIIJJIIJJIJIIJJIJJIIJJJII.None;
	}

	private void JIIIJJJIJIIIJJJJIJIJIJJJJIIIJIIIIIJIIJIIIIIIIJJ()
	{
	}

	private void IIJJJIIIJJJIIIIJJIIJIIJJJJIJIIJJIIJJJJJJIJIIJIJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ, string JJIJIIJJIJIJJIIIIJIJIJJIJIIJIJJJJJJJJJIIIIIIIJJ, LogType JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
	}

	private static JIJIJJJIJJJJJJJJIJJIJJIIIJJIIJJIJIIJJIJJIIJJJII IIJJJJIJIJJJIJIJIIIIJJIIJJIIIJJIIJIJJJJJJJJIJJJ(Type JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return JIJIJJJIJJJJJJJJIJJIJJIIIJJIIJJIJIIJJIJJIIJJJII.None;
	}

	public void JIJIJJIIJJIJJIIJIIIIJIIIJIJJJJJJJIIJIIJJIIIIJJI(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void JJIJIJIJJJJIIIJIIIIJJJJJIJJIIIIJIJJJJIJIIJIJJJJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJIIIJIJJIJJJIIIJJJJJJIJJIJIJIJIJIIJJJJIIIJIIJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ, string JJIJIIJJIJIJJIIIIJIJIJJIJIIJIJJJJJJJJJIIIIIIIJJ, LogType JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
	}

	private string[] IIIJJJJIIIJIJIIJJIIJIIIIJJJJIIJIJJJIIJIIIJIIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
		return null;
	}

	public void IJIJJIIIJJIJJJJJIIIIIJJJIIIJJJJIJJIIJJIIJIJIJIJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}
}
