using System.Runtime.CompilerServices;
using DG.Tweening;
using UnityEngine;

public class UICrosshair : MonoBehaviour
{
	public GameObject JJIIIJIJJIJIIJIJJJJJJIJJJJJIIIJJIJJJJIIJIIIIIII;

	public UISprite IIIJIIJIJIJIJJJJIIJIJJIIIIJJJJJJIJIIJIJIJJIJIIJ;

	public UISprite IIIJJIJJIIIJIIIIJJIJIJIIIIIJIJIJIIIIIJJJIIIJJJJ;

	public UISprite IJIJIIJJJIJJJIJJJJIJJJIIJJJIIJIIJIJJIIIJIJJJIJJ;

	public UISprite IIJIJIIJJJJIIJIJJIJJJJJJJJJJIIIJJJJIJJIJIIJIIIJ;

	public UISprite IJJIJIJIJJJIJJIIJIIIIIIIIJJJIJJJIIIIIJJJJIIJIJI;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII IJJIIIJIJIJIJIJJJJJIJJIIIIJIIJJJIIJIJJJJJIJJJJI;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JJIJIIIIIIIIIJJJJJIJJIJJJIJJJIIIJIJIJJIJIIIJIII;

	private Vector2 IJJIIJIIJJJJJJIIIJIJIJIJJIIIJJIJIIJIJIJJIIJJJIJ;

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JJJIJIJJIIIIIIIJIIIIJIIIJJJJIIJJIIJIIIJJJIJJJJJ;

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIJJJJJJJJIIIJJJJJIIIJJIIJIJJJIIIIIJJJJIIIIJJIJ;

	private Tweener JJIIIIJIIIIIJJIJJJJJJJJJIIJJIJIJJIJJIJIIIJIJIII;

	public UISprite IJIIIJJJIJIJIJJJJIJJJIJJJJIIIIJJIIJJJIIJIJJJJII;

	public UISprite IIJJJIJJJIJIIIIJJIJJIIIIJJJJJJJJJJJIJJIIIJJJIJI;

	public UISprite IIIIJIJJIJIIIJJJIIJJJIIIJJIIIJIJJJIIJIJJIJJIJIJ;

	public UISprite IIJJJJJIIJJIJJJIIJJIIIIIIJJJJIIIJIJIIIJJJIJJJII;

	public float IIJIIJJIIJIJIJJIJJJJIJIIJJIIJIIJJIIJJIJIJJIJIIJ;

	private Tweener IJIJIJJIJJIJJIIJJIJJJJJJJIIJJIJIIJIJIJIIIJJIIIJ;

	private float IJJJIIIJJIJJIJIIJIJIIJIJIJJJIIIIJJJJIJIIJJIIIJI;

	private bool IJIIIJJJIJJIJJJJIJJIJIJIIIJIIIJIIIIJIJJIIJJIIJJ;

	public UIWidget[] IIJJIIJJIIIIIIIIJJJIIIIJJIIJJIIJJIIJJJJIIIJIIIJ;

	public InputButton IJIIJJJIIIIIJIJIIJIIJJIJJJIIIIIJJIIJIIIIIJIIIJJ;

	private bool IIJJJIIJJJJJIIJIJJJIIJIIIJJJIJJJJJIIJIJIJJIJIJI;

	public int IJJJJIIIJJJIJJJIJIJJJJIIIJJIJIIJJJIIJJIIIIIJIJI;

	private bool JIJIJIIJJIJIJJJIJIIJIIIIJIIIJJIIIJJJJJJJJJIIIJI;

	private static UICrosshair JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void JIIJJIJJIIJJJJJJJIIIIIJIJIJJIJIIIJJIJIJJIJJIJJI(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
	{
	}

	private void Start()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	public static void IIJIJJJIJJIJJIJJJIIIIIJIIJIJJJJIJIIIJIIJIJJIJII(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void IJJJJJJIJJIIIIJIJIJJJIIIJJIIIIJJIJIIJIIIIJJJJIJ()
	{
	}

	public static void IIIJJJJIIIIJIIJIJIIJIJIJJJJJJJJIIJIJIJJIJIIIIJJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void JIIJJIIIIIIIIIJJJJIIJIIIIJIIIJJIIIIIIIJJJIIIIJJ()
	{
	}

	private void OnEnable()
	{
	}

	[CompilerGenerated]
	private float JIJJIJIJIJJJIIIIIJIIIJJIIJIJIIJIJIJIJJJIJIJJJJI()
	{
		return 0f;
	}

	public static void JJIJIJJJJJJIIJJIJJIJIIJIJJJIIJIJJIIIJJIJIIJIIJJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public static void JIJIJJJIJIIIJIJIJIIJIJJJJJIIIJIJIIIIIIIIJJJJIII(float IJIIJJJJIIJJIJIJJIIJJIIIJJIIIJIIJIJJJJIIJIJIIJI)
	{
	}

	private void JIJIIJIIJIIIJIJJJIIIJIJJJJJJJJJJJIIIIJJJJJJIJIJ()
	{
	}

	[CompilerGenerated]
	private void IJIJIIJJIJJJIIJJIIIJJIJJJIJIJJIJIJIIIJJJIJIJIII(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
	{
	}

	private void Awake()
	{
	}

	public static void IJJIIJJIIIJJIIIIIIIJJIJIIIJJJIJJJIJJJJIJIIIIIII(float IJJIJIJJJIJJJIIIIJJJJJIIJJIIJJJJJJJJJIJJJJJJJJI)
	{
	}

	private void JJJJIIJIJJJJJIJIJIJJIJJIIIJIJJIIJJJIIJJJJIIIJJI()
	{
	}

	public static Vector2 JJJJJJJIIIIIIJIJJIIIIJJJIIJIIIJIIJJIIIIJIJIIJII(float IJJIJIJJJIJJJIIIIJJJJJIIJJIIJJJJJJJJJIJJJJJJJJI)
	{
		return default;
	}

	public static void IIIJIJIJJIIJJIJIIIJIJJIJJJIIIJJIIIJIIJIIJJIIJJJ()
	{
	}

	public static void JJJJJJJJJJIJJJIIJJIJJIIIJJIJIJIIJJIJIJJIIJJIJJJ()
	{
	}

	public static void IIJIIIJIJJJJIJJJIIIJJJIIIJJJJJJIJIJIIIIIJIJJIII(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	[CompilerGenerated]
	private void IIJJIJIIJJJIIJJIIIIJIIJJJJJJJJJIJIIIJJJIIJJIJII()
	{
	}

	private void IJIIIJIJJIIJJIJIJJIIJIIIJJJIIJJIIIJIJIIIIIJJJII()
	{
	}

	[CompilerGenerated]
	private float IIIJIJIIJIJIJIJIJIJJIJIJIJJJJJJJIIIIIIJJJIJIIII()
	{
		return 0f;
	}

	public static void JJJIIIJIIIIJJJIIIIJJJIJJJIIIIIJJIIJJJJIJJJJJIJJ(float IJIIJJJJIIJJIJIJJIIJJIIIJJIIIJIIJIJJJJIIJIJIIJI)
	{
	}

	public static void JJJJIJJIIJJJJJJJJJIJJJJIJIJIIJIIJIJJJJJIJJIIIIJ()
	{
	}

	[CompilerGenerated]
	private void IJIIJIJJIJIJIJJIIJJIJIIIJIJJIJJIIIJIIIJJIIIIJIJ()
	{
	}

	private void JJJIIJIJJJIIIJIJJIJIJJIJJIJIJJJIJJIJIJJIIJIJJIJ()
	{
	}

	[CompilerGenerated]
	private void IJJIIJJJIJJIIJIJJJIJJJIJIIJIJJJJIJIJJJJIIJIIJII(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ)
	{
	}

	private void IJJIIJIJIJJIJIJJIIIJIJIJIIIIJIIJIIJIJIIIJIIJJIJ()
	{
	}

	private void JJIJJJIIJIIJIIJJJJJIIIIIJIIJIIIJIIJIJIJJIJJIJIJ()
	{
	}

	private void OnDisable()
	{
	}
}
