using UnityEngine;

public class UICrosshairSettings : MonoBehaviour
{
	public UISprite[] JJIIIJIJJIJIIJIJJJJJJIJJJJJIIIJJIJJJJIIJIIIIIII;

	public UIToggle[] JJJJJIJIIIJIIJJJJJJIIIIIJIJIJIIIIJJJJJJIJJJJJIJ;

	public UISprite IIJJJIIJJJIJJIIIIJIJIIJIJIJJIIIIIJJIIJIIIIJIIJJ;

	public UIToggle IJJIJIIJJJIJIJJIJIIJJJIJIIJIIJJIIIJIIIJIJJIIJII;

	public UIToggle JJJJJJIJIIIJIJIIJIIIIJIIJIIIJIIIJIIJJJJIJIIJIJJ;

	public UILabel JIJIJIJJIIJIIJIJIIIJJJJIJIIJJIJIIJIJIIJJJJIIJJJ;

	public UILabel IIJJJJIJIIJIJJJJJJIIIJJJJIJIIIIJIIJIIJJIJJJIIII;

	public UILabel JJIJJIIIIJJIIJIJJJJJJIJIIIJIJIJJIIIIJIJJJIJJIJI;

	public UILabel IJJJJIIIJJIJJJIIIJIJJIIJIIIIJJJIJJJJJJIJJIIIIII;

	public UISlider IIIIIJJIIJJJJJJIJIJJJJJIIJJJJJJIJIJIJJJJIIIIJJJ;

	public UISlider JJJJJJIJJJJIJIJJJJJIIJJJJIIIIIJIJIIJJIJIJJIIIIJ;

	public UISlider JIJIJIIIJIIJJJIIJIJJJJIIJJJIIJJJJIIIIJIJIIJJJJI;

	public UISlider JJJIJIJIJIJIJJIIJIIIIIIIIJJIIIJIJJIIJIIJIIIIIIJ;

	public UIColorPicker JJIJJIIJIIJJIJJJIIJIJIJIIIIJIJIJJJJIIJIJIIJJIJI;

	private void Awake()
	{
	}

	public void SetDynamics()
	{
	}

	public void JIJJJJIIJJIIJJIIJIJIIIIIIIJIIIJIJIJIIIJJJJJJIJI()
	{
	}

	public void IJJJIIJIJIJJJIJIJJJJJJJJIJJJIIIJJIJJJIJJJJJJJIJ()
	{
	}

	public void IJJIJIJJIIJJIJIIIIJJIJJIJIIJJIIIIIJIIIIIIIJJJII()
	{
	}

	public void SetSize()
	{
	}

	public void SetThickness()
	{
	}

	public void JIJJIIIJIJJJIIIIJJIIIIJIIIJIIIIJJIJIJIJJJJIJJJJ()
	{
	}

	public void JJJJIIJJJJJJJIJIJJJIJIIJJJIIIIIJJIIJJJIJIIJIIII()
	{
	}

	public void SetCrosshair()
	{
	}

	public void SetGap()
	{
	}

	public void IJJJIJIJIJJIJIJJJIJIJIIIJJIJJJJIJJIIJIJIJIIIIJJ()
	{
	}

	public void JIJIIJIIIJJJIIIJIIIJIJJJIIJJIJIIIJJIIIIIJJJIJII()
	{
	}

	private void JIIJIIIIJJIJJJJJIJJIJJIIIJJIIIIJJIJIJIJJJIJIJIJ()
	{
	}

	public void JJIJJJIJIJIJIJIIJIJIIJIIJIIIJJJJJJIIIJJIJIIJJJI()
	{
	}

	public void JIJJJIJJJIJIJIIIJIIIIIIJIIJIJJIIIJJIIJJJJIIIJIJ()
	{
	}

	public void IJIJJJIIIJIIJJJIIJJJIJIJJJJIJJIJIJIJIJJJJJIIIII()
	{
	}

	public void SetDefault()
	{
	}

	private void JIIJIJJJJJJJIIJJJIJIIJIIIJJIIIJIIIJJIIJIJIJJJII()
	{
	}

	public void SetColor()
	{
	}

	private void JIIJJIIJJJJIIIJIIIJJJJIJJIIJIIJJJIIIIJIJJJIJIJI()
	{
	}

	public void SetPoint()
	{
	}

	public void IJJJIJJIJIJIIIIIJIJJIIIJJIIIIIJJIJIIIJIIJJIJIJJ()
	{
	}

	public void IIJIIJIIJJJIIIIIIIIIIIIIJIJIIIIJJJJJJIIIIJIJIIJ()
	{
	}

	public void SetAlpha()
	{
	}

	public void IIJIJIJIIJJJIIIJIJIJJIJJIJIJJIIJIJIJJIJIJJJJJII()
	{
	}

	public void IIJIJIIIJIJJIJIIJJJJJJJIIIIJJJIJIJIJJIJJIJIIJIJ()
	{
	}

	public void IIJIIJIIIIIJJJJJJJIIIJIJIIIIIJIJJIJIJJIIJJJJJJJ()
	{
	}

	public void JIJIIJJIIJJJJJJIIIIIJIIIIJJJIIJJJIIJJJIJJJIIJJI()
	{
	}

	private void IIJIIIIIJJIJJJJJJJJJJIIJJJJJIJJIJJIIJJJIIJJJIII()
	{
	}
}
