using System.Collections.Generic;
using UnityEngine;

public class UIDeathScreen : MonoBehaviour
{
	public UISprite JJJJIJJJJJIJIJJJJIIIIIIJJIIJIIIJIIIIIJJIIJJJJJI;

	public UILabel IIIJJJJIJJIIJJIJIIIJJJJJIJIIIJJIIJIJIIJJJJJIJJI;

	public UILabel IJJIJJIIJJJIJJIIJJIJIJIIJJIIJIJIJJJIJIIIIIIJJIJ;

	public UILabel JIJIJIJIIJIIIIIIIJIIJJIJIJJIIIIJIJJJJJJJIJIJIII;

	public UILabel IIIJIJIIJIIJIJIJIJJIIIJIJIIIJIIIJJIIJIJJIIIJJII;

	public UITexture IJIIJIJIIJIJJIJIIJIIJJJIJIJJJJIIJJJIJJJJJIJJIJI;

	public UISprite JIJIIJIJIIIJIJIIIJIIIIJJIJIIJJIIJIIJJJIIIIJJIJJ;

	public UITexture JIIJIIJJJJIJJJIIJJIJJJIJIJJIJIJJJJIIIJIIIJIJIJJ;

	public UISprite JJJIIJIIIIJIJIIIIIJJJJJJIJIJJIJJIIJJJIIIJIJJIII;

	public float IIIIJJJJIIIJIIJIJIIIJIJJJJIJIIJJJJJIJJIIJJIIIJJ;

	private Dictionary<int, int> JJIJIIIIJIIIIJJIJIJJIIIIJIIJJJIIJJIIJIIJJIJIIII;

	private Dictionary<int, int> JJJJIIIIIJIIIJJJJIIIIIJJIIIIIJIJIIJJJIJIJJIJJII;

	private Dictionary<int, int> IIIIJIJIIJIIJJJIJIIIJJJJJIIIIJIIJJIIIJIIJIJJJJJ;

	private Dictionary<int, int> IIIIIJIIIIIJIIIIIIIJJJIIIJJIIJJIJJJIJIIIIJIIIJJ;

	private Dictionary<int, int> IIJJJJIJJIJIJJIJJJIIJIIJJIIIIIIJJIJIIJJIIIJJIIJ;

	private Dictionary<int, int> JJIIIIIJJJIIIIJJIJJIJIJIIIIJIJJJIJIIIIIJIJJIIJI;

	private int IIIIIJIIJIJIIIIJIJIJJIIIJIJJIJJIJIIJJJIJIJIJJJJ;

	private static UIDeathScreen JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void IIIIJJJIJJIJJJIJIJJIJJIIIIJIJJJJIIJIIJJIJJJJJJJ()
	{
	}

	public static void JJJIIIJJJJJJJJJIJIJIJIIJIIIJJIIJJIIIJJIJJIIJJJJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public static void IIJJIIIIJIIJJIIIJIJJIIJIIJIIIJJJJIIJIJJIJIJIJJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public static void IJIJJJJJJIIJIIIJJIJJJIIIJIIJJIIJIJJIIJIIIIIIJIJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, int JJJJJIJJIIJJIJJJJJJIJJJIIJJJIJJIIJJIIIIIJIIIJII)
	{
	}

	private Color JIJJJIIJIJIIJIJJIJJIIIJIIJJIJIJIIIIJJJIJIIIJJJI(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	public static void JJJJJIIIIIIJJJIJIJJJJJJJIJJIJIJIJJJJJJJJIJIJIJJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public static void IJIIIJIIIJJJJIJIJJIIIJIIJIIIJJIJIIIIIJJIJIJIJIJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public static void IJJIJJJJIJIIIJJIJIJJIIIIIIIJJIJJIJJIIIJIJIJIIII()
	{
	}

	public static void IJIIJJJIIJIIIJJIJJJJJIJIIJIJJJIJIJIJIJJJJIJJIIJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public static void IJIIIIIIJIJIIJIJJIIJJIJJIJJJJIJIJIIJJIIIIJJJJII(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, int JJJJJIJJIIJJIJJJJJJIJJJIIJJJIJJIIJJIIIIIJIIIJII)
	{
	}

	public static void IIJJJIIJJIIIIJIIIJJIJIJIJJIJJIIJIIJIJIIJIJJJJII(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	private void JJJJIJIIIJJJIIJIIIJJJJIJJJJIJIJJIIJIJJJIJJJJJJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public static void IJIIIIIIJJIJJIIIIIJIJJJIJIJIJIJJIJIIJIIJIJIJJJJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public static void JIIIIJJIJIIJIIJIIJJJIIIIJIJJJJJIIIJJIIJJIIJIJII(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, int JJJJJIJJIIJJIJJJJJJIJJJIIJJJIJJIIJJIIIIIJIIIJII)
	{
	}

	private static void IIJJJJJIIIIJJJJJIJJJIIJIJJIIJIJIIJIIJJIJJIJIJII(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public static void IJJJIJJJIJJJJJIIJJIJIIIJIIIIIJJIJIIJIIJJIIIJJJI()
	{
	}

	private Color JJIJJIIIIJIIJIJIJIIIIJIJIIIIIJIJIJJJJIJJIJIIJII(IIJJJJJJJIJJIIIIJJIIJIJJIJIIJJJJJIJJJIIIJIIJJIJ IIIIIIIJJJIIIJIJJJJJJJIJIIJJJIJJJIJJJIIJIIIJJII)
	{
		return default;
	}

	public static void IIJIIJJIIJIIJIJJIJIIJIJIJJIIIIJJIIIJIIJJIIJJJJJ()
	{
	}

	public static void JJJIJIJJJJIIJIJIIIIJJJIJJJIIIJJIJIJJIIJJJIIIIJI(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public static void JIIIIIJJJIJIIJIJIIJIJJJJIJIIJJIIIIJJJJIIIIIJJII(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public static void IJIJJJJIJJJJIJIJJJJJJJJIIJIJIIIJIIIJJIJIJIJIJII()
	{
	}

	public static void JJJIJIJJJJIIJIJIIIIJJJIJJJIIIJJIJIJJIIJJJIIIIJI()
	{
	}

	public static void JIIJIIJJJJIJJIIJIIJJJJJIJIJJJIJIIIJIJIJIIJJIJJI()
	{
	}

	public static void JIIIIIJJJIJJIIJJIIJJIJJIJJIIJIJJIIJIIIJIIIJIIJJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, int JJJJJIJJIIJJIJJJJJJIJJJIIJJJIJJIIJJIIIIIJIIIJII)
	{
	}

	public static void IIIIIIJIJIJIIJJIIJJIJIJIJIJJIJJJJIJIJJJJJIIJJIJ()
	{
	}

	public static void JJIIIJJJIJJJJIJIJIJIIIIJIJJIIIIIJIJJIIIJIJJJJIJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, int JJJJJIJJIIJJIJJJJJJIJJJIIJJJIJJIIJJIIIIIJIIIJII)
	{
	}

	private void Start()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private static void IJJJJJIJIJIJIIIJIIIJJJJIJIJIJJIJJIJJJIJJJJJJJIJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public static void IJJJIJJJIIJJJJIIIJJJJJIJJIJIIIJIJJIIIJIJIIIJIJJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}
}
