using UnityEngine;

public class UIDragResize : MonoBehaviour
{
	public UIWidget IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

	public UIWidget.JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII JJJJJIJIJJIJIJIIIJJIIIJJJIIIJJJJJJIIIJIJIIJJJJJ;

	public int JIIIJJJIIJJJIIIIIJJJJJJJIIJJJJIIJJJIIJIIJIIJJJJ;

	public int JIJJJJJIJJIIJJJJJJJJIJIIIIJJIJIJJJJIJJIIJJIIIIJ;

	public int JJJJJJJJJIJJIIIIJJJJJIIIIIJJIJIIIJJIIIJIJJIIJIJ;

	public int IIJIJJIJIJJIIIJIIJJIJJIIJJJJIJJJIJJJJIIIJIIJIII;

	public bool IIIIJIJIJJIJJIIJJJJIJIIJIIIIJJIJIJJJIJJIIJJIIIJ;

	private Plane JIIIJIJIJIJIJJJJIJIJIIIJJJJIIJJJIJJIJIJJIIJJIII;

	private Vector3 JIJIIJJJIIJJJJIJIJIJJJIIJJJJIIJJJJIJIIIIJIIJIII;

	private Vector3 JJJIIJJIIJJJJIIIJJJJIIJJIJIIIJJJIIIJJIJJJJIIIJI;

	private int JJJJIIJJIIJJIJJJJJIJJJIIJJJIIIJIJIIJIJJJIIIJJJI;

	private int IIIIIIJJJJJIIIJIIIJIJJJIJJJIJIIIJIIJIJJJJJIJJJJ;

	private bool IIIIJJJIJJJJJJJJIJJJJIIJIJIJIIJJJJJJJIIIIJIIIJJ;

	private void JJIJIIJJJIIIIIIJJIJIJJJIJJIJJJIJIJIJIIJJJIIJIII()
	{
	}

	private void IJIJIIJIJIIJJJIJJIIIIJJIJIJIJJJJJJJIJIJIJIJIIJJ()
	{
	}

	private void JJJIIJJIIIJJIJIJIJIJIJJIJJJIJIJIIJIJIIIIIIIJIIJ()
	{
	}

	private void JIJIIJJIJJIIIJJIIJJJJJJIJIIJIIIJIJJJIIIIJIJJJJI()
	{
	}

	private void IIJIJIIJJJIJJJIJIIJJIIJJIJIJJJIJIJJJJIIIIIJIIII(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JIJIJJIJIJIIIIIJIJJJIIIJIIJJJJJIIIIIJJJIIIIIJII(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JJIJJJIJJIJIJIIJJIJIIIIJJJJIIIJJJIJJJJIJJJJIJIJ(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JIIJJIJIJIJIIIIIJJJJJIJJJIIJIIIIJIIJJJIJIIIJIJJ(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IIIIJJJJIIIIJIJJIJIJJIIJIIIJJJIJIJJIJJJJIJIIIIJ()
	{
	}

	private void JJJJJJJJJJIIIJIJJJJJJIJIIJJJIJIJIIJIIJIIJJIJIJI(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IIIJJIJIJJJJJJIJJIIIIIIJJIJIJIIIIIJIIIIIJJJJIII()
	{
	}

	private void IIJJIJJJIIJJJIJIJJJIJIIJJJJJJIJJIJJIJJIIIIIJJJI()
	{
	}

	private void JIIIJJIJIIIIJIIJIIJIIIIJJIJIJJIIJJJJIJJJJIIJIII(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}
}
