using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class UIDragObject : MonoBehaviour
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JIIJJJJIIJIIIJIIJIIIIJIJIJJJIIIJIIJIIIJJIIJIJJJ
	{
		None = 0,
		Momentum = 1,
		MomentumAndSpring = 2
	}

	public Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

	public UIPanel JJJJIJIJIJJJIJJIIIIIIJJJJJIIJJJJJJIJJJIIIIIIIJI;

	public Vector3 JJJIJIIJJIJJIIIJJJJIIJJJJJJIIJIJJJJJIJIJJIIIJIJ;

	public bool IIIJIIJIIIIIIJIIJJJJJJIJIIJJJJJIJIJIIJIIIIJJJIJ;

	public UIRect IJIIJIIJJJIJJIIIJJJIIJIIJJIJJJIJJJIJIJIIJIIJJIJ;

	public JIIJJJJIIJIIIJIIJIIIIJIJIJJJIIIJIIJIIIJJIIJIJJJ JIIJJJJIJIJIJIJJJJJJIJJIJIJJIIJIJJJJJIIIIJJJIJJ;

	public float IIIIIIJIIJIIIJIIIIIIJJIIIJJIIJJIJJJJIIIIJIIJJIJ;

	[SerializeField]
	protected Vector3 scale;

	[SerializeField]
	[HideInInspector]
	private float scrollWheelFactor;

	private Plane JIIIJIJIJIJIJJJJIJIJIIIJJJJIIJJJIJJIJIJJIIJJIII;

	private Vector3 IIJIIIIIJIIJIJIJJIJIJIJJIJJJJJJJIIIJJJJJIIIIIII;

	private Vector3 JIIIJIIIJJJJIJIJIIJJIIJJIJJIIIJJIIJIJJIIIJIJJJI;

	private Vector3 JJJJJIIIIJIIIIIIJJIIJJIJJIIIJJIJJJIJJJIIJJIJIJJ;

	private Vector3 JIIIIIIJJIIIIJJIIIIJJJJIIJIJJIIIIJIJIJIIJIIJJIJ;

	private Bounds IIIIIJJIJIIJIJIIIIIJJIJIJJJJJJIJJIJJIIJJIIIIIIJ;

	private int IJJJJJJJJJIIIJIJJJJJIIIIIJJJIIIJIJJIJIJIIJJJIJJ;

	private bool IIJJIJIJJIJJIJIJIJJJIIIJJJIJJIIIIJJJJIJIJIIJIJI;

	private bool IJIJJJIIJIIJJIJJIIJIIIJJIJJJIJJJJIIIIJJJIJJJJJI;

	public Vector3 JIIJIIJIJJIIJJJIJIIIJJIJIJJJIJIIIIJJJJJIIIJIIIJ
	{
		get
		{
			return IIJJJIIJJIIJIIIJJIIIIIIIJJIJIJIJIIJIJIIJIIIJJII();
		}
		set
		{
			IJIIIJIJIJIIJJJIJJJJJIIIIIJIIJJJIIIIJJJJJIJJJJI(value);
		}
	}

	private void IJIJJIIJJJIJIJJJJJIIIIJIJJIIJIIIIIJIJJJJJIIIIIJ(Vector3 JIIJIIJIIJJJJJIJJJIIJJJJIJIIJJIJJIJIIJJJJJJIIJJ)
	{
	}

	public void IJIIIJIJIJIIJJJIJJJJJIIIIIJIIJJJIIIIJJJJJIJJJJI(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Vector3 IIJJJIIJJIIJIIIJJIIIIIIIJJIJIJIJIIJIJIIJIIIJJII()
	{
		return default;
	}

	private void JJJJJJIIJIJJJIIJIJIJJJIIJJJIIIIIIJIIIIIIJIJIJJJ()
	{
	}

	private void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	private void LateUpdate()
	{
	}

	private void IIIIJJJIIIJJIJIIJJJJJJJJJJJIIIIIIJJIJIIJIJJIIJJ(Vector3 JIIJIIJIIJJJJJIJJJIIJJJJIJIIJJIJJIJIIJJJJJJIIJJ)
	{
	}

	private void JJIJJJIJJIJIJIIJJIJIIIIJJJJIIIJJJIJJJJIJJJJIJIJ(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	public void IIJIJIJJJIJIJJIIJJJJIJJIIJIIJIJJJIJIJJJJJJJIIII()
	{
	}

	private void IIIIJIIIJIJIJIIJJIJJIJIJJJIIJIJIJJIIJIJIIJJIJJJ(float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IIIJJJIJJJIIIJJJJIJJIIJIIJJJJIJJJIIIIIJJIJJJIJJ()
	{
	}
	public void IJJIIIIJJJJJJJJIIJIJIJJJIJIJJJJIIIIIJIJJIIJIIJJ(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void IIJIIIJJJJJJIJJIIIIIIIJIJJIJJJIJJIJIIIJJIJJJJII(Vector3 JIIJIIJIIJJJJJIJJJIIJJJJIJIIJJIJJIJIIJJJJJJIIJJ)
	{
	}

	private void IJIJJIIJJIJIIIJIJIIJJIJIIJJJIJJIIIJJJJJIJJJIIII()
	{
	}

	private void IIJIJJJIIJIIIJJJJIJJIJJJJIIIJIJIJJIJJJJIJJIJIJI()
	{
	}

	private void IIIJIJJJJIIIIJJJIJIJIJIJIJIJJIIJJJIJIJJJIJJIIJJ()
	{
	}

	private void JJJIIJJIJIJJJJIIJJJJJIJJIIIJJJIJIJJIIIJIIJIIJII()
	{
	}

	private void IJJIJJJIJJIJIIJJIIJJIJIJJJJIIJJIJJIJJIJJJJIJIJI()
	{
	}

	private void IIIIJJJIJIJJIIIJIJJIIIIIJJIIIIIJIIIIJJIJIJIJIJJ(Vector3 JIIJIIJIIJJJJJIJJJIIJJJJIJIIJJIJJIJIIJJJJJJIIJJ)
	{
	}

	private void IJIIIIJJIIJJJIJIJJIIJJIJJIJJJJIIJIIJJJJJIIIIJIJ()
	{
	}

	private void IJIIIJIIIJJIJJIJIJJJIIJIJJJIJJJIJIIJIJJIJJJJJII()
	{
	}

	public void IJIIIIIIIJJIIIJJIJIJJJIIIJJIJJIIIJJJJJIIIJJJIIJ()
	{
	}

	private void OnDisable()
	{
	}

	public void JJIIIIIJJJIJJJIJJJIIJIIJJJIIIJIIJJJIIJJJIIIIIIJ()
	{
	}

	private void IJIIJIIIIIIIIJIIIIIJIJJJJIJIIIIJIJJJJJJJJIIIJII(float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JJJJJJIIIJIIJJIIJIJJIJJIJIJJIJIJIJJIJJIIJJJJJII(float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IIJJJJJIIIIJIJIIIJIIJJJIJIIIJJIJJIJIJIJIIIJIIJI()
	{
	}

	private void JJIJJJJIIIJJIIJJIJJIIJJIIJJJJJIIJJJJIJIIIIJIJII()
	{
	}

	private void IJJJIIJJIIJIJIJIIJIJIIJJJJJIJJJIJIJJIJJJIIJJJJJ()
	{
	}

	private void OnEnable()
	{
	}
	public Vector3 JIJIIIIJIIJJJIIJIJIIJJJIJIIJIJJIJIIIIJJIIIJJIJJ()
	{
		return default;
	}
	public Vector3 JJJJJIJJJJJJJJIJIJJIJIIIIIJIIIJIIIJIIIIIIIJJIJJ()
	{
		return default;
	}
}
