using UnityEngine;

[ExecuteInEditMode]
public class UIDragCamera : MonoBehaviour
{
	public UIDraggableCamera JIIIJIJIJJIIIJIJJIIIJIJJIJIJJJJJJIJJIIIIJIJJJII;

	private void IJJJJJJIJJIIIIJIJIJJJIIIJJIIIIJJIJIIJIIIIJJJJIJ()
	{
	}

	private void IIJJIIIJJIJIIJIJIIIJIIJIIJIJJIIJJIIIIJIJJIIIJJI()
	{
	}

	private void JJIJJJIJJIJIJIIJJIJIIIIJJJJIIIJJJIJJJJIJJJJIJIJ(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JIJJIIIIJJIIJIIIJIJJIJJJIJJIIJJJIJIJIJJIIIIJIII(float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JIJJJIIIJJJIJJJIJJIIIJJJIJIJJIJIIIJIJJIIJJIJIIJ()
	{
	}

	private void JIJJIIIJJIJIIIIIJIIJIIIIJJJIJIIIIJJJJJJJJIIIIIJ()
	{
	}

	private void JIIJJIJIJIJIIIIIJJJJJIJJJIIJIIIIJIIJJJIJIIIJIJJ(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void Awake()
	{
	}

	private void IIJIIIJJIJJJIJIIIIIJJJIJIJIJIIJJIJIJJIJIIIIJIII(float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IJIIJJJIJIIJIJIJIJJJIJJIJJIIJJJIIIJJJJJIJJIIIJI(float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JJJJJIJJJJIJJIJIJJIIIJJJJJJJJIJJIJJIIJJJIJIJIIJ(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	private void IIJIIJJIIJIJJIIJIIJIJIJIJIJIJIIJJIJIJIIJJIIJIJI(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	private void IIIJJJIJIJIJJIJJJJJJJJJIIIIJIIJIIJIIIIIIIJJIJJI(float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	private void IIIIJIIIJIJIJIIJJIJJIJIJJJIIJIJIJJIIJIJIIJJIJJJ(float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}
}
