using System;
using UnityEngine;

public class UIDragScrollView : MonoBehaviour
{
	public UIScrollView IJJIIIIIJIIJIJIIIIIIIIJIJIIIJIIJIJJIIJIIJIJJIIJ;

	[SerializeField]
	[HideInInspector]
	private UIScrollView draggablePanel;

	private Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	private UIScrollView JIIIIIIJJIIIIJJIIIIJJJJIIJIJJIIIIJIJIJIIJIIJJIJ;

	private bool IIIJJIIJIJIJJJIJJIJIJJIIJIIJJJJJJJIJJIIJIIJIIJI;

	private bool IIJJIJIJJIJJIJIJIJJJIIIJJJIJJIIIIJJJJIJIJIIJIJI;

	private GameObject IIIJIJIIIIIJJIIJIIIJJJIIJIJIIJIJIIJJJJIJJJJIIII;

	[NonSerialized]
	private bool IJIJJJIIJIIJJIJJIIJIIIJJIJJJIJJJJIIIIJJJIJJJJJI;

	private void OnDisable()
	{
	}

	private void JJJIIIIIJIIJJIJIJJJJIIJIIIIIIJJJJJJIJIJIIJJJIJJ()
	{
	}

	public void JJJJJJJIJIIJJJIJJIJIIJIJIIIJJIIIJJJJIJIJIIJIIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IIIIJIIIJIJIJIIJJIJJIJIJJJIIJIJIJJIIJIJIIJJIJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JJJJJIJJJJIJJIJIJJIIIJJJJJJJJIJJIJJIIJJJIJIJIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	private void JJIJJJIJJIJIJIIJJIJIIIIJJJJIIIJJJIJJJJIJJJJIJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JJIJJIJIJIIIJJIIIIIJJIJIIIIJJJIJIIJIIIJJIIJIJJI()
	{
	}

	private void OnEnable()
	{
	}

	private void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	public void JJJJJIIIIJJJJIJJJIIIJJJJIIIIIJIIIIIJJIIIJIJJJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IIJIJIIIIIJJIIIIIJJIJIIIJIJIJIIIJIJJIIIJJJJIIJJ()
	{
	}

	public void JIIIIIJIIIIJJJJIJIIJIJJIJIIIIIIJJJJJIJJIIJIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IIJJIJJJIJIIIIIJJIIJJJJJJJJIJJJJJJIIIIIJIIJIJIJ()
	{
	}

	public void IJIJJIJJIJJIJJJIJJJJJIIIJIIIJIIIIIIIJJJJIIIIIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JIJIJIIIJIIJJIIIIIJJIJIIIIJJJIJIJJIJIJIIIIJIJJI()
	{
	}

	private void JIIJIIIIIIJIIIIIJIIJJJJIJJIIIIJJJJJJJJJJJJJJJIJ()
	{
	}

	private void JJJJJJIIJJIJIIJIJJIIJIJIJJJIIJIIJJJIIJJIJJJIIII()
	{
	}

	private void IIJJJIJIIIJIIIJJJJIIIIJIJJIJIIIIJJJIIIJIIIIIJII()
	{
	}

	private void Start()
	{
	}

	private void JIJJIIJJIJIIIIIJJIIIIJJJIIIJJJIIIIIIJJIIIJJIIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IIIIJJIJJJJJJJIJIIJIIJIIJJIJIJIJIJJJJIIIJJJJIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JJJJJJIIIJIIJJIIJIJJIJJIJIJJIJIJIJJIJJIIJJJJJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JJJIIJIIIJIJIIJIJJJJIJIIIJJJJIIIJIJIJJIIIIJJIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}
}
