using System.Runtime.CompilerServices;
using UnityEngine;

public class UIDraggableCamera : MonoBehaviour
{
	public Transform JIJIIJIJJIJJJJJJJIIIIJIIJIIIIJJIIJJIJIJIIJJIJJJ;

	public Vector2 IJIJIJIJJJIIJJJJJIJJJJJIJJIIJJJJJJIJIJJJJIJJIJI;

	public float IIIJIIJJIJJJIJJIJIIIIIJJIJJIJJJIJJJJJIIJJJJJJIJ;

	public UIDragObject.JIIJJJJIIJIIIJIIJIIIIJIJIJJJIIIJIIJIIIJJIIJIJJJ JIIJJJJIJIJIJIJJJJJJIJJIJIJJIIJIJJJJJIIIIJJJIJJ;

	public bool IJIIIJJIIJIJIJIJIIJIJJIJIIJJJJIIJIJJJJIIJIJJIIJ;

	public float IIIIIIJIIJIIIJIIIIIIJJIIIJJIIJJIJJJJIIIIJIIJJIJ;

	private Camera IIIJJJIIJIIJIJJIJIJIIJJIIJIIJIJIJIIIJIJIJJIIJII;

	private Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	private bool IJIJJJIIJIIJJIJJIIJIIIJJIJJJIJJJJIIIIJJJIJJJJJI;

	private Vector2 JJJJJIIIIJIIIIIIJJIIJJIJJIIIJJIJJJIJJJIIJJIJIJJ;

	private Bounds IIIIIJJIJIIJIJIIIIIJJIJIJJJJJJIJJIJJIIJJIIIIIIJ;

	private float JIIIIIIJJIIIIJJIIIIJJJJIIJIJJIIIIJIJIJIIJIIJJIJ;

	private UIRoot JJJJIIJIIJIIJIIIJIJJJIJIJIIIJIIIIIJJJJJJIJJIJII;

	private bool IIJIIIIIIIJIJJJIIJIJIIIJIJIIIIIIIJIJJIIJJIJIIIJ;

	public Vector2 IJIIIJJJJJIIIIJIIIJJJIIIIIIJJJJIIJIIIJIIIIJIIJJ
	{
		get
		{
			return IIIIIIJJJIJJIJJIJIJIIIJIIIIIJJIIIJIJIJIJJIJJIJJ();
		}
		set
		{
			JIJIJJJJJJJIIIJIJIIIIIIIJJIIJIJJJIIIIIJIIIJJJJI(value);
		}
	}

	public Vector2 IIIIIIJJJIJJIJJIJIJIIIJIIIIIJJIIIJIJIJIJJIJJIJJ()
	{
		return default;
	}

	public void JIJIJIJJJIJJIIIIIIJJIJJIJJJIIIJIJJIJIJJIIIJJIJI(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	public void IJIIJIIIIIIIIIJIIIIJIIIJIIJJIIIIJJJIIJIIIIJIJII(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void Start()
	{
	}

	public bool IJJIJJJIIJJJJIIIJJJIJIIIIIJIIIJIIIIJIJIJJIJIIJJ(bool IJIIIIIJIJJIIIIJIIIJJIIIJJIJJJIJJIIIIJIJIIIIIII)
	{
		return false;
	}
	public void JIJJJJIJIJJIIIIJIJJJJIIJIIJJJJJJJIIJIJJIJIIIJII(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIJIJJJJJJJIIIJIJIIIIIIIJJIIJIJJJIIIIIJIIIJJJJI(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void IJIIIJJJJIIJIIIIJIJJJJIJIJJIIJIJJIJIIIIIIJIJIIJ(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private Vector3 IIIJIJJJIJIJJJJIJIIIJIJJIIIIJJJJJIJJIIJJJJJJJIJ()
	{
		return default;
	}

	public void IIIIJJIIIIJJIJJJIIIIJJJJIIIJJIJJIIIIIIIJIJIJJIJ(float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}
	public void JIIIJIJIJJJJIJJJIJIJJJJJJIJJIIIJIIIIIJJJJIJJIJI(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private Vector3 JIJIJJIJIIJIJJJIIIIJJIJJJJIJJJIIJJJIJJIIJJJIJIJ()
	{
		return default;
	}
	public Vector2 IJIIJIJJIJJJJIIIIIJJJIIJJJJJJJIIIIJIJJIIJJJIIJJ()
	{
		return default;
	}

	public void IIIJIJIJJIJJIJJJJIIIJIIJJJJJJJIJJJIJJIJJIJIIJJJ(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	private void Update()
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void IIJIJIIIIIJJIIIIIJJIJIIIJIJIJIIIJIJJIIIJJJJIIJJ()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	public void JJIJIIIJIIJJIJIJIIJIJIIJJIIIJJJIJJJJJIIJJIJJJJJ(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}
	public void IIJJJJIJIIJJJJJJIJJJJJIJJJIIJJIIIJJIJIJIIIIJIJJ(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public Vector2 IJJJIJIJJJJIJIJJJJIJIIIIJIJJJJJIIIJIJJJIJJIIJII()
	{
		return default;
	}

	public bool JJJIIJIIJIJJJIIJIJIJIIJIJIJJJIIJIIIIJJJJIJIJJII(bool IJIIIIIJIJJIIIIJIIIJJIIIJJIJJJIJJIIIIJIJIIIIIII)
	{
		return false;
	}

	private Vector3 JIIJIIJJIIJJIJJJIJJJJIIJJJIJJIJJJJIJJJJIIJIJIII()
	{
		return default;
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}
}
