using DG.Tweening;
using UnityEngine;

public class UIDuration : MonoBehaviour
{
	public UISprite JIIIJIIJJIIIJIJJJJJIJIIJIJIJJIIJIJJJIIJJJJJJJIJ;

	public UILabel JJJJJIJJIIJIIJIJJIIJJIJIJIIJJJJIJIIJJJIIIJJJJJJ;

	private Tweener IJJIIJJJJIJIIIJIJJJJIJIJJJIIJIIJJIJJJIJIJJIIJII;

	private static UIDuration JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static UISprite IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ => IJJIIJIJIIJJIJIJJJJJIIJIJJIJJJIIIIJJIJIIIIIJJIJ();

	public static void JIIIJJJIIIIIJJJIIJIIJJIJIIIJJIIJIIJIJIIIIIJIJJJ(float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, bool JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
	}

	private void IJIIIIIIIIIJIIIJJJJIJIIJIIIIIJJIIIIIJIJJIIIJJJJ()
	{
	}

	public static void IJIJJIJIJIIIIIIIIJJIIJJJJJJJIJIIIIJIJIJJIIIJJJI(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IJIIJJIJIJIJIIJJJIJIIIJIJIIJIJJIIIIJIIIJIIIIIJJ)
	{
	}

	public static void JIJIJIJIJIIIJIIJJIJIIIJIJIIIIJJJIJJIJIJIJIJIJIJ(float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public static void JJIIJIIIIIIIIJJJIJJJIJIIIJIIJIIJIIIIIIIJJIIJJJJ()
	{
	}

	private void Start()
	{
	}

	public static UISprite IJJIIJIJIIJJIJIJJJJJIIJIJJIJJJIIIIJJIJIIIIIJJIJ()
	{
		return null;
	}

	public static void IJIJIIIIIIIIJIIIIJJIJIIIIJIIIIJIJJIJIJIIJJJJIJI(float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, bool JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
	}

	private void JIJIIIIIIIIIJJIJIJIJJJIIIJIJJIJIJIJIJIIJJIJJIII()
	{
	}

	public static void JJJJIIIIIJJJJJJJIJIJIIJIIJIJIJJIJJJIJJJIJIIIIIJ(float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, bool JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
	}

	public static void JIIIIJIJIJIIJJJJIJIJJIIJJJJJIJJIIJIJJJJIJIIJIII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IJIIJJIJIJIJIIJJJIJIIIJIJIIJIJJIIIIJIIIJIIIIIJJ)
	{
	}

	public static void JJJJIIIIIJJJJJJJIJIJIIJIIJIJIJJIJJJIJJJIJIIIIIJ(float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public static void JJJJIIIIIJJJJJJJIJIJIIJIIJIJIJJIJJJIJJJIJIIIIIJ(float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, bool JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI, TweenCallback IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
	}

	public static void IIJJIIIIIJIIJJIJJIIJJJJJJJIIIJJIJJIIJJJJJJIJJJJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IJIIJJIJIJIJIIJJJIJIIIJIJIIJIJJIIIIJIIIJIIIIIJJ)
	{
	}

	public static void IIJIIIIIIJJJIIIIJJIIJIIIIJIJIJIIIIIIJJIJJJJIIJI(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, int IJIIJJIJIJIJIIJJJIJIIIJIJIIJIJJIIIIJIIIJIIIIIJJ)
	{
	}

	public static void IIJJIIIIJIIIIJIIJJJJIIIJIJIIJIIJJIIIIJIJJIJJIII(float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, bool JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI, TweenCallback IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
	}

	public static void JJJJJJJIJJJIJIJIJIIIJIJIIJIIIIIJIIJJIIIIJIJJIIJ(float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, bool JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI, TweenCallback IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
	}

	public static void IIIIIIIIJIIIJIIIJIIJIIJJJJJIJJIIJIIIJJIIJIJIJIJ(float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, bool JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI, TweenCallback IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
	}
}
