using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class UIElements : MonoBehaviour
{
	[Serializable]
	public class IIJIIJIIIJJIJIJJIIJIJIJIJJJJJJIIJIJIIIJIIIIIIJI
	{
		public string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ;

		public GameObject IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

		[HideInInspector]
		public UnityEngine.Object IIIIIJIIIJIIIJJIIJIIJIJJJJIJIIJIJIIIIIIIJIJIJJJ;
	}

	public IIJIIJIIIJJIJIJJIIJIJIJIJJJJJJIIJIJIIIJIIIIIIJI[] JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ;

	private static UIElements JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static bool IIJJIJJIJJIIIIIJIIIJJIJIIIJJIIIJJIIIIJJIIJIJIII => JJIJIJIJIIJJJJJJJJIIJIIJJIJJIJJJIJIJIJJJIJIJJIJ();

	private void IJJIIIJJJJIIJIJIJIIJJJIIJJJIJJIJJIIIJIJJIIIIIII()
	{
	}

	private void IJJJJIIJIIJIIJJIJJIJIJIIJIIJJIJJJIJIIJJJJJJIIII()
	{
	}
	public static bool IIJJJIIJIJJIJJJIIIJJJJJIJIIJJIIJJIIIJJIIJJJJJJI()
	{
		return false;
	}
	public static bool IJJJJJJIIIJIJJIJIIJJJJIJIJJIIIIJIJIJIJIJJIIJJIJ()
	{
		return false;
	}
	public static bool JIIIJIIJJIJIJIJIIJJJIJIIJIIIIIIIJIJIJIIJIJIJJJI()
	{
		return false;
	}

	private void IIJIIIJJJIJIIIJJIJIJJJIJJIIIIIIIJIIIIIIIJJIJJJI()
	{
	}

	private void IIIJIJJJIIJIIIJIIJJJIJJIJIIJJJIJJIIIJJJJIIJJJIJ()
	{
	}

	private void JJIJIJIIJJJJIIJIJJIIIIJIJJJIJJJJJJJJIJIJIIJIIII()
	{
	}

	public static T IJIIIIIIIIJJIIJIJJIIIIIJIIJIIIIIJIIJJIIIIJIIIJI<T>(string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ) where T : Component
	{
		return null;
	}

	private void JIJJIIIJJIJIIIIIJIIJIIIIJJJIJIIIIJJJJJJJJIIIIIJ()
	{
	}

	private void IIJJIIIJJIJIIJIJIIIJIIJIIJIJJIIJJIIIIJIJJIIIJJI()
	{
	}

	private void Awake()
	{
	}

	private void IJJIJJJJJIJIIIJJJIJIJIIIIJJIJIIJIIJIJJIIIJJIJIJ()
	{
	}

	private void JJIJIIIJIJIJJJJIJIIJJJJJIJJJJJIJIJIJIIJIIJIIIJJ()
	{
	}

	private void IJIIIJJJIIJIIJIIJJIJIJJJJJJIIIIIIIJIJJJJIJJIIJI()
	{
	}
	public static bool IJIIIJJJIJIIIIIIIIJIIIJIJIIIJIIJIIJJJIIIIJJIIJI()
	{
		return false;
	}
	public static bool JIIJIIJJIJJIJIIJIIJJIJIIIJIJJJIJIIJJJIJIIJJJIIJ()
	{
		return false;
	}

	private void OnDestroy()
	{
	}

	public static bool JJIJIJIJIIJJJJJJJJIIJIIJJIJJIJJJIJIJIJJJIJIJJIJ()
	{
		return false;
	}
}
