using UnityEngine;
using UnityEngine.Events;

public class UIEventClick : MonoBehaviour
{
	public bool JJJJJIIIJIJJJIIIIIJJIIJJIIIJJIJIJJJIIJIIIJJIIJI;

	public UnityEvent IJIIIJIJJJIIJJJIIIIJJJJJIIIIJJIIIIJJIJIIIJIIIJI;

	private GameObject IIIJIJIIIIIJJIIJIIIJJJIIJIJIIJIJIIJJJJIJJJJIIII;

	private void IJJJJIIIIJJIIIJJIJJJJJJIJIIJJJJJJJJIJJIIJIIIJIJ()
	{
	}

	private void JIIJIIIIJIJJJIIIIIJJIJJJJJJIIIJIIJJIJIJIJIJIIIJ()
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void IIJJJJJIIIIJIJIIIJIIJJJIJIIIJJIJJIJIJIJIIIJIIJI()
	{
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	private void IIIJJJIJIIIJJIJIIJJIIIIJIIIJJJIIIIIJIIIJJIIJJII()
	{
	}

	private void OnDisable()
	{
	UICamera.IJIIIJIJJJIIJJJIIIIJJJJJIIIIJJIIIIJJIJIIIJIIIJI -= OnClick;
	}

	private void JIJJJIIIIIIJJIIIIIJJIIIJJIJIJJJJJJJJIJIJIIJIJII()
	{
	}

	private void IJJIJIJIJIJIJJIJIIIJIJIJIJJIIIJIIJJIIIIJIIIJJJI()
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void IJJIIJJIIJJIIJJJJJJIIIJJJJJIJIIJIJIIJIIJIIIIJII()
	{
	}

	private void IJIJJJIIJIIJIJJIJIJIIIJIJIJJIIIIIIJJIJIJIJIJIJJ()
	{
	}

	private void OnEnable()
	{
	        if (IJIIIJIJJJIIJJJIIIIJJJJJIIIIJJIIIIJJIJIIIJIIIJI == null)
	        {
	            IJIIIJIJJJIIJJJIIIIJJJJJIIIIJJIIIIJJIJIIIJIIIJI = new UnityEvent();
	        }
	        UICamera.IJIIIJIJJJIIJJJIIIIJJJJJIIIIJJIIIIJJIJIIIJIIIJI += OnClick;

	}

	private void JJIIIJJIIJIJJIIJIIIJJJJJIJJIJJIJIIJIIIIIJIJIJJI()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void JJJIJIIJJIIJJJIIIJJIIIJJJIJJIIJJIIIJIIJJIJIJJJJ()
	{
	}

	private void IJJIJJIJIIJIIIJJIIIIIJJIJIIJJIJJIIJJJIIJIIJIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void IIJJIIIIJIIJJJJJIJIIIJJIJJJJIIIIIIIIIJIJIIIIIII()
	{
	}

	private void IIJIIIIIJJJIJJJIJIJIJJIIJIJJIIJIIJIJIIIIJJIIIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void Start()
	{
	}

	private void JIIIIJIJIIJIJJJIJJIIJIIJIJIIJIIJJIJJJIJIIJIJJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void OnClick(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	        if (IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII == gameObject && IJIIIJIJJJIIJJJIIIIJJJJJIIIIJJIIIIJJIJIIIJIIIJI != null)
	        {
	            IJIIIJIJJJIIJJJIIIIJJJJJIIIIJJIIIIJJIJIIIJIIIJI.Invoke();
	        }

	}
}
