using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class UIEventTrigger : MonoBehaviour
{
	public static UIEventTrigger JIIJIIIIIIIIIIJIJIIIJJIIJJJIIIJJIIIIIIIIJIJIJIJ;

	public List<EventDelegate> IJJJIJIJJIJJJIIIJIIIJIIJJIIJJJJIIIJIIJIJJIIJJJJ;

	public List<EventDelegate> JJIJIJIJJIJJJJIJJIJIJJJIJJIIIJIIJJJIJJJJJJJJJJI;

	public List<EventDelegate> IIIJJIIIIIIJIJJJJJIIJIIJJJIJIIJJIJJIJJIIIJIIJJI;

	public List<EventDelegate> JIJJJJJIJJIJJJIIJJIIJJJJJJJIIJJIIJJIIJIIJIJJIJJ;

	public List<EventDelegate> JIIJIIJJIIJJIIJJIJJIJIIIJIJIJJJIIIJJJJJIIIJJIJI;

	public List<EventDelegate> IIJJIIIIJJJIJJIIJIJIJIJJIJIJJIJJIIIJIJJIIJIIJIJ;

	public List<EventDelegate> IJIIIJIJJJIIJJJIIIIJJJJJIIIIJJIIIIJJIJIIIJIIIJI;

	public List<EventDelegate> JIIIJIIJIJJJIIJIIIIIJIJIJJJJIJJIIJJJJJIIJIIIJJI;

	public List<EventDelegate> JJJJIIIJIJIJJIJJJIIJIIJIJJIJIIJJJJJIJJIIIJJIJJI;

	public List<EventDelegate> IIIIIIJIIIIIIJJJIIJJIJJIJJIIIJJIJIJJJJIIJJJIIIJ;

	public List<EventDelegate> IIIIJIIIJIIIJIJIJIJJIJJJIJJJJIIIJIIJJIIIIIIIJJI;

	public List<EventDelegate> IIIIJJIIJJIJIIIIIJIJIIJJJIIJJIJIJJIJJIJJJIIJIIJ;

	public List<EventDelegate> JIIIJIJIIIIJIIJIJIJIJIIJJJIIIJIJIIIJIIIJIJJIJIJ;

	public bool JIJJIJIIIJJIIJIJIJIIJJIJIIIIJJJJIJJJIIJIIJIJIIJ => JIJIIJJJIJJIIJIJJJIIIJIIJIJJIJIIIJJJIJJIIJJJJIJ();

	private void IIJJJIIIJIJIJJJJIIJIJIJIJJJJJIJIJJJJJJJIJJIJJII(bool IJIJJJJIJJJJIIJJIJJIIJIIIIIJJIJIIJIIIIJJJJIIIIJ)
	{
	}

	private void IIIJJIJIJJJJJJIJJIIIIIIJJIJIJIIIIIJIIIIIJJJJIII()
	{
	}

	private void JJJIJIIIJJJIJIJJIJIJJJIJJIIIJIIIJJIIIJJJJJIIIIJ()
	{
	}

	private void JIIJIIIIJJJIIIIIIJJIIIIIIJJJIJJJJJIJIJJIIIIIIJI(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void IJIIJIJIIJJJJJJIJJJIJIJIJJJJIJJJJJJIJIIIIJIJJII(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void JIIIIJIIIIJJJIIIIJJJJJIIIJJJJJJIIJIJJJIIIJJIIJI()
	{
	}

	private void IJJJJIIJJJIIJJIJJJIIIIIJIJIIIJJJIJJIIJIIJJJIIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void JIIIIJIIJJJIIJIJJJJIJIIJIIIJIJJIJJIJJJJIIJIIIJJ()
	{
	}

	private void JIJIIJIIJJIJJJIJIJJIJIJIJIIIJJJIJJIJJJIJJJJJJIJ()
	{
	}

	private void JJIIIJJJJJJIJJJJJIJIJJIIIJJIIIIIIIJJIIIJIIIJIJI(bool IJIJJJJIJJJJIIJJIJJIIJIIIIIJJIJIIJIIIIJJJJIIIIJ)
	{
	}

	private void IIIIJJJJIIIIJIJJIJIJJIIJIIIJJJIJIJJIJJJJIJIIIIJ()
	{
	}
	public bool IJJJJJJIIIJIJIJIIIIJIJJJJIIJIJIJIIIJJJJIJIJIIIJ()
	{
		return false;
	}

	private void IIJJIIJJJJJJJJJJIJJIIIIJJJJJJIJJJJIIJIIJIJIJIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void JIJIJJIJIJJIIJJJIJIJJIIIJIJJJJJJJJJIIJIJJJJIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void IJIIJIIIIJJIIJJJJIJJIIIJIIIJIJIIIIIJIJJJJIIJJJJ(bool IJIJJJJIJJJJIIJJIJJIIJIIIIIJJIJIIJIIIIJJJJIIIIJ)
	{
	}

	private void OnClick()
	{
	}

	public bool JIJIIJJJIJJIIJIJJJIIIJIIJIJJIJIIIJJJIJJIIJJJJIJ()
	{
		return false;
	}

	private void IIJIJJJJIJJIIJJIIIIIJJJJJIJIJJIJIIJJIJJJIIJIJII()
	{
	}

	private void JJIJJJIJJIJIJIIJJIJIIIIJJJJIIIJJJIJJJJIJJJJIJIJ(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IJIJIIJIJIIJJJIJJIIIIJJIJIJIJJJJJJJIJIJIJIJIIJJ()
	{
	}

	private void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	private void IIIIIIJIIJJIIJJJJJIIJIIJIIJJIJJJJJIJIJJJJIIJIIJ()
	{
	}
}
