using DG.Tweening;
using UnityEngine;

public class UIFade : MonoBehaviour
{
	public UISprite JJJJIJJIIJIIJIIIIIIIIJIIIIJJIJJJJJJJIIIJJJIIJIJ;

	public Tweener IJJIIJJJJIJIIIJIJJJJIJIJJJIIJIIJJIJJJIJIJJIIJII;

	private static UIFade JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void IJJIJJJJJJIJIIJJIIJIJJIIJJJIJJIJIIJJIJJJJIIJJJJ(float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, TweenCallback IIIJIJJIJJIJJIIJIIIJIJJIJJJJJIIIJIJIJJJIJJIJIJJ)
	{
	}

	public static void IIIIIIIJJJIIIJIIJJJJIJIJJJJJIIIIIIJJIJJIIJJIIJI(float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, TweenCallback IIIJIJJIJJIJJIIJIIIJIJJIJJJJJIIIJIJIJJJIJJIJIJJ)
	{
	}

	private void IIIIIIJIIIJJIJIIIJIIIJIJIJJIJIIJIIIIJIJJIJJJIII()
	{
	}

	public static void JIJJIJIIJJIIIJIIJJIJIJJJJIIJIJJJJJIJJIIJIJIJJII(float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	private void JIIJIJJIJIJJIIJIIJIIIJJIJJIIIJJJIIIIJJIIJIIJIJJ()
	{
	}

	public static void JJIJJJJIIJIIIIIIIJJJJIJIJIIIJJIJJIJJIJJIIJJJJJJ(float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	private void Start()
	{
	}

	public static void JJIJJJJIIJIIIIIIIJJJJIJIJIIIJJIJJIJJIJJIIJJJJJJ(float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, TweenCallback IIIJIJJIJJIJJIIJIIIJIJJIJJJJJIIIJIJIJJJIJJIJIJJ)
	{
	}

	public static void JIJIJJJIJJIIIJIJJJIIIJJJIIJIJJJJJIJJIIIIIJIJIJI(float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	private void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII()
	{
	}

	public static void JIIIIJJJJJJJIIIJIIIJIJJJJIJJJIIJIIJIIJJIIIIIJJJ(float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public static void JIJIIJIIIJJJIIIIIIJJIIIJIIJIJJIJIIIIIJJIIIIJJJI(float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	public static void JIIIJJJJIIJIIIJIIJJJIJIJIJJJJJJIIJIJJIJIIJJIJJI(float IJJJIIIIJIIJJIIJJJJIJJJJJIIIJJJJJJJIJJJIIJIJIJJ, float JJIIIJIIIJJJIJJIIJIJIIJIJIJJIJJJJIIJIIJIIIJJJII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, TweenCallback IIIJIJJIJJIJJIIJIIIJIJJIJJJJJIIIJIJIJJJIJJIJIJJ)
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}
}
