using UnityEngine;

public class UIForwardEvents : MonoBehaviour
{
	public GameObject IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

	public bool JIJJJJJIJJIJJIJIIJJIIIIIJIIJIJIIIIIIJIIIJJIJIJI;

	public bool IIIJJIIIIIIJIJJJJJIIJIIJJJIJIIJJIJJIJJIIIJIIJJI;

	public bool IJIIIJIJJJIIJJJIIIIJJJJJIIIIJJIIIIJJIJIIIJIIIJI;

	public bool JIIIJIIJIJJJIIJIIIIIJIJIJJJJIJJIIJJJJJIIJIIIJJI;

	public bool JIIJIIJJIIJJIIJJIJJIJIIIJIJIJJJIIIJJJJJIIIJJIJI;

	public bool JIIIJIJIIIIJIIJIJIJIJIIJJJIIIJIJIIIJIIIJIJJIJIJ;

	public bool IIIJIIJJIIIJJIIJIJJJIIIJJJJIJJJIIJJJIJJIJIIIJIJ;

	public bool JJIIJJJIJIIJJIIIJJIIJJJIJIJJJIJIJIJJIIJJIIJIIJI;

	public bool JJIIJJJJJIIJJJJIIJIIJIIIJJJJIIJIIJIJIJIJIIIIJJJ;

	private void OnSubmit()
	{
	}

	private void IJJJJIJJJIIJJIIJIJJIIJJJIIJJJJJJJIIIJJIJJJJJJIJ()
	{
	}

	private void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	private void OnClick()
	{
	}

	private void JIIIIJIIJJJIIJIJJJJIJIIJIIIJIJJIJJIJJJJIIJIIIJJ()
	{
	}

	private void IJIJIIIJJJJJIJIIJIJJIIIJIIIIJJIIJIIJIIJIJIJIJJI(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void IIIIJIIIJIJIJIIJJIJJIJIJJJIIJIJIJJIIJIJIIJJIJJJ(float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IJIIJIIJIJIIJJJIJJJIIIIIIJJIJJJJJJIJJIJIJJJJJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void IIIJJIIJIIJJIIJIJIJIIIIIJJJJIIJIIJIIJJIJIIIJIJI()
	{
	}

	private void JJIJJJIJJIJIJIIJJIJIIIIJJJJIIIJJJIJJJJIJJJJIJIJ(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IJIIJIIIIIIIIJIIIIIJIJJJJIJIIIIJIJJJJJJJJIIIJII(float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void IIJJJIIIJIJIJJJJIIJIJIJIJJJJJIJIJJJJJJJIJJIJJII(bool IJIJJJJIJJJJIIJJIJJIIJIIIIIJJIJIIJIIIIJJJJIIIIJ)
	{
	}

	private void IIJIJIJJJJJJJIIIIJJIJJIJIJIIIJIIIJIJJIJIJJJIJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void JIJIJIIIJIJIJJJJIIIJIJIJJIJJIJJJJIIIIIIJIJIIJII(bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	private void JIJJIIIIJIIIIIIIJJJIIJJJIJJJIJJJIJJJIJIIIJJJIII()
	{
	}

	private void IIIIJIJJIJJJJIJIIJIJJIJJIJIJIJJIJIJJJJIIIJJIJJI(bool IJIJJJJIJJJJIIJJIJJIIJIIIIIJJIJIIJIIIIJJJJIIIIJ)
	{
	}

	private void JIIJJIJIJIJIIIIIJJJJJIJJJIIJIIIIJIIJJJIJIIIJIJJ(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JIJJJIIJJIIIIJIIIIJIJJIJIIJIIJJIJIIIJJJIIJIJJJI(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JIIJIIIIJJJIIIIIIJJIIIIIIJJJIJJJJJIJIJJIIIIIIJI(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void IJIIIJJIIJIIIIIIJJIJIJIJJIJJIIIJJIJIIIJJJJJIJJI()
	{
	}

	private void IIJIIIJJIJJJIJIIIIIJJJIJIJIJIIJJIJIJJIJIIIIJIII(float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JIJIJJIIJIIIJJJJIIJIIJIJJJJIIJJIJJIIJIIJIIJJIIJ(bool IJIJJJJIJJJJIIJJIJJIIJIIIIIJJIJIIJIIIIJJJJIIIIJ)
	{
	}

	private void JIJJIJIIJJJIJJIIJJIJJIJIJIIJIIIJIIIJIIJIIIJIJJI(bool IJIJJJJIJJJJIIJJIJJIIJIIIIIJJIJIIJIIIIJJJJIIIIJ)
	{
	}

	private void IIJIJIIJJJIJJJIJIIJJIIJJIJIJJJIJIJJJJIIIIIJIIII(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}
}
