using UnityEngine;

public class UIFollowTarget : MonoBehaviour
{
	public Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

	public Camera IIJJIIIJIJJJIIIJJJJJJIIJIIIJJIIIIIJIJJJIIIJIIII;

	public UIWidget JJIJJJIIIIIIIJIIIIIJJIIJIJIIIJJJJIJIJJJIJJIJIJI;

	public UISprite JIIIJIIJJIIIJIJJJJJIJIIJIJIJJIIJIJJJIIJJJJJJJIJ;

	public UILabel JJJJJIJJIIJIIJIJJIIJJIJIJIIJJJJIJIIJJJIIIJJJJJJ;

	private Camera JJIJIIJJJIIJIIJIIJJIJIIJJIIIIJIJJIIJIIIJJJJJIII;

	private Transform JJJIJIIIJIIIIJJJJIJJIJJIJIIJJIIIIJIJJJJJJIJIJJJ;

	public float IJIIIIIJIJIIJJIJIJJIIIJIIIJIJJJIJJIJJIIJJJJIJJI;

	public float IJIJJJJJJJIIIIJJJIJJJJIJJIJIIIJJJJJIIJIIIJIJJII;

	public Vector3 JJIJJIJJIIIJJJJIIJJIJIIJIJIIIIIIIJJJIJIIJJJJIJI;

	public Rect IJIIIJIJIIIIIIIJIIIJJIJJIJJJJIJIJJJJJIJIJJIJIJI;

	private Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ;

	private bool JIJIJIIJJIJIJJJIJIIJIIIIJIIIJJIIIJJJJJJJJJIIIJI;

	private static UIFollowTarget JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void JIJJJJIIIJIIIIJIJJJJIIJJJIIJJIIJJJIIIIIIIJIIIJI()
	{
	}

	private void Update()
	{
	}

	public static void JIIJJIIJJIJJJIJJIIIJJJJIIIIJJIIJIJIJJIJJJIIIIJI(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ, string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, Color IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ)
	{
	}

	public static void JIJIJIJIIJIIJIJJJIJIIIIIIIJIJJIJIIJIJIJIJJJIJJJ(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ, string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, Color IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ)
	{
	}

	private void JIJJIJJIIJJIJJIJIJJIIJIJJJJJIIJIIIJJIIIJJIJIJII()
	{
	}

	public static void JJJIJIJIIIJJJJJJIIIJJIIJIIIIJIJIIJIJJIJJIIIIIII()
	{
	}

	private void JIJJJIIIIIJIJJIIJIJIIIIJIJIIJIIIIJJJIIJJJIJJJIJ()
	{
	}

	private void JIIJIJJIIJJJJJIJJIJJIJJIJIJJJJIIJIJIJIJJJIIIJIJ()
	{
	}

	private void JJIIIJJIIJJIIIJJJIJIIJIIJIJJIIJJIIJJJIJIJIJJIIJ()
	{
	}

	private void JIIIJIIIJJJIIIIIJIIIIJJIIJIIJIJIIJJJJIIIJIIJJJI()
	{
	}

	private void JIIIJIIJJJJIJIJJJIIIIIJIJJIIIIJJJJJJJJIJIIIIJJI()
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void Start()
	{
	}

	public static void JJJJJIIJJJIJJJIJIJIIIJIJIIJJIIJJJJIJJIJJIJIJIJJ(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ, string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, Color IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ)
	{
	}

	private void JJJJIJIJIIJJJJIIIIJJJIIIIJJIIIJJIJJIIJIIIIIIJIJ()
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	public static void IIIIIJJIJIIJJJIJIIJIIJJJIIJIJIIJJJJIIJIIIJIIJJI(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ, string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, Color IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ)
	{
	}
}
