using UnityEngine;

public class UIFontManager : MonoBehaviour
{
	public UILabel[] IIJIJIIJJIJJJIJJJIJIJIJIJIJJIIIIIJIJJJJJIIJJJIJ;

	public UIPopupList[] JJJIIIIJIIIJIJIJJIIJIIJJJJIIJIJIJJJJJJJIIIIJIJJ;

	public Font[] JIIJJIIIIIJJIIJIIJIJJIJJJIJJJIIJIJJIJJIIIIJIJJJ;

	private static UIFontManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static Font[] IIJIJIIIJJIIIJJJIIIIJJIJIIIJIJJJIJJJIJJJJIIJIII()
	{
		return null;
	}

	public static void JIJJIIIJIJJIIIIIJJJIJJJIJIJJJJJJIIIJIJJJJJIIJII(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}

	public static void JJIIJIJJJIIIIIIIIIJIIJIJJIIJIIJIJIJJJJJIIIIIIJI(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}

	private void Awake()
	{
	}

	private void JIJJIIIJJIJIIIIIJIIJIIIIJJJIJIIIIJJJJJJJJIIIIIJ()
	{
	}

	private void IJIJJJJJIJJIIJJJJJIJIJJIJJJJJJIJIIIIIIJJJJIIIIJ()
	{
	}

	public static void IJJJJIJIIIJJIIJJJJJIIIIJIIIJJJIIJJJJIJIJJIJIJJI(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}

	public static void JIJJJJIIJJJIJJIIJJIIJJJIIJIIIIJIJIIIJJJIJIIIJJJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}

	public static Font[] JJIJJJJIIIIIJIIJIJIJIJJJJIIJJIIIIIJJJJIIIJIIJII()
	{
		return null;
	}

	public static Font[] JIJIIIIJJIIIJIIJJJJJJIIJJJIJIJIIJJIIJJJJJJIJIJI()
	{
		return null;
	}

	private void JIJJJIIIJJJIJJJIJJIIIJJJIJIJJIJIIIJIJJIIJJIJIIJ()
	{
	}

	private void IIJIIJJJIIJJJIIIJJIJIJJIIJJIIIJIJJJIJJIJIJJIJJI()
	{
	}

	public static void IJJIIIJIIIJIJJJIJIJJIJJJJJIIIJJIIJIJJJJJIJJJJIJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}

	private void JIIIJJIJIJJIJJJIIIIJJJIJIJIJIIIJJJJIJJIIIIJJIII()
	{
	}
}
