using System.Text;
using UnityEngine;

public class UIFramesPerSecond : MonoBehaviour
{
	public const int IIIJJIJIJJIJJIIIIJJJIIIIJJJIIIJJIJJIIJIJJJJJJJI = 1048576;

	public UILabel JJJJJIJJIIJIIJIJJIIJJIJIJIIJJJJIJIIJJJIIIJJJJJJ;

	private bool IJIJJJJIJJIJJIJJIIIJJJIIIJIJJJJJIJJJIJIIIIJJIIJ;

	private float JIIIIIJIJJJIJIIJJIIJJIIIIIJJJJIIJJJIIIIJJIIIJJI;

	private float IJIJIJIJIIJJJIJJJJJIJJJJIJJJIJIJJIIIIIJJIJIIJJI;

	private StringBuilder IJJIJIJIIIJIIIIJJIIJIJIIJIIIJJJIJIJIJIIIJJIJJJJ;

	public static bool JJJJJIIJJIJIJJJIJJIIJJIJIJIIIJJIJIJIJIJIIJJJIJJ;

	private void JIIIIJJJIIIIIIJIIIJJIIIJIIIJIJJIIJJIJJJJIJJJIJI()
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void JJJJJIJJIIIIJJJJIIJJIIIJJJIJJJJJJIJJIIIIIJIJIJI()
	{
	}

	private void Start()
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private void IIIJIJJIJJIJIJIJIJIIIIJIIJJIIIJJJIJJJJIIJIIJIIJ()
	{
	}

	private void JJJJJJIIJJIJIIJIJJIIJIJIJJJIIJIIJJJIIJJIJJJIIII()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	private void JJJJIJJIIJJJJIIJJJJJJJJIJJJIIJIIIJJJIJJIJIIIIJJ()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void IIIJJJIJIIIJJIJIIJJIIIIJIIIJJJIIIIIJIIIJJIIJJII()
	{
	}

	private void Update()
	{
	}

	private void IIJIIJJJIIIJJJIJJIJJIJIJJJIIJIJJJIJIIIIJJJIIIJJ()
	{
	}

	private void JJIJIJIJJJJJIIJJIIIJJIJIIIJJIIJJJIIIIJIJJIIIIJI()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void OnDisable()
	{
	}
}
