using System.Collections.Generic;
using UnityEngine;

public class UIFriends : MonoBehaviour
{
	private sealed class IIJJIJIJJIIIJIJIJJIIJJIJIJJJJJJJIIIIJJIJJJJIJJJ
	{
		public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII;

		internal void IJIJJIIJIIJJIIIIJIIIIIIJJIJJJJIJJIIIIIIJIIJJIII(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IJIIJJIJJJIJIIJJIIIJJJIIJIIJIIIJJJIJJJIJIIJJIII(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void JJIIIIJIIIIJJJIIJIJIJJIJIJIJJJIJJJIJJJIIIJIJJII(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IIIIJJIJIJJIJIJIIIJJIJJJIJIJIJIJJIJIIIIJJIIIIJI(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IJIJJJIIIJJJIJIJJIIJIJJIIJJIIJIIJIIJIJIJJIIJIII(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IJJIJJJIIIJIJJIIIJIIIIJJJJJJJIJJIIIIIIIJIJJJJJI(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IJJIIJJIIIIIIJIIIIJIJIJJIJIJIIJIIIIJIJJJJJIIJJI(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IJIIIJJJJJIJIJIIIJIIJIJJIJJJJIJJIJJIJJIJIJJIJIJ(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IIJJJJIJIIIJIJJJIJJIIJJIJJIJJIJIJIJIJJIIJIJJJIJ(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IIIJJJJIIIIIJJJJIIIIJJIIIJJIIJJIIJJIJIIIIJJJIII(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IJJJIJJJIIIIIJIJIIJJIIIJJIJIJJJIIJIIIJJIJIJJIII(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IIJIJJIJJJJIIIJIJIIIJJIIIIIJJJJIIIIJIJIIIJJJJIJ(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IIJJIJJJIIJJIJIJIIJJJIIJIJJIJIIJIIJJIJIIIIIJJIJ(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IIJIJJIJJJJIJIJIIIIIIJIJJIIIJJIIJIJJIIJJIJIIIJI(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void JIIJJJJIIIIJIIJIJJJJIIIJIJIIIJJJIIJJIJJJIJJIIJJ(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void JIIIIJJIJJIIJIIJJIJIIIJJIIJIJJIIIJIJJJJIJJIJJIJ(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IIJJJJIJIIIIJJJJIIJIJIIIJJIIJIJJJJJJIJIJJJJIJIJ(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IIJIJJIIJIJJJJJJJIIIIIJIIIJJIIJIIIJIJIJIJJIIIJI(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void JJIIJIJJJIJJIJJJJIJJIIJJIJIIJJJJIJJJIJJIIJJJJII(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IJIJJIIJJJIIIIIIJIJIIIJIIJJJIIJIJIIIJJJIJJIIIJI(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}

		internal void IIJIIJIIJIIJJJIJJIJJJJIIIIIIJJIJJJIJIIJJIJIJIII(bool JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
		{
		}
	}

	private static List<int> JIJIJIIIJIJJJJJJIJJJIJIJJJJJIIIJJIIJIIIIIJJIJJJ;

	public const int JJJJJIJJJJIJJIJIJIJJIIIIIIJIIIIIJIIIIIJJIIIJJJJ = 50;

	private void IIJJIIIJIIIJIIIIIIJJIIJJJJIIIIIJJJIJJJIIJJJIJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void JJIJIIJIIJIJIIIJIJIIIIJIIIJIJIIIIIJJJJJIIIIIJII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	private void IJJJIJIJIIIJJJJIJJJIIJJJJJJJJJJJIIJIIJIIJIJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IIJIJIIIJJIIIIIIIJJIIJIJIJIJIIJIJJJJJIJIJJJIJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	public static void IIIJJJJJJJJJIJJJIJJJIJJIIJIIIJJIJIJIJIJJIIIJJJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	public static void JIIIJJJIIJJJIIIIIJIIIIIJJJJJJJJIJJIJIIJIIJIIJJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	public static void JIJIIIIIIJIJJJIJIIJIIIJIIJIIIJJIJIJJIJJIJIIIIIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	public static void IJIJIJJJJJIIIJJJJIIJJJIIIIJJIJJJIJJIIJJJJIIIIJI(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void Start()
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	private void IIIIIIIJIJJIIIIIIJIJJJJJJIIJIIJJIJIJIJIIJIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJIJJIJIJIIJIJIJJIJJIJIIIIIJJJJIIJJIIJJIIJJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJIIJIJIJJIJJJJIJIIIJJJJIIIIIJIJIIJJJIJIIIIJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void JIIJJIJJJIJIJIJIJIIJIJIIJJIJIJIJIIIJIJJIJIJJJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJJIIJIJIJJIIIJIIJJIJJIJJIJJIJJJJJJJIJJIJIIJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IJJIJIIIIJJJJJJIJJIIJJIIJIJIIJIIIIIIJIIIJJIJJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	private void JJJIIIIJIJIIJIJIJJIJJIIJJIIIJJIJIJIIIJJIJJIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIIIJIIJIJJJJIJIIIJIIJIIIJIJJJIJIJJJIJJIIIJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJIIJJIJJJIIIIIIJIJIIJIIJJJJIIIIIIIIIJIJJIJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}
}
