using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;

public class UIGameConsole : MonoBehaviour
{
	public enum JIJJIJIIIJIJIJJIIJJJIIJJIIIJJIIIIIJJJIJJIJJIIJI
	{
		None = 0,
		Int = 1,
		Float = 2,
		Bool = 3,
		String = 4,
		Vector2 = 5,
		Vector3 = 6,
		Color = 7
	}

	public class JIIIJIIJIJIIJIIJIJIIIIIIJJIJJJIJIIJIIIJJIIIIJJI
	{
		public JIJJIJIIIJIJIJJIIJJJIIJJIIIJJIIIIIJJJIJJIJJIIJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI;

		public MethodInfo JJIJIJJJIIIIIJIJJJIIJJIJIIIJIJIIJIJIIJJJJJIJJJJ;
	}

	public UIInput JIIJJJIIIJJIJIJJIJJJIIJJJJJJIJJIIIIIIIJIIJJIJJI;

	public UITextList JJIIJIIIIIJIJJJJJJIJIJIIJJJJJJJIIIIJIJJIJJIJIII;

	private static Dictionary<string, JIIIJIIJIJIIJIIJIJIIIIIIJJIJJJIJIIJIIIJJIIIIJJI> IIIJJJIIIJJIIIIJIIJJIIJIIIJIJJJIJIIIIJIJIJJJIIJ;

	private List<string> JJIJIJIJIIIIIJJJJJIJIJIJJIIJIIJJIJIIJIIJIJJIIIJ;

	private int IJIIJIJJJJIIJJIIJIJIJJIJIIIJJJJIIJJJJIJIJJIIIJJ;

	private List<string> IJIIIJIJJIIIJIJJJIIIIIIJIJIJJIJJJIIIIIJIIIJJIIJ;

	private string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI;

	public static string JIIIIIJJIJJJIJJIIJIJIJJJIIJIIIJIJJIIJIIJIIJIIJJ;

	public static void JIJJIJIIJIIIIJJJJIIIIJJIJIJJJIJJIIJIJIIJJJJIJII(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private bool JJJIJIIJIJIJJIIIJIIJJIIIIIIIJJIIJIJJIIIIJJJJJJI(string JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ, string IIIJJIJIJJJJJIIIIJIJJIJIIIJJJJJJIJIJIIJJJJIIIJJ)
	{
		return false;
	}

	private string IJJJIIIJIIJIJIJJIIIJIIIIJJJJJIJIIJIIIJJJJIJIIIJ(JIJJIJIIIJIJIJJIIJJJIIJJIIIJJIIIIIJJJIJJIJJIIJI IJIJJIIIJIJIIIJIJIIJIJJIJIIIJJIJJIIIIIIJIIJJJII)
	{
		return null;
	}

	private string JIJJIJIJJIJJIIJJIIJJJJJJIJJJJIJIIJJIJIIJJIIJJJJ(JIJJIJIIIJIJIJJIIJJJIIJJIIIJJIIIIIJJJIJJIJJIIJI IJIJJIIIJIJIIIJIJIIJIJJIJIIIJJIJJIIIIIIJIIJJJII)
	{
		return null;
	}

	private static JIJJIJIIIJIJIJJIIJJJIIJJIIIJJIIIIIJJJIJJIJJIIJI IIJJJJIJIJJJIJIJIIIIJJIIJJIIIJJIIJIJJJJJJJJIJJJ(Type JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return JIJJIJIIIJIJIJJIIJJJIIJJIIIJJIIIIIJJJIJJIJJIIJI.None;
	}

	public void IIIIJJJIIJIJJIIIJJIJIIJJIJJIJJJIJJJIJJIIIJIJIJJ()
	{
	}

	public static void JIJJIJIJIJIIIIJIIIJIJIJIIIIJJJJIJIIJJIJJIJIJIII(bool JJIIJJJJJIIJIIIJJIJIIJIJJIIIIIIIJIJJIIIJJJJJIJI)
	{
	}

	private void IIIIJJIJIJJIJJIJJIJIIIJJIJJIJIJJIJIIJJIJJIJJJIJ()
	{
	}

	private bool IIJIJIIJJJJJJIIJIIJJJIJJJJJJIJIJJJIJIJJIIJIIIII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, out object JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, JIJJIJIIIJIJIJJIIJJJIIJJIIIJJIIIIIJJJIJJIJJIIJI IJIJJIIIJIJIIIJIJIIJIJJIJIIIJJIJJIIIIIIJIIJJJII)
	{
		JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ = null;
		return false;
	}

	public void OnSubmit()
	{
	}

	private bool IIIJJIJIIJIIJJIJIJIIJIIIJIJIIIJJJIJIIJIJJIIJIIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, out object JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ, JIJJIJIIIJIJIJJIIJJJIIJJIIIJJIIIIIJJJIJJIJJIIJI IJIJJIIIJIJIIIJIJIIJIJJIJIIIJJIJJIIIIIIJIIJJJII)
	{
		JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ = null;
		return false;
	}

	private void JJIJJIJIIJIJJJJIJIIJJIJJIJIJJJIIIIIIIJJIIIIIIJI()
	{
	}

	public static void JIJIIIIJJJJJJJIIIJJIIJJIIJIJJIIJJJJJIIJJJJIIJII(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJJIIJIJIIIIJIIJIJJJIIJIJJIIIIJIIJIIJIIJIIJJJJ()
	{
	}

	private void IIJJIJIJIIJJIJIIIJIJJIJJIIIIIIJIIJIJJIJJJIJIJII()
	{
	}

	public void IJIIIIIIIJIIIJJJJJJJIIJIIIJIJJIJIJIIJIIIJIJJIJJ()
	{
	}

	private void JIIJIJJIIIIJJJJIIJJJJJJJIIIIIIIJIJJIJJIIJIIJIJI()
	{
	}

	private void IJIJIIJIIJIJJIJJJIJIIIJJIIJJIJJJIIJJIJJIJJIIJIJ()
	{
	}

	public static void JIJIIJIJJIIIJJIIIIJJJJIIIIIJIIIJJJIJJIIIIIIIIJJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private bool IJIJIIIJIIJIIJIIIJIIIJJIIIJIJIJJIIJIIJIJIIIIIJJ(string JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ, string IIIJJIJIJJJJJIIIIJIJJIJIIIJJJJJJIJIJIIJJJJIIIJJ)
	{
		return false;
	}

	private static JIJJIJIIIJIJIJJIIJJJIIJJIIIJJIIIIIJJJIJJIJJIIJI JIIJJJJJJIJJJIJIIIJJJIIIJIJJJIIIJJJJIIIJJIJJIII(Type JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return JIJJIJIIIJIJIJJIIJJJIIJJIIIJJIIIIIJJJIJJIJJIIJI.None;
	}

	public static void IJIJJIIIJJIJJJJJIIIIIJJJIIIJJJJIJJIIJJIIJIJIJIJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IIJIJIJIIIJIJJJIJJIIIJJIIJJJIJJIJJJIIJJIJIIJJJJ(bool JJIIJJJJJIIJIIIJJIJIIJIJJIIIIIIIJIJJIIIJJJJJIJI)
	{
	}

	public static void IIIJIIJIIIJIIIJJIJJJIJJJIJJIJIIIJJIIJJJJJIJJIJJ(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private bool JJIJJIIJIIJIJJIJIIIIIJJIJIJJIJJIJIJJJIIJJIJIJIJ(string JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ, string IIIJJIJIJJJJJIIIIJIJJIJIIIJJJJJJIJIJIIJJJJIIIJJ)
	{
		return false;
	}

	public static void JIJIIIIJIIIJJIIIIJIIJIIIJJIJIIJIIJJIJJJJIIIIIII(string JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private static JIJJIJIIIJIJIJJIIJJJIIJJIIIJJIIIIIJJJIJJIJJIIJI IIIIJIJJIJIJJJJJJJIIJJIJIIIIJIJJIIJJJIIJIIIIIJI(Type JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return JIJJIJIIIJIJIJJIIJJJIIJJIIIJJIIIIIJJJIJJIJJIIJI.None;
	}

	private void Start()
	{
	}
}
