using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class UIGrid : UIWidgetContainer
{
	public delegate void IIIJIIIIIJIJIJIJIIIJIIIJJIJJJJJJJIIJJJJJJIJJJII();

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JJIJJJIJJIIIIJIIIJIJJJIIJJIIJIIIJJJIIIJIJJIIJIJ
	{
		Horizontal = 0,
		Vertical = 1,
		CellSnap = 2
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JJIIIIJIIJJIJIJIJJJIIIIIIJJIJIJJIIIIJIIIJIJIIJJ
	{
		None = 0,
		Alphabetic = 1,
		Horizontal = 2,
		Vertical = 3,
		Custom = 4
	}

	public JJIJJJIJJIIIIJIIIJIJJJIIJJIIJIIIJJJIIIJIJJIIJIJ JIIJJJJIJIIJJJJJIIJJJJJJIJJIIIJIIIJJJIIIIJIJIJI;

	public JJIIIIJIIJJIJIJIJJJIIIIIIJJIJIJJIIIIJIIIJIJIIJJ JJJIIIIJJIJIIIJJIIIJIIJIJIIIIJJJJJJIIIJIJJJJIIJ;

	public UIWidget.JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII JJJJJIJIJJIJIJIIIJJIIIJJJIIIJJJJJJIIIJIJIIJJJJJ;

	public int IIJJIJJIIJIJIIIJJJJIJIIJJIJJJIIJIJIJJIJIJIJIIIJ;

	public float IIIIJIIJIJIIJJJIIIIJIIIIJIJJJJIJJIIIIIIIIIJJJJJ;

	public float JIJJIIIIIJIJIJJJJJJIJIJJIIIIIIIJIJIJIIJIJJIJIIJ;

	public bool IIJIIIIJIJIJIIIJIJIIIIIIJJIIJJIIIJIJIIIJIIJJJJJ;

	public bool JJIIIJIJIIJIJIIJIIJIIIIIJJJIJIIIJIJJJJJJIIJJJJJ;

	public bool IJIIJJIJIJIIIJIIIIJJIIIJJJJIIIIIJJJJIIIIIJJIJJI;

	public IIIJIIIIIJIJIJIJIIIJIIIJJIJJJJJJJIIJJJJJJIJJJII JIJJIJIIJIIJIIIIJJJJIJIIIJJIJIIJIJJIJJJIIIIJJIJ;

	public Comparison<Transform> IJIJIJJIIJIJJJIIIJJIJJIJJJJIJIJIJJJJIIIIJIJIIIJ;

	[HideInInspector]
	[SerializeField]
	private bool sorted;

	protected bool IIIJIIIJJIIJIJJIJJJJJIIJIIIJJJIIJJJJJIJIIIJJJIJ;

	protected UIPanel IJJIIJJJIIJJJIIIIJIIJIIIJIIJIJIJIJIIJIJIIJJIJJJ;

	protected bool IJIIJIJJIJJJIJIJIIIJIIJJIJIJIIJIIJIIJIIJJIJIJIJ;

	public bool IIIJIJIIIIIJJJIJIJJIJIJJJIIIIIJIIIIIIIJJJJIJJJI
	{
		set
		{
			JIJIJIIIIJJIIIIJJJJIIIJIJJJJJJIIIIJJJJJJIJIJJJJ(value);
		}
	}

	[Obsolete]
	public void IIJIJIJJIJJJIJJJJIIJIJIIJIIIJIIJIJIJJIJJIJIIJJJ(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ)
	{
	}

	protected virtual void IJIIJJIIIIJJIIIIIIJJIJIJJJIIJJJIJJIJIIIIJJIJIJJ(List<Transform> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
	}

	public Transform JJJJIIIIIJJIJIIJIIIJIIJJJIIIJJJJIJIJIJJJJJJIJJI(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}
	public void IIIIIJJJIJIIIIJIJJIJJJJIJIJJIIJIIJJJJIIIIJIJIII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected virtual void JIIIJJIIJIJIIJIJJIIJJJJIJIJJIJIJJIJIJIIIIJJJIII(List<Transform> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
	}

	public virtual void JIIJIJJIIJJJIJIIIIJIJIIJIIJJIJIJIJJJJIJJJJJIIJI()
	{
	}

	public int IIIIJIJJJIIJJIJIIJJJJIJIIJIJIIIIIJJJIIJIJJIJJIJ(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ)
	{
		return 0;
	}

	protected virtual void JJIIIIIJIIJJIJIIIIJIIIIJJIJJJIJJJJJIIJIIIIJIJJJ(List<Transform> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
	}

	public Transform IIIIIIJIIIJIJJJJIJJJJJJIJIIJIIIJJJJJIJJIJJJJIIJ(int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
		return null;
	}

	public bool IJIIJIJIJJIJJIJJJIJJIJIJJIJJJIJJIJJJIJJJJJJIJII(Transform JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
	{
		return false;
	}

	public static int IIIJIIJJJIIIJIJJJIIIIIIIIIIJIIIJIJIJIIIJJJIJIJJ(Transform IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, Transform JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	protected virtual void Start()
	{
	}

	public void JIJIJIIIIJJIIIIJJJJIIIJIJJJJJJIIIIJJJJJJIJIJJJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static int JIIJIIIIIIJIIJJJJIJIIIIIIJJIJJJIJIJJJIIIJJJIIII(Transform IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, Transform JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	public void JIJJIJJJJJJIIJJJIIJIIJJIIJIIJIJIJJIIJJJIIJIIJII(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ)
	{
	}
	public void JJIIIIJIIJJIJIJJJIJJJIJIJJJJIIJIIJJIJIIJJJIJIII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIIIIJJJJIJJJJJJJJIJJIJIJJJIJJJIJIJIIIJJJIJJJI()
	{
	}

	public static int IIIJJJIJJJJIJJIIIIJIJJJIJJJJJIJJIIIJIJIIIJIIJIJ(Transform IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, Transform JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	protected virtual void IJIJIJIIIIJIIIJJIJIIJJJJIJJIJJJJIIIJJJIJIJIIJIJ()
	{
	}

	public static int JJJIIJIJIIJJJJJJIIJIIJIJJJJJJIJJIJIJJJJJIJIIJIJ(Transform IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, Transform JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	private void IIIIIJJJJIIJJJIJIJJIIIIIJJJJJIIIIJJIJIIJJJJJIII()
	{
	}

	public List<Transform> JJJJJJIIJJIIJIJIIJJIIJIJIJIJIJIIJIIIIIIIIIIIIIJ()
	{
		return null;
	}

	public int JJJJJIIIJJJIIJJIJIIJJJJIIIIJJJJJIIJJIIIJIIIIIIJ(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ)
	{
		return 0;
	}

	protected virtual void JIJJJJIIIJIIIIJIJJJJIIJJJIIJJIIJJJIIIIIIIJIIIJI()
	{
	}

	public void JIJIJJIIIIJJJIJJJJJJIJIJIIIJJJJIJIIIIJJJIJIJJJJ(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ, bool JJJJJJIJIIIIJIIJJJIIIIIIJJJJJJIIIJIIJIJJIIIJIJJ)
	{
	}

	protected virtual void IIIJJIJJJJIJIIJIIIIIIIIIJJIIJJIJJJIIIJIJJJJIJIJ()
	{
	}

	public virtual void JJJJJIIJJIJIJJJIIJJJJIJJJJIJJJJJIJJJIJIJIIJJIJJ()
	{
	}

	public void JIIIJIIJIJJIIJJIJJIJJIIJJIIIIJJIIIJJJIJJIIIIJJJ()
	{
	}

	[Obsolete]
	public void IIJIJIJJIJJJIJJJJIIJIJIIJIIIJIIJIJIJJIJJIJIIJJJ(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ, bool JJJJJJIJIIIIJIIJJJIIIIIIJJJJJJIIIJIIJIJJIIIJIJJ)
	{
	}

	protected virtual void Update()
	{
	}

	public void JJJJJJJIJIIJJJJIIIIJIJIJJIJIJIIJJIIIIJJIJIIIJII()
	{
	}

	public void JIIIJIJIJIJIJJJJIJIJIIIIJIJIIJJJJIJJIJJJIIJJJII(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ, bool JJJJJJIJIIIIJIIJJJIIIIIIJJJJJJIIIJIIJIJJIIIJIJJ)
	{
	}

	private void OnValidate()
	{
	}
}
