using UnityEngine;

public class UIHealth : MonoBehaviour
{
	public UILabel JJJJJIJJIIJIIJIJJIIJJIJIJIIJJJJIJIIJJJIIIJJJJJJ;

	public UISprite JIIIJIIJJIIIJIJJJJJIJIIJIJIJJIIJIJJJIIJJJJJJJIJ;

	private Color JIJIJJIIIIIJJJJIIJJIIIIJIJIJIJIJIIIJJIJJJJIJIJI;

	private Color JJIJJJIJJIJJJIJIJJJIIJJJJJJIIIJJIIJIJJJJJIIIIIJ;

	private static UIHealth JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private static readonly string IIJIJJIJJIIJJIIIJIJIJIJJIIIIJJJJJIIIJIJIJJIIIJI;

	private static readonly string JIIIJIJIIIJIIJIIIJJIIJIJJIJIIIIJJJIIJJIJJJIJIJJ;

	public static void JIJIJJIJIIJIJIJIIIIIIIJIIJJIIIIIJJJIIIIIJIJJJJI(int IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII, int IJJJIIIIIIIIIIIIJJIJJIIJJIIIJIIJJJJIIJJIJIJIJJI)
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	public static void JIIIJJJIIJJJIIJJIIIIIJIJJJJIIJJIJIIJJJIJJIJJIJI(int IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII, int IJJJIIIIIIIIIIIIJJIJJIIJJIIIJIIJJJJIIJJIJIJIJJI)
	{
	}

	public static void IIJJJJIIJJIIIJIIJIIJIJIJIIJJJJIIIJIIJIIJIJJIIJI(int IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII, int IJJJIIIIIIIIIIIIJJIJJIIJJIIIJIIJJJJIIJJIJIJIJJI)
	{
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void Start()
	{
	}

	public static void JJIJJIJIJIJIIJJIIIJJIJJIJIIIIJIIIIIIJJIJIIIJJIJ(int IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII)
	{
	}

	public static void IIJIJJIIJJIIJJIJIJJIIIIJJIJIJJIJJJJIJJJIIJIIIJJ(int IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII)
	{
	}

	public static void JIJIIJIIIIJJIJJJJIJJIIIIJIJIIIIIIIIIJIIJIJIIJJI(int IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII)
	{
	}

	public static void JIIJJJIJJIIJJJJJIIJJIIJJJJIJIJIIIJJJJJIIIIIJIJI(int IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII, int IJJJIIIIIIIIIIIIJJIJJIIJJIIIJIIJJJJIIJJIJIJIJJI)
	{
	}

	public static void JIIJIIJJIJJJIJIJIJJJJIJJJJIJIJJIJIIIIJJIIJJIJJJ(int IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII, int IJJJIIIIIIIIIIIIJJIJJIIJJIIIJIIJJJJIIJJIJIJIJJI)
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	public static void JJIJJIIIJJJIJJIIJIJJJJJIIIJIJIIJJJJIJJIIJJJJJJJ(int IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII, int IJJJIIIIIIIIIIIIJJIJJIIJJIIIJIIJJJJIIJJIJIJIJJI)
	{
	}

	public static void JIJIJJIJIIJIJIJIIIIIIIJIIJJIIIIIJJJIIIIIJIJJJJI(int IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII)
	{
	}
}
