using System.Runtime.CompilerServices;
using UnityEngine;

public class UIHUDManager : MonoBehaviour
{
	public UIWidget[] JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ;

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void JIIIIJJJIIIIIIJIIIJJIIIJIIIJIJJIIJJIJJJJIJJJIJI()
	{
	}

	private void JIJJIIIJIIIIIIJJJIJJJJIJJIIIJJIJIJIIJJIIIIJIJJI()
	{
	}

	private void JJJJJIJJIIIIJJJJIIJJIIIJJJIJJJJJJIJJIIIIIJIJIJI()
	{
	}

	private void IJJIIIJIJIIIIIIJJJIJJJIJJIIJIIIIIJJJIIIIJIIJIIJ()
	{
	}

	private void IIJJJIIJIIIJJIJJJJIJIIIIIJIJJIJIJIJJIIJIJIIIIIJ()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	private void IJJJJJJJIIJJJIJJIJJIJJIIJIJJIIJJIIIJJIJIIIIJJII()
	{
	}

	private void JIIJIIIJJIJJJIJIIJJIIJIIJIIJJIJJJIJJIIJJJIJJJJI()
	{
	}

	private void IIJIIIIJIJIIJJJJJJJIIIJIJIIJIIIIJJJJIIIIJIIJIJI()
	{
	}

	private void Start()
	{
	}

	private void IJJIJIJJIIJIIIJJJIJIJJJIJIIJIJIIIJIIJJJJJJIIIJJ()
	{
	}

	[CompilerGenerated]
	private void JIIJJJJIJJJJIIJJIJJJJJIJIIIJJIJIJIJJIIIJJJIIIJI()
	{
	}

	private void IIIJJJIIJIIIJJJJJIIJJIJJIJIIIIIIJJIIJJIIJJJJIJJ()
	{
	}
}
