using UnityEngine;

public class UIInviteFriendElement : MonoBehaviour
{
	public UILabel IJJJJIIIJIJJJJIIJJJIJJIIJIIJJJJJJIIIIJJIIJIIJIJ;

	public UIWidget JJIJJJIIIIIIIJIIIIIJJIIJIJIIIJJJJIJIJJJIJJIJIJI;

	public UILabel JIIIJIIIJIIJIIJJIIJIJJJJIIJIJJIJJJIJIIJJIJIJIIJ;

	public int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ;

	private bool JIJIIJJIIJJJJJJJIIJIJJIJIJIIIJIIJJJJJIIJJJIJJIJ;

	public void JIJIIJJIIIIIJIJIIJIJJJIIJIJIIIIIJJJIIIIJIJIIIJJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void IIJIIJIJJIJJIIIIJIIIJIJIJJIJIIJJIIIJJIIJIIJJIII(bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void IJIJIJIIIIIJJJJJJIIIJJIJJIIJJJIJIIJIIJIIJIJJIJI(bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void JIJJJJJJIIIIIJJIIJJIIIJIJJIJJJIJIIIJJJIJIIIJJJI(bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void IJJIJIJIJIIJIJIJIIIIJJIJIJJJJJJJIJIIIJIJJJIIIIJ(bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void JIIJJJIJJIJIIIJJIIJIJJIIIIIIIIIIJJJJIJJIJJIIJII(bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void IJIIJJIJJJIJIJIIIIIJJJIJIJIIIJIIIJJJJIIJJIJJJJI(bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void JJJIJIJIIJIJIJIIJIJIJJJIJIJJIJIJJJJJJIIIIIIIJIJ(bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void JIIIIJIJJJIJIJIIJIIJJIJIIIJIJIJJIIIIIIIJJJIIJII(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void JJJIIIIIJIIIJJIJIJJIIJJIIJIJIJJIIIIJIJIJJIJJJII(bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void IJJIJJJIIJJIIJJIIJIJJIJIIJIJJJJIJIJJIIIJJIJJIII(bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void JJJJIJIIJJJJJIIIIJIJIIJIJIIIJJIIJIJJIIJJIJJJJII(bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void IJIIIIJJIIIIJJJIIIJIJJJIJJJIJJIJJIJJIIJIIIJIIIJ(bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void JJIIJJJJJIJJIIIIIIIJJIIJIIJIJJIIJJJIIJJJJIJIIJI(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void JIIJJJJJIJJIJJIIIJJIIJJJIJIJJIJIIIJIJIIIJIIJJII(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void JIJIIIJJJJIIJIJJIIJIJJJIIIJJJIIJJJJJJJIIIIIJJIJ(bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void JJIIIJIIIIIIJIJJJIJJIIIJIJJIIJJIJIIJIIJIIIIIIIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void IJIIJJJIIJJIJJIIIJIIJJIJIIIIJJJIIJJJIJJIJIJIJIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void IIIIIIIJIJIJIIIIIIJIIIJJIJJIJIJIJJJJIJJJJJJJIJJ(bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void IIJJIJJIJIIIIJJJJJIJIJJJIJIIJJJIIIIIIJJIJIIJJIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void IJJIJIIIJIIJJIIJIIJJJIJJJJJIJIIJIIJIJIJJIIJJJJJ(bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}

	public void JJIIJIJJIIJIIIIJJJIJJJIIJIIIJIIIIIIIIJIJIIJIJIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, bool JIJIJJJJIJIJIJIIJJIIIJJIJJIJJIJJIJJJIJIIJIIJJJI)
	{
	}
}
