using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class UIInput : MonoBehaviour
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IJJJJJJJJJJIIJJJIJIIJJIIIJJIIIIJIIIIJJIJIIJIIJI
	{
		Standard = 0,
		AutoCorrect = 1,
		Password = 2
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IIJJIIJJIIIJIJIIJIJJIJIIJIJIIIIIJIJJJJJIIJIJIJJ
	{
		None = 0,
		Integer = 1,
		Float = 2,
		Alphanumeric = 3,
		Username = 4,
		Name = 5,
		Filename = 6
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IIJJIIJIJJIJJIJJJIJIIJIIJIIIIIIJIJIIJIJJIIIJJIJ
	{
		Default = 0,
		ASCIICapable = 1,
		NumbersAndPunctuation = 2,
		URL = 3,
		NumberPad = 4,
		PhonePad = 5,
		NamePhonePad = 6,
		EmailAddress = 7
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IJIJJIIJJIIIJJJJIIIJIJIJIIIIIIJJJIJJJIJIJIJIJIJ
	{
		Default = 0,
		Submit = 1,
		NewLine = 2
	}

	public delegate char IJJJIIIIJJIJIIJIIIJJIJIJJJJJJIJIIIIJIJJJIJJIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, int JJIJJJIJJIJJJJIJIIIJIJIIJJIJIIJJIJJIIJIJJJJIIIJ, char IIIIJJJJJJIIJIIIJJJJJIIIJIJJJIIIJJJIIJJIJJJJJII);

	private GameObject IIIJIJIIIIIJJIIJIIIJJJIIJIJIIJIJIIJJJJIJJJJIIII;

	public static UIInput JIIJIIIIIIIIIIJIJIIIJJIIJJJIIIJJIIIIIIIIJIJIJIJ;

	public static UIInput IIJIJJIIJIIJJIIJIJJIJJJJIIIIIIIJIIIJJJJIJIIIJJJ;

	public UILabel JJJJJIJJIIJIIJIJJIIJJIJIJIIJJJJIJIIJJJIIIJJJJJJ;

	public IJJJJJJJJJJIIJJJIJIIJJIIIJJIIIIJIIIIJJIJIIJIIJI IIIJIJIJJIIJJJJIJIJJIIJIIIIIJIJIIJJIJJIIJIIIIII;

	public IJIJJIIJJIIIJJJJIIIJIJIJIIIIIIJJJIJJJIJIJIJIJIJ IIJIJIJIIIJIJIIJJJIJIIJIIIIJJJIJIJIJJJJJJIJIIJI;

	public IIJJIIJIJJIJJIJJJIJIIJIIJIIIIIIJIJIIJIJJIIIJJIJ IJJIJIIJIJJJJIJJIIIJIIIJJJIJJIJIIJJIIJIIIIIJJII;

	public bool JIJIIIIIJJIJIIIJJIIJIJIIJJJIIIJJIJJJIIIJJIJIIJI;

	[NonSerialized]
	public bool JJJIJIIIIJJJIIJIJJIJJJJJIJJJJIJJIJJJJJJIJJJJIJI;

	public bool JIJIJJJJJIIJJIIJIJJIIJJIIJIIIIJIIIIIIIIJIIIIIJJ;

	public IIJJIIJJIIIJIJIIJIJJIJIIJIJIIIIIJIJJJJJIIJIJIJJ JJIIJIIIIIJJJJIIIIJIIIJIJIIIJIIIIJJJIJJJJJIIIJJ;

	public int IIIIJJJIIIIJJJIIJJJJJJIIIIIJJJIJJIIJIIJIIJJJIJI;

	public string IIIIJJIJIJIIIJJIJIJJIJJIIIJIJJJIIJIJIIIJIJIJJII;

	[HideInInspector]
	[SerializeField]
	private GameObject selectOnTab;

	public Color JIJJIJIJJIJJJJJIJJJIIJJJJJIIJIIJJIJJIIIJJIJIIJI;

	public Color JIIIIJIJIJJIJIIJJJIIIJJIJJJJIJIJIJIIJIIIIJJJJJI;

	public Color IJIJIJIIJJJIIJJIJJIJIJJIJIIIIJIIIJJJIJJJIIIIJII;

	public List<EventDelegate> JJIIJJJIJIIJJIIIJJIIJJJIJIJJJIJIJIJJIIJJIIJIIJI;

	public List<EventDelegate> JIIJJJJJJJIIJJIJJJIIJJJIIIJJJIIJJJJJIIJJJIJJJII;

	public IJJJIIIIJJIJIIJIIIJJIJIJJJJJJIJIIIIJIJJJIJJIIJJ JIIIJIJJJIJIIIIJIIIJIIIIIJJIIJJJJIJJJJJIIJIIIJJ;

	[HideInInspector]
	[SerializeField]
	protected string mValue;

	[NonSerialized]
	protected string JIJJJJJIIJJJJIJJJIJIIIJIIJIJJJJJIJIIJIIIIJIIJJI;

	[NonSerialized]
	protected Color JIIJIIIJJJJIIJIJJIJIJIIIIIIJJIJIIJIIJJJIIIJJJJJ;

	[NonSerialized]
	protected float IIIJJJIIIJIJJIIJIIIIJJJJIJJIIJJIIIIIJJIJJIJIIII;

	[NonSerialized]
	protected bool JIIIJJJIIIJIIIJJJJIIJIJJIJIJJIJJIJIJJJIJJIIIJIJ;

	[NonSerialized]
	protected IIJJJJJIIIJIJJJJIIIIIIJJJJJIIIIJJJJJIJIJIJIJIJJ.JJJJIJIIIIJIIIIJJIIJJIJJJIJJJJJJIIIJIIIJIIJJJJI JIIIJIIIIIJJJJJJIJIJJIJIJIIJJIIJJJIJIJIJJJJJIJJ;

	[NonSerialized]
	protected bool JIIIIIIJJIJJIJJIJIJJJJJJJIJIIIIIIIIJIIJIJIIJIII;

	protected static int JIJIJIIIJIIIJJJJJIIIJJIIIIIIJIIJIIIJIIIIJJIIIJJ;

	protected static string IIJJJIIJJIIJIJJIIJIJIIJIJJJJJIJIIIIIIIJIIJIIIII;

	protected static TouchScreenKeyboard IIIIIJIJIJJJJIJIJIJIIJIIIJIIJIJIJJIIJIJIIJIJJJI;

	private static bool JIIIIJJJIJJJIJIJJJJIIIIJIJJJJJJIIJIJIIIJJJJIJJI;

	[NonSerialized]
	protected int IJJJJIJJJIJJIIIIIIJIIJJIJIIIJJIIIIIJJIJJIJIIIIJ;

	[NonSerialized]
	protected int IIIJIIIJJJIJJJJJJIIIJJIJJIIIJIJIJJJIIJIJIIIJJJJ;

	[NonSerialized]
	protected UITexture IIIIJIJJIIIJIJJIIIJIJJJJIIIJJJIJIJIJIJIJJJJIIII;

	[NonSerialized]
	protected UITexture IIIIJJIIJJIIJIIJIIIIIIJIJJJJJJIIJIIJJIJIJIIIJJJ;

	[NonSerialized]
	protected Texture2D JJIJJJJIJJIIJJIJIJJJJIIJJIIJIIIJIIJJIJIIJIJJIII;

	[NonSerialized]
	protected float IIJIIIJIIIJJIIJIIJJJIIIIIIIIIJJIJJIIJJJJJIIJIII;

	[NonSerialized]
	protected float JIIIJJIIJJIIIIJJJJJJIJIIJIJJJJIJJIJJJIJJJIJIJJI;

	[NonSerialized]
	protected string JJJJIIIIJJJIIIIIJJJIIJIIJIIJJJJIJJIIJJIJJIIIJIJ;

	[NonSerialized]
	protected int IJJJJIJJIJJIIIIJJJIJJIJIIIIJJJJIIJJJIJJJIIIIJII;

	[NonSerialized]
	protected int JJJIJJIJJIIIIIIIIJJIIJJJJIIJIJIJJJIIJIJIIIIIJJI;

	[NonSerialized]
	protected bool IIJJIJIJJIJJIJIJIJJJIIIJJJIJJIIIIJJJJIJIJIIJIJI;

	[NonSerialized]
	private UICamera IIIJJJIIJIIJIJJIJIJIIJJIIJIIJIJIJIIIJIJIJJIIJII;

	[NonSerialized]
	private bool JIJJJIJJIIJIJJIIJIIIIJIIJIIIIIIJJIIJIIIJJJJJJIJ;

	private static int JJJJIJIIJIIIJIIJIIIIIIJJIIIJIJIIIIJIJJIIIJJJIII;

	[NonSerialized]
	public Action JJJIJIJJIJIIIIIJJJJIIJIIJIJIJIJJIIJIJIJIJIJJIII;

	[NonSerialized]
	public Action IJIIIIIIIJJJJIJJIIIIIIJIJIJIIJIJJJIJJIIIIIJJJJI;

	public string IIJJJJJJIJJIIJJIJJIIJIJIJIIJJJIIIIJIJJJIJIIJIIJ
	{
		get
		{
			return IIIIJIIIJJIIIJJJIIJIJJIIJIJIIJJJIJJJJIIIIIJIJJJ();
		}
		set
		{
			JIIIJJJIIJJIJJIJIJJJJIJJIJIJIIIIJJJIIJJIJJIIJJI(value);
		}
	}

	public Color IJJJJIIJIIIJIIJIJJJIIIJIIIJJJIIIJJIJJIJJJJJJJII
	{
		get
		{
			return IJIJJJIIIJIIJJJJJJJJIJJJIJIJJJIJJIJIIIIJJJJJIJI();
		}
		set
		{
			JIIJIIJJJJJIIIIIIJJJJIIIJIIJIJIJIJIIIJJJJJIIJJJ(value);
		}
	}

	public bool IIIIJIIIIIIJJIJIIJIIIIIJJJIJJJIIIIIJJIIJJJIJIJI => JJJJJJJJIIIJIJIIIIIJIIJJJJJIIJJJJIIIJJIJIJIIJIJ();

	[Obsolete]
	public string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI
	{
		get
		{
			return JIIJJJIJIJJJJJJJJJIIIJIIIJJJIIIIIJJIIIIJJJIIJIJ();
		}
		set
		{
			JJIJJIJIIIIJIIJJJJIIJJJJIIIJJIJIIJJIJJIJJIJJJJJ(value);
		}
	}

	public string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI
	{
		get
		{
			return JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII();
		}
		set
		{
			JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(value);
		}
	}

	[Obsolete]
	public bool IJIJJJJIJJJJIIJJIJJIIJIIIIIJJIJIIJIIIIJJJJIIIIJ
	{
		get
		{
			return JJIJIJJIJJJIJIJIIIJJJJIJJJIJIIJIIJIJJIIJJIJIJJJ();
		}
		set
		{
			IIJIIJJJIIIIIJIIJIJIJIIJJJIIIIJIIIIJIIJJIIIJIJI(value);
		}
	}

	public bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ
	{
		get
		{
			return JIIJIIJJJIJJIJIIJJIJJIJJJIIIIJIJIJIIIJJIJJJJIII();
		}
		set
		{
			IIJJJIIIIIIJIJJIIIJJIIJJIIIIIJJIJIJIIJIIIJJIJJI(value);
		}
	}

	public int JJJJJJIJJIJJJJJJIJJIJJIJJJJJIJJIIJJIJIIIIJIIIJI
	{
		get
		{
			return JJJJIJIJJIIIJJJIIJJJIJIJIIJIIJJIIJIJJIIJJIIJIIJ();
		}
		set
		{
			IJJIIJJIJJIIJJJIIIJJIIJJJIIJJIJIIJJIIIJIIIJIJJJ(value);
		}
	}

	public int JIIJJIJIJJJJIJJJJIJJIJIJIIIIIJJIJJJJIJIJIIJJIJI
	{
		get
		{
			return IIJIJIJJJJIIJJIJJIIIIIIJJIJJIIJJJIIJIIIIJIJIIJJ();
		}
		set
		{
			IIIJIIIJJJIJJJJIJIIIJIIIJIIIIJIIIIIIJIIIJIJIJII(value);
		}
	}

	public int JIJIIIJJIJJIIJJIJJJIJIJJJJIIJJJJIJJIJJIIJJIJJII
	{
		get
		{
			return IIJIIJJJJIIJIIIIJIJJJJIIJJJIJIIJJIIIJIJJIJJIIII();
		}
		set
		{
			JIJJIIJJIJJIIIJIIJIJJIIIIJJIJIJJJIIIJJJIIJIIJII(value);
		}
	}

	public UITexture JIIIJIIJJIIIJIIIJJIJJIIIIIJIJIIIJJJJJJJIIIIIIJJ => JIIIIIJIJIIIJIJJIIIIIIIJIIIJIIIIJIIIIJIIJIJIJJI();

	public bool JJIJIJJIJJJIJIJIIIJJJJIJJJIJIIJIIJIJJIIJJIJIJJJ()
	{
		return false;
	}

	protected virtual void JIJIJJIJIJIIIIIJIJJJIIIJIIJJJJJIIIIIJJJIIIIIJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	public string JIJIJIJIIIIIIJJIIJIIIIJJJJIJJJIIIJIJIIIIJIIIIJI(string JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
		return null;
	}
	public void JIIIIJJIIIJIJJIIIIIIJJIJJJJIIIJIIIIJIJJIIIJJIJI(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public string IIIIJIIIJJIIIJJJIIJIJJIIJIJIIJJJIJJJJIIIIIJIJJJ()
	{
		return null;
	}

	protected void IJIJIIJJJJIJJIIJIIJJJIIIIJIIJJIJIJJIIIIIJIIJIIJ(string JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
	}

	protected void JJJJJJJIIIJJIIJIIIJIIJJIIJJIIJJIIIIJIJJIJIJIIII()
	{
	}

	protected int IJIJIJJJJIIJJJJJJIIJJJJJJIJIIIIIIJJJIJIJJIJJIJI()
	{
		return 0;
	}

	public void JIJJIIJJIJJIIIJIIJIJJIIIIJJIJIJJJIIIJJJIIJIIJII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIIIIJIJJJIJJJIIJIIIJIJJJJIJJJIJIJJIJIIJIIIIJII()
	{
	}

	private void OnEnable()
	{
	}

	protected virtual void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	public void JIIIJJJIIJJIJJIJIJJJJIJJIJIJIIIIJJJIIJJIJJIIJJI(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public Color IJIJJJIIIJIIJJJJJJJJIJJJIJIJJJIJJIJIIIIJJJJJIJI()
	{
		return default;
	}

	protected string IIJJIJJIIJIIIJJJJIJIIIJJIJJIJIJJJJIJJIJJJIIIIJI()
	{
		return null;
	}
	public int IIJJJIJIJIIJIIIIJJIIIJIIJIJJIJIJIJJJJIIJIJIJIIJ()
	{
		return 0;
	}

	protected virtual void IJIIJIIIIJJIIJJJJIJJIIIJIIIJIJIIIIIJIJJJJIIJJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	protected virtual void JIJJIJJIIJJIJJIJIJJIIJIJJJJJIIJIIIJJIIIJJIJIJII()
	{
	}

	protected string JIJIJJIJIIIIIIJIIIJJJIJIIIJIJIIIJIJJIIJIIIJIIJI()
	{
		return null;
	}

	public void JIIIIJIIIJJIJJIJJIIJIIJIJIIJJJJJJJIIIJJIJJJJIII()
	{
	}

	public int IIJIJIJJJJIIJJIJJIIIIIIJJIJJIIJJJIIJIIIIJIJIIJJ()
	{
		return 0;
	}

	protected virtual void JJIJJJIJJIJIJIIJJIJIIIIJJJJIIIJJJIJJJJIJJJJIJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	public int JJJJIJIJJIIIJJJIIJJJIJIJIIJIIJJIIJIJJIIJJIIJIIJ()
	{
		return 0;
	}

	public void IIJJIJJJJIJIJJIIJJIIIJJJJIIIJIIIJJIJIIIIJJIIJJJ()
	{
	}

	protected virtual void Update()
	{
	}

	public void JIIJIIJJJJJIIIIIIJJJJIIIJIIJIJIJIJIIIJJJJJIIJJJ(Color JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected void IJJIJIJJJIIJJJIJJJIJJJJJIIIJJJIJJIIIJIJJIJJIIJJ()
	{
	}

	public UITexture JIIIIIJIJIIIJIJJIIIIIIIJIIIJIIIIJIIIIJIIJIJIJJI()
	{
		return null;
	}

	protected void JIJJJJJIIIJJIJIJJIJJJJIJIJIJIJIIIJJJIIIJIIJJIJI()
	{
	}

	protected virtual void IIJJJIIIJIJIJJJJIIJIJIJIJJJJJIJIJJJJJJJIJJIJJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}
	public bool JIJIJJJJIJJIIIJJIIJIIJJJJJJIIIJJJIJIIJIIIIJIIJJ()
	{
		return false;
	}

	public void JJIJJIJIIIIJIIJJJJIIJJJJIIIJJIJIIJJIJJIJJIJJJJJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void JIJJJIJIJIJIJIIIJJJIJIIIJJIJIIJJIJIJIIIIIIJJJII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIJIIIJJJIJJJJIJIIIJIIIJIIIIJIIIIIIJIIIJIJIJII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public int IIJIIJJJJIIJIIIIJIJJJJIIJJJIJIIJJIIIJIJJIJJIIII()
	{
		return 0;
	}

	public bool JJJJJJJJIIIJIJIIIIIJIIJJJJJIIJJJJIIIJJIJIJIIJIJ()
	{
		return false;
	}

	protected char JIJIJIJIIIIIIJJIIJIIIIJJJJIJJJIIIJIJIIIIJIIIIJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, int IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, char JJIJIIJJIIJJIIIIIJJIJIIJJJJJJIJIJIIIJJJJJIIJIJI)
	{
		return '\0';
	}

	private void IJIJJJIIJJJJIIJJIJIJIIJJIIJJJJJIIJJJIIJIIIJIJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, KeyCode IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
	}

	public void IIJJJIIIIIIJIJJIIIJJIIJJIIIIIJJIJIJIIJIIIJJIJJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void OnDisable()
	{
	}

	protected void IIIJJIJJJJIJIIJIIIIIIIIIJJIIJJIJJJIIIJIJJJJIJIJ()
	{
	}

	protected void IIJJIJIJJJJIIJIJJIIIJJIJIIIJIJJJIIJIIIIJIJIIJII()
	{
	}

	public void IIIJJJIIJIJIIJIJIIJJIJJIIJIIJIIJJJIIJIIJIJIIJIJ()
	{
	}

	public string JIIJJJIJIJJJJJJJJJIIIJIIIJJJIIIIIJJIIIIJJJIIJIJ()
	{
		return null;
	}

	public void JJIJJJIJIJIIIIIIIJJJJIJJJIIIJJIIIIIJJJJJJJIJIJI(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI, bool IIIIIIIIIJJJIIJJJIJJJIJJIIJJJJIJIJIIJIJIJIJJJIJ = true)
	{
	}

	public void IIJIIJJJIIIIIJIIJIJIJIIJJJIIIIJIIIIJIIJJIIIJIJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public UITexture JJIIJJIJIIJIJIIIJIJJJIIIJJJJJIJJIJIIJIJIIJIIJJI()
	{
		return null;
	}

	protected virtual void IJIIJIJIIIIJJIJIJJJIJJIJJIJJJJJJIIIJIJIJJIIIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public void JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected void IJIIJIIJIIJJJJIIJJIJJIJIJJIJJIIJIIIJIIJJIJIJJJI()
	{
	}

	public void IIJIIJJJIIIJJJIJJIJJIJIJJJIIJIJJJIJIIIIJJJIIIJJ()
	{
	}

	public string JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII()
	{
		return null;
	}

	public void IJJIJJJJJJIIIIIIJIJIIIIIJIJJJIJJJIIIJIJIIIJJJIJ()
	{
	}

	protected virtual void JJIJJJJJJJJIJJIJIJIIIIIIIIIIJJJIIJJIJJJJJIIJIIJ()
	{
	}

	public bool JIIJIIJJJIJJIJIIJJIJJIJJJIIIIJIJIJIIIJJIJJJJIII()
	{
		return false;
	}

	public void IJJIIJJIJJIIJJJIIIJJIIJJJIIJJIJIIJJIIIJIIIJIJJJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void Start()
	{
	}

	protected string IIIIIJJIIIIIIIIIJIJIIIJJIIIJIJIIIIIJIIJJIIJJIJJ()
	{
		return null;
	}
}
