using UnityEngine;

public class UIInfoLabelManager : MonoBehaviour
{
	public bool JJIJJIJIIJJIIIJIJIJJIIIJIJIIIJJIIJJJJJIIJIIJIII;

	public float IIJIIJIJJIJIJIJIIIIJIIIJIIIJIJJIJIIIJJIIJIIIJIJ;

	private PlayerInput JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII;

	private float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

	private Ray JJIIIJIJIJJIJJJIJIJJJIJJJJJJJIJJJJIIJIIJIJJJJII;

	private RaycastHit IIJIJIJJJIJIJJIJIJIIJJIJIJIJJJIJIJJJJJJJJJJJIJJ;

	private Vector3 JIIIJIIJJIIJJIJJJJIJIJIIIJJJIJJIIJJIIJIJIJJIIIJ;

	public LayerMask IIJJJIJJJIJIJIJJIIIIIJJJIIIJJIIJJIJJIJJJIIIIJII;

	private static UIInfoLabelManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void IJJIIIIJJIIIIIJJIIJIIIJJIJIIIJJIJJJJIIIIJIIIIJJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void JJJJIJIJIIJJJJIIIIJJJIIIIJJIIIJJIJJIIJIIIIIIJIJ()
	{
	}

	public static void IIJIIIJJJJIJIJJIIJJJIIJIIJIJJJIJIJIJIIJIJJIJJII(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void JIJJJJIIIJIIIIJIJJJJIIJJJIIJJIIJJJIIIIIIIJIIIJI()
	{
	}

	private void IJIJIJIIJJIIIJJIJIIIJIJJIIJJJIIJJJJJIJJIIIJJIIJ()
	{
	}

	public static void JJJJJIJJJIJIIJIIJJJJIIIJIJIJJIJIIIIIIIJJIJIJIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void IJIJIJIIIIJIIIJJIJIIJJJJIJJIJJJJIIIJJJIJIJIIJIJ()
	{
	}

	private void JJJIIIIIIIJJJIIJIIIIJJJJIIIIIIIIJJJJJJJIIIJIIJJ()
	{
	}

	private void JIJJJJIIIIJJJIIIJJIJIJJJIJIJJJIIIIIIJIIIJJJJIIJ()
	{
	}

	public static void IIJIIIJJIIJIJJJIJIIIJJJJJIJJIIIIJIIIIJJJIIIJIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public static void JIIIJJJJJJIJIIIJIIIIJJIIIIIJJIIJIJJIIIIJIJJIIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public static void JIIIJJIIJIIIIIIJIIJJIJIJJJIIJJIIIIJJJJJIIIJJIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void Update()
	{
	}

	private void IJIJJJJJIIJIIJIJIIIJJJIIIJIJIJIJJIJIJJJJJIJJJJJ()
	{
	}

	private void JIIIJIIJJJJIJIJJJIIIIIJIJJIIIIJJJJJJJJIJIIIIJJI()
	{
	}

	public static void JJJIIIJJIJIIIIJJJIIJIJIIIIJIJIIIJIJJJIIIJJIIIJJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}
}
