using System.Collections.Generic;
using UnityEngine;

public class UIInviteFriendManager : MonoBehaviour
{
	private static Dictionary<int, float> IJJJJJIJIJJJJIJJJIIIJIIJJIJJJIJJIIIJJIJIJJIIJII;

	public UIGrid IIIIIIJIJJJIIIIIIIIIJIJIIIIIJIIIJIJJJJIIJJJJIJI;

	public UIInviteFriendElement IJIJJJIIIIJJJIJIIJIIIIIIIJJJIJIIIIIJIJIJJJJIIIJ;

	public GameObject IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ;

	private List<UIInviteFriendElement> JIIJIJJJJJJJIJIIIJJJJJJJJIIJIJIIJIIIJIIIJIIJIJJ;

	private List<UIInviteFriendElement> JIIJJJJIIIJIJIIJJIIJIJIJIIIJJJIJJIJIJIJJJIJIIJI;

	public void IJJJIJIIIJIIIJJIJIJIIJIIJJIIJJIJIJIJIJIIJJJIIJI(GameObject go)
	{
	}

	private void JIIIJIJIJIJIIJJIJIIJJJJJIJIIIIIJJIJJIJJIIJJIIJJ()
	{
	}

	private void JIJIJJJJIJIIIIIJIJIIJIIIJIIJJJJIJIIIIIJIJIJIJJJ()
	{
	}

	public void JJJIJJIJJJJIIIJIIJJIJJJIIJIIJIJIIJJJJIJJIJIJIJI()
	{
	}

	private void IJJJIIJJJJJJIIJIIJIJIIJIJJIJJJIJJIIIIJIIJIIJIJI()
	{
	}

	public void JJIIJIJJIJIJJJJIIJIIIJIJIJIJJIJIIIIJJJIJIJIIJJJ()
	{
	}

	private void IIJJJJIJJIIIIIIIIJJJJIIIJJIIIIIJIIJIJJJIIIJIJIJ()
	{
	}

	private void JJJJJJIJJIIJJJIJIJJJIJJIIIIJJIIJIIIIJJJJJJIJIIJ()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	private UIInviteFriendElement JIJIIJIJIJJJIIJIIJIJIJIIIJJIIJJIIJIIIJIIIJIIJII()
	{
		return null;
	}

	private void Start()
	{
	}

	private UIInviteFriendElement IIIIIJIIJIIJIIIJJJJJIIIJIIJIIIIIJJIIJJJJJJJIJIJ()
	{
		return null;
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	public void JJIJIIIJJJIIJJJIIJIJIIJJIJIJIJIIJIIJJIIIJIIIIJI()
	{
	}

	private void IIJJJIJIIIIIJJJIJJJIIJJIIIJJJJJJJJJIJJJJIIIIIII()
	{
	}

	public void JIIJJIJJJIJJJJJJJIIJJJIIJIIIIJIIJIJJJIIIIJIIIIJ(GameObject go)
	{
	}

	private UIInviteFriendElement JIIIIIJJJJJJJIJIIJJJIJJJIIJJIIJJIIIJJIIIIIIIIJJ()
	{
		return null;
	}

	private UIInviteFriendElement JJJJIIJJIIIJJJIJJIIJJIJIJIJJIIJJJIIJJJJJJIIIJJJ()
	{
		return null;
	}

	private void IJIIJJIJJJIJIJJJIIJIJIIJJJJJIJIJJJJIIJIIJIJJJJI()
	{
	}

	public void SentInvite(GameObject go)
	{
	}

	private void JIJJJIJIJIIJIJIIJJJJJJIIIIJIJJJJIIIIJJIIIIIJIIJ()
	{
	}

	public void IIIJJIJJJJJJIIJJIJIIIJIIJIIIJIIIIJIIIJIJJIJIIJJ()
	{
	}

	public void Open()
	{
	}

	private void IJJJIIJJJJJIIJJJIJJJJIJJJJIJIJIIJIJJJJJIIIJJIII()
	{
	}
}
