using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class UIKeyBinding : MonoBehaviour
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JIIIIJIJJJJJJIIJIIIIIJIIJJJJIIIJJIJIIJJIIIIJIIJ
	{
		PressAndClick = 0,
		Select = 1,
		All = 2
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IJIJJJJIIIJJIIIIIIJJJJIJIJJIIJJJIIJJJIIJIJJJJJI
	{
		Any = 0,
		Shift = 1,
		Ctrl = 2,
		Alt = 3,
		None = 4
	}

	private static List<UIKeyBinding> IJIIJIJJJIIJIIIJJIJIIJIJIIJIIIJJJJIIJJJIJIIJJJI;

	public KeyCode JJIJJIIIJIIIJIIIJJJIIJJIJIIJJJJIIIIJIJJJIIJIIIJ;

	public IJIJJJJIIIJJIIIIIIJJJJIJIJJIIJJJIIJJJIIJIJJJJJI JJIIIIIIIJIJJIIIJIJJJIIIIIJJJJIJIJIJIJIJJJJIJJJ;

	public JIIIIJIJJJJJJIIJIIIIIJIIJJJJIIIJJIJIIJJIIIIJIIJ IJIIIIIJIJJJJJIIIJJIJIIIJIIIJIJIIIIIIIIIJIJIIIJ;

	[NonSerialized]
	private bool JIJJIJIIIJJJIJIIIIIIIIIJJIJJIIIJIJIIIIIJIIIJJJI;

	[NonSerialized]
	private bool JJJIIIJJJJIJJIJJJJIJJJIJIIIIJIJJIJJJJJIJIIJJIII;

	[NonSerialized]
	private bool JJJIJIJIIJJJIJJIJIIJIIIJIJJIIIIJJIIJIJIIIIJIJJJ;

	public string IIJJIIJJJJJJIIJIJIIIJJJIJIIJJIIJJJIIIJIJIJJJIIJ => IIJJIIIJJIJIJJJIIJIJJJIIJJIJJJJIIJJJIJJIJJIJJII();

	protected virtual bool JJIJJIIJJJIJJIIJIJJJJIJJIIIJIJJJIJJJIJIJJJIJIJI()
	{
		return false;
	}

	public static bool JIIIIIJJIIIIJJIJJIIJJIIIJIJIIIIIIJIIIIIIJJIJJJJ(KeyCode IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ)
	{
		return false;
	}

	protected virtual void JJJJIIJJIIJJJIIJIJJIJIIJJJIJJJJJIIIIIJJJIIIJJIJ(bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	protected virtual void OnDisable()
	{
	}

	public static bool IIJIJIIIIJJIIIIJIJJIIIJJIJIJJIIIJIJJIJIIIIJJJIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, out KeyCode IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, out IJIJJJJIIIJJIIIIIIJJJJIJIJJIIJJJIIJJJIIJIJJJJJI JJIIIIIIIJIJJIIIJIJJJIIIIIJJJJIJIJIJIJIJJJJIJJJ)
	{
		IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ = default;
		JJIIIIIIIJIJJIIIJIJJJIIIIIJJJJIJIJIJIJIJJJJIJJJ = default;
		return false;
	}

	protected virtual void IJJJJIIIIJJIIIJJIJJJJJJIJIIJJJJJJJJIJJIIJIIIJIJ()
	{
	}

	public static string IIJJIIJIIIJJIIIJJJIIIJIIIJIJJIIJIJIIIJIIIJIJJII(KeyCode JJIJJIIIJIIIJIIIJJJIIJJIJIIJJJJIIIIJIJJJIIJIIIJ, IJIJJJJIIIJJIIIIIIJJJJIJIJJIIJJJIIJJJIIJIJJJJJI JJIIIIIIIJIJJIIIJIJJJIIIIIJJJJIJIJIJIJIJJJJIJJJ)
	{
		return null;
	}

	protected virtual void OnSubmit()
	{
	}

	public static bool IIJJJIIJIIIJIIJJJJJJIJIIJIJJJIJIJIJJIIIIJJJIIJI(IJIJJJJIIIJJIIIIIIJJJJIJIJJIIJJJIIJJJIIJIJJJJJI JJIIIIIIIJIJJIIIJIJJJIIIIIJJJJIJIJIJIJIJJJJIJJJ)
	{
		return false;
	}

	public static IJIJJJJIIIJJIIIIIIJJJJIJIJJIIJJJIIJJJIIJIJJJJJI IIJIJIJIIJIJIIJIIJIJJIJIIIIJIJJIIJIJIJJJIIJIJJJ()
	{
		return IJIJJJJIIIJJIIIIIIJJJJIJIJJIIJJJIIJJJIIJIJJJJJI.Any;
	}

	protected virtual void IJIIIJJIIJIIIIIIJJIJIJIJJIJJIIIJJIJIIIJJJJJIJJI()
	{
	}
	public string IIJJJJIIJJJIIIJIJJIIJJIJJIJIJIJJIIJJIJJJIIJIIII()
	{
		return null;
	}

	protected virtual void IIIJIJJIJJIJIJIJIJIIIIJIIJJIIIJJJIJJJJIIJIIJIIJ()
	{
	}

	protected virtual void Update()
	{
	}

	public string IIJJIIIJJIJIJJJIIJIJJJIIJJIJJJJIIJJJIJJIJJIJJII()
	{
		return null;
	}

	protected virtual void IJIIIJIJJIIJJIJIJJIIJIIIJJJIIJJIIIJIJIIIIIJJJII()
	{
	}

	protected virtual void JJJIIIIIIIJJJIIJIIIIJJJJIIIIIIIIJJJJJJJIIIJIIJJ()
	{
	}

	protected virtual void JIIIJIIIJJJJJJIJIJJIJJJIJIIJJJIJJIJJJIJIIIIJIII()
	{
	}

	public override string ToString()
	{
		return null;
	}

	protected virtual void OnEnable()
	{
	}

	public static bool JJJJJJJJIIJIIIJJJJIJIIJJJJIIJIJJJIIIIIJIJJIIIJI(IJIJJJJIIIJJIIIIIIJJJJIJIJJIIJJJIIJJJIIJIJJJJJI JJIIIIIIIJIJJIIIJIJJJIIIIIJJJJIJIJIJIJIJJJJIJJJ)
	{
		return false;
	}

	protected virtual void JIIIJJIIJJJIIIJJJJIIJJIIJJIJIIJJJIJIJIJJIJJJIJJ()
	{
	}

	protected virtual void Start()
	{
	}

	public static IJIJJJJIIIJJIIIIIIJJJJIJIJJIIJJJIIJJJIIJIJJJJJI IIJJIIIIJJJIJJJJIIIJIJIJIJIIJIJJJIIIJIIIIJIJIII()
	{
		return IJIJJJJIIIJJIIIIIIJJJJIJIJJIIJJJIIJJJIIJIJJJJJI.Any;
	}

	public static bool IIIIJJIIIIIIJIJIJIIIJIIJJIIJJIJIIIJJJJJJIIIIJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, out KeyCode IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ, out IJIJJJJIIIJJIIIIIIJJJJIJIJJIIJJJIIJJJIIJIJJJJJI JJIIIIIIIJIJJIIIJIJJJIIIIIJJJJIJIJIJIJIJJJJIJJJ)
	{
		IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ = default;
		JJIIIIIIIJIJJIIIJIJJJIIIIIJJJJIJIJIJIJIJJJJIJJJ = default;
		return false;
	}

	public static IJIJJJJIIIJJIIIIIIJJJJIJIJJIIJJJIIJJJIIJIJJJJJI IIIJJJIJJIJJJJJJIIJIIJIIIJIIIIJJIJJIIIJJIIIIJJJ()
	{
		return IJIJJJJIIIJJIIIIIIJJJJIJIJJIIJJJIIJJJIIJIJJJJJI.Any;
	}

	protected virtual bool JJJJJJJJIIJIIIJJJJIJIIJJJJIIJIJJJIIIIIJIJJIIIJI()
	{
		return false;
	}
}
