using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class UILocalize : MonoBehaviour
{
	public string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ;

	public string IJJJIJJJJJIJJIIJJJIJJIJJJIJJIIIIJJJIJIIIIIIIJJI;

	private UILabel IJIJIJIIJJJJIJJJIJJIJIJIJJIJJIIJIJJIJJIJJIIIJII;

	private bool IIJJIJIJJIJJIJIJIJJJIIIJJJIJJIIIIJJJJIJIJIIJIJI;

	public string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI
	{
		set
		{
			JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(value);
		}
	}

	private void IJIJJIIIIIJIJIJIIJJIIJJJJIIIJIJIIJJJJIIIJJIIJII()
	{
	}
	public void IIIIIIJIJJIJJJJJJJJIJJIJIJJIJIIJJJIJJIIIJJIIJIJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JIIJIIJIJIJIIJIJJJJJIIJIIIIJIIIJIJJJJIJIJJJJJIJ()
	{
	}

	private void JIIJIIIIJIJJJIIIIIJJIJJJJJJIIIJIIJJIJIJIJIJIIIJ()
	{
	}
	public void JJIIJIIJJIJJJIJIJJJJIIIIJJIJJIIIIJJIJJIIJJIIJJJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJJIIJIJJJIIIJIJJIJIJJIJJIJIJJJIJJIJIJJIIJIJJIJ()
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void OnEnable()
	{
	}

	private void JIJJJIIIJJIJIJJIJJJJJIIIIJJIJJJIJJJJIJIIIJJJJII()
	{
	}

	private void IIJJJIJIIIJIIIJJJJIIIIJIJJIJIIIIJJJIIIJIIIIIJII()
	{
	}

	private void JJIJIJJIJJIJIJIJIJIIJJJJIIIIJJIJIJJIIIIIJIIIJJI()
	{
	}

	private void JIIJIIJJJJIIIJJIJIJJIJIIJJIIIIIIJIJIIJIJJIIJJJI()
	{
	}

	private void IJIJJIIJJIJIIIJIJIIJJIJIIJJJIJJIIIJJJJJIJJJIIII()
	{
	}
	public void IJJJJIJJJJJJIJIIIIIJIJJJJIJIIJJJIJJIIIIIIJIJIJJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void IIIJJJIJIIIJJIJIIJJIIIIJIIIJJJIIIIIJIIIJJIIJJII()
	{
	}

	private void Start()
	{
	}
	public void JJIIJJJJIJIJIIIJJJJIIJIIIIIIJIIJJIJIIIIIIIJIIJI(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	public void JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void IIJJIJJJIJJJJJJJJIJIIJJJJJIIIIJIIIJIIJIIJIIJJIJ()
	{
	}

	private void OnDisable()
	{
	}
}
