using UnityEngine;

public class UIMainStatus : MonoBehaviour
{
	public UILabel JJJJJIJJIIJIIJIJJIIJJIJIJIIJJJJIJIIJJJIIIJJJJJJ;

	public UISprite JJJJJIJJJJIJIJIIJJJIIJIJIIJJIJIIIJIIIIIIJIIJIJJ;

	public UISprite IIJJJIIJIIJIJJJJJIJIIIJJJJIIJJJJIJIJJIJIJJJJJII;

	public UILabel IIIIIIJIIJIJJIJJJJJIJIJJIJJIJJJIIIIJJJJIJJIIJJI;

	public UISprite IIJIIJJJIIJJIIIIJIJIJJJIJJJIIJIJIIJIIIJIIIJIJJI;

	private static UIMainStatus JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void IJJJJJIIJJJJIIIJJIJIJJJJIJIIIIJJJJIIIJIIIJIIIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IJJIJJJIIJJJJIIIIJIIJJIIJJJIIJIJJJJIIJIJIJIIIIJ, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public static void JJIIIJJJJIIIIJIJIJJJIIJJIJJIJJJJJJJIIIJIJIIJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public static void IJIJJJIIIJJIJJIIIJJIIIIIIJJJIJIJJIJIJJJJIJJIIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIJIIIJIJIIJIIJJJIIJJIIJIIJJJIJIIJIIJJJIJJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void IIJJIJIIIJJJJIJJJJIJJIIJJJJIIIJJJIIIIIJJIIIJJIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IJJIJJJIIJJJJIIIIJIIJJIIJJJIIJIJJJJIIJIJIJIIIIJ)
	{
	}

	public static void IJJJJIJJJJJIJJIIJIIIIIIJJIJJIJIJJJIJIJIJJIJIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public static void JIIJJIJJJJJIJJJIIJIJJJIIIJIIIJJIJIJIIJIIJJJIJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IJJIJJJIIJJJJIIIIJIIJJIIJJJIIJIJJJJIIJIJIJIIIIJ, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	public static void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}

	private void Start()
	{
	}

	public static void JJIIIJIJIIJJIIJIJIJIJJIJIJIIJIJIJJIJIJIJJIJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public static void IIIIIIIJJJJIJJJIJJIJJJIIJIJIJIJJIJJJIIJJJJJIJIJ()
	{
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IJJIJJJIIJJJJIIIIJIIJJIIJJJIIJIJJJJIIJIJIJIIIIJ, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, string JJJJJIIIIIJJIIJIJJIIIJIJIJIJJJJJJJIIIIIJJIIJJIJ)
	{
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IJJIJJJIIJJJJIIIIJIIJJIIJJJIIJIJJJJIIJIJIJIIIIJ)
	{
	}

	public static void IJJIIJIJJIIIJJJJJIJIIIIIJIJJJIIIIIJJJIJJIIJIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}
}
