using System.Runtime.CompilerServices;
using UnityEngine;

public class UIMapPosition : MonoBehaviour
{
	public UILabel JJJJJIJJIIJIIJIJJIIJJIJIJIIJJJJIJIIJJJIIIJJJJJJ;

	private JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IIIJJIIJIJIIJJIIJIIIJIIIJIJIIJIIJIIIJIJIJJIIIJJ;

	private static UIMapPosition JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IJJJIIIJIJIJIJIJJJJJJJJIIJJIJIJIIJJIJIJIIIIIIIJ => IJIIIIJJIJJIJJJIJJJIIIIIIJIJIIIIJIJJJIJIIIJJJJJ();
	public static JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IJJJJIIJIIJJIIJJJIJIJIJJIJIIIJJIJIIIIIIIJIIJIIJ()
	{
		return JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII.None;
	}

	public static void JJJJIIIIIJIIJJIJJJJJJIIJIJJJJJIJJIIJIJIIJIIIJII(JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}
	public static JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII JIJJJIIIIIIJIJIIIJJIJJIIJIIIIJJIIIIIJIJIIJJJJJJ()
	{
		return JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII.None;
	}
	public static JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IIIIIJJJIJJIJIIJIJJIJJIJJJJIIIIIJIIIIIJJJJJIIJI()
	{
		return JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII.None;
	}
	public static JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IJJJIJJJIJJJIJIJIJJJIIIIIJJJJIIJIIJJJIJJIIIJJII()
	{
		return JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII.None;
	}
	public static JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII JJJIIJIIIJIIIJIJJIIJJJIIJJJIIIIJJIJIIIJJJJIIIJJ()
	{
		return JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII.None;
	}
	public static JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IJJIIJIIJJJJJJJIJIIIJIIJJIJJIIJIJIJIIJJIIJIJJII()
	{
		return JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII.None;
	}

	public static void IJJJIIIJJIIJJIJJJJJIJIIIIIIIIIJJJIJJIIIIJJIJIJI(JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}
	public static JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII JIJIIIJJIJJJIIIIIIJIIIIJIIJIJIJIJJJJIJJIIJJJJJI()
	{
		return JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII.None;
	}

	public static void JJIJJJIIIIIIJJJIJJJIJIIJIJJIJJIIIIJJJJIJJJIJJII(JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	public static void JJIJJJIIIIJJIJIJJIIJJIIIJIJJJIIJIIIIJJJJJIJIIIJ(JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}
	public static JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IJJJIJIJJJJJJJJIIJJIIJJJJJJIIJIJJIIIIIIIIJIIJJI()
	{
		return JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII.None;
	}

	private void Start()
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	public static void JJIJJJIJIJIIIIIIIJJJJIJJJIIIJJIIIIIJJJJJJJIJIJI(JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	public static void IIIIIJIIIJJIIIIIJJIJJJIIIJIJJJJJJIIIIJIIJJIJIJJ(JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	public static JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IJIIIIJJIJJIJJJIJJJIIIIIIJIJIIIIJIJJJIJIIIJJJJJ()
	{
		return JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII.None;
	}

	public static void IJIJJIIJIJJJIIIJJJIIJIIJJJJJJIJJIIIIIIIJJJIJJJJ(JIJJIJJIIIJIIIJJJJIIJJIJJIJJJIIJIIJJIJIJIIJIJII IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ)
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}
}
