using System;
using System.Collections.Generic;
using UnityEngine;

public class UIMessage : MonoBehaviour
{
	public class JIIJJIIIIIIIJJIJJJJJJJIJIJIJJJJIIJIJJIIJJJJIJJJ
	{
		public string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII;

		public string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI;

		public Action<bool> IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI;

		public Action<bool, object> IJIIJJJIIIJJIJJJJIJJIJJJJIIJIIJIIJJJJJJIIJIJJIJ;

		public object IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII;
	}

	public UITexture JJIIJJJIJIJJJJIJIJJJJIIJJIJJJJJIJIJJIJJJJJJJJII;

	public UILabel IIJIJIJJJIJJJJJIIIIIIJIJIJJJIJIIIJJIJIJJIJIIIIJ;

	public UISprite IIIIIIIIJIIIJIIIJIJJJJIIIIIIIJIIIJJJIIJIJJIIJII;

	public List<JIIJJIIIIIIIJJIJJJJJJJIJIJIJJJJIIJIJJIIJJJJIJJJ> JIIIIIIJIJJIJIJJIIIJJIIIJJIIJJJJJJJJJJJIIJJJIII;

	private static UIMessage JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	public void Click()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	public static void IIJIJIJJJJIIJIIIIIJJIJJIJJJIJJJIIJIIIIJJIIIJIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, Action<bool> IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
	}

	private void IIIIIJJJIIJJIJJIJJIJIIJIIJIJJJIIJJJIIIIJJJIJIJI()
	{
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, object IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII, Action<bool, object> IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
	}

	private void JIJJJJIJJIIIJJIIJIIJJJJIJIJJIIIIIJJJIJJJIJIIIJI()
	{
	}

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	public static void IJIJIIIIJIJIIIIJIJIIJJJIJIJJJIIIIJIIIIJJJIIJJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, Action<bool> IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
	}

	public static void IJJJIJJJJIIIJIJIJIIJJIIJJJIIJJJIIJIIIIJJIIJJIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, Action<bool> IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
	}

	private void JJJJIJJJIJJIJIIJJJJJIJJIIJIIIJJIJIIJIJIJJJJJJJI()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void IJIIIJJJIIIJJIJJJIJJIIIJIIIJIIJIJIIJJIIJIJJJJJI()
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void JJJJIIIJJJIIIIIIIIIIJIJJJJIJJJJIIJIIIJJJJIJJIIJ()
	{
	}

	private void Start()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void JIIIIJIIIIJIJIJJIJIIIIJIJJIIJJJIIIIIJJJJJIIIIJI()
	{
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, Action<bool> IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
	{
	}
}
