using System;
using System.Collections.Generic;
using UnityEngine;

public class UINotification : MonoBehaviour
{
	[Serializable]
	public class JIIIJJIJJJIJIIIJIJJJIJJIJJIJJIIJIIJJIIIIIIJJJII
	{
		public int IJJJIIJIJIJJJIIIIJJIIJJIIIIIIIIIJJIJIJIIJIJIIIJ;

		public string IJJJJJIJIIIIJJJJIJIIJIJJJIIJIJJJIJJJJJJIIJIJIJI;

		public Action IJIJJIIIJJJJIIIIIJIIJJIIIIJJIJJIIIJJIIJIIJJJIII;

		public Action JJJIIJJIIIJIJJJJIIIJIIJIIIJJIIIIJJJJIJJJJIIJIIJ;
	}

	public GameObject JIIJJIJIIJJJJIJJJJJIJIJJIIIIIIJJJIIIIIJIJIIIJII;

	public UILabel IJIIJJJJIJJIJIJJJJJIJIIJIIIIIIJIJIJIIIJIJIJIIII;

	public GameObject JJJJIJJJJJIJIJJJJIIIIIIJJIIJIIIJIIIIIJJIIJJJJJI;

	public UILabel IJIIIJJIJJIIJIJIIJJIIIJIJJIJJJJJIIJIIIJIJJIIIJI;

	private List<JIIIJJIJJJIJIIIJIJJJIJJIJJIJJIIJIIJJIIIIIIJJJII> JIIIIIIIIJJIJJJIJIJIJIIIJIJJJJIIJJJIIIIIIIIJJIJ;

	private JIIIJJIJJJIJIIIJIJJJIJJIJJIJJIIJIIJJIIIIIIJJJII IJJIIIIIJJJJJIIIJIIIJIJIIIIIIJIIJIJJIIIJJIJIJIJ;

	private bool IIIJJJIIIJJIIIJJIIJIIJJJJIIIJIJIJIJIJJIJJJIIJJI;

	private bool JIJIJJIIJIIJJJIJIIIIJIJJJIIIIIJJJJIIIJJIIIJIIJI;

	private int IJIJJJJJIIIJIJJIJIIJJJJJIJJJJJIJIIIIIJJIIIJJIIJ;

	private static UINotification JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public void IJJIIIIIJJJIIJJJIIIIJJIIIIJJJJJJJJJIJJJJJJJIJJI()
	{
	}

	public void IJJJJJIIJJJJIIIJJIJIJJJJIJIIIIJJJJIIIJIIIJIIIIJ()
	{
	}

	private void IIIJIIJJIIIIIJIIJIIJIJJJJIIJIIIIJIIJIJIJJIIIJII(string IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void JJJIIJJIIIJJIIIIIJIIIIJIJIJJJJJIIJJJIIJJJJJIIJI(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	private void JJJIJJJJJIIJIJJJIJIIIIJJIJJJIJIIJJIIJIIJJJJIIJI()
	{
	}

	public void OnClickPositive()
	{
	}

	public static void JJIJIIJIJJIIIIJJIJJIIJJJIJIIIIJJJIJJJIIJIIJIJJI()
	{
	}

	public void JIJIIIIIJIIJJJJIIIIJIIJJIJIIIIJJJIJJIIIIIIJIIJI()
	{
	}

	private void IJIIIJIIJJJJIIIIJJJIIIIJJJIJIJIIJJJIJIJIIIIIIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public static int JJIJJJJIIIJJJJIIJIIIJIJIIIJIJIJJJJJJIJIJIJIJIJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, Action JJIIIIIJIJJIIIJIJIIIIIIJJIJJJIJJIJIJIIIJJJIIIJJ, Action IIIJIJJIJIJIIJJJJIJIJJIJJIJJJIIJIJIJIIJIJIIJJJJ)
	{
		return 0;
	}

	public void Show()
	{
	}

	public static int JIIJJJIIIJJJJJIIIIJIIIJIJJIJIJIIJJIIJJIIJIIIJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, Action JJIIIIIJIJJIIIJIJIIIIIIJJIJJJIJJIJIJIIIJJJIIIJJ, Action IIIJIJJIJIJIIJJJJIJIJJIJJIJJJIIJIJIJIIJIJIIJJJJ)
	{
		return 0;
	}

	public static void IIIJIJJJIJIJIJJIIJIIJJIIIIJJJIJIIIJIJIJIJJJIIIJ()
	{
	}

	public static void JIJIIIJJIJIJJJIIIIJIIIJIIJJJIJJIJIJIJIJIIIJJIJI(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	public void IJIJIIIJIIIJJJIIIIIIJIIJJJJJJJJIJJJJJJJIIJIIJII()
	{
	}

	private void IJJJIIJIIJJIJIIJIIJJJIIJIJJJJIJJJIJIIJIIJJJIIJI(string IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void IIJJIIIIIJIIIJIJJIJIIIJIJIIJJJJIJJIIJIJIJJIJJJJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public static int JIIJJIJJJJJIJJJIIJIJJJIIIJIIIJJIJIJIIJIIJJJIJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, Action JJIIIIIJIJJIIIJIJIIIIIIJJIJJJIJJIJIJIIIJJJIIIJJ, Action IIIJIJJIJIJIIJJJJIJIJJIJJIJJJIIJIJIJIIJIJIIJJJJ)
	{
		return 0;
	}

	private void IJIIIIJJJJIIJIIIIIIJIIIIJIIIIJIJJJIIIIJJJJIIJIJ(string IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void OnDisable()
	{
	}

	public void JIIJIIJJIIIIJIIIJJJJJIJJIIIIJIJJIJJJJIJIIIJIJIJ()
	{
	}

	private void Start()
	{
	}

	public void IIIIJIIJIIJIJJIIIJIIIIIJJIIIIIJIJJJIJIJIJIIJJJJ()
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void IIJIJIIIIIJJIIIIIJJIJIIIJIJIJIIIJIJJIIIJJJJIIJJ()
	{
	}

	public void IJIJIJJIJIIIIJJJJJJJJIIIJIJIJJJIIIJJIJJJJIIJIJJ()
	{
	}

	public void OnClickNegative()
	{
	}

	private void JJIJJJIIIJJIIJIJIIJIIJJJIIJIIJIIJJIJIJJIIJIIIIJ(bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI)
	{
	}

	public static int JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, Action JJIIIIIJIJJIIIJIJIIIIIIJJIJJJIJJIJIJIIIJJJIIIJJ, Action IIIJIJJIJIJIIJJJJIJIJJIJJIJJJIIJIJIJIIJIJIIJJJJ)
	{
		return 0;
	}

	private void IIJJJJJIIJJJJJJJJJIIIIJIIJJJIIIIIJIIIJIIJIJJIJJ()
	{
	}

	private void OnEnable()
	{
	}
}
