using UnityEngine;

[ExecuteInEditMode]
public class UIOrthoCamera : MonoBehaviour
{
	private Camera IIIJJJIIJIIJIJJIJIJIIJJIIJIIJIJIJIIIJIJIJJIIJII;

	private Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	private void JJJJIJIJIIJJJJIIIIJJJIIIIJJIIIJJIJJIIJIIIIIIJIJ()
	{
	}

	private void IJIJIJIIJJIIIJJIJIIIJIJJIIJJJIIJJJJJIJJIIIJJIIJ()
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	private void IIJJIJIJJJJJIJJIIJIJIJJIIJIJIIJJIIIJJIIIJIIIJJI()
	{
	}

	private void Update()
	{
	}

	private void JIIIJIIIJJJIIIIIJIIIIJJIIJIIJIJIIJJJJIIIJIIJJJI()
	{
	}

	private void JIJJJIIIIIJIJJIIJIJIIIIJIJIIJIIIIJJJIIJJJIJJJIJ()
	{
	}

	private void IJIJIJIIIIJIIIJJIJIIJJJJIJJIJJJJIIIJJJIJIJIIJIJ()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void Start()
	{
	}

	private void JIIJIJJIIJJJJJIJJIJJIJJIJIJJJJIIJIJIJIJJJIIIJIJ()
	{
	}

	private void JJIIJIJIIJJIIJJIIJJJIJJIIJJJJJJJJJJJJIIIIJIIJII()
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	private void JIJJIJIJIIJJJJJIIJJJIJIIJJIJIJJIJJJIIJJIIIJIIIJ()
	{
	}

	private void IJIJJJJJIIJIIJIJIIIJJJIIIJIJIJIJJIJIJJJJJIJJJJJ()
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}
}
