using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class UIOthers : MonoBehaviour
{
	private static Action JJIIJJJJIJIIJIIJJJIJJJIJJIJIJIJJIIJJIIIIIJIJIJJ__BackingField;

	public UICamera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ;

	public UIGrid JIIJIIJIIJJIJJJJJIIJIJJIIJJIJIIJIIIIIJJIIJJIIIJ;

	public static event Action JJIIJJJJIJIIJIIJJJIJJJIJJIJIJIJJIIJJIIIIIJIJIJJ
	{
		add
		{
			JIJIIJJIJJIIJJJJIIIIIJIJJJIIIIIJIJJJIJJJIIIIIJJ(value);
		}
		remove
		{
			JIJIIIIIIIJIJIJJIJJIIIIJJJJJJJIJJJIIIJIIJIIJJIJ(value);
		}
	}

	private void JIIIIJJJIIIIIIJIIIJJIIIJIIIJIJJIIJJIJJJJIJJJIJI()
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void Start()
	{
	}

	public static void JIJIIJJIJJIIJJJJIIIIIJIJJJIIIIIJIJJJIJJJIIIIIJJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JIJIIJJIIIIIIIJJIJIJIJJJIJJIJIIJJIJJJIJIIIJIIJJ()
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void IJIIIIJJJJIIJIIIIIIJIIIIJIIIIJIJJJIIIIJJJJIIJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public void LeaveRoom()
	{
	}
	public static void IIJJIJIJIJJJJIJJIJJJIJIIJIIJJJJIIJJJJIIJJIIIJIJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}
	public static void JIJJJJIIIIJIJIJJJIIIIIIIIJJJJIJIJJIJJJIJJJJIJJJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void JIJIIIIIIIJIJIJJIJJIIIIJJJJJJJIJJJIIIJIIJIIJJIJ(Action JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void OnLeftRoom()
	{
	}

	private void IJJJIIJJIIJIJIJIIJIJIIJJJJJIJJJIJIJJIJJJIIJJJJJ()
	{
	}

	private void JIIJIJIIIJIIJIIJJJIIIJJIJJIIIIIIJIJIIJIIJIIIIIJ()
	{
	}

	private void IJJIJIJIIJIIIJIJIJIIIIIJJIIJIIJJIJIJIIIJIIIIIJJ()
	{
	}

	private void JIJJIJJIIIJJIIJJIJJIJIJIIIJIJIJJIJJIIJJIIJIIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IIIJIIJJIIIIIJIIJIIJIJJJJIIJIIIIJIIJIJIJJIIIJII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IJIJJJIIJIIJIJJIJIJIIIJIJIJJIIIIIIJJIJIJIJIJIJJ()
	{
	}

	private void OnEnable()
	{
	}

	private void OnDisable()
	{
	}
}
