using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class UIPanel : UIRect
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IIIIIIIJJJJJIJIIIIIIIJJIIIIJIIIJJJIJJIJJJIIJJII
	{
		Automatic = 0,
		StartAt = 1,
		Explicit = 2
	}

	public delegate void JJJIIJIJIIIIIIIJIIIIIJJIIIJIIJJIJIJJIIIIJJIIJJI();

	public delegate void IIJJJIJIJJJJIIJIIIJIIIJIIJJIJJIJJJJJIIJIJIJIIII(UIPanel JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ);

	public delegate Material IIJIIJJIIJJIIIJJJIIIIJJIIJJIJIJJIIJIIJJJJIIJJIJ(UIWidget JJIJJJIIIIIIIJIIIIIJJIIJIJIIIJJJJIJIJJJIJJIJIJI, Material JJJIJJIJIIIJJJIIIJJIIJIIIIIIJIJIIIJJJIJJIIJIJJJ);

	public static List<UIPanel> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ;

	public JJJIIJIJIIIIIIIJIIIIIJJIIIJIIJJIJIJJIIIIJJIIJJI IIJJJJJIJIIJIJIJJJJIJIIIJIJJIJIJIIIIJIIIJJJIJJJ;

	public bool JJJJJJJJJIIIIIJIJIJJIJIJIJIIJJJJIIIJJIIIIJJIJII;

	public bool JJIIJIIJIJJIJIIJIIIJIIJIIJJIJIJIIJJIIJJIJIIIIJJ;

	public bool JJJIJIIJJIIIIIIJJJIJIJJJJJIIJJIJJIIJIIIIJIJIIJJ;

	public UIDrawCall.IJIIIJIIIIIJJIJJJJJIIJIIJIJIJIIJIJIIJIIIIJJJJJJ IIIJIIIJIIIIJJJIJIIIIIJJJJIJIJJJIIJIIIIJJIJIJJI;

	public int JJIJJIJJJIJIJJJJIJIIIJJIJIJIIJIJJJIIIJJJJIIIIII;

	public bool JJIJJIIIJJJJJJIJIJJJJIIIJJIJIIIJJIIJJIIJIIJJIJI;

	public bool JIIIIIJIIIJIIIJIJIIJJJIIJJIJIJIIJIJJIIJJJJIJIJI;

	public bool JJIJJJJIJJIIJIJJJJIIJIJJJJJIJJJIIJJIJIJJJJJIIII;

	public bool IIIJJJIJJJJIIIJJJJIIIIJJIIIJIIIIJIJJIIIIJJIJIJJ;

	public IIIIIIIJJJJJIJIIIIIIIJJIIIIJIIIJJJIJJIJJJIIJJII JJJJJIIJJJIIIIJIIJIIIIJIIJIIIIIJIIJIIIIIJIIIJJI;

	public int JIIJIIJJJIIIJJJJIIJJJJJJIJJJIJIIIIIJIJIJJJIJIII;

	[NonSerialized]
	public List<UIWidget> JJIIJIJJIJIIJJIJJJIIIIJJIIJJJJIJIJJIIJIJIJJJIJI;

	[NonSerialized]
	public List<UIDrawCall> JJIIJJJIIJJJIIJJJJIJJIIIJJJIIIIIIJIJIJJJJIJJIII;

	[NonSerialized]
	public Matrix4x4 JJJJJIIIJIIIIJJIIJJJIJIIJIJIJIIJIIJIJJIIIIIIJJJ;

	[NonSerialized]
	public Vector4 IIIIJJJJJIIIJIIJIIJJIJJJJIIJIIIJJIIJIJIJIJJJJII;

	public IIJJJIJIJJJJIIJIIIJIIIJIIJJIJJIJJJJJIIJIJIJIIII IJJIIJJJJIIIJIJJJIJIIIIIIJJJJJIIJJJJIJIIJIIJIIJ;

	public IIJIIJJIIJJIIIJJJIIIIJJIIJJIJIJJIIJIIJJJJIIJJIJ IIJJIIJIIIJJIIIIJIIJJIIJJIIIJJIJJJIIJJJIJIIIIIJ;

	public UIDrawCall.IJIIJIJJJIJJIIIIIIJIJJIIIJJIIIIJIIIIIIIIJJJJJJI JJJIJIJIIIJJIJIIJIIIIJIIJJIJIIJJIJJIJIIIJJIJJJI;

	[HideInInspector]
	[SerializeField]
	private Texture2D mClipTexture;

	[HideInInspector]
	[SerializeField]
	private float mAlpha;

	[HideInInspector]
	[SerializeField]
	private UIDrawCall.IIJIJJIIIJJJIJJJIJJIJJIIIJJJIJIJJIJJJJIJJJIIJIJ mClipping;

	[HideInInspector]
	[SerializeField]
	private Vector4 mClipRange;

	[HideInInspector]
	[SerializeField]
	private Vector2 mClipSoftness;

	[HideInInspector]
	[SerializeField]
	private int mDepth;

	[HideInInspector]
	[SerializeField]
	private int mSortingOrder;

	[HideInInspector]
	[SerializeField]
	private string mSortingLayerName;

	private bool JJJJIJIIIJJJJIIIIJJJJJIJIIJIIIJIJIJIIIJIIIJIIIJ;

	private bool JJJIIIIIJIIIIIIIJJJIJIJIJIIJJIIIJIJJJIJIJIJIIJJ;

	[SerializeField]
	private Vector2 mClipOffset;

	private int JIIIJIIJIJIJIIIJIIJIJJJJJJIJJIJIJIIJIJJJJIIIIJI;

	private int JIIJIIIJJIIJIJJIIIJIIIJIIJJIJIIIIJIIJIIIIIJIJII;

	private int JJJIJJJJJJJJIJJJJJJIIJJJIJJIJJJJIIJJJJJJJJIIIJI;

	private static float[] JIIIJIJIIJJJIIIIIIIIIJJJJJJJIJJIJIJIIIIJIIIIIIJ;

	private Vector2 JJJIJIJJJIIJJJIJJJIIJIJIIIJJIIIJIIIJIJIJJIJIIII;

	private Vector2 IIIIJJJIJIIJJIJIIJJJJJJJJIJJIJIIIIIIIJJJIJJJJJI;

	private bool JIIIIJIIJIJIJJIIJIIJIJIIJIJJIIIIIIIJIIJJIIIJIIJ;

	private bool IIJIJJJIIIJJJJJIJJIJIIJJJJJIJJJJIIJJIIJIJIIIIJI;

	public bool JJIIJIIJJJIIJJIJIJJJIJIJIJIJIJIIJIJIJIJJJJJJIJI;

	private UIPanel IIIJIIJIIIIIJJJIJJJJIJJJJJJJIIIJJJJJJJIJIJJJJJI;

	private static Vector3[] IIJIJJJJIJIIJJIIJJJIIJIJJJIIIJJIJJIJJJIJIIIJIJJ;

	private static int IIIJJIIJIIJIJIJIJJIIJJJIIIIIIIJIJIJIJJIJIIIIIJJ;

	private int JIJIJIJJJJIJIJJJIJJIIIIJIIIIIJJJJIIIJJJJJJIIIJI;

	[NonSerialized]
	private bool JJIIIJJJIJIJIJIIJJJIJIIJIJIIJJJJJJJIIIIIIJJJIJI;

	private UIDrawCall.IIIIJJIJJJJJJIJIIJJIJJJJIJJIJIIIIIIIIIIIJJIIJJI JIIIIIIIIIJJIIJJIJJJIIIIIIJJIIJJJJJIIJJIJIIJIII;

	private bool IJJIIIIJJIIIJIIJJJIJIIJIJJJIIJIJJJIJIIJIJJJIIIJ;

	public string JJJJIJJIIJJJJIJIIIJJJIJIIIJIIJJJJIJJJIIJIIJJIJI
	{
		get
		{
			return IIIIIJJIIIJJIJIIJIIIIIJIJJIJJJIJJIJJIIIJIJJIIJI();
		}
		set
		{
			IIIIIJJIIIJJJJJJIJIIIJIIIJIJIIIJJIIJIIJJIJIIIII(value);
		}
	}

	public static int JJJJIIJIIIIJIIJIIJJIIJIIIJJIIIJIIIIJIIIIJJJJJIJ => JJIJJJJIJJJJIJJJJIJJJJJIJIJIIJJJJIIIJJIJJJJJIIJ();

	public override bool IJIJIIIJIJJIIJIJIIJJIIJIIIJIJIIJJIJIJJIIJIJIJII => JIIIJJIIIIIJIJIIIIIJJIIIJJIJJIIIIJIJIIIIJIJJJII();

	public override float IJIIJJIIJIJJJIJIJJJIIJJIIIJJJIIIJJJJIIJJIIJIIIJ
	{
		get
		{
			return IJJJJIIJJIJJJJIIIIIJJJIIJJJJJJJIIJJJJIJJJJIIJIJ();
		}
		set
		{
			IIIJIIJIIJJJJIIIJIJJIJJJJJIIIIIJIJIJJIIIJJJIJJJ(value);
		}
	}

	public int JJJIJJIIJJJJIJJJJIIJJJIJIJJIJJIIJIJIIIIIIJJJJII
	{
		get
		{
			return JJJJJJJIJJIIJJIJJIJJIIJIJJJIIIIJIIJJIJIIJIJJIJI();
		}
		set
		{
			JIIJJIJJJJIIIIJJJIIIJIIJJJJJJJIIJJIJJJJIIIJIJII(value);
		}
	}

	public int JIJIJJJIIIIIIIJJJIIJJJJIIIJJIJIIIIJJIJJIJJJJIIJ
	{
		get
		{
			return JIIJIJIJJIJIIJIJJIJIIIJJIIIIIJJIJIIJIJIIIJIIJJJ();
		}
		set
		{
			JJJIJJJIIJJJJJJJJJJJIJJJIIIIIIIIJIIJJIIIJIIIIJJ(value);
		}
	}

	public float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ => JIIIJJJIIJIJIJIIJIIIJJJIJIJIJJIJIJIIIIJJIIIJJJI();

	public float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII => IJJJJIJJJIJIIIIIJJJIJIJIIJIJJJJJJJJJJIJIIJJJJJI();

	public bool IIJJIJIIIJIJIJIJIIIIJIJIIIIJIJIJIIIIJIIJIIJIJII => IIIIIJJJJIJJJIJIJJJJJIIJJIIJIJIJJJIIIJIIIIJJIJJ();

	public bool JIJIJJJJJJJIIIJJIJIIJJIJIIJIJJIJJJIIJJIJJJJIIJJ => JJJIIIIIJJIIIJIIIIJJJIJIJJJJJJJJJJJIIJJIIIIJJJJ();

	public Vector3 JJIIJIIIIIJJJIIJJIJJJJIJJJJIIIIJIJIJIJIIJJJIIJJ => IIIIIJJIJIJJJJIJIJJJIIJJIIIJJJIIIJIIIJIJJJJJJIJ();

	public UIDrawCall.IIJIJJIIIJJJIJJJIJJIJJIIIJJJIJIJJIJJJJIJJJIIJIJ JIIIJIJIIJIIIIIIIJIJJJJIJJJIJIIIJJJJIIJIJIJJIIJ
	{
		get
		{
			return JJJJJIJJJIIIIIIJJJJIJIIIJJJIJIJJJIJIIJIIJJJJIJI();
		}
		set
		{
			JIJIIIJJIJJJJIJIIIJIIIJIJJIJIIIIIJJJJJIIJJJIJJI(value);
		}
	}

	public UIPanel IIJIJIJIJIJJJIJIIJJJIIJJJIJIIJIJIIJJIIIJJJIJJJJ => JIIIIJIIJIIJJJIJJJJIIIIJJJJIJJJJIJJIJJIIIIIJJII();

	public int IJIJJIJJIJJJIIJIJIJIJIIJIJIIIJIJIJJIIJIIIJIIJIJ => JJIJJIJIJIIIJJJIJJIIIJIJJJIIJIIIIJJIIJIJJIIJJIJ();

	public bool JIIIIJJIJJJJIJIJJIJJJIJIJJJJJIJJJIJIIIJJJJJJIII => IIJJJJIJIJJIIIJJIJJIJJIJIIJJJJJJIIJJJIIIJIJJJIJ();

	public bool JIJJIJJJJJIJJJIJJJJIJIIIJJJIJIJIJJJJIJIIIJJIJJI => IJJJJIIJIJJJJIJJIIIJIIIIJIJIJJJIIJJJIJIJJJJIIJJ();

	[Obsolete]
	public bool IJIIIJJJIIJIIIJIJIJIJJJJIJIIJJJJJJJJJIJJIJJIJIJ => IIJIIIIIJIJIJIIIIJJJJJJIJJJIJIJIJJIIJIJJJJIIIIJ();

	public Vector2 JIJIIIIIIJJJIIJJJIJJIIIIJIJIIIJIIJIJJIIIJJIIIIJ
	{
		get
		{
			return IJJIIIJJJJIJJJIJJIIJJIJJIIJIIJJJJJIIJIIIIJIIIII();
		}
		set
		{
			IIJIJIJIIJIIJIJJIIJIJIIJIIIJJIIIIJIIJIIIIIIJIIJ(value);
		}
	}

	public Texture2D IIJJJIIJJJIIJIIJIJJJJIIIJIJIJIIIJJIIJIIIJIIJJII
	{
		get
		{
			return IIIJIJIJIJJJJJIJJIJIIJIJJIJIJIIIIJJIJIIJIIJIIII();
		}
		set
		{
			JJJIJJIJJJJJJJJIIIJJIIIIJIJJIIJIJIJJIIIIIJIIIJJ(value);
		}
	}

	[Obsolete]
	public Vector4 IJJIJJJIIJIIIIJJJJIIIJIJIJIIIIJJJIIJJJJIIJJIIII
	{
		get
		{
			return IIIJIIIJJIJJIIIJJJJJIJJIJIIIIIJJJJIIJJIJIJJIJII();
		}
		set
		{
			JIJIIIJIIIJIJJJIIJIJJIJIJJJJIJJIIJJJIJJJJJJIIII(value);
		}
	}

	public Vector4 JJJIJJIIIJIIJIIIIJIIIJJIIJIJJJIJJJJIIJJJIJJIIJJ
	{
		get
		{
			return IIJIJJIJIIJIIIIIJJJJJJJIIJJIIIIJJIJIIIIIJJIJIJI();
		}
		set
		{
			JIIJJJIJIIIIJJIIJJJJJIIIJIIJIIIJJIJJIIJIIIJIIIJ(value);
		}
	}

	public Vector4 JJJIJIIIJIJJIJIIJIIJJIJIJIJIJJJJJIIIIJJIJIIIJJJ => IIJJIJJIJIIIJIIIJIJIIJIIJJJIJJJIJIIJIIJJJIIIJIJ();

	public Vector2 JIJIJJJIJJJJJIJIIJJJJJJJIIIJJJIJIIIJIIJJJJJJIIJ
	{
		get
		{
			return IIIIJIJJJIJJJJJJIJIIJIJJJJJJIJIJIIJIIIIIJJIJJJI();
		}
		set
		{
			IIJJIJJJIJJJJJIJJIJIIIJIIIJJIJIIJIJIJIIIIIJJIJJ(value);
		}
	}

	public override Vector3[] IIJJJJIIIJIJIIJIJIIJJIIIIJIJJIIJJIJIIIIIIJJIIII => JIIIIIIIIIJIIJJIJJJJJJJIIIIIJJIIIJJJJIJIJIIJIII();

	public override Vector3[] JIIIIIIIJIJJJJIJJIJIJIJJIIIIJJIIIJIIIJIJIJJJJJI => JIJJIJIJIJIIJJJJJIJIJIIIIJIIJIIJJJJJJJJIIJIJJJI();

	public bool IJIJJJIIIIJIIJIIIJJIIJJIJIIIJJIIIIIIIJJIIIIIJII(UIWidget JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII)
	{
		return false;
	}

	public bool IIIIIJJJJIJJJIJIJJJJJIIJJIIJIJIJJJIIIJIIIIJJIJJ()
	{
		return false;
	}

	public static UIPanel IJIIJIIJIIJIJIJIIJIIJIJJJIIIJJIIIIJIIJJJIJJJIJI(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ, bool IJIIIJIJIIJIJJIJIJJIIIIJJIJIJJIIIJJJJIIIIIJJJII)
	{
		return null;
	}

	public override float IJJJJIIJJIJJJJIIIIIJJJIIJJJJJJJIIJJJJIJJJJIIJIJ()
	{
		return 0f;
	}

	public bool JJJIIIIIJJIIIJIIIIJJJIJIJJJJJJJJJJJIIJJIIIIJJJJ()
	{
		return false;
	}

	public void IIIJIJJJIJJIIJJJJIIJJJJJJIIJJIJJJJIJIIIJIJJIJJJ(UIWidget JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII)
	{
	}
	public virtual float IIIJIJIIIIJJIIIIJIJJJIIIIIJJJJIIJJIIJJIIIJIIJJJ()
	{
		return 0f;
	}

	private void JIJJJIJIIJIIJIIJJJIJJJIJJJJIIIIJIIJIJJIJIIJIIJJ(int IIJIIIJIJIIIJIJJJIJIIJIJJIIJIJIIJJIIJIIJIIIIJJJ)
	{
	}

	public Texture2D IIIJIJIJIJJJJJIJJIJIIJIJJIJIJIIIIJJIJIIJIIJIIII()
	{
		return null;
	}

	public bool IJJJJIIJIJJJJIJJIIIJIIIIJIJIJJJIIJJJIJIJJJJIIJJ()
	{
		return false;
	}

	public UIDrawCall JIJIJJJIIIJJJIJJIJJJJJJIIJJJIIJJJJJIIJJJIJJIJII(UIWidget JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII)
	{
		return null;
	}

	public UIPanel JIIIIJIIJIIJJJIJJJJIIIIJJJJIJJJJIJJIJJIIIIIJJII()
	{
		return null;
	}

	public override void IIJJIJJJIIJJJJJIIJJIIJIJIIJJJIJIIJJIJJIJJIJJJJJ(bool JJJJIJJJIJIJJJIJIIJIIJJIJIJIIJIJIIIIIJIJJIJIIJJ)
	{
	}

	public override void nLateUpdate(int IJIIIJJIIJJIIIIIJIJIJJIIIIJJIJJIJJJJJIJJIIJJIII)
	{
	}

	public static void IIIIJIIIJJJJIJIIJJIIIJJJJJJIIIJIJJIJIIJJJJJJIIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void JJIIJJJJIJJIIIJJJJJJJJJIIIIIIJIJJIJIJIJJJIIJJJJ()
	{
	}

	public bool IJJIIIJIJIJIJJJJJIIJIJJIIJIJIIJIIIIJJIIJIIIIIIJ(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, bool IJIIIIIJIJJIIIIJIIIJJIIIJJIJJJIJJIIIIJIJIIIIIII)
	{
		return false;
	}

	public void JJJIJJIJJJJJJJJIIIJJIIIIJIJJIIJIJIJJIIIIIJIIIJJ(Texture2D JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool IJJIIIJIJIJIJJJJJIIJIJJIIJIJIIJIIIIJJIIJIIIIIIJ(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, ref Bounds IIIIJJIJJJIIIIJJJIIJIJIJJIIJJJIIJIIJIJIJIJIJIIJ, bool IJIIIIIJIJJIIIIJIIIJJIIIJJIJJJIJJIIIIJIJIIIIIII)
	{
		return false;
	}

	public Vector4 IIIJIIIJJIJJIIIJJJJJIJJIJIIIIIJJJJIIJJIJIJJIJII()
	{
		return default;
	}

	public bool IIIIIIIIIIJIJIJIIIIIJIJIJJIIJJJJIIIJJJJJIJJJIJJ(Vector3 IIIIIIIJIIIJJIJIJJJJJJJIIIJJJJJIIIIJJIJIIJJIIJI)
	{
		return false;
	}

	public void JIJJIJIJJIJIIIIJJIIJIIIIJIJIJJJJIJIIJJJJIJJIIII()
	{
	}

	private void IJJJIJIJJIJJJIIJIJJIIJJJJJJJIJJJJIIJIJIJJJIJIIJ()
	{
	}

	public bool IIIIIIIIIIJIJIJIIIIIJIJIJJIIJJJJIIIJJJJJIJJJIJJ(UIWidget JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII)
	{
		return false;
	}

	public Vector4 IIJJIJJIJIIIJIIIJIJIIJIIJJJIJJJIJIIJIIJJJIIIJIJ()
	{
		return default;
	}

	public static UIPanel IJIIJIIJIIJIJIJIIJIIJIJJJIIIJJIIIIJIIJJJIJJJIJI(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ)
	{
		return null;
	}

	public static UIPanel IJIIJIIJIIJIJIJIIJIIJIJJJIIIJJIIIIJIIJJJIJJJIJI(Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ, bool IJIIIJIJIIJIJJIJIJJIIIIJJIJIJJIIIJJJJIIIIIJJJII, int IIJIJIJJIJIJIJIJJJIJJIJIIIJJJIJIIJJJIIJJIJJIJJJ)
	{
		return null;
	}
	public void JJIIJIIIJJIJIJIIIIIJJIIJIJIJJIJJJIJIJJIIIJJJJII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void IJIIJIIIJIJIJJJIJJJJIJJIIIJJJIIJIIIIIIJJIJJJJII()
	{
	}

	public Vector2 JIJJJJIIIIIIIIIJJJIJJIIJIJJIJJIIJJIJIIJIIJJJIIJ()
	{
		return default;
	}

	protected override void OnEnable()
	{
	}

	public void IIJJIJJJIJJJJJIJJIJIIIJIIIJJIJIIJIJIJIIIIIJJIJJ(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected override void JIIJJJJIIIIIJJIJIIIIJIIIIJJIJJJJJIJJJIJIJJJJJJJ()
	{
	}

	public override Vector3[] JIJJIJIJIJIIJJJJJIJIJIIIIJIIJIIJJJJJJJJIIJIJJJI()
	{
		return null;
	}

	public void IIIIIJJIIIJJJJJJIJIIIJIIIJIJIIIJJIIJIIJJIJIIIII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public bool JJIJIIJJJJIIJIIJJJJJJJJJJJIIIJJIIIIJIIIJJJJJIJI()
	{
		return false;
	}

	public override void IJJIJIJJJJIJIJJIJJIJJJIJJJIIJJJIJIJIJIIIJJIJIII()
	{
	}

	public virtual void JJIJJJJIIJJJIJIIIJJJJJIJJJIIJJJJIJIJJIJJJIIJIJI(bool JJJJIJJJIJIJJJIJIIJIIJJIJIJIIJIJIIIIIJIJJIJIIJJ)
	{
	}

	public override bool JIIIJJIIIIIJIJIIIIIJJIIIJJIJJIIIIJIJIIIIJIJJJII()
	{
		return false;
	}

	public int JIIJIJIJJIJIIJIJJIJIIIJJIIIIIJJIJIIJIJIIIJIIJJJ()
	{
		return 0;
	}

	public float IJJJJIJJJIJIIIIIJJJIJIJIIJIJJJJJJJJJJIJIIJJJJJI()
	{
		return 0f;
	}

	public bool IJJJJIIIJIJIIJJJJIJIIJJJIJIJJIIJIIJJJJJJJIJJJJI(UIDrawCall IJJIIJIIIJIJIJJIIJJIJIJJIIIJJJJIIJIIIJJIIJJJIJJ)
	{
		return false;
	}

	public Vector4 IIJIJJIJIIJIIIIIJJJJJJJIIJJIIIIJJIJIIIIIJJIJIJI()
	{
		return default;
	}

	public void JJJIJJJIIJJJJJJJJJJJIJJJIIIIIIIIJIIJJIIIJIIIIJJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public float JIIIJJJIIJIJIJIIJIIIJJJIJIJIJJIJIJIIIIJJIIIJJJI()
	{
		return 0f;
	}

	public bool IIIIIIIIIIJIJIJIIIIIJIJIJJIIJJJJIIIJJJJJIJJJIJJ(Vector3 IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, Vector3 JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII, Vector3 IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ, Vector3 JJIJIIJIJIJIJJJIJIIIJIJIIJJJIIIIJJIIIIIIJIIJIJI)
	{
		return false;
	}

	public Vector2 IIIIJIJJJIJJJJJJIJIIJIJJJJJJIJIJIIJIIIIIJJIJJJI()
	{
		return default;
	}

	public Vector2 IJJIIIJJJJIJJJIJJIIJJIJJIIJIIJJJJJIIJIIIIJIIIII()
	{
		return default;
	}

	public Vector2 JIIIIIJJJJJIJIIIJIIJIJJJJIIIJIJJIJJJIJJJJIIIIJI()
	{
		return default;
	}

	public override Vector3[] JJJJJIJJIJJJJIIIIIIIIJIJIJIJIIIJJJIJIIIIIIIJIII(Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
	{
		return null;
	}

	public void IIJJJJIIIIIJIJJIJJJJIIJIJIIIJJIIJJIJIJJIJJIIIJJ()
	{
	}

	public bool IIJJJJIJIJJIIIJJIJJIJJIJIIJJJJJJIIJJJIIIJIJJJIJ()
	{
		return false;
	}

	protected virtual void JJIJJIJIJIIIJJIIIIIJJIJIIIIJJJIJIIJIIIJJIIJIJJI()
	{
	}

	public static int JJIJJJJIJJJJIJJJJIJJJJJIJIJIIJJJJIIIJJIJJJJJIIJ()
	{
		return 0;
	}

	public void JIJIIIJJIJJJJIJIIIJIIIJIJJIJIIIIIJJJJJIIJJJIJJI(UIDrawCall.IIJIJJIIIJJJIJJJIJJIJJIIIJJJIJIJJIJJJJIJJJIIJIJ JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIIIJIJIJJJJJIJIIIJJJJJIIJJIJIJJIJJJJIIIJJJIJI()
	{
	}

	public void JIIJJJIJIIIIJJIIJJJJJIIIJIIJIIIJJIJJIIJIIIJIIIJ(Vector4 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool JJIJIJIIIJJJIJJIIJIIJIJJIJIIJIJJJIIIIIIIJIIJIJJ(UIDrawCall IJJIIJIIIJIJIJJIIJJIJIJJIIIJJJJIIJIIIJJIIJJJIJJ)
	{
		return false;
	}

	public override void IIIJIJIIIJIIJJIJIJIJJIIJJJJIIJIIJIJIJJJJIJJJJJJ(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
	}
	public void IJIIIJIJIJJJIJJIJJIIIJJJIJIIIJIJJJJJIJJJIIJIIJJ(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void IJJJIIIIIIIIJIIJIIIJIJIJJJIIJJJIJJIJJIJJJJIJJII()
	{
	}

	public virtual void JIJJIIJJJIIIIJIIIJJJIJJJIIIIIJJJJIJIIIJIIIIJJIJ()
	{
	}

	private void JIJJJJIIIIJIJIJJJIIIIJJIJIIIIJJIIJIIIIJJJIIJIII()
	{
	}

	public override Vector3[] JIIIIIIIIIJIIJJIJJJJJJJIIIIIJJIIIJJJJIJIJIIJIII()
	{
		return null;
	}

	public void JIIJJIJJJJIIIIJJJIIIJIIJJJJJJJIIJJIJJJJIIIJIJII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJJIJIJIIIJIJIJIIJIJIIJJIIIIIJIJJJIJIJJJIJJIIJ(UIWidget JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII)
	{
	}

	public bool JJIJIJIIIJJJIJJIIJIIJIJJIJIIJIJJJIIIIIIIJIIJIJJ(UIDrawCall IJJIIJIIIJIJIJJIIJJIJIJJIIIJJJJIIJIIIJJIIJJJIJJ, bool IIJJJJJIIJJIIIIIJIIJIJIJIJIIIIJIIJJJJIIIJIJIJIJ)
	{
		return false;
	}

	public Vector3 IIIIIJJIJIJJJJIJIJJJIIJJIIIJJJIIIJIIIJIJJJJJJIJ()
	{
		return default;
	}

	protected override void OnDisable()
	{
	}

	public bool IIJIIIIIJIJIJIIIIJJJJJJIJJJIJIJIJJIIJIJJJJIIIIJ()
	{
		return false;
	}

	public static int JIJIJJJJIJIJJJJIIIIJIJJIIJJJJJJJJJIJJJJJJIIJJIJ(UIPanel IJJJIIIJIIJJJJIIJJIJJIJJIJIIIJJIIJJIIJIIIIJJJJJ, UIPanel JJJIIIIIJIIIIIJIIJJJIIIIJIJJIJJIJIJIIIJJJJIIJII)
	{
		return 0;
	}

	public void IIJJIIIIIIJIIIJIJIJIIJJJJJIIIJJIIJIJIJIJJIJIJJJ()
	{
	}

	private void JIIIIIIJIJIIIIJIIJIJIIJJIIJJIIJJJJIJJJJJIIIIIIJ()
	{
	}

	public UIDrawCall.IIJIJJIIIJJJIJJJIJJIJJIIIJJJIJIJJIJJJJIJJJIIJIJ JJJJJIJJJIIIIIIJJJJIJIIIJJJIJIJJJIJIIJIIJJJJIJI()
	{
		return UIDrawCall.IIJIJJIIIJJJIJJJIJJIJJIIIJJJIJIJJIJJJJIJJJIIJIJ.None;
	}

	public void IIJIJIJIIJIIJIJJIIJIJIIJIIIJJIIIIJIIJIIIIIIJIIJ(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual Vector3 JIJIJJIJIIJIJJJIIIIJJIJJJJIJJJIIJJJIJJIIJJJIJIJ(Vector2 JJJJIJIIJIJJIIJJJIIJIJJIJIIIJJJIJIJIIJJIIJIJIJJ, Vector2 IJIIJJIJIJIJIIJJJIJIIIJIJIIJIJJIIIIJIIIJIIIIIJJ)
	{
		return default;
	}

	public override float IJJJIJJIIIJJIJJJJJIIIJIIIJJIIJIJIJIIIJIIJJIJJII(int JJIJJJJJJIJIIIIIJJIIJIIJJIJIJJJIIIJIIJJJJJIIIIJ)
	{
		return 0f;
	}

	public void JIJIIIJIIIJIJJJIIJIJJIJIJJJJIJJIIJJJIJJJJJJIIII(Vector4 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public int JJJJJJJIJJIIJJIJJIJJIIJIJJJIIIIJIIJJIJIIJIJJIJI()
	{
		return 0;
	}

	protected override void Awake()
	{
	}

	private void JJIIIIJIJIIJJIJIJIIJIIJIIIIJJJJJJIJIJJIIJJJJIJI()
	{
	}

	public void IJJJIJIIJIJJJJJJJIIIIJIJJJIJJJJIJJIIJJJJIIIJIJI()
	{
	}

	public string IIIIIJJIIIJJIJIIJIIIIIJIJJIJJJIJJIJJIIIJIJJIIJI()
	{
		return null;
	}

	protected override void JIIIJIIJIIJIJJJIIJIJIIIJIJIJJIIJJIIJIIIJIIJJIII()
	{
	}

	public override void IIIJIIJIIJJJJIIIJIJJIJJJJJIIIIIJIJIJJIIIJJJIJJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJJIJIJJIIIJJIIJIJIIJJIJIIIIIIIJIIIJIJJIIJIJIJI()
	{
	}
	public void IJJIIJJIIJIJIJJIIJIJIIJJIIJIJIIIJIJIJJJJIJJJJII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public bool IIJIJJJIIIJJIIJIJJIJJJIIIJJIIJIIIJIJJIIIJIIJIJI()
	{
		return false;
	}

	public int JJIJJIJIJIIIJJJIJJIIIJIJJJIIJIIIIJJIIJIJJIIJJIJ()
	{
		return 0;
	}
	public void IIJJJJJIJJJJJIJJJIIIJJJIJIIJJIIJIJIIJIIIIJIIJII(string JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected override void JJJIJIJIJIIJJIJIIJJIIJJIIIJJJIIJIJJIIJJJJIJIIII()
	{
	}
}
