using System.Collections.Generic;
using UnityEngine;

public class UIPanelManager : MonoBehaviour
{
	public List<GameObject> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ;

	private static UIPanelManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public void IJIJIIIJIIIIJJJIIJJIIIJIIIJIIIJJJIJIIJIIJIJIJII(string panel)
	{
	}

	public static GameObject IIJIJJIJJJIJJIJIIJIIIIJJIJJIJJJIIJJIJJJJIIIJJJI(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
		return null;
	}

	public static GameObject IIIIJIIIJJIIJIIIIIJJIJIJJJIJIIIIJIJJJJIIIJJJIJJ(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
		return null;
	}

	public static void IJIJJJJJJJJIIJIIIJJJIJIIJJJJJIIIJIJIIJJIJJIJIJI(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
	}

	public static GameObject JIIIJJIIJIJJJIJJIJIJJIIJIIJIIIJIJJJIIJIIJIIIJII(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
		return null;
	}

	private void JJIJIIIJIJIJJJJIJIIJJJJJIJJJJJIJIJIJIIJIIJIIIJJ()
	{
	}

	public static void JJJJJIIIJJIIJJJIIIJJIIIIJJIJIJIIJJJJJJIIIJJIJJJ(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
	}

	private void IIIJIJJJIIJIIIJIIJJJIJJIJIIJJJIJJIIIJJJJIIJJJIJ()
	{
	}

	private void IJIJJJJJIJJIIJJJJJIJIJJIJJJJJJIJIIIIIIJJJJIIIIJ()
	{
	}

	public static void JJJJIJIJIIJJJJJJJJIIIJIIIIJJIJIIJJJJJIJIJJIIJJJ()
	{
	}

	public static GameObject IJIIIIIIIIJJIIJIJJIIIIIJIIJIIIIIJIIJJIIIIJIIIJI(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
		return null;
	}

	public static void IJIIJJIIJIIJJJIIIJIJJJIJJIJJIJIIIIJJIIIIIIIJIII(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
	}

	private void IJJIJJJJJIJIIIJJJIJIJIIIIJJIJIIJIIJIJJIIIJJIJIJ()
	{
	}

	public static void JJJIJJIJIJJIIJIJIJJIJJIIJIJIJJIJJJJIIJJIIJJJIIJ()
	{
	}

	private void IJIIIJJJIIJIIJIIJJIJIJJJJJJIIIIIIIJIJJJJIJJIIJI()
	{
	}

	private void Awake()
	{
	}

	public void JJJIJIJIJJIIIIIIIJJIIJJIJIIJIJIJIJJJIJIIIJJJJJI(string panel)
	{
	}

	private void IIJIIJJJIIJJJIIIJJIJIJJIIJJIIIJIJJJIJJIJIJJIJJI()
	{
	}

	public static GameObject IJJJIJIIJIIJJJIJJIIIIJIIJIIJJIIJJIIJJIIIIJJIJJI(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
		return null;
	}

	public static void JJJJIJJJJJIIIIJIIIIJIIJIJJIJIIJIJIJJJJJIJIIJJJI(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
	}

	public static GameObject JIIIIJJJJIJJJIIIIIIIJJJJJIIJIIIJJJIJIIIIJIJIJIJ(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
		return null;
	}

	public static GameObject JJJIJJIJIJIJJJJJJIJIJJJJIJJJJIJIJJIJJIJJJJJIIIJ(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
		return null;
	}

	public static void IJIJJIJIIIJIJIJJIIIJJJIIIIJJJIJIIIIJJIIJJIIIIIJ(string JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
	}

	public void Show(string panel)
	{
	}
}
