using System.Runtime.CompilerServices;
using UnityEngine;

public class UIPlayerStatisticsElement : MonoBehaviour
{
	public UIPlayerStatistics IIIIIJIJIJIJJJJIJIJIJIJJIIJIJIIIJJIIIJIJIJJIIJJ;

	public UILabel IIJJJJJJJIIIIIIJIIJJJIJJJJIIIJIJJJIJJJIIJIIJIJJ;

	public UISprite JIJIJIIIIJIJIJIIIIIJJJJJIIIJJIIIJJIIIIJIJIJIJJJ;

	public UITexture IJIIJJJJIJIIJIIJJJIIJJIIJIJIIJJIIIIIIIJIJJIIJII;

	public UILabel IJJJJIIIJIJJJJIIJJJIJJIIJIIJJJJJJIIIIJJIIJIIJIJ;

	public UISprite JIJIIIJJJIIIIJJIJJJIIIJIJJJJJJIJIIJIIIJIIJIIIJJ;

	public UILabel IJIIJJJJIJIJIIJJJJIIIJJJJJJIIIJIJIIJJIJJIIJJIJJ;

	public UILabel JIIIIJJIIJJIJJIJJIJJIJIJJIIIIIJIIJIIIIIJIJJJJII;

	public UILabel JIJIJIIJJJJJJIJIIIJJIJJIIIJIIJIJIIIIIIIJIIJJJJI;

	public UILabel IIJJIJJIJJJIJJIIIIIJIIIIIJIIIIJIJIJIIJIJIIIIJIJ;

	public UILabel IJJJJJJJIJJIIIIJIJIJJJIJIIJIIJIIIIJIIIJJIIJJIJJ;

	public UILabel JIJIJIJIIJJIIJJIIIIIJJJIIIIIIIIIIJIJJJIJIJJIJJJ;

	public UIWidget JJIJJJIIIIIIIJIIIIIJJIIJIJIIIJJJJIJIJJJIJJIJIJI;

	private static Color32 JIJIIJIJJJJJIJIJIIJJJJIIIJJJIIJJJIIJIIJJJIIJIII;

	private static Color32 JJJIJJIJIJIJIIJIIJIIJJJJIJIIJIIIJJJJIJJIJJJIIJI;

	private static Color32 JJIIIIJIIIJIJJJIJJJJJIJJIIIJJJIJIJJIIIIJIJJIJJI;

	public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI;

	private int JIJJIIIJJIIJJJJJJJIJJJJJIIIJJIIJIJIIIIJJJIIJIJI;

	private Transform JJIJIIJIIJJJJJIIIJIIIJJJIJJJIIIIJJIJJJIIIJJIIII;

	private GameObject JJIJIJJJJJJJJJIJIJIJIJIIIJIIIJIJIIIIIIIJIJJJIJI;

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	public GameObject JIIIJIJJJIJJIJIJIIIJJJJIIJIJJJIIIJJIIIJIJIIJIII => JIJJIIJIIIJIJIIJJIJIJJJIIIJIIIJJIIIJIJJJIIIJJJJ();

	private void IJJIJIJIJIIIJIIIJJJJIIIIJIIJIJJJIIJIJIJIIIJIJII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	private void JIJJJIIIIJJJIJIJJIIJJJJJJIIJIIIIIIIIJIJJJJIIIIJ()
	{
	}

	private void IJIIIIIIIJJIIIJJIIIJJIIIJIIIIIJIJJIJIJJIIIJJJIJ()
	{
	}
	public Transform IJIIJIJIJJJIIJIJIIJIIJIIJIIIJJJJJJJIJIJIIJIJJJJ()
	{
		return null;
	}

	public void IJIIJJJIIJJIJJIIIJIIJJIJIIIIJJJIIJJJIJJIJIJIJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJJIIIJIJIJIIIJIIJIJIIIJIJIIIIJIIJJJIJJJJIJJJJ)
	{
	}

	private void JIIIIJJJJJJIJJJIIJIJIIIIIIIIIIJJIJIIJJIJIIIIIJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}

	private void OnClick(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	public void IJIJIIJJIIJIJJIIIJJJIJIJIJJIIIIIJIIJIJJIJJJJIII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJJIIIJIJIJIIIJIIJIJIIIJIJIIIIJIIJJJIJJJJIJJJJ)
	{
	}
	public GameObject JIIIJJJJJJJIIJIIJIJIJJIJJJIJIIJIJIIJJIIJJIIIIJI()
	{
		return null;
	}

	private void JIJJJIIIIJIJIJIIJJJIIIIJJIJJJIJIIIIIIJJIJIIIJJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}
	public GameObject JJJIIJJIIIIIIIJIJJIJJJIJJJIJJIJIJJIIJJIIJJIJIJI()
	{
		return null;
	}

	private void UpdateData()
	{
	}

	private void IJIJJIIJJIJIIIJIJIIJJIJIIJJJIJJIIIJJJJJIJJJIIII()
	{
	}

	private void JJIJIIJIJJIJJIIIJIIJIJIIIJIIJJIJJJIJJJIJJIIJIJI(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
	{
	}
	public Transform IJJJJIJIIIJIIIJJJJIJJJJJIJIJIIIJIJIJIJIIJIIIIJJ()
	{
		return null;
	}

	private void OnEnable()
	{
	}

	private void IJJIIIJIJJIJJIIIJJJIIJIJJIJJIJIIJJJJIIJIJIJJIIJ()
	{
	}

	public void JJIIJIJJIIJIIIIJJJIJJJIIJIIIJIIIIIIIIJIJIIJIJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJJIIIJIJIJIIIJIIJIJIIIJIJIIIIJIIJJJIJJJJIJJJJ)
	{
	}

	private void JJJIIIJIIIIJJIIJJIJIIJIJJJJJIIJJIIIIJIIIIIIIJIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
	{
	}

	private void IIJJIJIJJJIIIJJJIJJIJJIIJJIJJIJIIIIIJJJJJJIIIJI(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	public void IIJIIJIIIJJIIJJIIJJJIIJIJIIJIJIJJJJIJIJIJIJJJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJJIIIJIJIJIIIJIIJIJIIIJIJIIIIJIIJJJIJJJJIJJJJ)
	{
	}

	private void JIJJIJJJJIIIJJIIIJIJJJJIIJIIJJIIJJJIJIJIJIJJJIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
	{
	}

	private void JIIIIJIIJIIJJJIJIJIJJIIJJIIJIIJIIIJIJJJJIJIIJJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	public GameObject JIJJIIJIIIJIJIIJJIJIJJJIIIJIIIJJIIIJIJJJIIIJJJJ()
	{
		return null;
	}

	private void OnDisable()
	{
	}

	private void IIJJJIIJJJIJJIJJIIIIIJJJIIJIJJJJJJIJJIJJJIJJIIJ(string JIIJJJJIIIIJIIJIIJJIIIIJJIJIIJJJIIJIIIIIIJJJJIJ)
	{
	}
}
