using System.Runtime.CompilerServices;
using UnityEngine;

public class UIPlaySound : MonoBehaviour
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IJJJIIIJIJJJJIIIIJJJJJIJJJIIJIIIIIJJIJIIIJJIIII
	{
		OnClick = 0,
		OnMouseOver = 1,
		OnMouseOut = 2,
		OnPress = 3,
		OnRelease = 4,
		Custom = 5,
		OnEnable = 6,
		OnDisable = 7
	}

	public AudioClip IIIJIIJJJIIIIJJJIIJIIJJIJJIIJIJJJJIJJIIIIIJJJJJ;

	public IJJJIIIJIJJJJIIIIJJJJJIJJJIIJIIIIIJJIJIIIJJIIII IIJJIJJIJIIIIIIIIIJIIJJJJIJIJIJIIIJIJJJJJIIJIII;

	public float IIJJIIIJIJIJJJJIIJJJJIIIIIIIIIIJIIIIJIJIIIIIIII;

	public float IIIIJJJJIJIJJIJJIJIJJJIJIJJIIJIIJJIIIJJIIIJIJJJ;

	private bool JJIJIJIIIJIIIIIIIJIIIJJJIJIIIIIIJJJJIJJIIIJJIIJ;

	private bool IJIJIIIJIIJIIJIIIJJJIIIJJIIJIIIJIJIJIIJIIIIJIII => JIIJJIIIIIJIIIIJIJJJJJIJJIJJIJJJIJIJIJJJIJJJJIJ();

	private void JJJIJJJJJIIJIJJJIJIIIIJJIJJJIJIIJJIIJIIJJJJIIJI()
	{
	}

	private void IJIIJIIIIJJIIJJJJIJJIIIJIIIJIJIIIIIJIJJJJIIJJJJ(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	public void JIJJIIJIIJJJJJIJIIJJIJIIJIJJIIJJIJIIIIIJJJIIIJJ()
	{
	}

	private void JIJJJJIJIJIJJIJJJJJIIJIJJIIIJIIJIIIJJIJJJJIIJIJ(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void OnClick()
	{
	}

	private void IIJJJIIIJIJIJJJJIIJIJIJIJJJJJIJIJJJJJJJIJJIJJII(bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	public void IIJIJIIJIIIIJIIIIJIIIJIIJJIJIJIIJIIJIJJJJIIJJJJ()
	{
	}

	private void IJJJJJJJJIJJJIIJJJIIIJJIIJIIIJJIIJIIIJIIJJJJIJI(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}
	private bool JJIJIIJIIIIJIJJIIIIJJJIJJJJIJIJJIIJJIJJJIJJJIIJ()
	{
		return false;
	}

	private void IJIIJJIJIIJIIJIIIJJJIJJIIIIJIIIJIIJJJJIIJIJJJIJ()
	{
	}

	private void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	private void OnDisable()
	{
	}

	private void JIIJIIIIJJJIIIIIIJJIIIIIIJJJIJJJJJIJIJJIIIIIIJI(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private bool JIIJJIIIIIJIIIIJIJJJJJIJJIJJIJJJIJIJIJJJIJJJJIJ()
	{
		return false;
	}

	public void IJIJIJIJIIJJJIJIIJIJJJJJJIIJJIIIIIIJJJIJIIJJIJJ()
	{
	}

	private void IIJJJIJIIIJIIIJJJJIIIIJIJJIJIIIIJJJIIIJIIIIIJII()
	{
	}

	public void IJJJIIJIJIIIJJIJJIJJIJIIJIJJIJJJIJIJJJIJIJIJIII()
	{
	}

	private void JIIJIIIIJIJJJIIIIIJJIJJJJJJIIIJIIJJIJIJIJIJIIIJ()
	{
	}

	private void OnEnable()
	{
	}
}
