using System.Collections.Generic;
using UnityEngine;

public class UIPlayerList : MonoBehaviour
{
	public UIGrid IIIIIJIIJJJIJIJJIIJJIJJJJIJIJJJJIJJJIJIIIIIIJIJ;

	public GameObject IJJIJJIJIJIJJJIIIIJIJJJIIIIIIJJJJJIJIIJIJIIJJII;

	public UILabel IIIJJJJIJJIIJJIJIIIJJJJJIJIIIJJIIJIJIIJJJJJIJJI;

	public UILabel JIIIIJIJIIIJIJIJJJJIIJJIJJJIJIIJJIIIIJJIJIJJIII;

	public UILabel IJJIJIJJJIJIIIIJIIIIIJJJJIIIIIIJIIIIJIIIIIJIJJI;

	public UILabel IJJIIIJIIIJIIJJJJIIIIJJJIIJJIIJJJJIIJJJIIJJJIJJ;

	public UILabel JJIIJIJJIIIJIIIIJIIJIIIIJJJIIJJJJIIIJJJJJJIJJIJ;

	private List<Transform> IIIJIIIJJIJIJJIIIJIIIJIIIJJIIJIJJIIIIJJJIJIIJJJ;

	private List<Transform> IIIJJIJJJJJIJIJIJJIIJJJIJJIJIJJIIJJJIIJJIJJIIJI;

	private GameObject IIJJIJJIJJIJJJIIJIIIJIJIIIIJJJJIJIJJIIJIIJIIIII()
	{
		return null;
	}

	private void IIIIIJJJIIIJIIJIIIJJIJJJIJJIJIJIJIJJIIJIIJJJJJJ()
	{
	}

	public void IIIIJIJJIIJJIIJIJIJJJJIJJIIIIIJJIJJIIIIJIJIIIJI()
	{
	}

	private JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJJIIIJIIIJJJIJIIIIJIJIIJIJIJJIJIIIIIIJIJJJIIJI(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
		return null;
	}

	private void JIJIJJIIJIJJIIJIJJJJIJIIIJJIJJJIJJIJIJIIJJIJIJJ()
	{
	}

	private GameObject JJIJJIJJJJJIJJJJIIJJJIIIIJJIIIJJIIIJIIIJJIIIJIJ()
	{
		return null;
	}

	public void JJJJJIIIJIJJJJJIJIJJIIIIJIIIJJIJJIJIIJIJJJIJIIJ()
	{
	}

	private void IJJJIIJIIIJJJJJJIIIJIIIJIIIJJIIIJJIJJJJIIJJIJJJ()
	{
	}

	public void IJJJJIJIIIIJIJJIIIIIJIJIJJIIIIIIIJIJIJJJIIJIJII(Transform JJIJJIIJJIJIIIJJIJJIJJIJJIIIIJJIIJIJJIJJIIIJJJI)
	{
	}

	private JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJJJIIJIJIJIIJJJIIIJJJJIIIJJIJIIJIJIJJJIIIIJI(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
		return null;
	}

	private JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJJJIJJJJJIIJJJIIJJIIJIIJJJIJIJIIIIJJIIJJIIJI(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
		return null;
	}

	public void JJIIIIJJIJJJJIJJJIJIIIIJJIIIIIIJIJJIJIJJIJJIIII(Transform JJIJJIIJJIJIIIJJIJJIJJIJJIIIIJJIIJIJJIJJIIIJJJI)
	{
	}

	private GameObject JIIIJJJJJJJIJJJIJJJIIIIIJIIIJIJIJIJJJIJIJIJIIJJ()
	{
		return null;
	}

	private void JIJIIIJJIIIIIJIIJJJIJIIJJIIIIIIJIIJIJIJIJIIJJIJ()
	{
	}

	private void JIJIIJIJJJIJJJIIIJIJJIIJIJIIJIJJJJJIJJJIIJIJIJI()
	{
	}

	public void IIIJJJJJJJJIJIIJJJIJJIJJJJJJIJJIJJJIIJIJJIJIJJI()
	{
	}

	private GameObject IIIIIJJIIJJJJIIIIJIJIIJJJJIIIIIIJJIIIJIJIJIIIII()
	{
		return null;
	}

	private GameObject IJIIIJJIIIIIJJIJIJIJJJJJJJIIJIIJIIIIIJJJJIIIIJI()
	{
		return null;
	}

	private GameObject IIJJJIJIJIJJJIJJIJIIJJIJJIIIIJIIJIJJIJIJIIIIIJI()
	{
		return null;
	}

	private GameObject IIJJIIIJIIJJIJJJJIJJIIJIIJIIJIIJIJJIIJJJIJJIJII()
	{
		return null;
	}

	public void JIJIIJJIIJJJJJIJJJJJIIJJIJIIJJJJIIJJIJJIIJIJJII(Transform JJIJJIIJJIJIIIJJIJJIJJIJJIIIIJJIIJIJJIJJIIIJJJI)
	{
	}

	private GameObject IIIIIJJJIJIJJJJIIIIIJJIIIJJIIJJIIIJJJIIJJJJIJJI()
	{
		return null;
	}

	private void IIJJIIJJIIJIIJJIIJIJJIIIIIIIIIJJJJJIJJJJJJJIIII()
	{
	}

	private JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJJJJJJJJJIJIJJJJJJJIJIIJJIJIJIIJJIJIJJIJII(string IJIIJJJIJIJJIJIIJJIIIJIJJJIJJIJIIIIJIIIIIJJIJJI)
	{
		return null;
	}

	public void IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI()
	{
	}
}
