using System.Collections.Generic;
using UnityEngine;

[ExecuteInEditMode]
public class UIPlayTween : MonoBehaviour
{
	public static UIPlayTween JIIJIIIIIIIIIIJIJIIIJJIIJJJIIIJJIIIIIIIIJIJIJIJ;

	public GameObject IIIJJJJJIJJJIIIIIIIIIIJIIIIJJJJIJIJJJJJIIJJJJII;

	public int IIIIIIIIJIJIJIJIJIIIJIJJJJIJJJJIJIJJJJIJIIJIIII;

	public IIJJIJIJIJJJJJJJJIIJIJIJJJJJJIIJJJJJJJJIJIJJJJJ IIJJIJJIJIIIIIIIIIJIIJJJJIJIJIJIIIJIJJJJJIIJIII;

	public IIJJIIIIIIJJIJIJJJJJJIJJIJJJIJIIJJIJJJIJIJJJJJJ IIIIJIIIIIJIIIJJJJJJIJJIIJJIIJIJJIJIJJJIJJJIJJI;

	public bool JIIIJIIJJJIJIIIJIJJIJJIJIJJIIIJJJIJIIJJJJJJIIII;

	public bool IJJIJIJIJJJIIIJJJJIIJJIJJJJIJIJJIJJJIIJIJJJIIII;

	public JIJJIJIJJJJJJJIIJJIJJIJJJJJJIJIIIJJJIIIIJIIIJJI JJIJJIIJJJIJJJJIJJIJJIIIJIIIJJIIJIIJIJIJJIJJIJJ;

	public JJIIJJJJIIIIIIIJJJJJJJJJIJIIIIJIIIJJIJIJJJIIJIJ IIIJJJJIJIJJIIJIJIJJIIJIIIJJIIJIJJJJIJIIIJIIJJJ;

	public bool JJJJIJJJIJIJJJIJIIJIIJJIJIJIIJIJIIIIIJIJJIJIIJJ;

	public List<EventDelegate> IJIIIIIJJIIJJJIIJIIJJIIIIIIIJIJIIJIIIJJJJJIIJII;

	[SerializeField]
	[HideInInspector]
	private GameObject eventReceiver;

	[SerializeField]
	[HideInInspector]
	private string callWhenFinished;

	private UITweener[] IJJJJJJIJJJIIIJJJIJJJIJJIJIJJIIIJJIIJJJJJJIIIIJ;

	private bool IIJJIJIJJIJJIJIJIJJJIIIJJJIJJIIIIJJJJIJIJIIJIJI;

	private int JJIJJJJJJIIIIJIJJIIIJIJIJIJJIJJJJJIIIJIIJIIJJJI;

	private bool IJJJJJJIIIIIIJIJIIIJJJJIJJIJIJIJIJJIIJIJIIIJIII;

	private GameObject IIIJIJIIIIIJJIIJIIIJJJIIJIJIIJIJIIJJJJIJJJJIIII;

	private void IJIJIJIJIIJJIJJJJJJIIIJJJJJIJJJJJIIIJJIIIIIJJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void IJJJJIJJIJJIIJJIJIJIJIIJJJJIIIJJJJJIJIJIJIJJJII()
	{
	}

	private void JIIIIJIIJJJIIJIJJJJIJIIJIIIJIJJIJJIJJJJIIJIIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void Awake()
	{
	}

	private void OnDisable()
	{
	}

	private void JJJIJIIIIIIJJJIJJJJJIIIJIJIIIIIIIJIJIJIJJIJJIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, GameObject JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
	}

	private void JJJJJIJJIIJJJJIJIIIIJIJJJJIIIIIJIIIJIJJJJIJJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, GameObject JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
	}

	private void IIJJJIIIJIJIJJJJIIJIJIJIJJJJJIJIJJJJJJJIJJIJJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void IJJJJIIJJJIIJJIJJJIIIIIJIJIIIJJJIJJIIJIIJJJIIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, GameObject JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
	}

	private void IIIIJIJJJIJIIIJJJJIIJJIJJJJIJJIJIJJJJIJIIIIJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIIIJJIJIJIJIJJIIJJJIIIJJIIJIJIJJJIIJIJIJJIJIJJ)
	{
	}

	private void JJIJJJIIIIJIIIJJJIJJIJJJIIJJJIIJIJIJJIIJIJIIIJJ()
	{
	}

	public void JIJJIIJIIJJJJJIJIIJJIJIIJIJJIIJJIJIIIIIJJJIIIJJ(bool IIIIIIIJIIIJJJIJIIJIIIIJIJJJIJIJIIJIJIIIJIJJJII)
	{
	}

	private void OnEnable()
	{
	}

	private void JIJIJJIJIJJIIJJJIJIJJIIIJIJJJJJJJJJIIJIJJJJIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, GameObject JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ)
	{
	}

	private void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	private void JIIJIIIIIIIIJJJIJJIIIIJIIIJIJIIIJIIJJIIJIIJIJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void Start()
	{
	}

	private void JIIJIIIIJJJIIIIIIJJIIIIIIJJJIJJJJJIJIJJIIIIIIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	private void JIJIJJIIJIJJIIJJJJJJJJIJJJJJJJIJIJJIJIJJIIJIIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	public void IJJJIIJIJIIIJJIJJIJJIJIIJIJJIJJJIJIJJJIJIJIJIII()
	{
	}

	public void JIJJIIJIIJJJJJIJIIJJIJIIJIJJIIJJIJIIIIIJJJIIIJJ()
	{
	}

	private void OnClick(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	private void IIIJIJJJIJIIIJJJIIJJIIIJIIJIJIJJIIJJIJJIJIIIIII()
	{
	}

	private void IJJJJIIIIIIIJIIJIJIIJJJJJIIJIJIIJIJJJJIIIIIJIJI()
	{
	}

	public void IIIJJIIIJIIIJJIJJIJIIIIIIJJIIJJIIJJIJIIJJJIIIIJ(bool IIIIIIIJIIIJJJIJIIJIIIIJIJJJIJIJIIJIJIIIJIJJJII)
	{
	}

	private void JIIIJJJJIIIJJJIJJIJJJJIIIJIIIIIIJIIJIIIIIIJIJII()
	{
	}

	private void Update()
	{
	}
}
