using System;
using UnityEngine;

public class UIPopUp : MonoBehaviour
{
	public GameObject JJJJIJJJJJIJIJJJJIIIIIIJJIIJIIIJIIIIIJJIIJJJJJI;

	public UILabel IJJJJJIJIIIIJJJJIJIIJIJJJIIJIJJJIJJJJJJIIJIJIJI;

	public UILabel JIJIIIIJJIJIJJJIJJJIJJIIJIIIJJJJIIIJJIJJJIIIJJJ;

	public UILabel IJIIIJIJIJJJIJIJIJJIIIJIJIJIJIJJIIJJIJIJJIJJIIJ;

	public UILabel JJJJJJIJJIJJIIJJIIIIIJIJIJIIJJIIJJIIJIJJIJJIJII;

	public Action IIJIJJJIIJIIJJIJJIIJIJIIJIIIIIJJJIJIIIIIJIIJIII;

	public Action IIIIJIJJJIJIIIJJJIIIJIJJIIIIIJIJJJIIIJJIJIJJIJI;

	private static UIPopUp JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void JJIIIIIJJJIIJJJJIIIJJIIIJIIJJIIJJIIJJIIIJIIJJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	public void JIJIIIIJIJIIJJIJJIIJJJIIJIIJIJIIIIIJIJIJIJIJJIJ()
	{
	}

	public static void IJIJJJIJIIIJJIIJIJJJJIJIJIIIJIJJIJJJJJIIIIJIJII()
	{
	}

	private void Start()
	{
	}

	public static void IJJIJIJJJIJJJIIIIJIJIIIJJIIJJIJIJIJJIIIIJJJJIJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	public void IIJJIIJIIJIJIJIIJIJIJJJJIIIJJJIJIIIJIIIIJJIIIIJ()
	{
	}

	public void IJJJIIJIIIJJIJIJJIJIIIJIJIJJIJIJJJIIIJIIIJJIJJJ()
	{
	}

	public static void IJIJJIIIIIJJIIIIJIJIJJJIIJIIIIIJJIIJJIIJIJIIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	public void IJJIIIIJJIIIJJJIJIJIJIIIIIIIIJIJIIIJIIJJIJJJJII()
	{
	}

	public static void JIJJIIJIJJJJJJJJIJJJJJJIJJJIJJIIIIJJIJIIIIJIJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	public static void JIJIJJJJIJJIIJIIIIIIJJIIIJIJIIIIIJJJJIIIJJJJJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	public void IIJJJJJIJJJJJJJIJJJIIJJJIIJJIIJIIJJIJJIJJJJJIII()
	{
	}

	public static void IJJJJJIJJJIJJIIJJJJIJJIJJIJJJJJIIIJIJIJIIIIIJIJ()
	{
	}

	public void OnClickButton2()
	{
	}

	public void IJJJJJIJJIIJJIJJIIJIJJJJIJJJJIJIIJJJIJJJJJIIJJI()
	{
	}

	private void IIJIJIIIIIJJIIIIIJJIJIIIJIJIJIIIJIJJIIIJJJJIIJJ()
	{
	}

	public static void IIIJJIJIIIIJIJIJJIJJJJIIIJJIJIIIIJIJIIJIIIIIJII()
	{
	}

	public static void JJJJJJIJJIIJJIJJIIIIIJJJJJJIJIJIIIJIIJIJJJIJIJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, string JIJIJJJIJJIJJJJIIJIIJJJJIJJIJIJIIJJJIIJJJJJJJII, string IIJIIJIIJJIJIIJIIJIIJJIIJIIIIJJJJIIIJIJIIJIIJJI, Action IIJJJJJJIJIJIIJJJJIIJJIJIJIJJIIIJJIJIIIJJIIIIJI, string IJIJIIJJIIIJJJJJIIIJIIJIIIIIJIIJIIJIJJIIJIJIJJI, Action IIJIJIIIIJIIIJIJJIJJJIIJIIJJJIJJIIJJJIJJJIIJJJI)
	{
	}

	public static void IJJJJJIJIJJIIJIIJIIJIIJIIJJJIJIJIJJJJJIJIIJJIJI()
	{
	}

	public static void IJIJJJIIJJIIJJIJIIIIIIIIIIJIJIIIJIIJJIJIIJIJIJI()
	{
	}

	private void IJIIJJIJJJIJIJJJIIJIJIIJJJJJIJIJJJJIIJIIJIJJJJI()
	{
	}

	public void IJJIJIIIIIIIIJJJJIIJIJJIIJJIIJIJJJJIIIJJIJJJIJI()
	{
	}

	public void OnClickButton1()
	{
	}

	public void JIJJIIIJIIIJIIJIIIIJJJJJIJJJIJIIJIIJJIIIJIIIJII()
	{
	}

	public void JJJJIJJIIJIJIJIJIJJIJJJJJJJJJIIJIJIIIIIJJIIJJIJ()
	{
	}
}
