using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class UIProgressBar : UIWidgetContainer
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IJIIJJIJIJIJJIIIIIJIIIIJJJIIIJJIIIIJJJJJJJIIJII
	{
		LeftToRight = 0,
		RightToLeft = 1,
		BottomToTop = 2,
		TopToBottom = 3
	}

	public delegate void JIJJIJIIJJJJIIJJIJJIJJJJJJJIJIJIJIIIIIJJIIIIJJI();

	public static UIProgressBar JIIJIIIIIIIIIIJIJIIIJJIIJJJIIIJJIIIIIIIIJIJIJIJ;

	public JIJJIJIIJJJJIIJJIJJIJJJJJJJIJIJIJIIIIIJJIIIIJJI JIJIJIIJJJIIIIIJJIIIIJIIIIIIIIJIJJIJJIIJJJJIJJI;

	public Transform IIIIIIJIIIIIJJIIIJIIJJJIIJIIIIIJJJIIIIIIJIIIJJJ;

	[HideInInspector]
	[SerializeField]
	protected UIWidget mBG;

	[HideInInspector]
	[SerializeField]
	protected UIWidget mFG;

	[HideInInspector]
	[SerializeField]
	protected float mValue;

	[HideInInspector]
	[SerializeField]
	protected IJIIJJIJIJIJJIIIIIJIIIIJJJIIIJJIIIIJJJJJJJIIJII mFill;

	[NonSerialized]
	protected bool IIJJIJIJJIJJIJIJIJJJIIIJJJIJJIIIIJJJJIJIJIIJIJI;

	[NonSerialized]
	protected Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	[NonSerialized]
	protected bool JIJIIIIJJIJIIJIIIJJJJJIJIIJJIIJIJJJIIJJIJJJJJJI;

	[NonSerialized]
	protected Camera IIIJJJIIJIIJIJJIJIJIIJJIIJIIJIJIJIIIJIJIJJIIJII;

	[NonSerialized]
	protected float JIIJIJJIJIIIJJJJIJIJJJIJIJIIJJIJJJIJJJJJJJJIIJI;

	public int IIJIIIJIJJIIJJJIIJIJIJJIJJJJIJJIJIJIJIJIIIIIJIJ;

	public List<EventDelegate> JIIJJJJJJJIIJJIJJJIIJJJIIIJJJIIJJJJJIIJJJIJJJII;

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	public Camera IIJIJJJIJJJJJIJJIIJIJIIJJJIIIIIIIJIIJJJIJJJJIJI => IJIIIIJJIJJJIIJJJJJJIJJIIIIIJIJJJIJIIIJJIIJIJJI();

	public UIWidget JIJJIJIJJIIIJJIJJIJJIIIJJIJIIIJJJIIIJIIIIJIJJJJ
	{
		get
		{
			return IJIJJJIJIJIIIJJIIIIJJJIJIJIJIIJJJIIJJIIJIIIIIJI();
		}
		set
		{
			IIIJIJIIJIIJIJJJJJIJJJJIJJJIIJJJIJJIIJJIIJIJJII(value);
		}
	}

	public UIWidget IIJJJIJJIJJIIJJJJIJIJJIJIIIJIIIJIJIJIJJJJIJJIIJ
	{
		get
		{
			return JIIJJIJIIIIJIIIIIIIIJIIJIIJIJIIIJJJJJJJJIIIIIII();
		}
		set
		{
			JJJJJIIJJJJJJJJJIJIIJJJJJIJIJIJIIJJJJJJJIJIIJJI(value);
		}
	}

	public IJIIJJIJIJIJJIIIIIJIIIIJJJIIIJJIIIIJJJJJJJIIJII IJJJIJJIJIIJIJJIIIJJJJJJJIIJJJJJIIIJIIJJJJJIIIJ
	{
		get
		{
			return JJIIJIIIJJIJIIIIJIJIJIIJJIJIIJJIJJJJJIIJJJJIIJI();
		}
		set
		{
			IIJJIJJIIIIJIJIJJIJJJJJIIJIIJIIIIJJIIIJJJIIJIII(value);
		}
	}

	public float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI
	{
		get
		{
			return JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII();
		}
		set
		{
			JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(value);
		}
	}

	public float IJIIJJIIJIJJJIJIJJJIIJJIIIJJJIIIJJJJIIJJIIJIIIJ
	{
		get
		{
			return IJJJJIIJJIJJJJIIIIIJJJIIJJJJJJJIIJJJJIJJJJIIJIJ();
		}
		set
		{
			IIIJIIJIIJJJJIIIJIJJIJJJJJIIIIIJIJIJJIIIJJJIJJJ(value);
		}
	}

	protected bool JJJIIJJIJJJIIJIIIJIIJIIIIJJIIIIJJJIJIJIIJJJJIII => JJJIIJJJIIIJJJIJIIIIJIIJIJJIIJJIJJJIJIJIJIJIJJJ();

	protected bool IIIIIIJJJIJIJIJIIIJJJIIJJIIJIJIJJIJIIIJIJJIIJJJ => JIJJJIIIJJJJIJJIJJIIIJJJJJIIJJIIJIIJJJJJJIIIIII();

	protected virtual void JIIIJIIJIIJIJJJIIJIJIIIJIJIJJIIJJIIJIIIJIIJJIII()
	{
	}
	public float IJJIJIIJJIIJJJJIIIIIJIIJJIIJJIIIJJIIJIJJJIIJIIJ()
	{
		return 0f;
	}
	public IJIIJJIJIJIJJIIIIIJIIIIJJJIIIJJIIIIJJJJJJJIIJII JIJIIIIIJJJJJJIIIJIJIIIIIIJIIIJJIIIIJJJJIIIJIJI()
	{
		return IJIIJJIJIJIJJIIIIIJIIIIJJJIIIJJIIIIJJJJJJJIIJII.LeftToRight;
	}

	protected void JJJJJJIIJJJIIIIIJIJJIJJJJIIIIIIIIJJJIIIJJJJJIJI(Vector3 IIIIIIIJIIIJJIJIJJJJJJJIIIJJJJJIIIIJJIJIIJJIIJI)
	{
	}
	public IJIIJJIJIJIJJIIIIIJIIIIJJJIIIJJIIIIJJJJJJJIIJII IJIJIIJIJIIIJIJIIIIJIIIJJJJJJJIJIJIIIJJJJJIIIIJ()
	{
		return IJIIJJIJIJIJJIIIIIJIIIIJJJIIIJJIIIIJJJJJJJIIJII.LeftToRight;
	}

	public float JIIJIIIIIJJJJJIJJIJJIIJIIJIJIJJIIIIJIJJIJIIJIII()
	{
		return 0f;
	}

	public void IJIIIJJIIIJJIJJIJIJIIIJIJIJIIIJJIIIIIIIJJJIIIII(float JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ, bool IIIIIIIIIJJJIIJJJIJJJIJJIIJJJJIJIJIIJIJIJIJJJIJ = true)
	{
	}

	public IJIIJJIJIJIJJIIIIIJIIIIJJJIIIJJIIIIJJJJJJJIIJII JJIIJIIIJJIJIIIIJIJIJIIJJIJIIJJIJJJJJIIJJJJIIJI()
	{
		return IJIIJJIJIJIJJIIIIIJIIIIJJJIIIJJIIIIJJJJJJJIIJII.LeftToRight;
	}

	protected void JJIJIIJIIIJIIJJJIJIJIJIJIIJIIJIIIJJJIJIJJIIIJII()
	{
	}

	public virtual void JIJJIIIIIJIJJIIIJIIJIIIJIIJIIJIIIIJIIJIIIJJIIJI()
	{
	}

	public void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	protected float JIJIIJJIIJJIIJJJIJJIIJJIJJJIIIJJJIIIIIIJJIIJJJJ(Vector2 JIJIIJIJIIIJIJJJJJIIIJIIIJIJJJJJJIJJJIJJIJJJIJI)
	{
		return 0f;
	}

	protected bool JJJIIJJJIIIJJJIJIIIIJIIJIJJIIJJIJJJIJIJIJIJIJJJ()
	{
		return false;
	}
	public Transform IJIJJJIJIIIJIJIJIJJIIIJJJIJJIJIJJJJJJJJIJJIJIIJ()
	{
		return null;
	}

	protected void IJJJIIJJIJIIIIJIJJJIJIJIJJIIJIJIJIJIIJIJJIIJIJJ(Vector3 IIIIIIIJIIIJJIJIJJJJJJJIIIJJJJJIIIIJJIJIIJJIIJI)
	{
	}

	protected void OnValidate()
	{
	}

	protected void Update()
	{
	}

	public virtual void JJJJJJJJIIIIJIIJJJJJJJIJIJIIJJIIIIIIJJIIIJIJIIJ(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}

	public void JJIJJJIJIJIIIIIIIJJJJIJJJIIIJJIIIIIJJJJJJJIJIJI(float JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ, bool IIIIIIIIIJJJIIJJJIJJJIJJIIJJJJIJIJIIJIJIJIJJJIJ = true)
	{
	}

	public void Start()
	{
	}

	protected bool JIJJJIIIJJJJIJJIJJIIIJJJJJIIJJIIJIIJJJJJJIIIIII()
	{
		return false;
	}

	public float IJJJJIIJJIJJJJIIIIIJJJIIJJJJJJJIIJJJJIJJJJIIJIJ()
	{
		return 0f;
	}

	public virtual void JIIIIIJIIIIJJJJIJIIJIJJIJIIIIIIJJJJJIJJIIJIJIII(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}
	public Camera JJIJJJJJIIJJJJIJJIIIJIIJIJIJJIIIJIJIJIJJJJJIJII()
	{
		return null;
	}

	public UIWidget IJIJJJIJIJIIIJJIIIIJJJIJIJIJIIJJJIIJJIIJIIIIIJI()
	{
		return null;
	}

	public void JJIJIIIIJJJIJIJIIIJJJIJIIJIJJJIJIJJJIIIIJIIJIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIJJIJJIIIIJIJIJJIJJJJJIIJIIJIIIIJJIIIJJJIIJIII(IJIIJJIJIJIJJIIIIIJIIIIJJJIIIJJIIIIJJJJJJJIIJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJJJIIJJJJJJJJJIJIIJJJJJIJIJIJIIJJJJJJJIJIIJJI(UIWidget JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public Transform JIJIJJJJJJJJIJIJIJIIJIJIIJJJIJIJJJIJIIIIIJIJJII()
	{
		return null;
	}
	public float IJJIIIIIIJIJJJIIIIIJIIIIIIJIJJIIJIIIJJJJJJJJJJI()
	{
		return 0f;
	}

	public Camera IJIIIIJJIJJJIIJJJJJJIJJIIIIIJIJJJIJIIIJJIIJIJJI()
	{
		return null;
	}

	public void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	protected virtual void JIJIIIIIJJIIIJIIIIIIJJIIIIIIJJJIIIJJIJJIIJIIJJJ()
	{
	}
	public void JJIJJIIJJJJJJJIIIIIIJJIJJJJJIJIJJIIJIJIIIIIIIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected virtual float JJIJJJIJIIJIIJIIJJIIJJJJJJJJJJIIJJJJJIIJIJIJJJJ(Vector2 JJIJJIIIIJJIIJIJIIIIJJJIJJIJJIIIJIJIIJIIIIJIJIJ)
	{
		return 0f;
	}

	public void IIIJIIJIIJJJJIIIJIJJIJJJJJIIIIIJIJIJJIIIJJJIJJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIJIJIIJIIJIJJJJJIJJJJIJJJIIJJJIJJIIJJIIJIJJII(UIWidget JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public UIWidget JIIJJIJIIIIJIIIIIIIIJIIJIIJIJIIIJJJJJJJJIIIIIII()
	{
		return null;
	}
}
