using System;
using UnityEngine;

public abstract class UIRect : UIMonoBehaviour
{
	[Serializable]
	public class AnchorPoint
	{
		public Transform target;

		public float relative;

		public int absolute;

		[NonSerialized]
		public UIRect rect;

		[NonSerialized]
		public Camera targetCam;

		public void JJIJJJIJIJIIIIIIIJJJJIJJJIIIJJIIIIIJJJJJJJIJIJI(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII, float IIJIIJJIIIIIJJIJIJJIIJJIIIIJJJJIIIJJJIJJJIJJIJI, float JIIJIJIJIIJIJJJIIIJIIIIJIIJJJIJIJIJJIJIJIIJIJJJ)
		{
		}

		public void IJJJJIIIJJIIIIIJJJIJIJJIIJJJJIIJIIIIIIJIIIIJIIJ(float JIIIIJIIJIIJJJIJJJJIJIJIIJIIIIJJIIJJIIJJIJJIJIJ, float JJIIIIJIJIIIJJIIIJJIIJIJIIJJIJIJJJIIIIJIJIJIIIJ, float IIJJIIIIJIIJIJJIJIJIJIJIJJIJJJIJIIJIIJIJIJJJIII)
		{
		}

		public Vector3[] IJJIJJIJJJJIIJJJJJJIJJIJJIIJJIJIIJIJIJIIJIIJIIJ(Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
		{
			return null;
		}

		public void JJIJIIJJIJJIJIJJJJIIJIIJIJIIIIJIIJIJIIIJIIIJJJJ(Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, float JJIJJIIIIJJIIJIJIIIIJJJIJJIJJIIIJIJIIJIIIIJIJIJ)
		{
		}

		public void JIJIIJIIJJJJJIIIJJJIIIIJJIJIIIIIJIIIJJJIIIJJIJJ(Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, float JJIJJIIIIJJIIJIJIIIIJJJIJJIJJIIIJIJIIJIIIIJIJIJ)
		{
		}

		public void JIIJJIIIIIJIIIIIJJJIIIJIJIIJJIIIIJIJJIIIIJIJIJI(Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, float JJIJJIIIIJJIIJIJIIIIJJJIJJIJJIIIJIJIIJIIIIJIJIJ)
		{
		}

		public void IJIIJJIJJIIJIJJJJJJIIJJIJIJJJJJIJJIJIIIIJJJIJJJ(Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, float JJIJJIIIIJJIIJIJIIIIJJJIJJIJJIIIJIJIIJIIIIJIJIJ)
		{
		}

		public void IJIIIJJJJJIIIJIIJIIIJIIJIJIJJIIIIIIJIJIIJJJIIJI(float IIJIIJJIIIIIJJIJIJJIIJJIIIIJJJJIIIJJJIJJJIJJIJI, float JIIJIJIJIIJIJJJIIIJIIIIJIIJJJIJIJIJJIJIJIIJIJJJ)
		{
		}

		public Vector3[] IJIJJJJJJIIJJJJIJIIJJIIJJJIJIJIIIIJJIJIIJIIIIJI(Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
		{
			return null;
		}

		public void IJJJJJIIJIIIIIJJIJJIIJIJJIJJIJJIIJIJJIIIIIJIJJJ(Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, float JJIJJIIIIJJIIJIJIIIIJJJIJJIJJIIIJIJIIJIIIIJIJIJ)
		{
		}

		public AnchorPoint()
		{
		}

		public Vector3[] JJJJJIJJIJJJJIIIIIIIIJIJIJIJIIIJJJIJIIIIIIIJIII(Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
		{
			return null;
		}

		public void IJJIIIIJIJIIJIJJIJJJJIJIJIJIJIIJIJJJJJIIJIJIJIJ(float IIJIIJJIIIIIJJIJIJJIIJJIIIIJJJJIIIJJJIJJJIJJIJI, float JIIJIJIJIIJIJJJIIIJIIIIJIIJJJIJIJIJJIJIJIIJIJJJ)
		{
		}

		public void JIJJJIJIIJIJJIJIJIJIJJJIJJJJJJIIIIJIIJIIIIJIJII(float IIJIIJJIIIIIJJIJIJJIIJJIIIIJJJJIIIJJJIJJJIJJIJI, float JIIJIJIJIIJIJJJIIIJIIIIJIIJJJIJIJIJJIJIJIIJIJJJ)
		{
		}

		public void IIIIIIJIJJIJIJIJIIIIIIIJIIIJIIJIIIIJJJIIIIIIIII(Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, float JJIJJIIIIJJIIJIJIIIIJJJIJJIJJIIIJIJIIJIIIIJIJIJ)
		{
		}

		public void JJJIJIJJIJIIIIIJJIIJIIIIIIJJJJIJIIIJIJIJIIJIJII(Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, float JJIJJIIIIJJIIJIJIIIIJJJIJJIJJIIIJIJIIJIIIIJIJIJ)
		{
		}

		public void IJIJJIIJIJJJIIIJJJIIJIIJJJJJJIJJIIIIIIIJJJIJJJJ(float IIJIIJJIIIIIJJIJIJJIIJJIIIIJJJJIIIJJJIJJJIJJIJI, float JIIJIJIJIIJIJJJIIIJIIIIJIIJJJIJIJIJJIJIJIIJIJJJ)
		{
		}

		public void IJJJIJIIIIJIJJJJJIIJJIIIJJJJJIJIIJIIJIJIIIIIJIJ(float IIJIIJJIIIIIJJIJIJJIIJJIIIIJJJJIIIJJJIJJJIJJIJI, float JIIJIJIJIIJIJJJIIIJIIIIJIIJJJIJIJIJJIJIJIIJIJJJ)
		{
		}

		public Vector3[] JIJJJJJJJJIIIJJJIIIIIJJJJJJJIIIIIIIIJJJIIJJJIJI(Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
		{
			return null;
		}

		public void JJIJJJIJIJIIIIIIIJJJJIJJJIIIJJIIIIIJJJJJJJIJIJI(float IIJIIJJIIIIIJJIJIJJIIJJIIIIJJJJIIIJJJIJJJIJJIJI, float JIIJIJIJIIJIJJJIIIJIIIIJIIJJJIJIJIJJIJIJIIJIJJJ)
		{
		}

		public Vector3[] JJJJJJJJJJJJJJIJIJJJIJJIJIIIJJIJIJIJIJIJJJJJIIJ(Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
		{
			return null;
		}

		public void IIJJIIIJIJJJJJIIIJJIJIJIIIJIIIIJJIJJJJIIJIJJJJJ(Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, float JJIJJIIIIJJIIJIJIIIIJJJIJJIJJIIIJIJIIJIIIIJIJIJ)
		{
		}

		public void JJJIIIJIJIJIJIIJJIJJIIIJJIJIJJJIIJJIJJJIJJIIJII(float JIIIIJIIJIIJJJIJJJJIJIJIIJIIIIJJIIJJIIJJIJJIJIJ, float JJIIIIJIJIIIJJIIIJJIIJIJIIJJIJIJJJIIIIJIJIJIIIJ, float IIJJIIIIJIIJIJJIJIJIJIJIJJIJJJIJIIJIIJIJIJJJIII)
		{
		}

		public void IJJJJIIIJJIIIIIJJJIJIJJIIJJJJIIJIIIIIIJIIIIJIIJ(float JJIJIJIJIIIJIIIJIIIJJIJJJIIJIJJJJIIJIJIIIJJIIII, float IJIJJJIIIIJIIJIJIJIIIIJIJJIIIJJJIIJIIJIJIJJIJII, float JIIIIIJJIJJJIIIJIJIJIJIJIIIJJJJJJJIIJIIJJIIJJII, float JIIIIJIIJIIJJJIJJJJIJIJIIJIIIIJJIIJJIIJJIJJIJIJ, float JJIIIIJIJIIIJJIIIJJIIJIJIIJJIJIJJJIIIIJIJIJIIIJ, float IIJJIIIIJIIJIJJIJIJIJIJIJJIJJJIJIIJIIJIJIJJJIII)
		{
		}

		public Vector3[] IJIJIIJJJJJJIJJJJJJJJJIJIJJIIIIIJIIIJIIIIJIJIJI(Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
		{
			return null;
		}

		public void JIIIJIIJJJJJJJIJIJIJIIIIIJJJIJJIIJJIIJJIIJJJJJJ(Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, float JJIJJIIIIJJIIJIJIIIIJJJIJJIJJIIIJIJIIJIIIIJIJIJ)
		{
		}

		public void IJJIIJIJJJIIIJIJIIJIJJJJIIIIIJJIIJIJIIIJJIJIIJJ(float IIJIIJJIIIIIJJIJIJJIIJJIIIIJJJJIIIJJJIJJJIJJIJI, float JIIJIJIJIIJIJJJIIIJIIIIJIIJJJIJIJIJJIJIJIIJIJJJ)
		{
		}

		public void IIIIIIIIIIJIIJIJIIJIJJJJIIIIIIIJIIIJIJJJIJIIIJJ(Transform IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI, float JJIJJIIIIJJIIJIJIIIIJJJIJJIJJIIIJIJIIJIIIIJIJIJ)
		{
		}

		public AnchorPoint(float IIJIIJJIIIIIJJIJIJJIIJJIIIIJJJJIIIJJJIJJJIJJIJI)
		{
		}
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IIJIIJIIIIIIIJIJJJJIIIJIIJJIIIJJIJJIJIJIIJIIJJJ
	{
		OnEnable = 0,
		OnUpdate = 1,
		OnStart = 2
	}

	public bool IIJJIIJJIIJIJJIIIJJIJIJJJIIIIIIIJIIIIJJIJIJIJII;

	public bool JJIIIJIIJIJJIIIJIJJJJIIIJJIJIJJJIIJIIJJIIIIJIIJ;

	public AnchorPoint IJJIJJJJJJIJIJIIJIIIJJIIIIJJJIIJJJJJJJIJIIIIIIJ;

	public AnchorPoint IIJIIJJJIIJIJIJJIIJIJIJIIIJJIJJJIJIJIJJIIJIJIII;

	public AnchorPoint JIIJJJJJIJJJJIJJJJIIJIJIIIIJJJIIIJIJJIIIIJIIJIJ;

	public AnchorPoint JJIJJIIIJJJIIIIIJJJJIJIIIJJJIIJIJJJJIIJJJIIIIIJ;

	public IIJIIJIIIIIIIJIJJJJIIIJIIJJIIIJJIJJIJIJIIJIIJJJ IIIIJIJIJJIJJIIJJJJIJIIJIIIIJJIJIJJJIJJIIJJIIIJ;

	[NonSerialized]
	protected GameObject IJIJJIIIJJJIIJJIIIIJIJJIJJIJJIIIIIJJIJJIJIIJJJJ;

	[NonSerialized]
	protected Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	[NonSerialized]
	protected global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<UIRect> IIIJJIJJIJJJIJIJJIIJJIJJIIIIIIJJJIIIJIJIJJIJIJI;

	[NonSerialized]
	protected bool JIJJIIJJIIJJJIIIJJIIJIIJIIJIIIIJJIJJJJIIIJJJIJJ;

	[NonSerialized]
	protected bool JIIJJJJJJJJIJJJIIIIIJIIJJIJIJIJIJIIJIJIJJJJIJIJ;

	[NonSerialized]
	private bool IIIIJIJJJIJJIIIJJIIIIJIJIIJIJJIIJIJJIIIJIJIJIJI;

	[NonSerialized]
	private int IIIJJIIJIIJIJIJIJJIIJJJIIIIIIIJIJIJIJJIJIIIIIJJ;

	[NonSerialized]
	private bool IIIIJIIIJIJIJIIIJIIIIJIJJJJJJIIIIIJJJIIIJIIJJII;

	[NonSerialized]
	private UIRoot JJJJIIJIIJIIJIIIJIJJJIJIJIIIJIIIIIJJJJJJIJJIJII;

	[NonSerialized]
	private UIRect IJIJIIJIIJJIIIIJIIIJJIIIIJIJIIIIIIJIIJJIJIIJIJI;

	[NonSerialized]
	private bool IIJJIJIIJIIIJIJIIIJJJIJIJJJJJIJIIIIJIIIIIIJIJIJ;

	[NonSerialized]
	protected Camera IIIJJJIIJIIJIJJIJIJIIJJIIJIIJIJIJIIIJIJIJJIIJII;

	protected bool IIJJIJIJJIJJIJIJIJJJIIIJJJIJJIIIIJJJJIJIJIIJIJI;

	[NonSerialized]
	public float IJJJJIJJIIIIIJJJIIIIIIIJJIIJIIIJIIIJIJIIJIJIIJI;

	protected static Vector3[] IJJIIIJJIJIJIJIJJJJIJIJIJIIJIIIIIJJIIIJJIIIJJIJ;

	public bool IJJJJIIJJIJIIJIIIJJIIJIIIIIIJJIIIJJIJJIIJIJIIJI;

	public GameObject JIIIJIJJJIJJIJIJIIIJJJJIIJIJJJIIIJJIIIJIJIIJIII => JIJJIIJIIIJIJIIJJIJIJJJIIIJIIIJJIIIJIJJJIIIJJJJ();

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	public Camera JIJJJJIIIJIIIJJIJIIJJJIIJJIJJIJJJIJJIJJJJIIIIJI => JJJJIIIJJJIJJJIJIJIJJIJIJIIIJJJJIJJJJJJJIIJJIII();

	public bool IIJJIIJIIIJJJIIIJJIIJIJIIIIIIIJIJJIJIJJJIIIIIII => IIIIIJIJIJJJJIJJJIJJJIJIJJIJIJJIIIIJJIJIIIIJIJI();

	public virtual bool IIJIIIJJIIJJJJIJJJJJIJIIJIIIIIIJJJJJIJJIIJIIJII => IIJIIIIIJIIJJJJIJJJJJIJIIIJJIIIIIJIJJJIIIJJJJJI();

	public virtual bool JJIJJIIIIJIIJIJIJJIJJIJIIJIJJJIJIIJJIJIIIIJIJJJ => JJJJJJJIJIJJJJJJIIJIJJIIJJJJIIJJIIIJJJIJJJIJJIJ();

	public virtual bool IJIJIIIJIJJIIJIJIIJJIIJIIIJIJIIJJIJIJJIIJIJIJII => JIIIJJIIIIIJIJIIIIIJJIIIJJIJJIIIIJIJIIIIJIJJJII();

	public UIRect IJIJIJIJIJJIJIIIIIIJJIIJJJIJJJJIJIIIJIJIJIJJJJI => JIIIIIJIIJIIJIIIIIIIIJJJIJJJIJIIJIIJIIJIJJIIIII();

	public UIRoot IIIIJIIIJIJJJJIIJJJIIIIIIJJJJJIJJJJJJIIIJIIJIJI => JIIIIJJIIJIIJJJIJIJIJIIIIIIIJJIIJIIJJJIJJJJJJJI();

	public bool IIJJJIIIIIJJIJJJJJIIJIJJJIIJIJIIJIJIJJJJJJIJIII => JJIJJIJJIIJJIIJIJJIJIIJIIIIJJIJIJIIJIJIJIIJIJJI();

	public abstract float IJIIJJIIJIJJJIJIJJJIIJJIIIJJJIIIJJJJIIJJIIJIIIJ { get; set; }

	public abstract Vector3[] IIJJJJIIIJIJIIJIJIIJJIIIIJIJJIIJJIJIIIIIIJJIIII { get; }

	public abstract Vector3[] JIIIIIIIJIJJJJIJJIJIJIJJIIIIJJIIIJIIIJIJIJJJJJI { get; }

	protected float JJIIJIJIIJJJJIIJIJJIIJJJJIJJIIJIIIIJJIIJJIIIJIJ => IJIJIJJIIIJJIIJIIIJIJJJIIJJIIJIJJJJJIJIIIIIIIIJ();

	public GameObject JIJJIIJIIIJIJIIJJIJIJJJIIIJIIIJJIIIJIJJJIIIJJJJ()
	{
		return null;
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}

	public Camera JJJJIIIJJJIJJJIJIJIJJIJIJIIIJJJJIJJJJJJJIIJJIII()
	{
		return null;
	}

	public bool IIIIIJIJIJJJJIJJJIJJJIJIJJIJIJJIIIIJJIJIIIIJIJI()
	{
		return false;
	}

	public virtual bool IIJIIIIIJIIJJJJIJJJJJIJIIIJJIIIIIJIJJJIIIJJJJJI()
	{
		return false;
	}

	public virtual bool JJJJJJJIJIJJJJJJIIJIJJIIJJJJIIJJIIIJJJIJJJIJJIJ()
	{
		return false;
	}

	public virtual bool JIIIJJIIIIIJIJIIIIIJJIIIJJIJJIIIIJIJIIIIJIJJJII()
	{
		return false;
	}

	public UIRect JIIIIIJIIJIIJIIIIIIIIJJJIJJJIJIIJIIJIIJIJJIIIII()
	{
		return null;
	}

	public UIRoot JIIIIJJIIJIIJJJIJIJIJIIIIIIIJJIIJIIJJJIJJJJJJJI()
	{
		return null;
	}

	public bool JJIJJIJJIIJJIIJIJJIJIIJIIIIJJIJIJIIJIJIJIIJIJJI()
	{
		return false;
	}

	public abstract float IJJJJIIJJIJJJJIIIIIJJJIIJJJJJJJIIJJJJIJJJJIIJIJ();

	public abstract void IIIJIIJIIJJJJIIIJIJJIJJJJJIIIIIJIJIJJIIIJJJIJJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI);

	public abstract float IJJJIJJIIIJJIJJJJJIIIJIIIJJIIJIJIJIIIJIIJJIJJII(int JJIJJJJJJIJIIIIIJJIIJIIJJIJIJJJIIIJIIJJJJJIIIIJ);

	public abstract Vector3[] JIIIIIIIIIJIIJJIJJJJJJJIIIIIJJIIIJJJJIJIJIIJIII();

	public abstract Vector3[] JIJJIJIJIJIIJJJJJIJIJIIIIJIIJIIJJJJJJJJIIJIJJJI();

	protected float IJIJIJJIIIJJIIJIIIJIJJJIIJJIIJIJJJJJIJIIIIIIIIJ()
	{
		return 0f;
	}

	public virtual void IIJJIJJJIIJJJJJIIJJIIJIJIIJJJIJIIJJIJJIJJIJJJJJ(bool JJJJIJJJIJIJJJIJIIJIIJJIJIJIIJIJIIIIIJIJJIJIIJJ)
	{
	}

	public virtual Vector3[] JJJJJIJJIJJJJIIIIIIIIJIJIJIJIIIJJJIJIIIIIIIJIII(Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
	{
		return null;
	}

	protected Vector3 JJJJIJJIJIJIIJIJJIJIIIIIIIIJIJJIJIJJJJIIIJJJJJI(AnchorPoint JIIIJIIJJJIJIJIJIIIJIIIJIIIIJJJJJIJJJIJJJIIIIIJ, Transform JIIIIIJJJIIIJJJIIIJJJJIJJIJIIJIIIJJIJIJIJJIJJJJ)
	{
		return default;
	}

	protected virtual void OnEnable()
	{
	}

	protected virtual void JIIJJJJIIIIIJJIJIIIIJIIIIJJIJJJJJIJJJIJIJJJJJJJ()
	{
	}

	protected virtual void OnDisable()
	{
	}

	protected virtual void Awake()
	{
	}

	protected void Start()
	{
	}

	public override void nUpdate(int JIJIJIJJJJIJIJJJIJJIIIIJIIIIIJJJJIIIJJJJJJIIIJI)
	{
	}

	protected void IJIIIIJJIJIIIIIJJIJIIIJJIJIJIJIIJIJIIJIIIIJJIJI(int IJIJIIIJIJIIJIIJIJJJJIIJJIIJIIIIIIIIIJJJJJIIJJI)
	{
	}

	public void JIIIJIJIIJIJJIJJIIJIJJJIJIIJIIIIIJIIIIJIJIIIJII()
	{
	}

	protected abstract void JJJIJIJIJIIJJIJIIJJIIJJIIIJJJIIJIJJIIJJJJIJIIII();

	public void IJIIJIIJIJIIJIIIJIJIIJIIJJJJIIJIIJJJJIIJIIJJJIJ(Transform JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ)
	{
	}

	public void IJIIJIIJIJIIJIIIJIJIIJIIJJJJIIJIIJJJJIIJIIJJJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	public void IJIIJIIJIJIIJIIIJIJIIJIIJJJJIIJIIJJJJIIJIIJJJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, int JIJIIIIJJIIIIIJJJJJJIIIIJJIIIIJIIIIJJIJJJIIIIII, int IIIJJIIIIJIIIJIIJJIJIIJIIIJIIJJIIIJJJIIJIJJJJIJ, int IJIIJJJIIJIIJJJIIIJIIIJIJIIJJJJIIJJIIIJJJIJIIII, int IIIJIJJIIIJJIIIIIIJIJIJJIIJIIIJIJIIJIJIIJJJIIJJ)
	{
	}

	public void IJIIJIIJIJIIJIIIJIJIIJIIJJJJIIJIIJJJJIIJIIJJJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float JIJIIIIJJIIIIIJJJJJJIIIIJJIIIIJIIIIJJIJJJIIIIII, float IIIJJIIIIJIIIJIIJJIJIIJIIIJIIJJIIIJJJIIJIJJJJIJ, float IJIIJJJIIJIIJJJIIIJIIIJIJIIJJJJIIJJIIIJJJIJIIII, float IIIJIJJIIIJJIIIIIIJIJIJJIIJIIIJIJIIJIJIIJJJIIJJ)
	{
	}

	public void IJIIJIIJIJIIJIIIJIJIIJIIJJJJIIJIIJJJJIIJIIJJJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float JIJIIIIJJIIIIIJJJJJJIIIIJJIIIIJIIIIJJIJJJIIIIII, int JIIIJJJJJJJIIJIIIJJJIJIIIIIIJIIIJJIIJJJJJIIJJJI, float IIIJJIIIIJIIIJIIJJIJIIJIIIJIIJJIIIJJJIIJIJJJJIJ, int JJJIJIIJJJIIJIJIJIIJJIJJJJIJIJJJJIJJJJIIIIIJIII, float IJIIJJJIIJIIJJJIIIJIIIJIJIIJJJJIIJJIIIJJJIJIIII, int IIIJIIJIIIIJIJJJJIJIIIJJJJIIJJIJJJIJJIJIIJJJIJI, float IIIJIJJIIIJJIIIIIIJIJIJJIIJIIIJIJIIJIJIIJJJIIJJ, int JIIJJJIIJIJJIJIIJIJJIIIJIJJJIIIIJIJIJJIIIIIJJJI)
	{
	}

	public void IJIIJIIJIJIIJIIIJIJIIJIIJJJJIIJIIJJJJIIJIIJJJIJ(float JIJIIIIJJIIIIIJJJJJJIIIIJJIIIIJIIIIJJIJJJIIIIII, int JIIIJJJJJJJIIJIIIJJJIJIIIIIIJIIIJJIIJJJJJIIJJJI, float IIIJJIIIIJIIIJIIJJIJIIJIIIJIIJJIIIJJJIIJIJJJJIJ, int JJJIJIIJJJIIJIJIJIIJJIJJJJIJIJJJJIJJJJIIIIIJIII, float IJIIJJJIIJIIJJJIIIJIIIJIJIIJJJJIIJJIIIJJJIJIIII, int IIIJIIJIIIIJIJJJJIJIIIJJJJIIJJIJJJIJJIJIIJJJIJI, float IIIJIJJIIIJJIIIIIIJIJIJJIIJIIIJIJIIJIJIIJJJIIJJ, int JIIJJJIIJIJJIJIIJIJJIIIJIJJJIIIIJIJIJJIIIIIJJJI)
	{
	}

	public void IJJJJJIIJJIJIJIIIJIIJJJIJJJJIIJJIIJIJJIIIJIIIJJ(int JIJIIIIJJIIIIIJJJJJJIIIIJJIIIIJIIIIJJIJJJIIIIII, int IIIJIJJIIIJJIIIIIIJIJIJJIIJIIIJIJIIJIJIIJJJIIJJ, int JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, int JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
	}

	public void JIJIJJIJIIIIJIIJJJIIIJJIIJIIIJJJJJJIJIJJIJIIIII()
	{
	}

	public void IJJJIJJJIJJIIJJJJIIJJIJIJJIIIIIJIIIJJIJIIJJJIJI()
	{
	}

	public abstract void IIIJIJIIIJIIJJIJIJIJJIIJJJJIIJIIJIJIJJJJIJJJJJJ(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII);

	private void JJJJIIIIJIJIIJJIJJJIIJJJJIJJJJIIIJJIIIJIIJIJIII(AnchorPoint IIJJJIJJJIJJJJJJIJIJIIIIIJIJIJIIJJIJIIJJJJIIJJJ)
	{
	}

	public virtual void IJJIJIJJJJIJIJJIJJIJJJIJJJIIJJJIJIJIJIIIJJIJIII()
	{
	}

	protected abstract void JIIIJIIJIIJIJJJIIJIJIIIJIJIJJIIJJIIJIIIJIIJJIII();

	protected virtual void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII()
	{
	}
}
