using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class UIRoot : MonoBehaviour
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JJIJIIJJJIIIIIIIIJJIJJJJIJJIIJJJJJJJJIJIIIIJJJI
	{
		Flexible = 0,
		Constrained = 1,
		ConstrainedOnMobiles = 2
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IIJJJJIJJJIJIJIIJJIJJIIIIIIIIJJJIIIIIIIJJIIIIJJ
	{
		Fit = 0,
		Fill = 1,
		FitWidth = 2,
		FitHeight = 3
	}

	public static List<UIRoot> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ;

	public JJIJIIJJJIIIIIIIIJJIJJJJIJJIIJJJJJJJJIJIIIIJJJI JIIJIIJIIIJJJIIIJIIIJIIIJJIIJIIIIJJJJJIIIJIJJJJ;

	public int IJIIIJJJJJJIJJJJIIIIJJJJJJJIJJJJJJIJJJIJJIIIIJI;

	public int JIIIJIJJJJJJIJIJIJJIJJJJIIIIIIIJJIJIIIJJJJJIIII;

	public int JIJIJIJJIJIJJJIIJJIJIJIJJIIJJJJIJJJJJJIJIIJIIII;

	public int JJJIIIIIIIIIIIIJIIIJJIIIIIJJIIJIIIJJIIIJJJIIIJJ;

	public bool IIJIIJIJJJJIJIJJIIJJIJJJIJJIIJIIIJJJIIIIJJJJIJI;

	public bool JJJJJIJJIJIIJIIJJIJIJIIJJIJJIIIJJJIIJJJJIIIIJJI;

	public bool JJJJJJJJJIJIIIJJJIJJJIIIIJJIJIIJJIJJJJJIIIJIIIJ;

	public bool IIJIJIIIJIIJJJJJJIIJJIJJIJIJIJJJJJJJJIJJJJIIIJJ;

	private Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	public IIJJJJIJJJIJIJIIJJIJJIIIIIIIIJJJIIIIIIIJJIIIIJJ JJJJJJIJIJIJIIJIJIJJIJJJJJIJJJIIJJJIIJJJJJIJJJJ => IJJIIIIIIIJJJIIIJJJIIJJJJIJJJIJJIIJIJJIIJJIIIJI();

	public JJIJIIJJJIIIIIIIIJJIJJJJIJJIIJJJJJJJJIJIIIIJJJI JIJJIIJJIJJIIIJIIIIIJJIJIIJJIJJJIJIIJIJJJJIJJJI => IIIIIIIIJJIIJIIJJIIIIJIIJJJIIJJJJIJJJIIJIJJIIJI();

	public int IIJJIIJJJJJIIIIJJIJIJJIJIIIIJJIIIIJJJIJJIJIJIII => IJJIJIJJJIIIIIIJJJIJJJJJIIJIIJJIJJJJJJJJIIJIIJJ();

	public float IIIJIJIIIJJIJIJJJJJJJIJJJIIJJJJJJJJJIIIJJIJIJIJ => IJJJJIJJIJJIIJJJJJJJIJIIIJJJIIIIJIJJJIJJJJJJJII();
	public float JJJJIJJIIIIJJJJIIIJJJJIJJIJIIIJJJIIJJIJJIIJJJJJ()
	{
		return 0f;
	}

	protected virtual void OnDisable()
	{
	}

	public float IJJJJIJJIJIIIIIIJJJIJIJIIIIJIJIJJIIJIIJJJJJJJJI(int JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
		return 0f;
	}

	protected virtual void IIJJIIJJJIIJIJJIIIIJIIJIJIIIIIJIJJJJJIJJIIIIIJI()
	{
	}

	public void IJJJJJIJJIIJJIIJIJJIJIJIIJJJIJIIIIJJJJIJJIIIJIJ()
	{
	}

	protected virtual void JJJJJJIIJJIJIIJIJJIIJIJIJJJIIJIIJJJIIJJIJJJIIII()
	{
	}

	protected virtual void IJIIIJIJJIIJJIJIJJIIJIIIJJJIIJJIIIJIJIIIIIJJJII()
	{
	}

	private void IIIJIIJJJIIIIIJJJJIIJJIIJJJIIIJIIJJIIJIJJIJIJIJ()
	{
	}

	protected virtual void IJIJJJIIJIIJIJJIJIJIIIJIJIJJIIIIIIJJIJIJIJIJIJJ()
	{
	}

	public float IIJIIJIIIIJIJJIIIIIIIJIIJJIJJIIJJJJIJJJIJIIIIJJ(int JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
		return 0f;
	}

	public static float JIIIJIIIJJIJJIIJIJIIIIIIJIJJJJIIJJJIIIJIIJJIIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return 0f;
	}

	public static float IJJJJIJJIJIIIIIIJJJIJIJIIIIJIJIJJIIJIIJJJJJJJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
		return 0f;
	}
	public float JIIJJIIJIJJJJJJIIJIIJJJJJJJJIJJJIJIJIIIIIIIIJII()
	{
		return 0f;
	}

	public void JIIIJJIIJIJJIIIIJIJIJJJIIIIIIJIJIJJJJIIIIIIJJJI()
	{
	}

	public void IJJIIJJIJJJIIIIJIJJJJJJJIIJIJIIJIIJJJIJJJJIJIJI()
	{
	}

	private void JJIJJIJJJJIIIJJJJJJIJJIJJIIIJIIIIJIJIIJJJIIIIJI()
	{
	}

	public void IJJJJJIJJIIJJIIJIJJIJIJIIJJJIJIIIIJJJJIJJIIIJIJ(bool IIIIJIJIJJIJJIIJJJJIJIIJIIIIJJIJIJJJIJJIIJJIIIJ)
	{
	}

	protected virtual void Awake()
	{
	}

	protected virtual void Start()
	{
	}

	public JJIJIIJJJIIIIIIIIJJIJJJJIJJIIJJJJJJJJIJIIIIJJJI IIIIIIIIJJIIJIIJJIIIIJIIJJJIIJJJJIJJJIIJIJJIIJI()
	{
		return JJIJIIJJJIIIIIIIIJJIJJJJIJJIIJJJJJJJJIJIIIIJJJI.Flexible;
	}

	protected virtual void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	protected virtual void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	public float IJJJJIJJIJJIIJJJJJJJIJIIIJJJIIIIJIJJJIJJJJJJJII()
	{
		return 0f;
	}

	public static void IJIIIIJJJJIIJIIIJJIJIIJIIIJJIIIJJIIJJIIIJIIIJJJ(string JJJJIJIJJIIIIIIIIIIIJJIIJIIJIJJJIJJIIJJIJJJJIJI, object JJJIIJJIJIJJIJJJIJIJIIJIIIIIJJIJJJJJIJJJJIIIIJJ)
	{
	}

	protected virtual void OnEnable()
	{
	}

	protected virtual void JJJIIJJIJIJJJJIIJJJJJIJJIIIJJJIJIJJIIIJIIJIIJII()
	{
	}
	public JJIJIIJJJIIIIIIIIJJIJJJJIJJIIJJJJJJJJIJIIIIJJJI JJJJJJJJIIIJIJJIIJJIJJIIJJIJJJJIJIIIJIIIIIJIIII()
	{
		return JJIJIIJJJIIIIIIIIJJIJJJJIJJIIJJJJJJJJIJIIIIJJJI.Flexible;
	}
	public int IJJIJIJJIJJJIJIJJJIJJJIIJJIIIJJJIJIJIJIIIJIJJII()
	{
		return 0;
	}

	public IIJJJJIJJJIJIJIIJJIJJIIIIIIIIJJJIIIIIIIJJIIIIJJ IJJIIIIIIIJJJIIIJJJIIJJJJIJJJIJJIIJIJJIIJJIIIJI()
	{
		return IIJJJJIJJJIJIJIIJJIJJIIIIIIIIJJJIIIIIIIJJIIIIJJ.Fit;
	}

	public int IJJIJIJJJIIIIIIJJJIJJJJJIIJIIJJIJJJJJJJJIIJIIJJ()
	{
		return 0;
	}

	public void JJIIJJJIJIJIIIIJJJJJJJIJJIJIJIIIJJJJJIJIIIIIJJJ(bool IIIIJIJIJJIJJIIJJJJIJIIJIIIIJJIJIJJJIJJIIJJIIIJ)
	{
	}

	public static void IJIIIIJJJJIIJIIIJJIJIIJIIIJJIIIJJIIJJIIIJIIIJJJ(string JJJJIJIJJIIIIIIIIIIIJJIIJIIJIJJJIJJIIJJIJJJJIJI)
	{
	}

	protected virtual void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}
	public JJIJIIJJJIIIIIIIIJJIJJJJIJJIIJJJJJJJJIJIIIIJJJI IJIIIJJIJJJIJJIJIIIIJJJIIIIIJJIIJIIJIJJJJJIJIJI()
	{
		return JJIJIIJJJIIIIIIIIJJIJJJJIJJIIJJJJJJJJIJIIIIJJJI.Flexible;
	}
}
