using UnityEngine;

public class UISavedOption : MonoBehaviour
{
	public string JIJIIIJIJIIIIJIJIJIIIJIIIIJJJIJIJIJIIJIIJIIJJJI;

	private UIPopupList IJIIJIJJJIIJIIIJJIJIIJIJIIJIIIJJJJIIJJJIJIIJJJI;

	private UIToggle IJJJJJIJJJIJIIIIIJJIJJJIJIIJJJJJJIJIIIJJIJIIJJI;

	private UIProgressBar JIIIJJJJIIJIIIJJIJJIIIIJIIJIIJJIIJIIJJIIIIIIJJI;

	private string IIIJIJJJIIIIJJIIJJJIJJJIIIJJIJIIJJIJIJJJIIJIJIJ => IIJIJIIJJIJJJIJJJJJIJJJIJJIJIIIJIJJIJJIJIIIIJII();

	public void JJJJJJIIJIIJJJJIJIIIIIJIJIJIIIIIJJIIIIJIIIIJJIJ()
	{
	}

	public void JJIJIIIJJJIIIJJJJIIIJIJIJJIIJIJJIIIJJJJJIJJIJIJ()
	{
	}

	public void JIIIJJJIIJIJJJJJIIJIIIJJIIIIIJIJJJIJIJIIJIJJJJJ()
	{
	}

	private void OnEnable()
	{
	}

	public void JJJJJJIJIJJJJIJIIIIIJJJJIIJIIIJJIIIIIIJIIIJJIII()
	{
	}

	public void IIIIIJJIIIJIJIJIJIJJJJIJIJJIIJIIJJIJJIJJIIJIIIJ()
	{
	}

	private void IIIJIJJJIIJIIIJIIJJJIJJIJIIJJJIJJIIIJJJJIIJJJIJ()
	{
	}

	public void IJJJIJJJJIIJIIIJJIIIJJJIIJIIIJJJJJJIJJJIJIIJJIJ()
	{
	}

	private void JIIJIIIIJIJJJIIIIIJJIJJJJJJIIIJIIJJIJIJIJIJIIIJ()
	{
	}

	public void JIJIIJJIJIJJJIJIIIIJJIJJJJJJJJJJJIIJIJJJJIJJIII()
	{
	}

	private void JJJJJJIIJJIJIIJIJJIIJIJIJJJIIJIIJJJIIJJIJJJIIII()
	{
	}

	private void Awake()
	{
	}

	public void JIJJIIJIJIJIJJJIJJIIIIJIIJIIIJJJJJJIJIJJIJJJJJI()
	{
	}

	private string IIJIJIIJJIJJJIJJJJJIJJJIJJIJIIIJIJJIJJIJIIIIJII()
	{
		return null;
	}

	public void IIIJJIJIJJJJJJJIJJJIJIJIIJJIIIIIIIIJIJIJJIJIIIJ()
	{
	}

	private void JJIJJJIIJIIJIIJJJJJIIIIIJIIJIIIJIIJIJIJJIJJIJIJ()
	{
	}

	public void JIIIIJIJIJIJIIJIJJJIIJIIIJJJJIJJJIIIJJIIIJJJIJJ()
	{
	}

	private void OnDisable()
	{
	}

	public void JJIIIIIIJJIIJJIJIJIJIIIIJJJIJJJIJIIIIIJJIIIIJII()
	{
	}

	private void JIIIIIJIJJIIIIIIIJJIIJJJJIIJJJJJJIIJIJJJJIIIIJJ()
	{
	}
}
