using System;
using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class UIScrollView : MonoBehaviour
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JIJIIIJIIJJJJJJJIIIJIJIIJJJIIJIIJJJIJIJIIJJJIIJ
	{
		Horizontal = 0,
		Vertical = 1,
		Unrestricted = 2,
		Custom = 3
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IJJJIJJIIJIIJJJJIIJIIJIIJJIIIIIIJIIIJJJJJIJIIIJ
	{
		None = 0,
		Momentum = 1,
		MomentumAndSpring = 2
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IIIJIIJJJIJJJJIJIJIIIJIJJIIIIIJIJJIIIJIJIJJIIII
	{
		Always = 0,
		OnlyIfNeeded = 1,
		WhenDragging = 2
	}

	public delegate void JIJIIJIJJIIJJJIJIIJIIJIIIJJIIIJJIIIIIIJIJJIJIJI();

	public static global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<UIScrollView> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ;

	public JIJIIIJIIJJJJJJJIIIJIJIIJJJIIJIIJJJIJIJIIJJJIIJ IJJIIIJIJIIIIIJJJIJIJIIIJIIJIIJJIIJIIJJIIJJIIII;

	public IJJJIJJIIJIIJJJJIIJIIJIIJJIIIIIIJIIIJJJJJIJIIIJ JIIJJJJIJIJIJIJJJJJJIJJIJIJJIIJIJJJJJIIIIJJJIJJ;

	public bool IIIJIIJIIIIIIJIIJJJJJJIJIIJJJJJIJIJIIJIIIIJJJIJ;

	public bool IJJJJIJJIIJIIJIJJJJJIJIIJJIIJJJJJIIJIIIJJJIIIJJ;

	public bool IIJIIJIIJIIJJJIJIIIIJJJJIJJJJJJJIIJIIJIJIIIJIJJ;

	public bool IJIIIJJIIJIJIJIJIIJIJJIJIIJJJJIIJIJJJJIIJIJJIIJ;

	public bool JJIIJIJIJJJIJJJJIJIIJJJIJJIJIIJJJIJJJJIJJIJIJJJ;

	public float IIIJIIJJIJJJIJJIJIIIIIJJIJJIJJJIJJJJJIIJJJJJJIJ;

	public float IIIIIIJIIJIIIJIIIIIIJJIIIJJIIJJIJJJJIIIIJIIJJIJ;

	public float IIJIIIJJJJIIIIJJJJIIIIJIIIIIJJIIJJJIJIJJJIJIJJI;

	public UIProgressBar JIJIIJIIJIIJIIIIIIJIJIIJJIJIJJIIJJJJJJIIIIJJIJJ;

	public UIProgressBar IJIIJIJIJJIJJIJIIIJJIJJJIIIIIJIJJJIIJJIJIJIJJIJ;

	public IIIJIIJJJIJJJJIJIJIIIJIJJIIIIIJIJJIIIJIJIJJIIII IJJIJJIJJIJIIIJJIIIIJIJIIJIJIIJIIJJJJIIIJIIIIIJ;

	public Vector2 IJJJJJIJIIJIJIIIJIIJIIJIIIJJIJJJIJJIIJJJIIJJJIJ;

	public UIWidget.JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII IIJJIJIJJIJJJIIIIIJJJJIJJJJJIJJJJIIJIJJJIJIJIJJ;

	public JIJIIJIJJIIJJJIJIIJIIJIIIJJIIIJJIIIIIIJIJJIJIJI JIJIIJJIJIIIJIJJJJIJJJJIJIJJIIIJJIIIIJJIJJJIIJJ;

	public JIJIIJIJJIIJJJIJIIJIIJIIIJJIIIJJIIIIIIJIJJIJIJI JIJIJIIJJJIIIIIJJIIIIJIIIIIIIIJIJJIJJIIJJJJIJJI;

	public JIJIIJIJJIIJJJIJIIJIIJIIIJJIIIJJIIIIIIJIJJIJIJI IJJJIJJIIJIIIIIIIIIJJIIIJJJJJJJJJJJJJIJJJIIIJII;

	public JIJIIJIJJIIJJJIJIIJIIJIIIJJIIIJJIIIIIIJIJJIJIJI IJIIIJJJIIIJJIJJJJJJIIIIIJIJIJJJJIIJIJJJIJJJJII;

	[SerializeField]
	[HideInInspector]
	private Vector3 scale;

	[HideInInspector]
	[SerializeField]
	private Vector2 relativePositionOnReset;

	protected Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	protected UIPanel IJJIIJJJIIJJJIIIIJIIJIIIJIIJIJIJIJIIJIJIIJJIJJJ;

	protected Plane JIIIJIJIJIJIJJJJIJIJIIIJJJJIIJJJIJJIJIJJIIJJIII;

	protected Vector3 JIIIJIIIJJJJIJIJIIJJIIJJIJJIIIJJIIJIJJIIIJIJJJI;

	protected bool IJIJJJIIJIIJJIJJIIJIIIJJIJJJIJJJJIIIIJJJIJJJJJI;

	protected Vector3 JJJJJIIIIJIIIIIIJJIIJJIJJIIIJJIJJJIJJJIIJJIJIJJ;

	protected float JIIIIIIJJIIIIJJIIIIJJJJIIJIJJIIIIJIJIJIIJIIJJIJ;

	protected Bounds IIIIIJJIJIIJIJIIIIIJJIJIJJJJJJIJJIJJIIJJIIIIIIJ;

	protected bool IJJIJIJIIJJIIIIJIIIIJJJIIJIIJIJJJIIIJJJIJJJIJIJ;

	protected bool IIIJIJIIIIJIJIIIJIIIJIIJIJJJIIIJIIJIJJIIJJJIIJJ;

	protected bool IIJJJIJIIJJIIIJJIJIIJIIJIIJIJJJJIJIIIIJJJJJJJJJ;

	protected int JJJJJJIIJIIJIJJIIJJIIIIJIJJIIJIJJJJIJIJJJIIJJII;

	protected Vector2 JJIIJIIIIJIIIIJJIIIJIJIIJIIIIJIJJJIJIJIIJIIIJJJ;

	protected bool IIJIIIIIIIJIJJJIIJIJIIIJIJIIIIIIIJIJJIIJJIJIIIJ;

	[NonSerialized]
	private bool IIJJIJIJJIJJIJIJIJJJIIIJJJIJJIIIIJJJJIJIJIIJIJI;

	[HideInInspector]
	public UICenterOnChild JIJIIIIIIJJJJIIJJIJJIJJJIJJJIIIIIJIJIIJJJIJJJII;

	public UIPanel JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ => IIJJIJJIIIJIJIJJIIIIIJIIIJIIJJIIIIJIJIIJIIJJJJI();

	public bool IJJJJJJJIJJJJJIJJJJIJJJJJIIIIIIJIIJIJJIJJIIJJII => JIIJIJJIJIIJJIJJIIJIJIJJIIJJIJIJIIJJIIIJIJJIJII();

	public virtual Bounds JJIJIIJJJJJIJJJIIIIJIIIIIJIJIIIJIJIIJIIIIJJJJJJ => JIJIJJIIJIIJJIJJIIIJJIIIJIIJIIIIJJJIJIJIJJJJJII();

	public bool JIJIJJJJIJJJJIJIIIJJJIJJIJIIIIIJJIJJJIJIJJJJIIJ => JIJJIJIIIJIJJIJIIIIIJIJJJJIJIIJJJJJIIIJIJIIJIJI();

	public bool JJJJJJIIJJIJIIIJJJJIJIIJJJIIJIIJIJJIJJJJJJJIIJI => JJIIJIJJJJJJIIJIJIJJIJIIJJJIJJIIJIIIJJIJJIIIIJJ();

	public virtual bool IJJIJJJJIJIJIJJIIJJJJIIIIIJIJJIIJIIJJJJIIJJJJII => JJIIIJIJJIIJJJJIIJJJJIJIJJIIJJIJJIJJJIIJJJIJJJI();

	public virtual bool JJIIIJJJJIIJIJJJIJIIIIIIIJIJIIJIIJJIIIIJJIJIJII => IIJJIJJIIJJIJJIJIIIJJIIIIJIIIIJJIIJIIIJJJIIIIJJ();

	protected virtual bool JJIIJIIIJIIJIIJIIJJIIIIIJJIJIIIJIIJJIIIJIIIJJJJ => JIIIJJIIIJJJIJJIJIJIIJIJIJIIJJJJIIIJIJJJIIJIJJJ();

	public Vector3 IJIIIJJJJJIIIIJIIIJJJIIIIIIJJJJIIJIIIJIIIIJIIJJ
	{
		get
		{
			return IIIIIIJJJIJJIJJIJIJIIIJIIIIIJJIIIJIJIJIJJIJJIJJ();
		}
		set
		{
			JIJIJJJJJJJIIIJIJIIIIIIIJJIIJIJJJIIIIIJIIIJJJJI(value);
		}
	}

	public void JIIIJJIIJIJIIJIJJIIJJJJIJIJJIJIJJIJIJIIIIJJJIII()
	{
	}

	public virtual bool IIJJIJJIIJJIJJIJIIIJJIIIIJIIIIJJIIJIIIJJJIIIIJJ()
	{
		return false;
	}

	public virtual bool JJIIIJIJJIIJJJJIIJJJJIJIJJIIJJIJJIJJJIIJJJIJJJI()
	{
		return false;
	}

	private void OnDisable()
	{
	}

	public Vector3 IIIIIIJJJIJJIJJIJIJIIIJIIIIIJJIIIJIJIJIJJIJJIJJ()
	{
		return default;
	}

	private void OnEnable()
	{
	}

	public void IJJJJIIJJIIIIIIJJJIJIJJIIIIJJJIIIIIIIIJJIIIIJII()
	{
	}

	public void IIIJIJIJJIJJIJJJJIIIJIIJJJJJJJIJJJIJJIJJIJIIJJJ(bool IJJIJIIIJIJIIJIIJIIIJIJIIJJIIJJJIIJIIJJJJIJIJJI)
	{
	}

	public void JJJJIIJIJIJJIJIIIJJJIJJJIIIIJJIJJJJJJJJJIIJJJJJ()
	{
	}

	private void JIIIJJJIIJJIJIIIJIJIIJJIIIJIJIIIJIIJJIJIJJIJJIJ()
	{
	}

	protected virtual bool JIIIJJIIIJJJIJJIJIJIIJIJIJIIJJJJIIIJIJJJIIJIJJJ()
	{
		return false;
	}

	private void Start()
	{
	}

	private void JIIIJJIJIJJIJJJIIIIJJJIJIJIJIIIJJJJIJJIIIIJJIII()
	{
	}

	private void LateUpdate()
	{
	}

	public void JIIIIIJIIIIJJJJIJIIJIJJIJIIIIIIJJJJJIJJIIJIJIII(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void JIJJJIIIIIIJJIIIIIJJIIIJJIJIJJJJJJJJIJIJIIJIJII()
	{
	}

	public void JIJIJJJJJJJIIIJIJIIIIIIIJJIIJIJJJIIIIIJIIIJJJJI(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual void IIJJJIJJJJIJJJJJJJIIJJJJJJIJJJJJJIIIJIJJJIIJJIJ(Vector3 IIJIIJJIIIIIJJIJIJJIIJJIIIIJJJJIIIJJJIJJJIJJIJI)
	{
	}

	private void IIJIIJJJIIJJJIIIJJIJIJJIIJJIIIJIJJJIJJIJIJJIJJI()
	{
	}

	public void JIJJJIIIJIIIIIJJJJIIJJIIJIJJIJJJJJJIJIIJJJIJJJJ(float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	private void Awake()
	{
	}

	public virtual void IIIIIJJJIIIIJJJIIJIJJIIJIIIJIIJIJJIJIJIIJJJIJII(bool IJIIIJJJIJJIIJIJJIJJIJIJJIIJIJIJIIIIJIIJJIIIIJI)
	{
	}

	public void JJJIIIIIIIJJJJJIJJJJJIIIIJJIJIIJJIIJIIIIIIIJIJJ()
	{
	}

	public bool JIJJIJIIIJIJJIJIIIIIJIJJJJIJIIJJJJJIIIJIJIIJIJI()
	{
		return false;
	}

	public bool IIIJJJJJIJIJJJJIJJIJJJIIJJJJJJIJIJJJJJIJJJJIJJJ(bool JIJIJJJIJIIJJIIIIJIIIIJIIJJIIIIJJJJIIIIJIJIIJJI)
	{
		return false;
	}

	public virtual void JJIIIJIIIIJJIJJJIIIJIJJIIJIIIJIJJJJJIIJJIIJJJJI(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, bool IIJIJIIJIJIIJJIJJJIIIJJJJIJIJJJJJJIIJJJJJJIIJII)
	{
	}

	public virtual void IIJIJIIJJIJJJIIJJIIIIJIJJIIIIIIIJJIJIJJJJJIIIII(bool IJIIIJJJIJJIIJIJJIJJIJIJJIIJIJIJIIIIJIIJJIIIIJI)
	{
	}

	public void IIIJJIJJIIIJIJIIIJJJJJJJIIIJIJIIJIJJIIJJJJIIIJJ(Vector3 JIIJIJIJIIJIJJJIIIJIIIIJIIJJJIJIJIJJIJIJIIJIJJJ)
	{
	}

	public bool JJIIJIJJJJJJIIJIJIJJIJIIJJJIJJIIJIIIJJIJJIIIIJJ()
	{
		return false;
	}

	public void JIIJJIJIJIIIJJJIIJJJIIJJIIIJIJJJJIIJJJIJJIJIJJI(Vector3 JIIJIJIJIIJIJJJIIIJIIIIJIIJJJIJIJIJJIJIJIIJIJJJ)
	{
	}

	public bool IIJIJIIJJIIIJIJJIJIIIJJIIIIIIIIIJJIIJIJJIJJJJJI(bool JIJIJJJIJIIJJIIIIJIIIIJIIJJIIIIJJJJIIIIJIJIIJJI, bool IJIJIIJIJIJJIIJIJIIJJIIJIIIIJJIIJJIJIJJIIIJIJJI, bool IJIIIIIIIIIIJJIJIJJJIJJIJIIJIJIJJJJIIJJIIJJJJII)
	{
		return false;
	}

	public void JJJIIIIJJJIIJJIIIIJIIJJIIJJIIIIJJJJJJJJJIJJJIJJ(Vector3 JIIJIJIJIIJIJJJIIIJIIIIJIIJJJIJIJIJJIJIJIIJIJJJ)
	{
	}

	public void JIIJJJIIJIIJJIJIJJJIJIJIIIJIIIIJJJIJJIJIIIIIJIJ()
	{
	}

	public void IJJJJIIIIIJIIJJIIJIIIJJJIIJJJIIIJIJIJIJIJJJIIII()
	{
	}

	public void JJJJIJIIIJIJIIJJIJJJJIIJJIIIJJIJJIJIIJIJIJJJIIJ()
	{
	}

	public void JJIIJJJJIIJJIJIJIJJJJJIJJIIJJJJJJJIIIJIJIIIJIJI()
	{
	}

	public virtual void JJJJIJIIJIJIJJJIIJJIJJIIIIJIIJJJJJJJIJJIJJIJJII(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, bool IIJIJIIJIJIIJJIJJJIIIJJJJIJIJJJJJJIIJJJJJJIIJII)
	{
	}

	public void JIJJIIJIIIJIIIIIJJIIIJJIJJIIJIIJIJIJJJJJJJIIJJJ()
	{
	}
	public bool JJIJIJJJJJJJJIIJIJIIIJIJIJJIIIIIIIJIIJJJJJJJJJI()
	{
		return false;
	}
	public bool JIIJJJJIIIIIIJJJJIIIJJJIIIJIIIJIIIJIIJJIIJIJIJJ()
	{
		return false;
	}
	public void IIJIJIIIIIIIJIIIIIIIIJIJIIIIJIJIJJIIIIJIIJJIJJJ(Vector3 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool JIIJIJJIJIIJJIJJIIJIJIJJIIJJIJIJIIJJIIIJIJJIJII()
	{
		return false;
	}

	public void IJIIJIIIIIIIIIJIIIIJIIIJIIJJIIIIJJJIIJIIIIJIJII()
	{
	}

	protected void IIIIIJJJIIIIJJJIIJIJJIIJIIIJIIJIJJIJIJIIJJJIJII(UIProgressBar JIIIJJJIIIJIIJIIIIJIIIJJJJJIIIJIJIIJJIJIIIIJJIJ, float IIIIJJJJIIJIJJJIIJIIJJIJIJJJIJJJIJJJIJJIIJJIJJJ, float JJIJJIJIJIIIIJJIIJIJJIJIJIIJIIJJJIJJIJIIJJIJIII, float IIJJIJJIIJJIIIJJJJJIIJJIIIJJJJJJJIJJJIIJIJIIIIJ, float JIJJJJIIIJJJJJIJIIIJJIJJIJIJIJJJJIIJIIJIIJIJJJJ, bool JIIJIJIIJIIIIJIIIJJIIJIIJJIIJIIJJIJIJJIJJIJIJJJ)
	{
	}

	public UIPanel IIJJIJJIIIJIJIJJIIIIIJIIIJIIJJIIIIJIJIIJIIJJJJI()
	{
		return null;
	}

	public void IIIIIJJJIIIIJJJIIJIJJIIJIIIJIIJIJJIJIJIIJJJIJII()
	{
	}

	public void IIIIJJIIIIJJIJJJIIIIJJJJIIIJJIJJIIIIIIIJIJIJJIJ(float IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	public bool IIJIJIIJJIIIJIJJIJIIIJJIIIIIIIIIJJIIJIJJIJJJJJI(bool JIJIJJJIJIIJJIIIIJIIIIJIIJJIIIIJJJJIIIIJIJIIJJI)
	{
		return false;
	}

	public virtual Bounds JIJIJJIIJIIJJIJJIIIJJIIIJIIJIIIIJJJIJIJIJJJJJII()
	{
		return default;
	}

	public virtual void JIIIIIJIJIJIIIIJIIIIIJJIJJJJIJIJJJJIJIIIIIJIJJJ(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, bool IIJIJIIJIJIIJJIJJJIIIJJJJIJIJJJJJJIIJJJJJJIIJII)
	{
	}
}
