using System;
using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class UIScrollBar : UISlider
{
	private enum JIIIJJIJJJIJIIIJIIIJJIIJJJIJJJJIJIJJIIJJJIJIIJJ
	{
		Horizontal = 0,
		Vertical = 1,
		Upgraded = 2
	}

	[HideInInspector]
	[SerializeField]
	protected float mSize;

	[HideInInspector]
	[SerializeField]
	private float mScroll;

	[HideInInspector]
	[SerializeField]
	private JIIIJJIJJJIJIIIJIIIJJIIJJJIJJJJIJIJJIIJJJIJIIJJ mDir;

	[Obsolete]
	public float JJJIJIJJIIIJIJIJIIJJIIJIJJIJJIJIJJJJJJIJJJJJJIJ
	{
		get
		{
			return JIIJJJIJJJIJJJJJJJJIIIIIIJIIIJJJJJIJIJIJIIJJJJJ();
		}
		set
		{
			IJIIIIIJJIJIJIJIIJIJIJJJJJIIJJJJJIJIIIJIJJIJJIJ(value);
		}
	}

	public float JIIJIJIJJJJJJJIJJIIIIIJJIIJIJJIJIIJIJIIJJJJIIII
	{
		get
		{
			return IIIJJJIJJJJJJJIJIJJIIJJJJIJIIIIJJIJIIIIJIJJJIIJ();
		}
		set
		{
			IJIJJJIIIJJIIIJIJIIIIJIJJIIIIIIJIJJIIIJJJJJJJJI(value);
		}
	}

	protected override void JIIIJIIJIIJIJJJIIJIJIIIJIJIJJIIJJIIJIIIJIIJJIII()
	{
	}

	protected virtual void IIJIIIJJIIJJIJIJIJJIJJJIIIJIJJJJJJJIIJIIJIIJJII()
	{
	}

	public virtual void IIIIIJIIIJJJJJIIIIJJIJJIJJJJJIIIJJIIJIIJJJIIJIJ()
	{
	}

	public float IIIJJJIJJJJJJJIJIJJIIJJJJIJIIIIJJIJIIIIJIJJJIIJ()
	{
		return 0f;
	}

	protected virtual void JJIIJJJIIIIJJIJIIJJJJIJIIIIIIJIIIIIJIIJIIIIIJJJ()
	{
	}

	protected virtual void JIJJIJJIIJIIJIJIIIJIJJIIJIIIIJIIIJIIIIJIIJIIJJI()
	{
	}

	protected override void JIIJIJJJIIJJIIIIIJIJIIIJJIIIIJIJIIIJIJJIJJJIIJI()
	{
	}

	public override void JIJJIIIIIJIJJIIIJIIJIIIJIIJIIJIIIIJIIJIIIJJIIJI()
	{
	}

	public virtual void JIJJJJIJIJIIJJIIIJIIIIJIJIIIIJIIJJJJIIJIIIJJIIJ()
	{
	}

	public float JIIJJJIJJJIJJJJJJJJIIIIIIJIIIJJJJJIJIJIJIIJJJJJ()
	{
		return 0f;
	}
	public float IIJIJJJIJJIIJJJIJIIJJJIIJIIIIIJIIJIJIIIIJIJJIII()
	{
		return 0f;
	}

	protected override float JJIJJJIJIIJIIJIIJJIIJJJJJJJJJJIIJJJJJIIJIJIJJJJ(Vector2 JJIJJIIIIJJIIJIJIIIIJJJIJJIJJIIIJIJIIJIIIIJIJIJ)
	{
		return 0f;
	}

	protected virtual void IIIJJJJJIIJJJIJJJJIJIJJJJIIIIJIJJIIIIIIJIIJIIJJ()
	{
	}

	public virtual void IJIIJJJIIIJJIIJIIIIIIIJIIJJIJJJIJIIIJJJIJIJJIJJ()
	{
	}
	public void JJIJIJIJIIIIIJJIIJJJJIJJIIIIJIJJIJIIIJJJIIIJIII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void IJIIJJIJIJJJJJJJIJJJIIIIIJIIJJJJIJIIIIJIJJJJJJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void IJJJIIIIIJJJIIJIIJIJIIJJJJIJJIJJJJJJIJJIIIIIIJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public float IJIIJIJIJJIIJIJIJJJJJJJJJJJIIIJJIIIIIJJJJIIIIJJ()
	{
		return 0f;
	}

	protected override void JJJJJJJJIIJJIIJJIIJIIIJIIJIIJIJIJIIJIJJJJIJJIIJ()
	{
	}
	public float IJIJJJJIIIIIIJJJIJIIIJIJJJJIIIJJIIJIJIJIJJJJIJI()
	{
		return 0f;
	}

	public void IJIIIIIJJIJIJIJIIJIJIJJJJJIIJJJJJIJIIIJIJJIJJIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJIJJJIIIJJIIIJIJIIIIJIJJIIIIIIJIJJIIIJJJJJJJJI(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual void IJJJIJIJJIIIIJJJJJIJIIJJJIJJIIJIJJIJJIJJIIIJJJJ()
	{
	}
	public float IIJIJIIIJIJIIJJIIIIJIJJJJJJIJJIIIIIJIJIIJJJIJJJ()
	{
		return 0f;
	}

	protected override void JIJIIIIIJJIIIJIIIIIIJJIIIIIIJJJIIIJJIJJIIJIIJJJ()
	{
	}

	protected virtual void JIJJIIIIJJJJIJJIJJIJIJJIIIIIIJJJIJIJJJIIIIJJJII()
	{
	}
	public float JJJIJJJJJJJJIJIJIJIJIJJIIIJIIIIJIIJJIJIIIIJIJJJ()
	{
		return 0f;
	}
}
