using System.Collections.Generic;
using UnityEngine;

public class UISelectWeapon : MonoBehaviour
{
	public JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI IJJIJJJIIJJJIIIJIJIJIJJIIIJJJIJIJJIIIIIJIIJIJJJ;

	public UILabel IJJJJIJIJJIJIIIJJJJJJIIJJJJIIJIIIJIJIJJJIJIJJJJ;

	public UISprite JIJIIJIJIIIJIJIIIJIIIIJJIJIIJJIIJIIJJJIIIIJJIJJ;

	public float JJJIIJIIJJJJJJJIJIIJIJIIJJJIJIJJJIJJIIIIJIJIIIJ;

	public UILabel IIJJIIJJIIJIJJJJJIIIJIIIJJJIJJIIIIJJIJJJIJJIIJJ;

	private List<string> IIJIIIIJJJIIIJJIIJIJJJIIJIIIIIJIIIIJIJJJJIJJJJJ;

	private int IIJJJJIJJIIJJJIIJIJJJJIIIJIIIIIJIJJJIIIIJIJIIIJ;

	private static bool IJJIJJIIJIIIIIJIIIIJIIIJIJIIIIIIIJJIJIIJIJIIJJI;

	public static bool JIIJIJJIIJJJJIIJIJIIIJIIIIIIIJIIJJIJJIJJJIJJJJJ;

	public static bool JJJIJIJIIJIIIIIIIIIIJIIJJIJIJIIJJIJIJIIIJIJJIJI;

	public void Right()
	{
	}

	private void Start()
	{
	}

	private void IJIJIIJJJIIJIJJJJIJIJIJIJIJIIIJIJIIJIIJIIIJIJII()
	{
	}

	public void IJIIJJIIJJIIJIJJIIJIJIIJIIJIIJIJIIIJJIIIJIIJJJI()
	{
	}

	private void JJJIJJJIIJIIIJIJJIIJIIJJIIJJJJJJJJIJJJIJIJIJIIJ()
	{
	}

	private string JJIIJIJIJIJIIIIIJIIIIIJIIJJJJJJJJJIJJIIJIIJJIIJ(JJIJIIJJIJIJJIIJIJJJIJJIIIIIIJIJJJJIJIIJIIIIJJJ IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
		return null;
	}

	private void JIIJJIJIJIIIJJJIJJJIJJJIIIIIIJIIIJJIIJIJIJJIIJJ()
	{
	}

	public void Close()
	{
	}

	public void IIJIIJIIIIIIIJIJJIJJJIIIJIJJIJIIJJJJJIJIJIJIIJI()
	{
	}

	public void IIJJIIIJJJIJIIIJIJJIIIJJJIJJIIIJJJIIJIJJJIJIIJJ()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void IJJIIJJJIIJIIJJJIIJJIJIJJIJIJJJJIIIIIIIJIJIIIII()
	{
	}

	private void IJJIIIJIIIIJJIJJIJIJIIIJJIJJJJJJIIIIJIIIIIJJIJI()
	{
	}

	private void JIJIJIJJIIJIIJJJJIJIIJJJJJJIJJJJJIIIIJJJIJJIJII()
	{
	}

	private string JJIIIIIIJIIIJIIIJJIJIJIIIJIIIJIJIIIIIIJIIJJIJIJ(JJIJIIJJIJIJJIIJIJJJIJJIIIIIIJIJJJJIJIIJIIIIJJJ IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
		return null;
	}

	private void JJIJIJIJJIJJIJIJIJJJIIJIJJIIJJJJJIIJIJJJJJIIIII()
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	public void Left()
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	public void JJJIIIJIJIIJJJJJJIJJIJIJIIJJJJJIIIIJJIIJIJJIJJJ()
	{
	}

	private void JJJIIIJIIJJJIIIIIIJJJIJIIIJJJJIJIJJIJIJIJJJIJJJ()
	{
	}
}
