using System;
using System.Runtime.CompilerServices;
using UnityEngine;

public class UISelectTeam : MonoBehaviour
{
	private static Action<JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ> JJJJJIIIJJJJIJIIIIIJIIJJIIJIJJIIJJJJIIJIJJJIIJI__BackingField;

	public UILabel IJJJJIIJJIJIJIIJJJJIJIIIJIIIJJIJJJJJIJIIIIJIJII;

	public UILabel JIJJJJIIJJJJJIIIJJJJJJIJIIIJJJJJJJIJJIJIIJJIIJJ;

	public UILabel JIJJJJJIJIIIJIJIJIJIIIIIJJJJJJIJIIJIJIJIIJIJIII;

	public UILabel JIJJJJIIJIIJJIJJIJJIIJIIIJJJIIJJJIIJIIIIJIJIJJJ;

	public UITexture[] JJIJJIIIIJIIIIJIJIIJIJJIJIIIJIJIIIIIIJJIIJIJJIJ;

	public GameObject IJIIIIIIIJJJJIIJIJIIIIIJIJIJIJJJIJJIJIIIJIJJJJI;

	private bool IJIJIJJJJIJIJJJIJJJIIIIIJJIIIIIJIJJJIIIIIIIJJJJ;

	private int JIIJJJIJIJJJIJIIIJJIJJIJIJJJIJJIIJIIJIIJIJJIIIJ;

	private int IJJJJIIJJIJJJIJIIJJJIIIIJJJIJJIIIJIIIIIJIIJIJJJ;

	private int IIJIIJIJIJIIIIJJJIIIIJJJJIIIIJJJJJIIJJIJIJIIIII;

	private static UISelectTeam JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static event Action<JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ> JJJJJIIIJJJJIJIIIIIJIIJJIIJIJJIIJJJJIIJIJJJIIJI
	{
		add
		{
			JJIJJJIJIJIJIJIJIIJIIIIIJIIIIJIJIJJIJIIJIJIJJIJ(value);
		}
		remove
		{
			IJIIIIIIJJIJJJJIIJIIJIIIJJIIIIIJIIJJJIIIIJIJIJI(value);
		}
	}

	public static void JJIJJJJJJJIJIIJJJJJIIJIIIIJIIIJJIIIJJIIJIJIIJJI(bool JIIIJJIJIJIIJIIJIIJJJJIJIJJIIJIJIIJIJIIIIJIIJJJ)
	{
	}

	public static void IJJJIIIIIIJIJJIJIJIIIIIIJIIIJIIJJJIJJJJJJJJJIJI()
	{
	}

	public void SelectTeam(int team)
	{
	}

	private void IJJJJJJIJJIIIIJIJIJJJIIIJJIIIIJJIJIIJIIIIJJJJIJ()
	{
	}

	private void JJIIIIJIIJJIIJJJIIIJJIIIIJJJJIIJIIJIJJIIJJIIIJI()
	{
	}

	public static void JJIJIJIJJJJJIJJJIIIJJJJIJIIJIIIIIIJIJIJIIJIIJII()
	{
	}

	private void JIIIJJIJIJJIJJJIIIIJJJIJIJIJIIIJJJJIJJIIIIJJIII()
	{
	}
	public static void JIIIJIJJJJJJJIJIIJIIJJJJIJIJJIIJIIIIJIIIJIIJIJJ(Action<JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void JJJIJIJJJIJJJJIIIJIJJIJJJJIJIIIJIIIIJJJIJIJIIIJ()
	{
	}

	public static void JJIJJJIJIJIJIJIJIIJIIIIIJIIIIJIJIJJIJIIJIJIJJIJ(Action<JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static void JJJIJJJJJJIIIIIIJIJJJIIIIJIJIJJJJIIIIJJJIJIIIII(Action<JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void IJIJIJIJIIIJJIJJIIIIJIIIIJIIJIJJIIJIIIIJJIJIIII()
	{
	}

	public static void IJIIIIIIJJIJJJJIIJIIJIIIJJIIIIIJIIJJJIIIIJIJIJI(Action<JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public static void JJIJIIIJIJIJJJIIJJJJIIIIIJIIJIIIIIJIJJJJJIJIIJI(Action<JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void Awake()
	{
	}

	public static void IJJIJIJJIJIJIJIIIIIIIJJJJIJJJJJJIIIIJIJIJIJIIJI()
	{
	}

	private bool IIJJIIIIJIIIJJJJIIJIJIIIJJJIIIIIIIJIIIIIJIIJJIJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
		return false;
	}

	private void JIJJJIIIJJJIJJJIJJIIIJJJIJIJJIJIIIJIJJIIJJIJIIJ()
	{
	}
	public static void JJIIIIJJIJIIJJJJIJJJIIJJIIJJJIJJIIIIJJJIJIJIJJJ(Action<JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ> JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public static void IIJJIJJJIJJJIIJJIJJIJIJJIJJJJIIIIJIJJIIIJJJIJIJ(bool JIIIJJIJIJIIJIIJIIJJJJIJIJJIIJIJIIJIJIIIIJIIJJJ)
	{
	}
}
