using UnityEngine;

public class UISettings : MonoBehaviour
{
	public UILabel IIJIIJIJJJJJIIIIIIJIIIJIJJIIIJIJIIIJIIIIJIIJJJJ;

	private int IJIIJIJJIJIJJJJIIJJIJIIIJJJIIJJJJIIIJIJIIJJIIJI;

	public UILabel JJIJIJJIIIIJJIIIJIJJIJIIJIJIJIIIJIJJJJJJJIIJIJJ;

	private static int IJIJJJJJJJIIIJIJIIIJJIIJJJIIIJJIJIIIIJIJJJIIJIJ;

	public UISlider JJJIJJJIIIIIJJJJIJIJIJIIIJJIIJIJJJIIIJJIJIIJJII;

	public UILabel JJIJJIIIIJJJIIIIJJJJIJJJJJJIJJIIIIIIJIJIJJJIIIJ;

	public UISlider JJJJJJJIIIJIJJJIIIIJIJIJIJIIIIIJJIJJJJIIIJJJJJI;

	public UILabel IIIIJJJIIJJIIIIIJJJJJJJJIJIJIIIJIIJJIJJJIJIIIIJ;

	public UISlider IJIJJIJIIJIIIIIJIJJIIIIJIJIIIIIIIJJJJIJIIJIJJIJ;

	public UILabel IJJJJIJJIIJIJIJJJJIJJJIJJJJJJJIJIIJIIIIIJIIIIJJ;

	public UISlider JIIIJJIJIIIIJIJIJIIJJIIJIJJJJJJJIIIJIJJIJJIIIII;

	public UILabel IJJJIIJIJJJIIIJIIIIJIIJIJIIJJIJJJIIJJJJJIIJIJJI;

	public UIToggle JJJIJIIIJIIJIIJIJIJIIIJJJIJIJJJJIJJJIJJIIJIIIJI;

	public UIToggle IJJJJIIJIIJIJJJJJIJIJJIIIJIIIIJJJJIJIIIIIJIIJJI;

	public UIToggle JIIJIJJJIJJIJJJJJIIIIIJIJIIIIIIJJIJIJIIJJJIIIJI;

	public UISlider JIIIIJIJIIIIIIIJIIJJIJIJIIIJJIIIIIJJJIJIJJIJJJI;

	public UILabel IJIJIJIIJJJJJJJIIJJIJIJIJIIJIIJJJIJIIIIIJJIJJJJ;

	public UIToggle IIJJIIIIIJIIJIIJIIJJJJJJJJIJJIJIJJIIJIJIJIIJIJJ;

	public UIToggle JJIJJJIJIIIJIIJIJJIJJJIIJJJIIJJIIJIJIJIIIIJIJIJ;

	public UIToggle IJIIIJJJIIJIJIJIJIIJJJIJIJJIJJIIJJIIJJIJIIJJIJI;

	public UIToggle IIIIIJJJJJJIIIIIJJJIJIIJJJIJJJJJIIJJJIJJIJIJJII;

	public UIToggle JIJIIJIJJJIIJIIJIJJJJIIIIJIJJJIIJJJIIJJJIJJJIJJ;

	public UIToggle JIJIJJIIJJJJJJJJJIIJJIJIJJJJIIIIJJJJIIJJJIJJIII;

	public UIToggle JJJIJJIJIJIIJJJJJIJJJJIIIIIJJIJJJIJIIIJIIIIIJII;

	public UIToggle IJJJJIJJIJJIIJJJIJIIJJIIIIIJIIJJIIIIIJJJIJJJJII;

	public UIToggle IJIIJJIIIJIIJJJIIIIJIJIJIJIJJIJIJJIIIJIIJIIJJII;

	public UIToggle IJIIIJJJIJJIJJJJIJJIJIJIIIJIIIJIIIIJIJJIIJJIIJJ;

	public UIToggle JJIJJJJIIJJIIIIJIJJJJJIJJIJIJJIJIJJIJIIJJIJIJJJ;

	public UIToggle IJIIJJJJIIJJJJIJJJJJIIJIIIIIJIIIIJJIJJJIIJIIJII;

	public UIToggle IJJJIIIJJIJJJIIJJJIIIIIIJJIJJJIIJIJJIJIJIJJIIII;

	public UIToggle JIJJJIIJJIIIIIIJIJIJIIIIIIJIJIJJJJJJJIJIJJIIJIJ;

	public UIToggle IIJIJIIIIJIIJJIJIIIIIJJJJIIJIJJJIJJJJJIJJJIJJIJ;

	public UIToggle JJIIIIIIJIJJJJIJIIJJJJIJIIJJJJJJIJJJIIIJJJJIJII;

	public UIToggle IIJIJIJJIIIIJIIIIJIJIIIJIJJJIJIJJIJIJJJJIJIIIJJ;

	public UIToggle JJJIJIJIJJJIIIIIJJJJIIJJIJIJJJIJIJIIJIIJJIIJIJJ;

	public UIToggle JIJIIIIJJIJIIIIIIIIJIIJJIIJIIIJIJJIIIIJJJJJJJJI;

	public UIToggle IIIIJJJIJJJJIIJJJIJIIJIJIIJJJJIIJIJIIJIJJJJIIIJ;

	public UITable JIJJJIJJIJIJJIJJIJJIIIIIIIJIJIIJIJIIIIIJIIIIIIJ;

	public void SetSensitivity()
	{
	}

	private void Start()
	{
	}

	public void IJIJIJIJIJIIJJIJJJJIIIJIIJIIJIIIJJJIJJJJIJJIJJJ()
	{
	}

	public void LastFont()
	{
	}

	private void JIJJIIJIIIJIJIIJIIIJIJIIIJIJIIIIJIIJIIIIIJIIIJI()
	{
	}

	private static void JJIIJIJJIJJJJJIIJIJIIJIJJIIIJIJJIJIIJIJIJIIJJJJ(string JJJIIIIJIJIIIJIJIIIIJJIIJIJIIIIIJIIJIJIJJJJJIJJ)
	{
	}

	public void SetAcceleration()
	{
	}

	public void Optimization(UIToggle toggle)
	{
	}

	public void IJIJIJJJJIJJJIJIIIJIJIJJJJJJIIIJIIIIIJJIJJJIJJJ()
	{
	}

	private void JIIJJIJIIIJJJIJIIJJJIIIJIJIIIJJIIIJIIIIIJIJJJIJ()
	{
	}

	public static void JJJIIJIIIIJIJIIIIJIIJJJIIJJIIJJJJJIJIIIJIJIJJJI()
	{
	}

	public void IJIJJIIJIIIJJJJIIIJJIIJJIJIIIIJJJIJIJJIJJIJIIJI()
	{
	}

	public void LastLanguage()
	{
	}

	private void IJIIIIIIJJJIJJIIJJJJIJIJIJJIIJIIIJIJIIJJJIJIJJJ()
	{
	}

	public void JJJJJIJJJJIIJIIJJIJIJIJJIIIIIJIJIIIIIJJJJJIIIJI()
	{
	}

	public void JIIJIJIJIIIJJJJJIIJIJJIJJIJJIIJJJJIJJIJIJIJIJII()
	{
	}

	public void IJIIIIJIJIJJJJIJIIJJIJIIJJJIIIJIJIJJIIJJJIJJJJI()
	{
	}

	public void SetVolume()
	{
	}

	private void IIJJJIIIIJIJJJJIIJIJJJJJJIJJIIIIIIJJIIJJJIJJJJI()
	{
	}

	private void IJIIJIIIIJIIIJJIIIJJJJIIIIJJIIJJJJIJJJIIIIJIIIJ()
	{
	}

	public void NextFont()
	{
	}

	public void IJJIJIJJIIIJJIJJJIJJIIJIJIJJJIIIIJJIJJJJJJJIJJI()
	{
	}

	public void SetButtonAlpha()
	{
	}

	public void OnDefaultButton()
	{
	}

	private void IJIJIIIIIJJJJIIJIIIJJIJJJIJJIJIIJJJIIIJIIJIIJJJ()
	{
	}

	private void IJJJJIIJJIIJIIJIJIIJJJIIIIIIIIIJJJIIIIJIIIIJJJJ()
	{
	}

	private void IJJJJIIJJJIIJIIIIJJIJJJJIJIIJIIJJJJJIIJIJJJJJJJ()
	{
	}

	public void Default()
	{
	}

	public void OnSaveButton()
	{
	}

	private void IIJJJJIJIJIIIJIJIJJIJJJIJIJIIIJIIIJIJJJIJJJJIJI()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	public void Save()
	{
	}

	public void NextLanguage()
	{
	}

	private void JJIJIIIJIIIJIJJIIIIJIIJJIJIIIIIJIIIIIIJIIJIJIIJ()
	{
	}

	public void JIJIJJIIJIIIIIJIJIJIIJJJIIIJIJIJIIJJJJIJJJIIIJI()
	{
	}

	public void IJJJJIIIJIJJJIIIIIIIIIIIIJJJIIIIJIIIIJJJJJIIJIJ()
	{
	}
}
