using System;
using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class UISlider : UIProgressBar
{
	private enum JJIJIJJIIIJIJIIIIJJJIJIJJJIJJJIJJJIIIJIJJIJJIJJ
	{
		Horizontal = 0,
		Vertical = 1,
		Upgraded = 2
	}

	[HideInInspector]
	[SerializeField]
	private Transform foreground;

	[SerializeField]
	[HideInInspector]
	private float rawValue;

	[SerializeField]
	[HideInInspector]
	private JJIJIJJIIIJIJIIIIJJJIJIJJJIJJJIJJJIIIJIJJIJJIJJ direction;

	[SerializeField]
	[HideInInspector]
	protected bool mInverted;

	public bool JIJJIJIIIJJIIJIJIJIIJJIJIIIIJJJJIJJJIIJIIJIJIIJ => JIJIIJJJIJJIIJIJJJIIIJIIJIJJIJIIIJJJIJJIIJJJJIJ();

	[Obsolete]
	public float IIIJJIIJIJJJJIIJIJJIJIJJJIIIIJIJIIJIIJIIJIIIJIJ
	{
		get
		{
			return JIIJJJIJIIJIIJJIIIIJIJJJJJJJJJIJJIIJJJIJJJJIJII();
		}
		set
		{
			JIIIIJJJJIJJJIJIJIJJJIIIIIIIJIJJIJIJJJIIIIIIIIJ(value);
		}
	}

	[Obsolete]
	public bool JIIJIJIIJIIIIJIIIJJIIJIIJJIIJIIJJIJIJJIJJIJIJJJ
	{
		get
		{
			return JJIJIIJIIIJIIIIIJJJIJJIIIJIIJJIJIJJJIJJIIIIJIIJ();
		}
		set
		{
			JJIJJIIIJJJJJIIIJIIIJIJIIIJIIIJIJIJJIIJJIIIJJJI(value);
		}
	}

	public float JIIJJJIJIIJIIJJIIIIJIJJJJJJJJJIJJIIJJJIJJJJIJII()
	{
		return 0f;
	}

	protected void JJIJIJJJJIIJIIIJJJJIIJIJIIJIJIJIJJIIIIIIIJIIJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	protected void IJIJIIIJIJJJIJIIIJJIJIJJJJIIIIJJIJJJJJJIJJJJIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	protected virtual void IJJIIIJIJIJJJJJIIIJJIIJIJJIJIIJJIIJJJJIJIIJIJJJ()
	{
	}
	public void IIJIIIIIJIIIJIJJJIIJJJJIJJIJJIJJIIIIIJIJJIIIJII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected void IIJIIJIIIIJJIIJJJJIIIJIIJIIJJJIIIJIIJIJJIIJIJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	protected override void JIIIJIIJIIJIJJJIIJIJIIIJIJIJJIIJJIIJIIIJIIJJIII()
	{
	}

	public virtual void JJIIIIJJJIIIJIJJIIIJJIIJJIIJJJJIJJJJIIJJIIIJIII(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	protected void IJJJJIIIIIJIJIJIIIIIIJJJJJIIIJJJIJIIJJIIJJJJIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	public void JIIIIJJJJIJJJIJIJIJJJIIIIIIIJIJJIJIJJJIIIIIIIIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public bool IJJJJJIIJIJJIJIJIJJJJIJJJJJJJJJJIJJJJJJJIJJIIJI()
	{
		return false;
	}

	protected virtual void IIJJJIJIIJIJJIJIIJJIIJIIJIIJIIJIJJJJIJIIIJJJIJJ()
	{
	}

	public void JJIJJIIIJJJJJIIIJIIIJIJIIIJIIIJIJIJJIIJJIIIJJJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected void IIJJJIJIIJIJJJJIIIJIJJJJJIIJIJIIJJJJJJIIJIIIIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	protected void JIIIIIIJIJJJJIJJIIJJJJIIJIIJJJIJIJJJJIJIIIIIJJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	protected virtual void JIIJIJJJIIJJIIIIIJIJIIIJJIIIIJIJIIIJIJJIJJJIIJI()
	{
	}
	public bool JJIJJIIIIJIIIIIIJIIIIJJIIJIJJIJIJIJJIIIJIJIIJJJ()
	{
		return false;
	}

	public bool JIJIIJJJIJJIIJIJJJIIIJIIJIJJIJIIIJJJIJJIIJJJJIJ()
	{
		return false;
	}

	protected void IIJJIJJIJIJJIIJIJJJIIIIIIJIJIJJJIJJJJJJIJIJIIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	protected void IIIIJJJJJJJJJJJIJJJIIJJJIJJJIIIJJJIIIIJIIJJJIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	protected virtual void IIIIJJJJIIIIIJIIJJJJJIJJIJIIJJIIJIJIJIJJJIIJIII()
	{
	}

	public bool JJIJIIJIIIJIIIIIJJJIJJIIIJIIJJIJIJJJIJJIIIIJIIJ()
	{
		return false;
	}

	protected virtual void JJJJJJJJIIJJIIJJIIJIIIJIIJIIJIJIJIIJIJJJJIJJIIJ()
	{
	}

	protected override void JIJIIIIIJJIIIJIIIIIIJJIIIIIIJJJIIIJJIJJIIJIIJJJ()
	{
	}

	public override void JIIIIIJIIIIJJJJIJIIJIJJIJIIIIIIJJJJJIJJIIJIJIII(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	protected void IJIJIJIJJIIJIIJJJIJJIIIIIIIIIJIJJJIIJJIJIIIJJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	protected void IIJJJJIIJIIJJJJIIIIIJIIIIIJJIIIIJIIIIJJJJIIJIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	protected void IIJJIIIJIJIIIIIJIIJIJJJJIJIIIJIJJIIJIJIIJJIIIII(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	protected void JJIIJIJJIJIJJJIJIJIJJJIIIIIIIIIIJIJIIIJIJJJIJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}
}
