using UnityEngine;

[ExecuteInEditMode]
public class UISnapshotPoint : MonoBehaviour
{
	public bool IJIIJJIIJJJIJJIIIJIJIIJJIIJIIJIIIJJIIJIJJIIIIIJ;

	public float IIIJIIJJJIIJIJIIJIIIJIIIIIIJIJIIIJJIJJIJIIIIIII;

	public float IIJIIJIJIJIJIIIJIIJJJIJJIIIJJIIIJIIJJIJJJJJIIIJ;

	public int IJJJJJIJIIJIIIIJIIJIIIJIIIJJIIJIJIIIIIJJJJIIIJJ;

	public float JIIIJJIJIIJIJIJJJIIJIJIIJJJIJIJIIJIJIIIIJIIIJJJ;

	public Texture2D JJIIJIIIIIJJJIJIJJJJIIIIIJJJIIIIJIIIJJIJJJJJJII;

	private void JJJJIIIIIIJIJJIJIJJIJJJJIJJJIIJIIIIJJIJIIJIJIJI()
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private void Start()
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void IIJIJIIIIIJJIIIIIJJIJIIIJIJIJIIIJIJJIIIJJJJIIJJ()
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}
}
