using UnityEngine;

public class UISoundVolume : MonoBehaviour
{
	private void IJIJJJJJIJJIIJJJJJIJIJJIJJJJJJIJIIIIIIJJJJIIIIJ()
	{
	}

	private void JJJIJJIJJJIJIIJIIJIIIJIIIJIIIIIIIIJJJIIJIJJIJJJ()
	{
	}

	private void JIJIIJIJIIJJIIJIIJJIIJIIJJJJIJJIIJJIJJIJIJIJIJJ()
	{
	}

	private void JJIJIIIIIIIJIJJJJJIJJIJIJJIIIJJJIIIIJIIJJJIIJII()
	{
	}

	private void IIJIIJJJIIJJJIIIJJIJIJJIIJJIIIJIJJJIJJIJIJJIJJI()
	{
	}

	private void JJIJIIIJIJIJJJJIJIIJJJJJIJJJJJIJIJIJIIJIIJIIIJJ()
	{
	}

	private void JIJJIIIJJIJIIIIIJIIJIIIIJJJIJIIIIJJJJJJJJIIIIIJ()
	{
	}

	private void Awake()
	{
	}

	private void JIIJIJJIJJIIJIJIJIIJIJJJJIIJJJIIIIIIIIIIIIJJJII()
	{
	}

	private void IIIJIJJJIIJIIIJIIJJJIJJIJIIJJJIJJIIIJJJJIIJJJIJ()
	{
	}

	private void IIJJIIJIJJJIIIIIJJIJJJIJJJIJIIJIJJJJJIJJIIJIJII()
	{
	}

	private void JIIIJJIJIJJIJJJIIIIJJJIJIJIJIIIJJJJIJJIIIIJJIII()
	{
	}
}
