using Photon;
using UnityEngine;

public class UISpectator : Photon.MonoBehaviour
{
	public GameObject JJJJIJJJJJIJIJJJJIIIIIIJJIIJIIIJIIIIIJJIIJJJJJI;

	public UIWidget JIJJJJIJJIIJJJJJJIIIJIJJIIJIIIJJJIJJJJIJJIJJIIJ;

	public UISprite IJJJJJJJJJJIIJJIIIIJJJJJJIJIIIJIJIJJJJIIJJJJIIJ;

	public UILabel IJIJIIJIJIJIJIJJIJIJJIJIIJJIIJIIIJIIIJJJIJJJIJI;

	public UITexture JIIJIIJJJJIJJJIIJJIJJJIJIJJIJIJJJJIIIJIIIJIJIJJ;

	public UILabel IIJJJJIJIIJJJJIIJIIJIJJJJJIIIIIIIIJJIIIIIJIIIIJ;

	public UILabel JJIIIIIIJJJJJIIJIJJIJJJIIJJIJIJIJJIIIIJIJIJJIIJ;

	public UISprite IJJIIIIJIIJJIJJJIJJIIJJIIJIJJJIJIIJJJIJJJJJIIIJ;

	private JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJJIJIJJIJIIJIJJIIIIIJIJJJIIIJIIIJIJIJIIJJJIIIJ;

	private bool JIJIJIIJJIJIJJJIJIIJIIIIJIIIJJIIIJJJJJJJJJIIIJI;

	private static UISpectator JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private static void JJIIIIIIIIJIIJJJIJIJJIIIIIJIJJJJIIIIJJJJJJIIJIJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	private void IJIJJJIIJIIJIJJIJIJIIIJIJIJJIIIIIIJJIJIJIJIJIJJ()
	{
	}

	public static void JJIJJJJJJIJIIIIJIJIIIIIJJJJIIIJJJIIIJIJJIIIJJIJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	private static void IJIIIIIIJJJIIJIIIIIJIJIIJIIJJJJIJJIIIIJIJJIIJII(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public static void JIJJIJJIJIIIIJJJIJJIJJIJIIJJJJJJJIJJJJIJJIIJJJI(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	private static void JJIJJJJIIIJIJIJJJJJJIJIIIJJIJIJIJJJIJJIIJJJJJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	private void Start()
	{
	}

	private static void IIIJJJIJIIIJJIJIIJJIIJIIJJIJJIIIJJIJIIIJJJIJIJI(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	public static void JJIJJIIIIJIIIIJJJIJIIIJJIIJIIIIIJJIJJJIJIJIJIJI(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	private void IJJJJIIIIJJIIIJJIJJJJJJIJIIJJJJJJJJIJJIIJIIIJIJ()
	{
	}

	private static void IJJIJJIIIIJIJIIJJIJJIIJIJIIJIIIJIJJJJJIIIJIIJJI(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}

	private void OnDisable()
	{
	}

	public static void JIJIJIIJIIJJJIIJJJJJJJIIJIIJIJJJJJJJJJJIJIJIIII()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void OnEnable()
	{
	}

	private void JIJIJJIJIIJIJIJIIIIIIIJIIJJIIIIIJJJIIIIIJIJJJJI(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, byte IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII)
	{
	}

	private void JJJIJIIJJIIJJJIIIJJIIIJJJIJJIIJJIIIJIIJJIJIJJJJ()
	{
	}

	private static void JJIIIIIIIIJIIJJJIJIJJIIIIIJIJJJJIIIIJJJJJJIIJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	private void JJJJJJIIJJIJIIJIJJIIJIJIJJJIIJIIJJJIIJJIJJJIIII()
	{
	}

	private static void JJIIJIJJIIIIJIIJJJIIJIIJIJJIJJJIIJIJJJJIIJJJIJJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ)
	{
	}
}
