using UnityEngine;

public class UISpectatorElement : MonoBehaviour
{
	public UISprite JIJJJJIIJIJIIIIJJJIIIIJIJJJIJIJIJIJJJIIJJIJIIIJ;

	public UILabel IJIJIIJIJIJIJIJJIJIJJIJIIJJIIJIIIJIIIJJJIJJJIJI;

	public UISprite JIJIIJIJIIIJIJIIIJIIIIJJIJIIJJIIJIIJJJIIIIJJIJJ;

	public UISprite JIJJIJIIJIIIJJJIIIJJJJJIJJIIIIIJJIIJIJIJJJJJIII;

	public UILabel JJIIIIIIJJJJJIIJIJJIJJJIIJJIJIJIJJIIIIJIJIJJIIJ;

	public UITexture JIIJIIJJJJIJJJIIJJIJJJIJIJJIJIJJJJIIIJIIIJIJIJJ;

	public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJJJJIJJIJIJIJJIIJJIIJJIJJJIJJIIJJIIJIJJJJJJIIJ;

	public void JJIJJJJIJIIIIIJIIIJIJJJIIJIIIIJJIIJIIJJJIIJJIII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	public bool JJJJJIJIJIIIIIJIJJIJIIJIJJIIJJJIJJIIJIJIJJJJIJI(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, byte IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII)
	{
		return false;
	}

	public void JJJIIIJJJIIJIJJJJIJJIIJIIIIJJIIJJIIIIJJJJJJIIIJ(int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
	}

	public void JJJIIJIJIJIIIJIIIIJJIJJJIJJIIJJJIIIIIJIJJIJIIJI(int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
	}

	public void IIIJIIIJIIIJJIIJIIIIIIJIIJIJIIIJIIIIJJJIJIIJIJJ(bool IJJJIJJIIIJIIIIIIJJJJJJJIIJIJJJJIJJIJIIJJIIJIII)
	{
	}

	private void JJJIJJJJJIIJIJJJIJIIIIJJIJJJIJIIJJIIJIIJJJJIIJI()
	{
	}

	public void IJIIJJJIIJJIJJIIIJIIJJIJIIIIJJJIIJJJIJJIJIJIJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	public void JIJJJIIIIIIIIJIJJJIJJJJJIJJIJJJIJIJIJJIIJIIIIIJ()
	{
	}

	public bool IJJIJIJIIJIJJJJJJIJIJIJJIIJJJIJIIIIJIIJJJIJJIJJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
		return false;
	}

	public void IIIIIJJIJIJJJJJIIIIIIIIJIJIJJIIIIJJJJIJIJIIJIII(int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
	}

	public bool JJJIIIJJJIIJIJJJJIJJIIJIIIIJJIIJJIIIIJJJJJJIIIJ(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
		return false;
	}

	public void IJIIIIIIIIJJIJIJJJJJJIIJIJJJIJJIIIIJJIJIIIJIIIJ(int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
	}

	private void OnEnable()
	{
	}

	public void IIJIIJIIIJJIIJJIIJJJIIJIJIIJIJIJJJJIJIJIJIJJJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	public void IIIJJJIJIJIIJIIIJIJJJIJIJIJJIJIIJIJIJJIJJJJIJIJ(byte IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII)
	{
	}

	public void IIIJJJIIIIJJIJIJIIIIJIJIJIJIIIIJJIIIIIJIJJJJJJI(bool IJJJIJJIIIJIIIIIIJJJJJJJIIJIJJJJIJJIJIIJJIIJIII)
	{
	}

	public void IJIJJIJJJIIJJIJJJIIIIJIJJJJJJJJJIIJJJJIIIIJIIIJ()
	{
	}

	public bool JIJIJJIJIIJIJIJIIIIIIIJIIJJIIIIIJJJIIIIIJIJJJJI(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, byte IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII)
	{
		return false;
	}

	public void IIIIIJJJJIIIJIIJIJJJIIIIIIIJJJIJJJJIIIIJJJIJJJI(int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ)
	{
	}

	private void OnDisable()
	{
	}

	public void JIJIJJIJIIJIJIJIIIIIIIJIIJJIIIIIJJJIIIIIJIJJJJI(byte IIIJIJJJIIIJIJIIIJJJIJIJJJIJIJIJIIIJIIIIIJJIIII)
	{
	}

	private void OnClick(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII)
	{
	}

	public bool IIIJJJIIIIJJIJIJIIIIJIJIJIJIIIIJJIIIIIJIJJJJJJI(int JJIIJIJIIJIJJJJIIJIJJIIIJIJIJJIJJIJIIIIJJIJJJIJ, bool IJJJIJJIIIJIIIIIIJJJJJJJIIJIJJJJIJJIJIIJJIIJIII)
	{
		return false;
	}
}
