using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class UISpriteCollection : UIBasicSprite
{
	public struct IIIIJIIJJIIJIIJIIJIJIJJIJIIIIJJJJJJJIIIIJIJJJJI
	{
		public IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ JIIIJIIJJIIIJIJJJJJIJIIJIJIJJIIJIJJJIIJJJJJJJIJ;

		public Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ;

		public float IJJJJJJJIJIIIIIJJIIIIJIIIIJJJIIJJIJJJIJJIIIIJJI;

		public float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ;

		public float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII;

		public Color32 IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ;

		public Vector2 JJJJJIJIJJIJIJIIIJJIIIJJJIIIJJJJJJIIIJIJIIJJJJJ;

		public JIIJJIJJJJIJIIIJJIJIIJJIJJIJIIIIJIJIJIJJIIIJIII JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI;

		public IIJJIJIIIJJIJIJIJJJJJIJJJIIIIIIIJIIIJIIJIJIJIJJ JIJJJJJJIJJJIJJJIIIJIIJJJIIIJIJIJIJJJJIIJIJJJJJ;

		public bool IJJJJIIIIJIJIIIIIJJIJIJJIIIJJIIIIIJIIIJJJIIIIII;

		public Vector4 JIJIJIIIJJIIJJIIIJJIIIJIIJIJJJJJJJJJIJJJJJIJIII(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 JIJJIIIJIIIIJJJIJJJIIJJIIIIIJJJJIIJIJJJIJJIJJIJ(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 IIJJJIIJIJIIIIJJJJIJIIIIIJJIJJJJJIIJIJIIJJIJIJJ(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 IIJJIJIIIJIJJIJIJJIJIIJIIJJJJIJIJJIIIJIJJJIJJIJ(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 JJIIIJIJIJJIJJJJJIIJJJJJJIIJIJJJJIJJIJIIJIIIJII(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 JIJIIJIJJJIIIJIJIIIJIIJIJJJJIJJJIIIJJIJIIIJIIII(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 IJJIJIIIIJIJIJJJIIJJIJIJIJIIJJIIIJJIJIIIIJIIJJI(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 IIIJJJJJIJIIIJIJJJIIIJJIIIJJJIIIIIIIJJJIJJIJIJI(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 JIIJJJJIJIJIJJJIJIIIJJJIJJIJIIJJIIJIJJJJIIJIJJJ(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 IIJJJJJIIIIIJIJIIIJJIIJJJJIJJIIIIIJIJJJIJIIIJII(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 JIJIIIJJJIJJIIIJIJJIIIJJJIIJJIIIJIIJJJIIIJIJIJI(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 JIIJIJJJIJJIIJJJIJJIJIIJJJJJJIIIIJJJIJIIIJIJIIJ(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 IIIIJJIJJJJIJJJJJIJIIIJJIJIJIJIJIIIIJIIIIJIIIII(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 IJIIIIJIIIJJJIJJJIJIIIJIJIJIJIIIJJIIJIIJJJJIIJI(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 IJJJJJJIIJIJJIJIIJIJJIIIIIIJJIIIIJJIJIIJJJJIJJJ(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}

		public Vector4 JIIIJJIJJJIJJJIJJJIIJJJJJJJIIIJIJIIJIIJIIJJJIJJ(float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII)
		{
			return default;
		}
	}

	public delegate void IJJIIIIJIJIJJIIIJJJJJJJJIJJIJJJJIJJJJJJJIJIIIJJ(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ);

	public delegate void JJJJIJIJJJJJIIJIJJIIJIIIJJIIIJJJIJJIIJJJJJIIJII(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ);

	public delegate void IIIIJJJIIJIIJIJJJIIJJIJJIIJJJIIIIIJIIIJIIJJIJJI(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ);

	public delegate void JIJJJIJIJIIJIJJIIJIJIIIIIJJJJIJIIJJIJIIJIJJIIIJ(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI);

	public delegate void JJIJIJJIIJIIIIIJIIJJJIJJJIJIJJJIIJJJIIJIJJIJJII(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, bool JJIIJJJJJIIJIIIJJIJIIJIJJIIIIIIIJIJJIIIJJJJJIJI);

	[HideInInspector]
	[SerializeField]
	private UnityEngine.Object mAtlas;

	[NonSerialized]
	private Dictionary<object, IIIIJIIJJIIJIIJIIJIJIJJIJIIIIJJJJJJJIIIIJIJJJJI> JJIIIIIIIIJIIJIIIIJJJIJJJIJJJJIJJJIJJIIIJIJJIJI;

	[NonSerialized]
	private IJJJJJIIJIIIIJJIJJIJIJJJJJJJIJIJIJIIJIIJJIIIJJJ IJIJIIJIIIJIJJJIJJJIJIIJJJJJJJJIIIIIIIJJJJIIJJI;

	public IJJIIIIJIJIJJIIIJJJJJJJJIJJIJJJJIJJJJJJJIJIIIJJ JIJJJJJIJJIJJIJIIJJIIIIIJIIJIJIIIIIIJIIIJJIJIJI;

	public JJJJIJIJJJJJIIJIJJIIJIIIJJIIIJJJIJJIIJJJJJIIJII IIIJJIIIIIIJIJJJJJIIJIIJJJIJIIJJIJJIJJIIIJIIJJI;

	public IIIIJJJIIJIIJIJJJIIJJIJJIIJJJIIIIIJIIIJIIJJIJJI IJIIIJIJJJIIJJJIIIIJJJJJIIIIJJIIIIJJIJIIIJIIIJI;

	public JIJJJIJIJIIJIJJIIJIJIIIIIJJJJIJIIJJIJIIJIJJIIIJ JIIIJIJIIIIJIIJIJIJIJIIJJJIIIJIJIIIJIIIJIJJIJIJ;

	public JJIJIJJIIJIIIIIJIIJJJIJJJIJIJJJIIJJJIIJIJJIJJII IIIIJJIJJJJIJIJJJJJIIJJJJJJIIJJIJJIIJJIIJIJJIIJ;

	[NonSerialized]
	private object JIJJIJIJIJJIIJIIJIJJJJIIIJIJIIIJIJJJJJJIJJIJIIJ;

	[NonSerialized]
	private object IIIJIJJJIIJJJIJJIIJIJJJJJIJJIIIJJJIIJJIIIIIIIIJ;

	[NonSerialized]
	private object JIJIIJJIIIIIIIIJJIJJJJJIJJIJJJJJIIJIJJJIJJJJJII;

	public override Texture JJIJJJJJJIJJJJJIJIIJJIJJJJIIIJIIJJJJIIIJJIIIIJI
	{
		get
		{
			return IJIIIJJIJIJIJIIJIIJIIIIJIIIJIIJIJIJIJJJIIJJJIII();
		}
		set
		{
			IIIIIIJJJIIIJJJIIJJJJJJIIIIIJIJJJJIJJIIJIJIIIJI(value);
		}
	}

	public override Material IJIIJJJJJIIIJJJJIIIJJJJJIJJIJIJJIIIJJIIJJIIIIII
	{
		get
		{
			return IJJIIIIJIIIJIIJIJIIJJIIJJJIJJJJIJJJJIIJJIJJIIII();
		}
		set
		{
			IJJJJIIIIJJIJJIIJIJJJJJIJIJJJIIJJJJIJIJIIJJIJJJ(value);
		}
	}

	public IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JJJIIIJJJIIIIIJIJIJJIIIJIIIIIIIJIIIJIIIIIIJJJJI
	{
		get
		{
			return IIJJJIJJIIIIIIJJIIJJIIIJIJJIIIJIJJIIIJIIJJIIJII();
		}
		set
		{
			JJIIIJIIIJIJJJJJJJJIJJJJIIIIJIJIIIJJJIJIIIIIJJJ(value);
		}
	}

	public override float JJIIIIIIIIIJJIIJIIJIJIIIIJJIJJIIIIIIIJJIJIIIIII => IJJIIJJJJIJIIJIIIJJIIIIIJIIJJIIIIJIJJJIJIIIJJII();

	public override bool JIJJJIIJIIIJIJIJIIJIIIIJJIJIJIJIJIJIJJIJJJJIIJI => IIJIJJIJIIIJIIJIJJJJIIJIJIJJIIJIJIJIIJIIJIJIJJI();

	public override Vector4 IJJJJJIIIJJIJJIIJIIJIJJJJJIIJIIIIJIIIJIIJJIJIJI => JJIIIIJJJIJIIJIJIIJIJIIIIIIJJIIJIJIJIIJIJIIJIJJ();

	protected override Vector4 JJIIJIJJJIJIJJIIIJJJIJIIIIJJIIJJIIIIIIJIIIIIJIJ => JJJJIJIIIIJIJIIJIIIJIIJIJJIIJIJJJIJJIJIIJIJJJJI();

	public IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII IIJJJIJJIIIIIIJJIIJJIIIJIJJIIIJIJJIIIJIIJJIIJII()
	{
		return null;
	}

	private static Vector2 IIIJIIIIJIIIIIIIJJIIJJJIIIIJJIIJIIJIIJJIJJJJJIJ(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IJJJJJJJIJIIIIIJJIIIIJIIIIJJJIIJJIJJJIJJIIIIJJI)
	{
		return default;
	}

	public override float IJJIIJJJJIJIIJIIIJJIIIIIJIIJJIIIIJIJJJIJIIIJJII()
	{
		return 0f;
	}

	protected void JJIJJIJJJJJIJJIIIJJIIIIIJJJJIJJIIJJIIJJJIJIIJIJ(bool JJIIJJJJJIIJIIIJJIJIIJIJJIIIIIIIJIJJIIIJJJJJIJI)
	{
	}

	protected void IJJIIIIJJIJIJIIIIIJIJJIJJJIIIIIJJIIIJIIIIJJJJII(bool JIJJJIIJJJJJJIIIIIIIIJJIIJJJIJIIJJIIJIIIIIJJIJJ)
	{
	}

	protected void JIIIJIJJJIIIIIJJIIJJIIIIJJJIIIJIJJJIJJIJIIIJIJI(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	public bool JIIIIJJJIIJJIJJJIIJJJJIIIJIIIJIJIIIIJIIIJJJIIII(object IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return false;
	}

	public override Vector4 JJIIIIJJJIJIIJIJIIJIJIIIIIIJJIIJIJIJIIJIJIIJIJJ()
	{
		return default;
	}

	public void IJJJIJJJJIIIJIJIJIIJJIIJJJIIJJJIIJIIIIJJIIJJIJJ(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, string JIJJIIIIIIIJIIJIJJIJIJJIIJJIIIIIJIJJIJJJIIIJIJJ, Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
	}

	public object IIIJJIJIJIIJJJIJJIJJJJIIIJJJJIIJIJIJJIJIIIIIJJJ()
	{
		return null;
	}

	public bool JJIJIJIJIIIIJJJIJJIJIIIIIJIIJIIJJIJIIIIJIIIJIIJ(object IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, IIIIJIIJJIIJIIJIIJIJIJJIJIIIIJJJJJJJIIIIJIJJJJI IIIJIJIIIJJIJJJIIJIJJIJJJIJIJIJIJIJJJJIJJJIIJJI)
	{
		return false;
	}

	protected void OnClick()
	{
	}

	public bool JIIIJJIIJIIIIIIJIIJJIJIJJJIIJJIIIIJJJJJIIIJJIIJ(object IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ)
	{
		return false;
	}
	public virtual Material IJJJJJJIJIIJJJJIIJIIIJIIIIIJJJJJJJIIJIJJJJJJIJI()
	{
		return null;
	}

	public override bool IIJIJJIJIIIJIIJIJJJJIIJIJIJJIIJIJIJIIJIIJIJIJJI()
	{
		return false;
	}

	private static Vector2 IJJJJJJJIJJJJIIJJJJJIIJIJIIJJJJJJIJJIIIIIJJJIJJ(Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float IJJJJJJJIJIIIIIJJIIIIJIIIIJJJIIJJIJJJIJJIIIIJJI)
	{
		return default;
	}

	public object JJIJJJIJJJIIJIIJIJJIJIJIIIJIJJJIIIIIJIIIJJJJIJJ()
	{
		return null;
	}

	public override void IIIIIIJJJIIIJJJIIJJJJJJIIIIIJIJJJJIJJIIJIJIIIJI(Texture JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool JJIJIIIJIJIIJIJJIJJIJIJJJIIIIIJIIIJIIJIJIJIJIJJ(object IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, IIIIJIIJJIIJIIJIIJIJIJJIJIIIIJJJJJJJIIIIJIJJJJI IIIJIJIIIJJIJJJIIJIJJIJJJIJIJIJIJIJJJJIJJJIIJJI)
	{
		return false;
	}

	public void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}

	protected override Vector4 JJJJIJIIIIJIJIIJIIIJIIJIJJIIJIJJJIJJIJIIJIJJJJI()
	{
		return default;
	}

	public void IJJIJJJJIIIIIIJIIIJJIIJIJIJIJIIJJJIIIIJIJIIIJJI()
	{
	}
	protected virtual Vector4 IIJIJIJJIIIJIJJJIIJJIIJJJIIIJIJIJJJIIIJIJIIJJJI()
	{
		return default;
	}

	public void JJJJJIIJIJIJJJIJIIIIJJJIIJIIJIJJIJJJJJIJIJJIJJJ(object IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, string JIJJIIIIIIIJIIJIJJIJIJJIIJJIIIIIJIJJIJJJIIIJIJJ, Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII, Color32 IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ, Vector2 JJJJJIJIJJIJIJIIIJJIIIJJJIIIJJJJJJIIIJIJIIJJJJJ, float IJJJJJJJIJIIIIIJJIIIIJIIIIJJJIIJJIJJJIJJIIIIJJI = 0f, JIIJJIJJJJIJIIIJJIJIIJJIJJIJIIIIJIJIJIJJIIIJIII JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI = JIIJJIJJJJIJIIIJJIJIIJJIJJIJIIIIJIJIJIJJIIIJIII.Simple, IIJJIJIIIJJIJIJIJJJJJIJJJIIIIIIIJIIIJIIJIJIJIJJ JIJJJJJJIJJJIJJJIIIJIIJJJIIIJIJIJIJJJJIIJIJJJJJ = IIJJIJIIIJJIJIJIJJJJJIJJJIIIIIIIJIIIJIIJIJIJIJJ.Nothing, bool IJJJJIIIIJIJIIIIIJJIJIJJIIIJJIIIIIJIIIJJJIIIIII = true)
	{
	}

	public IIIIJIIJJIIJIIJIIJIJIJJIJIIIIJJJJJJJIIIIJIJJJJI? IJJJJJJJIIJJJJIJJIIIIIJIIJIJIJIIJIIIJIJJJJJIJJI(Vector3 IIIIIIIJIIIJJIJIJJJJJJJIIIJJJJJIIIIJJIJIIJJIIJI)
	{
		return null;
	}

	public object JIIIIIIIJIJIJJJJJIJJIJIJIJJJIIJJJIIIIJIJJJIJJIJ()
	{
		return null;
	}
	public virtual Material IJJIJJIIJJJJIJIJIIJIJIJIJJJJJIJIIJIJJJJIJJJIIIJ()
	{
		return null;
	}

	public bool JIIIJJIIIIIIJIJIIJIIJJIIJIIJIJJJJIIJIJIIIJIJIII(object IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ, Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, bool IJIJIIJIIIJJIIIIIJJJJIIIJJJIJJIJJJJIIJIJJIIJJIJ = true)
	{
		return false;
	}
	public virtual Material JIIJJJIJIIIIJJJJIIJJIJIJIJJJJIJIJIJJJJJJIJJIJII()
	{
		return null;
	}

	protected void JIIJIIIIJJJIIIIIIJJIIIIIIJJJIJJJJJIJIJJIIIIIIJI(bool JIIJIIJJIJIIJJJIIIJJJIJIJJJJIIIIJIJJIIJJIIIJJIJ)
	{
	}

	protected void JJIJJJIJJIJIJIIJJIJIIIIJJJJIIIJJJIJJJJIJJJJIJIJ(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}
	public virtual Material IIJJJJIJJIJIIIJIJJJIJIJIIJIJJJIJJJIIIIIJJJIJIII()
	{
		return null;
	}

	public bool JJIJJIJJIIIJJJJJJJJIIJIIIIIIJJJJJIJIJJJJJIJJJJJ(object IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return false;
	}

	public void JJIIIJIIIJIJJJJJJJJIJJJJIIIIJIJIIIJJJIJIIIIIJJJ(IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, string JIJJIIIIIIIJIIJIJJIJIJJIIJJIIIIIJIJJIJJJIIIJIJJ, Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
	}

	public void JJJJJIJIJIIIIJJJJIIIJIIJJIJIJJJJJJIIIIIIIIIJIIJ(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, string JIJJIIIIIIIJIIJIJJIJIJJIIJJIIIIIJIJJIJJJIIIJIJJ, Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
	}

	public bool IJJIJIJIJIJIJIIIIIIIJIIJIJIIJIIIIIJJIJJJJIJJIJJ(object IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return false;
	}

	public override Material IJJIIIIJIIIJIIJIJIIJJIIJJJIJJJJIJJJJIIJJIJJIIII()
	{
		return null;
	}
	public IIIIIJIIIIJIIIIJIJIJIIIIIJIJIJJIIIIJJIJIJIJJJII IJJJJIIJIIIJIIIJJIIJJIIIJIIJJJJJIJIIIIIIJIJIIIJ()
	{
		return null;
	}

	public IIIIJIIJJIIJIIJIIJIJIJJIJIIIIJJJJJJJIIIIJIJJJJI? IJJJJJJJIIJJJJIJJIIIIIJIIJIJIJIIJIIIJIJJJJJIJJI()
	{
		return null;
	}
	public virtual Vector4 JJIJIJJIJIJJJIJIIIJJIJJJIJIJIIIJJIIIIJIJIJJJJJJ()
	{
		return default;
	}

	public override Texture IJIIIJJIJIJIJIIJIIJIIIIJIIIJIIJIJIJIJJJIIJJJIII()
	{
		return null;
	}

	public IIIIJIIJJIIJIIJIIJIJIJJIJIIIIJJJJJJJIIIIJIJJJJI? JJJJIJJIIIIIJIJJIJJJJIJIIJJJJIJJIJIIIIJIJIJIIJJ(object IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return null;
	}
	public virtual void IJIJJIIJJJIIJJIJIJJIIJIIJJIIIIJJJIIJIJJIIIJJIJI(Material JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public IIIIJIIJJIIJIIJIIJIJIJJIJIIIIJJJJJJJIIIIJIJJJJI? IJJJJJIJJJJIIIIIIIIJJIIIJIIIJIIJIJIJJJIIIJIIJJI(object IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return null;
	}
	public virtual bool JJIIJJIIIJIIIJIJJJJJJJJJIIJIIIJIIJJIIJIJIIIJIJJ()
	{
		return false;
	}

	public void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, string JIJJIIIIIIIJIIJIJJIJIJJIIJJIIIIIJIJJIJJJIIIJIJJ, Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII, Color32 IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ)
	{
	}

	public override void JJIIJJIIJIJJJJIJIJJIIIJJJIIIJIJJJJJIJIJJJIJJJIJ(List<Vector3> IJJIIJJIIJIJIJIIIIIJIJIIJIJJJJIJIJIIJJIIIJJIJIJ, List<Vector2> IJJJIIJJJIJIJIIIJJIJIJIJIJJJJIIJIJJIJIJIJJIIJJJ, List<Color> IJIJIJJJJJJJIIIIJJIIIIJJJIIJJJJIJIJJJJIIJIJIJII)
	{
	}

	public object JJIJJJIJJJIIJIIJIJJIJIJIIIJIJJJIIIIIJIIIJJJJIJJ(Vector3 IIIIIIIJIIIJJIJIJJJJJJJIIIJJJJJIIIIJJIJIIJJIIJI)
	{
		return null;
	}

	public void IIIJJJJJIJJJJIJJJJJJIJIJIJIJIIJJJIIJJIJIIJJJJJJ(object JIIIIIJJJJJJIIJIIJJIIIIIIJJIIIJIJIIIJIIIIIJIIJJ, string JIJJIIIIIIIJIIJIJJIJIJJIIJJIIIIIJIJJIJJJIIIJIJJ, Vector2 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ, float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII, Color32 IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ)
	{
	}

	public override void IJJJJIIIIJJIJJIIJIJJJJJIJIJJJIIJJJJIJIJIIJJIJJJ(Material JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
}
