using UnityEngine;

public class UIStatusElement : MonoBehaviour
{
	public UILabel JJJJJIJJIIJIIJIJJIIJJIJIJIIJJJJIJIIJJJIIIJJJJJJ;

	public UISprite JJJJJIJJJJIJIJIIJJJIIJIJIIJJIJIIIJIIIIIIJIIJIJJ;

	public UISprite JJJJIIJJJIIIIJIJJIJJJJJJJJIJIJIJJIJJIIJJIIJJJJI;

	public void JIIIIIIJIIJIJJIJIJIIJJJIIJJJIJJIJIJJIIJIJJIJJIJ()
	{
	}

	public void JJIIIJIJJJJJJIIIJIIJJJIJIIIIJIIIJJIIIJJIJIJJIJJ()
	{
	}

	public void JIJJJIIIIIIIIJIJJJIJJJJJIJJIJJJIJIJIJJIIJIIIIIJ()
	{
	}

	public void JIIJIIJJJIIIIIIIIJIJIJIJIJIIIJJJJIIIJJJIIIJJIJJ()
	{
	}

	public void IJJJJJIIIJIJIJJJIIIJIIJJIIIIIJIIJIJIJJJIIIIIIIJ()
	{
	}

	public void IJJIIJJIIIIIJJJJJJIJJJJJJJIJJIIJJJJIJJIJIJJJJII()
	{
	}

	public void JJJJIIJJJIJIJJJJIIJIIIJJIJIIJJIJJJJJIIJJIJIIJJI()
	{
	}

	public void IIJIIJJJJIIJJJJJIIIIJIIIIJIJIJIJJJIIIIIJJIIJIII()
	{
	}

	public void IIIIJJJJIJIJJIIIJIJIIIIJIJIJJJJJJIIJIIIJJIIJJII()
	{
	}

	public void IJIJJIJJJIIJJIJJJIIIIJIJJJJJJJJJIIJJJJIIIIJIIIJ()
	{
	}

	public void IJIIJIJIIJJJJJJJIIJIIJJJJIIIJIIIJIIJIIIJIJJJJJI()
	{
	}

	public void JJIJJJJIIIIIJJJIJJIJIIIJIIJJIJJIIJJJJJIJIIJJIII()
	{
	}

	public void IIIJJJJJIIIJIJIIIJIIJJIIIIJJIJIJIIIIJIIIIJIIJII()
	{
	}

	public void JJIJIJJJIJIIIIIJIIJIIJJJIJJIJIJIJIJIJIIJJIIJJJI()
	{
	}

	public void IIJJJIIIIJIJIJIIIIIJJIJIJJJJIJJIIIJIIIIJJJJIIIJ()
	{
	}

	public void JIIJIJJJJJJJIIIIIJIJIJJJJJIIJJJJJIIJJJIJJJIJIIJ()
	{
	}

	public void JJIJIJJIJJIIJJIIJIJIIIIJIIJIIIJJJIIIIJIIIJJJJII()
	{
	}

	public void JIIJJIIIIIIIIIJIJIIJIIIIJJIIIIJJJIIIJJJIJJJIIIJ()
	{
	}

	public void JIJIIJIIIIJIIIIIIIIIJIIIJIJJJJJIIIIJIIJJJJIIIIJ()
	{
	}
}
