using System.Collections.Generic;
using UnityEngine;

public class UIStatus : MonoBehaviour
{
	public UIPanel JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ;

	public GameObject IIIIJIIIJIJJJJIIJJJIIIIIIJJJJJIJJJJJJIIIJIIJIJI;

	public GameObject IIIJIJJIJIIJIJJJIJIIIIJIIIJJIJIJIJJJJIJJJJJIIIJ;

	private List<UIStatusElement> JJIJJIJIIJJIIIJIJIJJIIIJIJIIIJJIIJJJJJIIJIIJIII;

	public List<UIStatusElement> JJJJIIIIIIJIIJIJJJJIIJIIJIIJIJJIIIJIIJJIJIIIIII;

	private static UIStatus JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void IJJJJIIIIIJIJJJIJIIJIIJJJIJJJJJIJJIJIIIJJIJJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void IIJJIJIIIJJJJIJJJJIJJIIJJJJIIIJJJIIIIIJJIIIJJIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IJJIJJJIIJJJJIIIIJIIJJIIJJJIIJIJJJJIIJIJIJIIIIJ)
	{
	}

	public static string JJJJIIIIJIIJIIJJIJJIIJIIJIIIIIJJJIJJJIIJIIJIJJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII, JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJIIJIIIIJJJJIIIIIIIIJIJIIIJIIJIJJJIIIIJJIIIIJ)
	{
		return null;
	}

	public static string JJJJIIIIJIIJIIJJIJJIIJIIJIIIIIJJJIJJJIIJIIJIJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
		return null;
	}

	public static string JIJJIIIJJIIIJJIIJIJJIJJIJIIIIIJIIJIIJIJIIJIIIII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII, JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJIIJIIIIJJJJIIIIIIIIJIJIIIJIIJIJJJIIIIJJIIIIJ)
	{
		return null;
	}

	public static void JIIJJIJJJJJIJJJIIJIJJJIIIJIIIJJIJIJIIJIIJJJIJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static string JJJJIIIIJIIJIIJJIJJIIJIIJIIIIIJJJIJJJIIJIIJIJJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
		return null;
	}

	public static void IIJIJIIJIJJIJJJIJIJJJIJIJJIJIJJJJIJIJJJJJJIJJII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	public static void JIJJIJIIIJJIJIIJIJJJIIIJJJIJIIJJIJJIJIIIJIIIIIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJJJJJJJIIIIIJJJIIIIIJIJIJIIJJJIJIJJIIIIJIJJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IJJIJJJIIJJJJIIIIJIIJJIIJJJIIJIJJJJIIJIJIJIIIIJ)
	{
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void IJIIIJJJJIIJJIJJJIJJIIIJJIIJJIIJJJJIIIIIIJJJIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static string JJIIJJIIJJJIJJJIIIIIJIJIJJJIIJIJIJJIJJJIJJJJIJI(int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ)
	{
		return null;
	}

	private string IIJJJJJIIIJJIJJJJIIIIJJIJJJIIIIJIIJIJIJJIIJJJJI(int IJJJIJIJIIIIJIIIJIJJIIJJIJIIJIJIJJJJJIIIJJIJJJI, int IJIIIIIJIJIJIIIIIJIIIJIIIIJIIIJIIIIIJIJIIIIJJJI, int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, bool JJJJJJJIJIJIJJIIJIIJIIJJIJJIJJIIIJIJJIJJJIJJJIJ, int JIJIIJIIIIJJJJIIIIIIIIJIJIIIJIIJIJJJIIIIJJIIIIJ)
	{
		return null;
	}

	private string JJJIJJJJJIJIJJIJJIIJJIJIIJIJIIJJJJJIIIIIIIIIIJJ(int IJJJIJIJIIIIJIIIJIJJIIJJIJIIJIJIJJJJJIIIJJIJJJI, int IJIIIIIJIJIJIIIIIJIIIJIIIIJIIIJIIIIIJIJIIIIJJJI, int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, bool JJJJJJJIJIJIJJIIJIIJIIJJIJJIJJIIIJIJJIJJJIJJJIJ, int JIJIIJIIIIJJJJIIIIIIIIJIJIIIJIIJIJJJIIIIJJIIIIJ)
	{
		return null;
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IJJIJJJIIJJJJIIIIJIIJJIIJJJIIJIJJJJIIJIJIJIIIIJ, string JJJJJIIIIIJJIIJIJJIIIJIJIJIJJJJJJJIIIIIJJIIJJIJ)
	{
	}

	private void IIIJJJJIIIIIJJIJJJJIIIJIIIIIJJIJIIIJIJIIJIJIJIJ()
	{
	}

	public static string IIJJJJIJIJJJIIIJJJIJJJJJJJJJIJJJJIJIIJIIJIJIJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
		return null;
	}

	public static void IJIIIJJJJIIJJIJJJIJJIIIJJIIJJIIJJJJIIIIIIJJJIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IIJJJIIJIIJIJJJJJIJIIIJJJJIIJJJJIJIJJIJIJJJJJII)
	{
	}

	private string JJJIJIIIIIJIIJJIJJJIJIJJIIIJIJJJJIJIJJJJJIJIJJI(int IJJJIJIJIIIIJIIIJIJJIIJJIJIIJIJIJJJJJIIIJJIJJJI, int IJIIIIIJIJIJIIIIIJIIIJIIIIJIIIJIIIIIJIJIIIIJJJI, int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, bool JJJJJJJIJIJIJJIIJIIJIIJJIJJIJJIIIJIJJIJJJIJJJIJ, int JIJIIJIIIIJJJJIIIIIIIIJIJIIIJIIJIJJJIIIIJJIIIIJ)
	{
		return null;
	}

	public static void IIJIJIIIIIIJJIJJJJIJJJIIIIIIJJJJIIIJJIJIIJIIJIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIJIJIJIJJIJJJIJIIJIIIIIJJIIIIIJJIIIIJJIJJIIII)
	{
	}

	public static void JJIIIJIJIIJJIIJJIJIJIIJJJJIIIIIIIIIJIIJJIJIJIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IIJJJIIJIIJIJJJJJIJIIIJJJJIIJJJJIJIJJIJIJJJJJII)
	{
	}

	public static string JIIJJIJJIJIJJJJJJJJIJJIJIIIJJIIJIJJJJIIIIJIJJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
		return null;
	}

	public static string IIJJIJIJJJIJIIJIIJJIIIJJIIJJJIJJJJIIIIIIIJJJIIJ(int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ)
	{
		return null;
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public static void IIIIIIIJIJJIJIIJIJIIIJIJIJIIIIJJJIJIJIIIJIIIJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IIJJJIIJIIJIJJJJJIJIIIJJJJIIJJJJIJIJJIJIJJJJJII)
	{
	}

	private void IIJIIJJJIIIJJJIJJIJJIJIJJJIIJIJJJIJIIIIJJJIIIJJ(bool JIJJIIIJJJJIJIJJIJIJIIIJIIIJJJIJJJJJIJIIIJJIJJJ)
	{
	}

	private void IIJIJIJJIIJIJJJIJJJJIIIJJIJJIIIIJJJJIJIJJIIJJIJ()
	{
	}

	private void Start()
	{
	}

	private void IJIJJIIJIIJIIIJJIIIIJIIJJJJJIIIJIIJIJJJIIIIJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJJJJIIIIJIIIJJJJJJIJIJIJJIIJJJJIIJJIIIJIJIJJI()
	{
	}
}
