using UnityEngine;

public class UITargetIndicator : MonoBehaviour
{
	public Transform IIJJJIIJIJIIJIIJJJJJIIIJJIIJJIIIJIIJJJIJJJJIIJI;

	public UISprite JJIJIJIJIIIIIIJIIJJIIJIIIIIJJIIJJIJIJJIIJIIJIIJ;

	public Camera IJIJJIIIJIIIJJJIJJIIJIJJJJJJIIJIIIIIIIJJIJIIJII;

	public float IIJIJJJJIJIIJIIJIIIIJIJIIIIJJIJJIJIIJIJIIIIIJIJ;

	public float JJJIIIJJIIJJJIJJIJIIJJIIJJIJIIIJJIJJIIIIJIJJIIJ;

	public float JIJJIJIJJJJIIIIJJIJJIIIIIJJIIJIJIJJJIIJIJIJIJJI;

	private Vector2 JJJJJJJJIJIJIIJJJIJIJJJJJJIIJIJIIJJJJJIIJIJIJII;

	private Vector2 IIJIJJIIIIIJJJIJJIIIIIJIJIJIIJJIJIIJJJIIIJJJIJJ;

	private Vector2 IIJJJJJIJIJJJIJIIJIIJJJIJIJIJIJIIJJJIJJIJIJJIJI;

	private Transform IJIIJJJIIIIIIIJJJJIIIIIJIIIJJJIJIIIIJJJIJIJIJIJ;

	private static UITargetIndicator JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	private void Start()
	{
	}

	public static void JJIIJJIIJIJIJJIIIIIJIIIIJJJJIIIIIIJIIJJJJJIIJIJ(Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ)
	{
	}

	public static void IIJJJIJJIIIJIJIJIJIIIJIIIIIIJJIIJIJIJJIJJIIJIII(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII)
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	private void JJJIIIIIJIJIIJIJIJIIIJIJJIJJIJIIJIJIIJJIIJJJJJI()
	{
	}

	private void IJJJIIJJIIIJJJJJJIIIIJIIIJIJIIJJIJJIJJJIIJJIJII()
	{
	}

	public static void JIIJJIIJJIJJJIJJIIIJJJJIIIIJJIIJIJIJJIJJJIIIIJI(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII)
	{
	}

	public static void JIIIJJIIJIJIJIIJIJJJJIJJJIJJJJJIIIJJJJIJIIJIIIJ(Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ)
	{
	}

	public static void IJJIIIIJIIJJJIIJIJIIIIIJJJJJIIIJIJJIIJJIJIJJIJJ(Camera IJIJIJJJIJIIIIIJIJJIIJIJIJJJIIJJJIJIJJIIJJJJJJJ)
	{
	}

	private void JIJIIJIJIIJJJJJIIJJIJJJIIJIJIIJIJIJJJIIJJJIIIJJ()
	{
	}

	private void JJIIIJIJIJJJJIJJJIIIIJIJJJIJJIJJJIIIJIIIIJIJIJI()
	{
	}

	public static void IJJIIJJJJIIJJIJIIIJJIJIIJIIIJJJIJJJIIIIIJJJIIII(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII)
	{
	}

	private void LateUpdate()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	public static void JIJIJIJIIJIIJIJJJIJIIIIIIIJIJJIJIIJIJIJIJJJIJJJ(Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII)
	{
	}
}
