using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class UITable : UIWidgetContainer
{
	public delegate void IIJIIIJIJJJJJJJIIJJIJIIJJIJIIJIIJIIJIIJJIIIIIIJ();

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JJJJJJIJJJJJIJIJIJJJIIIJJIJJJJJIIJIIIIIIJJIIJII
	{
		Down = 0,
		Up = 1
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IJJIJJIIJIJJJJIIJIJJIJJJIIIJJIJJIJIIJIIIIIIIJJI
	{
		None = 0,
		Alphabetic = 1,
		Horizontal = 2,
		Vertical = 3,
		Custom = 4
	}

	public int IIJIJJIIIIJJJJJIJJIJJJJJJIIIJJJJJJIIJIIIJIJJIII;

	public JJJJJJIJJJJJIJIJIJJJIIIJJIJJJJJIIJIIIIIIJJIIJII IJJIIIIJIIJJJIIJJJJIJIIJIJJJJIIJJJJIJJJJIJJJJJI;

	public IJJIJJIIJIJJJJIIJIJJIJJJIIIJJIJJIJIIJIIIIIIIJJI JJJIIIIJJIJIIIJJIIIJIIJIJIIIIJJJJJJIIIJIJJJJIIJ;

	public UIWidget.JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII JJJJJIJIJJIJIJIIIJJIIIJJJIIIJJJJJJIIIJIJIIJJJJJ;

	public UIWidget.JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII JIIIIIJJJJIJJIIJJIIIJJJJJJIIJJJIJIIIIJJJJIIJIII;

	public bool JJIIIJIJIIJIJIIJIIJIIIIIJJJIJIIIJIJJJJJJIIJJJJJ;

	public bool IJIIJJIJIJIIIJIIIIJJIIIJJJJIIIIIJJJJIIIIIJJIJJI;

	public Vector2 JJIIJIJJJIJIJJIIIJJJIJIIIIJJIIJJIIIIIIJIIIIIJIJ;

	public IIJIIIJIJJJJJJJIIJJIJIIJJIJIIJIIJIIJIIJJIIIIIIJ JIJJIJIIJIIJIIIIJJJJIJIIIJJIJIIJIJJIJJJIIIIJJIJ;

	public Comparison<Transform> IJIJIJJIIJIJJJIIIJJIJJIJJJJIJIJIJJJJIIIIJIJIIIJ;

	protected UIPanel IJJIIJJJIIJJJIIIIJIIJIIIJIIJIJIJIJIIJIJIIJJIJJJ;

	protected bool IJIIJIJJIJJJIJIJIIIJIIJJIJIJIIJIIJIIJIIJJIJIJIJ;

	protected bool IIIJIIIJJIIJIJJIJJJJJIIJIIIJJJIIJJJJJIJIIIJJJIJ;

	public bool IIIJIJIIIIIJJJIJIJJIJIJJJIIIIIJIIIIIIIJJJJIJJJI
	{
		set
		{
			JIJIJIIIIJJIIIIJJJJIIIJIJJJJJJIIIIJJJJJJIJIJJJJ(value);
		}
	}

	protected virtual void IJIIJJIIIIJJIIIIIIJJIJIJJJIIJJJIJJIJIIIIJJIJIJJ(List<Transform> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
	}

	public virtual void JJIJJIIJIIIIIJIIIJJJJJJJIIJJIIIJIIJJJIIIJIIIIJJ()
	{
	}

	public virtual void IIIJIIIJJJIJIJIIIJIJIJJIJIJIIIJIJIIJIIJIIJIJIJI()
	{
	}

	public List<Transform> IJJJIJJJIIJJJJIIIIIIJIIIJJIIIIJJIIIJIIIIJJIIJJI()
	{
		return null;
	}

	private void JIIJJJIIJIIJJJJIJJIIJJIJIJIIJJIJJIIIJJJJIIIIJJJ()
	{
	}

	public virtual void JIJJJIIIIIJIIJJJIJJIIJJIIIIIJJJJJJJJJIJIJJIJJJI()
	{
	}

	protected virtual void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	protected virtual void IJJIIIJJJIJIIIJJJJJIJJJJIJIIJIIIIIIJIJJIJJJIJJI(List<Transform> JIJIJJIIIJIJJIJIIJJJIJJJJJIJIIJJJJIIIIIJIJIIIIJ)
	{
	}

	protected virtual void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}
	public void IJJJJIJJIJIIIIJIJIJJJIJJJIIIIJJJJJIIJJIIIJJJJJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void IJIJJIIJJJJIIIIJJIIIIIIJJJJJJIIIJJIIJJIIIIJIJIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected virtual void JJJIJJJJIJJIJJIIIIIIJJJJJIJJJJJJIJJJIIJIJJIJJII()
	{
	}

	private void OnValidate()
	{
	}

	protected virtual void JJJJJJIJJJJIIJIJJJIIIJIIJIJJIJIJIIIJIIJJIIIJJII()
	{
	}

	private void JJIJIIJIIIJIIJJJIJIJIJIJIIJIIJIIIJJJIJIJJIIIJII()
	{
	}

	public void JIJIJIIIIJJIIIIJJJJIIIJIJJJJJJIIIIJJJJJJIJIJJJJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected virtual void JIJIIJIJIIJJJJJIIJJIJJJIIJIJIIJIJIJJJIIJJJIIIJJ()
	{
	}

	private void JIIJIIIIJIIIJJIIJJJJJJJJJIJIIIIJJJJIIJJIIIIJJJI()
	{
	}

	public virtual void JIIJIJJIIJJJIJIIIIJIJIIJIIJJIJIJIJJJJIJJJJJIIJI()
	{
	}

	protected virtual void IIIJJIJJJJIJIIJIIIIIIIIIJJIIJJIJJJIIIJIJJJJIJIJ()
	{
	}

	protected virtual void Start()
	{
	}
	public void IIIIJJIIIJIIIJJJJJJIJIIIIJIJIIIIJIIIIJJIJJIIIII(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public List<Transform> JJJJJJIIJJIIJIJIIJJIIJIJIJIJIJIIJIIIIIIIIIIIIIJ()
	{
		return null;
	}

	protected void JJJJJIJJIIIIJIIIIJIIJJIIIJIIJIJJIIIJIJJJJIJJJII(List<Transform> JJJJIIIJIJJIIJIJIIIJIIJIJJJIIIIJIIIIJIJJIIIJIJJ)
	{
	}

	protected virtual void LateUpdate()
	{
	}
}
