using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class UITextList : MonoBehaviour
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JIIIJJJJIJJJIJJJJJIJIJIJIJJIJJJJJJIJIJIJJIIJIJI
	{
		Text = 0,
		Chat = 1
	}

	protected class JIIIJIIJJIJJIJJIIJJIJIJIIIJIJIJIJIJJIJJJJIJJJJJ
	{
		public string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI;

		public string[] JIJIIJJJJIIIIIIIJJIJJJJIJIIJIJJJJJJIJIIIJIJIIJJ;
	}

	public UILabel JIJJIJJIJIJJIIJIIIIJJJIIIJIIIIIJJIIJJJJIJIIIIIJ;

	public UIProgressBar IJIJIIJIJIIIIJIIJJIIJIIJJIJIJJIJIJIJJIJIJJJJIJI;

	public JIIIJJJJIJJJIJJJJJIJIJIJIJJIJJJJJJIJIJIJJIIJIJI JIJIIJIJIJJIJJIIJJJIIIIJJJJIJJIIJIJIIIJIIIJJJII;

	public int JJIIJIIIJJIJJJJJJJJJJIJIIIIIIIJIJIJIJJIJIIJIIIJ;

	protected char[] JJIJJJIIIIIJIIJIJJJIIJIJJIJIJJIIIJIIJJJIJJIJJII;

	protected float JIIIIIIJJIIIIJJIIIIJJJJIIJIJJIIIIJIJIJIIJIIJJIJ;

	protected int IIJIIJIJIIIJIJIIIIIIIJIIJJIJJJJIJJJJJIJJIJIIIJI;

	protected int IJIIJJIIIJJJIJIIIIJJIJIIJJJIJIIIIIIJIJIJIIJJJJJ;

	protected int IIIJJJJIJJJJJJIJJIIIIIJJJIJIJIJJJIJIJJIIJIIJIJJ;

	private global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<JIIIJIIJJIJJIJJIIJJIJIJIIIJIJIJIJIJJIJJJJIJJJJJ> IIIJJJIJIJJJIIJIIJIIIJJJIJIIJJJIJIJIJJJJIJJIJII;

	private static Dictionary<string, global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<JIIIJIIJJIJJIJJIIJJIJIJIIIJIJIJIJIJJIJJJJIJJJJJ>> IJJJJJJIIIIIJJJIIIJIIJJIJJJJJIJJJIIIJJJIIIIIIJI;

	protected global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<JIIIJIIJJIJJIJJIIJJIJIJIIIJIJIJIJIJJIJJJJIJJJJJ> IJIJIIJIIJJIIJJIJJJJJJIJIIIJJJJJIIIIJIJJIIJIIJJ => IIJJIIIIJJJJIJJIIIIIJIJIJJJIJJJJIJIIJIJIIIJJIJJ();

	public int IJJJJIIJJIIIJJJJIJIIIJJJIIIJIIJJJIJJIIIIJJJIJII => IJJJJIJJJJJIJJJIIJIJJIJJJIIJJIJJIIJIIJJIJJIIIII();

	public bool IIIJIJJJIIJIJIJJJJJJJJJIJJIJIJIJIIIIIIJJJJJJIII => IIIIIIJJIJIIIJIIJIIIIJJIJJJJIJIJIIIIIIIIJJJIJJI();

	public float JJJIJIJJIIIJIJIJIIJJIIJIJJIJJIJIJJJJJJIJJJJJJIJ
	{
		get
		{
			return JIIJJJIJJJIJJJJJJJJIIIIIIJIIIJJJJJIJIJIJIIJJJJJ();
		}
		set
		{
			IJIIIIIJJIJIJIJIIJIJIJJJJJIIJJJJJIJIIIJIJJIJJIJ(value);
		}
	}

	protected float JIJJIJIIIIIIJIJIJJJIIJJIIJIJJJJJIIJJIIIIJIJJIJJ => JIJIJJIIIIJIIIIJIIJIIIJJJIIJJJIJJJIIIJIIIJIIIJJ();

	protected int IJIIJJIIIJJJJJJIJIIIIIJJJIIJIJIIJIIIIIIIJJJIIJI => JIIJIIIIIJIJIJIIJJJJJJIJJJIIIJIJJJJJIJJIJIIIIIJ();

	private void Start()
	{
	}

	public void IJIIIJIIJJIJIJJJIIJJJJIIIIJIJIIJJIJIJJJJIJJIJJJ()
	{
	}

	private void JIJJIIJIIIJIIIIIJJIIIJJIJJIIJIIJIJIJJJJJJJIIJJJ()
	{
	}

	public float JIIJJJIJJJIJJJJJJJJIIIIIIJIIIJJJJJIJIJIJIIJJJJJ()
	{
		return 0f;
	}
	public int IIJJJJIIIJIIJIIJJJJJIIIIJJJJJJIJIJIIIJIIIIJIJJJ()
	{
		return 0;
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	public int IJJJJIJJJJJIJJJIIJIJJIJJJIIJJIJJIIJIIJJIJJIIIII()
	{
		return 0;
	}

	private void JIJJJJIIIJIIIIJIJJJJIIJJJIIJJIIJJJIIIIIIIJIIIJI()
	{
	}

	protected void JIIJIJJIJJIIIJIIIIJIIIJJIJIIJIIIIJJIJJJJJIIJIIJ()
	{
	}

	public void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public void JJIJJJIJJIJIJIIJJIJIIIIJJJJIIIJJJIJJJJIJJJJIJIJ(Vector2 IJJJJIIJIIIJIJIIJIIIIJIJIJJIIJIIIIJIIJIJJIJJIJI)
	{
	}

	public bool IIIIIIJJIJIIIJIIJIIIIJJIJJJJIJIJIIIIIIIIJJJIJJI()
	{
		return false;
	}
	public bool IJIIIJJIJJIJJIJIJJIIIIIJJJIIJJIJIJJIIIJIJIIJJJI()
	{
		return false;
	}

	protected float JIJIJJIIIIJIIIIJIIJIIIJJJIIJJJIJJJIIIJIIIJIIIJJ()
	{
		return 0f;
	}

	protected void JJIJIJJIIJIJJJIJJJJJIIIJJIIIJIIJJJJJJIJJIIIJIJJ()
	{
	}
	protected int JJJJJIIIJIJIIIIIJIJJJJJJJJIIJJIJIIJJIJJJIIJJIIJ()
	{
		return 0;
	}
	public int JJJIJJJJJIJJIIIJJJIJIJIJIIIJJJJIJJJIIIJIIIIJIJI()
	{
		return 0;
	}

	public void IJIIIIIJJIJIJIJIIJIJIJJJJJIIJJJJJIJIIIJIJJIJJIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void JIIIJJIIJIJIIIIIJJJJJIJIIIJJIJIJJIIIIIIIJIJJIIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public float IIJIJJJJIJIJIJJJIIJJJJJJIJJIJIJIJJJIIJIJJJJIIJI()
	{
		return 0f;
	}
	protected int JJJIIJJIJIJIJJIIJJJIJJJIJJJJJJJJIJJIIJJIIJJJJJJ()
	{
		return 0;
	}

	public void IIJIJIJIJJIIJJJIJJIJJIJIIIJIJIIIIJIIIIIIIJIIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public void IIIIJIIIJIJIJIIJJIJJIJIJJJIIJIJIJJIIJIJIIJJIJJJ(float JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
	}
	protected global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<JIIIJIIJJIJJIJJIIJJIJIJIIIJIJIJIJIJJIJJJJIJJJJJ> IJIJJIIIJJIJIJJJIIIJJIJJIJJJJJJIIIJJJJIIJJJJJJJ()
	{
		return null;
	}

	protected void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, bool IJJIJIIJIIJJJJJIIIIJIIJIIIJJIIJJJIJIJIIJIJJJJII)
	{
	}

	protected global::JJJJIJJIJIJIJIIJIIIJJJJIIIIJJJIJIIIIJIIJJIIIIJJ<JIIIJIIJJIJJIJJIIJJIJIJIIIJIJIJIJIJJIJJJJIJJJJJ> IIJJIIIIJJJJIJJIIIIIJIJIJJJIJJJJIJIIJIJIIIJJIJJ()
	{
		return null;
	}

	protected int JIIJIIIIIJIJIJIIJJJJJJIJJJIIIJIJJJJJIJJIJIIIIIJ()
	{
		return 0;
	}

	public void JIIJJJIIIJJJJJIIIIJIIIJIJJIJIJIIJJIIJJIIJIIIJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private void Update()
	{
	}
}
