using System.Collections.Generic;
using UnityEngine;

public class UIToggledObjects : MonoBehaviour
{
	public List<GameObject> JJIIIJJIJIIIIIJIJIJIJIJIIJJIJIJJJIIIIJJIIIJJJII;

	public List<GameObject> JIJIJJJIJJJJJIJJIJJIJIIJIIIIIJJIJIJJIJJIIJJIJJJ;

	[HideInInspector]
	[SerializeField]
	private GameObject target;

	[SerializeField]
	[HideInInspector]
	private bool inverse;

	private void IIIIIJIIIJJIIIIIJJIJJJIIIJIJJJJJJIIIIJIIJJIJIJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}

	public void JJJIIIJIIJIIJIJJJIJIIIIJIJJIJIJJJJJJIJJJIIJIJJI()
	{
	}

	private void JJIJJJIJIJIIIIIIIJJJJIJJJIIIJJIIIIIJJJJJJJIJIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}

	private void JIIJIIJJJIIIJIIJJIJIJJIIIIIIIIIIJJJIJIIIJJIJIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}

	private void IJIJJIIJIJJJIIIJJJIIJIIJJJJJJIJJIIIIIIIJJJIJJJJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}

	public void IJJIIJIIIIJIJIIJIJJIJJIIJIIIIIJJJIJJIJIJJJIIIIJ()
	{
	}

	private void JIJJJJIIIJIIIIJIJJIIIIJJJIIJJJJJIJJJIIIJIJJIIJI(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}

	private void IJJJJIJJIJJIIJJIJIJIJIIJJJJIIIJJJJJIJIJIJIJJJII()
	{
	}

	private void Awake()
	{
	}

	private void JJIJJJIIIIJJIJIJJIIJJIIIJIJJJIIJIIIIJJJJJIJIIIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}

	private void JJIJIIIJIJIJJJJIJIIJJJJJIJJJJJIJIJIJIIJIIJIIIJJ()
	{
	}

	private void IJJIJJJJJIJIIIJJJIJIJIIIIJJIJIIJIIJIJJIIIJJIJIJ()
	{
	}

	private void JJIJJIIIJIJIJIJIJIIJIJIJJJJIIIIJJIIIJIIIJIIIIJI()
	{
	}

	private void JIJJIIIJJIJIIIIIJIIJIIIIJJJIJIIIIJJJJJJJJIIIIIJ()
	{
	}

	private void IJIJJJJJIJJIIJJJJJIJIJJIJJJJJJIJIIIIIIJJJJIIIIJ()
	{
	}

	private void IJJJJIJJJJIJJIIIJJIJJJJJJJJIIJJIIJJJIJIIIIIJJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, bool IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ)
	{
	}
}
