using System;
using UnityEngine;

public class UITooltip : MonoBehaviour
{
	protected static UITooltip IIIJJIIIJJIJIJIIJJIIIJIJJJIIJIIIJJJIJJJIJJIIJIJ;

	public Camera IIJJIIIJIJJJIIIJJJJJJIIJIIIJJIIIIIJIJJJIIIJIIII;

	public UILabel JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI;

	public GameObject IIJJIJIIJIIIJIIIJIJIIIJIJIJIIJIIJJJJIIIIIIJIJJJ;

	public UISprite JJJJJIJJJJIJIJIIJJJIIJIJIIJJIJIIIJIIIIIIJIIJIJJ;

	public float JIJIJJJJJJIJJIIIJJJJJIJJIIIIIIJIIIIJJIJIIJJIJJI;

	public bool JIJIIIJIIIJIIJIJJIIIJJJIJJJIIJJIIIJIJIJJIIJJJII;

	protected GameObject JIJJIIIIJJIJJJIIIJIJJIIIIJIIIJIIIIIJIJJJIIJIIJJ;

	protected Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	protected float IIJJIIJIIIIJJIIIIIJIJJJJIIIJJJIIIIIJJIJIIJJIIJJ;

	protected float JIIIIIIIIJIJJIIIIJIJIIJJJIJJIIJIJIJIJJJJJJIIJJI;

	protected Vector3 JJIIIJJJIIIJIIIIJIJIIJIIJJIIJJIIJJIJIJJJJJIIJII;

	protected Vector3 IJJJIJIIIJIIJJJJJIJIJJIJIIJIJJJJIJIJIIIIJIIJIIJ;

	protected UIWidget[] IJIJIIIJJIIJJJJIJIJJIJJIIIIJJIIIIIJJIJJJJJIJIJI;

	public static bool IJJIIIIIIJJIIJIJIJIIJJJJJIIIJIJJJJIJJIIIJIJIJII => IIJIIIJIIJIJJJIIIIJIIJJIIIIIIIJIJIJJIJJIIJJIIJI();

	private void Awake()
	{
	}

	protected virtual void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private void OnDestroy()
	{
	}

	protected virtual void Update()
	{
	}

	protected virtual void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}

	public static void JIIIJIIJJIJIIIIIJJJIIIIJJIJIJIIJIJIIJIIJIIJIIJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void IJJJJJIJIJJIIJIIJIIJIIJIIJJJIJIJIJJJJJIJIIJJIJI()
	{
	}

	public static void IIIJJIJIIIIJIJIJJIJJJJIIIJJIJIIIIJIJIIJIIIIIJII()
	{
	}

	public static void JJIJJIJJIIIJIIJIJIJIIIJIIJIIJJIJJIIJIJJJIIIIJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	protected virtual void IIIJIIJJJJIJJIIIJIIJIJIIIIIJIIIIJIJIIIJJJJJIJJJ(float JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
	}

	public static bool IIJIIIJIIJIJJJIIIIJIIJJIIIIIIIJIJIJJIJJIIJJIIJI()
	{
		return false;
	}

	public static void JJJIJIIIIJIIJJIJIJIIIJJIIIJJIJIJJIJIIIJJIJJJIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	protected virtual void Start()
	{
	}

	protected virtual void JIIJJIJIJIIIJJJJJJIJIJJJJJJJJIJIIJIIJJJJIJIIIJI(float JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
	}

	public static void JJIIIJJJJIIIIJIJIJJJIIJJIJJIJJJJJJJIIIJIJIIJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	[Obsolete]
	public static void JIIJJJJJJIIIIIJIJIIJJJIIJIJJJIJJIIIIJIJIJIJIIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	protected virtual void JIJIJJJIJJJIJIJIIIIIJIIJIIIIJIIIJIJJJJJIIIIIIIJ(string IIIIJJIIIIIJIIIJIIJIJJJIIIIJJJIJJIJJJJIIIIIJIJJ)
	{
	}

	protected virtual void IIIJJJJIJIIIIIJJJJIIJIJJIJIJIJIIIIJJJIJJIJIIJJJ(float JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
	}

	public static void JIJJIJJIJJIIIJIIJJJIIJIJIIJJJIIJJJJJJIJIIIIJJIJ()
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void IIJJIIIJJIJIIJIJIIIJIIJIIJIJJIIJJIIIIJIJJIIIJJI()
	{
	}

	private void JJJIIJJJIJIJIJJIJIJIIJJIJJJJIIJIIJIIJJIJJIJJJJJ()
	{
	}

	public static void JIIIJIIJIIJJJIIIIJIIJJIJIJIJIIIIJIJIJIIJJJIIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}
}
