using System.Collections.Generic;
using DG.Tweening;
using UnityEngine;

public class UIToast : MonoBehaviour
{
	public UILabel JJJJJIJJIIJIIJIJJIIJJIJIJIIJJJJIJIIJJJIIIJJJJJJ;

	public UISprite JJJJJIJJJJIJIJIIJJJIIJIJIIJJIJIIIJIIIIIIJIIJIJJ;

	private List<string> JJIIJIIIIIJIJJJJJJIJIJIIJJJJJJJIIIIJIJJIJJIJIII;

	private List<float> IJIIJJJJIIJIIJJIIJJJJIJJJJIIJIJIIJJIIJIIJIJIIII;

	private bool JJJIJIJJJIJIJJIIJIIIJIJIJIJIJJIIIJJJIIJJJIIIJJJ;

	private Tweener IJJIIJJJJIJIIIJIJJJJIJIJJJIIJIIJJIJJJIJIJJIIJII;

	private static UIToast JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	private void IJIJIIIIIJJJJIJJJJJJJJJIIJJJJIJIIJJIJJJIJJJJIJI()
	{
	}

	private void IJIJJJJJIJJIIJJJJJIJIJJIJJJJJJIJIIIIIIJJJJIIIIJ()
	{
	}

	public static void IJIJIIIJIIIJJJIIIIIIJIIJJJJJJJJIJJJJJJJIIJIIJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public static void JJIIIJJJJIIIIJIJIJJJIIJJIJJIJJJJJJJIIIJIJIIJJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, bool JJIIIJJIJJIIJJJIJIJJJIIIIJJIJJJIJIJIIJJIIIIIJIJ)
	{
	}

	private void JIJJJIIIJJJIJJJIJJIIIJJJIJIJJIJIIIJIJJIIJJIJIIJ()
	{
	}

	private void JJIIIIJIIJIJIIIJJIJIJJJJJIJIIIJIJJJIJIIJIIJIIJI()
	{
	}

	public static void IJIJJIIJIIIIIIJJIJIIJIJJJIIJIIJJIIIJJIIJIJJIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	private void IIJJJIIJJIIJJIIJJIJIJJIIJIJJIIJIJJIJJIIJIIIJJJJ()
	{
	}

	private void JIIIIJJJJIIJJJJJIJJJJJIIJIIJJJIJJIIJIJJIIIJJJII()
	{
	}

	public static void IJIJJIIJJJIIIIJIIJJJIIIIJIIIJIJIIJIJIIIJJJIJIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	private void IJIIIJJJIIJIIJIIJJIJIJJJJJJIIIIIIIJIJJJJIJJIIJI()
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, bool JJIIIJJIJJIIJJJIJIJJJIIIIJJIJJJIJIJIIJJIIIIIJIJ)
	{
	}

	private void Awake()
	{
	}

	public static void IJJJJIJJJJJIJJIIJIIIIIIJJIJJIJIJJJIJIJIJJIJIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, bool JJIIIJJIJJIIJJJIJIJJJIIIIJJIJJJIJIJIIJJIIIIIJIJ)
	{
	}

	public static void JJIJIIJIJIJJIIIIJJIJIJIIJJJIJJJJJIIIJIJJIIJJJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public static void IIJJIIIIJIIJJIIIJIJJIIJIIJIIIJJJJIIJIJJIJIJIJJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, bool JJIIIJJIJJIIJJJIJIJJJIIIIJJIJJJIJIJIIJJIIIIIJIJ)
	{
	}

	public static void IJJJJJIIJJJJIIIJJIJIJJJJIJIIIIJJJJIIIJIIIJIIIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	public static void JIJIIIJIJJIJJJJJJJIIIJIIIJJJJJIJIJIJJIJJJJIIIII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}

	private void JIIJIJJIJIJJIIJIIJIIIJJIJJIIIJJJIIIIJJIIJIIJIJJ()
	{
	}

	private void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII()
	{
	}

	public static void JJJIJIJIJJIIIIIIIJJIIJJIJIIJIJIJIJJJIJIIIJJJJJI(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void JIJIIJJIJIIIJJJJIJJJIIJJIJJJIJIIJIIJJIIIIIIIJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}
}
