using System;
using System.Collections.Generic;
using UnityEngine;

public abstract class UITweener : MonoBehaviour
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IIJIJJIIIJJIIJIJIJIJIJIIJIJIJIIJJJJIIIJIJJJJIJJ
	{
		Linear = 0,
		EaseIn = 1,
		EaseOut = 2,
		EaseInOut = 3,
		BounceIn = 4,
		BounceOut = 5
	}

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IJJJJIIIJJIJJIJIJIJJIJIJIJJIJJJIJIJIIIJIJIIIJII
	{
		Once = 0,
		Loop = 1,
		PingPong = 2
	}

	public static UITweener JIIJIIIIIIIIIIJIJIIIJJIIJJJIIIJJIIIIIIIIJIJIJIJ;

	[HideInInspector]
	public IIJIJJIIIJJIIJIJIJIJIJIIJIJIJIIJJJJIIIJIJJJJIJJ JJIJIJJJIIIIIJIJJJIIJJIJIIIJIJIIJIJIIJJJJJIJJJJ;

	[HideInInspector]
	public IJJJJIIIJJIJJIJIJIJJIJIJIJJIJJJIJIJIIIJIJIIIJII JIJIIJIJIJJIJJIIJJJIIIIJJJJIJJIIJIJIIIJIIIJJJII;

	[HideInInspector]
	public AnimationCurve JJJIJJIJIIJIIJJJJJJIIJJJIJJIIJIJIJIIIIJJJIIJIII;

	[HideInInspector]
	public bool JIJJJJIIJJIIJJJJIJIIIJIJIIJJJJJIJIIIJJIJJJJIJJI;

	[HideInInspector]
	public float IIJJJJJJIIIIJJIIJJJJIIIJJIJIJJJIJJIIJIJIIIJJIJI;

	[HideInInspector]
	public float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ;

	[HideInInspector]
	public bool IJIJIIJIJJIIIIIIIJJJJIJIJIIIIIJIJIIIJJIJIIJJIIJ;

	[HideInInspector]
	public int IIIIIIIIJIJIJIJIJIIIJIJJJJIJJJJIJIJJJJIJIIJIIII;

	public bool JJIIIJJJJJIIJIJJIJJIIIJIIJIIIIIIJJIJIJJIIIIJJII;

	[HideInInspector]
	public List<EventDelegate> IJIIIIIJJIIJJJIIJIIJJIIIIIIIJIJIIJIIIJJJJJIIJII;

	[HideInInspector]
	public GameObject JJJJJJIJJIJIIIIIJJJIIIIIIIIIIIJIJJIJJJJJIIJJIJI;

	[HideInInspector]
	public string JJIJJJJJIJIIJIJJJIIJIJJJJIIIIIJIJJJIJJIIJIJJJJJ;

	[NonSerialized]
	public float JJJJJIIIJIIJIIJJJIJIJIJJIIIJJJIJJIIIIIJJIJIJIII;

	private bool IIJJIJIJJIJJIJIJIJJJIIIJJJIJJIIIIJJJJIJIJIIJIJI;

	private float IIIIJJIJIJJIJJJIJIJJJIJJIIJIIIIJIJJJIIIIIIIIIII;

	private float IJIJIJJIJIIIIIIJIIIIIJJIIJJJJIJJIIIIIIIIJIIJJIJ;

	private float JIIIIIJIIIIJJIIIIJIIJIIIJIJJJIJIJJIIJIJJJJJJJJJ;

	private float JIIJJJIIIJIJJJIJIJIIIJJIJIJIIJIIIIIJIJJJIJJJIII;

	private List<EventDelegate> JIIIJIJIIJJJIIIIIIIIIJJJJJJJIJJIJIJIIIIJIIIIIIJ;

	public float JJIIJIJJJIJJJIIIIIJJJJJJIJIIJIIJJIJIIIIJJIJJJJJ => JJIJIIJJJIJJIIJIJJJJIIJJJIJJJJJJIIIJIJIIJIIJIJI();

	public float JJJJIJIIIJJIIJJIJJIJIIJJIJJIJIIIIJJIIJJJJIIIIIJ
	{
		get
		{
			return JIIJIJJIJIJJJJJIJIJIIJJJIJJIJIJIIIIIJIJJIIJIIII();
		}
		set
		{
			JJIIIIJIIIJIJIIIJIIIJIJJJIIJIJIIJJJIIIJJIJIIJJJ(value);
		}
	}

	public IIJJIIIIIIJJIJIJJJJJJIJJIJJJIJIIJJIJJJIJIJJJJJJ IJJIIIIJIIJJJIIJJJJIJIIJIJJJJIIJJJJIJJJJIJJJJJI => IJJIIJIJJJJIJJJIJJJIIJIIJIJJJJIJJJJIJJIIJJJIJJJ();

	public float JJIJIIJJJIJJIIJIJJJJIIJJJIJJJJJJIIIJIJIIJIIJIJI()
	{
		return 0f;
	}

	public float JIIJIJJIJIJJJJJIJIJIIJJJIJJIJIJIIIIIJIJJIIJIIII()
	{
		return 0f;
	}

	public void JJIIIIJIIIJIJIIIJIIIJIJJJIIJIJIIJJJIIIJJIJIIJJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public IIJJIIIIIIJJIJIJJJJJJIJJIJJJIJIIJJIJJJIJIJJJJJJ IJJIIJIJJJJIJJJIJJJIIJIIJIJJJJIJJJJIJJIIJJJIJJJ()
	{
		return IIJJIIIIIIJJIJIJJJJJJIJJIJJJIJIIJJIJJJIJIJJJJJJ.Toggle;
	}

	private void Reset()
	{
	}

	protected virtual void Start()
	{
	}

	protected void Update()
	{
	}

	protected void FixedUpdate()
	{
	}

	protected void JIJJJJJJJJJIIJIJJIIIIIIIJIJJJIIIJJIIJIIIIIJJIII()
	{
	}

	public void JIJJIJIJIIJIJJJJIJIJIIJJJIJIJJIIIJJJIIJIIJIJIJI(EventDelegate.IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ JIIIJJJIIJIIIIIIJIIIIJJIIJIJIIIIJJIJJIIJIJJJJJJ)
	{
	}

	public void JIJJIJIJIIJIJJJJIJIJIIJJJIJIJJIIIJJJIIJIIJIJIJI(EventDelegate JIIIJJJIIJIIIIIIJIIIIJJIIJIJIIIIJJIJJIIJIJJJJJJ)
	{
	}

	public void IIIJJJIIIIIJIJJJIIIIJJIJIJIJJIIIJJIJJIIJIIIIIJJ(EventDelegate.IJJIIJJJIJIIIIIJIIJIJIIIJJJIJIIJIJIIJJJIIIJIIJJ JIIIJJJIIJIIIIIIJIIIIJJIIJIJIIIIJJIJJIIJIJJJJJJ)
	{
	}

	public void IIIJJJIIIIIJIJJJIIIIJJIJIJIJJIIIJJIJJIIJIIIIIJJ(EventDelegate JIIIJJJIIJIIIIIIJIIIIJJIIJIJIIIIJJIJJIIJIJJJJJJ)
	{
	}

	public void JJJIIIIJIJIJJIIJIJJIJIJIJIIIIJIJJIIIIJIIJIJIIII(EventDelegate JIIIJJJIIJIIIIIIJIIIIJJIIJIJIIIIJJIJJIIJIJJJJJJ)
	{
	}

	private void OnDisable()
	{
	}

	public void JIIJIIIIJJIJJIIIJJIJJJIIJIJIJJIJIIIIIIJIJJIIJJJ()
	{
	}

	public void JIIJJIIJJIIJIIIIIIIJIJJIIIIIJIJIIIJJJIIJJIJJJII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ)
	{
	}

	private float JJIIIJJJIJJJIIIJJJJJJIJJJJIIJIJJJJIIIJIJIIIJIIJ(float JIIJIIIIIJIJJIJIIJIIJIJJJJJJIIJJIJIJIJIIIIIIIJJ)
	{
		return 0f;
	}

	[Obsolete]
	public void JIJJIIJIIJJJJJIJIIJJIJIIJIJJIIJJIJIIIIIJJJIIIJJ()
	{
	}

	public void IIIIJIIIIIJIJJJJJJIJJIJJIIIJJJIJIJIJJIIJIIIJJII()
	{
	}

	public void IIJIJIIJIJJJJIIJIJJIIJJJJJIJIIIIJIJIIJJIIJJJIII()
	{
	}

	public virtual void JIJJIIJIIJJJJJIJIIJJIJIIJIJJIIJJIJIIIIIJJJIIIJJ(bool IIIIIIIJIIIJJJIJIIJIIIIJIJJJIJIJIIJIJIIIJIJJJII)
	{
	}

	public void IJIJJIJIJJJJJJIJJIJJIIJJIIIJJIIIIIIJJJJIJIJIJJI()
	{
	}

	public void IJJIIJIIIIJIJIIJIJJIJJIIJIIIIIJJJIJJIJIJJJIIIIJ()
	{
	}

	protected abstract void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII(float JJIJIJJIIIJJIJIJIJJJJJJJJJJIIJIIJJJJJIJIIIIIIJI, bool IIJIJJJIJIJJJIJIJIIIJJJIIJJIIIIJJJIJIIIJJJIJIIJ);

	public static T JIIIJIIIJJJJJJIIIIJIIJJIJJIIIIJIIJIIIIJIIJIJIII<T>(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, float IIJJJJJJIIIIJJIIJJJJIIIJJIJIJJJIJJIIJIJIIIJJIJI = 0f) where T : UITweener
	{
		return null;
	}

	public virtual void JJJIIIIIIIJJJJJIJJJJIIJJJIIIIJIIIIJIJJJIJJJJJJI()
	{
	}

	public virtual void JIIIIIIJJJJIJJIIIJIIJJIIIJJIIIJJIJJIIIJJIJJJIII()
	{
	}
}
