using System.Collections.Generic;
using DG.Tweening;
using UnityEngine;

public class UIWarningToast : MonoBehaviour
{
	public UIWidget JJIJJJIIIIIIIJIIIIIJJIIJIJIIIJJJJIJIJJJIJJIJIJI;

	public UILabel JJJJJIJJIIJIIJIJJIIJJIJIJIIJJJJIJIIJJJIIIJJJJJJ;

	public UISprite JJJJJIJJJJIJIJIIJJJIIJIJIIJJIJIIIJIIIIIIJIIJIJJ;

	private List<string> JJIIJIIIIIJIJJJJJJIJIJIIJJJJJJJIIIIJIJJIJJIJIII;

	private List<float> IJIIJJJJIIJIIJJIIJJJJIJJJJIIJIJIIJJIIJIIJIJIIII;

	private bool JJJIJIJJJIJIJJIIJIIIJIJIJIJIJJIIIJJJIIJJJIIIJJJ;

	private Tweener IJJIIJJJJIJIIIJIJJJJIJIJJJIIJIIJJIJJJIJIJJIIJII;

	private static UIWarningToast JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private void IJIIIIJIIIIJIJJJIJJJJJIIIJJIJJIJIIJJIJJJIIJIJII()
	{
	}

	private void IJIIIJJJIIJIIJIIJJIJIJJJJJJIIIIIIIJIJJJJIJJIIJI()
	{
	}

	public static void IJJJJJIIJJJJIIIJJIJIJJJJIJIIIIJJJJIIIJIIIJIIIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, bool JJIIIJJIJJIIJJJIJIJJJIIIIJJIJJJIJIJIIJJIIIIIJIJ)
	{
	}

	private void IJJIJJJJJIJIIIJJJIJIJIIIIJJIJIIJIIJIJJIIIJJIJIJ()
	{
	}

	public static void IJJJJIJJJJJIJJIIJIIIIIIJJIJJIJIJJJIJIJIJJIJIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, bool JJIIIJJIJJIIJJJIJIJJJIIIIJJIJJJIJIJIIJJIIIIIJIJ)
	{
	}

	public static void IJIJIIIJIIIJJJIIIIIIJIIJJJJJJJJIJJJJJJJIIJIIJII(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ, bool JJIIIJJIJJIIJJJIJIJJJIIIIJJIJJJIJIJIIJJIIIIIJIJ)
	{
	}

	private void Awake()
	{
	}

	public static void JIIJJIJJJIJJJIIJJJJIIIJJIIIIJIIJJIIIIJIIIJIIIJJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	private void IIJJIIIJJIJIIJIJIIIJIIJIIJIJJIIJJIIIIJIJJIIIJJI()
	{
	}

	private void IJJIIIIJJJIJIJIJJIJIIJJIIJJJIIJJJIIIJIJIJJIJJII()
	{
	}

	private void JJIIIIJIIJIJIIIJJIJIJJJJJIJIIIJIJJJIJIIJIIJIIJI()
	{
	}

	private void IIJIIJJJIIJJJIIIJJIJIJJIIJJIIIJIJJJIJJIJIJJIJJI()
	{
	}

	private void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII()
	{
	}

	private void IJIJJJJJIJJIIJJJJJIJIJJIJJJJJJIJIIIIIIJJJJIIIIJ()
	{
	}

	private void JIIJIJJIJIJJIIJIIJIIIJJIJJIIIJJJIIIIJJIIJIIJIJJ()
	{
	}

	private void JIIJIIJIJJIIIJJJJJIJIJJIJJIIJIIJIIJJIIIJJIJJIJJ()
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI)
	{
	}

	public static void IIIJIIJJIJJJIIJIIIJIJIJJJIIIJIIIIIJIIIJJJJIJIIJ(string JIIJJJIJJIIJIJJJJJJJIIIIJIIIJJJJIIIJIIJJJIIIJJI, float IIIIIJIIJJJIJIJIJIIJIIIJJJJJIIIJJJIJJIJJIIIIIIJ)
	{
	}
}
