using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class UIWeaponManager : MonoBehaviour
{
	public static bool IJIIIIJJIJIIIJIJIIJJJIIJIIJIJJIIJJJIJIIJJJJIJJI;

	public static bool JIIIIIJIIIJIIJIJIIIIJJJIJJIJJJIJJIJIJJJJIIIJJIJ;

	public static bool IJJJIIJJJJJJJIJJJJJJJJIIJJJIJJJJIJJIIIIJJJIJJIJ;

	public static bool IJIIJIIIJJJJIJIJJIIJJIJJIJJIIIJJIIIIJIIJIIIIIII;

	public static bool JJJIIJJIIIJJJIIIIIJIJJIJIIJIIIJIIJJJJJJJIJJJIJI;

	public static bool JIJJIIJIJJJJIJIJJJJIIJIIJJJJIJIJJIJJIJIIIIIIIII;

	public static bool JIIIIJJIIIJJJJJIIIJJIJIIIIIJIJIJJJIIJIIJJJIIJJJ;

	public static bool IJJJIJJJIJIIIIIIIIIJIIJJJIJJJJIJJIJIIIJIIIIJIII;

	public UILabel IJJJIIJIJJJIIIJJIJIIIJJIIJJJJIIJIIJIIJJIIIJJJJJ;

	public UILabel IIIIJIJJIIIJJJIJIIJIJIJIIJIJJIJJJJIIIJJIJJJJIJI;

	public UILabel JJIJJJJJJIJIJIJJJJIJIJIIIJIJIJJIJIIIIIIIJIIJIII;

	public UILabel IJJJJIJJJJJJIIIIIJIIJIIIJIJIIJIJIJIIIIJJJJIJIJJ;

	public UILabel IIJJJJIJJJJJIIJJIJIJJJJIIIIIIIJJIIIJIIIJJJJIJJI;

	public UILabel JIIJIJIJJIIIJIJJIIIJIJJIJIIIIJJJIJIIJJJJJIJJJII;

	public UILabel JIIJIIIIIJIIJIJIJIJIIJIJJIIJIIIIIIIIJIIJIJIJJIJ;

	public UIGrid JJJJJJJJJJIJJIIIIIIJIIJJJIJIJJIJIIJIJJJIJIIIJII;

	public UISprite JIIIJJJJJJJIIJJIJIIIIJJJIIIJIJIJJIIJIJJJIJIIJJJ;

	public UISprite JIJJJJIIIIIIIIIIJIJJJIJIIIIIJIJIJIIIJIIIIIIIJJJ;

	public UISprite JIIJJIIIIJIJIIJIJJJJIJIIJJIJIIJIJIIIJJJJJIIIIJI;

	public UIGrid IJIJJIIJIJJIIIIJIJIJJJIIIJIJIJIJJIJIIJIIJIJIJJI;

	public UILabel JIIIIJJIIJJIJJIJJIJJIJIJJIIIIIJIIJIIIIIJIJJJJII;

	public UISprite JIIJIIJJIIIIIIJJIJIJIJJJJJIJJIJIIIIIIIIIIJIIJIJ;

	public UILabel JJJJIJIIJIIIJJJIJJIIIIIIJJIJIJIJJJIIIJIIIIIJJII;

	public UIWeaponElement[] IIJJIJIIIIIJJJJIJIJIJJIJJIIIJIJIIJJIIIJIIJJJJII;

	public UIGrid IIJJIIIIJJJIIJJIIIIJIIJIIJIJJIJIIJIIJJJIJIJJIJJ;

	public UIScrollView JIJJJJJIIIIJIIIJIJJJIIJIIIJIIJJIIJJJIJJJJJIJJIJ;

	public UILabel IIIIIIJIIJIJJIJJJJJIJIJJIJJIJJJIIIIJJJJIJJIIJJI;

	public UIAtlas IJJIJJJJIJJJIIIIJJIIIIIIIJIJIIIIJIJJIJIIIIJIJJI;

	public UIAtlas IIIIIJIIJJIJIIJIJJIJJJIIIIJIJJJIIJJJIIIIJJIJJJJ;

	private float IJIIJJJJIJJIIIIIIIIIIIJIIIJIIIIJJIJIIIJJJIIIJIJ;

	private IJJIIIIJIJIIIJIJIIIIJJIIJIJIJIIIIIIIJJIIIIIJIJJ JJIIIJIIIIJIJJJJJIIIJIJJIIJJJJJIJJIJIJIIIJJJJJJ;

	private static IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIIJIIIJJJIJJJIIJJIIIIJIJIJJIJJIIJIIJIJIIJJIIJI;

	private static UIWeaponManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private bool JJIIIJJIJIIIIIJIJIJIJIJIIJJIJIJJJIIIIJJIIIJJJII;

	public static int IIIJJJIIJIJIJJJJIIIJJJIJIIJIJJJJJJIIJIJJJJJJJJJ
	{
		get
		{
			return JJIIJJIIJIIIJJIIJJJIJJJIJJJJIJJJJJJJIIJIJJJJIJJ();
		}
		set
		{
			JIJJJIIIJIJJIJIIJIIIIIJIJJJJJJIIIIIJIIIJIIJIJIJ(value);
		}
	}

	private void JJJIJJJJJJIJJJJJJJIIIJJIIIJIIJIIIIIJJJIIJIIIJJJ(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	public static void JIJJJIIIJIJJIJIIJIIIIIJIJJJJJJIIIIIJIIIJIIJIJIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private List<IIJJJJJJJJIIJJIIJJIJIIJIJJIIJIJJJJJIJJIJIJJIJJI> IIJIJJIJJIIJIJJIIJJIIIIIIIJJIIJIIJIJJIJIIJIJIJJ(IJJIIIIJIJIIIJIJIIIIJJIIJIJIJIIIIIIIJJIIIIIJIJJ JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return null;
	}

	public static void JIJJIIJJIIIIIJIIJJIJJJJJJIJIJJJIJIIJIJIIJJIJJII(float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
	}

	private void JJIJIJJIJIJIJIJIIIJIIJJJJIJIIJJIIIJIJJIJIIJIIII()
	{
	}

	public void Open()
	{
	}

	private void JIJIJIJIIIJJIIIJIJJIJJIJJJJIJJIJIJJIJJJIIJIJIII(IJJIIIIJIJIIIJIJIIIIJJIIJIJIJIIIIIIIJJIIIIIJIJJ JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	private void IJJIJIJJJJIJIJIIJJIJIJIJIJJIIIIJJJIIIIJJIIJIJJJ()
	{
	}

	public void SelectWeapon(GameObject go)
	{
	}

	private void IIJIJIJIIJIIJJJJJIJJIJIJIIJIJJJJJJIJJIIIJIIJJIJ()
	{
	}

	public void Close()
	{
	}

	private void OnDisable()
	{
	}

	private void OnEnable()
	{
	}

	private void IJIIIIIIJIJJJJJJJJIJJJJJJJIIJIIJJJIIIIIJJIIIJIJ()
	{
	}

	public static void IJJJIIJIJJIIIIJJJIJJJIIIIJJJJJJJJJIJIIIIJIJJJJI()
	{
	}

	private void IIJIIIJIJJJJIIIIIIJIIIJIJIJIJJIIIIIIJJIJJIJJIII(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public static int JJIIJJIIJIIIJJIIJJJIJJJIJJJJIJJJJJJJIIJIJJJJIJJ()
	{
		return 0;
	}

	private void IJIJJJJIIIJIIJIIIIIJJIJIIJJJJIJJIJJJJJJIIJIIJJJ()
	{
	}

	private void IJIIIIJJJJIIJIIIIIIJIIIIJIIIIJIJJJIIIIJJJJIIJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	public static bool IIIJIIIJJIIJJIIIIJJJIJJIJJIIIIJIJIJJJJJJJJJIJII()
	{
		return false;
	}

	private void JJIIIIIJJJIIJJJJIJIJIJIJIJJIIJJIJJIJJIIJJJIIIJJ()
	{
	}

	private void IIJJIIJIIJIIJJJIIIIJJJIIIJJJIIIIJJIIJIJJJJJIIJJ()
	{
	}

	private void JIJJIIJIIIJJIJJIJJIIIJJJIIJIJJIIIJJJJIJJIJJIJIJ()
	{
	}

	public void IJJIJIJJIJIJIJIIIIIIIJJJJIJJJJJJIIIIJIJIJIJIIJI()
	{
	}

	private void JIIIIJIJJJIJJIJJJIIIIJIJJIIIJJJIJJIIJIIJIIJIJJJ(IJJIIIIJIJIIIJIJIIIIJJIIJIJIJIIIIIIIJJIIIIIJIJJ JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
	}

	private void JIJIJIJIIIJJIIIJIJJIJJIJJJJIJJIJIJJIJJJIIJIJIII(IJJIIIIJIJIIIJIJIIIIJJIIJIJIJIIIIIIIJJIIIIIJIJJ JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI, bool JJJJIIJIIJJIIJIIJIJIIJJIIIIIJJJJIIIIJJIJJJJJJII)
	{
	}

	public static void IJJJIJJIJIJJIIIJJJIJIJIJJJJIIJJIJIJJIJJJIIIIJIJ(float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI, bool IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	public static void IJJJIJJIJIJJIIIJJJIJIJIJJJJIIJJIJIJJIJJJIIIIJIJ(float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI)
	{
	}

	public void SelectType(int index)
	{
	}

	private void IJIIJJJIJJIIJIIIIIJJJJJIIIIJJJJJJIJIIJIIIJJJIJI()
	{
	}
	public static void IIIIJJJIIIJIIIIIIIJJIIJIJJIIIJIIIIIJIIJJJJJJJJJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	private void Start()
	{
	}

	private void Awake()
	{
	}

	private void JJJJIJIIIIJJIJIJIIIIIIIJJIJIIIIJJIJIIIJJJJJIIII()
	{
	}

	public static void IJJIIJIJJJIIJJIJIIIJJIIJIJJIIIJJJJIJIJIIJJIIIJI(float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI, bool IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void IIJJJJJJIIIIIIJIJJJJIJIIIJIIJIJIJJJJIIJIIJJIIJJ(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	public static bool IJJJIIIIJIJIIIJIIJIJJJJJIIIJJJIJJJIJJIIIJIJJJJJ()
	{
		return false;
	}

	private void IIJJIJIIIIIJJJIIIJJIIJJIJIJIIIIJIJJJIIJIJJJJIJJ()
	{
	}

	private void IJIJIIIIJIJJJJIJJIIJJIIIIIJIIIJJIIJJIJJJIIIIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IJJIIIJIJJIJJIIIJJJIIJIJJIJJIJIIJJJJIIJIJIJJIIJ()
	{
	}

	private void IJJJJJIIJJIIIJIIIIIJIIIIJIJJJJIIJJIJIIIIIJIJJII(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}
}
