using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class UIWidget : UIRect
{
	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII
	{
		TopLeft = 0,
		Top = 1,
		TopRight = 2,
		Left = 3,
		Center = 4,
		Right = 5,
		BottomLeft = 6,
		Bottom = 7,
		BottomRight = 8
	}

	public delegate void JJIJJJIJJJIJIJIIIJJJJJJJJJIJJJIIJIJIJIIIIJJJJJI();

	public delegate void IIJJJJIIIIJIIIJIJIIIIIIIJIIJIIIJIJIJJIIIJJJIIJJ(UIWidget JJIJJJIIIIIIIJIIIIIJJIIJIJIIIJJJJIJIJJJIJJIJIJI, int IJIJJJJJIJJJJJJJIJJIJIIIIIJJJJIIIIJIIJIIIIIIIJI, List<Vector3> IJJIIJJIIJIJIJIIIIIJIJIIJIJJJJIJIJIIJJIIIJJIJIJ, List<Vector2> IJJJIIJJJIJIJIIIJJIJIJIJIJJJJIIJIJJIJIJIJJIIJJJ, List<Color> IJIJIJJJJJJJIIIIJJIIIIJJJIIJJJJIJIJJJJIIJIJIJII);

	[IIIIIJIJJJIJIIIJIJJIIIIIIJIJJIJJIJIIIIIJJIJJJII]
	public enum IJJIJIJIIJIIIIIIJJIJJJIJJJJIIIIJJIIIJIIIIJJJIIJ
	{
		Free = 0,
		BasedOnWidth = 1,
		BasedOnHeight = 2
	}

	public delegate bool JIJIJJJJIJIIIIJJJJIJIIJJJJJJJJIJJIIIJIIJIJJJJJI(Vector3 IIIIIIIJIIIJJIJIJJJJJJJIIIJJJJJIIIIJJIJIIJJIIJI);

	public bool JIIIJJIJIIIJIIJIJIIJJJIIIJJIIJIJIJIIIIJIIJJJIJJ;

	public bool JIJJIIJIJJJIJIJIJJIJIIJIIJJIJIJJIJIIJIIIIIIIJJI;

	public UIWidget[] IJIIIIJJJJJIIIJJJJIIJIIIJIIJIJJIJIIJJJIIJJIIIJI;

	[HideInInspector]
	[SerializeField]
	protected Color mColor;

	[HideInInspector]
	[SerializeField]
	protected JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII mPivot;

	[HideInInspector]
	[SerializeField]
	protected int mWidth;

	[SerializeField]
	[HideInInspector]
	protected int mHeight;

	[HideInInspector]
	[SerializeField]
	protected int mDepth;

	[HideInInspector]
	[SerializeField]
	protected Material mMat;

	public JJIJJJIJJJIJIJIIIJJJJJJJJJIJJJIIJIJIJIIIIJJJJJI JIIJJJJJJJIIJJIJJJIIJJJIIIJJJIIJJJJJIIJJJIJJJII;

	public IIJJJJIIIIJIIIJIJIIIIIIIJIIJIIIJIJIJJIIIJJJIIJJ IIIJIJIIIJIIIIJJJJJJJIIIJIIIIJIJIJIJJJIJIJIIIII;

	public UIDrawCall.IIIIJJIJJJJJJIJIIJJIJJJJIJJIJIIIIIIIIIIIJJIIJJI JIIIIIIIIIJJIIJJIJJJIIIIIIJJIIJJJJJIIJJIJIIJIII;

	public bool JJIIIIIIIIJIJIJJIJIIJJJIJIIJJJIJJIIJJIIJIJIJJJJ;

	public bool IJJIIJJJIJIJIJIIJJIJIJJJIIJJJIJJJJIJIIIJJJIIJII;

	public IJJIJIJIIJIIIIIIJJIJJJIJJJJIIIIJJIIIJIIIIJJJIIJ IJJIIJIJJIIJJJJIIJJJJIIJIIIJJIIJJJIJJIJJIIIIJII;

	public float IIJJJIJJIJJIJIJJIIIIIIJJJIIJIIIJJIJJJIJJIIJJJJI;

	public JIJIJJJJIJIIIIJJJJIJIIJJJJJJJJIJJIIIJIIJIJJJJJI JJIIJIIIJIIIJJIIJJJJIIJJIJJJJJJIJIJIJJIIIJIIIII;

	[NonSerialized]
	public UIPanel JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ;

	[NonSerialized]
	public JIIJJIIIJJIIIJIJJIIJIIIIJJJIIIIJIJIIJJJJIJIJIJJ JJJJJIIJJJJJJIJIJIJJIIIIJIIIJJJIJJIJIIIIIJJIIIJ;

	[NonSerialized]
	public bool IIJJIJIJJIIJIJIIIIJJIIIJJIIIIJJIJIJIIJJJJJJJIJI;

	[NonSerialized]
	protected bool JJIJIIIJIJJIIIJIJJJIIJIIIIJIIJJIIIJJIJIIIIJIIJI;

	[NonSerialized]
	protected Vector4 IIJIIJIIJIIJJIJJJIIJIIJJJJIIJJIIJJJJIJJJIIIJIJJ;

	[NonSerialized]
	private Matrix4x4 IJIJJIJJJJJJJIJJJIJJJIIJIIIJJJIIJJIIJJIIIIIJIII;

	[NonSerialized]
	private bool IJJJIJJIIIJIJJJJJIIJIIIIIJJJJJJJIJIIIIIIIIJIIJJ;

	[NonSerialized]
	private bool IJJIJIJJJIJIIJIJJIIJJIJJIJJIIJIIIJJIJJJIIIIJJJI;

	[NonSerialized]
	private bool JIIIIIJJJJIJIIIJIJJIIJIJIIJIIJIJIJJJJIJJJJIJIJJ;

	[NonSerialized]
	private float JIIIJJIIJJIIIIJJJJJJIJIIJIJJJJIJJIJJJIJJJIJIJJI;

	[NonSerialized]
	private bool IIJIJIJIJIIIIIIJJIIJJIIIIIIJIIJIJJIIIIIJJJJIJJI;

	[NonSerialized]
	public UIDrawCall IIJIIJJIIJIJIIIJIIJIJIIJIJJIJJJJIJJJIJIIIJIIIJJ;

	[NonSerialized]
	protected Vector3[] IIJIJJJJIJIIJJIIJJJIIJIJJJIIIJJIJJIJJJIJIIIJIJJ;

	[NonSerialized]
	private int JIIJIIIJJIIJIJJIIIJIIIJIIJJIJIIIIJIIJIIIIIJIJII;

	private int JIIIJIIJIJIJIIIJIIJIJJJJJJIJJIJIJIIJIJJJJIIIIJI;

	private Vector3 IJIIIJIJJJIJJIJIIJIIIIJJIIJIJIJIJIIIIJIJIIJJJJI;

	private Vector3 IIJJJIJJIJIIJJIJJJIJIJIJIIIJIJJJIIJJIJIIIIJIIII;

	public UIDrawCall.IIIIJJIJJJJJJIJIIJJIJJJJIJJIJIIIIIIIIIIIJJIIJJI IIIIIJIJIJJJIIJJIJIJIIIIJJIIIJJJJJJIJJJIIIIIJIJ
	{
		get
		{
			return JIIIJIIIIJJJJIIJIJJJJJIIJJJIJIIJIJIJIJJJJJJIJJI();
		}
		set
		{
			IJJJIIIIJIIJJIIJJJJJJIJJIIIJIJJJIIJIJIIIJIJJIII(value);
		}
	}

	public Vector4 JJJJJJIIIJIIIIJIIJIJJIJIIJIJJIIJIIIIJJIIJJIIIJI
	{
		get
		{
			return IIJIIIJJJIJJIIIIIJIJIIJIJIJJIJJJJJIJIJJJJJJIIJI();
		}
		set
		{
			IJJIJJIIIIJIIJIIIJIJIIIIIJIIJJIJIJJJJJIIJJIIJII(value);
		}
	}

	public Vector2 IIJIIJIIIIJIJJJJIIIJIJIIJJIJJJJJIJIIJJIJIIIJIII => JJJJJIIIJIJJIJIJJIJIIJJJIIIIJIJIIIIJJJJJJIJJJJJ();

			public int JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ
	{
		get { return mWidth; }
		set { mWidth = value; }
	}

			public int JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII
	{
		get { return mHeight; }
		set { mHeight = value; }
	}

			public Color IJJJIIJJJJIIIIIIIJJIJIIIJJIJIJJIIJJJIIIJJIJJIIJ
	{
		get { return mColor; }
		set { mColor = value; }
	}

	public override float IJIIJJIIJIJJJIJIJJJIIJJIIIJJJIIIJJJJIIJJIIJIIIJ
	{
		get
		{
			return IJJJJIIJJIJJJJIIIIIJJJIIJJJJJJJIIJJJJIJJJJIIJIJ();
		}
		set
		{
			IIIJIIJIIJJJJIIIJIJJIJJJJJIIIIIJIJIJJIIIJJJIJJJ(value);
		}
	}

	public float alpha
	{
		get
		{
			return IJJJJIIJJIJJJJIIIIIJJJIIJJJJJJJIIJJJJIJJJJIIJIJ();
		}
		set
		{
			IIIJIIJIIJJJJIIIJIJJIJJJJJIIIIIJIJIJJIIIJJJIJJJ(value);
		}
	}

	public bool IJJIIIIIIJJIIJIJIJIIJJJJJIIIJIJJJJIJJIIIJIJIJII => IIJIIIJIIJIJJJIIIIJIIJJIIIIIIIJIJIJJIJJIIJJIIJI();

	public bool JIJIJJIIIJIIJJIJJJIJIIIJJIIJJIJIIJJIJJIJJJJJJII => IJIJIJIJJIJIJJIJJJIIJJIIJIIJJJIIIJJJIIJIIIJIIIJ();

	public JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII JIJJJJJJIIJJIJIIIJIJIIJIIIJJJIIJJIIJJIIJJJIJJJJ
	{
		get
		{
			return JIJIJJJIJJIIJJJIIIIIJIIJIJIJJJJJJJIJIIIJJIJJJII();
		}
		set
		{
			IIJIJJJIIJIJIJJJIIIJJJIIJIJIJJJIIIJIIJJIIIJJJJJ(value);
		}
	}

	public JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII JJJJJIJIJJIJIJIIIJJIIIJJJIIIJJJJJJIIIJIJIIJJJJJ
	{
		get
		{
			return IJIJJJJJJIJJIJIJIJIJIIJIJIIJIJJIIIJIJIJIIJJIIJI();
		}
		set
		{
			IJIIJJJIIJIJJJJJJJIJJIJJIIIIIIIJIJJJJIIJJJJIJJI(value);
		}
	}

	public int JJJIJJIIJJJJIJJJJIIJJJIJIJJIJJIIJIJIIIIIIJJJJII
	{
		get
		{
			return JJJJJJJIJJIIJJIJJIJJIIJIJJJIIIIJIIJJIJIIJIJJIJI();
		}
		set
		{
			JIIJJIJJJJIIIIJJJIIIJIIJJJJJJJIIJJIJJJJIIIJIJII(value);
		}
	}

	public int JJJJIIIJJIIJIIJIIJJJJIJJIJJIJJJIJJJJJIIIJJIIIJJ => IJJJIJJJJJJIIIJJJJJIJJIJJJJIJJJIIJJIJIJIIJIIJII();

	public override Vector3[] IIJJJJIIIJIJIIJIJIIJJIIIIJIJJIIJJIJIIIIIIJJIIII => JIIIIIIIIIJIIJJIJJJJJJJIIIIIJJIIIJJJJIJIJIIJIII();

	public virtual Vector2 JIIIIJJJJJJJIJJIJJIJJIIIJIJJJJIJIIIIJJJJJIIIIIJ => JJIJJJIIJJIJIIIJIJIJJIIJIIJJIJJJIIJJIJJJJJJIJJI();

	public Vector3 IIJIJIIIJJJJJJIJIJJIIIJJIJIIIIIIJJJIJIIJIJJJJJI => JJIJIIIJIIJIIJIIIIJIIIIIIIJIIJJIJIJIIJIJIIJJIJJ();

	public override Vector3[] JIIIIIIIJIJJJJIJJIJIJIJJIIIIJJIIIJIIIJIJIJJJJJI => JIJJIJIJIJIIJJJJJIJIJIIIIJIIJIIJJJJJJJJIIJIJJJI();

	public Vector3 IIJIJJJIIIIJJJIJIJIJIIJIIJIIIJJJJIJJIJJJIIJIIJJ => IJJIIJJJJJJJIJJJIIJJJJJJJIIJIIJIJIIIJJIJJIIJJJI();

	public virtual Vector4 JJJIJJJJJIIIJIJJIIIJJJJIJJJIIIJJIIJIJIJIJIJIJII => JIJIIJIIJJJJJIJIIJJJIJJIJJIIIJJIIIIJIIJIJIJIIJI();

	public virtual Material IJIIJJJJJIIIJJJJIIIJJJJJIJJIJIJJIIIJJIIJJIIIIII
	{
		get
		{
			return IJJIIIIJIIIJIIJIJIIJJIIJJJIJJJJIJJJJIIJJIJJIIII();
		}
		set
		{
			IJJJJIIIIJJIJJIIJIJJJJJIJIJJJIIJJJJIJIJIIJJIJJJ(value);
		}
	}

	public virtual Texture JJIJJJJJJIJJJJJIJIIJJIJJJJIIIJIIJJJJIIIJJIIIIJI
	{
		get
		{
			return IJIIIJJIJIJIJIIJIIJIIIIJIIIJIIJIJIJIJJJIIJJJIII();
		}
		set
		{
			IIIIIIJJJIIIJJJIIJJJJJJIIIIIJIJJJJIJJIIJIJIIIJI(value);
		}
	}

	public virtual Shader IJIJJIJJJIJIJIIIJIIIIJIIJJIIJIIIIIIIIIJJIJJJIJJ
	{
		get
		{
			return IIIIJIJIJJIIIJIJIIIJJJJJIJJJJIJJIJIJIIIIIJIJJJJ();
		}
		set
		{
			IJIIIJJJIJJIJIJIJIIIJIJIIIJIIJJJIIJJIJJIJIIJJIJ(value);
		}
	}

	[Obsolete]
	public Vector2 JJJIIJIIIIJJIIIJIJJIJIIJJIJIIIJIIJIIIJIJIJJIIJJ => JIJJIIJJJIJIJIJIIIJJIIIIJJIIIJJJJJIJIIIIJJJIJII();

	public bool IJIJJIJIIJJIIIJJIIJJIJIJIJIIJIJJIIIJJIIIIIIIIIJ => IIIJIIJIJIJJIJIIJIIJJJIJIIIIJJJIIJJIIJIJJJIJJJI();

	public virtual int JIIIJJJIIJJJIIIIIJJJJJJJIIJJJJIIJJJIIJIIJIIJJJJ => IIJIJJJJJJJIJIIIJIIJJIJJIJJJJIJIIIJIIJJJJIJJIJJ();

	public virtual int JIJJJJJIJJIIJJJJJJJJIJIIIIJJIJIJJJJIJJIIJJIIIIJ => IJIIIIIIIIJIIIIIJIIJIJJJJIJJIIJIJJIJJJIIJIIJJJJ();

	public virtual Vector4 IJJJJJIIIJJIJJIIJIIJIJJJJJIIJIIIIJIIIJIIJJIJIJI
	{
		get
		{
			return JJIIIIJJJIJIIJIJIIJIJIIIIIIJJIIJIJIJIIJIJIIJIJJ();
		}
		set
		{
			IIIIJJJIIIJIJJJJIIJIJIIIIIIJJIJJIIJJIIIJIJIIIIJ(value);
		}
	}

	public virtual void JJIIJJIIJIJJJJIJIJJIIIJJJIIIJIJJJJJIJIJJJIJJJIJ(List<Vector3> IJJIIJJIIJIJIJIIIIIJIJIIJIJJJJIJIJIIJJIIIJJIJIJ, List<Vector2> IJJJIIJJJIJIJIIIJJIJIJIJIJJJJIIJIJJIJIJIJJIIJJJ, List<Color> IJIJIJJJJJJJIIIIJJIIIIJJJIIJJJJIJIJJJJIIJIJIJII)
	{
	}

	public Bounds JJIIJIIIJIJIIJIJIIIJIJJIJJJIJJIJIJJIIJJJJIIIJII(Transform IIJJIIJJJJJJJJIJJJJJIIIIIJIJJIIJIIJIJJJJIJJIJII)
	{
		return default;
	}

	public override Vector3[] JJJJJIJJIJJJJIIIIIIIIJIJIJIJIIIJJJIJIIIIIIIJIII(Transform JJJJJIJIJJIIIJIJJJJIJJJIIIJIIJJJIJIIIJJIIIJIIJJ)
	{
		return null;
	}

	public bool IIIJIIJIJIJJIJIIJIIJJJIJIIIIJJJIIJJIIJIJJJIJJJI()
	{
		return false;
	}

	public void IIIIIJIJIJJJJJIJIIIJJJJJIIJJIJIJJIJJJJIIIJJJIJI()
	{
	}

	public void IJJJIIIIJIIJJIIJJJJJJIJJIIIJIJJJIIJIJIIIJIJJIII(UIDrawCall.IIIIJJIJJJJJJIJIIJJIJJJJIJJIJIIIIIIIIIIIJJIIJJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void JIJIIJJJJJIIJJIJIJIIIIJJJIIJJIJJIIJJIJIIJJJIIII(Color JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJIIJIJIIIJJJIJIJJJIJIJIIJIIIIIJIJJIIIJIJIIJIJI()
	{
	}

	public virtual void IJJIJIIIIIIJIJJIJJJJJJJJJIJJJJIIJJIIJJJIIJJIIII(List<Vector3> IJJIIJJIIJIJIJIIIIIJIJIIJIJJJJIJIJIIJJIIIJJIJIJ, List<Vector2> IJJJIIJJJIJIJIIIJJIJIJIJIJJJJIIJIJJIJIJIJJIIJJJ, List<Color> IJIJIJJJJJJJIIIIJJIIIIJJJIIJJJJIJIJJJJIIJIJIJII)
	{
	}

	public Vector2 JJJJJIIIJIJJIJIJJIJIIJJJIIIIJIJIIIIJJJJJJIJJJJJ()
	{
		return default;
	}

	public static int JIIIJJIJIIJJIIJJIIJIIJJIJIJIJIJJJJJJJJIJIJIIIJJ(UIWidget JIJIIIIJJIIIIIJJJJJJIIIIJJIIIIJIIIIJJIJJJIIIIII, UIWidget IJIIJJJIIJIIJJJIIIJIIIJIJIIJJJJIIJJIIIJJJIJIIII)
	{
		return 0;
	}

	public override void IIJJIJJJIIJJJJJIIJJIIJIJIIJJJIJIIJJIJJIJJIJJJJJ(bool JJJJIJJJIJIJJJIJIIJIIJJIJIJIIJIJIIIIIJIJJIJIIJJ)
	{
	}

	public override void IIIJIJIIIJIIJJIJIJIJJIIJJJJIIJIIJIJIJJJJIJJJJJJ(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, float JJIIIIJJIIJJIJJIJIJIJJJJJIIIIIJJIJIIJJIJJJJJIJJ, float JJIJIJJIJJIJJIJIIIJJIIIIJJIJIIJIIIJJJJJIIJJJIII)
	{
	}

	public Vector3 JJIJIIIJIIJIIJIIIIJIIIIIIIJIIJJIJIJIIJIJIIJJIJJ()
	{
		return default;
	}

	public void JIJJJJIJJJJIJIIIJIJIIIJIJIIIJJJIIIIIIJIJIJIIJJJ(int JIJJJIJJJIIJIJJJJJJJJIJIIJJJJJJIJJJIJIIJIJJIJII, int JIJJJIJIJIIIJIJIIIJJIJIJIJJJJJIIJJIIIJJJJIIIJII)
	{
	}

	public bool IJIJIJIJJIJIJJIJJJIIJJIIJIIJJJIIIJJJIIJIIIJIIIJ()
	{
		return false;
	}

	public override float IJJJIJJIIIJJIJJJJJIIIJIIIJJIIJIJIJIIIJIIJJIJJII(int JJIJJJJJJIJIIIIIJJIIJIIJJIJIJJJIIIJIIJJJJJIIIIJ)
	{
		return 0f;
	}

	public virtual void IJJJJIIIIJJIJJIIJIJJJJJIJIJJJIIJJJJIJIJIIJJIJJJ(Material JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void IIJJIJJIJIJIJIIIIJIIJJJIIIIIJIJIJIIIJIIIIIJJJII(UIDrawCall.IIIIJJIJJJJJJIJIIJJIJJJJIJJIJIIIIIIIIIIIJJIIJJI JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected override void JIIIJIIJIIJIJJJIIJIJIIIJIJIJJIIJJIIJIIIJIIJJIII()
	{
	}

	public Vector3 IJJIIJJJJJJJIJJJIIJJJJJJJIIJIIJIJIIIJJIJJIIJJJI()
	{
		return default;
	}

	public void JJJIIIJJJIIIIIJJJIIJJJIIIIIJIJIIIJIJIIIIJIIJJJI()
	{
	}
	public Vector3 IIIJIIJIJJJIIJIIIJIJIJIJJJIIIJJJJIIJJIJIJJJJIJJ()
	{
		return default;
	}

	public Vector2 JIJJIIJJJIJIJIJIIIJJIIIIJJIIIJJJJJIJIIIIJJJIJII()
	{
		return default;
	}

	public virtual void JIJIIIIJJIIIJJIIIIJJJJIIJJIIIJJJIIJIIJJIIIJJJII()
	{
	}

	public UIPanel IIJJIIJIJIIJJIIIJIIJJIJJIIJIIJJJIIJIJJIJIJIIJIJ()
	{
		return null;
	}

	public Vector4 IIJIIIJJJIJJIIIIIJIJIIJIJIJJIJJJJJIJIJJJJJJIIJI()
	{
		return default;
	}

	protected void IIJIJIIJJJJJJJIIJJIJIIIJIIJJJIIIIJJJJJJJJIJJJJI(int JJIJJJJJJIJIIIIIJJIIJIIJJIJIJJJIIIJIIJJJJJIIIIJ)
	{
	}

	public bool JJJIJJIIIJIJJJJJIIJIJIJJJIJIJIIIJJIJJIIIJJIJJII()
	{
		return false;
	}

	public int IJJJJIJJJIJIIIIIJJJIJIJIIJIJJJJJJJJJJIJIIJJJJJI()
	{
		return 0;
	}

	public virtual void IIIIIIJJJIIIJJJIIJJJJJJIIIIIJIJJJJIJJIIJIJIIIJI(Texture JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected override void IIJJIIIJJJJJIJIJIIIJIJIJJIIJJIIIIJJIJJJIIIJIJII()
	{
	}

	private void IIJIIIJJJIJIIIJJIJIJJJIJJIIIIIIIJIIIIIIIJJIJJJI()
	{
	}

	public void IJIIJJJIIJIJJJJJJJIJJIJJIIIIIIIJIJJJJIIJJJJIJJI(JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public float IJJJIJJJJIJIIIJJJJIJIIIIIJJJIJIIJIJJJIJJJJIJIII(int JJIJJJJJJIJIIIIIJJIIJIIJJIJIJJJIIIJIIJJJJJIIIIJ)
	{
		return 0f;
	}

	public override float IJJJJIIJJIJJJJIIIIIJJJIIJJJJJJJIIJJJJIJJJJIIJIJ()
	{
		return 0f;
	}

	[DebuggerStepThrough]
	[DebuggerHidden]
	public static int JJJIIJJJIJJIJIIIIJIJIIJIJJJJJIIIJIJJJJIJJJIJIJJ(UIWidget JIJIIIIJJIIIIIJJJJJJIIIIJJIIIIJIIIIJJIJJJIIIIII, UIWidget IJIIJJJIIJIIJJJIIIJIIIJIJIIJJJJIIJJIIIJJJIJIIII)
	{
		return 0;
	}

	public UIDrawCall.IIIIJJIJJJJJJIJIIJJIJJJJIJJIJIIIIIIIIIIIJJIIJJI JIIIJIIIIJJJJIIJIJJJJJIIJJJIJIIJIJIJIJJJJJJIJJI()
	{
		return null;
	}

	protected override void OnDisable()
	{
	}

	public virtual Vector4 JIJIIJIIJJJJJIJIIJJJIJJIJJIIIJJIIIIJIIJIJIJIIJI()
	{
		return default;
	}

	public int IJJJIJJJJJJIIIJJJJJIJJIJJJJIJJJIIJJIJIJIIJIIJII()
	{
		return 0;
	}

	public void JJJIJIIIJJJJIJIIIIIJIJJIJIJJJJIIJJIJJJIJJJJJJII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IJIJJIJJJIIJJIJJJIIIIJIJJJJJJJJJIIJJJJIIIIJIIIJ()
	{
	}

	public float IJJJJIIJJIIIIIJJJJIJIJJIJIIIIIIIJJIJJJJIJJJIIIJ(int JJIJJJJJJIJIIIIIJJIIJIIJJIJIJJJIIIJIIJJJJJIIIIJ)
	{
		return 0f;
	}

	public virtual int IJIIIIIIIIJIIIIIJIIJIJJJJIJJIIJIJJIJJJIIJIIJJJJ()
	{
		return 0;
	}

	public Bounds JJIIJIIIJIJIIJIJIIIJIJJIJJJIJJIJIJJIIJJJJIIIJII()
	{
		return default;
	}

	public int JIIIJJJIIJIJIJIIJIIIJJJIJIJIJJIJIJIIIIJJIIIJJJI()
	{
		return 0;
	}

	protected override void JIIJJJJIIIIIJJIJIIIIJIIIIJJIJJJJJIJJJIJIJJJJJJJ()
	{
	}

	private void OnApplicationPause(bool JIJIIJIIIIJJJJJJIIJIJIIIIIJIIJJIJJJIJJIJJJJIIII)
	{
	}

	protected override void Awake()
	{
	}

	public bool IJJIJJJIIJJJIJIJJJJJIJJJJJJJIJJIJIIIIIIJJJIJJJJ(bool IJJIIJIIIIIJIJJJIJIJIJJJIIJIJIIIIIIIIIJJIIIIIJI, bool IIJIIIIIJIIJIIIIIIIJJIIJIIJIIIIJIJJIJIJIJJJJIII)
	{
		return false;
	}

	public virtual Vector4 JJIIIIJJJIJIIJIJIIJIJIIIIIIJJIIJIJIJIIJIJIIJIJJ()
	{
		return default;
	}

	[DebuggerHidden]
	[DebuggerStepThrough]
	public static int IJIIJIJJJIJJJIJJIIIIJIIJJIJJIIIIJIIJJJJIJIIJIJJ(UIWidget JIJIIIIJJIIIIIJJJJJJIIIIJJIIIIJIIIIJJIJJJIIIIII, UIWidget IJIIJJJIIJIIJJJIIIJIIIJIJIIJJJJIIJJIIIJJJIJIIII)
	{
		return 0;
	}

	public JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII JIJIJJJIJJIIJJJIIIIIJIIJIJIJJJJJJJIJIIIJJIJJJII()
	{
		return JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII.TopLeft;
	}

	public virtual void JIIIJIIIIIJIJIJJIIIIIJIJIIJIJIJIIIIJIJIIIIJIJJI()
	{
	}

	public virtual Material IJJIIIIJIIIJIIJIJIIJJIIJJJIJJJJIJJJJIIJJIJJIIII()
	{
	return mMat;
	}

	private void OnDestroy()
	{
	}

	public void IJJIJJIIIIJIIJIIIJIJIIIIIJIIJJIJIJJJJJIIJJIIJII(Vector4 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIIJJIIIIIJIIIIJJIJJJJIJIIIJJIIJIJJIIIIIJJJJJJJ()
	{
	}

	public void IIJIJJJJIIJJJIJJJJIJIJJIJIIIIJJJIIJIJJJJJJJIJII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public void IIIJIJJJIIIIIJJIIJJJIIIIIIJIJIIJIIJJIJIJIJJIJJI(Vector4 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool JJJJJJJIIIJIJIIIJJIJIJIJIJJJJJIIIIJIIJIJJIJIIJI(int IJIJIIIJIJIIJIIJIJJJJIIJJIIJIIIIIIIIIJJJJJIIJJI)
	{
		return false;
	}

	public bool JIJJJJIIJJJIJIJJIJJIIIIIIJJIIIIJJJJJJIJJIJJJIII(int IJIJIIIJIJIIJIIJIJJJJIIJJIIJIIIIIIIIIJJJJJIIJJI)
	{
		return false;
	}

	public virtual void IIIIJJJIIIJIJJJJIIJIJIIIIIIJJIJJIIJJIIIJIJIIIIJ(Vector4 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected override void JJJIJIJIJIIJJIJIIJJIIJJIIIJJJIIJIJJIIJJJJIJIIII()
	{
	}

	public int JJJJJJJIJJIIJJIJJIJJIIJIJJJIIIIJIIJJIJIIJIJJIJI()
	{
		return 0;
	}

	public virtual void IJIIIJJJIJJIJIJIJIIIJIJIIIJIIJJJIIJJIJJIJIIJJIJ(Shader JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII IJIJJJJJJIJJIJIJIJIJIIJIJIIJIJJIIIJIJIJIIJJIIJI()
	{
		return JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII.TopLeft;
	}

	public override Vector3[] JIJJIJIJIJIIJJJJJIJIJIIIIJIIJIIJJJJJJJJIIJIJJJI()
	{
		return null;
	}

	public void JIIJJIJJJJIIIIJJJIIIJIIJJJJJJJIIJJIJJJJIIIJIJII(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual int IIJIJJJJJJJIJIIIJIIJJIJJIJJJJIJIIIJIIJJJJIJJIJJ()
	{
		return 0;
	}

	public virtual Texture IJIIIJJIJIJIJIIJIIJIIIIJIIIJIIJIJIJIJJJIIJJJIII()
	{
		return null;
	}

	public void JJIJIJIJJIJIJJIJIJIJIJJIIJIIIIJIIIIIJIIJJIIJIJJ(List<Vector3> JIIJJJJJJIIJJIJIIIIIIJIIJIIIIIIJJJJJIJIIIJJJIJI, List<Vector2> JIJIJIIIJJIIIIJJIIIJJJIJIIJJJIIJJJJJJJJJJIJJJIJ, List<Color> IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ, List<Vector3> JIIJJIJIJJJJJJJIJJIJJJJIIJJJIIJIJJIJJIIJJJJIJII, List<Vector4> JIIJJJJJIIJIIJJIJIJIIIJJIJIIIIJIJIJJJIJIIJJIIJJ, List<Vector4> JJJIJJJIJIJJJJIIIIJJJJJJJJIJIIJJJJIIIIIJIIIIIII)
	{
	}

	public override void IJJIJIJJJJIJIJJIJJIJJJIJJJIIJJJIJIJIJIIIJJIJIII()
	{
	}

	public override Vector3[] JIIIIIIIIIJIIJJIJJJJJJJIIIIIJJIIIJJJJIJIJIIJIII()
	{
		return null;
	}

	public bool IIJIIIJIIJIJJJIIIIJIIJJIIIIIIIJIJIJJIJJIIJJIIJI()
	{
		return false;
	}
	public void JIJJJIJIJJIIJJJJJIJJIIJIIIJIIIIJIIJIJJIIJIJIJIJ(int JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public virtual void IIJIIIJIJIJJJJIJJIIJIIJJIIJJJJJIIIIIIJIJIJIIIIJ()
	{
	}

	public bool JJJIJJIIIJIJJJJJIIJIJIJJJIJIJIIIJJIJJIIIJJIJJII(int IJIJIIIJIJIIJIIJIJJJJIIJJIIJIIIIIIIIIJJJJJIIJJI)
	{
		return false;
	}

	public virtual Shader IIIIJIJIJJIIIJIJIIIJJJJJIJJJJIJJIJIJIIIIIJIJJJJ()
	{
		return null;
	}

	protected virtual void JJIIJJIIJIJIJIJIJIIIJIIIIJJJJIIJJIIJJIJIIIJJIII()
	{
	}

	public virtual Vector2 JJIJJJIIJJIJIIIJIJIJJIIJIIJJIJJJIIJJIJJJJJJIJJI()
	{
		return default;
	}
	public Color JIIIJJJJIJIJJJIIJJIIIIIIIJIJIIIIJJJIIIIIIJIJJJJ()
	{
		return default;
	}

	public void IIIJJJIJIJIJIIIJIIIIIIIIJJJJIJJJJJIJJJJJIJJJIJI(Color IJJIJIJIIIJIJIIIIIIJJIIJJJIIJIIJJIIJJJJJJIIJJJJ)
	{
	}

	public void IIJIJJJIIJIJIJJJIIIJJJIIJIJIJJJIIIJIIJJIIIJJJJJ(JJJJIJIJIIJJJIJJJJIIIIJIIIIJJJJIIIIIIIJIIIJIJII JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public bool JJJJJJIJJJIJIIIIIIIIJJIJIIJIJIJIIJJJIJIJJIJJIIJ()
	{
		return false;
	}

	public Color JIIJJIIIIJIIJJJIIIIJIIJJIJIJJJJIJIJIJIJJJJIIJJI()
	{
		return default;
	}
	public virtual void IJIJIIJJJIIIIJJJJJJIJJIIIJJIJIIIIIJJIJIJIIJIIJJ(Texture JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public override void IIIJIIJIIJJJJIIIJIJJIJJJJJIIIIIJIJIJJIIIJJJIJJJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
}
