using System.Collections.Generic;
using UnityEngine;

public class UIWrapContent : MonoBehaviour
{
	public delegate void IJJIJIJJJIIIIJIIJJJJJIJIJJIJJIIJIJJIJJIIJJJJJIJ(GameObject IIIJJJIJIJIIJJIJIJIJIIIJIJJJJIJJIIIJIJJJJIJJIII, int JIJJJJIIJIJJJIIJIIIJJIIJJJJIJJJIIJIJJIJJJIIJIJI, int IIIJIJJIIJIIIIJJIJJIJIJJIJJIIIIIIJIJJIJJIJJJIIJ);

	public int IJIIIIIIJIIIIJIJIIJJJJJIJJJIJJIIIIIIIIJIJIJIIJI;

	public bool JIIIIJJJIJIIJIIJJJJIJIJIIIJIIJIIJIJIJIJJIIIJJIJ;

	public int JIIIIJJJIIJJIIIIJIIJIIJIIJIJIJJIJJJIIIIJJJJJIJJ;

	public int JIJIJIJJJJIJIIIJIJIJJIJJIIJIJJIJJJJJIJJJIJIIIJI;

	public bool JJIIIJIJIIJIJIIJIIJIIIIIJJJIJIIIJIJJJJJJIIJJJJJ;

	public IJJIJIJJJIIIIJIIJJJJJIJIJJIJJIIJIJJIJJIIJJJJJIJ JIIIJIJIJIIJIJJJIIIJJJJJJIJIIIJIJJJIJIJIJJIIIIJ;

	protected Transform JIIJJIJJIIIJJIJJIJJIJJIIIIJIIJJIIIJJJIJJJJJJJJI;

	protected UIPanel IJJIIJJJIIJJJIIIIJIIJIIIJIIJIJIJIJIIJIJIIJJIJJJ;

	protected UIScrollView JIIIIIIJJIIIIJJIIIIJJJJIIJIJJIIIIJIJIJIIJIIJJIJ;

	protected bool IJIIJJJJIJJIJIJJJJIIJJJJJIIIJJIIJIIIJIIIIIIJIJJ;

	protected bool JJIIIIIJJIIIJJIIJJJJIJIJJIIJIJJJIJJJJJIJJIJIJJJ;

	protected List<Transform> IIIJJIJJIJJJIJIJJIIJJIJJIIIIIIJJJIIIJIJIJJIJIJI;

	protected bool IIIIJJIIIJJJIJIJJIJJIJJJJJJIIIIJIIJIJIJJIIIJJIJ()
	{
		return false;
	}

	public virtual void JIJIJIJJJJIIJJJIJJJJIJJJIJJIIIJJJIJJJJIJJIJIJII()
	{
	}

	private void IJJJIIJIJIJIJIJJJJIIJJJIIJJJJJJIJJIJJJIJIIIIJIJ()
	{
	}

	public virtual void JIJJJJJJIJIIJJJJJJJJIJJIIIJJJIJJIIIIJJIJJIJJIII()
	{
	}

	public virtual void JIJIIJJIIJJIJIIJIIIIJJIJJIJIJJJIIIJJIIIIJJIIIJJ()
	{
	}

	protected virtual void IJIIJJIJIIIIJIIJJIIJIJIJJIIJIJIJJIJIJIIJIJIJIJJ(Transform JJIIIJJIJIJJIIIJJJJJJIIIJIIJIJJJIIJJJIIJIIJIJIJ, int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}

	public virtual void IIJJJJJIIJJIJJIIIIJIIIJIIJJIIIJJJJJIIJIJJIIIJIJ()
	{
	}

	protected virtual void Start()
	{
	}

	protected virtual void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	protected virtual void JIIIIJJIJJIIIJIJJIJIIIIJIIJJIIIJJJJJJIJIIIIJJIJ(Transform JJIIIJJIJIJJIIIJJJJJJIIIJIIJIJJJIIJJJIIJIIJIJIJ, int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}

	public virtual void IJIJJJJJJIIJIIIIIJJIJIJJIIJIIJJIIIIJIIIIJJJIIIJ()
	{
	}

	private void JJJIJIIIJJIJJJIJIIJIIJJJJJIJIIIJIJIIJJJIIIJJIJJ()
	{
	}

	protected virtual void IJJIJIIJJIIJJJIIIJJIIIIJJJIIIIJJJIIJIJJJJJJIIIJ(UIPanel JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
	}

	protected virtual void JIIIIJJJIIJJJJIJIJJIJJJJIJIIIIIJJJJJIJIIJJJJJJJ(UIPanel JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
	}

	protected virtual void JIIIJIJJJIIIIIJJIIJJIIIIJJJIIIJIJJJIJJIJIIIJIJI(UIPanel JJIJIIJJIJJIIIJJJIIJIJJIIIJIJIJIIIJIJJIJJIJIIIJ)
	{
	}

	public virtual void JIIJJIJIJIIJIJJIJIIJJIJJJJIIJJJJIIJIIIJIJIJIJJI()
	{
	}

	public virtual void JJIIJJJJIIIIJIIIIIIJJJIIJJJJJIJIIJJIIJIJIIJIJJI()
	{
	}

	protected bool JJIIIJJIIJJIJJJIJIIJJIJIJIJIIIIIIIIIJIIIJIJIJII()
	{
		return false;
	}

	private void OnValidate()
	{
	}

	protected virtual void JJIIJIJIIIIIJJIJIIJIIIJIIIIIIIIJJIIJJIJIIJIJIIJ(Transform JJIIIJJIJIJJIIIJJJJJJIIIJIIJIJJJIIJJJIIJIIJIJIJ, int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}

	public virtual void IJIJIJJIIIJIIIIJJJIIIJIJIJJIIJIIIIIIJIJJJIIIIJI()
	{
	}

	public virtual void JIIIIJJJJIJJIIJJIJJIIJJIJIIIIJIIJJJIIIJJIIIIIII()
	{
	}

	protected virtual void JIJIIIIJIIIIIJJIJIJIJIIIIJJIJIIJIJJJIJJJJJIJIJI(Transform JJIIIJJIJIJJIIIJJJJJJIIIJIIJIJJJIIJJJIIJIIJIJIJ, int IIJJIJJJIJIIJIIJJJIJJJIIJJIIJJJIIJJIJJIJIJJIIJJ)
	{
	}

	protected bool JJJJIIIIJJJIJIJIJJIJJJJJIJIJIIIJJIIIJIJIIJIIIII()
	{
		return false;
	}

	private void IIJIJIJIIJJIIIJIJJJJJJIJIJIJJJJIJJIJIJIIIIIJIIJ()
	{
	}

	protected virtual void JJJJJIIJJIIIJIIIJJJJJIIJIJJJIJIIJIJJIJIIJJJJIJI()
	{
	}

	protected bool JJJJIJIJIJIJJJIIIJIJIJIIIJIJIJJJJIJJIIJIIJJIJII()
	{
		return false;
	}

	protected virtual void IJIIJJIJJJIJIJJJIIJIJIIJJJJJIJIJJJJIIJIIJIJJJJI()
	{
	}
}
