using UnityEngine;

public class UpdateManager : MonoBehaviour
{
	private static UpdateManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	private int IIJJJIIIIJIJJIJJIIJIIIJJJJJIIIJIJIJIIIJIJJIIIJJ;

	private nTimer[] JJIJJIJIJIJIIJIIJIIIJIJIIJJIJIIIIIIJIJIJJIJIJJI;

	public static void IJJJJIJJIJJIJIJJIIJIIJIJJJIIJJIJIIJJIJIJIJIJIII(nTimer IJJJIIJIJJIJJJIJJJJJIIJJIIJJIIIIJIJJJJJIIIJJJII)
	{
	}

	private void IIJJIIIJJIJIIJIJIIIJIIJIIJIJJIIJJIIIIJIJJIIIJJI()
	{
	}

	public static void JIIJJIJJJJJIJJJIIJIJJJIIIJIIIJJIJIJIIJIIJJJIJJI(nTimer IJJJIIJIJJIJJJIJJJJJIIJJIIJJIIIIJIJJJJJIIIJJJII)
	{
	}

	public static void IIJIJIJJJJIIJIIIIIJJIJJIJJJIJJJIIJIIIIJJIIIJIII(nTimer IJJJIIJIJJIJJJIJJJJJIIJJIIJJIIIIJIJJJJJIIIJJJII)
	{
	}

	private static void IIJIIJJIJIIIIIIJIJJIJJIJIJIIJIIIIIIIJJIIJJIJIJJ()
	{
	}

	public static void JIJIIIJJIJIJJJIIIIJIIIJIIJJJIJJIJIJIJIJIIIJJIJI(nTimer IJJJIIJIJJIJJJIJJJJJIIJJIIJJIIIIJIJJJJJIIIJJJII)
	{
	}

	private void IJJJJJJIJJIIIIJIJIJJJIIIJJIIIIJJIJIIJIIIIJJJJIJ()
	{
	}

	private void Awake()
	{
	}

	public static void IJJJJIJJIJIJIJIIIJIJJIIIJIIIJIJJIJJIIJIJJJJIIJI(nTimer IJJJIIJIJJIJJJIJJJJJIIJJIIJJIIIIJIJJJJJIIIJJJII)
	{
	}

	private void JIJJIJJJIJJIJIJIJIJJJIJJJJIJJIIJJJJJIIIJIJIIIJJ()
	{
	}

	private void IJJIJJJJJIJIIIJJJIJIJIIIIJJIJIIJIIJIJJIIIJJIJIJ()
	{
	}

	private static void JIJJJIJJIIJJIIIJJJIIIJIIIJJIIIJJIIJJJJJIIJJJJIJ()
	{
	}

	private void JJIIIJJIIJJIIIJJJIJIIJIIJIJJIIJJIIJJJIJIJIJJIIJ()
	{
	}

	public static void IIJIIJIIIJJJJIIIIJIIJIIJJIIJJJJJIIJIJIIIIJIIIJJ(nTimer IJJJIIJIJJIJJJIJJJJJIIJJIIJJIIIIJIJJJJJIIIJJJII)
	{
	}

	public static void JIIJJJIJIIIJIIIIJJIJJIJJJJJJIJJIJIJJJIJJIJIJIII(nTimer IJJJIIJIJJIJJJIJJJJJIIJJIIJJIIIIJIJJJJJIIIJJJII)
	{
	}

	private void Update()
	{
	}

	public static void IJIIJIJJIIIJIJIIJIJJJJJIIIJIIIIIIJIIIIJJIIJIIJI(nTimer IJJJIIJIJJIJJJIJJJJJIIJJIIJJIIIIJIJJJJJIIIJJJII)
	{
	}

	private static void IIIJJIJJJJIJIIJIIIIIIIIIJJIIJJIJJJIIIJIJJJJIJIJ()
	{
	}

	private static void IJJIJJJIJIJJIJIIJJIIJIIJJIIJJJJJIIIJJJJJJJJIJJJ()
	{
	}

	public static void JIJIIIJIIJJIJJIJJIIIIIJJJJJIJIJIJJJIJJIJJJJIIII(nTimer IJJJIIJIJJIJJJIJJJJJIIJJIIJJIIIIJIJJJJJIIIJJJII)
	{
	}

	private static void IIIJJIIJJIIIIIJJJIIIIIIIJIIIJJJIIJJJIJIJJIJJJJI()
	{
	}

	public static void JIIJJJJJIJJJJIIJJIIJIJJIIIIIJIIIIJIJJIIIIIIIJII(nTimer IJJJIIJIJJIJJJIJJJJJIIJJIIJJIIIIJIJJJJJIIIJJJII)
	{
	}

	public static void JJJJJIJJJIJJJJIIIIJJJJJIIJIIJIIIJIJIJIIIJJJJJJJ(nTimer IJJJIIJIJJIJJJIJJJJJIIJJIIJJIIIIJIJJJJJIIIJJJII)
	{
	}
}
