using System.Runtime.CompilerServices;
using Photon;
using UnityEngine;

public class VIPMode : Photon.MonoBehaviour
{
	private sealed class IIJJJJJIIJJJIIJJJJJJJIIIJIIJJJJJIIIJJJJJIJJJJIJ
	{
		public VIPMode JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII;

		internal void JIJIJIIIJJIIJIIJJIIJJJIJIJIJIIIIJIIJIIJJJIIJIIJ()
		{
		}

		internal void JJJJJJJJIJIJIIIJIJIJJIIJIJJJIIIJIJJJIJJIJJJIJII()
		{
		}

		internal void IJIJJIIJIJIIIJIIIJIIIJIJIIIJJJIJIIIJIJIIIJJJJIJ()
		{
		}

		internal void JIJIJJJJJJIJJIIIIIIJJIIJJIJIIIIJJJJIJJJJJIJJJIJ()
		{
		}

		internal void IJIJJIJJIJJIJIJJJJIIIIIJJJIJJIJJIJIIIJIIIIJIIII()
		{
		}

		internal void IJJJJIIIIIIIIJJJIIIJJJJJIJJIIJIJIIJIIIIJIJIIJIJ()
		{
		}

		internal void IJIIIIJIJIIJIIJJJJIIIJJJIIJIIIJIIJJIIJIJIIIIIJJ()
		{
		}

		internal void IIJIJIIIIIIJIIJIJJIJIIIJIJIIJIIIIIIJIIJIIIIIIJJ()
		{
		}

		internal void IIJJJJIJIJIJIJJJJIJJIIJJJJJJIJJIIIIIJIIIIIJJIII()
		{
		}

		internal void JIIIIJIIJIJJJIIJIIJIJIIJIIIIIJIIJIJIJJIIIJIIIII()
		{
		}

		internal void JIJIIIIIJIJIJJIIJIIJIJIIJJIIJJJJJIJIIJJIIIIJIIJ()
		{
		}
	}

	private sealed class JIJIIJJIIJIJIIJJJIJIJJJIJJIIJJIJIJIIIIIIJIIJJJI
	{
		public float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

		public JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ;

		public VIPMode JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		internal void IIIJJJIJIIIJJJIIIIIJJJIIIJIJJJJJJJIJJIIIJIJIJJJ()
		{
		}

		internal void JJJIIIIJIJJJIJJJIIJIIJJIJIIIJIIIIIJJIJJJJJJJJIJ()
		{
		}

		internal void IIIJJJJIJIIJIIIJIIIJJIIIJIJIIJIIJJJJIJIJIJJIJJI()
		{
		}

		internal void JJIJIJIIIIJJJJJJIJJIIIIIJIJJIIJIJIIJJIIJIIJIIII()
		{
		}

		internal void IJIJIIJJJIJJIIIJJJIJJJIJIIIJJIIIIIJIJIIIIJJJJII()
		{
		}

		internal void JIJIJIJIIIIJIIIIIJIIIIIIIIJIIIIJIIIIJIJIJJIJIII()
		{
		}

		internal void IJIJJJJIIIJJJIJJJJIIIJIJIJIJIJJIJIIJJIIIIJJJJII()
		{
		}

		internal void JIJJIJJJJJJJJJIJJJJJJJJIIJJIIJJJJJJIIIJJIJIJIJJ()
		{
		}

		internal void IIIIIJIIJIIJIIIJIIIJIIIIIJIIIIJIIJIJJJJJIJJIIIJ()
		{
		}

		internal void JIIJIJJJIJIIJJIIIIIJJIJJIIIIJJIIJIJIIJIIJJIIJII()
		{
		}

		internal void IJIIJJJIIIIIJIIIIJJIIIJIIJJIJJIJJIJIIIJIJJJJJJJ()
		{
		}

		internal void IIJJJJJJJIJJJJIJJIJIIIJIJJJJIJIJIJJIIIJJIIJJIIJ()
		{
		}

		internal void IJJJJIIJJJJJJJIJIIIJJIJIIJJJJJJJJJJIIJJJIIIJJIJ()
		{
		}

		internal void IIIIJJIIIIJIIIIJIJIJJIIJJIIIIIJIJIIIIIIIIIJIJJI()
		{
		}

		internal void IJJIJIIIJIIJIJIJIJJIJJJIJJJIIJJIJJJIJJJIIIJJIIJ()
		{
		}

		internal void JJIIJJIJJIIJJJJJIJIJIIIIIIJJJIIIIIIIIIJIJIJJJII()
		{
		}

		internal void IJJIIJIIJJJIJIIIIJIIIIIIIJJIIJJJJJIIIIJJJIIIJJI()
		{
		}

		internal void JIIIIJJJIJJIIJJJIIJIIIJIIJIIJJIJIIIIJIIIIIIIIJI()
		{
		}
	}

	public Transform JIJJIIJJJJIJIJIJIIJJJIIIIJIIJJJIJIJIJIIJJJIIJJI;

	private int JIJIIIIJIJIJJJJIIJIIJJJIIIJJIIIJIJIIJJIJJIIIIJI;

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIJJJIJJJJIJIJIIJIIJJJIIJIJIIIIIJIJIJIJIJIJJJJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void JIIJJIJJIIJIJIIJIJIJJIIIIJIJJIIIJIJJIJJJIIIIJJI()
	{
	}

	private void Start()
	{
	}

	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJJIIJJJIIIJJIIJJJIIIIIIJJJIIJJJJJIIJJJJIIIJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIIJIIJJIJIJJIJIJJIJIIJIIJJJJIJJIIIIJIIIJIJIIJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJIIIJJJJJJJJIJJIJJIJIJIJIIJJIJJJIJIIIIJIIJIIIJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJJIJIIJIJIJIIJIIJJJJJIJJJIIJJIJJJIJJIIIJIIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJJIJIJIJIIJIJIJJJIIIIIIJIJIIIIJJIJIJJJIJJJIII(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	private void JIIIIJIJIJIIJIIIIJIJJIIIIIIIIJJJJIIJIJJJJIIJIII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIIIJIIIJJJJJJIJIIIIJJJJIIJIIIJJIJIJIIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIIJJJIJJJJIJIJJJJIJIJJJJJIIJIIIJIJIJJJIJIIJJJJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void JIJIJIIJJJJIJJJJJJIIJIJIIJJJJIIIIIIIIIJJJJJIJJJ()
	{
	}

	private void IJIJIJJIJJJIIJJIJJJJJIIJJIJIIIIJIIJIIJIJJJJJJJI()
	{
	}

	private void IIIJIJJJIIIJJIIIJIJIJIIJJIJJJIJJIIJJJJJIJIIIJJI()
	{
	}

	private void IJJJJIIIIJIIIIIJJIIJIIIJIJJJJJJJJJIIJIIIIIIJIJJ()
	{
	}

	[CompilerGenerated]
	private void JIIIJIIJJJIJJIJIJJJJJJIJIIIJJJIJJIIIJJJIJIJIJJI()
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void JJJIJIIIIJIJJIJJJIJIJJIJJIJJJIIJIIIIIJJIJJIIIII(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	[CompilerGenerated]
	private void IIJIJJIJIJIIIIIJJJIJIIIIJJJJJIJIJIIIJJJJJJIJJIJ()
	{
	}

	private void JIIIJIIJIJIIIIIIIIJJJIJIJJIIJIIJIJJJJJJIIIJJJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnDisable()
	{
	}

	private void JIIIIIIJJIJJJIJIJIIIIJJJJIIJJJIIIJJJJIIIJIIIIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public void OnEnterTrigger()
	{
	}

	private JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII[] IJJIJJJIJJJIIJJIIIJIIIIIIIJIIJJJIJJIIJIJIIIIIJJ()
	{
		return null;
	}

	private void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void JIIJIJJIIIJJIJIIJJIJIIIJIJJIJIIIIIJIJJJIIJIJIIJ()
	{
	}

	private void IIJIIIIJIJJIJJIIIJIIIIJJJJJJJIIIJIJIJJIJIIIIIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJIJJJJJIJIIIJJJIJIJIIIIJJIJIIJIIJIJJIIIJJIJIJ()
	{
	}

	private void Awake()
	{
	}

	private int IJJIIJJJIIIIIJJJIJJIIIJIIIJIIJJIJIIIIIIJJIJJJIJ()
	{
		return 0;
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}

	private void IJIJIJJJIIIIJIIIIIJIIIJIIJJIJJJJIJJIJJIIIJJJIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void JJJIJJJIJIJJJJIJJJJIIIIJJIIIJJJIJJJIIJJIJJIIJII(JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJIIIIJJIJIIIJJJIJJJIIJJIJIIIJIIJIJIJJJIJJJJIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void JIIJJJIJJJIIIJJJJIIJJJIJJIJJJIJIJJIJIJJIIIJIIII()
	{
	}

	private void OnEnable()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII()
	{
	}

	private void IIJJIJIJIJIJJJJJIJJIIIIIIIJJIIIJJIIJJJIJIIJJJII()
	{
	}
}
