using UnityEngine;

public class vp_Bob : MonoBehaviour
{
	public Vector3 IIJIIIJJIIIIIJJIIJJIIIIJIIJIJJJJIJJJJIJJJIJIJJJ;

	public Vector3 JJIIJIIIIIJIJJIJIJJJIJJIJJJIJIIJIJJIIIJJIJJIJJI;

	public float JJJJJIJJJJIJJJJIIIIJIJJJJJIIIIJIJJIIJIJIIIIJJIJ;

	public float JJJJIJJJJJIIIIJJJIIIJIJJIJIJJJIIIJIIJIJIIIIIJJI;

	public bool IJIIJIIIJJIIIJJJJIIIIIIIIJIJJJIJJJJJJJJJIJJIJII;

	public bool JJIIIIIJJIIJJJIIIIIJJJIIIJIJIIJIJIJJIJJJIIJIIIJ;

	protected Transform IJJIIJIJJIIIIIIJIJJIIJJIJIIJIIIJIJJJIIIIJJJJIJJ;

	protected Vector3 JJJJIJIIJJIJJIIIJJIIIIIIJJJIIJJJJJJIJIJIIJJIJIJ;

	protected Vector3 JJJJJJIJJJIJIJJJJIJIIJIJJIJJIJJJIJJJIIJIJIIJIJJ;

	protected virtual void JIJJIJJJIJJIJIJIJIJJJIJJJJIJJIIJJJJJIIIJIJIIIJJ()
	{
	}

	protected virtual void IJIJJJJJIIJIIJIJIIIJJJIIIJIJIJIJJIJIJJJJJIJJJJJ()
	{
	}

	protected virtual void JIJJJJIIIJIIIIJIJJJJIIJJJIIJJIIJJJIIIIIIIJIIIJI()
	{
	}

	protected virtual void JIJJJJIIIIJJJIIIJJIJIJJJIJIJJJIIIIIIJIIIJJJJIIJ()
	{
	}

	protected virtual void JJIJJIIIJIJIJIJIJIIJIJIJJJJIIIIJJIIIJIIIJIIIIJI()
	{
	}

	protected virtual void Awake()
	{
	}

	protected virtual void OnEnable()
	{
	}

	protected virtual void IIJJIIIJJIJIIJIJIIIJIIJIIJIJJIIJJIIIIJIJJIIIJJI()
	{
	}

	protected virtual void JIJJIIIJJIJIIIIIJIIJIIIIJJJIJIIIIJJJJJJJJIIIIIJ()
	{
	}

	protected virtual void IJJIJIJIJIJIJJIJIIIJIJIJIJJIIIJIIJJIIIIJIIIJJJI()
	{
	}

	protected virtual void JJIIIJJJIIJJIJJJJJIJJJJIIJIIJJJIJJIIIJJJJJJIJIJ()
	{
	}

	protected virtual void JIJJJIIIIIJIJJIIJIJIIIIJIJIIJIIIIJJJIIJJJIJJJIJ()
	{
	}

	protected virtual void JJJIJJJJJIIJIJJJIJIIIIJJIJJJIJIIJJIIJIIJJJJIIJI()
	{
	}

	protected virtual void IIJJJJJIIJJJJJJJJJIIIIJIIJJJIIIIIJIIIJIIJIJJIJJ()
	{
	}

	protected virtual void JIIIIIJIJJIIIIIIIJJIIJJJJIIJJJJJJIIJIJJJJIIIIJJ()
	{
	}

	protected virtual void JIIIJJIJIJJIJJJIIIIJJJIJIJIJIIIJJJJIJJIIIIJJIII()
	{
	}

	protected virtual void JJJIIIIJIIJJIIJIIIJJJIIJIIIIIJIJJIJIIIIJIJJIIJJ()
	{
	}

	protected virtual void IJIIIJJJIIJIIJIIJJIJIJJJJJJIIIIIIIJIJJJJIJJIIJI()
	{
	}

	protected virtual void Update()
	{
	}

	protected virtual void IIJIIJJJIIJJJIIIJJIJIJJIIJJIIIJIJJJIJJIJIJJIJJI()
	{
	}

	protected virtual void JIIIJJJJIIIJJJIJJIJJJJIIIJIIIIIIJIIJIIIIIIJIJII()
	{
	}
}
