using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class vp_Component : MonoBehaviour
{
	public bool IIIIJIIIIJJJJJJJIIIJJIIIIJJJJJJIIJJJJIJIIJJIJJJ;

	protected JJJJIJJJJJIIJJJJJIIIIJIIJIIIIJIIJJIJJIIJJIIIJIJ IJIJJIIJJJIJJJJJIIIIJIJIIJIIJJJIJIJJIIJJIJIJIJI;

	[NonSerialized]
	protected IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII IJJJJIJJJJIJIJJJIIJJIIJJJIIJJIIIJIIJJJJIIIJIJII;

	protected bool JJJJJIJIIIIIJIJIIIIIIJJIIJJIIIIIIJJJIJJJJIIIJII;

	protected Transform IJJIIJIJJIIIIIIJIJJIIJJIJIIJIIIJIJJJIIIIJJJJIJJ;

	protected Transform IJIIJIJIIIJIIJIJIJJJJIIIIIIJIIJIIIJIIIJIIIJJJIJ;

	protected Transform IJIJIIIJIIJJIIIIIIIIJJIJIIIJJJIJIJJIJJJIJJIJIJI;

	protected AudioSource IJJJIIJIJIJJJIIIIIIJIIJIJJJJIIIJIJJJIJIIIIIIIJI;

	protected Collider JIIIJIIIIIIIJIIIIIIIIIJIJIIIIJIIIIIJIJJJJJIJIJJ;

	public List<IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII> IJIIJIIIIIIJJIJIJIIIJJJJJJJJIIIIIJIIIJIJJIJIJIJ;

	public List<vp_Component> IJIJJIIJIJJIJIIJIJIJJJIIJIIIIJJJIJJIIIJJIIJIIJJ;

	public List<vp_Component> JJIJJIJJJIJJIIJJIIJIIJJIIIJIIIIIJJIJJIIIIIJIJJI;

	public List<vp_Component> IJJIJJJIIJIJJIIJJJJJIIIJJJJJIJIJIIIIJIJIIJJIIJI;

	public List<Renderer> JJJIIIIJIJJIIIJJJJJJJIIJJJJIIJIJIIJIJJIIIJIIJJJ;

	public List<AudioSource> JIJJJIJJIJJJIIJIIJJJJIJJJIJIIIIJIJJJIJIIJJIJJIJ;

	protected int IIIJIIIIJIIIIIJJIJIIIJJIIJJJIIJJIJJIJJIJIJIJJIJ;

	public JJJJIJJJJJIIJJJJJIIIIJIIJIIIIJIIJJIJJIIJJIIIJIJ IIJIIIJJJJJIIIJJIIIJJJJJJJIIJJIIIIIIIIJIJJJIIIJ => JJJJIJIJJIJJIJJIJIJJJIJJJJJIJIJIJIJJJIJJJIJIIJJ();

	public IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII JJIIJJJJJIIIJJIJIIIJJIIJJIJIJJJIJIJIJIIJIJJIJII => JJJIIJIJIIIJJJJIIJJJIIIJIJJIIJJIIIJIIIJJJJJIIJJ();

	public float JIIIJIIJIJJIJIIJIIJJIIJJIIJJIJJIJJJIJIIJJJIIIII => JIIJIJIIIIJJIJJJIIIJIJIIIJJJJIJIJJJIJIIIJJJJIJJ();

	public Transform JJIJIIJIJJJJJJIIIIJIJIJIIIIJJJIIIJIIJIIJIJJJJIJ => IJIJIJJJJJIIIIIJJIIJJJJJJJIIIIIJIIJIJJIJIJIJIIJ();

	public Transform IJJJIJIJJJJIIJIIJIIJIJJIIJIJJIJJIIIIIIIJIJJJIJJ => JIJIIJIIIJIJIIIJJJJJIIIIIIIJJIIIIJIIJJJIIIIIJJJ();

	public Transform JIIIIIJJJJJJJJJIJJIIIIIIJIIIJJIJIIJIIIIIIJJIJJI => JIIIIJIIJIJJIIJJIIJJIIJJJIIIIJJIIIJIIIIIJJJJIII();

	public AudioSource JJJJJIIJIIIJJJIJIJJJIIJJJJJJJJIIJIIJJIIIIJJIJJI => IIIJJJJIIJIJIIJIIJJIIJJIIJJIIJJJIIIIJIIJJJJJJJI();

	public Collider JIJIJIJJJIJJIIJIJIIJJJIIJIIJJIJIIJJIIIIJIIJJJJJ => JJJJJJIIJJIIIJIJIIJIJIJIIIJIIJJJJJIIIJJIIJJIIIJ();

	public bool IJIIIJIIIJIJJJIIIJJIJJJJJJJIJIJJIIJIIIJJJJIIJJJ
	{
		get
		{
			return JIJIJJJIJIIJJJIIJIJJIJJIJIJIIJIIIJJIIIJJJJJIJJJ();
		}
		set
		{
			JJJJJJIJIIJJJJIJIJIJJJJJJIJIJJIIJJJIJIJJIJIIJJI(value);
		}
	}

	public Collider JJJJJJIIJJIIIJIJIIJIJIJIIIJIIJJJJJIIIJJIIJJIIIJ()
	{
		return null;
	}

	public void JJJJJJIJIIJJJJIJIJIJJJJJJIJIJJIIJJJIJIJJIJIIJJI(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIJIIIIIIIJIIIJJJJJJJJIJIJJJJIJJIIJJIIJJIJJJJIJ()
	{
	}

	public void IJJIIIIIJIJJIIIJIJJJIIIJJIIJIIJJIJJIJJIJIIIJJIJ()
	{
	}

	public virtual void IJIIJIJIJIJJJJJJJIJIJIIJIIJIIIIIJJJIJIIJJJIJIII()
	{
	}

	public virtual void JJIIIIJJIIJIJIJIJJIJJIIJIJJJJJJIIJIJJJJJJJJJJIJ()
	{
	}

	public JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI IIJJJIIIIJIJJJJIIJIJJJJJJIJJIIIIIIJJIIJJJIJJJJI(string IJJJJIJIJJIIIIIJJJIJJIIJJJJIIIIJJIJIIIIIIIJIIIJ)
	{
		return null;
	}
	public AudioSource JJJJJJJIJJJJJIJJJJIJIIIJIIJIJJJIIIJIJIIJJIIJJJI()
	{
		return null;
	}

	public void JIJJJIIIIIIIIJJJIJJIIJIJJIIIJJIIIJJIIIJIJIJJIJI()
	{
	}

	protected virtual void IIIJJIJJJJIJIIJIIIIIIIIIJJIIJJIJJJIIIJIJJJJIJIJ()
	{
	}

	public void JIJIJJIIJJIIIIIIIIJJIIJJIJJIIIJJJIJIIJIJIIIIJII()
	{
	}
	public IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII JJIJIJJIIJJIIJIIIJJIJIJJJIJJJIIIIIJJIJIJJIIJIJJ()
	{
		return null;
	}

	public virtual void IIJJJJIIIIIJIJJIJJJJIIJIJIIIJJIIJJIJIJJIJJIIIJJ()
	{
	}

	protected virtual void OnDisable()
	{
	}

	public void JJIJJIJJIJJIJIJIIIJJIIJJJJJJIIIJJIJJIJJJIIJIIJI()
	{
	}

	public void IJIIIJIIJJJJIIIIJJJIJIJIIJJIJIJJIIIJIJJJIJIIIIJ()
	{
	}

	[CompilerGenerated]
	private void IIIJJIIJJIIIJJIIJIJIJJIJJJIIIJJJJJIJIJJJJIJIJII()
	{
	}

	public void IIIIJIJIIIJIJJIIJIJJJJJJJJIJIIIJJJIJJIJIIIJJJJJ()
	{
	}

	public void JJIIIIIJIIJJIIIJIIJIIJIJIIIJIJIJJIJJJIJJJIJIIIJ(bool JIJIJJIIJIIJIJIJJJJJIIIIIJIJJJJIIJJIJIIIIJIIJJI = true)
	{
	}

	protected virtual void OnEnable()
	{
	}

	public void IIIJJJIIJIJIJIJIIIIJJJIJJJIJJJJJIJIJJJIJJJIIJJI(string IIJJIJJJJIJIIJIIJJJIIIJIIIIIIIJJJJJJIJJJIJJJIIJ, bool IJJJJIIIIJIJIIIIIJJIJIJJIIIJJIIIIIJIIIJJJIIIIII = true, bool JIJJJJIJIIJJJIIIJIJJJIJIJJJJIIJIJJIIIIJJIIIJJIJ = false, bool IJIJIIJJJIJJIJJJJJIJJIJIIJJJIIJJJJJJIIIJIIIJJJI = false)
	{
	}

	public AudioSource IIIJJJJIIJIJIIJIIJJIIJJIIJJIIJJJIIIIJIIJJJJJJJI()
	{
		return null;
	}
	public Transform IIIJJIJIIIJIJIJJIIIIJJIIIIJIJJJJJJIJJIIJIIJJIJJ()
	{
		return null;
	}

	protected virtual void Start()
	{
	}

	public float JIIJIJIIIIJJIJJJIIIJIJIIIJJJJIJIJJJIJIIIJJJJIJJ()
	{
		return 0f;
	}
	public bool IIJIIJJJJJIIIIIJIJIJIIIJIIJIIJJIIIJJJIJIIIIIJII()
	{
		return false;
	}

	public void IIJJIJIJJJJIJIIJIIJIJJJIIJJJIIIJJIIIJJJJJJJJJJJ(bool JIJIJJIIJIIJIJIJJJJJIIIIIJIJJJJIIJJIJIIIIJIIJJI = true)
	{
	}

	public JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI JIJIIJJJJJIIJIIIIIIIJJJIJJJIJJJIJJIIIIIJIIIIIJJ(TextAsset JIJIJJJJIJJIJIJIJIJJIIJIJJJIJIIJIIJJIIJIIIJJIIJ)
	{
		return null;
	}

	public JJJJIJJJJJIIJJJJJIIIIJIIJIIIIJIIJJIJJIIJJIIIJIJ JJJJIJIJJIJJIJJIJIJJJIJJJJJIJIJIJIJJJIJJJIJIIJJ()
	{
		return null;
	}

	public void IJIIIIJJJJJJIJIIJIIIJJIIIIIIIIIIJJJIIIIIJIJIJII()
	{
	}
	public Transform JIIJJJJJIIJIJJIJIJJIIIJIJIJIIJIIIJIIJJJIIIJJIII()
	{
		return null;
	}

	protected virtual void Update()
	{
	}

	protected virtual void FixedUpdate()
	{
	}

	public Transform JIIIIJIIJIJJIIJJIIJJIIJJJIIIIJJIIIJIIIIIJJJJIII()
	{
		return null;
	}

	public void JIJJJJJIIIIIIJJIIJJIJIJJJIIIIIJIIJJIIJJIJIJIIII(JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI JIJIIIJJIIJJJJIJIJJJIJJJJIIIIIJIJJJIJJIIJIJJJII)
	{
	}

	public virtual void IIJJIIJIIJIJJIJJJJJJJIJJJIJIIIIJJIJJJJIIIIIIIIJ()
	{
	}

	protected virtual void LateUpdate()
	{
	}

	public Transform IJIJIJJJJJIIIIIJJIIJJJJJJJIIIIIJIIJIJJIJIJIJIIJ()
	{
		return null;
	}

	public void IJJIIIJJIJJJIJIIIJJIIJJJJJIJIJJJJIJJIJJIJIIJIJJ()
	{
	}

	public JIIIIJJIIJJJJJIJIIIIJJJJIIIJIJIIIJJIJJIJJJIIIJI IIJJJIIIIJIJJJJIIJIJJJJJJIJJIIIIIIJJIIJJJIJJJJI(TextAsset JIJIJJJJIJJIJIJIJIJJIIJIJJJIJIIJIIJJIIJIIIJJIIJ)
	{
		return null;
	}

	public IIJJIIJJIJJJJJJIJIJJIJJJJJJJJJIJJIIIJJJIJIIJIII JJJIIJIJIIIJJJJIIJJJIIIJIJJIIJJIIIJIIIJJJJJIIJJ()
	{
		return null;
	}

	public void IIJIJIJJJIIIJIIJIIJJJIJIJIIJIJJJIJJJJIIIJIJIJII()
	{
	}

	public void JIIJJJJJJIIIJIJJIIIJJIJIJJIJJJJJIIJJJJIJIIJJJJJ()
	{
	}

	protected virtual void Awake()
	{
	}

	public void JJIJJIJIIIIIIIJIJIIIJJJIIIJIIIJIIJJJJJJJJJIIIJJ(bool JIJIJJIIJIIJIJIJJJJJIIIIIJIJJJJIIJJIJIIIIJIIJJI = true)
	{
	}

	public bool JIJJJJJJIJIJIJJJIJJIIIJIIIJIJJJIJIJIIIIJIJIJJIJ(string JIIIJJIJIJJJIJIIIJJIIJJIJJJJJJJIJIJJJJJIJJJJJJI)
	{
		return false;
	}

	public void JJIIIIIIJIJJIIIIIJJIIIJIIIJIJJJJJJJJIIIJJJIIJIJ()
	{
	}

	public Transform JIJIIJIIIJIJIIIJJJJJIIIIIIIJJIIIIJIIJJJIIIIIJJJ()
	{
		return null;
	}

	public virtual void JJJJIJJJJJJJJIJIJIIIIJIIJJJJIIIJJJJJIIJJJIIIIII()
	{
	}

	public bool JIJIJJJIJIIJJJIIJIJJIJJIJIJIIJIIIJJIIIJJJJJIJJJ()
	{
		return false;
	}
	public Transform JJJIJJJJJIJIIJIJJIJJIJJIIJJIJJJIJIJJJJJJJIJIIJI()
	{
		return null;
	}
}
