using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEngine;

public class vp_FPCamera : vp_Component
{
	public delegate void JIIIIJIJJJJJJIJIIIIIJJJIIIIIIIJIIJJIIIIIJJIIIJI();

	public bool IJIJIIJJIJJJIJJJJJJIJJJJJIJIIIJIJJJJJJIIJJJJJII;

	public vp_FPController IJIJJJJIIIJJIJIIIJJJJJJJJIJIIJJIJIJIIIIJIIJIIJJ;

	public Vector2 IJJJJIIJJJJJJJIIJJJJIIJIIIJJJJIIIJJIIIIJJIJJIJJ;

	public int IIJJIJIIJJIJIIIJIIJJIJJIIIJIJIIJIJJIIJIIJIIIIII;

	public float JJIJIJIJIIJJIIIIJJIJIJJIIJIIJJIJIJIJJJIIIJJJIJI;

	public bool IIIJJIIJIIIJJIIJJIIIJJIJIJIIJIJIIIJIIIJIJJJJIJJ;

	public float IIIJIIJIJJIIIJJIIJJIJIJIIJJIIIIJJJJJIJJJJIIIIJI;

	protected Vector2 JJJIJIIJIJIJIJIJJJIIJJJJJJIIJJJIIIIIJIJJIJIIIIJ;

	protected List<Vector2> JJJIIIJJIIIJIJIJIIJJIJJIJIIJIJJJJJIIJIIIIJIIJIJ;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIIIIIJJIIIJIIIIIJIIJIJIJIJJJIIJIIJIIIIJJJJJIJI;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII IIIJIJIIJIJIIIJIIJJIIJJJJJJJIJIJIIIIIIIJIIIIJIJ;

	protected float IJIJJJJJIJJJIJIJIIJIIIJIIIJJJIIJIJIIJIIJJJIJJJI;

	public JJIIIJIIIJJJJIJIJIJIJIJJJJIIIIJJJJIJJJIIJIIIIJJ JIIIIJJIJIJJIJIJIJIIJJIJIJIIJIJIJJIIJJJJIJIIIII;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII IIIJIIIIIIJIIJIIIJJIIJJIIJJIJJJJIJIJIIIJIJIIIJI;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIJIJJJIJIJIJIJJJIIJIJJIIJJIIJIJIIJJIIIIIIJJIIJ;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JJJIJIIIJIIJJJIJJJJIIJIIIJIJJJJIIJIIJIIIJJIIJJI;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIIJJIJIIJJIIIJIJIJIIJJJIIJJJIIIJJIJJJJJIIJJIII;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII IJIJJIIJJJJIIJIJIIIIIIIIJIJJJJJJIJIIIIIJJIIJJII;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIJJIJJIIJJJJJIIJIIIJIJJIIIJJIJIJJIJJJIJJIJJJIJ;

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIIIJJIIIIJIIJIJIIIIJIIIJJJJJIIIIJIIJJIIJJIJJJI;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII IIJJJJIIIIJIIIJJJIIJIJIJJIJIJIIJJJIJJIJIIJJJJJJ;

	protected IJIIIJJIJIIJIIJJJJJIJJIIJJJJJJJIIIJIJJIIJIJJJJJ JJIJJJJIJJJJIIIIJJIIIIJIIIJJJJIIJIJJIJIJIJIJJJJ;

	protected IJIIIJJIJIIJIIJJJJJIJJIIJJJJJJJIIIJIJJIIJIJJJJJ JIIJIIJJIIJJJIIJIIIIJIJIIIIIIIJIJJIIIIJIIIJJIJI;

	protected bool IJJIJIJJIJIIIJIJJJJIJJJIIJIJIIJIJJIIJJIIJIIIJJI;

	public Vector2 JJJJJIJIJJJIIJIIIIJJJJIJJIJIJJIIIJIIIIJIJJJIIJJ;

	public Vector2 IIIIIIJJJJIJJIJJJIJJJIJJIIJIIJIIIIIIJIJIIIIIJJI;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIJIJIJJIIIJJIIJIIJJIIIIIIJIIIIIIIJIIJIIJJIJJJI;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIJIJIIJJIJIIIJJIJJIIJJJIJJIJIJJJIIJIJJIIJJJJJJ;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JJJJIIJIIJJIIJJIIIIIJIIJJIIJIJIIIIIJJJIJJIJIJIJ;

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JIJIJJJIJIIIJIIJJIIIIJJIIIIJIIIIJIJIJIIIJIJIIII;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII JIIJJIJJJJJIJIIIJIIJIIJIIIJJIJJIJJJIJIIJIIIJJJI;

	public IJJJIJJJJJIJIIIJJJIIJJJJJJIIIJIJJJIJJIIJJJIIJII IIJIIJJJJJJJIJIIIJIJIJJIIIIJIIJJJJIJJIIIJJIIJIJ;

	protected float IJIIIIJJJIIJJIIIIJIJJJJJJIIJJIIIJJIJJJJJJJJJIJI;

	protected float JJJJJIJJJJIIIJJIJIJJJJIJJIJJIIJIJIIJJIIJJJIIJJJ;

	protected IJIIIJJIJIIJIIJJJJJIJJIIJJJJJJJIIIJIJJIIJIJJJJJ JIJJJJJIIJIJJIJJJIIJIJJIIIIJIIJIJJJIJIJJIIJJIJJ;

	protected Vector2 JJIIIIJIIJIJIJJJJIIIJIJIJIJIJIJJJJJJJIJIJIJIJII;

	public float JIIIJJIIJIJJIIJIJJIIJJJJIJJJIIIIIJIIJJJJJJIJJII;

	public Vector3 IIIIIJIJIJJIIIJJIJIJJJIIJJJIJJJJJJIJIJIIIJIJJJI;

	protected Vector3 IJIIJIIIJJJIJJIIIIJIJJJIIIJJIIJJIIIIIIJJJJJJIIJ;

	public Vector4 JJIIJIIIIIJIJJIJIJJJIJJIJJJIJIIJIJJIIIJJIJJIJJI;

	public Vector4 IIJJJJJJIIIIIJJJJJIJIIIIJJIJJJIIJIJIJJJJJIJJJIJ;

	public float IJIJJIJIJIJIJIIIJJIJIIJJJIIIJIJIIIIIIIJIJJIIJII;

	public float IJJJJJJJJIJIIJIIJJJIJJIJIJJJJJJIJIIIIIJJJJJJIIJ;

	public bool IIJIIIJIIJIJJJIIJIJJIJIIIIIJJIIJIIIJJJJIIIIIIJI;

	protected float JIIIIJIIIJIJIJIJJJIIIIIJJJJIIJJJJJIIIJJJIJIJIJI;

	protected Vector4 IJIIJIJJJIJIIJJIIJIIJIJJJJJJJIIJIJJJIJIJIJIIIII;

	protected Vector4 JIJJIIJJJJIJJIJIIJJIJJIJJJJJJJIIIIJJIJJIJIJIJJI;

	protected float JJIIIJIJIIIIIIJJIJJJJJJIJIJIJIIIJIIIIIIJJIIJIJJ;

	public JIIIIJIJJJJJJIJIIIIIJJJIIIIIIIJIIJJIIIIIJJIIIJI JJJJIIIIJIIIJIJJIJIIIIJIJIJIIJJJIJIJIJIIJIIIIJJ;

	public float IJJJIIIJJIJIJJIIJIJJJIJIIIIJIJJIJIIJIJIIJJJIIJJ;

	protected float IJIJJJIJJJJIJJIIIJIJIIIIJIIJIIIJIJJJIJIJIJIJIJJ;

	protected bool JIIJIIIJIJJJIIJJIIJIJJIIIIIIIJIIIIJIJIIIJIIIIII;

	protected Vector3 JIIIIIIIJIJIJIJIIIJJJJJJIJIJJIJJJJIIJJJIJIJJIJJ;

	protected Vector3 JIJIJJIIIJJIJJIIJJIIIIIIIIJIIIIJIIJJIJJJJIIJJIJ;

	protected RaycastHit JJJJIIJJJIJIIJJIIJJIIIIJIJIIIIIIIJIIIIJIJIJIJJI;

	private bool IIIJJJIJIIJJIJIIIJJJIIJJJIJIJIIIJJIIJJIIJJIJJJI;

	private Vector3 IIJJIJJIJIJIIJIJIIJIIIIIIJJIIJIJIJJJIJIIJJIIIJI;

	private float JIIIIJIJJJIIJIIIIIIIIIJIIIIIJIIIIJIJJJJJJIIJJII;

	public bool IJJJJJIIJJJJJIJIIJIJJJJIJIIIJJJJJJIJJJJIIJJIJII
	{
		get
		{
			return JIJIJIJIJIJJJIIJIJJJIIIJJIJJIJIJIIJIJIJJJIJIJIJ();
		}
		set
		{
			JIJIJIIJJJJJJJIIJJIIIIJIIJJIIJIIJJIIJJJJJIJJIIJ(value);
		}
	}

	public Vector2 JIJJJIJIJIIIIIJJIIJJJIJIJIIIJJIIIJJJJJIJJIIIJJI
	{
		get
		{
			return JJIJJJJJIJIIJJJIIJIJJJIIIIJIIJIIJJIIIJJJJIIJJJI();
		}
		set
		{
			IJJIJJJIJIIJIIJIJJIJIJIIIJIJIJIIIIJIIIJJIIJJJJJ(value);
		}
	}

	public Vector3 IJJJIJJJIJIJJJJIJIIJIIIJJIJJJIJJJIJIIIIIIJJJJII => JIJJJJJJIIJIIJIIJIJJIJIIJIIJJIJJIJJJJJIIIIJJJIJ();

	public float IJJIJJJJIIIIJJJIJIJJIIIJJIJJIJJJIJIIJIIJJJJJJIJ
	{
		get
		{
			return JIJJIJIJJIJIJJJIIJJJJJIIJIJJJIIIJJJJJIIJIJIIJJJ();
		}
		set
		{
			JIJIIIJIIIIJIIIIIJJIIJIIJJIJIJIJIJJJIIIJIIJJJIJ(value);
		}
	}

	public float IIJJIIIIJIJJJJIJIJJJIJIJJJJIIJIIIJJJIIIIIIJIJII
	{
		get
		{
			return JIIIIJJJIJIJIIJIIIJJJJJIIIJIJJJIJJJJJJIJIIIIIJJ();
		}
		set
		{
			IIJIIJIJIIJIIIIIIIJIJJIJIJJJJIIJIIJIJJIJJJJIJII(value);
		}
	}

	protected override void OnDisable()
	{
	}

	protected virtual void IIIJIJJJIIIIIJIIIJIIIIIJIIJJJJJJJIJIIIIIIIJIIIJ()
	{
	}

	public void JIJIIIJIIIIJIIIIIJJIIJIIJJIJIJIJIJJJIIIJIIJJJIJ(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected override void LateUpdate()
	{
	}

	public float JIJJIJIJJIJIJJJIIJJJJJIIJIJJJIIIJJJJJIIJIJIIJJJ()
	{
		return 0f;
	}

	public virtual void IJIJIIJIIJJIJJIJJIIIIJIIJIJIJIIJIJJIIJJJJJJIJII()
	{
	}

	protected override void Awake()
	{
	}

	public void JJIIJIJJJJIIIJIJJJJJJJIIJJJJJIIIJIJJIJJIJJIJIJJ(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, float JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII)
	{
	}

	public void JIJIJIIJJJJJJJIIJJIIIIJIIJJIIJIIJJIIJJJJJIJJIIJ(bool JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}
	public float IJJIIIIIJIIJJIJIIIIJIIJJIJIJIJJIJIJIIJIJIIIIIIJ()
	{
		return 0f;
	}

	public Vector3 JIJJJJJJIIJIIJIIJIJJIJIIJIIJJIJJIJJJJJIIIIJJJIJ()
	{
		return default;
	}

	public virtual void IJIIJJIIIJJIIIIIIJJJJIIJJJJIJIIIIIJIIJIJIIIIIIJ()
	{
	}

	protected override void OnEnable()
	{
	}

	protected virtual void IJJJIIJIIIJIIIIJJIJJIIIIIIIJIJIIJJIJJJJIJJJIJIJ()
	{
	}

	public virtual void IIIJIJIJJJJJIJJJJIJJIJIJJIJIIIIJIJJJJJJJJIIJJIJ(Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}

	public virtual void IJJJJIIIJJJJJJJJIJIJJIJJJJIJIJIIJJJIIIIJJIJJIIJ(Vector3 IJIIJJIJIIJJJJJJIIJIIJIJIIIIIJIJJIJIIIIIIJJIJII, float JIIJJJIJIIIIJJIJIJIIIIIIJIJIJIJIIIIJJJJJIIJIIIJ, float IIJJJIIJJIIJIJIIIIIIIJJJIJJIIIIJJJIIIJJJJJIJIII)
	{
	}

	public virtual void JIIJJIJJIIIIJJJJJIIJJJIJJJIIIJJJIJIJIJIIIIIIJII(Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}

	protected virtual void IJJJJJJIJJIIIIJIJIJJJIIIJJIIIIJJIJIIJIIIIJJJJIJ()
	{
	}

	protected virtual void JJJIJIIIJJJJJIIIJJJIIJIIIJJIJIJJJIJJJIJIJJIIIIJ()
	{
	}

	protected virtual void JJIIIIJIIIJJIIIIIJJJIIJJJJIJIJIJIIJJIIJIJIJJJII()
	{
	}

	public virtual void IJJJJIJJIIJJJIJIIJJJIIIIJJJJJIJIJJJIJIIJJJIIJIJ(Vector2 JIJIIIJJJIIIJJJJIIIJJIIIIJJJIJJIIJJJIJIIJIIIIJJ, bool IIJJIIIJIIIIJJJIIJJIJJJIIJJIJJIIIIJIIIIIIIIIIII = true, bool JJJJIJIJIIJJIIJIIJIIIJJIJIIIJJJJJJJJJIIIIIIJJJI = true)
	{
	}

	private void JJJJJIIIJIIIIJJJIIIIJJJIJJJIIIJJIJJJIIJIIJJIIIJ()
	{
	}
	public Vector3 JIIIJJIIJJJIIJJJJIIJIIIIJJJIIJIJJIJJJIJIJJIIJII()
	{
		return default;
	}

	public virtual void JIJIIIJJJJJIJJJJIJJJJIJIJIIJJJJJIJIIIIJIIIJIIIJ()
	{
	}

	protected virtual void IJIJJIIJIJIIIIIJIJJJJJIJJJIJIJIIIJIJIIJIJJJIIJI()
	{
	}

	public virtual void IJJJIJJJIJIJJIIIIJIJIJIIIJIJIJJJJIJIIJJJIIIJJJI(Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}
	public float IJIIIJIJIIIJIIJJIIIJJJJIJJJIIIIIJJJJIJJIJIJJJII()
	{
		return 0f;
	}

	protected virtual void IJJJIIJJIIJIJIJIIJIJIIJJJJJIJJJIJIJJIJJJIIJJJJJ()
	{
	}

	public virtual void JIIJIJJIJJIIIIJIIIIIJJIJIJJJJIIJJJJIJIIIIJJJJJJ()
	{
	}

	protected virtual void JIIJJIJIJIJJIJJJIJIJIIIIJIJIIJJIJJJJIJIJIJJIIII(Vector2 JJJIIIJJJIIJIJIIIIJJJJIJJIIJIIJIIJJJJJIIJIIIIIJ)
	{
	}

	public virtual void JJIIJIJJJJIIIJIJJJJJJJIIJJJJJIIIJIJJIJJIJJIJIJJ(Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}

	protected virtual void IIJJIIJIIJIJIJJJJIIJIIIJJIJJJIJJIJIIJJJJJJJIJIJ(float JIIJJJIIIJJIIIIJIJJJIIIJJIIIJJIIJIJJJJJJIJJJJJI, float IJIIIIJIJJJJJIJIIJIJJIJIIIJIIJJIIJJIJIJIIJJIJIJ)
	{
	}

	public void IJJIJJJIJIIJIIJIJJIJIJIIIJIJIJIIIIJIIIJJIIJJJJJ(Vector2 JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	public void IIJIJIIIJJJJIIIJJIIJIJIIJJIIIIJIIIJJJJJIIJJJIIJ()
	{
	}
	public bool IIJIJIJIIIIJJIIJJJJJIJIIJIJJJJIJIIIIIJJJJJJIIJJ()
	{
		return false;
	}

	protected virtual void IJIJIIIJJJIJIJJJJIIIIIIJJIJJJJJJJIJJJJJIIJJIJII()
	{
	}

	public void IIIJIJIJJJJJIJJJJIJJIJIJJIJIIIIJIJJJJJJJJIIJJIJ(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, float JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII)
	{
	}

	protected virtual void JIJIJJIIIJJIIJIIJIIJJIJIIJIIIIIJJIIIJIJIJJJIJJJ(float JIIJJJIIIJJIIIIJIJJJIIIJJIIIJJIIJIJJJJJJIJJJJJI, float IJIIIIJIJJJJJIJIIJIJJIJIIIJIIJJIIJJIJIJIIJJIJIJ)
	{
	}

	public virtual void JJIJJIJJJIIIIIIJIJJJIJIJIJJJJIIJJJJJJJIIIIJIIJI(Vector3 JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}

	public virtual void IIIIJJIIJIIIIIJIJIIIIIIJIIJJIIIIJIIIIJJJJJIIJJJ()
	{
	}

	public virtual void IJIJJJJIIIJIJJJIJJJJJJIIIIJIJJJJIJJJJIIJIIJJJJI()
	{
	}

	public void OnMessage_JJJJJIJJIIIIJJJIIIJIJIJIIIIIJIIJIJIIIJIJIIJIIJI(float JIIIJJJIIIIJJJIJJJIIIIJJJIIIJIJIIIIIJJJJJJJIJIJ)
	{
	}

	protected override void Update()
	{
	}

	public virtual void JIIJJIJJIIIIJJJJJIIJJJIJJJIIIJJJIJIJIJIIIIIIJII(float JJJJIIIJJJIIJJIIJJIJIJIIJIJJJJJIIJJJJJJJJIIJIJJ, float IIJIIJIJIIIJJJJJJJJJJJJIIIIJJJIJIIIIIIJIIJJIIJI, float JIJIJJIJIJIJJJIJIJIIJJIIIIJIIIIIJIIIIIJIJIIJJII)
	{
	}

	public bool JIJIJIJIJIJJJIIJIJJJIIIJJIJJIJIJIIJIJIJJJIJIJIJ()
	{
		return false;
	}

	public void IIJIIJIJIIJIIIIIIIJIJJIJIJJJJIIJIIJIJJIJJJJIJII(float JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
	{
	}

	protected virtual void IJIIJJIIJJIIJIIIIJIIIJIJIIJIIJJJIIJIJJJIJIIIJIJ()
	{
	}

	public virtual void IIIIIIJJJJJJIIJIIIIJIIIIJJIIIJIJJJJIIJJIJJJIIJI()
	{
	}

	public Vector2 JJIJJJJJIJIIJJJIIJIJJJIIIIJIIJIIJJIIIJJJJIIJJJI()
	{
		return default;
	}

	public virtual void IJJJIJIJIJJJIIJJIJIJIIJIIIIIIIJJIJJIIJIJIIIIIJI()
	{
	}

	protected override void IIIJJIJJJJIJIIJIIIIIIIIIJJIIJJIJJJIIIJIJJJJIJIJ()
	{
	}

	public void IIIIJJJIJJIJIIIIJIJIJJIIJIJIIIJIJJIIIJJIJIIJJJJ(Vector2 JJJIIIJJJIIJIJIIIIJJJJIJJIIJIIJIIJJJJJIIJIIIIIJ)
	{
	}

	public override void IIJJJJIIIIIJIJJIJJJJIIJIJIIIJJIIJJIJIJJIJJIIIJJ()
	{
	}

	protected virtual void IJJIIJJIIJJIIJJJJJJIIIJJJJJIJIIJIJIIJIIJIIIIJII()
	{
	}

	public virtual void IIJJJIJJIIJJIJJIJJJIIIJIIJJJIJIJIIIIJJJJIJIIJJJ(float JJIIJIJJJJJIJIIJJIIIIIIJJIJIIJIJIJJJIJJJIJIJJII)
	{
	}

	public float JIIIIJJJIJIJIIJIIIJJJJJIIIJIJJJIJJJJJJIJIIIIIJJ()
	{
		return 0f;
	}

	protected override void Start()
	{
	}

	public virtual void IJJIJIJIJIJJJJJJIJIIJJIJIJJJIJJIJJJIJJJJIIIIIIJ()
	{
	}
}
