using UnityEngine;

public class vp_RigidbodyImpulse : MonoBehaviour
{
	protected Rigidbody JJJIJIJJIIIIJIJIIIJIIIJJIJJJIJIJJJIIJIJJIIJJIII;

	public Vector3 IJIIJJIIJIIIJIJJIIJIJJJIJIJIJIIIJIJIIIJJJJIJJII;

	public float JIIIJJIJJIJJIIJJJIIIIJJIIIJJIJIJJJJJJJIJJJJJIJI;

	protected virtual void IIJIIJJJIIJJJIIIJJIJIJJIIJJIIIJIJJJIJJIJIJJIJJI()
	{
	}

	protected virtual void JJJIIJJIJIJJJJIIJJJJJIJJIIIJJJIJIJJIIIJIIJIIJII()
	{
	}

	protected virtual void JIIIJJIJIJJIJJJIIIIJJJIJIJIJIIIJJJJIJJIIIIJJIII()
	{
	}

	protected virtual void IIIJJIJJJJJJJJIIJJIJJJIJJIIIIJIIIJJIIIIIIJJJJJJ()
	{
	}

	protected virtual void IJIIIJIJJIIJJIJIJJIIJIIIJJJIIJJIIIJIJIIIIIJJJII()
	{
	}

	protected virtual void IJIJJJJJIJJIIJJJJJIJIJJIJJJJJJIJIIIIIIJJJJIIIIJ()
	{
	}

	protected virtual void OnEnable()
	{
	}

	protected virtual void JIJJIIIJJIJIIIIIJIIJIIIIJJJIJIIIIJJJJJJJJIIIIIJ()
	{
	}

	protected virtual void JJJIJIIJJIIJJJIIIJJIIIJJJIJJIIJJIIIJIIJJIJIJJJJ()
	{
	}

	protected virtual void JIJIIJJIIIIIIIJJIJIJIJJJIJJIJIIJJIJJJIJIIIJIIJJ()
	{
	}

	protected virtual void IIIJIJJJIIJIIIJIIJJJIJJIJIIJJJIJJIIIJJJJIIJJJIJ()
	{
	}

	protected virtual void JIJJIJIIJIIIJJIIIJIJIIIIIIJIIIIIIJJIIJJIJJJIIJI()
	{
	}

	protected virtual void JJIJIIIJIJIJJJJIJIIJJJJJIJJJJJIJIJIJIIJIIJIIIJJ()
	{
	}

	protected virtual void JIJIJIIIJIIJJIIIIIJJIJIIIIJJJIJIJJIJIJIIIIJIJJI()
	{
	}

	protected virtual void IJIJIIJJIJIJIIJJJJIJIJIJIIJJJJIJJIJIJJIJJJIJIJI()
	{
	}

	protected virtual void JJIIIJJIIJIJJIIJIIIJJJJJIJJIJJIJIIJIIIIIJIJIJJI()
	{
	}

	protected virtual void JJJIJJJJJIIJIJJJIJIIIIJJIJJJIJIIJJIIJIIJJJJIIJI()
	{
	}

	protected virtual void Awake()
	{
	}

	protected virtual void JIJJJIIIIIIJJIIIIIJJIIIJJIJIJJJJJJJJIJIJIIJIJII()
	{
	}

	protected virtual void JJJIIIIIJIIJJIJIJJJJIIJIIIIIIJJJJJJIJIJIIJJJIJJ()
	{
	}
}
