using UnityEngine;

public class vp_Spin : MonoBehaviour
{
	public Vector3 IIIIJIIJJIJIIJIJIIIJIJJJIIJJIJJIIJIJIIIJJJIJIIJ;

	private Transform IJJIIJIJJIIIIIIJIJJIIJJIJIIJIIIJIJJJIIIIJJJJIJJ;

	protected virtual void IJIJJJJJIIJIIJIJIIIJJJIIIJIJIJIJJIJIJJJJJIJJJJJ()
	{
	}

	protected virtual void IJIJIJIIJJIIIJJIJIIIJIJJIIJJJIIJJJJJIJJIIIJJIIJ()
	{
	}

	protected virtual void JJJIIIIIIIJJJIIJIIIIJJJJIIIIIIIIJJJJJJJIIIJIIJJ()
	{
	}

	protected virtual void JIJJIJJIIJJIJJIJIJJIIJIJJJJJIIJIIIJJIIIJJIJIJII()
	{
	}

	protected virtual void JIJJJJIIIJIIIIJIJJJJIIJJJIIJJIIJJJIIIIIIIJIIIJI()
	{
	}

	protected virtual void JJIIIJJIIJJIIIJJJIJIIJIIJIJJIIJJIIJJJIJIJIJJIIJ()
	{
	}

	protected virtual void JIJJJJIIIIJJJIIIJJIJIJJJIJIJJJIIIIIIJIIIJJJJIIJ()
	{
	}

	protected virtual void IJIJIJIIIIJIIIJJIJIIJJJJIJJIJJJJIIIJJJIJIJIIJIJ()
	{
	}

	protected virtual void JIJJJIIIIIJIJJIIJIJIIIIJIJIIJIIIIJJJIIJJJIJJJIJ()
	{
	}

	protected virtual void JJIJJJIIJIJIJIJIJJJJJIIJIJIIIIJJIIIJIIJJJJJIJIJ()
	{
	}

	protected virtual void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	protected virtual void Start()
	{
	}

	protected virtual void JJJJIJIJIIJJJJIIIIJJJIIIIJJIIIJJIJJIIJIIIIIIJIJ()
	{
	}

	protected virtual void JIIJJIIJIIIIIJIIIIJJIIJJJIIJIJIJJIIIIIIJJIJJIII()
	{
	}

	protected virtual void Update()
	{
	}
}
