using UnityEngine;

public class WaterSystem : MonoBehaviour
{
	public bool IJJJIJIJIJIJJJIJIIIJIIIJJJJJIIJJJIIJJIIJJJIJJJI;

	private BoxCollider IJJIJIJJJJJJJIIIIJJJIJJJJJJIIJIIIIIJJIIIIJIJJJJ;

	private void IIJJIJIJJJJJIJJIIJIJIJJIIJIJIIJJIIIJJIIIJIIIJJI()
	{
	}

	private void JIJIJJJJJJJJIJJJJJIJJIIIJJJIIJJIIIIJJIIJIJJJIIJ()
	{
	}

	private void IIIIJIJIJJIIJIIIIJIJIJIJIJIIJIJIJJIJJJJJIIIJIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJIIJJIIIIIIJIJJIJIJIIJJJIIJJJJJIJIJIIJIJIJIIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJJIJJIIIJIJJIIIIJIJJIJIJJJIJJIIIJJIJJIJJJJJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIJIJIIIIIJJIIIIIJJIJIIIJIJIJIIIJIJJIIIJJJJIIJJ()
	{
	}

	private void IIJIJIJJIJIIIJIJJIJIIIJIIIJJJJJIIIJJIIIJIJIIIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJJJJIJIJIJIJJIIJJJIIJIIIIIJIIJJJIIJJIJIJIIJIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJJIIIJIJIIJJIJIJJJIIJIJIJJJJIJJJJJJJIIJJIJJJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void JJIIJIJJJJJIJJJJIIJIJJJJIJJJIIJJJIJJJIIJJIIIIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void OnTriggerExit(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJJJJIJJIIIJJIIJJIIIJIIIIIJIIJIJJIIJJJIIIJIIJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIJJIIJIIIJJJIIJJJJJJJIJIJIJJJIIIIIJIJJIIIIIJIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void Start()
	{
	}

	private void IIJJJIJIJIIIJIJIJIIIJIIIJIJJIJIIJIJIIJIIIJJJJIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIIIJJJIJIIIIIIJIIIIIJJIIJJJJJIJIIJJIIJJIIJIIJJ()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void JIIIJIIIIIJIIJJIJIJJJIIJJJIJJJIIJJJIJJIIJIIJIII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIIIIJIJJIIIIJIIIIJIJJJIJJJJJIJIIJIIJJJIIJJIIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JJIJJIJJJJJJIIJIIJIJIJJIJJJJJJJIIIJJJJIIIJJJIII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}
}
