using System;
using System.Collections.Generic;
using UnityEngine;

public class WeaponSkinManager : MonoBehaviour
{
	[Serializable]
	public class IJIJJIIJJIIJIJIIJIIJIJIJIIIIJJIJJJIIJJIJJJJJJII
	{
		public int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ;

		public List<JJIJJJIJIIJJIJIJIIJIJJIIIIIIIJIJJIJIJJJJJJJIJJI> IIIIJIIIJJJJIJJIJJIJIJJIJJJIJJJIJJJIIJJJJIJIIIJ;

		public List<JJIJJJIJIIJJIJIJIIJIJJIIIIIIIJIJJIJIJJJJJJJIJJI> IIJIIIIJJJJJJJIIJJIIJJJJIJIJIJIJJIIJJIJIJIIIIIJ;

		public List<JJIJJJIJIIJJIJIJIIJIJJIIIIIIIJIJJIJIJJJJJJJIJJI> JIJJIJIJJIJIIJJIJJIJIJIIJIJJIIIJIIIIJIIIIJIJIII;
	}

	[Serializable]
	public class JJIJJJIJIIJJIJIJIIJIJJIIIIIIIJIJJIJIJJJJJJJIJJI
	{
		public int JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ;

		public int IJIJIJJIIIJIJIIIJJJIJIJIIJIIIJIIIJIJIIJJJIIJIIJ;
	}

	public IJIJJIIJJIIJIJIIJIIJIJIJIIIIJJIJJJIIJJIJJJJJJII[] IIJJJJJIIIJIIIIIJIJJIJIIJIIIIJIIIIIIJIJIJJJIJII;

	public int IJJJJJJIJIIIJJIIIJIJIJJIJIIIJJIJJJIIJJJJJIIJIII;

	public UISprite[] IJIIJIJIIJIIJIJJJJIJIJJIIJIIIJIJIJJIJIIJIJIIJIJ;

	public int IIJJIJIJJJIJIJIJJIJJJIJIIJIJIJJJJJIIJIJIIIJJIII;

	private void JIJIJJJIIJIIIJJIIJIIIIIIIIIIJIJIJJIIJJIIJIJIIJJ()
	{
	}

	private void IJJJJIIJIJJJJIIJJJJIIIIJJJIJIJIIJIJJIIJIIJJIJIJ()
	{
	}

	private void JJJJIIJJIIJIJIJJJIJJIJIIIJIIIJIJIJIIIJJJIIJJJII()
	{
	}

	private void JIIJJIJJJJJJIJJJIJIIIIIJIJJIIIIJJJIIIJJIJIJIJJJ()
	{
	}

	private void JIJJJIIIIIJJJIJIJIIJIIJIJIJJIIIIIIJJIIJIIJIJJJI()
	{
	}

	private void IIIIJIJIIIIJJJJIIJIJJIIJIJJJIJIIJIJIJJJIJJJIIIJ()
	{
	}

	private void JJJIJJIJIJJIIIJJIJIJIIJIJIIIIIIIIJIIJJJJIJJIIJJ()
	{
	}

	private void JIJIJIJIJIIJJIIIJJJJIJJIJIJIJIJJJJIJJIIIIJJJIII()
	{
	}

	private void JIIJJIIIIJJIIIJJIJIJIIIIIIIJJIJIJJJJJIIJJJIIJII()
	{
	}

	private void JIJJJIJIIJJIIJIJJJIJIIIIIJJIIIIIIJJJIIIJIJIJIJJ()
	{
	}

	private void IIJIIJJIIIIJJJIJJIJIIIJJIJJIJIIJJIJIJIIIJIIJJII()
	{
	}

	private void IJIJIIIIJIJIJJJJJIJJJJJIIIJJJIJJIJJIIJIIIJJIIII()
	{
	}

	private void IJIJJJIJJIJIIJIJJIIIIIJJIJJIJJJIIJJIJIJJJJJJJJJ()
	{
	}

	private void IJJIJIJJJIJJJIIJIJIIIJIJIJIJIJJIIJIIJJJIIIJJIIJ()
	{
	}

	private void IIIJJIIJIIIIIJJIIJJIJIIJJIIJIJIIIJJIJIIIJJIIIII()
	{
	}

	private void JIJJJJIJJIIJJJIJIIIJJIJJJIJIIIJIJIIJIIIIJJIJJII()
	{
	}

	private void IIIJIJIIJJJJIIIJJJJJJIJIJIJJIIIJJIIIIJJJIIJIJII()
	{
	}

	private void JJIIJJJIJJIIIJJJJIIJJJIIJIIIJJIIIJIIJIIIJJJIIJI()
	{
	}

	private void IIJIJIJIIIJIIIJJJJJIIJIIJJIJIIJIIIJJIIIJIJIIIJI()
	{
	}

	private void JJJIIJJJJIIIIIIIIIIIJJJIJIIIIIIJJIIJIJIIJJJIIJI()
	{
	}
}
