using UnityEngine;

public class WeaponManager : MonoBehaviour
{
	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IJIIIIIIIIIIJJJJJIJJIIJIJJJJIIJIIIIJJIIIJIJJJJJ;

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI IJIIJIJIIIJJIJIIIIJIJJIJJIJIJIIJJIJIIJJJIIJIJIJ;

	public IIJJIJJIJIJIIIJIJJJJJIJIJJIIJJJIIJIIIIJJIIJIIJI JJJIJIJIJJIIJIIIJIJIIJIIIJJIIJJIIJJIJJJIIJIJJJI;

	public static JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJJJJJIJJJIIJIIJIJJJIIIJIJIIJJIJIJJIJJIIIJIIIJJ;

	public static bool IIIIJIJJIIJIIIJJIJJIIIJIIIIIIIJJJIJIJIJIJIJJIJI;

	private PlayerWeapons IJJJJIJIIJIIIIJIIJJJJIJJIIJJIJIIJIIJJIIJIJJJIII;

	private static WeaponManager JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static string JIIJJJIJJIJIIIIIJIIJJIJJJIIJJIIJIJJJJIIJJJJJIII(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return null;
	}

	public static IJIJJIJIIIJJIJIIIJJJJIIIJJJJJJIJIIJJIJIIJIJJIIJ IJIIIJJIIJJJIJJIJJJJIIJJJJIJJIIIJJJJIIIIIIJJJIJ(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
		return null;
	}

	public static IIJJJJJJJJIIJJIIJJIJIIJIJJIIJIJJJJJIJJIJIJJIJJI JJIIJJJJJIJJJIIIJJJJJJJJJJJJJIIIJIIJJJIJIIIJIJI(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return null;
	}

	public static JJIJIIJJIJIJJIIJIJJJIJJIIIIIIJIJJJJIJIIJIIIIJJJ JJJIJJIIJJJJJIJJJIJIIIJJIIIIIJJIJIIJIJJJJJJJJJJ(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, string IIJIJIJIIJJJIJJJJJIJIIJIJJIJIJIJJIJJJIIJIJIJJIJ)
	{
		return null;
	}

	public static int IIIIJJJJIJJJJIJJIJJJJIJIJJJJJJIJIJIJJJIIJIJIIJJ(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return 0;
	}

	public static JJIIJJIJJIJIJIIJIIIJJIJIIJIJIIJJIIJIIIJJIJIJJJJ IJJJJIIJJJJIJJIJIIJIIJIJJJJJIJJJIIJIIIIIIJIIJJJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return null;
	}

	public static void UpdateData()
	{
	}

	public static int JJJJIJIIIJIJIIIJIIJJIJIIIIJIJJIJJJJIIIIIIJIIJJI(IIJJIIIJJJIJJIJIIIIJJJJIIJIIJIIIIIJIJJJJJIJJIJI IIIJJIIIIIJIJJIIIIIIIJJJIIIIJIJIJIIJJJJJJIJIJIJ, int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
		return 0;
	}

	public static int IIJJIIJIJIJJJIIJJIJIJJIJIIIJJJIIIIJIJJJJIJJJJJI(IIJJIIIJJJIJJIJIIIIJJJJIIJIIJIIIIIJIJJJJJIJJIJI IIIJJIIIIIJIJJIIIIIIIJJJIIIIJIJIJIIJJJJJJIJIJIJ, IIJJJJJJJJIIJJIIJJIJIIJIJJIIJIJJJJJIJJIJIJJIJJI IJJIJJJIIJIJIIIJJIIJJIJJJIIIIIJJIJJJIJJIIIJJJII)
	{
		return 0;
	}

	public static IIJJJJJJJJIIJJIIJJIJIIJIJJIIJIJJJJJIJJIJIJJIJJI IIJIJJIJJIIJIJJIIJJIIIIIIIJJIIJIIJIJJIJIIJIJIJJ(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
		return null;
	}

	public static int IIJJIIJIJIJJJIIJJIJIJJIJIIIJJJIIIIJIJJJJIJJJJJI(IIJJIIIJJJIJJIJIIIIJJJJIIJIIJIIIIIJIJJJJJIJJIJI IIIJJIIIIIJIJJIIIIIIIJJJIIIIJIJIJIIJJJJJJIJIJIJ, int JJIIJIIJJIJJJJIJJIIJIJJJJIJJIJIIJJJJIIJJIJIIJJI, int JIJJIJJJJIIIIJJIIIIIJIJJJJJJIIIIJIJIJJJIIIIIIJJ, int IJIIJIIJJJIJIJJIIIJJJJIIJJIJJIIIIJJJIJJIJJIJIII, int JJJIIJIJIJIIJIIIJJJIJIJIIJJIIJIJJJIJJIJIIJJJIJI)
	{
		return 0;
	}

	private void Awake()
	{
	}

	public static int JJIIIIIIIJIJIJIIIJJJIJIIJJIIJJJJJIIJIJJJJJJIIII(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return 0;
	}

	public static bool JJJJIJJJJJIIIJIJIIIIJJJJIJJIIJJIIJIJIJJJJJIIJII(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return false;
	}

	public static string JIJIJIJIJIJJJJJJJJJIIIJJJJIIJIIIIJIIIIJIJIIJIJI(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
		return null;
	}

	public static int JIJJJJJIIJJJIIJJIIJJIIJJIJIIIIJIIJJJIIIIIJIJIJJ(string JJIJJIJJIIIJJJJIJIJIIJJJIIJIJIJJJJIIIJJJJJJJIJJ)
	{
		return 0;
	}

	public static IIJJJJJJJJIIJJIIJJIJIIJIJJIIJIJJJJJIJJIJIJJIJJI IIJIJJIJJIIJIJJIIJJIIIIIIIJJIIJIIJIJJIJIIJIJIJJ(string JJIJJIJJIIIJJJJIJIJIIJJJIIJIJIJJJJIIIJJJJJJJIJJ)
	{
		return null;
	}

	public static int IJIJJJIIIIJJJJJIJJJJJJIIJJIIIJJJIIJIJIIIIIIIJJJ(bool JIJJIIJIJJJJIJIJJJJIIJIIJJJJIJIJJIJJIJIIIIIIIII, bool IJJJIIJJJJJJJIJJJJJJJJIIJJJIJJJJIJJIIIIJJJIJJIJ, bool JIIIIIJIIIJIIJIJIIIIJJJIJJIJJJIJJIJIJJJJIIIJJIJ, bool IIJJIIIJIJJJJJJIJJJIJIIJIIJIIIIIIIJJJIIJIIIJIII)
	{
		return 0;
	}

	public static int JJIIIIJJJJIJIJIIJIIIJIIIJIJJIIJIJJJJJIIJJIJJJIJ(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return 0;
	}

	public static string JIIJJIIIJJJIJJIIIJJJIIIJJJIIIJJJIJJIJJJIIJIJJJI(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return null;
	}

	public static JJIJIIJJIJIJJIIJIJJJIJJIIIIIIJIJJJJIJIIJIIIIJJJ IJJJIJJIJJJJIJIIIJIIJIJJIJJJIIIIIIIJJJJIIIJJIIJ(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, string IIJIJIJIIJJJIJJJJJIJIIJIJJIJIJIJJIJJJIIJIJIJJIJ)
	{
		return null;
	}

	public static void IJIJJJJIJJJIIIJIJJIIJIJJJIIIIIIJIIJIJJJIIJIJIJJ(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
	}

	public static int IJJJJJIIIJJIIJIJJJJIIJIIIIIJJIJJJJJJIIIIJIJJJII(string JJIJJIJJIIIJJJJIJIJIIJJJIIJIJIJJJJIIIJJJJJJJIJJ)
	{
		return 0;
	}

	public static int IIJJIIJIJIJJJIIJJIJIJJIJIIIJJJIIIIJIJJJJIJJJJJI(IIJJIIIJJJIJJIJIIIIJJJJIIJIIJIIIIIJIJJJJJIJJIJI IIIJJIIIIIJIJJIIIIIIIJJJIIIIJIJIJIIJJJJJJIJIJIJ, int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
		return 0;
	}

	public static string IIJIIIIIJJIIIJJJIJIJIIIIIJJJJJJIIIIIIIIJJJJIJJJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return null;
	}

	public static IIJJJJJJJJIIJJIIJJIJIIJIJJIIJIJJJJJIJJIJIJJIJJI JJJJIJIIJJJIJJJJIIJJIIIJJJJJIIIJIIIIJJJIJIIIIJI(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return null;
	}

	public static string IJJIIIJJJJJIIJJJJJIIIIJIJIIJIIIJJIJIIIIIJJJJJIJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return null;
	}

	public static JJIJIIJJIJIJJIIJIJJJIJJIIIIIIJIJJJJIJIIJIIIIJJJ JIIJIIJIIIJJJJIIIIJJIJJJIIIIJIJIIJIJJIJIJJIIIJI(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
		return null;
	}

	public static void IIIJIIJJJJIJJIIIJIIJJJJJJJIIIJJIIJJJIIIJIIJIIJI(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
	}

	public static void IIIJJIJJJJIJIIJIIIIIIIIIJJIIJJIJJJIIIJIJJJJIJIJ()
	{
	}

	public static int JJIIIIIIIJIJIJIIIJJJIJIIJJIIJJJJJIIJIJJJJJJIIII(bool JIJJIIJIJJJJIJIJJJJIIJIIJJJJIJIJJIJJIJIIIIIIIII, bool IJJJIIJJJJJJJIJJJJJJJJIIJJJIJJJJIJJIIIIJJJIJJIJ, bool JIIIIIJIIIJIIJIJIIIIJJJIJJIJJJIJJIJIJJJJIIIJJIJ, bool IIJJIIIJIJJJJJJIJJJIJIIJIIJIIIIIIIJJJIIJIIIJIII)
	{
		return 0;
	}

	public static bool IIJIJIJJJIIJJIJIJIJIJJJIJJJJJJIIIJIJIJJJIIIJJII(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
		return false;
	}

	public static int JIIJJIJIJIIIJJJIJJJIJJJIIIIIIJIIIJJIIJIJIJJIIJJ(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIIJJIIJIJJIIJIJIIJIIIJIIJIJIJIIJIJIIIIJIJIJI)
	{
		return 0;
	}

	public static void IJIJJJJIJJJIIIJIJJIIJIJJJIIIIIIJIIJIJJJIIJIJIJJ(JIJJJIJJIIIJJJIJJIJIIIJIIJJIJJJIJIJIJIJJIIJIIJI JJIIJJIJIIJJJIJIIJIJIJJJIIIJJJIJIIJIIIIIIIJIJJJ, int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI)
	{
	}

	public static JJIJIIJJIJIJJIIJIJJJIJJIIIIIIJIJJJJIJIIJIIIIJJJ JJJIJJIIJJJJJIJJJIJIIIJJIIIIIJJIJIIJIJJJJJJJJJJ(int JJJJJIJJJJIIIIJJJIIIJIJIJJIJIIJJJIJJIJJIJJIIJJI, int IIJJJJJIIIIJIIJJJIIJIIIJIIIIJIJJJJIIIIJJJJJJJJI)
	{
		return null;
	}

	public static string IIIIIIIIIIJIIIIIJJIIJIJJJJIJJIJIIJJJIIJIIIIJIJJ(int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
		return null;
	}

	public static int JJIIIIIIIJIJIJIIIJJJIJIIJJIIJJJJJIIJIJJJJJJIIII()
	{
		return 0;
	}
}
