using System.Runtime.CompilerServices;
using UnityEngine;

public class ZombieSounds : MonoBehaviour
{
	public AudioClip[] IJIIJIIJIJIJIIJIIIJIJJIIJJJJJIJJJIJIIJJJIJIJJIJ;

	public AudioSource IIJIJJJIIIIIIIJIJJIJJIIIIIJJIIIIJJJIIIIIJIIJJII;

	public Vector2 IJJJJJJIJIIIJJIIIJIJIJJIJIIIJJIJJJIIJJJJJIIJIII;

	private int IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ;

	[CompilerGenerated]
	private void JJJJIJIIJIJIJJJIJJIIIJIIIIIIIIIIJIJIIJJJIJJIJIJ()
	{
	}

	private void IIJJIIIJJJJJIIJIJJJJJIJJJJJJIIIJIIIJIJJIIIIJJIJ()
	{
	}

	private void JIIIJJJJIIIJJJIJJIJJJJIIIJIIIIIIJIIJIIIIIIJIJII()
	{
	}

	private void JIJJJJJJIIJIJJIJJIIIJIJIJJJJJJIJIIIIJIIJJJIIIII()
	{
	}

	private void JJJIJIIJJIIJJJIIIJJIIIJJJIJJIIJJIIIJIIJJIJIJJJJ()
	{
	}

	private void IIJIJJJJJIJJJJJJJIIIJIJJJIIJJJIIIIIIIJIIJIIIIJJ()
	{
	}

	private void JIIJIJIIIIIIJIJJIIIJIIIIJJJIIIIIIJIIIIIIJJJIIIJ()
	{
	}

	private void JIJJIIIJIIIIJIJJIJIJIIIJIIJJJJJJJJIJJIIJIJJJJJI()
	{
	}

	private void IIJJJIJIIIJIIIJJJJIIIIJIJJIJIIIIJJJIIIJIIIIIJII()
	{
	}

	private void IIIJIJJIJJIJIJIJIJIIIIJIIJJIIIJJJIJJJJIIJIIJIIJ()
	{
	}

	private void IJJJIJJIIJIJJJIJIIIIIIJJIIIIJJJIIIIIJJJIJJJIJJJ()
	{
	}

	private void OnDisable()
	{
	}

	private void JIJIJIJJJJJJIIIIJIIJIJIJIJJJIIJIIJJIIJIJJJIIIII()
	{
	}

	private void JJIJJIJIJIIIJJIIIIIJJIJIIIIJJJIJIIJIIIJJIIJIJJI()
	{
	}

	private void JJIIIJIIJIJJIJIJJIJIJJJIJJIIIIIJIJIJIIIIIJIJIII()
	{
	}

	private void OnEnable()
	{
	}

	private void IIIJJJIJIIIJJIJIIJJIIIIJIIIJJJIIIIIJIIIJJIIJJII()
	{
	}

	private void IJIJJJIIJIIJIJJIJIJIIIJIJIJJIIIIIIJJIJIJIJIJIJJ()
	{
	}
}
