using System.Runtime.CompilerServices;
using Photon;
using UnityEngine;

public class ZombieWavesSpawnManager : Photon.MonoBehaviour
{
	public int IJIIJJJIJJJIIJJIJIJIIJJIJIIIJJIJJIJJJIIJIJIJJIJ;

	public int IJIIJIIIJJIJIJJIJIJJJIJJIJIIIJIIIJJJJJJJIIIIIJJ;

	public int JJIJIIIIIJIIIIJIJJJIJJIIIIJJJJIIJJIIJJIJJJJIJII;

	public int IIJJJIIJIJIIJIIIJJJJIJIIIJIJJJIIJJJIIJJJIIJJIJI;

	public Transform[] IIIJIIJJJIJIJIIJIIJIJJIJIJIJJJIJJIIIJIIIIIJJIII;

	public GameObject JIIJJJJIIIIJIJJJIIJIJIIJIIIIIIJIIIIJJJJJIJJJJIJ;

	private void JJIIJJIIJIIJJIIJIIJIJJJJIIJJIIJIJIIJJJIIIJJJJJJ()
	{
	}

	private void JJJJIJJIJIIIIIJJJJJJJJIJIIIIIJIIIJIIIJIJJJJJJJJ(PlayerAI JIJJJJIIJJJJJIIJJIJIIIJIIIJIJJIJIIIJJIJIIIJJJII)
	{
	}

	private void JJIJIJJJIIJJIIIJIIIIIIJJJIIJIJIIIJJJIJIIIJJIIII(PlayerAI JIJJJJIIJJJJJIIJJIJIIIJIIIJIJJIJIIIJJIJIIIJJJII)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIJJJJJJIIJJIIJIJIIJIIJJIIJIIJIJIIIIJJIJJJJIJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIJIJIJJIJIIJIJIJJJIJJJIIIJIJIIIJJJJJJJIJIJJJIJ()
	{
	}

	[CompilerGenerated]
	private void JIIJJJJIJIIIJJIJJIJJIIJJIJJJIJIIJIJJJJIJIJIIJJJ()
	{
	}

	private void JJJIIIJJJJIIJJIIIIJJJIIJJIJIJJIJIIIJJIJJIJJIIII()
	{
	}

	private void IJIJJJJIIIJIIIJIIIJJJJIIIIIIJIIIJJJIIIJJIJIJJJI()
	{
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	private void IIJJIJJIIIIIIIJJIIJJIJJIIIIIJIIIIIJJJIJIJIJIIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJIJJJJJIIJJJIJIJJJIIJIJIJIIIJJIIIJIJIIIIJIJIIJ()
	{
	}

	private void JJJIJJIIJJIIIIIIIIJJJIIJJJIJJJJIJIJIJJIIIIIJIJJ(PlayerAI JIJJJJIIJJJJJIIJJIJIIIJIIIJIJJIJIIIJJIJIIIJJJII)
	{
	}

	private void IIJIIIJJIIJIIIIJIJIJJJIIIJIIJJIJIJJJJIJJJIJJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJJJIIIIIIIJJJIJIIJIIJIJIIJIJIIIIIIJJJIJIJJJII()
	{
	}

	private void IJJIIJJJJJIJJJIJJJJIJIIIIJIJJJJJIIJIIJIIIIIJJIJ()
	{
	}

	private void IJIJIIJJJIIJJIJJJJJJJIJIJJJIIJJJJJIJIJJIIJJIIIJ(PlayerAI JIJJJJIIJJJJJIIJJIJIIIJIIIJIJJIJIIIJJIJIIIJJJII)
	{
	}

	private void IJJJIJIJIIIJJJIIIIIJJIIIIJIIIIIJJIJIIIIJIIJJJII(PlayerAI JIJJJJIIJJJJJIIJJIJIIIJIIIJIJJIJIIIJJIJIIIJJJII)
	{
	}

	private void IIJJJJJJJIJIIIIJIIIJIIIIIJJJIIJJIIJIJIJIIJJJIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void Start()
	{
	}

	private void JIIJJIJJIJIIIJJJJJJIIIIJJJIIIJIJJJIIIJJJIIJJIII(PlayerAI JIJJJJIIJJJJJIIJJIJIIIJIIIJIJJIJIIIJJIJIIIJJJII)
	{
	}

	private void JJJJJJIIJIJIJIJJJIIJJIIJIJJIIJIJIIIJIIJIIJJJJJI(PlayerAI JIJJJJIIJJJJJIIJJIJIIIJIIIJIJJIJIIIJJIJIIIJJJII)
	{
	}
}
