using System;
using UnityEngine;

public class ZombieEscapeManager : MonoBehaviour
{
	[Serializable]
	public class IIJJIJJJIIIJIIJIJIIJJIIJJIJIIJIJIJIIIIIJJJIJJII
	{
		public Transform IIJIJIIJJIIIJJJIJIIIJIJIIJJIIIJIJIIJIJIIJIIIIII;

		public float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

		public bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI;
	}

	[Serializable]
	public class IJIJJIJJIJJJIIIJIIJJIIIIJIIIJJJIJJIJJJIIJJJJJJI
	{
		public Vector3 IIIIIIIIJIJIJIJJIIIIIJJJJIJIIIJJIJJJJIIJJIJIJIJ;

		public Vector3 IJJJJJJJIJIIIIIJJIIIIJIIIIJJJIIJJIJJJIJJIIIIJJI;

		public float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

		public bool IJIJIJIIIIIIIIIIIIJIIIJJJIJJIIIJIJIIIIIIJJIJIJI;
	}

	public IIJJIJJJIIIJIIJIJIIJJIIJJIJIIJIJIJIIIIIJJJIJJII[] JJIJIIIJIJJJIIIIJIJJIJIJIJIIIIIJJJIJJJJJIIIIIII;

	public IJIJJIJJIJJJIIIJIIJJIIIIJIIIJJJIJJIJJJIIJJJJJJI[] JJIIJJIIIJJJJIJJIIIJIIIIIJJIJIIIIIIIJIJJJIJIIII;

	public IJIJJIJJIJJJIIIJIIJJIIIIJIIIJJJIJJIJJJIIJJJJJJI JIJIJJJJJJJIJJIIJJIJJIIIJJIJJIJJIIIJJJJIIJJJIIJ;

	public Color IJJJJIJIJIJIIJIIIIIIIIIIIJJJIIJIJIIIIJJJIIIIIII;

	public Vector3 JIIJIIJIJIJIJJJIJIJJJIJJIIJIIJJJIJIIJIIJJJIIIJI;

	private Transform JIIIJIJJJIIIJJJIJJJJJJJJIJJJIJIIIJIJJIJIIJIIIIJ;

	private void IIJJIJIIIIIIJJJIIIIIIJIIIJJJIIIIJIIJIIIJIJJIJIJ()
	{
	}

	private void Start()
	{
	}

	private void JIJIIJIJJJIIIJIIIJJIIIIJIIIJIJJIIIIIJJIIIIIJIII()
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void JJJJIJIIJIJIJJJJIIJIIIJJIJJJIIIIJJJIIJIJJIIIJIJ()
	{
	}

	private void IIJJIJIJIIIJIIJIJIIJJJIJJIIIJJJJIIIIJIJJJIJIIJJ()
	{
	}

	private void IIIJJIJIJJIJIIIIJJIIJJIJIIIIIIJIJJIJIJJIJIJJJJI()
	{
	}

	private void JIIIJJIIJJJIIJIJIJIIIJJJIIJJIIIIIJJJIIJIIIIIJJI()
	{
	}

	private void JIIIIIIIIIJJJJJJJJJIJIJJIIJIIJIJIJJIIJIJIIJIIII()
	{
	}

	private void IIIIJJIIIIIIIJJIJJJIIJIIJJIJJIIIIIJIIIJIJJIJJII()
	{
	}

	private void UpdateData()
	{
	}

	private void IJIIIIIIIJJIIIJJIIIJJIIIJIIIIIJIJJIJIJJIIIJJJIJ()
	{
	}

	private void IIJJJIIJIJIJIIIIJIJIIIIJIJJIJJJJJJJJJJIJJJIJIJI()
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void JIJJJIJIIIJIIIIIIJIJIIIIIJIIJIJJIJIJJIJJJIIIIJI()
	{
	}
}
