using System.Runtime.CompilerServices;
using Photon;

public class ZombieMode : MonoBehaviour
{
	private sealed class IJJIJIIIJIIJIIIJJJJJJIJJIJIJIJIJJIJJJJIJJIJJIJJ
	{
		public JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII;

		public ZombieMode JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		internal void IJIJJIJJIJJIJIJJJJIIIIIJJJIJJIJJIJIIIJIIIIJIIII()
		{
		}

		internal void IIJJJIIJIJJIIIIJJIIIJIIIJIIJJJIJJIJJJJJIJJIIIJI()
		{
		}

		internal void IJIJJIIJIJIIIJIIIJIIIJIJIIIJJJIJIIIJIJIIIJJJJIJ()
		{
		}

		internal void JIJIJJJJJJIJJIIIIIIJJIIJJIJIIIIJJJJIJJJJJIJJJIJ()
		{
		}

		internal void JJJIJJIIJIJJJJIIJJJJJIIIJIIJJIIJIJIIJJIIJJJIJIJ()
		{
		}

		internal void JIJIIJJIJJIJJJJIIIIJJJIIJIIIJIJIJJJJJIJIIJIIJII()
		{
		}

		internal void IJIJJJIIJIIIJJIIJJJIJIIIIJJJJJIJIJJIIJIIJIIJJJJ()
		{
		}

		internal void JIJJJIJJJJIJJIJIJIIJIIJIIIIJIJJJJJIIJJJJJIIJIJJ()
		{
		}

		internal void IIJJJIJJIIIIJIIIJJIJIJJIIIJIIIJIIIIIJJIJIJIIIII()
		{
		}

		internal void JIIJIJJJJIJIIJJIJIJIIJJJIJIJIIJIIJJIJIJJJIIIJIJ()
		{
		}

		internal void IJJIJIJJJJJIJJJJJJJJIJIJJJJIJIJJIJJIIIIIJIJIIJI()
		{
		}

		internal void JIJIJIIIJJIIJIIJJIIJJJIJIJIJIIIIJIIJIIJJJIIJIIJ()
		{
		}

		internal void IJJJJIIIIJIJJIJIJJIIIIJJJJJIJJIIIIJIIIIJJJJJIIJ()
		{
		}

		internal void JJIIIJIJJJJJIJIJIJIJIIIJJJIJIIIJIJJJJIIJJIIIJJJ()
		{
		}
	}

	private sealed class JJJJIJJJIIIJIIIIJJIJIJIIIJJJIIJJJJJJIIIJJIJIJJJ
	{
		public float JJJJIIJJIIJJJJIIIIIIJJJIJIJJJIIJJIIJJIJIJJIJIJI;

		public double JIJJIJIIJIIJIJJJIIIJIIJJJJIIIIJJJIIJJJIIJIJIJJJ;

		public ZombieMode JIJJIJIJIJJIJJJIIIIIJIIIJJJJIJJIIJJIIJIIIJJIIII;

		internal void JJJIIIIJIJJJIJJJIIJIIJJIJIIIJIIIIIJJIJJJJJJJJIJ()
		{
		}

		internal void JJIJIJIIIIJJJJJJIJJIIIIIJIJJIIJIJIIJJIIJIIJIIII()
		{
		}

		internal void IIIJJJIJIIIJJJIIIIIJJJIIIJIJJJJJJJIJJIIIJIJIJJJ()
		{
		}

		internal void JJIIJJIJJIIJJJJJIJIJIIIIIIJJJIIIIIIIIIJIJIJJJII()
		{
		}

		internal void IIIIIJIIJIIJIIIJIIIJIIIIIJIIIIJIIJIJJJJJIJJIIIJ()
		{
		}

		internal void IJJJJIIJJJJJJJIJIIIJJIJIIJJJJJJJJJJIIJJJIIIJJIJ()
		{
		}

		internal void JIJJIJJJJJJJJJIJJJJJJJJIIJJIIJJJJJJIIIJJIJIJIJJ()
		{
		}

		internal void IJIJIIJJJIJJIIIJJJIJJJIJIIIJJIIIIIJIJIIIIJJJJII()
		{
		}

		internal void IIIJJJJIJIIJIIIJIIIJJIIIJIJIIJIIJJJJIJIJIJJIJJI()
		{
		}

		internal void JIIIIJJJIJJIIJJJIIJIIIJIIJIIJJIJIIIIJIIIIIIIIJI()
		{
		}

		internal void IIIIJJIIIIJIIIIJIJIJJIIJJIIIIIJIJIIIIIIIIIJIJJI()
		{
		}

		internal void JIJIJIJIIIIJIIIIIJIIIIIIIIJIIIIJIIIIJIJIJJIJIII()
		{
		}

		internal void IJIJJJJIIIJJJIJJJJIIIJIJIJIJIJJIJIIJJIIIIJJJJII()
		{
		}
	}

	public ZombieBlock[] IJIJJJIIIIIJIIJIJIIJIIJJJIIIJJIJJIJIIIIIJJJIJJJ;

	private bool IIJJJJIIIIJJIIIIJIIJIJJIJJJJIIJIIJIIIIIIJJJIIIJ;

	private int JIIIJJIJIJJIJJJJIIJIIIIIJJIIJIJJJJJIJJJIJIIIIII;

	private static ZombieMode JIIIIJJJJIIJJJIIJIJIIJIIJJIIIIIIIIJJIJIJJJJJJJJ;

	public static void JIIIIJIIIIJJIJIJIIIJJIJJIIJIJJIIIIIIJJIJJJJIJJI(byte IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private void JIIJIJJIIIJJIJIIJJIJIIIJIJJIJIIIIIJIJJJIIJIJIIJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJJJIIJIIJJJIIJIIJIJIJJJIIIIJIJJIJJJJIJJIIJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[CompilerGenerated]
	private void JIJJJIIJJIIIIJIJJIJIJIIIJJJIJIJIIJIJIIIJIIJIJII()
	{
	}

	private void JJJIIIJJJJJIJIIJIIIIIJIJJIIJJJJIIJIIJIJIIJIIJII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIJIIIJIJJJJIJJIIIIJJIJIIJIIJIJJIIIIJIIJIIJJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void OnDisable()
	{
	}

	[CompilerGenerated]
	private void IIJIIJJJJJJIIIIJJIJJJJJIIJJJIIIIJJJJIJJIIJJIJJI()
	{
	}

	public static void JIIJIJIJIIJJJJIJJIJJJJJIJIIJIIIJJJJJJIIJIIJIJJI(byte IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private void JIJJJJIJIIJIIIJIIJIIIIIIIJIIIIIIIJJIJJIJJJJJIJI(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJJJIJJJJIIJJIJIIIJJJJIJJJIIJJJJIJJJJJJIIJJIJII()
	{
	}

	private void JJIIJJJIIIJIJIIIIIJJIJJJIJJIIJIJIIIIIJJIIIJIJJI()
	{
	}

	private void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IJIJJJIJJIIJIJJIIJJJJJJIJJJIIIJJIJJIIJIIJIJJJII)
	{
	}

	private void JIJJIJJJIJJIJIJIJIJJJIJJJJIJJIIJJJJJIIIJIJIIIJJ()
	{
	}

	private void JIJIIJJJIJIJJJJIJJIJJJIJIJJJIJIJIIJIJJIJIIJIJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJIJIJIJIIJIIIJIIIJIJIIIJJIIIIJIJIJJJJIIIIJIIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIIIJIJIJIIJIIIIJIJJIIIIIIIIJJJJIIJIJJJJIIJIII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJJIJIJIJIIIJIJIJJIJJIIJJIJJIIIJJJJIIIIJJIIIIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIIIIIJIIIJJJJJJIJIIIIJJJJIIJIIIJJIJIJIIIIJJJJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII()
	{
	}

	private void IJIJJJJIIJIJJJIJIJIJIJIJJJJIIJIJJIJIIJJJJJJJIIJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IIJJIJIIJIJIJIIJIIJJJJJIJJJIIJJIJJJIJJIIIJIIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIIIIJIIIIIJJJJJIJJIIIJIJIJIIIJIJJJIJJIJJIIII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIIIIJIIIJJJJJJJJIJJJIJIIIIIIJIIIIIJJJIIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJJIIIJIIJIIIIJIIJJIJIIJJIJIIJIIJJJIJJIIJJIIII()
	{
	}

	private void Awake()
	{
	}

	[CompilerGenerated]
	private void IJJIIJJJIJIJIJJJJJJIJJJIJIIIIJJIIIIJIJJJJJIJIII()
	{
	}

	private void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIJJIJIJIIIJJJJIIIJIJJJIIIJIIJJIIIJIJJIIIIJIIII)
	{
	}

	private void IIIJJJIJJJJJJIIIIIJIIJJJJJIJIJIJIJJJJIJJJJJJJII()
	{
	}

	private void IJIJIJJIJJJIIJJIJJJJJIIJJIJIIIIJIIJIIJIJJJJJJJI()
	{
	}

	private void JIJIJIJJIIIJIIJIJIJJJIIIJJJJJIIIJIJIIJIIIJJIJJI(IIJJJIJIJIJIIIJIJIIIJIJJIJIJJJJIJJJJJIIJIJJJIII JJJIJJIJJIIJJIJJJJJJJIJJJJIIJJJJIJIIIJJIIIJIIIJ)
	{
	}

	private void IJJIIJJJJJJIJJIJIJIJIIJIIJIIJIIIIJIIIIIJJIIJIJI()
	{
	}

	private void IJJJIIIIJIJJJIIIJIJIJIJJJJJJIJIJIJIJIIIJIIJJIJJ()
	{
	}

	private void OnEnable()
	{
	}

	[CompilerGenerated]
	private void IJJJJIJJJIJIIJJJJIJJIIIIIJJIIIIIJJJIJJJIIJIJIJI()
	{
	}

	public static void JIIJJIIIJJJIIJIIIJJIIIIIIIIJJIJJJIJIJIJJIIJJJII(byte IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void JIJJIIJIJIJJIJIIJIJJJJJIJIIIIIJJJJIIJIJJJJIIJII()
	{
	}

	private void Start()
	{
	}

	[CompilerGenerated]
	private void IJJJJJJIJJJJIJIIJIIIJIJJIJJJIIIIJIJIIIIJJJJIIII()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JJIIJIJJIIJIJJJIIIJIIIIJJJJIIJJIIJJJIIJJIJJJJII(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IIIIJJJIJIIIIIIJIIIIIJJIIJJJJJIJIIJJIIJJIIJIIJJ()
	{
	}

	[CompilerGenerated]
	private void IJIIJIJIIIJJJIJJIJIIJIJIJIJJIIIIJIJIIJIIJIJJIJJ()
	{
	}

	private void JIIJJJIIIIJIIJIJIJIJIJIJIIIJJJIIIJJIJIIIIIJIIIJ()
	{
	}

	public static void IIJIJJJJJJJIJJJJIIIJJJIJJIJJJJIIJIJJJIIIIIIJJIJ(byte IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private int IJIIJIJJIJJJJIJIJIIJIJIJIJIIIIIJJIIIJIIJIIJIJJI(int JJIJIJJJIIJJIJJJJIJJIIIJIJJJJIJJJJJJJJJIJIIJJJJ)
	{
		return 0;
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void JIIJIIJIJIJJJJJIIJIIIJIJJIJJJIJJJIIJJIIJIIIIJIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void IJJJJIIIIJIIIIIJJIIJIIIJIJJJJJJJJJIIJIIIIIIJIJJ()
	{
	}

	[IJIIJJIJJIIIJJJIIJJJJJJJJJIJJJIIIJIIJIIJIIIIIJI]
	private void IJJJJJIIJIIJJJIIIIJIJIJIIJJJIIJJIIJJIJIJIJJJIJJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	public static void JJIJJJIIJJIIIJJJIJIIJJIJJIJIJIJIJIJIJIIJIJJIIIJ(byte IIJIJIIIJIIJIIJIJJJIJJIJIIJIJJJIJJJIIJIJIIIJJJJ)
	{
	}

	private int IJIJJJIJJIIJIJIJJJIIJJJJJIJJJJJIIIIIJIIJJIIIIII(int JJIJIJJJIIJJIJJJJIJJIIIJIJJJJIJJJJJJJJJIJIIJJJJ)
	{
		return 0;
	}

	[CompilerGenerated]
	private void JIJIJIJIIIIJIJJIIIJJIIIJIJIJJJIIJIIIIJIJIIIJIJI()
	{
	}

	private void IJIJIJIIIIIIIIIIIJJIIJJIJIIIJJJIJJJJIJJJIJJIIJJ()
	{
	}

	private void IJJIIJIJIJJIJIJIJJIJIIIIJIIIJIJIIIJIIJIJIIIIIIJ(JJJIJJIJIIJIIIIIJIJIIJJIIIIJJIIIJJIJIIJJIJIIIII JIJJJJIJJIIIJIJJIJIIIIIIJJJIJIJJIIJJIJJIIIJIIIJ)
	{
	}

	private void JJIIJIJJJIIJIJJIIJIJJJIJIJJIIIIJJJIIIIJIJJIIIJI()
	{
	}
}
