using System.Runtime.CompilerServices;
using UnityEngine;

[ExecuteInEditMode]
public class ZombieRigidbodyObject : MonoBehaviour
{
	public Vector3 IIIJIJJJIJIJJJJJJIIJIIJIJJJJIJJIIJJIJIJIIJJIIIJ;

	public Quaternion JJIIIJJJIJJJJJJIIIJJIJIJJJIIJJJIJIJJJJJIJJIJIJJ;

	private Transform JJIJIIJIIJJJJJIIIJIIIJJJIJJJIIIIJJIJJJIIIJJIIII;

	public Transform JIJIIJIJIIJIJIJIIJIJJIIIIJJJJJIJJJJJIJIJIIIIIIJ => JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ();

	public void IJIJIIJIJJIIJJJJIIJIIJJJJIIJIJIIJIJIJJJJIJJIJJI()
	{
	}
	public Transform JJJIIIIJJJIIJIJJIIJJIJJIIJJIIIIIIJJIJIJJIIJIJII()
	{
		return null;
	}

	private void JIJIIIIJIJJJIIJJJIIIIIJIIIJIJJJJIJJJIIJJIJIIJJI()
	{
	}

	public Transform JIJIIIIIJIIJJJIJIJJIJJIIJJJJIIJIIIIIJIIJJJJIIIJ()
	{
		return null;
	}
	public Transform IIIJJIJJJIIJJIIIJJJIJJIJJJIIIJIJIIIJIIIIIIIIIIJ()
	{
		return null;
	}

	private void Start()
	{
	}

	public void JIJJIJJJIJJJIJJIIIJIIIJIJIJIIJJJIJJIJJJJJJIJIIJ()
	{
	}

	private void JIJIJJIIJIIIJJJIIJJJJJJIIIJIJIIIJIJIJJJIIJIIJJJ()
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	public void IIIJJJJIJJJJIJJIIJIJJJIIJIJIIJJIIIIJIIJJJIIIJJI()
	{
	}
	public Transform IJJJIJIIIJJIIJJIJJIJJJIJJIIIIIJIIJJIIJJIIJJIJJI()
	{
		return null;
	}
	public Transform IJIIJIIIIIIIJIIIJIJIIJJIJJJJIIJJJJJJJJJJIIIIIII()
	{
		return null;
	}

	private void JJJJIJJIJIJJIIJIIIIIJJJJJIJIJJJIJJIIJJJIJIIJIJJ()
	{
	}

	public void JIJJIIJJIIIJIIIJIJJJIJJJIIJJJJJIIJJJJJIJIIIJIJJ()
	{
	}
	public Transform IJIIJIJIJJJIIJIJIIJIIJIIJIIIJJJJJJJIJIJIIJIJJJJ()
	{
		return null;
	}

	private void JIJJJJIJIIJJIJJJIIJIJJIIJJIIJIIJIJJIIJIIJIIIJJJ()
	{
	}

	private void JJJIJIJIJJJIIIIIJJIJIIIIJIIJIJIJIIJJJIJJJJIIIJI()
	{
	}
	public Transform JJJIIJJIJJJJIJJIJJIIJIIJIJJJJIIJJJJJJJJIIJJJJJI()
	{
		return null;
	}

	private void IJIIJJIJJJIJIJJJIIJIJIIJJJJJIJIJJJJIIJIIJIJJJJI()
	{
	}

	private void IJJIJJIJJIJJJIIIJJJIIJIIIIJJIIIIIJJJIIJIIJIIIJJ()
	{
	}

	public void JJJIIIIJIIJIIJJJJJJJIJIJIJJJIIJIIJJJIJIIJJIJIJJ()
	{
	}

	private void IIIIJJJIJIIIIIIJIIIIIJJIIJJJJJIJIIJJIIJJIIJIIJJ()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	private void JJJJIIIIJJJJIIIIJIJIIJJJJIIJIIIJIJJJJJJIIIJJIJJ()
	{
	}
}
