using System.Runtime.CompilerServices;
using UnityEngine;

public class ZombieButton : MonoBehaviour
{
	public JIIIIIJJIJIIIJIIJJJIIJJIIIJJJIJIJIJIJIJIIIJIJJJ IIJJIIIJJJIIJIJIIIIIIIJJJJJJIIIJJIIIJIIIJIJIJJJ;

	public int JIIJJIJIIJJJJIJJJJJIJIJJIIIIIIJJJIIIIIJIJIIIJII;

	public KeyCode JIJIIJIIIIJIJJIIJJIJJIJIIJJIIIIIJJIJJIJIJIIJJJI;

	public MeshRenderer JIIIIJJIIIIIIJJJJIJIJIIIJJIJIJJIIJJIIJIJJJJIJJJ;

	public Transform JIIIJIJIJJIJJIJIIIJIIJIIJJIJIJIJIJJIJJIJIJIJJIJ;

	private bool JJIIJJIIJJIJIJIJJJIIJJJIIIIJIJIIIIIIJIIIIJJIJJJ;

	private bool IIIIJIIIJJIIJIIJIIJJJJJJIJJJIJJIIJJJIIIIJIJJIIJ;

	private bool IIJIJJJJIIIIJJIIIJJJIIJIJIIJJJJIIIIIIJIJIJJIIJI;

	private void JIIIIIIIJJIIJIJIIJIIJJJIIJIIIJIJIIIIIIJJJIJIJII()
	{
	}

	private void JIJIJIIIJIIJJIIIIIJJIJIIIIJJJIJIJJIJIJIIIIJIJJI()
	{
	}

	private void Start()
	{
	}

	private void IIJIJJJJJJJIJJJJIIIJJJIJJIJJJJIIJIJJJIIIIIIJJIJ()
	{
	}

	private void OnTriggerExit(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJJIIJIJIIIJIJJIJIIIJJIIIJIJIIIIJIJJIIIIJIIJIJI()
	{
	}

	private void JJJIJJJJJIIJIJJJIJIIIIJJIJJJIJIIJJIIJIIJJJJIIJI()
	{
	}

	private void IIIJJIIJJJJJJIIIIJJIJJJIJJIIJJIIJIJIJIJJJIIJIJI()
	{
	}

	[CompilerGenerated]
	private void IJJIJJIIJJIJJJJIIJJIIJIJIJJIIIJJJIIJIIJIIIIJJIJ()
	{
	}

	private void OnEnable()
	{
	}

	private void IIJJJIJIJIIIJIJIJIIIJIIIJIJJIJIIJIJIIJIIIJJJJIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	public void JJJJJIJIIJIJIIIJJJJIJIIJJIJIJJJJJIJIJJJJIIJIJIJ(byte IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void IIIIIJIJJIIIJIJJJJJIIIIJIIJIJIIJJIIJIJJIJJJJJJJ()
	{
	}

	private void IJIIIJIJJIIJJIJIJJIIJIIIJJJIIJJIIIJIJIIIIIJJJII()
	{
	}

	public void IJIJIIIJIIIJIJJIIIJJIIIIIIIJIJJJJJJIJIIJIJJJJII(byte IJJIIIJIIIIIJIIIJJJJIIIIIIJJIIIJIJIIJJJJIJJIIIJ)
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void IJIIIIJJJJIIJIIIIIIJIIIIJIIIIJIJJJIIIIJJJJIIJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IJIIJJIIIIIIJIJJIJIJIIJJJIIJJJJJIJIJIIJIJIJIIJJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void OnDisable()
	{
	}

	private void IIJJIIIJJJIIIIIIIIIJIIIIJJJIIIJJJIIIIIIIJJJIIIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void JJJIJJJIIIJIIJJJIJIJJJIIIIJJIIIIIIJIJJIJJIIJIJJ()
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIJIIJIIJIIIIJIJIIIJJJJJJIJIIIJIJJIIJJJIIJJIIJJ()
	{
	}
}
