using UnityEngine;

public class ZombieEasterEggs : MonoBehaviour
{
	[IIIJJJIJIJIIJJIIIIIIJJJJJJIJIIIJIJIIJIJIIIJJJIJ]
	public bool JIIJIJIIIJJJIIJIIIIIJIJJJIJJIJIIIJJJIJIIJIJIJIJ;

	public Transform IJJJIJJIJIJJJJIIJIIJJJJJIJJJJJJJIJIIJJJJJJIJJIJ;

	public ZombieEasterEggs[] IJJJIIIJJIJIIIJJJIJJJJIJJIIIJIJIJJJJIJJJIIJJJJI;

	private bool JJIIJJIIJJIJIJIJJJIIJJJIIIIJIJIIIIIIJIIIIJJIJJJ;

	private void JIJJIJJIIIJIJJIIIIJIJJIJIJJJIJJIIIJJIJJIJJJJJII(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void OnTriggerEnter(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIIIIJIIIJIIIIJIJIIJIJIJIIJIJIJJJIIIIJIJJIJIIII(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IJIIIJJJJIJIJIJIIIJIIJIIIJIIJIIJIJJIJJJIIJJIIIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void Start()
	{
	}

	private void IJIIIIJJJJIIJIIIIIIJIIIIJIIIIJIJJJIIIIJJJJIIJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void IJJJJJIIIIJJJIIJIJIJIJJIIJJIIIIIIIIJIIIIJJJIIJI()
	{
	}

	private void IIJIIIIJIJJIJIJIJJJIJIIIJIJIJIIJJJJIIIJIIIJIIJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIIJIIIJJIIIIIIIIJIJIIJIIIIJJIJIJIJIJJJIJIIIJJI()
	{
	}

	private void IJJIIIJJJIJIJIIJIIIJJIIJJJJJIIJJIIIIIJIIIIIIIJJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void JIJIIIIIIIJJJIJJJJJJIIIIJJIJJIIIIJJJJJIJJIIIJII()
	{
	}

	private void IJJIIJJIJJIJIJJIJJIIJIIJIJJJIJJIJJJIIIJIJJIIJJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IJIIIIJJIJIJJJJIIJJIIIIJJJIIJJIJIIIIJJIIIJJJJIJ(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ)
	{
	}

	private void JIJIIJJIIIIIIJIIJIJIIJJIJJJIJIJJJIJJJJIIJJJIJJI(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void JIIIIIIIIIJJJJJJJJJIJIJJIIJIIJIJIJJIIJIJIIJIIII()
	{
	}

	private void IIIJJIIIJJJIIJIIIIIJJIIIJIIIJJJJIIIJIIIIIJIIIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void OnTriggerExit(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}

	private void IIJIJIJJIJIIIJIJJIJIIIJIIIJJJJJIIIJJIIIJIJIIIIJ(Collider IIJIJJIIJIIIIIJIIJJJJIIIIJJJJIIJIJIJIJJJIIIIJJJ)
	{
	}
}
