using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using UnityEngine.Events;
using UnityEngine.SceneManagement;

namespace CodeStage.AntiCheat.Detectors
{
	public class InjectionDetector : ActDetectorBase
	{
		private class IIJJIIJJIJJIJJJIJIIJIIIJIIIIJIJIIIIJJIIIJIIJIJI
		{
			public readonly string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ;

			public readonly int[] JIIJJIJIJJJJJIJIIIIJJJJJJIIIJIJIIIIIIIIIIJIIJJI;

			public IIJJIIJJIJJIJJJIJIIJIIIJIIIIJIJIIIIJJIIIJIIJIJI(string JIIJIJIJJJIIJJJJJIIJJJIIIIJIIIJIJIIIJIJIIJJJJIJ, int[] JIIJJIJIJJJJJIJIIIIJJJJJJIIIJIJIIIIIIIIIIJIIJJI)
			{
			}
		}

		internal const string IIIJJIIJIIIJIJIIJIJIIIIJIIJIJJJIJIIIIJJJJJIJIJI = "Injection Detector";

		internal const string IJIJJIJIIIIJJIJJJJJIIIJJIIIIIIIJJIIJJJJJJJJJJJI = "[ACTk] Injection Detector: ";

		protected UnityAction<string> IJJJIJJJJJJJIIJIIJIJIJJIJJIJJJJJIIIIIJJJJJIJJJI;

		private static int IJJIJJIIJJIIJIIJJJIJJJJJIIJJJIIJIJJIJJJJJJJIJII;

		private bool JIIJIIIJJJIIJJIJIJIIJIIJJJIJIJJIJIJIIIIIJJJIIIJ;

		private IIJJIIJJIJJIJJJIJIIJIIIJIIIIJIJIIIIJJIIIJIIJIJI[] JIJJJJJIJJIJIJJJIJJJJIJIJJJIJJIIIIIIJJIIIJIIJIJ;

		private string[] IIIJIIJJJJIJIJJIJJIIJIJJJIIIIJIIIJIIIJIJIJIIJJJ;

		private static InjectionDetector IJIIIJIIIIIJIIIJIJJJJJIJJJIJIJJIJJIJJIJIJJIIJJI;

		public static InjectionDetector JIJJIJJJJIIJIIJJJJJJJJIJJJJJJIJJIJIIIIJIJJIJJJJ
		{
			get
			{
				return JJJJJJJIIJJJJIIJIJIIIIJIJIJJIJJIIJIIIIIIJJIJIII();
			}
			private set
			{
				IJJIJIIJJIJIJIJIIJJIIJJIJJJIJJIJIJJJJJJJIJIJIJI(value);
			}
		}

		private static InjectionDetector IIIJIJIIJIJIIJJIIJJJIJJIIJIIJJJIJIJJJIJIJJIIIIJ => IIJIJJJJIJJJIJJJIJIIIIIJIJIIIIJJJJIIIJJIIIJJJII();

		private bool IJIIJJJJIIJJJIJJJIJJJJJJJIIIJIJIJJIIIJIJJIJJIJI(out string IIJIIIIIIJJIIJJJJJIJIIJIJJJJJJIIJIJJJIJJIIIIIJI)
		{
			IIJIIIIIIJJIIJJJJJIJIIJIJJJJJJIIJIJJJIJJIIIIIJI = null;
			return false;
		}

		protected override void IJJIIJJJIIJIIJIJJJJIJJJJIJIJJIJJJIIJJJJJJIIIJJJ()
		{
		}

		private string JJJIIIJIJJJJIJIIJJJJIIJJJIJIIIIIIIJJJJJJIIIIIII(byte[] JIIIJJIJIJIJJJIIJIJJJJJIJIJIIIIJIIIIJJIIJIJJIIJ)
		{
			return null;
		}

		private void Awake()
		{
		}

		public static void JJIIJIJJJJJJIIJJIJIIIJJJIIJJIIJJJIJIJJIIJJJJJJJ(UnityAction IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
		{
		}

		public static void IJJIIIIJIIIIJIIJJJIIJIJIJIJJJJIJJJJIJIIIIJIIIJI()
		{
		}

		private InjectionDetector()
		{
		}

		public static void JJJIIJJIJIIJIIIJJIIJJJIJIJJJJJIIJIIJJIIJJIIJIIJ(UnityAction<string> IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
		{
		}

		protected override void JJJJIJJJIJIIJIIJJJJIIJJIJIJIIJIIIJIJIJIJJJIIJII()
		{
		}

		private bool JIIIIIJIIIJJJIIJJJIIJJJJJIJJIIIJIIJIJJIJIJJIJJI(out string IIJIIIIIIJJIIJJJJJIJIIJIJJJJJJIIJIJJJIJJIIIIIJI)
		{
			IIJIIIIIIJJIIJJJJJIJIIJIJJJJJJIIJIJJJIJJIIIIIJI = null;
			return false;
		}

		private void IJJIJIIIIIIJJJJJJJJIJIIIJJIIJIJJIIJIJIIIJJIIIII(UnityAction IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI, UnityAction<string> JIJJIJIJIIJIJIIIIIJIJJIJIJIJJJIJJIIIJJJJIJJIJJI)
		{
		}

		public static void JIIIJJIJJJIIIJJIIJIJIJJIIIIJIIIJIJJJIIIIIJJJIJJ()
		{
		}

		public static void JJIIJIJJJJJJIIJJIJIIIJJJIIJJIIJJJIJIJJIIJJJJJJJ()
		{
		}

		private void IJJJJJIJIIJJIIJJJIJIJIIIJIJJIIJIIJIJJIJJIIJIIJI(object JJIJJJJIJJIJJJJIJJIIIIJJJIIJJJJIJIJIIIIIJJIIIIJ, AssemblyLoadEventArgs IJIIIJJJJIIIIJJIIJJIJJIIJJIIIIIIIIIIJJJJIJJJJII)
		{
		}

		private void JJJIIIIIIJJIJJIIJJIIJJIJIIIJIJIJJJIJIJJJIJIJJIJ(object JJIJJJJIJJIJJJJIJJIIIIJJJIIJJJJIJIJIIIIIJJIIIIJ, AssemblyLoadEventArgs IJIIIJJJJIIIIJJIIJJIJJIIJJIIIIIIIIIIJJJJIJJJJII)
		{
		}

		private bool IJIJJIIIJJJJJJJIIJJJIJJIJIIIJJIIIIJJJJJJIIIIIJI(Assembly JJJJIIJJIIJIIIIIJIIIJIJJJIIJJJIJJJJIIJIJIIIJJII)
		{
			return false;
		}

		protected virtual void IIIIJIIIJJIJJIJIJJIJJJJJJJJIIJIJJJJJJJJIIIJIJII()
		{
		}

		protected virtual void IJJJJIIJIIJIIJJIJJIJIJIIJIIJJIJJJIJIIJJJJJJIIII()
		{
		}

		private void IJJJIJIJIJIIJIJJJIJJJJJJJJJJIIIJJIIIIIIJJIIJIII(Scene JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ, LoadSceneMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
		{
		}

		protected virtual void IIJIIJIJJJJJJJIJJJIJJJIIJIJIJIJIIIIIJJJJJJJIIJJ()
		{
		}

		protected override void JIJIIIJIJIIIJIIJIIIJIIIIJJJIJJJJJIJIIJJJJIJJJIJ()
		{
		}

		protected override void JJIJJIIJJJIJJJIJJJIIJIJIIJJJJJIJJJIIJIIJIIJJJJI()
		{
		}

		public static void JJIIJIJJJJJJIIJJIJIIIJJJIIJJIIJJJIJIJJIIJJJJJJJ(UnityAction<string> IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
		{
		}

		private int JIIJJJJJIIJJIIIJJJJIIIJIJIJJIIJIIIIIIJIIJIIJIIJ(Assembly JJJJIIJJIIJIIIIIJIIIJIJJJIIJJJIJJJJIIJIJIIIJJII)
		{
			return 0;
		}

		private static InjectionDetector IIJIJJJJIJJJIJJJIJIIIIIJIJIIIIJJJJIIIJJIIIJJJII()
		{
			return null;
		}

		private void JJIJIIIIIJIIIIIJIIJJIJIIIJIJJIJJJIJIJJIJJJIIIJI(string IIJIIIIIIJJIIJJJJJIJIIJIJJJJJJIIJIJJJIJJIIIIIJI)
		{
		}

		private void IIJJIJJIIJJJIJIJIIJIIIIIJJJIIIIJIJJIIIIIIJJIJJI()
		{
		}

		private void IJIIIIJIIJIIJIJIIJJJJJIJIIJJJIIJJIJJJJIJIJIIIIJ()
		{
		}

		private bool IIJJJJIJIJIIJIJIIIJIIJJIJJIJIJJIIJJJIIJIIJJIJIJ(Assembly JJJJIIJJIIJIIIIIJIIIJIJJJIIJJJIJJJJIIJIJIIIJJII)
		{
			return false;
		}

		private bool IIJJJIJJIJIIIJJIJIJIIJIJIJJIJIJJJIIIIIJIIJIIJJJ(out string IIJIIIIIIJJIIJJJJJIJIIJIJJJJJJIIJIJJJIJJIIIIIJI)
		{
			IIJIIIIIIJJIIJJJJJIJIIJIJJJJJJIIJIJJJIJJIIIIIJI = null;
			return false;
		}

		public static void JJJJIJIJJIJJJIJJJJIJJIJJJIJJIJIJJJJIJJIIIIJJJJJ()
		{
		}

		public static InjectionDetector JJJJJJJIIJJJJIIJIJIIIIJIJIJJIJJIIJIIIIIIJJIJIII()
		{
			return null;
		}

		protected override void OnDestroy()
		{
		}

		private void JJJJJIIIJJIJIIJJIJIIIJJIJJJIJIJJIJJJJJIIJJJIJII(Scene JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ, LoadSceneMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
		{
		}

		private void JIIJIIJJIIJJJIJJJJIIIJJJIJJIIIIIIIIIJIIIIIJIJJJ(Scene JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ, LoadSceneMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
		{
		}

		private static void IJJIJIIJJIJIJIJIIJJIIJJIJJJIJJIJIJJJJJJJIJIJIJI(InjectionDetector JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}
		private static InjectionDetector JJIIIJIIIJJIJIIIJJIIJJIJJJIJIIIJJIJIIIJIIJIJJJI()
		{
			return null;
		}

		protected override void JJJJIJJJJIJJJIJJIIIIJIIJIJJJJIJIIJIIJJJIIIIIJIJ()
		{
		}
	}
}
