using System.Runtime.CompilerServices;
using UnityEngine.Events;
using UnityEngine.SceneManagement;

namespace CodeStage.AntiCheat.Detectors
{
	public class ObscuredCheatingDetector : ActDetectorBase
	{
		internal const string IIIJJIIJIIIJIJIIJIJIIIIJIIJIJJJIJIIIIJJJJJIJIJI = "Obscured Cheating Detector";

		internal const string IJIJJIJIIIIJJIJJJJJIIIJJIIIIIIIJJIIJJJJJJJJJJJI = "[ACTk] Obscured Cheating Detector: ";

		private static int IJJIJJIIJJIIJIIJJJIJJJJJIIJJJIIJIJJIJJJJJJJIJII;

		public float IIJIIJJIIJIJJJJJIJIJJIIIJIIIIIJIIJIJJJJJIIJIIJJ;

		public float JIIJIIJJJJJIIJIIJIIIIJIIIIIJIIIIJJIIJIIIIJJIJIJ;

		public float IIIIIIJIJIIJIJIIJJIIIIJIIIJIIJJJJJJIIJIIJJJIIIJ;

		public float JIIJIJJJJJIIIJIIJIJIIIJIIIIIJIJIJIJJIJJIJIIIJIJ;

		private static ObscuredCheatingDetector IJIIIJIIIIIJIIIJIJJJJJIJJJIJIJJIJJIJJIJIJJIIJJI;

		public static ObscuredCheatingDetector JIJJIJJJJIIJIIJJJJJJJJIJJJJJJIJJIJIIIIJIJJIJJJJ
		{
			get
			{
				return JJJJJJJIIJJJJIIJIJIIIIJIJIJJIJJIIJIIIIIIJJIJIII();
			}
			private set
			{
				IJJIJIIJJIJIJIJIIJJIIJJIJJJIJJIJIJJJJJJJIJIJIJI(value);
			}
		}

		private static ObscuredCheatingDetector IIIJIJIIJIJIIJJIIJJJIJJIIJIIJJJIJIJJJIJIJJIIIIJ => IIJIJJJJIJJJIJJJIJIIIIIJIJIIIIJJJJIIIJJIIIJJJII();

		internal static bool IJJJIJJJJIIJIIIJJJIJJIJIJIIJJJIIIJIIIIJJIIIJJJI => IIIJJJJIJJJJJIJIIIIIJIJJIIJIIIIIIJIJJJJIIIIIIJI();

		internal static bool IIIJJJJIJJJJJIJIIIIIJIJJIIJIIIIIIJIJJJJIIIIIIJI()
		{
			return false;
		}
		private static ObscuredCheatingDetector JJIJIJJIIJJJIIIJJIIJIJIJJJJJJIJJIIIJJIIJIJJIIIJ()
		{
			return null;
		}

		protected override void JJIJJIIJJJIJJJIJJJIIJIJIIJJJJJIJJJIIJIIJIIJJJJI()
		{
		}

		public static void JJIIJIJJJJJJIIJJIJIIIJJJIIJJIIJJJIJIJJIIJJJJJJJ(UnityAction IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
		{
		}

		private void Awake()
		{
		}

		protected virtual void IIJIJIIIJJIIIIJIJJJJJIIJJJIIIJJJJJJJIJJIJJIJJII()
		{
		}

		protected override void JJJJIJJJJIJJJIJJIIIIJIIJIJJJJIJIIJIIJJJIIIIIJIJ()
		{
		}

		public static void JJJIIIIJJIJIIJJJJIJIIIJJJJJJJJJIIIJIJJJJIJIIIIJ()
		{
		}

		public static void JIIIJJIJJJIIIJJIIJIJIJJIIIIJIIIJIJJJIIIIIJJJIJJ()
		{
		}

		private void IJIIIJJJIIIJJJJJIJJIJJJIJJJJIJIIJJIJJIJJJIIIIJI(Scene JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ, LoadSceneMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
		{
		}
		public static ObscuredCheatingDetector IJJJJJIIIJIIJIJJIJIJIJIJIIIIIIIIIIJJJIIIIIJIIII()
		{
			return null;
		}

		public static void IJJIIIIJIIIIJIIJJJIIJIJIJIJJJJIJJJJIJIIIIJIIIJI()
		{
		}

		private void IJJJIJIJIJIIJIJJJIJJJJJJJJJJIIIJJIIIIIIJJIIJIII(Scene JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ, LoadSceneMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
		{
		}

		protected override void OnDestroy()
		{
		}
		private static ObscuredCheatingDetector JJIJJIJJIJIJIJIJIIJJIIIJJIJIIIIIIIJIJIJJJIJIJIJ()
		{
			return null;
		}

		public static void IIJIIJIJJIIJJJJJJJJIJJJIJIIIIJJIIJIIJJIJIJJJJJI()
		{
		}

		public static ObscuredCheatingDetector JJJJJJJIIJJJJIIJIJIIIIJIJIJJIJJIIJIIIIIIJJIJIII()
		{
			return null;
		}

		protected virtual void IIJIJJJIIJIJIIJJJJJIJJIIJJJIJJIIIJJJJJJIJJIJIII()
		{
		}

		private void IJIIIIJIIJIIJIJIIJJJJJIJIIJJJIIJJIJJJJIJIJIIIIJ()
		{
		}

		protected virtual void JJIIJIJJJIJIJIJJJIJJJJJJIIIIIJJJJJIIJJIJIJIJJJI()
		{
		}

		protected override void JIJIIIJIJIIIJIIJIIIJIIIIJJJIJJJJJIJIIJJJJIJJJIJ()
		{
		}

		protected override void IJJIIJJJIIJIIJIJJJJIJJJJIJIJJIJJJIIJJJJJJIIIJJJ()
		{
		}

		private static void IJJIJIIJJIJIJIJIIJJIIJJIJJJIJJIJIJJJJJJJIJIJIJI(ObscuredCheatingDetector JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}
		internal static bool IJIIIIIJIJIIJIIIJIIIJIIJJJIJIJJJJIJJIJJJIIJIIJI()
		{
			return false;
		}

		protected override void JJJJIJJJIJIIJIIJJJJIIJJIJIJIIJIIIJIJIJIJJJIIJII()
		{
		}

		private void IIJJIIJIIIIIIJJIJJJIIJIJJJJIIIIIIIJJIIIIIIJJJJI(UnityAction IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
		{
		}

		private void IJJIJIIIIIIJJJJJJJJIJIIIJJIIJIJJIIJIJIIIJJIIIII(UnityAction IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
		{
		}

		private static ObscuredCheatingDetector IIJIJJJJIJJJIJJJIJIIIIIJIJIIIIJJJJIIIJJIIIJJJII()
		{
			return null;
		}

		private ObscuredCheatingDetector()
		{
		}

		private void IIIIJJJIIJJIIIJJJJIJJIIJIJIJJJJJIIJJIJJIJJIIIJI()
		{
		}

		public static void JJIIJIJJJJJJIIJJIJIIIJJJIIJJIIJJJIJIJJIIJJJJJJJ()
		{
		}
	}
}
