using System.Runtime.CompilerServices;
using UnityEngine.Events;
using UnityEngine.SceneManagement;

namespace CodeStage.AntiCheat.Detectors
{
	public class SpeedHackDetector : ActDetectorBase
	{
		internal const string IIIJJIIJIIIJIJIIJIJIIIIJIIJIJJJIJIIIIJJJJJIJIJI = "Speed Hack Detector";

		internal const string IJIJJIJIIIIJJIJJJJJIIIJJIIIIIIIJJIIJJJJJJJJJJJI = "[ACTk] Speed Hack Detector: ";

		private const long IJIIJIIJJIJIIIIJIJJJJIIIIJJJIIIIJJIJJJJJIIJIIIJ = 10000000L;

		private const int JIJJJJJJJIJIIJIJJJIIIJIIJIJIJIIJJJJJIJIJIIJIJIJ = 5000000;

		private static int IJJIJJIIJJIIJIIJJJIJJJJJIIJJJIIJIJJIJJJJJJJIJII;

		public float IIIJIIIIJJJIIJJIJIIIIJIIIJJIIJIIIIJIIIIJJJIIJII;

		public byte JJIJJJIJIJIIIIJJIJJJIJIIJIIJJJJJJIIJJJIIIIJIIJJ;

		public int IJIIIJIJIIIJIIJJJIJIIIIIJJIJIIJJIJJJJIIIJIIJIJJ;

		private byte IIIIJJJIJIIJIIJIJIJIIJJIJIJIIIJIJIIJJIIJJJJJJIJ;

		private int IIJIIIIJIJIIJIIIIIJJJIJJJJIJIIJJJIJJJIJJIJIIIII;

		private long JIJIIIJJJJJIJIIJJJIJIIIJIJJJIJIIJJIJJJIJIIJIIJI;

		private long JJJJJJIJIJJIIIIJIIIJIJJJJIJIIIIJJJIIJIJJIJJJJJJ;

		private long IJIJJIJJIIIJIIIIJJJIIJIIJJIJJJIJIJJIIIIJJIJJIII;

		private long JIIIJJJIJIIJIJIJIIIJIJIJJJIJIIIJIJJIJJIIIIJIIJJ;

		private static SpeedHackDetector IJIIIJIIIIIJIIIJIJJJJJIJJJIJIJJIJJIJJIJIJJIIJJI;

		public static SpeedHackDetector JIJJIJJJJIIJIIJJJJJJJJIJJJJJJIJJIJIIIIJIJJIJJJJ
		{
			get
			{
				return JJJJJJJIIJJJJIIJIJIIIIJIJIJJIJJIIJIIIIIIJJIJIII();
			}
			private set
			{
				IJJIJIIJJIJIJIJIIJJIIJJIJJJIJJIJIJJJJJJJIJIJIJI(value);
			}
		}

		private static SpeedHackDetector IIIJIJIIJIJIIJJIIJJJIJJIIJIIJJJIJIJJJIJIJJIIIIJ => IIJIJJJJIJJJIJJJIJIIIIIJIJIIIIJJJJIIIJJIIIJJJII();

		private void Update()
		{
		}

		protected override void IJJIIJJJIIJIIJIJJJJIJJJJIJIJJIJJJIIJJJJJJIIIJJJ()
		{
		}

		public static void JJIIJIJJJJJJIIJJIJIIIJJJIIJJIIJJJIJIJJIIJJJJJJJ(UnityAction IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI, float IIIJIIIIJJJIIJJIJIIIIJIIIJJIIJIIIIJIIIIJJJIIJII, byte JJIJJJIJIJIIIIJJIJJJIJIIJIIJJJJJJIIJJJIIIIJIIJJ)
		{
		}

		public static void JJIIJIJJJJJJIIJJIJIIIJJJIIJJIIJJJIJIJJIIJJJJJJJ(UnityAction IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI, float IIIJIIIIJJJIIJJIJIIIIJIIIJJIIJIIIIJIIIIJJJIIJII, byte JJIJJJIJIJIIIIJJIJJJIJIIJIIJJJJJJIIJJJIIIIJIIJJ, int IJIIIJIJIIIJIIJJJIJIIIIIJJIJIIJJIJJJJIIIJIIJIJJ)
		{
		}

		public static void JJIIJIJJJJJJIIJJIJIIIJJJIIJJIIJJJIJIJJIIJJJJJJJ()
		{
		}

		private void JIIIJIIJJJJJIJIJIJIJIJIIJJJIJIIJJJIIJJJJJJJJIJJ(bool JJJJIJJJJIIIIIJIJIJJIIIIJIIJJJIJIIIJJJIJJIIIIIJ)
		{
		}

		protected override void JJJJIJJJIJIIJIIJJJJIIJJIJIJIIJIIIJIJIJIJJJIIJII()
		{
		}

		public static void JJIIJIJJJJJJIIJJIJIIIJJJIIJJIIJJJIJIJJIIJJJJJJJ(UnityAction IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
		{
		}

		private void OnApplicationPause(bool JJJJIJJJJIIIIIJIJIJJIIIIJIIJJJIJIIIJJJIJJIIIIIJ)
		{
		}
		private static void JIIJIIJIIJJJJIJJIIIIJIIIIIJIJIIJJIIIIJIJJJIIIJJ(SpeedHackDetector JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}

		protected override void OnDestroy()
		{
		}

		protected virtual void JIIIIJIIJIJJIJIIIJIJIIJIIIIIIIIIIIJIIIIJIJJIJIJ()
		{
		}

		public static void IIIIIIJJJJJIJJJIIIJJJIJIJIJIIJJIJJIIJJJJIJJIJII()
		{
		}

		public static void JIIJIIJIJJIJJIJJJJJJJIIJIJIIJIIIJJJIJJIJJIJJIJI(UnityAction IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI)
		{
		}

		public static void JIJIJIJIIIIIIIJJIJIJIIJJIIJIIIJJJJJJJJJJJIJIIJJ()
		{
		}

		private void JIJIJJIJIIIJJIIIJJIIIIJJJIIIJJIIJJIJJJJIIIIJIJJ()
		{
		}

		private static void IJJIJIIJJIJIJIJIIJJIIJJIJJJIJJIJIJJJJJJJIJIJIJI(SpeedHackDetector JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}

		private void IJIIIIJIIJIIJIJIIJJJJJIJIIJJJIIJJIJJJJIJIJIIIIJ()
		{
		}

		private void IJJIJIIIIIIJJJJJJJJIJIIIJJIIJIJJIIJIJIIIJJIIIII(UnityAction IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI, float IIIIJIIJIIIIJIJIIIIJJIJIJIJIJJJIJJIJIIIIIJIJJJJ, byte JIJJIIJJIIIJJIJIIJJJJJIIIJIIJIIJJJJIIIIJIIJJJJI, int IJJJIIIJJIJIIIIIJJJJJJIJIIJIJIJIIJIJJIJJIJJJIII)
		{
		}

		protected virtual void JJIIJIIJJIJIJJJIJJIJJIJIJJIJJIIJJIIIJIIJJIJJJJI()
		{
		}

		private void JJIIJIJJJJJJJJJJIIJIJJIJJIIJJJIIJJIJIJIJJIIIIIJ()
		{
		}

		public static void JIJIJJIJIIIJIJIIJIJJJJIIIJIJIIIIIJIIIIJJJJJIIJJ(UnityAction IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI, float IIIJIIIIJJJIIJJIJIIIIJIIIJJIIJIIIIJIIIIJJJIIJII)
		{
		}
		public static SpeedHackDetector IJIJJIIJJJJIIJIIJIJIIIIJJJJIJIIIIJIIJJJIIJJIJIJ()
		{
			return null;
		}

		protected virtual void JJJJIIIJIIJJJJIJIJIIIIIIJJIJJIIJJJJJIIIJIIJIIII()
		{
		}

		private void IIIIJJJIIJJIIIJJJJIJJIIJIJIJJJJJIIJJIJJIJJIIIJI()
		{
		}

		protected virtual void IJJJIIJJJIIJIIIJJIJIIJJJIIIIJJJIJIIIJIIJJJJJJII()
		{
		}

		private void JJJJIJIJIJIIIJJJIJJJIJJIIIJJIJIIJIJIIJJJIJIIIII()
		{
		}

		private SpeedHackDetector()
		{
		}

		public static void JIIIJJIJJJIIIJJIIJIJIJJIIIIJIIIJIJJJIIIIIJJJIJJ()
		{
		}

		protected virtual void IIIJJIJIIJIIIJJIIJIJIJIIIJJIJIIIJJIIJJJJIIJJJJI()
		{
		}

		private static SpeedHackDetector IIJIJJJJIJJJIJJJIJIIIIIJIJIIIIJJJJIIIJJIIIJJJII()
		{
			return null;
		}

		protected override void JJJJIJJJJIJJJIJJIIIIJIIJIJJJJIJIIJIIJJJIIIIIJIJ()
		{
		}

		public static void IJJIIIIJIIIIJIIJJJIIJIJIJIJJJJIJJJJIJIIIIJIIIJI()
		{
		}

		private void Awake()
		{
		}

		private void IIIIJIJJJIJJJIJIJIJJIIJJIIIJJJIJIJIJIIJIIJIJJII(Scene JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ, LoadSceneMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
		{
		}

		public static void IJIJIJIIJIJIJJJJIIIIJJIIJJJIJIJIIIJIIIIIJJJJIJJ()
		{
		}

		protected override void JIJIIIJIJIIIJIIJIIIJIIIIJJJIJJJJJIJIIJJJJIJJJIJ()
		{
		}

		private void IJJJIJIJIJIIJIJJJIJJJJJJJJJJIIIJJIIIIIIJJIIJIII(Scene JJJJJIJJIIIJIJIIIIIIIJIIIJJJIJIJJJIIIJIIIJIIIJJ, LoadSceneMode JIIJJJJIJIIIIIIJIJJIIIIJJJJJJIIJJIIJJJIIJJJIJJI)
		{
		}

		public static SpeedHackDetector JJJJJJJIIJJJJIIJIJIIIIJIJIJJIJJIIJIIIIIIJJIJIII()
		{
			return null;
		}
		private static void JJIIIIJJJIJIJJIIJJIJJJJJJJJJJJJJIIJIIJIIJJIJJII(SpeedHackDetector JIIJJIIJIIJIJJJJIJIIIJIIIIJJJIIIIJIJIIJJIIJIIJI)
		{
		}

		protected override void JJIJJIIJJJIJJJIJJJIIJIJIIJJJJJIJJJIIJIIJIIJJJJI()
		{
		}

		public static void JJIIJIJJJJJJIIJJIJIIIJJJIIJJIIJJJIJIJJIIJJJJJJJ(UnityAction IIJIJIIIJIIIJIIJJJIIJJJJJJJIIIIIIIIJIJJIIIIIIJI, float IIIJIIIIJJJIIJJIJIIIIJIIIJJIIJIIIIJIIIIJJJIIJII)
		{
		}
	}
}
