using System;
using UnityEngine;

namespace Android.Runtime.Permissions
{
	public class PermissionCallbackHelper : MonoBehaviour
	{
		private Action IIJJIJJIJJJIJIJJIJIIIIJJIIIJIIJJIIIIJIIIIIIJJJI;

		private void JIJJIJJIIJJIJJIJIJJIIJIJJJJJIIJIIIJJIIIJJIJIJII()
		{
		}

		private void JJIIIJJIIJJIIIJJJIJIIJIIJIJJIIJJIIJJJIJIJIJJIIJ()
		{
		}

		private void IIJJIIIJJIJIIJIJIIIJIIJIIJIJJIIJJIIIIJIJJIIIJJI()
		{
		}

		private void JJJIIIIIIIJJJIIJIIIIJJJJIIIIIIIIJJJJJJJIIIJIIJJ()
		{
		}

		private void JIIJJIIJIIIIIJIIIIJJIIJJJIIJIJIJJIIIIIIJJIJJIII()
		{
		}

		public void IIIJJIIIJIJJJJIJIIIIJJJIIJJIIJJIIJIJJIJJIIJIIJI(Action IJIJIIIIIJIIIIJIJJJIJJIIJJJIIIJJIIJJJIIJJJIIIJI)
		{
		}

		private void JIIIIIJIJJIIIIIIIJJIIJJJJIIJJJJJJIIJIJJJJIIIIJJ()
		{
		}

		public void IIJJIIIJIJJJIIJJJJJJIIJIJJJJIIJIIIJIIIJIJJJJIJI(Action IJIJIIIIIJIIIIJIJJJIJJIIJJJIIIJJIIJJJIIJJJIIIJI)
		{
		}

		private void Update()
		{
		}

		private void JIJJJJIIIJIIIIJIJJJJIIJJJIIJJIIJJJIIIIIIIJIIIJI()
		{
		}

		private void IJIJIJIIIIJIIIJJIJIIJJJJIJJIJJJJIIIJJJIJIJIIJIJ()
		{
		}

		private void Awake()
		{
		}

		public void JJJJJIIIIIIJJIIJIIJIIJJIIJIIJJJIIJJIJJIIIJJIJJI(Action IJIJIIIIIJIIIIJIJJJIJJIIJJJIIIJJIIJJJIIJJJIIIJI)
		{
		}

		private void JIJJIIIJJIJIIIIIJIIJIIIIJJJIJIIIIJJJJJJJJIIIIIJ()
		{
		}

		public void IJIJIIIJJIJJIIJIIJIJJIJJJIJJIIIIIIIIJJIJJJIIIII(Action IJIJIIIIIJIIIIJIJJJIJJIIJJJIIIJJIIJJJIIJJJIIIJI)
		{
		}
	}
}
