using UnityEngine;
using UnityEngine.UI;

namespace DemoUpdateManager
{
	public class UiManagerTest : MonoBehaviour
	{
		public AndroidUpdateManager JIJJIIJIJIJIIIIIIJIJIJJIIIJIJIJIIJIJIJIJIIJIIII;

		public Text JIIJJIIIJIIIIIJIIIIJJJIIIJIIJJJIIIJIIJIJJIIIJJJ;

		private void JIIIJJJJIIIJJJIJJIJJJJIIIJIIIIIIJIIJIIIIIIJIJII()
		{
		}

		private void JJIJIIIJJJIIJJIIJIJIJJJJJJJJJIJIJJIIIIIIIIJJJJJ(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI)
		{
		}

		private void IJIJJJIIJIIJIJJIJIJIIIJIJIJJIIIIIIJJIJIJIJIJIJJ()
		{
		}

		private void IIJIIIIIIIIIJIIIJJJJJJJIJIJJJIJJJJJJJIIJIIIJJJI(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI)
		{
		}

		private void JIIJJJIIIIJJIIJJIIJIIJJIJIJIIJJIIIIJJIIJJIJIJIJ()
		{
		}

		private void JIJJIJIJIIJJIIJJJIIJIJIIJIIJJIJIIIIIJJJIJIJJIJJ(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI)
		{
		}

		private void IIJIIIIIJJIIJJIJJJJIIJIIJIIIJIIJIJIIJIIIIJIJIJI()
		{
		}

		private void JJJJIJIJIJIJIJIJIJIIJIJJJJIJIIIIJJIIJJJIJIJJJJI()
		{
		}

		private void OnDisable()
		{
		}

		private void IJJJIJIJIIIJIIJJIIIIJIIIJJIJIIIIJJIJJIIIJIJIJJJ(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI)
		{
		}

		private void IJJJJJJIIIIIJIIJJIIJJIJJJIJIIIIJJJIJJJIJJIJIIJJ()
		{
		}

		private void IJJIIJJIIJJIIJJJJJJIIIJJJJJIJIIJIJIIJIIJIIIIJII()
		{
		}

		private void JJJJJJIIIIIIIJIJIJIIIJJJIIJJIJJJJJIIJIJIJIJJIJI(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI)
		{
		}

		private void IIIJJJJIJIIJJJIIJJIIJJIIJJIIJIIJIJIIIIIIJIIIIII(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI)
		{
		}

		private void IJJJJJIIIIIJJJJJIJIJIIJIIIIIJIJJJIJIIIJIJIJIJJJ()
		{
		}

		private void JJJIIJIJJJIIIJIJJIJIJJIJJIJIJJJIJJIJIJJIIJIJJIJ()
		{
		}

		private void IJJIJIJIJIJIJJIJIIIJIJIJIJJIIIJIIJJIIIIJIIIJJJI()
		{
		}

		private void JIJIJIIIJIIJJIIIIIJJIJIIIIJJJIJIJJIJIJIIIIJIJJI()
		{
		}

		private void IIJJJIJIIIJIIIJJJJIIIIJIJJIJIIIIJJJIIIJIIIIIJII()
		{
		}

		private void OnEnable()
		{
		}

		private void JJIIIIIJJIJJJIJIIIJIIJIIIJIIJJIJIJJIJJIIIIIIIJI(int JIJJJIJJJJIIIJJIJJJJJIIJIIIJIIIJIJJIIIJIJJJJJJI)
		{
		}

		private void IIJIJJJIJJIJIIJIIIIJJJIJJJJJJJIJIJIIIIIJJJIIJJJ()
		{
		}
	}
}
