using System.Collections.Generic;
using ExitGames.Client.Photon;

namespace Photon
{
	public class PunBehaviour : MonoBehaviour, JJIJJIJJJIJJIJJIIJJIIIJJIIIIIIJJJJJIJIIJIIIJIJJ
	{
		public virtual void IIIJIJIIIJJIIJJJJIJIJJJJIIJJJJJJIJIJJIIIIJJIIIJ(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJIJJJIIIJIIIJJIJIIJIIIIIJJIJIIJJIIIIJIJJIJJIJJ)
		{
		}

		public virtual void OnMasterClientSwitched(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JIIIJIIJJJIJJIIJIIJIJIIJJIJJJIJJJJIIJJIIIIJIJII)
		{
		}

		public virtual void OnLeftLobby()
		{
		}

		public virtual void OnDisconnectedFromPhoton()
		{
		}

		public virtual void OnReceivedRoomListUpdate()
		{
		}

		public virtual void IJIJJIIIJIJIIIIJJIIIIJIIJIIIJJIIJJJIJJJIIJIJIJI(OperationResponse IJJIIJJJJIJJJIIJIJJJIJJJIIIJJIIJJIIIIIIJIIJIJJI)
		{
		}

		public virtual void OnPhotonRandomJoinFailed(object[] IIIIIIJJIIJIIJJIIIIJJJJJJIJIIIJJJIIJJJIJIJJIJIJ)
		{
		}

		public virtual void OnFailedToConnectToPhoton(JIJJIJIIJIJJIIIJJIIJIJIIJIJIJIJJIIJIJJIJJIJIIJI IIJIIIIIIJJIIJJJJJIJIIJIJJJJJJIIJIJJJIJJIIIIIJI)
		{
		}

		public virtual void OnPhotonPlayerDisconnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJIJJJIIIJIIIJJIJIIJIIIIIJJIJIIJJIIIIJIJJIJJIJJ)
		{
		}

		public virtual void OnLeftRoom()
		{
		}

		public virtual void OnConnectedToMaster()
		{
		}

		public virtual void OnUpdatedFriendList()
		{
		}

		public virtual void OnConnectionFail(JIJJIJIIJIJJIIIJJIIJIJIIJIJIJIJJIIJIJJIJJIJIIJI IIJIIIIIIJJIIJJJJJIJIIJIJJJJJJIIJIJJJIJJIIIIIJI)
		{
		}

		public virtual void JIJIIJIJIIIJIIIIJJIJJIJJIJIIJJIJIJJIIIIIJJIJIIJ(OperationResponse IJJIIJJJJIJJJIIJIJJJIJJJIIIJJIIJJIIIIIIJIIJIJJI)
		{
		}

		public virtual void OnCustomAuthenticationFailed(string JIJJIJJJJJJJIIJIJIJIJJIIJIJIIIJIIIJIIIIIIJIIIJJ)
		{
		}

		public virtual void IIIJJIJIIJIIIIIJJJIIJIIIJJIJIJJJJJJIIIJIIJJJJJI()
		{
		}

		public virtual void OnJoinedLobby()
		{
		}

		public virtual void OnPhotonMaxCccuReached()
		{
		}

		public virtual void JJJIJJIJIJIIIJJIJIIIJJJIIIJIIJIJJIJJIIJIJIJJIII(object[] JIIJJJIJJIIJJIJJJIIIJIJJJIJIIIIIJJJJIIIIIJIIJJI)
		{
		}

		public virtual void IIJIIJJIJIJJIIIJIIIIJJJJJIIJJJIIIJIJJJIJJJJIIJI(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII JJIJJJIIIJIIIJJIJIIJIIIIIJJIJIIJJIIIIJIJJIJJIJJ)
		{
		}

		public virtual void OnPhotonCustomRoomPropertiesChanged(Hashtable IIJIJJJJJIIJJIIIIJJIIIJJJIIJIJIJIIJIIJJJJIIIJIJ)
		{
		}

		public virtual void OnWebRpcResponse(OperationResponse IJJIIJJJJIJJJIIJIJJJIJJJIIIJJIIJJIIIIIIJIIJIJJI)
		{
		}

		public virtual void OnPhotonCreateRoomFailed(object[] IIIIIIJJIIJIIJJIIIIJJJJJJIJIIIJJJIIJJJIJIJJIJIJ)
		{
		}

		public virtual void OnCustomAuthenticationResponse(Dictionary<string, object> IIJJJIJIIIIIJIIJIJIJIJIJIIIIJIJJJJIIJIJIJJJJJII)
		{
		}

		public virtual void OnPhotonPlayerConnected(JJJJIIJIIIJIIIJIIJIJJJJIJJJJIIIJIJIIJIIJJIIJIII IIJIIIIIJJJJIJJJJIJJJJIJIJJJIJJIIIIIJJIIJJJJIII)
		{
		}

		public virtual void JJJIJIJIJJJJJJJIJIJIJIIJIJJIIIIJIJJJJJJJJIJJIIJ()
		{
		}

		public virtual void OnConnectedToPhoton()
		{
		}

		public virtual void OnCreatedRoom()
		{
		}

		public virtual void IIJIIIJIJJIJIJIJIIJJIIJJIIIJJJIJJIJIJJIIIIJIIIJ()
		{
		}

		public virtual void OnPhotonInstantiate(IIJJIIIJIIIJJJIJJJJJJJIIJIIJJIIIIJJJIIJIJIIIJIJ IIIJIJJIJJIJJJIIIIJJJIJJIJIIJIJIIJJIJIIJJIIJIJI)
		{
		}

		public virtual void OnOwnershipRequest(object[] IIIJJJJIIJIIIIJJJIIIIJJIJIIJIJJJJIJJJJJIJIIIJJI)
		{
		}

		public virtual void OnPhotonPlayerPropertiesChanged(object[] JIIJJJIJJIIJJIJJJIIIJIJJJIJIIIIIJJJJIIIIIJIIJJI)
		{
		}

		public virtual void IJIIJJIIJJIIIIIJJIIIIJJJIIJJIIIIJJIIJIJIJJIJIII(object[] IIIIIIJJIIJIIJJIIIIJJJJJJIJIIIJJJIIJJJIJIJJIJIJ)
		{
		}

		public virtual void JJJJIJJIJJIIJJJJJIIIJJIIIIJJIJIIJIIIJJJJIIJJIJI(object[] JIIJJJIJJIIJJIJJJIIIJIJJJIJIIIIIJJJJIIIIIJIIJJI)
		{
		}

		public virtual void IIJIJIIJJIJJIJJIJIIIIIIIJJJJIIIIJIJJIIIIIJIIJJJ(object[] IIIJJIIIJJIIJJIIIIJJIJJJIJJIIIJIJJIJIIIJJJIJIJJ)
		{
		}

		public virtual void IIIIIIIIJJIJJJIIIJJIJJIIJIJIJJJIJJJIJIIJIIJJJIJ(object[] IIIIIIJJIIJIIJJIIIIJJJJJJIJIIIJJJIIJJJIJIJJIJIJ)
		{
		}

		public virtual void JJJJJJIIIJIIJJJJJIIJJIJIIIIIJJJJIJJIJIJJJJIIJIJ(object[] IIIIIIJJIIJIIJJIIIIJJJJJJIJIIIJJJIIJJJIJIJJIJIJ)
		{
		}

		public virtual void JIJJIIJJJIIIJJJIIJJIIJJIIJIJJJJJIIJIJIJJJIJIIII(Hashtable IIJIJJJJJIIJJIIIIJJIIIJJJIIJIJIJIIJIIJJJJIIIJIJ)
		{
		}

		public virtual void JJJIIIJIIIJIJIIJJJJJIIJJIIIIIJJIJIJIIJIJJJJIJJI(object[] IIIJJIIIJJIIJJIIIIJJIJJJIJJIIIJIJJIJIIIJJJIJIJJ)
		{
		}

		public virtual void JIIIJIJJIJIJIIIJJJIIJIIIJIJIJIIJJIIIJIIIIIJIIII()
		{
		}

		public virtual void IIIIIJIIIIIJJIIIIJJIJJIJIJIIIJJIJJIJIJIJJJIIJJJ(JIJJIJIIJIJJIIIJJIIJIJIIJIJIJIJJIIJIJJIJJIJIIJI IIJIIIIIIJJIIJJJJJIJIIJIJJJJJJIIJIJJJIJJIIIIIJI)
		{
		}

		public virtual void OnJoinedRoom()
		{
		}

		public virtual void OnLobbyStatisticsUpdate()
		{
		}

		public virtual void JJJIIJJJJJJJJIJJJIIJIJIJIIJJIJIIJIJIIJIJIIJIJJJ()
		{
		}

		public virtual void OnPhotonJoinRoomFailed(object[] IIIIIIJJIIJIIJJIIIIJJJJJJIJIIIJJJIIJJJIJIJJIJIJ)
		{
		}
	}
}
